package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN03 {
	public static String[][] pl = { { "ben zhang", "本章" }, { "ben zhe", "本着" }, { "ben zhi", "本职" }, { "ben zhi", "本质" }, { "ben zhi gong zuo", "本职工作" },
			{ "ben zhong", "笨重" }, { "ben zhou", "本周" }, { "ben zhou mo", "本周末" }, { "ben zhu", "笨猪" }, { "ben zhuan ye", "本专业" }, { "ben zhuo", "笨拙" },
			{ "ben zi", "本子" }, { "ben zou", "奔走" }, { "ben zu", "本组" }, { "ben zuo", "本作" }, { "beng", "伻" }, { "beng", "嘣" }, { "beng", "埲" },
			{ "beng", "塴" }, { "beng", "崩" }, { "beng", "嵭" }, { "beng", "泵" }, { "beng", "琫" }, { "beng", "甏" }, { "beng", "甭" }, { "beng", "祊" },
			{ "beng", "繃" }, { "beng", "绷" }, { "beng", "菶" }, { "beng", "蚌" }, { "beng", "蹦" }, { "beng", "迸" }, { "beng", "閍" },
			{ "beng beng tiao tiao", "蹦蹦跳跳" }, { "beng bu", "蚌埠" }, { "beng chu", "蹦出" }, { "beng dai", "绷带" }, { "beng fa", "迸发" }, { "beng jin", "绷紧" },
			{ "beng kui", "崩溃" }, { "beng pan", "崩盘" }, { "beng ta", "崩塌" }, { "beng zhan", "泵站" }, { "bi", "佖" }, { "bi", "俾" }, { "bi", "匂" }, { "bi", "匕" },
			{ "bi", "吡" }, { "bi", "哔" }, { "bi", "嗶" }, { "bi", "坒" }, { "bi", "堛" }, { "bi", "壁" }, { "bi", "奰" }, { "bi", "妣" }, { "bi", "妼" },
			{ "bi", "婢" }, { "bi", "嬖" }, { "bi", "嬶" }, { "bi", "屄" }, { "bi", "币" }, { "bi", "幣" }, { "bi", "幤" }, { "bi", "庇" }, { "bi", "庳" },
			{ "bi", "廦" }, { "bi", "弊" }, { "bi", "弼" }, { "bi", "彃" }, { "bi", "彼" }, { "bi", "必" }, { "bi", "怭" }, { "bi", "愊" }, { "bi", "愎" },
			{ "bi", "敝" }, { "bi", "斃" }, { "bi", "朼" }, { "bi", "柀" }, { "bi", "梐" }, { "bi", "楅" }, { "bi", "比" }, { "bi", "毕" }, { "bi", "毖" },
			{ "bi", "毙" }, { "bi", "沘" }, { "bi", "泌" }, { "bi", "湢" }, { "bi", "滗" }, { "bi", "滭" }, { "bi", "潷" }, { "bi", "濞" }, { "bi", "熚" },
			{ "bi", "狴" }, { "bi", "獘" }, { "bi", "獙" }, { "bi", "珌" }, { "bi", "璧" }, { "bi", "畀" }, { "bi", "畢" }, { "bi", "疕" }, { "bi", "疪" },
			{ "bi", "痹" }, { "bi", "痺" }, { "bi", "皕" }, { "bi", "睥" }, { "bi", "碧" }, { "bi", "秕" }, { "bi", "秘" }, { "bi", "笔" }, { "bi", "筆" },
			{ "bi", "筚" }, { "bi", "箅" }, { "bi", "篦" }, { "bi", "篳" }, { "bi", "粊" }, { "bi", "綼" }, { "bi", "縪" }, { "bi", "繴" }, { "bi", "罼" },
			{ "bi", "腷" }, { "bi", "臂" }, { "bi", "舭" }, { "bi", "芘" }, { "bi", "苾" }, { "bi", "荜" }, { "bi", "荸" }, { "bi", "萆" }, { "bi", "蓖" },
			{ "bi", "蓽" }, { "bi", "蔽" }, { "bi", "薜" }, { "bi", "蜌" }, { "bi", "裨" }, { "bi", "襞" }, { "bi", "襣" }, { "bi", "觱" }, { "bi", "詖" },
			{ "bi", "貏" }, { "bi", "賁" }, { "bi", "贔" }, { "bi", "贲" }, { "bi", "跸" }, { "bi", "蹕" }, { "bi", "躄" }, { "bi", "辟" }, { "bi", "逼" },
			{ "bi", "避" }, { "bi", "邲" }, { "bi", "鄙" }, { "bi", "鄨" }, { "bi", "鄪" }, { "bi", "鏎" }, { "bi", "铋" }, { "bi", "閇" }, { "bi", "閉" },
			{ "bi", "閟" }, { "bi", "闭" }, { "bi", "陛" }, { "bi", "飶" }, { "bi", "馝" }, { "bi", "駜" }, { "bi", "驆" }, { "bi", "髀" }, { "bi", "髲" },
			{ "bi", "鮅" }, { "bi", "鵖" }, { "bi", "鷝" }, { "bi", "鷩" }, { "bi", "鼊" }, { "bi", "鼻" }, { "bi an", "彼岸" }, { "bi bang", "臂膀" },
			{ "bi bei", "必备" }, { "bi bi", "比比" }, { "bi bi", "笔笔" }, { "bi bi jie shi", "比比皆是" }, { "bi bing", "弊病" }, { "bi bo", "碧波" },
			{ "bi bu ke shao", "必不可少" }, { "bi bu shang", "比不上" }, { "bi chu", "笔触" }, { "bi ci", "彼此" }, { "bi ci bi ci", "彼此彼此" }, { "bi dao", "逼到" },
			{ "bi de", "彼得" }, { "bi de", "逼得" }, { "bi de shang", "比得上" }, { "bi ding", "必定" }, { "bi du", "必读" }, { "bi duan", "弊端" }, { "bi dui", "比对" },
			{ "bi er", "比尔" }, { "bi er gai ci", "比尔盖茨" }, { "bi fa", "笔法" }, { "bi fang", "比方" }, { "bi fen", "比分" }, { "bi feng tang", "避风塘" },
			{ "bi guan", "闭关" }, { "bi gui yuan", "碧桂园" }, { "bi hai", "碧海" }, { "bi he", "闭合" }, { "bi hu", "壁虎" }, { "bi hu", "庇护" }, { "bi hua", "壁画" },
			{ "bi hua", "比划" }, { "bi hua", "笔划" }, { "bi hua", "笔画" }, { "bi huan", "闭环" }, { "bi hui", "避讳" }, { "bi ji", "笔记" }, { "bi ji", "笔迹" },
			{ "bi ji ben", "笔记本" }, { "bi ji ni", "比基尼" }, { "bi jia", "比价" }, { "bi jia suo", "毕加索" }, { "bi jian", "比肩" }, { "bi jian", "鼻尖" },
			{ "bi jiang", "必将" }, { "bi jiao", "比较" }, { "bi jiao da", "比较大" }, { "bi jiao di", "比较低" }, { "bi jiao duo", "比较多" }, { "bi jiao hao", "比较好" },
			{ "bi jiao he shi", "比较合适" }, { "bi jiao rong yi", "比较容易" }, { "bi jiao xi huan", "比较喜欢" }, { "bi jiao yan jiu", "比较研究" },
			{ "bi jiao you shi", "比较优势" }, { "bi jin", "逼近" }, { "bi jing", "必经" }, { "bi jing", "毕竟" }, { "bi jing zhi lu", "必经之路" }, { "bi jiu", "必究" },
			{ "bi kai", "避开" }, { "bi kan", "必看" }, { "bi kong", "鼻孔" }, { "bi kou", "闭口" }, { "bi lei", "壁垒" }, { "bi li", "比例" }, { "bi li shi", "比利时" },
			{ "bi liang", "鼻梁" }, { "bi lu", "秘鲁" }, { "bi lu", "笔录" }, { "bi lv", "比率" }, { "bi lv", "碧绿" }, { "bi men", "闭门" }, { "bi mi", "笔迷" },
			{ "bi mian", "避免" }, { "bi ming", "笔名" }, { "bi mo", "笔墨" }, { "bi mu", "闭幕" }, { "bi mu shi", "闭幕式" }, { "bi nan", "避难" }, { "bi ni", "比你" },
			{ "bi ni", "比拟" }, { "bi ni", "逼你" }, { "bi pin", "比拼" }, { "bi ping", "逼平" }, { "bi po", "逼迫" }, { "bi qi", "比起" }, { "bi qian", "比前" },
			{ "bi qian", "笔钱" }, { "bi qiang", "鼻腔" }, { "bi qiu", "比丘" }, { "bi ran", "必然" }, { "bi ran xing", "必然性" }, { "bi ran yao qiu", "必然要求" },
			{ "bi ren", "逼人" }, { "bi ren", "鄙人" }, { "bi ru", "比如" }, { "bi ru shuo", "比如说" }, { "bi sa", "比萨" }, { "bi sai", "比赛" },
			{ "bi sai xiang mu", "比赛项目" }, { "bi se", "闭塞" }, { "bi sha", "必杀" }, { "bi shang", "壁上" }, { "bi shang", "比上" }, { "bi shang", "闭上" },
			{ "bi shang yan", "闭上眼" }, { "bi shang yan jing", "闭上眼睛" }, { "bi sheng", "必胜" }, { "bi sheng", "毕生" }, { "bi sheng ke", "必胜客" },
			{ "bi shi", "彼时" }, { "bi shi", "必是" }, { "bi shi", "比试" }, { "bi shi", "笔试" }, { "bi shi", "鄙视" }, { "bi shou", "匕首" }, { "bi shu", "避暑" },
			{ "bi shui", "比谁" }, { "bi shui", "碧水" }, { "bi shui", "避税" }, { "bi si", "必死" }, { "bi suo", "闭锁" }, { "bi ta", "比他" }, { "bi ta", "比她" },
			{ "bi te", "比特" }, { "bi ti", "鼻涕" }, { "bi tian", "必填" }, { "bi wo", "比我" }, { "bi wo", "逼我" }, { "bi wo da", "比我大" }, { "bi wo hao", "比我好" },
			{ "bi wu", "比武" }, { "bi wu", "笔误" }, { "bi xia", "笔下" }, { "bi xia", "陛下" }, { "bi xian", "必先" }, { "bi xian", "避险" }, { "bi xie", "辟邪" },
			{ "bi xiu", "必修" }, { "bi xiu ke", "必修课" }, { "bi xu", "必需" }, { "bi xu", "必须" }, { "bi xu pin", "必需品" }, { "bi xue", "鼻血" },
			{ "bi ya di", "比亚迪" }, { "bi yan", "闭眼" }, { "bi yan", "鼻炎" }, { "bi yao", "必要" }, { "bi yao tiao jian", "必要条件" }, { "bi yao xing", "必要性" },
			{ "bi ye", "毕业" }, { "bi ye dian li", "毕业典礼" }, { "bi ye lun wen", "毕业论文" }, { "bi ye qian", "毕业前" }, { "bi ye she ji", "毕业设计" },
			{ "bi ye sheng", "毕业生" }, { "bi ye zhao", "毕业照" }, { "bi ye zheng", "毕业证" }, { "bi ye zheng shu", "毕业证书" }, { "bi yi", "鄙夷" }, { "bi you", "必有" },
			{ "bi you zhi lu", "必由之路" }, { "bi yu", "比喻" }, { "bi yu", "碧玉" }, { "bi yun", "碧云" }, { "bi yun", "避孕" }, { "bi yun tao", "避孕套" },
			{ "bi yun yao", "避孕药" }, { "bi zhang", "笔账" }, { "bi zhao", "比照" }, { "bi zhe", "笔者" }, { "bi zhe", "逼着" }, { "bi zhe", "闭着" },
			{ "bi zhe yan jing", "闭着眼睛" }, { "bi zhen", "逼真" }, { "bi zhi", "壁纸" }, { "bi zhi", "比值" }, { "bi zhi", "笔直" }, { "bi zhong", "币种" },
			{ "bi zhong", "比重" }, { "bi zi", "鼻子" }, { "bi zu", "鼻祖" }, { "bi zui", "闭嘴" }, { "bi zuo", "比作" }, { "bian", "便" }, { "bian", "匾" },
			{ "bian", "卞" }, { "bian", "变" }, { "bian", "変" }, { "bian", "峅" }, { "bian", "弁" }, { "bian", "忭" }, { "bian", "惼" }, { "bian", "扁" },
			{ "bian", "抃" }, { "bian", "揙" }, { "bian", "汳" }, { "bian", "汴" }, { "bian", "煸" }, { "bian", "甂" }, { "bian", "砭" }, { "bian", "碥" },
			{ "bian", "稨" }, { "bian", "窆" }, { "bian", "笾" }, { "bian", "箯" }, { "bian", "籩" }, { "bian", "編" }, { "bian", "缏" }, { "bian", "编" },
			{ "bian", "艑" }, { "bian", "苄" }, { "bian", "萹" }, { "bian", "蝙" }, { "bian", "褊" }, { "bian", "變" }, { "bian", "豍" }, { "bian", "貶" },
			{ "bian", "贬" }, { "bian", "辧" }, { "bian", "辨" }, { "bian", "辩" }, { "bian", "辫" }, { "bian", "辮" }, { "bian", "辯" }, { "bian", "边" },
			{ "bian", "遍" }, { "bian", "邉" }, { "bian", "邊" }, { "bian", "釆" }, { "bian", "鞭" }, { "bian", "髟" }, { "bian", "鳊" }, { "bian", "鴘" },
			{ "bian ba", "便把" }, { "bian bai", "变白" }, { "bian bei", "便被" }, { "bian ben jia li", "变本加厉" }, { "bian bian", "便便" }, { "bian bian", "边边" },
			{ "bian bie", "辨别" }, { "bian bu", "遍布" }, { "bian ce", "鞭策" }, { "bian cha", "变差" }, { "bian chang", "变长" }, { "bian cheng", "便成" },
			{ "bian cheng", "变成" }, { "bian cheng", "编成" }, { "bian cheng", "编程" }, { "bian cheng yu yan", "编程语言" }, { "bian chi", "边吃" }, { "bian da", "变大" },
			{ "bian dang", "便当" }, { "bian dao", "编导" }, { "bian de", "变得" }, { "bian de", "变的" }, { "bian de geng jia", "变得更加" }, { "bian di", "贬低" },
			{ "bian di", "遍地" }, { "bian di kai hua", "遍地开花" }, { "bian dian zhan", "变电站" }, { "bian dong", "变动" }, { "bian du", "边度" }, { "bian dui", "编队" },
			{ "bian fa", "变法" }, { "bian fang", "边防" }, { "bian feng", "边锋" }, { "bian fu", "蝙蝠" }, { "bian fu xia", "蝙蝠侠" }, { "bian ge", "变革" },
			{ "bian ge", "边个" }, { "bian geng", "变更" }, { "bian geng deng ji", "变更登记" }, { "bian gu", "变故" }, { "bian hao", "变好" }, { "bian hao", "编号" },
			{ "bian hei", "变黑" }, { "bian hong", "变红" }, { "bian hu", "辩护" }, { "bian hu lv shi", "辩护律师" }, { "bian hu ren", "辩护人" }, { "bian hua", "变化" },
			{ "bian hua qing kuang", "变化情况" }, { "bian huai", "变坏" }, { "bian huan", "变幻" }, { "bian huan", "变换" }, { "bian huang", "变黄" },
			{ "bian hui", "便会" }, { "bian hui", "变回" }, { "bian ji", "编辑" }, { "bian ji", "边际" }, { "bian ji", "遍及" }, { "bian ji bu", "编辑部" },
			{ "bian ji qi", "编辑器" }, { "bian jiang", "便将" }, { "bian jiang", "边疆" }, { "bian jiao", "变焦" }, { "bian jiao", "边角" }, { "bian jie", "便捷" },
			{ "bian jie", "辩解" }, { "bian jie", "边界" }, { "bian jing", "边境" }, { "bian ju", "编剧" }, { "bian kan", "边看" }, { "bian ke", "便可" },
			{ "bian ke yi", "便可以" }, { "bian kuang", "边框" }, { "bian lao", "变老" }, { "bian le", "变了" }, { "bian li", "便利" }, { "bian li", "遍历" },
			{ "bian li dian", "便利店" }, { "bian lian", "变脸" }, { "bian liang", "变量" }, { "bian lu", "边路" }, { "bian lun", "辩论" }, { "bian lun sai", "辩论赛" },
			{ "bian ma", "编码" }, { "bian ma qi", "编码器" }, { "bian mai", "变卖" }, { "bian man", "变慢" }, { "bian mi", "便秘" }, { "bian min", "便民" },
			{ "bian neng", "便能" }, { "bian nuan", "变暖" }, { "bian pai", "编排" }, { "bian pao", "鞭炮" }, { "bian pin", "变频" }, { "bian pin qi", "变频器" },
			{ "bian ping", "扁平" }, { "bian po", "边坡" }, { "bian qian", "变迁" }, { "bian qu", "编曲" }, { "bian qu", "边区" }, { "bian ren", "辨认" },
			{ "bian ru", "编入" }, { "bian se", "变色" }, { "bian shang", "边上" }, { "bian shen", "变身" }, { "bian shi", "便是" }, { "bian shi", "辨识" },
			{ "bian shu", "变数" }, { "bian shuo", "边说" }, { "bian su", "变速" }, { "bian su qi", "变速器" }, { "bian su xiang", "变速箱" }, { "bian tai", "变态" },
			{ "bian tao ti", "扁桃体" }, { "bian tong", "变通" }, { "bian wei", "变为" }, { "bian wei", "变味" }, { "bian xi", "辨析" }, { "bian xian", "变现" },
			{ "bian xian", "边线" }, { "bian xiang", "便向" }, { "bian xiang", "变相" }, { "bian xiao", "变小" }, { "bian xie", "便携" }, { "bian xie", "编写" },
			{ "bian xie shi", "便携式" }, { "bian xin", "变心" }, { "bian xing", "变形" }, { "bian xing", "变性" }, { "bian xing jin gang", "变形金刚" },
			{ "bian ya qi", "变压器" }, { "bian yan", "边沿" }, { "bian yang", "变样" }, { "bian yao", "便要" }, { "bian yi", "便以" }, { "bian yi", "便已" },
			{ "bian yi", "便衣" }, { "bian yi", "变异" }, { "bian yi", "编译" }, { "bian yi", "贬义" }, { "bian yi qi", "编译器" }, { "bian you", "便又" },
			{ "bian you", "便有" }, { "bian yu", "便于" }, { "bian yuan", "边缘" }, { "bian yuan", "边远" }, { "bian yuan hua", "边缘化" }, { "bian zai", "便在" },
			{ "bian zao", "编造" }, { "bian zhe", "编者" }, { "bian zheng", "辨证" }, { "bian zheng", "辩证" }, { "bian zheng fa", "辩证法" }, { "bian zhi", "便知" },
			{ "bian zhi", "变质" }, { "bian zhi", "编制" }, { "bian zhi", "编织" }, { "bian zhi", "贬值" }, { "bian zhong", "变种" }, { "bian zhuan", "编撰" },
			{ "bian zi", "辫子" }, { "bian zi", "鞭子" }, { "bian zou bian", "边走边" }, { "bian zuan", "编纂" }, { "biao", "俵" }, { "biao", "儦" }, { "biao", "墂" },
			{ "biao", "婊" }, { "biao", "彪" }, { "biao", "摽" }, { "biao", "杓" }, { "biao", "标" }, { "biao", "標" }, { "biao", "檦" }, { "biao", "滮" },
			{ "biao", "瀌" }, { "biao", "灬" }, { "biao", "熛" }, { "biao", "爂" }, { "biao", "猋" }, { "biao", "瘭" }, { "biao", "膘" }, { "biao", "臕" },
			{ "biao", "藨" }, { "biao", "表" }, { "biao", "裱" }, { "biao", "褾" }, { "biao", "諘" }, { "biao", "贆" }, { "biao", "錶" }, { "biao", "鏢" },
			{ "biao", "鑣" }, { "biao", "镖" }, { "biao", "镳" }, { "biao", "飆" }, { "biao", "飇" }, { "biao", "飑" }, { "biao", "飙" }, { "biao", "飚" },
			{ "biao", "驃" }, { "biao", "骠" }, { "biao", "髟" }, { "biao", "鰾" }, { "biao", "鳔" }, { "biao bai", "表白" }, { "biao bang", "标榜" },
			{ "biao ben", "标本" }, { "biao bing", "标兵" }, { "biao ceng", "表层" }, { "biao che", "飚车" }, { "biao cheng", "标称" }, { "biao chi", "标尺" },
			{ "biao chu", "标出" }, { "biao da", "表达" }, { "biao da fang shi", "表达方式" }, { "biao da neng li", "表达能力" }, { "biao da shi", "表达式" },
			{ "biao da zi ji", "表达自己" }, { "biao dan", "表单" }, { "biao di", "标的" }, { "biao di", "表弟" }, { "biao dian", "标点" }, { "biao dian fu hao", "标点符号" },
			{ "biao ding", "标定" }, { "biao duan", "标段" }, { "biao gan", "标杆" }, { "biao gao", "标高" }, { "biao ge", "表哥" }, { "biao ge", "表格" },
			{ "biao han", "彪悍" }, { "biao hao", "标号" }, { "biao ji", "标记" }, { "biao jia", "标价" }, { "biao jie", "表姐" }, { "biao jue", "表决" },
			{ "biao jue quan", "表决权" }, { "biao kong jian", "表空间" }, { "biao li", "表里" }, { "biao lu", "表露" }, { "biao mei", "表妹" }, { "biao mian", "表面" },
			{ "biao ming", "标明" }, { "biao ming", "表明" }, { "biao pai", "标牌" }, { "biao pei", "标配" }, { "biao pi", "表皮" }, { "biao qian", "标签" },
			{ "biao qing", "表情" }, { "biao sheng", "飙升" }, { "biao shi", "标示" }, { "biao shi", "标识" }, { "biao shi", "表示" }, { "biao shi fu", "标识符" },
			{ "biao shi gan xie", "表示感谢" }, { "biao shu", "标书" }, { "biao shu", "表述" }, { "biao shuai", "表率" }, { "biao tai", "表态" }, { "biao ti", "标题" },
			{ "biao ti lan", "标题栏" }, { "biao tou", "表头" }, { "biao xian", "表现" }, { "biao xian chu", "表现出" }, { "biao xian chu lai", "表现出来" },
			{ "biao xian li", "表现力" }, { "biao xian shou fa", "表现手法" }, { "biao xian xing shi", "表现形式" }, { "biao xiang", "表象" }, { "biao xin li yi", "标新立异" },
			{ "biao yan", "表演" }, { "biao yan zhe", "表演者" }, { "biao yang", "表扬" }, { "biao you", "标有" }, { "biao yu", "标语" }, { "biao zhang", "表彰" },
			{ "biao zhang da hui", "表彰大会" }, { "biao zheng", "表征" }, { "biao zhi", "标志" }, { "biao zhi", "标致" }, { "biao zhi", "标识" },
			{ "biao zhi xing", "标志性" }, { "biao zhong", "表中" }, { "biao zhu", "标注" }, { "biao zhun", "标准" }, { "biao zhun ban", "标准版" },
			{ "biao zhun hua", "标准化" }, { "biao zi", "婊子" }, { "bie", "別" }, { "bie", "别" }, { "bie", "咇" }, { "bie", "彆" }, { "bie", "徶" }, { "bie", "憋" },
			{ "bie", "柲" }, { "bie", "瘪" }, { "bie", "癟" }, { "bie", "虌" }, { "bie", "蛂" }, { "bie", "蟞" }, { "bie", "襒" }, { "bie", "蹩" }, { "bie", "鱉" },
			{ "bie", "鳖" }, { "bie", "鼈" }, { "bie ba", "别把" }, { "bie bu zhu", "憋不住" }, { "bie chu", "别处" }, { "bie chu xin cai", "别出心裁" },
			{ "bie da", "别打" }, { "bie de", "别的" }, { "bie dong", "别动" }, { "bie ge", "别个" }, { "bie guai", "别怪" }, { "bie guan", "别管" }, { "bie guo", "别国" },
			{ "bie ji", "别急" }, { "bie jia", "别家" }, { "bie jiao", "蹩脚" }, { "bie ju", "别具" }, { "bie ju yi ge", "别具一格" }, { "bie kan", "别看" },
			{ "bie ke", "别克" }, { "bie ke qi", "别客气" }, { "bie ku", "别哭" }, { "bie lai", "别来" }, { "bie li", "别离" }, { "bie mai", "别买" }, { "bie ming", "别名" },
			{ "bie na", "别拿" }, { "bie niu", "别扭" }, { "bie pa", "别怕" }, { "bie qu", "别去" }, { "bie qu", "憋屈" }, { "bie rang", "别让" }, { "bie ren", "别人" },
			{ "bie shu", "别墅" }, { "bie shu qu", "别墅区" }, { "bie shuo", "别说" }, { "bie si", "憋死" }, { "bie tai", "别太" }, { "bie ti", "别提" },
			{ "bie wang", "别忘" }, { "bie wen", "别问" }, { "bie wu", "别无" }, { "bie wu xuan ze", "别无选择" }, { "bie xiang", "别想" }, { "bie yang", "别样" },
			{ "bie yi wei", "别以为" }, { "bie yong", "别用" }, { "bie you", "别有" }, { "bie you yong xin", "别有用心" }, { "bie zai", "别再" }, { "bie zai", "别在" },
			{ "bie zhe", "憋着" }, { "bie zhi", "别致" }, { "bie zou", "别走" }, { "bin", "傧" }, { "bin", "儐" }, { "bin", "宾" }, { "bin", "彬" }, { "bin", "摈" },
			{ "bin", "擯" }, { "bin", "斌" }, { "bin", "椕" }, { "bin", "槟" }, { "bin", "殡" }, { "bin", "殯" }, { "bin", "滨" }, { "bin", "濒" }, { "bin", "濱" },
			{ "bin", "濵" }, { "bin", "瀕" }, { "bin", "玢" }, { "bin", "繽" }, { "bin", "缤" }, { "bin", "膑" }, { "bin", "臏" }, { "bin", "虨" }, { "bin", "蠙" },
			{ "bin", "豳" }, { "bin", "賓" }, { "bin", "邠" }, { "bin", "鑌" }, { "bin", "镔" }, { "bin", "霦" }, { "bin", "髌" }, { "bin", "髕" }, { "bin", "鬓" },
			{ "bin", "鬢" }, { "bin bin", "彬彬" }, { "bin bin you li", "彬彬有礼" }, { "bin de", "宾得" }, { "bin fen", "缤纷" }, { "bin guan", "宾馆" },
			{ "bin hai", "滨海" }, { "bin hai xin qu", "滨海新区" }, { "bin jiang", "滨江" }, { "bin ke", "宾客" }, { "bin li", "宾利" }, { "bin lin", "濒临" },
			{ "bin qi bu", "滨崎步" }, { "bin wei", "濒危" }, { "bin yi guan", "殡仪馆" }, { "bin yu", "宾语" }, { "bin zang", "殡葬" }, { "bin zhou", "滨州" },
			{ "bing", "丙" }, { "bing", "並" }, { "bing", "併" }, { "bing", "倂" }, { "bing", "偋" }, { "bing", "兵" }, { "bing", "冰" }, { "bing", "垪" },
			{ "bing", "寎" }, { "bing", "屏" }, { "bing", "并" }, { "bing", "幷" }, { "bing", "庰" }, { "bing", "怲" }, { "bing", "抦" }, { "bing", "掤" },
			{ "bing", "摒" }, { "bing", "昺" }, { "bing", "柄" }, { "bing", "栟" }, { "bing", "梹" }, { "bing", "棅" }, { "bing", "槟" }, { "bing", "檳" },
			{ "bing", "氷" }, { "bing", "炳" }, { "bing", "病" }, { "bing", "禀" }, { "bing", "秉" }, { "bing", "稟" }, { "bing", "窉" }, { "bing", "竝" },
			{ "bing", "苪" }, { "bing", "蛃" }, { "bing", "誁" }, { "bing", "邴" }, { "bing", "鋲" }, { "bing", "陃" }, { "bing", "鞆" }, { "bing", "鞞" },
			{ "bing", "餅" }, { "bing", "餠" }, { "bing", "饼" }, { "bing an", "并按" }, { "bing ba", "并把" }, { "bing bao", "冰雹" }, { "bing bao", "并报" },
			{ "bing bei", "并被" }, { "bing bian", "病变" }, { "bing bing", "冰冰" }, { "bing bu", "并不" }, { "bing bu dai biao", "并不代表" }, { "bing bu duo", "并不多" },
			{ "bing bu hui", "并不会" }, { "bing bu nan", "并不难" }, { "bing bu shi", "并不是" }, { "bing bu xiang", "并不像" }, { "bing bu yi ding", "并不一定" },
			{ "bing bu zhi dao", "并不知道" }, { "bing cheng", "并称" }, { "bing cheng", "病程" }, { "bing cheng", "秉承" }, { "bing chi", "秉持" },
			{ "bing chong", "病虫" }, { "bing chong hai", "病虫害" }, { "bing chu", "并处" }, { "bing chuan", "冰川" }, { "bing chuang", "病床" }, { "bing cong", "并从" },
			{ "bing cun", "并存" }, { "bing dao", "冰岛" }, { "bing dao", "病倒" }, { "bing dian", "冰点" }, { "bing dong", "冰冻" }, { "bing du", "病毒" },
			{ "bing du gan ran", "病毒感染" }, { "bing du ku", "病毒库" }, { "bing du xing", "病毒性" }, { "bing dui", "并对" }, { "bing er", "冰儿" }, { "bing fa", "兵法" },
			{ "bing fa", "冰法" }, { "bing fa", "并发" }, { "bing fa zheng", "并发症" }, { "bing fang", "病房" }, { "bing fang li", "病房里" }, { "bing fei", "并非" },
			{ "bing fei ru ci", "并非如此" }, { "bing feng", "冰封" }, { "bing gan", "饼干" }, { "bing gei", "并给" }, { "bing gou", "并购" }, { "bing gun", "冰棍" },
			{ "bing hai", "病害" }, { "bing he", "冰河" }, { "bing huan", "病患" }, { "bing huan zhe", "病患者" }, { "bing huo", "冰火" }, { "bing ji ling", "冰激凌" },
			{ "bing jia", "病假" }, { "bing jian", "并肩" }, { "bing jiang", "并将" }, { "bing jiang qi", "并将其" }, { "bing jing", "并经" }, { "bing ju", "并举" },
			{ "bing jun", "病菌" }, { "bing ke", "并可" }, { "bing kou", "并口" }, { "bing kuai", "冰块" }, { "bing lang", "槟榔" }, { "bing leng", "冰冷" },
			{ "bing li", "兵力" }, { "bing li", "病例" }, { "bing li", "病历" }, { "bing li", "病理" }, { "bing li xue", "病理学" }, { "bing lian", "并联" },
			{ "bing liang", "冰凉" }, { "bing lie", "并列" }, { "bing long", "冰龙" }, { "bing ma", "兵马" }, { "bing ma yong", "兵马俑" }, { "bing mei", "并没" },
			{ "bing mo", "病魔" }, { "bing neng", "并能" }, { "bing pai", "并排" }, { "bing qi", "兵器" }, { "bing qi", "摒弃" }, { "bing qi lin", "冰淇淋" },
			{ "bing qie", "并且" }, { "bing qing", "并请" }, { "bing qing", "病情" }, { "bing rang", "并让" }, { "bing ren", "病人" }, { "bing ru", "并入" },
			{ "bing shan", "冰山" }, { "bing shi", "并使" }, { "bing shi", "病史" }, { "bing shi", "病逝" }, { "bing shuang", "冰霜" }, { "bing shui", "冰水" },
			{ "bing si", "病死" }, { "bing tai", "病态" }, { "bing tang", "冰糖" }, { "bing tian xue di", "冰天雪地" }, { "bing tong", "病痛" }, { "bing tuan", "兵团" },
			{ "bing wei", "并为" }, { "bing wei", "并未" }, { "bing wei", "病危" }, { "bing wu", "并无" }, { "bing xiang", "冰箱" }, { "bing xiang", "并向" },
			{ "bing xiang li", "冰箱里" }, { "bing xin", "冰心" }, { "bing xing", "并行" }, { "bing xue", "冰雪" }, { "bing yi", "并以" }, { "bing yi", "并已" },
			{ "bing yin", "病因" }, { "bing ying", "兵营" }, { "bing yong", "并用" }, { "bing you", "并有" }, { "bing you", "并由" }, { "bing you", "病友" },
			{ "bing yu", "并与" }, { "bing yu", "并于" }, { "bing yuan", "病原" }, { "bing yuan ti", "病原体" }, { "bing zai", "并在" }, { "bing zao", "病灶" },
			{ "bing zhen", "冰镇" }, { "bing zheng", "病症" }, { "bing zhong", "兵种" }, { "bing zhong", "并重" }, { "bing zhong", "病重" }, { "bing zi", "饼子" },
			{ "bing zi fu", "并自负" }, { "bing zuo", "并作" } };
};
