package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN47 {
	public static String[][] pl = { { "tong", "仝" }, { "tong", "佟" }, { "tong", "侗" }, { "tong", "偅" }, { "tong", "僮" }, { "tong", "同" }, { "tong", "哃" },
			{ "tong", "嗵" }, { "tong", "囲" }, { "tong", "垌" }, { "tong", "峒" }, { "tong", "彤" }, { "tong", "恸" }, { "tong", "慟" }, { "tong", "捅" },
			{ "tong", "曈" }, { "tong", "朣" }, { "tong", "桐" }, { "tong", "桶" }, { "tong", "樋" }, { "tong", "橦" }, { "tong", "氃" }, { "tong", "浵" },
			{ "tong", "湩" }, { "tong", "潼" }, { "tong", "炵" }, { "tong", "烔" }, { "tong", "爞" }, { "tong", "犝" }, { "tong", "狪" }, { "tong", "痌" },
			{ "tong", "痛" }, { "tong", "瞳" }, { "tong", "砼" }, { "tong", "童" }, { "tong", "筒" }, { "tong", "粡" }, { "tong", "絧" }, { "tong", "統" },
			{ "tong", "统" }, { "tong", "膧" }, { "tong", "茼" }, { "tong", "蓪" }, { "tong", "衕" }, { "tong", "詷" }, { "tong", "通" }, { "tong", "酮" },
			{ "tong", "鉖" }, { "tong", "銅" }, { "tong", "铜" }, { "tong", "餇" }, { "tong", "鮦" }, { "tong ban", "同伴" }, { "tong ban", "同班" },
			{ "tong ban", "铜板" }, { "tong ban tong xue", "同班同学" }, { "tong bao", "同胞" }, { "tong bao", "通宝" }, { "tong bao", "通报" },
			{ "tong bao pi ping", "通报批评" }, { "tong bi", "同比" }, { "tong bi zeng zhang", "同比增长" }, { "tong bian", "通便" }, { "tong bing", "通病" },
			{ "tong bing xiang lian", "同病相怜" }, { "tong bu", "同步" }, { "tong bu yu sheng", "痛不欲生" }, { "tong chang", "通常" }, { "tong chang", "通畅" },
			{ "tong che", "通车" }, { "tong cheng", "同城" }, { "tong cheng", "统称" }, { "tong chi", "痛斥" }, { "tong chi", "通吃" }, { "tong chou", "统筹" },
			{ "tong chu", "痛楚" }, { "tong chuang", "同窗" }, { "tong da", "通达" }, { "tong da wei", "佟大为" }, { "tong dao", "同道" }, { "tong dao", "通道" },
			{ "tong de", "痛得" }, { "tong deng", "同等" }, { "tong dian", "通电" }, { "tong dian hua", "通电话" }, { "tong fang", "同房" }, { "tong fang", "同方" },
			{ "tong feng", "痛风" }, { "tong feng", "通风" }, { "tong gan", "同感" }, { "tong gan", "痛感" }, { "tong gao", "通告" }, { "tong gong", "童工" },
			{ "tong guan", "通关" }, { "tong gui yu jin", "同归于尽" }, { "tong guo", "通过" }, { "tong guo lv", "通过率" }, { "tong guo shou ji", "通过手机" },
			{ "tong guo wang luo", "通过网络" }, { "tong guo xue xi", "通过学习" }, { "tong hang", "同行" }, { "tong hang", "通航" }, { "tong hang ye", "同行业" },
			{ "tong hao", "同好" }, { "tong hen", "痛恨" }, { "tong hong", "通红" }, { "tong hua", "同化" }, { "tong hua", "童话" }, { "tong hua", "通化" },
			{ "tong hua", "通话" }, { "tong hua gu shi", "童话故事" }, { "tong hua shun", "同花顺" }, { "tong huo", "同伙" }, { "tong huo peng zhang", "通货膨胀" },
			{ "tong ji", "同济" }, { "tong ji", "同级" }, { "tong ji", "统计" }, { "tong ji", "通缉" }, { "tong ji bao gao", "统计报告" }, { "tong ji biao", "统计表" },
			{ "tong ji da xue", "同济大学" }, { "tong ji fen xi", "统计分析" }, { "tong ji gong zuo", "统计工作" }, { "tong ji ju", "统计局" }, { "tong ji ling", "通缉令" },
			{ "tong ji shu ju", "统计数据" }, { "tong ji shu zi", "统计数字" }, { "tong ji xue", "统计学" }, { "tong ji zi liao", "统计资料" }, { "tong jia", "铜价" },
			{ "tong jing", "痛经" }, { "tong ju", "同居" }, { "tong kao", "统考" }, { "tong kong", "瞳孔" }, { "tong ku", "痛哭" }, { "tong ku", "痛苦" },
			{ "tong ku liu ti", "痛哭流涕" }, { "tong kuai", "痛快" }, { "tong kuang", "铜矿" }, { "tong le", "同乐" }, { "tong lei", "同类" },
			{ "tong lei chan pin", "同类产品" }, { "tong lei xing", "同类型" }, { "tong li", "同理" }, { "tong ling", "同龄" }, { "tong ling", "统领" },
			{ "tong ling", "通灵" }, { "tong ling", "铜陵" }, { "tong ling ren", "同龄人" }, { "tong lu", "通路" }, { "tong luo", "通络" }, { "tong luo wan", "铜锣湾" },
			{ "tong ma", "痛骂" }, { "tong mai", "同埋" }, { "tong men", "同门" }, { "tong meng", "同盟" }, { "tong ming", "同名" }, { "tong nian", "同年" },
			{ "tong nian", "童年" }, { "tong pai", "铜牌" }, { "tong pian", "通篇" }, { "tong qi", "同期" }, { "tong qi", "通气" }, { "tong qian", "铜钱" },
			{ "tong qing", "同情" }, { "tong qing xin", "同情心" }, { "tong qu", "同去" }, { "tong qu", "童趣" }, { "tong ren", "同人" }, { "tong ren", "同仁" },
			{ "tong ren nv", "同人女" }, { "tong ren tang", "同仁堂" }, { "tong ri", "同日" }, { "tong shang", "同上" }, { "tong shi", "同事" }, { "tong shi", "同时" },
			{ "tong shi", "同是" }, { "tong shi", "痛失" }, { "tong shi dai", "同时代" }, { "tong shi jin xing", "同时进行" }, { "tong shi shi yong", "同时使用" },
			{ "tong shi you", "同时又" }, { "tong shu", "同属" }, { "tong shuai", "统帅" }, { "tong shun", "通顺" }, { "tong su", "通俗" }, { "tong su yi dong", "通俗易懂" },
			{ "tong tai", "同台" }, { "tong ti", "通体" }, { "tong tian", "通天" }, { "tong tong", "童童" }, { "tong tong", "统统" }, { "tong tong", "通通" },
			{ "tong tou", "通透" }, { "tong wang", "通往" }, { "tong wei", "同为" }, { "tong wei su", "同位素" }, { "tong wu", "同屋" }, { "tong xi", "同喜" },
			{ "tong xiang", "同乡" }, { "tong xiang", "桐乡" }, { "tong xiang", "通向" }, { "tong xiang", "铜像" }, { "tong xiao", "通宵" }, { "tong xin", "同心" },
			{ "tong xin", "痛心" }, { "tong xin", "童心" }, { "tong xin", "通信" }, { "tong xin hang ye", "通信行业" }, { "tong xin ji shou", "痛心疾首" },
			{ "tong xin ji shu", "通信技术" }, { "tong xin she bei", "通信设备" }, { "tong xin xi tong", "通信系统" }, { "tong xing", "同性" }, { "tong xing", "同行" },
			{ "tong xing", "通行" }, { "tong xing fei", "通行费" }, { "tong xing lian", "同性恋" }, { "tong xing zheng", "通行证" }, { "tong xu", "通许" },
			{ "tong xue", "同学" }, { "tong xue hui", "同学会" }, { "tong xue ju hui", "同学聚会" }, { "tong xue lu", "同学录" }, { "tong xun", "通讯" },
			{ "tong xun lu", "通讯录" }, { "tong xun she", "通讯社" }, { "tong xun yuan", "通讯员" }, { "tong yang", "同样" }, { "tong yao", "童谣" }, { "tong ye", "同业" },
			{ "tong ye", "铜业" }, { "tong yi", "同一" }, { "tong yi", "同意" }, { "tong yi", "统一" }, { "tong yi ci", "同义词" }, { "tong yi guan li", "统一管理" },
			{ "tong yi shou ge", "同一首歌" }, { "tong yi si xiang", "统一思想" }, { "tong yi tian", "同一天" }, { "tong yi tiao", "同一条" },
			{ "tong yi zhan xian", "统一战线" }, { "tong yi zhong", "同一种" }, { "tong yong", "通用" }, { "tong yong qi che", "通用汽车" }, { "tong yu", "同于" },
			{ "tong yuan", "同源" }, { "tong yue", "同月" }, { "tong zai", "同在" }, { "tong zhan", "统战" }, { "tong zhan bu", "统战部" }, { "tong zhang", "通胀" },
			{ "tong zhen", "童真" }, { "tong zhi", "同志" }, { "tong zhi", "统治" }, { "tong zhi", "通知" }, { "tong zhi dan", "通知单" }, { "tong zhi hua", "同质化" },
			{ "tong zhi jie ji", "统治阶级" }, { "tong zhi shu", "通知书" }, { "tong zhi zhe", "统治者" }, { "tong zhong", "同种" }, { "tong zhou", "通州" },
			{ "tong zhou qu", "通州区" }, { "tong zhu", "同住" }, { "tong zhuang", "童装" }, { "tong zhuo", "同桌" }, { "tong zi", "童子" }, { "tong zi", "筒子" },
			{ "tou", "偷" }, { "tou", "偸" }, { "tou", "埱" }, { "tou", "头" }, { "tou", "妵" }, { "tou", "投" }, { "tou", "敨" }, { "tou", "斢" }, { "tou", "紏" },
			{ "tou", "蘣" }, { "tou", "透" }, { "tou", "鍮" }, { "tou", "钭" }, { "tou", "頭" }, { "tou", "骰" }, { "tou", "黈" }, { "tou an", "投案" },
			{ "tou ban", "头版" }, { "tou bao", "头孢" }, { "tou bao", "投保" }, { "tou bao ren", "投保人" }, { "tou ben", "投奔" }, { "tou biao", "投标" },
			{ "tou biao ren", "投标人" }, { "tou bu", "头部" }, { "tou chan", "投产" }, { "tou che", "透彻" }, { "tou chi", "偷吃" }, { "tou chu", "透出" },
			{ "tou cun", "头寸" }, { "tou da", "头大" }, { "tou dai", "头戴" }, { "tou dang", "投档" }, { "tou dao", "偷盗" }, { "tou dao", "投到" },
			{ "tou deng cang", "头等舱" }, { "tou deng da shi", "头等大事" }, { "tou di", "投递" }, { "tou ding", "头顶" }, { "tou ding", "透顶" },
			{ "tou dong xi", "偷东西" }, { "tou du", "偷渡" }, { "tou er", "头儿" }, { "tou fa", "头发" }, { "tou fang", "投放" }, { "tou gao", "投稿" },
			{ "tou gong jian liao", "偷工减料" }, { "tou gu", "头骨" }, { "tou guo", "透过" }, { "tou hang", "投行" }, { "tou hao", "头号" }, { "tou hun", "头昏" },
			{ "tou ji", "投机" }, { "tou ji xing", "投机性" }, { "tou ji zhe", "投机者" }, { "tou jian li", "投简历" }, { "tou jiang", "头奖" }, { "tou jin", "头巾" },
			{ "tou jin", "投进" }, { "tou jing", "透镜" }, { "tou kan", "偷看" }, { "tou kao", "投靠" }, { "tou kui", "偷窥" }, { "tou kui", "头盔" }, { "tou lai", "偷来" },
			{ "tou lai", "头来" }, { "tou lan", "偷懒" }, { "tou lan", "投篮" }, { "tou le", "透了" }, { "tou liang", "透亮" }, { "tou ling", "头领" },
			{ "tou lou", "透漏" }, { "tou lu", "头颅" }, { "tou lu", "透露" }, { "tou ming", "透明" }, { "tou ming du", "透明度" }, { "tou mu", "头目" },
			{ "tou nao", "头脑" }, { "tou niu", "头牛" }, { "tou pai", "偷拍" }, { "tou pi", "头皮" }, { "tou piao", "投票" }, { "tou po xue liu", "头破血流" },
			{ "tou qi", "透气" }, { "tou qie", "偷窃" }, { "tou qing", "偷情" }, { "tou qiu", "头球" }, { "tou rong zi", "投融资" }, { "tou ru", "投入" },
			{ "tou ru shi yong", "投入使用" }, { "tou shang", "头上" }, { "tou she", "投射" }, { "tou shen", "投身" }, { "tou shi", "头饰" }, { "tou shi", "透视" },
			{ "tou shui", "偷税" }, { "tou su", "投诉" }, { "tou su dian hua", "投诉电话" }, { "tou tai", "投胎" }, { "tou teng", "头疼" }, { "tou tian", "头天" },
			{ "tou tiao", "头条" }, { "tou ting", "偷听" }, { "tou tong", "头痛" }, { "tou tou", "偷偷" }, { "tou tou", "头头" }, { "tou tou de", "偷偷的" },
			{ "tou tou mo mo", "偷偷摸摸" }, { "tou wen jian", "头文件" }, { "tou wen zi", "头文字" }, { "tou xi", "偷袭" }, { "tou xi", "透析" }, { "tou xia", "投下" },
			{ "tou xian", "头先" }, { "tou xian", "头衔" }, { "tou xiang", "头像" }, { "tou xiang", "投向" }, { "tou xiang", "投降" }, { "tou xiao", "偷笑" },
			{ "tou xu", "头绪" }, { "tou ye", "头也" }, { "tou ying", "投影" }, { "tou ying ji", "投影机" }, { "tou ying yi", "投影仪" }, { "tou yuan", "投缘" },
			{ "tou yun", "头晕" }, { "tou zhe", "偷着" }, { "tou zhe", "透着" }, { "tou zhe le", "偷着乐" }, { "tou zhi", "投掷" }, { "tou zhi", "透支" },
			{ "tou zhong", "投中" }, { "tou zhu", "投注" }, { "tou zhu zhan", "投注站" }, { "tou zi", "头子" }, { "tou zi", "投资" }, { "tou zi ce lue", "投资策略" },
			{ "tou zi cheng ben", "投资成本" }, { "tou zi e", "投资额" }, { "tou zi fang", "投资方" }, { "tou zi feng xian", "投资风险" }, { "tou zi gong si", "投资公司" },
			{ "tou zi guan li", "投资管理" }, { "tou zi gui mo", "投资规模" }, { "tou zi huan jing", "投资环境" }, { "tou zi hui bao", "投资回报" },
			{ "tou zi ji gou", "投资机构" }, { "tou zi ji hua", "投资计划" }, { "tou zi ji hui", "投资机会" }, { "tou zi ji jin", "投资基金" }, { "tou zi ji tuan", "投资集团" },
			{ "tou zi jia zhi", "投资价值" }, { "tou zi jian yi", "投资建议" }, { "tou zi jue ce", "投资决策" }, { "tou zi li cai", "投资理财" }, { "tou zi li nian", "投资理念" },
			{ "tou zi qi ye", "投资企业" }, { "tou zi qu dao", "投资渠道" }, { "tou zi ren", "投资人" }, { "tou zi shang", "投资商" }, { "tou zi shou yi", "投资收益" },
			{ "tou zi xiang mu", "投资项目" }, { "tou zi yin hang", "投资银行" }, { "tou zi zhe", "投资者" }, { "tou zi zhu ti", "投资主体" }, { "tou zi zong e", "投资总额" },
			{ "tou zi zu he", "投资组合" }, { "tou zou", "偷走" }, { "tu", "兎" }, { "tu", "兔" }, { "tu", "凸" }, { "tu", "吐" }, { "tu", "唋" }, { "tu", "図" },
			{ "tu", "图" }, { "tu", "圖" }, { "tu", "土" }, { "tu", "堍" }, { "tu", "塗" }, { "tu", "屠" }, { "tu", "峹" }, { "tu", "嵞" }, { "tu", "嶀" },
			{ "tu", "廜" }, { "tu", "徒" }, { "tu", "捈" }, { "tu", "捸" }, { "tu", "梌" }, { "tu", "汢" }, { "tu", "涂" }, { "tu", "涋" }, { "tu", "湥" },
			{ "tu", "瑹" }, { "tu", "瘏" }, { "tu", "禿" }, { "tu", "秃" }, { "tu", "稌" }, { "tu", "突" }, { "tu", "筡" }, { "tu", "腯" }, { "tu", "荼" },
			{ "tu", "莵" }, { "tu", "菟" }, { "tu", "葖" }, { "tu", "蒤" }, { "tu", "跿" }, { "tu", "途" }, { "tu", "酴" }, { "tu", "釷" }, { "tu", "鋀" },
			{ "tu", "鍎" }, { "tu", "钍" }, { "tu", "駼" }, { "tu", "鵌" }, { "tu", "鵚" }, { "tu", "鵵" }, { "tu", "鶟" }, { "tu", "鷋" }, { "tu", "鷵" },
			{ "tu", "鼵" }, { "tu an", "图案" }, { "tu an", "途安" }, { "tu bian", "突变" }, { "tu biao", "图标" }, { "tu biao", "图表" }, { "tu bie", "土鳖" },
			{ "tu bu", "徒步" }, { "tu ceng", "图层" }, { "tu ceng", "涂层" }, { "tu chu", "凸出" }, { "tu chu", "吐出" }, { "tu chu", "突出" },
			{ "tu chu gong xian", "突出贡献" }, { "tu chu wen ti", "突出问题" }, { "tu chu zhong dian", "突出重点" }, { "tu di", "土地" }, { "tu di", "徒弟" },
			{ "tu di cheng bao", "土地承包" }, { "tu di chu bei", "土地储备" }, { "tu di chu rang", "土地出让" }, { "tu di gong ying", "土地供应" },
			{ "tu di guan li", "土地管理" }, { "tu di kai fa", "土地开发" }, { "tu di li yong", "土地利用" }, { "tu di mian ji", "土地面积" }, { "tu di shi chang", "土地市场" },
			{ "tu di zi yuan", "土地资源" }, { "tu dou", "土豆" }, { "tu dou si", "土豆丝" }, { "tu dou wang", "土豆网" }, { "tu er qi", "土耳其" }, { "tu fa", "突发" },
			{ "tu fa shi jian", "突发事件" }, { "tu fa xing", "突发性" }, { "tu fang", "土方" }, { "tu fei", "土匪" }, { "tu fei meng jin", "突飞猛进" }, { "tu fu", "屠夫" },
			{ "tu ge", "图个" }, { "tu hua", "图画" }, { "tu ji", "图集" }, { "tu ji", "突击" }, { "tu ji dui", "突击队" }, { "tu jia zu", "土家族" }, { "tu jian", "土建" },
			{ "tu jie", "图解" }, { "tu jing", "图景" }, { "tu jing", "途径" }, { "tu jing", "途经" }, { "tu jue", "突厥" }, { "tu ku", "图库" }, { "tu lao", "徒劳" },
			{ "tu le", "吐了" }, { "tu li", "图例" }, { "tu li", "土里" }, { "tu liao", "涂料" }, { "tu long", "屠龙" }, { "tu lu", "吐露" }, { "tu lu fan", "吐鲁番" },
			{ "tu mo", "涂抹" }, { "tu mou", "图谋" }, { "tu mu", "土木" }, { "tu mu gong cheng", "土木工程" }, { "tu ni si", "突尼斯" }, { "tu pian", "图片" },
			{ "tu po", "突破" }, { "tu po kou", "突破口" }, { "tu po xing", "突破性" }, { "tu pu", "图谱" }, { "tu qi", "凸起" }, { "tu qi", "突起" }, { "tu ran", "突然" },
			{ "tu ran chu xian", "突然出现" }, { "tu ran jian", "突然间" }, { "tu ran jue de", "突然觉得" }, { "tu ran xiang qi", "突然想起" }, { "tu rang", "土壤" },
			{ "tu ren", "土人" }, { "tu ru", "突入" }, { "tu ru qi lai", "突如其来" }, { "tu sha", "屠杀" }, { "tu shang", "涂上" }, { "tu sheng tu zhang", "土生土长" },
			{ "tu shi", "图示" }, { "tu shou", "徒手" }, { "tu shu", "图书" }, { "tu shu guan", "图书馆" }, { "tu si", "土司" }, { "tu te chan", "土特产" },
			{ "tu teng", "图腾" }, { "tu tou", "秃头" }, { "tu tu", "兔兔" }, { "tu tu", "吐吐" }, { "tu tu", "图图" }, { "tu wei", "图为" }, { "tu wei", "突围" },
			{ "tu wen", "图文" }, { "tu wen ban", "图文版" }, { "tu wen bing mao", "图文并茂" }, { "tu wu", "突兀" }, { "tu xi", "突袭" }, { "tu xian", "凸显" },
			{ "tu xian", "凸现" }, { "tu xian", "突显" }, { "tu xiang", "图像" }, { "tu xiang", "图象" }, { "tu xiang chu li", "图像处理" }, { "tu xie", "吐血" },
			{ "tu xing", "图形" }, { "tu xing", "土星" }, { "tu xing hua", "图形化" }, { "tu xing jie mian", "图形界面" }, { "tu xue", "吐血" }, { "tu ya", "涂鸦" },
			{ "tu yang", "图样" }, { "tu zai", "屠宰" }, { "tu zai", "涂在" }, { "tu zai chang", "屠宰场" }, { "tu zhi", "图纸" }, { "tu zhong", "图中" },
			{ "tu zhong", "途中" }, { "tu zhu", "土著" }, { "tu zhuang", "涂装" }, { "tu zi", "兔子" }, { "tu zi", "秃子" }, { "tuan", "团" }, { "tuan", "団" },
			{ "tuan", "團" }, { "tuan", "墥" }, { "tuan", "彖" }, { "tuan", "慱" }, { "tuan", "抟" }, { "tuan", "槫" }, { "tuan", "湍" }, { "tuan", "煓" },
			{ "tuan", "猯" }, { "tuan", "疃" }, { "tuan", "糰" }, { "tuan", "褖" }, { "tuan", "貒" }, { "tuan", "鏄" }, { "tuan", "鷒" }, { "tuan", "鷻" },
			{ "tuan dui", "团队" }, { "tuan dui jing shen", "团队精神" }, { "tuan gou", "团购" }, { "tuan huo", "团伙" }, { "tuan jie", "团结" },
			{ "tuan jie qi lai", "团结起来" }, { "tuan jie yi zhi", "团结一致" }, { "tuan ju", "团聚" }, { "tuan li", "团里" }, { "tuan shi wei", "团市委" },
			{ "tuan ti", "团体" }, { "tuan tuan", "团团" }, { "tuan tuan zhuan", "团团转" }, { "tuan wei", "团委" }, { "tuan yuan", "团员" }, { "tuan yuan", "团圆" },
			{ "tuan zhang", "团长" }, { "tuan zhi bu", "团支部" }, { "tuan zhong yang", "团中央" }, { "tuan zu zhi", "团组织" }, { "tui", "俀" }, { "tui", "僓" },
			{ "tui", "弚" }, { "tui", "忒" }, { "tui", "怢" }, { "tui", "推" }, { "tui", "橔" }, { "tui", "煺" }, { "tui", "穨" }, { "tui", "腿" }, { "tui", "蓷" },
			{ "tui", "藬" }, { "tui", "蜕" }, { "tui", "褪" }, { "tui", "蹪" }, { "tui", "退" }, { "tui", "隤" }, { "tui", "頹" }, { "tui", "頽" }, { "tui", "颓" },
			{ "tui", "駾" }, { "tui", "騩" }, { "tui", "魋" }, { "tui bao", "退保" }, { "tui bian", "蜕变" }, { "tui bo zhu lan", "推波助澜" }, { "tui bu", "腿部" },
			{ "tui bu", "退步" }, { "tui ce", "推测" }, { "tui chang", "退场" }, { "tui che", "推车" }, { "tui chen chu xin", "推陈出新" }, { "tui chi", "推迟" },
			{ "tui chong", "推崇" }, { "tui chu", "推出" }, { "tui chu", "退出" }, { "tui ci", "推辞" }, { "tui dang", "退党" }, { "tui dao", "推倒" },
			{ "tui dao", "推到" }, { "tui dao", "推导" }, { "tui dao", "退到" }, { "tui diao", "推掉" }, { "tui diao", "退掉" }, { "tui ding", "推定" },
			{ "tui ding", "退订" }, { "tui dong", "推动" }, { "tui dong li", "推动力" }, { "tui dong zuo yong", "推动作用" }, { "tui duan", "推断" }, { "tui fan", "推翻" },
			{ "tui fang", "退房" }, { "tui fei", "退费" }, { "tui fei", "颓废" }, { "tui gao", "推高" }, { "tui gei", "推给" }, { "tui geng huan lin", "退耕还林" },
			{ "tui guang", "推广" }, { "tui guang ying yong", "推广应用" }, { "tui hou", "退后" }, { "tui hua", "退化" }, { "tui huan", "退换" }, { "tui huan", "退还" },
			{ "tui hui", "退回" }, { "tui hui lai", "退回来" }, { "tui huo", "退火" }, { "tui huo", "退货" }, { "tui jian", "推荐" }, { "tui jian shi yong", "推荐使用" },
			{ "tui jian xin", "推荐信" }, { "tui jiao", "腿脚" }, { "tui jie", "推介" }, { "tui jie hui", "推介会" }, { "tui jin", "推进" }, { "tui ju", "推举" },
			{ "tui kai", "推开" }, { "tui kuan", "退款" }, { "tui li", "推力" }, { "tui li", "推理" }, { "tui lu", "退路" }, { "tui lun", "推论" }, { "tui men", "推门" },
			{ "tui na", "推拿" }, { "tui piao", "退票" }, { "tui qian", "退钱" }, { "tui qiao", "推敲" }, { "tui qu", "褪去" }, { "tui qu", "退去" }, { "tui que", "退却" },
			{ "tui rang", "退让" }, { "tui se", "褪色" }, { "tui shai", "褪色" }, { "tui shang", "推上" }, { "tui shang", "腿上" }, { "tui shi", "退市" },
			{ "tui shi", "颓势" }, { "tui shou", "推手" }, { "tui shui", "退税" }, { "tui song", "推送" }, { "tui suan", "推算" }, { "tui suo", "退缩" },
			{ "tui tu ji", "推土机" }, { "tui tuo", "推脱" }, { "tui wei", "推诿" }, { "tui wu", "退伍" }, { "tui wu jun ren", "退伍军人" }, { "tui xia", "退下" },
			{ "tui xiang", "推向" }, { "tui xiao", "推销" }, { "tui xiao yuan", "推销员" }, { "tui xie", "推卸" }, { "tui xing", "推行" }, { "tui xiu", "退休" },
			{ "tui xiu jin", "退休金" }, { "tui xiu nian ling", "退休年龄" }, { "tui xiu ren yuan", "退休人员" }, { "tui xuan", "推选" }, { "tui xue", "退学" },
			{ "tui yi", "推移" }, { "tui yi", "退役" }, { "tui yi bu", "退一步" }, { "tui zhe", "推着" }, { "tun", "吞" }, { "tun", "呑" }, { "tun", "囤" },
			{ "tun", "坉" }, { "tun", "屯" }, { "tun", "庉" }, { "tun", "暾" }, { "tun", "氽" }, { "tun", "焞" }, { "tun", "畽" }, { "tun", "臀" }, { "tun", "芚" },
			{ "tun", "蜳" }, { "tun", "褪" }, { "tun", "豚" }, { "tun", "軘" }, { "tun", "錪" }, { "tun", "飩" }, { "tun", "饨" }, { "tun", "魨" },
			{ "tun bing", "吞并" }, { "tun bu", "臀部" }, { "tun ji", "囤积" }, { "tun mo", "吞没" }, { "tun shi", "吞噬" }, { "tun shi", "吞食" }, { "tun tu", "吞吐" },
			{ "tun tu liang", "吞吐量" }, { "tun tun tu tu", "吞吞吐吐" }, { "tun xia", "吞下" }, { "tun yan", "吞咽" }, { "tuo", "乇" }, { "tuo", "佗" }, { "tuo", "侂" },
			{ "tuo", "侻" }, { "tuo", "唾" }, { "tuo", "嘽" }, { "tuo", "坨" }, { "tuo", "堶" }, { "tuo", "妥" }, { "tuo", "嫷" }, { "tuo", "岮" }, { "tuo", "庹" },
			{ "tuo", "托" }, { "tuo", "拓" }, { "tuo", "拖" }, { "tuo", "柁" }, { "tuo", "柝" }, { "tuo", "椭" }, { "tuo", "楕" }, { "tuo", "橐" }, { "tuo", "橢" },
			{ "tuo", "毤" }, { "tuo", "毻" }, { "tuo", "沰" }, { "tuo", "沱" }, { "tuo", "砣" }, { "tuo", "碢" }, { "tuo", "箨" }, { "tuo", "籜" }, { "tuo", "紽" },
			{ "tuo", "脫" }, { "tuo", "脱" }, { "tuo", "莌" }, { "tuo", "蟺" }, { "tuo", "袉" }, { "tuo", "託" }, { "tuo", "跅" }, { "tuo", "跎" }, { "tuo", "酡" },
			{ "tuo", "铊" }, { "tuo", "陀" }, { "tuo", "飥" }, { "tuo", "馱" }, { "tuo", "駄" }, { "tuo", "駝" }, { "tuo", "騨" }, { "tuo", "驒" }, { "tuo", "驮" },
			{ "tuo", "驼" }, { "tuo", "魄" }, { "tuo", "魠" }, { "tuo", "鮀" }, { "tuo", "鴕" }, { "tuo", "鸵" }, { "tuo", "鼉" }, { "tuo", "鼍" }, { "tuo ba", "拖把" },
			{ "tuo bei", "驼背" }, { "tuo chan", "脱产" }, { "tuo che", "拖车" }, { "tuo chu qu", "拖出去" }, { "tuo dang", "妥当" }, { "tuo dao", "拖到" },
			{ "tuo di", "托蒂" }, { "tuo di", "拖地" }, { "tuo diao", "脱掉" }, { "tuo dong", "拖动" }, { "tuo fa", "脱发" }, { "tuo fu", "托付" }, { "tuo fu", "托福" },
			{ "tuo guan", "托管" }, { "tuo guan ren", "托管人" }, { "tuo guang", "脱光" }, { "tuo guang le", "脱光了" }, { "tuo huang", "拓荒" }, { "tuo ji", "脱机" },
			{ "tuo jie", "脱节" }, { "tuo kou er chu", "脱口而出" }, { "tuo kuan", "拓宽" }, { "tuo la", "拖拉" }, { "tuo la ji", "拖拉机" }, { "tuo le", "脱了" },
			{ "tuo lei", "拖累" }, { "tuo li", "脱离" }, { "tuo liu", "脱硫" }, { "tuo luo", "脱落" }, { "tuo luo", "陀螺" }, { "tuo ma si", "托马斯" },
			{ "tuo mao", "脱毛" }, { "tuo min", "脱敏" }, { "tuo mo", "唾沫" }, { "tuo ni", "托尼" }, { "tuo niao", "鸵鸟" }, { "tuo pan", "托盘" }, { "tuo pi", "脱皮" },
			{ "tuo pin", "脱贫" }, { "tuo pin zhi fu", "脱贫致富" }, { "tuo pu", "拓扑" }, { "tuo qi", "唾弃" }, { "tuo qi", "托起" }, { "tuo qian", "拖欠" },
			{ "tuo qu", "脱去" }, { "tuo ren", "托人" }, { "tuo shan", "妥善" }, { "tuo shan chu li", "妥善处理" }, { "tuo shan jie jue", "妥善解决" }, { "tuo shen", "脱身" },
			{ "tuo shou", "托收" }, { "tuo shou", "脱手" }, { "tuo shui", "脱水" }, { "tuo su", "脱俗" }, { "tuo ta", "拖沓" }, { "tuo tai huan gu", "脱胎换骨" },
			{ "tuo tuo", "脱脱" }, { "tuo xia", "脱下" }, { "tuo xian", "脱险" }, { "tuo xie", "妥协" }, { "tuo xie", "拖鞋" }, { "tuo yan", "拖延" }, { "tuo ye", "唾液" },
			{ "tuo yi", "脱衣" }, { "tuo yi fu", "脱衣服" }, { "tuo yi wu", "脱衣舞" }, { "tuo ying er chu", "脱颖而出" }, { "tuo yuan", "椭圆" },
			{ "tuo yuan xing", "椭圆形" }, { "tuo yun", "托运" }, { "tuo zhan", "拓展" }, { "tuo zhan xun lian", "拓展训练" }, { "tuo zhe", "托着" }, { "tuo zhe", "拖着" },
			{ "tuo zhuai", "拖拽" }, { "wa", "佤" }, { "wa", "哇" }, { "wa", "唲" }, { "wa", "嗢" }, { "wa", "娃" }, { "wa", "娲" }, { "wa", "媧" }, { "wa", "挖" },
			{ "wa", "洼" }, { "wa", "溛" }, { "wa", "漥" }, { "wa", "瓦" }, { "wa", "瓲" }, { "wa", "窊" }, { "wa", "窐" }, { "wa", "窪" }, { "wa", "腽" },
			{ "wa", "膃" }, { "wa", "蛙" }, { "wa", "袜" }, { "wa", "襪" }, { "wa", "韈" }, { "wa", "韎" }, { "wa chu", "挖出" }, { "wa dao", "挖到" },
			{ "wa di", "洼地" }, { "wa er", "娃儿" }, { "wa er", "瓦尔" }, { "wa ha ha", "娃哈哈" }, { "wa ha ha ha", "哇哈哈哈" }, { "wa jie", "瓦解" }, { "wa jue", "挖掘" },
			{ "wa jue ji", "挖掘机" }, { "wa kao", "哇靠" }, { "wa keng", "挖坑" }, { "wa ku", "挖苦" }, { "wa kuang", "挖矿" }, { "wa lun xi ya", "瓦伦西亚" },
			{ "wa pian", "瓦片" }, { "wa sai", "哇塞" }, { "wa si", "瓦斯" }, { "wa wa", "哇哇" }, { "wa wa", "娃娃" }, { "wa wa lian", "娃娃脸" }, { "wa zi", "娃子" },
			{ "wa zi", "袜子" }, { "wai", "咼" }, { "wai", "喎" }, { "wai", "外" }, { "wai", "崴" }, { "wai", "歪" }, { "wai", "瀤" }, { "wai bao", "外包" },
			{ "wai bao zhuang", "外包装" }, { "wai bi", "外币" }, { "wai bian", "外边" }, { "wai biao", "外表" }, { "wai bin", "外宾" }, { "wai bu", "外部" },
			{ "wai bu huan jing", "外部环境" }, { "wai ce", "外侧" }, { "wai ceng", "外层" }, { "wai chu", "外出" }, { "wai chu wu gong", "外出务工" } };
};
