package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN04 {
	public static String[][] pl = { { "bo", "亳" }, { "bo", "伯" }, { "bo", "僠" }, { "bo", "僰" }, { "bo", "剝" }, { "bo", "剥" }, { "bo", "勃" }, { "bo", "博" },
			{ "bo", "卜" }, { "bo", "啵" }, { "bo", "孛" }, { "bo", "嶓" }, { "bo", "帛" }, { "bo", "愽" }, { "bo", "懪" }, { "bo", "拨" }, { "bo", "挬" },
			{ "bo", "搏" }, { "bo", "撥" }, { "bo", "播" }, { "bo", "擘" }, { "bo", "柏" }, { "bo", "檗" }, { "bo", "欂" }, { "bo", "泊" }, { "bo", "波" },
			{ "bo", "浡" }, { "bo", "渤" }, { "bo", "犦" }, { "bo", "狛" }, { "bo", "玻" }, { "bo", "瓝" }, { "bo", "癶" }, { "bo", "礡" }, { "bo", "礴" },
			{ "bo", "秡" }, { "bo", "箔" }, { "bo", "簙" }, { "bo", "簸" }, { "bo", "糪" }, { "bo", "缽" }, { "bo", "胉" }, { "bo", "脖" }, { "bo", "膊" },
			{ "bo", "舶" }, { "bo", "菠" }, { "bo", "葧" }, { "bo", "蔔" }, { "bo", "薄" }, { "bo", "蘗" }, { "bo", "襮" }, { "bo", "詙" }, { "bo", "譒" },
			{ "bo", "跛" }, { "bo", "踣" }, { "bo", "蹳" }, { "bo", "郣" }, { "bo", "鈸" }, { "bo", "鉑" }, { "bo", "鉢" }, { "bo", "鋍" }, { "bo", "鎛" },
			{ "bo", "鑮" }, { "bo", "钵" }, { "bo", "钹" }, { "bo", "铂" }, { "bo", "餑" }, { "bo", "餺" }, { "bo", "饽" }, { "bo", "駁" }, { "bo", "駮" },
			{ "bo", "驳" }, { "bo", "魄" }, { "bo", "鱍" }, { "bo", "鵓" }, { "bo", "鹁" }, { "bo ai", "博爱" }, { "bo ba", "波霸" }, { "bo bao", "播报" },
			{ "bo bo", "伯伯" }, { "bo bo", "波波" }, { "bo cai", "博彩" }, { "bo cai", "菠菜" }, { "bo chang", "波长" }, { "bo chi", "驳斥" }, { "bo chu", "拨出" },
			{ "bo chu", "播出" }, { "bo da", "博大" }, { "bo da", "拨打" }, { "bo da jing shen", "博大精深" }, { "bo dao", "博导" }, { "bo dao", "波导" }, { "bo de", "博得" },
			{ "bo dong", "拨动" }, { "bo dong", "波动" }, { "bo dou", "搏斗" }, { "bo duan", "波段" }, { "bo duo", "剥夺" }, { "bo er", "波尔" }, { "bo er dun", "博尔顿" },
			{ "bo fang", "播放" }, { "bo fang ji", "播放机" }, { "bo fang lie biao", "播放列表" }, { "bo fang qi", "播放器" }, { "bo fu", "伯父" }, { "bo fu", "拨付" },
			{ "bo ge", "伯格" }, { "bo ge", "博格" }, { "bo hai", "渤海" }, { "bo hao", "拨号" }, { "bo he", "薄荷" }, { "bo hui", "博会" }, { "bo hui", "驳回" },
			{ "bo ji", "搏击" }, { "bo ji", "波及" }, { "bo jin", "铂金" }, { "bo jing", "脖颈" }, { "bo jue", "伯爵" }, { "bo kai", "拨开" }, { "bo ke", "博克" },
			{ "bo ke", "博客" }, { "bo ke", "播客" }, { "bo ke quan", "博客圈" }, { "bo ke qun", "博客群" }, { "bo ke shou ye", "博客首页" }, { "bo ke wang", "博客网" },
			{ "bo ke wang zhan", "博客网站" }, { "bo ke wen zhang", "博客文章" }, { "bo kuan", "拨款" }, { "bo la tu", "柏拉图" }, { "bo lan", "博览" }, { "bo lan", "波兰" },
			{ "bo lan", "波澜" }, { "bo lan bu jing", "波澜不惊" }, { "bo lan hui", "博览会" }, { "bo lan zhuang kuo", "波澜壮阔" }, { "bo lang", "波浪" }, { "bo le", "伯乐" },
			{ "bo li", "剥离" }, { "bo li", "波里" }, { "bo li", "玻璃" }, { "bo li bei", "玻璃杯" }, { "bo li chuang", "玻璃窗" }, { "bo li gang", "玻璃钢" },
			{ "bo li men", "玻璃门" }, { "bo li ping", "玻璃瓶" }, { "bo lin", "柏林" }, { "bo luo", "剥落" }, { "bo luo", "波罗" }, { "bo luo", "菠萝" },
			{ "bo ming han", "伯明翰" }, { "bo mo", "薄膜" }, { "bo mu", "伯母" }, { "bo nong", "拨弄" }, { "bo pi", "剥皮" }, { "bo qi", "勃起" }, { "bo qu", "博取" },
			{ "bo ruo", "薄弱" }, { "bo ruo huan jie", "薄弱环节" }, { "bo sha", "搏杀" }, { "bo shi", "博世" }, { "bo shi", "博士" }, { "bo shi", "博时" },
			{ "bo shi dun", "波士顿" }, { "bo shi hou", "博士后" }, { "bo shi lun wen", "博士论文" }, { "bo shi sheng", "博士生" }, { "bo shi xue wei", "博士学位" },
			{ "bo si", "波斯" }, { "bo tao", "波涛" }, { "bo tao xiong yong", "波涛汹涌" }, { "bo te", "波特" }, { "bo tong", "拨通" }, { "bo wei", "泊位" },
			{ "bo wen", "博文" }, { "bo wen", "波纹" }, { "bo wu guan", "博物馆" }, { "bo xi lai", "薄熙来" }, { "bo xing", "波形" }, { "bo xue", "剥削" },
			{ "bo xue", "博学" }, { "bo ya", "博雅" }, { "bo yi", "博弈" }, { "bo yin", "播音" }, { "bo yin", "波音" }, { "bo yin yuan", "播音员" }, { "bo you", "博友" },
			{ "bo zhe", "波折" }, { "bo zhong", "播种" }, { "bo zhong mian ji", "播种面积" }, { "bo zi", "脖子" }, { "bu", "不" }, { "bu", "佈" }, { "bu", "卜" },
			{ "bu", "卟" }, { "bu", "吥" }, { "bu", "咘" }, { "bu", "哺" }, { "bu", "埔" }, { "bu", "埠" }, { "bu", "堡" }, { "bu", "峬" }, { "bu", "布" },
			{ "bu", "怖" }, { "bu", "捕" }, { "bu", "晡" }, { "bu", "步" }, { "bu", "歩" }, { "bu", "瓿" }, { "bu", "篰" }, { "bu", "簿" }, { "bu", "蔀" },
			{ "bu", "补" }, { "bu", "補" }, { "bu", "誧" }, { "bu", "踄" }, { "bu", "轐" }, { "bu", "逋" }, { "bu", "部" }, { "bu", "醭" }, { "bu", "鈽" },
			{ "bu", "钚" }, { "bu", "钸" }, { "bu", "餔" }, { "bu", "鳪" }, { "bu", "鸔" }, { "bu ai", "不爱" }, { "bu ai ni", "不爱你" }, { "bu ai wo", "不爱我" },
			{ "bu an", "不安" }, { "bu an", "不按" }, { "bu ba", "不把" }, { "bu bai", "不败" }, { "bu ban", "不办" }, { "bu ban", "补办" }, { "bu bao", "不保" },
			{ "bu bao", "不包" }, { "bu bao", "不报" }, { "bu bao", "不抱" }, { "bu bao han", "不包含" }, { "bu bao zheng", "不保证" }, { "bu bei", "不被" },
			{ "bu bi", "不必" }, { "bu bi", "不比" }, { "bu bian", "不便" }, { "bu bian", "不变" }, { "bu bian de", "不变的" }, { "bu bing", "步兵" }, { "bu bu", "步步" },
			{ "bu bu", "补补" }, { "bu bu gao", "步步高" }, { "bu bu zhang", "部部长" }, { "bu cang", "补仓" }, { "bu ce", "不测" }, { "bu ceng", "不曾" },
			{ "bu cha", "不差" }, { "bu chang", "不常" }, { "bu chang", "不畅" }, { "bu chang", "不长" }, { "bu chang", "补偿" }, { "bu chang fei", "补偿费" },
			{ "bu chang jin", "补偿金" }, { "bu cheng", "不成" }, { "bu chi", "不吃" }, { "bu chi", "不迟" }, { "bu chi", "不齿" }, { "bu chong", "补充" },
			{ "bu chou", "不愁" }, { "bu chu", "不出" }, { "bu chu sheng", "不出声" }, { "bu chuan", "不穿" }, { "bu cun", "不存" }, { "bu cuo", "不错" },
			{ "bu cuo a", "不错啊" }, { "bu da", "不大" }, { "bu da", "不打" }, { "bu da", "不答" }, { "bu da bu xiao", "不大不小" }, { "bu da la gong", "布达拉宫" },
			{ "bu dai", "不带" }, { "bu dai", "不戴" }, { "bu dai", "布袋" }, { "bu dan", "不但" }, { "bu dan", "不单" }, { "bu dang", "不当" }, { "bu dao", "不倒" },
			{ "bu dao", "不到" }, { "bu dao de", "不道德" }, { "bu de", "不得" }, { "bu de bu", "不得不" }, { "bu de er zhi", "不得而知" }, { "bu de hao si", "不得好死" },
			{ "bu de qi jie", "不得其解" }, { "bu de shan zi", "不得擅自" }, { "bu de yi", "不得已" }, { "bu deng", "不等" }, { "bu di", "不低" }, { "bu di", "不敌" },
			{ "bu dian", "布点" }, { "bu dian ying", "部电影" }, { "bu diao", "不掉" }, { "bu diao", "步调" }, { "bu die", "不跌" }, { "bu ding", "不定" },
			{ "bu ding", "布丁" }, { "bu ding", "补丁" }, { "bu ding shi", "不定时" }, { "bu dong", "不动" }, { "bu dong", "不懂" }, { "bu dong chan", "不动产" },
			{ "bu dong le", "不动了" }, { "bu dong sheng se", "不动声色" }, { "bu dou", "布兜" }, { "bu du", "不读" }, { "bu duan", "不断" }, { "bu duan", "不短" },
			{ "bu duan chuang xin", "不断创新" }, { "bu duan fa zhan", "不断发展" }, { "bu duan geng xin", "不断更新" }, { "bu duan jia qiang", "不断加强" },
			{ "bu duan kuo da", "不断扩大" }, { "bu duan ti gao", "不断提高" }, { "bu duan wan shan", "不断完善" }, { "bu duan zeng jia", "不断增加" },
			{ "bu duan zeng qiang", "不断增强" }, { "bu dui", "不对" }, { "bu dui", "部队" }, { "bu dui jin", "不对劲" }, { "bu duo", "不多" }, { "bu e", "不饿" },
			{ "bu er", "不二" }, { "bu er", "布尔" }, { "bu fa", "不乏" }, { "bu fa", "不发" }, { "bu fa", "不法" }, { "bu fa", "步伐" }, { "bu fa", "补发" },
			{ "bu fa fen zi", "不法分子" }, { "bu fan", "不凡" }, { "bu fan", "不烦" }, { "bu fang", "不妨" }, { "bu fang", "不放" }, { "bu fei", "不菲" },
			{ "bu fen", "不分" }, { "bu fen", "部份" }, { "bu fen", "部分" }, { "bu fen di qu", "部分地区" }, { "bu fen nei rong", "部分内容" },
			{ "bu fen zu cheng", "部分组成" }, { "bu feng", "布冯" }, { "bu fu", "不复" }, { "bu fu", "不服" }, { "bu fu", "不符" }, { "bu fu", "不负" }, { "bu fu", "部副" },
			{ "bu fu cun zai", "不复存在" }, { "bu fu ze ren", "不负责任" }, { "bu gai", "不改" }, { "bu gai", "不该" }, { "bu gai", "补钙" }, { "bu gan", "不干" },
			{ "bu gan", "不敢" }, { "bu gan", "不甘" }, { "bu gan dang", "不敢当" }, { "bu gan jiao", "不干胶" }, { "bu gan xiang xin", "不敢相信" },
			{ "bu gan xing qu", "不感兴趣" }, { "bu gao", "不搞" }, { "bu gao", "不高" }, { "bu gei", "不给" }, { "bu gei", "补给" }, { "bu gen", "不跟" },
			{ "bu gong", "不公" }, { "bu gou", "不够" }, { "bu gu", "不顾" }, { "bu gu yi qie", "不顾一切" }, { "bu guai", "不乖" }, { "bu guai", "不怪" },
			{ "bu guan", "不关" }, { "bu guan", "不惯" }, { "bu guan", "不管" }, { "bu guan yong", "不管用" }, { "bu guan zen yang", "不管怎样" }, { "bu guang", "不光" },
			{ "bu gui", "不归" }, { "bu gui", "不贵" }, { "bu gui lu", "不归路" }, { "bu gui ze", "不规则" }, { "bu guo", "不过" }, { "bu guo ru ci", "不过如此" },
			{ "bu han", "不含" }, { "bu han er li", "不寒而栗" }, { "bu hao", "不好" }, { "bu hao guo", "不好过" }, { "bu hao ma", "不好吗" }, { "bu hao yi si", "不好意思" },
			{ "bu hao yong", "不好用" }, { "bu he", "不合" }, { "bu he", "不和" }, { "bu he", "不喝" }, { "bu he shi yi", "不合时宜" }, { "bu hei", "不黑" },
			{ "bu hua", "不花" }, { "bu huai", "不坏" }, { "bu huai hao yi", "不怀好意" }, { "bu huan", "不换" }, { "bu huan", "不还" }, { "bu huang", "不慌" },
			{ "bu hui", "不会" }, { "bu hui", "不回" }, { "bu hui", "不悔" }, { "bu hui ba", "不会吧" }, { "bu hui bian", "不会变" }, { "bu hui chu xian", "不会出现" },
			{ "bu hui shuo hua", "不会说话" }, { "bu hui wang ji", "不会忘记" }, { "bu hui yong", "不会用" }, { "bu huo", "不活" }, { "bu huo", "捕获" }, { "bu huo", "补货" },
			{ "bu ji", "不及" }, { "bu ji", "不急" }, { "bu ji", "不济" }, { "bu ji", "不羁" }, { "bu ji", "不计" }, { "bu ji", "布吉" }, { "bu ji", "补给" },
			{ "bu ji", "部级" }, { "bu ji de", "不记得" }, { "bu ji qi shu", "不计其数" }, { "bu jia", "不佳" }, { "bu jia", "不假" }, { "bu jia", "不加" },
			{ "bu jia", "不嫁" }, { "bu jia si suo", "不假思索" }, { "bu jian", "不减" }, { "bu jian", "不见" }, { "bu jian", "部件" }, { "bu jian de", "不见得" },
			{ "bu jiang", "不讲" }, { "bu jiang", "不降" }, { "bu jiao", "不交" }, { "bu jiao", "不叫" }, { "bu jiao", "补交" }, { "bu jiao", "补缴" }, { "bu jie", "不接" },
			{ "bu jie", "不洁" }, { "bu jie", "不解" }, { "bu jin", "不仅" }, { "bu jin", "不尽" }, { "bu jin", "不禁" }, { "bu jin", "不进" }, { "bu jin", "步进" },
			{ "bu jin bu man", "不紧不慢" }, { "bu jin jin", "不仅仅" }, { "bu jin ru ci", "不仅如此" }, { "bu jing", "不敬" }, { "bu jing", "不经" }, { "bu jing", "布景" },
			{ "bu jing li", "部经理" }, { "bu jing qi", "不景气" }, { "bu jing yi", "不经意" }, { "bu jing yi jian", "不经意间" }, { "bu jiu", "不久" }, { "bu jiu", "不就" },
			{ "bu jiu", "不救" }, { "bu jiu", "补救" }, { "bu jiu qian", "不久前" }, { "bu ju", "不具" }, { "bu ju", "不惧" }, { "bu ju", "布局" }, { "bu jue", "不绝" },
			{ "bu jue", "不觉" }, { "bu jue yu er", "不绝于耳" }, { "bu jun", "不均" }, { "bu ka", "不卡" }, { "bu kai", "不开" }, { "bu kan", "不堪" }, { "bu kan", "不看" },
			{ "bu kan hui shou", "不堪回首" }, { "bu kan she xiang", "不堪设想" }, { "bu kan yi ji", "不堪一击" }, { "bu kan zhong fu", "不堪重负" }, { "bu kao", "不靠" },
			{ "bu kao", "补考" }, { "bu ke", "不可" }, { "bu ke", "补课" }, { "bu ke bi mian", "不可避免" }, { "bu ke duo de", "不可多得" }, { "bu ke fen ge", "不可分割" },
			{ "bu ke gao ren", "不可告人" }, { "bu ke gu liang", "不可估量" }, { "bu ke hu shi", "不可忽视" }, { "bu ke huo que", "不可或缺" }, { "bu ke kai jiao", "不可开交" },
			{ "bu ke kang ju", "不可抗拒" }, { "bu ke kang li", "不可抗力" }, { "bu ke li yu", "不可理喻" }, { "bu ke neng de", "不可能的" }, { "bu ke ni zhuan", "不可逆转" },
			{ "bu ke que shao", "不可缺少" }, { "bu ke si yi", "不可思议" }, { "bu ke ti dai", "不可替代" }, { "bu ke xiang xiang", "不可想象" }, { "bu ke yi shi", "不可一世" },
			{ "bu ken", "不肯" }, { "bu kou", "不扣" }, { "bu ku", "不哭" }, { "bu kuai", "不快" }, { "bu kuai le", "不快乐" }, { "bu kui", "不亏" }, { "bu kui", "不愧" },
			{ "bu la", "不拉" }, { "bu la", "布拉" }, { "bu la ge", "布拉格" }, { "bu lai", "不来" }, { "bu lai", "不赖" }, { "bu lai er", "布莱尔" },
			{ "bu lai mei", "不来梅" }, { "bu lan ni", "布兰妮" }, { "bu lang", "布朗" }, { "bu lao", "不老" }, { "bu lao", "捕捞" }, { "bu le", "不了" },
			{ "bu lei", "不累" }, { "bu lei", "布雷" }, { "bu leng", "不冷" }, { "bu li", "不利" }, { "bu li", "不力" }, { "bu li", "不理" }, { "bu li", "不离" },
			{ "bu li bu qi", "不离不弃" }, { "bu li wo", "不理我" }, { "bu li yin su", "不利因素" }, { "bu li ying xiang", "不利影响" }, { "bu lian", "不练" },
			{ "bu liang", "不亮" }, { "bu liang", "不良" }, { "bu liang dai kuan", "不良贷款" }, { "bu liang fan ying", "不良反应" }, { "bu liang ying xiang", "不良影响" },
			{ "bu liang zi chan", "不良资产" }, { "bu liao", "不了" }, { "bu liao", "不料" }, { "bu liao", "布料" }, { "bu liao le", "不了了" },
			{ "bu liao liao zhi", "不了了之" }, { "bu lin", "不吝" }, { "bu ling", "不灵" }, { "bu liu", "不留" }, { "bu lou", "不漏" }, { "bu lu", "不露" },
			{ "bu lu", "布鲁" }, { "bu lu", "补录" }, { "bu lu sai er", "布鲁塞尔" }, { "bu lu si", "布鲁斯" }, { "bu luan", "不乱" }, { "bu lun", "不论" },
			{ "bu lun bu lei", "不伦不类" }, { "bu lun shi", "不论是" }, { "bu luo", "不落" }, { "bu luo", "部落" }, { "bu luo ge", "部落格" }, { "bu lv", "步履" },
			{ "bu mai", "不买" }, { "bu mai", "不卖" }, { "bu man", "不慢" }, { "bu man", "不满" }, { "bu man", "布满" }, { "bu mang", "不忙" }, { "bu mei", "不美" },
			{ "bu men", "部门" }, { "bu men jing li", "部门经理" }, { "bu mian", "不免" }, { "bu miao", "不妙" }, { "bu mie", "不灭" }, { "bu ming", "不明" },
			{ "bu ming bu bai", "不明不白" }, { "bu mou er he", "不谋而合" }, { "bu na", "不拿" }, { "bu nai", "不耐" }, { "bu nai fan", "不耐烦" }, { "bu nan", "不难" },
			{ "bu neng", "不能" }, { "bu neng chao guo", "不能超过" }, { "bu neng cheng shou", "不能承受" }, { "bu neng chi", "不能吃" }, { "bu neng dong", "不能动" },
			{ "bu neng jie shou", "不能接受" }, { "bu neng kan", "不能看" }, { "bu neng que ding", "不能确定" }, { "bu neng rong ren", "不能容忍" },
			{ "bu neng shang wang", "不能上网" }, { "bu neng shi yong", "不能使用" }, { "bu neng tong guo", "不能通过" }, { "bu neng wang ji", "不能忘记" },
			{ "bu neng yong", "不能用" }, { "bu neng zheng chang", "不能正常" }, { "bu neng zi ba", "不能自拔" }, { "bu neng zuo", "不能做" }, { "bu pa", "不怕" },
			{ "bu pa bu pa", "不怕不怕" }, { "bu pang", "不胖" }, { "bu pao", "不跑" }, { "bu pei", "不赔" }, { "bu pei", "不配" }, { "bu peng", "不碰" },
			{ "bu pi pei", "不匹配" }, { "bu pian yi", "不便宜" }, { "bu pin", "补品" }, { "bu ping", "不平" }, { "bu po", "不破" }, { "bu qi", "不起" }, { "bu qi", "不齐" },
			{ "bu qi", "补气" }, { "bu qi", "补齐" }, { "bu qi yan", "不起眼" }, { "bu qi zuo yong", "不起作用" }, { "bu qian", "不浅" }, { "bu qiang", "不强" },
			{ "bu qiang", "步枪" }, { "bu qiao", "不巧" }, { "bu qie shi ji", "不切实际" }, { "bu qing", "不清" }, { "bu qing", "不轻" }, { "bu qiu", "不求" },
			{ "bu qu", "不去" }, { "bu qu", "不屈" }, { "bu qu bu nao", "不屈不挠" }, { "bu quan", "不全" }, { "bu que", "不缺" }, { "bu que ding xing", "不确定性" },
			{ "bu ran", "不然" }, { "bu rang", "不让" }, { "bu re", "不热" }, { "bu ren", "不忍" }, { "bu ren", "不认" }, { "bu rong", "不容" },
			{ "bu rong hu shi", "不容忽视" }, { "bu rong le guan", "不容乐观" }, { "bu rong zhi yi", "不容置疑" }, { "bu ru", "不入" }, { "bu ru", "不如" }, { "bu ru", "哺乳" },
			{ "bu ru", "步入" }, { "bu ru dong wu", "哺乳动物" }, { "bu ru qi", "哺乳期" }, { "bu ru shuo", "不如说" }, { "bu san", "不散" }, { "bu sha", "不傻" },
			{ "bu sha", "不杀" }, { "bu sha", "捕杀" }, { "bu shan", "不善" }, { "bu shang", "不上" }, { "bu shang", "不伤" }, { "bu shang", "补上" }, { "bu shao", "不少" },
			{ "bu shao ren", "不少人" }, { "bu she", "不舍" }, { "bu she", "不设" }, { "bu shen", "不慎" }, { "bu shen", "不深" }, { "bu shen", "不甚" },
			{ "bu shen", "补肾" }, { "bu sheng", "不生" }, { "bu sheng", "不胜" }, { "bu shi", "不失" }, { "bu shi", "不实" }, { "bu shi", "不时" }, { "bu shi", "不是" },
			{ "bu shi", "不识" }, { "bu shi", "不适" }, { "bu shi", "布什" }, { "bu shi", "布施" }, { "bu shi", "捕食" }, { "bu shi bie ren", "不是别人" },
			{ "bu shi bu", "不是不" }, { "bu shi hen", "不是很" }, { "bu shi hen hao", "不是很好" }, { "bu shi ma", "不是吗" }, { "bu shi mei you", "不是没有" },
			{ "bu shi ni", "不是你" }, { "bu shi shi ji", "不失时机" }, { "bu shi shuo", "不是说" }, { "bu shi wei", "不失为" }, { "bu shi wo", "不是我" },
			{ "bu shi yi ge", "不是一个" }, { "bu shi zi wei", "不是滋味" }, { "bu shi zong tong", "布什总统" }, { "bu shou", "不受" }, { "bu shou", "不守" },
			{ "bu shou", "不收" }, { "bu shu", "不熟" }, { "bu shu", "不输" }, { "bu shu", "部属" }, { "bu shu", "部署" }, { "bu shuai", "不帅" }, { "bu shuai", "不衰" },
			{ "bu shuang", "不爽" }, { "bu shui", "不睡" }, { "bu shui", "补水" }, { "bu shui jiao", "不睡觉" }, { "bu shun", "不顺" }, { "bu shuo", "不说" },
			{ "bu si", "不似" }, { "bu si", "不思" }, { "bu si", "不死" }, { "bu si jin qu", "不思进取" }, { "bu si xin", "不死心" }, { "bu song", "不送" },
			{ "bu su", "不俗" }, { "bu suan", "不算" }, { "bu suan shen me", "不算什么" }, { "bu tai", "不太" }, { "bu tai hao", "不太好" }, { "bu tan", "不谈" },
			{ "bu teng", "不疼" }, { "bu ti", "不提" }, { "bu tiao", "不调" }, { "bu tiao", "不跳" }, { "bu tie", "补贴" }, { "bu ting", "不停" }, { "bu ting", "不听" },
			{ "bu ting de", "不停的" }, { "bu tong", "不同" }, { "bu tong", "不痛" }, { "bu tong", "不通" }, { "bu tong ceng ci", "不同层次" },
			{ "bu tong cheng du", "不同程度" }, { "bu tong di qu", "不同地区" }, { "bu tong fan xiang", "不同凡响" }, { "bu tong guo jia", "不同国家" },
			{ "bu tong jie duan", "不同阶段" }, { "bu tong lei xing", "不同类型" }, { "bu tong shi qi", "不同时期" }, { "bu tong xun chang", "不同寻常" },
			{ "bu tong yan se", "不同颜色" }, { "bu tong yi jian", "不同意见" }, { "bu tong zhi chu", "不同之处" }, { "bu tou", "不透" }, { "bu tui", "不退" },
			{ "bu tuo", "不妥" }, { "bu tuo", "不脱" }, { "bu tuo", "布托" }, { "bu wai hu", "不外乎" }, { "bu wan", "不完" }, { "bu wan", "不晚" }, { "bu wan", "不玩" },
			{ "bu wan mei", "不完美" }, { "bu wang", "不忘" }, { "bu wang", "不枉" }, { "bu wei", "不为" }, { "bu wei", "不畏" }, { "bu wei", "部位" }, { "bu wei", "部委" },
			{ "bu wei ren zhi", "不为人知" }, { "bu wen", "不稳" }, { "bu wen", "不问" }, { "bu wen bu wen", "不闻不问" }, { "bu wu", "不无" }, { "bu wu", "不误" },
			{ "bu wu zheng ye", "不务正业" }, { "bu xi", "不喜" }, { "bu xi", "不息" }, { "bu xi", "不惜" }, { "bu xi", "不洗" }, { "bu xi", "补习" },
			{ "bu xi ban", "补习班" }, { "bu xia", "不下" }, { "bu xia", "部下" }, { "bu xia yu", "不下雨" }, { "bu xian", "不嫌" }, { "bu xian", "不限" },
			{ "bu xian", "布线" }, { "bu xian shi", "不显示" }, { "bu xiang", "不像" }, { "bu xiang", "不想" }, { "bu xiang", "不相" }, { "bu xiang", "不祥" },
			{ "bu xiang", "不详" }, { "bu xiang", "不象" }, { "bu xiang shang xia", "不相上下" }, { "bu xiang yao", "不想要" }, { "bu xiang zuo", "不想做" },
			{ "bu xiao", "不孝" }, { "bu xiao", "不小" }, { "bu xiao", "不笑" }, { "bu xiao de", "不小的" }, { "bu xie", "不写" }, { "bu xie", "不屑" }, { "bu xie", "不懈" },
			{ "bu xie", "不谢" }, { "bu xie", "布鞋" }, { "bu xie nu li", "不懈努力" }, { "bu xie yi gu", "不屑一顾" }, { "bu xin", "不信" }, { "bu xing", "不幸" },
			{ "bu xing", "不行" }, { "bu xing", "不醒" }, { "bu xing", "步行" }, { "bu xing fu", "不幸福" }, { "bu xing jie", "步行街" }, { "bu xiu", "不休" },
			{ "bu xiu", "不朽" }, { "bu xiu gang", "不锈钢" }, { "bu xu", "不许" }, { "bu xu", "不需" }, { "bu xu", "不须" }, { "bu xuan", "不选" }, { "bu xue", "不学" },
			{ "bu xue", "补血" }, { "bu ya", "不雅" }, { "bu yan", "不严" }, { "bu yan", "不厌" }, { "bu yan", "不言" }, { "bu yan er yu", "不言而喻" },
			{ "bu yan qi fan", "不厌其烦" }, { "bu yao", "不要" }, { "bu yao cuo guo", "不要错过" }, { "bu yao jin", "不要紧" }, { "bu yao lian", "不要脸" },
			{ "bu yao qian", "不要钱" }, { "bu yao qing yi", "不要轻易" }, { "bu yao qu", "不要去" }, { "bu yao tai", "不要太" }, { "bu yao wang ji", "不要忘记" },
			{ "bu yao wen", "不要问" }, { "bu yao yi wei", "不要以为" }, { "bu yao yong", "不要用" }, { "bu yao zuo", "不要做" }, { "bu ye", "不也" }, { "bu yi", "不一" },
			{ "bu yi", "不以" }, { "bu yi", "不宜" }, { "bu yi", "不已" }, { "bu yi", "不易" }, { "bu yi", "布艺" }, { "bu yi", "布衣" }, { "bu yi bu rao", "不依不饶" },
			{ "bu yi hui", "不一会" }, { "bu yi hui er", "不一会儿" }, { "bu yi le hu", "不亦乐乎" }, { "bu yi wei ran", "不以为然" }, { "bu yi yu li", "不遗余力" },
			{ "bu ying", "不应" }, { "bu ying", "不赢" }, { "bu yong", "不用" }, { "bu yong dan xin", "不用担心" }, { "bu yong ke qi", "不用客气" },
			{ "bu yong zhu ce", "不用注册" }, { "bu you", "不由" }, { "bu you de", "不由得" }, { "bu you zi zhu", "不由自主" }, { "bu yu", "不予" }, { "bu yu", "不育" },
			{ "bu yu", "不语" }, { "bu yu", "哺育" }, { "bu yu", "捕鱼" }, { "bu yuan", "不愿" }, { "bu yuan", "不远" }, { "bu yuan chu", "不远处" }, { "bu yue", "不悦" },
			{ "bu yue er tong", "不约而同" }, { "bu yun", "不孕" }, { "bu yun bu yu", "不孕不育" }, { "bu yun zheng", "不孕症" }, { "bu zai", "不再" }, { "bu zai", "不在" },
			{ "bu zai hu", "不在乎" }, { "bu zai hua xia", "不在话下" }, { "bu zai shao shu", "不在少数" }, { "bu zai xian", "不在线" }, { "bu zao", "不早" },
			{ "bu ze shou duan", "不择手段" }, { "bu zen me yang", "不怎么样" }, { "bu zhan", "不占" }, { "bu zhan", "不沾" }, { "bu zhan", "布展" }, { "bu zhang", "不涨" },
			{ "bu zhang", "不长" }, { "bu zhang", "补涨" }, { "bu zhang", "部长" }, { "bu zhao", "不找" }, { "bu zhao", "不着" }, { "bu zhe bu kou", "不折不扣" },
			{ "bu zhen", "不振" }, { "bu zheng", "不争" }, { "bu zheng", "不正" }, { "bu zheng zhi feng", "不正之风" }, { "bu zhi", "不值" }, { "bu zhi", "不只" },
			{ "bu zhi", "不支" }, { "bu zhi", "不止" }, { "bu zhi", "不治" }, { "bu zhi", "不知" }, { "bu zhi", "不致" }, { "bu zhi", "布置" },
			{ "bu zhi bu jue", "不知不觉" }, { "bu zhi ke fou", "不置可否" }, { "bu zhi suo cuo", "不知所措" }, { "bu zhi suo yun", "不知所云" }, { "bu zhi yi ci", "不止一次" },
			{ "bu zhi yu", "不至于" }, { "bu zhong", "不中" }, { "bu zhong", "不忠" }, { "bu zhong", "不重" }, { "bu zhou", "步骤" }, { "bu zhu", "不住" },
			{ "bu zhu", "补助" }, { "bu zhu ren", "部主任" }, { "bu zhuan", "不赚" }, { "bu zhuan", "不转" }, { "bu zhuang", "不装" }, { "bu zhun", "不准" },
			{ "bu zhuo", "捕捉" }, { "bu zi", "步子" }, { "bu zi ran", "不自然" }, { "bu zong jing li", "部总经理" }, { "bu zou", "不走" }, { "bu zu", "不足" },
			{ "bu zu", "补足" }, { "bu zu", "部族" }, { "bu zu wei qi", "不足为奇" }, { "bu zu zhi chu", "不足之处" }, { "bu zuo", "不作" }, { "bu zuo", "不做" },
			{ "bu zuo wei", "不作为" }, { "ca", "嚓" }, { "ca", "拆" }, { "ca", "擦" }, { "ca", "礤" }, { "ca", "礸" }, { "ca bian qiu", "擦边球" }, { "ca ca", "擦擦" },
			{ "ca diao", "擦掉" }, { "ca gan", "擦干" }, { "ca han", "擦汗" }, { "ca jian er guo", "擦肩而过" }, { "ca le", "擦了" }, { "ca liang", "擦亮" },
			{ "ca qu", "擦去" }, { "ca shen er guo", "擦身而过" }, { "ca shi", "擦拭" }, { "ca xi", "擦洗" }, { "ca zhe", "擦着" }, { "cai", "偲" }, { "cai", "埰" },
			{ "cai", "婇" }, { "cai", "寀" }, { "cai", "彩" }, { "cai", "戝" }, { "cai", "才" }, { "cai", "採" }, { "cai", "材" }, { "cai", "棌" }, { "cai", "猜" },
			{ "cai", "睬" }, { "cai", "綵" }, { "cai", "縩" }, { "cai", "菜" }, { "cai", "蔡" }, { "cai", "裁" }, { "cai", "財" }, { "cai", "财" }, { "cai", "跴" },
			{ "cai", "踩" }, { "cai", "采" }, { "cai ba", "才把" }, { "cai bao", "财宝" }, { "cai bao", "财报" }, { "cai bei", "才被" }, { "cai bian", "采编" },
			{ "cai bu", "才不" }, { "cai bu hui", "才不会" }, { "cai cai", "猜猜" }, { "cai cai", "菜菜" }, { "cai cai", "踩踩" }, { "cai ce", "猜测" },
			{ "cai chan", "财产" }, { "cai chan quan", "财产权" }, { "cai chan sun shi", "财产损失" }, { "cai chang", "菜场" }, { "cai chu", "猜出" }, { "cai cong", "才从" },
			{ "cai cuo", "猜错" }, { "cai da", "财大" }, { "cai dan", "菜单" }, { "cai dan lan", "菜单栏" }, { "cai dan zhong", "菜单中" }, { "cai dao", "才到" },
			{ "cai dao", "猜到" }, { "cai dao", "菜刀" }, { "cai dao", "踩到" }, { "cai de", "才得" }, { "cai di", "菜地" }, { "cai dian", "彩电" }, { "cai ding", "裁定" },
			{ "cai dui", "才对" }, { "cai dui", "猜对" }, { "cai fa", "采伐" }, { "cai fa xian", "才发现" }, { "cai fang", "采访" }, { "cai feng", "裁缝" },
			{ "cai feng", "采风" }, { "cai fu", "财富" }, { "cai fu tong", "财付通" } };
};
