package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN41 {
	public static String[][] pl = { { "shang tu", "上图" }, { "shang wan", "上万" }, { "shang wang", "上网" }, { "shang wang", "伤亡" }, { "shang wang ka", "上网卡" },
			{ "shang wang shi", "上网时" }, { "shang wang shi jian", "上网时间" }, { "shang wei", "上位" }, { "shang wei", "上尉" }, { "shang wei", "尚未" },
			{ "shang wen", "上文" }, { "shang wu", "上午" }, { "shang wu", "商务" }, { "shang wu", "尚无" }, { "shang wu bu", "商务部" }, { "shang wu che", "商务车" },
			{ "shang wu ju", "商务局" }, { "shang wu ren shi", "商务人士" }, { "shang wu ting", "商务厅" }, { "shang wu zhong xin", "商务中心" }, { "shang xi", "赏析" },
			{ "shang xia", "上下" }, { "shang xia ban", "上下班" }, { "shang xia wen", "上下文" }, { "shang xia you", "上下游" }, { "shang xian", "上线" },
			{ "shang xian", "上限" }, { "shang xiao", "上校" }, { "shang xie", "上写" }, { "shang xin", "上心" }, { "shang xin", "伤心" },
			{ "shang xin yue mu", "赏心悦目" }, { "shang xing", "上行" }, { "shang xing qi", "上星期" }, { "shang xu", "尚需" }, { "shang xue", "上学" },
			{ "shang xue yuan", "商学院" }, { "shang xun", "上旬" }, { "shang yan", "上演" }, { "shang yang", "上扬" }, { "shang ye", "上也" }, { "shang ye", "商业" },
			{ "shang ye di chan", "商业地产" }, { "shang ye gong si", "商业公司" }, { "shang ye hua", "商业化" }, { "shang ye hui lu", "商业贿赂" },
			{ "shang ye huo dong", "商业活动" }, { "shang ye jia zhi", "商业价值" }, { "shang ye jie", "商业街" }, { "shang ye mi mi", "商业秘密" },
			{ "shang ye mo shi", "商业模式" }, { "shang ye pian", "商业片" }, { "shang ye qi ye", "商业企业" }, { "shang ye qu", "商业区" }, { "shang ye xing", "商业性" },
			{ "shang ye yin hang", "商业银行" }, { "shang ye yong tu", "商业用途" }, { "shang ye zhong xin", "商业中心" }, { "shang yi", "上一" }, { "shang yi", "上亿" },
			{ "shang yi", "上衣" }, { "shang yi", "商议" }, { "shang yi ceng", "上一层" }, { "shang yi ci", "上一次" }, { "shang yi nian", "上一年" },
			{ "shang yi pian", "上一篇" }, { "shang yi ye", "上一页" }, { "shang yin", "上瘾" }, { "shang ying", "上映" }, { "shang yong", "商用" },
			{ "shang yong che", "商用车" }, { "shang you", "上有" }, { "shang you", "上游" }, { "shang you", "商友" }, { "shang you", "尚有" }, { "shang yu", "上虞" },
			{ "shang yu", "伤愈" }, { "shang yuan", "伤员" }, { "shang yue", "上月" }, { "shang yue", "赏月" }, { "shang zai", "上载" }, { "shang zai", "尚在" },
			{ "shang zhan", "上站" }, { "shang zhan", "商战" }, { "shang zhang", "上涨" }, { "shang zhe", "伤者" }, { "shang zhen", "上阵" }, { "shang zheng", "上证" },
			{ "shang zheng suo", "上证所" }, { "shang zheng zhi shu", "上证指数" }, { "shang zhi", "上肢" }, { "shang zhi", "上至" }, { "shang zhou", "上周" },
			{ "shang zhou mo", "上周末" }, { "shang zhou si", "上周四" }, { "shang zhuang", "上装" }, { "shang zhuo", "上桌" }, { "shang zuo", "上做" }, { "shao", "劭" },
			{ "shao", "勺" }, { "shao", "卲" }, { "shao", "召" }, { "shao", "哨" }, { "shao", "少" }, { "shao", "弰" }, { "shao", "捎" }, { "shao", "旓" },
			{ "shao", "杓" }, { "shao", "梢" }, { "shao", "潲" }, { "shao", "烧" }, { "shao", "焼" }, { "shao", "燒" }, { "shao", "玿" }, { "shao", "稍" },
			{ "shao", "筲" }, { "shao", "紹" }, { "shao", "绍" }, { "shao", "艄" }, { "shao", "芍" }, { "shao", "苕" }, { "shao", "蕱" }, { "shao", "蛸" },
			{ "shao", "袑" }, { "shao", "輎" }, { "shao", "邵" }, { "shao", "鞘" }, { "shao", "韶" }, { "shao", "髾" }, { "shao", "鮹" }, { "shao bing", "哨兵" },
			{ "shao bing", "烧饼" }, { "shao bu fen", "少部分" }, { "shao bu liao", "少不了" }, { "shao cai", "烧菜" }, { "shao cheng", "烧成" }, { "shao chi", "少吃" },
			{ "shao da", "稍大" }, { "shao de", "烧得" }, { "shao deng", "稍等" }, { "shao dian", "少点" }, { "shao diao", "烧掉" }, { "shao er", "少儿" },
			{ "shao fan", "烧饭" }, { "shao fu", "少妇" }, { "shao gao", "稍高" }, { "shao guan", "韶关" }, { "shao hou", "稍后" }, { "shao huai", "烧坏" },
			{ "shao hui", "烧毁" }, { "shao ji", "烧鸡" }, { "shao jia", "稍加" }, { "shao jia yi", "邵佳一" }, { "shao jian", "少见" }, { "shao jiang", "少将" },
			{ "shao jiao", "烧焦" }, { "shao jie", "烧结" }, { "shao kai", "烧开" }, { "shao kao", "烧烤" }, { "shao lai", "少来" }, { "shao liang", "少量" },
			{ "shao lin", "少林" }, { "shao lin si", "少林寺" }, { "shao lu", "烧录" }, { "shao nan", "少男" }, { "shao nan shao nv", "少男少女" }, { "shao nian", "少年" },
			{ "shao nian er tong", "少年儿童" }, { "shao nv", "少女" }, { "shao qian", "烧钱" }, { "shao re", "烧热" }, { "shao shan", "韶山" }, { "shao shang", "烧伤" },
			{ "shao shao", "少少" }, { "shao shao", "稍稍" }, { "shao shu", "少数" }, { "shao shu min zu", "少数民族" }, { "shao shu ren", "少数人" },
			{ "shao shui", "烧水" }, { "shao shuo", "少说" }, { "shao si", "烧死" }, { "shao wei", "稍微" }, { "shao xian", "稍显" }, { "shao xian dui", "少先队" },
			{ "shao xiang", "烧香" }, { "shao xiao", "少校" }, { "shao xie", "少些" }, { "shao xing", "绍兴" }, { "shao xing shi", "绍兴市" }, { "shao xu", "少许" },
			{ "shao yang", "邵阳" }, { "shao yao", "芍药" }, { "shao ye", "少爷" }, { "shao yi dian", "少一点" }, { "shao yong", "少用" }, { "shao you", "少有" },
			{ "shao you", "稍有" }, { "shao yu", "少于" }, { "shao ze", "少则" }, { "shao zhi", "烧制" }, { "shao zhi", "烧纸" }, { "shao zi", "勺子" },
			{ "shao zuo", "稍作" }, { "she", "佘" }, { "she", "厍" }, { "she", "厙" }, { "she", "奢" }, { "she", "射" }, { "she", "慑" }, { "she", "慴" },
			{ "she", "懾" }, { "she", "折" }, { "she", "挕" }, { "she", "捨" }, { "she", "揲" }, { "she", "摄" }, { "she", "攝" }, { "she", "檨" }, { "she", "歙" },
			{ "she", "涉" }, { "she", "涻" }, { "she", "渉" }, { "she", "滠" }, { "she", "猞" }, { "she", "畲" }, { "she", "社" }, { "she", "舌" }, { "she", "舍" },
			{ "she", "舎" }, { "she", "蔎" }, { "she", "蛇" }, { "she", "蠂" }, { "she", "設" }, { "she", "设" }, { "she", "賒" }, { "she", "赊" }, { "she", "赦" },
			{ "she", "輋" }, { "she", "闍" }, { "she", "韘" }, { "she", "騇" }, { "she", "麝" }, { "she an", "涉案" }, { "she bao", "社保" },
			{ "she bao ji jin", "社保基金" }, { "she bei", "设备" }, { "she bu de", "舍不得" }, { "she cheng", "射程" }, { "she cheng", "设成" }, { "she chi", "奢侈" },
			{ "she chi pin", "奢侈品" }, { "she chu", "射出" }, { "she de", "舍得" }, { "she diao", "射雕" }, { "she ding", "设定" }, { "she fa", "设法" },
			{ "she fang", "设防" }, { "she fu qin ke", "舍甫琴科" }, { "she hua", "奢华" }, { "she hui", "社会" }, { "she hui bao xian", "社会保险" },
			{ "she hui bao zhang", "社会保障" }, { "she hui di wei", "社会地位" }, { "she hui fa zhan", "社会发展" }, { "she hui feng qi", "社会风气" },
			{ "she hui fu li", "社会福利" }, { "she hui fu wu", "社会服务" }, { "she hui ge jie", "社会各界" }, { "she hui gong ping", "社会公平" },
			{ "she hui gong zhong", "社会公众" }, { "she hui gong zuo", "社会工作" }, { "she hui guan li", "社会管理" }, { "she hui guan xi", "社会关系" },
			{ "she hui he xie", "社会和谐" }, { "she hui hua", "社会化" }, { "she hui huan jing", "社会环境" }, { "she hui huo dong", "社会活动" },
			{ "she hui jie ceng", "社会阶层" }, { "she hui jie gou", "社会结构" }, { "she hui jin bu", "社会进步" }, { "she hui jing ji", "社会经济" },
			{ "she hui jiu zhu", "社会救助" }, { "she hui ke xue", "社会科学" }, { "she hui li liang", "社会力量" }, { "she hui mao dun", "社会矛盾" },
			{ "she hui sheng huo", "社会生活" }, { "she hui shi jian", "社会实践" }, { "she hui shi ye", "社会事业" }, { "she hui tuan ti", "社会团体" },
			{ "she hui wen ding", "社会稳定" }, { "she hui wen hua", "社会文化" }, { "she hui wen ti", "社会问题" }, { "she hui xian xiang", "社会现象" },
			{ "she hui xiao yi", "社会效益" }, { "she hui xing", "社会性" }, { "she hui xue", "社会学" }, { "she hui xue jia", "社会学家" },
			{ "she hui ying xiang", "社会影响" }, { "she hui ze ren", "社会责任" }, { "she hui zhi an", "社会治安" }, { "she hui zhi du", "社会制度" },
			{ "she hui zhi xu", "社会秩序" }, { "she hui zhu yi", "社会主义" }, { "she hui zi yuan", "社会资源" }, { "she hui zu zhi", "社会组织" }, { "she ji", "射击" },
			{ "she ji", "涉及" }, { "she ji", "设计" }, { "she ji da sai", "设计大赛" }, { "she ji dan wei", "设计单位" }, { "she ji fang an", "设计方案" },
			{ "she ji fang fa", "设计方法" }, { "she ji feng ge", "设计风格" }, { "she ji gong si", "设计公司" }, { "she ji li nian", "设计理念" },
			{ "she ji mo shi", "设计模式" }, { "she ji ren yuan", "设计人员" }, { "she ji shi", "设计师" }, { "she ji tu", "设计图" }, { "she ji yao qiu", "设计要求" },
			{ "she ji yuan", "设计院" }, { "she ji zhe", "设计者" }, { "she ji zhi zuo", "设计制作" }, { "she jian", "射箭" }, { "she jian", "舌尖" }, { "she jiao", "社交" },
			{ "she jing", "射精" }, { "she ke", "社科" }, { "she ke yuan", "社科院" }, { "she kou", "蛇口" }, { "she li", "舍利" }, { "she li", "设立" },
			{ "she lie", "涉猎" }, { "she lun", "社论" }, { "she men", "射门" }, { "she mian", "赦免" }, { "she ming", "社名" }, { "she nong", "涉农" },
			{ "she pin", "射频" }, { "she qi", "舍弃" }, { "she qiu", "奢求" }, { "she qu", "摄取" }, { "she qu", "社区" }, { "she qu", "设区" },
			{ "she qu fu wu", "社区服务" }, { "she qu jian she", "社区建设" }, { "she qu ju min", "社区居民" }, { "she qu wang", "社区网" }, { "she qun", "社群" },
			{ "she ru", "摄入" }, { "she ru liang", "摄入量" }, { "she sha", "射杀" }, { "she shen", "舍身" }, { "she shen chu di", "设身处地" }, { "she shi", "设施" },
			{ "she shi du", "摄氏度" }, { "she shi jian she", "设施建设" }, { "she shi man", "佘诗曼" }, { "she shou", "射手" }, { "she shou zuo", "射手座" },
			{ "she tai", "舌苔" }, { "she tou", "舌头" }, { "she tuan", "社团" }, { "she wa", "舍瓦" }, { "she wai", "涉外" }, { "she wang", "奢望" }, { "she wei", "设为" },
			{ "she xia", "设下" }, { "she xian", "射线" }, { "she xian", "涉嫌" }, { "she xian", "设限" }, { "she xiang", "摄像" }, { "she xiang", "设想" },
			{ "she xiang ji", "摄像机" }, { "she xiang tou", "摄像头" }, { "she ying", "摄影" }, { "she ying ji", "摄影机" }, { "she ying ji zhe", "摄影记者" },
			{ "she ying jia", "摄影家" }, { "she ying shi", "摄影师" }, { "she ying zuo pin", "摄影作品" }, { "she you", "舍友" }, { "she you", "设有" },
			{ "she yuan", "社员" }, { "she zai", "设在" }, { "she zhang", "社长" }, { "she zhi", "摄制" }, { "she zhi", "设置" }, { "she zhi cheng", "设置成" },
			{ "she zhi wei", "设置为" }, { "she zu", "涉足" }, { "shei", "谁" }, { "shei de", "谁的" }, { "shei dou", "谁都" }, { "shei hui", "谁会" },
			{ "shei jia", "谁家" }, { "shei jiu", "谁就" }, { "shei lai", "谁来" }, { "shei neng", "谁能" }, { "shei rang", "谁让" }, { "shei shi", "谁是" },
			{ "shei shuo", "谁说" }, { "shei yao", "谁要" }, { "shei ye", "谁也" }, { "shei you", "谁又" }, { "shei you", "谁有" }, { "shei zhi", "谁知" },
			{ "shei zhi dao", "谁知道" }, { "shen", "什" }, { "shen", "伔" }, { "shen", "伸" }, { "shen", "侁" }, { "shen", "侺" }, { "shen", "兟" }, { "shen", "参" },
			{ "shen", "呻" }, { "shen", "哂" }, { "shen", "堔" }, { "shen", "妽" }, { "shen", "娠" }, { "shen", "婶" }, { "shen", "嫀" }, { "shen", "嬸" },
			{ "shen", "审" }, { "shen", "審" }, { "shen", "屾" }, { "shen", "峷" }, { "shen", "幓" }, { "shen", "愼" }, { "shen", "慎" }, { "shen", "抌" },
			{ "shen", "曋" }, { "shen", "柛" }, { "shen", "棯" }, { "shen", "椹" }, { "shen", "榊" }, { "shen", "槮" }, { "shen", "氠" }, { "shen", "沈" },
			{ "shen", "淰" }, { "shen", "深" }, { "shen", "渖" }, { "shen", "渗" }, { "shen", "滲" }, { "shen", "瀋" }, { "shen", "燊" }, { "shen", "珅" },
			{ "shen", "甚" }, { "shen", "甡" }, { "shen", "申" }, { "shen", "眒" }, { "shen", "瞫" }, { "shen", "矧" }, { "shen", "砷" }, { "shen", "神" },
			{ "shen", "祳" }, { "shen", "籸" }, { "shen", "糁" }, { "shen", "紳" }, { "shen", "綝" }, { "shen", "绅" }, { "shen", "罧" }, { "shen", "肾" },
			{ "shen", "胂" }, { "shen", "脤" }, { "shen", "腎" }, { "shen", "莘" }, { "shen", "葚" }, { "shen", "葠" }, { "shen", "蔘" }, { "shen", "蜃" },
			{ "shen", "覾" }, { "shen", "訷" }, { "shen", "詵" }, { "shen", "諗" }, { "shen", "讅" }, { "shen", "诜" }, { "shen", "谂" }, { "shen", "身" },
			{ "shen", "邥" }, { "shen", "鋠" }, { "shen", "駪" }, { "shen", "鯓" }, { "shen", "鯵" }, { "shen", "鰰" }, { "shen", "鰺" }, { "shen ai", "深爱" },
			{ "shen an", "深谙" }, { "shen ao", "深奥" }, { "shen ao", "申奥" }, { "shen ban", "申办" }, { "shen bao", "申报" }, { "shen bao biao", "申报表" },
			{ "shen bian", "身边" }, { "shen biao", "深表" }, { "shen bing", "神兵" }, { "shen bing", "肾病" }, { "shen bu", "深部" }, { "shen bu ke ce", "深不可测" },
			{ "shen bu you ji", "身不由己" }, { "shen cai", "神采" }, { "shen cai", "身材" }, { "shen cai fei yang", "神采飞扬" }, { "shen cang", "深藏" },
			{ "shen ceng", "深层" }, { "shen ceng ci", "深层次" }, { "shen ceng qing jie", "深层清洁" }, { "shen cha", "审查" }, { "shen chang", "伸长" },
			{ "shen chen", "深沉" }, { "shen cheng", "申城" }, { "shen chu", "伸出" }, { "shen chu", "深处" }, { "shen chu", "渗出" }, { "shen chu", "身处" },
			{ "shen chu shou", "伸出手" }, { "shen chuan", "身穿" }, { "shen dao", "伸到" }, { "shen de", "深得" }, { "shen dian", "神殿" }, { "shen diao", "神雕" },
			{ "shen diao xia lv", "神雕侠侣" }, { "shen ding", "审定" }, { "shen du", "深度" }, { "shen duan", "身段" }, { "shen duo", "甚多" }, { "shen fa zhan", "深发展" },
			{ "shen fen", "身份" }, { "shen fen", "身分" }, { "shen fen yan zheng", "身份验证" }, { "shen fen zheng", "身份证" }, { "shen fen zheng hao", "身份证号" },
			{ "shen fen zheng jian", "身份证件" }, { "shen fen zheng ming", "身份证明" }, { "shen fu", "神父" }, { "shen gan", "深感" }, { "shen gang", "深港" },
			{ "shen gao", "审稿" }, { "shen gao", "身高" }, { "shen gong", "神功" }, { "shen gong neng", "肾功能" }, { "shen gou", "申购" }, { "shen hai", "深海" },
			{ "shen he", "审核" }, { "shen hou", "深厚" }, { "shen hou", "身后" }, { "shen hu xi", "深呼吸" }, { "shen hua", "深化" }, { "shen hua", "申花" },
			{ "shen hua", "神化" }, { "shen hua", "神华" }, { "shen hua", "神话" }, { "shen hua dui", "申花队" }, { "shen hua gai ge", "深化改革" }, { "shen huan", "身患" },
			{ "shen huo", "甚或" }, { "shen ji", "审计" }, { "shen ji bao gao", "审计报告" }, { "shen ji gong zuo", "审计工作" }, { "shen ji ji guan", "审计机关" },
			{ "shen ji ju", "审计局" }, { "shen ji ren yuan", "审计人员" }, { "shen ji shu", "审计署" }, { "shen jia", "身价" }, { "shen jia", "身家" },
			{ "shen jia gong", "深加工" }, { "shen jian", "神剑" }, { "shen jian", "身兼" }, { "shen jiao suo", "深交所" }, { "shen jie shi", "肾结石" },
			{ "shen jin", "伸进" }, { "shen jing", "神经" }, { "shen jing bing", "神经病" }, { "shen jing mo shao", "神经末梢" }, { "shen jing shuai ruo", "神经衰弱" },
			{ "shen jing tong", "神经痛" }, { "shen jing wang luo", "神经网络" }, { "shen jing xi tong", "神经系统" }, { "shen jing yuan", "神经元" },
			{ "shen jing zhi", "神经质" }, { "shen jiu", "深究" }, { "shen ke", "深刻" }, { "shen ke li jie", "深刻理解" }, { "shen ke ren shi", "深刻认识" },
			{ "shen lai", "神来" }, { "shen lan", "深蓝" }, { "shen lan se", "深蓝色" }, { "shen li", "审理" }, { "shen li", "神力" }, { "shen lin qi jing", "身临其境" },
			{ "shen ling", "申领" }, { "shen ling", "神灵" }, { "shen liu", "神六" }, { "shen long", "神龙" }, { "shen lou", "渗漏" }, { "shen lun", "申论" },
			{ "shen ma", "神码" }, { "shen mai", "深埋" }, { "shen me", "什么" }, { "shen me a", "什么啊" }, { "shen me bing", "什么病" }, { "shen me che", "什么车" },
			{ "shen me cheng du", "什么程度" }, { "shen me de", "什么的" }, { "shen me di fang", "什么地方" }, { "shen me dong dong", "什么东东" },
			{ "shen me dong xi", "什么东西" }, { "shen me ge", "什么歌" }, { "shen me guan xi", "什么关系" }, { "shen me hao", "什么好" }, { "shen me hua", "什么话" },
			{ "shen me jiao", "什么叫" }, { "shen me jiao zuo", "什么叫做" }, { "shen me ming zi", "什么名字" }, { "shen me ne", "什么呢" }, { "shen me pai zi", "什么牌子" },
			{ "shen me qing kuang", "什么情况" }, { "shen me ren", "什么人" }, { "shen me shi hou", "什么时候" }, { "shen me shi jian", "什么时间" },
			{ "shen me shi qing", "什么事情" }, { "shen me shu", "什么书" }, { "shen me wen ti", "什么问题" }, { "shen me yan se", "什么颜色" }, { "shen me yang", "什么样" },
			{ "shen me yang zi", "什么样子" }, { "shen me yao", "什么药" }, { "shen me yi si", "什么意思" }, { "shen me yong", "什么用" }, { "shen me yuan yin", "什么原因" },
			{ "shen me zuo yong", "什么作用" }, { "shen mei", "审美" }, { "shen mei guan", "审美观" }, { "shen mei pi lao", "审美疲劳" }, { "shen mi", "神秘" },
			{ "shen mi gan", "神秘感" }, { "shen mi mian sha", "神秘面纱" }, { "shen miao", "神庙" }, { "shen ming", "申明" }, { "shen ming", "神明" }, { "shen mo", "神魔" },
			{ "shen nan", "深南" }, { "shen nong", "神农" }, { "shen nong jia", "神农架" }, { "shen pan", "审判" }, { "shen pang", "身旁" }, { "shen pi", "审批" },
			{ "shen pi", "身披" }, { "shen pi biao", "审批表" }, { "shen pi cheng xu", "审批程序" }, { "shen pi shou xu", "审批手续" }, { "shen qi", "神器" },
			{ "shen qi", "神奇" }, { "shen qi", "神气" }, { "shen qi", "神起" }, { "shen qian", "深浅" }, { "shen qian", "身前" }, { "shen qie", "深切" },
			{ "shen qing", "深情" }, { "shen qing", "申请" }, { "shen qing", "神情" }, { "shen qing biao", "申请表" }, { "shen qing cai liao", "申请材料" },
			{ "shen qing dan", "申请单" }, { "shen qing jia ru", "申请加入" }, { "shen qing ren", "申请人" }, { "shen qing shu", "申请书" }, { "shen qing zhe", "申请者" },
			{ "shen qiu", "深秋" }, { "shen qu", "身躯" }, { "shen ren", "神人" }, { "shen ru", "深入" }, { "shen ru", "渗入" }, { "shen ru kai zhan", "深入开展" },
			{ "shen ru qian chu", "深入浅出" }, { "shen ru ren xin", "深入人心" }, { "shen ru yan jiu", "深入研究" }, { "shen se", "深色" }, { "shen se", "神色" },
			{ "shen shan", "深山" }, { "shen shan", "神山" }, { "shen shang", "身上" }, { "shen shang xian", "肾上腺" }, { "shen shao", "甚少" }, { "shen shen", "婶婶" },
			{ "shen shen", "审慎" }, { "shen shen", "深深" }, { "shen sheng", "神圣" }, { "shen shi", "审视" }, { "shen shi", "深市" }, { "shen shi", "甚是" },
			{ "shen shi", "绅士" }, { "shen shi", "身世" }, { "shen shou", "伸手" }, { "shen shou", "深受" }, { "shen shou", "神兽" }, { "shen shou", "身手" },
			{ "shen shui", "深水" }, { "shen shui", "渗水" }, { "shen si", "深思" }, { "shen si", "神似" }, { "shen si shu lv", "深思熟虑" }, { "shen su", "申诉" },
			{ "shen su", "神速" }, { "shen sui", "深邃" }, { "shen suo", "伸缩" }, { "shen tai", "神态" }, { "shen tan", "神探" }, { "shen ti", "身体" },
			{ "shen ti jian kang", "身体健康" }, { "shen ti li xing", "身体力行" }, { "shen ti su zhi", "身体素质" }, { "shen ti zhuang kuang", "身体状况" },
			{ "shen tong", "神童" }, { "shen tong", "神通" }, { "shen tou", "渗透" }, { "shen wang", "神往" }, { "shen wang", "身亡" }, { "shen wei", "甚为" },
			{ "shen wei", "身为" }, { "shen wen", "审问" }, { "shen wu tong jue", "深恶痛绝" }, { "shen xi", "深吸" }, { "shen xia", "身下" }, { "shen xian", "深陷" },
			{ "shen xian", "神仙" }, { "shen xian", "身陷" }, { "shen xiang", "伸向" }, { "shen xiang", "神像" }, { "shen xin", "深信" }, { "shen xin", "身心" },
			{ "shen xin bu yi", "深信不疑" }, { "shen xin jian kang", "身心健康" }, { "shen xing", "身形" }, { "shen xu", "肾虚" }, { "shen xue", "神学" },
			{ "shen xun", "审讯" }, { "shen yan", "肾炎" }, { "shen yang", "沈阳" }, { "shen ye", "深夜" }, { "shen yi", "审议" }, { "shen yi", "深意" },
			{ "shen yi", "神医" }, { "shen yin", "呻吟" }, { "shen yin wan guo", "申银万国" }, { "shen ying", "身影" }, { "shen yong", "慎用" }, { "shen yong", "神勇" },
			{ "shen you", "深有" }, { "shen you", "神游" }, { "shen you gan chu", "深有感触" }, { "shen yuan", "深渊" }, { "shen yuan", "深远" }, { "shen yuan", "甚远" },
			{ "shen yue", "审阅" }, { "shen yun", "神韵" }, { "shen yun", "身孕" }, { "shen zai", "身在" }, { "shen zang", "肾脏" }, { "shen zao", "深造" },
			{ "shen zhan", "伸展" }, { "shen zhang", "伸张" }, { "shen zhen", "深圳" }, { "shen zhen dui", "深圳队" }, { "shen zhen shi", "深圳市" },
			{ "shen zheng", "深证" }, { "shen zhi", "伸直" }, { "shen zhi", "深知" }, { "shen zhi", "甚至" }, { "shen zhi", "神志" }, { "shen zhi lian", "甚至连" },
			{ "shen zhi yu", "甚至于" }, { "shen zhong", "慎重" }, { "shen zhong", "深重" }, { "shen zhou", "神州" }, { "shen zhou", "神舟" },
			{ "shen zhou shu ma", "神州数码" }, { "shen zhou xing", "神州行" }, { "shen zhuo", "身着" }, { "shen zi", "身姿" }, { "shen zi", "身子" }, { "shen zu", "神族" },
			{ "sheng", "乗" }, { "sheng", "乘" }, { "sheng", "偗" }, { "sheng", "剩" }, { "sheng", "剰" }, { "sheng", "勝" }, { "sheng", "升" }, { "sheng", "呏" },
			{ "sheng", "圣" }, { "sheng", "声" }, { "sheng", "嵊" }, { "sheng", "憴" }, { "sheng", "昇" }, { "sheng", "晟" }, { "sheng", "曻" }, { "sheng", "枡" },
			{ "sheng", "橳" }, { "sheng", "泩" }, { "sheng", "渑" }, { "sheng", "渻" }, { "sheng", "湦" }, { "sheng", "澠" }, { "sheng", "焺" }, { "sheng", "牲" },
			{ "sheng", "生" }, { "sheng", "甥" }, { "sheng", "盛" }, { "sheng", "省" }, { "sheng", "眚" }, { "sheng", "笙" }, { "sheng", "繩" }, { "sheng", "绳" },
			{ "sheng", "聖" }, { "sheng", "聲" }, { "sheng", "胜" }, { "sheng", "譝" }, { "sheng", "貹" }, { "sheng", "賸" }, { "sheng", "鉎" }, { "sheng", "陞" },
			{ "sheng", "鵿" }, { "sheng", "鼪" }, { "sheng bao luo", "圣保罗" }, { "sheng bi de bao", "圣彼得堡" }, { "sheng bing", "生病" }, { "sheng bo", "声波" },
			{ "sheng bu ji", "省部级" }, { "sheng bu ru si", "生不如死" }, { "sheng cai", "生菜" }, { "sheng cai zheng ting", "省财政厅" }, { "sheng chan", "生产" },
			{ "sheng chan", "盛产" }, { "sheng chan bu", "生产部" }, { "sheng chan chang", "生产厂" }, { "sheng chan chang jia", "生产厂家" },
			{ "sheng chan chang shang", "生产厂商" }, { "sheng chan che jian", "生产车间" }, { "sheng chan cheng ben", "生产成本" }, { "sheng chan dui", "生产队" },
			{ "sheng chan fang shi", "生产方式" }, { "sheng chan gong yi", "生产工艺" }, { "sheng chan guan li", "生产管理" }, { "sheng chan guan xi", "生产关系" },
			{ "sheng chan gui mo", "生产规模" }, { "sheng chan guo cheng", "生产过程" }, { "sheng chan ji di", "生产基地" }, { "sheng chan ji hua", "生产计划" },
			{ "sheng chan ji shu", "生产技术" }, { "sheng chan jia gong", "生产加工" }, { "sheng chan jing ying", "生产经营" }, { "sheng chan li", "生产力" },
			{ "sheng chan lv", "生产率" }, { "sheng chan neng li", "生产能力" }, { "sheng chan qi ye", "生产企业" }, { "sheng chan ri qi", "生产日期" },
			{ "sheng chan shang", "生产商" }, { "sheng chan she bei", "生产设备" }, { "sheng chan xian", "生产线" }, { "sheng chan xiao lv", "生产效率" },
			{ "sheng chan xiao shou", "生产销售" }, { "sheng chan xing", "生产性" }, { "sheng chan yao su", "生产要素" }, { "sheng chan zhe", "生产者" },
			{ "sheng chan zhi zao", "生产制造" }, { "sheng chan zi liao", "生产资料" }, { "sheng chan zong zhi", "生产总值" }, { "sheng chang", "声场" },
			{ "sheng chen", "生辰" }, { "sheng cheng", "声称" }, { "sheng cheng", "生成" }, { "sheng cheng", "省城" }, { "sheng cheng qi", "生成器" },
			{ "sheng chi", "生吃" }, { "sheng chi jian yong", "省吃俭用" }, { "sheng chu", "牲畜" }, { "sheng chu", "生出" }, { "sheng chu", "胜出" },
			{ "sheng chuan", "盛传" }, { "sheng cun", "生存" }, { "sheng cun huan jing", "生存环境" }, { "sheng cun kong jian", "生存空间" },
			{ "sheng cun zhuang tai", "生存状态" }, { "sheng da", "盛大" }, { "sheng dai", "声带" }, { "sheng dan", "圣诞" }, { "sheng dan jie", "圣诞节" },
			{ "sheng dan kuai le", "圣诞快乐" }, { "sheng dan lao ren", "圣诞老人" }, { "sheng dan shu", "圣诞树" }, { "sheng dao", "升到" }, { "sheng dao", "声道" },
			{ "sheng dao", "省道" }, { "sheng de", "生得" }, { "sheng de", "省得" }, { "sheng di", "圣地" }, { "sheng di", "胜地" }, { "sheng dian", "圣殿" },
			{ "sheng dian", "盛典" }, { "sheng dian", "省电" }, { "sheng diao", "声调" }, { "sheng dong", "生动" }, { "sheng dou shi", "圣斗士" }, { "sheng fa", "生发" },
			{ "sheng fan", "剩饭" }, { "sheng fen", "省份" }, { "sheng fu", "升幅" }, { "sheng fu", "胜负" }, { "sheng gao", "升高" }, { "sheng ge", "升格" },
			{ "sheng ge", "笙歌" }, { "sheng gen", "生根" }, { "sheng gong an ting", "省公安厅" }, { "sheng guan", "升官" }, { "sheng guang", "圣光" },
			{ "sheng guo", "胜过" }, { "sheng hai zi", "生孩子" }, { "sheng hua", "升华" }, { "sheng hua", "生化" }, { "sheng hua wei ji", "生化危机" },
			{ "sheng huan", "生还" }, { "sheng hui", "盛会" }, { "sheng hui", "省会" }, { "sheng hui cheng shi", "省会城市" }, { "sheng huo", "圣火" },
			{ "sheng huo", "生活" }, { "sheng huo fang shi", "生活方式" }, { "sheng huo fei", "生活费" }, { "sheng huo hua", "生活化" }, { "sheng huo huan jing", "生活环境" },
			{ "sheng huo kun nan", "生活困难" }, { "sheng huo la ji", "生活垃圾" }, { "sheng huo li", "生活里" }, { "sheng huo qu", "生活区" },
			{ "sheng huo shui ping", "生活水平" }, { "sheng huo tai du", "生活态度" }, { "sheng huo tiao jian", "生活条件" }, { "sheng huo xi guan", "生活习惯" },
			{ "sheng huo yong pin", "生活用品" }, { "sheng huo zhao", "生活照" }, { "sheng huo zhi liang", "生活质量" }, { "sheng ji", "升技" }, { "sheng ji", "升级" },
			{ "sheng ji", "生机" }, { "sheng ji", "生计" }, { "sheng ji", "省级" }, { "sheng ji ban", "升级版" }, { "sheng ji bao", "升级包" },
			{ "sheng ji bo bo", "生机勃勃" }, { "sheng ji huan dai", "升级换代" }, { "sheng ji wei", "省纪委" }, { "sheng jiang", "升降" }, { "sheng jiang", "生姜" },
			{ "sheng jiao yu ting", "省教育厅" }, { "sheng jie", "圣洁" }, { "sheng jin", "生津" }, { "sheng jing", "圣经" }, { "sheng ju", "省局" }, { "sheng ka", "声卡" },
			{ "sheng kai", "盛开" }, { "sheng kong", "升空" }, { "sheng kou", "牲口" }, { "sheng kuang", "盛况" }, { "sheng lai", "生来" }, { "sheng li", "生理" },
			{ "sheng li", "省力" }, { "sheng li", "省里" }, { "sheng li", "胜利" }, { "sheng li jun", "生力军" }, { "sheng li xue", "生理学" }, { "sheng li zhe", "胜利者" },
			{ "sheng ling", "圣灵" }, { "sheng ling", "生灵" }, { "sheng lu", "生路" }, { "sheng lue", "省略" }, { "sheng lue hao", "省略号" }, { "sheng lv", "胜率" },
			{ "sheng meng", "生猛" }, { "sheng ming", "声名" }, { "sheng ming", "声明" }, { "sheng ming", "生命" }, { "sheng ming", "盛名" },
			{ "sheng ming an quan", "生命安全" }, { "sheng ming ke xue", "生命科学" }, { "sheng ming li", "生命力" }, { "sheng ming wei xian", "生命危险" },
			{ "sheng ming xian", "生命线" }, { "sheng ming zhe", "声明者" }, { "sheng ming zhong zui", "生命中最" }, { "sheng ming zhou qi", "生命周期" },
			{ "sheng mu", "圣母" }, { "sheng mu", "生母" }, { "sheng nei", "省内" }, { "sheng nv", "圣女" }, { "sheng pa", "生怕" }, { "sheng ping", "生平" },
			{ "sheng qi", "升起" }, { "sheng qi", "圣骑" }, { "sheng qi", "生气" } };
};
