package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN52 {
	public static String[][] pl = { { "xiao ai", "小爱" }, { "xiao ai", "小艾" }, { "xiao an", "小安" }, { "xiao ao", "笑傲" }, { "xiao ao jiang hu", "笑傲江湖" },
			{ "xiao ba wang", "小霸王" }, { "xiao bai", "小白" }, { "xiao bai cai", "小白菜" }, { "xiao bai lian", "小白脸" }, { "xiao bai shu", "小白鼠" },
			{ "xiao bai tu", "小白兔" }, { "xiao ban", "小班" }, { "xiao bang", "肖邦" }, { "xiao bao", "小包" }, { "xiao bao", "小宝" }, { "xiao bao", "小报" },
			{ "xiao bao bao", "小宝宝" }, { "xiao bao bei", "小宝贝" }, { "xiao bei", "小贝" }, { "xiao ben", "小本" }, { "xiao bian", "小便" }, { "xiao bian", "小编" },
			{ "xiao bing", "小兵" }, { "xiao bing", "小病" }, { "xiao bo", "小波" }, { "xiao bo", "晓波" }, { "xiao bu", "小布" }, { "xiao bu", "小步" },
			{ "xiao bu dian", "小不点" }, { "xiao bu shi", "小布什" }, { "xiao cai", "小菜" }, { "xiao cai", "小蔡" }, { "xiao cao", "小草" }, { "xiao ce zi", "小册子" },
			{ "xiao cha qu", "小插曲" }, { "xiao chang", "小厂" }, { "xiao chang", "小肠" }, { "xiao che", "小车" }, { "xiao che", "校车" }, { "xiao chen", "小陈" },
			{ "xiao chen", "消沉" }, { "xiao cheng", "小城" }, { "xiao cheng shi", "小城市" }, { "xiao cheng xu", "小程序" }, { "xiao cheng zhen", "小城镇" },
			{ "xiao chi", "小吃" }, { "xiao chi", "小池" }, { "xiao chong", "小虫" }, { "xiao chou", "小丑" }, { "xiao chu", "削除" }, { "xiao chu", "消除" },
			{ "xiao chu pi lao", "消除疲劳" }, { "xiao chuan", "哮喘" }, { "xiao chuan", "小川" }, { "xiao chuan", "小船" }, { "xiao chuang", "小窗" },
			{ "xiao chun", "小春" }, { "xiao cong", "小葱" }, { "xiao cong ming", "小聪明" }, { "xiao cui", "小崔" }, { "xiao cui", "小翠" }, { "xiao dao", "小刀" },
			{ "xiao dao", "小到" }, { "xiao dao", "小岛" }, { "xiao dao", "小道" }, { "xiao dao", "笑道" }, { "xiao dao xiao xi", "小道消息" }, { "xiao de", "小德" },
			{ "xiao de", "晓得" }, { "xiao de", "笑得" }, { "xiao di", "小弟" }, { "xiao di di", "小弟弟" }, { "xiao di fang", "小地方" }, { "xiao dian", "小店" },
			{ "xiao dian ying", "小电影" }, { "xiao diao", "小调" }, { "xiao ding", "小丁" }, { "xiao dong", "小东" }, { "xiao dong", "小董" }, { "xiao dong", "晓东" },
			{ "xiao dong wu", "小动物" }, { "xiao dong xi", "小东西" }, { "xiao dong zuo", "小动作" }, { "xiao dou", "小豆" }, { "xiao du", "消毒" }, { "xiao duan", "小段" },
			{ "xiao dui", "小队" }, { "xiao e", "小额" }, { "xiao e dai kuan", "小额贷款" }, { "xiao er", "小二" }, { "xiao er", "小儿" }, { "xiao er ke", "小儿科" },
			{ "xiao er zi", "小儿子" }, { "xiao fan", "小凡" }, { "xiao fan", "小贩" }, { "xiao fang", "小方" }, { "xiao fang", "小芳" }, { "xiao fang", "效仿" },
			{ "xiao fang", "校方" }, { "xiao fang", "消防" }, { "xiao fang an quan", "消防安全" }, { "xiao fang che", "消防车" }, { "xiao fang jian", "小房间" },
			{ "xiao fang zi", "小房子" }, { "xiao fei", "小费" }, { "xiao fei", "小非" }, { "xiao fei", "小飞" }, { "xiao fei", "消费" }, { "xiao fei dian zi", "消费电子" },
			{ "xiao fei guan nian", "消费观念" }, { "xiao fei lei", "消费类" }, { "xiao fei liang", "消费量" }, { "xiao fei neng li", "消费能力" },
			{ "xiao fei pin", "消费品" }, { "xiao fei qun", "消费群" }, { "xiao fei qun ti", "消费群体" }, { "xiao fei shi chang", "消费市场" }, { "xiao fei shui", "消费税" },
			{ "xiao fei shui ping", "消费水平" }, { "xiao fei xi guan", "消费习惯" }, { "xiao fei xu qiu", "消费需求" }, { "xiao fei yang", "小肥羊" },
			{ "xiao fei zhe", "消费者" }, { "xiao fei zhi chu", "消费支出" }, { "xiao fen dui", "小分队" }, { "xiao feng", "小凤" }, { "xiao feng", "小峰" },
			{ "xiao feng", "小风" }, { "xiao feng", "晓峰" }, { "xiao feng", "晓风" }, { "xiao feng", "萧峰" }, { "xiao fu", "小幅" }, { "xiao fu", "小腹" },
			{ "xiao fu", "校服" }, { "xiao gan", "孝感" }, { "xiao gang", "小刚" }, { "xiao gao", "小高" }, { "xiao gao ceng", "小高层" }, { "xiao ge", "小哥" },
			{ "xiao ge zi", "小个子" }, { "xiao gong", "小工" }, { "xiao gong ju", "小工具" }, { "xiao gong si", "小公司" }, { "xiao gong zhu", "小公主" },
			{ "xiao gou", "小狗" }, { "xiao gu", "小姑" }, { "xiao gu niang", "小姑娘" }, { "xiao gu shi", "小故事" }, { "xiao guai", "小乖" }, { "xiao guang", "小光" },
			{ "xiao guang gao", "小广告" }, { "xiao gui", "小鬼" }, { "xiao gui mo", "小规模" }, { "xiao guo", "小国" }, { "xiao guo", "小郭" }, { "xiao guo", "效果" },
			{ "xiao guo hao", "效果好" }, { "xiao guo ru he", "效果如何" }, { "xiao guo tu", "效果图" }, { "xiao hai", "小孩" }, { "xiao hai", "小海" },
			{ "xiao hai er", "小孩儿" }, { "xiao hai zi", "小孩子" }, { "xiao hao", "小号" }, { "xiao hao", "消耗" }, { "xiao hao diao", "消耗掉" },
			{ "xiao hao liang", "消耗量" }, { "xiao he", "小河" }, { "xiao he he", "笑呵呵" }, { "xiao he shang", "小和尚" }, { "xiao hei", "小黑" }, { "xiao hong", "小红" },
			{ "xiao hong mao", "小红帽" }, { "xiao hou", "小猴" }, { "xiao hou zi", "小猴子" }, { "xiao hu", "小胡" }, { "xiao hu", "小虎" }, { "xiao hu", "销户" },
			{ "xiao hu li", "小狐狸" }, { "xiao hu shi", "小护士" }, { "xiao hu xing", "小户型" }, { "xiao hua", "小华" }, { "xiao hua", "小花" }, { "xiao hua", "校花" },
			{ "xiao hua", "消化" }, { "xiao hua", "笑话" }, { "xiao hua bu liang", "消化不良" }, { "xiao hua dao", "消化道" }, { "xiao hua xi shou", "消化吸收" },
			{ "xiao hua xi tong", "消化系统" }, { "xiao huang", "小黄" }, { "xiao hui", "小慧" }, { "xiao hui", "销毁" }, { "xiao hun", "销魂" },
			{ "xiao hun hun", "小混混" }, { "xiao huo", "小伙" }, { "xiao huo", "小火" }, { "xiao huo ban", "小伙伴" }, { "xiao huo zi", "小伙子" }, { "xiao ji", "小计" },
			{ "xiao ji", "小记" }, { "xiao ji", "小鸡" }, { "xiao ji", "校级" }, { "xiao ji", "消极" }, { "xiao ji ji", "小鸡鸡" }, { "xiao ji qiao", "小技巧" },
			{ "xiao jia", "小家" }, { "xiao jia dian", "小家电" }, { "xiao jia huo", "小家伙" }, { "xiao jiang", "小将" }, { "xiao jiao", "小脚" },
			{ "xiao jiao che", "小轿车" }, { "xiao jie", "小姐" }, { "xiao jie", "小杰" }, { "xiao jie", "小结" }, { "xiao jie", "小节" }, { "xiao jie", "小街" },
			{ "xiao jie", "消解" }, { "xiao jin", "小金" }, { "xiao jing", "孝敬" }, { "xiao jing", "小径" }, { "xiao jing", "小静" }, { "xiao jing ling", "小精灵" },
			{ "xiao jiu", "小酒" }, { "xiao ju", "小聚" }, { "xiao juan", "小娟" }, { "xiao jun", "小军" }, { "xiao ka", "小卡" }, { "xiao kan", "小看" },
			{ "xiao kan", "笑看" }, { "xiao kang", "小康" }, { "xiao kang she hui", "小康社会" }, { "xiao ke", "小克" }, { "xiao ke", "小可" }, { "xiao ke ai", "小可爱" },
			{ "xiao kong", "小孔" }, { "xiao kou", "小口" }, { "xiao kuai", "小块" }, { "xiao la ba", "小喇叭" }, { "xiao lan", "小兰" }, { "xiao lang", "小狼" },
			{ "xiao lao ban", "小老板" }, { "xiao lao po", "小老婆" }, { "xiao lao shu", "小老鼠" }, { "xiao le", "笑了" }, { "xiao le xiao", "笑了笑" },
			{ "xiao lei", "小雷" }, { "xiao li", "小丽" }, { "xiao li", "小李" }, { "xiao li", "效力" }, { "xiao li wu", "小礼物" }, { "xiao lian", "小脸" },
			{ "xiao lian", "笑脸" }, { "xiao liang", "小亮" }, { "xiao liang", "销量" }, { "xiao liang kou", "小两口" }, { "xiao liao", "笑料" }, { "xiao lin", "小林" },
			{ "xiao ling", "小玲" }, { "xiao ling dao", "校领导" }, { "xiao ling tong", "小灵通" }, { "xiao liu", "小六" }, { "xiao liu", "小刘" }, { "xiao long", "小龙" },
			{ "xiao long nv", "小龙女" }, { "xiao long xia", "小龙虾" }, { "xiao lou", "小楼" }, { "xiao lu", "小路" }, { "xiao lu", "小鹿" }, { "xiao lu", "销路" },
			{ "xiao luo", "小罗" }, { "xiao lv", "效率" }, { "xiao lv gao", "效率高" }, { "xiao ma", "小马" }, { "xiao ma ge", "小马哥" }, { "xiao mai", "小麦" },
			{ "xiao mai bu", "小卖部" }, { "xiao mai jia ge", "小麦价格" }, { "xiao man", "小曼" }, { "xiao mao", "小毛" }, { "xiao mao", "小猫" }, { "xiao mei", "小妹" },
			{ "xiao mei", "小梅" }, { "xiao mei", "小美" }, { "xiao mei mei", "小妹妹" }, { "xiao mei nv", "小美女" }, { "xiao men", "校门" }, { "xiao men kou", "校门口" },
			{ "xiao mi", "小秘" }, { "xiao mi", "小米" }, { "xiao mi", "小蜜" }, { "xiao mi feng", "小蜜蜂" }, { "xiao mi mi", "笑眯眯" }, { "xiao mie", "消灭" },
			{ "xiao min", "小敏" }, { "xiao min", "小民" }, { "xiao ming", "小名" }, { "xiao ming", "小命" }, { "xiao ming", "小明" }, { "xiao ming", "晓明" },
			{ "xiao mo", "消磨" }, { "xiao nan", "小南" }, { "xiao nan", "晓楠" }, { "xiao nan hai", "小男孩" }, { "xiao nan ren", "小男人" }, { "xiao nan sheng", "小男生" },
			{ "xiao nei", "校内" }, { "xiao neng", "效能" }, { "xiao ni zi", "小妮子" }, { "xiao niao", "小鸟" }, { "xiao ning", "小宁" }, { "xiao niu", "小妞" },
			{ "xiao niu", "小牛" }, { "xiao niu dui", "小牛队" }, { "xiao nong", "小农" }, { "xiao nv", "小女" }, { "xiao nv er", "小女儿" }, { "xiao nv hai", "小女孩" },
			{ "xiao nv ren", "小女人" }, { "xiao nv sheng", "小女生" }, { "xiao nv zi", "小女子" }, { "xiao pan", "小盘" }, { "xiao pan gu", "小盘股" },
			{ "xiao pang", "小胖" }, { "xiao pang zi", "小胖子" }, { "xiao pao", "小跑" }, { "xiao peng you", "小朋友" }, { "xiao pi hai", "小屁孩" },
			{ "xiao pian", "小片" }, { "xiao piao", "小票" }, { "xiao pin", "小品" }, { "xiao ping", "小平" }, { "xiao qi", "小七" }, { "xiao qi", "小憩" },
			{ "xiao qi", "小气" }, { "xiao qi che", "小汽车" }, { "xiao qi lai", "笑起来" }, { "xiao qi ye", "小企业" }, { "xiao qian", "小倩" }, { "xiao qian", "小钱" },
			{ "xiao qian", "消遣" }, { "xiao qiang", "小强" }, { "xiao qiang", "萧蔷" }, { "xiao qiao", "小乔" }, { "xiao qiao", "小巧" }, { "xiao qiao", "小桥" },
			{ "xiao qing", "小青" }, { "xiao qing", "校庆" }, { "xiao qing nian", "小青年" }, { "xiao qiu", "小球" }, { "xiao qu", "小区" }, { "xiao qu", "小曲" },
			{ "xiao qu", "小觑" }, { "xiao qu", "校区" }, { "xiao quan", "小泉" }, { "xiao quan zi", "小圈子" }, { "xiao ren", "小人" }, { "xiao ren wu", "小人物" },
			{ "xiao ri ben", "小日本" }, { "xiao ri zi", "小日子" }, { "xiao rong", "消融" }, { "xiao rong", "笑容" }, { "xiao sa", "潇洒" }, { "xiao san", "小三" },
			{ "xiao san", "消散" }, { "xiao se", "萧瑟" }, { "xiao shan", "小山" }, { "xiao shan", "萧山" }, { "xiao shang pin", "小商品" }, { "xiao she", "校舍" },
			{ "xiao sheng", "小声" }, { "xiao sheng", "小生" }, { "xiao sheng", "小胜" }, { "xiao sheng", "笑声" }, { "xiao sheng ni ji", "销声匿迹" },
			{ "xiao sheng yi", "小生意" }, { "xiao shi", "小事" }, { "xiao shi", "小时" }, { "xiao shi", "小视" }, { "xiao shi", "小诗" }, { "xiao shi", "消失" },
			{ "xiao shi", "消逝" }, { "xiao shi hou", "小时侯" }, { "xiao shi hou", "小时候" }, { "xiao shi mei", "小师妹" }, { "xiao shi min", "小市民" },
			{ "xiao shi tou", "小石头" }, { "xiao shi zi", "小狮子" }, { "xiao shou", "小手" }, { "xiao shou", "消瘦" }, { "xiao shou", "销售" },
			{ "xiao shou bu", "销售部" }, { "xiao shou dai biao", "销售代表" }, { "xiao shou dian", "销售点" }, { "xiao shou e", "销售额" },
			{ "xiao shou gong si", "销售公司" }, { "xiao shou jia ge", "销售价格" }, { "xiao shou jing li", "销售经理" }, { "xiao shou liang", "销售量" },
			{ "xiao shou mo shi", "销售模式" }, { "xiao shou qing kuang", "销售情况" }, { "xiao shou qu dao", "销售渠道" }, { "xiao shou ren yuan", "销售人员" },
			{ "xiao shou shang", "销售商" }, { "xiao shou shou ru", "销售收入" }, { "xiao shou wang luo", "销售网络" }, { "xiao shou ye ji", "销售业绩" },
			{ "xiao shou yuan", "销售员" }, { "xiao shu", "小数" }, { "xiao shu", "小树" }, { "xiao shu", "小鼠" }, { "xiao shu dian", "小数点" },
			{ "xiao shuai ge", "小帅哥" }, { "xiao shun", "孝顺" }, { "xiao shuo", "小说" }, { "xiao shuo", "笑说" }, { "xiao shuo jia", "小说家" }, { "xiao si", "小四" },
			{ "xiao si", "笑死" }, { "xiao song", "小松" }, { "xiao su", "小苏" }, { "xiao suan", "硝酸" }, { "xiao sun", "小孙" }, { "xiao tan", "小摊" },
			{ "xiao tan", "笑谈" }, { "xiao tang", "小唐" }, { "xiao tao", "小桃" }, { "xiao ti qin", "小提琴" }, { "xiao tian", "小天" }, { "xiao tian", "小田" },
			{ "xiao tian e", "小天鹅" }, { "xiao tian shi", "小天使" }, { "xiao tian tian", "小甜甜" }, { "xiao tiao", "萧条" }, { "xiao ting", "消停" },
			{ "xiao tong", "小童" }, { "xiao tou", "小偷" }, { "xiao tu", "小兔" }, { "xiao tu", "小图" }, { "xiao tu zi", "小兔子" }, { "xiao tui", "小腿" },
			{ "xiao tui", "消退" }, { "xiao wai", "校外" }, { "xiao wan", "小碗" }, { "xiao wan zi", "小丸子" }, { "xiao wang", "小王" }, { "xiao wang", "消亡" },
			{ "xiao wang", "销往" }, { "xiao wang zi", "小王子" }, { "xiao wei", "小伟" }, { "xiao wei", "小薇" }, { "xiao wen", "小文" }, { "xiao wo", "小窝" },
			{ "xiao wo", "笑我" }, { "xiao wu", "小五" }, { "xiao wu", "小吴" }, { "xiao wu", "小屋" }, { "xiao wu", "小武" }, { "xiao wu gui", "小乌龟" },
			{ "xiao xi", "小溪" }, { "xiao xi", "小西" }, { "xiao xi", "消息" }, { "xiao xi fu", "小媳妇" }, { "xiao xi mian", "消息面" }, { "xiao xi xi", "笑嘻嘻" },
			{ "xiao xia", "小夏" }, { "xiao xia", "小虾" }, { "xiao xian", "小仙" }, { "xiao xian cheng", "小县城" }, { "xiao xiang", "小巷" }, { "xiao xiang", "潇湘" },
			{ "xiao xiang", "肖像" }, { "xiao xiao", "小小" }, { "xiao xiao", "晓晓" }, { "xiao xiao", "潇潇" }, { "xiao xiao", "笑笑" }, { "xiao xiao", "萧萧" },
			{ "xiao xiao de", "小小的" }, { "xiao xiao luo", "小小罗" }, { "xiao xiao nian ji", "小小年纪" }, { "xiao xie", "小写" }, { "xiao xie", "小谢" },
			{ "xiao xie", "消协" }, { "xiao xin", "孝心" }, { "xiao xin", "小心" }, { "xiao xin", "小新" }, { "xiao xin dian", "小心点" },
			{ "xiao xin jin shen", "小心谨慎" }, { "xiao xin yan", "小心眼" }, { "xiao xin yi yi", "小心翼翼" }, { "xiao xing", "小型" }, { "xiao xing che", "小型车" },
			{ "xiao xing ji", "小型机" }, { "xiao xing xing", "小行星" }, { "xiao xiong", "小熊" }, { "xiao xiong di", "小兄弟" }, { "xiao xu", "小徐" },
			{ "xiao xue", "小学" }, { "xiao xue", "小穴" }, { "xiao xue", "小雪" }, { "xiao xue bi ye", "小学毕业" }, { "xiao xue jiao shi", "小学教师" },
			{ "xiao xue sheng", "小学生" }, { "xiao ya", "小丫" }, { "xiao ya", "小雅" }, { "xiao ya", "小鸭" }, { "xiao ya tou", "小丫头" }, { "xiao ya xuan", "萧亚轩" },
			{ "xiao yan", "小燕" }, { "xiao yan", "消炎" }, { "xiao yan", "硝烟" }, { "xiao yan", "笑言" }, { "xiao yan", "笑颜" }, { "xiao yan jing", "小眼睛" },
			{ "xiao yan yao", "消炎药" }, { "xiao yan zi", "小燕子" }, { "xiao yang", "小杨" }, { "xiao yang", "小样" }, { "xiao yang", "小羊" }, { "xiao yao", "小妖" },
			{ "xiao yao", "逍遥" }, { "xiao yao jing", "小妖精" }, { "xiao ye", "宵夜" }, { "xiao ye", "小叶" }, { "xiao ye", "小野" }, { "xiao yi", "小姨" },
			{ "xiao yi", "效益" }, { "xiao yi", "笑意" }, { "xiao yi si", "小意思" }, { "xiao yi xiao", "笑一笑" }, { "xiao yi zi", "小姨子" }, { "xiao ying", "小樱" },
			{ "xiao ying", "效应" }, { "xiao yong", "小勇" }, { "xiao yong", "效用" }, { "xiao you", "校友" }, { "xiao you hui", "校友会" }, { "xiao you lu", "校友录" },
			{ "xiao you ming qi", "小有名气" }, { "xiao you xi", "小游戏" }, { "xiao yu", "小于" }, { "xiao yu", "小宇" }, { "xiao yu", "小玉" }, { "xiao yu", "小雨" },
			{ "xiao yu", "小鱼" }, { "xiao yu", "笑语" }, { "xiao yu er", "小鱼儿" }, { "xiao yu zhong", "小语种" }, { "xiao yu zhou", "小宇宙" }, { "xiao yuan", "小院" },
			{ "xiao yuan", "校园" }, { "xiao yuan li", "校园里" }, { "xiao yuan wang", "校园网" }, { "xiao yuan wen hua", "校园文化" }, { "xiao yuan zhao pin", "校园招聘" },
			{ "xiao yue", "小月" }, { "xiao yun", "小云" }, { "xiao zai", "消灾" }, { "xiao ze", "小泽" }, { "xiao zhan", "小站" }, { "xiao zhang", "嚣张" },
			{ "xiao zhang", "小张" }, { "xiao zhang", "校长" }, { "xiao zhao", "小赵" }, { "xiao zhe", "笑着" }, { "xiao zhe shuo", "笑着说" }, { "xiao zhen", "小镇" },
			{ "xiao zhi", "小志" }, { "xiao zhi", "小指" }, { "xiao zhong", "小众" }, { "xiao zhong", "效忠" }, { "xiao zhong", "消肿" }, { "xiao zhou", "小周" },
			{ "xiao zhou", "小舟" }, { "xiao zhu", "小朱" }, { "xiao zhu", "小猪" }, { "xiao zhu", "小筑" }, { "xiao zhu shou", "小助手" }, { "xiao zhu zhu", "小猪猪" },
			{ "xiao zi", "孝子" }, { "xiao zi", "小子" }, { "xiao zi", "小字" }, { "xiao zi", "小资" }, { "xiao zu", "小组" }, { "xiao zu cheng yuan", "小组成员" },
			{ "xiao zu sai", "小组赛" }, { "xiao zui", "小嘴" }, { "xiao zuo fang", "小作坊" }, { "xie", "些" }, { "xie", "亵" }, { "xie", "伳" }, { "xie", "偕" },
			{ "xie", "偰" }, { "xie", "僁" }, { "xie", "写" }, { "xie", "冩" }, { "xie", "劦" }, { "xie", "勰" }, { "xie", "协" }, { "xie", "協" }, { "xie", "卨" },
			{ "xie", "卸" }, { "xie", "叶" }, { "xie", "吤" }, { "xie", "嗋" }, { "xie", "垥" }, { "xie", "奊" }, { "xie", "契" }, { "xie", "媟" }, { "xie", "孈" },
			{ "xie", "寫" }, { "xie", "屑" }, { "xie", "屓" }, { "xie", "屧" }, { "xie", "屭" }, { "xie", "嶰" }, { "xie", "廨" }, { "xie", "恊" }, { "xie", "愶" },
			{ "xie", "慀" }, { "xie", "懈" }, { "xie", "拹" }, { "xie", "挟" }, { "xie", "挾" }, { "xie", "揳" }, { "xie", "搚" }, { "xie", "携" }, { "xie", "撷" },
			{ "xie", "擷" }, { "xie", "攜" }, { "xie", "斜" }, { "xie", "械" }, { "xie", "楔" }, { "xie", "榍" }, { "xie", "榭" }, { "xie", "歇" }, { "xie", "泄" },
			{ "xie", "泻" }, { "xie", "渫" }, { "xie", "滊" }, { "xie", "澥" }, { "xie", "瀉" }, { "xie", "瀣" }, { "xie", "灺" }, { "xie", "焎" }, { "xie", "熁" },
			{ "xie", "燮" }, { "xie", "燲" }, { "xie", "猲" }, { "xie", "獬" }, { "xie", "瑎" }, { "xie", "祄" }, { "xie", "絜" }, { "xie", "緳" }, { "xie", "繲" },
			{ "xie", "纈" }, { "xie", "绁" }, { "xie", "缬" }, { "xie", "胁" }, { "xie", "脅" }, { "xie", "脇" }, { "xie", "薢" }, { "xie", "薤" }, { "xie", "蝎" },
			{ "xie", "蝢" }, { "xie", "蟹" }, { "xie", "蠍" }, { "xie", "蠏" }, { "xie", "血" }, { "xie", "裌" }, { "xie", "褉" }, { "xie", "褻" }, { "xie", "襭" },
			{ "xie", "觟" }, { "xie", "解" }, { "xie", "觧" }, { "xie", "諧" }, { "xie", "謝" }, { "xie", "谐" }, { "xie", "谢" }, { "xie", "躞" }, { "xie", "躠" },
			{ "xie", "邂" }, { "xie", "邪" }, { "xie", "鞋" }, { "xie", "韰" }, { "xie", "颉" }, { "xie", "魼" }, { "xie", "鮭" }, { "xie", "齂" }, { "xie", "齘" },
			{ "xie", "齛" }, { "xie", "齥" }, { "xie", "龤" }, { "xie ba", "写吧" }, { "xie ban", "协办" }, { "xie bo", "谐波" }, { "xie bo ke", "写博客" },
			{ "xie cha", "斜插" }, { "xie chang ting", "谢长廷" }, { "xie cheng", "写成" }, { "xie cheng", "携程" }, { "xie chi", "挟持" }, { "xie chu", "写出" },
			{ "xie chu lai", "写出来" }, { "xie cuo", "写错" }, { "xie dai", "懈怠" }, { "xie dai", "携带" }, { "xie dai", "鞋带" }, { "xie dai zhe", "携带者" },
			{ "xie dao", "写到" }, { "xie dao", "写道" }, { "xie de", "写得" }, { "xie de", "写的" }, { "xie di", "鞋底" }, { "xie dian", "写点" }, { "xie dian", "鞋垫" },
			{ "xie diao", "卸掉" }, { "xie ding", "协定" }, { "xie du", "亵渎" }, { "xie dui mian", "斜对面" }, { "xie e", "邪恶" }, { "xie fa", "写法" },
			{ "xie fang", "协防" }, { "xie gao", "写稿" }, { "xie ge", "写个" }, { "xie ge", "写歌" }, { "xie gei", "写给" }, { "xie guan yuan", "协管员" },
			{ "xie guo", "写过" }, { "xie guo", "谢过" }, { "xie hao", "写好" }, { "xie he", "协和" }, { "xie hou", "邂逅" }, { "xie hui", "协会" },
			{ "xie hui hui yuan", "协会会员" }, { "xie hui hui zhang", "协会会长" }, { "xie jiao", "邪教" }, { "xie jin", "写进" }, { "xie jin", "谢晋" },
			{ "xie jue", "谢绝" }, { "xie la", "谢拉" }, { "xie le", "写了" }, { "xie lei", "鞋类" }, { "xie li", "协力" }, { "xie lou", "泄漏" }, { "xie lou", "泄露" },
			{ "xie lu", "泄露" }, { "xie lun wen", "写论文" }, { "xie man", "写满" }, { "xie men", "邪门" }, { "xie mi", "泄密" }, { "xie ming", "写明" },
			{ "xie mu", "谢幕" }, { "xie na", "谢娜" }, { "xie po", "斜坡" }, { "xie po", "胁迫" }, { "xie qi", "泄气" }, { "xie qi", "邪气" }, { "xie qian", "些钱" },
			{ "xie ren", "卸任" }, { "xie ri ji", "写日记" }, { "xie ru", "写入" }, { "xie shang", "写上" }, { "xie shang", "协商" }, { "xie shen me", "些什么" },
			{ "xie sheng", "写生" }, { "xie shi", "写实" }, { "xie shi", "写诗" }, { "xie shou", "写手" }, { "xie shou", "携手" }, { "xie shu", "写书" },
			{ "xie si di li", "歇斯底里" }, { "xie tian xie di", "谢天谢地" }, { "xie tiao", "协调" }, { "xie tiao fa zhan", "协调发展" }, { "xie tiao ji zhi", "协调机制" },
			{ "xie tiao xing", "协调性" }, { "xie ting feng", "谢霆锋" }, { "xie tong", "协同" }, { "xie wan", "写完" }, { "xie wen dong", "谢文东" },
			{ "xie wen zhang", "写文章" }, { "xie xi", "歇息" }, { "xie xia", "写下" }, { "xie xia", "卸下" }, { "xie xie", "写些" }, { "xie xie", "写写" },
			{ "xie xie", "歇歇" }, { "xie xie", "谢谢" }, { "xie xie da jia", "谢谢大家" }, { "xie xie he zuo", "谢谢合作" }, { "xie xie le", "谢谢了" }, { "xie xin", "写信" },
			{ "xie xu", "些许" }, { "xie ya long", "谢亚龙" }, { "xie yang", "斜阳" }, { "xie ye", "鞋业" }, { "xie yi", "写意" }, { "xie yi", "协议" }, { "xie yi", "谢意" },
			{ "xie yi pian", "写一篇" }, { "xie yi shu", "协议书" }, { "xie yin", "谐音" }, { "xie you", "写有" }, { "xie zai", "写在" }, { "xie zai", "卸载" },
			{ "xie zhao", "写照" }, { "xie zhe", "写着" }, { "xie zhe", "歇着" }, { "xie zhen", "写真" }, { "xie zhen ji", "写真集" }, { "xie zhu", "协助" },
			{ "xie zhuang", "卸妆" }, { "xie zi", "写字" }, { "xie zi", "蝎子" }, { "xie zi", "鞋子" }, { "xie zi lou", "写字楼" }, { "xie zou qu", "协奏曲" },
			{ "xie zui", "谢罪" }, { "xie zuo", "写作" }, { "xie zuo", "协作" }, { "xie zuo wen", "写作文" }, { "xin", "伈" }, { "xin", "信" }, { "xin", "噺" },
			{ "xin", "囟" }, { "xin", "妡" }, { "xin", "寻" }, { "xin", "庍" }, { "xin", "廞" }, { "xin", "心" }, { "xin", "忄" }, { "xin", "忻" }, { "xin", "惞" },
			{ "xin", "愖" }, { "xin", "撢" }, { "xin", "新" }, { "xin", "昕" }, { "xin", "杺" }, { "xin", "枔" }, { "xin", "橝" }, { "xin", "欣" }, { "xin", "歆" },
			{ "xin", "潃" }, { "xin", "炘" }, { "xin", "焮" }, { "xin", "盺" }, { "xin", "礥" }, { "xin", "舋" }, { "xin", "芯" }, { "xin", "莘" }, { "xin", "薪" },
			{ "xin", "衅" }, { "xin", "辛" }, { "xin", "釁" }, { "xin", "鈊" }, { "xin", "鋅" }, { "xin", "鐔" }, { "xin", "鑫" }, { "xin", "锌" }, { "xin", "镡" },
			{ "xin", "阠" }, { "xin", "馨" }, { "xin", "馫" }, { "xin", "鬵" }, { "xin ai", "心爱" }, { "xin an", "心安" }, { "xin an", "新安" },
			{ "xin an li de", "心安理得" }, { "xin ao er liang", "新奥尔良" }, { "xin ban", "新办" }, { "xin ban", "新版" }, { "xin bian", "新编" }, { "xin bing", "心病" },
			{ "xin bing", "新兵" }, { "xin bu", "信步" }, { "xin bu zai yan", "心不在焉" }, { "xin chan bu", "信产部" }, { "xin chang", "心肠" }, { "xin chang", "新昌" },
			{ "xin chao", "新潮" }, { "xin che", "新车" }, { "xin chen dai xie", "新陈代谢" }, { "xin cheng", "新城" }, { "xin cheng qu", "新城区" }, { "xin chong", "新宠" },
			{ "xin chou", "薪酬" }, { "xin chu", "新出" }, { "xin chun", "新春" }, { "xin ci", "新词" }, { "xin cun", "心存" }, { "xin cun", "新村" }, { "xin da", "信达" },
			{ "xin da lu", "新大陆" }, { "xin dai", "信贷" }, { "xin dan", "新蛋" }, { "xin dao", "信道" }, { "xin de", "心得" }, { "xin de", "新的" },
			{ "xin de guo", "信得过" }, { "xin de li", "新德里" }, { "xin de ti hui", "心得体会" }, { "xin di", "心地" }, { "xin di", "心底" }, { "xin di", "新低" },
			{ "xin dian", "新店" }, { "xin dian tu", "心电图" }, { "xin dong", "心动" }, { "xin dong fang", "新东方" }, { "xin dou", "心都" }, { "xin fa", "心法" },
			{ "xin fa", "新发" }, { "xin fa", "新法" }, { "xin fan", "心烦" }, { "xin fan", "新番" }, { "xin fang", "信访" }, { "xin fang", "心房" }, { "xin fang", "新房" },
			{ "xin fang gong zuo", "信访工作" }, { "xin fei", "心扉" }, { "xin fei", "心肺" }, { "xin feng", "信奉" }, { "xin feng", "信封" }, { "xin feng", "新风" },
			{ "xin fo", "信佛" }, { "xin fu", "信服" }, { "xin fu", "心腹" }, { "xin fu", "新服" }, { "xin gan", "心肝" }, { "xin gan qing yuan", "心甘情愿" },
			{ "xin gang", "新港" }, { "xin gao", "新高" }, { "xin ge", "新歌" }, { "xin ge", "辛格" }, { "xin gu", "新股" }, { "xin gu fa xing", "新股发行" },
			{ "xin gu shen gou", "新股申购" }, { "xin guang", "新光" }, { "xin gui", "新规" }, { "xin gui", "新贵" }, { "xin hai ge ming", "辛亥革命" }, { "xin han", "信函" },
			{ "xin han", "心寒" }, { "xin hao", "信号" }, { "xin hua", "新华" }, { "xin hua she", "新华社" }, { "xin hua shu dian", "新华书店" }, { "xin hua wang", "新华网" },
			{ "xin huai", "心怀" }, { "xin huan", "新欢" }, { "xin huang", "心慌" }, { "xin hui yi leng", "心灰意冷" }, { "xin hun", "新婚" }, { "xin huo", "新货" },
			{ "xin ji", "心急" }, { "xin ji", "心悸" }, { "xin ji", "心机" }, { "xin ji", "心肌" }, { "xin ji", "心计" }, { "xin ji", "新机" },
			{ "xin ji geng se", "心肌梗塞" }, { "xin ji ru fen", "心急如焚" }, { "xin ji yuan", "新纪元" }, { "xin jia", "新加" }, { "xin jia", "新家" },
			{ "xin jia po", "新加坡" }, { "xin jian", "信件" }, { "xin jian", "心间" }, { "xin jian", "新建" }, { "xin jiang", "新疆" }, { "xin jiang ren", "新疆人" },
			{ "xin jiao tong", "心绞痛" }, { "xin jie", "心结" }, { "xin jie kou", "新街口" }, { "xin jin", "新近" }, { "xin jin", "新进" }, { "xin jin", "薪金" },
			{ "xin jing", "心境" }, { "xin jing", "心惊" }, { "xin jing", "心经" }, { "xin jing", "心静" }, { "xin jing bao", "新京报" }, { "xin jing rou tiao", "心惊肉跳" },
			{ "xin jiu", "新旧" }, { "xin ju", "新剧" }, { "xin ju", "新居" }, { "xin jun", "新军" }, { "xin kai", "新开" }, { "xin ke", "新科" },
			{ "xin ke biao", "新课标" }, { "xin kou", "心口" }, { "xin ku", "辛苦" }, { "xin kuai bao", "新快报" }, { "xin kuan", "新款" },
			{ "xin kuang shen yi", "心旷神怡" }, { "xin la", "辛辣" } };
};
