package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN29 {
	public static String[][] pl = { { "lia", "俩" }, { "lia", "倆" }, { "lia ren", "俩人" }, { "lian", "僆" }, { "lian", "匳" }, { "lian", "嗹" }, { "lian", "堜" },
			{ "lian", "奁" }, { "lian", "奩" }, { "lian", "嬚" }, { "lian", "帘" }, { "lian", "廉" }, { "lian", "怜" }, { "lian", "恋" }, { "lian", "憐" },
			{ "lian", "戀" }, { "lian", "摙" }, { "lian", "敛" }, { "lian", "斂" }, { "lian", "楝" }, { "lian", "槤" }, { "lian", "歛" }, { "lian", "殓" },
			{ "lian", "殮" }, { "lian", "浰" }, { "lian", "涟" }, { "lian", "湅" }, { "lian", "漣" }, { "lian", "潋" }, { "lian", "澰" }, { "lian", "濂" },
			{ "lian", "瀲" }, { "lian", "炼" }, { "lian", "煉" }, { "lian", "琏" }, { "lian", "璉" }, { "lian", "磏" }, { "lian", "簾" }, { "lian", "練" },
			{ "lian", "縺" }, { "lian", "练" }, { "lian", "羷" }, { "lian", "翴" }, { "lian", "联" }, { "lian", "聨" }, { "lian", "聯" }, { "lian", "脸" },
			{ "lian", "臁" }, { "lian", "臉" }, { "lian", "莲" }, { "lian", "萰" }, { "lian", "蓮" }, { "lian", "蔹" }, { "lian", "薕" }, { "lian", "蠊" },
			{ "lian", "裢" }, { "lian", "裣" }, { "lian", "褳" }, { "lian", "襝" }, { "lian", "覝" }, { "lian", "謰" }, { "lian", "蹥" }, { "lian", "连" },
			{ "lian", "連" }, { "lian", "鄻" }, { "lian", "錬" }, { "lian", "鍊" }, { "lian", "鎌" }, { "lian", "鏈" }, { "lian", "鐮" }, { "lian", "链" },
			{ "lian", "镰" }, { "lian", "鬑" }, { "lian", "鰊" }, { "lian", "鰱" }, { "lian", "鲢" }, { "lian ai", "怜爱" }, { "lian ai", "恋爱" },
			{ "lian bai", "连败" }, { "lian bang", "联邦" }, { "lian bang zheng fu", "联邦政府" }, { "lian bao", "联保" }, { "lian biao", "链表" }, { "lian bing", "练兵" },
			{ "lian bo", "联播" }, { "lian bu", "脸部" }, { "lian bu shang", "连不上" }, { "lian cai", "敛财" }, { "lian che", "练车" }, { "lian cheng", "炼成" },
			{ "lian cheng", "练成" }, { "lian cheng", "联城" }, { "lian cheng", "连城" }, { "lian cheng", "连成" }, { "lian chi", "廉耻" }, { "lian chuang", "联创" },
			{ "lian da", "联大" }, { "lian dai", "连带" }, { "lian dai ze ren", "连带责任" }, { "lian dan", "脸蛋" }, { "lian dao", "练到" }, { "lian dao", "连到" },
			{ "lian dao", "镰刀" }, { "lian de", "练得" }, { "lian dong", "联动" }, { "lian dui", "联队" }, { "lian dui", "连队" }, { "lian fa", "连发" },
			{ "lian fang", "联防" }, { "lian gan", "连杆" }, { "lian gang", "炼钢" }, { "lian ge", "恋歌" }, { "lian ge", "连个" }, { "lian gong", "练功" },
			{ "lian guan", "连贯" }, { "lian guo", "练过" }, { "lian hao", "练好" }, { "lian he", "联合" }, { "lian he guo", "联合国" }, { "lian he hui", "联合会" },
			{ "lian he qi lai", "联合起来" }, { "lian he ti", "联合体" }, { "lian hong", "脸红" }, { "lian hua", "炼化" }, { "lian hua", "联华" }, { "lian hua", "莲花" },
			{ "lian huan", "连环" }, { "lian huan hua", "连环画" }, { "lian huan hui", "联欢会" }, { "lian ji", "练级" }, { "lian ji", "联机" }, { "lian ji", "连击" },
			{ "lian jia", "廉价" }, { "lian jia", "脸颊" }, { "lian jie", "廉洁" }, { "lian jie", "联接" }, { "lian jie", "联结" }, { "lian jie", "连接" },
			{ "lian jie", "连结" }, { "lian jie", "链接" }, { "lian jie chi", "连接池" }, { "lian jie di zhi", "链接地址" }, { "lian jie qi", "连接器" },
			{ "lian jie qi lai", "连接起来" }, { "lian jie shu", "连接数" }, { "lian jie xian", "连接线" }, { "lian jie zi lv", "廉洁自律" }, { "lian jin", "炼金" },
			{ "lian jiu", "练就" }, { "lian jun", "联军" }, { "lian kao", "联考" }, { "lian kong", "脸孔" }, { "lian lei", "连累" }, { "lian lian", "恋恋" },
			{ "lian lian", "练练" }, { "lian lian", "连连" }, { "lian lian bu she", "恋恋不舍" }, { "lian lian kan", "连连看" }, { "lian lu", "链路" },
			{ "lian luo", "联络" }, { "lian luo yuan", "联络员" }, { "lian mang", "连忙" }, { "lian mei", "联袂" }, { "lian meng", "联盟" }, { "lian meng bei", "联盟杯" },
			{ "lian mian", "脸面" }, { "lian mian", "连绵" }, { "lian min", "怜悯" }, { "lian ming", "联名" }, { "lian nian", "连年" }, { "lian pai", "连拍" },
			{ "lian pang", "脸庞" }, { "lian pen", "脸盆" }, { "lian peng", "莲蓬" }, { "lian pi", "脸皮" }, { "lian pi hou", "脸皮厚" }, { "lian pian", "连篇" },
			{ "lian pu", "脸谱" }, { "lian qing", "恋情" }, { "lian ren", "恋人" }, { "lian ren", "连任" }, { "lian ri", "连日" }, { "lian ri lai", "连日来" },
			{ "lian sai", "联赛" }, { "lian se", "脸色" }, { "lian shang", "恋上" }, { "lian shang", "脸上" }, { "lian shang", "连上" }, { "lian she", "联社" },
			{ "lian sheng", "连声" }, { "lian sheng", "连胜" }, { "lian shou", "联手" }, { "lian suo", "连锁" }, { "lian suo dian", "连锁店" },
			{ "lian suo fan ying", "连锁反应" }, { "lian suo jing ying", "连锁经营" }, { "lian suo qi ye", "连锁企业" }, { "lian ti", "连体" }, { "lian tian", "连天" },
			{ "lian tiao", "联调" }, { "lian tiao", "链条" }, { "lian tong", "联通" }, { "lian tong", "连同" }, { "lian tong", "连通" }, { "lian wang", "联网" },
			{ "lian wo", "连我" }, { "lian xi", "怜惜" }, { "lian xi", "练习" }, { "lian xi", "联系" }, { "lian xi dian hua", "联系电话" }, { "lian xi fang shi", "联系方式" },
			{ "lian xi hui yi", "联席会议" }, { "lian xi qi lai", "联系起来" }, { "lian xi ren", "联系人" }, { "lian xi ti", "练习题" }, { "lian xian", "连线" },
			{ "lian xiang", "联想" }, { "lian xiang ji tuan", "联想集团" }, { "lian xing", "脸型" }, { "lian xu", "连续" }, { "lian xu ju", "连续剧" },
			{ "lian xu xing", "连续性" }, { "lian ye", "连夜" }, { "lian yi", "涟漪" }, { "lian yi", "联谊" }, { "lian yi hui", "联谊会" }, { "lian yi qun", "连衣裙" },
			{ "lian yin", "联姻" }, { "lian ying", "联营" }, { "lian you", "炼油" }, { "lian you chang", "炼油厂" }, { "lian yu", "炼狱" }, { "lian yun gang", "连云港" },
			{ "lian zai", "连载" }, { "lian zai yi qi", "连在一起" }, { "lian zhan", "连战" }, { "lian zhang", "连长" }, { "lian zhe", "连着" }, { "lian zheng", "廉政" },
			{ "lian zheng jian she", "廉政建设" }, { "lian zhong", "联众" }, { "lian zi", "帘子" }, { "lian zi", "莲子" }, { "lian zi", "链子" },
			{ "lian zu fang", "廉租房" }, { "lian zu zhu fang", "廉租住房" }, { "liang", "両" }, { "liang", "两" }, { "liang", "亮" }, { "liang", "俍" },
			{ "liang", "俩" }, { "liang", "倞" }, { "liang", "兩" }, { "liang", "凉" }, { "liang", "啢" }, { "liang", "喨" }, { "liang", "墚" }, { "liang", "悢" },
			{ "liang", "晾" }, { "liang", "梁" }, { "liang", "椋" }, { "liang", "樑" }, { "liang", "涼" }, { "liang", "湸" }, { "liang", "簗" }, { "liang", "粮" },
			{ "liang", "粱" }, { "liang", "糧" }, { "liang", "綡" }, { "liang", "緉" }, { "liang", "良" }, { "liang", "蜋" }, { "liang", "裲" }, { "liang", "諒" },
			{ "liang", "谅" }, { "liang", "踉" }, { "liang", "輌" }, { "liang", "輛" }, { "liang", "輬" }, { "liang", "辆" }, { "liang", "量" }, { "liang", "鍄" },
			{ "liang", "靓" }, { "liang", "靚" }, { "liang", "駺" }, { "liang", "魉" }, { "liang", "魎" }, { "liang an", "两岸" }, { "liang an guan xi", "两岸关系" },
			{ "liang an jing mao", "两岸经贸" }, { "liang ba", "两把" }, { "liang bai", "两百" }, { "liang ban", "两半" }, { "liang ban", "凉拌" }, { "liang bao", "两包" },
			{ "liang bei", "两倍" }, { "liang bei", "两杯" }, { "liang ben", "两本" }, { "liang bi", "两笔" }, { "liang bi", "量比" }, { "liang bian", "两边" },
			{ "liang bian", "两遍" }, { "liang bian", "量变" }, { "liang biao", "量表" }, { "liang bu", "两步" }, { "liang bu", "两部" }, { "liang bu fen", "两部分" },
			{ "liang bu wu", "两不误" }, { "liang cai", "凉菜" }, { "liang cang", "粮仓" }, { "liang cao", "粮草" }, { "liang ce", "两侧" }, { "liang ceng", "两层" },
			{ "liang cha", "凉茶" }, { "liang chan", "量产" }, { "liang chang", "两场" }, { "liang chao wei", "梁朝伟" }, { "liang che", "两车" }, { "liang che", "辆车" },
			{ "liang cheng", "两成" }, { "liang chu", "两处" }, { "liang chu", "亮出" }, { "liang ci", "两次" }, { "liang da", "两大" }, { "liang da", "量大" },
			{ "liang da lei", "两大类" }, { "liang dai", "两代" }, { "liang dang", "两党" }, { "liang dao", "两道" }, { "liang di", "两地" }, { "liang dian", "两点" },
			{ "liang dian", "亮点" }, { "liang du", "两度" }, { "liang du", "亮度" }, { "liang duan", "两段" }, { "liang duan", "两端" }, { "liang dui", "两对" },
			{ "liang dui", "两队" }, { "liang duo", "良多" }, { "liang fa", "两罚" }, { "liang fang", "两房" }, { "liang fang", "两方" }, { "liang fang", "良方" },
			{ "liang fang mian", "两方面" }, { "liang fen", "两份" }, { "liang fen", "两分" }, { "liang fen", "凉粉" }, { "liang fen zhong", "两分钟" },
			{ "liang feng", "凉风" }, { "liang fu", "两幅" }, { "liang gan", "晾干" }, { "liang ge", "两个" }, { "liang ge fang mian", "两个方面" },
			{ "liang ge hai zi", "两个孩子" }, { "liang ge nan ren", "两个男人" }, { "liang ge nv ren", "两个女人" }, { "liang ge ren", "两个人" }, { "liang ge yue", "两个月" },
			{ "liang ge zi", "两个字" }, { "liang gen", "两根" }, { "liang guang", "亮光" }, { "liang guo", "两国" }, { "liang hang", "两行" }, { "liang hao", "良好" },
			{ "liang hao xing xiang", "良好形象" }, { "liang hua", "量化" }, { "liang hui", "两会" }, { "liang hui shi", "两回事" }, { "liang ji", "两季" },
			{ "liang ji", "两极" }, { "liang ji", "两级" }, { "liang ji", "两集" }, { "liang ji", "良机" }, { "liang ji fen hua", "两极分化" }, { "liang jia", "两家" },
			{ "liang jia", "两架" }, { "liang jia", "粮价" }, { "liang jia hui", "梁家辉" }, { "liang jian", "两件" }, { "liang jian", "两间" }, { "liang jian", "亮剑" },
			{ "liang jiao", "两脚" }, { "liang jie", "两届" }, { "liang jie", "两节" }, { "liang jie", "谅解" }, { "liang jing jing", "亮晶晶" },
			{ "liang jing ru", "梁静茹" }, { "liang jiu", "良久" }, { "liang ju", "两句" }, { "liang ju", "两居" }, { "liang jun", "两军" }, { "liang ke", "两颗" },
			{ "liang kou", "两口" }, { "liang kou zi", "两口子" }, { "liang kuai", "两块" }, { "liang kuai", "凉快" }, { "liang kuan", "两款" }, { "liang le", "亮了" },
			{ "liang le", "凉了" }, { "liang lei", "两类" }, { "liang li", "两粒" }, { "liang li", "亮丽" }, { "liang li", "靓丽" }, { "liang li er xing", "量力而行" },
			{ "liang liang", "两辆" }, { "liang liang", "亮亮" }, { "liang liang", "凉凉" }, { "liang lu", "两路" }, { "liang lun", "两轮" }, { "liang ma shi", "两码事" },
			{ "liang mei", "两枚" }, { "liang men", "两门" }, { "liang mi", "两米" }, { "liang mian", "两面" }, { "liang min", "良民" }, { "liang ming", "两名" },
			{ "liang nan", "两难" }, { "liang neng", "量能" }, { "liang nian", "两年" }, { "liang nian hou", "两年后" }, { "liang nian nei", "两年内" },
			{ "liang nian qian", "两年前" }, { "liang nv", "靓女" }, { "liang pai", "两排" }, { "liang pai", "两派" }, { "liang pan", "两盘" }, { "liang pang", "两旁" },
			{ "liang pi", "凉皮" }, { "liang pian", "两片" }, { "liang pian", "两篇" }, { "liang ping", "两瓶" }, { "liang qi", "两期" }, { "liang qi", "两起" },
			{ "liang qi", "亮起" }, { "liang qi chao", "梁启超" }, { "liang qian", "两千" }, { "liang qian duo", "两千多" }, { "liang qiang", "踉跄" },
			{ "liang qiu", "两球" }, { "liang quan", "两圈" }, { "liang ren", "两人" }, { "liang ri", "两日" }, { "liang san", "两三" }, { "liang san tian", "两三天" },
			{ "liang shai", "晾晒" }, { "liang shan", "梁山" }, { "liang shan bo", "梁山伯" }, { "liang shao", "量少" }, { "liang shen", "量身" },
			{ "liang shen ding zuo", "量身定做" }, { "liang sheng", "两声" }, { "liang sheng", "两省" }, { "liang shi", "两市" }, { "liang shi", "粮食" },
			{ "liang shi an quan", "粮食安全" }, { "liang shi ju", "粮食局" }, { "liang shi sheng chan", "粮食生产" }, { "liang shou", "两手" }, { "liang shou", "两首" },
			{ "liang shuang", "两双" }, { "liang shuang", "凉爽" }, { "liang shui", "凉水" }, { "liang sou", "两艘" }, { "liang sui", "两岁" }, { "liang tai", "两台" },
			{ "liang tao", "两套" }, { "liang tian", "两天" }, { "liang tian", "良田" }, { "liang tiao", "两条" }, { "liang tou", "两头" }, { "liang tui", "两腿" },
			{ "liang wan", "两万" }, { "liang wan yuan", "两万元" }, { "liang wei", "两位" }, { "liang wei", "两委" }, { "liang wei", "量为" },
			{ "liang wei shu", "两位数" }, { "liang xi", "凉席" }, { "liang xia", "两下" }, { "liang xiang", "两厢" }, { "liang xiang", "两相" }, { "liang xiang", "两项" },
			{ "liang xiang", "亮相" }, { "liang xiang che", "两厢车" }, { "liang xiao shi", "两小时" }, { "liang xie", "凉鞋" }, { "liang xin", "良心" },
			{ "liang xing", "两性" }, { "liang xing", "良性" }, { "liang xing", "量刑" }, { "liang xing xun huan", "良性循环" }, { "liang xiong di", "两兄弟" },
			{ "liang yan", "两眼" }, { "liang yang", "两样" }, { "liang yao", "良药" }, { "liang ye", "两页" }, { "liang yi", "两亿" }, { "liang yi", "两翼" },
			{ "liang yi", "凉意" }, { "liang yin zi", "两银子" }, { "liang ying", "靓颖" }, { "liang yong", "两用" }, { "liang yong qi", "梁咏琪" }, { "liang you", "粮油" },
			{ "liang you bu qi", "良莠不齐" }, { "liang yuan", "两元" }, { "liang yue", "两月" }, { "liang zai", "靓仔" }, { "liang zhan", "两站" },
			{ "liang zhang", "两张" }, { "liang zhao", "靓照" }, { "liang zhe", "两者" }, { "liang zhe", "亮着" }, { "liang zhi", "两只" }, { "liang zhi", "两支" },
			{ "liang zhi", "良知" }, { "liang zhong", "两种" }, { "liang zhong", "良种" }, { "liang zhou", "两周" }, { "liang zhu", "梁祝" }, { "liang zi", "两字" },
			{ "liang zi", "量子" }, { "liang zu", "两组" }, { "liang zuo", "两座" }, { "liao", "了" }, { "liao", "僚" }, { "liao", "嘹" }, { "liao", "嫽" },
			{ "liao", "寥" }, { "liao", "寮" }, { "liao", "尞" }, { "liao", "尥" }, { "liao", "屪" }, { "liao", "嵺" }, { "liao", "嶚" }, { "liao", "廖" },
			{ "liao", "憀" }, { "liao", "憭" }, { "liao", "摎" }, { "liao", "撂" }, { "liao", "撩" }, { "liao", "敹" }, { "liao", "料" }, { "liao", "暸" },
			{ "liao", "樛" }, { "liao", "潦" }, { "liao", "炓" }, { "liao", "燎" }, { "liao", "獠" }, { "liao", "疗" }, { "liao", "療" }, { "liao", "瞭" },
			{ "liao", "窌" }, { "liao", "窷" }, { "liao", "簝" }, { "liao", "繚" }, { "liao", "缭" }, { "liao", "聊" }, { "liao", "膋" }, { "liao", "膫" },
			{ "liao", "蓼" }, { "liao", "蟟" }, { "liao", "蟧" }, { "liao", "豂" }, { "liao", "轑" }, { "liao", "辽" }, { "liao", "遼" }, { "liao", "鄝" },
			{ "liao", "釕" }, { "liao", "鐐" }, { "liao", "钌" }, { "liao", "镣" }, { "liao", "镽" }, { "liao", "飂" }, { "liao", "飉" }, { "liao", "鷯" },
			{ "liao", "鹩" }, { "liao ba", "聊吧" }, { "liao bu qi", "了不起" }, { "liao cheng", "疗程" }, { "liao cheng", "聊城" }, { "liao dao", "料到" },
			{ "liao dao", "聊到" }, { "liao de", "了得" }, { "liao de", "聊得" }, { "liao dong", "辽东" }, { "liao duan", "了断" }, { "liao fa", "疗法" },
			{ "liao fa zhi liao", "疗法治疗" }, { "liao guo", "聊过" }, { "liao jie", "了结" }, { "liao jie", "了解" }, { "liao jie yi xia", "了解一下" },
			{ "liao jie zi ji", "了解自己" }, { "liao jiu", "料酒" }, { "liao kuo", "辽阔" }, { "liao li", "料理" }, { "liao liang", "嘹亮" }, { "liao liao", "寥寥" },
			{ "liao liao", "聊聊" }, { "liao liao tian", "聊聊天" }, { "liao liao wu ji", "寥寥无几" }, { "liao ning", "辽宁" }, { "liao ning dui", "辽宁队" },
			{ "liao ning sheng", "辽宁省" }, { "liao qi", "聊起" }, { "liao ran", "了然" }, { "liao rao", "缭绕" }, { "liao ren", "撩人" },
			{ "liao ru zhi zhang", "了如指掌" }, { "liao shang", "疗伤" }, { "liao tian", "聊天" }, { "liao tian ji lu", "聊天记录" }, { "liao tian shi", "聊天室" },
			{ "liao xiao", "疗效" }, { "liao xiao guan cha", "疗效观察" }, { "liao yang", "疗养" }, { "liao yang", "辽阳" }, { "liao yang yuan", "疗养院" },
			{ "liao zhai", "聊斋" }, { "liao zhe", "聊着" }, { "liao zi", "料子" }, { "liao zu", "辽足" }, { "lie", "儠" }, { "lie", "冽" }, { "lie", "列" },
			{ "lie", "劣" }, { "lie", "咧" }, { "lie", "埒" }, { "lie", "埓" }, { "lie", "姴" }, { "lie", "捩" }, { "lie", "擸" }, { "lie", "櫑" }, { "lie", "毟" },
			{ "lie", "洌" }, { "lie", "烈" }, { "lie", "犣" }, { "lie", "猎" }, { "lie", "猟" }, { "lie", "獵" }, { "lie", "睙" }, { "lie", "綟" }, { "lie", "茢" },
			{ "lie", "蛚" }, { "lie", "裂" }, { "lie", "趔" }, { "lie", "躐" }, { "lie", "迾" }, { "lie", "颲" }, { "lie", "鬣" }, { "lie", "鮤" }, { "lie", "鴷" },
			{ "lie bao", "猎豹" }, { "lie biao", "列表" }, { "lie biao zhong", "列表中" }, { "lie che", "列车" }, { "lie chu", "列出" }, { "lie dui", "列队" },
			{ "lie feng", "裂缝" }, { "lie gen xing", "劣根性" }, { "lie hen", "裂痕" }, { "lie huo", "烈火" }, { "lie jie", "裂解" }, { "lie ju", "列举" },
			{ "lie kai", "裂开" }, { "lie ming", "列明" }, { "lie ning", "列宁" }, { "lie qi", "猎奇" }, { "lie qiang", "列强" }, { "lie qiang", "猎枪" },
			{ "lie ren", "猎人" }, { "lie ri", "烈日" }, { "lie ru", "列入" }, { "lie sha", "猎杀" }, { "lie shi", "劣势" }, { "lie shi", "烈士" },
			{ "lie shi ling yuan", "烈士陵园" }, { "lie shou", "猎手" }, { "lie tou", "猎头" }, { "lie wei", "列为" }, { "lie wen", "裂纹" }, { "lie wu", "猎物" },
			{ "lie xi", "列席" }, { "lie yan", "烈焰" }, { "lie zhi", "列支" }, { "lie zhi", "劣质" }, { "lie zhuan", "列传" }, { "lie zui", "咧嘴" }, { "lin", "临" },
			{ "lin", "亃" }, { "lin", "僯" }, { "lin", "凛" }, { "lin", "凜" }, { "lin", "吝" }, { "lin", "啉" }, { "lin", "壣" }, { "lin", "嶙" }, { "lin", "廩" },
			{ "lin", "廪" }, { "lin", "悋" }, { "lin", "惏" }, { "lin", "懍" }, { "lin", "懔" }, { "lin", "拎" }, { "lin", "暽" }, { "lin", "林" }, { "lin", "橉" },
			{ "lin", "檁" }, { "lin", "檩" }, { "lin", "淋" }, { "lin", "潾" }, { "lin", "焛" }, { "lin", "燐" }, { "lin", "琳" }, { "lin", "璘" }, { "lin", "甐" },
			{ "lin", "疄" }, { "lin", "瞵" }, { "lin", "碄" }, { "lin", "磷" }, { "lin", "箖" }, { "lin", "粼" }, { "lin", "繗" }, { "lin", "翷" }, { "lin", "膦" },
			{ "lin", "臨" }, { "lin", "菻" }, { "lin", "蔺" }, { "lin", "藺" }, { "lin", "賃" }, { "lin", "赁" }, { "lin", "蹸" }, { "lin", "躏" }, { "lin", "躙" },
			{ "lin", "躪" }, { "lin", "轔" }, { "lin", "辚" }, { "lin", "遴" }, { "lin", "邻" }, { "lin", "鄰" }, { "lin", "鏻" }, { "lin", "閵" }, { "lin", "隣" },
			{ "lin", "霖" }, { "lin", "顲" }, { "lin", "驎" }, { "lin", "鱗" }, { "lin", "鳞" }, { "lin", "麟" }, { "lin an", "临安" }, { "lin ba", "淋巴" },
			{ "lin ba jie", "淋巴结" }, { "lin ba xi bao", "淋巴细胞" }, { "lin biao", "林彪" }, { "lin bing", "淋病" }, { "lin chang", "临场" }, { "lin chang", "林场" },
			{ "lin chong", "林冲" }, { "lin chuang", "临床" }, { "lin chuang biao xian", "临床表现" }, { "lin chuang shi yan", "临床试验" },
			{ "lin chuang yan jiu", "临床研究" }, { "lin chuang yi xue", "临床医学" }, { "lin chuang yi yi", "临床意义" }, { "lin chuang ying yong", "临床应用" },
			{ "lin chuang zheng zhuang", "临床症状" }, { "lin dai yu", "林黛玉" }, { "lin dan", "林丹" }, { "lin di", "林地" }, { "lin fen", "临汾" }, { "lin feng", "临风" },
			{ "lin feng", "林峰" }, { "lin gang", "临港" }, { "lin guo", "邻国" }, { "lin hai", "临海" }, { "lin hai", "林海" }, { "lin jia", "林家" },
			{ "lin jia", "邻家" }, { "lin jian", "林间" }, { "lin jiang", "临江" }, { "lin jie", "临界" }, { "lin jie", "临街" }, { "lin jie dian", "临界点" },
			{ "lin jin", "临近" }, { "lin jin", "邻近" }, { "lin ju", "邻居" }, { "lin ju jia", "邻居家" }, { "lin jun jie", "林俊杰" }, { "lin ken", "林肯" },
			{ "lin lang man mu", "琳琅满目" }, { "lin li", "林立" }, { "lin li", "淋漓" }, { "lin li", "邻里" }, { "lin li jin zhi", "淋漓尽致" }, { "lin lie", "凛冽" },
			{ "lin lin", "琳琳" }, { "lin mei mei", "林妹妹" }, { "lin mo", "临摹" }, { "lin mu", "林木" }, { "lin na", "琳娜" }, { "lin pian", "鳞片" },
			{ "lin qi", "林奇" }, { "lin qing xia", "林青霞" }, { "lin qu", "林区" }, { "lin se", "吝啬" }, { "lin shi", "临时" }, { "lin shi", "淋湿" },
			{ "lin shi gong", "临时工" }, { "lin shi wen jian", "临时文件" }, { "lin shi xing", "临时性" }, { "lin shui", "临睡" }, { "lin si", "临死" },
			{ "lin suan", "磷酸" }, { "lin xi", "林夕" }, { "lin xin ru", "林心如" }, { "lin xing", "临行" }, { "lin xuan", "遴选" }, { "lin ye", "林业" },
			{ "lin ye ju", "林业局" }, { "lin ye ting", "林业厅" }, { "lin yi", "临沂" }, { "lin yi lian", "林忆莲" }, { "lin yi shi", "临沂市" }, { "lin yu", "淋浴" },
			{ "lin yu", "淋雨" }, { "lin zhe", "拎着" }, { "lin zhi ling", "林志玲" }, { "lin zhi ying", "林志颖" }, { "lin zhong", "临终" }, { "lin zhong", "林中" },
			{ "lin zi", "林子" }, { "lin zong", "林总" }, { "lin zou", "临走" }, { "ling", "〇" }, { "ling", "令" }, { "ling", "伶" }, { "ling", "倰" }, { "ling", "凌" },
			{ "ling", "另" }, { "ling", "呤" }, { "ling", "囹" }, { "ling", "坽" }, { "ling", "夌" }, { "ling", "姈" }, { "ling", "婈" }, { "ling", "岭" },
			{ "ling", "岺" }, { "ling", "崚" }, { "ling", "嶺" }, { "ling", "彾" }, { "ling", "昤" }, { "ling", "朎" }, { "ling", "柃" }, { "ling", "棂" },
			{ "ling", "棱" }, { "ling", "櫺" }, { "ling", "欞" }, { "ling", "泠" }, { "ling", "淩" }, { "ling", "澪" }, { "ling", "灵" }, { "ling", "炩" },
			{ "ling", "爧" }, { "ling", "狑" }, { "ling", "玲" }, { "ling", "琌" }, { "ling", "瓴" }, { "ling", "皊" }, { "ling", "砱" }, { "ling", "笭" },
			{ "ling", "綾" }, { "ling", "绫" }, { "ling", "羚" }, { "ling", "翎" }, { "ling", "聆" }, { "ling", "舲" }, { "ling", "苓" }, { "ling", "菱" },
			{ "ling", "蔆" }, { "ling", "蕶" }, { "ling", "蘦" }, { "ling", "蛉" }, { "ling", "裬" }, { "ling", "詅" }, { "ling", "軨" }, { "ling", "輘" },
			{ "ling", "酃" }, { "ling", "醽" }, { "ling", "鈴" }, { "ling", "錂" }, { "ling", "铃" }, { "ling", "陵" }, { "ling", "零" }, { "ling", "霊" },
			{ "ling", "霝" }, { "ling", "靈" }, { "ling", "領" }, { "ling", "领" }, { "ling", "駖" }, { "ling", "鯪" }, { "ling", "鲮" }, { "ling", "鴒" },
			{ "ling", "齡" }, { "ling", "齢" }, { "ling", "龄" }, { "ling ban", "领班" }, { "ling bu jian", "零部件" }, { "ling chen", "凌晨" }, { "ling cun", "另存" },
			{ "ling cun wei", "另存为" }, { "ling dai", "领带" }, { "ling dang", "铃铛" }, { "ling dang bie lun", "另当别论" }, { "ling dao", "领到" },
			{ "ling dao", "领导" }, { "ling dao ban zi", "领导班子" }, { "ling dao ceng", "领导层" }, { "ling dao gan bu", "领导干部" }, { "ling dao ji ti", "领导集体" },
			{ "ling dao li", "领导力" }, { "ling dao ren", "领导人" }, { "ling dao xiao zu", "领导小组" }, { "ling dao zhe", "领导者" }, { "ling di", "领地" },
			{ "ling dian", "零点" }, { "ling dong", "灵动" }, { "ling du", "零度" }, { "ling dui", "领队" }, { "ling er", "灵儿" }, { "ling gan", "灵感" },
			{ "ling guang", "灵光" }, { "ling hang", "领航" }, { "ling hu", "令狐" }, { "ling hu chong", "令狐冲" }, { "ling hua qian", "零花钱" }, { "ling hui", "领会" },
			{ "ling hun", "灵魂" }, { "ling huo", "灵活" }, { "ling huo xing", "灵活性" }, { "ling jia", "凌驾" }, { "ling jia", "另加" }, { "ling jian", "零件" },
			{ "ling jiang", "领奖" }, { "ling jiang tai", "领奖台" }, { "ling jiao", "领教" }, { "ling ju", "另据" }, { "ling ju li", "零距离" }, { "ling jun", "领军" },
			{ "ling jun ren wu", "领军人物" }, { "ling kong", "凌空" }, { "ling kou", "领口" }, { "ling lei", "另类" }, { "ling li", "伶俐" }, { "ling li", "凌厉" },
			{ "ling li", "灵力" }, { "ling ling", "玲玲" }, { "ling long", "玲珑" }, { "ling luan", "凌乱" }, { "ling lue", "领略" }, { "ling min", "灵敏" },
			{ "ling min du", "灵敏度" }, { "ling mu", "铃木" }, { "ling mu", "陵墓" }, { "ling nan", "岭南" }, { "ling ni", "令你" }, { "ling pai", "令牌" },
			{ "ling pao", "领跑" }, { "ling pei jian", "零配件" }, { "ling qi", "令其" }, { "ling qi", "灵气" }, { "ling qian", "零钱" }, { "ling qiao", "灵巧" },
			{ "ling qing", "领情" }, { "ling qu", "领取" }, { "ling ren", "令人" }, { "ling ren chi jing", "令人吃惊" }, { "ling ren dan you", "令人担忧" },
			{ "ling ren fa zhi", "令人发指" }, { "ling ren gan dong", "令人感动" }, { "ling ren man yi", "令人满意" }, { "ling ren xian mu", "令人羡慕" },
			{ "ling ren xin fu", "令人信服" }, { "ling ren zhen jing", "令人震惊" }, { "ling ren zhu mu", "令人瞩目" }, { "ling ru", "凌辱" }, { "ling san", "零散" },
			{ "ling shan", "灵山" }, { "ling sheng", "铃声" }, { "ling shi", "零时" }, { "ling shi", "零食" }, { "ling shi", "领事" }, { "ling shi guan", "领事馆" },
			{ "ling shou", "零售" }, { "ling shou dian", "零售店" }, { "ling shou e", "零售额" }, { "ling shou jia", "零售价" }, { "ling shou jia ge", "零售价格" },
			{ "ling shou qi ye", "零售企业" }, { "ling shou shang", "零售商" }, { "ling shou shi chang", "零售市场" } };
};
