package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN06 {
	public static String[][] pl = { { "chang yi", "倡议" }, { "chang yi", "常以" }, { "chang yi", "长椅" }, { "chang yi shu", "倡议书" }, { "chang yong", "常用" },
			{ "chang you", "常有" }, { "chang you", "畅游" }, { "chang yu", "长于" }, { "chang yuan", "长远" }, { "chang yue", "长约" }, { "chang zai", "常在" },
			{ "chang zhang", "厂长" }, { "chang zhe", "唱着" }, { "chang zhe", "长着" }, { "chang zheng", "长征" }, { "chang zhi", "长治" }, { "chang zhou", "常州" },
			{ "chang zhou shi", "常州市" }, { "chang zhu", "常住" }, { "chang zhu", "常驻" }, { "chang zi", "厂子" }, { "chang zi", "场子" }, { "chang zi", "肠子" },
			{ "chang zu", "长足" }, { "chao", "剿" }, { "chao", "吵" }, { "chao", "嘲" }, { "chao", "巐" }, { "chao", "巢" }, { "chao", "巣" }, { "chao", "弨" },
			{ "chao", "怊" }, { "chao", "抄" }, { "chao", "晁" }, { "chao", "朝" }, { "chao", "漅" }, { "chao", "潮" }, { "chao", "炒" }, { "chao", "焯" },
			{ "chao", "牊" }, { "chao", "眧" }, { "chao", "窲" }, { "chao", "绰" }, { "chao", "罺" }, { "chao", "耖" }, { "chao", "超" }, { "chao", "轈" },
			{ "chao", "鄛" }, { "chao", "鈔" }, { "chao", "钞" }, { "chao bai", "朝拜" }, { "chao bao", "超薄" }, { "chao biao", "抄表" }, { "chao biao", "超标" },
			{ "chao bo", "超薄" }, { "chao cai", "炒菜" }, { "chao chang", "超常" }, { "chao chang", "超长" }, { "chao chao", "吵吵" }, { "chao chao", "超超" },
			{ "chao che", "超车" }, { "chao chu", "超出" }, { "chao da", "超大" }, { "chao da xing", "超大型" }, { "chao dai", "朝代" }, { "chao dao", "超导" },
			{ "chao de", "吵得" }, { "chao de", "炒得" }, { "chao di", "抄底" }, { "chao di", "超低" }, { "chao di jia", "超低价" }, { "chao die", "超跌" },
			{ "chao duo", "超多" }, { "chao e", "超额" }, { "chao fan", "炒饭" }, { "chao fan", "超凡" }, { "chao fang", "炒房" }, { "chao feng", "嘲讽" },
			{ "chao fu he", "超负荷" }, { "chao gao", "超高" }, { "chao gu", "炒股" }, { "chao gu piao", "炒股票" }, { "chao guo", "炒锅" }, { "chao guo", "超过" },
			{ "chao he wen ti", "朝核问题" }, { "chao hu", "巢湖" }, { "chao hu", "超乎" }, { "chao ji", "超级" }, { "chao ji da guo", "超级大国" },
			{ "chao ji nv sheng", "超级女声" }, { "chao ji nv sheng", "超级女生" }, { "chao ji tu zi", "超级兔子" }, { "chao ji wu di", "超级无敌" }, { "chao jia", "吵架" },
			{ "chao jia", "炒家" }, { "chao ku", "超酷" }, { "chao le", "吵了" }, { "chao lian jie", "超链接" }, { "chao liu", "潮流" }, { "chao mian", "炒面" },
			{ "chao nan", "朝南" }, { "chao nao", "吵闹" }, { "chao neng", "超能" }, { "chao neng li", "超能力" }, { "chao nong", "嘲弄" }, { "chao nv", "超女" },
			{ "chao piao", "钞票" }, { "chao pin", "超频" }, { "chao qi", "超期" }, { "chao qian", "超前" }, { "chao qiang", "超强" }, { "chao qun", "超群" },
			{ "chao ran", "超然" }, { "chao ren", "超人" }, { "chao shan", "潮汕" }, { "chao shang", "朝上" }, { "chao sheng", "朝圣" }, { "chao sheng", "超声" },
			{ "chao sheng", "超生" }, { "chao sheng bo", "超声波" }, { "chao shi", "潮湿" }, { "chao shi", "超市" }, { "chao shi", "超时" }, { "chao shi li", "超市里" },
			{ "chao shui", "潮水" }, { "chao song", "抄送" }, { "chao su", "超速" }, { "chao tian", "朝天" }, { "chao ting", "朝廷" }, { "chao tuo", "超脱" },
			{ "chao wei", "超微" }, { "chao xi", "抄袭" }, { "chao xi", "潮汐" }, { "chao xi huan", "超喜欢" }, { "chao xia", "朝下" }, { "chao xian", "朝鲜" },
			{ "chao xian", "超限" }, { "chao xian ban dao", "朝鲜半岛" }, { "chao xian zhan zheng", "朝鲜战争" }, { "chao xian zu", "朝鲜族" }, { "chao xiang", "朝向" },
			{ "chao xiao", "嘲笑" }, { "chao xie", "抄写" }, { "chao xing", "吵醒" }, { "chao xing", "超星" }, { "chao xue", "巢穴" }, { "chao yang", "朝阳" },
			{ "chao yang qu", "朝阳区" }, { "chao ye", "朝野" }, { "chao yin su", "超音速" }, { "chao yue", "超越" }, { "chao zai", "超载" }, { "chao zhe", "吵着" },
			{ "chao zhe", "朝着" }, { "chao zhi", "超值" }, { "chao zhong", "朝中" }, { "chao zhong", "超重" }, { "chao zhou", "潮州" }, { "chao zuo", "炒作" },
			{ "che", "偖" }, { "che", "坼" }, { "che", "尺" }, { "che", "彻" }, { "che", "徹" }, { "che", "扯" }, { "che", "掣" }, { "che", "撤" }, { "che", "撦" },
			{ "che", "澈" }, { "che", "烢" }, { "che", "砗" }, { "che", "硨" }, { "che", "硩" }, { "che", "莗" }, { "che", "車" }, { "che", "车" }, { "che", "迠" },
			{ "che biao", "车标" }, { "che che", "车车" }, { "che chen", "车臣" }, { "che cheng", "车程" }, { "che chu", "撤出" }, { "che chuang", "车床" },
			{ "che chuang", "车窗" }, { "che ci", "车次" }, { "che dan", "扯淡" }, { "che dan", "扯蛋" }, { "che dan", "撤单" }, { "che dao", "扯到" },
			{ "che dao", "车道" }, { "che deng", "车灯" }, { "che di", "彻底" }, { "che di jie jue", "彻底解决" }, { "che diao", "撤掉" }, { "che ding", "车顶" },
			{ "che dui", "车队" }, { "che fei", "车费" }, { "che fu", "车夫" }, { "che guan suo", "车管所" }, { "che hang", "车行" }, { "che hou", "车后" },
			{ "che hui", "撤回" }, { "che huo", "车祸" }, { "che jia", "车价" }, { "che jia", "车架" }, { "che jian", "车间" }, { "che jun", "撤军" }, { "che kai", "扯开" },
			{ "che ku", "车库" }, { "che kuang", "车况" }, { "che li", "撤离" }, { "che li", "车里" }, { "che liang", "车辆" }, { "che liu", "车流" }, { "che lun", "车轮" },
			{ "che ma", "车马" }, { "che men", "车门" }, { "che mi", "车迷" }, { "che mo", "车模" }, { "che nei", "车内" }, { "che pai", "车牌" },
			{ "che pai hao", "车牌号" }, { "che pi", "扯皮" }, { "che piao", "车票" }, { "che qian", "车前" }, { "che shang", "扯上" }, { "che shang", "车上" },
			{ "che shen", "车身" }, { "che shi", "车市" }, { "che shou", "车手" }, { "che shui ma long", "车水马龙" }, { "che su", "车速" }, { "che tan", "车坛" },
			{ "che ti", "车体" }, { "che ting", "车停" }, { "che tou", "车头" }, { "che tou che wei", "彻头彻尾" }, { "che tui", "撤退" }, { "che wai", "车外" },
			{ "che wei", "车位" }, { "che wei", "车尾" }, { "che xia", "撤下" }, { "che xian", "车险" }, { "che xiang", "车厢" }, { "che xiao", "撤消" },
			{ "che xiao", "撤销" }, { "che xing", "车型" }, { "che ye", "彻夜" }, { "che yong", "车用" }, { "che you", "车友" }, { "che you hui", "车友会" },
			{ "che zai", "车载" }, { "che zhan", "车展" }, { "che zhan", "车站" }, { "che zhe", "扯着" }, { "che zhi", "撤职" }, { "che zhong", "车中" },
			{ "che zhu", "车主" }, { "che zhuang", "车撞" }, { "che zi", "车子" }, { "chen", "伧" }, { "chen", "傖" }, { "chen", "嗔" }, { "chen", "嚫" },
			{ "chen", "塵" }, { "chen", "墋" }, { "chen", "宸" }, { "chen", "尘" }, { "chen", "忱" }, { "chen", "抻" }, { "chen", "揨" }, { "chen", "晨" },
			{ "chen", "棽" }, { "chen", "榇" }, { "chen", "樄" }, { "chen", "沈" }, { "chen", "沉" }, { "chen", "煁" }, { "chen", "琛" }, { "chen", "疢" },
			{ "chen", "瞋" }, { "chen", "碜" }, { "chen", "磣" }, { "chen", "称" }, { "chen", "肜" }, { "chen", "臣" }, { "chen", "茞" }, { "chen", "莐" },
			{ "chen", "蔯" }, { "chen", "螴" }, { "chen", "衬" }, { "chen", "襯" }, { "chen", "諃" }, { "chen", "諶" }, { "chen", "讖" }, { "chen", "谌" },
			{ "chen", "谶" }, { "chen", "賝" }, { "chen", "贂" }, { "chen", "趁" }, { "chen", "踸" }, { "chen", "辰" }, { "chen", "郴" }, { "chen", "陈" },
			{ "chen", "陳" }, { "chen", "鷐" }, { "chen", "麎" }, { "chen", "齔" }, { "chen", "龀" }, { "chen ai", "尘埃" }, { "chen ai luo ding", "尘埃落定" },
			{ "chen bao", "晨报" }, { "chen chen", "晨晨" }, { "chen chen", "沉沉" }, { "chen chu", "陈楚" }, { "chen chuan", "沉船" }, { "chen dao ming", "陈道明" },
			{ "chen dian", "沉淀" }, { "chen dian dian", "沉甸甸" }, { "chen du xiu", "陈独秀" }, { "chen feng", "尘封" }, { "chen fu", "沉浮" }, { "chen gang", "陈刚" },
			{ "chen gong", "陈宫" }, { "chen guan xi", "陈冠希" }, { "chen guang", "晨光" }, { "chen guo", "陈国" }, { "chen hao", "陈好" }, { "chen hao", "陈浩" },
			{ "chen hong", "陈红" }, { "chen hui lin", "陈慧琳" }, { "chen ji", "沉寂" }, { "chen ji", "沉积" }, { "chen ji", "趁机" }, { "chen jia", "陈家" },
			{ "chen jiang", "沉降" }, { "chen jin", "沉浸" }, { "chen jing", "沉静" }, { "chen jing", "陈静" }, { "chen jiu", "陈旧" }, { "chen jun", "陈俊" },
			{ "chen kai ge", "陈凯歌" }, { "chen ke xin", "陈可辛" }, { "chen kun", "陈坤" }, { "chen le", "沉了" }, { "chen lian", "晨练" }, { "chen liang yu", "陈良宇" },
			{ "chen lie", "陈列" }, { "chen lun", "沉沦" }, { "chen men", "沉闷" }, { "chen mi", "沉迷" }, { "chen ming", "陈明" }, { "chen mo", "沉没" },
			{ "chen mo", "沉默" }, { "chen mou", "陈某" }, { "chen ni", "沉溺" }, { "chen nian", "陈年" }, { "chen ping", "陈平" }, { "chen qi zhen", "陈绮贞" },
			{ "chen re", "趁热" }, { "chen ru", "沉入" }, { "chen shan", "衬衫" }, { "chen she", "陈设" }, { "chen sheng", "陈升" }, { "chen shi", "尘世" },
			{ "chen shu", "陈述" }, { "chen shui", "沉睡" }, { "chen shui bian", "陈水扁" }, { "chen si", "沉思" }, { "chen tao", "陈涛" }, { "chen tian qiao", "陈天桥" },
			{ "chen tong", "沉痛" }, { "chen tu", "尘土" }, { "chen tuo", "衬托" }, { "chen wei", "陈伟" }, { "chen wen", "沉稳" }, { "chen wen", "陈文" },
			{ "chen xi", "晨曦" }, { "chen xia qu", "沉下去" }, { "chen xian sheng", "陈先生" }, { "chen xiang", "沉香" }, { "chen xiao", "陈晓" },
			{ "chen xiao chun", "陈小春" }, { "chen xiao jie", "陈小姐" }, { "chen xiao xu", "陈晓旭" }, { "chen xing", "晨星" }, { "chen yi", "衬衣" },
			{ "chen yi", "陈毅" }, { "chen yi fei", "陈逸飞" }, { "chen yi xun", "陈奕迅" }, { "chen yin", "沉吟" }, { "chen yong", "陈勇" }, { "chen yuan", "尘缘" },
			{ "chen yun", "陈云" }, { "chen yun lin", "陈云林" }, { "chen zao", "趁早" }, { "chen zhe", "趁着" }, { "chen zhi", "称职" }, { "chen zhi", "陈志" },
			{ "chen zhong", "沉重" }, { "chen zhou", "郴州" }, { "chen zhuo", "沉着" }, { "chen zui", "沉醉" }, { "cheng", "丞" }, { "cheng", "乘" }, { "cheng", "偁" },
			{ "cheng", "呈" }, { "cheng", "城" }, { "cheng", "埕" }, { "cheng", "塍" }, { "cheng", "宬" }, { "cheng", "峸" }, { "cheng", "庱" }, { "cheng", "悜" },
			{ "cheng", "惩" }, { "cheng", "懲" }, { "cheng", "成" }, { "cheng", "承" }, { "cheng", "掁" }, { "cheng", "撐" }, { "cheng", "撑" }, { "cheng", "枨" },
			{ "cheng", "柽" }, { "cheng", "棖" }, { "cheng", "棦" }, { "cheng", "橕" }, { "cheng", "橙" }, { "cheng", "檉" }, { "cheng", "浾" }, { "cheng", "溗" },
			{ "cheng", "澂" }, { "cheng", "澄" }, { "cheng", "牚" }, { "cheng", "珵" }, { "cheng", "珹" }, { "cheng", "琤" }, { "cheng", "盛" }, { "cheng", "瞠" },
			{ "cheng", "碀" }, { "cheng", "秤" }, { "cheng", "称" }, { "cheng", "程" }, { "cheng", "稱" }, { "cheng", "竀" }, { "cheng", "筬" }, { "cheng", "脭" },
			{ "cheng", "荿" }, { "cheng", "蛏" }, { "cheng", "蟶" }, { "cheng", "裎" }, { "cheng", "誠" }, { "cheng", "诚" }, { "cheng", "赬" }, { "cheng", "逞" },
			{ "cheng", "郕" }, { "cheng", "酲" }, { "cheng", "鋮" }, { "cheng", "鏿" }, { "cheng", "铖" }, { "cheng", "铛" }, { "cheng", "饓" }, { "cheng", "騁" },
			{ "cheng", "騬" }, { "cheng", "骋" }, { "cheng ba", "称霸" }, { "cheng bai", "成败" }, { "cheng bai shang qian", "成百上千" }, { "cheng ban", "承办" },
			{ "cheng bang", "城邦" }, { "cheng bao", "城堡" }, { "cheng bao", "承保" }, { "cheng bao", "承包" }, { "cheng bao ren", "承包人" },
			{ "cheng bao shang", "承包商" }, { "cheng bei", "城北" }, { "cheng bei", "成倍" }, { "cheng ben", "成本" }, { "cheng ben di", "成本低" },
			{ "cheng ben he suan", "成本核算" }, { "cheng ben jia", "成本价" }, { "cheng ben kong zhi", "成本控制" }, { "cheng bu liao", "成不了" },
			{ "cheng bu zhu", "撑不住" }, { "cheng cai", "成才" }, { "cheng che", "乘车" }, { "cheng chi", "城池" }, { "cheng chu", "惩处" }, { "cheng chuan", "乘船" },
			{ "cheng da", "成大" }, { "cheng dan", "承担" }, { "cheng dan ze ren", "承担责任" }, { "cheng dao", "称道" }, { "cheng de", "承德" },
			{ "cheng de shang", "称得上" }, { "cheng di", "称帝" }, { "cheng dong", "城东" }, { "cheng dou", "成都" }, { "cheng du", "成都" }, { "cheng du", "程度" },
			{ "cheng du ren", "成都人" }, { "cheng du shi", "成都市" }, { "cheng dui", "成堆" }, { "cheng dui", "承兑" }, { "cheng fa", "乘法" }, { "cheng fa", "惩罚" },
			{ "cheng fei ji", "乘飞机" }, { "cheng fen", "成份" }, { "cheng fen", "成分" }, { "cheng feng", "乘风" }, { "cheng feng", "成风" }, { "cheng fo", "成佛" },
			{ "cheng fu", "城府" }, { "cheng gong", "成功" }, { "cheng gong an li", "成功案例" }, { "cheng gong jing yan", "成功经验" }, { "cheng gong ju ban", "成功举办" },
			{ "cheng gong lv", "成功率" }, { "cheng gong ren shi", "成功人士" }, { "cheng gong zhe", "成功者" }, { "cheng guan", "城关" }, { "cheng guan", "城管" },
			{ "cheng guan zhi fa", "城管执法" }, { "cheng guo", "成果" }, { "cheng hai", "澄海" }, { "cheng hao", "称号" }, { "cheng hu", "称呼" },
			{ "cheng huang miao", "城隍庙" }, { "cheng hun", "成婚" }, { "cheng huo che", "乘火车" }, { "cheng huo lv", "成活率" }, { "cheng ji", "乘机" },
			{ "cheng ji", "城际" }, { "cheng ji", "成绩" }, { "cheng ji dan", "成绩单" }, { "cheng ji si han", "成吉思汗" }, { "cheng jia", "成家" },
			{ "cheng jian", "城建" }, { "cheng jian", "成见" }, { "cheng jian", "承建" }, { "cheng jiao", "城郊" }, { "cheng jiao", "成交" }, { "cheng jiao", "成教" },
			{ "cheng jiao e", "成交额" }, { "cheng jiao jia", "成交价" }, { "cheng jiao jia ge", "成交价格" }, { "cheng jiao liang", "成交量" }, { "cheng jie", "惩戒" },
			{ "cheng jie", "承接" }, { "cheng jiu", "成就" }, { "cheng jiu gan", "成就感" }, { "cheng kai", "撑开" }, { "cheng ke", "乘客" }, { "cheng ken", "诚恳" },
			{ "cheng lan", "承揽" }, { "cheng le", "成了" }, { "cheng li", "城里" }, { "cheng li", "成立" }, { "cheng li ren", "城里人" }, { "cheng li yi lai", "成立以来" },
			{ "cheng liang", "乘凉" }, { "cheng long", "成龙" }, { "cheng men", "城门" }, { "cheng ming", "成名" }, { "cheng mu jie she", "瞠目结舌" },
			{ "cheng nan", "城南" }, { "cheng nei", "城内" }, { "cheng nian", "成年" }, { "cheng nian ren", "成年人" }, { "cheng nuo", "承诺" },
			{ "cheng nuo shu", "承诺书" }, { "cheng pian", "成片" }, { "cheng pin", "成品" }, { "cheng pin", "诚聘" }, { "cheng pin you", "成品油" }, { "cheng qi", "撑起" },
			{ "cheng qi", "称其" }, { "cheng qian shang wan", "成千上万" }, { "cheng qiang", "城墙" }, { "cheng qin", "成亲" }, { "cheng qing", "澄清" },
			{ "cheng qu", "城区" }, { "cheng quan", "成全" }, { "cheng qun", "成群" }, { "cheng ren", "成人" }, { "cheng ren", "承认" },
			{ "cheng ren dian ying", "成人电影" }, { "cheng ri", "成日" }, { "cheng se", "成色" }, { "cheng se", "橙色" }, { "cheng shi", "城市" }, { "cheng shi", "程式" },
			{ "cheng shi", "诚实" }, { "cheng shi dao lu", "城市道路" }, { "cheng shi fa zhan", "城市发展" }, { "cheng shi guan li", "城市管理" },
			{ "cheng shi gui hua", "城市规划" }, { "cheng shi hua", "城市化" }, { "cheng shi huan jing", "城市环境" }, { "cheng shi jian she", "城市建设" },
			{ "cheng shi jiao tong", "城市交通" }, { "cheng shi ju min", "城市居民" }, { "cheng shi li", "城市里" }, { "cheng shi qun", "城市群" },
			{ "cheng shi ren kou", "城市人口" }, { "cheng shi sheng huo", "城市生活" }, { "cheng shi shou xin", "诚实守信" }, { "cheng shou", "成熟" },
			{ "cheng shou", "承受" }, { "cheng shou li", "承受力" }, { "cheng shou neng li", "承受能力" }, { "cheng shu", "成熟" }, { "cheng shu du", "成熟度" },
			{ "cheng shu qi", "成熟期" }, { "cheng si", "撑死" }, { "cheng ta", "称他" }, { "cheng tao", "成套" }, { "cheng tao she bei", "成套设备" },
			{ "cheng tian", "成天" }, { "cheng tie", "城铁" }, { "cheng wai", "城外" }, { "cheng wei", "成为" }, { "cheng wei", "称为" }, { "cheng wei", "称谓" },
			{ "cheng wei shi jie", "成为世界" }, { "cheng wei xian shi", "成为现实" }, { "cheng wei yi ming", "成为一名" }, { "cheng wei yi zhong", "成为一种" },
			{ "cheng wei zhong guo", "成为中国" }, { "cheng wen", "成文" }, { "cheng wen ti", "成问题" }, { "cheng wu yuan", "乘务员" }, { "cheng xi", "城西" },
			{ "cheng xian", "呈现" }, { "cheng xian", "成仙" }, { "cheng xian chu", "呈现出" }, { "cheng xiang", "丞相" }, { "cheng xiang", "城乡" },
			{ "cheng xiang", "成像" }, { "cheng xiang gui hua", "城乡规划" }, { "cheng xiang ju min", "城乡居民" }, { "cheng xiang tong chou", "城乡统筹" },
			{ "cheng xiao", "成效" }, { "cheng xiao", "承销" }, { "cheng xiao shang", "承销商" }, { "cheng xin", "成新" }, { "cheng xin", "诚信" }, { "cheng xin", "诚心" },
			{ "cheng xin tong", "诚信通" }, { "cheng xing", "成型" }, { "cheng xing", "成形" }, { "cheng xing", "成行" }, { "cheng xu", "程序" },
			{ "cheng xu she ji", "程序设计" }, { "cheng xu yuan", "程序员" }, { "cheng xu yun xing", "程序运行" }, { "cheng yao", "撑腰" }, { "cheng yao", "诚邀" },
			{ "cheng yi", "乘以" }, { "cheng yi", "成一" }, { "cheng yi", "成衣" }, { "cheng yi", "诚意" }, { "cheng yin", "成因" }, { "cheng yin", "成瘾" },
			{ "cheng yong che", "乘用车" }, { "cheng yu", "成语" }, { "cheng yu wang", "城域网" }, { "cheng yuan", "乘员" }, { "cheng yuan", "成员" },
			{ "cheng yuan guo", "成员国" }, { "cheng yun", "承运" }, { "cheng yun ren", "承运人" }, { "cheng zai", "承载" }, { "cheng zai li", "承载力" },
			{ "cheng zan", "称赞" }, { "cheng zhang", "成长" }, { "cheng zhang guo cheng", "成长过程" }, { "cheng zhang xing", "成长性" }, { "cheng zhao", "诚招" },
			{ "cheng zhe", "乘着" }, { "cheng zhe", "撑着" }, { "cheng zhen", "城镇" }, { "cheng zhen", "成真" }, { "cheng zhen hua", "城镇化" },
			{ "cheng zhen ju min", "城镇居民" }, { "cheng zhen zhi gong", "城镇职工" }, { "cheng zheng", "诚征" }, { "cheng zheng bi", "成正比" }, { "cheng zhi", "惩治" },
			{ "cheng zhi", "橙汁" }, { "cheng zhi", "诚挚" }, { "cheng zhi wei", "称之为" }, { "cheng zhong", "城中" }, { "cheng zhong", "承重" },
			{ "cheng zhong", "称重" }, { "cheng zhong cun", "城中村" }, { "cheng zhu", "城主" }, { "cheng zi", "橙子" }, { "cheng zu", "承租" },
			{ "cheng zu ren", "承租人" }, { "cheng zuo", "乘坐" }, { "cheng zuo", "称作" }, { "cheng zuo", "称做" }, { "chi", "侈" }, { "chi", "傺" }, { "chi", "勅" },
			{ "chi", "匙" }, { "chi", "叱" }, { "chi", "叺" }, { "chi", "吃" }, { "chi", "呎" }, { "chi", "哧" }, { "chi", "啻" }, { "chi", "喫" }, { "chi", "嗤" },
			{ "chi", "坻" }, { "chi", "墀" }, { "chi", "妛" }, { "chi", "媸" }, { "chi", "尺" }, { "chi", "岻" }, { "chi", "弛" }, { "chi", "彳" }, { "chi", "恥" },
			{ "chi", "懘" }, { "chi", "抶" }, { "chi", "持" }, { "chi", "摛" }, { "chi", "攡" }, { "chi", "敕" }, { "chi", "斥" }, { "chi", "歯" }, { "chi", "池" },
			{ "chi", "淔" }, { "chi", "湁" }, { "chi", "漦" }, { "chi", "炽" }, { "chi", "熾" }, { "chi", "瓻" }, { "chi", "痴" }, { "chi", "痸" }, { "chi", "瘈" },
			{ "chi", "瘛" }, { "chi", "癡" }, { "chi", "眵" }, { "chi", "瞝" }, { "chi", "笞" }, { "chi", "篪" }, { "chi", "絺" }, { "chi", "翅" }, { "chi", "翨" },
			{ "chi", "耻" }, { "chi", "胣" }, { "chi", "腟" }, { "chi", "茌" }, { "chi", "荎" }, { "chi", "蚇" }, { "chi", "蚩" }, { "chi", "螭" }, { "chi", "褫" },
			{ "chi", "謘" }, { "chi", "豉" }, { "chi", "貾" }, { "chi", "赤" }, { "chi", "踟" }, { "chi", "迟" }, { "chi", "遅" }, { "chi", "遫" }, { "chi", "遲" },
			{ "chi", "鉓" }, { "chi", "鉹" }, { "chi", "饎" }, { "chi", "饬" }, { "chi", "馳" }, { "chi", "驰" }, { "chi", "魑" }, { "chi", "鴟" }, { "chi", "鵄" },
			{ "chi", "鶒" }, { "chi", "鷘" }, { "chi", "鸱" }, { "chi", "麶" }, { "chi", "黐" }, { "chi", "齒" }, { "chi", "齝" }, { "chi", "齿" }, { "chi ba", "吃吧" },
			{ "chi bang", "翅膀" }, { "chi bao", "吃饱" }, { "chi bao le", "吃饱了" }, { "chi bi", "持币" }, { "chi bi", "赤壁" }, { "chi bu", "吃不" },
			{ "chi bu liao", "吃不了" }, { "chi bu xia", "吃不下" }, { "chi bu xiao", "吃不消" }, { "chi cang", "持仓" }, { "chi cao", "吃草" }, { "chi cheng", "驰骋" },
			{ "chi chi", "吃吃" }, { "chi chi", "痴痴" }, { "chi chi", "迟迟" }, { "chi chu", "吃出" }, { "chi cu", "吃醋" }, { "chi cun", "尺寸" }, { "chi dai", "痴呆" },
			{ "chi dao", "吃到" }, { "chi dao", "持刀" }, { "chi dao", "赤道" }, { "chi dao", "迟到" }, { "chi de", "吃得" }, { "chi dian", "吃点" }, { "chi diao", "吃掉" },
			{ "chi dong xi", "吃东西" }, { "chi du", "尺度" }, { "chi dun", "吃顿" }, { "chi dun", "迟钝" }, { "chi duo", "吃多" }, { "chi duo le", "吃多了" },
			{ "chi fa", "吃法" }, { "chi fan", "吃饭" }, { "chi feng", "赤峰" }, { "chi ge", "吃个" }, { "chi gu", "持股" }, { "chi gu bi li", "持股比例" },
			{ "chi guang", "吃光" }, { "chi guo", "吃过" }, { "chi hai xian", "吃海鲜" }, { "chi hao", "吃好" }, { "chi he", "吃喝" }, { "chi he wan le", "吃喝玩乐" },
			{ "chi huan", "迟缓" }, { "chi huo guo", "吃火锅" }, { "chi jiao", "赤脚" }, { "chi jin", "吃紧" }, { "chi jin", "吃进" }, { "chi jing", "吃惊" },
			{ "chi jiu", "持久" }, { "chi jiu zhan", "持久战" }, { "chi ka ren", "持卡人" }, { "chi ku", "吃苦" }, { "chi ku nai lao", "吃苦耐劳" }, { "chi kui", "吃亏" },
			{ "chi la", "吃辣" }, { "chi lai", "迟来" }, { "chi le", "吃了" }, { "chi li", "吃力" }, { "chi ling shi", "吃零食" }, { "chi lun", "齿轮" },
			{ "chi luo", "赤裸" }, { "chi luo luo", "赤裸裸" }, { "chi ma", "尺码" }, { "chi mi", "痴迷" }, { "chi mian", "吃面" }, { "chi ming", "驰名" },
			{ "chi ming shang biao", "驰名商标" }, { "chi nai", "吃奶" }, { "chi pang xie", "吃螃蟹" }, { "chi ping", "持平" }, { "chi qiang", "持枪" },
			{ "chi qing", "痴情" }, { "chi re", "炽热" }, { "chi ren", "吃人" }, { "chi rou", "吃肉" }, { "chi ru", "耻辱" }, { "chi shang", "吃上" },
			{ "chi shen", "赤身" }, { "chi shen me", "吃什么" }, { "chi shi", "吃屎" }, { "chi shui guo", "吃水果" }, { "chi su", "吃素" }, { "chi tang", "吃糖" },
			{ "chi tang", "池塘" }, { "chi tou", "吃透" }, { "chi wan", "吃完" }, { "chi wan fan", "吃完饭" }, { "chi wan fan", "吃晚饭" }, { "chi xi gua", "吃西瓜" },
			{ "chi xia", "吃下" }, { "chi xia qu", "吃下去" }, { "chi xiang", "吃香" }, { "chi xiao", "耻笑" }, { "chi xie", "吃些" }, { "chi xin", "痴心" },
			{ "chi xu", "持续" }, { "chi xu fa zhan", "持续发展" }, { "chi xu shi jian", "持续时间" }, { "chi xu xing", "持续性" }, { "chi xu zeng zhang", "持续增长" },
			{ "chi yao", "吃药" }, { "chi yi", "迟疑" }, { "chi you", "持有" }, { "chi you", "蚩尤" }, { "chi you ren", "持有人" }, { "chi you zhe", "持有者" },
			{ "chi yu", "吃鱼" }, { "chi zao", "迟早" }, { "chi zao can", "吃早餐" }, { "chi ze", "斥责" }, { "chi zhe", "吃着" }, { "chi zheng", "持证" },
			{ "chi zhi", "迟滞" }, { "chi zhi yi bi", "嗤之以鼻" }, { "chi zhi yi heng", "持之以恒" }, { "chi zhong", "池中" }, { "chi zhu", "吃住" }, { "chi zi", "尺子" },
			{ "chi zi", "斥资" }, { "chi zi", "池子" }, { "chi zi", "赤字" }, { "chong", "充" }, { "chong", "冲" }, { "chong", "宠" }, { "chong", "寵" },
			{ "chong", "崇" }, { "chong", "忡" }, { "chong", "憃" }, { "chong", "憧" }, { "chong", "沖" }, { "chong", "浺" }, { "chong", "珫" }, { "chong", "种" },
			{ "chong", "罿" }, { "chong", "翀" }, { "chong", "舂" }, { "chong", "艟" }, { "chong", "茺" }, { "chong", "虫" }, { "chong", "蟲" }, { "chong", "衝" },
			{ "chong", "蹖" }, { "chong", "重" }, { "chong", "銃" }, { "chong", "铳" }, { "chong", "隀" }, { "chong ai", "宠爱" }, { "chong bai", "崇拜" },
			{ "chong bo", "重播" }, { "chong cao", "虫草" }, { "chong chi", "充斥" }, { "chong chong", "冲冲" }, { "chong chong", "虫虫" }, { "chong chong", "重重" },
			{ "chong chu", "冲出" }, { "chong chu jiang hu", "重出江湖" }, { "chong ci", "冲刺" }, { "chong dan", "冲淡" }, { "chong dang", "充当" },
			{ "chong dao", "冲到" }, { "chong dao", "重蹈" }, { "chong dian", "充电" }, { "chong dian qi", "充电器" }, { "chong die", "重叠" },
			{ "chong ding xiang", "重定向" }, { "chong dong", "冲动" }, { "chong du", "重读" }, { "chong er", "宠儿" }, { "chong fa", "重发" }, { "chong fa", "重罚" },
			{ "chong fan", "重返" }, { "chong fen", "充分" }, { "chong fen fa hui", "充分发挥" }, { "chong fen kao lv", "充分考虑" }, { "chong fen ken ding", "充分肯定" },
			{ "chong fen li yong", "充分利用" }, { "chong fen ren shi", "充分认识" }, { "chong fen ti xian", "充分体现" }, { "chong feng", "冲锋" }, { "chong feng", "重逢" },
			{ "chong feng qiang", "冲锋枪" }, { "chong fu", "重复" }, { "chong fu jian she", "重复建设" }, { "chong fu xing", "重复性" }, { "chong gao", "冲高" },
			{ "chong gao", "崇高" }, { "chong gou", "重构" }, { "chong gu", "重估" }, { "chong guo", "冲过" }, { "chong hao", "充好" }, { "chong he", "重合" },
			{ "chong huai", "宠坏" }, { "chong hui", "重回" }, { "chong ji", "充饥" }, { "chong ji", "冲击" }, { "chong ji", "冲剂" }, { "chong ji", "冲级" },
			{ "chong ji bo", "冲击波" }, { "chong ji li", "冲击力" }, { "chong jian", "重建" }, { "chong jin", "冲劲" }, { "chong jin", "冲进" }, { "chong jing", "崇敬" },
			{ "chong jing", "憧憬" }, { "chong kai", "重开" }, { "chong lai", "重来" }, { "chong lang", "冲浪" }, { "chong le", "冲了" }, { "chong liang", "冲凉" },
			{ "chong man", "充满" }, { "chong man huo li", "充满活力" }, { "chong man xi wang", "充满希望" }, { "chong man xin xin", "充满信心" } };
};
