package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN62 {
	public static String[][] pl = { { "zheng de", "争得" }, { "zheng de", "征得" }, { "zheng de", "挣得" }, { "zheng di", "征地" }, { "zheng dian", "整点" },
			{ "zheng dian", "正点" }, { "zheng ding", "征订" }, { "zheng dou", "争斗" }, { "zheng duan", "争端" }, { "zheng dui", "正对" }, { "zheng dun", "整顿" },
			{ "zheng duo", "争夺" }, { "zheng duo zhan", "争夺战" }, { "zheng er ba jing", "正儿八经" }, { "zheng fa", "政法" }, { "zheng fa", "正法" },
			{ "zheng fa", "蒸发" }, { "zheng fa qi", "蒸发器" }, { "zheng fa wei", "政法委" }, { "zheng fan", "正反" }, { "zheng fang", "正方" },
			{ "zheng fang xing", "正方形" }, { "zheng fu", "征服" }, { "zheng fu", "政府" }, { "zheng fu", "正负" }, { "zheng fu bu men", "政府部门" },
			{ "zheng fu cai gou", "政府采购" }, { "zheng fu gong zuo", "政府工作" }, { "zheng fu guan yuan", "政府官员" }, { "zheng fu ji gou", "政府机构" },
			{ "zheng fu ji guan", "政府机关" }, { "zheng fu tou zi", "政府投资" }, { "zheng fu wang zhan", "政府网站" }, { "zheng fu zhi neng", "政府职能" },
			{ "zheng gai", "整改" }, { "zheng gai cuo shi", "整改措施" }, { "zheng gao", "征稿" }, { "zheng ge", "整个" }, { "zheng ge guo cheng", "整个过程" },
			{ "zheng ge ren", "整个人" }, { "zheng ge shi jie", "整个世界" }, { "zheng guan", "征管" }, { "zheng guang", "争光" }, { "zheng gui", "正规" },
			{ "zheng gui", "正轨" }, { "zheng guo", "正果" }, { "zheng hao", "正好" }, { "zheng hao", "蒸好" }, { "zheng he", "整合" }, { "zheng he", "郑和" },
			{ "zheng hun", "征婚" }, { "zheng ji", "征集" }, { "zheng ji", "政绩" }, { "zheng ji", "整机" }, { "zheng jia", "正佳" }, { "zheng jian", "证件" },
			{ "zheng jian hui", "证监会" }, { "zheng jiao", "正交" }, { "zheng jiao suo", "证交所" }, { "zheng jie", "政界" }, { "zheng jie", "整洁" },
			{ "zheng jie", "正解" }, { "zheng jie", "症结" }, { "zheng jie", "郑洁" }, { "zheng jing", "政经" }, { "zheng jing", "正经" }, { "zheng jiu", "拯救" },
			{ "zheng ju", "政局" }, { "zheng ju", "证据" }, { "zheng juan", "证卷" }, { "zheng jun", "郑钧" }, { "zheng kai", "睁开" }, { "zheng kai yan jing", "睁开眼睛" },
			{ "zheng ke", "政客" }, { "zheng kuai", "整块" }, { "zheng li", "整理" }, { "zheng ling", "政令" }, { "zheng liu", "整流" }, { "zheng liu", "蒸馏" },
			{ "zheng long", "正龙" }, { "zheng lun", "争论" }, { "zheng men", "正门" }, { "zheng mian", "正面" }, { "zheng ming", "正名" }, { "zheng ming", "证明" },
			{ "zheng ming cai liao", "证明材料" }, { "zheng ming shu", "证明书" }, { "zheng ming wen jian", "证明文件" }, { "zheng ning", "狰狞" }, { "zheng pai", "正派" },
			{ "zheng pin", "正品" }, { "zheng qi", "争气" }, { "zheng qi", "整齐" }, { "zheng qi", "正气" }, { "zheng qi", "蒸气" }, { "zheng qi", "蒸汽" },
			{ "zheng qian", "挣钱" }, { "zheng qiang", "争抢" }, { "zheng qiao", "正巧" }, { "zheng qiu", "征求" }, { "zheng qiu yi jian", "征求意见" },
			{ "zheng qu", "争取" }, { "zheng quan", "政权" }, { "zheng quan", "证券" }, { "zheng quan fa", "证券法" }, { "zheng quan gong si", "证券公司" },
			{ "zheng quan hua", "证券化" }, { "zheng quan jiao yi", "证券交易" }, { "zheng quan shi chang", "证券市场" }, { "zheng quan tou zi", "证券投资" },
			{ "zheng quan ye", "证券业" }, { "zheng que", "正确" }, { "zheng que chu li", "正确处理" }, { "zheng que da an", "正确答案" }, { "zheng que dui dai", "正确对待" },
			{ "zheng que ren shi", "正确认识" }, { "zheng que xing", "正确性" }, { "zheng ren", "整人" }, { "zheng ren", "证人" }, { "zheng ri", "整日" },
			{ "zheng rong", "整容" }, { "zheng ru", "正如" }, { "zheng shao qiu", "郑少秋" }, { "zheng shen", "政审" }, { "zheng shi", "政事" }, { "zheng shi", "正事" },
			{ "zheng shi", "正式" }, { "zheng shi", "正是" }, { "zheng shi", "正视" }, { "zheng shi", "证实" }, { "zheng shi ban", "正式版" },
			{ "zheng shi cheng li", "正式成立" }, { "zheng shi fa bu", "正式发布" }, { "zheng shi kai shi", "正式开始" }, { "zheng shi qi dong", "正式启动" },
			{ "zheng shi shi shi", "正式实施" }, { "zheng shou", "征收" }, { "zheng shu", "整数" }, { "zheng shu", "蒸熟" }, { "zheng shu", "证书" },
			{ "zheng shui", "征税" }, { "zheng si", "整死" }, { "zheng tai", "正太" }, { "zheng tan", "政坛" }, { "zheng tao", "整套" }, { "zheng ti", "政体" },
			{ "zheng ti", "整体" }, { "zheng ti", "正题" }, { "zheng ti gui hua", "整体规划" }, { "zheng ti shang shi", "整体上市" }, { "zheng ti su zhi", "整体素质" },
			{ "zheng ti xing", "整体性" }, { "zheng tian", "整天" }, { "zheng tiao", "整条" }, { "zheng tong", "正统" }, { "zheng tu", "征途" }, { "zheng tuo", "挣脱" },
			{ "zheng wan", "整晚" }, { "zheng wei", "政委" }, { "zheng wei", "正为" }, { "zheng wen", "征文" }, { "zheng wen", "正文" }, { "zheng wu", "政务" },
			{ "zheng wu", "正午" }, { "zheng wu gong kai", "政务公开" }, { "zheng xian kong hou", "争先恐后" }, { "zheng xiang", "争相" }, { "zheng xiang", "正像" },
			{ "zheng xiang", "正向" }, { "zheng xiang", "正想" }, { "zheng xie", "政协" }, { "zheng xie gong zuo", "政协工作" }, { "zheng xie wei yuan", "政协委员" },
			{ "zheng xie zhu xi", "政协主席" }, { "zheng xin", "征信" }, { "zheng xing", "整形" }, { "zheng xiu", "整修" }, { "zheng xiu wen", "郑秀文" },
			{ "zheng xun", "征询" }, { "zheng yan", "睁眼" }, { "zheng yan", "证言" }, { "zheng yao", "政要" }, { "zheng yao", "正要" }, { "zheng ye", "整夜" },
			{ "zheng yi", "争议" }, { "zheng yi", "正义" }, { "zheng yi", "正以" }, { "zheng yi gan", "正义感" }, { "zheng yi jian", "郑伊健" }, { "zheng yin", "正因" },
			{ "zheng yin wei", "正因为" }, { "zheng yong", "征用" }, { "zheng you", "征友" }, { "zheng yu", "正与" }, { "zheng yue", "正月" }, { "zheng zai", "正在" },
			{ "zheng zai jin xing", "正在进行" }, { "zheng zai yun xing", "正在运行" }, { "zheng ze", "正则" }, { "zheng zha", "挣扎" }, { "zheng zhan", "征战" },
			{ "zheng zhang", "整张" }, { "zheng zhao", "征兆" }, { "zheng zhao", "证照" }, { "zheng zhe", "争着" }, { "zheng zhe", "睁着" }, { "zheng zheng", "怔怔" },
			{ "zheng zheng", "整整" }, { "zheng zheng qi qi", "整整齐齐" }, { "zheng zheng ri shang", "蒸蒸日上" }, { "zheng zhi", "争执" }, { "zheng zhi", "政治" },
			{ "zheng zhi", "整治" }, { "zheng zhi", "正值" }, { "zheng zhi", "正直" }, { "zheng zhi", "正职" }, { "zheng zhi", "郑智" }, { "zheng zhi bu", "政治部" },
			{ "zheng zhi dou zheng", "政治斗争" }, { "zheng zhi gong zuo", "整治工作" }, { "zheng zhi jia", "政治家" }, { "zheng zhi jing ji", "政治经济" },
			{ "zheng zhi ju", "政治局" }, { "zheng zhi quan li", "政治权利" }, { "zheng zhi ren wu", "政治人物" }, { "zheng zhi ren wu", "政治任务" },
			{ "zheng zhi sheng huo", "政治生活" }, { "zheng zhi ti zhi", "政治体制" }, { "zheng zhi wei yuan", "政治委员" }, { "zheng zhi wen ming", "政治文明" },
			{ "zheng zhi xue", "政治学" }, { "zheng zhi zhi du", "政治制度" }, { "zheng zhong", "正中" }, { "zheng zhong", "郑重" }, { "zheng zhong sheng ming", "郑重声明" },
			{ "zheng zhou", "郑州" }, { "zheng zhou shi", "郑州市" }, { "zheng zhuang", "正装" }, { "zheng zhuang", "症状" }, { "zheng zhun bei", "正准备" },
			{ "zheng zong", "正宗" }, { "zheng zuo", "争做" }, { "zheng zuo", "整座" }, { "zhi", "之" }, { "zhi", "乿" }, { "zhi", "亊" }, { "zhi", "侄" },
			{ "zhi", "値" }, { "zhi", "值" }, { "zhi", "偫" }, { "zhi", "傂" }, { "zhi", "凪" }, { "zhi", "制" }, { "zhi", "剬" }, { "zhi", "卮" }, { "zhi", "厔" },
			{ "zhi", "只" }, { "zhi", "吱" }, { "zhi", "咫" }, { "zhi", "嚔" }, { "zhi", "址" }, { "zhi", "坁" }, { "zhi", "埴" }, { "zhi", "執" }, { "zhi", "墆" },
			{ "zhi", "夛" }, { "zhi", "姪" }, { "zhi", "媞" }, { "zhi", "嬂" }, { "zhi", "寘" }, { "zhi", "峙" }, { "zhi", "巵" }, { "zhi", "帋" }, { "zhi", "帙" },
			{ "zhi", "帜" }, { "zhi", "幟" }, { "zhi", "庢" }, { "zhi", "庤" }, { "zhi", "廌" }, { "zhi", "彘" }, { "zhi", "徴" }, { "zhi", "徵" }, { "zhi", "志" },
			{ "zhi", "忮" }, { "zhi", "恉" }, { "zhi", "慹" }, { "zhi", "懥" }, { "zhi", "懫" }, { "zhi", "戠" }, { "zhi", "执" }, { "zhi", "扺" }, { "zhi", "扻" },
			{ "zhi", "挃" }, { "zhi", "指" }, { "zhi", "挚" }, { "zhi", "捗" }, { "zhi", "掷" }, { "zhi", "搘" }, { "zhi", "摨" }, { "zhi", "摭" }, { "zhi", "摯" },
			{ "zhi", "擲" }, { "zhi", "擳" }, { "zhi", "擿" }, { "zhi", "支" }, { "zhi", "旨" }, { "zhi", "晊" }, { "zhi", "智" }, { "zhi", "杝" }, { "zhi", "枝" },
			{ "zhi", "枳" }, { "zhi", "柣" }, { "zhi", "栀" }, { "zhi", "栉" }, { "zhi", "栺" }, { "zhi", "桎" }, { "zhi", "梔" }, { "zhi", "植" }, { "zhi", "椥" },
			{ "zhi", "楖" }, { "zhi", "榰" }, { "zhi", "樀" }, { "zhi", "樲" }, { "zhi", "樴" }, { "zhi", "櫍" }, { "zhi", "櫛" }, { "zhi", "止" }, { "zhi", "歭" },
			{ "zhi", "殖" }, { "zhi", "氏" }, { "zhi", "汁" }, { "zhi", "汥" }, { "zhi", "汦" }, { "zhi", "沚" }, { "zhi", "治" }, { "zhi", "泜" }, { "zhi", "洷" },
			{ "zhi", "淽" }, { "zhi", "滍" }, { "zhi", "滞" }, { "zhi", "滯" }, { "zhi", "潪" }, { "zhi", "瀄" }, { "zhi", "炙" }, { "zhi", "犆" }, { "zhi", "狾" },
			{ "zhi", "猘" }, { "zhi", "瓆" }, { "zhi", "瓡" }, { "zhi", "畤" }, { "zhi", "疐" }, { "zhi", "疻" }, { "zhi", "痔" }, { "zhi", "痣" }, { "zhi", "瘈" },
			{ "zhi", "直" }, { "zhi", "知" }, { "zhi", "礩" }, { "zhi", "祉" }, { "zhi", "祑" }, { "zhi", "祗" }, { "zhi", "禔" }, { "zhi", "秖" }, { "zhi", "秩" },
			{ "zhi", "秪" }, { "zhi", "秷" }, { "zhi", "稙" }, { "zhi", "稚" }, { "zhi", "穉" }, { "zhi", "窒" }, { "zhi", "紙" }, { "zhi", "紩" }, { "zhi", "絷" },
			{ "zhi", "緻" }, { "zhi", "縶" }, { "zhi", "織" }, { "zhi", "纸" }, { "zhi", "织" }, { "zhi", "置" }, { "zhi", "翐" }, { "zhi", "职" }, { "zhi", "職" },
			{ "zhi", "肢" }, { "zhi", "胑" }, { "zhi", "胝" }, { "zhi", "胵" }, { "zhi", "脂" }, { "zhi", "膣" }, { "zhi", "膱" }, { "zhi", "至" }, { "zhi", "致" },
			{ "zhi", "臷" }, { "zhi", "臸" }, { "zhi", "芝" }, { "zhi", "芷" }, { "zhi", "薙" }, { "zhi", "藢" }, { "zhi", "蘵" }, { "zhi", "蚔" }, { "zhi", "蛭" },
			{ "zhi", "蜘" }, { "zhi", "螲" }, { "zhi", "蟙" }, { "zhi", "衹" }, { "zhi", "衼" }, { "zhi", "袟" }, { "zhi", "製" }, { "zhi", "覟" }, { "zhi", "觝" },
			{ "zhi", "觯" }, { "zhi", "觶" }, { "zhi", "誌" }, { "zhi", "謢" }, { "zhi", "识" }, { "zhi", "豸" }, { "zhi", "貭" }, { "zhi", "質" }, { "zhi", "贄" },
			{ "zhi", "质" }, { "zhi", "贽" }, { "zhi", "趾" }, { "zhi", "跖" }, { "zhi", "跱" }, { "zhi", "踬" }, { "zhi", "踯" }, { "zhi", "蹛" }, { "zhi", "蹢" },
			{ "zhi", "躑" }, { "zhi", "躓" }, { "zhi", "軹" }, { "zhi", "軽" }, { "zhi", "輊" }, { "zhi", "轵" }, { "zhi", "轾" }, { "zhi", "迣" }, { "zhi", "郅" },
			{ "zhi", "酈" }, { "zhi", "酯" }, { "zhi", "釞" }, { "zhi", "鉄" }, { "zhi", "銍" }, { "zhi", "銴" }, { "zhi", "鋕" }, { "zhi", "鑕" }, { "zhi", "阤" },
			{ "zhi", "阯" }, { "zhi", "陟" }, { "zhi", "隲" }, { "zhi", "隻" }, { "zhi", "雉" }, { "zhi", "馽" }, { "zhi", "駤" }, { "zhi", "騭" }, { "zhi", "騺" },
			{ "zhi", "骘" }, { "zhi", "鳷" }, { "zhi", "鴙" }, { "zhi", "鶨" }, { "zhi", "鷙" }, { "zhi", "鸷" }, { "zhi", "黹" }, { "zhi ai", "之爱" },
			{ "zhi ai", "只爱" }, { "zhi ai", "挚爱" }, { "zhi ai", "至爱" }, { "zhi ai", "致癌" }, { "zhi an", "治安" }, { "zhi ba", "只把" }, { "zhi bai", "直白" },
			{ "zhi ban", "值班" }, { "zhi ban", "制版" }, { "zhi ban", "直板" }, { "zhi ban", "纸板" }, { "zhi ban shi", "值班室" }, { "zhi bao", "之宝" },
			{ "zhi bao", "质保" }, { "zhi bei", "之辈" }, { "zhi bei", "制备" }, { "zhi bei", "植被" }, { "zhi ben", "之本" }, { "zhi ben", "治本" }, { "zhi ben", "直奔" },
			{ "zhi bi", "之比" }, { "zhi bi", "之笔" }, { "zhi bi", "只比" }, { "zhi bi", "执笔" }, { "zhi bi", "直逼" }, { "zhi bi", "纸币" }, { "zhi bian", "之变" },
			{ "zhi bian", "质变" }, { "zhi biao", "指标" }, { "zhi biao", "治标" }, { "zhi biao ti xi", "指标体系" }, { "zhi bin", "之滨" }, { "zhi bing", "治病" },
			{ "zhi bing", "致病" }, { "zhi bing xing", "致病性" }, { "zhi bo", "直播" }, { "zhi bo yuan", "直播员" }, { "zhi bu", "支部" }, { "zhi bu", "止步" },
			{ "zhi bu ding", "指不定" }, { "zhi bu guo", "只不过" }, { "zhi bu shu ji", "支部书记" }, { "zhi bu zhi dao", "知不知道" }, { "zhi bu zhu", "止不住" },
			{ "zhi cai", "制裁" }, { "zhi can", "致残" }, { "zhi ce", "之策" }, { "zhi cha", "之差" }, { "zhi cha", "只差" }, { "zhi chang", "之长" },
			{ "zhi chang", "直肠" }, { "zhi chang", "职场" }, { "zhi chang ai", "直肠癌" }, { "zhi cheng", "之城" }, { "zhi cheng", "之称" }, { "zhi cheng", "制成" },
			{ "zhi cheng", "制程" }, { "zhi cheng", "支撑" }, { "zhi cheng", "职称" }, { "zhi chi", "只吃" }, { "zhi chi", "咫尺" }, { "zhi chi", "支持" },
			{ "zhi chi", "智齿" }, { "zhi chi lv", "支持率" }, { "zhi chi zhe", "支持者" }, { "zhi chong", "直冲" }, { "zhi chu", "之初" }, { "zhi chu", "之处" },
			{ "zhi chu", "指出" }, { "zhi chu", "支出" }, { "zhi chuan", "只穿" }, { "zhi chuang", "之窗" }, { "zhi chuang", "痔疮" }, { "zhi chun lu", "知春路" },
			{ "zhi ci", "之词" }, { "zhi ci", "至此" }, { "zhi ci", "致词" }, { "zhi ci", "致辞" }, { "zhi cuo", "知错" }, { "zhi da", "之大" }, { "zhi da", "只打" },
			{ "zhi da", "直达" }, { "zhi dai", "只带" }, { "zhi dai", "纸袋" }, { "zhi dai biao", "只代表" }, { "zhi dan bai", "脂蛋白" }, { "zhi dang", "只当" },
			{ "zhi dao", "之道" }, { "zhi dao", "制导" }, { "zhi dao", "执导" }, { "zhi dao", "指导" }, { "zhi dao", "直到" }, { "zhi dao", "知道" },
			{ "zhi dao gong zuo", "指导工作" }, { "zhi dao jia", "指导价" }, { "zhi dao lao shi", "指导老师" }, { "zhi dao ma", "知道吗" }, { "zhi dao si xiang", "指导思想" },
			{ "zhi dao xian zai", "直到现在" }, { "zhi dao xing", "指导性" }, { "zhi dao xue sheng", "指导学生" }, { "zhi dao yi jian", "指导意见" },
			{ "zhi dao yi yi", "指导意义" }, { "zhi dao yuan", "指导员" }, { "zhi dao zi ji", "知道自己" }, { "zhi de", "值得" }, { "zhi de", "只得" }, { "zhi de", "质的" },
			{ "zhi de guan zhu", "值得关注" }, { "zhi de qi dai", "值得期待" }, { "zhi de shi", "指的是" }, { "zhi de xin lai", "值得信赖" }, { "zhi de yi kan", "值得一看" },
			{ "zhi de yi ti", "值得一提" }, { "zhi de zhu yi", "值得注意" }, { "zhi di", "之地" }, { "zhi di", "置地" }, { "zhi di", "质地" }, { "zhi dian", "之巅" },
			{ "zhi dian", "指点" }, { "zhi dian", "支点" }, { "zhi dian", "致电" }, { "zhi die", "止跌" }, { "zhi ding", "制定" }, { "zhi ding", "制订" },
			{ "zhi ding", "指定" }, { "zhi ding", "置顶" }, { "zhi ding zhe", "制定者" }, { "zhi dong", "制动" }, { "zhi du", "之都" }, { "zhi du", "制度" },
			{ "zhi du", "只读" }, { "zhi du chuang xin", "制度创新" }, { "zhi du gai ge", "制度改革" }, { "zhi du hua", "制度化" }, { "zhi du jian she", "制度建设" },
			{ "zhi du xing", "制度性" }, { "zhi dui", "只对" }, { "zhi dui", "支队" }, { "zhi duo", "之多" }, { "zhi duo", "至多" }, { "zhi duo shao", "知多少" },
			{ "zhi en", "之恩" }, { "zhi er", "之二" }, { "zhi er", "侄儿" }, { "zhi fa", "执法" }, { "zhi fa", "直发" }, { "zhi fa bu men", "执法部门" },
			{ "zhi fa jian cha", "执法检查" }, { "zhi fa ren yuan", "执法人员" }, { "zhi fa zhe", "执法者" }, { "zhi fang", "脂肪" }, { "zhi fang gan", "脂肪肝" },
			{ "zhi fang suan", "脂肪酸" }, { "zhi fei", "直飞" }, { "zhi fen", "之分" }, { "zhi feng", "之风" }, { "zhi fu", "之父" }, { "zhi fu", "制服" },
			{ "zhi fu", "支付" }, { "zhi fu", "知府" }, { "zhi fu", "致富" }, { "zhi fu bao", "支付宝" }, { "zhi gan", "之感" }, { "zhi gan", "质感" },
			{ "zhi gang", "志刚" }, { "zhi gao", "之高" }, { "zhi gao", "至高" }, { "zhi gao dian", "制高点" }, { "zhi gao wu shang", "至高无上" }, { "zhi ge", "之歌" },
			{ "zhi ge", "之隔" }, { "zhi gei", "只给" }, { "zhi gong", "职工" }, { "zhi gong gong zi", "职工工资" }, { "zhi gu", "只顾" }, { "zhi guai", "只怪" },
			{ "zhi guan", "之冠" }, { "zhi guan", "只管" }, { "zhi guan", "直观" }, { "zhi guan zhong yao", "至关重要" }, { "zhi guang", "之光" }, { "zhi guo", "治国" },
			{ "zhi hang", "支行" }, { "zhi hang", "直航" }, { "zhi hao", "只好" }, { "zhi hao", "治好" }, { "zhi he", "只喝" }, { "zhi he", "纸盒" }, { "zhi heng", "制衡" },
			{ "zhi hou", "之后" }, { "zhi hou", "滞后" }, { "zhi hu", "支护" }, { "zhi hu", "直呼" }, { "zhi hua", "之花" }, { "zhi huan", "指环" }, { "zhi huan", "置换" },
			{ "zhi huan wang", "指环王" }, { "zhi hui", "只会" }, { "zhi hui", "指挥" }, { "zhi hui", "智慧" }, { "zhi hui", "知会" }, { "zhi hui bu", "指挥部" },
			{ "zhi hui guan", "指挥官" }, { "zhi hui yuan", "指挥员" }, { "zhi hui zhong xin", "指挥中心" }, { "zhi hun", "之魂" }, { "zhi huo", "之火" },
			{ "zhi ji", "之机" }, { "zhi ji", "之极" }, { "zhi ji", "之计" }, { "zhi ji", "之际" }, { "zhi ji", "制剂" }, { "zhi ji", "直击" }, { "zhi ji", "知己" },
			{ "zhi ji", "至极" }, { "zhi ji zhi bi", "知己知彼" }, { "zhi jia", "之家" }, { "zhi jia", "制假" }, { "zhi jia", "指甲" }, { "zhi jia", "支架" },
			{ "zhi jia ge", "芝加哥" }, { "zhi jia you", "指甲油" }, { "zhi jian", "之剑" }, { "zhi jian", "之间" }, { "zhi jian", "只见" }, { "zhi jian", "指尖" },
			{ "zhi jian", "指间" }, { "zhi jian", "质检" }, { "zhi jian", "质监" }, { "zhi jian ju", "质监局" }, { "zhi jiao", "之交" }, { "zhi jiao", "执教" },
			{ "zhi jiao", "指教" }, { "zhi jiao", "支教" }, { "zhi jiao", "直角" }, { "zhi jiao", "职教" }, { "zhi jie", "直接" }, { "zhi jie", "肢解" },
			{ "zhi jie dian ji", "直接点击" }, { "zhi jie guan xi", "直接关系" }, { "zhi jie jin ru", "直接进入" }, { "zhi jie liao dang", "直截了当" },
			{ "zhi jie tou zi", "直接投资" }, { "zhi jie ying xiang", "直接影响" }, { "zhi jin", "纸巾" }, { "zhi jin", "至今" }, { "zhi jing", "直径" },
			{ "zhi jing", "致敬" }, { "zhi jiu", "之久" }, { "zhi ju", "之举" }, { "zhi jue", "只觉" }, { "zhi jue", "直觉" }, { "zhi jue", "知觉" },
			{ "zhi jue de", "只觉得" }, { "zhi jun", "志军" }, { "zhi kan", "只看" }, { "zhi kan dao", "只看到" }, { "zhi kao", "只靠" }, { "zhi ke", "只可" },
			{ "zhi ke", "止咳" }, { "zhi ke xi", "只可惜" }, { "zhi ke yi", "只可以" }, { "zhi kong", "指控" }, { "zhi kou", "之口" }, { "zhi ku", "之苦" },
			{ "zhi kuai", "之快" }, { "zhi le", "之乐" }, { "zhi lei", "之类" }, { "zhi leng", "制冷" }, { "zhi li", "之力" }, { "zhi li", "智利" }, { "zhi li", "智力" },
			{ "zhi li", "治理" }, { "zhi li", "直立" }, { "zhi li", "致力" }, { "zhi li jie gou", "治理结构" }, { "zhi li po sui", "支离破碎" }, { "zhi lian", "之恋" },
			{ "zhi lian", "智联" }, { "zhi lian", "直连" }, { "zhi liang", "质量" }, { "zhi liang an quan", "质量安全" }, { "zhi liang bao zheng", "质量保证" },
			{ "zhi liang biao zhun", "质量标准" }, { "zhi liang cha", "质量差" }, { "zhi liang guan li", "质量管理" }, { "zhi liang hao", "质量好" },
			{ "zhi liang jian ce", "质量检测" }, { "zhi liang jian du", "质量监督" }, { "zhi liang kong zhi", "质量控制" }, { "zhi liang wen ti", "质量问题" },
			{ "zhi liao", "治疗" }, { "zhi liao fang an", "治疗方案" }, { "zhi liao fang fa", "治疗方法" }, { "zhi liao man xing", "治疗慢性" },
			{ "zhi liao xiao er", "治疗小儿" }, { "zhi liao xiao guo", "治疗效果" }, { "zhi lie", "之列" }, { "zhi ling", "指令" }, { "zhi liu", "之流" },
			{ "zhi liu", "只留" }, { "zhi liu", "支流" }, { "zhi liu", "滞留" }, { "zhi liu", "直流" }, { "zhi liu xia", "只留下" }, { "zhi lu", "之路" },
			{ "zhi lu", "指路" }, { "zhi lv", "之旅" }, { "zhi ma", "芝麻" }, { "zhi mai", "只买" }, { "zhi mai", "只卖" }, { "zhi mao", "只猫" }, { "zhi mei", "之美" },
			{ "zhi men", "之门" }, { "zhi meng", "之梦" }, { "zhi mi", "之谜" }, { "zhi mian", "直面" }, { "zhi miao", "之妙" }, { "zhi min", "殖民" },
			{ "zhi min di", "殖民地" }, { "zhi ming", "之名" }, { "zhi ming", "指名" }, { "zhi ming", "指明" }, { "zhi ming", "知名" }, { "zhi ming", "致命" },
			{ "zhi ming du", "知名度" }, { "zhi ming pin pai", "知名品牌" }, { "zhi ming qi ye", "知名企业" }, { "zhi ming ren shi", "知名人士" }, { "zhi mu", "之母" },
			{ "zhi na", "支那" }, { "zhi na jin", "滞纳金" }, { "zhi nan", "指南" }, { "zhi nan zhen", "指南针" }, { "zhi nei", "之内" }, { "zhi nen", "稚嫩" },
			{ "zhi neng", "只能" }, { "zhi neng", "智能" }, { "zhi neng", "职能" }, { "zhi neng bu men", "职能部门" }, { "zhi neng hua", "智能化" },
			{ "zhi neng ji", "智能机" }, { "zhi neng ka", "智能卡" }, { "zhi neng kan", "只能看" }, { "zhi neng shou ji", "智能手机" }, { "zhi neng wang", "智能网" },
			{ "zhi neng yong", "只能用" }, { "zhi niu", "执拗" }, { "zhi nong", "支农" }, { "zhi nv", "之女" }, { "zhi nv", "侄女" }, { "zhi nv", "织女" },
			{ "zhi pa", "只怕" }, { "zhi pai", "指派" }, { "zhi pai", "纸牌" }, { "zhi pei", "支配" }, { "zhi pi", "制皮" }, { "zhi pian", "制片" }, { "zhi pian", "纸片" },
			{ "zhi pian fang", "制片方" }, { "zhi pian ren", "制片人" }, { "zhi piao", "支票" }, { "zhi pin", "制品" }, { "zhi pu", "质朴" }, { "zhi qi", "之妻" },
			{ "zhi qi", "之气" }, { "zhi qi", "志气" }, { "zhi qi", "知其" }, { "zhi qi", "稚气" }, { "zhi qi guan", "支气管" }, { "zhi qi guan yan", "支气管炎" },
			{ "zhi qian", "之前" }, { "zhi qian", "值钱" }, { "zhi qian", "致歉" }, { "zhi qiang", "志强" }, { "zhi qiang", "至强" }, { "zhi qin", "执勤" },
			{ "zhi qing", "之情" }, { "zhi qing", "知情" }, { "zhi qing", "知青" }, { "zhi qing quan", "知情权" }, { "zhi qing ren", "知情人" }, { "zhi qing zhe", "知情者" },
			{ "zhi qiu", "只求" }, { "zhi qiu dui", "支球队" }, { "zhi qu", "支取" }, { "zhi quan", "职权" }, { "zhi re", "炙热" }, { "zhi ren", "之人" },
			{ "zhi ri", "之日" }, { "zhi ri ke dai", "指日可待" }, { "zhi ri qi", "之日起" }, { "zhi ru", "植入" }, { "zhi ru", "置入" }, { "zhi se", "之色" },
			{ "zhi shang", "之上" }, { "zhi shang", "智商" }, { "zhi shang", "纸上" }, { "zhi shang", "至上" }, { "zhi shang tan bing", "纸上谈兵" }, { "zhi shao", "至少" },
			{ "zhi she", "直射" }, { "zhi shen", "之神" }, { "zhi shen", "之身" }, { "zhi shen", "只身" }, { "zhi shen", "置身" }, { "zhi sheng", "之声" },
			{ "zhi sheng", "制胜" }, { "zhi sheng", "只剩" }, { "zhi sheng", "吱声" }, { "zhi sheng fei ji", "直升飞机" }, { "zhi sheng ji", "直升机" },
			{ "zhi sheng xia", "只剩下" }, { "zhi shi", "之事" }, { "zhi shi", "之势" }, { "zhi shi", "之士" }, { "zhi shi", "之师" }, { "zhi shi", "之时" },
			{ "zhi shi", "制式" }, { "zhi shi", "只是" }, { "zhi shi", "指使" }, { "zhi shi", "指示" }, { "zhi shi", "直视" }, { "zhi shi", "知识" }, { "zhi shi", "致使" },
			{ "zhi shi", "芝士" }, { "zhi shi chan quan", "知识产权" }, { "zhi shi deng", "指示灯" }, { "zhi shi dian", "知识点" }, { "zhi shi fen zi", "知识分子" },
			{ "zhi shi ge", "只是个" }, { "zhi shi guan li", "知识管理" }, { "zhi shi jie gou", "知识结构" }, { "zhi shi jing ji", "知识经济" },
			{ "zhi shi jing sai", "知识竞赛" }, { "zhi shi ku", "知识库" }, { "zhi shi mian", "知识面" }, { "zhi shou", "之手" }, { "zhi shou", "之首" },
			{ "zhi shou", "只手" }, { "zhi shou", "只收" }, { "zhi shou hua jiao", "指手画脚" }, { "zhi shou ke re", "炙手可热" }, { "zhi shu", "之术" },
			{ "zhi shu", "指数" }, { "zhi shu", "支书" }, { "zhi shu", "植树" }, { "zhi shu", "直属" }, { "zhi shu ji jin", "指数基金" }, { "zhi shu yu", "只属于" },
			{ "zhi shuai", "直率" }, { "zhi shuang", "直爽" }, { "zhi shui", "治水" }, { "zhi shuo", "只说" }, { "zhi shuo", "直说" }, { "zhi si", "之死" },
			{ "zhi si", "至死" }, { "zhi si", "致死" }, { "zhi su", "质素" }, { "zhi sun", "止损" }, { "zhi suo", "之所" }, { "zhi suo yi", "之所以" },
			{ "zhi suo zai", "之所在" }, { "zhi tan", "只谈" }, { "zhi ti", "肢体" }, { "zhi ti gong", "只提供" }, { "zhi tiao", "枝条" }, { "zhi tiao", "纸条" },
			{ "zhi ting", "只听" }, { "zhi tong", "之痛" }, { "zhi tong", "止痛" }, { "zhi tong", "直通" }, { "zhi tong che", "直通车" }, { "zhi tong dao he", "志同道合" },
			{ "zhi tou", "指头" }, { "zhi tou", "枝头" }, { "zhi tu", "之徒" }, { "zhi tu", "制图" }, { "zhi wai", "之外" }, { "zhi wang", "之王" }, { "zhi wang", "指望" },
			{ "zhi wei", "之位" }, { "zhi wei", "值为" }, { "zhi wei", "只为" }, { "zhi wei", "志伟" }, { "zhi wei", "职位" }, { "zhi wen", "之吻" }, { "zhi wen", "指纹" },
			{ "zhi wen", "质问" }, { "zhi wen shi bie", "指纹识别" }, { "zhi wo jian", "之我见" }, { "zhi wu", "之物" }, { "zhi wu", "之舞" }, { "zhi wu", "植物" },
			{ "zhi wu", "治污" }, { "zhi wu", "织物" }, { "zhi wu", "职务" }, { "zhi wu fan zui", "职务犯罪" }, { "zhi wu ren", "植物人" }, { "zhi wu you", "植物油" },
			{ "zhi wu yuan", "植物园" }, { "zhi xi", "知悉" }, { "zhi xi", "窒息" }, { "zhi xia", "之下" }, { "zhi xia", "直辖" }, { "zhi xia shi", "直辖市" },
			{ "zhi xian", "之嫌" }, { "zhi xian", "只限" }, { "zhi xian", "支线" }, { "zhi xian", "直线" }, { "zhi xian", "知县" }, { "zhi xian shi", "只显示" },
			{ "zhi xian yu", "只限于" }, { "zhi xiang", "之乡" }, { "zhi xiang", "只想" }, { "zhi xiang", "志向" }, { "zhi xiang", "指向" }, { "zhi xiang", "纸箱" },
			{ "zhi xiao", "滞销" }, { "zhi xiao", "直销" }, { "zhi xiao", "知晓" }, { "zhi xiao", "职校" }, { "zhi xie", "制鞋" }, { "zhi xie", "只写" },
			{ "zhi xie", "致谢" }, { "zhi xin", "之心" }, { "zhi xin", "知心" }, { "zhi xin", "置信" }, { "zhi xin", "致信" }, { "zhi xing", "之星" },
			{ "zhi xing", "之行" }, { "zhi xing", "执行" }, { "zhi xing", "直行" }, { "zhi xing", "知性" }, { "zhi xing dong shi", "执行董事" },
			{ "zhi xing guo cheng", "执行过程" }, { "zhi xing li", "执行力" } };
};
