package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN25 {
	public static String[][] pl = { { "jiu bu shi", "就不是" }, { "jiu cai", "韭菜" }, { "jiu can", "就餐" }, { "jiu ceng", "就曾" }, { "jiu cha", "就差" },
			{ "jiu chan", "纠缠" }, { "jiu chan bu qing", "纠缠不清" }, { "jiu chang", "酒厂" }, { "jiu che", "旧车" }, { "jiu cheng", "九城" }, { "jiu cheng", "九成" },
			{ "jiu cheng", "就成" }, { "jiu cheng", "旧城" }, { "jiu cheng gai zao", "旧城改造" }, { "jiu chi", "就吃" }, { "jiu chu", "揪出" }, { "jiu chu", "救出" },
			{ "jiu ci", "就此" }, { "jiu cong", "就从" }, { "jiu cuo", "纠错" }, { "jiu da", "九大" }, { "jiu da", "就打" }, { "jiu da", "就达" }, { "jiu dai", "就带" },
			{ "jiu dang", "就当" }, { "jiu dao", "就到" }, { "jiu de", "就得" }, { "jiu de", "旧的" }, { "jiu dei", "就得" }, { "jiu deng", "久等" }, { "jiu dian", "九点" },
			{ "jiu dian", "酒店" }, { "jiu dian ban", "九点半" }, { "jiu du", "就读" }, { "jiu duan", "九段" }, { "jiu dui", "就对" }, { "jiu duo", "就多" },
			{ "jiu er jiu zhi", "久而久之" }, { "jiu fen", "纠纷" }, { "jiu gai", "就该" }, { "jiu ge", "九个" }, { "jiu ge", "纠葛" }, { "jiu ge yue", "九个月" },
			{ "jiu gei", "就给" }, { "jiu gen", "就跟" }, { "jiu geng", "就更" }, { "jiu gou", "就够" }, { "jiu gou le", "就够了" }, { "jiu guan", "酒馆" },
			{ "jiu gui", "酒鬼" }, { "jiu guo", "救国" }, { "jiu hao", "就好" }, { "jiu hao xiang", "就好象" }, { "jiu he", "就和" }, { "jiu hen", "就很" },
			{ "jiu hou", "酒后" }, { "jiu hu", "救护" }, { "jiu hu che", "救护车" }, { "jiu hua shan", "九华山" }, { "jiu hui", "就会" }, { "jiu hui", "就回" },
			{ "jiu hui", "酒会" }, { "jiu hui chu xian", "就会出现" }, { "jiu hui you", "就会有" }, { "jiu huo", "救活" }, { "jiu huo", "救火" }, { "jiu huo", "旧货" },
			{ "jiu ji", "救急" }, { "jiu ji", "救济" }, { "jiu jia", "酒家" }, { "jiu jian", "就见" }, { "jiu jiang", "九江" }, { "jiu jiang", "就将" },
			{ "jiu jiao", "就叫" }, { "jiu jie", "九届" }, { "jiu jie", "纠结" }, { "jiu jin", "就近" }, { "jiu jin", "就进" }, { "jiu jin shan", "旧金山" },
			{ "jiu jing", "究竟" }, { "jiu jing", "酒精" }, { "jiu jiu", "久久" }, { "jiu jiu", "九九" }, { "jiu jiu", "救救" }, { "jiu jiu", "舅舅" },
			{ "jiu kai", "就开" }, { "jiu kan", "就看" }, { "jiu ke", "就可" }, { "jiu kuai", "就快" }, { "jiu lai", "就来" }, { "jiu le", "救了" }, { "jiu lei", "酒类" },
			{ "jiu lian", "就连" }, { "jiu liang", "酒量" }, { "jiu liu", "九六" }, { "jiu long", "九龙" }, { "jiu lou", "酒楼" }, { "jiu ma", "舅妈" },
			{ "jiu mai", "就买" }, { "jiu mei", "就没" }, { "jiu ming", "救命" }, { "jiu ming dao cao", "救命稻草" }, { "jiu na", "就拿" }, { "jiu nan", "就难" },
			{ "jiu neng", "就能" }, { "jiu nian", "九年" }, { "jiu pa", "就怕" }, { "jiu pao", "就跑" }, { "jiu ping", "就凭" }, { "jiu ping", "酒瓶" },
			{ "jiu qi", "究其" }, { "jiu qian", "九千" }, { "jiu qing", "就请" }, { "jiu qing", "旧情" }, { "jiu qu", "就去" }, { "jiu quan", "酒泉" },
			{ "jiu rang", "就让" }, { "jiu rang ni", "就让你" }, { "jiu rang wo", "就让我" }, { "jiu ren", "就任" }, { "jiu ren", "救人" }, { "jiu ri", "九日" },
			{ "jiu ri", "旧日" }, { "jiu ru", "就如" }, { "jiu san", "九三" }, { "jiu she hui", "旧社会" }, { "jiu sheng", "救生" }, { "jiu sheng quan", "救生圈" },
			{ "jiu shi", "九十" }, { "jiu shi", "就是" }, { "jiu shi", "救市" }, { "jiu shi", "旧事" }, { "jiu shi", "旧式" }, { "jiu shi", "旧时" },
			{ "jiu shi ai", "就是爱" }, { "jiu shi jiu", "九十九" }, { "jiu shi lun shi", "就事论事" }, { "jiu shi na ge", "就是那个" }, { "jiu shi nian dai", "九十年代" },
			{ "jiu shi zhe yang", "就是这样" }, { "jiu shi zhi", "就是指" }, { "jiu shi zhu", "救世主" }, { "jiu shou", "就收" }, { "jiu shu", "救赎" }, { "jiu shu", "旧书" },
			{ "jiu shui", "酒水" }, { "jiu shuo", "就说" }, { "jiu si", "九四" }, { "jiu si", "就死" }, { "jiu song", "就送" }, { "jiu suan", "就算" },
			{ "jiu sui", "九岁" }, { "jiu tian", "九天" }, { "jiu tiao", "九条" }, { "jiu ting", "就听" }, { "jiu wei", "久违" }, { "jiu wen", "就问" },
			{ "jiu wo", "就我" }, { "jiu wo", "救我" }, { "jiu wo", "酒窝" }, { "jiu wu", "九五" }, { "jiu xi", "酒席" }, { "jiu xia", "救下" }, { "jiu xian", "就先" },
			{ "jiu xiang", "就像" }, { "jiu xiang", "就向" }, { "jiu xiang", "就想" }, { "jiu xiang", "就象" }, { "jiu xiang shi", "就像是" }, { "jiu xie", "就写" },
			{ "jiu xin", "揪心" }, { "jiu xing", "就行" }, { "jiu xing", "救星" }, { "jiu xing", "酒醒" }, { "jiu xu", "就绪" }, { "jiu xue", "就学" },
			{ "jiu yao", "就要" }, { "jiu ye", "就业" }, { "jiu ye", "酒业" }, { "jiu ye fu wu", "就业服务" }, { "jiu ye gang wei", "就业岗位" },
			{ "jiu ye gong zuo", "就业工作" }, { "jiu ye ji hui", "就业机会" }, { "jiu ye lv", "就业率" }, { "jiu ye wen ti", "就业问题" }, { "jiu ye xing shi", "就业形势" },
			{ "jiu ye ya li", "就业压力" }, { "jiu ye yuan zhu", "就业援助" }, { "jiu ye zhi dao", "就业指导" }, { "jiu yi", "就以" }, { "jiu yi", "就医" },
			{ "jiu yi", "就已" }, { "jiu ying", "就应" }, { "jiu yong", "就用" }, { "jiu you", "就又" }, { "jiu you", "就有" }, { "jiu you", "旧有" },
			{ "jiu you le", "就有了" }, { "jiu yuan", "久远" }, { "jiu yuan", "救援" }, { "jiu yuan dui", "救援队" }, { "jiu yue", "九月" }, { "jiu yue", "就越" },
			{ "jiu yue fen", "九月份" }, { "jiu zai", "就再" }, { "jiu zai", "就在" }, { "jiu zai", "救灾" }, { "jiu zai zhe", "就在这" }, { "jiu zai zhe li", "就在这里" },
			{ "jiu zhai", "九寨" }, { "jiu zhai gou", "九寨沟" }, { "jiu zhao", "就找" }, { "jiu zhe", "就这" }, { "jiu zhen", "就诊" }, { "jiu zheng", "纠正" },
			{ "jiu zhi", "就只" }, { "jiu zhi", "就职" }, { "jiu zhi", "救治" }, { "jiu zhi", "旧址" }, { "jiu zhou", "九州" }, { "jiu zhu", "揪住" }, { "jiu zhu", "救助" },
			{ "jiu zou", "就走" }, { "jiu zui", "酒醉" }, { "jiu zuo", "就做" }, { "jiu zuo", "就坐" }, { "ju", "且" }, { "ju", "举" }, { "ju", "侷" }, { "ju", "俥" },
			{ "ju", "俱" }, { "ju", "倨" }, { "ju", "倶" }, { "ju", "具" }, { "ju", "剧" }, { "ju", "劇" }, { "ju", "匊" }, { "ju", "句" }, { "ju", "咀" },
			{ "ju", "埧" }, { "ju", "壉" }, { "ju", "姖" }, { "ju", "娵" }, { "ju", "局" }, { "ju", "居" }, { "ju", "屦" }, { "ju", "屨" }, { "ju", "岠" },
			{ "ju", "岨" }, { "ju", "崌" }, { "ju", "巨" }, { "ju", "惧" }, { "ju", "懅" }, { "ju", "懼" }, { "ju", "拒" }, { "ju", "拘" }, { "ju", "拠" },
			{ "ju", "挙" }, { "ju", "挶" }, { "ju", "据" }, { "ju", "掬" }, { "ju", "據" }, { "ju", "擧" }, { "ju", "枸" }, { "ju", "柜" }, { "ju", "桔" },
			{ "ju", "梮" }, { "ju", "椇" }, { "ju", "椈" }, { "ju", "椐" }, { "ju", "榉" }, { "ju", "榘" }, { "ju", "橘" }, { "ju", "櫸" }, { "ju", "欅" },
			{ "ju", "沮" }, { "ju", "泃" }, { "ju", "洰" }, { "ju", "涺" }, { "ju", "淗" }, { "ju", "湨" }, { "ju", "澽" }, { "ju", "炬" }, { "ju", "焗" },
			{ "ju", "焣" }, { "ju", "犋" }, { "ju", "犑" }, { "ju", "狊" }, { "ju", "狙" }, { "ju", "琚" }, { "ju", "疽" }, { "ju", "痀" }, { "ju", "矩" },
			{ "ju", "秬" }, { "ju", "窭" }, { "ju", "筥" }, { "ju", "粔" }, { "ju", "罝" }, { "ju", "耟" }, { "ju", "聚" }, { "ju", "腒" }, { "ju", "舉" },
			{ "ju", "苣" }, { "ju", "苴" }, { "ju", "莒" }, { "ju", "菊" }, { "ju", "蒟" }, { "ju", "蘜" }, { "ju", "虡" }, { "ju", "蚷" }, { "ju", "蜛" },
			{ "ju", "袓" }, { "ju", "裾" }, { "ju", "襷" }, { "ju", "詎" }, { "ju", "讵" }, { "ju", "豦" }, { "ju", "趄" }, { "ju", "距" }, { "ju", "踘" },
			{ "ju", "踞" }, { "ju", "踽" }, { "ju", "躆" }, { "ju", "輂" }, { "ju", "车" }, { "ju", "遽" }, { "ju", "郹" }, { "ju", "醵" }, { "ju", "鉅" },
			{ "ju", "鋦" }, { "ju", "鋸" }, { "ju", "钜" }, { "ju", "锔" }, { "ju", "锯" }, { "ju", "閰" }, { "ju", "陱" }, { "ju", "雎" }, { "ju", "鞠" },
			{ "ju", "鞫" }, { "ju", "颶" }, { "ju", "飓" }, { "ju", "駏" }, { "ju", "駒" }, { "ju", "駶" }, { "ju", "驧" }, { "ju", "驹" }, { "ju", "鵙" },
			{ "ju", "鵴" }, { "ju", "鶋" }, { "ju", "鶪" }, { "ju", "龃" }, { "ju an zhi", "聚氨酯" }, { "ju ban", "举办" }, { "ju bao", "举报" },
			{ "ju bao dian hua", "举报电话" }, { "ju bao ren", "举报人" }, { "ju bei", "举杯" }, { "ju bei", "具备" }, { "ju ben", "剧本" }, { "ju bian", "巨变" },
			{ "ju bing", "句柄" }, { "ju bing xi", "聚丙烯" }, { "ju bu", "局部" }, { "ju bu", "拒不" }, { "ju bu", "拘捕" }, { "ju bu di qu", "局部地区" },
			{ "ju can", "聚餐" }, { "ju chang", "剧场" }, { "ju chang ban", "剧场版" }, { "ju cheng", "据称" }, { "ju chi", "锯齿" }, { "ju chu", "举出" },
			{ "ju chuan", "据传" }, { "ju ci", "据此" }, { "ju cu", "局促" }, { "ju cuo", "举措" }, { "ju da", "巨大" }, { "ju da bian hua", "巨大变化" },
			{ "ju dian", "据点" }, { "ju dong", "举动" }, { "ju du", "剧毒" }, { "ju duo", "居多" }, { "ju e", "巨额" }, { "ju fang", "局方" }, { "ju feng", "飓风" },
			{ "ju fu", "巨幅" }, { "ju fu ju zhang", "局副局长" }, { "ju gao bu xia", "居高不下" }, { "ju gao lin xia", "居高临下" }, { "ju ge", "举个" }, { "ju gong", "鞠躬" },
			{ "ju guo", "举国" }, { "ju hao", "句号" }, { "ju he", "聚合" }, { "ju he wu", "聚合物" }, { "ju hua", "句话" }, { "ju hua", "菊花" }, { "ju hui", "聚会" },
			{ "ju ji", "剧集" }, { "ju ji", "狙击" }, { "ju ji", "聚集" }, { "ju ji di", "聚集地" }, { "ju ji guan", "局机关" }, { "ju ji shou", "狙击手" },
			{ "ju jia", "举家" }, { "ju jia", "俱佳" }, { "ju jia", "居家" }, { "ju jiao", "聚焦" }, { "ju jin", "拘谨" }, { "ju jin", "距今" },
			{ "ju jing hui shen", "聚精会神" }, { "ju ju", "句句" }, { "ju ju", "聚居" }, { "ju ju", "聚聚" }, { "ju ju zhang", "局局长" }, { "ju jue", "咀嚼" },
			{ "ju jue", "拒绝" }, { "ju kuan", "巨款" }, { "ju lang", "巨浪" }, { "ju le", "举了" }, { "ju le bu", "俱乐部" }, { "ju lei", "聚类" }, { "ju li", "举例" },
			{ "ju li", "局里" }, { "ju li", "距离" }, { "ju liang", "巨量" }, { "ju lie", "剧烈" }, { "ju liu", "居留" }, { "ju liu", "拘留" }, { "ju long", "巨龙" },
			{ "ju mian", "局面" }, { "ju min", "居民" }, { "ju min lou", "居民楼" }, { "ju min qu", "居民区" }, { "ju min sheng huo", "居民生活" },
			{ "ju min shou ru", "居民收入" }, { "ju min xiao fei", "居民消费" }, { "ju mo", "巨魔" }, { "ju mu", "剧目" }, { "ju ni", "拘泥" }, { "ju pa", "惧怕" },
			{ "ju qi", "举起" }, { "ju qian", "居前" }, { "ju qian", "拒签" }, { "ju qing", "剧情" }, { "ju qing jie shao", "剧情介绍" }, { "ju quan", "俱全" },
			{ "ju ran", "居然" }, { "ju ren", "巨人" }, { "ju ru", "巨乳" }, { "ju sang", "沮丧" }, { "ju shi", "举世" }, { "ju shi", "句式" }, { "ju shi", "局势" },
			{ "ju shi", "居士" }, { "ju shi", "居室" }, { "ju shi", "巨石" }, { "ju shi jie", "居世界" }, { "ju shi zhu mu", "举世瞩目" }, { "ju shou", "举手" },
			{ "ju shou", "拒收" }, { "ju shou", "聚首" }, { "ju shou tou zu", "举手投足" }, { "ju shou zhi lao", "举手之劳" }, { "ju shu", "拘束" }, { "ju shuo", "据说" },
			{ "ju suo", "居所" }, { "ju ti", "具体" }, { "ju ti biao xian", "具体表现" }, { "ju ti cao zuo", "具体操作" }, { "ju ti cuo shi", "具体措施" },
			{ "ju ti fang fa", "具体方法" }, { "ju ti gong zuo", "具体工作" }, { "ju ti gui ding", "具体规定" }, { "ju ti hua", "具体化" }, { "ju ti nei rong", "具体内容" },
			{ "ju ti qing kuang", "具体情况" }, { "ju ti shi shi", "具体实施" }, { "ju ti wei zhi", "具体位置" }, { "ju ti wen ti", "具体问题" }, { "ju ti yao qiu", "具体要求" },
			{ "ju tong", "剧痛" }, { "ju tou", "巨头" }, { "ju tuan", "剧团" }, { "ju wai ren", "局外人" }, { "ju wei hui", "居委会" }, { "ju wo", "据我" },
			{ "ju wu ba", "巨无霸" }, { "ju xi", "据悉" }, { "ju xian", "局限" }, { "ju xian xing", "局限性" }, { "ju xiang", "巨响" }, { "ju xie", "巨蟹" },
			{ "ju xie zuo", "巨蟹座" }, { "ju xing", "举行" }, { "ju xing", "句型" }, { "ju xing", "巨型" }, { "ju xing", "巨星" }, { "ju xing", "矩形" },
			{ "ju yi fan san", "举一反三" }, { "ju yi xi", "聚乙烯" }, { "ju you", "具有" }, { "ju you jiao qiang", "具有较强" }, { "ju you liang hao", "具有良好" },
			{ "ju yu", "居于" }, { "ju yu wang", "局域网" }, { "ju yuan", "剧院" }, { "ju zai", "聚在" }, { "ju zeng", "剧增" }, { "ju zhang", "局长" },
			{ "ju zhao", "剧照" }, { "ju zhe", "举着" }, { "ju zhen", "矩阵" }, { "ju zheng", "举证" }, { "ju zhi", "举止" }, { "ju zhi", "聚酯" },
			{ "ju zhi men wai", "拒之门外" }, { "ju zhong", "举重" }, { "ju zhong", "剧中" }, { "ju zhong", "居中" }, { "ju zhong", "聚众" }, { "ju zhu", "居住" },
			{ "ju zhu", "巨著" }, { "ju zhu di", "居住地" }, { "ju zhu huan jing", "居住环境" }, { "ju zhu qu", "居住区" }, { "ju zhu zheng", "居住证" }, { "ju zi", "句子" },
			{ "ju zi", "巨资" }, { "ju zi", "桔子" }, { "ju zi", "橘子" }, { "ju zu", "剧组" }, { "ju zu qing zhong", "举足轻重" }, { "juan", "倦" }, { "juan", "劵" },
			{ "juan", "卷" }, { "juan", "呟" }, { "juan", "圈" }, { "juan", "娟" }, { "juan", "帣" }, { "juan", "捐" }, { "juan", "捲" }, { "juan", "朘" },
			{ "juan", "桊" }, { "juan", "涓" }, { "juan", "淃" }, { "juan", "狷" }, { "juan", "眷" }, { "juan", "睊" }, { "juan", "睠" }, { "juan", "絭" },
			{ "juan", "絹" }, { "juan", "绢" }, { "juan", "罥" }, { "juan", "羂" }, { "juan", "臇" }, { "juan", "菤" }, { "juan", "蠲" }, { "juan", "裐" },
			{ "juan", "鄄" }, { "juan", "鋑" }, { "juan", "錈" }, { "juan", "鐫" }, { "juan", "锩" }, { "juan", "镌" }, { "juan", "隽" }, { "juan", "雋" },
			{ "juan", "鵑" }, { "juan", "鹃" }, { "juan chu", "捐出" }, { "juan dai", "倦怠" }, { "juan fa", "卷发" }, { "juan gei", "捐给" }, { "juan gu", "眷顾" },
			{ "juan juan", "娟娟" }, { "juan kuan", "捐款" }, { "juan lian", "眷恋" }, { "juan qi", "卷起" }, { "juan qian", "捐钱" }, { "juan qu", "卷曲" },
			{ "juan rong", "倦容" }, { "juan ru", "卷入" }, { "juan shu", "眷属" }, { "juan tu chong lai", "卷土重来" }, { "juan xian", "捐献" }, { "juan yan", "卷烟" },
			{ "juan yan chang", "卷烟厂" }, { "juan zeng", "捐赠" }, { "juan zhou", "卷轴" }, { "juan zhu", "捐助" }, { "juan zi", "卷子" }, { "juan zi", "娟子" },
			{ "juan zi", "捐资" }, { "jue", "亅" }, { "jue", "倔" }, { "jue", "傕" }, { "jue", "决" }, { "jue", "刔" }, { "jue", "劂" }, { "jue", "厥" },
			{ "jue", "噘" }, { "jue", "噱" }, { "jue", "嚼" }, { "jue", "孓" }, { "jue", "屩" }, { "jue", "崛" }, { "jue", "嶡" }, { "jue", "廴" }, { "jue", "彏" },
			{ "jue", "憰" }, { "jue", "戄" }, { "jue", "抉" }, { "jue", "掘" }, { "jue", "撅" }, { "jue", "攫" }, { "jue", "桷" }, { "jue", "橛" }, { "jue", "殌" },
			{ "jue", "決" }, { "jue", "爝" }, { "jue", "爵" }, { "jue", "獗" }, { "jue", "玃" }, { "jue", "玦" }, { "jue", "玨" }, { "jue", "珏" }, { "jue", "瘚" },
			{ "jue", "矍" }, { "jue", "絕" }, { "jue", "絶" }, { "jue", "绝" }, { "jue", "脚" }, { "jue", "臄" }, { "jue", "芵" }, { "jue", "蕝" }, { "jue", "蕨" },
			{ "jue", "虳" }, { "jue", "蟨" }, { "jue", "覚" }, { "jue", "覺" }, { "jue", "觉" }, { "jue", "角" }, { "jue", "觖" }, { "jue", "觼" }, { "jue", "訣" },
			{ "jue", "譎" }, { "jue", "诀" }, { "jue", "谲" }, { "jue", "貜" }, { "jue", "赽" }, { "jue", "趉" }, { "jue", "趹" }, { "jue", "蹶" }, { "jue", "鈌" },
			{ "jue", "鐍" }, { "jue", "钁" }, { "jue", "镢" }, { "jue", "镼" }, { "jue", "駃" }, { "jue", "鱖" }, { "jue", "鴃" }, { "jue", "鷢" },
			{ "jue ban", "绝版" }, { "jue bu", "决不" }, { "jue bu", "绝不" }, { "jue bu neng", "决不能" }, { "jue ce", "决策" }, { "jue ce ceng", "决策层" },
			{ "jue ce zhe", "决策者" }, { "jue cha", "觉察" }, { "jue chen", "绝尘" }, { "jue chu", "决出" }, { "jue da", "绝大" }, { "jue da bu fen", "绝大部分" },
			{ "jue da duo shu", "绝大多数" }, { "jue dai", "绝代" }, { "jue de", "觉得" }, { "jue de", "觉的" }, { "jue de hen", "觉得很" }, { "jue de zi ji", "觉得自己" },
			{ "jue di", "绝地" }, { "jue ding", "决定" }, { "jue ding", "绝顶" }, { "jue ding quan", "决定权" }, { "jue ding shu", "决定书" }, { "jue ding xing", "决定性" },
			{ "jue dou", "决斗" }, { "jue duan", "决断" }, { "jue dui", "绝对" }, { "jue dui bu hui", "绝对不会" }, { "jue dui bu neng", "绝对不能" },
			{ "jue dui bu shi", "绝对不是" }, { "jue dui you shi", "绝对优势" }, { "jue dui zhi", "绝对值" }, { "jue fei", "绝非" }, { "jue hao", "绝好" },
			{ "jue huo", "绝活" }, { "jue ji", "绝技" }, { "jue ji", "绝迹" }, { "jue jia", "绝佳" }, { "jue jiang", "倔强" }, { "jue jiao", "绝交" }, { "jue jin", "掘金" },
			{ "jue jing", "绝境" }, { "jue jue", "决绝" }, { "jue lie", "决裂" }, { "jue lu", "绝路" }, { "jue lun", "绝伦" }, { "jue mei", "绝美" }, { "jue mi", "绝密" },
			{ "jue miao", "绝妙" }, { "jue pei", "绝配" }, { "jue qi", "崛起" }, { "jue qiao", "诀窍" }, { "jue qing", "绝情" }, { "jue qu", "攫取" }, { "jue sai", "决赛" },
			{ "jue se", "绝色" }, { "jue se", "角色" }, { "jue sha", "绝杀" }, { "jue shi", "爵士" }, { "jue shi", "绝世" }, { "jue shi", "绝食" },
			{ "jue shi yue", "爵士乐" }, { "jue suan", "决算" }, { "jue wang", "绝望" }, { "jue wu", "绝无" }, { "jue wu", "觉悟" }, { "jue wu jin you", "绝无仅有" },
			{ "jue xin", "决心" }, { "jue xing", "觉醒" }, { "jue yi", "决意" }, { "jue yi", "决议" }, { "jue yuan", "绝缘" }, { "jue ze", "抉择" }, { "jue zhan", "决战" },
			{ "jue zhao", "绝招" }, { "jue zhe", "觉着" }, { "jue zheng", "绝症" }, { "jue zhong", "绝种" }, { "jue zhu", "角逐" }, { "jun", "俊" }, { "jun", "儁" },
			{ "jun", "军" }, { "jun", "君" }, { "jun", "呁" }, { "jun", "均" }, { "jun", "埈" }, { "jun", "寯" }, { "jun", "峻" }, { "jun", "捃" }, { "jun", "晙" },
			{ "jun", "桾" }, { "jun", "浚" }, { "jun", "焌" }, { "jun", "燇" }, { "jun", "珺" }, { "jun", "畯" }, { "jun", "皲" }, { "jun", "皸" }, { "jun", "皹" },
			{ "jun", "碅" }, { "jun", "竣" }, { "jun", "筠" }, { "jun", "箟" }, { "jun", "莙" }, { "jun", "菌" }, { "jun", "蔨" }, { "jun", "蚐" }, { "jun", "蜠" },
			{ "jun", "袀" }, { "jun", "軍" }, { "jun", "郡" }, { "jun", "鈞" }, { "jun", "鍕" }, { "jun", "钧" }, { "jun", "隽" }, { "jun", "餕" }, { "jun", "駿" },
			{ "jun", "骏" }, { "jun", "鮶" }, { "jun", "鵔" }, { "jun", "鵘" }, { "jun", "麇" }, { "jun", "龟" }, { "jun bei", "均被" }, { "jun bu", "均不" },
			{ "jun bu jian", "君不见" }, { "jun che", "军车" }, { "jun chen", "君臣" }, { "jun dao", "军刀" }, { "jun deng", "均等" }, { "jun dui", "军队" },
			{ "jun fa", "军阀" }, { "jun fang", "军方" }, { "jun fei", "军费" }, { "jun fen qu", "军分区" }, { "jun fu", "军服" }, { "jun gong", "军工" },
			{ "jun gong", "竣工" }, { "jun gong yan shou", "竣工验收" }, { "jun guan", "军官" }, { "jun guo zhu yi", "军国主义" }, { "jun heng", "均衡" },
			{ "jun huo", "军火" }, { "jun jia", "均价" }, { "jun jian", "军舰" }, { "jun jie", "俊杰" }, { "jun jie", "骏捷" }, { "jun jing", "军警" },
			{ "jun jun", "君君" }, { "jun ke", "均可" }, { "jun lang", "俊朗" }, { "jun li", "军力" }, { "jun lv", "军旅" }, { "jun ma", "骏马" }, { "jun mei", "俊美" },
			{ "jun min", "军民" }, { "jun nan", "俊男" }, { "jun neng", "均能" }, { "jun qi", "军旗" }, { "jun qiao", "俊俏" }, { "jun qing", "军情" }, { "jun qu", "军区" },
			{ "jun ren", "军人" }, { "jun shi", "军事" }, { "jun shi", "军师" }, { "jun shi", "均是" }, { "jun shi ji di", "军事基地" }, { "jun shi li liang", "军事力量" },
			{ "jun shi xing dong", "军事行动" }, { "jun shi xun lian", "军事训练" }, { "jun shi yan xi", "军事演习" }, { "jun shu", "均属" }, { "jun tuan", "军团" },
			{ "jun wang", "君王" }, { "jun wei", "军委" }, { "jun wei", "均为" }, { "jun wei", "均未" }, { "jun wu", "均无" }, { "jun xian", "军衔" },
			{ "jun xian", "均线" }, { "jun xiao", "军校" }, { "jun xiu", "俊秀" }, { "jun xu", "均需" }, { "jun xun", "军训" }, { "jun yan", "军演" }, { "jun yi", "军医" },
			{ "jun yi", "均以" }, { "jun yi", "均已" }, { "jun ying", "军营" }, { "jun ying", "均应" }, { "jun yong", "军用" }, { "jun you", "均有" }, { "jun you", "均由" },
			{ "jun yun", "均匀" }, { "jun zai", "均在" }, { "jun zhang", "军长" }, { "jun zheng", "军政" }, { "jun zhi", "均值" }, { "jun zhong", "军中" },
			{ "jun zhong", "菌种" }, { "jun zhu", "君主" }, { "jun zhu", "菌株" }, { "jun zhu", "郡主" }, { "jun zhuang", "军装" }, { "jun zi", "君子" }, { "ka", "佧" },
			{ "ka", "卡" }, { "ka", "咔" }, { "ka", "咖" }, { "ka", "咯" }, { "ka", "喀" }, { "ka", "垰" }, { "ka", "擖" }, { "ka", "胩" }, { "ka", "裃" },
			{ "ka", "鉲" }, { "ka ba", "卡吧" }, { "ka ba", "卡巴" }, { "ka ba si ji", "卡巴斯基" }, { "ka cha", "咔嚓" }, { "ka cha", "喀嚓" }, { "ka che", "卡车" },
			{ "ka ding che", "卡丁车" }, { "ka en", "卡恩" }, { "ka er", "卡尔" }, { "ka er de", "卡尔德" }, { "ka fei", "咖啡" }, { "ka fei dian", "咖啡店" },
			{ "ka fei guan", "咖啡馆" }, { "ka fei se", "咖啡色" }, { "ka fei ting", "咖啡厅" }, { "ka fei yin", "咖啡因" }, { "ka fu ka", "卡夫卡" }, { "ka hao", "卡号" },
			{ "ka ka", "卡卡" }, { "ka ka", "咔咔" }, { "ka ka xi", "卡卡西" }, { "ka la", "卡拉" }, { "ka le", "卡勒" }, { "ka li", "卡里" }, { "ka lu li", "卡路里" },
			{ "ka luo", "卡罗" }, { "ka luo si", "卡洛斯" }, { "ka mai long", "喀麦隆" }, { "ka men", "卡门" }, { "ka na wa luo", "卡纳瓦罗" }, { "ka ni", "卡尼" },
			{ "ka pei luo", "卡佩罗" }, { "ka pian", "卡片" }, { "ka pian ji", "卡片机" }, { "ka shang", "卡上" }, { "ka shi", "喀什" }, { "ka si", "卡斯" },
			{ "ka si", "卡死" }, { "ka si te luo", "卡斯特罗" }, { "ka ta er", "卡塔尔" }, { "ka te", "卡特" }, { "ka tong", "卡通" }, { "ka wa yi", "卡哇伊" },
			{ "ka xi ou", "卡西欧" }, { "ka zai", "卡在" }, { "ka zhu", "卡住" }, { "kai", "凯" }, { "kai", "凱" }, { "kai", "剀" }, { "kai", "剴" }, { "kai", "勓" },
			{ "kai", "垲" }, { "kai", "塏" }, { "kai", "开" }, { "kai", "忾" }, { "kai", "恺" }, { "kai", "愷" }, { "kai", "慨" }, { "kai", "揩" }, { "kai", "暟" },
			{ "kai", "楷" }, { "kai", "欬" }, { "kai", "烗" }, { "kai", "蒈" }, { "kai", "輆" }, { "kai", "鍇" }, { "kai", "鎎" }, { "kai", "鎧" }, { "kai", "铠" },
			{ "kai", "锎" }, { "kai", "锴" }, { "kai", "開" }, { "kai", "闓" }, { "kai", "颽" }, { "kai ban", "开办" }, { "kai ban", "开班" }, { "kai biao", "开标" },
			{ "kai bo", "开播" }, { "kai cai", "开采" }, { "kai chang", "开唱" }, { "kai chang", "开场" }, { "kai chang bai", "开场白" }, { "kai che", "开车" },
			{ "kai che qu", "开车去" }, { "kai chu", "开出" }, { "kai chu", "开除" }, { "kai chuang", "开创" }, { "kai chuang", "开窗" }, { "kai da", "开打" },
			{ "kai dao", "开刀" }, { "kai dao", "开到" }, { "kai dao", "开导" }, { "kai de", "开得" }, { "kai deng", "开灯" }, { "kai di", "凯迪" },
			{ "kai di la ke", "凯迪拉克" }, { "kai dian", "开店" }, { "kai dong", "开动" }, { "kai duan", "开端" }, { "kai en si", "凯恩斯" }, { "kai er te ren", "凯尔特人" },
			{ "kai fa", "开发" }, { "kai fa ban", "开发板" }, { "kai fa bu", "开发部" }, { "kai fa chu", "开发出" }, { "kai fa gong ju", "开发工具" },
			{ "kai fa gong si", "开发公司" }, { "kai fa guo cheng", "开发过程" }, { "kai fa huan jing", "开发环境" }, { "kai fa jian she", "开发建设" },
			{ "kai fa li yong", "开发利用" }, { "kai fa piao", "开发票" }, { "kai fa qi ye", "开发企业" }, { "kai fa qu", "开发区" }, { "kai fa ren yuan", "开发人员" },
			{ "kai fa shang", "开发商" }, { "kai fa xiang mu", "开发项目" }, { "kai fa zhe", "开发者" }, { "kai fan", "开饭" }, { "kai fang", "开房" }, { "kai fang", "开放" },
			{ "kai fang shi", "开放式" } };
};
