package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN43 {
	public static String[][] pl = { { "shi yi", "事宜" }, { "shi yi", "十一" }, { "shi yi", "十亿" }, { "shi yi", "失忆" }, { "shi yi", "失意" }, { "shi yi", "施以" },
			{ "shi yi", "是一" }, { "shi yi", "是以" }, { "shi yi", "示意" }, { "shi yi", "诗意" }, { "shi yi", "适宜" }, { "shi yi", "释义" }, { "shi yi ben", "是一本" },
			{ "shi yi bu", "是一部" }, { "shi yi dian", "十一点" }, { "shi yi jian", "是一件" }, { "shi yi jie", "十一届" }, { "shi yi kuan", "是一款" },
			{ "shi yi men", "是一门" }, { "shi yi ming", "是一名" }, { "shi yi shi", "试一试" }, { "shi yi tu", "示意图" }, { "shi yi wei", "是一位" },
			{ "shi yi wu", "十一五" }, { "shi yi xiang", "是一项" }, { "shi yi yang de", "是一样的" }, { "shi yi yue", "十一月" }, { "shi yi zhi", "是一只" },
			{ "shi yi zhong", "是一种" }, { "shi yi zuo", "是一座" }, { "shi ying", "时应" }, { "shi ying", "石英" }, { "shi ying", "适应" }, { "shi ying lv", "市盈率" },
			{ "shi ying neng li", "适应能力" }, { "shi ying xing", "适应性" }, { "shi ying zhu yi", "时应注意" }, { "shi yong", "使用" }, { "shi yong", "实用" },
			{ "shi yong", "施用" }, { "shi yong", "时用" }, { "shi yong", "是用" }, { "shi yong", "试用" }, { "shi yong", "适用" }, { "shi yong", "食用" },
			{ "shi yong ban", "试用版" }, { "shi yong dian nao", "使用电脑" }, { "shi yong fan wei", "适用范围" }, { "shi yong fang fa", "使用方法" },
			{ "shi yong fei", "使用费" }, { "shi yong ji shu", "实用技术" }, { "shi yong jia zhi", "使用价值" }, { "shi yong jun", "食用菌" }, { "shi yong liang", "使用量" },
			{ "shi yong lv", "使用率" }, { "shi yong qi", "试用期" }, { "shi yong qian", "使用前" }, { "shi yong qing kuang", "使用情况" }, { "shi yong quan", "使用权" },
			{ "shi yong shi jian", "使用时间" }, { "shi yong shou ming", "使用寿命" }, { "shi yong shuo ming", "使用说明" }, { "shi yong xing", "实用性" },
			{ "shi yong xing", "适用性" }, { "shi yong you", "食用油" }, { "shi yong zhe", "使用者" }, { "shi yong zhu yi", "实用主义" }, { "shi yong zuo pin", "使用作品" },
			{ "shi you", "事由" }, { "shi you", "室友" }, { "shi you", "时有" }, { "shi you", "是有" }, { "shi you", "是由" }, { "shi you", "石油" },
			{ "shi you ba jiu", "十有八九" }, { "shi you fa sheng", "时有发生" }, { "shi you gong si", "石油公司" }, { "shi you hua gong", "石油化工" },
			{ "shi you jia ge", "石油价格" }, { "shi yu", "十余" }, { "shi yu", "始于" }, { "shi yu", "适于" }, { "shi yu", "食欲" }, { "shi yu bu zhen", "食欲不振" },
			{ "shi yu yuan wei", "事与愿违" }, { "shi yu zhu", "史玉柱" }, { "shi yuan", "十元" }, { "shi yue", "十月" }, { "shi yue fen", "十月份" },
			{ "shi yun hui", "十运会" }, { "shi yun xing", "试运行" }, { "shi zai", "实在" }, { "shi zai", "是在" }, { "shi zai bi xing", "势在必行" },
			{ "shi zai tai", "实在太" }, { "shi ze", "实则" }, { "shi zen me le", "是怎么了" }, { "shi zhan", "实战" }, { "shi zhan", "施展" }, { "shi zhang", "市长" },
			{ "shi zhang", "师长" }, { "shi zhe", "使者" }, { "shi zhe", "侍者" }, { "shi zhe", "试着" }, { "shi zhe", "逝者" }, { "shi zhen", "失真" },
			{ "shi zhen", "市镇" }, { "shi zhen", "是真" }, { "shi zhen", "湿疹" }, { "shi zhen de", "是真的" }, { "shi zhen shi jia", "是真是假" }, { "shi zheng", "实证" },
			{ "shi zheng", "市政" }, { "shi zheng", "施政" }, { "shi zheng", "时政" }, { "shi zheng fu", "市政府" }, { "shi zheng gong cheng", "市政工程" },
			{ "shi zheng xie", "市政协" }, { "shi zhi", "使之" }, { "shi zhi", "十指" }, { "shi zhi", "失职" }, { "shi zhi", "实质" }, { "shi zhi", "市值" },
			{ "shi zhi", "市直" }, { "shi zhi", "是指" }, { "shi zhi", "视之" }, { "shi zhi", "试制" }, { "shi zhi", "试纸" }, { "shi zhi", "食之" }, { "shi zhi", "食指" },
			{ "shi zhi jin ri", "时至今日" }, { "shi zhi xing", "实质性" }, { "shi zhong", "十种" }, { "shi zhong", "始终" }, { "shi zhong", "时钟" },
			{ "shi zhong", "是种" }, { "shi zhong", "诗中" }, { "shi zhong", "适中" }, { "shi zhong bao chi", "始终保持" }, { "shi zhong guo ren", "是中国人" },
			{ "shi zhong jian chi", "始终坚持" }, { "shi zhong xin", "市中心" }, { "shi zhou", "市州" }, { "shi zhou nian", "十周年" }, { "shi zhu", "事主" },
			{ "shi zhu", "失主" }, { "shi zhu", "施主" }, { "shi zhu", "是猪" }, { "shi zhu", "石柱" }, { "shi zhu ren", "室主任" }, { "shi zhuang", "时装" },
			{ "shi zhuang zhou", "时装周" }, { "shi zi", "十字" }, { "shi zi", "师资" }, { "shi zi", "柿子" }, { "shi zi", "狮子" }, { "shi zi", "石子" },
			{ "shi zi", "虱子" }, { "shi zi", "识字" }, { "shi zi jia", "十字架" }, { "shi zi jun", "十字军" }, { "shi zi lu kou", "十字路口" }, { "shi zi xing", "十字星" },
			{ "shi zi xiu", "十字绣" }, { "shi zi zuo", "狮子座" }, { "shi zong", "失踪" }, { "shi zu", "十足" }, { "shi zu", "失足" }, { "shi zu", "始祖" },
			{ "shi zu", "氏族" }, { "shi zui", "是最" }, { "shi zuo", "是做" }, { "shi zuo", "视作" }, { "shi zuo", "诗作" }, { "shi zuo yong zhe", "始作俑者" },
			{ "shou", "兽" }, { "shou", "収" }, { "shou", "受" }, { "shou", "售" }, { "shou", "壽" }, { "shou", "守" }, { "shou", "寿" }, { "shou", "手" },
			{ "shou", "扌" }, { "shou", "授" }, { "shou", "收" }, { "shou", "熟" }, { "shou", "狩" }, { "shou", "獣" }, { "shou", "獸" }, { "shou", "痩" },
			{ "shou", "瘦" }, { "shou", "綬" }, { "shou", "绶" }, { "shou", "艏" }, { "shou", "首" }, { "shou ba shou", "手把手" }, { "shou bei", "手背" },
			{ "shou bi", "手笔" }, { "shou bi", "手臂" }, { "shou bian", "手边" }, { "shou bian", "收编" }, { "shou biao", "手表" }, { "shou bing", "手柄" },
			{ "shou bo", "首播" }, { "shou bu", "手部" }, { "shou bu", "首部" }, { "shou bu dao", "收不到" }, { "shou bu le", "受不了" }, { "shou bu liao", "受不了" },
			{ "shou cang", "收藏" }, { "shou cang jia", "收藏夹" }, { "shou cang jia zhi", "收藏价值" }, { "shou cang pin", "收藏品" }, { "shou cang zhe", "收藏者" },
			{ "shou ce", "手册" }, { "shou chang", "收场" }, { "shou chang", "首场" }, { "shou cheng", "收成" }, { "shou chi", "手持" }, { "shou chong", "受宠" },
			{ "shou chong ruo jing", "受宠若惊" }, { "shou chu", "售出" }, { "shou chu", "收出" }, { "shou chuang", "首创" }, { "shou ci", "受此" }, { "shou ci", "首次" },
			{ "shou cuo", "受挫" }, { "shou dai", "手袋" }, { "shou dang qi chong", "首当其冲" }, { "shou dao", "受到" }, { "shou dao", "收到" },
			{ "shou dao xian zhi", "受到限制" }, { "shou dao ying xiang", "受到影响" }, { "shou dian", "手电" }, { "shou dian tong", "手电筒" }, { "shou dong", "手动" },
			{ "shou du", "首度" }, { "shou du", "首都" }, { "shou du ji chang", "首都机场" }, { "shou duan", "手段" }, { "shou er", "首尔" }, { "shou fa", "受罚" },
			{ "shou fa", "守法" }, { "shou fa", "手法" }, { "shou fa", "收发" }, { "shou fa", "首发" }, { "shou fa zhen rong", "首发阵容" }, { "shou fang", "受访" },
			{ "shou fang", "售房" }, { "shou fang", "收房" }, { "shou fang zhe", "受访者" }, { "shou fei", "收费" }, { "shou fei biao zhun", "收费标准" },
			{ "shou fei xiang mu", "收费项目" }, { "shou fei zhan", "收费站" }, { "shou fu", "收复" }, { "shou fu", "首付" }, { "shou fu", "首富" }, { "shou fu", "首府" },
			{ "shou fu kuan", "首付款" }, { "shou gan", "手感" }, { "shou gang", "首钢" }, { "shou gao", "手稿" }, { "shou ge", "收割" }, { "shou ge", "首个" },
			{ "shou ge", "首歌" }, { "shou ge qu", "首歌曲" }, { "shou gong", "手工" }, { "shou gong", "收工" }, { "shou gou", "收购" }, { "shou gou jia", "收购价" },
			{ "shou gou jia ge", "收购价格" }, { "shou guo", "受过" }, { "shou hai", "受害" }, { "shou hai ren", "受害人" }, { "shou hai zhe", "受害者" },
			{ "shou hao", "收好" }, { "shou heng", "守恒" }, { "shou hou", "售后" }, { "shou hou", "守候" }, { "shou hou fu wu", "售后服务" }, { "shou hu", "守护" },
			{ "shou hu shen", "守护神" }, { "shou hu zhe", "守护者" }, { "shou huan ying", "受欢迎" }, { "shou hui", "受惠" }, { "shou hui", "受贿" }, { "shou hui", "手绘" },
			{ "shou hui", "收回" }, { "shou hui zui", "受贿罪" }, { "shou huo", "收获" }, { "shou huo", "收货" }, { "shou huo ren", "收货人" }, { "shou huo yuan", "售货员" },
			{ "shou ji", "手机" }, { "shou ji", "手记" }, { "shou ji", "收集" }, { "shou ji bao", "手机报" }, { "shou ji chang shang", "手机厂商" },
			{ "shou ji dian chi", "手机电池" }, { "shou ji dian shi", "手机电视" }, { "shou ji duan xin", "手机短信" }, { "shou ji fei", "手机费" },
			{ "shou ji hao ma", "手机号码" }, { "shou ji ka", "手机卡" }, { "shou ji li", "手机里" }, { "shou ji ling sheng", "手机铃声" }, { "shou ji shang wang", "手机上网" },
			{ "shou ji shi chang", "手机市场" }, { "shou ji yong hu", "手机用户" }, { "shou ji you xi", "手机游戏" }, { "shou jia", "售价" }, { "shou jia", "首家" },
			{ "shou jian", "收件" }, { "shou jian ren", "收件人" }, { "shou jian xiang", "收件箱" }, { "shou jiao", "手脚" }, { "shou jiao", "收缴" },
			{ "shou jiao bing liang", "手脚冰凉" }, { "shou jiao yu", "受教育" }, { "shou jie", "首届" }, { "shou jie zhong guo", "首届中国" }, { "shou jin", "受尽" },
			{ "shou jin", "收紧" }, { "shou jing", "受惊" }, { "shou jing", "受精" }, { "shou jing luan", "受精卵" }, { "shou ju", "收据" }, { "shou juan", "手绢" },
			{ "shou jun", "守军" }, { "shou kai", "首开" }, { "shou kan", "收看" }, { "shou kao", "手铐" }, { "shou ke", "授课" }, { "shou kong", "受控" },
			{ "shou ku", "受苦" }, { "shou kuan", "收款" }, { "shou kuan", "首款" }, { "shou kun", "受困" }, { "shou la shou", "手拉手" }, { "shou lei", "受累" },
			{ "shou lei", "手雷" }, { "shou li", "受力" }, { "shou li", "受理" }, { "shou li", "手里" }, { "shou li", "首例" }, { "shou lian", "手链" },
			{ "shou lian", "收敛" }, { "shou lie", "狩猎" }, { "shou ling", "首领" }, { "shou liu", "收留" }, { "shou liu dan", "手榴弹" }, { "shou lou", "售楼" },
			{ "shou lou chu", "售楼处" }, { "shou lu", "收录" }, { "shou lun", "首轮" }, { "shou mai", "售卖" }, { "shou mai", "收买" },
			{ "shou mang jiao luan", "手忙脚乱" }, { "shou men", "守门" }, { "shou men yuan", "守门员" }, { "shou ming", "受命" }, { "shou ming", "寿命" },
			{ "shou na", "手拿" }, { "shou na", "收纳" }, { "shou nan", "受难" }, { "shou nao", "首脑" }, { "shou nao hui yi", "首脑会议" }, { "shou nue", "受虐" },
			{ "shou pa", "手帕" }, { "shou pan", "收盘" }, { "shou pan jia", "收盘价" }, { "shou peng", "手捧" }, { "shou pi", "首批" }, { "shou pian", "受骗" },
			{ "shou piao", "售票" }, { "shou piao chu", "售票处" }, { "shou piao yuan", "售票员" }, { "shou pin", "受聘" }, { "shou qi", "受其" }, { "shou qi", "受气" },
			{ "shou qi", "手气" }, { "shou qi", "收起" }, { "shou qi", "首期" }, { "shou qian", "售前" }, { "shou qian", "收钱" }, { "shou qian shou", "手牵手" },
			{ "shou qiang", "手枪" }, { "shou qu", "收取" }, { "shou qu yi zhi", "首屈一指" }, { "shou quan", "授权" }, { "shou quan shu", "授权书" },
			{ "shou rang", "受让" }, { "shou re", "受热" }, { "shou ren", "兽人" }, { "shou ren", "受人" }, { "shou ren", "手刃" }, { "shou ren", "收人" },
			{ "shou ri", "首日" }, { "shou rong", "收容" }, { "shou rou", "瘦肉" }, { "shou ru", "收入" }, { "shou ru cha ju", "收入差距" }, { "shou ru fen pei", "收入分配" },
			{ "shou ru lai yuan", "收入来源" }, { "shou ru shui ping", "收入水平" }, { "shou ru zeng zhang", "收入增长" }, { "shou ruan", "手软" }, { "shou ruo", "瘦弱" },
			{ "shou sha", "手刹" }, { "shou shang", "受伤" }, { "shou shang", "手上" }, { "shou shang le", "受伤了" }, { "shou shen", "受审" }, { "shou shen", "手伸" },
			{ "shou shen", "瘦身" }, { "shou shi", "手势" }, { "shou shi", "收市" }, { "shou shi", "收拾" }, { "shou shi", "收视" }, { "shou shi", "首诗" },
			{ "shou shi", "首饰" }, { "shou shi hao", "收拾好" }, { "shou shi lv", "收视率" }, { "shou shou", "收受" }, { "shou shou", "收手" }, { "shou shou", "瘦瘦" },
			{ "shou shu", "手术" }, { "shou shu shi", "手术室" }, { "shou shu zhi liao", "手术治疗" }, { "shou si", "寿司" }, { "shou sun", "受损" }, { "shou suo", "收缩" },
			{ "shou tao", "手套" }, { "shou ti", "受体" }, { "shou ti", "手提" }, { "shou ti dian nao", "手提电脑" }, { "shou ting", "收听" }, { "shou tou", "手头" },
			{ "shou tui", "首推" }, { "shou tuo", "受托" }, { "shou tuo ren", "受托人" }, { "shou wan", "手腕" }, { "shou wang", "兽王" }, { "shou wang", "守望" },
			{ "shou wang zhe", "守望者" }, { "shou wei", "守卫" }, { "shou wei", "收尾" }, { "shou wei", "首位" }, { "shou wo", "手握" }, { "shou wu zu dao", "手舞足蹈" },
			{ "shou xi", "首席" }, { "shou xia", "手下" }, { "shou xia", "收下" }, { "shou xian", "受限" }, { "shou xian", "寿险" }, { "shou xian", "首先" },
			{ "shou xian zhi", "受限制" }, { "shou xiang", "首相" }, { "shou xiao", "收效" }, { "shou xiao", "瘦小" }, { "shou xie", "手写" }, { "shou xin", "守信" },
			{ "shou xin", "手心" }, { "shou xin", "授信" }, { "shou xin", "收信" }, { "shou xing", "兽性" }, { "shou xing", "寿星" }, { "shou xu", "手续" },
			{ "shou xu fei", "手续费" }, { "shou xuan", "首选" }, { "shou ya", "受压" }, { "shou yan", "首演" }, { "shou yang", "收养" }, { "shou yao", "兽药" },
			{ "shou yao", "受邀" }, { "shou yao", "首要" }, { "shou yao ren wu", "首要任务" }, { "shou ye", "首页" }, { "shou yi", "兽医" }, { "shou yi", "受益" },
			{ "shou yi", "手艺" }, { "shou yi", "授意" }, { "shou yi", "收益" }, { "shou yi fei qian", "受益匪浅" }, { "shou yi lv", "收益率" }, { "shou yi ren", "受益人" },
			{ "shou yi zhe", "受益者" }, { "shou yin", "手印" }, { "shou yin", "手淫" }, { "shou yin", "收银" }, { "shou yin", "收音" }, { "shou yin ji", "收音机" },
			{ "shou yin yuan", "收银员" }, { "shou ying", "首映" }, { "shou ying shi", "首映式" }, { "shou ying xiang", "受影响" }, { "shou yong", "受用" },
			{ "shou yu", "手语" }, { "shou yu", "授予" }, { "shou yun", "受孕" }, { "shou zai", "受灾" }, { "shou zai", "守在" }, { "shou ze", "守则" },
			{ "shou zhan", "首战" }, { "shou zhang", "手掌" }, { "shou zhang", "首张" }, { "shou zhang", "首长" }, { "shou zhe", "守着" }, { "shou zhi", "受制" },
			{ "shou zhi", "手指" }, { "shou zhi", "手纸" }, { "shou zhi", "收支" }, { "shou zhi", "收治" }, { "shou zhong", "受众" }, { "shou zhong", "手中" },
			{ "shou zhu", "守住" }, { "shou zhuo", "手镯" }, { "shou zi", "瘦子" }, { "shou zi mu", "首字母" }, { "shou zu", "受阻" }, { "shou zu", "手足" },
			{ "shou zu wu cuo", "手足无措" }, { "shou zui", "受罪" }, { "shu", "丨" }, { "shu", "书" }, { "shu", "俞" }, { "shu", "倏" }, { "shu", "叔" }, { "shu", "塾" },
			{ "shu", "墅" }, { "shu", "姝" }, { "shu", "婌" }, { "shu", "孰" }, { "shu", "属" }, { "shu", "屬" }, { "shu", "庶" }, { "shu", "怷" }, { "shu", "恕" },
			{ "shu", "戍" }, { "shu", "抒" }, { "shu", "摅" }, { "shu", "攄" }, { "shu", "数" }, { "shu", "數" }, { "shu", "暑" }, { "shu", "曙" }, { "shu", "書" },
			{ "shu", "朮" }, { "shu", "术" }, { "shu", "束" }, { "shu", "杸" }, { "shu", "枢" }, { "shu", "树" }, { "shu", "梳" }, { "shu", "樞" }, { "shu", "樹" },
			{ "shu", "橾" }, { "shu", "殊" }, { "shu", "殳" }, { "shu", "毹" }, { "shu", "氀" }, { "shu", "沐" }, { "shu", "沭" }, { "shu", "淑" }, { "shu", "漱" },
			{ "shu", "潻" }, { "shu", "澍" }, { "shu", "焂" }, { "shu", "熟" }, { "shu", "璹" }, { "shu", "疋" }, { "shu", "疎" }, { "shu", "疏" }, { "shu", "癙" },
			{ "shu", "秫" }, { "shu", "竖" }, { "shu", "竪" }, { "shu", "糬" }, { "shu", "紓" }, { "shu", "綀" }, { "shu", "纾" }, { "shu", "署" }, { "shu", "腧" },
			{ "shu", "舒" }, { "shu", "菽" }, { "shu", "蔬" }, { "shu", "薯" }, { "shu", "虪" }, { "shu", "蜀" }, { "shu", "術" }, { "shu", "裋" }, { "shu", "襡" },
			{ "shu", "襩" }, { "shu", "豎" }, { "shu", "贖" }, { "shu", "赎" }, { "shu", "跾" }, { "shu", "踈" }, { "shu", "軗" }, { "shu", "輸" }, { "shu", "输" },
			{ "shu", "述" }, { "shu", "鄃" }, { "shu", "鉥" }, { "shu", "鏣" }, { "shu", "陎" }, { "shu", "鮛" }, { "shu", "鵨" }, { "shu", "鶐" }, { "shu", "黍" },
			{ "shu", "鼠" }, { "shu", "鼡" }, { "shu bai", "数百" }, { "shu bai wan", "数百万" }, { "shu bao", "书包" }, { "shu bei", "数倍" }, { "shu ben", "书本" },
			{ "shu biao", "鼠标" }, { "shu biao dian", "鼠标垫" }, { "shu biao you jian", "鼠标右键" }, { "shu bu qing", "数不清" }, { "shu bu sheng shu", "数不胜数" },
			{ "shu bu zhi", "殊不知" }, { "shu cai", "蔬菜" }, { "shu chang", "舒畅" }, { "shu cheng", "书城" }, { "shu chu", "输出" }, { "shu chu gong lv", "输出功率" },
			{ "shu ci", "数次" }, { "shu cong", "树丛" }, { "shu cu", "暑促" }, { "shu dai zi", "书呆子" }, { "shu dao", "疏导" }, { "shu de", "输得" }, { "shu di", "属地" },
			{ "shu dian", "书店" }, { "shu dian", "输电" }, { "shu diao", "输掉" }, { "shu du", "数度" }, { "shu e", "数额" }, { "shu fa", "书法" }, { "shu fa", "抒发" },
			{ "shu fa jia", "书法家" }, { "shu fang", "书房" }, { "shu fu", "束缚" }, { "shu fu", "舒服" }, { "shu gan", "树干" }, { "shu gao", "书稿" },
			{ "shu ge", "数个" }, { "shu gei", "输给" }, { "shu gen", "树根" }, { "shu guang", "曙光" }, { "shu gui", "书柜" }, { "shu guo", "蔬果" }, { "shu guo", "蜀国" },
			{ "shu hou", "术后" }, { "shu hu", "疏忽" }, { "shu hua", "书画" }, { "shu huan", "舒缓" }, { "shu hui", "赎回" }, { "shu ji", "书籍" }, { "shu ji", "书记" },
			{ "shu jia", "书架" }, { "shu jia", "数家" }, { "shu jia", "暑假" }, { "shu jiao", "树胶" }, { "shu ju", "书局" }, { "shu ju", "数据" },
			{ "shu ju bao", "数据包" }, { "shu ju biao", "数据表" }, { "shu ju cai ji", "数据采集" }, { "shu ju cang ku", "数据仓库" }, { "shu ju chu li", "数据处理" },
			{ "shu ju chuan shu", "数据传输" }, { "shu ju cun chu", "数据存储" }, { "shu ju fen xi", "数据分析" }, { "shu ju hui fu", "数据恢复" }, { "shu ju ji", "数据集" },
			{ "shu ju jiao huan", "数据交换" }, { "shu ju jie gou", "数据结构" }, { "shu ju ku", "数据库" }, { "shu ju lei xing", "数据类型" }, { "shu ju liang", "数据量" },
			{ "shu ju liu", "数据流" }, { "shu ju tong ji", "数据统计" }, { "shu ju wa jue", "数据挖掘" }, { "shu ju wen jian", "数据文件" }, { "shu ju xian", "数据线" },
			{ "shu ju xian shi", "数据显示" }, { "shu ju ye wu", "数据业务" }, { "shu ju yuan", "数据源" }, { "shu ju zhong xin", "数据中心" }, { "shu kan", "书刊" },
			{ "shu kong", "数控" }, { "shu kong ji chuang", "数控机床" }, { "shu kou", "漱口" }, { "shu ku", "书库" }, { "shu le", "熟了" }, { "shu li", "书里" },
			{ "shu li", "数理" }, { "shu li", "树立" }, { "shu li", "梳理" }, { "shu li", "疏离" }, { "shu li", "竖立" }, { "shu li zheng que", "树立正确" },
			{ "shu lian", "熟练" }, { "shu lian zhang wo", "熟练掌握" }, { "shu liang", "数量" }, { "shu liang ji", "数量级" }, { "shu lie", "数列" }, { "shu lin", "树林" },
			{ "shu lin li", "树林里" }, { "shu lou", "疏漏" }, { "shu luan guan", "输卵管" }, { "shu luo", "数落" }, { "shu ma", "数码" }, { "shu ma chan pin", "数码产品" },
			{ "shu ma dan fan", "数码单反" }, { "shu ma he", "舒马赫" }, { "shu ma xiang ji", "数码相机" }, { "shu ma zhao pian", "数码照片" }, { "shu mian", "书面" },
			{ "shu mian xing shi", "书面形式" }, { "shu miao", "树苗" }, { "shu ming", "书名" }, { "shu ming", "数名" }, { "shu ming", "署名" }, { "shu mu", "书目" },
			{ "shu mu", "数目" }, { "shu mu", "树木" }, { "shu nian", "数年" }, { "shu niao guan", "输尿管" }, { "shu niu", "枢纽" }, { "shu nv", "淑女" },
			{ "shu nv", "熟女" }, { "shu pi", "树皮" }, { "shu pian", "薯片" }, { "shu ping", "书评" }, { "shu ping", "述评" }, { "shu qi", "暑期" }, { "shu qi", "竖起" },
			{ "shu qi", "舒淇" }, { "shu qian", "书签" }, { "shu qian", "数千" }, { "shu qian", "数钱" }, { "shu qian", "术前" }, { "shu qian wan", "数千万" },
			{ "shu qing", "抒情" }, { "shu qiu", "输球" }, { "shu ren", "数人" }, { "shu ren", "熟人" }, { "shu ri", "数日" }, { "shu rong", "殊荣" }, { "shu ru", "输入" },
			{ "shu ru fa", "输入法" }, { "shu ru kuang", "输入框" }, { "shu ru mi ma", "输入密码" }, { "shu ru nin", "输入您" }, { "shu ru shu chu", "输入输出" },
			{ "shu san", "疏散" }, { "shu shan", "蜀山" }, { "shu shang", "书上" }, { "shu shang", "书商" }, { "shu shang", "树上" }, { "shu shao", "树梢" },
			{ "shu sheng", "书生" }, { "shu shi", "书市" }, { "shu shi", "属实" }, { "shu shi", "数十" }, { "shu shi", "术士" }, { "shu shi", "熟识" },
			{ "shu shi", "熟食" }, { "shu shi", "舒适" }, { "shu shi du", "舒适度" }, { "shu shi wan", "数十万" }, { "shu shi xing", "舒适性" }, { "shu shi yi", "数十亿" },
			{ "shu shou wu ce", "束手无策" }, { "shu shu", "叔叔" }, { "shu shu", "数数" }, { "shu shu fu fu", "舒舒服服" }, { "shu shui", "熟睡" }, { "shu shuo", "述说" },
			{ "shu song", "疏松" }, { "shu song", "输送" }, { "shu tan", "舒坦" }, { "shu tian", "数天" }, { "shu tiao", "薯条" }, { "shu tong", "疏通" },
			{ "shu tou", "梳头" }, { "shu tou", "熟透" }, { "shu wan", "数万" }, { "shu wei", "数为" }, { "shu wei", "数位" }, { "shu wo", "恕我" }, { "shu wu", "书屋" },
			{ "shu xi", "熟悉" }, { "shu xia", "属下" }, { "shu xia", "树下" }, { "shu xiang", "书香" }, { "shu xiang", "属相" }, { "shu xie", "书写" },
			{ "shu xin", "书信" }, { "shu xin", "舒心" }, { "shu xing", "属性" }, { "shu xing", "树形" }, { "shu xue", "数学" }, { "shu xue", "输血" },
			{ "shu xue jia", "数学家" }, { "shu xue mo xing", "数学模型" }, { "shu xue ti", "数学题" }, { "shu xue xi", "数学系" }, { "shu ye", "树叶" }, { "shu ye", "输液" },
			{ "shu yi", "数亿" }, { "shu yi shu er", "数一数二" }, { "shu yi wan ji", "数以万计" }, { "shu yin", "树荫" }, { "shu ying", "输赢" }, { "shu you", "书友" },
			{ "shu yu", "属于" }, { "shu yu", "术语" }, { "shu yu", "疏于" }, { "shu yu zi ji", "属于自己" }, { "shu yuan", "书院" }, { "shu yuan", "疏远" },
			{ "shu yue", "数月" }, { "shu zhan", "舒展" }, { "shu zhe", "数着" }, { "shu zhe", "竖着" }, { "shu zhi", "数值" }, { "shu zhi", "树枝" }, { "shu zhi", "树脂" },
			{ "shu zhi", "熟知" }, { "shu zhi", "述职" }, { "shu zhong", "书中" }, { "shu zhong", "术中" }, { "shu zhong", "树种" }, { "shu zhuo", "书桌" },
			{ "shu zi", "数字" }, { "shu zi", "梳子" }, { "shu zi dian shi", "数字电视" }, { "shu zi hua", "数字化" }, { "shu zi jia ting", "数字家庭" },
			{ "shu zi xin hao", "数字信号" }, { "shu zu", "数组" }, { "shu zui", "赎罪" }, { "shua", "刷" }, { "shua", "唰" }, { "shua", "耍" }, { "shua fen", "刷分" },
			{ "shua ji", "刷机" }, { "shua ka", "刷卡" }, { "shua lai", "耍赖" }, { "shua ping", "刷屏" }, { "shua shua", "刷刷" }, { "shua shua", "耍耍" },
			{ "shua xin", "刷新" }, { "shua ya", "刷牙" }, { "shua zi", "刷子" }, { "shuai", "帅" }, { "shuai", "帥" }, { "shuai", "摔" }, { "shuai", "率" },
			{ "shuai", "甩" }, { "shuai", "蟀" }, { "shuai", "衰" }, { "shuai bai", "衰败" }, { "shuai da", "率达" }, { "shuai dao", "摔倒" }, { "shuai diao", "甩掉" },
			{ "shuai dui", "率队" }, { "shuai ge", "帅哥" }, { "shuai jian", "衰减" }, { "shuai jiao", "摔跤" }, { "shuai jie", "衰竭" }, { "shuai kai", "甩开" },
			{ "shuai lao", "衰老" }, { "shuai le", "摔了" }, { "shuai le", "甩了" }, { "shuai ling", "率领" }, { "shuai luo", "衰落" }, { "shuai mai", "甩卖" },
			{ "shuai qi", "帅气" }, { "shuai ruo", "衰弱" }, { "shuai shang", "摔伤" }, { "shuai shuai", "帅帅" }, { "shuai si", "摔死" }, { "shuai tui", "衰退" },
			{ "shuai xia", "摔下" }, { "shuai xian", "率先" }, { "shuai xing", "率性" }, { "shuai zai", "摔在" }, { "shuai zhen", "率真" }, { "shuan", "拴" },
			{ "shuan", "栓" }, { "shuan", "涮" }, { "shuan", "閂" }, { "shuan", "闩" }, { "shuang", "双" }, { "shuang", "塽" }, { "shuang", "孀" }, { "shuang", "孇" },
			{ "shuang", "慡" }, { "shuang", "樉" }, { "shuang", "泷" }, { "shuang", "滝" }, { "shuang", "漺" }, { "shuang", "灀" }, { "shuang", "爽" },
			{ "shuang", "礵" }, { "shuang", "縔" }, { "shuang", "艭" }, { "shuang", "雙" }, { "shuang", "霜" }, { "shuang", "驦" }, { "shuang", "鷞" },
			{ "shuang a", "爽啊" }, { "shuang bao tai", "双胞胎" }, { "shuang bei", "双倍" }, { "shuang bi", "双臂" }, { "shuang bian", "双边" }, { "shuang ce", "双侧" },
			{ "shuang ceng", "双层" }, { "shuang chong", "双重" }, { "shuang chun", "双唇" }, { "shuang da", "双打" }, { "shuang fang", "双方" }, { "shuang fei", "双飞" },
			{ "shuang fei yan", "双飞燕" }, { "shuang feng", "双峰" }, { "shuang fu shui", "爽肤水" }, { "shuang he", "双核" }, { "shuang he xin", "双核心" },
			{ "shuang hui", "双汇" }, { "shuang ji", "双击" }, { "shuang ji", "双机" }, { "shuang jian", "双肩" }, { "shuang jiao", "双脚" },
			{ "shuang jiao xian", "双绞线" }, { "shuang ka", "双卡" }, { "shuang kai", "双开" }, { "shuang kou", "爽口" }, { "shuang kuai", "爽快" },
			{ "shuang lang", "爽朗" }, { "shuang le", "爽了" }, { "shuang liu", "双流" }, { "shuang long", "双龙" }, { "shuang mian", "双面" }, { "shuang min", "双敏" },
			{ "shuang mo", "双模" }, { "shuang mou", "双眸" }, { "shuang mu", "双目" }, { "shuang qin", "双亲" }, { "shuang ren", "双人" }, { "shuang ren jian", "双刃剑" },
			{ "shuang se", "双色" }, { "shuang se qiu", "双色球" }, { "shuang shou", "双手" }, { "shuang shuang", "双双" }, { "shuang shuang", "爽爽" },
			{ "shuang si", "爽死" }, { "shuang tong dao", "双通道" }, { "shuang tou", "双头" }, { "shuang tui", "双腿" }, { "shuang xian", "双线" },
			{ "shuang xiang", "双向" }, { "shuang xing", "双星" }, { "shuang xiong", "双雄" }, { "shuang xiu", "双休" }, { "shuang xiu", "双修" },
			{ "shuang xiu ri", "双休日" }, { "shuang yan", "双眼" }, { "shuang yan pi", "双眼皮" }, { "shuang ying", "双赢" }, { "shuang yu", "双语" },
			{ "shuang yu", "双鱼" }, { "shuang yu zuo", "双鱼座" }, { "shuang zi", "双子" }, { "shuang zi zuo", "双子座" }, { "shui", "帨" }, { "shui", "水" },
			{ "shui", "氵" }, { "shui", "涗" }, { "shui", "睡" }, { "shui", "稅" }, { "shui", "税" }, { "shui", "脽" }, { "shui", "裞" }, { "shui", "誰" },
			{ "shui", "说" }, { "shui", "谁" }, { "shui", "閖" }, { "shui a", "谁啊" }, { "shui an", "水岸" }, { "shui ba", "睡吧" }, { "shui bei", "水杯" },
			{ "shui beng", "水泵" }, { "shui bian", "水边" }, { "shui biao", "水表" } };
};
