package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN65 {
	public static String[][] pl = { { "zi hui", "自毁" }, { "zi ji", "子集" }, { "zi ji", "字迹" }, { "zi ji", "自己" }, { "zi ji dong shou", "自己动手" },
			{ "zi ji ren", "自己人" }, { "zi ji xi huan", "自己喜欢" }, { "zi ji xie", "自己写" }, { "zi ji zi zu", "自给自足" }, { "zi ji zuo", "自己做" }, { "zi jia", "自家" },
			{ "zi jia", "自驾" }, { "zi jia che", "自驾车" }, { "zi jia you", "自驾游" }, { "zi jian", "自建" }, { "zi jian", "自检" }, { "zi jian", "自荐" },
			{ "zi jie", "字节" }, { "zi jin", "紫金" }, { "zi jin", "自尽" }, { "zi jin", "资金" }, { "zi jin cheng", "紫禁城" }, { "zi jin guan li", "资金管理" },
			{ "zi jin lai yuan", "资金来源" }, { "zi jin lian", "资金链" }, { "zi jin liang", "资金量" }, { "zi jin shi yong", "资金使用" }, { "zi jin tou ru", "资金投入" },
			{ "zi jing", "紫荆" }, { "zi jiu", "自救" }, { "zi ju", "字句" }, { "zi ju", "自居" }, { "zi jue", "自觉" }, { "zi jue xing", "自觉性" },
			{ "zi jue zun shou", "自觉遵守" }, { "zi kao", "自考" }, { "zi kong", "自控" }, { "zi ku", "字库" }, { "zi lai", "自来" }, { "zi lai shui", "自来水" },
			{ "zi lei", "子类" }, { "zi li", "自理" }, { "zi li", "自立" }, { "zi li", "资历" }, { "zi li geng sheng", "自力更生" }, { "zi li hang jian", "字里行间" },
			{ "zi lian", "自恋" }, { "zi liao", "资料" }, { "zi liao ku", "资料库" }, { "zi liao pian", "资料片" }, { "zi liao tu pian", "资料图片" }, { "zi long", "子龙" },
			{ "zi lu", "子路" }, { "zi luo lan", "紫罗兰" }, { "zi lv", "自律" }, { "zi mei", "姊妹" }, { "zi mian", "字面" }, { "zi min", "子民" },
			{ "zi min dang", "自民党" }, { "zi ming", "自明" }, { "zi mo", "自摸" }, { "zi mu", "字幕" }, { "zi mu", "字母" }, { "zi mu lu", "子目录" },
			{ "zi mu zu", "字幕组" }, { "zi nue", "自虐" }, { "zi nv", "子女" }, { "zi pai", "自拍" }, { "zi ping", "自评" }, { "zi qi qi ren", "自欺欺人" },
			{ "zi qiang", "自强" }, { "zi qiang bu xi", "自强不息" }, { "zi qu", "自取" }, { "zi ran", "自然" }, { "zi ran", "自燃" }, { "zi ran cun", "自然村" },
			{ "zi ran er ran", "自然而然" }, { "zi ran feng guang", "自然风光" }, { "zi ran gui lv", "自然规律" }, { "zi ran huan jing", "自然环境" }, { "zi ran jie", "自然界" },
			{ "zi ran jing guan", "自然景观" }, { "zi ran ke xue", "自然科学" }, { "zi ran ren", "自然人" }, { "zi ran tiao jian", "自然条件" }, { "zi ran xing", "自然醒" },
			{ "zi ran zai hai", "自然灾害" }, { "zi ran zi yuan", "自然资源" }, { "zi ren", "自认" }, { "zi ren wei", "自认为" }, { "zi ru", "自如" }, { "zi run", "滋润" },
			{ "zi se", "姿色" }, { "zi se", "紫色" }, { "zi sha", "紫砂" }, { "zi sha", "自杀" }, { "zi shen", "自身" }, { "zi shen", "资深" },
			{ "zi shen jian she", "自身建设" }, { "zi sheng", "滋生" }, { "zi sheng tang", "资生堂" }, { "zi sheng zi mie", "自生自灭" }, { "zi shi", "姿势" },
			{ "zi shi", "自是" }, { "zi shi ying", "自适应" }, { "zi shi zhi zhong", "自始至终" }, { "zi shou", "自首" }, { "zi shu", "字数" }, { "zi shu", "自述" },
			{ "zi si", "自私" }, { "zi sun", "子孙" }, { "zi sun hou dai", "子孙后代" }, { "zi tai", "姿态" }, { "zi ti", "字体" }, { "zi ti", "自体" }, { "zi ti", "自提" },
			{ "zi tiao", "字条" }, { "zi tou", "字头" }, { "zi wai", "紫外" }, { "zi wai xian", "紫外线" }, { "zi wang", "子网" }, { "zi wei", "滋味" }, { "zi wei", "紫薇" },
			{ "zi wei", "自卫" }, { "zi wei", "自慰" }, { "zi wei dui", "自卫队" }, { "zi wen", "自问" }, { "zi wo", "自我" }, { "zi xi", "仔细" }, { "zi xi", "自习" },
			{ "zi xi kan", "仔细看" }, { "zi xi shi", "自习室" }, { "zi xi tong", "子系统" }, { "zi xi yue du", "仔细阅读" }, { "zi xia", "紫霞" },
			{ "zi xiang mao dun", "自相矛盾" }, { "zi xiao", "自小" }, { "zi xin", "自信" }, { "zi xin", "资信" }, { "zi xin xin", "自信心" }, { "zi xing", "字型" },
			{ "zi xing", "字形" }, { "zi xing", "自省" }, { "zi xing", "自行" }, { "zi xing che", "自行车" }, { "zi xiu", "自修" }, { "zi xu", "自诩" },
			{ "zi xuan", "自选" }, { "zi xue", "自学" }, { "zi xue kao shi", "自学考试" }, { "zi xun", "咨询" }, { "zi xun", "资讯" }, { "zi xun dian hua", "咨询电话" },
			{ "zi xun fu wu", "咨询服务" }, { "zi xun gong si", "咨询公司" }, { "zi xun gu wen", "咨询顾问" }, { "zi xun ji gou", "咨询机构" }, { "zi xun shi", "咨询师" },
			{ "zi xun wang", "资讯网" }, { "zi yan", "字眼" }, { "zi yan zi yu", "自言自语" }, { "zi yang", "字样" }, { "zi yang", "滋养" }, { "zi ye", "子夜" },
			{ "zi yi", "子怡" }, { "zi yi", "恣意" }, { "zi yi", "紫衣" }, { "zi yi", "自已" }, { "zi yi wei", "自以为" }, { "zi yi wei shi", "自以为是" },
			{ "zi yin", "滋阴" }, { "zi ying", "自营" }, { "zi yong", "自用" }, { "zi you", "自幼" }, { "zi you", "自有" }, { "zi you", "自由" }, { "zi you du", "自由度" },
			{ "zi you hua", "自由化" }, { "zi you ji", "自由基" }, { "zi you mao yi", "自由贸易" }, { "zi you pin pai", "自有品牌" }, { "zi you ren", "自由人" },
			{ "zi you xing", "自由行" }, { "zi you xuan ze", "自由选择" }, { "zi you zhu yi", "自由主义" }, { "zi you zi jin", "自有资金" }, { "zi you zi zai", "自由自在" },
			{ "zi yu zi le", "自娱自乐" }, { "zi yuan", "自愿" }, { "zi yuan", "资源" }, { "zi yuan feng fu", "资源丰富" }, { "zi yuan gong xiang", "资源共享" },
			{ "zi yuan jie yue", "资源节约" }, { "zi yuan kai fa", "资源开发" }, { "zi yuan ku", "资源库" }, { "zi yuan pei zhi", "资源配置" }, { "zi yuan you shi", "资源优势" },
			{ "zi yuan zheng he", "资源整合" }, { "zi yun", "紫云" }, { "zi zai", "自在" }, { "zi ze", "自责" }, { "zi zhao", "自找" }, { "zi zhi", "自制" },
			{ "zi zhi", "自治" }, { "zi zhi", "自知" }, { "zi zhi", "资质" }, { "zi zhi li", "自制力" }, { "zi zhi qu", "自治区" }, { "zi zhi xian", "自治县" },
			{ "zi zhi zhi ming", "自知之明" }, { "zi zhi zhou", "自治州" }, { "zi zhong", "自重" }, { "zi zhu", "仔猪" }, { "zi zhu", "紫竹" }, { "zi zhu", "自主" },
			{ "zi zhu", "自住" }, { "zi zhu", "自助" }, { "zi zhu", "资助" }, { "zi zhu can", "自助餐" }, { "zi zhu chuang xin", "自主创新" },
			{ "zi zhu chuang ye", "自主创业" }, { "zi zhu kai fa", "自主开发" }, { "zi zhu pin pai", "自主品牌" }, { "zi zhu quan", "自主权" }, { "zi zhu xing", "自主性" },
			{ "zi zhu xue xi", "自主学习" }, { "zi zhu yan fa", "自主研发" }, { "zi zhu you", "自助游" }, { "zi zhu zhao sheng", "自主招生" }, { "zi zhuan", "自传" },
			{ "zi zi", "姊姊" }, { "zi zi", "字字" }, { "zi zi bu juan", "孜孜不倦" }, { "zi zun", "自尊" }, { "zi zun xin", "自尊心" }, { "zi zuo duo qing", "自作多情" },
			{ "zong", "倧" }, { "zong", "偬" }, { "zong", "傯" }, { "zong", "宗" }, { "zong", "嵕" }, { "zong", "总" }, { "zong", "惣" }, { "zong", "惾" },
			{ "zong", "愡" }, { "zong", "摠" }, { "zong", "昮" }, { "zong", "朡" }, { "zong", "枞" }, { "zong", "棕" }, { "zong", "椶" }, { "zong", "潀" },
			{ "zong", "熧" }, { "zong", "猣" }, { "zong", "瘲" }, { "zong", "稯" }, { "zong", "粽" }, { "zong", "綜" }, { "zong", "総" }, { "zong", "縦" },
			{ "zong", "縱" }, { "zong", "總" }, { "zong", "纵" }, { "zong", "综" }, { "zong", "翪" }, { "zong", "腙" }, { "zong", "艐" }, { "zong", "蓗" },
			{ "zong", "蓯" }, { "zong", "蝬" }, { "zong", "豵" }, { "zong", "踪" }, { "zong", "蹤" }, { "zong", "錝" }, { "zong", "鑁" }, { "zong", "騣" },
			{ "zong", "鬃" }, { "zong", "鬷" }, { "zong ai", "总爱" }, { "zong bi", "总比" }, { "zong bian", "总编" }, { "zong bian ji", "总编辑" }, { "zong bu", "总不" },
			{ "zong bu", "总部" }, { "zong cai", "总裁" }, { "zong chan liang", "总产量" }, { "zong chan zhi", "总产值" }, { "zong chang", "总厂" },
			{ "zong chang", "总长" }, { "zong cheng", "总成" }, { "zong cheng", "总称" }, { "zong cheng ji", "总成绩" }, { "zong dai", "总代" }, { "zong de", "总的" },
			{ "zong dei", "总得" }, { "zong dian", "总店" }, { "zong dong yuan", "总动员" }, { "zong du", "总督" }, { "zong dui", "总队" }, { "zong dui", "纵队" },
			{ "zong e", "总额" }, { "zong er yan zhi", "总而言之" }, { "zong fen", "总分" }, { "zong gong", "总共" }, { "zong gong", "总工" },
			{ "zong gong cheng shi", "总工程师" }, { "zong gong hui", "总工会" }, { "zong gong si", "总公司" }, { "zong guan", "总管" }, { "zong guan", "纵观" },
			{ "zong guan", "综观" }, { "zong gui", "总归" }, { "zong hang", "总行" }, { "zong he", "总和" }, { "zong he", "综合" }, { "zong he fen xi", "综合分析" },
			{ "zong he fu wu", "综合服务" }, { "zong he guan li", "综合管理" }, { "zong he guo li", "综合国力" }, { "zong he kai fa", "综合开发" },
			{ "zong he li yong", "综合利用" }, { "zong he lou", "综合楼" }, { "zong he neng li", "综合能力" }, { "zong he ping jia", "综合评价" },
			{ "zong he shi li", "综合实力" }, { "zong he su zhi", "综合素质" }, { "zong he xing", "综合性" }, { "zong he zheng", "综合征" }, { "zong he zheng", "综合症" },
			{ "zong he zhi li", "综合治理" }, { "zong he zhi shu", "综合指数" }, { "zong heng", "纵横" }, { "zong heng jiao cuo", "纵横交错" }, { "zong hui", "总会" },
			{ "zong hui", "总汇" }, { "zong ji", "总机" }, { "zong ji", "总计" }, { "zong ji", "踪迹" }, { "zong jia", "总价" }, { "zong jian", "总监" },
			{ "zong jiao", "宗教" }, { "zong jiao xin yang", "宗教信仰" }, { "zong jiao zheng ce", "宗教政策" }, { "zong jie", "总结" }, { "zong jie jing yan", "总结经验" },
			{ "zong jing li", "总经理" }, { "zong ju", "总局" }, { "zong jue", "总觉" }, { "zong jue sai", "总决赛" }, { "zong li", "总理" }, { "zong liang", "总量" },
			{ "zong lv", "棕榈" }, { "zong lv you", "棕榈油" }, { "zong mian ji", "总面积" }, { "zong neng", "总能" }, { "zong qing", "纵情" }, { "zong qing hou", "宗庆后" },
			{ "zong ran", "纵然" }, { "zong ren kou", "总人口" }, { "zong rong", "纵容" }, { "zong se", "棕色" }, { "zong shang suo shu", "综上所述" },
			{ "zong she", "总社" }, { "zong shen", "纵深" }, { "zong shen", "纵身" }, { "zong shi", "宗师" }, { "zong shi", "总是" }, { "zong shi", "纵使" },
			{ "zong shou ru", "总收入" }, { "zong shu", "总数" }, { "zong shu", "总署" }, { "zong shu", "综述" }, { "zong shu ji", "总书记" }, { "zong shuo", "总说" },
			{ "zong si ling", "总司令" }, { "zong suan", "总算" }, { "zong ti", "总体" }, { "zong ti gui hua", "总体规划" }, { "zong ti mu biao", "总体目标" },
			{ "zong ti yao qiu", "总体要求" }, { "zong tong", "总统" }, { "zong tong fu", "总统府" }, { "zong wu", "总务" }, { "zong xian", "总线" },
			{ "zong xiang", "总想" }, { "zong xiang", "纵向" }, { "zong yao", "总要" }, { "zong ye", "总也" }, { "zong yi", "综艺" }, { "zong yi jie mu", "综艺节目" },
			{ "zong ying", "踪影" }, { "zong you", "总有" }, { "zong you yi tian", "总有一天" }, { "zong you yi zhong", "总有一种" }, { "zong yu", "纵欲" },
			{ "zong zai", "总在" }, { "zong ze", "总则" }, { "zong zhan", "总站" }, { "zong zhi", "宗旨" }, { "zong zhi", "总之" }, { "zong zhi", "总值" },
			{ "zong zhi", "综指" }, { "zong zhi hui", "总指挥" }, { "zong zhuang", "总装" }, { "zong zi", "粽子" }, { "zong zu", "宗族" }, { "zou", "偢" }, { "zou", "奏" },
			{ "zou", "媰" }, { "zou", "掫" }, { "zou", "揍" }, { "zou", "搊" }, { "zou", "棷" }, { "zou", "棸" }, { "zou", "楱" }, { "zou", "緅" }, { "zou", "菆" },
			{ "zou", "諏" }, { "zou", "诹" }, { "zou", "走" }, { "zou", "赱" }, { "zou", "邹" }, { "zou", "郰" }, { "zou", "鄒" }, { "zou", "鄹" }, { "zou", "陬" },
			{ "zou", "騶" }, { "zou", "驺" }, { "zou", "鯫" }, { "zou", "鲰" }, { "zou", "黀" }, { "zou", "齱" }, { "zou", "齺" }, { "zou ba", "走吧" },
			{ "zou bian", "走遍" }, { "zou chu", "走出" }, { "zou chu lai", "走出来" }, { "zou chu le", "走出了" }, { "zou chu qu", "走出去" }, { "zou cuo", "走错" },
			{ "zou dao", "走到" }, { "zou dao", "走道" }, { "zou dao yi qi", "走到一起" }, { "zou de", "走得" }, { "zou de", "走的" }, { "zou di", "走低" },
			{ "zou diao", "走掉" }, { "zou dong", "走动" }, { "zou duo yuan", "走多远" }, { "zou fang", "走访" }, { "zou gao", "走高" }, { "zou gou", "走狗" },
			{ "zou guang", "走光" }, { "zou guo", "走过" }, { "zou guo lai", "走过来" }, { "zou guo qu", "走过去" }, { "zou hao", "走好" }, { "zou hong", "走红" },
			{ "zou hou", "走后" }, { "zou hui", "走回" }, { "zou huo ru mo", "走火入魔" }, { "zou jin", "走近" }, { "zou jin", "走进" }, { "zou kai", "走开" },
			{ "zou lai", "走来" }, { "zou lai zou qu", "走来走去" }, { "zou lang", "走廊" }, { "zou le", "走了" }, { "zou lu", "走路" }, { "zou ma", "走马" },
			{ "zou ma guan hua", "走马观花" }, { "zou qiang", "走强" }, { "zou qiao", "走俏" }, { "zou qu", "走去" }, { "zou ren", "走人" }, { "zou ru", "走入" },
			{ "zou ruo", "走弱" }, { "zou shang", "走上" }, { "zou shang le", "走上了" }, { "zou shen", "走神" }, { "zou shi", "走势" }, { "zou shi", "走失" },
			{ "zou shi", "走时" }, { "zou shi tu", "走势图" }, { "zou si", "走私" }, { "zou tian ya", "走天涯" }, { "zou tou wu lu", "走投无路" }, { "zou wan", "走完" },
			{ "zou xia", "走下" }, { "zou xia qu", "走下去" }, { "zou xiang", "奏响" }, { "zou xiang", "走向" }, { "zou xiang shi jie", "走向世界" }, { "zou xiao", "奏效" },
			{ "zou xiu", "走秀" }, { "zou yi bu", "走一步" }, { "zou yuan", "走远" }, { "zou yun", "走运" }, { "zou zai", "走在" }, { "zou zai lu shang", "走在路上" },
			{ "zou zhe", "走着" }, { "zou zou", "走走" }, { "zu", "伜" }, { "zu", "伹" }, { "zu", "俎" }, { "zu", "倅" }, { "zu", "傶" }, { "zu", "卆" }, { "zu", "卒" },
			{ "zu", "哫" }, { "zu", "崒" }, { "zu", "怚" }, { "zu", "族" }, { "zu", "柤" }, { "zu", "爼" }, { "zu", "珇" }, { "zu", "砠" }, { "zu", "祖" },
			{ "zu", "租" }, { "zu", "箤" }, { "zu", "組" }, { "zu", "綷" }, { "zu", "组" }, { "zu", "菹" }, { "zu", "葅" }, { "zu", "蒩" }, { "zu", "詛" },
			{ "zu", "謯" }, { "zu", "诅" }, { "zu", "趲" }, { "zu", "足" }, { "zu", "踤" }, { "zu", "踿" }, { "zu", "鉏" }, { "zu", "鉐" }, { "zu", "鏃" },
			{ "zu", "镞" }, { "zu", "阻" }, { "zu", "靻" }, { "zu", "駔" }, { "zu ai", "阻碍" }, { "zu bei", "祖辈" }, { "zu bie", "组别" }, { "zu bo", "组播" },
			{ "zu bu", "足部" }, { "zu bu chu hu", "足不出户" }, { "zu cai", "足彩" }, { "zu ce lue", "组策略" }, { "zu che", "租车" }, { "zu cheng", "组成" },
			{ "zu cheng bu fen", "组成部分" }, { "zu cheng yuan", "组成员" }, { "zu chu qu", "租出去" }, { "zu chuan", "祖传" }, { "zu dang", "阻挡" }, { "zu de", "祖德" },
			{ "zu di", "足底" }, { "zu duan", "阻断" }, { "zu dui", "组队" }, { "zu e", "足额" }, { "zu fang", "租房" }, { "zu fang zi", "租房子" }, { "zu fen", "组分" },
			{ "zu fu", "祖父" }, { "zu ge", "阻隔" }, { "zu gei", "租给" }, { "zu gou", "足够" }, { "zu guo", "祖国" }, { "zu he", "组合" }, { "zu hu", "租户" },
			{ "zu ji", "祖籍" }, { "zu ji", "足迹" }, { "zu ji", "阻击" }, { "zu jian", "组件" }, { "zu jian", "组建" }, { "zu jian", "足见" }, { "zu jie", "租借" },
			{ "zu jie", "租界" }, { "zu jin", "租金" }, { "zu kang", "阻抗" }, { "zu lan", "阻拦" }, { "zu le", "租了" }, { "zu le", "足了" }, { "zu li", "组里" },
			{ "zu li", "阻力" }, { "zu lin", "租赁" }, { "zu mu", "祖母" }, { "zu nao", "阻挠" }, { "zu ni", "阻尼" }, { "zu qiu", "足球" }, { "zu qiu bi sai", "足球比赛" },
			{ "zu qiu chang", "足球场" }, { "zu qiu dui", "足球队" }, { "zu qiu sai", "足球赛" }, { "zu qun", "族群" }, { "zu ran", "阻燃" }, { "zu ren", "族人" },
			{ "zu sai", "阻塞" }, { "zu se", "阻塞" }, { "zu shang", "祖上" }, { "zu shi", "祖师" }, { "zu shou", "租售" }, { "zu tan", "足坛" }, { "zu tu", "组图" },
			{ "zu tuan", "组团" }, { "zu wang", "组网" }, { "zu wei hui", "组委会" }, { "zu xian", "祖先" }, { "zu xie", "足协" }, { "zu yi", "足以" }, { "zu yi", "足矣" },
			{ "zu yong", "租用" }, { "zu you", "足有" }, { "zu yuan", "组员" }, { "zu zhang", "族长" }, { "zu zhang", "组长" }, { "zu zhi", "组织" }, { "zu zhi", "阻止" },
			{ "zu zhi", "阻滞" }, { "zu zhi bu", "组织部" }, { "zu zhi bu men", "组织部门" }, { "zu zhi bu zhang", "组织部长" }, { "zu zhi gong zuo", "组织工作" },
			{ "zu zhi ji gou", "组织机构" }, { "zu zhi jia gou", "组织架构" }, { "zu zhi jian she", "组织建设" }, { "zu zhi jie gou", "组织结构" },
			{ "zu zhi kai zhan", "组织开展" }, { "zu zhi ling dao", "组织领导" }, { "zu zhi shi shi", "组织实施" }, { "zu zhi xie tiao", "组织协调" },
			{ "zu zhi xing shi", "组织形式" }, { "zu zhi zhe", "组织者" }, { "zu zhou", "诅咒" }, { "zu zhu", "租住" }, { "zu zhuang", "组装" }, { "zu zong", "祖宗" },
			{ "zu zu", "足足" }, { "zu zu zhang", "组组长" }, { "zuan", "揝" }, { "zuan", "攥" }, { "zuan", "欑" }, { "zuan", "篹" }, { "zuan", "籫" }, { "zuan", "纂" },
			{ "zuan", "纉" }, { "zuan", "纘" }, { "zuan", "缵" }, { "zuan", "赚" }, { "zuan", "躜" }, { "zuan", "躦" }, { "zuan", "鑚" }, { "zuan", "鑽" },
			{ "zuan", "钻" }, { "zuan chu", "钻出" }, { "zuan dao", "钻到" }, { "zuan jie", "钻戒" }, { "zuan jin", "钻进" }, { "zuan jing", "钻井" },
			{ "zuan kong", "钻孔" }, { "zuan qian", "赚钱" }, { "zuan shi", "钻石" }, { "zuan tou", "钻头" }, { "zuan yan", "钻研" }, { "zui", "厜" }, { "zui", "咀" },
			{ "zui", "嗺" }, { "zui", "嘴" }, { "zui", "噿" }, { "zui", "嫢" }, { "zui", "嶉" }, { "zui", "嶊" }, { "zui", "嶵" }, { "zui", "晬" }, { "zui", "最" },
			{ "zui", "枠" }, { "zui", "樶" }, { "zui", "檇" }, { "zui", "檌" }, { "zui", "欈" }, { "zui", "濢" }, { "zui", "璻" }, { "zui", "睟" }, { "zui", "祽" },
			{ "zui", "絊" }, { "zui", "纗" }, { "zui", "罪" }, { "zui", "脧" }, { "zui", "蕞" }, { "zui", "觜" }, { "zui", "酔" }, { "zui", "酨" }, { "zui", "醉" },
			{ "zui", "鋷" }, { "zui ai", "最爱" }, { "zui ba", "嘴巴" }, { "zui bang", "最棒" }, { "zui bian", "嘴边" }, { "zui bu", "最不" }, { "zui can", "最惨" },
			{ "zui cha", "最差" }, { "zui cha de", "最差的" }, { "zui chang", "最常" }, { "zui chang", "最长" }, { "zui chang de", "最长的" }, { "zui chi", "最迟" },
			{ "zui chu", "最初" }, { "zui chun", "嘴唇" }, { "zui da", "最大" }, { "zui da de", "最大的" }, { "zui da gong lv", "最大功率" }, { "zui da gui mo", "最大规模" },
			{ "zui da hua", "最大化" }, { "zui da xian du", "最大限度" }, { "zui da zhi", "最大值" }, { "zui dao", "醉倒" }, { "zui di", "最低" }, { "zui di ceng", "最底层" },
			{ "zui di dian", "最低点" }, { "zui di gong zi", "最低工资" }, { "zui di jia", "最低价" }, { "zui duan", "最短" }, { "zui duan de", "最短的" },
			{ "zui duo", "最多" }, { "zui duo de", "最多的" }, { "zui e", "罪恶" }, { "zui e xin", "最恶心" }, { "zui fan", "最烦" }, { "zui fan", "罪犯" },
			{ "zui fu", "最富" }, { "zui gao", "最高" }, { "zui gao dian", "最高点" }, { "zui gao fa yuan", "最高法院" }, { "zui gao fen", "最高分" },
			{ "zui gao feng", "最高峰" }, { "zui gao jia", "最高价" }, { "zui gao jing jie", "最高境界" }, { "zui gao qi wen", "最高气温" }, { "zui gao xue li", "最高学历" },
			{ "zui guang", "最广" }, { "zui gui", "最贵" }, { "zui guo", "罪过" }, { "zui hao", "最好" }, { "zui hao de", "最好的" }, { "zui hao yong", "最好用" },
			{ "zui hen", "最恨" }, { "zui hong", "最红" }, { "zui hou", "最后" }, { "zui hou geng xin", "最后更新" }, { "zui hou hai shi", "最后还是" },
			{ "zui hou shi ke", "最后时刻" }, { "zui hou yi chang", "最后一场" }, { "zui hou yi ci", "最后一次" }, { "zui hou yi tian", "最后一天" }, { "zui huai", "最坏" },
			{ "zui huo", "最火" }, { "zui ji", "最忌" }, { "zui jia", "最佳" }, { "zui jia da an", "最佳答案" }, { "zui jia shi ji", "最佳时机" },
			{ "zui jia shi jian", "最佳时间" }, { "zui jia xuan ze", "最佳选择" }, { "zui jian dan de", "最简单的" }, { "zui jiao", "嘴角" }, { "zui jin", "最近" },
			{ "zui jin ji nian", "最近几年" }, { "zui jing", "最精" }, { "zui jing dian", "最经典" }, { "zui jiu", "醉酒" }, { "zui ju", "最具" }, { "zui ku", "最酷" },
			{ "zui kuai", "最快" }, { "zui kuai de", "最快的" }, { "zui kui huo shou", "罪魁祸首" }, { "zui le", "醉了" }, { "zui li", "嘴里" }, { "zui li hai", "最厉害" },
			{ "zui lian", "嘴脸" }, { "zui ling", "最令" }, { "zui liu xing de", "最流行的" }, { "zui man", "最慢" }, { "zui mei", "最美" }, { "zui ming", "罪名" },
			{ "zui nan", "最难" }, { "zui neng", "最能" }, { "zui nie", "罪孽" }, { "zui niu", "最牛" }, { "zui pa", "最怕" }, { "zui pian yi de", "最便宜的" },
			{ "zui qian yan", "最前沿" }, { "zui qiang", "最强" }, { "zui quan de", "最全的" }, { "zui rang", "最让" }, { "zui rang ren", "最让人" }, { "zui re", "最热" },
			{ "zui re men", "最热门" }, { "zui ren", "罪人" }, { "zui ren", "醉人" }, { "zui shang", "嘴上" }, { "zui shao", "最少" }, { "zui shao de", "最少的" },
			{ "zui shen", "最深" }, { "zui shen de", "最深的" }, { "zui shou", "最受" }, { "zui shou guan zhu", "最受关注" }, { "zui shou huan ying", "最受欢迎" },
			{ "zui shuai", "最帅" }, { "zui wan", "最晚" }, { "zui wei", "最为" }, { "zui xi huan de", "最喜欢的" }, { "zui xian", "最先" }, { "zui xiang", "最想" },
			{ "zui xiao", "最小" }, { "zui xiao de", "最小的" }, { "zui xiao hua", "最小化" }, { "zui xiao zhi", "最小值" }, { "zui xin", "最新" },
			{ "zui xin ban", "最新版" }, { "zui xin ban ben", "最新版本" }, { "zui xin dong tai", "最新动态" }, { "zui xin jin zhan", "最新进展" }, { "zui xin kuan", "最新款" },
			{ "zui xin tui chu", "最新推出" }, { "zui xin xiao xi", "最新消息" }, { "zui xing", "罪行" }, { "zui xing gan", "最性感" }, { "zui yi", "最易" },
			{ "zui ying", "嘴硬" }, { "zui you", "最优" }, { "zui you", "最有" }, { "zui you jia zhi", "最有价值" }, { "zui you xiu de", "最优秀的" }, { "zui yuan", "最远" },
			{ "zui zao", "最早" }, { "zui zao de", "最早的" }, { "zui zhong", "最终" }, { "zui zhong", "最重" }, { "zui zhong hai shi", "最终还是" },
			{ "zui zhong huan xiang", "最终幻想" }, { "zui zhong mu biao", "最终目标" }, { "zui zhong yao de", "最重要的" }, { "zui zhong yong hu", "最终用户" },
			{ "zui zhu yao de", "最主要的" }, { "zui zhuan ye", "最专业" }, { "zui zui", "最最" }, { "zun", "僎" }, { "zun", "僔" }, { "zun", "噂" }, { "zun", "墫" },
			{ "zun", "尊" }, { "zun", "嶟" }, { "zun", "拵" }, { "zun", "捘" }, { "zun", "撙" }, { "zun", "栫" }, { "zun", "樽" }, { "zun", "瀳" }, { "zun", "繜" },
			{ "zun", "罇" }, { "zun", "袸" }, { "zun", "譐" }, { "zun", "跧" }, { "zun", "踆" }, { "zun", "遵" }, { "zun", "銌" }, { "zun", "鐏" }, { "zun", "鱒" },
			{ "zun", "鳟" }, { "zun", "鷷" }, { "zun cheng", "尊称" }, { "zun chong", "尊崇" }, { "zun cong", "遵从" }, { "zun gui", "尊贵" },
			{ "zun ji shou fa", "遵纪守法" }, { "zun jing", "尊敬" }, { "zun ming", "遵命" }, { "zun shou", "遵守" }, { "zun xun", "遵循" }, { "zun yan", "尊严" },
			{ "zun yi", "遵义" }, { "zun zhao", "遵照" }, { "zun zhe", "尊者" }, { "zun zhong", "尊重" }, { "zun zhong wang shang", "尊重网上" }, { "zuo", "佐" },
			{ "zuo", "作" }, { "zuo", "侳" }, { "zuo", "做" }, { "zuo", "凿" }, { "zuo", "唑" }, { "zuo", "嘬" }, { "zuo", "坐" }, { "zuo", "岝" }, { "zuo", "左" },
			{ "zuo", "座" }, { "zuo", "怍" }, { "zuo", "捽" }, { "zuo", "撮" }, { "zuo", "昨" }, { "zuo", "柞" }, { "zuo", "椊" }, { "zuo", "琢" }, { "zuo", "祚" },
			{ "zuo", "稓" }, { "zuo", "笮" }, { "zuo", "筰" }, { "zuo", "繓" }, { "zuo", "胙" }, { "zuo", "莋" }, { "zuo", "葃" }, { "zuo", "葄" }, { "zuo", "蓙" },
			{ "zuo", "酢" }, { "zuo", "鈼" }, { "zuo", "鑿" }, { "zuo", "阼" }, { "zuo ai", "做爱" }, { "zuo an", "作案" }, { "zuo an", "左岸" }, { "zuo ba", "作罢" },
			{ "zuo bi", "作弊" }, { "zuo bi", "左臂" }, { "zuo bi qi", "作弊器" }, { "zuo bian", "左边" }, { "zuo biao", "坐标" }, { "zuo biao xi", "坐标系" },
			{ "zuo bu dao", "做不到" }, { "zuo bu liao", "做不了" }, { "zuo bu zhu", "坐不住" }, { "zuo cai", "做菜" }, { "zuo ce", "左侧" }, { "zuo ce pai ming", "左侧排名" },
			{ "zuo che", "坐车" }, { "zuo cheng", "作成" }, { "zuo cheng", "做成" }, { "zuo cheng shi", "座城市" }, { "zuo chong", "座充" }, { "zuo chu", "作出" },
			{ "zuo chu", "做出" }, { "zuo chu jue ding", "作出决定" }, { "zuo chu lai", "做出来" }, { "zuo chuan", "坐船" }, { "zuo ci", "作词" }, { "zuo cuo", "做错" },
			{ "zuo da", "作答" }, { "zuo da", "做大" }, { "zuo da zuo qiang", "做大做强" }, { "zuo dao", "做到" }, { "zuo dao", "坐到" }, { "zuo de", "做得" },
			{ "zuo de", "做的" }, { "zuo de geng hao", "做得更好" }, { "zuo de hao", "做得好" }, { "zuo dian", "做点" }, { "zuo dian", "坐垫" }, { "zuo diao", "做掉" },
			{ "zuo dou zheng", "作斗争" }, { "zuo dui", "作对" }, { "zuo duo", "做多" }, { "zuo e", "作恶" }, { "zuo er", "昨儿" }, { "zuo fa", "作法" },
			{ "zuo fa", "做法" }, { "zuo fan", "做饭" }, { "zuo fang", "作坊" }, { "zuo fei", "作废" }, { "zuo fei ji", "坐飞机" }, { "zuo feng", "作风" },
			{ "zuo feng jian she", "作风建设" }, { "zuo ge", "作个" }, { "zuo ge", "做个" }, { "zuo gong", "做工" }, { "zuo gong xian", "作贡献" },
			{ "zuo gong xian", "做贡献" }, { "zuo gu piao", "做股票" }, { "zuo guai", "作怪" }, { "zuo guan", "做官" }, { "zuo guang gao", "做广告" }, { "zuo guo", "做过" },
			{ "zuo guo", "坐过" }, { "zuo hao", "作好" }, { "zuo hao", "做好" }, { "zuo hao shi", "做好事" }, { "zuo hao zhun bei", "做好准备" }, { "zuo hua", "作画" },
			{ "zuo hui", "做回" }, { "zuo huo che", "坐火车" }, { "zuo ji", "座机" }, { "zuo jia", "作价" }, { "zuo jia", "作假" }, { "zuo jia", "作家" },
			{ "zuo jia wu", "做家务" }, { "zuo jian", "左键" }, { "zuo jiao", "左脚" }, { "zuo ke", "作客" }, { "zuo ke", "做客" }, { "zuo kong", "做空" },
			{ "zuo lao", "坐牢" }, { "zuo le", "作了" }, { "zuo le", "做了" }, { "zuo le", "坐了" } };
};
