package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN49 {
	public static String[][] pl = { { "wei sheng", "为生" }, { "wei sheng", "卫生" }, { "wei sheng", "威盛" }, { "wei sheng", "尾声" }, { "wei sheng bu", "卫生部" },
			{ "wei sheng bu men", "卫生部门" }, { "wei sheng jian", "卫生间" }, { "wei sheng jian du", "卫生监督" }, { "wei sheng jin", "卫生巾" },
			{ "wei sheng ju", "卫生局" }, { "wei sheng su", "维生素" }, { "wei sheng wu", "微生物" }, { "wei sheng xi tong", "卫生系统" }, { "wei sheng yuan", "卫生院" },
			{ "wei sheng zhi", "卫生纸" }, { "wei shi", "为使" }, { "wei shi", "为师" }, { "wei shi", "卫士" }, { "wei shi", "卫视" }, { "wei shi", "喂食" },
			{ "wei shi", "尾市" }, { "wei shi ji", "威士忌" }, { "wei shou", "为首" }, { "wei shu", "位数" }, { "wei shu", "尾数" }, { "wei shu bu duo", "为数不多" },
			{ "wei shu ji", "委书记" }, { "wei shui", "为谁" }, { "wei si", "维斯" }, { "wei suan", "胃酸" }, { "wei sui", "尾随" }, { "wei sui", "未遂" },
			{ "wei suo", "猥琐" }, { "wei suo", "萎缩" }, { "wei suo yu wei", "为所欲为" }, { "wei ta", "为他" }, { "wei ta", "为她" }, { "wei ta", "为它" },
			{ "wei ta ming", "维他命" }, { "wei te", "维特" }, { "wei teng", "胃疼" }, { "wei ti", "为题" }, { "wei tiao", "微调" }, { "wei tong", "胃痛" },
			{ "wei tu", "位图" }, { "wei tuo", "委托" }, { "wei tuo ren", "委托人" }, { "wei tuo shu", "委托书" }, { "wei wan", "委婉" }, { "wei wan", "未完" },
			{ "wei wan cheng", "未完成" }, { "wei wang", "为王" }, { "wei wang", "威望" }, { "wei wei", "喂喂" }, { "wei wei", "巍巍" }, { "wei wei", "微微" },
			{ "wei wei", "维维" }, { "wei wei", "薇薇" }, { "wei wei dao lai", "娓娓道来" }, { "wei wei yi xiao", "微微一笑" }, { "wei wen", "慰问" }, { "wei wo", "为我" },
			{ "wei wu", "为伍" }, { "wei wu", "威武" }, { "wei wu er", "维吾尔" }, { "wei wu zhu yi", "唯物主义" }, { "wei xi", "维系" }, { "wei xian", "为先" },
			{ "wei xian", "危险" }, { "wei xian pin", "危险品" }, { "wei xian xing", "危险性" }, { "wei xian yin su", "危险因素" }, { "wei xiao", "微小" },
			{ "wei xiao", "微笑" }, { "wei xiao bao", "韦小宝" }, { "wei xie", "威胁" }, { "wei xie", "猥亵" }, { "wei xin", "威信" }, { "wei xin", "违心" },
			{ "wei xing", "卫星" }, { "wei xing", "微型" }, { "wei xing", "微星" }, { "wei xing dian shi", "卫星电视" }, { "wei xing fa she", "卫星发射" },
			{ "wei xiu", "维修" }, { "wei xiu ren yuan", "维修人员" }, { "wei xiu zhan", "维修站" }, { "wei xun huan", "微循环" }, { "wei ya", "维亚" }, { "wei yan", "威严" },
			{ "wei yan", "胃炎" }, { "wei yan song ting", "危言耸听" }, { "wei yang", "喂养" }, { "wei yang", "未央" }, { "wei ye", "伟业" }, { "wei ye na", "维也纳" },
			{ "wei yi", "为一" }, { "wei yi", "为宜" }, { "wei yi", "位移" }, { "wei yi", "唯一" }, { "wei yi", "惟一" }, { "wei you", "为由" }, { "wei you", "唯有" },
			{ "wei you", "惟有" }, { "wei you", "未有" }, { "wei yu", "位于" }, { "wei yu", "卫浴" }, { "wei yu", "微雨" }, { "wei yu", "未予" },
			{ "wei yu chou mou", "未雨绸缪" }, { "wei yuan", "委员" }, { "wei yuan hui", "委员会" }, { "wei yuan zhang", "委员长" }, { "wei yue", "违约" },
			{ "wei yue jin", "违约金" }, { "wei yue ze ren", "违约责任" }, { "wei zai", "围在" }, { "wei zao", "伪造" }, { "wei zhang", "违章" }, { "wei zhe", "围着" },
			{ "wei zhe", "违者" }, { "wei zheng", "为证" }, { "wei zhi", "为之" }, { "wei zhi", "为止" }, { "wei zhi", "位置" }, { "wei zhi", "未知" },
			{ "wei zhi", "谓之" }, { "wei zhi shu", "未知数" }, { "wei zhong", "为重" }, { "wei zhong xin de", "为中心的" }, { "wei zhu", "为主" }, { "wei zhu", "围住" },
			{ "wei zhuang", "伪装" }, { "wei zhun", "为准" }, { "wei zi", "位子" }, { "wei zu", "维族" }, { "wei zuo", "围坐" }, { "wei zuo", "未作" }, { "wen", "亠" },
			{ "wen", "刎" }, { "wen", "吻" }, { "wen", "呅" }, { "wen", "呡" }, { "wen", "問" }, { "wen", "塭" }, { "wen", "妏" }, { "wen", "忞" }, { "wen", "抆" },
			{ "wen", "搵" }, { "wen", "文" }, { "wen", "桽" }, { "wen", "榲" }, { "wen", "歾" }, { "wen", "殟" }, { "wen", "汶" }, { "wen", "温" }, { "wen", "溫" },
			{ "wen", "炆" }, { "wen", "玟" }, { "wen", "瑥" }, { "wen", "璺" }, { "wen", "瘟" }, { "wen", "稳" }, { "wen", "穏" }, { "wen", "穩" }, { "wen", "紊" },
			{ "wen", "紋" }, { "wen", "絻" }, { "wen", "纹" }, { "wen", "聞" }, { "wen", "脕" }, { "wen", "芠" }, { "wen", "蕴" }, { "wen", "蚊" }, { "wen", "豱" },
			{ "wen", "閺" }, { "wen", "閿" }, { "wen", "闅" }, { "wen", "问" }, { "wen", "闻" }, { "wen", "阌" }, { "wen", "雯" }, { "wen", "顐" }, { "wen", "饂" },
			{ "wen", "馼" }, { "wen", "魰" }, { "wen", "鰛" }, { "wen", "鰮" }, { "wen", "鳼" }, { "wen", "鼤" }, { "wen an", "文案" }, { "wen bao", "温饱" },
			{ "wen ben", "文本" }, { "wen ben kuang", "文本框" }, { "wen ben wen jian", "文本文件" }, { "wen bi", "文笔" }, { "wen bu", "稳步" }, { "wen cai", "文采" },
			{ "wen cha", "温差" }, { "wen chang", "文昌" }, { "wen chong", "蚊虫" }, { "wen chuan", "汶川" }, { "wen chuan xian", "汶川县" }, { "wen chuang", "温床" },
			{ "wen cun", "温存" }, { "wen da", "问答" }, { "wen dang", "文档" }, { "wen dang", "稳当" }, { "wen dang zhong", "文档中" }, { "wen dao", "问到" },
			{ "wen dao", "问道" }, { "wen dao", "闻到" }, { "wen de", "问得" }, { "wen di", "文帝" }, { "wen ding", "稳定" }, { "wen ding", "问鼎" },
			{ "wen ding fa zhan", "稳定发展" }, { "wen ding xing", "稳定性" }, { "wen du", "温度" }, { "wen du ji", "温度计" }, { "wen fa", "文法" }, { "wen feng", "文峰" },
			{ "wen feng", "文风" }, { "wen gao", "文稿" }, { "wen ge", "文革" }, { "wen ge", "温格" }, { "wen ge", "问个" }, { "wen ge hua", "温哥华" },
			{ "wen gong tuan", "文工团" }, { "wen gu", "稳固" }, { "wen guo", "问过" }, { "wen hao", "问号" }, { "wen hao", "问好" }, { "wen he", "吻合" },
			{ "wen he", "温和" }, { "wen hou", "问候" }, { "wen hua", "文化" }, { "wen hua", "文华" }, { "wen hua", "问话" }, { "wen hua bei jing", "文化背景" },
			{ "wen hua bu", "文化部" }, { "wen hua chan ye", "文化产业" }, { "wen hua cheng du", "文化程度" }, { "wen hua chuan bo", "文化传播" },
			{ "wen hua chuan tong", "文化传统" }, { "wen hua di yun", "文化底蕴" }, { "wen hua fa zhan", "文化发展" }, { "wen hua fen wei", "文化氛围" },
			{ "wen hua guan", "文化馆" }, { "wen hua guang chang", "文化广场" }, { "wen hua huo dong", "文化活动" }, { "wen hua jian she", "文化建设" },
			{ "wen hua jiao liu", "文化交流" }, { "wen hua jiao yu", "文化教育" }, { "wen hua jie", "文化节" }, { "wen hua ju", "文化局" }, { "wen hua ke", "文化课" },
			{ "wen hua nei han", "文化内涵" }, { "wen hua ren", "文化人" }, { "wen hua sheng huo", "文化生活" }, { "wen hua shi chang", "文化市场" },
			{ "wen hua shi ye", "文化事业" }, { "wen hua shui ping", "文化水平" }, { "wen hua su zhi", "文化素质" }, { "wen hua yi chan", "文化遗产" },
			{ "wen hua yi shu", "文化艺术" }, { "wen hua zhi shi", "文化知识" }, { "wen hua zhong xin", "文化中心" }, { "wen huo", "文火" }, { "wen ji", "文集" },
			{ "wen ji", "问及" }, { "wen jia bao", "温家宝" }, { "wen jian", "文件" }, { "wen jian", "稳健" }, { "wen jian da xiao", "文件大小" },
			{ "wen jian ge shi", "文件格式" }, { "wen jian jia", "文件夹" }, { "wen jian jia li", "文件夹里" }, { "wen jian jia xia", "文件夹下" },
			{ "wen jian jia zhong", "文件夹中" }, { "wen jian jing shen", "文件精神" }, { "wen jian lei xing", "文件类型" }, { "wen jian lie biao", "文件列表" },
			{ "wen jian ming", "文件名" }, { "wen jian xi tong", "文件系统" }, { "wen jiang", "温江" }, { "wen jiao", "文教" }, { "wen jing", "文静" }, { "wen ju", "文具" },
			{ "wen ju", "稳居" }, { "wen juan", "问卷" }, { "wen juan diao cha", "问卷调查" }, { "wen ke", "文科" }, { "wen ku", "文库" }, { "wen lai", "文莱" },
			{ "wen le", "吻了" }, { "wen li", "文理" }, { "wen li", "纹理" }, { "wen lian", "文联" }, { "wen ling", "温岭" }, { "wen long", "文龙" }, { "wen lu", "纹路" },
			{ "wen lu", "问路" }, { "wen luan", "紊乱" }, { "wen mang", "文盲" }, { "wen mi", "文秘" }, { "wen ming", "文明" }, { "wen ming", "闻名" },
			{ "wen ming ban", "文明办" }, { "wen ming dan wei", "文明单位" }, { "wen ming yong yu", "文明用语" }, { "wen ni", "吻你" }, { "wen ni", "问你" },
			{ "wen nuan", "温暖" }, { "wen ping", "文凭" }, { "wen qi", "问起" }, { "wen qing", "温情" }, { "wen quan", "温泉" }, { "wen re", "温热" },
			{ "wen ren", "文人" }, { "wen rou", "温柔" }, { "wen run", "温润" }, { "wen shan", "文山" }, { "wen shen", "纹身" }, { "wen shi", "文史" },
			{ "wen shi", "温室" }, { "wen shi", "问世" }, { "wen shi qi ti", "温室气体" }, { "wen shu", "文书" }, { "wen shui", "温水" }, { "wen shun", "温顺" },
			{ "wen ta", "问他" }, { "wen tai", "稳态" }, { "wen tan", "文坛" }, { "wen ti", "文体" }, { "wen ti", "问题" }, { "wen ti jie jue", "问题解决" },
			{ "wen tuo", "稳妥" }, { "wen wan", "温婉" }, { "wen wang", "温网" }, { "wen wang wen", "文网文" }, { "wen wen", "文文" }, { "wen wen", "稳稳" },
			{ "wen wen", "问问" }, { "wen wen", "闻闻" }, { "wen wen", "雯雯" }, { "wen wen er ya", "温文尔雅" }, { "wen wo", "问我" }, { "wen wu", "文武" },
			{ "wen wu", "文物" }, { "wen wu bao hu", "文物保护" }, { "wen xi", "温习" }, { "wen xian", "文献" }, { "wen xiang", "蚊香" }, { "wen xin", "温馨" },
			{ "wen xin ti shi", "温馨提示" }, { "wen xin wu kui", "问心无愧" }, { "wen xiong", "文胸" }, { "wen xue", "文学" }, { "wen xue chuang zuo", "文学创作" },
			{ "wen xue jia", "文学家" }, { "wen xue jiang", "文学奖" }, { "wen xue shi", "文学史" }, { "wen xue yi shu", "文学艺术" }, { "wen xue yuan", "文学院" },
			{ "wen xue zuo pin", "文学作品" }, { "wen xun", "问询" }, { "wen xun", "闻讯" }, { "wen ya", "文雅" }, { "wen yan", "文言" }, { "wen yan", "闻言" },
			{ "wen yan wen", "文言文" }, { "wen yi", "文艺" }, { "wen yi", "瘟疫" }, { "wen yi fu xing", "文艺复兴" }, { "wen yi pian", "文艺片" },
			{ "wen yi wan hui", "文艺晚会" }, { "wen yi xia", "问一下" }, { "wen yi yan chu", "文艺演出" }, { "wen yuan", "文员" }, { "wen ze", "问责" },
			{ "wen zhai", "文摘" }, { "wen zhang", "文章" }, { "wen zhang", "蚊帐" }, { "wen zhang lai yuan", "文章来源" }, { "wen zhang lei xing", "文章类型" },
			{ "wen zhang nei rong", "文章内容" }, { "wen zhe", "吻着" }, { "wen zhi", "闻之" }, { "wen zhong", "文中" }, { "wen zhong", "稳重" }, { "wen zhou", "温州" },
			{ "wen zhou ren", "温州人" }, { "wen zhou shi", "温州市" }, { "wen zhu", "稳住" }, { "wen zi", "文字" }, { "wen zi", "蚊子" }, { "wen zi ji", "问自己" },
			{ "wen zong li", "温总理" }, { "weng", "嗡" }, { "weng", "塕" }, { "weng", "奣" }, { "weng", "暡" }, { "weng", "滃" }, { "weng", "瓮" }, { "weng", "甕" },
			{ "weng", "瞈" }, { "weng", "罋" }, { "weng", "翁" }, { "weng", "聬" }, { "weng", "蓊" }, { "weng", "蕹" }, { "weng", "螉" }, { "weng", "鶲" },
			{ "weng", "齆" }, { "weng mei ling", "翁美玲" }, { "weng weng", "嗡嗡" }, { "wo", "仴" }, { "wo", "倭" }, { "wo", "偓" }, { "wo", "卧" }, { "wo", "喔" },
			{ "wo", "堝" }, { "wo", "婐" }, { "wo", "婑" }, { "wo", "幄" }, { "wo", "我" }, { "wo", "挝" }, { "wo", "捰" }, { "wo", "捼" }, { "wo", "握" },
			{ "wo", "撾" }, { "wo", "擭" }, { "wo", "斡" }, { "wo", "沃" }, { "wo", "涡" }, { "wo", "涴" }, { "wo", "渥" }, { "wo", "渦" }, { "wo", "濄" },
			{ "wo", "濣" }, { "wo", "焥" }, { "wo", "猧" }, { "wo", "瓁" }, { "wo", "瞃" }, { "wo", "硪" }, { "wo", "窝" }, { "wo", "窩" }, { "wo", "肟" },
			{ "wo", "腛" }, { "wo", "臥" }, { "wo", "莴" }, { "wo", "萵" }, { "wo", "薶" }, { "wo", "蜗" }, { "wo", "蝸" }, { "wo", "踒" }, { "wo", "踠" },
			{ "wo", "雘" }, { "wo", "齷" }, { "wo", "龌" }, { "wo a", "我啊" }, { "wo ai", "我爱" }, { "wo ai ni", "我爱你" }, { "wo ai wo jia", "我爱我家" },
			{ "wo ba", "我吧" }, { "wo ba", "我把" }, { "wo ba", "我爸" }, { "wo bang", "我帮" }, { "wo bang ni", "我帮你" }, { "wo bei", "我辈" }, { "wo ben", "我本" },
			{ "wo bing bu", "我并不" }, { "wo bu", "我不" }, { "wo bu", "我部" }, { "wo bu hui", "我不会" }, { "wo bu xiang", "我不想" }, { "wo bu yao", "我不要" },
			{ "wo bu zai", "我不在" }, { "wo cai", "我才" }, { "wo cai", "我猜" }, { "wo ceng", "我曾" }, { "wo chang", "我厂" }, { "wo chang", "我常" },
			{ "wo cheng ren", "我承认" }, { "wo chuang", "卧床" }, { "wo chuo", "龌龊" }, { "wo cuo le", "我错了" }, { "wo da", "我打" }, { "wo da feng", "沃达丰" },
			{ "wo dai", "我带" }, { "wo dang", "我党" }, { "wo dao", "我倒" }, { "wo de", "我得" }, { "wo de", "我的" }, { "wo de ai", "我的爱" }, { "wo de jia", "我的家" },
			{ "wo de lian", "我的脸" }, { "wo de meng", "我的梦" }, { "wo de shou", "我的手" }, { "wo de xin", "我的心" }, { "wo dei", "我得" }, { "wo deng", "我等" },
			{ "wo deng ni", "我等你" }, { "wo di", "卧底" }, { "wo dian", "窝点" }, { "wo ding", "我顶" }, { "wo dou", "我都" }, { "wo dui", "我对" },
			{ "wo dui ni", "我对你" }, { "wo en", "沃恩" }, { "wo er", "沃尔" }, { "wo er ma", "沃尔玛" }, { "wo er wo", "沃尔沃" }, { "wo fa", "我发" }, { "wo fang", "我方" },
			{ "wo gai", "我该" }, { "wo gan", "我敢" }, { "wo gang", "我刚" }, { "wo gao su ni", "我告诉你" }, { "wo gei ni", "我给你" }, { "wo gen", "我跟" },
			{ "wo geng", "我更" }, { "wo guo", "我国" }, { "wo hai", "我还" }, { "wo hai neng", "我还能" }, { "wo hang", "我行" }, { "wo hao", "我好" },
			{ "wo hao xiang", "我好想" }, { "wo he", "我和" }, { "wo he ni", "我和你" }, { "wo he ta", "我和他" }, { "wo he wo", "我和我" }, { "wo hen", "我很" },
			{ "wo hen", "我恨" }, { "wo hen xiang", "我很想" }, { "wo hu cang long", "卧虎藏龙" }, { "wo jia", "我家" }, { "wo jian", "我见" }, { "wo jian guo", "我见过" },
			{ "wo jiang", "我将" }, { "wo jiang", "我讲" }, { "wo jiao", "我叫" }, { "wo jin", "握紧" }, { "wo jiu", "我就" }, { "wo jiu bu", "我就不" }, { "wo ju", "我局" },
			{ "wo jun", "我军" }, { "wo kan", "我看" }, { "wo kan guo", "我看过" }, { "wo kan kan", "我看看" }, { "wo kan ni", "我看你" }, { "wo kan zhe", "我看着" },
			{ "wo ke", "我可" }, { "wo kou", "倭寇" }, { "wo ku le", "我哭了" }, { "wo lai", "我来" }, { "wo lao", "我老" }, { "wo lao po", "我老婆" }, { "wo le", "我了" },
			{ "wo li", "窝里" }, { "wo lia", "我俩" }, { "wo long", "卧龙" }, { "wo lun", "涡轮" }, { "wo ma", "我吗" }, { "wo ma", "我妈" }, { "wo mei", "我没" },
			{ "wo men", "我们" }, { "wo men lia", "我们俩" }, { "wo na", "我拿" }, { "wo na", "我那" }, { "wo nang", "窝囊" }, { "wo neng", "我能" }, { "wo niu", "蜗牛" },
			{ "wo pa", "我怕" }, { "wo pai", "我拍" }, { "wo pu", "卧铺" }, { "wo qin ai de", "我亲爱的" }, { "wo qu", "我区" }, { "wo qu", "我去" }, { "wo que", "我却" },
			{ "wo shang", "我上" }, { "wo sheng", "我省" }, { "wo shi", "卧室" }, { "wo shi", "卧式" }, { "wo shi", "我市" }, { "wo shi", "我是" }, { "wo shi ge", "我是个" },
			{ "wo shi li", "卧室里" }, { "wo shi ni", "我是你" }, { "wo shi shui", "我是谁" }, { "wo shou", "握手" }, { "wo shuo", "我说" }, { "wo shuo guo", "我说过" },
			{ "wo shuo wo", "我说我" }, { "wo song ni", "我送你" }, { "wo suo", "我所" }, { "wo tao yan", "我讨厌" }, { "wo ting", "我听" }, { "wo tu", "沃土" },
			{ "wo wang", "我往" }, { "wo wei", "我为" }, { "wo wen", "我问" }, { "wo wo", "喔喔" }, { "wo wo", "窝窝" }, { "wo xian", "我先" }, { "wo xian", "我县" },
			{ "wo xiang", "我想" }, { "wo xiang kan", "我想看" }, { "wo xiang mai", "我想买" }, { "wo xiang ni", "我想你" }, { "wo xiang shuo", "我想说" },
			{ "wo xiang wo", "我想我" }, { "wo xiang yao", "我想要" }, { "wo xiang zuo", "我想做" }, { "wo xiao", "我校" }, { "wo xiao", "我笑" }, { "wo xie", "我写" },
			{ "wo xin", "我心" }, { "wo xing wo su", "我行我素" }, { "wo xuan", "斡旋" }, { "wo xue hui le", "我学会了" }, { "wo yao", "我要" }, { "wo yao kan", "我要看" },
			{ "wo yao mai", "我要买" }, { "wo yao zhao", "我要找" }, { "wo yao zuo", "我要做" }, { "wo ye", "我也" }, { "wo ye bu", "我也不" }, { "wo ye lai", "我也来" },
			{ "wo ye shi", "我也是" }, { "wo ye xiang", "我也想" }, { "wo ye yao", "我也要" }, { "wo ye you", "我也有" }, { "wo yi", "我一" }, { "wo yi", "我已" },
			{ "wo yi ding hui", "我一定会" }, { "wo yi yan", "我一眼" }, { "wo yong", "我用" }, { "wo you", "我又" }, { "wo you", "我有" }, { "wo you", "握有" },
			{ "wo you ge", "我有个" }, { "wo yuan", "我愿" }, { "wo yuan", "我院" }, { "wo zai", "我再" }, { "wo zai", "我在" }, { "wo zai shou", "握在手" },
			{ "wo zao", "我早" }, { "wo zhao", "我找" }, { "wo zhe", "我这" }, { "wo zhe", "握着" }, { "wo zhen", "我真" }, { "wo zheng", "我正" }, { "wo zhi", "我只" },
			{ "wo zhi dao ni", "我知道你" }, { "wo zhi xiang", "我只想" }, { "wo zhu", "握住" }, { "wo zong", "我总" }, { "wo zou", "我走" }, { "wo zou le", "我走了" },
			{ "wo zui", "我最" }, { "wo zui ai", "我最爱" }, { "wo zuo", "我做" }, { "wu", "乌" }, { "wu", "五" }, { "wu", "亡" }, { "wu", "仵" }, { "wu", "伍" },
			{ "wu", "侮" }, { "wu", "俉" }, { "wu", "倵" }, { "wu", "兀" }, { "wu", "剭" }, { "wu", "务" }, { "wu", "務" }, { "wu", "勿" }, { "wu", "午" },
			{ "wu", "吳" }, { "wu", "吴" }, { "wu", "吾" }, { "wu", "呉" }, { "wu", "呜" }, { "wu", "唔" }, { "wu", "啎" }, { "wu", "嗚" }, { "wu", "圬" },
			{ "wu", "坞" }, { "wu", "堥" }, { "wu", "塢" }, { "wu", "墲" }, { "wu", "妩" }, { "wu", "婺" }, { "wu", "嫵" }, { "wu", "寤" }, { "wu", "屋" },
			{ "wu", "屼" }, { "wu", "岉" }, { "wu", "嵨" }, { "wu", "巫" }, { "wu", "幠" }, { "wu", "庑" }, { "wu", "廡" }, { "wu", "忤" }, { "wu", "怃" },
			{ "wu", "恶" }, { "wu", "悟" }, { "wu", "憮" }, { "wu", "戊" }, { "wu", "扤" }, { "wu", "捂" }, { "wu", "摀" }, { "wu", "於" }, { "wu", "无" },
			{ "wu", "旿" }, { "wu", "晤" }, { "wu", "杇" }, { "wu", "杌" }, { "wu", "梧" }, { "wu", "橆" }, { "wu", "武" }, { "wu", "毋" }, { "wu", "汙" },
			{ "wu", "污" }, { "wu", "沕" }, { "wu", "洖" }, { "wu", "洿" }, { "wu", "浯" }, { "wu", "潕" }, { "wu", "烏" }, { "wu", "焐" }, { "wu", "無" },
			{ "wu", "物" }, { "wu", "牾" }, { "wu", "玝" }, { "wu", "珷" }, { "wu", "珸" }, { "wu", "甒" }, { "wu", "痦" }, { "wu", "瞴" }, { "wu", "矹" },
			{ "wu", "碔" }, { "wu", "禑" }, { "wu", "窏" }, { "wu", "粅" }, { "wu", "膴" }, { "wu", "舞" }, { "wu", "芜" }, { "wu", "芴" }, { "wu", "茣" },
			{ "wu", "莁" }, { "wu", "蕪" }, { "wu", "蘁" }, { "wu", "蜈" }, { "wu", "螐" }, { "wu", "誣" }, { "wu", "誤" }, { "wu", "譕" }, { "wu", "诬" },
			{ "wu", "误" }, { "wu", "趶" }, { "wu", "躌" }, { "wu", "迕" }, { "wu", "逜" }, { "wu", "邬" }, { "wu", "郚" }, { "wu", "鄔" }, { "wu", "釫" },
			{ "wu", "鋈" }, { "wu", "鋘" }, { "wu", "錻" }, { "wu", "鎢" }, { "wu", "钨" }, { "wu", "阢" }, { "wu", "雺" }, { "wu", "雾" }, { "wu", "霧" },
			{ "wu", "霿" }, { "wu", "靰" }, { "wu", "騖" }, { "wu", "骛" }, { "wu", "鯃" }, { "wu", "鴮" }, { "wu", "鵐" }, { "wu", "鵡" }, { "wu", "鶩" },
			{ "wu", "鷡" }, { "wu", "鹉" }, { "wu", "鹜" }, { "wu", "鼯" }, { "wu", "齀" }, { "wu ai", "无碍" }, { "wu an", "午安" }, { "wu bai", "五百" },
			{ "wu bai", "伍佰" }, { "wu bai wan", "五百万" }, { "wu bang guo", "吴邦国" }, { "wu bao", "误报" }, { "wu bei", "五倍" }, { "wu bi", "五笔" },
			{ "wu bi", "务必" }, { "wu bi", "无比" }, { "wu bi", "舞弊" }, { "wu bian", "无边" }, { "wu bian wu ji", "无边无际" }, { "wu bing shen yin", "无病呻吟" },
			{ "wu bu", "无不" }, { "wu bu", "舞步" }, { "wu bu ji", "无不及" }, { "wu cai", "五彩" }, { "wu cai bin fen", "五彩缤纷" }, { "wu can", "午餐" },
			{ "wu cao zuo", "误操作" }, { "wu ceng", "五层" }, { "wu cha", "误差" }, { "wu chan", "物产" }, { "wu chan jie ji", "无产阶级" }, { "wu chang", "无偿" },
			{ "wu chang", "无常" }, { "wu chang", "武昌" }, { "wu chang xian xue", "无偿献血" }, { "wu chen", "无尘" }, { "wu cheng", "五成" }, { "wu chi", "无耻" },
			{ "wu chi", "舞池" }, { "wu chu", "悟出" }, { "wu chu", "无处" }, { "wu chu bu zai", "无处不在" }, { "wu ci", "五次" }, { "wu ci", "无此" },
			{ "wu ci hui yi", "五次会议" }, { "wu cong", "无从" }, { "wu da", "五大" }, { "wu da", "武大" }, { "wu da", "武打" }, { "wu da lang", "武大郎" },
			{ "wu dai", "五代" }, { "wu dang", "武当" }, { "wu dao", "舞蹈" }, { "wu dao", "误导" }, { "wu dao kou", "五道口" }, { "wu dao xing", "误导性" },
			{ "wu de", "伍德" }, { "wu di", "无敌" }, { "wu di", "武帝" }, { "wu di zi rong", "无地自容" }, { "wu dian", "五点" }, { "wu dian", "污点" },
			{ "wu ding", "屋顶" }, { "wu dong", "舞动" }, { "wu dong yu zhong", "无动于衷" }, { "wu du", "无度" }, { "wu du", "无毒" }, { "wu du", "误读" },
			{ "wu duan", "无端" }, { "wu duan", "武断" }, { "wu fa", "无法" }, { "wu fa da kai", "无法打开" }, { "wu fa fang wen", "无法访问" },
			{ "wu fa gai bian", "无法改变" }, { "wu fa jin ru", "无法进入" }, { "wu fa kang ju", "无法抗拒" }, { "wu fa kong zhi", "无法控制" }, { "wu fa qi dong", "无法启动" },
			{ "wu fa shi yong", "无法使用" }, { "wu fa wan cheng", "无法完成" }, { "wu fa wang ji", "无法忘记" }, { "wu fa wu tian", "无法无天" },
			{ "wu fa xian shi", "无法显示" }, { "wu fa zhao dao", "无法找到" }, { "wu fa zheng chang", "无法正常" }, { "wu fan", "午饭" }, { "wu fang", "无妨" },
			{ "wu fei", "无非" }, { "wu fen", "五分" }, { "wu fen zhi yi", "五分之一" }, { "wu fen zhong", "五分钟" }, { "wu feng", "无缝" }, { "wu feng", "无风" },
			{ "wu feng xian", "无风险" }, { "wu gang", "吴刚" }, { "wu gang", "武钢" }, { "wu ge", "五个" }, { "wu ge fang mian", "五个方面" }, { "wu ge ren", "五个人" },
			{ "wu ge yue", "五个月" }, { "wu gong", "务工" }, { "wu gong", "无功" }, { "wu gong", "武功" }, { "wu gong", "蜈蚣" }, { "wu gong hai", "无公害" },
			{ "wu gong ren yuan", "务工人员" }, { "wu gou", "污垢" }, { "wu gu", "无故" }, { "wu gu", "无辜" }, { "wu guan", "五官" }, { "wu guan", "无关" },
			{ "wu guan", "物管" }, { "wu guan jin yao", "无关紧要" }, { "wu guang", "无光" }, { "wu gui", "乌龟" }, { "wu guo", "吴国" }, { "wu guo", "无果" },
			{ "wu hai", "无害" }, { "wu hai hua", "无害化" }, { "wu han", "武汉" }, { "wu han da xue", "武汉大学" }, { "wu han dui", "武汉队" }, { "wu han ren", "武汉人" },
			{ "wu han shi", "武汉市" }, { "wu hao", "五号" }, { "wu hao", "唔好" }, { "wu hei", "乌黑" }, { "wu hen", "无痕" }, { "wu hou", "午后" }, { "wu hu", "五湖" },
			{ "wu hu", "芜湖" }, { "wu hu si hai", "五湖四海" }, { "wu hua", "无话" }, { "wu hua", "物化" }, { "wu hua", "雾化" }, { "wu hua ba men", "五花八门" },
			{ "wu hua rou", "五花肉" }, { "wu huan", "五环" }, { "wu hui", "无悔" }, { "wu hui", "污秽" }, { "wu hui", "舞会" }, { "wu hui", "误会" }, { "wu ji", "五级" },
			{ "wu ji", "无忌" }, { "wu ji", "无机" }, { "wu ji", "无极" }, { "wu ji", "无计" }, { "wu ji xian", "无极限" }, { "wu ji yu shi", "无济于事" },
			{ "wu ji zhi tan", "无稽之谈" }, { "wu jia", "五家" }, { "wu jia", "无价" }, { "wu jia", "物价" }, { "wu jia ju", "物价局" }, { "wu jia ke gui", "无家可归" },
			{ "wu jia shang zhang", "物价上涨" }, { "wu jia zhi shu", "物价指数" }, { "wu jian", "无间" }, { "wu jian", "物件" }, { "wu jian dao", "无间道" },
			{ "wu jiang", "吴江" }, { "wu jiang", "武将" }, { "wu jiao", "午觉" }, { "wu jiao chang", "五角场" }, { "wu jiao da lou", "五角大楼" }, { "wu jie", "五届" },
			{ "wu jie", "无界" }, { "wu jie", "无解" }, { "wu jie", "误解" }, { "wu jin", "五金" }, { "wu jin", "无尽" }, { "wu jing", "武警" },
			{ "wu jing bu dui", "武警部队" }, { "wu jing da cai", "无精打采" }, { "wu jing lian", "吴敬琏" }, { "wu ju wu shu", "无拘无束" }, { "wu jun", "无菌" },
			{ "wu ke", "无可" }, { "wu ke hou fei", "无可厚非" }, { "wu ke jiu yao", "无可救药" }, { "wu ke lan", "乌克兰" }, { "wu ke nai he", "无可奈何" },
			{ "wu ke tiao ti", "无可挑剔" }, { "wu kong", "悟空" }, { "wu kuang", "五矿" }, { "wu kui", "无愧" }, { "wu kui yu", "无愧于" }, { "wu la gui", "乌拉圭" },
			{ "wu lai", "无赖" }, { "wu le", "误了" }, { "wu lei", "五类" }, { "wu lei", "无泪" }, { "wu li", "屋里" }, { "wu li", "无力" }, { "wu li", "无理" },
			{ "wu li", "无礼" }, { "wu li", "武力" }, { "wu li", "物力" }, { "wu li", "物理" }, { "wu li", "雾里" }, { "wu li qu nao", "无理取闹" }, { "wu li tou", "无厘头" },
			{ "wu li xi", "物理系" }, { "wu li xue", "物理学" }, { "wu li xue jia", "物理学家" }, { "wu liang", "无良" }, { "wu liang", "无量" }, { "wu liang ye", "五粮液" },
			{ "wu liao", "无聊" }, { "wu liao", "物料" }, { "wu lin", "武林" }, { "wu lin", "舞林" }, { "wu lin wai zhuan", "武林外传" }, { "wu liu", "五六" },
			{ "wu liu", "物流" }, { "wu liu gong si", "物流公司" } };
};
