package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN55 {
	public static String[][] pl = { { "yan xian", "沿线" }, { "yan xian", "眼线" }, { "yan xian", "艳羡" }, { "yan xiao yun san", "烟消云散" }, { "yan xing", "言行" },
			{ "yan xiu", "研修" }, { "yan xu", "延续" }, { "yan xun", "烟熏" }, { "yan yan", "炎炎" }, { "yan yan", "燕燕" }, { "yan yan shi shi", "严严实实" },
			{ "yan yan yi xi", "奄奄一息" }, { "yan yang", "艳阳" }, { "yan yao shui", "眼药水" }, { "yan ye", "烟叶" }, { "yan yi", "演义" }, { "yan yi", "演绎" },
			{ "yan yi", "演艺" }, { "yan yi jie", "演艺界" }, { "yan yi quan", "演艺圈" }, { "yan ying", "掩映" }, { "yan ying", "眼影" }, { "yan yong", "沿用" },
			{ "yan yu", "烟雨" }, { "yan yu", "艳遇" }, { "yan yu", "言语" }, { "yan yu", "谚语" }, { "yan yuan", "演员" }, { "yan zhan", "延展" }, { "yan zhao", "艳照" },
			{ "yan zhe", "沿着" }, { "yan zheng", "严正" }, { "yan zheng", "炎症" }, { "yan zheng", "验证" }, { "yan zheng ma", "验证码" }, { "yan zheng zheng", "眼睁睁" },
			{ "yan zhi", "研制" }, { "yan zhi", "胭脂" }, { "yan zhi", "腌制" }, { "yan zhi", "言之" }, { "yan zhi cheng gong", "研制成功" }, { "yan zhi chu", "研制出" },
			{ "yan zhong", "严重" }, { "yan zhong", "眼中" }, { "yan zhong hou guo", "严重后果" }, { "yan zhong xing", "严重性" }, { "yan zhong ying xiang", "严重影响" },
			{ "yan zhong zhe", "严重者" }, { "yan zhou", "兖州" }, { "yan zhu", "眼珠" }, { "yan zhu zi", "眼珠子" }, { "yan zi", "晏紫" }, { "yan zi", "燕姿" },
			{ "yan zi", "燕子" }, { "yan zi", "验资" }, { "yan zou", "演奏" }, { "yang", "仰" }, { "yang", "佒" }, { "yang", "佯" }, { "yang", "养" }, { "yang", "卬" },
			{ "yang", "坱" }, { "yang", "垟" }, { "yang", "央" }, { "yang", "姎" }, { "yang", "婸" }, { "yang", "岟" }, { "yang", "崵" }, { "yang", "崸" },
			{ "yang", "徉" }, { "yang", "怏" }, { "yang", "恙" }, { "yang", "懩" }, { "yang", "扬" }, { "yang", "抰" }, { "yang", "揚" }, { "yang", "攁" },
			{ "yang", "敭" }, { "yang", "昜" }, { "yang", "暘" }, { "yang", "杨" }, { "yang", "样" }, { "yang", "楊" }, { "yang", "様" }, { "yang", "樣" },
			{ "yang", "歍" }, { "yang", "殃" }, { "yang", "氧" }, { "yang", "泱" }, { "yang", "洋" }, { "yang", "漾" }, { "yang", "潒" }, { "yang", "瀁" },
			{ "yang", "炀" }, { "yang", "炴" }, { "yang", "烊" }, { "yang", "煬" }, { "yang", "珜" }, { "yang", "瑒" }, { "yang", "疡" }, { "yang", "痒" },
			{ "yang", "瘍" }, { "yang", "癢" }, { "yang", "眻" }, { "yang", "禓" }, { "yang", "秧" }, { "yang", "紻" }, { "yang", "羊" }, { "yang", "羕" },
			{ "yang", "胦" }, { "yang", "蛘" }, { "yang", "軮" }, { "yang", "鉠" }, { "yang", "鍈" }, { "yang", "鍚" }, { "yang", "鐊" }, { "yang", "阳" },
			{ "yang", "陽" }, { "yang", "雵" }, { "yang", "鞅" }, { "yang", "颺" }, { "yang", "養" }, { "yang", "鴦" }, { "yang", "鸉" }, { "yang", "鸯" },
			{ "yang ban", "样板" }, { "yang ban fang", "样板房" }, { "yang ban jian", "样板间" }, { "yang ben", "样本" }, { "yang bing", "养病" }, { "yang cheng", "养成" },
			{ "yang cheng", "羊城" }, { "yang cheng liang hao", "养成良好" }, { "yang cheng lin", "杨丞琳" }, { "yang chun", "阳春" }, { "yang cong", "洋葱" },
			{ "yang cong tou", "洋葱头" }, { "yang da", "养大" }, { "yang de", "养的" }, { "yang dong xi", "样东西" }, { "yang er", "样儿" }, { "yang fan", "扬帆" },
			{ "yang fan", "杨帆" }, { "yang fang", "洋房" }, { "yang fen", "养分" }, { "yang gang", "阳刚" }, { "yang gou", "养狗" }, { "yang guan", "阳关" },
			{ "yang guang", "杨光" }, { "yang guang", "阳光" }, { "yang guang ming mei", "阳光明媚" }, { "yang gui fei", "杨贵妃" }, { "yang guo", "杨过" },
			{ "yang hang", "央行" }, { "yang hao", "养好" }, { "yang hu", "养护" }, { "yang hua", "氧化" }, { "yang hua lv", "氧化铝" }, { "yang hua wu", "氧化物" },
			{ "yang huo", "养活" }, { "yang ji", "养鸡" }, { "yang ji", "样机" }, { "yang ji", "阳极" }, { "yang jia", "养家" }, { "yang jia", "杨佳" },
			{ "yang jia", "杨家" }, { "yang jia hu kou", "养家糊口" }, { "yang jiang", "阳江" }, { "yang jiu", "洋酒" }, { "yang ju", "阳具" }, { "yang lan", "杨澜" },
			{ "yang lao", "养老" }, { "yang lao bao xian", "养老保险" }, { "yang lao jin", "养老金" }, { "yang lao yuan", "养老院" }, { "yang li", "阳历" },
			{ "yang li juan", "杨丽娟" }, { "yang lin", "杨林" }, { "yang ling", "杨凌" }, { "yang liu", "杨柳" }, { "yang lu fei", "养路费" }, { "yang mao", "样貌" },
			{ "yang mao", "羊毛" }, { "yang mao shan", "羊毛衫" }, { "yang mei", "杨梅" }, { "yang ming", "扬名" }, { "yang ming", "杨明" }, { "yang ming", "阳明" },
			{ "yang mou", "杨某" }, { "yang mu", "仰慕" }, { "yang niu", "养牛" }, { "yang pi", "羊皮" }, { "yang pian", "样片" }, { "yang pin", "样品" },
			{ "yang pu", "杨浦" }, { "yang pu qu", "杨浦区" }, { "yang qi", "仰起" }, { "yang qi", "央企" }, { "yang qi", "扬起" }, { "yang qi", "氧气" },
			{ "yang qi", "洋气" }, { "yang qi", "阳气" }, { "yang qiu", "央求" }, { "yang quan", "养犬" }, { "yang qun", "羊群" }, { "yang ren", "洋人" },
			{ "yang rong", "羊绒" }, { "yang rou", "羊肉" }, { "yang rou chuan", "羊肉串" }, { "yang shang", "养伤" }, { "yang shen", "养神" }, { "yang sheng", "养生" },
			{ "yang sheng qi", "扬声器" }, { "yang shi", "仰视" }, { "yang shi", "央视" }, { "yang shi", "样式" }, { "yang shi biao", "样式表" },
			{ "yang shi chun wan", "央视春晚" }, { "yang shu", "杨树" }, { "yang shui", "羊水" }, { "yang shuo", "阳朔" }, { "yang tai", "阳台" }, { "yang tian", "仰天" },
			{ "yang tou", "仰头" }, { "yang wa wa", "洋娃娃" }, { "yang wang", "仰望" }, { "yang wei", "杨威" }, { "yang wei", "阳痿" }, { "yang wo", "仰卧" },
			{ "yang wo qi zuo", "仰卧起坐" }, { "yang xian", "阳线" }, { "yang xiao", "杨晓" }, { "yang xing", "阳性" }, { "yang xue", "养血" }, { "yang yan", "养眼" },
			{ "yang yan", "养颜" }, { "yang yan", "扬言" }, { "yang yang", "扬扬" }, { "yang yang", "样样" }, { "yang yang", "洋洋" }, { "yang yang", "痒痒" },
			{ "yang yang", "羊羊" }, { "yang yang", "阳阳" }, { "yang yi", "洋溢" }, { "yang yu", "养育" }, { "yang yu", "养鱼" }, { "yang zhang", "样张" },
			{ "yang zhe", "养着" }, { "yang zhen ning", "杨振宁" }, { "yang zhi", "养殖" }, { "yang zhi chang", "养殖场" }, { "yang zhi hu", "养殖户" },
			{ "yang zhi ye", "养殖业" }, { "yang zhou", "扬州" }, { "yang zhou shi", "扬州市" }, { "yang zhu", "养猪" }, { "yang zi", "扬子" }, { "yang zi", "杨子" },
			{ "yang zi", "样子" }, { "yang zi", "洋子" }, { "yao", "么" }, { "yao", "侥" }, { "yao", "偠" }, { "yao", "傜" }, { "yao", "吆" }, { "yao", "咬" },
			{ "yao", "喓" }, { "yao", "嗂" }, { "yao", "噛" }, { "yao", "垚" }, { "yao", "堯" }, { "yao", "夭" }, { "yao", "妖" }, { "yao", "姚" }, { "yao", "媱" },
			{ "yao", "宎" }, { "yao", "尧" }, { "yao", "尭" }, { "yao", "岆" }, { "yao", "崾" }, { "yao", "嶢" }, { "yao", "幺" }, { "yao", "徭" }, { "yao", "恌" },
			{ "yao", "愮" }, { "yao", "抭" }, { "yao", "揺" }, { "yao", "搖" }, { "yao", "摇" }, { "yao", "摿" }, { "yao", "撽" }, { "yao", "曜" }, { "yao", "曣" },
			{ "yao", "杳" }, { "yao", "柼" }, { "yao", "榚" }, { "yao", "榣" }, { "yao", "殀" }, { "yao", "殽" }, { "yao", "溔" }, { "yao", "烑" }, { "yao", "燿" },
			{ "yao", "爻" }, { "yao", "猺" }, { "yao", "獟" }, { "yao", "玅" }, { "yao", "珧" }, { "yao", "瑤" }, { "yao", "瑶" }, { "yao", "疟" }, { "yao", "眑" },
			{ "yao", "祅" }, { "yao", "穾" }, { "yao", "窅" }, { "yao", "窈" }, { "yao", "窑" }, { "yao", "窔" }, { "yao", "窯" }, { "yao", "窰" }, { "yao", "筄" },
			{ "yao", "繇" }, { "yao", "约" }, { "yao", "耀" }, { "yao", "肴" }, { "yao", "腰" }, { "yao", "舀" }, { "yao", "艞" }, { "yao", "苭" }, { "yao", "药" },
			{ "yao", "葯" }, { "yao", "葽" }, { "yao", "蕘" }, { "yao", "薬" }, { "yao", "藥" }, { "yao", "袎" }, { "yao", "要" }, { "yao", "覞" }, { "yao", "訞" },
			{ "yao", "詏" }, { "yao", "謠" }, { "yao", "謡" }, { "yao", "谣" }, { "yao", "軺" }, { "yao", "轺" }, { "yao", "遙" }, { "yao", "遥" }, { "yao", "邀" },
			{ "yao", "銚" }, { "yao", "鑰" }, { "yao", "钥" }, { "yao", "铫" }, { "yao", "陶" }, { "yao", "靿" }, { "yao", "顤" }, { "yao", "颻" }, { "yao", "餚" },
			{ "yao", "騕" }, { "yao", "驁" }, { "yao", "鰩" }, { "yao", "鳐" }, { "yao", "鴢" }, { "yao", "鷂" }, { "yao", "鷕" }, { "yao", "鹞" }, { "yao an", "要按" },
			{ "yao ba", "要把" }, { "yao bai", "摇摆" }, { "yao ban", "要办" }, { "yao bao", "腰包" }, { "yao bei", "要被" }, { "yao bi", "要比" }, { "yao bu", "腰部" },
			{ "yao bu", "要不" }, { "yao bu de", "要不得" }, { "yao bu ke ji", "遥不可及" }, { "yao bu ran", "要不然" }, { "yao bu shi", "要不是" }, { "yao bu yao", "要不要" },
			{ "yao cai", "药材" }, { "yao cao", "药草" }, { "yao chang", "药厂" }, { "yao chi", "瑶池" }, { "yao chi", "要吃" }, { "yao chu", "要出" },
			{ "yao chuan", "要穿" }, { "yao chuan", "谣传" }, { "yao cong", "要从" }, { "yao da", "要打" }, { "yao dai", "腰带" }, { "yao dai", "要带" },
			{ "yao dang", "要当" }, { "yao dao", "要到" }, { "yao de", "要得" }, { "yao deng", "要等" }, { "yao di", "要低" }, { "yao dian", "药店" },
			{ "yao dian", "要点" }, { "yao dong", "摇动" }, { "yao dong", "窑洞" }, { "yao dui", "要对" }, { "yao duo", "要多" }, { "yao duo jiu", "要多久" },
			{ "yao duo shao qian", "要多少钱" }, { "yao fan", "要饭" }, { "yao fang", "药房" }, { "yao fang", "药方" }, { "yao fei", "药费" }, { "yao gan", "摇杆" },
			{ "yao gan", "要干" }, { "yao gan", "遥感" }, { "yao gao", "药膏" }, { "yao gao", "要搞" }, { "yao gao", "要高" }, { "yao gei", "要给" }, { "yao gen", "要跟" },
			{ "yao guai", "妖怪" }, { "yao guan", "药罐" }, { "yao gun", "摇滚" }, { "yao gun yue", "摇滚乐" }, { "yao guo", "要过" }, { "yao hai", "要害" },
			{ "yao hao", "摇号" }, { "yao hao", "要好" }, { "yao he", "吆喝" }, { "yao he", "要和" }, { "yao he", "要喝" }, { "yao hua", "要花" }, { "yao huang", "摇晃" },
			{ "yao hui", "要回" }, { "yao ji", "药剂" }, { "yao jia", "药价" }, { "yao jia", "要价" }, { "yao jia", "要加" }, { "yao jian", "腰间" }, { "yao jian", "药监" },
			{ "yao jian", "要件" }, { "yao jian", "要见" }, { "yao jian ju", "药监局" }, { "yao jiang", "要将" }, { "yao jiang", "要讲" }, { "yao jiao", "要交" },
			{ "yao jiao", "要叫" }, { "yao jin", "要紧" }, { "yao jing", "妖精" }, { "yao jiu", "药酒" }, { "yao kai", "要开" }, { "yao kan", "要看" },
			{ "yao kao", "要考" }, { "yao kao", "要靠" }, { "yao kong", "遥控" }, { "yao kong qi", "遥控器" }, { "yao ku", "要哭" }, { "yao kuai", "要快" },
			{ "yao lai", "要来" }, { "yao lan", "摇篮" }, { "yao le", "咬了" }, { "yao le", "摇了" }, { "yao le", "要了" }, { "yao li", "药理" }, { "yao ling", "要领" },
			{ "yao ma", "要吗" }, { "yao mai", "姚麦" }, { "yao mai", "要买" }, { "yao mai", "要卖" }, { "yao me", "要么" }, { "yao ming", "姚明" }, { "yao ming", "要命" },
			{ "yao mo", "妖魔" }, { "yao mo hua", "妖魔化" }, { "yao na", "要拿" }, { "yao neng", "要能" }, { "yao ni", "要你" }, { "yao nie", "妖孽" },
			{ "yao pai", "要拍" }, { "yao pian", "药片" }, { "yao pin", "药品" }, { "yao qi", "药企" }, { "yao qian", "要钱" }, { "yao qiang", "要强" },
			{ "yao qing", "要请" }, { "yao qing", "邀请" }, { "yao qing han", "邀请函" }, { "yao qing sai", "邀请赛" }, { "yao qiu", "要求" }, { "yao qu", "要去" },
			{ "yao rang", "要让" }, { "yao rao", "妖娆" }, { "yao ren", "咬人" }, { "yao sai", "要塞" }, { "yao sha", "要杀" }, { "yao shan", "药膳" },
			{ "yao shang", "咬伤" }, { "yao shang", "腰上" }, { "yao shao", "要少" }, { "yao shen yi bian", "摇身一变" }, { "yao shi", "药师" }, { "yao shi", "要使" },
			{ "yao shi", "要是" }, { "yao shi", "钥匙" }, { "yao shui", "药水" }, { "yao shuo", "要说" }, { "yao si", "咬死" }, { "yao si", "要死" }, { "yao song", "要送" },
			{ "yao su", "要素" }, { "yao suan", "腰酸" }, { "yao suan bei teng", "腰酸背疼" }, { "yao teng", "腰疼" }, { "yao tiao", "窈窕" }, { "yao ting", "要听" },
			{ "yao tong", "腰痛" }, { "yao tou", "摇头" }, { "yao wan", "药丸" }, { "yao wan", "要玩" }, { "yao wang", "遥望" }, { "yao wei", "腰围" },
			{ "yao wei", "要为" }, { "yao wen", "要问" }, { "yao wen", "要闻" }, { "yao wo", "要我" }, { "yao wu", "药物" }, { "yao wu zhi liao", "药物治疗" },
			{ "yao xian", "要先" }, { "yao xiang", "要像" }, { "yao xiang", "要向" }, { "yao xiang", "要想" }, { "yao xiao", "药效" }, { "yao xie", "要写" },
			{ "yao xie", "要挟" }, { "yao xue", "药学" }, { "yao xue", "要学" }, { "yao ya", "咬牙" }, { "yao ya qie chi", "咬牙切齿" }, { "yao yan", "妖艳" },
			{ "yao yan", "耀眼" }, { "yao yan", "谣言" }, { "yao yao", "妖妖" }, { "yao yao", "摇摇" }, { "yao yao", "瑶瑶" }, { "yao yao", "遥遥" },
			{ "yao yao ling xian", "遥遥领先" }, { "yao yao tou", "摇摇头" }, { "yao yao wu qi", "遥遥无期" }, { "yao yao yu zhui", "摇摇欲坠" }, { "yao ye", "摇曳" },
			{ "yao ye", "药业" }, { "yao ye", "药液" }, { "yao yi", "要义" }, { "yao yi", "要以" }, { "yao yong", "药用" }, { "yao yong", "要用" }, { "yao you", "要有" },
			{ "yao you", "要由" }, { "yao yu", "要与" }, { "yao yuan", "遥远" }, { "yao yue", "要约" }, { "yao yue", "邀约" }, { "yao zai", "要再" }, { "yao zai", "要在" },
			{ "yao zen me", "要怎么" }, { "yao zhao", "要找" }, { "yao zhe", "咬着" }, { "yao zhe", "夭折" }, { "yao zhe", "摇着" }, { "yao zhu", "咬住" },
			{ "yao zhua", "要抓" }, { "yao zhui", "腰椎" }, { "yao zou", "要走" }, { "yao zuo", "要做" }, { "yao zuo shen me", "要做什么" }, { "ye", "业" }, { "ye", "也" },
			{ "ye", "倻" }, { "ye", "冶" }, { "ye", "叶" }, { "ye", "咽" }, { "ye", "噎" }, { "ye", "埜" }, { "ye", "堨" }, { "ye", "夜" }, { "ye", "嶪" },
			{ "ye", "抴" }, { "ye", "拽" }, { "ye", "掖" }, { "ye", "揶" }, { "ye", "擛" }, { "ye", "擨" }, { "ye", "擫" }, { "ye", "晔" }, { "ye", "暍" },
			{ "ye", "曄" }, { "ye", "曳" }, { "ye", "枒" }, { "ye", "椰" }, { "ye", "楪" }, { "ye", "業" }, { "ye", "歋" }, { "ye", "殕" }, { "ye", "殗" },
			{ "ye", "液" }, { "ye", "漜" }, { "ye", "澲" }, { "ye", "烨" }, { "ye", "熀" }, { "ye", "燁" }, { "ye", "爷" }, { "ye", "爺" }, { "ye", "瓛" },
			{ "ye", "痷" }, { "ye", "瞱" }, { "ye", "窫" }, { "ye", "緤" }, { "ye", "耶" }, { "ye", "腋" }, { "ye", "葉" }, { "ye", "蠮" }, { "ye", "謁" },
			{ "ye", "谒" }, { "ye", "邪" }, { "ye", "邺" }, { "ye", "鄴" }, { "ye", "野" }, { "ye", "鍱" }, { "ye", "鎑" }, { "ye", "鐷" }, { "ye", "铘" },
			{ "ye", "靥" }, { "ye", "靨" }, { "ye", "頁" }, { "ye", "页" }, { "ye", "饁" }, { "ye", "鵺" }, { "ye ba", "也把" }, { "ye ba", "也罢" }, { "ye ban", "夜半" },
			{ "ye ban", "夜班" }, { "ye bei", "也被" }, { "ye bi", "也比" }, { "ye bie", "也别" }, { "ye bu", "也不" }, { "ye bu ke neng", "也不可能" },
			{ "ye bu li wai", "也不例外" }, { "ye bu yuan", "也不愿" }, { "ye bu zhi dao", "也不知道" }, { "ye cai", "也才" }, { "ye cai", "野菜" }, { "ye cao", "野草" },
			{ "ye ceng", "也曾" }, { "ye cha", "夜叉" }, { "ye chang", "也常" }, { "ye cheng", "也称" }, { "ye cong", "也从" }, { "ye da", "也大" }, { "ye de", "也得" },
			{ "ye dei", "也得" }, { "ye dian", "夜店" }, { "ye dou", "也都" }, { "ye dou shi", "也都是" }, { "ye dui", "也对" }, { "ye duo", "也多" },
			{ "ye fa zhan", "业发展" }, { "ye fei", "也非" }, { "ye feng", "夜风" }, { "ye fu", "耶夫" }, { "ye gai", "也该" }, { "ye gan", "也敢" }, { "ye gei", "也给" },
			{ "ye gen", "也跟" }, { "ye geng", "也更" }, { "ye gou", "也够" }, { "ye gou", "野狗" }, { "ye hai", "也还" }, { "ye hao", "也好" }, { "ye he hua", "耶和华" },
			{ "ye hen", "也很" }, { "ye hu", "业户" }, { "ye hua", "液化" }, { "ye hua", "野花" }, { "ye hua qi", "液化气" }, { "ye hui", "也会" }, { "ye hui you", "也会有" },
			{ "ye ji", "业绩" }, { "ye ji", "也即" }, { "ye ji", "野鸡" }, { "ye ji zeng zhang", "业绩增长" }, { "ye jian", "夜间" }, { "ye jian ying", "叶剑英" },
			{ "ye jiang", "也将" }, { "ye jiao", "也叫" }, { "ye jiao", "也较" }, { "ye jiao", "页脚" }, { "ye jie", "业界" }, { "ye jin", "冶金" }, { "ye jing", "夜景" },
			{ "ye jing", "液晶" }, { "ye jing dian shi", "液晶电视" }, { "ye jing mian ban", "液晶面板" }, { "ye jing ping", "液晶屏" }, { "ye jiu", "也就" },
			{ "ye jiu shi shuo", "也就是说" }, { "ye ke", "也可" }, { "ye kong", "夜空" }, { "ye kuai", "也快" }, { "ye lai", "也来" }, { "ye lang", "野狼" },
			{ "ye li", "夜里" }, { "ye li qin", "叶利钦" }, { "ye lian", "冶炼" }, { "ye lu", "耶鲁" }, { "ye lu da xue", "耶鲁大学" }, { "ye lu sa leng", "耶路撒冷" },
			{ "ye lv", "耶律" }, { "ye ma", "野马" }, { "ye ma", "页码" }, { "ye man", "野蛮" }, { "ye man ren", "野蛮人" }, { "ye mao", "野猫" }, { "ye mao zi", "夜猫子" },
			{ "ye mei", "也没" }, { "ye mei", "页眉" }, { "ye men", "爷们" }, { "ye mian", "页面" }, { "ye mu", "夜幕" }, { "ye nan", "也难" }, { "ye nei", "业内" },
			{ "ye nei ren shi", "业内人士" }, { "ye neng", "也能" }, { "ye pa", "也怕" }, { "ye pian", "叶片" }, { "ye qing", "也请" }, { "ye qu", "也去" },
			{ "ye qu", "夜曲" }, { "ye rang", "也让" }, { "ye ren", "野人" }, { "ye se", "夜色" }, { "ye shao", "也少" }, { "ye shen", "夜深" },
			{ "ye shen ren jing", "夜深人静" }, { "ye sheng", "野生" }, { "ye sheng dong wu", "野生动物" }, { "ye sheng huo", "夜生活" }, { "ye shi", "也使" },
			{ "ye shi", "也是" }, { "ye shi", "夜市" }, { "ye shi yi zhong", "也是一种" }, { "ye shou", "野兽" }, { "ye shou", "页首" }, { "ye shu", "页数" },
			{ "ye shuo", "也说" }, { "ye su", "耶稣" }, { "ye suan", "也算" }, { "ye suan", "叶酸" }, { "ye tai", "业态" }, { "ye tai", "也太" }, { "ye tai", "液态" },
			{ "ye ti", "液体" }, { "ye ting", "也挺" }, { "ye wai", "野外" }, { "ye wan", "夜晚" }, { "ye wei", "也为" }, { "ye wei", "也未" }, { "ye wei", "页尾" },
			{ "ye wei hui", "业委会" }, { "ye wu", "业务" }, { "ye wu", "也无" }, { "ye wu bu", "业务部" }, { "ye wu bu men", "业务部门" }, { "ye wu fa zhan", "业务发展" },
			{ "ye wu fan wei", "业务范围" }, { "ye wu gong zuo", "业务工作" }, { "ye wu liang", "业务量" }, { "ye wu liu cheng", "业务流程" }, { "ye wu luo ji", "业务逻辑" },
			{ "ye wu mo shi", "业务模式" }, { "ye wu neng li", "业务能力" }, { "ye wu pei xun", "业务培训" }, { "ye wu ren yuan", "业务人员" }, { "ye wu shou ru", "业务收入" },
			{ "ye wu shui ping", "业务水平" }, { "ye wu su zhi", "业务素质" }, { "ye wu xi tong", "业务系统" }, { "ye wu yuan", "业务员" }, { "ye xia", "腋下" },
			{ "ye xiang", "也像" }, { "ye xiang", "也向" }, { "ye xiang", "也想" }, { "ye xiao", "夜宵" }, { "ye xin", "野心" }, { "ye xing", "也行" },
			{ "ye xing", "夜行" }, { "ye xing", "野性" }, { "ye xu", "也许" }, { "ye xue", "也学" }, { "ye ya", "液压" }, { "ye yan", "夜宴" }, { "ye yao", "也要" },
			{ "ye ye", "夜夜" }, { "ye ye", "爷爷" }, { "ye ye nai nai", "爷爷奶奶" }, { "ye yi", "业已" }, { "ye yi", "也已" }, { "ye yi qian", "叶一茜" },
			{ "ye yin", "也因" }, { "ye ying", "也应" }, { "ye yong", "也用" }, { "ye you", "也有" }, { "ye you", "也由" }, { "ye you", "夜游" }, { "ye yu", "业余" },
			{ "ye yu", "夜雨" }, { "ye yu shi jian", "业余时间" }, { "ye zai", "也在" }, { "ye zhan", "野战" }, { "ye zhan jun", "野战军" }, { "ye zhe", "业者" },
			{ "ye zheng", "也正" }, { "ye zhi", "也只" }, { "ye zhu", "业主" }, { "ye zhu", "野猪" }, { "ye zhu da hui", "业主大会" }, { "ye zhu lun tan", "业主论坛" },
			{ "ye zi", "叶子" }, { "ye zi", "椰子" }, { "ye zong hui", "夜总会" }, { "ye zuo", "也做" }, { "yi", "一" }, { "yi", "乂" }, { "yi", "义" }, { "yi", "乙" },
			{ "yi", "亄" }, { "yi", "亦" }, { "yi", "亿" }, { "yi", "仡" }, { "yi", "以" }, { "yi", "仪" }, { "yi", "伊" }, { "yi", "伿" }, { "yi", "佁" },
			{ "yi", "佚" }, { "yi", "佾" }, { "yi", "侇" }, { "yi", "依" }, { "yi", "俋" }, { "yi", "倚" }, { "yi", "偯" }, { "yi", "儀" }, { "yi", "億" },
			{ "yi", "儗" }, { "yi", "冝" }, { "yi", "刈" }, { "yi", "劓" }, { "yi", "劮" }, { "yi", "勩" }, { "yi", "匇" }, { "yi", "匜" }, { "yi", "医" },
			{ "yi", "呓" }, { "yi", "咦" }, { "yi", "咿" }, { "yi", "唈" }, { "yi", "嗌" }, { "yi", "噫" }, { "yi", "囈" }, { "yi", "圛" }, { "yi", "圯" },
			{ "yi", "垼" }, { "yi", "埶" }, { "yi", "埸" }, { "yi", "墿" }, { "yi", "壱" }, { "yi", "壹" }, { "yi", "夷" }, { "yi", "奕" }, { "yi", "姨" },
			{ "yi", "媐" }, { "yi", "嫕" }, { "yi", "嫛" }, { "yi", "宜" }, { "yi", "宧" }, { "yi", "寱" }, { "yi", "寲" }, { "yi", "尾" }, { "yi", "屹" },
			{ "yi", "峄" }, { "yi", "峓" }, { "yi", "崺" }, { "yi", "嶧" }, { "yi", "嶬" }, { "yi", "嶷" }, { "yi", "已" }, { "yi", "帟" }, { "yi", "帠" },
			{ "yi", "廙" }, { "yi", "异" }, { "yi", "弈" }, { "yi", "弋" }, { "yi", "弌" }, { "yi", "彛" }, { "yi", "彜" }, { "yi", "彝" }, { "yi", "役" },
			{ "yi", "忆" }, { "yi", "怡" }, { "yi", "怿" }, { "yi", "恞" }, { "yi", "悒" }, { "yi", "意" }, { "yi", "憶" }, { "yi", "懌" }, { "yi", "懿" },
			{ "yi", "戺" }, { "yi", "扆" }, { "yi", "扡" }, { "yi", "抑" }, { "yi", "拸" }, { "yi", "挹" }, { "yi", "掜" }, { "yi", "揖" }, { "yi", "搤" },
			{ "yi", "敼" }, { "yi", "斁" }, { "yi", "旖" }, { "yi", "易" }, { "yi", "昳" }, { "yi", "晹" }, { "yi", "暆" }, { "yi", "曀" }, { "yi", "曵" },
			{ "yi", "杙" }, { "yi", "枍" }, { "yi", "枻" }, { "yi", "柂" }, { "yi", "栘" }, { "yi", "桋" }, { "yi", "椅" }, { "yi", "椸" }, { "yi", "槷" },
			{ "yi", "槸" }, { "yi", "檍" }, { "yi", "檥" }, { "yi", "檹" }, { "yi", "欥" }, { "yi", "歖" }, { "yi", "殔" }, { "yi", "殪" }, { "yi", "毅" },
			{ "yi", "毉" }, { "yi", "沂" }, { "yi", "沶" }, { "yi", "泆" }, { "yi", "洢" }, { "yi", "洩" }, { "yi", "浂" }, { "yi", "浥" }, { "yi", "溢" },
			{ "yi", "漪" }, { "yi", "潩" }, { "yi", "澺" }, { "yi", "瀷" }, { "yi", "焲" }, { "yi", "熈" }, { "yi", "熠" }, { "yi", "熤" }, { "yi", "熪" },
			{ "yi", "熼" }, { "yi", "燚" }, { "yi", "燡" }, { "yi", "燱" }, { "yi", "狋" }, { "yi", "猗" }, { "yi", "玴" }, { "yi", "珆" }, { "yi", "瑿" },
			{ "yi", "瓵" }, { "yi", "畩" }, { "yi", "異" }, { "yi", "疑" }, { "yi", "疫" }, { "yi", "痍" }, { "yi", "瘗" }, { "yi", "瘞" }, { "yi", "瘱" },
			{ "yi", "癔" }, { "yi", "益" }, { "yi", "眙" }, { "yi", "矣" }, { "yi", "礒" }, { "yi", "禕" }, { "yi", "移" }, { "yi", "稦" }, { "yi", "箷" },
			{ "yi", "簃" }, { "yi", "紲" }, { "yi", "絏" }, { "yi", "縊" }, { "yi", "繄" }, { "yi", "繶" }, { "yi", "繹" }, { "yi", "绎" }, { "yi", "缢" },
			{ "yi", "羛" }, { "yi", "羠" }, { "yi", "義" }, { "yi", "羿" }, { "yi", "翊" }, { "yi", "翌" }, { "yi", "翳" }, { "yi", "翼" }, { "yi", "耛" },
			{ "yi", "耴" }, { "yi", "肄" }, { "yi", "肊" }, { "yi", "胰" }, { "yi", "膉" }, { "yi", "臆" }, { "yi", "舣" }, { "yi", "艗" }, { "yi", "艤" },
			{ "yi", "艺" }, { "yi", "艾" }, { "yi", "芅" }, { "yi", "苅" }, { "yi", "苡" }, { "yi", "荑" }, { "yi", "萓" }, { "yi", "蓺" }, { "yi", "薏" },
			{ "yi", "藙" }, { "yi", "藝" }, { "yi", "蘙" }, { "yi", "蚁" }, { "yi", "蛇" }, { "yi", "蛜" }, { "yi", "蛦" }, { "yi", "蜴" }, { "yi", "螔" },
			{ "yi", "螘" }, { "yi", "蟻" }, { "yi", "衣" }, { "yi", "衪" }, { "yi", "衵" }, { "yi", "袘" }, { "yi", "裔" }, { "yi", "裛" }, { "yi", "褘" },
			{ "yi", "襼" }, { "yi", "觺" }, { "yi", "訑" }, { "yi", "訳" }, { "yi", "詍" }, { "yi", "詑" }, { "yi", "詒" }, { "yi", "詣" }, { "yi", "誃" },
			{ "yi", "誒" }, { "yi", "誼" }, { "yi", "謚" }, { "yi", "謻" }, { "yi", "譯" }, { "yi", "議" }, { "yi", "譺" }, { "yi", "议" }, { "yi", "译" },
			{ "yi", "诒" }, { "yi", "诣" }, { "yi", "谊" }, { "yi", "豷" }, { "yi", "貤" }, { "yi", "貽" }, { "yi", "賹" }, { "yi", "贀" }, { "yi", "贻" },
			{ "yi", "跇" }, { "yi", "跠" }, { "yi", "踦" }, { "yi", "軼" }, { "yi", "輗" }, { "yi", "轙" }, { "yi", "轶" }, { "yi", "辷" }, { "yi", "迆" },
			{ "yi", "迤" }, { "yi", "迻" }, { "yi", "逸" }, { "yi", "遗" }, { "yi", "遺" }, { "yi", "邑" }, { "yi", "郼" }, { "yi", "酏" }, { "yi", "醫" },
			{ "yi", "醳" }, { "yi", "醷" }, { "yi", "釔" }, { "yi", "釴" }, { "yi", "釶" }, { "yi", "鉯" }, { "yi", "銕" }, { "yi", "銥" }, { "yi", "錡" },
			{ "yi", "鎰" }, { "yi", "鏔" }, { "yi", "鐿" }, { "yi", "钀" }, { "yi", "钇" }, { "yi", "铱" }, { "yi", "镒" }, { "yi", "镱" }, { "yi", "阣" },
			{ "yi", "陭" }, { "yi", "隿" }, { "yi", "霬" }, { "yi", "靉" }, { "yi", "靾" }, { "yi", "頤" }, { "yi", "顊" }, { "yi", "顗" }, { "yi", "颐" },
			{ "yi", "飴" }, { "yi", "饐" }, { "yi", "饴" }, { "yi", "駅" }, { "yi", "驛" }, { "yi", "驿" }, { "yi", "鮨" }, { "yi", "鯣" }, { "yi", "鳦" },
			{ "yi", "鶂" }, { "yi", "鷁" }, { "yi", "鷊" }, { "yi", "鷖" }, { "yi", "鷾" }, { "yi", "鸃" }, { "yi", "黓" }, { "yi", "黟" }, { "yi", "黳" },
			{ "yi", "齮" }, { "yi", "齸" } };
};
