package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN35 {
	public static String[][] pl = { { "pai shou", "拍手" }, { "pai shui", "排水" }, { "pai song", "派送" }, { "pai tou", "派头" }, { "pai tou bing", "排头兵" },
			{ "pai tuo", "拍拖" }, { "pai wai", "排外" }, { "pai wan", "拍完" }, { "pai wang", "派往" }, { "pai wei", "排位" }, { "pai wu", "排污" }, { "pai xi", "拍戏" },
			{ "pai xi", "派系" }, { "pai xia", "拍下" }, { "pai xian", "排线" }, { "pai xie", "排泄" }, { "pai xu", "排序" }, { "pai you jie nan", "排忧解难" },
			{ "pai yuan", "派员" }, { "pai zai", "排在" }, { "pai zhang", "排长" }, { "pai zhao", "拍照" }, { "pai zhao", "牌照" }, { "pai zhao pian", "拍照片" },
			{ "pai zhao shou ji", "拍照手机" }, { "pai zhe", "拍着" }, { "pai zhe", "排着" }, { "pai zhu", "派驻" }, { "pai zhuan", "拍砖" }, { "pai zi", "拍子" },
			{ "pai zi", "牌子" }, { "pan", "丬" }, { "pan", "判" }, { "pan", "叛" }, { "pan", "坢" }, { "pan", "媻" }, { "pan", "幋" }, { "pan", "拚" }, { "pan", "攀" },
			{ "pan", "槃" }, { "pan", "沜" }, { "pan", "泮" }, { "pan", "溿" }, { "pan", "潘" }, { "pan", "瀊" }, { "pan", "爿" }, { "pan", "牉" }, { "pan", "牓" },
			{ "pan", "畔" }, { "pan", "番" }, { "pan", "盘" }, { "pan", "盤" }, { "pan", "盼" }, { "pan", "眅" }, { "pan", "碆" }, { "pan", "磐" }, { "pan", "磻" },
			{ "pan", "籓" }, { "pan", "縏" }, { "pan", "胖" }, { "pan", "蒰" }, { "pan", "蟠" }, { "pan", "袢" }, { "pan", "褩" }, { "pan", "襻" }, { "pan", "詊" },
			{ "pan", "跘" }, { "pan", "蹒" }, { "pan", "蹣" }, { "pan", "鞶" }, { "pan", "頖" }, { "pan bi", "攀比" }, { "pan bian", "叛变" }, { "pan bie", "判别" },
			{ "pan chu", "判处" }, { "pan deng", "攀登" }, { "pan dian", "盘点" }, { "pan ding", "判定" }, { "pan duan", "判断" }, { "pan duan li", "判断力" },
			{ "pan fa", "判罚" }, { "pan fu", "盘符" }, { "pan gang", "攀钢" }, { "pan gu", "盘古" }, { "pan huo", "盘活" }, { "pan ji wen", "潘基文" },
			{ "pan jin", "盘锦" }, { "pan jin lian", "潘金莲" }, { "pan ju", "盘踞" }, { "pan jue", "判决" }, { "pan jue shu", "判决书" }, { "pan jun", "叛军" },
			{ "pan kou", "盘口" }, { "pan li", "盘里" }, { "pan luan", "叛乱" }, { "pan mian", "盘面" }, { "pan ni", "叛逆" }, { "pan pa", "攀爬" }, { "pan pan", "盼盼" },
			{ "pan pian", "盘片" }, { "pan shan", "蹒跚" }, { "pan shang", "攀上" }, { "pan shang", "盘上" }, { "pan sheng", "攀升" }, { "pan shi", "磐石" },
			{ "pan shi yi", "潘石屹" }, { "pan suan", "盘算" }, { "pan tou", "盼头" }, { "pan tu", "叛徒" }, { "pan wang", "盼望" }, { "pan wei bo", "潘玮柏" },
			{ "pan wen", "盘问" }, { "pan xing", "判刑" }, { "pan xuan", "盘旋" }, { "pan yan", "攀岩" }, { "pan yu", "番禺" }, { "pan yu qu", "番禺区" },
			{ "pan zhe", "盼着" }, { "pan zheng", "盘整" }, { "pan zhi hua", "攀枝花" }, { "pan zhong", "盘中" }, { "pan zi", "盘子" }, { "pang", "乓" }, { "pang", "嗙" },
			{ "pang", "夆" }, { "pang", "尨" }, { "pang", "庞" }, { "pang", "彷" }, { "pang", "徬" }, { "pang", "旁" }, { "pang", "汸" }, { "pang", "滂" },
			{ "pang", "磅" }, { "pang", "耪" }, { "pang", "胖" }, { "pang", "膀" }, { "pang", "舽" }, { "pang", "螃" }, { "pang", "逄" }, { "pang", "雱" },
			{ "pang", "龐" }, { "pang bai", "旁白" }, { "pang bian", "旁边" }, { "pang da", "庞大" }, { "pang guan", "旁观" }, { "pang guan zhe", "旁观者" },
			{ "pang guang", "膀胱" }, { "pang huang", "彷徨" }, { "pang pang", "胖胖" }, { "pang ren", "旁人" }, { "pang ting", "旁听" }, { "pang xie", "螃蟹" },
			{ "pang zi", "胖子" }, { "pao", "刨" }, { "pao", "匏" }, { "pao", "咆" }, { "pao", "嚗" }, { "pao", "垉" }, { "pao", "奅" }, { "pao", "庖" },
			{ "pao", "抛" }, { "pao", "拋" }, { "pao", "泡" }, { "pao", "炮" }, { "pao", "炰" }, { "pao", "狍" }, { "pao", "瓟" }, { "pao", "疱" }, { "pao", "皰" },
			{ "pao", "砲" }, { "pao", "穮" }, { "pao", "脟" }, { "pao", "脬" }, { "pao", "萢" }, { "pao", "蚫" }, { "pao", "袌" }, { "pao", "袍" }, { "pao", "褜" },
			{ "pao", "跑" }, { "pao", "鉋" }, { "pao", "鞄" }, { "pao", "颮" }, { "pao", "麃" }, { "pao", "麭" }, { "pao ba", "泡吧" }, { "pao bian", "跑遍" },
			{ "pao bing", "炮兵" }, { "pao bu", "跑步" }, { "pao bu ji", "跑步机" }, { "pao cai", "泡菜" }, { "pao cha", "泡茶" }, { "pao che", "跑车" },
			{ "pao chu", "抛出" }, { "pao chu", "跑出" }, { "pao chu qu", "跑出去" }, { "pao dan", "炮弹" }, { "pao dao", "跑到" }, { "pao dao", "跑道" },
			{ "pao de", "跑得" }, { "pao de kuai", "跑得快" }, { "pao diao", "抛掉" }, { "pao diao", "跑掉" }, { "pao dong", "跑动" }, { "pao guang", "抛光" },
			{ "pao guo", "跑过" }, { "pao hong", "炮轰" }, { "pao hui", "炮灰" }, { "pao hui", "跑回" }, { "pao huo", "炮火" }, { "pao jin", "跑进" }, { "pao kai", "抛开" },
			{ "pao kai", "跑开" }, { "pao lai", "跑来" }, { "pao le", "泡了" }, { "pao le", "跑了" }, { "pao lu", "跑路" }, { "pao ma", "跑马" }, { "pao mian", "泡面" },
			{ "pao mo", "泡沫" }, { "pao niu", "泡妞" }, { "pao pan", "抛盘" }, { "pao pao", "泡泡" }, { "pao pao", "跑跑" }, { "pao pao tang", "泡泡堂" },
			{ "pao qi", "抛弃" }, { "pao qu", "跑去" }, { "pao shang", "跑上" }, { "pao shang", "跑商" }, { "pao shou", "抛售" }, { "pao tai", "炮台" },
			{ "pao tang", "泡汤" }, { "pao ti", "跑题" }, { "pao tui", "跑腿" }, { "pao wan", "跑完" }, { "pao wei", "跑位" }, { "pao xia", "抛下" }, { "pao xiao", "咆哮" },
			{ "pao xie", "跑鞋" }, { "pao ya", "抛压" }, { "pao zai", "抛在" }, { "pao zai", "泡在" }, { "pao zao", "泡澡" }, { "pao zhe", "跑着" }, { "pao zhen", "疱疹" },
			{ "pao zhi", "炮制" }, { "pao zhuan yin yu", "抛砖引玉" }, { "pao zi", "袍子" }, { "pei", "伂" }, { "pei", "佩" }, { "pei", "俖" }, { "pei", "呸" },
			{ "pei", "培" }, { "pei", "姵" }, { "pei", "帔" }, { "pei", "怌" }, { "pei", "旆" }, { "pei", "柸" }, { "pei", "毰" }, { "pei", "沛" }, { "pei", "浿" },
			{ "pei", "珮" }, { "pei", "琣" }, { "pei", "胚" }, { "pei", "茷" }, { "pei", "蓜" }, { "pei", "衃" }, { "pei", "裴" }, { "pei", "裵" }, { "pei", "賠" },
			{ "pei", "赔" }, { "pei", "轡" }, { "pei", "辔" }, { "pei", "配" }, { "pei", "醅" }, { "pei", "锫" }, { "pei", "陪" }, { "pei", "陫" }, { "pei", "霈" },
			{ "pei ban", "陪伴" }, { "pei bei", "配备" }, { "pei ben", "赔本" }, { "pei bi", "配比" }, { "pei bu shang", "配不上" }, { "pei chang", "赔偿" },
			{ "pei chang jin", "赔偿金" }, { "pei chang ze ren", "赔偿责任" }, { "pei chen", "陪衬" }, { "pei dai", "佩带" }, { "pei dai", "佩戴" }, { "pei dian", "配电" },
			{ "pei dui", "配对" }, { "pei e", "配额" }, { "pei fa", "配发" }, { "pei fang", "配方" }, { "pei fu", "佩服" }, { "pei fu", "赔付" }, { "pei gen", "培根" },
			{ "pei gu", "配股" }, { "pei he", "配合" }, { "pei jian", "配件" }, { "pei jue", "配角" }, { "pei kuan", "赔款" }, { "pei le", "赔了" },
			{ "pei li dao qian", "赔礼道歉" }, { "pei lian", "陪练" }, { "pei liao", "配料" }, { "pei lv", "赔率" }, { "pei ni", "陪你" }, { "pei ou", "配偶" },
			{ "pei pei", "陪陪" }, { "pei qian", "赔钱" }, { "pei se", "配色" }, { "pei shang", "配上" }, { "pei shen tuan", "陪审团" }, { "pei shi", "配饰" },
			{ "pei shou", "配售" }, { "pei song", "配送" }, { "pei song zhong xin", "配送中心" }, { "pei ta", "陪他" }, { "pei ta", "陪她" }, { "pei tai", "胚胎" },
			{ "pei tao", "配套" }, { "pei tao she shi", "配套设施" }, { "pei tong", "陪同" }, { "pei wo", "陪我" }, { "pei wu", "配伍" }, { "pei xun", "培训" },
			{ "pei xun ban", "培训班" }, { "pei xun fei", "培训费" }, { "pei xun gong zuo", "培训工作" }, { "pei xun ji di", "培训基地" }, { "pei xun ji gou", "培训机构" },
			{ "pei xun ji hua", "培训计划" }, { "pei xun ke cheng", "培训课程" }, { "pei xun shi", "培训师" }, { "pei xun xue xiao", "培训学校" },
			{ "pei xun zhong xin", "培训中心" }, { "pei yang", "培养" }, { "pei yang chu", "培养出" }, { "pei yang hai zi", "培养孩子" }, { "pei yang ji", "培养基" },
			{ "pei yang ren cai", "培养人才" }, { "pei yang xue sheng", "培养学生" }, { "pei yi", "配以" }, { "pei yin", "配音" }, { "pei yong jun", "裴勇俊" },
			{ "pei you", "配有" }, { "pei yu", "培育" }, { "pei yu chu", "培育出" }, { "pei yue", "配乐" }, { "pei zhe", "陪着" }, { "pei zhe ni", "陪着你" },
			{ "pei zhe wo", "陪着我" }, { "pei zhi", "培植" }, { "pei zhi", "配制" }, { "pei zhi", "配置" }, { "pei zhi wen jian", "配置文件" }, { "pei zhong", "配种" },
			{ "pen", "呠" }, { "pen", "喷" }, { "pen", "噴" }, { "pen", "歕" }, { "pen", "湓" }, { "pen", "盆" }, { "pen", "翉" }, { "pen", "翸" }, { "pen", "葐" },
			{ "pen", "衯" }, { "pen chu", "喷出" }, { "pen di", "盆地" }, { "pen hui", "喷绘" }, { "pen huo", "喷火" }, { "pen jing", "盆景" }, { "pen li", "盆里" },
			{ "pen mo", "喷墨" }, { "pen qi", "喷漆" }, { "pen qiang", "盆腔" }, { "pen quan", "喷泉" }, { "pen sa", "喷洒" }, { "pen she", "喷射" }, { "pen shui", "喷水" },
			{ "pen ti", "喷嚏" }, { "pen tou", "喷头" }, { "pen tu", "喷涂" }, { "pen wu", "喷雾" }, { "pen xue", "喷血" }, { "pen zai", "盆栽" }, { "pen zi", "盆子" },
			{ "pen zui", "喷嘴" }, { "peng", "傰" }, { "peng", "剻" }, { "peng", "匉" }, { "peng", "嘭" }, { "peng", "堋" }, { "peng", "弸" }, { "peng", "彭" },
			{ "peng", "怦" }, { "peng", "恲" }, { "peng", "憉" }, { "peng", "抨" }, { "peng", "捧" }, { "peng", "掽" }, { "peng", "搒" }, { "peng", "摓" },
			{ "peng", "朋" }, { "peng", "棚" }, { "peng", "椪" }, { "peng", "樥" }, { "peng", "漰" }, { "peng", "澎" }, { "peng", "烹" }, { "peng", "熢" },
			{ "peng", "痭" }, { "peng", "皏" }, { "peng", "砰" }, { "peng", "硼" }, { "peng", "碰" }, { "peng", "磞" }, { "peng", "篣" }, { "peng", "篷" },
			{ "peng", "絣" }, { "peng", "膨" }, { "peng", "芃" }, { "peng", "蓬" }, { "peng", "蟛" }, { "peng", "踫" }, { "peng", "軯" }, { "peng", "輣" },
			{ "peng", "錋" }, { "peng", "鑝" }, { "peng", "閛" }, { "peng", "韸" }, { "peng", "駍" }, { "peng", "髼" }, { "peng", "鬅" }, { "peng", "鵬" },
			{ "peng", "鹏" }, { "peng bi", "碰壁" }, { "peng bo", "蓬勃" }, { "peng bo fa zhan", "蓬勃发展" }, { "peng chang", "捧场" }, { "peng chu", "碰触" },
			{ "peng dao", "碰到" }, { "peng de huai", "彭德怀" }, { "peng fei", "鹏飞" }, { "peng guo", "碰过" }, { "peng hu qu", "棚户区" }, { "peng hua", "鹏华" },
			{ "peng ji", "抨击" }, { "peng jian", "碰见" }, { "peng ke", "朋克" }, { "peng lai", "蓬莱" }, { "peng le", "碰了" }, { "peng mian", "碰面" },
			{ "peng pai", "澎湃" }, { "peng peng", "碰碰" }, { "peng qi", "捧起" }, { "peng qiao", "碰巧" }, { "peng ren", "烹饪" }, { "peng shang", "碰上" },
			{ "peng song", "蓬松" }, { "peng tiao", "烹调" }, { "peng tou", "碰头" }, { "peng you", "朋友" }, { "peng you yi qi", "朋友一起" },
			{ "peng you zhi jian", "朋友之间" }, { "peng yu", "彭宇" }, { "peng zhang", "膨胀" }, { "peng zhe", "捧着" }, { "peng zhi", "烹制" }, { "peng zhuang", "碰撞" },
			{ "pi", "丕" }, { "pi", "仳" }, { "pi", "伓" }, { "pi", "伾" }, { "pi", "僻" }, { "pi", "劈" }, { "pi", "匹" }, { "pi", "否" }, { "pi", "啤" },
			{ "pi", "噼" }, { "pi", "嚭" }, { "pi", "圮" }, { "pi", "坯" }, { "pi", "埤" }, { "pi", "媲" }, { "pi", "屁" }, { "pi", "岯" }, { "pi", "崥" },
			{ "pi", "庀" }, { "pi", "憵" }, { "pi", "批" }, { "pi", "披" }, { "pi", "揊" }, { "pi", "枇" }, { "pi", "毗" }, { "pi", "毘" }, { "pi", "毞" },
			{ "pi", "淠" }, { "pi", "澼" }, { "pi", "狉" }, { "pi", "猈" }, { "pi", "琵" }, { "pi", "甓" }, { "pi", "疋" }, { "pi", "疲" }, { "pi", "痞" },
			{ "pi", "癖" }, { "pi", "皮" }, { "pi", "睥" }, { "pi", "砒" }, { "pi", "礔" }, { "pi", "秠" }, { "pi", "稫" }, { "pi", "笓" }, { "pi", "箆" },
			{ "pi", "粃" }, { "pi", "紕" }, { "pi", "纰" }, { "pi", "罴" }, { "pi", "羆" }, { "pi", "脾" }, { "pi", "膍" }, { "pi", "蚍" }, { "pi", "蚽" },
			{ "pi", "蚾" }, { "pi", "蜱" }, { "pi", "螷" }, { "pi", "蠯" }, { "pi", "裨" }, { "pi", "諀" }, { "pi", "譬" }, { "pi", "豼" }, { "pi", "貔" },
			{ "pi", "辟" }, { "pi", "邳" }, { "pi", "郫" }, { "pi", "鈚" }, { "pi", "鈲" }, { "pi", "鈹" }, { "pi", "銔" }, { "pi", "銢" }, { "pi", "錍" },
			{ "pi", "鎞" }, { "pi", "铍" }, { "pi", "闢" }, { "pi", "阰" }, { "pi", "陂" }, { "pi", "陴" }, { "pi", "霹" }, { "pi", "駓" }, { "pi", "髬" },
			{ "pi", "魾" }, { "pi", "鴄" }, { "pi", "鵧" }, { "pi", "鷿" }, { "pi", "鼙" }, { "pi bao", "皮包" }, { "pi bei", "疲惫" }, { "pi bei bu kan", "疲惫不堪" },
			{ "pi bo", "批驳" }, { "pi cao", "皮草" }, { "pi chu li", "批处理" }, { "pi ci", "批次" }, { "pi dai", "皮带" }, { "pi dan", "皮蛋" }, { "pi di", "匹敌" },
			{ "pi dou", "批斗" }, { "pi er luo", "皮尔洛" }, { "pi er si", "皮尔斯" }, { "pi fa", "批发" }, { "pi fa", "疲乏" }, { "pi fa jia", "批发价" },
			{ "pi fa ling shou", "批发零售" }, { "pi fa shang", "批发商" }, { "pi fa shi chang", "批发市场" }, { "pi feng", "披风" }, { "pi fu", "批复" }, { "pi fu", "皮肤" },
			{ "pi fu bing", "皮肤病" }, { "pi fu gan zao", "皮肤干燥" }, { "pi fu guo min", "皮肤过敏" }, { "pi fu ke", "皮肤科" }, { "pi gai", "批改" }, { "pi ge", "皮革" },
			{ "pi gu", "屁股" }, { "pi hao", "批号" }, { "pi hao", "癖好" }, { "pi hua", "屁话" }, { "pi jia", "皮夹" }, { "pi jian", "披肩" }, { "pi jiu", "啤酒" },
			{ "pi jiu jie", "啤酒节" }, { "pi ju", "皮具" }, { "pi juan", "疲倦" }, { "pi ka", "皮卡" }, { "pi lao", "疲劳" }, { "pi li", "霹雳" },
			{ "pi li pa la", "噼里啪啦" }, { "pi liang", "批量" }, { "pi liang sheng chan", "批量生产" }, { "pi lin", "毗邻" }, { "pi lu", "披露" }, { "pi ma", "匹马" },
			{ "pi mao", "皮毛" }, { "pi mei", "媲美" }, { "pi pa", "枇杷" }, { "pi pa", "琵琶" }, { "pi pan", "批判" }, { "pi pei", "匹配" }, { "pi pi", "屁屁" },
			{ "pi pi", "皮皮" }, { "pi ping", "批评" }, { "pi ping jia", "批评家" }, { "pi qi", "脾气" }, { "pi qiu", "皮球" }, { "pi rou", "皮肉" }, { "pi ru", "譬如" },
			{ "pi ruan", "疲软" }, { "pi ruo", "疲弱" }, { "pi sa", "批萨" }, { "pi shang", "披上" }, { "pi shi", "屁事" }, { "pi shi", "批示" }, { "pi shuang", "砒霜" },
			{ "pi tao", "皮套" }, { "pi te", "皮特" }, { "pi tui", "劈腿" }, { "pi wei", "脾胃" }, { "pi wen", "批文" }, { "pi xia", "皮下" }, { "pi xia zu zhi", "皮下组织" },
			{ "pi xie", "皮鞋" }, { "pi xiu", "貔貅" }, { "pi yan", "屁眼" }, { "pi yan", "皮炎" }, { "pi yao", "辟谣" }, { "pi ye luo", "皮耶罗" }, { "pi yi", "皮衣" },
			{ "pi yong", "屁用" }, { "pi zhe", "披着" }, { "pi zhen", "皮疹" }, { "pi zhi", "皮脂" }, { "pi zhi", "皮质" }, { "pi zhi xian", "皮脂腺" }, { "pi zhu", "批注" },
			{ "pi zhun", "批准" }, { "pi zi", "痞子" }, { "pian", "便" }, { "pian", "偏" }, { "pian", "媥" }, { "pian", "扁" }, { "pian", "楄" }, { "pian", "楩" },
			{ "pian", "片" }, { "pian", "犏" }, { "pian", "猵" }, { "pian", "璸" }, { "pian", "篇" }, { "pian", "緶" }, { "pian", "翩" }, { "pian", "胼" },
			{ "pian", "諚" }, { "pian", "諞" }, { "pian", "谝" }, { "pian", "貵" }, { "pian", "跰" }, { "pian", "蹁" }, { "pian", "駢" }, { "pian", "騈" },
			{ "pian", "騙" }, { "pian", "骈" }, { "pian", "骗" }, { "pian", "骿" }, { "pian", "鶣" }, { "pian ai", "偏爱" }, { "pian cha", "偏差" },
			{ "pian chang", "片场" }, { "pian chou", "片酬" }, { "pian chu", "偏出" }, { "pian da", "偏大" }, { "pian dao", "骗到" }, { "pian di", "偏低" },
			{ "pian duan", "片断" }, { "pian duan", "片段" }, { "pian fang", "偏方" }, { "pian fu", "篇幅" }, { "pian gao", "偏高" }, { "pian guo", "骗过" },
			{ "pian hao", "偏好" }, { "pian hua", "片花" }, { "pian ji", "偏激" }, { "pian jian", "偏见" }, { "pian ju", "骗局" }, { "pian ke", "片刻" },
			{ "pian le", "骗了" }, { "pian li", "偏离" }, { "pian mian", "片面" }, { "pian ming", "片名" }, { "pian ni", "骗你" }, { "pian pi", "偏僻" },
			{ "pian pian", "便便" }, { "pian pian", "偏偏" }, { "pian pian", "片片" }, { "pian pian", "翩翩" }, { "pian pian qi wu", "翩翩起舞" }, { "pian po", "偏颇" },
			{ "pian qian", "骗钱" }, { "pian qu", "片区" }, { "pian qu", "骗取" }, { "pian ren", "骗人" }, { "pian shao", "偏少" }, { "pian shu", "骗术" },
			{ "pian tan", "偏袒" }, { "pian tou", "片头" }, { "pian tou tong", "偏头痛" }, { "pian wei", "片尾" }, { "pian wei qu", "片尾曲" },
			{ "pian wen zhang", "篇文章" }, { "pian wo", "骗我" }, { "pian xiang", "偏向" }, { "pian xiao", "偏小" }, { "pian xin", "偏心" }, { "pian yao", "偏要" },
			{ "pian yi", "便宜" }, { "pian yi", "偏移" }, { "pian yi huo", "便宜货" }, { "pian yuan", "偏远" }, { "pian yuan", "片源" }, { "pian zhang", "篇章" },
			{ "pian zhi", "偏执" }, { "pian zhong", "偏重" }, { "pian zhong", "片中" }, { "pian zi", "片子" }, { "pian zi", "骗子" }, { "piao", "僄" }, { "piao", "剽" },
			{ "piao", "嘌" }, { "piao", "嫖" }, { "piao", "彯" }, { "piao", "慓" }, { "piao", "旚" }, { "piao", "朴" }, { "piao", "殍" }, { "piao", "漂" },
			{ "piao", "犥" }, { "piao", "瓢" }, { "piao", "皫" }, { "piao", "瞟" }, { "piao", "票" }, { "piao", "篻" }, { "piao", "縹" }, { "piao", "缥" },
			{ "piao", "翲" }, { "piao", "莩" }, { "piao", "蔈" }, { "piao", "薸" }, { "piao", "螵" }, { "piao", "謤" }, { "piao", "醥" }, { "piao", "顠" },
			{ "piao", "飃" }, { "piao", "飄" }, { "piao", "飘" }, { "piao", "驫" }, { "piao", "骠" }, { "piao", "髟" }, { "piao", "魒" }, { "piao bai", "漂白" },
			{ "piao bo", "漂泊" }, { "piao chang", "嫖娼" }, { "piao dang", "飘荡" }, { "piao fan zi", "票贩子" }, { "piao fang", "票房" }, { "piao fei", "飘飞" },
			{ "piao fu", "漂浮" }, { "piao fu", "飘浮" }, { "piao guo", "飘过" }, { "piao hong", "飘红" }, { "piao hu", "飘忽" }, { "piao ji", "嫖妓" },
			{ "piao jia", "票价" }, { "piao ju", "票据" }, { "piao ke", "嫖客" }, { "piao lai", "飘来" }, { "piao liang", "漂亮" }, { "piao liang nv ren", "漂亮女人" },
			{ "piao ling", "飘零" }, { "piao liu", "漂流" }, { "piao luo", "飘落" }, { "piao mian", "票面" }, { "piao miao", "缥缈" }, { "piao miao", "飘渺" },
			{ "piao piao", "漂漂" }, { "piao piao", "票票" }, { "piao piao", "飘飘" }, { "piao qie", "剽窃" }, { "piao ran", "飘然" }, { "piao san", "飘散" },
			{ "piao shu", "票数" }, { "piao wu", "票务" }, { "piao xiang", "飘香" }, { "piao xuan", "票选" }, { "piao yang", "飘扬" }, { "piao yao", "飘摇" },
			{ "piao yi", "漂移" }, { "piao yi", "飘逸" }, { "piao yun", "飘云" }, { "piao zhe", "飘着" }, { "piao zi", "票子" }, { "piao zou", "飘走" }, { "pie", "丿" },
			{ "pie", "嫳" }, { "pie", "撇" }, { "pie", "暼" }, { "pie", "氕" }, { "pie", "潎" }, { "pie", "瞥" }, { "pie", "苤" }, { "pie", "覕" },
			{ "pie jian", "瞥见" }, { "pie kai", "撇开" }, { "pin", "品" }, { "pin", "嚬" }, { "pin", "姘" }, { "pin", "嫔" }, { "pin", "嬪" }, { "pin", "拚" },
			{ "pin", "拼" }, { "pin", "榀" }, { "pin", "牝" }, { "pin", "玭" }, { "pin", "矉" }, { "pin", "砏" }, { "pin", "礗" }, { "pin", "聘" }, { "pin", "蘋" },
			{ "pin", "貧" }, { "pin", "贫" }, { "pin", "頻" }, { "pin", "顰" }, { "pin", "频" }, { "pin", "颦" }, { "pin", "驞" }, { "pin bo", "拼搏" },
			{ "pin cha", "品茶" }, { "pin chang", "品尝" }, { "pin che", "拼车" }, { "pin cou", "拼凑" }, { "pin dao", "频道" }, { "pin de", "品德" },
			{ "pin duan", "频段" }, { "pin fa", "贫乏" }, { "pin fa", "频发" }, { "pin fan", "频繁" }, { "pin fu", "贫富" }, { "pin fu cha ju", "贫富差距" },
			{ "pin ge", "品格" }, { "pin han", "贫寒" }, { "pin ji", "贫瘠" }, { "pin jie", "拼接" }, { "pin ku", "贫苦" }, { "pin kun", "贫困" },
			{ "pin kun di qu", "贫困地区" }, { "pin kun hu", "贫困户" }, { "pin kun jia ting", "贫困家庭" }, { "pin kun ren kou", "贫困人口" }, { "pin kun sheng", "贫困生" },
			{ "pin kun xian", "贫困县" }, { "pin kun xue sheng", "贫困学生" }, { "pin le", "拼了" }, { "pin lei", "品类" }, { "pin lv", "频率" }, { "pin min", "贫民" },
			{ "pin min ku", "贫民窟" }, { "pin ming", "品名" }, { "pin ming", "拼命" }, { "pin pai", "品牌" }, { "pin pai ji", "品牌机" }, { "pin pai jia zhi", "品牌价值" },
			{ "pin pai jian she", "品牌建设" }, { "pin pai xiao ying", "品牌效应" }, { "pin pai xing xiang", "品牌形象" }, { "pin pai zhan lue", "品牌战略" },
			{ "pin pin", "频频" }, { "pin pu", "频谱" }, { "pin qiang", "拼抢" }, { "pin qing", "聘请" }, { "pin qiong", "贫穷" }, { "pin ren", "聘任" },
			{ "pin sha", "拼杀" }, { "pin si", "拼死" }, { "pin tu", "拼图" }, { "pin wei", "品位" }, { "pin wei", "品味" }, { "pin wei", "聘为" }, { "pin xie", "拼写" },
			{ "pin xing", "品性" }, { "pin xing", "品行" }, { "pin xue", "贫血" }, { "pin yin", "拼音" }, { "pin yong", "聘用" }, { "pin zhi", "品质" },
			{ "pin zhong", "品种" }, { "pin zhuang", "拼装" }, { "pin zui", "贫嘴" }, { "ping", "乒" }, { "ping", "俜" }, { "ping", "倗" }, { "ping", "凭" },
			{ "ping", "呯" }, { "ping", "坪" }, { "ping", "塀" }, { "ping", "娉" }, { "ping", "屏" }, { "ping", "屛" }, { "ping", "岼" }, { "ping", "帡" },
			{ "ping", "平" }, { "ping", "憑" }, { "ping", "枰" }, { "ping", "泙" }, { "ping", "洴" }, { "ping", "涄" }, { "ping", "淜" }, { "ping", "玶" },
			{ "ping", "瓶" }, { "ping", "甁" }, { "ping", "甹" }, { "ping", "砯" }, { "ping", "竮" }, { "ping", "缾" }, { "ping", "艵" }, { "ping", "苹" },
			{ "ping", "荓" }, { "ping", "萍" }, { "ping", "蓱" }, { "ping", "蛢" }, { "ping", "評" }, { "ping", "评" }, { "ping", "軿" }, { "ping", "輧" },
			{ "ping", "郱" }, { "ping", "鉼" }, { "ping", "頩" }, { "ping", "鮃" }, { "ping", "鲆" }, { "ping an", "平安" }, { "ping an ye", "平安夜" },
			{ "ping ban", "平板" }, { "ping ban dian shi", "平板电视" }, { "ping bao", "屏保" }, { "ping bi", "屏蔽" }, { "ping bi", "评比" }, { "ping biao", "评标" },
			{ "ping cang", "平仓" }, { "ping ce", "评测" }, { "ping chang", "平常" }, { "ping chang ren", "平常人" }, { "ping chang xin", "平常心" }, { "ping chu", "评出" },
			{ "ping dan", "平淡" }, { "ping deng", "平等" }, { "ping di", "平地" }, { "ping dian", "评点" }, { "ping ding", "平定" }, { "ping ding", "评定" },
			{ "ping ding shan", "平顶山" }, { "ping du", "平度" }, { "ping fan", "平凡" }, { "ping fan", "平反" }, { "ping fang", "平房" }, { "ping fang", "平方" },
			{ "ping fang gong li", "平方公里" }, { "ping fang mi", "平方米" }, { "ping fen", "平分" }, { "ping fen", "评分" }, { "ping feng", "屏风" }, { "ping fu", "平复" },
			{ "ping gai", "瓶盖" }, { "ping gu", "平谷" }, { "ping gu", "评估" }, { "ping gu bao gao", "评估报告" }, { "ping guo", "苹果" },
			{ "ping guo dian nao", "苹果电脑" }, { "ping guo gong si", "苹果公司" }, { "ping he", "平和" }, { "ping heng", "平衡" }, { "ping heng dian", "平衡点" },
			{ "ping hu", "平湖" }, { "ping hua", "平滑" }, { "ping hua ji", "平滑肌" }, { "ping huan", "平缓" }, { "ping ji", "评级" }, { "ping jia", "平价" },
			{ "ping jia", "评价" }, { "ping jia biao zhun", "评价标准" }, { "ping jia ti xi", "评价体系" }, { "ping jiang", "评奖" }, { "ping jie", "凭借" } };
};
