package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN42 {
	public static String[][] pl = { { "sheng qi shi", "圣骑士" }, { "sheng qian", "升迁" }, { "sheng qian", "生前" }, { "sheng qian", "省钱" }, { "sheng qing", "盛情" },
			{ "sheng qu", "省区" }, { "sheng qu", "省去" }, { "sheng ren", "升任" }, { "sheng ren", "圣人" }, { "sheng ren", "生人" }, { "sheng ren", "胜任" },
			{ "sheng ren da", "省人大" }, { "sheng ren shi ting", "省人事厅" }, { "sheng ri", "生日" }, { "sheng ri kuai le", "生日快乐" }, { "sheng ri li wu", "生日礼物" },
			{ "sheng ru", "升入" }, { "sheng se", "声色" }, { "sheng sheng", "声声" }, { "sheng sheng", "生生" }, { "sheng sheng", "省省" },
			{ "sheng sheng bu xi", "生生不息" }, { "sheng shi", "升势" }, { "sheng shi", "声势" }, { "sheng shi", "盛世" }, { "sheng shi", "盛事" }, { "sheng shi", "省事" },
			{ "sheng shi", "省市" }, { "sheng shi", "省时" }, { "sheng shi hao da", "声势浩大" }, { "sheng shu", "生疏" }, { "sheng shu", "省属" }, { "sheng si", "生死" },
			{ "sheng si li jie", "声嘶力竭" }, { "sheng su", "胜诉" }, { "sheng suan", "胜算" }, { "sheng suo", "绳索" }, { "sheng tai", "生态" },
			{ "sheng tai bao hu", "生态保护" }, { "sheng tai huan jing", "生态环境" }, { "sheng tai jian she", "生态建设" }, { "sheng tai lv you", "生态旅游" },
			{ "sheng tai nong ye", "生态农业" }, { "sheng tai wen ming", "生态文明" }, { "sheng tai xi tong", "生态系统" }, { "sheng tai xue", "生态学" },
			{ "sheng tang", "盛唐" }, { "sheng tao", "声讨" }, { "sheng teng", "升腾" }, { "sheng tian", "升天" }, { "sheng ting", "省厅" }, { "sheng wai", "省外" },
			{ "sheng wang", "声望" }, { "sheng wei", "升为" }, { "sheng wei", "省委" }, { "sheng wei chang wei", "省委常委" }, { "sheng wei sheng ting", "省卫生厅" },
			{ "sheng wei shu ji", "省委书记" }, { "sheng wen", "升温" }, { "sheng wu", "生物" }, { "sheng wu chai you", "生物柴油" }, { "sheng wu gong cheng", "生物工程" },
			{ "sheng wu hua xue", "生物化学" }, { "sheng wu ji shu", "生物技术" }, { "sheng wu xue", "生物学" }, { "sheng wu yi yao", "生物医药" }, { "sheng wu zhi", "生物质" },
			{ "sheng wu zhong", "生物钟" }, { "sheng xi", "升息" }, { "sheng xi", "生息" }, { "sheng xi luo", "圣西罗" }, { "sheng xia", "剩下" }, { "sheng xia", "生下" },
			{ "sheng xia", "盛夏" }, { "sheng xia", "省下" }, { "sheng xia lai", "生下来" }, { "sheng xian", "圣贤" }, { "sheng xian", "声线" }, { "sheng xiang", "声响" },
			{ "sheng xiao", "生效" }, { "sheng xiao", "生肖" }, { "sheng xiao hai", "生小孩" }, { "sheng xin", "省心" }, { "sheng xing", "生性" }, { "sheng xing", "盛行" },
			{ "sheng xiu", "生锈" }, { "sheng xue", "升学" }, { "sheng xue", "声学" }, { "sheng xue lv", "升学率" }, { "sheng ya", "生涯" }, { "sheng yan", "盛宴" },
			{ "sheng yi", "生意" }, { "sheng yi ren", "生意人" }, { "sheng yin", "声音" }, { "sheng ying", "生硬" }, { "sheng you", "声优" }, { "sheng you", "省油" },
			{ "sheng yu", "剩余" }, { "sheng yu", "声誉" }, { "sheng yu", "生于" }, { "sheng yu", "生育" }, { "sheng yu", "胜于" }, { "sheng yu bao xian", "生育保险" },
			{ "sheng yu jia zhi", "剩余价值" }, { "sheng yu si", "生与死" }, { "sheng yuan", "声援" }, { "sheng yuan", "生源" }, { "sheng yue", "声乐" },
			{ "sheng zai", "生在" }, { "sheng zan", "盛赞" }, { "sheng zhan", "圣战" }, { "sheng zhang", "生长" }, { "sheng zhang", "省长" },
			{ "sheng zhang fa yu", "生长发育" }, { "sheng zhang yin zi", "生长因子" }, { "sheng zhe", "生者" }, { "sheng zhe", "胜者" }, { "sheng zheng fu", "省政府" },
			{ "sheng zheng xie", "省政协" }, { "sheng zhi", "升值" }, { "sheng zhi", "升职" }, { "sheng zhi", "升至" }, { "sheng zhi", "圣旨" }, { "sheng zhi", "生殖" },
			{ "sheng zhi", "省直" }, { "sheng zhi jian kang", "生殖健康" }, { "sheng zhi qi", "生殖器" }, { "sheng zhong", "声中" }, { "sheng zhu", "生猪" },
			{ "sheng zhuang", "盛装" }, { "sheng zi", "生子" }, { "sheng zi", "绳子" }, { "shi", "世" }, { "shi", "丗" }, { "shi", "事" }, { "shi", "什" },
			{ "shi", "仕" }, { "shi", "似" }, { "shi", "使" }, { "shi", "侍" }, { "shi", "势" }, { "shi", "勢" }, { "shi", "匙" }, { "shi", "十" }, { "shi", "史" },
			{ "shi", "咶" }, { "shi", "嗜" }, { "shi", "嘘" }, { "shi", "噬" }, { "shi", "埘" }, { "shi", "塒" }, { "shi", "士" }, { "shi", "失" }, { "shi", "奭" },
			{ "shi", "始" }, { "shi", "实" }, { "shi", "実" }, { "shi", "室" }, { "shi", "寔" }, { "shi", "實" }, { "shi", "尸" }, { "shi", "屍" }, { "shi", "屎" },
			{ "shi", "峙" }, { "shi", "崼" }, { "shi", "市" }, { "shi", "师" }, { "shi", "師" }, { "shi", "式" }, { "shi", "弑" }, { "shi", "弒" }, { "shi", "忕" },
			{ "shi", "忯" }, { "shi", "恀" }, { "shi", "恃" }, { "shi", "拭" }, { "shi", "拾" }, { "shi", "揓" }, { "shi", "施" }, { "shi", "时" }, { "shi", "是" },
			{ "shi", "時" }, { "shi", "枾" }, { "shi", "柿" }, { "shi", "栻" }, { "shi", "榁" }, { "shi", "榯" }, { "shi", "殖" }, { "shi", "氏" }, { "shi", "湜" },
			{ "shi", "湤" }, { "shi", "湿" }, { "shi", "溡" }, { "shi", "溮" }, { "shi", "溼" }, { "shi", "澨" }, { "shi", "濕" }, { "shi", "炻" }, { "shi", "烒" },
			{ "shi", "狮" }, { "shi", "獅" }, { "shi", "矢" }, { "shi", "石" }, { "shi", "示" }, { "shi", "礻" }, { "shi", "祏" }, { "shi", "竍" }, { "shi", "笶" },
			{ "shi", "筮" }, { "shi", "篒" }, { "shi", "簭" }, { "shi", "絁" }, { "shi", "舐" }, { "shi", "莳" }, { "shi", "葹" }, { "shi", "蒔" }, { "shi", "蓍" },
			{ "shi", "虱" }, { "shi", "蚀" }, { "shi", "蝕" }, { "shi", "蝨" }, { "shi", "螫" }, { "shi", "褷" }, { "shi", "襫" }, { "shi", "襹" }, { "shi", "視" },
			{ "shi", "视" }, { "shi", "觢" }, { "shi", "試" }, { "shi", "詩" }, { "shi", "誓" }, { "shi", "諟" }, { "shi", "諡" }, { "shi", "識" }, { "shi", "识" },
			{ "shi", "试" }, { "shi", "诗" }, { "shi", "谥" }, { "shi", "豕" }, { "shi", "貰" }, { "shi", "贳" }, { "shi", "軾" }, { "shi", "轼" }, { "shi", "辻" },
			{ "shi", "适" }, { "shi", "逝" }, { "shi", "適" }, { "shi", "遰" }, { "shi", "遾" }, { "shi", "邿" }, { "shi", "酾" }, { "shi", "釃" }, { "shi", "釈" },
			{ "shi", "释" }, { "shi", "釋" }, { "shi", "鈰" }, { "shi", "鉽" }, { "shi", "鍉" }, { "shi", "鎩" }, { "shi", "铈" }, { "shi", "食" }, { "shi", "飭" },
			{ "shi", "飾" }, { "shi", "餝" }, { "shi", "饣" }, { "shi", "饰" }, { "shi", "駛" }, { "shi", "驶" }, { "shi", "鮖" }, { "shi", "鰣" }, { "shi", "鰤" },
			{ "shi", "鲥" }, { "shi", "鲺" }, { "shi", "鳲" }, { "shi", "鶳" }, { "shi", "鼫" }, { "shi", "鼭" }, { "shi a", "是啊" }, { "shi ai", "是爱" },
			{ "shi ai", "示爱" }, { "shi an", "是按" }, { "shi ba", "事吧" }, { "shi ba", "十八" }, { "shi ba", "是吧" }, { "shi ba", "是把" }, { "shi ba sui", "十八岁" },
			{ "shi ba tiao", "十八条" }, { "shi bai", "失败" }, { "shi bai zhe", "失败者" }, { "shi ban", "石板" }, { "shi ban gong bei", "事半功倍" }, { "shi bao", "时报" },
			{ "shi bei", "十倍" }, { "shi bei", "是被" }, { "shi bei", "石碑" }, { "shi bi", "势必" }, { "shi bi", "石壁" }, { "shi bian", "事变" }, { "shi bie", "识别" },
			{ "shi bing", "士兵" }, { "shi bo", "世博" }, { "shi bo hui", "世博会" }, { "shi bo qi", "示波器" }, { "shi bu", "是不" }, { "shi bu ke neng", "是不可能" },
			{ "shi bu shi", "时不时" }, { "shi bu shi", "是不是" }, { "shi cai", "时才" }, { "shi cai", "石材" }, { "shi ce", "史册" }, { "shi ce", "实测" },
			{ "shi ceng", "时曾" }, { "shi cha", "时差" }, { "shi cha", "视察" }, { "shi chang", "失常" }, { "shi chang", "市场" }, { "shi chang", "时常" },
			{ "shi chang", "时长" }, { "shi chang bu", "市场部" }, { "shi chang diao cha", "市场调查" }, { "shi chang diao yan", "市场调研" },
			{ "shi chang ding wei", "市场定位" }, { "shi chang fen e", "市场份额" }, { "shi chang fen xi", "市场分析" }, { "shi chang feng xian", "市场风险" },
			{ "shi chang gui mo", "市场规模" }, { "shi chang hang qing", "市场行情" }, { "shi chang hua", "市场化" }, { "shi chang huan jing", "市场环境" },
			{ "shi chang ji zhi", "市场机制" }, { "shi chang jia", "市场价" }, { "shi chang jia ge", "市场价格" }, { "shi chang jia zhi", "市场价值" },
			{ "shi chang jian guan", "市场监管" }, { "shi chang jiao yi", "市场交易" }, { "shi chang jing ji", "市场经济" }, { "shi chang jing zheng", "市场竞争" },
			{ "shi chang kai fa", "市场开发" }, { "shi chang kai tuo", "市场开拓" }, { "shi chang qian jing", "市场前景" }, { "shi chang qian li", "市场潜力" },
			{ "shi chang qing kuang", "市场情况" }, { "shi chang tui guang", "市场推广" }, { "shi chang xiao shou", "市场销售" }, { "shi chang xin xi", "市场信息" },
			{ "shi chang xu qiu", "市场需求" }, { "shi chang ying xiao", "市场营销" }, { "shi chang yun zuo", "市场运作" }, { "shi chang zhi xu", "市场秩序" },
			{ "shi chang zhu ti", "市场主体" }, { "shi chang zhun ru", "市场准入" }, { "shi chang zou shi", "市场走势" }, { "shi che", "试车" }, { "shi chen", "时辰" },
			{ "shi cheng", "时称" }, { "shi chu", "使出" }, { "shi chuan", "失传" }, { "shi chuan", "试穿" }, { "shi chuang", "视窗" }, { "shi ci", "十次" },
			{ "shi ci", "诗词" }, { "shi cong", "师从" }, { "shi cong", "是从" }, { "shi cuo", "是错" }, { "shi da", "十大" }, { "shi da", "师大" }, { "shi da", "是大" },
			{ "shi da fu", "士大夫" }, { "shi dai", "世代" }, { "shi dai", "时代" }, { "shi dai bei jing", "时代背景" }, { "shi dai guang chang", "时代广场" },
			{ "shi dai jing shen", "时代精神" }, { "shi dang", "适当" }, { "shi dao", "世道" }, { "shi dao", "食道" }, { "shi de", "似地" }, { "shi de", "似的" },
			{ "shi de", "使得" }, { "shi de", "实德" }, { "shi de", "师德" }, { "shi de", "识得" }, { "shi de qi fan", "适得其反" }, { "shi di", "失地" },
			{ "shi di", "实地" }, { "shi di", "师弟" }, { "shi di", "湿地" }, { "shi di nong min", "失地农民" }, { "shi dian", "十点" }, { "shi dian", "视点" },
			{ "shi dian", "试点" }, { "shi dian gong zuo", "试点工作" }, { "shi diao", "失掉" }, { "shi diao", "石雕" }, { "shi dou", "事都" }, { "shi dou", "时都" },
			{ "shi du", "湿度" }, { "shi du", "适度" }, { "shi duan", "事端" }, { "shi duan", "时段" }, { "shi dui", "是对" }, { "shi dui de", "是对的" },
			{ "shi duo", "十多" }, { "shi duo nian", "十多年" }, { "shi duo sui", "十多岁" }, { "shi er", "事儿" }, { "shi er", "十二" }, { "shi er", "时而" },
			{ "shi er bu jian", "视而不见" }, { "shi er dian", "十二点" }, { "shi er sheng xiao", "十二生肖" }, { "shi er sui", "十二岁" }, { "shi er tiao", "十二条" },
			{ "shi er xing zuo", "十二星座" }, { "shi er yue", "十二月" }, { "shi fa", "事发" }, { "shi fa", "始发" }, { "shi fa", "施法" }, { "shi fan", "师范" },
			{ "shi fan", "示范" }, { "shi fan cun", "示范村" }, { "shi fan da xue", "师范大学" }, { "shi fan dian", "示范点" }, { "shi fan gong cheng", "示范工程" },
			{ "shi fan ji di", "示范基地" }, { "shi fan qu", "示范区" }, { "shi fan xue yuan", "师范学院" }, { "shi fang", "十方" }, { "shi fang", "施放" },
			{ "shi fang", "释放" }, { "shi fei", "施肥" }, { "shi fei", "是非" }, { "shi fei", "试飞" }, { "shi fen", "十分" }, { "shi fen", "时分" },
			{ "shi fen zhi yi", "十分之一" }, { "shi fen zhong", "十分钟" }, { "shi fen zhong yao", "十分重要" }, { "shi feng", "适逢" }, { "shi fou", "是否" },
			{ "shi fou cun zai", "是否存在" }, { "shi fou fu he", "是否符合" }, { "shi fou neng gou", "是否能够" }, { "shi fou zheng que", "是否正确" }, { "shi fu", "市府" },
			{ "shi fu", "师傅" }, { "shi fu", "师父" }, { "shi gai", "是该" }, { "shi gan", "实干" }, { "shi gao", "石膏" }, { "shi ge", "十个" }, { "shi ge", "师哥" },
			{ "shi ge", "时隔" }, { "shi ge", "是个" }, { "shi ge", "诗歌" }, { "shi ge yue", "十个月" }, { "shi gei", "是给" }, { "shi gong", "施工" },
			{ "shi gong dan wei", "施工单位" }, { "shi gong dui", "施工队" }, { "shi gong ji shu", "施工技术" }, { "shi gong qi ye", "施工企业" },
			{ "shi gong ren yuan", "施工人员" }, { "shi gong shang ju", "市工商局" }, { "shi gong tu", "施工图" }, { "shi gong xian chang", "施工现场" }, { "shi gu", "世故" },
			{ "shi gu", "事故" }, { "shi gu", "尸骨" }, { "shi gu xian chang", "事故现场" }, { "shi guan", "事关" }, { "shi guan", "使馆" }, { "shi guan", "士官" },
			{ "shi guan", "试管" }, { "shi guan", "食管" }, { "shi guang", "时光" }, { "shi guo", "试过" }, { "shi guo", "驶过" }, { "shi hang", "世行" },
			{ "shi hao", "十号" }, { "shi hao", "嗜好" }, { "shi hao", "是好" }, { "shi he", "是何" }, { "shi he", "适合" }, { "shi he zi ji", "适合自己" },
			{ "shi he zuo", "适合做" }, { "shi hen", "是很" }, { "shi heng", "失衡" }, { "shi hou", "事后" }, { "shi hou", "时候" }, { "shi hu", "石斛" },
			{ "shi hua", "实话" }, { "shi hua", "市话" }, { "shi hua", "石化" }, { "shi hua shi shuo", "实话实说" }, { "shi huai", "是坏" }, { "shi huai", "释怀" },
			{ "shi huan", "使唤" }, { "shi hui", "实惠" }, { "shi hui", "时会" }, { "shi hui", "石灰" }, { "shi huo", "失火" }, { "shi ji", "世纪" }, { "shi ji", "事迹" },
			{ "shi ji", "十几" }, { "shi ji", "史记" }, { "shi ji", "实绩" }, { "shi ji", "实际" }, { "shi ji", "市级" }, { "shi ji", "时机" }, { "shi ji", "试剂" },
			{ "shi ji", "诗集" }, { "shi ji cao zuo", "实际操作" }, { "shi ji chu", "世纪初" }, { "shi ji chu fa", "实际出发" }, { "shi ji gong zuo", "实际工作" },
			{ "shi ji kong zhi", "实际控制" }, { "shi ji mo", "世纪末" }, { "shi ji qing kuang", "实际情况" }, { "shi ji shang", "实际上" }, { "shi ji wan", "十几万" },
			{ "shi ji wei", "市纪委" }, { "shi ji wen ti", "实际问题" }, { "shi ji xing dong", "实际行动" }, { "shi ji yi yi", "实际意义" }, { "shi ji ying yong", "实际应用" },
			{ "shi jia", "世家" }, { "shi jia", "十佳" }, { "shi jia", "市价" }, { "shi jia", "施加" }, { "shi jia", "是假" }, { "shi jia", "试驾" },
			{ "shi jia de", "是假的" }, { "shi jia mou ni", "释迦牟尼" }, { "shi jia zhuang", "石家庄" }, { "shi jia zhuang shi", "石家庄市" }, { "shi jia zu", "氏家族" },
			{ "shi jian", "世间" }, { "shi jian", "事件" }, { "shi jian", "始建" }, { "shi jian", "实践" }, { "shi jian", "尸检" }, { "shi jian", "时间" },
			{ "shi jian", "是件" }, { "shi jian an pai", "时间安排" }, { "shi jian bi jiao", "时间比较" }, { "shi jian biao", "时间表" }, { "shi jian cha", "时间差" },
			{ "shi jian chang", "时间长" }, { "shi jian duan", "时间段" }, { "shi jian duan", "时间短" }, { "shi jian fa sheng", "事件发生" },
			{ "shi jian huo dong", "实践活动" }, { "shi jian jian ge", "时间间隔" }, { "shi jian jing yan", "实践经验" }, { "shi jian li", "时间里" },
			{ "shi jian neng li", "实践能力" }, { "shi jian wei", "市建委" }, { "shi jian xian zhi", "时间限制" }, { "shi jian zheng ming", "实践证明" },
			{ "shi jian zui chang", "时间最长" }, { "shi jiang", "是将" }, { "shi jiao", "市郊" }, { "shi jiao", "视角" }, { "shi jiao wei", "市教委" },
			{ "shi jie", "世界" }, { "shi jie", "十届" }, { "shi jie", "师姐" }, { "shi jie", "时节" }, { "shi jie", "视界" }, { "shi jie bei", "世界杯" },
			{ "shi jie bei sai", "世界杯赛" }, { "shi jie da zhan", "世界大战" }, { "shi jie di yi", "世界第一" }, { "shi jie ding ji", "世界顶级" },
			{ "shi jie ge di", "世界各地" }, { "shi jie ge guo", "世界各国" }, { "shi jie guan", "世界观" }, { "shi jie guan jun", "世界冠军" },
			{ "shi jie he ping", "世界和平" }, { "shi jie ji", "世界级" }, { "shi jie ji lu", "世界纪录" }, { "shi jie jing ji", "世界经济" }, { "shi jie li", "世界里" },
			{ "shi jie mo ri", "世界末日" }, { "shi jie pai ming", "世界排名" }, { "shi jie shang zui", "世界上最" }, { "shi jie xing", "世界性" },
			{ "shi jie yi chan", "世界遗产" }, { "shi jie yi liu", "世界一流" }, { "shi jie yin hang", "世界银行" }, { "shi jie zhi chuang", "世界之窗" },
			{ "shi jie zhi ming", "世界知名" }, { "shi jie zhu ming", "世界著名" }, { "shi jie zui da", "世界最大" }, { "shi jin", "使劲" }, { "shi jin sai", "世锦赛" },
			{ "shi jing", "实景" }, { "shi jing", "市井" }, { "shi jing", "诗经" }, { "shi jing shan", "石景山" }, { "shi jiu", "十九" }, { "shi jiu", "时就" },
			{ "shi jiu ri", "十九日" }, { "shi jiu shi ji", "十九世纪" }, { "shi jiu sui", "十九岁" }, { "shi ju", "市局" }, { "shi ju", "诗句" }, { "shi juan", "试卷" },
			{ "shi jue", "视觉" }, { "shi jue chong ji", "视觉冲击" }, { "shi jue xiao guo", "视觉效果" }, { "shi kan", "是看" }, { "shi kan", "试看" }, { "shi kao", "是靠" },
			{ "shi ke", "时刻" }, { "shi ke", "时可" }, { "shi ke", "石刻" }, { "shi ke", "食客" }, { "shi ke biao", "时刻表" }, { "shi ke er zhi", "适可而止" },
			{ "shi kong", "失控" }, { "shi kong", "时空" }, { "shi kong de", "是空的" }, { "shi ku", "石窟" }, { "shi kuai", "十块" }, { "shi kuai", "石块" },
			{ "shi kuang", "实况" }, { "shi lai", "十来" }, { "shi lang", "侍郎" }, { "shi lao", "是老" }, { "shi le", "湿了" }, { "shi lei", "石磊" }, { "shi li", "事例" },
			{ "shi li", "事理" }, { "shi li", "势利" }, { "shi li", "势力" }, { "shi li", "十里" }, { "shi li", "失利" }, { "shi li", "失礼" }, { "shi li", "实例" },
			{ "shi li", "实力" }, { "shi li", "室里" }, { "shi li", "市里" }, { "shi li", "示例" }, { "shi li", "视力" }, { "shi li hua", "实例化" },
			{ "shi li pai", "实力派" }, { "shi li xiong hou", "实力雄厚" }, { "shi lian", "失恋" }, { "shi lian", "试炼" }, { "shi lian le", "失恋了" },
			{ "shi liang", "矢量" }, { "shi liang", "适量" }, { "shi liang", "食量" }, { "shi liao", "史料" }, { "shi liao", "石料" }, { "shi liao", "食疗" },
			{ "shi lin", "石林" }, { "shi ling", "失灵" }, { "shi ling", "适龄" }, { "shi ling dao", "市领导" }, { "shi liu", "十六" }, { "shi liu", "石榴" },
			{ "shi liu da", "十六大" }, { "shi liu jie", "十六届" }, { "shi liu sui", "十六岁" }, { "shi liu tiao", "十六条" }, { "shi lu", "实录" }, { "shi lu lu", "湿漉漉" },
			{ "shi lun", "试论" }, { "shi luo", "失落" }, { "shi luo de", "施罗德" }, { "shi ma", "是吗" }, { "shi mao", "世贸" }, { "shi mao", "时髦" },
			{ "shi mao zu zhi", "世贸组织" }, { "shi mei", "师妹" }, { "shi men", "师门" }, { "shi men", "石门" }, { "shi mi", "十米" }, { "shi mi si", "史密斯" },
			{ "shi mian", "世面" }, { "shi mian", "失眠" }, { "shi mian", "市面" }, { "shi mian mai fu", "十面埋伏" }, { "shi min", "市民" },
			{ "shi min zheng ju", "市民政局" }, { "shi ming", "使命" }, { "shi ming", "十名" }, { "shi ming", "失明" }, { "shi ming", "实名" }, { "shi ming gan", "使命感" },
			{ "shi ming zhi", "实名制" }, { "shi mo", "始末" }, { "shi mo", "石墨" }, { "shi mu", "实木" }, { "shi mu", "师母" }, { "shi mu di ban", "实木地板" },
			{ "shi mu yi dai", "拭目以待" }, { "shi nai de", "施耐德" }, { "shi nei", "室内" }, { "shi nei", "市内" }, { "shi nei kong qi", "室内空气" },
			{ "shi nei she ji", "室内设计" }, { "shi neng", "时能" }, { "shi ni", "使你" }, { "shi ni", "是你" }, { "shi nian", "十年" }, { "shi nian hou", "十年后" },
			{ "shi nian lai", "十年来" }, { "shi nian qian", "十年前" }, { "shi nin", "使您" }, { "shi nin", "是您" }, { "shi nv", "侍女" }, { "shi pai", "实拍" },
			{ "shi pan", "实盘" }, { "shi pei", "适配" }, { "shi pei qi", "适配器" }, { "shi pi fu", "使皮肤" }, { "shi pian", "诗篇" }, { "shi pin", "视频" },
			{ "shi pin", "食品" }, { "shi pin", "饰品" }, { "shi pin an quan", "食品安全" }, { "shi pin bo fang", "视频播放" }, { "shi pin ge shi", "视频格式" },
			{ "shi pin gong ye", "食品工业" }, { "shi pin hui yi", "视频会议" }, { "shi pin jia gong", "食品加工" }, { "shi pin jiao cheng", "视频教程" },
			{ "shi pin liao tian", "视频聊天" }, { "shi pin sheng chan", "食品生产" }, { "shi pin wang", "视频网" }, { "shi pin wei sheng", "食品卫生" },
			{ "shi pin wen jian", "视频文件" }, { "shi pin yao pin", "食品药品" }, { "shi ping", "时评" }, { "shi ping", "视屏" }, { "shi ping sai", "世乒赛" },
			{ "shi po", "识破" }, { "shi pu", "食谱" }, { "shi qi", "使其" }, { "shi qi", "十七" }, { "shi qi", "士气" }, { "shi qi", "拾起" }, { "shi qi", "时期" },
			{ "shi qi", "石器" }, { "shi qi da", "十七大" }, { "shi qi sui", "十七岁" }, { "shi qian", "事前" }, { "shi qian", "史前" }, { "shi qiang", "十强" },
			{ "shi qiao", "石桥" }, { "shi qie", "失窃" }, { "shi qing", "事情" }, { "shi qing", "实情" }, { "shi qing", "时请" }, { "shi qing hua yi", "诗情画意" },
			{ "shi qing sai", "世青赛" }, { "shi qiu", "失球" }, { "shi qu", "失去" }, { "shi qu", "市区" }, { "shi qu", "拾取" }, { "shi qu", "时区" }, { "shi qu", "逝去" },
			{ "shi quan", "实权" }, { "shi quan shi mei", "十全十美" }, { "shi que", "时却" }, { "shi ran", "使然" }, { "shi ran", "释然" }, { "shi rang", "是让" },
			{ "shi re", "湿热" }, { "shi ren", "世人" }, { "shi ren", "使人" }, { "shi ren", "十人" }, { "shi ren", "时任" }, { "shi ren", "是人" }, { "shi ren", "示人" },
			{ "shi ren", "诗人" }, { "shi ren da", "市人大" }, { "shi ri", "十日" }, { "shi ri", "时日" }, { "shi rong", "市容" }, { "shi ru", "驶入" },
			{ "shi run", "湿润" }, { "shi ruo", "示弱" }, { "shi san", "十三" }, { "shi san", "失散" }, { "shi san sui", "十三岁" }, { "shi san tiao", "十三条" },
			{ "shi se", "失色" }, { "shi sha", "是啥" }, { "shi shang", "世上" }, { "shi shang", "史上" }, { "shi shang", "时尚" }, { "shi shang za zhi", "时尚杂志" },
			{ "shi shang zui", "史上最" }, { "shi she", "施舍" }, { "shi she", "试射" }, { "shi shei", "是谁" }, { "shi shen", "失身" }, { "shi shen", "食神" },
			{ "shi sheng", "失声" }, { "shi sheng", "师生" }, { "shi shi", "世事" }, { "shi shi", "事事" }, { "shi shi", "事实" }, { "shi shi", "史实" },
			{ "shi shi", "史诗" }, { "shi shi", "失事" }, { "shi shi", "失实" }, { "shi shi", "实事" }, { "shi shi", "实施" }, { "shi shi", "实时" }, { "shi shi", "时事" },
			{ "shi shi", "时时" }, { "shi shi", "湿湿" }, { "shi shi", "石狮" }, { "shi shi", "试试" }, { "shi shi", "适时" }, { "shi shi", "逝世" },
			{ "shi shi ban fa", "实施办法" }, { "shi shi fang an", "实施方案" }, { "shi shi guo cheng", "实施过程" }, { "shi shi jian kong", "实时监控" },
			{ "shi shi jie shang", "是世界上" }, { "shi shi kan", "试试看" }, { "shi shi ke ke", "时时刻刻" }, { "shi shi qing kuang", "实施情况" },
			{ "shi shi qiu shi", "实事求是" }, { "shi shi xi ze", "实施细则" }, { "shi shi yi jian", "实施意见" }, { "shi shi zai zai", "实实在在" },
			{ "shi shi zheng ming", "事实证明" }, { "shi shou", "失守" }, { "shi shou", "失手" }, { "shi shou", "市售" }, { "shi shou", "是受" }, { "shi shu", "十数" },
			{ "shi shu", "史书" }, { "shi shu", "实属" }, { "shi shu", "市属" }, { "shi shui", "是谁" }, { "shi shui", "试水" }, { "shi shui zai", "是谁在" },
			{ "shi shuo", "时说" }, { "shi shuo", "是说" }, { "shi si", "十四" }, { "shi si", "誓死" }, { "shi si sui", "十四岁" }, { "shi su", "世俗" },
			{ "shi su", "时速" }, { "shi su", "食宿" }, { "shi sui", "十岁" }, { "shi ta", "使他" }, { "shi ta", "使它" }, { "shi ta", "是他" }, { "shi tai", "事态" },
			{ "shi tai", "失态" }, { "shi tai", "师太" }, { "shi tai", "时态" }, { "shi tan", "试探" }, { "shi tang", "食堂" }, { "shi tang", "食糖" }, { "shi ti", "事体" },
			{ "shi ti", "实体" }, { "shi ti", "尸体" }, { "shi ti", "试题" }, { "shi ti dian", "实体店" }, { "shi tian", "十天" }, { "shi tiao", "十条" },
			{ "shi tiao", "失调" }, { "shi ting", "视听" }, { "shi ting", "试听" }, { "shi tong", "视同" }, { "shi tou", "势头" }, { "shi tou", "湿透" },
			{ "shi tou", "石头" }, { "shi tu", "仕途" }, { "shi tu", "师徒" }, { "shi tu", "视图" }, { "shi tu", "试图" }, { "shi tuan", "师团" }, { "shi wai", "室外" },
			{ "shi wai tao yuan", "世外桃源" }, { "shi wan", "十万" }, { "shi wan", "试玩" }, { "shi wan yuan", "十万元" }, { "shi wang", "失望" },
			{ "shi wang mo", "视网膜" }, { "shi wei", "侍卫" }, { "shi wei", "十位" }, { "shi wei", "实为" }, { "shi wei", "市委" }, { "shi wei", "是为" },
			{ "shi wei", "是位" }, { "shi wei", "示威" }, { "shi wei", "视为" }, { "shi wei chang wei", "市委常委" }, { "shi wei sheng ju", "市卫生局" },
			{ "shi wei shu ji", "市委书记" }, { "shi wen", "室温" }, { "shi wen", "试问" }, { "shi wen", "诗文" }, { "shi wo", "使我" }, { "shi wo", "是我" },
			{ "shi wo de", "是我的" }, { "shi wu", "事务" }, { "shi wu", "事物" }, { "shi wu", "十五" }, { "shi wu", "失误" }, { "shi wu", "实务" }, { "shi wu", "实物" },
			{ "shi wu", "食物" }, { "shi wu", "饰物" }, { "shi wu qian li", "史无前例" }, { "shi wu sui", "十五岁" }, { "shi wu suo", "事务所" },
			{ "shi wu zhong du", "食物中毒" }, { "shi xi", "世袭" }, { "shi xi", "实习" }, { "shi xi", "市西" }, { "shi xi sheng", "实习生" }, { "shi xia", "时下" },
			{ "shi xia", "试下" }, { "shi xian", "事先" }, { "shi xian", "实现" }, { "shi xian", "市县" }, { "shi xian", "时限" }, { "shi xian", "视线" },
			{ "shi xiang", "事项" }, { "shi xiang", "十项" }, { "shi xiang", "是想" }, { "shi xiang", "石像" }, { "shi xiang", "试想" }, { "shi xiang", "驶向" },
			{ "shi xiao", "失效" }, { "shi xiao", "实效" }, { "shi xiao", "时效" }, { "shi xiao xing", "实效性" }, { "shi xiao xing", "时效性" }, { "shi xie", "是些" },
			{ "shi xin", "失信" }, { "shi xin", "实心" }, { "shi xing", "实行" }, { "shi xing", "施行" }, { "shi xing", "试行" }, { "shi xiong", "师兄" },
			{ "shi xu", "时序" }, { "shi xu", "时许" }, { "shi xue", "史学" }, { "shi xue", "嗜血" }, { "shi xue", "失学" }, { "shi xue", "失血" },
			{ "shi xue jia", "史学家" }, { "shi xun", "实训" }, { "shi xun", "视讯" }, { "shi xun", "试训" }, { "shi ya", "施压" }, { "shi ya", "是呀" },
			{ "shi yan", "十堰" }, { "shi yan", "实验" }, { "shi yan", "时延" }, { "shi yan", "誓言" }, { "shi yan", "试验" }, { "shi yan", "食盐" }, { "shi yan", "饰演" },
			{ "shi yan ban", "实验班" }, { "shi yan jiao xue", "实验教学" }, { "shi yan jie guo", "试验结果" }, { "shi yan qu", "试验区" }, { "shi yan shi", "实验室" },
			{ "shi yan xiao xue", "实验小学" }, { "shi yan xing", "实验性" }, { "shi yan xue xiao", "实验学校" }, { "shi yan yan jiu", "实验研究" },
			{ "shi yan yan jiu", "试验研究" }, { "shi yan zhong xue", "实验中学" }, { "shi yang", "式样" }, { "shi yang", "试样" }, { "shi yao", "时要" },
			{ "shi yao", "是要" }, { "shi ye", "事业" }, { "shi ye", "失业" }, { "shi ye", "实业" }, { "shi ye", "时也" }, { "shi ye", "视野" },
			{ "shi ye bao xian", "失业保险" }, { "shi ye bu", "事业部" }, { "shi ye dan wei", "事业单位" }, { "shi ye fa zhan", "事业发展" }, { "shi ye gong si", "实业公司" },
			{ "shi ye lv", "失业率" }, { "shi ye pai", "什叶派" }, { "shi ye ren yuan", "失业人员" }, { "shi ye xin", "事业心" }, { "shi ye you cheng", "事业有成" } };
};
