package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN21 {
	public static String[][] pl = { { "huo sheng sheng", "活生生" }, { "huo shi", "伙食" }, { "huo shi", "或是" }, { "huo shi", "火势" }, { "huo shi", "获释" },
			{ "huo shi fei", "伙食费" }, { "huo su", "火速" }, { "huo ti", "活体" }, { "huo tong", "伙同" }, { "huo tui", "火腿" }, { "huo tui chang", "火腿肠" },
			{ "huo wu", "货物" }, { "huo wu yun shu", "货物运输" }, { "huo xi", "获悉" }, { "huo xia qu", "活下去" }, { "huo xian", "火线" }, { "huo xing", "活性" },
			{ "huo xing", "火星" }, { "huo xing ren", "火星人" }, { "huo xing tan", "活性炭" }, { "huo xu", "或许" }, { "huo xue", "活血" }, { "huo yan", "火焰" },
			{ "huo yao", "火药" }, { "huo yi", "或以" }, { "huo yi", "获益" }, { "huo yi shang", "或以上" }, { "huo yin", "或因" }, { "huo ying", "火影" },
			{ "huo ying dong", "霍英东" }, { "huo ying ren zhe", "火影忍者" }, { "huo yong", "或用" }, { "huo you", "或有" }, { "huo yuan", "货源" },
			{ "huo yuan jia", "霍元甲" }, { "huo yue", "活跃" }, { "huo yun", "货运" }, { "huo zai", "活在" }, { "huo zai", "火灾" }, { "huo ze", "或则" },
			{ "huo zeng", "获赠" }, { "huo zhe", "或者" }, { "huo zhe", "活着" }, { "huo zhe qi ta", "或者其他" }, { "huo zhen jia shi", "货真价实" }, { "huo zhi", "获知" },
			{ "huo zhong", "火种" }, { "huo zhu", "货主" }, { "huo zhun", "获准" }, { "ji", "丌" }, { "ji", "丮" }, { "ji", "乩" }, { "ji", "亟" }, { "ji", "亼" },
			{ "ji", "伋" }, { "ji", "伎" }, { "ji", "佶" }, { "ji", "偈" }, { "ji", "偮" }, { "ji", "其" }, { "ji", "冀" }, { "ji", "几" }, { "ji", "击" },
			{ "ji", "刉" }, { "ji", "剂" }, { "ji", "剞" }, { "ji", "剤" }, { "ji", "劑" }, { "ji", "勣" }, { "ji", "即" }, { "ji", "卽" }, { "ji", "及" },
			{ "ji", "叝" }, { "ji", "叽" }, { "ji", "吇" }, { "ji", "吉" }, { "ji", "咭" }, { "ji", "唧" }, { "ji", "喞" }, { "ji", "嘰" }, { "ji", "圾" },
			{ "ji", "基" }, { "ji", "堲" }, { "ji", "塈" }, { "ji", "塉" }, { "ji", "墼" }, { "ji", "奇" }, { "ji", "妀" }, { "ji", "妓" }, { "ji", "姞" },
			{ "ji", "姬" }, { "ji", "嫉" }, { "ji", "季" }, { "ji", "寂" }, { "ji", "寄" }, { "ji", "屐" }, { "ji", "岋" }, { "ji", "岌" }, { "ji", "嵇" },
			{ "ji", "嵴" }, { "ji", "嶯" }, { "ji", "己" }, { "ji", "幾" }, { "ji", "庴" }, { "ji", "彑" }, { "ji", "彶" }, { "ji", "徛" }, { "ji", "忌" },
			{ "ji", "忣" }, { "ji", "急" }, { "ji", "悸" }, { "ji", "惎" }, { "ji", "懻" }, { "ji", "戟" }, { "ji", "戢" }, { "ji", "技" }, { "ji", "挤" },
			{ "ji", "掎" }, { "ji", "揤" }, { "ji", "撃" }, { "ji", "撠" }, { "ji", "擊" }, { "ji", "擠" }, { "ji", "旡" }, { "ji", "既" }, { "ji", "旣" },
			{ "ji", "暨" }, { "ji", "暩" }, { "ji", "期" }, { "ji", "机" }, { "ji", "极" }, { "ji", "枅" }, { "ji", "棘" }, { "ji", "楫" }, { "ji", "極" },
			{ "ji", "槉" }, { "ji", "機" }, { "ji", "橶" }, { "ji", "檕" }, { "ji", "櫅" }, { "ji", "殛" }, { "ji", "汲" }, { "ji", "泲" }, { "ji", "洎" },
			{ "ji", "济" }, { "ji", "湒" }, { "ji", "漃" }, { "ji", "漈" }, { "ji", "潗" }, { "ji", "激" }, { "ji", "濟" }, { "ji", "瀱" }, { "ji", "犄" },
			{ "ji", "犱" }, { "ji", "玑" }, { "ji", "璣" }, { "ji", "畟" }, { "ji", "畸" }, { "ji", "畿" }, { "ji", "疾" }, { "ji", "痵" }, { "ji", "瘠" },
			{ "ji", "癠" }, { "ji", "癪" }, { "ji", "皀" }, { "ji", "矶" }, { "ji", "磯" }, { "ji", "祭" }, { "ji", "禝" }, { "ji", "积" }, { "ji", "稷" },
			{ "ji", "稽" }, { "ji", "穄" }, { "ji", "穊" }, { "ji", "積" }, { "ji", "穖" }, { "ji", "笄" }, { "ji", "笈" }, { "ji", "箕" }, { "ji", "簊" },
			{ "ji", "簎" }, { "ji", "籍" }, { "ji", "系" }, { "ji", "紀" }, { "ji", "級" }, { "ji", "継" }, { "ji", "緝" }, { "ji", "績" }, { "ji", "繋" },
			{ "ji", "繼" }, { "ji", "级" }, { "ji", "纪" }, { "ji", "给" }, { "ji", "继" }, { "ji", "绩" }, { "ji", "缉" }, { "ji", "罽" }, { "ji", "羁" },
			{ "ji", "羇" }, { "ji", "羈" }, { "ji", "耭" }, { "ji", "肌" }, { "ji", "脊" }, { "ji", "膌" }, { "ji", "臮" }, { "ji", "芨" }, { "ji", "芰" },
			{ "ji", "茍" }, { "ji", "茤" }, { "ji", "荠" }, { "ji", "蒺" }, { "ji", "蓟" }, { "ji", "蕀" }, { "ji", "蕺" }, { "ji", "薊" }, { "ji", "薺" },
			{ "ji", "藉" }, { "ji", "蘮" }, { "ji", "蘻" }, { "ji", "虀" }, { "ji", "虮" }, { "ji", "螏" }, { "ji", "蠀" }, { "ji", "裚" }, { "ji", "襋" },
			{ "ji", "覊" }, { "ji", "覘" }, { "ji", "覬" }, { "ji", "覿" }, { "ji", "觊" }, { "ji", "觙" }, { "ji", "計" }, { "ji", "記" }, { "ji", "誋" },
			{ "ji", "諅" }, { "ji", "諔" }, { "ji", "譏" }, { "ji", "计" }, { "ji", "讥" }, { "ji", "记" }, { "ji", "诘" }, { "ji", "谻" }, { "ji", "赍" },
			{ "ji", "跡" }, { "ji", "跻" }, { "ji", "跽" }, { "ji", "踖" }, { "ji", "蹐" }, { "ji", "蹟" }, { "ji", "躋" }, { "ji", "輯" }, { "ji", "轚" },
			{ "ji", "辑" }, { "ji", "迹" }, { "ji", "銈" }, { "ji", "銡" }, { "ji", "錤" }, { "ji", "鏶" }, { "ji", "鐖" }, { "ji", "鑇" }, { "ji", "际" },
			{ "ji", "際" }, { "ji", "隮" }, { "ji", "集" }, { "ji", "雞" }, { "ji", "霁" }, { "ji", "霵" }, { "ji", "霽" }, { "ji", "革" }, { "ji", "鞿" },
			{ "ji", "韲" }, { "ji", "飢" }, { "ji", "饑" }, { "ji", "饥" }, { "ji", "驥" }, { "ji", "骑" }, { "ji", "骥" }, { "ji", "髻" }, { "ji", "鮆" },
			{ "ji", "鯚" }, { "ji", "鰶" }, { "ji", "鰿" }, { "ji", "鱀" }, { "ji", "鱭" }, { "ji", "鲚" }, { "ji", "鲫" }, { "ji", "鵋" }, { "ji", "鶏" },
			{ "ji", "鶺" }, { "ji", "鷄" }, { "ji", "鷑" }, { "ji", "鸄" }, { "ji", "鸡" }, { "ji", "麂" }, { "ji", "齌" }, { "ji", "齎" }, { "ji", "齏" },
			{ "ji", "齑" }, { "ji an", "吉安" }, { "ji ang", "激昂" }, { "ji ba", "几把" }, { "ji ba", "即把" }, { "ji ba", "鸡吧" }, { "ji ba", "鸡巴" },
			{ "ji bai", "几百" }, { "ji bai", "击败" }, { "ji bai", "祭拜" }, { "ji bai wan", "几百万" }, { "ji ban", "基板" }, { "ji ban", "羁绊" }, { "ji bao", "季报" },
			{ "ji bei", "几倍" }, { "ji bei", "几杯" }, { "ji bei", "脊背" }, { "ji ben", "几本" }, { "ji ben", "基本" }, { "ji ben fa", "基本法" },
			{ "ji ben gai nian", "基本概念" }, { "ji ben gong", "基本功" }, { "ji ben gong neng", "基本功能" }, { "ji ben gong zi", "基本工资" },
			{ "ji ben jian she", "基本建设" }, { "ji ben li lun", "基本理论" }, { "ji ben mian", "基本面" }, { "ji ben nei rong", "基本内容" },
			{ "ji ben nong tian", "基本农田" }, { "ji ben qing kuang", "基本情况" }, { "ji ben quan li", "基本权利" }, { "ji ben shang", "基本上" },
			{ "ji ben te zheng", "基本特征" }, { "ji ben tiao jian", "基本条件" }, { "ji ben wan cheng", "基本完成" }, { "ji ben xin xi", "基本信息" },
			{ "ji ben yao qiu", "基本要求" }, { "ji ben yuan li", "基本原理" }, { "ji ben yuan ze", "基本原则" }, { "ji ben zhi shi", "基本知识" }, { "ji bi", "几笔" },
			{ "ji bi", "击毙" }, { "ji bian", "几遍" }, { "ji bian", "即便" }, { "ji bian", "畸变" }, { "ji biao ming", "即表明" }, { "ji bie", "级别" },
			{ "ji bing", "疾病" }, { "ji bu", "几步" }, { "ji bu", "几部" }, { "ji bu", "基部" }, { "ji bu", "既不" }, { "ji bu", "记不" }, { "ji bu qing", "记不清" },
			{ "ji cai", "集采" }, { "ji cang", "机舱" }, { "ji ceng", "几层" }, { "ji ceng", "基层" }, { "ji ceng dan wei", "基层单位" }, { "ji ceng gan bu", "基层干部" },
			{ "ji ceng zu zhi", "基层组织" }, { "ji cha", "极差" }, { "ji cha", "稽查" }, { "ji chang", "几场" }, { "ji chang", "机场" }, { "ji che", "机车" },
			{ "ji cheng", "即成" }, { "ji cheng", "继承" }, { "ji cheng", "集成" }, { "ji cheng dian lu", "集成电路" }, { "ji cheng ren", "继承人" },
			{ "ji cheng xian ka", "集成显卡" }, { "ji chi", "鸡翅" }, { "ji chou", "记仇" }, { "ji chu", "几处" }, { "ji chu", "基础" }, { "ji chu", "寄出" },
			{ "ji chu", "挤出" }, { "ji chu gong zuo", "基础工作" }, { "ji chu jian she", "基础建设" }, { "ji chu jiao yu", "基础教育" }, { "ji chu ke", "基础课" },
			{ "ji chu li lun", "基础理论" }, { "ji chu she shi", "基础设施" }, { "ji chu xing", "基础性" }, { "ji chu yan jiu", "基础研究" }, { "ji chu zhi shi", "基础知识" },
			{ "ji chuan", "击穿" }, { "ji chuang", "机床" }, { "ji ci", "几次" }, { "ji cong cong", "急匆匆" }, { "ji cu", "急促" }, { "ji cun", "寄存" },
			{ "ji cun qi", "寄存器" }, { "ji cuo", "记错" }, { "ji da", "几大" }, { "ji da", "击打" }, { "ji da", "吉大" }, { "ji da", "极大" }, { "ji dai", "亟待" },
			{ "ji dai", "几代" }, { "ji dai jie jue", "亟待解决" }, { "ji dan", "鸡蛋" }, { "ji dang", "激荡" }, { "ji dao", "几道" }, { "ji dao", "击倒" },
			{ "ji dao", "寄到" }, { "ji dao", "挤到" }, { "ji de", "基德" }, { "ji de", "急得" }, { "ji de", "挤得" }, { "ji de", "级的" }, { "ji de", "记得" },
			{ "ji de li yi", "既得利益" }, { "ji de ni", "记得你" }, { "ji di", "几滴" }, { "ji di", "基地" }, { "ji di", "基底" }, { "ji di", "极低" }, { "ji di", "极地" },
			{ "ji di jian she", "基地建设" }, { "ji dian", "几点" }, { "ji dian", "基点" }, { "ji dian", "机电" }, { "ji dian", "极点" }, { "ji dian", "祭奠" },
			{ "ji dian", "积淀" }, { "ji dian chan pin", "机电产品" }, { "ji dian qi", "继电器" }, { "ji dian she bei", "机电设备" }, { "ji dian si kao", "几点思考" },
			{ "ji dian zhong", "几点钟" }, { "ji diao", "基调" }, { "ji die", "急跌" }, { "ji ding", "既定" }, { "ji ding he", "机顶盒" }, { "ji dong", "悸动" },
			{ "ji dong", "机动" }, { "ji dong", "激动" }, { "ji dong che", "机动车" }, { "ji dong che liang", "机动车辆" }, { "ji dong ren xin", "激动人心" },
			{ "ji du", "几度" }, { "ji du", "基督" }, { "ji du", "嫉妒" }, { "ji du", "季度" }, { "ji du", "极度" }, { "ji du jiao", "基督教" }, { "ji du tu", "基督徒" },
			{ "ji duan", "几段" }, { "ji duan", "极端" }, { "ji dui", "及对" }, { "ji dui", "挤兑" }, { "ji duo", "几多" }, { "ji e", "饥饿" }, { "ji er", "吉尔" },
			{ "ji er", "继而" }, { "ji fa", "技法" }, { "ji fa", "激发" }, { "ji fa", "继发" }, { "ji fa xing", "继发性" }, { "ji fa xue sheng", "激发学生" },
			{ "ji fan", "几番" }, { "ji fang", "己方" }, { "ji fang", "机房" }, { "ji fei", "计费" }, { "ji fen", "几分" }, { "ji fen", "激愤" }, { "ji fen", "积分" },
			{ "ji fen", "计分" }, { "ji fen", "记分" }, { "ji fen bang", "积分榜" }, { "ji feng", "季风" }, { "ji feng", "疾风" }, { "ji feng", "讥讽" }, { "ji fu", "极富" },
			{ "ji fu", "给付" }, { "ji fu", "继父" }, { "ji fu", "肌肤" }, { "ji gai", "技改" }, { "ji gao", "极高" }, { "ji ge", "几个" }, { "ji ge", "及格" },
			{ "ji ge fang mian", "几个方面" }, { "ji ge ren", "几个人" }, { "ji ge wen ti", "几个问题" }, { "ji ge xiao shi", "几个小时" }, { "ji ge yue", "几个月" },
			{ "ji ge zhong", "及各种" }, { "ji ge zi", "几个字" }, { "ji gei", "寄给" }, { "ji gen", "几根" }, { "ji gong", "技工" }, { "ji gong jin li", "急功近利" },
			{ "ji gong xue xiao", "技工学校" }, { "ji gou", "机构" }, { "ji gou gai ge", "机构改革" }, { "ji guan", "机关" }, { "ji guan", "籍贯" },
			{ "ji guan gan bu", "机关干部" }, { "ji guang", "极光" }, { "ji guang", "激光" }, { "ji guang qi", "激光器" }, { "ji gui", "机柜" }, { "ji guo", "记过" },
			{ "ji hang", "几行" }, { "ji hao", "几号" }, { "ji hao", "几好" }, { "ji hao", "极好" }, { "ji hao", "记号" }, { "ji he", "几何" }, { "ji he", "稽核" },
			{ "ji he", "集合" }, { "ji hou sai", "季后赛" }, { "ji hu", "几乎" }, { "ji hu mei you", "几乎没有" }, { "ji hu suo you", "几乎所有" }, { "ji hua", "极化" },
			{ "ji hua", "激化" }, { "ji hua", "计划" }, { "ji hua jing ji", "计划经济" }, { "ji hua sheng yu", "计划生育" }, { "ji hua shu", "计划书" }, { "ji huan", "疾患" },
			{ "ji huang", "饥荒" }, { "ji hui", "几回" }, { "ji hui", "寄回" }, { "ji hui", "忌讳" }, { "ji hui", "机会" }, { "ji hui", "集会" }, { "ji huo", "激活" },
			{ "ji huo ma", "激活码" }, { "ji ji", "几级" }, { "ji ji", "几集" }, { "ji ji", "唧唧" }, { "ji ji", "急急" }, { "ji ji", "积极" }, { "ji ji", "鸡鸡" },
			{ "ji ji can jia", "积极参加" }, { "ji ji can yu", "积极参与" }, { "ji ji fen zi", "积极分子" }, { "ji ji kai zhan", "积极开展" }, { "ji ji mang mang", "急急忙忙" },
			{ "ji ji tan suo", "积极探索" }, { "ji ji xiang shang", "积极向上" }, { "ji ji xing", "积极性" }, { "ji ji yi yi", "积极意义" }, { "ji ji zha zha", "叽叽喳喳" },
			{ "ji ji zhu dong", "积极主动" }, { "ji ji zuo yong", "积极作用" }, { "ji jia", "几家" }, { "ji jia", "技嘉" }, { "ji jia", "机架" }, { "ji jia", "机甲" },
			{ "ji jia", "极佳" }, { "ji jia", "计价" }, { "ji jian", "几件" }, { "ji jian", "几间" }, { "ji jian", "基建" }, { "ji jian", "纪检" },
			{ "ji jian jian cha", "纪检监察" }, { "ji jiang", "即将" }, { "ji jiang dao lai", "即将到来" }, { "ji jiang jie shu", "即将结束" },
			{ "ji jiang lai lin", "即将来临" }, { "ji jiang shang shi", "即将上市" }, { "ji jiang tui chu", "即将推出" }, { "ji jiao", "计较" }, { "ji jie", "季节" },
			{ "ji jie", "集结" }, { "ji jie xing", "季节性" }, { "ji jin", "几斤" }, { "ji jin", "几近" }, { "ji jin", "基金" }, { "ji jin", "挤进" }, { "ji jin", "极尽" },
			{ "ji jin", "激进" }, { "ji jin", "集锦" }, { "ji jin gong si", "基金公司" }, { "ji jin guan li", "基金管理" }, { "ji jin hui", "基金会" },
			{ "ji jin jing li", "基金经理" }, { "ji jin jing zhi", "基金净值" }, { "ji jin tou zi", "基金投资" }, { "ji jin ye", "基金业" }, { "ji jing", "几经" },
			{ "ji jing", "寂静" }, { "ji jing", "己经" }, { "ji jing", "鸡精" }, { "ji jiu", "急救" }, { "ji ju", "几句" }, { "ji ju", "急剧" }, { "ji ju", "机具" },
			{ "ji ju", "极具" }, { "ji ju", "积聚" }, { "ji ju", "集聚" }, { "ji ju hua", "几句话" }, { "ji jun", "季军" }, { "ji ke", "几颗" }, { "ji ke", "即刻" },
			{ "ji ke", "即可" }, { "ji ke", "既可" }, { "ji ke", "机壳" }, { "ji ke", "饥渴" }, { "ji ke yi", "既可以" }, { "ji kong zhong xin", "疾控中心" },
			{ "ji kou", "几口" }, { "ji ku", "疾苦" }, { "ji kuai", "几块" }, { "ji kuai", "极快" }, { "ji kuan", "几款" }, { "ji kui", "击溃" }, { "ji lai", "寄来" },
			{ "ji le", "极乐" }, { "ji lei", "几类" }, { "ji lei", "基类" }, { "ji lei", "积累" }, { "ji lei", "鸡肋" }, { "ji li", "吉利" }, { "ji li", "机理" },
			{ "ji li", "极力" }, { "ji li", "激励" }, { "ji li ji zhi", "激励机制" }, { "ji lian", "级联" }, { "ji liang", "伎俩" }, { "ji liang", "几辆" },
			{ "ji liang", "剂量" }, { "ji liang", "脊梁" }, { "ji liang", "计量" }, { "ji liao", "寂寥" }, { "ji lie", "激烈" }, { "ji lin", "吉林" },
			{ "ji lin da xue", "吉林大学" }, { "ji lin sheng", "吉林省" }, { "ji lin shi", "吉林市" }, { "ji ling", "机灵" }, { "ji liu", "激流" }, { "ji liu", "肌瘤" },
			{ "ji long po", "吉隆坡" }, { "ji lou", "几楼" }, { "ji lu", "纪录" }, { "ji lu", "记录" }, { "ji lu pian", "纪录片" }, { "ji lu pian", "记录片" },
			{ "ji lu xia lai", "记录下来" }, { "ji lun", "几轮" }, { "ji luo", "击落" }, { "ji lv", "几率" }, { "ji lv", "机率" }, { "ji lv", "纪律" },
			{ "ji lv jian cha", "纪律检查" }, { "ji man", "挤满" }, { "ji mang", "急忙" }, { "ji mao", "鸡毛" }, { "ji mao shi chang", "集贸市场" },
			{ "ji mao suan pi", "鸡毛蒜皮" }, { "ji mei", "集美" }, { "ji mei you", "既没有" }, { "ji men", "几门" }, { "ji mi", "几米" }, { "ji mi", "吉米" },
			{ "ji mi", "机密" }, { "ji miao", "几秒" }, { "ji ming", "几名" }, { "ji mo", "寂寞" }, { "ji mou", "计谋" }, { "ji mu", "吉姆" }, { "ji mu", "积木" },
			{ "ji mu", "继母" }, { "ji nan", "济南" }, { "ji nan da xue", "暨南大学" }, { "ji nan shi", "济南市" }, { "ji neng", "技能" }, { "ji neng", "既能" },
			{ "ji neng", "机能" }, { "ji neng pei xun", "技能培训" }, { "ji nian", "几年" }, { "ji nian", "纪念" }, { "ji nian bei", "纪念碑" }, { "ji nian bi", "纪念币" },
			{ "ji nian de", "几年的" }, { "ji nian guan", "纪念馆" }, { "ji nian huo dong", "纪念活动" }, { "ji nian lai", "几年来" }, { "ji nian pin", "纪念品" },
			{ "ji nian qian", "几年前" }, { "ji nian ri", "纪念日" }, { "ji ning", "济宁" }, { "ji nu", "激怒" }, { "ji nv", "妓女" }, { "ji pi ge da", "鸡皮疙瘩" },
			{ "ji pian", "几片" }, { "ji pian", "几篇" }, { "ji piao", "机票" }, { "ji piao jia ge", "机票价格" }, { "ji pin", "极品" }, { "ji pin fei che", "极品飞车" },
			{ "ji ping", "几瓶" }, { "ji po", "击破" }, { "ji po", "急迫" }, { "ji pu", "吉普" }, { "ji pu che", "吉普车" }, { "ji qi", "及其" }, { "ji qi", "机器" },
			{ "ji qi", "极其" }, { "ji qi", "激起" }, { "ji qi", "记起" }, { "ji qi mao", "机器猫" }, { "ji qi ren", "机器人" }, { "ji qi ta", "及其它" },
			{ "ji qi xiang guan", "及其相关" }, { "ji qi ying yong", "及其应用" }, { "ji qian", "几千" }, { "ji qian", "寄钱" }, { "ji qian nian", "几千年" },
			{ "ji qian wan", "几千万" }, { "ji qiang", "机枪" }, { "ji qiang", "极强" }, { "ji qiao", "技巧" }, { "ji qie", "急切" }, { "ji qing", "激情" },
			{ "ji qing xi", "激情戏" }, { "ji qiu", "击球" }, { "ji qu", "汲取" }, { "ji quan", "几圈" }, { "ji quan", "集权" }, { "ji qun", "集群" }, { "ji ran", "既然" },
			{ "ji ran ru ci", "既然如此" }, { "ji ren", "几人" }, { "ji ren", "己任" }, { "ji ri", "几日" }, { "ji ri", "即日" }, { "ji rou", "肌肉" }, { "ji rou", "鸡肉" },
			{ "ji ru", "计入" }, { "ji ru", "记入" }, { "ji san di", "集散地" }, { "ji sha", "击杀" }, { "ji shang", "机上" }, { "ji shao", "极少" },
			{ "ji shao shu", "极少数" }, { "ji shen", "机身" }, { "ji shen", "跻身" }, { "ji sheng", "几声" }, { "ji sheng", "寄生" }, { "ji sheng", "计生" },
			{ "ji sheng chong", "寄生虫" }, { "ji sheng gong zuo", "计生工作" }, { "ji sheng wei", "计生委" }, { "ji shi", "几十" }, { "ji shi", "几时" },
			{ "ji shi", "即使" }, { "ji shi", "即时" }, { "ji shi", "即是" }, { "ji shi", "及时" }, { "ji shi", "基石" }, { "ji shi", "急事" }, { "ji shi", "技师" },
			{ "ji shi", "既是" }, { "ji shi", "纪事" }, { "ji shi", "纪实" }, { "ji shi", "计时" }, { "ji shi", "记事" }, { "ji shi", "集市" }, { "ji shi ben", "记事本" },
			{ "ji shi qi", "计时器" }, { "ji shi tong xin", "即时通信" }, { "ji shi tong xun", "即时通讯" }, { "ji shi wan", "几十万" }, { "ji shi xing", "及时性" },
			{ "ji shi yi", "几十亿" }, { "ji shou", "几首" }, { "ji shou", "棘手" }, { "ji shu", "基数" }, { "ji shu", "奇数" }, { "ji shu", "技术" }, { "ji shu", "级数" },
			{ "ji shu", "计数" }, { "ji shu", "记述" }, { "ji shu biao zhun", "技术标准" }, { "ji shu bu", "技术部" }, { "ji shu can shu", "技术参数" },
			{ "ji shu chuang xin", "技术创新" }, { "ji shu fa zhan", "技术发展" }, { "ji shu fen xi", "技术分析" }, { "ji shu fu wu", "技术服务" },
			{ "ji shu gai zao", "技术改造" }, { "ji shu gong ren", "技术工人" }, { "ji shu gui fan", "技术规范" }, { "ji shu han liang", "技术含量" },
			{ "ji shu he zuo", "技术合作" }, { "ji shu jiao liu", "技术交流" }, { "ji shu jin bu", "技术进步" }, { "ji shu kai fa", "技术开发" },
			{ "ji shu li liang", "技术力量" }, { "ji shu ling yu", "技术领域" }, { "ji shu pei xun", "技术培训" }, { "ji shu qi", "计数器" }, { "ji shu ren cai", "技术人才" },
			{ "ji shu ren yuan", "技术人员" }, { "ji shu shou duan", "技术手段" }, { "ji shu shui ping", "技术水平" }, { "ji shu tiao jian", "技术条件" },
			{ "ji shu tui guang", "技术推广" }, { "ji shu wen ti", "技术问题" }, { "ji shu xing", "技术性" }, { "ji shu yan fa", "技术研发" }, { "ji shu yan jiu", "技术研究" },
			{ "ji shu yao qiu", "技术要求" }, { "ji shu you shi", "技术优势" }, { "ji shu yuan", "技术员" }, { "ji shu zhi biao", "技术指标" }, { "ji shu zhi chi", "技术支持" },
			{ "ji shu zhi dao", "技术指导" }, { "ji shu zhong xin", "技术中心" }, { "ji shu zhuan rang", "技术转让" }, { "ji shu zhuang bei", "技术装备" },
			{ "ji shu zi liao", "技术资料" }, { "ji shui", "积水" }, { "ji shui", "计税" }, { "ji si", "急死" }, { "ji si", "祭司" }, { "ji si", "祭祀" },
			{ "ji song", "寄送" }, { "ji su", "寄宿" }, { "ji su", "急速" }, { "ji su", "极速" }, { "ji su", "激素" }, { "ji suan", "计算" }, { "ji suan chu", "计算出" },
			{ "ji suan fang fa", "计算方法" }, { "ji suan gong shi", "计算公式" }, { "ji suan ji", "计算机" }, { "ji suan ji xi", "计算机系" }, { "ji suan jie guo", "计算结果" },
			{ "ji suan qi", "计算器" }, { "ji sui", "几岁" }, { "ji sui", "脊髓" }, { "ji ta", "吉他" }, { "ji ta", "吉它" }, { "ji ta shou", "吉他手" }, { "ji tai", "几台" },
			{ "ji tan", "祭坛" }, { "ji tang", "鸡汤" }, { "ji tao", "几套" }, { "ji ti", "机体" }, { "ji ti", "肌体" }, { "ji ti", "计提" }, { "ji ti", "集体" },
			{ "ji ti jing ji", "集体经济" }, { "ji ti qi ye", "集体企业" }, { "ji ti tu di", "集体土地" }, { "ji tian", "几天" }, { "ji tian", "吉田" },
			{ "ji tian hou", "几天后" }, { "ji tiao", "几条" }, { "ji tou", "机头" }, { "ji tuan", "集团" }, { "ji tuan gong si", "集团公司" }, { "ji tuan jun", "集团军" },
			{ "ji tuan zong cai", "集团总裁" }, { "ji tui", "击退" }, { "ji tui", "鸡腿" }, { "ji tuo", "寄托" }, { "ji wan", "几万" }, { "ji wang", "寄望" },
			{ "ji wang", "既往" }, { "ji wei", "几位" }, { "ji wei", "即为" }, { "ji wei", "即位" }, { "ji wei", "极为" }, { "ji wei", "纪委" }, { "ji wei", "继位" },
			{ "ji wei jiu", "鸡尾酒" }, { "ji wei shu ji", "纪委书记" }, { "ji wei zhong yao", "极为重要" }, { "ji wu", "既无" }, { "ji xia", "几下" }, { "ji xia", "记下" },
			{ "ji xian", "基线" }, { "ji xian", "极限" }, { "ji xian qi", "集线器" }, { "ji xiang", "几项" }, { "ji xiang", "吉祥" }, { "ji xiang", "机箱" },
			{ "ji xiang", "迹象" }, { "ji xiang wu", "吉祥物" }, { "ji xiao", "技校" }, { "ji xiao", "极小" }, { "ji xiao", "绩效" }, { "ji xiao", "讥笑" },
			{ "ji xiao guan li", "绩效管理" }, { "ji xiao kao he", "绩效考核" }, { "ji xie", "机械" }, { "ji xie chang", "机械厂" }, { "ji xie gong ye", "机械工业" },
			{ "ji xie hang ye", "机械行业" }, { "ji xie hua", "机械化" }, { "ji xie she bei", "机械设备" }, { "ji xie zhi zao", "机械制造" }, { "ji xin", "寄信" },
			{ "ji xin", "机芯" }, { "ji xing", "剂型" }, { "ji xing", "即兴" }, { "ji xing", "急性" }, { "ji xing", "机型" }, { "ji xing", "极性" }, { "ji xing", "畸形" },
			{ "ji xing", "记性" }, { "ji xiong", "吉凶" }, { "ji xu", "亟需" }, { "ji xu", "几许" }, { "ji xu", "急需" }, { "ji xu", "积蓄" }, { "ji xu", "继续" },
			{ "ji xu jiao yu", "继续教育" }, { "ji xu nu li", "继续努力" }, { "ji xue", "积雪" }, { "ji xun", "集训" }, { "ji ya", "挤压" }, { "ji ya", "积压" },
			{ "ji ya", "羁押" }, { "ji ya", "鸡鸭" }, { "ji yan", "几眼" }, { "ji yang", "几样" }, { "ji yang", "寄养" }, { "ji yao", "既要" }, { "ji yao", "纪要" },
			{ "ji ye", "几页" }, { "ji ye", "基业" }, { "ji ye", "积液" }, { "ji yi", "几亿" }, { "ji yi", "即以" }, { "ji yi", "技艺" }, { "ji yi", "机翼" },
			{ "ji yi", "极易" }, { "ji yi", "记忆" }, { "ji yi bang", "记忆棒" }, { "ji yi ka", "记忆卡" }, { "ji yi li", "记忆力" }, { "ji yi shang", "级以上" },
			{ "ji yi you xin", "记忆犹新" }, { "ji yin", "基因" }, { "ji yin zu", "基因组" }, { "ji yong", "即用" }, { "ji yong", "急用" }, { "ji you", "即有" },
			{ "ji you", "既有" }, { "ji you", "机油" }, { "ji you", "绩优" }, { "ji you", "集邮" }, { "ji you gu", "绩优股" }, { "ji yu", "基于" }, { "ji yu", "寄予" },
			{ "ji yu", "寄语" }, { "ji yu", "急于" }, { "ji yu", "机遇" }, { "ji yu", "给与" }, { "ji yu", "给予" }, { "ji yu", "觊觎" }, { "ji yu", "际遇" },
			{ "ji yu", "鲫鱼" }, { "ji yuan", "妓院" }, { "ji yuan", "机缘" }, { "ji yue", "几月" }, { "ji yue", "集约" }, { "ji yue hua", "集约化" }, { "ji zai", "即在" },
			{ "ji zai", "挤在" }, { "ji zai", "记在" }, { "ji zai", "记载" }, { "ji zan", "积攒" }, { "ji zao", "及早" }, { "ji zao", "急躁" }, { "ji zeng", "激增" },
			{ "ji zhan", "基站" }, { "ji zhan", "挤占" }, { "ji zhan", "机战" }, { "ji zhan", "激战" }, { "ji zhan shu", "技战术" }, { "ji zhang", "几张" },
			{ "ji zhang", "机长" }, { "ji zhang", "记帐" }, { "ji zhang", "记账" }, { "ji zhao", "几招" }, { "ji zhe", "几折" }, { "ji zhe", "急着" }, { "ji zhe", "记着" },
			{ "ji zhe", "记者" }, { "ji zhe cai fang", "记者采访" }, { "ji zhe hui", "记者会" }, { "ji zhe li", "记者李" }, { "ji zhe liu", "记者刘" },
			{ "ji zhe wang", "记者王" }, { "ji zhe wen", "记者问" }, { "ji zhe zhang", "记者张" }, { "ji zhen", "急诊" }, { "ji zhen", "集镇" } };
};
