package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN33 {
	public static String[][] pl = { { "mo huan", "魔幻" }, { "mo ji", "墨迹" }, { "mo ji", "磨叽" }, { "mo jie", "摩羯" }, { "mo jie", "魔戒" }, { "mo jie", "魔界" },
			{ "mo jie", "魔羯" }, { "mo jie zuo", "摩羯座" }, { "mo jing", "墨镜" }, { "mo jing", "魔镜" }, { "mo ju", "模具" }, { "mo ke er", "默克尔" },
			{ "mo kuai", "模块" }, { "mo kuai hua", "模块化" }, { "mo le", "抹了" }, { "mo le", "摸了" }, { "mo li", "磨砺" }, { "mo li", "茉莉" }, { "mo li", "魔力" },
			{ "mo li hua", "茉莉花" }, { "mo lian", "磨炼" }, { "mo lian", "磨练" }, { "mo lu", "陌路" }, { "mo luo", "没落" }, { "mo luo ge", "摩洛哥" },
			{ "mo mie", "磨灭" }, { "mo ming", "莫名" }, { "mo ming qi miao", "莫名其妙" }, { "mo mo", "嬷嬷" }, { "mo mo", "摸摸" }, { "mo mo", "默默" },
			{ "mo mo wu wen", "默默无闻" }, { "mo na ge", "摩纳哥" }, { "mo nan", "磨难" }, { "mo ni", "模拟" }, { "mo ni qi", "模拟器" }, { "mo ni ti", "模拟题" },
			{ "mo nian", "末年" }, { "mo nian", "默念" }, { "mo nv", "魔女" }, { "mo qi", "末期" }, { "mo qi", "默契" }, { "mo qing", "摸清" }, { "mo qu", "抹去" },
			{ "mo ran", "漠然" }, { "mo ran", "蓦然" }, { "mo ran", "默然" }, { "mo ren", "默认" }, { "mo ren de", "默认的" }, { "mo ren zhi", "默认值" }, { "mo ri", "末日" },
			{ "mo sha", "抹杀" }, { "mo sha", "磨砂" }, { "mo shang", "抹上" }, { "mo shang", "陌上" }, { "mo shen", "魔神" }, { "mo sheng", "陌生" },
			{ "mo sheng ren", "陌生人" }, { "mo shi", "模式" }, { "mo shi", "漠视" }, { "mo shou", "没收" }, { "mo shou", "魔兽" }, { "mo shou shi jie", "魔兽世界" },
			{ "mo shou zheng ba", "魔兽争霸" }, { "mo shu", "莫属" }, { "mo shu", "魔术" }, { "mo shu shi", "魔术师" }, { "mo shui", "墨水" }, { "mo si ke", "莫斯科" },
			{ "mo sun", "磨损" }, { "mo suo", "摸索" }, { "mo te", "模特" }, { "mo te er", "模特儿" }, { "mo tian lun", "摩天轮" }, { "mo tou", "魔头" }, { "mo tuo", "摩托" },
			{ "mo tuo che", "摩托车" }, { "mo tuo luo la", "摩托罗拉" }, { "mo wang", "魔王" }, { "mo wei", "末尾" }, { "mo wen wei", "莫文蔚" }, { "mo xi", "摩西" },
			{ "mo xi ge", "墨西哥" }, { "mo xing", "模型" }, { "mo xu", "默许" }, { "mo xu you", "莫须有" }, { "mo ya", "磨牙" }, { "mo yan", "莫言" }, { "mo yang", "模样" },
			{ "mo yu", "魔域" }, { "mo yu", "魔芋" }, { "mo zha te", "莫扎特" }, { "mo zhang", "魔杖" }, { "mo zhe", "摸着" }, { "mo zhou", "魔咒" }, { "mo zi", "墨子" },
			{ "mo zu", "模组" }, { "mo zu", "魔族" }, { "mou", "侔" }, { "mou", "哞" }, { "mou", "某" }, { "mou", "洠" }, { "mou", "牟" }, { "mou", "眸" },
			{ "mou", "缪" }, { "mou", "蛑" }, { "mou", "謀" }, { "mou", "谋" }, { "mou", "鉾" }, { "mou", "鍪" }, { "mou", "鴾" }, { "mou", "麰" }, { "mou bu", "某部" },
			{ "mou chu", "某处" }, { "mou ci", "某次" }, { "mou da xue", "某大学" }, { "mou di", "某地" }, { "mou ge", "某个" }, { "mou ge ren", "某个人" },
			{ "mou gong si", "某公司" }, { "mou hua", "谋划" }, { "mou jia", "某家" }, { "mou li", "牟利" }, { "mou lue", "谋略" }, { "mou mian", "谋面" },
			{ "mou mou", "某某" }, { "mou mou mou", "某某某" }, { "mou qiu", "谋求" }, { "mou qu", "谋取" }, { "mou ren", "某人" }, { "mou ri", "某日" },
			{ "mou sha", "谋杀" }, { "mou sheng", "谋生" }, { "mou shi", "某事" }, { "mou shi", "某市" }, { "mou tian", "某天" }, { "mou wei", "某位" },
			{ "mou xiang", "某项" }, { "mou xie", "某些" }, { "mou xie ren", "某些人" }, { "mou yi", "某一" }, { "mou yi tian", "某一天" }, { "mou zhong", "某种" },
			{ "mou zhong cheng du", "某种程度" }, { "mou zi", "眸子" }, { "mu", "亩" }, { "mu", "仫" }, { "mu", "凩" }, { "mu", "募" }, { "mu", "呒" }, { "mu", "坶" },
			{ "mu", "墓" }, { "mu", "姆" }, { "mu", "姥" }, { "mu", "峔" }, { "mu", "幕" }, { "mu", "幙" }, { "mu", "慔" }, { "mu", "慕" }, { "mu", "拇" },
			{ "mu", "暮" }, { "mu", "木" }, { "mu", "楘" }, { "mu", "模" }, { "mu", "母" }, { "mu", "毣" }, { "mu", "毪" }, { "mu", "氁" }, { "mu", "沐" },
			{ "mu", "炑" }, { "mu", "牟" }, { "mu", "牡" }, { "mu", "牧" }, { "mu", "牳" }, { "mu", "獏" }, { "mu", "畆" }, { "mu", "畝" }, { "mu", "目" },
			{ "mu", "睦" }, { "mu", "砪" }, { "mu", "穆" }, { "mu", "縸" }, { "mu", "艒" }, { "mu", "苜" }, { "mu", "茻" }, { "mu", "莯" }, { "mu", "萺" },
			{ "mu", "蚞" }, { "mu", "踇" }, { "mu", "鉧" }, { "mu", "鉬" }, { "mu", "钼" }, { "mu", "霂" }, { "mu", "鞪" }, { "mu ai", "母爱" }, { "mu ban", "木板" },
			{ "mu ban", "模板" }, { "mu bei", "墓碑" }, { "mu biao", "目标" }, { "mu biao guan li", "目标管理" }, { "mu biao jia", "目标价" }, { "mu biao ke hu", "目标客户" },
			{ "mu biao ren wu", "目标任务" }, { "mu biao shi chang", "目标市场" }, { "mu bu", "幕布" }, { "mu bu zhuan jing", "目不转睛" }, { "mu cai", "木材" },
			{ "mu cao", "牧草" }, { "mu ce", "目测" }, { "mu chan", "亩产" }, { "mu chang", "牧场" }, { "mu cun", "木村" }, { "mu dan", "牡丹" },
			{ "mu dan jiang", "牡丹江" }, { "mu de", "目地" }, { "mu deng kou dai", "目瞪口呆" }, { "mu di", "墓地" }, { "mu di", "目的" }, { "mu di ban", "木地板" },
			{ "mu di xing", "目的性" }, { "mu diao", "木雕" }, { "mu du", "目睹" }, { "mu er", "木耳" }, { "mu gong", "木工" }, { "mu gong si", "母公司" },
			{ "mu gou", "母狗" }, { "mu gua", "木瓜" }, { "mu guang", "目光" }, { "mu gun", "木棍" }, { "mu han mo de", "穆罕默德" }, { "mu hou", "幕后" },
			{ "mu ji", "募集" }, { "mu ji", "母鸡" }, { "mu ji", "目击" }, { "mu ji zhe", "目击者" }, { "mu ji zi jin", "募集资金" }, { "mu jiang", "木匠" },
			{ "mu ju", "模具" }, { "mu juan", "募捐" }, { "mu lan", "木兰" }, { "mu li", "牡蛎" }, { "mu li ni ao", "穆里尼奥" }, { "mu lu", "目录" },
			{ "mu lu xia", "目录下" }, { "mu ma", "木马" }, { "mu ma bing du", "木马病毒" }, { "mu men", "木门" }, { "mu mian", "木棉" }, { "mu min", "牧民" },
			{ "mu mu", "木木" }, { "mu nai yi", "木乃伊" }, { "mu ne", "木讷" }, { "mu ni hei", "慕尼黑" }, { "mu niu", "母牛" }, { "mu nv", "母女" }, { "mu ou", "木偶" },
			{ "mu qian", "目前" }, { "mu qian guo nei", "目前国内" }, { "mu qian shi chang", "目前市场" }, { "mu qiang", "幕墙" }, { "mu qin", "母亲" },
			{ "mu qin jie", "母亲节" }, { "mu qu", "牧区" }, { "mu rong", "慕容" }, { "mu ru", "母乳" }, { "mu ru wei yang", "母乳喂养" }, { "mu se", "暮色" },
			{ "mu sha la fu", "穆沙拉夫" }, { "mu shi", "牧师" }, { "mu si lin", "穆斯林" }, { "mu song", "目送" }, { "mu tan", "木炭" }, { "mu ti", "母体" },
			{ "mu tong", "木桶" }, { "mu tou", "木头" }, { "mu wu", "木屋" }, { "mu xian", "母线" }, { "mu xiang", "木箱" }, { "mu xiao", "母校" }, { "mu xing", "木星" },
			{ "mu xing", "母性" }, { "mu xue", "墓穴" }, { "mu yang", "模样" }, { "mu yang", "牧羊" }, { "mu ye", "木业" }, { "mu ye", "木叶" }, { "mu ye", "牧业" },
			{ "mu ying", "母婴" }, { "mu yu", "木鱼" }, { "mu yu", "母语" }, { "mu yu", "沐浴" }, { "mu yu lu", "沐浴露" }, { "mu zang", "墓葬" }, { "mu zhi", "拇指" },
			{ "mu zhi", "木制" }, { "mu zhi", "木质" }, { "mu zhu", "母猪" }, { "mu zi", "木子" }, { "mu zi", "母子" }, { "mu zi mei", "木子美" }, { "n", "唔" },
			{ "n", "嗯" }, { "na", "呐" }, { "na", "哪" }, { "na", "娜" }, { "na", "拏" }, { "na", "拿" }, { "na", "捺" }, { "na", "秅" }, { "na", "笝" },
			{ "na", "納" }, { "na", "纳" }, { "na", "肭" }, { "na", "衲" }, { "na", "豽" }, { "na", "貀" }, { "na", "軜" }, { "na", "那" }, { "na", "鈉" },
			{ "na", "钠" }, { "na", "镎" }, { "na", "雫" }, { "na", "靹" }, { "na", "魶" }, { "na ba", "那把" }, { "na ban", "那般" }, { "na bang", "那帮" },
			{ "na ben", "那本" }, { "na bian", "哪边" }, { "na bian", "那边" }, { "na bu", "哪部" }, { "na bu", "拿不" }, { "na bu", "那不" }, { "na bu", "那部" },
			{ "na bu dao", "拿不到" }, { "na cai", "那才" }, { "na ceng", "那层" }, { "na chang", "那场" }, { "na chu", "拿出" }, { "na chu lai", "拿出来" },
			{ "na ci", "哪次" }, { "na ci", "那次" }, { "na cui", "纳粹" }, { "na da er", "纳达尔" }, { "na dao", "拿刀" }, { "na dao", "拿到" }, { "na dao", "那倒" },
			{ "na dao", "那道" }, { "na de", "拿得" }, { "na de", "那得" }, { "na dian", "拿点" }, { "na dian", "那点" }, { "na diao", "拿掉" }, { "na duan", "那段" },
			{ "na dui", "那对" }, { "na duo", "那多" }, { "na er", "哪儿" }, { "na er", "纳尔" }, { "na er", "那儿" }, { "na fen", "那份" }, { "na fu", "那副" },
			{ "na gai", "那该" }, { "na gan", "哪敢" }, { "na ge", "哪个" }, { "na ge", "拿个" }, { "na ge", "那个" }, { "na ge di fang", "哪个地方" },
			{ "na ge di fang", "那个地方" }, { "na ge guo jia", "哪个国家" }, { "na ge hao", "哪个好" }, { "na ge nan ren", "那个男人" }, { "na ge nv hai", "那个女孩" },
			{ "na ge nv ren", "那个女人" }, { "na ge ren", "那个人" }, { "na ge shi hou", "那个时候" }, { "na gei", "拿给" }, { "na gen", "那根" }, { "na gu", "那股" },
			{ "na guo", "哪国" }, { "na guo", "拿过" }, { "na hai", "那还" }, { "na han", "呐喊" }, { "na hao", "那好" }, { "na hui", "哪会" }, { "na hui", "拿回" },
			{ "na hui", "那会" }, { "na hui er", "那会儿" }, { "na hui qu", "拿回去" }, { "na huo", "拿货" }, { "na ji", "那几" }, { "na ji ge", "那几个" },
			{ "na jia", "哪家" }, { "na jia", "那家" }, { "na jia huo", "那家伙" }, { "na jian", "那件" }, { "na jian", "那间" }, { "na jiao", "那叫" }, { "na jiu", "那就" },
			{ "na jiu shi", "那就是" }, { "na ju", "那句" }, { "na ju hua", "那句话" }, { "na ke", "那可" }, { "na ke", "那棵" }, { "na ke", "那颗" }, { "na kuai", "那块" },
			{ "na kuan", "哪款" }, { "na kuan", "那款" }, { "na lai", "哪来" }, { "na lai", "拿来" }, { "na lan", "纳兰" }, { "na li", "哪里" }, { "na li", "那里" },
			{ "na li qu", "哪里去" }, { "na li ren", "哪里人" }, { "na liang", "那两" }, { "na liang", "那辆" }, { "na me", "那么" }, { "na me da", "那么大" },
			{ "na me hao", "那么好" }, { "na me nan", "那么难" }, { "na me yuan", "那么远" }, { "na men", "纳闷" }, { "na mi", "纳米" }, { "na mi ji shu", "纳米技术" },
			{ "na mian", "那面" }, { "na ming", "那名" }, { "na mo", "南无" }, { "na mo", "那末" }, { "na na", "娜娜" }, { "na nan", "那男" }, { "na ne", "哪呢" },
			{ "na neng", "哪能" }, { "na nian", "那年" }, { "na nie", "拿捏" }, { "na nin", "那您" }, { "na nv", "那女" }, { "na nv ren", "那女人" }, { "na pa", "哪怕" },
			{ "na pa", "那怕" }, { "na pi", "那批" }, { "na pian", "那片" }, { "na pian", "那篇" }, { "na po lun", "拿破仑" }, { "na qi", "拿起" }, { "na qian", "拿钱" },
			{ "na qu", "哪去" }, { "na qu", "拿去" }, { "na qun", "那群" }, { "na ren", "那人" }, { "na ri", "那日" }, { "na ru", "纳入" }, { "na shang", "拿上" },
			{ "na shen me", "拿什么" }, { "na shi", "哪是" }, { "na shi", "纳什" }, { "na shi", "那时" }, { "na shi", "那是" }, { "na shi hou", "那时候" },
			{ "na shi wo", "那是我" }, { "na shou", "拿手" }, { "na shou", "那首" }, { "na shou ge", "那首歌" }, { "na shuang", "那双" }, { "na shui", "纳税" },
			{ "na shui ren", "纳税人" }, { "na shui shen bao", "纳税申报" }, { "na si", "纳斯" }, { "na si", "那厮" }, { "na si da ke", "纳斯达克" }, { "na ta", "那他" },
			{ "na tai", "那台" }, { "na tao", "那套" }, { "na tian", "哪天" }, { "na tian", "那天" }, { "na tian wan shang", "那天晚上" }, { "na tiao", "哪条" },
			{ "na tiao", "那条" }, { "na tou", "那头" }, { "na wan", "那晚" }, { "na wei", "哪位" }, { "na wei", "那位" }, { "na wo jiu", "那我就" }, { "na xi", "纳西" },
			{ "na xia", "拿下" }, { "na xiang", "哪像" }, { "na xiao zi", "那小子" }, { "na xie", "哪些" }, { "na xie", "那些" }, { "na xie di fang", "哪些地方" },
			{ "na xie fang mian", "哪些方面" }, { "na xie ren", "哪些人" }, { "na xie ren", "那些人" }, { "na yang", "哪样" }, { "na yang", "那样" },
			{ "na yang zi", "那样子" }, { "na yao", "那要" }, { "na ye", "那也" }, { "na ye shi", "那也是" }, { "na yi", "哪一" }, { "na yi", "那一" },
			{ "na yi ci", "那一次" }, { "na yi ke", "那一刻" }, { "na yi nian", "那一年" }, { "na yi shun jian", "那一瞬间" }, { "na yi tian", "哪一天" },
			{ "na yi tian", "那一天" }, { "na yi ye", "那一夜" }, { "na yi zhong", "那一种" }, { "na ying", "那英" }, { "na you", "哪有" }, { "na you", "那又" },
			{ "na you", "那有" }, { "na zhang", "那张" }, { "na zhe", "拿着" }, { "na zhi", "哪只" }, { "na zhi", "哪知" }, { "na zhi", "那只" }, { "na zhi", "那支" },
			{ "na zhong", "哪种" }, { "na zhong", "那种" }, { "na zhong gan jue", "那种感觉" }, { "na zou", "拿走" }, { "na zuo", "那座" }, { "nai", "乃" }, { "nai", "佴" },
			{ "nai", "倷" }, { "nai", "奈" }, { "nai", "奶" }, { "nai", "孻" }, { "nai", "廼" }, { "nai", "柰" }, { "nai", "氖" }, { "nai", "渿" }, { "nai", "耏" },
			{ "nai", "耐" }, { "nai", "艿" }, { "nai", "萘" }, { "nai", "褦" }, { "nai", "迺" }, { "nai", "釢" }, { "nai", "錼" }, { "nai", "鼐" },
			{ "nai bu zhu", "耐不住" }, { "nai cha", "奶茶" }, { "nai fen", "奶粉" }, { "nai gao wen", "耐高温" }, { "nai he", "奈何" }, { "nai jiu", "耐久" },
			{ "nai kan", "耐看" }, { "nai ke", "耐克" }, { "nai lao", "奶酪" }, { "nai li", "耐力" }, { "nai ma", "奶妈" }, { "nai mo", "耐磨" }, { "nai nai", "奶奶" },
			{ "nai niu", "奶牛" }, { "nai ping", "奶瓶" }, { "nai re", "耐热" }, { "nai ren xun wei", "耐人寻味" }, { "nai shi", "乃是" }, { "nai shou", "耐受" },
			{ "nai shui", "奶水" }, { "nai tou", "奶头" }, { "nai xin", "耐心" }, { "nai xing", "耐性" }, { "nai yao", "耐药" }, { "nai yao xing", "耐药性" },
			{ "nai ye", "奶业" }, { "nai yong", "耐用" }, { "nai you", "奶油" }, { "nai zhi", "乃至" }, { "nai zhi pin", "奶制品" }, { "nai zi", "奶子" },
			{ "nai zui", "奶嘴" }, { "nan", "南" }, { "nan", "喃" }, { "nan", "囝" }, { "nan", "囡" }, { "nan", "妠" }, { "nan", "娚" }, { "nan", "婻" },
			{ "nan", "嫨" }, { "nan", "戁" }, { "nan", "抩" }, { "nan", "揇" }, { "nan", "暔" }, { "nan", "枏" }, { "nan", "柟" }, { "nan", "楠" }, { "nan", "湳" },
			{ "nan", "男" }, { "nan", "腩" }, { "nan", "莮" }, { "nan", "萳" }, { "nan", "蝻" }, { "nan", "諵" }, { "nan", "赧" }, { "nan", "遖" }, { "nan", "难" },
			{ "nan", "難" }, { "nan an", "南岸" }, { "nan ao", "难熬" }, { "nan ban", "难办" }, { "nan bao", "难保" }, { "nan bei", "南北" }, { "nan bei chao", "南北朝" },
			{ "nan bian", "南边" }, { "nan bu", "南部" }, { "nan bu cheng", "难不成" }, { "nan ce", "南侧" }, { "nan chan", "难产" }, { "nan chan", "难缠" },
			{ "nan chang", "南昌" }, { "nan chang shi", "南昌市" }, { "nan chao", "南朝" }, { "nan cheng", "南城" }, { "nan chi", "难吃" }, { "nan chong", "南充" },
			{ "nan chu", "难处" }, { "nan da", "南大" }, { "nan da", "难打" }, { "nan dan", "男单" }, { "nan dao", "难倒" }, { "nan dao", "难道" }, { "nan de", "难得" },
			{ "nan de yi jian", "难得一见" }, { "nan dian", "难点" }, { "nan dong", "难懂" }, { "nan du", "南都" }, { "nan du", "难度" }, { "nan duan", "南端" },
			{ "nan er", "男儿" }, { "nan fang", "南方" }, { "nan fang", "男方" }, { "nan fang ren", "南方人" }, { "nan fang zhou mo", "南方周末" }, { "nan fei", "南非" },
			{ "nan feng", "南风" }, { "nan gao", "难搞" }, { "nan ge shou", "男歌手" }, { "nan gong", "南宫" }, { "nan gua", "南瓜" }, { "nan guai", "难怪" },
			{ "nan guan", "难关" }, { "nan guo", "南国" }, { "nan guo", "难过" }, { "nan hai", "南海" }, { "nan hai", "男孩" }, { "nan hai er", "男孩儿" },
			{ "nan hai zi", "男孩子" }, { "nan han", "南韩" }, { "nan hang", "南航" }, { "nan hu", "南湖" }, { "nan hua", "南华" }, { "nan hui", "南汇" },
			{ "nan ji", "南极" }, { "nan jiang", "南疆" }, { "nan jiao", "南郊" }, { "nan jie", "南街" }, { "nan jie", "难解" }, { "nan jing", "南京" },
			{ "nan jing da xue", "南京大学" }, { "nan jing lu", "南京路" }, { "nan jing ren", "南京人" }, { "nan jing shi", "南京市" }, { "nan jing xi lu", "南京西路" },
			{ "nan kai", "南开" }, { "nan kai da xue", "南开大学" }, { "nan kan", "难堪" }, { "nan kan", "难看" }, { "nan lan", "男篮" }, { "nan lu", "南路" },
			{ "nan mai", "难买" }, { "nan mei", "南美" }, { "nan mei zhou", "南美洲" }, { "nan men", "南门" }, { "nan mi", "难觅" }, { "nan mian", "南面" },
			{ "nan mian", "难免" }, { "nan min", "难民" }, { "nan nai", "难耐" }, { "nan nan", "喃喃" }, { "nan nan", "囡囡" }, { "nan nan", "楠楠" },
			{ "nan nan nv nv", "男男女女" }, { "nan nan zi yu", "喃喃自语" }, { "nan neng ke gui", "难能可贵" }, { "nan ning", "南宁" }, { "nan ning shi", "南宁市" },
			{ "nan nv", "男女" }, { "nan nv guan xi", "男女关系" }, { "nan nv lao shao", "男女老少" }, { "nan nv peng you", "男女朋友" }, { "nan nv ping deng", "男女平等" },
			{ "nan nv zhi jian", "男女之间" }, { "nan nv zhu jue", "男女主角" }, { "nan pai", "男排" }, { "nan peng you", "男朋友" }, { "nan ping", "南坪" },
			{ "nan ping", "南平" }, { "nan qi", "南汽" }, { "nan qiao", "南桥" }, { "nan qing nian", "男青年" }, { "nan qiu", "难求" }, { "nan qu", "南区" },
			{ "nan ren", "男人" }, { "nan ren", "难忍" }, { "nan ren bu", "男人不" }, { "nan ren dou", "男人都" }, { "nan ren wei", "男人味" }, { "nan sha", "南沙" },
			{ "nan shan", "南山" }, { "nan shan qu", "南山区" }, { "nan sheng", "男声" }, { "nan sheng", "男生" }, { "nan shi", "男士" }, { "nan shi", "男式" },
			{ "nan shi", "难事" }, { "nan shou", "难受" }, { "nan shui bei diao", "南水北调" }, { "nan shuo", "难说" }, { "nan si la fu", "南斯拉夫" }, { "nan song", "南宋" },
			{ "nan tao", "难逃" }, { "nan ti", "难题" }, { "nan tian", "南天" }, { "nan ting", "难听" }, { "nan tong", "南通" }, { "nan tong", "男童" },
			{ "nan tong shi", "南通市" }, { "nan tong xue", "男同学" }, { "nan wang", "难忘" }, { "nan wei", "难为" }, { "nan wei qing", "难为情" }, { "nan wen", "难闻" },
			{ "nan wu", "南无" }, { "nan xia", "南下" }, { "nan xing", "男性" }, { "nan xing", "男星" }, { "nan ya", "南亚" }, { "nan yan", "难掩" }, { "nan yan", "难言" },
			{ "nan yan yuan", "男演员" }, { "nan yang", "南洋" }, { "nan yang", "南阳" }, { "nan yi", "难以" }, { "nan yi", "难易" }, { "nan yi ren shou", "难以忍受" },
			{ "nan yi wang huai", "难以忘怀" }, { "nan yi xiang xiang", "难以想象" }, { "nan yi zhi xin", "难以置信" }, { "nan ying", "男婴" }, { "nan you", "男友" },
			{ "nan you", "难有" }, { "nan yu", "难于" }, { "nan yuan", "南苑" }, { "nan zhan", "南站" }, { "nan zhao", "难找" }, { "nan zhi", "南至" },
			{ "nan zhu jue", "男主角" }, { "nan zhuang", "男装" }, { "nan zi", "男子" }, { "nan zi han", "男子汉" }, { "nan zu", "男足" }, { "nan zuo", "难做" },
			{ "nang", "嚢" }, { "nang", "囊" }, { "nang", "囔" }, { "nang", "擃" }, { "nang", "攮" }, { "nang", "曩" }, { "nang", "涳" }, { "nang", "灢" },
			{ "nang", "馕" }, { "nang", "鬞" }, { "nang", "齉" }, { "nang kuo", "囊括" }, { "nang zhong", "囊中" }, { "nang zhong", "囊肿" }, { "nao", "呶" },
			{ "nao", "垴" }, { "nao", "夒" }, { "nao", "婥" }, { "nao", "嫐" }, { "nao", "孬" }, { "nao", "峱" }, { "nao", "嶩" }, { "nao", "恼" }, { "nao", "悩" },
			{ "nao", "惱" }, { "nao", "挠" }, { "nao", "撓" }, { "nao", "淖" }, { "nao", "猱" }, { "nao", "獿" }, { "nao", "瑙" }, { "nao", "硇" }, { "nao", "碙" },
			{ "nao", "碯" }, { "nao", "脑" }, { "nao", "脳" }, { "nao", "腦" }, { "nao", "臑" }, { "nao", "蛲" }, { "nao", "蟯" }, { "nao", "鐃" }, { "nao", "铙" },
			{ "nao", "閙" }, { "nao", "闹" }, { "nao", "鬧" }, { "nao bai jin", "脑白金" }, { "nao bu", "脑部" }, { "nao chu", "闹出" }, { "nao chu xue", "脑出血" },
			{ "nao dai", "脑袋" }, { "nao de", "闹得" }, { "nao fan", "闹翻" }, { "nao geng si", "脑梗死" }, { "nao hai", "脑海" }, { "nao hai li", "脑海里" },
			{ "nao hou", "脑后" }, { "nao huo", "恼火" }, { "nao jin", "脑筋" }, { "nao ju", "闹剧" }, { "nao ke", "脑壳" }, { "nao li", "脑力" }, { "nao men", "脑门" },
			{ "nao nao", "闹闹" }, { "nao nu", "恼怒" }, { "nao shi", "闹事" }, { "nao shi", "闹市" }, { "nao tan", "脑瘫" }, { "nao teng", "闹腾" },
			{ "nao xi bao", "脑细胞" }, { "nao xin", "闹心" }, { "nao xiu cheng nu", "恼羞成怒" }, { "nao zhe", "闹着" }, { "nao zhong", "脑中" }, { "nao zhong", "闹钟" },
			{ "nao zi", "脑子" }, { "nao zi li", "脑子里" }, { "ne", "吶" }, { "ne", "呐" }, { "ne", "呢" }, { "ne", "哪" }, { "ne", "眲" }, { "ne", "訥" },
			{ "ne", "讷" }, { "ne ge", "呢个" }, { "ne zha", "哪吒" }, { "nei", "內" }, { "nei", "内" }, { "nei", "哪" }, { "nei", "氝" }, { "nei", "腇" },
			{ "nei", "那" }, { "nei", "餒" }, { "nei", "馁" }, { "nei bi", "内壁" }, { "nei bian", "那边" }, { "nei bu", "内部" }, { "nei bu guan li", "内部管理" },
			{ "nei bu jie gou", "内部结构" }, { "nei bu kong zhi", "内部控制" }, { "nei bu shen ji", "内部审计" }, { "nei can", "内参" }, { "nei ce", "内侧" },
			{ "nei ce", "内测" }, { "nei ci", "那次" }, { "nei cun", "内存" }, { "nei cun tiao", "内存条" }, { "nei dan", "内胆" }, { "nei di", "内地" },
			{ "nei ding", "内定" }, { "nei fen mi", "内分泌" }, { "nei fu", "内服" }, { "nei ge", "内阁" }, { "nei gong", "内功" }, { "nei han", "内含" },
			{ "nei han", "内涵" }, { "nei hang", "内行" }, { "nei he", "内核" }, { "nei he", "内河" }, { "nei hong", "内讧" }, { "nei huan", "内环" }, { "nei jia", "那家" },
			{ "nei jia de", "内贾德" }, { "nei jian", "内建" }, { "nei jiang", "内将" }, { "nei jiang", "内江" }, { "nei jing", "内镜" }, { "nei jiu", "内疚" },
			{ "nei ke", "内科" }, { "nei kong", "内控" }, { "nei ku", "内裤" }, { "nei li", "内力" }, { "nei lian", "内敛" }, { "nei lu", "内陆" }, { "nei meng", "内蒙" },
			{ "nei meng gu", "内蒙古" }, { "nei mo", "内膜" }, { "nei mu", "内幕" }, { "nei qian", "内嵌" }, { "nei qin", "内勤" }, { "nei qing", "内情" },
			{ "nei ran ji", "内燃机" }, { "nei rong", "内容" }, { "nei rong bao kuo", "内容包括" }, { "nei rong jun", "内容均" }, { "nei shang", "内伤" },
			{ "nei she", "内设" }, { "nei shen", "内审" }, { "nei shi", "内饰" }, { "nei shi hou", "那时候" }, { "nei si ta", "内斯塔" }, { "nei tai", "那台" },
			{ "nei tian", "那天" }, { "nei wai", "内外" }, { "nei wang", "内网" }, { "nei wei", "那位" }, { "nei wu", "内务" }, { "nei xian", "内线" },
			{ "nei xiang", "内向" }, { "nei xiao", "内销" }, { "nei xin", "内心" }, { "nei xin shi jie", "内心世界" }, { "nei xu", "内需" }, { "nei ye", "内页" },
			{ "nei yi", "内衣" }, { "nei yin", "内因" }, { "nei you", "内有" }, { "nei zai", "内在" }, { "nei zang", "内脏" }, { "nei zhan", "内战" },
			{ "nei zhang", "那张" }, { "nei zheng", "内政" }, { "nei zhi", "内置" }, { "nei zhong", "那种" }, { "nei zi", "内资" }, { "nen", "嫩" }, { "nen", "恁" },
			{ "nen fu", "嫩肤" }, { "nen nen", "嫩嫩" }, { "neng", "能" }, { "neng", "螚" }, { "neng ba", "能把" }, { "neng bang", "能帮" }, { "neng bei", "能被" },
			{ "neng bi", "能比" }, { "neng bu", "能不" }, { "neng bu", "能补" }, { "neng chi", "能吃" }, { "neng cong", "能从" }, { "neng da", "能打" },
			{ "neng dai", "能带" }, { "neng dao", "能到" }, { "neng dong", "能动" }, { "neng dui", "能对" }, { "neng duo", "能多" }, { "neng fou", "能否" },
			{ "neng gai", "能改" }, { "neng gan", "能干" }, { "neng gei", "能给" }, { "neng gou", "能够" }, { "neng guo", "能过" }, { "neng hao", "能耗" },
			{ "neng huo", "能活" }, { "neng jian du", "能见度" }, { "neng jiang", "能将" }, { "neng jin", "能进" }, { "neng kan", "能看" }, { "neng li", "能力" },
			{ "neng li cha", "能力差" }, { "neng li jian she", "能力建设" }, { "neng li qiang", "能力强" }, { "neng liang", "能量" }, { "neng mai", "能卖" },
			{ "neng mai dao", "能买到" }, { "neng na dao", "能拿到" }, { "neng nai", "能耐" }, { "neng qu", "能去" }, { "neng rang", "能让" }, { "neng ren", "能人" },
			{ "neng shang wang", "能上网" }, { "neng shi", "能使" }, { "neng shou", "能手" }, { "neng shuo", "能说" }, { "neng ting", "能听" }, { "neng wan", "能玩" },
			{ "neng wei", "能为" }, { "neng xiang", "能像" }, { "neng xiao", "能效" }, { "neng xie", "能写" }, { "neng yi", "能以" }, { "neng ying", "能赢" },
			{ "neng yong", "能用" }, { "neng you", "能有" }, { "neng yu", "能与" }, { "neng yuan", "能源" }, { "neng yuan xiao hao", "能源消耗" } };
};
