package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN07 {
	public static String[][] pl = { { "chong ming", "崇明" }, { "chong ming", "重名" }, { "chong ming ming", "重命名" }, { "chong pai", "重拍" }, { "chong pao", "冲泡" },
			{ "chong pei", "充沛" }, { "chong po", "冲破" }, { "chong qi", "充气" }, { "chong qi", "重启" }, { "chong qi hou", "重启后" }, { "chong qi liang", "充其量" },
			{ "chong qing", "重庆" }, { "chong qing shi", "重庆市" }, { "chong qu", "冲去" }, { "chong ru", "冲入" }, { "chong shang", "冲上" }, { "chong shang", "崇尚" },
			{ "chong shang qu", "冲上去" }, { "chong shen", "重申" }, { "chong sheng", "冲绳" }, { "chong sheng", "重生" }, { "chong shi", "充实" },
			{ "chong shi", "重拾" }, { "chong shi", "重试" }, { "chong shua", "冲刷" }, { "chong su", "重塑" }, { "chong tian", "充填" }, { "chong tian", "冲天" },
			{ "chong tu", "冲突" }, { "chong wen", "重温" }, { "chong wen men", "崇文门" }, { "chong wen qu", "崇文区" }, { "chong wo", "冲我" }, { "chong wu", "宠物" },
			{ "chong xi", "冲洗" }, { "chong xian", "重现" }, { "chong xiang", "冲向" }, { "chong xie", "重写" }, { "chong xin", "重新" },
			{ "chong xin an zhuang", "重新安装" }, { "chong xin hui dao", "重新回到" }, { "chong xin kai shi", "重新开始" }, { "chong xin qi dong", "重新启动" },
			{ "chong xin ren shi", "重新认识" }, { "chong xiu", "重修" }, { "chong xue", "充血" }, { "chong ya", "冲压" }, { "chong yan", "重演" }, { "chong yang", "重阳" },
			{ "chong yang jie", "重阳节" }, { "chong yang mei wai", "崇洋媚外" }, { "chong yin", "冲印" }, { "chong ying", "充盈" }, { "chong yong", "重用" },
			{ "chong yu", "充裕" }, { "chong zai", "重载" }, { "chong zhe", "冲着" }, { "chong zhen", "崇祯" }, { "chong zhen", "重振" }, { "chong zheng", "重整" },
			{ "chong zhi", "充值" }, { "chong zhi", "重置" }, { "chong zhi ka", "充值卡" }, { "chong zhuang", "冲撞" }, { "chong zhuang", "重装" },
			{ "chong zhuang xi tong", "重装系统" }, { "chong zi", "虫子" }, { "chong zu", "充足" }, { "chong zu", "重组" }, { "chong zuo", "重做" }, { "chou", "丑" },
			{ "chou", "仇" }, { "chou", "俦" }, { "chou", "吜" }, { "chou", "嬦" }, { "chou", "帱" }, { "chou", "惆" }, { "chou", "愁" }, { "chou", "懤" },
			{ "chou", "抽" }, { "chou", "杻" }, { "chou", "杽" }, { "chou", "栦" }, { "chou", "殠" }, { "chou", "燽" }, { "chou", "犨" }, { "chou", "畴" },
			{ "chou", "疇" }, { "chou", "瘳" }, { "chou", "瞅" }, { "chou", "稠" }, { "chou", "筹" }, { "chou", "篘" }, { "chou", "籌" }, { "chou", "絒" },
			{ "chou", "綢" }, { "chou", "绸" }, { "chou", "臭" }, { "chou", "菗" }, { "chou", "讎" }, { "chou", "讐" }, { "chou", "踌" }, { "chou", "躊" },
			{ "chou", "酬" }, { "chou", "醜" }, { "chou", "雔" }, { "chou", "雠" }, { "chou ban", "筹办" }, { "chou bei", "筹备" }, { "chou bei gong zuo", "筹备工作" },
			{ "chou cha", "抽插" }, { "chou cha", "抽查" }, { "chou chang", "惆怅" }, { "chou chong", "臭虫" }, { "chou chou", "丑丑" }, { "chou chou", "瞅瞅" },
			{ "chou chou", "臭臭" }, { "chou chu", "抽出" }, { "chou chu", "抽搐" }, { "chou chu", "踌躇" }, { "chou cuo", "筹措" }, { "chou dao", "抽到" },
			{ "chou diao", "抽调" }, { "chou dong", "抽动" }, { "chou dou fu", "臭豆腐" }, { "chou duan", "绸缎" }, { "chou e", "丑恶" }, { "chou feng", "抽风" },
			{ "chou hen", "仇恨" }, { "chou hua", "丑化" }, { "chou hua", "筹划" }, { "chou ji", "筹集" }, { "chou ji zi jin", "筹集资金" }, { "chou jia", "仇家" },
			{ "chou jian", "抽检" }, { "chou jian", "筹建" }, { "chou jiang", "抽奖" }, { "chou jin", "抽筋" }, { "chou jin", "酬金" }, { "chou kong", "抽空" },
			{ "chou kuan", "筹款" }, { "chou lao", "酬劳" }, { "chou lou", "丑陋" }, { "chou ma", "筹码" }, { "chou mei", "臭美" }, { "chou nv", "丑女" },
			{ "chou pi", "臭屁" }, { "chou qi", "抽泣" }, { "chou qi", "臭气" }, { "chou qian", "抽签" }, { "chou qu", "抽取" }, { "chou ren", "仇人" },
			{ "chou she", "抽射" }, { "chou shen", "抽身" }, { "chou shi", "仇视" }, { "chou ti", "抽屉" }, { "chou wei", "臭味" }, { "chou wen", "丑闻" },
			{ "chou xiang", "抽象" }, { "chou xiao ya", "丑小鸭" }, { "chou xue", "抽血" }, { "chou yan", "抽烟" }, { "chou yang", "抽样" }, { "chou yang", "臭氧" },
			{ "chou yang diao cha", "抽样调查" }, { "chou zhe", "抽着" }, { "chou zhe", "瞅着" }, { "chou zi", "筹资" }, { "chu", "亍" }, { "chu", "俶" }, { "chu", "储" },
			{ "chu", "儊" }, { "chu", "儲" }, { "chu", "処" }, { "chu", "出" }, { "chu", "刍" }, { "chu", "初" }, { "chu", "厨" }, { "chu", "处" }, { "chu", "幮" },
			{ "chu", "廚" }, { "chu", "怵" }, { "chu", "憷" }, { "chu", "懨" }, { "chu", "搐" }, { "chu", "摴" }, { "chu", "敊" }, { "chu", "斶" }, { "chu", "杵" },
			{ "chu", "楚" }, { "chu", "楮" }, { "chu", "樗" }, { "chu", "橱" }, { "chu", "檚" }, { "chu", "櫥" }, { "chu", "歜" }, { "chu", "滀" }, { "chu", "滁" },
			{ "chu", "濋" }, { "chu", "犓" }, { "chu", "珿" }, { "chu", "琡" }, { "chu", "畜" }, { "chu", "矗" }, { "chu", "础" }, { "chu", "礎" }, { "chu", "篨" },
			{ "chu", "絀" }, { "chu", "绌" }, { "chu", "耡" }, { "chu", "臅" }, { "chu", "芻" }, { "chu", "蒢" }, { "chu", "蒭" }, { "chu", "處" }, { "chu", "蜍" },
			{ "chu", "褚" }, { "chu", "触" }, { "chu", "觸" }, { "chu", "豖" }, { "chu", "貙" }, { "chu", "趎" }, { "chu", "蹰" }, { "chu", "躇" }, { "chu", "躕" },
			{ "chu", "鄐" }, { "chu", "鋤" }, { "chu", "锄" }, { "chu", "除" }, { "chu", "雏" }, { "chu", "雛" }, { "chu", "鶵" }, { "chu", "黜" }, { "chu", "齣" },
			{ "chu ban", "出版" }, { "chu ban", "除斑" }, { "chu ban fa xing", "出版发行" }, { "chu ban shang", "出版商" }, { "chu ban she", "出版社" },
			{ "chu ban wu", "出版物" }, { "chu ban ye", "出版业" }, { "chu bei", "储备" }, { "chu bing", "出兵" }, { "chu bu", "初步" }, { "chu bu lai", "出不来" },
			{ "chu bu liao", "出不了" }, { "chu bu xing cheng", "初步形成" }, { "chu bu yan jiu", "初步研究" }, { "chu cai", "出彩" }, { "chu cang", "储藏" },
			{ "chu chai", "出差" }, { "chu chan", "出产" }, { "chu chang", "出厂" }, { "chu chang", "出场" }, { "chu chang jia", "出厂价" },
			{ "chu chang jia ge", "出厂价格" }, { "chu che huo", "出车祸" }, { "chu chen", "除尘" }, { "chu cheng", "出城" }, { "chu chou", "出丑" }, { "chu chu", "出处" },
			{ "chu chu", "处处" }, { "chu chu", "楚楚" }, { "chu chu zhang", "处处长" }, { "chu chuang", "橱窗" }, { "chu chun", "初春" }, { "chu ci", "初次" },
			{ "chu ci", "除此" }, { "chu ci zhi wai", "除此之外" }, { "chu cun", "储存" }, { "chu cuo", "出错" }, { "chu dao", "出道" }, { "chu dao", "初到" },
			{ "chu dao", "触到" }, { "chu de", "出的" }, { "chu dian", "触点" }, { "chu dian", "触电" }, { "chu diao", "除掉" }, { "chu ding", "初定" },
			{ "chu dong", "出动" }, { "chu dong", "触动" }, { "chu er", "初二" }, { "chu fa", "出发" }, { "chu fa", "处罚" }, { "chu fa", "触发" },
			{ "chu fa dian", "出发点" }, { "chu fa qi", "触发器" }, { "chu fan", "触犯" }, { "chu fang", "出访" }, { "chu fang", "厨房" }, { "chu fang", "处方" },
			{ "chu fang li", "厨房里" }, { "chu fang yao", "处方药" }, { "chu fei", "除非" }, { "chu fen", "处分" }, { "chu gan", "触感" }, { "chu gao", "初稿" },
			{ "chu ge", "出个" }, { "chu ge", "出格" }, { "chu guan", "出关" }, { "chu gui", "出轨" }, { "chu gui", "橱柜" }, { "chu guo", "出国" }, { "chu guo", "出过" },
			{ "chu guo", "出锅" }, { "chu guo", "楚国" }, { "chu guo liu xue", "出国留学" }, { "chu hai", "出海" }, { "chu han", "出汗" }, { "chu hu", "储户" },
			{ "chu hu", "出乎" }, { "chu hu yi liao", "出乎意料" }, { "chu huo", "出货" }, { "chu huo liang", "出货量" }, { "chu ji", "出击" }, { "chu ji", "初级" },
			{ "chu ji", "触及" }, { "chu ji jie duan", "初级阶段" }, { "chu jia", "出价" }, { "chu jia", "出嫁" }, { "chu jia", "出家" }, { "chu jia ren", "出家人" },
			{ "chu jian", "初见" }, { "chu jiao", "触角" }, { "chu jin", "出尽" }, { "chu jing", "出境" }, { "chu jing", "出镜" }, { "chu jing", "处境" },
			{ "chu jing you", "出境游" }, { "chu ju", "出具" }, { "chu ju", "出局" }, { "chu ju", "厨具" }, { "chu ju gui mo", "初具规模" }, { "chu jue", "处决" },
			{ "chu jue", "触觉" }, { "chu kou", "出口" }, { "chu kou chan pin", "出口产品" }, { "chu kou chuang hui", "出口创汇" }, { "chu kou e", "出口额" },
			{ "chu kou guo", "出口国" }, { "chu kou liang", "出口量" }, { "chu kou qi ye", "出口企业" }, { "chu kou ri ben", "出口日本" }, { "chu kou shang", "出口商" },
			{ "chu kou shang pin", "出口商品" }, { "chu kou tui shui", "出口退税" }, { "chu ku", "出库" }, { "chu lai", "出来" }, { "chu lai", "初来" },
			{ "chu lai hun", "出来混" }, { "chu lai zha dao", "初来乍到" }, { "chu lan", "出栏" }, { "chu le", "出了" }, { "chu le", "除了" }, { "chu lei ba cui", "出类拔萃" },
			{ "chu li", "出力" }, { "chu li", "处理" }, { "chu li", "矗立" }, { "chu li fang fa", "处理方法" }, { "chu li fang shi", "处理方式" },
			{ "chu li ji shu", "处理技术" }, { "chu li jie guo", "处理结果" }, { "chu li neng li", "处理能力" }, { "chu li qi", "处理器" }, { "chu li wen ti", "处理问题" },
			{ "chu li yi jian", "处理意见" }, { "chu lian", "初恋" }, { "chu lian qing ren", "初恋情人" }, { "chu liang", "储量" }, { "chu liu xiang", "楚留香" },
			{ "chu long", "出笼" }, { "chu lu", "出炉" }, { "chu lu", "出路" }, { "chu ma", "出马" }, { "chu mai", "出卖" }, { "chu men", "出门" },
			{ "chu men zai wai", "出门在外" }, { "chu mian", "出面" }, { "chu ming", "出名" }, { "chu mo", "出没" }, { "chu mo", "触摸" }, { "chu mo ban", "触摸板" },
			{ "chu mo ping", "触摸屏" }, { "chu mou hua ce", "出谋划策" }, { "chu mu jing xin", "触目惊心" }, { "chu na", "出纳" }, { "chu nan", "处男" },
			{ "chu nian", "初年" }, { "chu nv", "处女" }, { "chu nv mo", "处女膜" }, { "chu nv zuo", "处女作" }, { "chu nv zuo", "处女座" }, { "chu pai", "出牌" },
			{ "chu peng", "触碰" }, { "chu piao", "出票" }, { "chu pin", "出品" }, { "chu qi", "出奇" }, { "chu qi", "出气" }, { "chu qi", "初期" },
			{ "chu qi bu yi", "出其不意" }, { "chu qian", "出钱" }, { "chu qin", "出勤" }, { "chu qin", "畜禽" }, { "chu qiu", "初秋" }, { "chu qu", "出去" },
			{ "chu qu", "除去" }, { "chu qu wan", "出去玩" }, { "chu quan", "除权" }, { "chu rang", "出让" }, { "chu ren", "出任" }, { "chu ren tou di", "出人头地" },
			{ "chu ren yi liao", "出人意料" }, { "chu ru", "出入" }, { "chu ru jing", "出入境" }, { "chu ru kou", "出入口" }, { "chu sai", "初赛" }, { "chu san", "初三" },
			{ "chu se", "出色" }, { "chu shan", "出山" }, { "chu shen", "出神" }, { "chu shen", "出身" }, { "chu shen", "初审" }, { "chu shen me", "出什么" },
			{ "chu shen ru hua", "出神入化" }, { "chu sheng", "出声" }, { "chu sheng", "出生" }, { "chu sheng", "初生" }, { "chu sheng", "畜牲" }, { "chu sheng", "畜生" },
			{ "chu sheng di", "出生地" }, { "chu sheng nian yue", "出生年月" }, { "chu sheng ri qi", "出生日期" }, { "chu shi", "出世" }, { "chu shi", "出事" },
			{ "chu shi", "出师" }, { "chu shi", "出示" }, { "chu shi", "初始" }, { "chu shi", "初试" }, { "chu shi", "厨师" }, { "chu shi", "处世" }, { "chu shi", "处事" },
			{ "chu shi", "处室" }, { "chu shi hua", "初始化" }, { "chu shou", "出售" }, { "chu shou", "出手" }, { "chu shou", "触手" }, { "chu shu", "出书" },
			{ "chu shui", "出水" }, { "chu si", "处死" }, { "chu tai", "出台" }, { "chu tan", "初探" }, { "chu tao", "出逃" }, { "chu ti", "出题" }, { "chu tian", "楚天" },
			{ "chu ting", "出庭" }, { "chu tou", "出头" }, { "chu tou", "锄头" }, { "chu tu", "出土" }, { "chu wai", "出外" }, { "chu wai", "除外" }, { "chu wang", "楚王" },
			{ "chu wei", "出位" }, { "chu wei", "厨卫" }, { "chu wen", "初吻" }, { "chu wen ti", "出问题" }, { "chu xi", "出席" }, { "chu xi", "出息" }, { "chu xi", "出戏" },
			{ "chu xi", "除夕" }, { "chu xi hui yi", "出席会议" }, { "chu xia", "初夏" }, { "chu xian", "出现" }, { "chu xian", "出线" }, { "chu xian", "初现" },
			{ "chu xian cuo wu", "出现错误" }, { "chu xian gu zhang", "出现故障" }, { "chu xian wen ti", "出现问题" }, { "chu xie", "出血" }, { "chu xin", "出新" },
			{ "chu xing", "出行" }, { "chu xing", "雏形" }, { "chu xu", "储蓄" }, { "chu xu cun kuan", "储蓄存款" }, { "chu xuan", "初选" }, { "chu xue", "出血" },
			{ "chu xue", "初学" }, { "chu xue zhe", "初学者" }, { "chu yan", "出演" }, { "chu ye", "初夜" }, { "chu yi", "刍议" }, { "chu yi", "初一" }, { "chu yi", "厨艺" },
			{ "chu yi", "处以" }, { "chu yi", "除以" }, { "chu you", "出油" }, { "chu you", "出游" }, { "chu yu", "出于" }, { "chu yu", "出狱" }, { "chu yu", "处于" },
			{ "chu yuan", "出院" }, { "chu yun", "储运" }, { "chu zai", "处在" }, { "chu zhan", "出战" }, { "chu zhan", "出站" }, { "chu zhang", "处长" },
			{ "chu zhao", "出招" }, { "chu zheng", "出征" }, { "chu zhi", "处置" }, { "chu zhong", "出众" }, { "chu zhong", "初中" }, { "chu zhong", "初衷" },
			{ "chu zhong bi ye", "初中毕业" }, { "chu zhong sheng", "初中生" }, { "chu zhou", "滁州" }, { "chu zhu yi", "出主意" }, { "chu zi", "出自" }, { "chu zi", "出资" },
			{ "chu zi", "厨子" }, { "chu zi", "处子" }, { "chu zi ren", "出资人" }, { "chu zou", "出走" }, { "chu zu", "出租" }, { "chu zu che", "出租车" },
			{ "chu zu fang", "出租房" }, { "chu zu qi che", "出租汽车" }, { "chu zu wu", "出租屋" }, { "chua", "欻" }, { "chuai", "啜" }, { "chuai", "嘬" },
			{ "chuai", "揣" }, { "chuai", "搋" }, { "chuai", "欼" }, { "chuai", "膗" }, { "chuai", "膪" }, { "chuai", "踹" }, { "chuai ce", "揣测" },
			{ "chuai mo", "揣摩" }, { "chuai zhe", "揣着" }, { "chuan", "串" }, { "chuan", "传" }, { "chuan", "傳" }, { "chuan", "喘" }, { "chuan", "巛" },
			{ "chuan", "川" }, { "chuan", "暷" }, { "chuan", "椽" }, { "chuan", "歂" }, { "chuan", "氚" }, { "chuan", "汌" }, { "chuan", "玔" }, { "chuan", "瑏" },
			{ "chuan", "穿" }, { "chuan", "舛" }, { "chuan", "舡" }, { "chuan", "船" }, { "chuan", "荈" }, { "chuan", "賗" }, { "chuan", "踳" }, { "chuan", "輲" },
			{ "chuan", "遄" }, { "chuan", "釧" }, { "chuan", "钏" }, { "chuan bian", "传遍" }, { "chuan bo", "传播" }, { "chuan bo", "船舶" },
			{ "chuan bo xue", "传播学" }, { "chuan bu guo qi", "喘不过气" }, { "chuan cai", "川菜" }, { "chuan cha", "穿插" }, { "chuan chang", "传唱" },
			{ "chuan chang", "船厂" }, { "chuan cheng", "传承" }, { "chuan chu", "传出" }, { "chuan chu", "穿出" }, { "chuan chuan", "串串" }, { "chuan ci", "穿刺" },
			{ "chuan da", "传达" }, { "chuan da", "川大" }, { "chuan dai", "穿戴" }, { "chuan dan", "传单" }, { "chuan dao", "传到" }, { "chuan dao", "传导" },
			{ "chuan dao", "传道" }, { "chuan de", "传得" }, { "chuan de", "穿得" }, { "chuan de", "穿的" }, { "chuan di", "传递" }, { "chuan di xin xi", "传递信息" },
			{ "chuan dong", "传动" }, { "chuan dong", "船东" }, { "chuan dui", "船队" }, { "chuan gan", "传感" }, { "chuan gan qi", "传感器" }, { "chuan gei", "传给" },
			{ "chuan gong si", "船公司" }, { "chuan guo", "穿过" }, { "chuan hao", "串号" }, { "chuan hao", "穿好" }, { "chuan huan", "传唤" }, { "chuan hui", "传回" },
			{ "chuan jiao", "传教" }, { "chuan jiao shi", "传教士" }, { "chuan kai", "传开" }, { "chuan kong", "穿孔" }, { "chuan kou", "串口" }, { "chuan lai", "传来" },
			{ "chuan le", "穿了" }, { "chuan lian", "串联" }, { "chuan mei", "传媒" }, { "chuan mei ji tuan", "传媒集团" }, { "chuan men", "串门" },
			{ "chuan piao", "传票" }, { "chuan piao", "船票" }, { "chuan qi", "传奇" }, { "chuan qi", "喘气" }, { "chuan qi", "川崎" }, { "chuan qi", "船期" },
			{ "chuan qiu", "传球" }, { "chuan qun zi", "穿裙子" }, { "chuan ran", "传染" }, { "chuan ran bing", "传染病" }, { "chuan ran xing", "传染性" },
			{ "chuan re", "传热" }, { "chuan ren", "传人" }, { "chuan ru", "传入" }, { "chuan shang", "穿上" }, { "chuan shang", "船上" }, { "chuan shen", "传神" },
			{ "chuan shen me", "穿什么" }, { "chuan shi", "传世" }, { "chuan shi si fu", "传世私服" }, { "chuan shou", "传授" }, { "chuan shu", "传输" },
			{ "chuan shu su du", "传输速度" }, { "chuan shu su lv", "传输速率" }, { "chuan shuo", "传说" }, { "chuan song", "传送" }, { "chuan suo", "穿梭" },
			{ "chuan tong", "串通" }, { "chuan tong", "传统" }, { "chuan tong chan ye", "传统产业" }, { "chuan tong guan nian", "传统观念" },
			{ "chuan tong jie ri", "传统节日" }, { "chuan tong mei de", "传统美德" }, { "chuan tong mei ti", "传统媒体" }, { "chuan tong wen hua", "传统文化" },
			{ "chuan tou", "穿透" }, { "chuan tou", "船头" }, { "chuan tou li", "穿透力" }, { "chuan wen", "传闻" }, { "chuan xi", "喘息" }, { "chuan xi", "川西" },
			{ "chuan xiao", "传销" }, { "chuan xie", "穿鞋" }, { "chuan xing", "串行" }, { "chuan xing", "穿行" }, { "chuan yan", "传言" }, { "chuan yi", "穿衣" },
			{ "chuan yi fu", "穿衣服" }, { "chuan yuan", "船员" }, { "chuan yue", "穿越" }, { "chuan yue shi kong", "穿越时空" }, { "chuan zai", "穿在" },
			{ "chuan zhang", "船长" }, { "chuan zhe", "喘着" }, { "chuan zhe", "穿着" }, { "chuan zhen", "传真" }, { "chuan zhen ji", "传真机" }, { "chuan zhi", "船只" },
			{ "chuan zhong", "传中" }, { "chuan zhuo", "穿着" }, { "chuang", "傸" }, { "chuang", "创" }, { "chuang", "刱" }, { "chuang", "剏" }, { "chuang", "創" },
			{ "chuang", "幢" }, { "chuang", "床" }, { "chuang", "怆" }, { "chuang", "愴" }, { "chuang", "摐" }, { "chuang", "牀" }, { "chuang", "疮" },
			{ "chuang", "瘡" }, { "chuang", "磢" }, { "chuang", "窓" }, { "chuang", "窗" }, { "chuang", "闖" }, { "chuang", "闯" }, { "chuang ban", "创办" },
			{ "chuang ban ren", "创办人" }, { "chuang bian", "床边" }, { "chuang bian", "窗边" }, { "chuang chu", "创出" }, { "chuang dan", "床单" },
			{ "chuang dang", "闯荡" }, { "chuang dian", "床垫" }, { "chuang guan", "闯关" }, { "chuang hong deng", "闯红灯" }, { "chuang hu", "窗户" },
			{ "chuang ji lu", "创纪录" }, { "chuang jian", "创建" }, { "chuang jian gong zuo", "创建工作" }, { "chuang jian huo dong", "创建活动" },
			{ "chuang jian yi ge", "创建一个" }, { "chuang jin", "闯进" }, { "chuang ju", "创举" }, { "chuang kan", "创刊" }, { "chuang kou", "窗口" },
			{ "chuang kou zhong", "窗口中" }, { "chuang li", "创立" }, { "chuang lian", "窗帘" }, { "chuang mian", "创面" }, { "chuang pu", "床铺" },
			{ "chuang qian", "床前" }, { "chuang qian", "窗前" }, { "chuang ru", "闯入" }, { "chuang shang", "创伤" }, { "chuang shang", "床上" },
			{ "chuang shang yong pin", "床上用品" }, { "chuang she", "创设" }, { "chuang shi", "创世" }, { "chuang shi ji", "创世纪" }, { "chuang shi ren", "创始人" },
			{ "chuang shou", "创收" }, { "chuang tai", "窗台" }, { "chuang ti", "窗体" }, { "chuang tou", "创投" }, { "chuang tou", "床头" },
			{ "chuang tou gui", "床头柜" }, { "chuang wai", "窗外" }, { "chuang wei", "创卫" }, { "chuang wei", "创维" }, { "chuang wei", "床位" }, { "chuang xi", "床戏" },
			{ "chuang xia", "创下" }, { "chuang xia", "床下" }, { "chuang xin", "创新" }, { "chuang xin fa zhan", "创新发展" }, { "chuang xin gao", "创新高" },
			{ "chuang xin jing shen", "创新精神" }, { "chuang xin neng li", "创新能力" }, { "chuang xin xing", "创新型" }, { "chuang xin xing", "创新性" },
			{ "chuang xin yi shi", "创新意识" }, { "chuang ye", "创业" }, { "chuang ye ban", "创业板" }, { "chuang ye tou zi", "创业投资" }, { "chuang ye yuan", "创业园" },
			{ "chuang ye zhe", "创业者" }, { "chuang yi", "创意" }, { "chuang yi chan ye", "创意产业" }, { "chuang zao", "创造" }, { "chuang zao cai fu", "创造财富" },
			{ "chuang zao chu", "创造出" }, { "chuang zao jia zhi", "创造价值" }, { "chuang zao li", "创造力" }, { "chuang zao liang hao", "创造良好" },
			{ "chuang zao tiao jian", "创造条件" }, { "chuang zao xing", "创造性" }, { "chuang zao zhe", "创造者" }, { "chuang zi", "窗子" }, { "chuang zuo", "创作" },
			{ "chuang zuo zhe", "创作者" }, { "chui", "吹" }, { "chui", "圌" }, { "chui", "垂" }, { "chui", "捶" }, { "chui", "棰" }, { "chui", "椎" }, { "chui", "槌" },
			{ "chui", "炊" }, { "chui", "缍" }, { "chui", "菙" }, { "chui", "錘" }, { "chui", "鎚" }, { "chui", "锤" }, { "chui", "陲" }, { "chui chui", "吹吹" },
			{ "chui de", "吹得" }, { "chui diao", "垂钓" }, { "chui feng", "吹风" }, { "chui feng ji", "吹风机" }, { "chui fu", "吹拂" }, { "chui guo", "吹过" },
			{ "chui lai", "吹来" }, { "chui lian", "锤炼" }, { "chui niu", "吹牛" }, { "chui peng", "吹捧" }, { "chui qi", "吹起" }, { "chui qing", "垂青" },
			{ "chui shui", "吹水" }, { "chui tou sang qi", "垂头丧气" }, { "chui xia", "垂下" }, { "chui xian", "垂涎" }, { "chui xiang", "吹响" }, { "chui xu", "吹嘘" },
			{ "chui yan", "炊烟" }, { "chui zhe", "吹着" }, { "chui zhi", "垂直" }, { "chui zi", "锤子" }, { "chun", "偆" }, { "chun", "唇" }, { "chun", "媋" },
			{ "chun", "惷" }, { "chun", "春" }, { "chun", "暙" }, { "chun", "杶" }, { "chun", "椿" }, { "chun", "槆" }, { "chun", "橁" }, { "chun", "淳" },
			{ "chun", "漘" }, { "chun", "犉" }, { "chun", "瑃" }, { "chun", "純" }, { "chun", "纯" }, { "chun", "脣" }, { "chun", "莼" }, { "chun", "萶" },
			{ "chun", "蓴" }, { "chun", "蝽" }, { "chun", "蠢" }, { "chun", "賰" }, { "chun", "醇" }, { "chun", "鯙" }, { "chun", "鰆" }, { "chun", "鶉" },
			{ "chun", "鶞" }, { "chun", "鹑" }, { "chun ai", "纯爱" }, { "chun bai", "纯白" }, { "chun bian", "唇边" }, { "chun chun", "春春" }, { "chun chun", "纯纯" },
			{ "chun chun yu dong", "蠢蠢欲动" }, { "chun cui", "纯粹" }, { "chun du", "纯度" }, { "chun feng", "春风" }, { "chun gao", "唇膏" }, { "chun geng", "春耕" },
			{ "chun guang", "春光" }, { "chun gui", "春归" }, { "chun hou", "醇厚" }, { "chun hua", "春花" }, { "chun hua", "纯化" }, { "chun hui", "春晖" },
			{ "chun ji", "春季" }, { "chun jiang", "春江" }, { "chun jie", "春节" }, { "chun jie", "纯洁" }, { "chun jie bao ji", "春节包机" },
			{ "chun jie qi jian", "春节期间" }, { "chun jie qian", "春节前" }, { "chun jie wan hui", "春节晚会" }, { "chun jing", "纯净" }, { "chun jing shui", "纯净水" },
			{ "chun lai", "春来" }, { "chun lan", "春兰" }, { "chun lian", "春联" }, { "chun mei", "纯美" }, { "chun meng", "春梦" }, { "chun mian", "纯棉" },
			{ "chun nuan hua kai", "春暖花开" }, { "chun ping", "纯平" }, { "chun pu", "淳朴" }, { "chun pu", "纯朴" }, { "chun qing", "纯情" }, { "chun qiu", "春秋" },
			{ "chun ri", "春日" }, { "chun se", "春色" }, { "chun shou ru", "纯收入" }, { "chun shu", "纯属" }, { "chun shui", "春水" }, { "chun shui", "纯水" },
			{ "chun tian", "春天" }, { "chun tian ran", "纯天然" }, { "chun wan", "春晚" }, { "chun xia", "春夏" }, { "chun xia qiu dong", "春夏秋冬" },
			{ "chun xiao", "春晓" }, { "chun yao", "春药" }, { "chun yi", "春意" }, { "chun yin", "纯银" }, { "chun you", "春游" }, { "chun yu", "春雨" },
			{ "chun yun", "春运" }, { "chun zhen", "纯真" }, { "chun zheng", "纯正" }, { "chun zhong", "纯种" }, { "chuo", "啜" }, { "chuo", "嚽" }, { "chuo", "娖" },
			{ "chuo", "惙" }, { "chuo", "戳" }, { "chuo", "擉" }, { "chuo", "歠" }, { "chuo", "磭" }, { "chuo", "綽" }, { "chuo", "绰" }, { "chuo", "踔" },
			{ "chuo", "輟" }, { "chuo", "辍" }, { "chuo", "逴" }, { "chuo", "齪" }, { "chuo", "龊" }, { "chuo chuo you yu", "绰绰有余" }, { "chuo hao", "绰号" },
			{ "chuo xue", "辍学" }, { "ci", "伺" }, { "ci", "佌" }, { "ci", "佽" }, { "ci", "偨" }, { "ci", "兹" }, { "ci", "刺" }, { "ci", "嬨" }, { "ci", "差" },
			{ "ci", "庛" }, { "ci", "慈" }, { "ci", "朿" }, { "ci", "柌" }, { "ci", "栨" }, { "ci", "次" }, { "ci", "此" }, { "ci", "泚" }, { "ci", "濨" },
			{ "ci", "瓷" }, { "ci", "疵" }, { "ci", "皉" }, { "ci", "磁" }, { "ci", "祠" }, { "ci", "糍" }, { "ci", "絘" }, { "ci", "茈" }, { "ci", "茦" },
			{ "ci", "茨" }, { "ci", "莿" }, { "ci", "蛓" }, { "ci", "詞" }, { "ci", "词" }, { "ci", "賜" }, { "ci", "赐" }, { "ci", "趀" }, { "ci", "跐" },
			{ "ci", "辞" }, { "ci", "辭" }, { "ci", "雌" }, { "ci", "飺" }, { "ci", "餈" }, { "ci", "鶿" }, { "ci", "鹚" }, { "ci ai", "慈爱" }, { "ci an", "此案" },
			{ "ci ba", "词霸" }, { "ci ban", "此版" }, { "ci bei", "慈悲" }, { "ci bi", "刺鼻" }, { "ci bing", "此病" }, { "ci cao zuo", "此操作" }, { "ci chang", "磁场" },
			{ "ci chu", "此处" }, { "ci ci", "次次" }, { "ci ci", "此次" }, { "ci dai", "磁带" }, { "ci dao", "刺刀" }, { "ci deng", "此等" }, { "ci di", "次第" },
			{ "ci di", "此地" }, { "ci dian", "词典" }, { "ci dian", "辞典" }, { "ci diao", "辞掉" }, { "ci er", "刺耳" }, { "ci er", "词儿" }, { "ci fa", "此法" },
			{ "ci fan", "此番" }, { "ci gei", "赐给" }, { "ci gong neng", "此功能" }, { "ci gu", "刺骨" }, { "ci hou", "伺候" }, { "ci hou", "此后" }, { "ci hua", "此话" },
			{ "ci hui", "词汇" }, { "ci hui liang", "词汇量" }, { "ci hui yi", "次会议" }, { "ci ji", "刺激" }, { "ci ji", "次级" }, { "ci ji su", "雌激素" },
			{ "ci ji xing", "刺激性" }, { "ci ji zhai", "次级债" }, { "ci jian", "此间" }, { "ci jiao", "赐教" }, { "ci ju", "此举" }, { "ci ju", "此剧" },
			{ "ci ju", "词句" }, { "ci ka", "磁卡" }, { "ci ke", "刺客" }, { "ci ke", "此刻" }, { "ci ku", "词库" }, { "ci kuan", "此款" }, { "ci lei", "此类" } };
};
