package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN08 {
	public static String[][] pl = { { "ci nai", "此乃" }, { "ci nian", "次年" }, { "ci nv", "此女" }, { "ci pan", "磁盘" }, { "ci pan zhen lie", "磁盘阵列" },
			{ "ci pian", "此片" }, { "ci pian wen zhang", "此篇文章" }, { "ci pin", "次品" }, { "ci qi", "瓷器" }, { "ci qi bi fu", "此起彼伏" }, { "ci qian", "此前" },
			{ "ci qing", "刺青" }, { "ci qu", "词曲" }, { "ci qu", "辞去" }, { "ci quan hui", "次全会" }, { "ci ren", "此人" }, { "ci ren", "词人" }, { "ci ri", "次日" },
			{ "ci sha", "刺杀" }, { "ci shan", "慈善" }, { "ci shan ji gou", "慈善机构" }, { "ci shan shi ye", "慈善事业" }, { "ci shang", "刺伤" }, { "ci sheng", "此生" },
			{ "ci shi", "刺史" }, { "ci shi", "此事" }, { "ci shi", "此时" }, { "ci shi", "辞世" }, { "ci shi ci ke", "此时此刻" }, { "ci shu", "次数" }, { "ci shu", "此书" },
			{ "ci tang", "祠堂" }, { "ci tiao", "词条" }, { "ci tie", "此帖" }, { "ci tie", "此贴" }, { "ci tie", "磁铁" }, { "ci tong", "刺痛" }, { "ci tou", "磁头" },
			{ "ci tui", "辞退" }, { "ci wai", "此外" }, { "ci wei", "刺猬" }, { "ci wei", "此为" }, { "ci wen", "此文" }, { "ci wen jian", "此文件" },
			{ "ci wen ti", "此问题" }, { "ci xi", "慈溪" }, { "ci xi", "慈禧" }, { "ci xi shi", "慈溪市" }, { "ci xiang", "慈祥" }, { "ci xiang", "此项" },
			{ "ci xing", "此行" }, { "ci xing", "磁性" }, { "ci xing", "雌性" }, { "ci xiong", "雌雄" }, { "ci xiu", "刺绣" }, { "ci xu", "次序" },
			{ "ci xuan fu", "磁悬浮" }, { "ci yan", "刺眼" }, { "ci yan", "此言" }, { "ci yao", "次要" }, { "ci yi", "此一" }, { "ci yu", "词语" }, { "ci yu", "赐予" },
			{ "ci zhi", "次之" }, { "ci zhi", "此致" }, { "ci zhi", "辞职" }, { "ci zhong", "此种" }, { "ci zhuan", "瓷砖" }, { "ci zi", "次子" }, { "ci zu", "词组" },
			{ "cong", "丛" }, { "cong", "从" }, { "cong", "匆" }, { "cong", "叢" }, { "cong", "囪" }, { "cong", "囱" }, { "cong", "婃" }, { "cong", "孮" },
			{ "cong", "従" }, { "cong", "徖" }, { "cong", "從" }, { "cong", "怱" }, { "cong", "悤" }, { "cong", "悰" }, { "cong", "慒" }, { "cong", "暰" },
			{ "cong", "枞" }, { "cong", "樅" }, { "cong", "欉" }, { "cong", "淙" }, { "cong", "熜" }, { "cong", "琮" }, { "cong", "瑽" }, { "cong", "璁" },
			{ "cong", "瞛" }, { "cong", "聡" }, { "cong", "聪" }, { "cong", "聰" }, { "cong", "苁" }, { "cong", "葱" }, { "cong", "蔥" }, { "cong", "藂" },
			{ "cong", "蟌" }, { "cong", "謥" }, { "cong", "賨" }, { "cong", "鏦" }, { "cong", "驄" }, { "cong", "骢" }, { "cong bu", "从不" }, { "cong ci", "从此" },
			{ "cong ci yi hou", "从此以后" }, { "cong cong", "匆匆" }, { "cong cong mang mang", "匆匆忙忙" }, { "cong er", "从而" }, { "cong fei", "丛飞" },
			{ "cong gen ben shang", "从根本上" }, { "cong he", "从何" }, { "cong hua", "从化" }, { "cong hua", "葱花" }, { "cong hui", "聪慧" }, { "cong jin", "从紧" },
			{ "cong jin tian qi", "从今天起" }, { "cong ju", "从句" }, { "cong lai", "从来" }, { "cong lai mei you", "从来没有" }, { "cong lin", "丛林" },
			{ "cong ling kai shi", "从零开始" }, { "cong mang", "匆忙" }, { "cong mei", "从没" }, { "cong ming", "聪明" }, { "cong ming cai zhi", "聪明才智" },
			{ "cong ming ren", "聪明人" }, { "cong na", "从那" }, { "cong na li lai", "从哪里来" }, { "cong qi", "从其" }, { "cong qian", "从前" }, { "cong qing", "从轻" },
			{ "cong rong", "从容" }, { "cong sheng", "丛生" }, { "cong shi", "从事" }, { "cong shu", "丛书" }, { "cong tian er jiang", "从天而降" }, { "cong tou", "从头" },
			{ "cong tou dao wei", "从头到尾" }, { "cong tou kai shi", "从头开始" }, { "cong wei", "从未" }, { "cong wen", "从文" }, { "cong wo", "从我" },
			{ "cong wu", "从无" }, { "cong xiao", "从小" }, { "cong xin", "从新" }, { "cong yan", "从严" }, { "cong ye", "从业" }, { "cong ye ren yuan", "从业人员" },
			{ "cong ye zhe", "从业者" }, { "cong yi kai shi", "从一开始" }, { "cong zao", "从早" }, { "cong zhe", "从这" }, { "cong zheng", "从政" },
			{ "cong zhong", "丛中" }, { "cong zhong", "从中" }, { "cong zuo", "从左" }, { "cou", "凑" }, { "cou", "楱" }, { "cou", "湊" }, { "cou", "玼" },
			{ "cou", "腠" }, { "cou", "輳" }, { "cou", "辏" }, { "cou dao", "凑到" }, { "cou he", "凑合" }, { "cou jin", "凑近" }, { "cou qi", "凑齐" },
			{ "cou qiao", "凑巧" }, { "cou re nao", "凑热闹" }, { "cu", "促" }, { "cu", "卒" }, { "cu", "徂" }, { "cu", "憱" }, { "cu", "殂" }, { "cu", "猝" },
			{ "cu", "瘯" }, { "cu", "簇" }, { "cu", "粗" }, { "cu", "蔟" }, { "cu", "觕" }, { "cu", "踀" }, { "cu", "踧" }, { "cu", "蹙" }, { "cu", "蹴" },
			{ "cu", "酢" }, { "cu", "醋" }, { "cu", "顣" }, { "cu", "麁" }, { "cu", "麤" }, { "cu", "鼀" }, { "cu bao", "粗暴" }, { "cu cao", "粗糙" },
			{ "cu cheng", "促成" }, { "cu da", "粗大" }, { "cu fang", "粗放" }, { "cu guang", "粗犷" }, { "cu hua", "粗话" }, { "cu jin", "促进" },
			{ "cu jin hui", "促进会" }, { "cu jin zuo yong", "促进作用" }, { "cu kou", "粗口" }, { "cu lu", "粗鲁" }, { "cu lue", "粗略" }, { "cu qi", "粗气" },
			{ "cu shi", "促使" }, { "cu si", "猝死" }, { "cu su", "粗俗" }, { "cu suan", "醋酸" }, { "cu xi", "粗细" }, { "cu xiao", "促销" },
			{ "cu xiao huo dong", "促销活动" }, { "cu xiao yuan", "促销员" }, { "cu xin", "粗心" }, { "cu yong", "簇拥" }, { "cu zhuang", "粗壮" }, { "cuan", "巑" },
			{ "cuan", "撺" }, { "cuan", "攅" }, { "cuan", "攒" }, { "cuan", "攛" }, { "cuan", "攢" }, { "cuan", "汆" }, { "cuan", "爨" }, { "cuan", "窜" },
			{ "cuan", "竄" }, { "cuan", "篡" }, { "cuan", "簒" }, { "cuan", "蹿" }, { "cuan", "躥" }, { "cuan", "镩" }, { "cuan gai", "篡改" }, { "cui", "催" },
			{ "cui", "凗" }, { "cui", "啐" }, { "cui", "墔" }, { "cui", "崔" }, { "cui", "忰" }, { "cui", "悴" }, { "cui", "慛" }, { "cui", "摧" }, { "cui", "榱" },
			{ "cui", "毳" }, { "cui", "淬" }, { "cui", "漼" }, { "cui", "焠" }, { "cui", "璀" }, { "cui", "瘁" }, { "cui", "磪" }, { "cui", "竁" }, { "cui", "粹" },
			{ "cui", "翆" }, { "cui", "翠" }, { "cui", "脆" }, { "cui", "膬" }, { "cui", "膵" }, { "cui", "萃" }, { "cui", "衰" }, { "cui", "鏙" },
			{ "cui can", "摧残" }, { "cui can", "璀璨" }, { "cui cu", "催促" }, { "cui cui", "翠翠" }, { "cui hua", "催化" }, { "cui hua", "翠花" },
			{ "cui hua ji", "催化剂" }, { "cui hui", "摧毁" }, { "cui jian", "崔健" }, { "cui lv", "翠绿" }, { "cui mian", "催眠" }, { "cui qu", "萃取" },
			{ "cui ruo", "脆弱" }, { "cui sheng", "催生" }, { "cui yong yuan", "崔永元" }, { "cun", "刌" }, { "cun", "吋" }, { "cun", "存" }, { "cun", "寸" },
			{ "cun", "忖" }, { "cun", "村" }, { "cun", "皴" }, { "cun", "籿" }, { "cun", "蹲" }, { "cun", "邨" }, { "cun chu", "存储" },
			{ "cun chu guo cheng", "存储过程" }, { "cun chu ka", "存储卡" }, { "cun chu kong jian", "存储空间" }, { "cun chu qi", "存储器" }, { "cun chu she bei", "存储设备" },
			{ "cun cun", "村村" }, { "cun cun tong", "村村通" }, { "cun dan", "存单" }, { "cun dang", "存档" }, { "cun fang", "存放" }, { "cun gan bu", "村干部" },
			{ "cun gu", "村姑" }, { "cun guan", "存管" }, { "cun guan", "村官" }, { "cun huo", "存活" }, { "cun huo", "存货" }, { "cun ji", "村级" }, { "cun kou", "村口" },
			{ "cun kuan", "存款" }, { "cun kuan li lv", "存款利率" }, { "cun li", "村里" }, { "cun li ren", "村里人" }, { "cun liang", "存量" }, { "cun luo", "村落" },
			{ "cun min", "村民" }, { "cun pan", "存盘" }, { "cun qian", "存钱" }, { "cun qu", "存取" }, { "cun ren", "村人" }, { "cun ru", "存入" }, { "cun shang", "村上" },
			{ "cun wang", "存亡" }, { "cun wei", "村委" }, { "cun wei hui", "村委会" }, { "cun xin", "存心" }, { "cun xu", "存续" }, { "cun you", "存有" },
			{ "cun zai", "存在" }, { "cun zai wen ti", "存在问题" }, { "cun zhang", "村长" }, { "cun zhe", "存折" }, { "cun zhe", "存着" }, { "cun zhen", "村镇" },
			{ "cun zhi shu", "村支书" }, { "cun zhuang", "村庄" }, { "cun zi", "村子" }, { "cuo", "剉" }, { "cuo", "剒" }, { "cuo", "厝" }, { "cuo", "夎" },
			{ "cuo", "嵯" }, { "cuo", "嵳" }, { "cuo", "挫" }, { "cuo", "措" }, { "cuo", "搓" }, { "cuo", "撮" }, { "cuo", "棤" }, { "cuo", "瑳" }, { "cuo", "痤" },
			{ "cuo", "瘥" }, { "cuo", "矬" }, { "cuo", "磋" }, { "cuo", "脞" }, { "cuo", "莝" }, { "cuo", "蒫" }, { "cuo", "蓌" }, { "cuo", "蹉" }, { "cuo", "遳" },
			{ "cuo", "醝" }, { "cuo", "銼" }, { "cuo", "錯" }, { "cuo", "锉" }, { "cuo", "错" }, { "cuo", "髊" }, { "cuo", "鹺" }, { "cuo", "鹾" }, { "cuo", "齹" },
			{ "cuo bai", "挫败" }, { "cuo bie zi", "错别字" }, { "cuo chuang", "痤疮" }, { "cuo ci", "措辞" }, { "cuo de", "错的" }, { "cuo guo", "错过" },
			{ "cuo he", "撮合" }, { "cuo jue", "错觉" }, { "cuo kai", "错开" }, { "cuo luan", "错乱" }, { "cuo luo", "错落" }, { "cuo shang", "挫伤" },
			{ "cuo shang", "磋商" }, { "cuo shi", "措施" }, { "cuo shi", "错事" }, { "cuo shi", "错失" }, { "cuo shou bu ji", "措手不及" }, { "cuo wei", "错位" },
			{ "cuo wu", "错误" }, { "cuo wu xin xi", "错误信息" }, { "cuo zai", "错在" }, { "cuo zhe", "挫折" }, { "cuo zi", "错字" }, { "cuo zong fu za", "错综复杂" },
			{ "da", "匒" }, { "da", "咑" }, { "da", "哒" }, { "da", "嗒" }, { "da", "噠" }, { "da", "大" }, { "da", "妲" }, { "da", "怛" }, { "da", "打" },
			{ "da", "搭" }, { "da", "沓" }, { "da", "炟" }, { "da", "燵" }, { "da", "畣" }, { "da", "瘩" }, { "da", "笪" }, { "da", "答" }, { "da", "繨" },
			{ "da", "羍" }, { "da", "耷" }, { "da", "薘" }, { "da", "褡" }, { "da", "躂" }, { "da", "达" }, { "da", "達" }, { "da", "鎝" }, { "da", "鐽" },
			{ "da", "靼" }, { "da", "鞑" }, { "da", "韃" }, { "da", "龘" }, { "da ai", "大爱" }, { "da ai", "大碍" }, { "da an", "大案" }, { "da an", "答案" },
			{ "da ba", "大坝" }, { "da ba", "大巴" }, { "da ba", "大把" }, { "da bai", "大白" }, { "da bai", "大败" }, { "da bai", "打败" }, { "da bai cai", "大白菜" },
			{ "da bai tian", "大白天" }, { "da ban", "大半" }, { "da ban", "大板" }, { "da ban", "大班" }, { "da ban", "大阪" }, { "da ban", "打扮" },
			{ "da ban tian", "大半天" }, { "da bang", "大棒" }, { "da bao", "大包" }, { "da bao", "大宝" }, { "da bao", "打包" }, { "da bao yu", "大暴雨" },
			{ "da bei", "大悲" }, { "da ben", "大本" }, { "da ben ying", "大本营" }, { "da bi", "大笔" }, { "da bi pin", "大比拼" }, { "da bian", "大便" },
			{ "da bian", "大变" }, { "da bian", "答辩" }, { "da biao", "达标" }, { "da bing", "大兵" }, { "da bing", "大病" }, { "da bing", "大饼" }, { "da bo", "大伯" },
			{ "da bo", "大波" }, { "da bu", "大步" }, { "da bu", "大部" }, { "da bu", "打不" }, { "da bu dao", "达不到" }, { "da bu ding", "打补丁" },
			{ "da bu dui", "大部队" }, { "da bu fen", "大部分" }, { "da bu kai", "打不开" }, { "da bu liao", "大不了" }, { "da bu xiang tong", "大不相同" },
			{ "da bu yi yang", "大不一样" }, { "da can", "大餐" }, { "da cao yuan", "大草原" }, { "da chang", "大厂" }, { "da chang", "大肠" },
			{ "da chang gan jun", "大肠杆菌" }, { "da chang jin", "大长今" }, { "da chang mian", "大场面" }, { "da chao", "大吵" }, { "da chao", "大潮" },
			{ "da che", "大车" }, { "da che", "打车" }, { "da che", "搭车" }, { "da chen", "大臣" }, { "da cheng", "大乘" }, { "da cheng", "大成" }, { "da cheng", "打成" },
			{ "da cheng", "搭乘" }, { "da cheng", "达成" }, { "da cheng shi", "大城市" }, { "da cheng xie yi", "达成协议" }, { "da chi", "大吃" },
			{ "da chi yi jing", "大吃一惊" }, { "da chu", "大厨" }, { "da chu", "打出" }, { "da chu lai", "打出来" }, { "da chu xue", "大出血" }, { "da chuan", "大船" },
			{ "da chuang", "大床" }, { "da cong", "大葱" }, { "da cuo", "大错" }, { "da cuo", "打错" }, { "da da", "大大" }, { "da da", "大打" }, { "da da", "打打" },
			{ "da da", "达达" }, { "da da chu shou", "大打出手" }, { "da da lie lie", "大大咧咧" }, { "da da ti gao", "大大提高" }, { "da da xiao xiao", "大大小小" },
			{ "da da zhe kou", "大打折扣" }, { "da dan", "大单" }, { "da dan", "大胆" }, { "da dang", "搭档" }, { "da dao", "大刀" }, { "da dao", "大到" },
			{ "da dao", "大盗" }, { "da dao", "大道" }, { "da dao", "打倒" }, { "da dao", "打到" }, { "da dao", "答道" }, { "da dao", "达到" },
			{ "da dao gao chao", "达到高潮" }, { "da dao kuo fu", "大刀阔斧" }, { "da dao li", "大道理" }, { "da de", "大德" }, { "da de", "大的" }, { "da de", "打得" },
			{ "da deng", "大灯" }, { "da di", "大地" }, { "da di", "大堤" }, { "da di", "大帝" }, { "da di", "大抵" }, { "da di", "打的" }, { "da di zhen", "大地震" },
			{ "da dian", "大典" }, { "da dian", "大殿" }, { "da dian", "大点" }, { "da dian", "打点" }, { "da dian hua", "打电话" }, { "da diao", "打掉" },
			{ "da die", "大碟" }, { "da die", "大跌" }, { "da dong", "大东" }, { "da dong", "打动" }, { "da dong zuo", "大动作" }, { "da dou", "大豆" }, { "da dou", "大都" },
			{ "da dou", "打斗" }, { "da du", "大度" }, { "da du", "大肚" }, { "da du", "大都" }, { "da du", "打赌" }, { "da du shi", "大都市" }, { "da du zi", "大肚子" },
			{ "da duan", "大段" }, { "da duan", "打断" }, { "da dui", "大堆" }, { "da dui", "大队" }, { "da dui", "答对" }, { "da dui zhang", "大队长" },
			{ "da dun", "打盹" }, { "da duo", "大多" }, { "da duo shu", "大多数" }, { "da duo shu ren", "大多数人" }, { "da e", "大额" }, { "da e", "大鳄" },
			{ "da er", "大二" }, { "da er", "达尔" }, { "da er fu er", "达尔富尔" }, { "da er wen", "达尔文" }, { "da er zi", "大儿子" }, { "da fa", "大发" },
			{ "da fa", "大法" }, { "da fa", "打发" }, { "da fa", "打法" }, { "da fa di zi", "大法弟子" }, { "da fa guan", "大法官" }, { "da fa zhan", "大发展" },
			{ "da fan", "大凡" }, { "da fan", "打翻" }, { "da fan dian", "大饭店" }, { "da fan wei", "大范围" }, { "da fang", "大方" }, { "da fang xiang", "大方向" },
			{ "da fei", "大飞" }, { "da fei ji", "打飞机" }, { "da fen", "打分" }, { "da fen qi", "达芬奇" }, { "da feng", "大风" }, { "da fo", "大佛" }, { "da fu", "大夫" },
			{ "da fu", "大幅" }, { "da fu", "答复" }, { "da fu du", "大幅度" }, { "da fu weng", "大富翁" }, { "da fu zeng zhang", "大幅增长" }, { "da gai", "大概" },
			{ "da gan", "大干" }, { "da gang", "大港" }, { "da gang", "大纲" }, { "da gao", "大搞" }, { "da ge", "大个" }, { "da ge", "大哥" }, { "da ge", "打个" },
			{ "da ge", "打嗝" }, { "da ge da", "大哥大" }, { "da ge dian hua", "打个电话" }, { "da ge ge", "大哥哥" }, { "da ge ming", "大革命" }, { "da ge zi", "大个子" },
			{ "da gei", "打给" }, { "da gong", "大公" }, { "da gong", "打工" }, { "da gong gao cheng", "大功告成" }, { "da gong lv", "大功率" }, { "da gong mei", "打工妹" },
			{ "da gong si", "大公司" }, { "da gong zai", "打工仔" }, { "da gong zhe", "打工者" }, { "da gou", "大狗" }, { "da gou", "打勾" }, { "da gou", "打狗" },
			{ "da gu", "打鼓" }, { "da gu dong", "大股东" }, { "da gu niang", "大姑娘" }, { "da guai", "打怪" }, { "da guan", "大关" }, { "da guan", "大官" },
			{ "da guan", "大观" }, { "da guan si", "打官司" }, { "da guan yuan", "大观园" }, { "da gui mo", "大规模" }, { "da gun", "打滚" }, { "da guo", "大国" },
			{ "da guo", "大锅" }, { "da guo", "打过" }, { "da hai", "大海" }, { "da han", "大喊" }, { "da han", "大汉" }, { "da han", "大汗" },
			{ "da han lin li", "大汗淋漓" }, { "da hang hai", "大航海" }, { "da hao", "大号" }, { "da hao", "大好" }, { "da hao", "打好" }, { "da he", "大河" },
			{ "da he wang", "大河网" }, { "da hei", "大黑" }, { "da heng", "大亨" }, { "da hong", "大红" }, { "da hong da zi", "大红大紫" }, { "da hou", "大吼" },
			{ "da hu", "大呼" }, { "da hu", "大户" }, { "da hu xing", "大户型" }, { "da hu zi", "大胡子" }, { "da hua", "大华" }, { "da hua", "大花" }, { "da hua", "大话" },
			{ "da hua", "打滑" }, { "da hua xi you", "大话西游" }, { "da huan jing", "大环境" }, { "da huang", "大黄" }, { "da huang feng", "大黄蜂" }, { "da hui", "大会" },
			{ "da hui lang", "大灰狼" }, { "da huo", "大伙" }, { "da huo", "大火" }, { "da huo che", "大货车" }, { "da huo er", "大伙儿" }, { "da huo ji", "打火机" },
			{ "da ji", "大吉" }, { "da ji", "大忌" }, { "da ji", "大计" }, { "da ji", "打击" }, { "da ji", "打机" }, { "da ji bao fu", "打击报复" },
			{ "da ji liang", "大剂量" }, { "da ji tuan", "大集团" }, { "da ji yuan", "大纪元" }, { "da ji zhe wen", "答记者问" }, { "da jia", "大加" }, { "da jia", "大家" },
			{ "da jia", "打假" }, { "da jia", "打架" }, { "da jia dou lai", "大家都来" }, { "da jia dou shi", "大家都是" }, { "da jia fen xiang", "大家分享" },
			{ "da jia hao", "大家好" }, { "da jia kan", "大家看" }, { "da jia kan kan", "大家看看" }, { "da jia ting", "大家庭" }, { "da jia yi qi", "大家一起" },
			{ "da jian", "大件" }, { "da jian", "大剑" }, { "da jian", "搭建" }, { "da jian cha", "大检查" }, { "da jiang", "大奖" }, { "da jiang", "大将" },
			{ "da jiang", "大江" }, { "da jiang jun", "大将军" }, { "da jiang nan bei", "大江南北" }, { "da jiang sai", "大奖赛" }, { "da jiang wang", "大江网" },
			{ "da jiao", "大叫" }, { "da jiao", "大脚" }, { "da jiao", "打搅" }, { "da jiao dao", "打交道" }, { "da jiao tang", "大教堂" }, { "da jie", "大姐" },
			{ "da jie", "大街" }, { "da jie", "打劫" }, { "da jie jie", "大姐姐" }, { "da jie ju", "大结局" }, { "da jie xiao xiang", "大街小巷" }, { "da jin", "打进" },
			{ "da jing", "大惊" }, { "da jing xiao guai", "大惊小怪" }, { "da jiu", "大舅" }, { "da jiu dian", "大酒店" }, { "da ju", "大举" }, { "da ju", "大局" },
			{ "da ju yuan", "大剧院" }, { "da juan", "答卷" }, { "da jun", "大军" }, { "da ka", "大卡" }, { "da ka", "打卡" }, { "da kai", "大开" }, { "da kai", "打开" },
			{ "da kai dian nao", "打开电脑" }, { "da kai wang ye", "打开网页" }, { "da kai yan jie", "大开眼界" }, { "da ke", "大可" }, { "da ke bu bi", "大可不必" },
			{ "da ke che", "大客车" }, { "da ke hu", "大客户" }, { "da ke shui", "打瞌睡" }, { "da keng", "大坑" }, { "da kong", "打孔" }, { "da kou", "大口" },
			{ "da ku", "大哭" }, { "da kuai", "大块" }, { "da kuan", "大款" }, { "da kui", "大亏" }, { "da la", "耷拉" }, { "da la si", "达拉斯" }, { "da lai", "打来" },
			{ "da lai", "达赖" }, { "da lai la ma", "达赖喇嘛" }, { "da lan qiu", "打篮球" }, { "da lang", "大浪" }, { "da lao", "大佬" }, { "da lao", "打捞" },
			{ "da lao yuan", "大老远" }, { "da le ge", "打了个" }, { "da lei", "大类" }, { "da lei", "打雷" }, { "da li", "大力" }, { "da li", "大理" }, { "da li", "大礼" },
			{ "da li", "打理" }, { "da li", "搭理" }, { "da li bao", "大礼包" }, { "da li fa zhan", "大力发展" }, { "da li jia qiang", "大力加强" },
			{ "da li kai zhan", "大力开展" }, { "da li shi", "大理石" }, { "da li tui jin", "大力推进" }, { "da li zhi chi", "大力支持" }, { "da lian", "大连" },
			{ "da lian shi", "大连市" }, { "da lian shi de", "大连实德" }, { "da liang", "大梁" }, { "da liang", "大量" }, { "da liang", "打量" }, { "da lie", "打猎" },
			{ "da ling", "大龄" }, { "da long", "大龙" }, { "da lou", "大楼" }, { "da lu", "大路" }, { "da lu", "大陆" }, { "da lu ren", "大陆人" }, { "da luan", "大乱" },
			{ "da luan", "打乱" }, { "da luo", "大罗" }, { "da ma", "大妈" }, { "da ma", "大马" }, { "da ma", "大骂" }, { "da ma", "大麻" }, { "da ma", "打骂" },
			{ "da ma jiang", "打麻将" }, { "da mai", "大卖" }, { "da mai", "大麦" }, { "da mai chang", "大卖场" }, { "da man guan", "大满贯" }, { "da mang", "大忙" },
			{ "da mang ren", "大忙人" }, { "da mao", "大猫" }, { "da mei nv", "大美女" }, { "da men", "大门" }, { "da men kou", "大门口" }, { "da mi", "大米" },
			{ "da mian ji", "大面积" }, { "da ming", "大名" }, { "da ming", "大明" }, { "da ming ding ding", "大名鼎鼎" }, { "da ming xing", "大明星" }, { "da mo", "大漠" },
			{ "da mo", "打磨" }, { "da mo", "达摩" }, { "da mu", "大幕" }, { "da mu zhi", "大拇指" }, { "da nai", "大奶" }, { "da nan hai", "大男孩" },
			{ "da nan ren", "大男人" }, { "da nao", "大脑" }, { "da nao", "大闹" }, { "da nao", "打闹" }, { "da neng", "达能" }, { "da niang", "大娘" },
			{ "da niao", "大鸟" }, { "da niu", "大牛" }, { "da niu shi", "大牛市" }, { "da nu", "大怒" }, { "da nv er", "大女儿" }, { "da pai", "大牌" }, { "da pai", "打牌" },
			{ "da pai dang", "大排档" }, { "da pan", "大盘" }, { "da pan gu", "大盘股" }, { "da pang", "大胖" }, { "da pao", "大炮" }, { "da pao", "打炮" },
			{ "da pei", "搭配" }, { "da pen ti", "打喷嚏" }, { "da peng", "大棚" }, { "da peng", "大鹏" }, { "da pi", "大批" }, { "da pi liang", "大批量" },
			{ "da pian", "大片" }, { "da pin", "打拼" }, { "da pin pai", "大品牌" }, { "da ping", "大屏" }, { "da ping", "打平" }, { "da ping mu", "大屏幕" },
			{ "da po", "打破" }, { "da qi", "大旗" }, { "da qi", "大气" }, { "da qi", "打气" }, { "da qi", "打起" }, { "da qi", "搭起" }, { "da qi ceng", "大气层" },
			{ "da qi da luo", "大起大落" }, { "da qi wu ran", "大气污染" }, { "da qi ye", "大企业" }, { "da qian", "大钱" }, { "da qian", "打钱" }, { "da qian feng", "大前锋" },
			{ "da qian shi jie", "大千世界" }, { "da qiao", "大桥" }, { "da qin", "大秦" }, { "da qing", "大庆" }, { "da qing", "大清" }, { "da qing ma qiao", "打情骂俏" },
			{ "da qing zao", "大清早" }, { "da qiu", "打球" }, { "da qu", "大区" }, { "da qu", "打趣" }, { "da qu shi", "大趋势" }, { "da quan", "大全" },
			{ "da quan", "大权" }, { "da qun", "大群" }, { "da rao", "打扰" }, { "da re", "大热" }, { "da re tian", "大热天" }, { "da ren", "大人" }, { "da ren", "打人" },
			{ "da ren", "达人" }, { "da ren wu", "大人物" }, { "da rong liang", "大容量" }, { "da ru", "打入" }, { "da sai", "大赛" }, { "da san", "大三" },
			{ "da san", "打伞" }, { "da sao", "大嫂" }, { "da sao", "打扫" }, { "da sao chu", "大扫除" }, { "da sao wei sheng", "打扫卫生" }, { "da sha", "大傻" },
			{ "da sha", "大厦" }, { "da shan", "大山" }, { "da shan", "搭讪" }, { "da shang", "打上" }, { "da shang", "打伤" }, { "da shang", "搭上" },
			{ "da shang chang", "大商场" }, { "da she", "大蛇" }, { "da shen", "大婶" }, { "da shen", "大神" }, { "da shen me", "打什么" }, { "da sheng", "大圣" },
			{ "da sheng", "大声" }, { "da sheng", "大省" }, { "da sheng", "大胜" }, { "da shi", "大事" }, { "da shi", "大使" }, { "da shi", "大势" }, { "da shi", "大市" },
			{ "da shi", "大师" }, { "da shi", "大石" }, { "da shi", "打湿" }, { "da shi chang", "大市场" }, { "da shi dai", "大时代" }, { "da shi guan", "大使馆" },
			{ "da shi ji", "大事记" }, { "da shi ji", "大师级" }, { "da shi jie", "大世界" }, { "da shi sai", "大师赛" }, { "da shi suo qu", "大势所趋" },
			{ "da shi tou", "大石头" }, { "da shi xiong", "大师兄" }, { "da shou", "大受" }, { "da shou", "大寿" }, { "da shou", "大手" }, { "da shou", "打手" },
			{ "da shou bi", "大手笔" }, { "da shou ji", "打手机" }, { "da shu", "大叔" }, { "da shu", "大树" }, { "da shu", "大鼠" }, { "da shui", "大水" },
			{ "da shui", "打水" }, { "da si", "大四" }, { "da si", "大肆" }, { "da si", "打死" }, { "da song", "大宋" }, { "da suan", "大蒜" }, { "da suan", "打算" },
			{ "da sui", "打碎" }, { "da tan", "大谈" }, { "da tan", "打探" }, { "da tang", "大唐" }, { "da tang", "大堂" }, { "da tang dian xin", "大唐电信" },
			{ "da tao lun", "大讨论" }, { "da ti", "大体" }, { "da ti", "答题" }, { "da ti qin", "大提琴" }, { "da ti shang", "大体上" }, { "da tian", "大田" },
			{ "da tiao", "大跳" }, { "da ting", "大厅" }, { "da ting", "打听" }, { "da ting guang zhong", "大庭广众" }, { "da tong", "大同" }, { "da tong", "大通" },
			{ "da tong", "打通" }, { "da tong xiao yi", "大同小异" }, { "da tou", "大头" }, { "da tou", "打头" }, { "da tou tie", "大头贴" }, { "da tu", "大图" },
			{ "da tu sha", "大屠杀" }, { "da tui", "大腿" }, { "da wan", "大碗" }, { "da wan", "大腕" }, { "da wan", "打完" }, { "da wang", "大王" }, { "da wei", "大为" },
			{ "da wei", "大伟" }, { "da wei", "大卫" }, { "da wen ti", "大问题" }, { "da wo", "打我" }, { "da wu", "大雾" }, { "da wu tai", "大舞台" }, { "da xi", "大喜" },
			{ "da xi", "大戏" }, { "da xi yang", "大西洋" }, { "da xia", "大侠" }, { "da xia", "大虾" }, { "da xia", "打下" }, { "da xia gu", "大峡谷" },
			{ "da xian", "大仙" }, { "da xian", "大显" }, { "da xian", "大限" }, { "da xiang", "大象" }, { "da xiang", "打响" }, { "da xiang jing ting", "大相径庭" },
			{ "da xiang mu", "大项目" }, { "da xiao", "大小" }, { "da xiao", "大校" }, { "da xiao", "大笑" }, { "da xiao", "打消" }, { "da xiao bian", "大小便" },
			{ "da xiao jie", "大小姐" }, { "da xiao xie", "大小写" }, { "da xie", "大些" }, { "da xie", "大写" }, { "da xie", "答谢" } };
};
