package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN36 {
	public static String[][] pl = { { "ping jing", "平静" }, { "ping jing", "瓶颈" }, { "ping ju", "凭据" }, { "ping ju", "平局" }, { "ping jun", "平均" },
			{ "ping jun fen", "平均分" }, { "ping jun gong zi", "平均工资" }, { "ping jun jia ge", "平均价格" }, { "ping jun nian ling", "平均年龄" },
			{ "ping jun qi wen", "平均气温" }, { "ping jun shu", "平均数" }, { "ping jun shui ping", "平均水平" }, { "ping jun zhi", "平均值" }, { "ping kong", "凭空" },
			{ "ping lun", "评论" }, { "ping lun jia", "评论家" }, { "ping lun nei rong", "评论内容" }, { "ping lun yuan", "评论员" }, { "ping mi", "平米" },
			{ "ping mian", "平面" }, { "ping mian mei ti", "平面媒体" }, { "ping mian she ji", "平面设计" }, { "ping mian tu", "平面图" }, { "ping min", "平民" },
			{ "ping min bai xing", "平民百姓" }, { "ping min hua", "平民化" }, { "ping mu", "屏幕" }, { "ping pan", "评判" }, { "ping pang", "乒乓" },
			{ "ping pang qiu", "乒乓球" }, { "ping ping", "平平" }, { "ping ping an an", "平平安安" }, { "ping ping dan dan", "平平淡淡" }, { "ping rang", "平壤" },
			{ "ping ri", "平日" }, { "ping sha", "凭啥" }, { "ping shen", "评审" }, { "ping shen me", "凭什么" }, { "ping sheng", "平生" }, { "ping shi", "平实" },
			{ "ping shi", "平时" }, { "ping shou", "平手" }, { "ping shu", "评书" }, { "ping shu", "评述" }, { "ping shuo", "评说" }, { "ping tai", "平台" },
			{ "ping tan", "平坦" }, { "ping tang", "平躺" }, { "ping tian", "平添" }, { "ping tou", "平头" }, { "ping wei", "评为" }, { "ping wei", "评委" },
			{ "ping wei hui", "评委会" }, { "ping wen", "平稳" }, { "ping xi", "平息" }, { "ping xi", "评析" }, { "ping xing", "平行" }, { "ping xing xian", "平行线" },
			{ "ping xuan", "评选" }, { "ping xuan huo dong", "评选活动" }, { "ping yang", "平阳" }, { "ping yao", "平遥" }, { "ping yi", "平抑" }, { "ping yi", "平移" },
			{ "ping yi", "评议" }, { "ping yi jin ren", "平易近人" }, { "ping yong", "平庸" }, { "ping you", "平邮" }, { "ping you", "评优" }, { "ping yu", "评语" },
			{ "ping yuan", "平原" }, { "ping ze", "平仄" }, { "ping zhang", "屏障" }, { "ping zhe", "凭着" }, { "ping zheng", "凭证" }, { "ping zheng", "平整" },
			{ "ping zhuang", "瓶装" }, { "ping zi", "瓶子" }, { "po", "叵" }, { "po", "哱" }, { "po", "坡" }, { "po", "婆" }, { "po", "尃" }, { "po", "岥" },
			{ "po", "岶" }, { "po", "巿" }, { "po", "搫" }, { "po", "攴" }, { "po", "昢" }, { "po", "朴" }, { "po", "桲" }, { "po", "櫇" }, { "po", "泊" },
			{ "po", "泺" }, { "po", "泼" }, { "po", "溌" }, { "po", "潑" }, { "po", "濼" }, { "po", "烞" }, { "po", "猼" }, { "po", "珀" }, { "po", "皤" },
			{ "po", "破" }, { "po", "笸" }, { "po", "粕" }, { "po", "繁" }, { "po", "翍" }, { "po", "蒪" }, { "po", "謈" }, { "po", "迫" }, { "po", "鄱" },
			{ "po", "醱" }, { "po", "釙" }, { "po", "鏺" }, { "po", "钋" }, { "po", "钷" }, { "po", "陂" }, { "po", "頗" }, { "po", "颇" }, { "po", "馞" },
			{ "po", "髆" }, { "po", "魄" }, { "po an", "破案" }, { "po bai", "破败" }, { "po bu de yi", "迫不得已" }, { "po bu ji dai", "迫不及待" }, { "po cai", "破财" },
			{ "po chan", "破产" }, { "po che", "破车" }, { "po chu", "破除" }, { "po du", "坡度" }, { "po duo", "颇多" }, { "po fei", "破费" }, { "po feng", "颇丰" },
			{ "po fu", "泼妇" }, { "po gan", "颇感" }, { "po gao", "颇高" }, { "po ge", "破格" }, { "po hai", "迫害" }, { "po huai", "破坏" }, { "po huai li", "破坏力" },
			{ "po huai xing", "破坏性" }, { "po huo", "破获" }, { "po jia", "婆家" }, { "po jia", "破甲" }, { "po jie", "破解" }, { "po jie ban", "破解版" },
			{ "po jiu", "破旧" }, { "po ju", "颇具" }, { "po kou da ma", "破口大骂" }, { "po la", "泼辣" }, { "po lan", "破烂" }, { "po le", "破了" }, { "po li", "破例" },
			{ "po li", "魄力" }, { "po lie", "破裂" }, { "po men", "破门" }, { "po mie", "破灭" }, { "po niang", "婆娘" }, { "po po", "婆婆" }, { "po po ma ma", "婆婆妈妈" },
			{ "po qie", "迫切" }, { "po qie xu yao", "迫切需要" }, { "po shen", "颇深" }, { "po shi", "迫使" }, { "po shou", "颇受" }, { "po sui", "破碎" },
			{ "po sui ji", "破碎机" }, { "po sun", "破损" }, { "po suo", "婆娑" }, { "po tian huang", "破天荒" }, { "po wang", "破网" }, { "po wei", "颇为" },
			{ "po xi", "婆媳" }, { "po yi", "破译" }, { "po you", "颇有" }, { "po yu", "迫于" }, { "po zai mei jie", "迫在眉睫" }, { "po zhan", "破绽" }, { "pou", "剖" },
			{ "pou", "垺" }, { "pou", "婄" }, { "pou", "抔" }, { "pou", "捊" }, { "pou", "掊" }, { "pou", "棓" }, { "pou", "裒" }, { "pou", "襃" }, { "pou fu", "剖腹" },
			{ "pou fu chan", "剖腹产" }, { "pou gong chan", "剖宫产" }, { "pou mian", "剖面" }, { "pou xi", "剖析" }, { "pu", "仆" }, { "pu", "僕" }, { "pu", "匍" },
			{ "pu", "噗" }, { "pu", "圃" }, { "pu", "埔" }, { "pu", "堡" }, { "pu", "墣" }, { "pu", "扑" }, { "pu", "抪" }, { "pu", "撲" }, { "pu", "普" },
			{ "pu", "暴" }, { "pu", "曝" }, { "pu", "朴" }, { "pu", "樸" }, { "pu", "氆" }, { "pu", "浦" }, { "pu", "溥" }, { "pu", "潽" }, { "pu", "濮" },
			{ "pu", "瀑" }, { "pu", "烳" }, { "pu", "獛" }, { "pu", "璞" }, { "pu", "痡" }, { "pu", "瞨" }, { "pu", "纀" }, { "pu", "脯" }, { "pu", "舖" },
			{ "pu", "舗" }, { "pu", "莆" }, { "pu", "菩" }, { "pu", "葡" }, { "pu", "蒱" }, { "pu", "蒲" }, { "pu", "襆" }, { "pu", "譜" }, { "pu", "谱" },
			{ "pu", "蹼" }, { "pu", "酺" }, { "pu", "鋪" }, { "pu", "鏷" }, { "pu", "鐠" }, { "pu", "铺" }, { "pu", "镤" }, { "pu", "镨" }, { "pu", "駇" },
			{ "pu", "鯆" }, { "pu", "鵏" }, { "pu bi", "扑鼻" }, { "pu bian", "普遍" }, { "pu bian cun zai", "普遍存在" }, { "pu bian xing", "普遍性" }, { "pu bu", "瀑布" },
			{ "pu cha", "普查" }, { "pu chu", "扑出" }, { "pu dao", "扑倒" }, { "pu dao", "扑到" }, { "pu dian", "铺垫" }, { "pu dong", "浦东" },
			{ "pu dong xin qu", "浦东新区" }, { "pu er", "普洱" }, { "pu er cha", "普洱茶" }, { "pu fa", "普法" }, { "pu fa", "浦发" }, { "pu fa yin hang", "浦发银行" },
			{ "pu fu", "匍匐" }, { "pu gong ying", "蒲公英" }, { "pu guang", "曝光" }, { "pu huo", "铺货" }, { "pu ji", "普及" }, { "pu ji lv", "普及率" },
			{ "pu jiang", "浦江" }, { "pu jie", "仆街" }, { "pu jing", "普京" }, { "pu jiu", "扑救" }, { "pu kai", "铺开" }, { "pu ke", "扑克" }, { "pu ke pai", "扑克牌" },
			{ "pu lu", "铺路" }, { "pu luo", "普罗" }, { "pu man", "铺满" }, { "pu mian", "铺面" }, { "pu mian er lai", "扑面而来" }, { "pu mie", "扑灭" },
			{ "pu pu tong tong", "普普通通" }, { "pu ren", "仆人" }, { "pu sa", "菩萨" }, { "pu she", "铺设" }, { "pu shi", "普世" }, { "pu shi", "朴实" },
			{ "pu shu", "朴树" }, { "pu shuo mi li", "扑朔迷离" }, { "pu su", "朴素" }, { "pu tao", "葡萄" }, { "pu tao jiu", "葡萄酒" }, { "pu tao tang", "葡萄糖" },
			{ "pu tao ya", "葡萄牙" }, { "pu ti", "菩提" }, { "pu tian", "普天" }, { "pu tian", "莆田" }, { "pu tian gai di", "铺天盖地" }, { "pu tong", "扑通" },
			{ "pu tong", "普通" }, { "pu tong bai xing", "普通百姓" }, { "pu tong ban", "普通版" }, { "pu tong gao xiao", "普通高校" }, { "pu tong gao zhong", "普通高中" },
			{ "pu tong gu", "普通股" }, { "pu tong hua", "普通话" }, { "pu tong peng you", "普通朋友" }, { "pu tong ren", "普通人" }, { "pu tong yong hu", "普通用户" },
			{ "pu tong zhu fang", "普通住房" }, { "pu tong zhu zhai", "普通住宅" }, { "pu tuo", "普陀" }, { "pu tuo qu", "普陀区" }, { "pu tuo shan", "普陀山" },
			{ "pu xi", "浦西" }, { "pu xiang", "扑向" }, { "pu xie", "谱写" }, { "pu yang", "濮阳" }, { "pu yi", "溥仪" }, { "pu zhuang", "铺装" }, { "pu zi", "铺子" },
			{ "qi", "七" }, { "qi", "乞" }, { "qi", "亓" }, { "qi", "亟" }, { "qi", "企" }, { "qi", "俟" }, { "qi", "倛" }, { "qi", "僛" }, { "qi", "其" },
			{ "qi", "凄" }, { "qi", "启" }, { "qi", "呇" }, { "qi", "咠" }, { "qi", "唭" }, { "qi", "啓" }, { "qi", "啟" }, { "qi", "嘁" }, { "qi", "噐" },
			{ "qi", "器" }, { "qi", "圻" }, { "qi", "埼" }, { "qi", "奇" }, { "qi", "契" }, { "qi", "妻" }, { "qi", "娸" }, { "qi", "婍" }, { "qi", "屺" },
			{ "qi", "岂" }, { "qi", "岐" }, { "qi", "岓" }, { "qi", "崎" }, { "qi", "弃" }, { "qi", "忔" }, { "qi", "悽" }, { "qi", "愒" }, { "qi", "慼" },
			{ "qi", "慽" }, { "qi", "憇" }, { "qi", "憩" }, { "qi", "懠" }, { "qi", "戚" }, { "qi", "扢" }, { "qi", "捿" }, { "qi", "掑" }, { "qi", "攲" },
			{ "qi", "敧" }, { "qi", "斉" }, { "qi", "旂" }, { "qi", "旗" }, { "qi", "朞" }, { "qi", "期" }, { "qi", "杞" }, { "qi", "柒" }, { "qi", "栔" },
			{ "qi", "栖" }, { "qi", "桤" }, { "qi", "桼" }, { "qi", "棄" }, { "qi", "棊" }, { "qi", "棋" }, { "qi", "棨" }, { "qi", "棲" }, { "qi", "榿" },
			{ "qi", "槭" }, { "qi", "欹" }, { "qi", "欺" }, { "qi", "歧" }, { "qi", "毄" }, { "qi", "气" }, { "qi", "気" }, { "qi", "氣" }, { "qi", "汔" },
			{ "qi", "汽" }, { "qi", "沏" }, { "qi", "泣" }, { "qi", "淇" }, { "qi", "淒" }, { "qi", "済" }, { "qi", "湆" }, { "qi", "湇" }, { "qi", "漆" },
			{ "qi", "濝" }, { "qi", "焏" }, { "qi", "玂" }, { "qi", "玘" }, { "qi", "琦" }, { "qi", "琪" }, { "qi", "璂" }, { "qi", "甈" }, { "qi", "畦" },
			{ "qi", "疧" }, { "qi", "盵" }, { "qi", "砌" }, { "qi", "碁" }, { "qi", "碕" }, { "qi", "碛" }, { "qi", "磎" }, { "qi", "磧" }, { "qi", "祁" },
			{ "qi", "祇" }, { "qi", "祈" }, { "qi", "祺" }, { "qi", "禨" }, { "qi", "稘" }, { "qi", "稽" }, { "qi", "竒" }, { "qi", "籏" }, { "qi", "綦" },
			{ "qi", "綺" }, { "qi", "緀" }, { "qi", "緕" }, { "qi", "纃" }, { "qi", "绮" }, { "qi", "缉" }, { "qi", "罊" }, { "qi", "耆" }, { "qi", "肐" },
			{ "qi", "肵" }, { "qi", "脐" }, { "qi", "臍" }, { "qi", "艩" }, { "qi", "芑" }, { "qi", "芞" }, { "qi", "芪" }, { "qi", "荠" }, { "qi", "萁" },
			{ "qi", "萋" }, { "qi", "葺" }, { "qi", "蕲" }, { "qi", "藄" }, { "qi", "蚑" }, { "qi", "蚚" }, { "qi", "蛴" }, { "qi", "蜞" }, { "qi", "蟣" },
			{ "qi", "蟿" }, { "qi", "蠐" }, { "qi", "褄" }, { "qi", "觭" }, { "qi", "訖" }, { "qi", "諆" }, { "qi", "讫" }, { "qi", "豈" }, { "qi", "起" },
			{ "qi", "跂" }, { "qi", "踑" }, { "qi", "蹊" }, { "qi", "躩" }, { "qi", "軝" }, { "qi", "迄" }, { "qi", "迉" }, { "qi", "邔" }, { "qi", "郪" },
			{ "qi", "鄿" }, { "qi", "釮" }, { "qi", "鏚" }, { "qi", "隑" }, { "qi", "霋" }, { "qi", "頎" }, { "qi", "颀" }, { "qi", "騎" }, { "qi", "騏" },
			{ "qi", "騹" }, { "qi", "骐" }, { "qi", "骑" }, { "qi", "鬐" }, { "qi", "鬾" }, { "qi", "鬿" }, { "qi", "魌" }, { "qi", "魕" }, { "qi", "鯕" },
			{ "qi", "鰭" }, { "qi", "鳍" }, { "qi", "鵸" }, { "qi", "鶀" }, { "qi", "鶈" }, { "qi", "麒" }, { "qi", "麡" }, { "qi", "鼜" }, { "qi", "齊" },
			{ "qi", "齐" }, { "qi ba", "七八" }, { "qi bai", "七百" }, { "qi bao", "七宝" }, { "qi bei", "齐备" }, { "qi bing", "奇兵" }, { "qi bing", "骑兵" },
			{ "qi bu", "岂不" }, { "qi bu", "起步" }, { "qi bu cheng sheng", "泣不成声" }, { "qi bu lai", "起不来" }, { "qi bu shi", "岂不是" }, { "qi cai", "七彩" },
			{ "qi cai", "器材" }, { "qi cai", "奇才" }, { "qi cai hong", "七彩虹" }, { "qi can", "凄惨" }, { "qi cao", "起草" }, { "qi che", "汽车" }, { "qi che", "骑车" },
			{ "qi che chan ye", "汽车产业" }, { "qi che chang shang", "汽车厂商" }, { "qi che dian zi", "汽车电子" }, { "qi che gong si", "汽车公司" },
			{ "qi che gong ye", "汽车工业" }, { "qi che hang ye", "汽车行业" }, { "qi che pei jian", "汽车配件" }, { "qi che pin pai", "汽车品牌" },
			{ "qi che qi ye", "汽车企业" }, { "qi che shi chang", "汽车市场" }, { "qi che wei xiu", "汽车维修" }, { "qi che xiao fei", "汽车消费" },
			{ "qi che xiao shou", "汽车销售" }, { "qi che ye", "汽车业" }, { "qi che zhan", "汽车站" }, { "qi che zhi jia", "汽车之家" }, { "qi cheng", "七成" },
			{ "qi cheng", "启程" }, { "qi chu", "期初" }, { "qi chu", "起初" }, { "qi chuan", "气喘" }, { "qi chuan xu xu", "气喘吁吁" }, { "qi chuang", "起床" },
			{ "qi ci", "七次" }, { "qi ci", "其次" }, { "qi da", "七大" }, { "qi da", "骐达" }, { "qi da nei", "齐达内" }, { "qi dai", "期待" }, { "qi dai", "脐带" },
			{ "qi dan", "契丹" }, { "qi dao", "气道" }, { "qi dao", "祈祷" }, { "qi dao", "起到" }, { "qi de", "气得" }, { "qi de", "起得" }, { "qi di", "启迪" },
			{ "qi dian", "七点" }, { "qi dian", "起点" }, { "qi dong", "启东" }, { "qi dong", "启动" }, { "qi dong", "气动" }, { "qi dong", "起动" },
			{ "qi dong pan", "启动盘" }, { "qi dong xiang", "启动项" }, { "qi dong yi shi", "启动仪式" }, { "qi du", "气度" }, { "qi e", "企鹅" }, { "qi er", "其二" },
			{ "qi er", "妻儿" }, { "qi fa", "启发" }, { "qi fang", "期房" }, { "qi fei", "起飞" }, { "qi fen", "七分" }, { "qi fen", "气愤" }, { "qi fen", "气氛" },
			{ "qi fu", "其父" }, { "qi fu", "岐阜" }, { "qi fu", "欺负" }, { "qi fu", "祈福" }, { "qi fu", "起伏" }, { "qi fu ren", "欺负人" }, { "qi gai", "乞丐" },
			{ "qi gai", "气概" }, { "qi gan", "旗杆" }, { "qi gang", "气缸" }, { "qi ge", "七个" }, { "qi gong", "气功" }, { "qi guai", "奇怪" }, { "qi guan", "器官" },
			{ "qi guan", "奇观" }, { "qi guan", "气管" }, { "qi guan dian", "其观点" }, { "qi guan yi zhi", "器官移植" }, { "qi guo", "齐国" }, { "qi hang", "启航" },
			{ "qi hao", "七号" }, { "qi hao", "旗号" }, { "qi he", "契合" }, { "qi hei", "漆黑" }, { "qi hong", "起哄" }, { "qi hou", "其后" }, { "qi hou", "气候" },
			{ "qi hou bian hua", "气候变化" }, { "qi hou tiao jian", "气候条件" }, { "qi hu", "奇虎" }, { "qi hua", "企划" }, { "qi hua", "气化" }, { "qi hua", "气话" },
			{ "qi huan", "奇幻" }, { "qi huo", "期货" }, { "qi huo", "起火" }, { "qi huo gong si", "期货公司" }, { "qi huo jia ge", "期货价格" },
			{ "qi huo jiao yi", "期货交易" }, { "qi huo shi chang", "期货市场" }, { "qi ji", "企及" }, { "qi ji", "奇迹" }, { "qi ji", "契机" },
			{ "qi ji bai huai", "气急败坏" }, { "qi jia", "期价" }, { "qi jia", "起价" }, { "qi jia", "起家" }, { "qi jian", "其间" }, { "qi jian", "器件" },
			{ "qi jian", "旗舰" }, { "qi jian", "期间" }, { "qi jian", "起见" }, { "qi jian dian", "旗舰店" }, { "qi jiang", "起降" }, { "qi jiao", "起脚" },
			{ "qi jie", "七届" }, { "qi jie", "气节" }, { "qi jin", "起劲" }, { "qi jin", "迄今" }, { "qi jin wei zhi", "迄今为止" }, { "qi jiu", "起就" },
			{ "qi ju", "器具" }, { "qi ju", "起居" }, { "qi ju", "齐聚" }, { "qi kan", "期刊" }, { "qi lai", "起来" }, { "qi li", "凄厉" }, { "qi li", "气力" },
			{ "qi li", "起立" }, { "qi liang", "凄凉" }, { "qi liang", "气量" }, { "qi lin", "麒麟" }, { "qi ling", "欺凌" }, { "qi liu", "气流" }, { "qi lou", "七楼" },
			{ "qi lu", "齐鲁" }, { "qi lun ji", "汽轮机" }, { "qi luo", "起落" }, { "qi ma", "起码" }, { "qi ma", "骑马" }, { "qi man", "期满" }, { "qi mei", "凄美" },
			{ "qi men", "气门" }, { "qi meng", "启蒙" }, { "qi miao", "奇妙" }, { "qi min", "器皿" }, { "qi ming", "其名" }, { "qi ming", "启明" }, { "qi ming", "起名" },
			{ "qi ming", "齐名" }, { "qi ming zi", "起名字" }, { "qi mo", "期末" }, { "qi mo kao shi", "期末考试" }, { "qi mu", "其母" }, { "qi nang", "气囊" },
			{ "qi nei", "期内" }, { "qi nei", "气馁" }, { "qi neng", "岂能" }, { "qi nian", "七年" }, { "qi pai", "棋牌" }, { "qi pai", "气派" }, { "qi pan", "企盼" },
			{ "qi pan", "期盼" }, { "qi pan", "棋盘" }, { "qi pao", "旗袍" }, { "qi pao", "气泡" }, { "qi pao", "起跑" }, { "qi pao xian", "起跑线" }, { "qi pei", "汽配" },
			{ "qi pian", "欺骗" }, { "qi po", "气魄" }, { "qi qi", "七七" }, { "qi qi", "其妻" }, { "qi qi", "奇奇" }, { "qi qi", "琦琦" }, { "qi qi", "琪琪" },
			{ "qi qi", "齐齐" }, { "qi qi ha er", "齐齐哈尔" }, { "qi qian", "七千" }, { "qi qiang", "气枪" }, { "qi qiao", "蹊跷" }, { "qi qin", "齐秦" },
			{ "qi qiu", "乞求" }, { "qi qiu", "气球" }, { "qi qiu", "祈求" }, { "qi qu", "崎岖" }, { "qi quan", "弃权" }, { "qi quan", "期权" }, { "qi quan", "齐全" },
			{ "qi ren", "七人" }, { "qi ren", "其人" }, { "qi ren", "奇人" }, { "qi ren", "气人" }, { "qi ren you tian", "杞人忧天" }, { "qi ri", "七日" },
			{ "qi rui", "奇瑞" }, { "qi se", "七色" }, { "qi se", "气色" }, { "qi se", "起色" }, { "qi shang", "骑上" }, { "qi shen", "其身" }, { "qi shen", "起身" },
			{ "qi sheng", "齐声" }, { "qi shi", "七十" }, { "qi shi", "其事" }, { "qi shi", "其实" }, { "qi shi", "其时" }, { "qi shi", "启事" }, { "qi shi", "启示" },
			{ "qi shi", "奇石" }, { "qi shi", "岂是" }, { "qi shi", "歧视" }, { "qi shi", "气势" }, { "qi shi", "起始" }, { "qi shi", "骑士" }, { "qi shi er", "七十二" },
			{ "qi shi lu", "启示录" }, { "qi shi nian dai", "七十年代" }, { "qi shi ye", "企事业" }, { "qi shou", "旗手" }, { "qi shou", "棋手" }, { "qi shu", "骑术" },
			{ "qi shui", "契税" }, { "qi shui", "汽水" }, { "qi si", "气死" }, { "qi si hui sheng", "起死回生" }, { "qi su", "起诉" }, { "qi su shu", "起诉书" },
			{ "qi sui", "七岁" }, { "qi suo", "其所" }, { "qi ta", "其他" }, { "qi ta", "其它" }, { "qi ta di fang", "其他地方" }, { "qi ta di qu", "其他地区" },
			{ "qi ta guo jia", "其他国家" }, { "qi ta hang ye", "其他行业" }, { "qi ta mei ti", "其他媒体" }, { "qi ta mei ti", "其它媒体" }, { "qi ta pin pai", "其他品牌" },
			{ "qi ta ren", "其他人" }, { "qi ta wen ti", "其它问题" }, { "qi ta wen zhang", "其他文章" }, { "qi ta yong hu", "其他用户" }, { "qi ta zu zhi", "其他组织" },
			{ "qi tao", "乞讨" }, { "qi te", "奇特" }, { "qi ti", "气体" }, { "qi tian", "七天" }, { "qi tiao", "起跳" }, { "qi tong", "期铜" }, { "qi tu", "企图" },
			{ "qi wang", "期望" }, { "qi wang zhi", "期望值" }, { "qi wei", "七位" }, { "qi wei", "其为" }, { "qi wei", "气味" }, { "qi wen", "企稳" }, { "qi wen", "气温" },
			{ "qi wu", "器物" }, { "qi wu", "起舞" }, { "qi xi", "七喜" }, { "qi xi", "七夕" }, { "qi xi", "栖息" }, { "qi xi", "气息" }, { "qi xi di", "栖息地" },
			{ "qi xia", "旗下" }, { "qi xia de", "旗下的" }, { "qi xian", "期限" }, { "qi xian", "起先" }, { "qi xiang", "奇想" }, { "qi xiang", "气象" },
			{ "qi xiang bu men", "气象部门" }, { "qi xiang ju", "气象局" }, { "qi xiang tai", "气象台" }, { "qi xie", "器械" }, { "qi xin", "齐心" },
			{ "qi xin xie li", "齐心协力" }, { "qi xing", "七星" }, { "qi xing", "骑行" }, { "qi xu", "期许" }, { "qi xu", "气虚" }, { "qi xue", "气血" }, { "qi ya", "欺压" },
			{ "qi ya", "气压" }, { "qi ya", "起亚" }, { "qi ye", "七夜" }, { "qi ye", "企业" }, { "qi ye ban", "企业版" }, { "qi ye dan wei", "企业单位" },
			{ "qi ye fa ren", "企业法人" }, { "qi ye fa zhan", "企业发展" }, { "qi ye gai ge", "企业改革" }, { "qi ye gai zhi", "企业改制" }, { "qi ye guan li", "企业管理" },
			{ "qi ye gui mo", "企业规模" }, { "qi ye ji", "企业级" }, { "qi ye ji tuan", "企业集团" }, { "qi ye jia", "企业家" }, { "qi ye jian", "企业间" },
			{ "qi ye jie", "企业界" }, { "qi ye jing ying", "企业经营" }, { "qi ye ming cheng", "企业名称" }, { "qi ye ming lu", "企业名录" }, { "qi ye nei bu", "企业内部" },
			{ "qi ye nian jin", "企业年金" }, { "qi ye pin pai", "企业品牌" }, { "qi ye wang zhan", "企业网站" }, { "qi ye wen hua", "企业文化" },
			{ "qi ye xing xiang", "企业形象" }, { "qi ye yong hu", "企业用户" }, { "qi ye yuan gong", "企业员工" }, { "qi ye zhan lue", "企业战略" },
			{ "qi ye zhi gong", "企业职工" }, { "qi ye zhu", "企业主" }, { "qi yi", "其一" }, { "qi yi", "其意" }, { "qi yi", "奇异" }, { "qi yi", "歧义" },
			{ "qi yi", "起义" }, { "qi yin", "起因" }, { "qi yong", "启用" }, { "qi yong", "起用" }, { "qi you", "汽油" }, { "qi yu", "其余" }, { "qi yu", "奇遇" },
			{ "qi yuan", "起源" }, { "qi yue", "七月" }, { "qi yue", "器乐" }, { "qi yue", "契约" }, { "qi yue fen", "七月份" }, { "qi zai", "骑在" }, { "qi zha", "欺诈" },
			{ "qi zhe", "起着" }, { "qi zhe", "骑着" }, { "qi zhi", "岂止" }, { "qi zhi", "岂知" }, { "qi zhi", "旗帜" }, { "qi zhi", "期指" }, { "qi zhi", "气质" },
			{ "qi zhi xian ming", "旗帜鲜明" }, { "qi zhong", "七种" }, { "qi zhong", "其中" }, { "qi zhong", "器重" }, { "qi zhong", "期中" }, { "qi zhong ji", "起重机" },
			{ "qi zhong yi wei", "其中一位" }, { "qi zhu yao", "其主要" }, { "qi zi", "其子" }, { "qi zi", "妻子" }, { "qi zi", "旗子" }, { "qi zi", "棋子" },
			{ "qi zi xing che", "骑自行车" }, { "qia", "冾" }, { "qia", "卡" }, { "qia", "帢" }, { "qia", "恰" }, { "qia", "愘" }, { "qia", "掐" }, { "qia", "殎" },
			{ "qia", "洽" }, { "qia", "硈" }, { "qia", "葜" }, { "qia", "袷" }, { "qia", "酠" }, { "qia", "鞐" }, { "qia", "髂" }, { "qia", "鮚" },
			{ "qia dang", "恰当" }, { "qia dao hao chu", "恰到好处" }, { "qia feng", "恰逢" }, { "qia hao", "恰好" }, { "qia jia", "掐架" }, { "qia qia", "恰恰" },
			{ "qia qia xiang fan", "恰恰相反" }, { "qia qiao", "恰巧" }, { "qia ru", "恰如" }, { "qia ru qi fen", "恰如其分" }, { "qia si", "恰似" }, { "qia si", "掐死" },
			{ "qia tan", "洽谈" }, { "qia tan hui", "洽谈会" }, { "qian", "乾" }, { "qian", "仟" }, { "qian", "仱" }, { "qian", "佥" }, { "qian", "倩" },
			{ "qian", "傔" }, { "qian", "僉" }, { "qian", "刋" }, { "qian", "前" }, { "qian", "千" }, { "qian", "唊" }, { "qian", "嗛" }, { "qian", "堑" },
			{ "qian", "塹" }, { "qian", "墘" }, { "qian", "奷" }, { "qian", "婜" }, { "qian", "媊" }, { "qian", "岍" }, { "qian", "岒" }, { "qian", "嵌" },
			{ "qian", "悭" }, { "qian", "愆" }, { "qian", "慊" }, { "qian", "扦" }, { "qian", "拑" }, { "qian", "挳" }, { "qian", "掮" }, { "qian", "揃" },
			{ "qian", "揵" }, { "qian", "搴" }, { "qian", "攐" }, { "qian", "攓" }, { "qian", "朁" }, { "qian", "棈" }, { "qian", "椠" }, { "qian", "榩" },
			{ "qian", "槧" }, { "qian", "檶" }, { "qian", "櫏" }, { "qian", "欠" }, { "qian", "欿" }, { "qian", "歁" }, { "qian", "歉" }, { "qian", "汧" },
			{ "qian", "浅" }, { "qian", "淺" }, { "qian", "潛" }, { "qian", "潜" }, { "qian", "濳" }, { "qian", "灊" }, { "qian", "牵" }, { "qian", "牽" },
			{ "qian", "犍" }, { "qian", "竏" }, { "qian", "签" }, { "qian", "箝" }, { "qian", "箞" }, { "qian", "篏" }, { "qian", "篟" }, { "qian", "簽" },
			{ "qian", "籖" }, { "qian", "籤" }, { "qian", "粁" }, { "qian", "縴" }, { "qian", "繾" }, { "qian", "纤" }, { "qian", "缱" }, { "qian", "肷" },
			{ "qian", "芊" }, { "qian", "芡" }, { "qian", "茜" }, { "qian", "荨" }, { "qian", "葥" }, { "qian", "蒨" }, { "qian", "蕁" }, { "qian", "虔" },
			{ "qian", "蜸" }, { "qian", "褰" }, { "qian", "謙" }, { "qian", "譴" }, { "qian", "谦" }, { "qian", "谴" }, { "qian", "軡" }, { "qian", "輤" },
			{ "qian", "迁" }, { "qian", "遣" }, { "qian", "遷" }, { "qian", "鈐" }, { "qian", "鉗" }, { "qian", "鉛" }, { "qian", "銭" }, { "qian", "錢" },
			{ "qian", "鐱" }, { "qian", "鑓" }, { "qian", "鑯" }, { "qian", "钎" }, { "qian", "钤" }, { "qian", "钱" }, { "qian", "钳" }, { "qian", "铅" },
			{ "qian", "阡" }, { "qian", "雃" }, { "qian", "靬" }, { "qian", "韆" }, { "qian", "顅" }, { "qian", "馯" }, { "qian", "騚" }, { "qian", "騝" },
			{ "qian", "騫" }, { "qian", "骞" }, { "qian", "鰜" }, { "qian", "鰬" }, { "qian", "鶼" }, { "qian", "黔" }, { "qian", "黚" } };
};
