package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN60 {
	public static String[][] pl = { { "zai chi", "再吃" }, { "zai chu", "再出" }, { "zai chuan", "再传" }, { "zai chuang", "再创" }, { "zai chuang", "在床" },
			{ "zai chuang shang", "在床上" }, { "zai ci", "再次" }, { "zai ci", "在此" }, { "zai ci zhi qian", "在此之前" }, { "zai cong", "再从" }, { "zai da", "再大" },
			{ "zai da", "再打" }, { "zai da", "在大" }, { "zai dao", "再到" }, { "zai deng", "再等" }, { "zai dian", "再点" }, { "zai ding", "再顶" }, { "zai du", "再度" },
			{ "zai du", "再读" }, { "zai du", "在读" }, { "zai duo", "再多" }, { "zai er san", "再而三" }, { "zai fa", "再发" }, { "zai fang", "再放" },
			{ "zai fei ji shang", "在飞机上" }, { "zai feng zhong", "在风中" }, { "zai gai", "再改" }, { "zai gan ma", "在干吗" }, { "zai gang", "在岗" },
			{ "zai gao", "再高" }, { "zai ge", "在各" }, { "zai gei", "再给" }, { "zai gen", "再跟" }, { "zai gong zuo zhong", "在工作中" }, { "zai guo", "再过" },
			{ "zai guo ji shang", "在国际上" }, { "zai hai", "灾害" }, { "zai hang", "在行" }, { "zai hao", "再好" }, { "zai he", "载荷" }, { "zai hei an zhong", "在黑暗中" },
			{ "zai hou", "灾后" }, { "zai hu", "在乎" }, { "zai hu ni", "在乎你" }, { "zai hua", "在华" }, { "zai hui", "再回" }, { "zai hun", "再婚" },
			{ "zai huo", "灾祸" }, { "zai huo che shang", "在火车上" }, { "zai ji", "在即" }, { "zai jia", "再加" }, { "zai jia", "在家" }, { "zai jian", "再建" },
			{ "zai jian", "再见" }, { "zai jian", "在建" }, { "zai jiang", "再将" }, { "zai jiang", "再讲" }, { "zai jiang", "再降" }, { "zai jie", "再接" },
			{ "zai jie zai li", "再接再厉" }, { "zai jin", "再进" }, { "zai jing", "在京" }, { "zai jiu ba", "在酒吧" }, { "zai jiu ye", "再就业" }, { "zai kai", "再开" },
			{ "zai kan", "再看" }, { "zai kan", "在看" }, { "zai ke", "载客" }, { "zai lai", "再来" }, { "zai lai yi ci", "再来一次" }, { "zai li shi shang", "在历史上" },
			{ "zai liang ge", "在两个" }, { "zai liang zhou nei", "在两周内" }, { "zai ma", "在马" }, { "zai mai", "再买" }, { "zai mang", "再忙" }, { "zai mei", "再没" },
			{ "zai mei", "在美" }, { "zai meng li", "在梦里" }, { "zai meng zhong", "在梦中" }, { "zai min", "灾民" }, { "zai ming", "载明" }, { "zai mou", "在某" },
			{ "zai na", "再拿" }, { "zai na", "在哪" }, { "zai na", "在那" }, { "zai nan", "灾难" }, { "zai nan xing", "灾难性" }, { "zai nei", "在内" },
			{ "zai ni mian qian", "在你面前" }, { "zai ni shen bian", "在你身边" }, { "zai nin", "在您" }, { "zai pang", "在旁" }, { "zai pei", "栽培" },
			{ "zai pei ji shu", "栽培技术" }, { "zai qi", "再起" }, { "zai qi", "在其" }, { "zai qian", "在前" }, { "zai qing", "灾情" }, { "zai qu", "再去" },
			{ "zai qu", "灾区" }, { "zai rang", "再让" }, { "zai ren", "载人" }, { "zai ren hang tian", "载人航天" }, { "zai rong zi", "再融资" }, { "zai ru", "载入" },
			{ "zai ru zhong", "载入中" }, { "zai san", "再三" }, { "zai sha", "宰杀" }, { "zai shang", "再上" }, { "zai she hui shang", "在社会上" }, { "zai shen", "再审" },
			{ "zai shen", "在身" }, { "zai sheng", "再生" }, { "zai sheng huo zhong", "在生活中" }, { "zai shi", "再试" }, { "zai shi", "在世" },
			{ "zai shi jian zhong", "在实践中" }, { "zai shi jie shang", "在世界上" }, { "zai shou", "在手" }, { "zai shui li", "在水里" }, { "zai shuo", "再说" },
			{ "zai shuo", "在说" }, { "zai si xiang shang", "在思想上" }, { "zai song", "再送" }, { "zai suo nan mian", "在所难免" }, { "zai ta", "在他" },
			{ "zai ta", "在她" }, { "zai tan", "再谈" }, { "zai ti", "再提" }, { "zai ti", "载体" }, { "zai tian", "再添" }, { "zai ting", "再听" }, { "zai ting", "在听" },
			{ "zai wai", "在外" }, { "zai wang", "再往" }, { "zai wang ba", "在网吧" }, { "zai wang luo shang", "在网络上" }, { "zai wang zhan", "在网站" },
			{ "zai wen", "再问" }, { "zai wo", "在我" }, { "zai wo xin", "在我心" }, { "zai wu", "再无" }, { "zai xia", "再下" }, { "zai xia", "在下" },
			{ "zai xian", "再掀" }, { "zai xian", "再现" }, { "zai xian", "在线" }, { "zai xian bo fang", "在线播放" }, { "zai xian fu wu", "在线服务" },
			{ "zai xian guan kan", "在线观看" }, { "zai xian kan", "在线看" }, { "zai xian ren shu", "在线人数" }, { "zai xiang", "再向" }, { "zai xiang", "再想" },
			{ "zai xiang", "在想" }, { "zai xiang", "宰相" }, { "zai xiao", "在校" }, { "zai xiao sheng", "在校生" }, { "zai xiao xue sheng", "在校学生" },
			{ "zai xie", "再写" }, { "zai xie", "在写" }, { "zai xin", "在心" }, { "zai xin", "在新" }, { "zai xin chuang kou", "在新窗口" }, { "zai xin de", "在新的" },
			{ "zai xing", "再行" }, { "zai yang guang xia", "在阳光下" }, { "zai ye", "再也" }, { "zai ye jie", "在业界" }, { "zai ye mei you", "再也没有" },
			{ "zai ye mian", "在页面" }, { "zai yi", "再以" }, { "zai yi", "再议" }, { "zai yi", "在一" }, { "zai yi", "在意" }, { "zai yi ci", "再一次" },
			{ "zai yi ci", "在一次" }, { "zai yi jia", "在一家" }, { "zai yong", "再用" }, { "zai yong", "在用" }, { "zai you", "再有" }, { "zai you", "再由" },
			{ "zai yu", "在于" }, { "zai yu zhong", "在雨中" }, { "zai zai", "仔仔" }, { "zai zao", "再造" }, { "zai zhan", "再战" }, { "zai zhao", "再找" },
			{ "zai zhe", "再者" }, { "zai zhe", "在这" }, { "zai zhe", "载着" }, { "zai zhe fang mian", "在这方面" }, { "zai zhe yang de", "在这样的" },
			{ "zai zhe yi", "在这一" }, { "zai zhi", "在职" }, { "zai zhi", "栽植" }, { "zai zhong", "栽种" }, { "zai zhong", "载重" }, { "zai zhu", "仔猪" },
			{ "zai zhuang", "再装" }, { "zai zhuo mian shang", "在桌面上" }, { "zai zou", "再走" }, { "zai zuo", "再作" }, { "zai zuo", "再做" }, { "zai zuo", "在做" },
			{ "zai zuo", "在座" }, { "zan", "偺" }, { "zan", "儹" }, { "zan", "咱" }, { "zan", "喒" }, { "zan", "噆" }, { "zan", "囋" }, { "zan", "寁" },
			{ "zan", "拶" }, { "zan", "攒" }, { "zan", "昝" }, { "zan", "暂" }, { "zan", "暫" }, { "zan", "灒" }, { "zan", "瓒" }, { "zan", "瓚" }, { "zan", "禶" },
			{ "zan", "簪" }, { "zan", "糌" }, { "zan", "臢" }, { "zan", "讃" }, { "zan", "讚" }, { "zan", "賛" }, { "zan", "贊" }, { "zan", "赞" }, { "zan", "趱" },
			{ "zan", "蹔" }, { "zan", "酇" }, { "zan", "錾" }, { "zan", "鏨" }, { "zan", "鐕" }, { "zan", "饡" }, { "zan bu", "暂不" }, { "zan bu jue kou", "赞不绝口" },
			{ "zan cheng", "赞成" }, { "zan ding", "暂定" }, { "zan ge", "赞歌" }, { "zan huan", "暂缓" }, { "zan jia", "咱家" }, { "zan lia", "咱俩" },
			{ "zan liang", "咱俩" }, { "zan mei", "赞美" }, { "zan men", "咱们" }, { "zan qian", "攒钱" }, { "zan qie", "暂且" }, { "zan shang", "赞赏" },
			{ "zan shi", "暂时" }, { "zan shi mei you", "暂时没有" }, { "zan shi xing", "暂时性" }, { "zan tan", "赞叹" }, { "zan ting", "暂停" }, { "zan tong", "赞同" },
			{ "zan wei", "暂未" }, { "zan wu", "暂无" }, { "zan xing ban fa", "暂行办法" }, { "zan xing gui ding", "暂行规定" }, { "zan xu", "赞许" }, { "zan yang", "赞扬" },
			{ "zan yu", "赞誉" }, { "zan zhu", "暂住" }, { "zan zhu", "赞助" }, { "zan zhu shang", "赞助商" }, { "zan zhu zheng", "暂住证" }, { "zang", "奘" },
			{ "zang", "弉" }, { "zang", "牂" }, { "zang", "脏" }, { "zang", "臓" }, { "zang", "臟" }, { "zang", "臧" }, { "zang", "葬" }, { "zang", "蔵" },
			{ "zang", "藏" }, { "zang", "賍" }, { "zang", "贓" }, { "zang", "赃" }, { "zang", "驵" }, { "zang", "髒" }, { "zang ao", "藏獒" },
			{ "zang chuan fo jiao", "藏传佛教" }, { "zang fu", "脏腑" }, { "zang hua", "脏话" }, { "zang kuan", "赃款" }, { "zang li", "葬礼" },
			{ "zang ling yang", "藏羚羊" }, { "zang min", "藏民" }, { "zang qi", "脏器" }, { "zang qu", "藏区" }, { "zang ren", "藏人" }, { "zang song", "葬送" },
			{ "zang wu", "赃物" }, { "zang xi xi", "脏兮兮" }, { "zang zu", "藏族" }, { "zao", "傮" }, { "zao", "凿" }, { "zao", "唣" }, { "zao", "喿" }, { "zao", "噪" },
			{ "zao", "慥" }, { "zao", "早" }, { "zao", "枣" }, { "zao", "梍" }, { "zao", "棗" }, { "zao", "澡" }, { "zao", "灶" }, { "zao", "煰" }, { "zao", "燥" },
			{ "zao", "璅" }, { "zao", "璪" }, { "zao", "皁" }, { "zao", "皂" }, { "zao", "竃" }, { "zao", "竈" }, { "zao", "簉" }, { "zao", "糟" }, { "zao", "繅" },
			{ "zao", "繰" }, { "zao", "藻" }, { "zao", "蚤" }, { "zao", "譟" }, { "zao", "趮" }, { "zao", "蹧" }, { "zao", "躁" }, { "zao", "造" }, { "zao", "遭" },
			{ "zao an", "早安" }, { "zao ban", "早班" }, { "zao bao", "早报" }, { "zao can", "早餐" }, { "zao cha", "早茶" }, { "zao chan", "早产" }, { "zao che", "造车" },
			{ "zao chen", "早晨" }, { "zao cheng", "造成" }, { "zao cheng sun shi", "造成损失" }, { "zao chu", "造出" }, { "zao chuan", "造船" }, { "zao chun", "早春" },
			{ "zao dao", "早稻" }, { "zao dao", "遭到" }, { "zao dian", "噪点" }, { "zao dian", "早点" }, { "zao dong", "躁动" }, { "zao fan", "早饭" },
			{ "zao fan", "造反" }, { "zao fang", "造访" }, { "zao fu", "造福" }, { "zao gai", "早该" }, { "zao gao", "糟糕" }, { "zao hua", "造化" }, { "zao jia", "造价" },
			{ "zao jia", "造假" }, { "zao jiu", "早就" }, { "zao jiu", "造就" }, { "zao lian", "早恋" }, { "zao lin", "造林" }, { "zao nian", "早年" },
			{ "zao nie", "造孽" }, { "zao pan", "早盘" }, { "zao po", "糟粕" }, { "zao qi", "早期" }, { "zao qi", "早起" }, { "zao qian", "早前" }, { "zao re", "燥热" },
			{ "zao ren", "遭人" }, { "zao ri", "早日" }, { "zao ri kang fu", "早日康复" }, { "zao shang", "早上" }, { "zao shang hao", "早上好" },
			{ "zao shang qi chuang", "早上起床" }, { "zao shang qi lai", "早上起来" }, { "zao sheng", "噪声" }, { "zao shi", "早逝" }, { "zao shi", "造势" },
			{ "zao shou", "遭受" }, { "zao shu", "早熟" }, { "zao shui", "早睡" }, { "zao shui zao qi", "早睡早起" }, { "zao shuo", "早说" }, { "zao si", "早死" },
			{ "zao ta", "糟蹋" }, { "zao tang", "澡堂" }, { "zao tui", "早退" }, { "zao wan", "早晚" }, { "zao xian", "早先" }, { "zao xie", "早些" }, { "zao xie", "早泄" },
			{ "zao xing", "造型" }, { "zao xing she ji", "造型设计" }, { "zao xing shi", "造型师" }, { "zao xue", "造血" }, { "zao yang", "遭殃" }, { "zao yao", "造谣" },
			{ "zao yi", "早已" }, { "zao yi", "造诣" }, { "zao yin", "噪音" }, { "zao ying", "造影" }, { "zao you", "早有" }, { "zao yu", "早于" }, { "zao yu", "遭遇" },
			{ "zao yun", "早孕" }, { "zao zai", "早在" }, { "zao zao", "早早" }, { "zao zhi", "早知" }, { "zao zhi", "造纸" }, { "zao zhi dao", "早知道" },
			{ "zao zhuang", "枣庄" }, { "zao zuo", "造作" }, { "ze", "仄" }, { "ze", "伬" }, { "ze", "侧" }, { "ze", "则" }, { "ze", "則" }, { "ze", "厠" },
			{ "ze", "咋" }, { "ze", "啧" }, { "ze", "嘖" }, { "ze", "崱" }, { "ze", "帻" }, { "ze", "幘" }, { "ze", "庂" }, { "ze", "択" }, { "ze", "择" },
			{ "ze", "捑" }, { "ze", "擇" }, { "ze", "昃" }, { "ze", "樍" }, { "ze", "沢" }, { "ze", "泽" }, { "ze", "滜" }, { "ze", "澤" }, { "ze", "稄" },
			{ "ze", "箦" }, { "ze", "舴" }, { "ze", "蘀" }, { "ze", "蠌" }, { "ze", "襗" }, { "ze", "謮" }, { "ze", "責" }, { "ze", "賾" }, { "ze", "责" },
			{ "ze", "赜" }, { "ze", "迮" }, { "ze", "鸅" }, { "ze bei", "责备" }, { "ze bian", "责编" }, { "ze biao shi", "则表示" }, { "ze bu", "则不" },
			{ "ze cheng", "责成" }, { "ze cong", "则从" }, { "ze guai", "责怪" }, { "ze hui", "则会" }, { "ze ji", "择机" }, { "ze jiang", "则将" }, { "ze ke", "则可" },
			{ "ze ke yi", "则可以" }, { "ze ling", "责令" }, { "ze ma", "责骂" }, { "ze min", "泽民" }, { "ze nan", "责难" }, { "ze neng", "则能" }, { "ze ou", "择偶" },
			{ "ze ren", "责任" }, { "ze ren bian ji", "责任编辑" }, { "ze ren gan", "责任感" }, { "ze ren ren", "责任人" }, { "ze ren ren yuan", "责任人员" },
			{ "ze ren shu", "责任书" }, { "ze ren xian", "责任险" }, { "ze ren xin", "责任心" }, { "ze ren yi shi", "责任意识" }, { "ze ren zhi", "责任制" },
			{ "ze ren zhui jiu", "责任追究" }, { "ze shi", "则是" }, { "ze shuo", "则说" }, { "ze wei", "则为" }, { "ze wen", "责问" }, { "ze xiao", "择校" },
			{ "ze xu", "则需" }, { "ze yao", "则要" }, { "ze ye", "择业" }, { "ze yi", "则以" }, { "ze ying", "则应" }, { "ze yong", "则用" }, { "ze you", "则有" },
			{ "ze you", "则由" }, { "ze you", "择优" }, { "ze zai", "则在" }, { "ze ze", "啧啧" }, { "zei", "蠈" }, { "zei", "賊" }, { "zei", "贼" }, { "zei", "鯽" },
			{ "zen", "囎" }, { "zen", "怎" }, { "zen", "譖" }, { "zen", "譛" }, { "zen", "谮" }, { "zen hui", "怎会" }, { "zen me", "怎么" }, { "zen me ba", "怎么把" },
			{ "zen me ban", "怎么办" }, { "zen me ban a", "怎么办啊" }, { "zen me chi", "怎么吃" }, { "zen me chu li", "怎么处理" }, { "zen me da", "怎么打" },
			{ "zen me gai", "怎么改" }, { "zen me gao", "怎么搞" }, { "zen me hui shi", "怎么回事" }, { "zen me jiang", "怎么讲" }, { "zen me jie jue", "怎么解决" },
			{ "zen me kan", "怎么看" }, { "zen me ke neng", "怎么可能" }, { "zen me la", "怎么啦" }, { "zen me neng gou", "怎么能够" }, { "zen me nong", "怎么弄" },
			{ "zen me qu", "怎么去" }, { "zen me suan", "怎么算" }, { "zen me wan", "怎么玩" }, { "zen me xie", "怎么写" }, { "zen me yang", "怎么样" },
			{ "zen me yong", "怎么用" }, { "zen me zhao", "怎么找" }, { "zen me zhao", "怎么着" }, { "zen me zhe", "怎么着" }, { "zen me zhe me", "怎么这么" },
			{ "zen me zou", "怎么走" }, { "zen me zuo", "怎么做" }, { "zen neng", "怎能" }, { "zen neng bu", "怎能不" }, { "zen yang", "怎样" },
			{ "zen yang cai neng", "怎样才能" }, { "zen yang zuo", "怎样做" }, { "zeng", "増" }, { "zeng", "增" }, { "zeng", "憎" }, { "zeng", "曽" }, { "zeng", "曾" },
			{ "zeng", "橧" }, { "zeng", "璔" }, { "zeng", "甑" }, { "zeng", "矰" }, { "zeng", "磳" }, { "zeng", "縡" }, { "zeng", "繒" }, { "zeng", "综" },
			{ "zeng", "缯" }, { "zeng", "罾" }, { "zeng", "贈" }, { "zeng", "赠" }, { "zeng", "鄫" }, { "zeng", "锃" }, { "zeng bai", "增白" }, { "zeng bu", "增补" },
			{ "zeng cang", "增仓" }, { "zeng chan", "增产" }, { "zeng cheng", "增城" }, { "zeng chi", "增持" }, { "zeng da", "增大" }, { "zeng dao ren", "曾道人" },
			{ "zeng duo", "增多" }, { "zeng fa", "增发" }, { "zeng fei", "增肥" }, { "zeng fu", "增幅" }, { "zeng gao", "增高" }, { "zeng guo fan", "曾国藩" },
			{ "zeng hen", "憎恨" }, { "zeng hou", "增厚" }, { "zeng jia", "增加" }, { "zeng jia zhi", "增加值" }, { "zeng jian", "增减" }, { "zeng jin", "增进" },
			{ "zeng liang", "增量" }, { "zeng pin", "赠品" }, { "zeng qiang", "增强" }, { "zeng qing hong", "曾庆红" }, { "zeng se", "增色" }, { "zeng she", "增设" },
			{ "zeng sheng", "增生" }, { "zeng shou", "增收" }, { "zeng song", "赠送" }, { "zeng su", "增速" }, { "zeng tian", "增添" }, { "zeng wu", "憎恶" },
			{ "zeng xiao", "增效" }, { "zeng ya", "增压" }, { "zeng yi", "增益" }, { "zeng yin quan", "曾荫权" }, { "zeng yu", "赠与" }, { "zeng yuan", "增援" },
			{ "zeng zhang", "增长" }, { "zeng zhang dian", "增长点" }, { "zeng zhang fang shi", "增长方式" }, { "zeng zhang fu du", "增长幅度" },
			{ "zeng zhang lv", "增长率" }, { "zeng zhang su du", "增长速度" }, { "zeng zhi", "增值" }, { "zeng zhi", "增殖" }, { "zeng zhi", "增至" },
			{ "zeng zhi fu wu", "增值服务" }, { "zeng zhi shui", "增值税" }, { "zeng zhi wei", "曾志伟" }, { "zeng zhi ye wu", "增值业务" }, { "zeng zi", "增资" },
			{ "zeng zi kuo gu", "增资扩股" }, { "zha", "乍" }, { "zha", "偞" }, { "zha", "剳" }, { "zha", "劄" }, { "zha", "吒" }, { "zha", "咋" }, { "zha", "咤" },
			{ "zha", "哳" }, { "zha", "喋" }, { "zha", "喥" }, { "zha", "喳" }, { "zha", "囃" }, { "zha", "奓" }, { "zha", "扎" }, { "zha", "扠" }, { "zha", "抯" },
			{ "zha", "挓" }, { "zha", "挿" }, { "zha", "揷" }, { "zha", "揸" }, { "zha", "搾" }, { "zha", "札" }, { "zha", "柞" }, { "zha", "查" }, { "zha", "栅" },
			{ "zha", "楂" }, { "zha", "榨" }, { "zha", "樝" }, { "zha", "渣" }, { "zha", "溠" }, { "zha", "潳" }, { "zha", "炸" }, { "zha", "煠" }, { "zha", "痄" },
			{ "zha", "皻" }, { "zha", "眨" }, { "zha", "砟" }, { "zha", "箚" }, { "zha", "紮" }, { "zha", "苲" }, { "zha", "蔖" }, { "zha", "蚱" }, { "zha", "蚻" },
			{ "zha", "蜡" }, { "zha", "觰" }, { "zha", "詐" }, { "zha", "譇" }, { "zha", "譗" }, { "zha", "诈" }, { "zha", "軋" }, { "zha", "轧" }, { "zha", "醡" },
			{ "zha", "鍘" }, { "zha", "铡" }, { "zha", "閘" }, { "zha", "闸" }, { "zha", "霅" }, { "zha", "鞢" }, { "zha", "鮓" }, { "zha", "鰈" }, { "zha", "齄" },
			{ "zha", "齇" }, { "zha", "齟" }, { "zha", "齰" }, { "zha bei", "闸北" }, { "zha cai", "榨菜" }, { "zha da", "渣打" }, { "zha dan", "炸弹" },
			{ "zha diao", "炸掉" }, { "zha dui", "扎堆" }, { "zha gen", "扎根" }, { "zha hui", "炸毁" }, { "zha jiang mian", "炸酱面" }, { "zha jin", "扎进" },
			{ "zha ka wei", "扎卡维" }, { "zha kai", "炸开" }, { "zha lan", "栅栏" }, { "zha le", "炸了" }, { "zha men", "闸门" }, { "zha pian", "诈骗" },
			{ "zha shi", "扎实" }, { "zha shi tui jin", "扎实推进" }, { "zha si", "炸死" }, { "zha xi", "扎西" }, { "zha yan", "眨眼" }, { "zha yao", "炸药" },
			{ "zha zha shi shi", "扎扎实实" }, { "zha zi", "渣滓" }, { "zhai", "侧" }, { "zhai", "债" }, { "zhai", "債" }, { "zhai", "厏" }, { "zhai", "哜" },
			{ "zhai", "嚌" }, { "zhai", "宅" }, { "zhai", "寨" }, { "zhai", "择" }, { "zhai", "捚" }, { "zhai", "摘" }, { "zhai", "斋" }, { "zhai", "斎" },
			{ "zhai", "檡" }, { "zhai", "瘵" }, { "zhai", "砦" }, { "zhai", "窄" }, { "zhai", "簀" }, { "zhai", "粂" }, { "zhai", "翟" }, { "zhai", "鉙" },
			{ "zhai", "駘" }, { "zhai", "骴" }, { "zhai", "齋" }, { "zhai bian", "摘编" }, { "zhai chao", "摘抄" }, { "zhai chu", "摘除" }, { "zhai de", "摘得" },
			{ "zhai diao", "摘掉" }, { "zhai fu", "窄幅" }, { "zhai ji di", "宅基地" }, { "zhai ji song", "宅急送" }, { "zhai lu", "摘录" }, { "zhai qu", "摘取" },
			{ "zhai quan", "债券" }, { "zhai quan", "债权" }, { "zhai quan ji jin", "债券基金" }, { "zhai quan ren", "债权人" }, { "zhai quan shi chang", "债券市场" },
			{ "zhai shi", "债市" }, { "zhai wu", "债务" }, { "zhai wu chong zu", "债务重组" }, { "zhai wu ren", "债务人" }, { "zhai xia", "摘下" }, { "zhai yao", "摘要" },
			{ "zhai zhu", "债主" }, { "zhai zi", "摘自" }, { "zhan", "佔" }, { "zhan", "偡" }, { "zhan", "占" }, { "zhan", "嫸" }, { "zhan", "展" }, { "zhan", "崭" },
			{ "zhan", "嵁" }, { "zhan", "嶄" }, { "zhan", "惉" }, { "zhan", "战" }, { "zhan", "戦" }, { "zhan", "戰" }, { "zhan", "搌" }, { "zhan", "斩" },
			{ "zhan", "斬" }, { "zhan", "旃" }, { "zhan", "栈" }, { "zhan", "栴" }, { "zhan", "桟" }, { "zhan", "棧" }, { "zhan", "橏" }, { "zhan", "欃" },
			{ "zhan", "毡" }, { "zhan", "氈" }, { "zhan", "沾" }, { "zhan", "湛" }, { "zhan", "琖" }, { "zhan", "盏" }, { "zhan", "盞" }, { "zhan", "瞻" },
			{ "zhan", "站" }, { "zhan", "粘" }, { "zhan", "綻" }, { "zhan", "绽" }, { "zhan", "薝" }, { "zhan", "蘸" }, { "zhan", "虥" }, { "zhan", "蛅" },
			{ "zhan", "襢" }, { "zhan", "詀" }, { "zhan", "詹" }, { "zhan", "譧" }, { "zhan", "譫" }, { "zhan", "谵" }, { "zhan", "跕" }, { "zhan", "輚" },
			{ "zhan", "輾" }, { "zhan", "轏" }, { "zhan", "辗" }, { "zhan", "邅" }, { "zhan", "醆" }, { "zhan", "霑" }, { "zhan", "颤" }, { "zhan", "颭" },
			{ "zhan", "餰" }, { "zhan", "饘" }, { "zhan", "驏" }, { "zhan", "驙" }, { "zhan", "魙" }, { "zhan", "鱣" }, { "zhan", "鳽" }, { "zhan", "鸇" },
			{ "zhan", "黵" }, { "zhan bai", "战败" }, { "zhan ban", "展板" }, { "zhan bao", "战报" }, { "zhan bei", "战备" }, { "zhan bian", "沾边" },
			{ "zhan bu", "占卜" }, { "zhan chang", "战场" }, { "zhan che", "战车" }, { "zhan chi", "展翅" }, { "zhan chu", "展出" }, { "zhan chu lai", "站出来" },
			{ "zhan dao", "占到" }, { "zhan dao", "占道" }, { "zhan dao", "站到" }, { "zhan de", "站得" }, { "zhan di", "占地" }, { "zhan di", "战地" },
			{ "zhan di mian ji", "占地面积" }, { "zhan dian", "站点" }, { "zhan ding jie tie", "斩钉截铁" }, { "zhan dou", "战斗" }, { "zhan dou ji", "战斗机" },
			{ "zhan dou li", "战斗力" }, { "zhan duan", "斩断" }, { "zhan dui", "战队" }, { "zhan fa", "战法" }, { "zhan fan", "战犯" }, { "zhan fang", "绽放" },
			{ "zhan fu", "战俘" }, { "zhan gang", "站岗" }, { "zhan ge", "战歌" }, { "zhan gong", "战功" }, { "zhan guan", "展馆" }, { "zhan guo", "战国" },
			{ "zhan guo", "战果" }, { "zhan hou", "战后" }, { "zhan hui", "展会" }, { "zhan huo", "战火" }, { "zhan huo", "斩获" }, { "zhan ji", "战机" },
			{ "zhan ji", "战绩" }, { "zhan jian", "战舰" }, { "zhan jiang", "湛江" }, { "zhan jin", "占尽" }, { "zhan ju", "占据" }, { "zhan ju", "战局" },
			{ "zhan kai", "展开" }, { "zhan kuang", "战况" }, { "zhan lan", "展览" }, { "zhan lan", "湛蓝" }, { "zhan lan guan", "展览馆" }, { "zhan lan hui", "展览会" },
			{ "zhan le", "占了" }, { "zhan le", "沾了" }, { "zhan le", "站了" }, { "zhan li", "战力" }, { "zhan li", "战栗" }, { "zhan li", "站立" },
			{ "zhan li pin", "战利品" }, { "zhan lian", "粘连" }, { "zhan ling", "占领" }, { "zhan lu", "展露" }, { "zhan lu tou jiao", "崭露头角" }, { "zhan luan", "战乱" },
			{ "zhan lue", "战略" }, { "zhan lue gui hua", "战略规划" }, { "zhan lue he zuo", "战略合作" }, { "zhan lue jue ce", "战略决策" }, { "zhan lue mu biao", "战略目标" },
			{ "zhan lue si xiang", "战略思想" }, { "zhan lue xing", "战略性" }, { "zhan lue yi yi", "战略意义" }, { "zhan ma", "战马" }, { "zhan man", "沾满" },
			{ "zhan mu si", "詹姆斯" }, { "zhan nei", "站内" }, { "zhan pai", "站牌" }, { "zhan pian yi", "占便宜" }, { "zhan pin", "展品" }, { "zhan ping", "战平" },
			{ "zhan qi", "站起" }, { "zhan qi lai", "站起来" }, { "zhan qi shen", "站起身" }, { "zhan qian", "战前" }, { "zhan qu", "展区" }, { "zhan qu", "战区" },
			{ "zhan quan", "占全" }, { "zhan ran", "沾染" }, { "zhan sha", "斩杀" }, { "zhan shang", "沾上" }, { "zhan shang", "站上" }, { "zhan shen", "战神" },
			{ "zhan sheng", "战胜" }, { "zhan shi", "展示" }, { "zhan shi", "战事" }, { "zhan shi", "战士" }, { "zhan shi", "战时" }, { "zhan shi chu", "展示出" },
			{ "zhan shou", "斩首" }, { "zhan shu", "战术" }, { "zhan si", "战死" }, { "zhan tai", "展台" }, { "zhan tai", "站台" }, { "zhan tie", "粘贴" },
			{ "zhan ting", "展厅" }, { "zhan wang", "展望" }, { "zhan wei", "占位" }, { "zhan wei", "展位" }, { "zhan wei", "站位" }, { "zhan wen", "站稳" },
			{ "zhan wu", "站务" }, { "zhan xian", "占线" }, { "zhan xian", "展现" }, { "zhan xian", "战线" }, { "zhan xiao", "展销" }, { "zhan xin", "崭新" },
			{ "zhan xing", "占星" }, { "zhan yang", "瞻仰" }, { "zhan yi", "战役" }, { "zhan yong", "占用" }, { "zhan yong kong jian", "占用空间" },
			{ "zhan yong lv", "占用率" }, { "zhan you", "占优" }, { "zhan you", "占有" }, { "zhan you", "战友" }, { "zhan you lv", "占有率" }, { "zhan zai", "站在" },
			{ "zhan zai", "粘在" }, { "zhan zhan jing jing", "战战兢兢" }, { "zhan zhan zi xi", "沾沾自喜" }, { "zhan zhang", "站长" }, { "zhan zhao", "展昭" },
			{ "zhan zhe", "占着" }, { "zhan zhe", "站着" }, { "zhan zheng", "战争" }, { "zhan zhong", "战中" }, { "zhan zhu", "站住" }, { "zhan zhuan", "辗转" },
			{ "zhan zong", "占总" }, { "zhan zuo", "占座" }, { "zhang", "丈" }, { "zhang", "仉" }, { "zhang", "仗" }, { "zhang", "傽" }, { "zhang", "墇" },
			{ "zhang", "嫜" }, { "zhang", "嶂" }, { "zhang", "帐" }, { "zhang", "帳" }, { "zhang", "幛" }, { "zhang", "张" }, { "zhang", "弡" }, { "zhang", "張" },
			{ "zhang", "彰" }, { "zhang", "慞" }, { "zhang", "扙" }, { "zhang", "掌" }, { "zhang", "暲" }, { "zhang", "杖" }, { "zhang", "樟" }, { "zhang", "涨" },
			{ "zhang", "漲" }, { "zhang", "漳" }, { "zhang", "獐" }, { "zhang", "璋" }, { "zhang", "瘴" }, { "zhang", "瞕" }, { "zhang", "章" }, { "zhang", "粀" },
			{ "zhang", "粻" }, { "zhang", "胀" }, { "zhang", "脹" }, { "zhang", "蟑" }, { "zhang", "賬" }, { "zhang", "账" }, { "zhang", "遧" }, { "zhang", "鄣" },
			{ "zhang", "长" }, { "zhang", "障" }, { "zhang", "鞝" }, { "zhang", "騿" }, { "zhang", "鱆" }, { "zhang ai", "障碍" }, { "zhang ai ling", "张爱玲" },
			{ "zhang ai wu", "障碍物" }, { "zhang bai zhi", "张柏芝" }, { "zhang bei", "长辈" }, { "zhang ben", "账本" }, { "zhang bin", "张斌" },
			{ "zhang bu da", "长不大" }, { "zhang chao", "张超" } };
};
