package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN10 {
	public static String[][] pl = { { "de shou", "得手" }, { "de shou", "的手" }, { "de shu", "的书" }, { "de shuo", "地说" }, { "de shuo", "的说" }, { "de si", "德斯" },
			{ "de ti", "得体" }, { "de tian du hou", "得天独厚" }, { "de ting", "地听" }, { "de wen", "德文" }, { "de xian", "得闲" }, { "de xin", "的信" },
			{ "de xin", "的心" }, { "de xin", "的新" }, { "de xin ying shou", "得心应手" }, { "de xing", "德性" }, { "de xing", "德行" }, { "de yang", "德阳" },
			{ "de yi", "得以" }, { "de yi", "得意" }, { "de yi", "得益" }, { "de yi yang yang", "得意洋洋" }, { "de yi yuan", "的一员" }, { "de yi zhi", "德意志" },
			{ "de yi zhong", "的一种" }, { "de yong fa", "的用法" }, { "de yu", "德育" }, { "de yu", "德语" }, { "de zhi", "得志" }, { "de zhi", "得知" },
			{ "de zhou", "德州" }, { "de zhu", "得主" }, { "de zhu", "得住" }, { "de zou", "地走" }, { "de zui", "得罪" }, { "de zuo", "地做" }, { "dei", "得" },
			{ "dei duo", "得多" }, { "dei hao", "得好" }, { "dei hen", "得很" }, { "dei qu", "得去" }, { "dei xian", "得先" }, { "dei you", "得有" }, { "den", "扥" },
			{ "den", "扽" }, { "deng", "凳" }, { "deng", "噔" }, { "deng", "墱" }, { "deng", "嬁" }, { "deng", "嶝" }, { "deng", "戥" }, { "deng", "澄" },
			{ "deng", "灯" }, { "deng", "燈" }, { "deng", "璒" }, { "deng", "登" }, { "deng", "瞪" }, { "deng", "磴" }, { "deng", "等" }, { "deng", "簦" },
			{ "deng", "豋" }, { "deng", "蹬" }, { "deng", "邓" }, { "deng", "鄧" }, { "deng", "鐙" }, { "deng", "镫" }, { "deng chang", "登场" },
			{ "deng chao", "邓超" }, { "deng che", "等车" }, { "deng chu", "登出" }, { "deng chu", "等处" }, { "deng da", "瞪大" }, { "deng dai", "等待" },
			{ "deng dao", "等到" }, { "deng deng", "等等" }, { "deng deng deng deng", "等等等等" }, { "deng di", "等地" }, { "deng ding", "登顶" }, { "deng gao", "登高" },
			{ "deng guan", "灯管" }, { "deng guang", "灯光" }, { "deng guo", "等国" }, { "deng hao", "等号" }, { "deng hong jiu lv", "灯红酒绿" }, { "deng hou", "等候" },
			{ "deng hui", "灯会" }, { "deng huo", "灯火" }, { "deng ji", "登基" }, { "deng ji", "登机" }, { "deng ji", "登记" }, { "deng ji", "等级" },
			{ "deng ji biao", "登记表" }, { "deng ji ji guan", "登记机关" }, { "deng ji jie suan", "登记结算" }, { "deng ji kao shi", "等级考试" },
			{ "deng ji shou xu", "登记手续" }, { "deng ji zheng", "登记证" }, { "deng ji zhu ce", "登记注册" }, { "deng jia", "等价" }, { "deng ju", "灯具" },
			{ "deng jun", "等均" }, { "deng ken", "邓肯" }, { "deng le", "瞪了" }, { "deng li jun", "邓丽君" }, { "deng li zi", "等离子" }, { "deng li zi ti", "等离子体" },
			{ "deng long", "灯笼" }, { "deng lu", "登录" }, { "deng lu", "登陆" }, { "deng lu qi", "登陆器" }, { "deng men", "登门" }, { "deng ni", "等你" },
			{ "deng pao", "灯泡" }, { "deng ren", "等人" }, { "deng ru", "登入" }, { "deng shan", "登山" }, { "deng shang", "登上" }, { "deng shi", "灯饰" },
			{ "deng si", "等死" }, { "deng ta", "灯塔" }, { "deng ta", "等他" }, { "deng tai", "登台" }, { "deng tong", "等同" }, { "deng wo", "等我" },
			{ "deng xia", "灯下" }, { "deng xian", "等闲" }, { "deng xiang", "灯箱" }, { "deng xiao", "等效" }, { "deng xiao ping", "邓小平" },
			{ "deng yi xi lie", "等一系列" }, { "deng yu", "等于" }, { "deng yue", "登月" }, { "deng zai", "登载" }, { "deng zhe", "瞪着" }, { "deng zhe", "等着" },
			{ "deng zhe ni", "等着你" }, { "deng zhi", "等值" }, { "deng zi", "凳子" }, { "di", "低" }, { "di", "俤" }, { "di", "厎" }, { "di", "呧" }, { "di", "嘀" },
			{ "di", "嚁" }, { "di", "地" }, { "di", "坻" }, { "di", "堤" }, { "di", "墑" }, { "di", "墬" }, { "di", "奀" }, { "di", "娣" }, { "di", "嫡" },
			{ "di", "帝" }, { "di", "底" }, { "di", "廸" }, { "di", "弟" }, { "di", "弤" }, { "di", "彽" }, { "di", "抵" }, { "di", "提" }, { "di", "敌" },
			{ "di", "敵" }, { "di", "旳" }, { "di", "柢" }, { "di", "梊" }, { "di", "梑" }, { "di", "棣" }, { "di", "氐" }, { "di", "涤" }, { "di", "滌" },
			{ "di", "滴" }, { "di", "焍" }, { "di", "牴" }, { "di", "狄" }, { "di", "玓" }, { "di", "甋" }, { "di", "的" }, { "di", "眱" }, { "di", "睇" },
			{ "di", "砥" }, { "di", "碲" }, { "di", "磾" }, { "di", "禘" }, { "di", "笛" }, { "di", "第" }, { "di", "籴" }, { "di", "糴" }, { "di", "締" },
			{ "di", "缔" }, { "di", "羝" }, { "di", "翟" }, { "di", "聜" }, { "di", "苖" }, { "di", "荻" }, { "di", "菂" }, { "di", "菧" }, { "di", "蒂" },
			{ "di", "蔋" }, { "di", "蔕" }, { "di", "藡" }, { "di", "蚳" }, { "di", "螮" }, { "di", "袛" }, { "di", "觌" }, { "di", "諦" }, { "di", "诋" },
			{ "di", "谛" }, { "di", "踶" }, { "di", "蹢" }, { "di", "軧" }, { "di", "迪" }, { "di", "递" }, { "di", "逓" }, { "di", "遞" }, { "di", "邸" },
			{ "di", "釱" }, { "di", "鏑" }, { "di", "镝" }, { "di", "阺" }, { "di", "隄" }, { "di", "靮" }, { "di", "鞮" }, { "di", "馰" }, { "di", "骶" },
			{ "di", "髢" }, { "di", "鸐" }, { "di ai", "低矮" }, { "di ao", "迪奥" }, { "di ba", "第八" }, { "di ba ci", "第八次" }, { "di ba jie", "第八届" },
			{ "di ba tiao", "第八条" }, { "di ba zhang", "第八章" }, { "di bai", "迪拜" }, { "di ban", "地板" }, { "di ban", "底板" }, { "di bao", "低保" },
			{ "di bao hu", "低保户" }, { "di bei", "地被" }, { "di biao", "地标" }, { "di biao", "地表" }, { "di bu", "地步" }, { "di bu", "底部" }, { "di ceng", "低层" },
			{ "di ceng", "地层" }, { "di ceng", "底层" }, { "di chan", "地产" }, { "di chan gu", "地产股" }, { "di chan shang", "地产商" }, { "di chao", "低潮" },
			{ "di chen", "低沉" }, { "di cheng ben", "低成本" }, { "di chu", "地处" }, { "di chu", "抵触" }, { "di chui", "低垂" }, { "di da", "抵达" }, { "di da", "滴答" },
			{ "di dai", "地带" }, { "di dang", "低档" }, { "di dang", "抵挡" }, { "di dao", "地道" }, { "di di", "低低" }, { "di di", "弟弟" }, { "di di", "滴滴" },
			{ "di di dao dao", "地地道道" }, { "di dian", "低点" }, { "di dian", "地点" }, { "di diao", "低调" }, { "di duan", "低端" }, { "di duan", "地段" },
			{ "di dui", "敌对" }, { "di er", "地儿" }, { "di er", "第二" }, { "di er ban", "第二版" }, { "di er bu", "第二部" }, { "di er bu fen", "第二部分" },
			{ "di er ceng", "第二层" }, { "di er chang", "第二场" }, { "di er ci", "第二次" }, { "di er da", "第二大" }, { "di er dai", "第二代" }, { "di er dian", "第二点" },
			{ "di er ji", "第二季" }, { "di er ji du", "第二季度" }, { "di er jie", "第二届" }, { "di er jie", "第二节" }, { "di er jie duan", "第二阶段" },
			{ "di er juan", "第二卷" }, { "di er kuan", "第二款" }, { "di er lun", "第二轮" }, { "di er ming", "第二名" }, { "di er pi", "第二批" }, { "di er qi", "第二期" },
			{ "di er shi jiu", "第二十九" }, { "di er shi qi", "第二十七" }, { "di er shi si", "第二十四" }, { "di er shi tiao", "第二十条" }, { "di er shi wu", "第二十五" },
			{ "di er tao", "第二套" }, { "di er tian", "第二天" }, { "di er tiao", "第二条" }, { "di er wei", "第二位" }, { "di er ye", "第二页" }, { "di er zhang", "第二章" },
			{ "di er zhong", "第二种" }, { "di fang", "地方" }, { "di fang", "堤防" }, { "di fang", "提防" }, { "di fang", "敌方" }, { "di fang cai zheng", "地方财政" },
			{ "di fang jing ji", "地方经济" }, { "di fang te se", "地方特色" }, { "di fang xing", "地方性" }, { "di fang zheng fu", "地方政府" }, { "di fen", "低分" },
			{ "di fu", "地府" }, { "di gei", "递给" }, { "di gong hao", "低功耗" }, { "di gu", "低估" }, { "di gu", "低谷" }, { "di gu", "嘀咕" }, { "di gua", "地瓜" },
			{ "di gui", "递归" }, { "di guo", "帝国" }, { "di guo shi dai", "帝国时代" }, { "di guo zhu yi", "帝国主义" }, { "di hui", "诋毁" }, { "di ji", "低级" },
			{ "di ji", "地基" }, { "di ji", "第几" }, { "di ji shi", "地级市" }, { "di jia", "低价" }, { "di jia", "地价" }, { "di jia", "底价" }, { "di jia gu", "低价股" },
			{ "di jia wei", "低价位" }, { "di jian", "递减" }, { "di jiao", "递交" }, { "di jie", "缔结" }, { "di jing", "地精" }, { "di jiu", "第九" },
			{ "di jiu ci", "第九次" }, { "di jiu jie", "第九届" }, { "di jiu tiao", "第九条" }, { "di jiu zhang", "第九章" }, { "di jun", "敌军" }, { "di kai", "低开" },
			{ "di kang", "抵抗" }, { "di kang li", "抵抗力" }, { "di ke", "迪克" }, { "di kong", "低空" }, { "di kou", "抵扣" }, { "di ku", "底裤" }, { "di kuai", "地块" },
			{ "di lei", "地雷" }, { "di li", "地理" }, { "di li", "地里" }, { "di li huan jing", "地理环境" }, { "di li wei zhi", "地理位置" }, { "di lian", "低廉" },
			{ "di lie", "低劣" }, { "di liu", "第六" }, { "di liu ci", "第六次" }, { "di liu gan", "第六感" }, { "di liu jie", "第六届" }, { "di liu tiao", "第六条" },
			{ "di liu zhang", "第六章" }, { "di lou", "地漏" }, { "di lun", "涤纶" }, { "di luo", "低落" }, { "di luo", "滴落" }, { "di mao", "地貌" }, { "di mei", "弟妹" },
			{ "di mi", "低迷" }, { "di mi du", "低密度" }, { "di mian", "地面" }, { "di ming", "地名" }, { "di neng", "低能" }, { "di nuan", "地暖" }, { "di pai", "底牌" },
			{ "di pan", "地盘" }, { "di pan", "底盘" }, { "di pi", "地皮" }, { "di pian", "底片" }, { "di pin", "低频" }, { "di ping xian", "地平线" }, { "di pu", "地铺" },
			{ "di qi", "底气" }, { "di qi", "第七" }, { "di qi ci", "第七次" }, { "di qi jie", "第七届" }, { "di qi tiao", "第七条" }, { "di qi zhang", "第七章" },
			{ "di qiao", "地壳" }, { "di qiu", "地球" }, { "di qiu ren", "地球人" }, { "di qu", "地区" }, { "di qu xing", "地区性" }, { "di que", "的确" },
			{ "di re", "地热" }, { "di ren", "敌人" }, { "di san", "第三" }, { "di san ban", "第三版" }, { "di san bu", "第三部" }, { "di san bu fen", "第三部分" },
			{ "di san chan ye", "第三产业" }, { "di san ci", "第三次" }, { "di san da", "第三大" }, { "di san dai", "第三代" }, { "di san fang", "第三方" },
			{ "di san ji", "第三季" }, { "di san ji", "第三集" }, { "di san ji du", "第三季度" }, { "di san jie", "第三届" }, { "di san jie", "第三节" },
			{ "di san jie duan", "第三阶段" }, { "di san lun", "第三轮" }, { "di san ming", "第三名" }, { "di san pi", "第三批" }, { "di san qi", "第三期" },
			{ "di san ren", "第三人" }, { "di san shi", "第三十" }, { "di san shi jie", "第三世界" }, { "di san tian", "第三天" }, { "di san tiao", "第三条" },
			{ "di san zhang", "第三章" }, { "di san zhe", "第三者" }, { "di san zhong", "第三种" }, { "di se", "底色" }, { "di shang", "地上" }, { "di shang", "递上" },
			{ "di sheng", "低声" }, { "di shi", "地势" }, { "di shi", "地市" }, { "di shi", "敌视" }, { "di shi", "的士" }, { "di shi", "第十" },
			{ "di shi ba tiao", "第十八条" }, { "di shi ci", "第十次" }, { "di shi er", "第十二" }, { "di shi er jie", "第十二届" }, { "di shi er tiao", "第十二条" },
			{ "di shi jie", "第十届" }, { "di shi jiu tiao", "第十九条" }, { "di shi liu tiao", "第十六条" }, { "di shi ni", "迪士尼" }, { "di shi qi", "第十七" },
			{ "di shi qi tiao", "第十七条" }, { "di shi san", "第十三" }, { "di shi san tiao", "第十三条" }, { "di shi si", "第十四" }, { "di shi si tiao", "第十四条" },
			{ "di shi tiao", "第十条" }, { "di shi wu", "第十五" }, { "di shi wu tiao", "第十五条" }, { "di shi yi", "第十一" }, { "di shi yi jie", "第十一届" },
			{ "di shi yi tiao", "第十一条" }, { "di shi zhang", "第十章" }, { "di shou ru", "低收入" }, { "di shou ru zhe", "低收入者" }, { "di shui", "地税" },
			{ "di shui", "滴水" }, { "di shui ju", "地税局" }, { "di shui ping", "低水平" }, { "di shuo", "地说" }, { "di si", "第四" }, { "di si", "迪斯" },
			{ "di si ci", "第四次" }, { "di si da", "第四大" }, { "di si dai", "第四代" }, { "di si ji", "第四季" }, { "di si ji du", "第四季度" }, { "di si jie", "第四届" },
			{ "di si ni", "迪斯尼" }, { "di si tiao", "第四条" }, { "di si zhang", "第四章" }, { "di su", "低俗" }, { "di su", "低速" }, { "di tan", "地摊" },
			{ "di tan", "地毯" }, { "di te lv", "底特律" }, { "di tie", "地铁" }, { "di tie zhan", "地铁站" }, { "di ting", "迪厅" }, { "di tou", "低头" },
			{ "di tou", "地头" }, { "di tu", "地图" }, { "di wang", "帝王" }, { "di wei", "低位" }, { "di wei", "地位" }, { "di wen", "低温" }, { "di wu", "第五" },
			{ "di wu ci", "第五次" }, { "di wu dai", "第五代" }, { "di wu jie", "第五届" }, { "di wu tiao", "第五条" }, { "di wu zhang", "第五章" }, { "di xi", "低吸" },
			{ "di xi", "底细" }, { "di xia", "低下" }, { "di xia", "地下" }, { "di xia", "底下" }, { "di xia cheng", "地下城" }, { "di xia shi", "地下室" },
			{ "di xia shui", "地下水" }, { "di xia tou", "低下头" }, { "di xian", "底线" }, { "di xiao", "抵消" }, { "di xin", "底薪" }, { "di xing", "地形" },
			{ "di xiong", "低胸" }, { "di xiong", "弟兄" }, { "di xue", "地穴" }, { "di xue", "滴血" }, { "di xue tang", "低血糖" }, { "di ya", "低压" }, { "di ya", "抵押" },
			{ "di ya", "迪亚" }, { "di ya dai kuan", "抵押贷款" }, { "di ya wu", "抵押物" }, { "di yi", "敌意" }, { "di yi", "第一" }, { "di yi bai", "第一百" },
			{ "di yi ban", "第一版" }, { "di yi ben", "第一本" }, { "di yi bi", "第一笔" }, { "di yi bu", "第一步" }, { "di yi bu", "第一部" }, { "di yi bu fen", "第一部分" },
			{ "di yi chang", "第一场" }, { "di yi ci", "第一次" }, { "di yi da", "第一大" }, { "di yi dai", "第一代" }, { "di yi dian", "第一点" }, { "di yi fen", "第一份" },
			{ "di yi ge yue", "第一个月" }, { "di yi guan", "第一关" }, { "di yi hang", "第一行" }, { "di yi ji", "第一季" }, { "di yi ji", "第一集" },
			{ "di yi ji du", "第一季度" }, { "di yi jia", "第一家" }, { "di yi jian shi", "第一件事" }, { "di yi jie", "第一届" }, { "di yi jie", "第一节" },
			{ "di yi jie duan", "第一阶段" }, { "di yi ju hua", "第一句话" }, { "di yi juan", "第一卷" }, { "di yi ke", "第一颗" }, { "di yi kuan", "第一款" },
			{ "di yi lun", "第一轮" }, { "di yi mei nv", "第一美女" }, { "di yi ming", "第一名" }, { "di yi pi", "第一批" }, { "di yi pian", "第一篇" },
			{ "di yi pin pai", "第一品牌" }, { "di yi qi", "第一期" }, { "di yi ren", "第一人" }, { "di yi ren", "第一任" }, { "di yi shi jian", "第一时间" },
			{ "di yi shou", "第一手" }, { "di yi shou", "第一首" }, { "di yi tao", "第一套" }, { "di yi tian", "第一天" }, { "di yi tiao", "第一条" },
			{ "di yi tong jin", "第一桶金" }, { "di yi wei", "第一位" }, { "di yi xian", "第一线" }, { "di yi xiang", "第一项" }, { "di yi xue qi", "第一学期" },
			{ "di yi yan", "第一眼" }, { "di yi yao wu", "第一要务" }, { "di yi ye", "第一页" }, { "di yi yin xiang", "第一印象" }, { "di yi zhan", "第一站" },
			{ "di yi zhang", "第一章" }, { "di yi zhi", "第一支" }, { "di yi zhong", "第一种" }, { "di yi zhou", "第一周" }, { "di yi zuo", "第一座" }, { "di yin", "低音" },
			{ "di yin pao", "低音炮" }, { "di yu", "低于" }, { "di yu", "低语" }, { "di yu", "地域" }, { "di yu", "地狱" }, { "di yu", "抵御" }, { "di yu huo", "地狱火" },
			{ "di yuan", "地缘" }, { "di yue guo", "缔约国" }, { "di yun", "底蕴" }, { "di zao", "缔造" }, { "di zeng", "递增" }, { "di zhai", "抵债" },
			{ "di zhe tou", "低着头" }, { "di zhen", "地震" }, { "di zhen ju", "地震局" }, { "di zhi", "地址" }, { "di zhi", "地质" }, { "di zhi", "抵制" },
			{ "di zhi lan", "地址栏" }, { "di zhi ri huo", "抵制日货" }, { "di zhi zai hai", "地质灾害" }, { "di zhong hai", "地中海" }, { "di zhu", "地主" },
			{ "di zhuan", "地砖" }, { "di zi", "底子" }, { "di zi", "弟子" }, { "di zi", "笛子" }, { "di zuo", "底座" }, { "dia", "嗲" }, { "dian", "丶" },
			{ "dian", "佃" }, { "dian", "傎" }, { "dian", "典" }, { "dian", "厧" }, { "dian", "坫" }, { "dian", "垫" }, { "dian", "墊" }, { "dian", "壂" },
			{ "dian", "奠" }, { "dian", "婝" }, { "dian", "婰" }, { "dian", "巅" }, { "dian", "巓" }, { "dian", "巔" }, { "dian", "店" }, { "dian", "惦" },
			{ "dian", "扂" }, { "dian", "掂" }, { "dian", "敁" }, { "dian", "椣" }, { "dian", "槙" }, { "dian", "殿" }, { "dian", "淀" }, { "dian", "滇" },
			{ "dian", "澱" }, { "dian", "点" }, { "dian", "玷" }, { "dian", "电" }, { "dian", "甸" }, { "dian", "瘨" }, { "dian", "癜" }, { "dian", "癫" },
			{ "dian", "癲" }, { "dian", "碘" }, { "dian", "磹" }, { "dian", "簟" }, { "dian", "蒧" }, { "dian", "蕇" }, { "dian", "踮" }, { "dian", "蹎" },
			{ "dian", "钿" }, { "dian", "阽" }, { "dian", "電" }, { "dian", "靛" }, { "dian", "顛" }, { "dian", "颠" }, { "dian", "驔" }, { "dian", "點" },
			{ "dian", "齻" }, { "dian ba", "点吧" }, { "dian ban", "点半" }, { "dian bao", "电报" }, { "dian biao", "电表" }, { "dian bing xiang", "电冰箱" },
			{ "dian bo", "点拨" }, { "dian bo", "点播" }, { "dian bo", "电波" }, { "dian bo", "颠簸" }, { "dian cai", "点菜" }, { "dian chang", "电厂" },
			{ "dian chang", "电场" }, { "dian che", "电车" }, { "dian chi", "滇池" }, { "dian chi", "电池" }, { "dian ci", "点此" }, { "dian ci", "电磁" },
			{ "dian ci bo", "电磁波" }, { "dian ci chang", "电磁场" }, { "dian ci fa", "电磁阀" }, { "dian ci fu she", "电磁辐射" }, { "dian ci lu", "电磁炉" },
			{ "dian da", "电大" }, { "dian dang", "典当" }, { "dian dao", "点到" }, { "dian dao", "颠倒" }, { "dian deng", "点灯" }, { "dian deng", "电灯" },
			{ "dian deng pao", "电灯泡" }, { "dian di", "垫底" }, { "dian di", "点滴" }, { "dian dian", "点点" }, { "dian dian di di", "点点滴滴" },
			{ "dian dian tou", "点点头" }, { "dian ding", "奠定" }, { "dian dong", "电动" }, { "dian dong che", "电动车" }, { "dian dong ji", "电动机" },
			{ "dian dong qi che", "电动汽车" }, { "dian du", "电镀" }, { "dian dui dian", "点对点" }, { "dian er", "点儿" }, { "dian fan", "典范" },
			{ "dian fan bao", "电饭煲" }, { "dian fan guo", "电饭锅" }, { "dian fei", "电费" }, { "dian fen", "淀粉" }, { "dian feng", "巅峰" }, { "dian feng", "颠峰" },
			{ "dian feng shan", "电风扇" }, { "dian fu", "垫付" }, { "dian fu", "颠覆" }, { "dian gan", "电感" }, { "dian ge", "点歌" }, { "dian gong", "电工" },
			{ "dian gu", "典故" }, { "dian he", "电荷" }, { "dian hu", "电弧" }, { "dian hua", "电话" }, { "dian hua ben", "电话本" }, { "dian hua bu", "电话簿" },
			{ "dian hua fei", "电话费" }, { "dian hua hao ma", "电话号码" }, { "dian hua ji", "电话机" }, { "dian hua ka", "电话卡" }, { "dian hua li", "电话里" },
			{ "dian hua lian xi", "电话联系" }, { "dian hua xian", "电话线" }, { "dian hua xue", "电化学" }, { "dian hui", "电汇" }, { "dian huo", "点火" },
			{ "dian ji", "典籍" }, { "dian ji", "奠基" }, { "dian ji", "惦记" }, { "dian ji", "点击" }, { "dian ji", "电击" }, { "dian ji", "电机" }, { "dian ji", "电极" },
			{ "dian ji cha kan", "点击查看" }, { "dian ji ci chu", "点击此处" }, { "dian ji jin ru", "点击进入" }, { "dian ji lv", "点击率" }, { "dian ji tu pian", "点击图片" },
			{ "dian ji zhe li", "点击这里" }, { "dian jia", "店家" }, { "dian jia", "电价" }, { "dian jiao", "电教" }, { "dian jie", "电解" }, { "dian jie lv", "电解铝" },
			{ "dian jie zhi", "电解质" }, { "dian jing", "点睛" }, { "dian ka", "点卡" }, { "dian kai", "点开" }, { "dian kong", "电控" }, { "dian kuang", "癫狂" },
			{ "dian lan", "电缆" }, { "dian le", "点了" }, { "dian li", "典礼" }, { "dian li", "店里" }, { "dian li", "电力" }, { "dian li gong si", "电力公司" },
			{ "dian li gong ying", "电力供应" }, { "dian li hang ye", "电力行业" }, { "dian li qi ye", "电力企业" }, { "dian li xi tong", "电力系统" }, { "dian liang", "掂量" },
			{ "dian liang", "点亮" }, { "dian liang", "电量" }, { "dian liu", "电流" }, { "dian lu", "电炉" }, { "dian lu", "电路" }, { "dian lu ban", "电路板" },
			{ "dian lu tu", "电路图" }, { "dian luo", "电骡" }, { "dian lv", "电驴" }, { "dian mei", "电煤" }, { "dian mian", "店面" }, { "dian ming", "店名" },
			{ "dian ming", "点名" }, { "dian nao", "电脑" }, { "dian nao bao", "电脑报" }, { "dian nao cheng", "电脑城" }, { "dian nao gong si", "电脑公司" },
			{ "dian nao li", "电脑里" }, { "dian nao ping mu", "电脑屏幕" }, { "dian nao qian", "电脑前" }, { "dian nao xi tong", "电脑系统" },
			{ "dian nao you xi", "电脑游戏" }, { "dian nao zhi shi", "电脑知识" }, { "dian nao zhuo", "电脑桌" }, { "dian nei", "店内" }, { "dian neng", "电能" },
			{ "dian ping", "点评" }, { "dian ping", "电平" }, { "dian ping", "电瓶" }, { "dian ping che", "电瓶车" }, { "dian pu", "店铺" }, { "dian qi", "电器" },
			{ "dian qi", "电气" }, { "dian qian", "点钱" }, { "dian qiu", "点球" }, { "dian ran", "点燃" }, { "dian re", "电热" }, { "dian re shui qi", "电热水器" },
			{ "dian rong", "电容" }, { "dian rong qi", "电容器" }, { "dian shan", "电扇" }, { "dian shang", "点上" }, { "dian shi", "电视" },
			{ "dian shi gou wu", "电视购物" }, { "dian shi guang gao", "电视广告" }, { "dian shi ji", "电视机" }, { "dian shi jie mu", "电视节目" }, { "dian shi ju", "电视剧" },
			{ "dian shi ka", "电视卡" }, { "dian shi li", "电视里" }, { "dian shi mei ti", "电视媒体" }, { "dian shi pin dao", "电视频道" }, { "dian shi tai", "电视台" },
			{ "dian shu", "点数" }, { "dian shui", "点水" }, { "dian tai", "电台" }, { "dian tang", "殿堂" }, { "dian ti", "电梯" }, { "dian tou", "点头" },
			{ "dian wan", "电玩" }, { "dian wang", "电网" }, { "dian wei", "点位" }, { "dian wei", "电位" }, { "dian wu", "玷污" }, { "dian xia", "殿下" },
			{ "dian xian", "电线" }, { "dian xian", "癫痫" }, { "dian xian gan", "电线杆" }, { "dian xin", "点心" }, { "dian xin", "电信" },
			{ "dian xin gong si", "电信公司" }, { "dian xin hang ye", "电信行业" }, { "dian xin ju", "电信局" }, { "dian xin qi ye", "电信企业" }, { "dian xin ye", "电信业" },
			{ "dian xin ye wu", "电信业务" }, { "dian xing", "典型" }, { "dian xing an li", "典型案例" }, { "dian xuan", "点选" }, { "dian xun", "电讯" },
			{ "dian ya", "典雅" }, { "dian ya", "电压" }, { "dian yang", "点样" }, { "dian yin", "电音" }, { "dian ying", "电影" }, { "dian ying ban", "电影版" },
			{ "dian ying gong si", "电影公司" }, { "dian ying jie", "电影节" }, { "dian ying li", "电影里" }, { "dian ying mian fei", "电影免费" },
			{ "dian ying piao", "电影票" }, { "dian ying pin dao", "电影频道" }, { "dian ying ren", "电影人" }, { "dian ying xia zai", "电影下载" },
			{ "dian ying xue yuan", "电影学院" }, { "dian ying yuan", "电影院" }, { "dian yong", "电泳" }, { "dian you", "电邮" }, { "dian yuan", "店员" },
			{ "dian yuan", "电源" }, { "dian yuan guan li", "电源管理" }, { "dian yuan xian", "电源线" }, { "dian zhan", "电站" }, { "dian zhang", "店长" },
			{ "dian zhe", "点着" }, { "dian zhe li", "点这里" }, { "dian zhen", "点阵" }, { "dian zhong", "点钟" }, { "dian zhu", "店主" }, { "dian zhui", "点缀" },
			{ "dian zi", "垫子" }, { "dian zi", "点子" }, { "dian zi", "电子" }, { "dian zi ban", "电子版" }, { "dian zi chan pin", "电子产品" },
			{ "dian zi cheng", "电子城" }, { "dian zi di tu", "电子地图" }, { "dian zi hua", "电子化" }, { "dian zi ji shu", "电子技术" }, { "dian zi jing ji", "电子竞技" },
			{ "dian zi qin", "电子琴" }, { "dian zi shang wu", "电子商务" }, { "dian zi she bei", "电子设备" }, { "dian zi shu", "电子书" }, { "dian zi xin xi", "电子信息" },
			{ "dian zi xin xiang", "电子信箱" }, { "dian zi you jian", "电子邮件" }, { "dian zi you xi", "电子游戏" }, { "dian zi you xiang", "电子邮箱" },
			{ "dian zi za zhi", "电子杂志" }, { "dian zi zheng wu", "电子政务" }, { "dian zi zhi fu", "电子支付" }, { "dian zu", "电阻" }, { "diao", "伄" }, { "diao", "凋" },
			{ "diao", "刁" }, { "diao", "叼" }, { "diao", "吊" }, { "diao", "奝" }, { "diao", "屌" }, { "diao", "弔" }, { "diao", "弴" }, { "diao", "彫" },
			{ "diao", "掉" }, { "diao", "殦" }, { "diao", "琱" }, { "diao", "碉" }, { "diao", "窵" }, { "diao", "簓" }, { "diao", "蓧" }, { "diao", "虭" },
			{ "diao", "蛁" }, { "diao", "调" }, { "diao", "貂" }, { "diao", "釣" }, { "diao", "钓" }, { "diao", "铞" }, { "diao", "铫" }, { "diao", "雕" },
			{ "diao", "雿" }, { "diao", "魡" }, { "diao", "鯛" }, { "diao", "鲷" }, { "diao", "鵰" }, { "diao", "鸟" }, { "diao bao", "碉堡" }, { "diao bo", "调拨" },
			{ "diao cha", "调查" }, { "diao cha bao gao", "调查报告" }, { "diao cha biao", "调查表" }, { "diao cha gong zuo", "调查工作" }, { "diao cha jie guo", "调查结果" },
			{ "diao cha qu zheng", "调查取证" }, { "diao cha wen juan", "调查问卷" }, { "diao cha xian shi", "调查显示" }, { "diao cha yan jiu", "调查研究" },
			{ "diao cha zu", "调查组" }, { "diao chan", "貂蝉" }, { "diao che", "吊车" }, { "diao chu", "调出" }, { "diao dai", "吊带" }, { "diao dao", "掉到" },
			{ "diao dao", "调到" }, { "diao deng", "吊灯" }, { "diao diao", "调调" }, { "diao ding", "吊顶" }, { "diao dong", "调动" }, { "diao du", "调度" },
			{ "diao hua", "雕花" }, { "diao huan", "调换" }, { "diao ji", "调集" }, { "diao jin", "掉进" }, { "diao ke", "雕刻" }, { "diao li", "调离" },
			{ "diao ling", "凋零" }, { "diao luo", "掉落" }, { "diao nan", "刁难" }, { "diao pai", "吊牌" }, { "diao pei", "调配" }, { "diao ren", "调任" },
			{ "diao ru", "掉入" }, { "diao ru", "调入" }, { "diao shui", "调水" }, { "diao si", "吊死" }, { "diao su", "雕塑" }, { "diao tou", "掉头" },
			{ "diao tou", "调头" }, { "diao wang", "凋亡" }, { "diao xia", "掉下" }, { "diao xia lai", "掉下来" }, { "diao xia qu", "掉下去" }, { "diao xian", "掉线" },
			{ "diao xiang", "雕像" }, { "diao xiao", "吊销" }, { "diao xie", "凋谢" }, { "diao yan", "调研" }, { "diao yan bao gao", "调研报告" },
			{ "diao yan lei", "掉眼泪" }, { "diao yan zu", "调研组" }, { "diao yi qing xin", "掉以轻心" }, { "diao yong", "调用" }, { "diao yu", "钓鱼" },
			{ "diao yu dao", "钓鱼岛" }, { "diao yu tai", "钓鱼台" }, { "diao zai", "掉在" }, { "diao zhe", "叼着" }, { "diao zhuang", "吊装" }, { "diao zhui", "吊坠" },
			{ "diao zhuo", "雕琢" }, { "diao zi", "调子" } };
};
