package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN61 {
	public static String[][] pl = { { "zhang chao yang", "张朝阳" }, { "zhang cheng", "章程" }, { "zhang cheng", "长成" }, { "zhang chu", "张楚" },
			{ "zhang chu", "长出" }, { "zhang chu lai", "长出来" }, { "zhang da", "张大" }, { "zhang da", "长大" }, { "zhang dan", "帐单" }, { "zhang dan", "账单" },
			{ "zhang dao", "涨到" }, { "zhang dao", "长到" }, { "zhang de", "涨得" }, { "zhang de", "长得" }, { "zhang de", "长的" }, { "zhang de jiang", "张德江" },
			{ "zhang die", "涨跌" }, { "zhang die fu", "涨跌幅" }, { "zhang fa", "章法" }, { "zhang fei", "张飞" }, { "zhang fu", "丈夫" }, { "zhang fu", "涨幅" },
			{ "zhang gao", "长高" }, { "zhang gong zi", "涨工资" }, { "zhang guan", "掌管" }, { "zhang guan", "长官" }, { "zhang gui", "掌柜" },
			{ "zhang gui de", "掌柜的" }, { "zhang guo", "张国" }, { "zhang guo li", "张国立" }, { "zhang guo rong", "张国荣" }, { "zhang hai", "张海" },
			{ "zhang han yun", "张含韵" }, { "zhang hao", "帐号" }, { "zhang hao", "账号" }, { "zhang hong", "张宏" }, { "zhang hu", "帐户" }, { "zhang hu", "账户" },
			{ "zhang hua", "张华" }, { "zhang hui", "张辉" }, { "zhang hui mei", "张惠妹" }, { "zhang ji", "掌机" }, { "zhang ji zhong", "张纪中" }, { "zhang jia", "张家" },
			{ "zhang jia", "涨价" }, { "zhang jia gang", "张家港" }, { "zhang jia jie", "张家界" }, { "zhang jia kou", "张家口" }, { "zhang jian", "张健" },
			{ "zhang jian", "张建" }, { "zhang jian shi", "长见识" }, { "zhang jiang", "张江" }, { "zhang jie", "张杰" }, { "zhang jie", "章节" }, { "zhang jin", "长进" },
			{ "zhang jing", "张静" }, { "zhang jun", "张俊" }, { "zhang jun", "张军" }, { "zhang kai", "张开" }, { "zhang kong", "掌控" }, { "zhang kou", "张口" },
			{ "zhang kuan", "账款" }, { "zhang kuang", "张狂" }, { "zhang lang", "蟑螂" }, { "zhang lao", "长老" }, { "zhang lao shi", "张老师" }, { "zhang le", "长了" },
			{ "zhang lei", "张磊" }, { "zhang li", "张丽" }, { "zhang li", "张力" }, { "zhang li", "张立" }, { "zhang lian", "张脸" }, { "zhang liang", "张良" },
			{ "zhang liang ying", "张靓颖" }, { "zhang liao", "张辽" }, { "zhang luo", "张罗" }, { "zhang man", "长满" }, { "zhang man yu", "张曼玉" },
			{ "zhang men", "掌门" }, { "zhang men ren", "掌门人" }, { "zhang mian", "账面" }, { "zhang min", "张敏" }, { "zhang ming", "张明" }, { "zhang mou", "张某" },
			{ "zhang mu", "帐目" }, { "zhang mu", "账目" }, { "zhang mu niang", "丈母娘" }, { "zhang na la", "张娜拉" }, { "zhang ning", "张宁" }, { "zhang pang", "长胖" },
			{ "zhang peng", "帐篷" }, { "zhang peng", "张鹏" }, { "zhang qiang", "张强" }, { "zhang quan", "掌权" }, { "zhang rou", "长肉" }, { "zhang san", "张三" },
			{ "zhang san feng", "张三丰" }, { "zhang shang", "掌上" }, { "zhang shang", "账上" }, { "zhang shang dian nao", "掌上电脑" }, { "zhang shao han", "张韶涵" },
			{ "zhang sheng", "掌声" }, { "zhang shi", "张氏" }, { "zhang shi", "涨势" }, { "zhang shi", "长势" }, { "zhang sun", "长孙" }, { "zhang tao", "张涛" },
			{ "zhang tie", "张贴" }, { "zhang ting", "涨停" }, { "zhang ting ban", "涨停板" }, { "zhang tong", "胀痛" }, { "zhang wang", "张望" }, { "zhang wei", "张伟" },
			{ "zhang wei jian", "张卫健" }, { "zhang wei ying", "张维迎" }, { "zhang wen", "张文" }, { "zhang wo", "掌握" }, { "zhang wu", "帐务" },
			{ "zhang wu ji", "张无忌" }, { "zhang xian", "彰显" }, { "zhang xian sheng", "张先生" }, { "zhang xiang", "长相" }, { "zhang xiao", "张晓" },
			{ "zhang xin", "掌心" }, { "zhang xin zhe", "张信哲" }, { "zhang xu", "张旭" }, { "zhang xue liang", "张学良" }, { "zhang xue you", "张学友" },
			{ "zhang ya dong", "张亚东" }, { "zhang yang", "张扬" }, { "zhang yi", "仗义" }, { "zhang yi mou", "张艺谋" }, { "zhang yi ning", "张怡宁" },
			{ "zhang ying", "张颖" }, { "zhang yong", "张勇" }, { "zhang yu", "张宇" }, { "zhang yu", "张玉" }, { "zhang yu", "张裕" }, { "zhang yu", "张钰" },
			{ "zhang yu", "章鱼" }, { "zhang zai", "长在" }, { "zhang zhang", "涨涨" }, { "zhang zhe", "仗着" }, { "zhang zhe", "张着" }, { "zhang zhe", "长着" },
			{ "zhang zhe", "长者" }, { "zhang zhen", "张震" }, { "zhang zhen yue", "张震岳" }, { "zhang zhi", "张志" }, { "zhang zhong", "掌中" }, { "zhang zhou", "漳州" },
			{ "zhang zi", "长子" }, { "zhang zi yi", "章子怡" }, { "zhang zui", "张嘴" }, { "zhao", "兆" }, { "zhao", "召" }, { "zhao", "啁" }, { "zhao", "嘲" },
			{ "zhao", "垗" }, { "zhao", "妱" }, { "zhao", "找" }, { "zhao", "招" }, { "zhao", "旐" }, { "zhao", "昭" }, { "zhao", "曌" }, { "zhao", "朝" },
			{ "zhao", "棹" }, { "zhao", "櫂" }, { "zhao", "沼" }, { "zhao", "炤" }, { "zhao", "照" }, { "zhao", "爪" }, { "zhao", "狣" }, { "zhao", "瑵" },
			{ "zhao", "皽" }, { "zhao", "盄" }, { "zhao", "着" }, { "zhao", "笊" }, { "zhao", "箌" }, { "zhao", "罩" }, { "zhao", "肇" }, { "zhao", "菬" },
			{ "zhao", "詔" }, { "zhao", "诏" }, { "zhao", "赵" }, { "zhao", "趙" }, { "zhao", "釗" }, { "zhao", "釽" }, { "zhao", "鉊" }, { "zhao", "鍣" },
			{ "zhao", "钊" }, { "zhao", "駋" }, { "zhao", "鮡" }, { "zhao", "鳭" }, { "zhao ban", "招办" }, { "zhao ban", "照搬" }, { "zhao bei", "罩杯" },
			{ "zhao ben shan", "赵本山" }, { "zhao biao", "招标" }, { "zhao biao gong gao", "招标公告" }, { "zhao biao ren", "招标人" }, { "zhao biao tou biao", "招标投标" },
			{ "zhao biao wen jian", "招标文件" }, { "zhao bu chu", "找不出" }, { "zhao bu dao le", "找不到了" }, { "zhao cai", "招财" }, { "zhao cha", "找茬" },
			{ "zhao chang", "照常" }, { "zhao chao", "照抄" }, { "zhao chou", "找抽" }, { "zhao chu", "找出" }, { "zhao da", "找打" }, { "zhao dai", "招待" },
			{ "zhao dai hui", "招待会" }, { "zhao dai suo", "招待所" }, { "zhao dao", "找到" }, { "zhao dao", "招到" }, { "zhao de", "找的" }, { "zhao de", "照得" },
			{ "zhao ge", "找个" }, { "zhao gong", "招工" }, { "zhao gu", "招股" }, { "zhao gu", "照顾" }, { "zhao guo", "找过" }, { "zhao guo", "赵国" },
			{ "zhao hang", "招行" }, { "zhao hao", "找好" }, { "zhao hu", "招呼" }, { "zhao huan", "召唤" }, { "zhao hui", "召回" }, { "zhao hui", "找回" },
			{ "zhao hui", "朝晖" }, { "zhao huo", "着火" }, { "zhao ji", "召集" }, { "zhao ji", "着急" }, { "zhao ji hui", "找机会" }, { "zhao jia", "招架" },
			{ "zhao jia", "赵家" }, { "zhao jian", "召见" }, { "zhao jing zi", "照镜子" }, { "zhao jiu", "照旧" }, { "zhao kai", "召开" }, { "zhao kai hui yi", "召开会议" },
			{ "zhao kan", "照看" }, { "zhao kao", "招考" }, { "zhao lai", "找来" }, { "zhao lai", "招来" }, { "zhao lan", "招揽" }, { "zhao li", "照例" },
			{ "zhao liang", "照亮" }, { "zhao liang", "着凉" }, { "zhao liao", "照料" }, { "zhao lu", "招录" }, { "zhao lu", "着陆" }, { "zhao luo", "着落" },
			{ "zhao mi", "着迷" }, { "zhao min", "赵敏" }, { "zhao ming", "照明" }, { "zhao mou", "赵某" }, { "zhao mu", "招募" }, { "zhao ni", "找你" },
			{ "zhao pai", "招牌" }, { "zhao pian", "照片" }, { "zhao pin", "招聘" }, { "zhao pin hui", "招聘会" }, { "zhao pin xin xi", "招聘信息" }, { "zhao qi", "朝气" },
			{ "zhao qi", "沼气" }, { "zhao qi chi", "沼气池" }, { "zhao qing", "肇庆" }, { "zhao re", "招惹" }, { "zhao ren", "找人" }, { "zhao ren", "招人" },
			{ "zhao shang", "招商" }, { "zhao shang ju", "招商局" }, { "zhao shang men", "找上门" }, { "zhao shang yin hang", "招商银行" },
			{ "zhao shang yin zi", "招商引资" }, { "zhao shang zheng quan", "招商证券" }, { "zhao she", "照射" }, { "zhao sheng", "招生" }, { "zhao sheng ban", "招生办" },
			{ "zhao sheng ji hua", "招生计划" }, { "zhao sheng jian zhang", "招生简章" }, { "zhao sheng kao shi", "招生考试" }, { "zhao shi", "找事" }, { "zhao shi", "招式" },
			{ "zhao shi", "昭示" }, { "zhao shi", "肇事" }, { "zhao shi zhe", "肇事者" }, { "zhao shou", "招手" }, { "zhao shou", "招收" }, { "zhao shou", "着手" },
			{ "zhao shu", "招数" }, { "zhao shui", "找谁" }, { "zhao si", "找死" }, { "zhao ta", "找他" }, { "zhao tou biao", "招投标" }, { "zhao wei", "赵薇" },
			{ "zhao wo", "找我" }, { "zhao xi", "朝夕" }, { "zhao xi xiang chu", "朝夕相处" }, { "zhao xia", "朝霞" }, { "zhao xian sheng", "赵先生" },
			{ "zhao xiang", "照相" }, { "zhao xiang", "着想" }, { "zhao xiang guan", "照相馆" }, { "zhao xiang ji", "照相机" }, { "zhao xie", "找些" },
			{ "zhao xun", "找寻" }, { "zhao ya zhi", "赵雅芝" }, { "zhao yang", "朝阳" }, { "zhao yang", "照样" }, { "zhao yao", "招摇" }, { "zhao yao", "照耀" },
			{ "zhao ying", "照应" }, { "zhao yun", "赵云" }, { "zhao zai", "照在" }, { "zhao ze", "沼泽" }, { "zhao zhao", "找找" }, { "zhao zhao", "找着" },
			{ "zhao zhao", "招招" }, { "zhao zhao", "照照" }, { "zhao zhe", "照着" }, { "zhao zhe", "罩着" }, { "zhao zhi", "招致" }, { "zhao zhong xiang", "赵忠祥" },
			{ "zhao zhun", "找准" }, { "zhao zi yang", "赵紫阳" }, { "zhao zong", "赵总" }, { "zhao zu", "招租" }, { "zhe", "乇" }, { "zhe", "哲" }, { "zhe", "喆" },
			{ "zhe", "囁" }, { "zhe", "夂" }, { "zhe", "嫬" }, { "zhe", "悊" }, { "zhe", "折" }, { "zhe", "摂" }, { "zhe", "摺" }, { "zhe", "晢" }, { "zhe", "柘" },
			{ "zhe", "棏" }, { "zhe", "浙" }, { "zhe", "淛" }, { "zhe", "着" }, { "zhe", "矺" }, { "zhe", "砓" }, { "zhe", "磔" }, { "zhe", "粍" }, { "zhe", "者" },
			{ "zhe", "聑" }, { "zhe", "蔗" }, { "zhe", "虴" }, { "zhe", "蛰" }, { "zhe", "蜇" }, { "zhe", "螫" }, { "zhe", "蟄" }, { "zhe", "蟅" }, { "zhe", "褶" },
			{ "zhe", "謫" }, { "zhe", "謺" }, { "zhe", "讋" }, { "zhe", "谪" }, { "zhe", "赭" }, { "zhe", "輒" }, { "zhe", "輙" }, { "zhe", "轍" }, { "zhe", "辄" },
			{ "zhe", "辙" }, { "zhe", "这" }, { "zhe", "這" }, { "zhe", "遮" }, { "zhe", "鍺" }, { "zhe", "锗" }, { "zhe", "馲" }, { "zhe", "鮿" }, { "zhe", "鷓" },
			{ "zhe", "鹧" }, { "zhe ba", "这把" }, { "zhe ban", "这般" }, { "zhe bang", "这帮" }, { "zhe ben", "这本" }, { "zhe bi", "这比" }, { "zhe bi", "这笔" },
			{ "zhe bi", "遮蔽" }, { "zhe bian", "这边" }, { "zhe bu", "这不" }, { "zhe bu", "这步" }, { "zhe bu", "这部" }, { "zhe bu dian ying", "这部电影" },
			{ "zhe cai", "这才" }, { "zhe cai shi", "这才是" }, { "zhe ceng", "这层" }, { "zhe chang", "这场" }, { "zhe che", "这车" }, { "zhe ci", "这次" },
			{ "zhe da", "浙大" }, { "zhe dang", "遮挡" }, { "zhe dao", "这倒" }, { "zhe dao", "这道" }, { "zhe deng", "这等" }, { "zhe dian", "这点" },
			{ "zhe die", "折叠" }, { "zhe die shi", "折叠式" }, { "zhe dong", "这栋" }, { "zhe dou", "这都" }, { "zhe dou shi", "这都是" }, { "zhe duan", "折断" },
			{ "zhe duan", "这段" }, { "zhe duan hua", "这段话" }, { "zhe duan shi jian", "这段时间" }, { "zhe dui", "这对" }, { "zhe er", "这儿" }, { "zhe fan", "这番" },
			{ "zhe fen", "这份" }, { "zhe feng", "这封" }, { "zhe fu", "折服" }, { "zhe fu", "这副" }, { "zhe fu", "这幅" }, { "zhe gai", "遮盖" }, { "zhe ge", "这个" },
			{ "zhe ge", "这歌" }, { "zhe ge cheng shi", "这个城市" }, { "zhe ge ci", "这个词" }, { "zhe ge di fang", "这个地方" }, { "zhe ge dong xi", "这个东西" },
			{ "zhe ge gu shi", "这个故事" }, { "zhe ge guo jia", "这个国家" }, { "zhe ge ji hui", "这个机会" }, { "zhe ge jia huo", "这个家伙" }, { "zhe ge ming zi", "这个名字" },
			{ "zhe ge nan ren", "这个男人" }, { "zhe ge nv hai", "这个女孩" }, { "zhe ge nv ren", "这个女人" }, { "zhe ge ren", "这个人" }, { "zhe ge shi dai", "这个时代" },
			{ "zhe ge shi hou", "这个时候" }, { "zhe ge shi jie", "这个世界" }, { "zhe ge shu zi", "这个数字" }, { "zhe ge wang zhan", "这个网站" },
			{ "zhe ge wen jian", "这个文件" }, { "zhe ge wen ti", "这个问题" }, { "zhe ge xia tian", "这个夏天" }, { "zhe ge xiao xi", "这个消息" },
			{ "zhe ge you xi", "这个游戏" }, { "zhe ge yue", "这个月" }, { "zhe ge zi", "这个字" }, { "zhe gei", "这给" }, { "zhe gen", "这根" }, { "zhe gen", "这跟" },
			{ "zhe geng", "这更" }, { "zhe gu", "这股" }, { "zhe hai", "这还" }, { "zhe hang", "这行" }, { "zhe he", "折合" }, { "zhe he", "这和" }, { "zhe hua", "这话" },
			{ "zhe hui", "这会" }, { "zhe hui", "这回" }, { "zhe hui er", "这会儿" }, { "zhe hui shi", "这回事" }, { "zhe huo", "这伙" }, { "zhe ji", "这几" },
			{ "zhe ji", "这既" }, { "zhe ji ge", "这几个" }, { "zhe ji nian", "这几年" }, { "zhe ji tian", "这几天" }, { "zhe jia", "折价" }, { "zhe jia", "这家" },
			{ "zhe jia huo", "这家伙" }, { "zhe jia lv", "折价率" }, { "zhe jian", "这件" }, { "zhe jian", "这间" }, { "zhe jian shi", "这件事" },
			{ "zhe jian shi qing", "这件事情" }, { "zhe jiang", "浙江" }, { "zhe jiang", "这将" }, { "zhe jiang da xue", "浙江大学" }, { "zhe jiang ren", "浙江人" },
			{ "zhe jiang sheng", "浙江省" }, { "zhe jiao", "这叫" }, { "zhe jie", "这届" }, { "zhe jiu", "折旧" }, { "zhe jiu", "这就" }, { "zhe jiu shi shuo", "这就是说" },
			{ "zhe ju", "这句" }, { "zhe ju hua", "这句话" }, { "zhe ke", "这可" }, { "zhe ke", "这棵" }, { "zhe ke", "这颗" }, { "zhe kou", "折扣" }, { "zhe kou", "这口" },
			{ "zhe kuai", "这块" }, { "zhe kuan", "这款" }, { "zhe lei", "这类" }, { "zhe li", "哲理" }, { "zhe li", "这里" }, { "zhe lia", "这俩" }, { "zhe lian", "着脸" },
			{ "zhe liang", "这两" }, { "zhe liang", "这辆" }, { "zhe liang ge", "这两个" }, { "zhe liang tian", "这两天" }, { "zhe liang zhong", "这两种" },
			{ "zhe lun", "这轮" }, { "zhe me", "这么" }, { "zhe me da", "这么大" }, { "zhe me dian", "这么点" }, { "zhe me duo", "这么多" }, { "zhe me duo nian", "这么多年" },
			{ "zhe me duo ren", "这么多人" }, { "zhe me hao", "这么好" }, { "zhe me jian dan", "这么简单" }, { "zhe me jiu", "这么久" }, { "zhe me man", "这么慢" },
			{ "zhe me nan", "这么难" }, { "zhe me xie", "这么些" }, { "zhe me zuo", "这么做" }, { "zhe mei", "这枚" }, { "zhe men", "这门" }, { "zhe mian", "这面" },
			{ "zhe ming", "这名" }, { "zhe mo", "折磨" }, { "zhe ne", "着呢" }, { "zhe pan", "这盘" }, { "zhe pi", "这批" }, { "zhe pian", "这片" }, { "zhe pian", "这篇" },
			{ "zhe pian wen zhang", "这篇文章" }, { "zhe qi", "这期" }, { "zhe qi", "这起" }, { "zhe qian", "这钱" }, { "zhe qun", "这群" }, { "zhe rang", "这让" },
			{ "zhe ren", "哲人" }, { "zhe ren", "这人" }, { "zhe san", "这三" }, { "zhe san ge", "这三个" }, { "zhe shang", "浙商" }, { "zhe she", "折射" },
			{ "zhe she chu", "折射出" }, { "zhe shen", "这身" }, { "zhe shi", "这事" }, { "zhe shi", "这使" }, { "zhe shi", "这时" }, { "zhe shi", "这是" },
			{ "zhe shi ge", "这是个" }, { "zhe shi hou", "这时候" }, { "zhe shi ni", "这是你" }, { "zhe shi shen me", "这是什么" }, { "zhe shi ta", "这是他" },
			{ "zhe shi wo", "这是我" }, { "zhe shi yi ge", "这是一个" }, { "zhe shi yi zhong", "这是一种" }, { "zhe shou", "这首" }, { "zhe shou ge", "这首歌" },
			{ "zhe shou ge qu", "这首歌曲" }, { "zhe shou shi", "这首诗" }, { "zhe shu", "这书" }, { "zhe shuang", "这双" }, { "zhe si", "这厮" }, { "zhe si", "这四" },
			{ "zhe sou", "这艘" }, { "zhe suan", "折算" }, { "zhe suan", "这算" }, { "zhe suo", "这所" }, { "zhe tai", "这台" }, { "zhe tang", "蔗糖" },
			{ "zhe tang", "这趟" }, { "zhe tao", "这套" }, { "zhe teng", "折腾" }, { "zhe tian", "这天" }, { "zhe tiao", "这条" }, { "zhe tiao lu", "这条路" },
			{ "zhe tie", "这贴" }, { "zhe tou", "这头" }, { "zhe wei", "这位" }, { "zhe xi", "浙西" }, { "zhe xia", "这下" }, { "zhe xiang", "这项" }, { "zhe xie", "这些" },
			{ "zhe xie dong xi", "这些东西" }, { "zhe xie dou shi", "这些都是" }, { "zhe xie hua", "这些话" }, { "zhe xie ren", "这些人" }, { "zhe xie wen ti", "这些问题" },
			{ "zhe xue", "哲学" }, { "zhe xue jia", "哲学家" }, { "zhe xue qi", "这学期" }, { "zhe yan", "遮掩" }, { "zhe yang", "这样" }, { "zhe yang", "遮阳" },
			{ "zhe yang cai neng", "这样才能" }, { "zhe yang xie", "这样写" }, { "zhe yang yi lai", "这样一来" }, { "zhe yang zuo", "这样做" }, { "zhe yao", "这要" },
			{ "zhe ye", "者也" }, { "zhe ye", "这也" }, { "zhe ye shi", "这也是" }, { "zhe yi", "这一" }, { "zhe yi bu", "这一步" }, { "zhe yi ci", "这一次" },
			{ "zhe yi duan", "这一段" }, { "zhe yi nian", "这一年" }, { "zhe yi qie dou", "这一切都" }, { "zhe yi tian", "这一天" }, { "zhe you", "这又" },
			{ "zhe you", "这有" }, { "zhe you hui", "折优惠" }, { "zhe yu", "这与" }, { "zhe zai", "这在" }, { "zhe ze", "这则" }, { "zhe zhang", "这张" },
			{ "zhe zhang zhuan ji", "这张专辑" }, { "zhe zhao", "这招" }, { "zhe zhe yan yan", "遮遮掩掩" }, { "zhe zhen", "这真" }, { "zhe zhi", "这只" },
			{ "zhe zhi", "这支" }, { "zhe zhong", "折中" }, { "zhe zhong", "这种" }, { "zhe zhong fang fa", "这种方法" }, { "zhe zhong fang shi", "这种方式" },
			{ "zhe zhong gan jue", "这种感觉" }, { "zhe zhong qing kuang", "这种情况" }, { "zhe zhong ren", "这种人" }, { "zhe zhong shi", "这种事" },
			{ "zhe zhong shi qing", "这种事情" }, { "zhe zhou", "褶皱" }, { "zhe zhou", "这周" }, { "zhe zhu", "遮住" }, { "zhe zhu yao shi", "这主要是" },
			{ "zhe zhuang", "这桩" }, { "zhe zu", "这组" }, { "zhe zuo", "这座" }, { "zhei", "这" }, { "zhen", "侦" }, { "zhen", "侲" }, { "zhen", "偵" },
			{ "zhen", "圳" }, { "zhen", "塡" }, { "zhen", "姫" }, { "zhen", "寊" }, { "zhen", "帧" }, { "zhen", "抮" }, { "zhen", "挋" }, { "zhen", "振" },
			{ "zhen", "揕" }, { "zhen", "敶" }, { "zhen", "斟" }, { "zhen", "朕" }, { "zhen", "朾" }, { "zhen", "枕" }, { "zhen", "枮" }, { "zhen", "栚" },
			{ "zhen", "桢" }, { "zhen", "桭" }, { "zhen", "椹" }, { "zhen", "楨" }, { "zhen", "榐" }, { "zhen", "榛" }, { "zhen", "槇" }, { "zhen", "樼" },
			{ "zhen", "沴" }, { "zhen", "浈" }, { "zhen", "溱" }, { "zhen", "潧" }, { "zhen", "澵" }, { "zhen", "獉" }, { "zhen", "珍" }, { "zhen", "珎" },
			{ "zhen", "瑧" }, { "zhen", "瑱" }, { "zhen", "甄" }, { "zhen", "畛" }, { "zhen", "疹" }, { "zhen", "眕" }, { "zhen", "眞" }, { "zhen", "真" },
			{ "zhen", "眹" }, { "zhen", "砧" }, { "zhen", "碪" }, { "zhen", "祯" }, { "zhen", "禎" }, { "zhen", "禛" }, { "zhen", "稹" }, { "zhen", "竧" },
			{ "zhen", "箴" }, { "zhen", "籈" }, { "zhen", "紖" }, { "zhen", "紾" }, { "zhen", "絼" }, { "zhen", "縝" }, { "zhen", "縥" }, { "zhen", "缜" },
			{ "zhen", "胗" }, { "zhen", "臻" }, { "zhen", "葴" }, { "zhen", "蓁" }, { "zhen", "薽" }, { "zhen", "蜄" }, { "zhen", "袗" }, { "zhen", "裖" },
			{ "zhen", "診" }, { "zhen", "誫" }, { "zhen", "謓" }, { "zhen", "诊" }, { "zhen", "貞" }, { "zhen", "賑" }, { "zhen", "贞" }, { "zhen", "赈" },
			{ "zhen", "軫" }, { "zhen", "轃" }, { "zhen", "轸" }, { "zhen", "辴" }, { "zhen", "遉" }, { "zhen", "針" }, { "zhen", "鈂" }, { "zhen", "鍖" },
			{ "zhen", "鍼" }, { "zhen", "鎭" }, { "zhen", "鎮" }, { "zhen", "针" }, { "zhen", "镇" }, { "zhen", "阵" }, { "zhen", "陣" }, { "zhen", "震" },
			{ "zhen", "靕" }, { "zhen", "駗" }, { "zhen", "鬒" }, { "zhen", "鱵" }, { "zhen", "鴆" }, { "zhen", "鸩" }, { "zhen", "黰" }, { "zhen ai", "珍爱" },
			{ "zhen ai", "真爱" }, { "zhen bang", "真棒" }, { "zhen bao", "珍宝" }, { "zhen bian", "枕边" }, { "zhen bie", "甄别" }, { "zhen bu", "真不" },
			{ "zhen bu zhi dao", "真不知道" }, { "zhen cang", "珍藏" }, { "zhen cao", "贞操" }, { "zhen ce", "侦测" }, { "zhen cha", "侦察" }, { "zhen cha", "侦查" },
			{ "zhen chan", "震颤" }, { "zhen cheng", "真诚" }, { "zhen ci", "针刺" }, { "zhen dang", "振荡" }, { "zhen dang", "震荡" }, { "zhen dang wei", "镇党委" },
			{ "zhen de", "真得" }, { "zhen de", "真的" }, { "zhen de ai", "真的爱" }, { "zhen de hen", "真的很" }, { "zhen de ma", "真的吗" }, { "zhen dei", "真得" },
			{ "zhen di", "真谛" }, { "zhen di", "阵地" }, { "zhen ding", "镇定" }, { "zhen dong", "振动" }, { "zhen dong", "震动" }, { "zhen duan", "诊断" },
			{ "zhen dui", "针对" }, { "zhen dui xing", "针对性" }, { "zhen duo", "真多" }, { "zhen e xin", "真恶心" }, { "zhen fa", "阵法" }, { "zhen fen", "振奋" },
			{ "zhen feng xiang dui", "针锋相对" }, { "zhen fu", "振幅" }, { "zhen ge", "真个" }, { "zhen gong fu", "真功夫" }, { "zhen gou", "真够" },
			{ "zhen guai", "真乖" }, { "zhen guan", "贞观" }, { "zhen gui", "珍贵" }, { "zhen hai", "镇海" }, { "zhen han", "震撼" }, { "zhen han li", "震撼力" },
			{ "zhen hao", "真好" }, { "zhen hua", "振华" }, { "zhen hua", "真话" }, { "zhen hui", "真会" }, { "zhen ji", "真机" }, { "zhen jia", "真假" },
			{ "zhen jiang", "镇江" }, { "zhen jiao", "真叫" }, { "zhen jie", "贞洁" }, { "zhen jing", "镇静" }, { "zhen jing", "震惊" }, { "zhen jiu", "针灸" },
			{ "zhen jun", "真菌" }, { "zhen kong", "真空" }, { "zhen kuai", "真快" }, { "zhen lei", "真累" }, { "zhen li", "真理" }, { "zhen li", "镇里" },
			{ "zhen liao", "诊疗" }, { "zhen lie", "阵列" }, { "zhen mei", "真没" }, { "zhen mei", "真美" }, { "zhen mi", "缜密" }, { "zhen mian mu", "真面目" },
			{ "zhen ming", "真名" }, { "zhen nan", "真难" }, { "zhen neng", "真能" }, { "zhen ni", "珍妮" }, { "zhen niu", "真牛" }, { "zhen pi", "真皮" },
			{ "zhen piao liang", "真漂亮" }, { "zhen pin", "珍品" }, { "zhen pin", "真品" }, { "zhen po", "侦破" }, { "zhen qi", "真气" }, { "zhen qiang", "真强" },
			{ "zhen qie", "真切" }, { "zhen qing", "真情" }, { "zhen qu", "镇区" }, { "zhen ren", "真人" }, { "zhen ren ban", "真人版" }, { "zhen ren xiu", "真人秀" },
			{ "zhen rong", "阵容" }, { "zhen ru", "真如" }, { "zhen shan mei", "真善美" }, { "zhen shang", "镇上" }, { "zhen she", "震慑" }, { "zhen shen", "真身" },
			{ "zhen shi", "珍视" }, { "zhen shi", "真实" }, { "zhen shi", "真是" }, { "zhen shi", "阵势" }, { "zhen shi qing kuang", "真实情况" },
			{ "zhen shi shen fen", "真实身份" }, { "zhen shi tai", "真是太" }, { "zhen shi xie zhao", "真实写照" }, { "zhen shi xing", "真实性" },
			{ "zhen shi xing ming", "真实姓名" }, { "zhen shuang", "真爽" }, { "zhen si", "真丝" }, { "zhen suo", "诊所" }, { "zhen tan", "侦探" }, { "zhen ti", "真题" },
			{ "zhen tian", "震天" }, { "zhen tong", "镇痛" }, { "zhen tong", "阵痛" }, { "zhen tou", "枕头" }, { "zhen tou", "针头" }, { "zhen wang", "阵亡" },
			{ "zhen wei", "真伪" }, { "zhen xi", "珍惜" }, { "zhen xi", "珍稀" }, { "zhen xi sheng ming", "珍惜生命" }, { "zhen xian", "阵线" }, { "zhen xiang", "真像" },
			{ "zhen xiang", "真想" }, { "zhen xiang", "真相" }, { "zhen xiang", "真象" }, { "zhen xin", "真心" }, { "zhen xin hua", "真心话" }, { "zhen xing", "振兴" },
			{ "zhen xing", "阵型" }, { "zhen ya", "镇压" }, { "zhen yan", "真言" }, { "zhen yan", "箴言" }, { "zhen yao", "真要" }, { "zhen ying", "阵营" },
			{ "zhen you", "真有" }, { "zhen yu", "阵雨" }, { "zhen yu men", "真郁闷" }, { "zhen yun", "真晕" }, { "zhen zai", "赈灾" }, { "zhen zhang", "镇长" },
			{ "zhen zhe", "枕着" }, { "zhen zhen", "真真" }, { "zhen zhen", "阵阵" }, { "zhen zhen qie qie", "真真切切" }, { "zhen zheng", "真正" },
			{ "zhen zheng fu", "镇政府" }, { "zhen zheng yuan yin", "真正原因" }, { "zhen zheng zuo dao", "真正做到" }, { "zhen zhi", "真挚" }, { "zhen zhi", "诊治" },
			{ "zhen zhi", "针织" }, { "zhen zhong", "珍重" }, { "zhen zhong", "震中" }, { "zhen zhu", "珍珠" }, { "zhen zhu", "真主" }, { "zhen zhu dang", "真主党" },
			{ "zhen zhu fen", "珍珠粉" }, { "zhen zhu gang", "珍珠港" }, { "zhen zhuo", "斟酌" }, { "zhen zi", "贞子" }, { "zhen zi", "阵子" }, { "zhen zi dan", "甄子丹" },
			{ "zhen zuo", "振作" }, { "zheng", "丁" }, { "zheng", "争" }, { "zheng", "倀" }, { "zheng", "凧" }, { "zheng", "埥" }, { "zheng", "埩" }, { "zheng", "塣" },
			{ "zheng", "姃" }, { "zheng", "媜" }, { "zheng", "峥" }, { "zheng", "崝" }, { "zheng", "崢" }, { "zheng", "幀" }, { "zheng", "征" }, { "zheng", "怔" },
			{ "zheng", "拯" }, { "zheng", "挣" }, { "zheng", "掙" }, { "zheng", "掟" }, { "zheng", "撜" }, { "zheng", "政" }, { "zheng", "整" }, { "zheng", "晸" },
			{ "zheng", "正" }, { "zheng", "氶" }, { "zheng", "浧" }, { "zheng", "湞" }, { "zheng", "炡" }, { "zheng", "烝" }, { "zheng", "爭" }, { "zheng", "狰" },
			{ "zheng", "猙" }, { "zheng", "症" }, { "zheng", "癥" }, { "zheng", "眐" }, { "zheng", "睁" }, { "zheng", "睜" }, { "zheng", "筝" }, { "zheng", "箏" },
			{ "zheng", "篜" }, { "zheng", "糽" }, { "zheng", "綪" }, { "zheng", "聇" }, { "zheng", "脀" }, { "zheng", "蒸" }, { "zheng", "証" }, { "zheng", "諍" },
			{ "zheng", "證" }, { "zheng", "证" }, { "zheng", "诤" }, { "zheng", "郑" }, { "zheng", "鄭" }, { "zheng", "鉦" }, { "zheng", "錚" }, { "zheng", "钲" },
			{ "zheng", "铮" }, { "zheng", "鮏" }, { "zheng", "鯖" }, { "zheng ba", "争霸" }, { "zheng ban", "整版" }, { "zheng ban", "正版" }, { "zheng bei", "正被" },
			{ "zheng ben", "正本" }, { "zheng bi", "正比" }, { "zheng bian", "争辩" }, { "zheng bian", "政变" }, { "zheng bing", "征兵" }, { "zheng bu", "整部" },
			{ "zheng bu kai", "睁不开" }, { "zheng can", "正餐" }, { "zheng ce", "政策" }, { "zheng ce cuo shi", "政策措施" }, { "zheng ce fa gui", "政策法规" },
			{ "zheng ce gui ding", "政策规定" }, { "zheng ce huan jing", "政策环境" }, { "zheng ce mian", "政策面" }, { "zheng ce xing", "政策性" }, { "zheng chang", "整场" },
			{ "zheng chang", "正常" }, { "zheng chang gong zuo", "正常工作" }, { "zheng chang hua", "正常化" }, { "zheng chang ren", "正常人" },
			{ "zheng chang shi yong", "正常使用" }, { "zheng chang yun xing", "正常运行" }, { "zheng chao", "争吵" }, { "zheng che", "整车" }, { "zheng cheng", "征程" },
			{ "zheng chu", "正处" }, { "zheng chu yu", "正处于" }, { "zheng chuang", "争创" }, { "zheng ci", "证词" }, { "zheng cong", "正从" }, { "zheng da", "正大" },
			{ "zheng da", "睁大" }, { "zheng dang", "争当" }, { "zheng dang", "政党" }, { "zheng dang", "正当" }, { "zheng dao", "挣到" }, { "zheng dao", "正道" } };
};
