package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN22 {
	public static String[][] pl = { { "ji zhi", "几只" }, { "ji zhi", "几支" }, { "ji zhi", "及至" }, { "ji zhi", "基质" }, { "ji zhi", "机制" }, { "ji zhi", "机智" },
			{ "ji zhi", "极至" }, { "ji zhi", "极致" }, { "ji zhong", "几种" }, { "ji zhong", "击中" }, { "ji zhong", "机种" }, { "ji zhong", "集中" },
			{ "ji zhong cai gou", "集中采购" }, { "ji zhong du", "集中度" }, { "ji zhong jing li", "集中精力" }, { "ji zhong ti xian", "集中体现" },
			{ "ji zhong xue xi", "集中学习" }, { "ji zhong ying", "集中营" }, { "ji zhou", "几周" }, { "ji zhu", "脊柱" }, { "ji zhu", "记住" }, { "ji zhu wo", "记住我" },
			{ "ji zhuang xiang", "集装箱" }, { "ji zhui", "脊椎" }, { "ji zhun", "基准" }, { "ji zhun li lv", "基准利率" }, { "ji zi", "机子" }, { "ji zi", "集资" },
			{ "ji zi shang", "机子上" }, { "ji zu", "几组" }, { "ji zu", "机组" }, { "ji zu", "祭祖" }, { "jia", "价" }, { "jia", "伽" }, { "jia", "佳" }, { "jia", "假" },
			{ "jia", "傢" }, { "jia", "價" }, { "jia", "加" }, { "jia", "嘉" }, { "jia", "嘏" }, { "jia", "夹" }, { "jia", "夾" }, { "jia", "婽" }, { "jia", "嫁" },
			{ "jia", "家" }, { "jia", "岬" }, { "jia", "幏" }, { "jia", "恝" }, { "jia", "戛" }, { "jia", "戞" }, { "jia", "扴" }, { "jia", "抸" }, { "jia", "斝" },
			{ "jia", "架" }, { "jia", "枷" }, { "jia", "梜" }, { "jia", "椵" }, { "jia", "榎" }, { "jia", "檟" }, { "jia", "毠" }, { "jia", "泇" }, { "jia", "浃" },
			{ "jia", "犌" }, { "jia", "猳" }, { "jia", "玾" }, { "jia", "珈" }, { "jia", "甲" }, { "jia", "痂" }, { "jia", "瘕" }, { "jia", "稼" }, { "jia", "笳" },
			{ "jia", "筴" }, { "jia", "糘" }, { "jia", "耞" }, { "jia", "胛" }, { "jia", "茄" }, { "jia", "荚" }, { "jia", "莢" }, { "jia", "葭" }, { "jia", "蛱" },
			{ "jia", "蛺" }, { "jia", "袈" }, { "jia", "豭" }, { "jia", "貑" }, { "jia", "賈" }, { "jia", "贾" }, { "jia", "跏" }, { "jia", "迦" }, { "jia", "郏" },
			{ "jia", "郟" }, { "jia", "鉀" }, { "jia", "鋏" }, { "jia", "鎵" }, { "jia", "钾" }, { "jia", "铗" }, { "jia", "镓" }, { "jia", "頬" }, { "jia", "頰" },
			{ "jia", "颊" }, { "jia", "駕" }, { "jia", "驾" }, { "jia", "鴶" }, { "jia", "鵊" }, { "jia", "麚" }, { "jia ban", "假扮" }, { "jia ban", "加班" },
			{ "jia ban", "甲板" }, { "jia ban fei", "加班费" }, { "jia ban jia dian", "加班加点" }, { "jia bao yu", "贾宝玉" }, { "jia bei", "加倍" }, { "jia bi", "假币" },
			{ "jia bin", "嘉宾" }, { "jia ceng", "夹层" }, { "jia cha", "价差" }, { "jia chan", "家产" }, { "jia chang", "加长" }, { "jia chang", "家常" },
			{ "jia chang bian fan", "家常便饭" }, { "jia chang cai", "家常菜" }, { "jia chao", "假钞" }, { "jia che", "驾车" }, { "jia cheng", "加成" },
			{ "jia chi", "加持" }, { "jia chong", "甲虫" }, { "jia chu", "家畜" }, { "jia chu qu", "嫁出去" }, { "jia chun", "甲醇" }, { "jia cu", "加粗" },
			{ "jia cun", "家村" }, { "jia da", "加大" }, { "jia dang", "家当" }, { "jia dao", "加到" }, { "jia dao", "嫁到" }, { "jia de", "家的" }, { "jia di", "家底" },
			{ "jia dian", "加点" }, { "jia dian", "家店" }, { "jia dian", "家电" }, { "jia dian lian suo", "家电连锁" }, { "jia ding", "假定" }, { "jia ding", "嘉定" },
			{ "jia ding", "家丁" }, { "jia fa", "假发" }, { "jia fa", "加法" }, { "jia fang", "家纺" }, { "jia fang", "家访" }, { "jia fang", "甲方" },
			{ "jia fei", "加菲" }, { "jia fei", "钾肥" }, { "jia fei ji", "架飞机" }, { "jia fei mao", "加菲猫" }, { "jia fen", "加分" }, { "jia feng", "夹缝" },
			{ "jia gai", "加盖" }, { "jia gao", "价高" }, { "jia ge", "价格" }, { "jia ge", "加个" }, { "jia ge", "嫁个" }, { "jia ge biao", "价格表" },
			{ "jia ge bo dong", "价格波动" }, { "jia ge di", "价格低" }, { "jia ge pian yi", "价格便宜" }, { "jia ge shang zhang", "价格上涨" }, { "jia ge zhan", "价格战" },
			{ "jia ge zhi shu", "价格指数" }, { "jia ge zou shi", "价格走势" }, { "jia gei", "嫁给" }, { "jia gei ni", "嫁给你" }, { "jia gei wo", "嫁给我" },
			{ "jia gong", "加工" }, { "jia gong chang", "加工厂" }, { "jia gong fei", "加工费" }, { "jia gong gong yi", "加工工艺" }, { "jia gong mao yi", "加工贸易" },
			{ "jia gong qi ye", "加工企业" }, { "jia gong ye", "加工业" }, { "jia gou", "架构" }, { "jia gou shi", "架构师" }, { "jia gu", "加固" }, { "jia gu wen", "甲骨文" },
			{ "jia guo", "加国" }, { "jia hao", "加号" }, { "jia he", "嘉禾" }, { "jia hou", "加厚" }, { "jia hua", "佳话" }, { "jia hua", "假话" }, { "jia hua", "嘉华" },
			{ "jia huo", "假货" }, { "jia huo", "家伙" }, { "jia ji", "佳绩" }, { "jia ji", "加急" }, { "jia ji", "夹击" }, { "jia ji", "甲基" }, { "jia ji", "甲级" },
			{ "jia jia", "佳佳" }, { "jia jia", "加价" }, { "jia jia", "加加" }, { "jia jia", "嘉嘉" }, { "jia jia", "家家" }, { "jia jia hu hu", "家家户户" },
			{ "jia jian", "加减" }, { "jia jiang", "嘉奖" }, { "jia jiao", "家教" }, { "jia jie", "佳节" }, { "jia jie", "假借" }, { "jia jie", "嫁接" },
			{ "jia jin", "加紧" }, { "jia jin", "加进" }, { "jia jing", "加精" }, { "jia jing", "嘉靖" }, { "jia jing", "家境" }, { "jia ju", "加剧" }, { "jia ju", "夹具" },
			{ "jia ju", "家具" }, { "jia ju", "家居" }, { "jia ju", "家驹" }, { "jia kang", "甲亢" }, { "jia ke", "夹克" }, { "jia ke chong", "甲壳虫" },
			{ "jia kong", "架空" }, { "jia kuai", "加快" }, { "jia kuai fa zhan", "加快发展" }, { "jia kuai jian she", "加快建设" }, { "jia kuai tui jin", "加快推进" },
			{ "jia kuan", "价款" }, { "jia le", "嫁了" }, { "jia le bi", "加勒比" }, { "jia le fu", "家乐福" }, { "jia li", "佳丽" }, { "jia li", "加里" },
			{ "jia li", "家里" }, { "jia li lue", "伽利略" }, { "jia li mian", "家里面" }, { "jia li ren", "家里人" }, { "jia lian wu mei", "价廉物美" }, { "jia ma", "价码" },
			{ "jia ma", "加码" }, { "jia man", "加满" }, { "jia mao", "假冒" }, { "jia mao wei lie", "假冒伪劣" }, { "jia mei", "佳美" }, { "jia men", "家们" },
			{ "jia men", "家门" }, { "jia men kou", "家门口" }, { "jia meng", "加盟" }, { "jia meng dian", "加盟店" }, { "jia meng shang", "加盟商" }, { "jia mi", "加密" },
			{ "jia mi gou", "加密狗" }, { "jia mian", "假面" }, { "jia ming", "假名" }, { "jia mu", "贾母" }, { "jia mu si", "佳木斯" }, { "jia na", "加纳" },
			{ "jia na", "戛纳" }, { "jia na da", "加拿大" }, { "jia nei te", "加内特" }, { "jia neng", "佳能" }, { "jia nian hua", "嘉年华" }, { "jia pin", "佳品" },
			{ "jia pu", "家谱" }, { "jia qi", "假期" }, { "jia qi", "架起" }, { "jia qi lai", "加起来" }, { "jia qi ye", "家企业" }, { "jia qian", "价钱" },
			{ "jia qian", "加钱" }, { "jia qiang", "加强" }, { "jia qiang guan li", "加强管理" }, { "jia qin", "家禽" }, { "jia qing", "嘉庆" }, { "jia qing lin", "贾庆林" },
			{ "jia qu", "家去" }, { "jia quan", "加权" }, { "jia quan", "甲醛" }, { "jia re", "加热" }, { "jia ren", "佳人" }, { "jia ren", "嫁人" }, { "jia ren", "家人" },
			{ "jia ri", "假日" }, { "jia ru", "假如" }, { "jia ru", "加入" }, { "jia ru shi jian", "加入时间" }, { "jia ruo", "假若" }, { "jia sha", "加沙" },
			{ "jia shan", "假山" }, { "jia shan", "嘉善" }, { "jia shang", "加上" }, { "jia shang", "架上" }, { "jia shang qu", "加上去" }, { "jia she", "假设" },
			{ "jia she", "架设" }, { "jia shen", "加深" }, { "jia shi", "假使" }, { "jia shi", "嘉实" }, { "jia shi", "家世" }, { "jia shi", "家事" }, { "jia shi", "架势" },
			{ "jia shi", "驾驶" }, { "jia shi qi", "加湿器" }, { "jia shi ren", "驾驶人" }, { "jia shi sai", "加时赛" }, { "jia shi shi", "驾驶室" },
			{ "jia shi yuan", "驾驶员" }, { "jia shi zhe", "驾驶者" }, { "jia shi zheng", "驾驶证" }, { "jia shou", "加收" }, { "jia shu", "家属" }, { "jia shu", "家数" },
			{ "jia shui", "加水" }, { "jia shuo", "假说" }, { "jia si", "假死" }, { "jia si", "家私" }, { "jia su", "加速" }, { "jia su du", "加速度" },
			{ "jia su qi", "加速器" }, { "jia suo", "枷锁" }, { "jia tang", "加糖" }, { "jia ting", "家庭" }, { "jia ting bao li", "家庭暴力" },
			{ "jia ting cheng yuan", "家庭成员" }, { "jia ting jiao yu", "家庭教育" }, { "jia ting jing ji", "家庭经济" }, { "jia ting sheng huo", "家庭生活" },
			{ "jia ting shou ru", "家庭收入" }, { "jia ting ying yuan", "家庭影院" }, { "jia ting zhu fu", "家庭主妇" }, { "jia tu suo", "加图索" }, { "jia wan", "甲烷" },
			{ "jia wei", "价为" }, { "jia wei", "价位" }, { "jia wei", "加为" }, { "jia wen", "加温" }, { "jia wo", "加我" }, { "jia wu", "家务" }, { "jia xi", "加息" },
			{ "jia xiang", "假想" }, { "jia xiang", "假象" }, { "jia xiang", "家乡" }, { "jia xiao", "驾校" }, { "jia xie", "加些" }, { "jia xie hui", "家协会" },
			{ "jia xin", "加薪" }, { "jia xin wen", "假新闻" }, { "jia xing", "嘉兴" }, { "jia xing shi", "嘉兴市" }, { "jia xue", "加血" }, { "jia ya", "假牙" },
			{ "jia ya", "加压" }, { "jia yan", "加盐" }, { "jia yang", "家养" }, { "jia yao", "佳肴" }, { "jia yao", "假药" }, { "jia yi", "加一" }, { "jia yi", "加以" },
			{ "jia yi", "嫁衣" }, { "jia yi", "甲乙" }, { "jia yin", "佳音" }, { "jia yong", "家用" }, { "jia yong dian qi", "家用电器" }, { "jia you", "加油" },
			{ "jia you", "家有" }, { "jia you a", "加油啊" }, { "jia you ba", "加油吧" }, { "jia you zhan", "加油站" }, { "jia yu", "甲鱼" }, { "jia yu", "驾驭" },
			{ "jia yu hu xiao", "家喻户晓" }, { "jia yuan", "佳缘" }, { "jia yuan", "加元" }, { "jia yuan", "嘉园" }, { "jia yuan", "家园" }, { "jia za", "夹杂" },
			{ "jia zai", "加在" }, { "jia zai", "加载" }, { "jia zai", "夹在" }, { "jia zhang", "家长" }, { "jia zhang ke", "贾樟柯" }, { "jia zhao", "驾照" },
			{ "jia zhe", "夹着" }, { "jia zheng", "家政" }, { "jia zheng fu wu", "家政服务" }, { "jia zhi", "价值" }, { "jia zhi", "加之" }, { "jia zhi guan", "价值观" },
			{ "jia zhi guan nian", "价值观念" }, { "jia zhi lian", "价值链" }, { "jia zhi qu xiang", "价值取向" }, { "jia zhi tou zi", "价值投资" }, { "jia zhong", "加重" },
			{ "jia zhong", "家中" }, { "jia zhou", "加州" }, { "jia zhu", "加注" }, { "jia zhu", "夹住" }, { "jia zhu", "家住" }, { "jia zhuang", "假装" },
			{ "jia zhuang", "加装" }, { "jia zhuang", "嫁妆" }, { "jia zhuang", "家庄" }, { "jia zhuang", "家装" }, { "jia zhuang xian", "甲状腺" }, { "jia zi", "夹子" },
			{ "jia zi", "架子" }, { "jia zi", "甲子" }, { "jia zu", "家族" }, { "jia zu qi ye", "家族企业" }, { "jia zuo", "佳作" }, { "jian", "件" }, { "jian", "俭" },
			{ "jian", "俴" }, { "jian", "倹" }, { "jian", "偂" }, { "jian", "健" }, { "jian", "僭" }, { "jian", "儉" }, { "jian", "兼" }, { "jian", "减" },
			{ "jian", "剑" }, { "jian", "剣" }, { "jian", "剪" }, { "jian", "剱" }, { "jian", "劍" }, { "jian", "劒" }, { "jian", "劔" }, { "jian", "劗" },
			{ "jian", "囝" }, { "jian", "坚" }, { "jian", "堅" }, { "jian", "墹" }, { "jian", "奸" }, { "jian", "姦" }, { "jian", "寋" }, { "jian", "尖" },
			{ "jian", "幵" }, { "jian", "建" }, { "jian", "彅" }, { "jian", "惤" }, { "jian", "戋" }, { "jian", "戔" }, { "jian", "戩" }, { "jian", "戬" },
			{ "jian", "拣" }, { "jian", "挸" }, { "jian", "捡" }, { "jian", "揀" }, { "jian", "搛" }, { "jian", "撿" }, { "jian", "擶" }, { "jian", "枧" },
			{ "jian", "柬" }, { "jian", "检" }, { "jian", "検" }, { "jian", "椷" }, { "jian", "楗" }, { "jian", "槛" }, { "jian", "樫" }, { "jian", "檢" },
			{ "jian", "櫼" }, { "jian", "歼" }, { "jian", "殱" }, { "jian", "殲" }, { "jian", "毽" }, { "jian", "洊" }, { "jian", "浅" }, { "jian", "涧" },
			{ "jian", "渐" }, { "jian", "減" }, { "jian", "湔" }, { "jian", "湕" }, { "jian", "溅" }, { "jian", "漸" }, { "jian", "澗" }, { "jian", "濺" },
			{ "jian", "瀸" }, { "jian", "煎" }, { "jian", "熞" }, { "jian", "熸" }, { "jian", "牋" }, { "jian", "牮" }, { "jian", "犍" }, { "jian", "猏" },
			{ "jian", "珔" }, { "jian", "瑊" }, { "jian", "瑐" }, { "jian", "监" }, { "jian", "監" }, { "jian", "睑" }, { "jian", "瞷" }, { "jian", "瞼" },
			{ "jian", "硷" }, { "jian", "碱" }, { "jian", "磵" }, { "jian", "礛" }, { "jian", "笕" }, { "jian", "笺" }, { "jian", "简" }, { "jian", "箋" },
			{ "jian", "箭" }, { "jian", "簡" }, { "jian", "籛" }, { "jian", "糋" }, { "jian", "緘" }, { "jian", "縑" }, { "jian", "繝" }, { "jian", "繭" },
			{ "jian", "缄" }, { "jian", "缣" }, { "jian", "翦" }, { "jian", "肩" }, { "jian", "腱" }, { "jian", "舰" }, { "jian", "艦" }, { "jian", "艰" },
			{ "jian", "艱" }, { "jian", "茧" }, { "jian", "荐" }, { "jian", "菅" }, { "jian", "菺" }, { "jian", "葌" }, { "jian", "蒹" }, { "jian", "蕑" },
			{ "jian", "薦" }, { "jian", "藆" }, { "jian", "虃" }, { "jian", "螹" }, { "jian", "裥" }, { "jian", "襉" }, { "jian", "襺" }, { "jian", "見" },
			{ "jian", "见" }, { "jian", "諓" }, { "jian", "謇" }, { "jian", "譾" }, { "jian", "谏" }, { "jian", "谫" }, { "jian", "賎" }, { "jian", "賤" },
			{ "jian", "贱" }, { "jian", "趼" }, { "jian", "践" }, { "jian", "踐" }, { "jian", "踺" }, { "jian", "蹇" }, { "jian", "轞" }, { "jian", "釼" },
			{ "jian", "鉴" }, { "jian", "鋻" }, { "jian", "鍵" }, { "jian", "鑑" }, { "jian", "鑒" }, { "jian", "鑳" }, { "jian", "锏" }, { "jian", "键" },
			{ "jian", "間" }, { "jian", "间" }, { "jian", "鞬" }, { "jian", "鞯" }, { "jian", "韉" }, { "jian", "餞" }, { "jian", "饯" }, { "jian", "鬋" },
			{ "jian", "鰎" }, { "jian", "鰹" }, { "jian", "鲣" }, { "jian", "鵳" }, { "jian", "鹣" }, { "jian", "鹸" }, { "jian", "鹼" }, { "jian", "麉" },
			{ "jian an", "建安" }, { "jian ao", "煎熬" }, { "jian ban", "减半" }, { "jian bang", "肩膀" }, { "jian bao", "简报" }, { "jian bao", "见报" },
			{ "jian bei", "兼备" }, { "jian bian", "渐变" }, { "jian bian", "简便" }, { "jian bie", "鉴别" }, { "jian bing", "兼并" }, { "jian bing", "煎饼" },
			{ "jian bu", "肩部" }, { "jian bu dao", "见不到" }, { "jian bu de", "见不得" }, { "jian bu de ren", "见不得人" }, { "jian cai", "剪彩" }, { "jian cai", "剪裁" },
			{ "jian cai", "建材" }, { "jian cai shi chang", "建材市场" }, { "jian cang", "减仓" }, { "jian cang", "建仓" }, { "jian ce", "检测" }, { "jian ce", "监测" },
			{ "jian ce bao gao", "检测报告" }, { "jian ce chu", "检测出" }, { "jian ce fang fa", "检测方法" }, { "jian ce jie guo", "检测结果" },
			{ "jian ce xi tong", "监测系统" }, { "jian ce zhong xin", "检测中心" }, { "jian cha", "检察" }, { "jian cha", "检查" }, { "jian cha", "监察" },
			{ "jian cha bu", "监察部" }, { "jian cha gong zuo", "检查工作" }, { "jian cha guan", "检察官" }, { "jian cha ji guan", "检察机关" },
			{ "jian cha jie guo", "检查结果" }, { "jian cha ju", "监察局" }, { "jian cha yuan", "检察院" }, { "jian cha zhang", "检察长" }, { "jian cha zu", "检查组" },
			{ "jian chan", "减产" }, { "jian chang", "建厂" }, { "jian chang", "见长" }, { "jian cheng", "坚称" }, { "jian cheng", "建成" }, { "jian cheng", "渐成" },
			{ "jian cheng", "简称" }, { "jian chi", "减持" }, { "jian chi", "坚持" }, { "jian chi bu xie", "坚持不懈" }, { "jian chi dao di", "坚持到底" },
			{ "jian chi zou", "坚持走" }, { "jian chu", "检出" }, { "jian chuan", "舰船" }, { "jian dai", "肩带" }, { "jian dan", "煎蛋" }, { "jian dan", "简单" },
			{ "jian dan hua", "简单化" }, { "jian dao", "减到" }, { "jian dao", "剪刀" }, { "jian dao", "尖刀" }, { "jian dao", "捡到" }, { "jian dao", "见到" },
			{ "jian de", "兼得" }, { "jian de", "见得" }, { "jian de", "间的" }, { "jian di", "减低" }, { "jian di", "见地" }, { "jian di", "见底" },
			{ "jian dian", "检点" }, { "jian diao", "减掉" }, { "jian diao", "剪掉" }, { "jian die", "间谍" }, { "jian ding", "坚定" }, { "jian ding", "检定" },
			{ "jian ding", "见顶" }, { "jian ding", "鉴定" }, { "jian ding bu yi", "坚定不移" }, { "jian du", "监督" }, { "jian du gong zuo", "监督工作" },
			{ "jian du guan li", "监督管理" }, { "jian du ji zhi", "监督机制" }, { "jian du jian cha", "监督检查" }, { "jian du yuan", "监督员" }, { "jian duan", "剪断" },
			{ "jian duan", "尖端" }, { "jian duan", "简短" }, { "jian duan", "间断" }, { "jian dui", "舰队" }, { "jian er", "健儿" }, { "jian fa", "减法" },
			{ "jian fa", "剑法" }, { "jian fan", "简繁" }, { "jian fang", "建房" }, { "jian fang", "检方" }, { "jian fang", "间房" }, { "jian fei", "减肥" },
			{ "jian fei fa", "减肥法" }, { "jian fei shou shen", "减肥瘦身" }, { "jian fei yao", "减肥药" }, { "jian feng", "剑锋" }, { "jian feng", "尖峰" },
			{ "jian fu", "减负" }, { "jian fu", "肩负" }, { "jian ge", "间隔" }, { "jian gong", "建功" }, { "jian gong", "建工" }, { "jian gong", "监工" },
			{ "jian gou", "建构" }, { "jian gu", "兼顾" }, { "jian gu", "坚固" }, { "jian gu", "荐股" }, { "jian guai", "见怪" }, { "jian guai bu guai", "见怪不怪" },
			{ "jian guan", "监管" }, { "jian guan bu men", "监管部门" }, { "jian guan gong zuo", "监管工作" }, { "jian guan ji gou", "监管机构" }, { "jian guan ju", "监管局" },
			{ "jian gui", "见鬼" }, { "jian guo", "坚果" }, { "jian guo", "建国" }, { "jian guo", "见过" }, { "jian guo hou", "建国后" }, { "jian guo men", "建国门" },
			{ "jian guo yi lai", "建国以来" }, { "jian hang", "建行" }, { "jian hao", "建好" }, { "jian hao", "见好" }, { "jian hao shi", "件好事" }, { "jian hu", "监护" },
			{ "jian hu ren", "监护人" }, { "jian hua", "建华" }, { "jian hua", "简化" }, { "jian huan", "减缓" }, { "jian huo", "贱货" }, { "jian huo", "间或" },
			{ "jian ji", "剪辑" }, { "jian jian", "尖尖" }, { "jian jian", "渐渐" }, { "jian jian", "见见" }, { "jian jian", "贱贱" }, { "jian jian dan dan", "简简单单" },
			{ "jian jiao", "尖叫" }, { "jian jiao", "建交" }, { "jian jiao sheng", "尖叫声" }, { "jian jie", "简介" }, { "jian jie", "简洁" }, { "jian jie", "见解" },
			{ "jian jie", "间接" }, { "jian jin", "渐进" }, { "jian jin", "监禁" }, { "jian ju", "兼具" }, { "jian ju", "检举" }, { "jian ju", "艰巨" },
			{ "jian ju", "间距" }, { "jian jue", "坚决" }, { "jian jue fan dui", "坚决反对" }, { "jian jun", "建军" }, { "jian kang", "健康" },
			{ "jian kang cheng zhang", "健康成长" }, { "jian kang fa zhan", "健康发展" }, { "jian kang jiao yu", "健康教育" }, { "jian kang kuai le", "健康快乐" },
			{ "jian kang wang", "健康网" }, { "jian kang zhuang kuang", "健康状况" }, { "jian kao", "监考" }, { "jian ke", "剑客" }, { "jian kong", "监控" },
			{ "jian kong xi tong", "监控系统" }, { "jian ku", "艰苦" }, { "jian ku fen dou", "艰苦奋斗" }, { "jian le", "剪了" }, { "jian li", "建立" }, { "jian li", "监理" },
			{ "jian li", "简历" }, { "jian li bao", "健力宝" }, { "jian li jian quan", "建立健全" }, { "jian li zi ji", "建立自己" }, { "jian lian", "简练" },
			{ "jian liang", "见谅" }, { "jian lou", "简陋" }, { "jian lue", "简略" }, { "jian mai", "贱卖" }, { "jian man", "减慢" }, { "jian mei", "健美" },
			{ "jian mei cao", "健美操" }, { "jian mian", "减免" }, { "jian mian", "见面" }, { "jian mian hui", "见面会" }, { "jian mian shui", "减免税" },
			{ "jian mie", "歼灭" }, { "jian ming", "建明" }, { "jian ming", "简明" }, { "jian mo", "建模" }, { "jian mo", "缄默" }, { "jian nan", "艰难" },
			{ "jian ni", "见你" }, { "jian pai", "减排" }, { "jian pan", "键盘" }, { "jian pi", "健脾" }, { "jian ping", "建平" }, { "jian pu", "简朴" },
			{ "jian pu zhai", "柬埔寨" }, { "jian qi", "建起" }, { "jian qi", "捡起" }, { "jian qiang", "坚强" }, { "jian qiao", "剑桥" }, { "jian qiao da xue", "剑桥大学" },
			{ "jian qie", "剪切" }, { "jian qing", "减轻" }, { "jian qu", "减去" }, { "jian qu", "渐趋" }, { "jian quan", "健全" }, { "jian ren", "兼任" },
			{ "jian ren", "坚韧" }, { "jian ren", "见人" }, { "jian ren", "贱人" }, { "jian ren jian zhi", "见仁见智" }, { "jian rong", "兼容" },
			{ "jian rong xing", "兼容性" }, { "jian ru", "键入" }, { "jian rui", "尖锐" }, { "jian rui shi you", "尖锐湿疣" }, { "jian ruo", "减弱" },
			{ "jian shang", "奸商" }, { "jian shang", "肩上" }, { "jian shang", "鉴赏" }, { "jian shao", "减少" }, { "jian she", "建设" }, { "jian she bu", "建设部" },
			{ "jian she cheng wei", "建设成为" }, { "jian she dan wei", "建设单位" }, { "jian she gong cheng", "建设工程" }, { "jian she gong zuo", "建设工作" },
			{ "jian she gui hua", "建设规划" }, { "jian she he xie", "建设和谐" }, { "jian she ju", "建设局" }, { "jian she ting", "建设厅" },
			{ "jian she xiang mu", "建设项目" }, { "jian she xing", "建设性" }, { "jian she yin hang", "建设银行" }, { "jian she yong di", "建设用地" },
			{ "jian she zhe", "建设者" }, { "jian she zi jin", "建设资金" }, { "jian shen", "健身" }, { "jian shen fang", "健身房" }, { "jian sheng", "剑圣" },
			{ "jian shi", "件事" }, { "jian shi", "剑士" }, { "jian shi", "坚实" }, { "jian shi", "检视" }, { "jian shi", "监事" }, { "jian shi", "监视" },
			{ "jian shi", "见识" }, { "jian shi hui", "监事会" }, { "jian shi qi", "监视器" }, { "jian shi qing", "件事情" }, { "jian shou", "坚守" }, { "jian shu", "件数" },
			{ "jian shu", "剑术" }, { "jian shu", "建树" }, { "jian shu", "简述" }, { "jian shu", "键鼠" }, { "jian shui", "减税" }, { "jian su", "减速" },
			{ "jian su ji", "减速机" }, { "jian suo", "检索" }, { "jian ta", "践踏" }, { "jian tao", "检讨" }, { "jian ti", "简体" }, { "jian ti zhong wen", "简体中文" },
			{ "jian ti zi", "简体字" }, { "jian tie ban", "剪贴板" }, { "jian ting", "坚挺" }, { "jian ting", "监听" }, { "jian ting", "舰艇" }, { "jian tou", "箭头" },
			{ "jian tou", "肩头" }, { "jian tou fa", "剪头发" }, { "jian tui", "减退" }, { "jian wai", "见外" }, { "jian wang", "健忘" }, { "jian wei", "建委" },
			{ "jian wei", "键位" }, { "jian wen", "见闻" }, { "jian xi", "减息" }, { "jian xi", "见习" }, { "jian xi", "间隙" }, { "jian xia", "剑侠" },
			{ "jian xian", "艰险" }, { "jian xiao", "减小" }, { "jian xiao", "奸笑" }, { "jian xiao", "建校" }, { "jian xiao", "见效" }, { "jian xiao", "见笑" },
			{ "jian xie", "简写" }, { "jian xie", "间歇" }, { "jian xie xing", "间歇性" }, { "jian xin", "坚信" }, { "jian xin", "建新" }, { "jian xin", "艰辛" },
			{ "jian xing", "渐行" }, { "jian xing", "碱性" }, { "jian xing", "践行" }, { "jian xiu", "检修" }, { "jian xun", "简讯" }, { "jian ya", "减压" },
			{ "jian yan", "检验" }, { "jian yan jian yi", "检验检疫" }, { "jian yao", "简要" }, { "jian ye", "建业" }, { "jian yi", "坚毅" }, { "jian yi", "建议" },
			{ "jian yi", "检疫" }, { "jian yi", "简易" }, { "jian yi nin", "建议您" }, { "jian yi shu", "建议书" }, { "jian yi yong wei", "见义勇为" }, { "jian yin", "奸淫" },
			{ "jian ying", "剪影" }, { "jian ying", "坚硬" }, { "jian you", "兼有" }, { "jian you", "建有" }, { "jian yu", "建于" }, { "jian yu", "监狱" },
			{ "jian yu", "见于" }, { "jian yu", "鉴于" }, { "jian yu li", "监狱里" }, { "jian yuan", "渐远" }, { "jian yue", "检阅" }, { "jian yue", "简约" },
			{ "jian zai", "健在" }, { "jian zai", "减灾" }, { "jian zai", "建在" }, { "jian zao", "建造" }, { "jian zha", "奸诈" }, { "jian zhan", "建站" },
			{ "jian zhang", "简章" }, { "jian zhang", "见长" }, { "jian zhe", "见着" }, { "jian zhen", "减震" }, { "jian zheng", "见证" }, { "jian zheng", "鉴证" },
			{ "jian zhi", "兼职" }, { "jian zhi", "剪纸" }, { "jian zhi", "建制" }, { "jian zhi", "监制" }, { "jian zhi", "简直" }, { "jian zhi", "键值" },
			{ "jian zhu", "建筑" }, { "jian zhu", "见诸" }, { "jian zhu cai liao", "建筑材料" }, { "jian zhu feng ge", "建筑风格" }, { "jian zhu gong cheng", "建筑工程" },
			{ "jian zhu gong di", "建筑工地" }, { "jian zhu gong si", "建筑公司" }, { "jian zhu jie neng", "建筑节能" }, { "jian zhu mian ji", "建筑面积" },
			{ "jian zhu qun", "建筑群" }, { "jian zhu she ji", "建筑设计" }, { "jian zhu shi", "建筑师" }, { "jian zhu shi gong", "建筑施工" }, { "jian zhu wu", "建筑物" },
			{ "jian zhu xue", "建筑学" }, { "jian zhu ye", "建筑业" }, { "jian zhuang", "健壮" }, { "jian zhuang", "见状" }, { "jiang", "丬" }, { "jiang", "傋" },
			{ "jiang", "僵" }, { "jiang", "匠" }, { "jiang", "奖" }, { "jiang", "奨" }, { "jiang", "奬" }, { "jiang", "姜" }, { "jiang", "将" }, { "jiang", "將" },
			{ "jiang", "嵹" }, { "jiang", "弶" }, { "jiang", "强" }, { "jiang", "杢" }, { "jiang", "桨" }, { "jiang", "槳" }, { "jiang", "橿" }, { "jiang", "櫤" },
			{ "jiang", "殭" }, { "jiang", "江" }, { "jiang", "洚" }, { "jiang", "浆" }, { "jiang", "漿" }, { "jiang", "犟" }, { "jiang", "獎" }, { "jiang", "畺" },
			{ "jiang", "疆" }, { "jiang", "礓" }, { "jiang", "糨" }, { "jiang", "絳" }, { "jiang", "绛" }, { "jiang", "缰" }, { "jiang", "翞" }, { "jiang", "耩" },
			{ "jiang", "膙" }, { "jiang", "茳" }, { "jiang", "蒋" }, { "jiang", "蔣" }, { "jiang", "薑" }, { "jiang", "虹" }, { "jiang", "螿" }, { "jiang", "袶" },
			{ "jiang", "講" }, { "jiang", "謽" }, { "jiang", "讲" }, { "jiang", "豇" }, { "jiang", "酱" }, { "jiang", "醤" }, { "jiang", "醬" }, { "jiang", "降" },
			{ "jiang", "韁" }, { "jiang", "顜" }, { "jiang an", "将按" }, { "jiang ba", "将把" }, { "jiang bei", "奖杯" }, { "jiang bei", "将被" },
			{ "jiang bei", "江北" }, { "jiang bi", "将比" }, { "jiang bian", "江边" }, { "jiang cheng", "奖惩" }, { "jiang cheng", "将成" }, { "jiang cheng", "江城" },
			{ "jiang cheng wei", "将成为" } };
};
