package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN58 {
	public static String[][] pl = { { "yong jiao", "用脚" }, { "yong jin", "佣金" }, { "yong jin", "涌进" }, { "yong jin", "用尽" }, { "yong jiu", "永久" },
			{ "yong jiu xing", "永久性" }, { "yong ju", "用具" }, { "yong kang", "永康" }, { "yong lai", "涌来" }, { "yong lai", "用来" }, { "yong lan", "慵懒" },
			{ "yong le", "永乐" }, { "yong li", "用例" }, { "yong li", "用力" }, { "yong liang", "用量" }, { "yong liao", "用料" }, { "yong meng", "勇猛" },
			{ "yong pin", "用品" }, { "yong qi", "勇气" }, { "yong qi", "涌起" }, { "yong qian", "用钱" }, { "yong ren", "佣人" }, { "yong ren", "用人" },
			{ "yong ren dan wei", "用人单位" }, { "yong ru", "涌入" }, { "yong shang", "涌上" }, { "yong shang", "用上" }, { "yong shang xin tou", "涌上心头" },
			{ "yong shen me", "用什么" }, { "yong sheng", "永生" }, { "yong shi", "勇士" }, { "yong shi", "永世" }, { "yong shi", "用时" }, { "yong shou", "用手" },
			{ "yong shou ji", "用手机" }, { "yong shu", "用书" }, { "yong shu biao", "用鼠标" }, { "yong shui", "用水" }, { "yong shui liang", "用水量" },
			{ "yong su", "庸俗" }, { "yong ta", "用它" }, { "yong tu", "用途" }, { "yong wan", "用完" }, { "yong wang zhi qian", "勇往直前" },
			{ "yong wu zhi di", "用武之地" }, { "yong xian", "涌现" }, { "yong xian chu", "涌现出" }, { "yong xiang", "涌向" }, { "yong xin", "用心" },
			{ "yong xin liang ku", "用心良苦" }, { "yong xing", "永兴" }, { "yong yao", "用药" }, { "yong yi", "泳衣" }, { "yong yi", "用以" }, { "yong yi", "用意" },
			{ "yong ying yu", "用英语" }, { "yong yong", "用用" }, { "yong you", "拥有" }, { "yong you", "用友" }, { "yong you", "用油" }, { "yong you zhe", "拥有者" },
			{ "yong yu", "勇于" }, { "yong yu", "用于" }, { "yong yu", "用语" }, { "yong yuan", "永远" }, { "yong yuan bu hui", "永远不会" }, { "yong yue", "踊跃" },
			{ "yong zai", "用在" }, { "yong zhe", "勇者" }, { "yong zhe", "拥着" }, { "yong zhe", "用着" }, { "yong zheng", "雍正" }, { "yong zhi", "用之" },
			{ "yong zhi", "用纸" }, { "yong zhong", "臃肿" }, { "yong zhou", "永州" }, { "yong zhuang", "泳装" }, { "yong zui", "用嘴" }, { "yong zuo", "用作" },
			{ "you", "优" }, { "you", "佑" }, { "you", "侑" }, { "you", "偤" }, { "you", "優" }, { "you", "冘" }, { "you", "卣" }, { "you", "又" }, { "you", "友" },
			{ "you", "右" }, { "you", "呦" }, { "you", "嚘" }, { "you", "囿" }, { "you", "姷" }, { "you", "宥" }, { "you", "尢" }, { "you", "尤" }, { "you", "峟" },
			{ "you", "幼" }, { "you", "幽" }, { "you", "庮" }, { "you", "忧" }, { "you", "怞" }, { "you", "怮" }, { "you", "悠" }, { "you", "憂" }, { "you", "懮" },
			{ "you", "戭" }, { "you", "揂" }, { "you", "攸" }, { "you", "斿" }, { "you", "有" }, { "you", "柚" }, { "you", "楢" }, { "you", "槱" }, { "you", "櫌" },
			{ "you", "沋" }, { "you", "油" }, { "you", "泑" }, { "you", "浟" }, { "you", "游" }, { "you", "瀀" }, { "you", "牖" }, { "you", "牰" }, { "you", "犹" },
			{ "you", "狖" }, { "you", "猶" }, { "you", "猷" }, { "you", "獶" }, { "you", "由" }, { "you", "疣" }, { "you", "祐" }, { "you", "秞" }, { "you", "繇" },
			{ "you", "纋" }, { "you", "羑" }, { "you", "耰" }, { "you", "聈" }, { "you", "肬" }, { "you", "苃" }, { "you", "莜" }, { "you", "莠" }, { "you", "莤" },
			{ "you", "莸" }, { "you", "蒏" }, { "you", "蕕" }, { "you", "蚘" }, { "you", "蚰" }, { "you", "蚴" }, { "you", "蝣" }, { "you", "蝤" }, { "you", "褎" },
			{ "you", "訧" }, { "you", "誘" }, { "you", "诱" }, { "you", "貁" }, { "you", "輶" }, { "you", "迶" }, { "you", "逌" }, { "you", "遊" }, { "you", "邮" },
			{ "you", "郵" }, { "you", "鄾" }, { "you", "酉" }, { "you", "釉" }, { "you", "銪" }, { "you", "銹" }, { "you", "铀" }, { "you", "铕" }, { "you", "魷" },
			{ "you", "鱿" }, { "you", "麀" }, { "you", "黝" }, { "you", "鼬" }, { "you a", "有啊" }, { "you ai", "友爱" }, { "you ai", "有爱" }, { "you an", "右岸" },
			{ "you an", "幽暗" }, { "you ba", "又把" }, { "you ba wo", "有把握" }, { "you bang", "友邦" }, { "you bei", "又被" }, { "you bi", "右臂" },
			{ "you bian", "右边" }, { "you bian", "有变" }, { "you bian", "邮编" }, { "you biao", "游标" }, { "you bie", "有别" }, { "you bing", "有病" },
			{ "you bing du", "有病毒" }, { "you bu", "又不" }, { "you bu de", "由不得" }, { "you bu neng", "又不能" }, { "you bu shi", "又不是" }, { "you cai", "有才" },
			{ "you cai", "油菜" }, { "you cai hua", "油菜花" }, { "you ce", "右侧" }, { "you chang", "悠长" }, { "you chang", "有偿" }, { "you chang", "油厂" },
			{ "you chang shi yong", "有偿使用" }, { "you che", "有车" }, { "you cheng", "又称" }, { "you cheng wei", "又称为" }, { "you chi", "幼齿" },
			{ "you chong", "幼虫" }, { "you chong tu", "有冲突" }, { "you chou", "忧愁" }, { "you chou", "有仇" }, { "you chu", "又出" }, { "you chu xian", "又出现" },
			{ "you chuan", "游船" }, { "you ci", "有次" }, { "you ci", "有此" }, { "you ci", "由此" }, { "you ci ke jian", "由此可见" }, { "you cong", "又从" },
			{ "you cuo", "有错" }, { "you da", "又大" }, { "you da", "又打" }, { "you da", "有大" }, { "you dai", "优待" }, { "you dai", "有待" }, { "you dang", "游荡" },
			{ "you dao", "又到" }, { "you dao", "有道" }, { "you dao", "诱导" }, { "you de", "又得" }, { "you de", "有得" }, { "you de", "有的" }, { "you de ren", "有的人" },
			{ "you de shi", "有的是" }, { "you dei", "又得" }, { "you deng", "油灯" }, { "you di", "邮递" }, { "you di fang shi", "有的放矢" }, { "you dian", "优点" },
			{ "you dian", "有点" }, { "you dian", "邮电" }, { "you dian er", "有点儿" }, { "you dian xiang", "有点像" }, { "you dong", "游动" }, { "you du", "有毒" },
			{ "you duo", "又多" }, { "you duo", "有多" }, { "you duo chang", "有多长" }, { "you duo da", "有多大" }, { "you duo gao", "有多高" }, { "you duo ge", "有多个" },
			{ "you duo shao ge", "有多少个" }, { "you duo shao ren", "有多少人" }, { "you duo shen", "有多深" }, { "you duo yuan", "有多远" }, { "you er", "幼儿" },
			{ "you er", "诱饵" }, { "you er yuan", "幼儿园" }, { "you fa", "诱发" }, { "you fang", "有房" }, { "you fei", "油费" }, { "you fei", "邮费" },
			{ "you fen", "有份" }, { "you feng", "有风" }, { "you feng fu de", "有丰富的" }, { "you fou", "有否" }, { "you fu", "有福" }, { "you gai", "又该" },
			{ "you gan", "有感" }, { "you gan er fa", "有感而发" }, { "you gan jue", "有感觉" }, { "you ge", "有个" }, { "you gei", "又给" }, { "you gong", "有功" },
			{ "you gou", "邮购" }, { "you gu", "幽谷" }, { "you guan", "有关" }, { "you guan bu men", "有关部门" }, { "you guan dan wei", "有关单位" },
			{ "you guan fa lv", "有关法律" }, { "you guan fang mian", "有关方面" }, { "you guan gui ding", "有关规定" }, { "you guan qing kuang", "有关情况" },
			{ "you guan ren shi", "有关人士" }, { "you guan ren yuan", "有关人员" }, { "you guan shi xiang", "有关事项" }, { "you guan wen jian", "有关文件" },
			{ "you guan wen ti", "有关问题" }, { "you guan zheng ce", "有关政策" }, { "you guan zi liao", "有关资料" }, { "you gui", "有鬼" }, { "you guo", "有过" },
			{ "you guo", "油锅" }, { "you guo zhi", "有过之" }, { "you hai", "有害" }, { "you hai wu zhi", "有害物质" }, { "you hao", "又好" }, { "you hao", "友好" },
			{ "you hao", "有好" }, { "you hao", "油耗" }, { "you hao gan", "有好感" }, { "you hao he zuo", "友好合作" }, { "you he", "又何" }, { "you he", "有何" },
			{ "you he bi", "又何必" }, { "you hei", "黝黑" }, { "you hen", "有很" }, { "you hen da", "有很大" }, { "you hen duo ren", "有很多人" },
			{ "you hen qiang", "有很强" }, { "you hou", "优厚" }, { "you hua", "优化" }, { "you hua", "有话" }, { "you hua", "油画" }, { "you hua da shi", "优化大师" },
			{ "you hua pei zhi", "优化配置" }, { "you hua she ji", "优化设计" }, { "you huan", "忧患" }, { "you huan yi shi", "忧患意识" }, { "you hui", "优惠" },
			{ "you hui", "又会" }, { "you hui", "幽会" }, { "you hui dao", "又回到" }, { "you hui huo dong", "优惠活动" }, { "you hui jia", "优惠价" },
			{ "you hui lai le", "又回来了" }, { "you hui quan", "优惠券" }, { "you hui zheng ce", "优惠政策" }, { "you huo", "有货" }, { "you huo", "诱惑" },
			{ "you huo li", "诱惑力" }, { "you ji", "右击" }, { "you ji", "有机" }, { "you ji", "游击" }, { "you ji", "游记" }, { "you ji", "邮寄" },
			{ "you ji ci", "有几次" }, { "you ji dui", "游击队" }, { "you ji fei", "有机肥" }, { "you ji fen", "有几分" }, { "you ji ge", "有几个" }, { "you ji jia", "有几家" },
			{ "you ji jie he", "有机结合" }, { "you ji shi pin", "有机食品" }, { "you ji wu", "有机物" }, { "you ji zhan", "游击战" }, { "you ji zhong", "有几种" },
			{ "you jia", "有加" }, { "you jia", "有家" }, { "you jia", "油价" }, { "you jia shang zhang", "油价上涨" }, { "you jian", "又见" }, { "you jian", "右键" },
			{ "you jian", "邮件" }, { "you jian cai dan", "右键菜单" }, { "you jian di zhi", "邮件地址" }, { "you jiang", "又将" }, { "you jiang", "有奖" },
			{ "you jiao", "又叫" }, { "you jiao", "右脚" }, { "you jiao", "幼教" }, { "you jiao da", "有较大" }, { "you jiao qiang", "有较强" }, { "you jin", "有劲" },
			{ "you jing", "幽静" }, { "you jing yan de", "有经验的" }, { "you jiu", "悠久" }, { "you ju", "有句" }, { "you ju", "邮局" }, { "you kai shi", "又开始" },
			{ "you ke", "又可" }, { "you ke", "有课" }, { "you ke", "游客" }, { "you ke yi", "又可以" }, { "you kong", "有空" }, { "you ku", "油库" }, { "you lai", "又来" },
			{ "you lai", "由来" }, { "you lai yi jiu", "由来已久" }, { "you lai yu", "有赖于" }, { "you lan", "幽兰" }, { "you lan", "游览" }, { "you le", "有了" },
			{ "you le", "游乐" }, { "you le chang", "游乐场" }, { "you le qian", "有了钱" }, { "you le yuan", "游乐园" }, { "you lei", "有泪" }, { "you li", "有利" },
			{ "you li", "有力" }, { "you li", "有理" }, { "you li", "有礼" }, { "you li", "游历" }, { "you li", "游离" }, { "you li ke tu", "有利可图" },
			{ "you li tiao jian", "有利条件" }, { "you liang", "优良" }, { "you liang", "有两" }, { "you liang chuan tong", "优良传统" }, { "you liang ge", "有两个" },
			{ "you liang hao de", "有良好的" }, { "you liang zhong", "有两种" }, { "you liao", "油料" }, { "you lie", "优劣" }, { "you ling", "幽灵" }, { "you lu", "右路" },
			{ "you lun", "油轮" }, { "you lv", "忧虑" }, { "you ma", "邮码" }, { "you mei", "优美" }, { "you mei", "又没" }, { "you mei", "由美" },
			{ "you mei you", "有没有" }, { "you mei you ren", "有没有人" }, { "you men", "友们" }, { "you men", "油门" }, { "you mian", "右面" }, { "you miao", "幼苗" },
			{ "you ming", "又名" }, { "you ming", "有名" }, { "you mo", "幽默" }, { "you mo", "油墨" }, { "you mo gan", "幽默感" }, { "you mu", "游牧" },
			{ "you mu gong du", "有目共睹" }, { "you na", "有哪" }, { "you na si", "尤纳斯" }, { "you nan", "有难" }, { "you nao", "右脑" }, { "you neng", "又能" },
			{ "you ni", "有你" }, { "you ni", "油腻" }, { "you ni", "由你" }, { "you nian", "幼年" }, { "you nv", "幼女" }, { "you pa", "又怕" }, { "you pai", "优派" },
			{ "you pai", "右派" }, { "you pan", "优盘" }, { "you pian", "诱骗" }, { "you piao", "邮票" }, { "you pin", "油品" }, { "you qi", "尤其" }, { "you qi", "有其" },
			{ "you qi", "油气" }, { "you qi", "油漆" }, { "you qi", "由其" }, { "you qi tu xing", "有期徒刑" }, { "you qi zhi", "有气质" }, { "you qian", "有钱" },
			{ "you qian le", "有钱了" }, { "you qian ren", "有钱人" }, { "you qing", "友情" }, { "you qing", "有情" }, { "you qing", "有请" },
			{ "you qing lian jie", "友情连接" }, { "you qing lian jie", "友情链接" }, { "you qing ren", "有情人" }, { "you qing ti shi", "友情提示" }, { "you qu", "又去" },
			{ "you qu", "有趣" }, { "you quan", "幼犬" }, { "you quan", "有权" }, { "you que dian", "优缺点" }, { "you ran", "悠然" }, { "you ran er sheng", "油然而生" },
			{ "you rang", "又让" }, { "you ren", "友人" }, { "you ren", "有人" }, { "you ren", "游人" }, { "you ren", "诱人" }, { "you ren ren wei", "有人认为" },
			{ "you ren yong", "有人用" }, { "you ren you yu", "游刃有余" }, { "you rou gua duan", "优柔寡断" }, { "you ru", "又如" }, { "you ru", "有如" },
			{ "you ru", "犹如" }, { "you ru he", "又如何" }, { "you san ge", "有三个" }, { "you san zhong", "有三种" }, { "you se", "有色" }, { "you se jin shu", "有色金属" },
			{ "you sha", "有啥" }, { "you shan", "友善" }, { "you shang", "右上" }, { "you shang", "忧伤" }, { "you shang", "有伤" }, { "you shang jiao", "右上角" },
			{ "you shei", "有谁" }, { "you shen", "幽深" }, { "you shen", "有什" }, { "you shen", "有神" }, { "you sheng", "有声" }, { "you sheng", "由省" },
			{ "you sheng lie tai", "优胜劣汰" }, { "you sheng you se", "有声有色" }, { "you sheng zhi nian", "有生之年" }, { "you shi", "优势" }, { "you shi", "又是" },
			{ "you shi", "有事" }, { "you shi", "有失" }, { "you shi", "有时" }, { "you shi", "由市" }, { "you shi chan ye", "优势产业" }, { "you shi hou", "有时候" },
			{ "you shi hu bu", "优势互补" }, { "you shi yi ge", "又是一个" }, { "you shi yi lai", "有史以来" }, { "you shi zhi shi", "有识之士" }, { "you shou", "右手" },
			{ "you shu", "有数" }, { "you shui", "有水" }, { "you shui", "有谁" }, { "you shui", "油水" }, { "you shui", "游水" }, { "you shui", "游说" },
			{ "you shui", "由谁" }, { "you shui zhi dao", "有谁知道" }, { "you shuo", "又说" }, { "you si ge", "有四个" }, { "you sun", "有损" }, { "you suo", "有所" },
			{ "you suo bu tong", "有所不同" }, { "you suo zuo wei", "有所作为" }, { "you ta", "由他" }, { "you tai", "犹太" }, { "you tai duo", "有太多" },
			{ "you tai ren", "犹太人" }, { "you tian", "又添" }, { "you tian", "有天" }, { "you tian", "油田" }, { "you tiao", "油条" }, { "you tiao bu wen", "有条不紊" },
			{ "you tiao jian de", "有条件的" }, { "you ting", "游艇" }, { "you tui", "右腿" }, { "you wan", "游玩" }, { "you wang", "有望" }, { "you wei", "又为" },
			{ "you wei", "尤为" }, { "you wei", "有位" }, { "you wei", "有违" }, { "you wen", "又问" }, { "you wen", "尤文" }, { "you wen tu si", "尤文图斯" },
			{ "you wo", "有我" }, { "you wu", "尤物" }, { "you wu", "有无" }, { "you wu", "有误" }, { "you wu", "油污" }, { "you xi", "有戏" }, { "you xi", "游戏" },
			{ "you xi bi", "游戏币" }, { "you xi gui ze", "游戏规则" }, { "you xi hua mian", "游戏画面" }, { "you xi ji", "游戏机" }, { "you xi li", "游戏里" },
			{ "you xi wan jia", "游戏玩家" }, { "you xia", "右下" }, { "you xia", "游侠" }, { "you xia jiao", "右下角" }, { "you xian", "优先" }, { "you xian", "悠闲" },
			{ "you xian", "有线" }, { "you xian", "有限" }, { "you xian", "由县" }, { "you xian dian shi", "有线电视" }, { "you xian fa zhan", "优先发展" },
			{ "you xian gong si", "有限公司" }, { "you xian ji", "优先级" }, { "you xian kao lv", "优先考虑" }, { "you xian quan", "优先权" }, { "you xian tong", "有线通" },
			{ "you xian yuan", "有限元" }, { "you xian ze ren", "有限责任" }, { "you xiang", "又像" }, { "you xiang", "又向" }, { "you xiang", "幽香" },
			{ "you xiang", "油箱" }, { "you xiang", "邮箱" }, { "you xiang di zhi", "邮箱地址" }, { "you xiao", "幼小" }, { "you xiao", "有效" },
			{ "you xiao cheng fen", "有效成分" }, { "you xiao cuo shi", "有效措施" }, { "you xiao kong zhi", "有效控制" }, { "you xiao li yong", "有效利用" },
			{ "you xiao qi", "有效期" }, { "you xiao tu jing", "有效途径" }, { "you xiao xing", "有效性" }, { "you xie", "有些" }, { "you xie ren", "有些人" },
			{ "you xie shi", "有些事" }, { "you xie shi qing", "有些事情" }, { "you xin", "忧心" }, { "you xin", "有心" }, { "you xin", "有新" },
			{ "you xin chong chong", "忧心忡忡" }, { "you xin ren", "有心人" }, { "you xing", "有幸" }, { "you xing", "有形" }, { "you xing", "油性" },
			{ "you xing", "游行" }, { "you xiu", "优秀" }, { "you xiu jiao shi", "优秀教师" }, { "you xiu ren cai", "优秀人才" }, { "you xiu xue sheng", "优秀学生" },
			{ "you xiu zuo pin", "优秀作品" }, { "you xu", "有序" }, { "you xuan", "优选" }, { "you ya", "优雅" }, { "you ya", "幽雅" }, { "you yan", "右眼" },
			{ "you yan", "油烟" }, { "you yang", "悠扬" }, { "you yang", "有氧" }, { "you yao", "又要" }, { "you yi", "优异" }, { "you yi", "又一" }, { "you yi", "又以" },
			{ "you yi", "友谊" }, { "you yi", "右翼" }, { "you yi", "尤以" }, { "you yi", "有一" }, { "you yi", "有意" }, { "you yi", "有益" }, { "you yi ci", "又一次" },
			{ "you yi ci", "有一次" }, { "you yi duan", "有一段" }, { "you yi fen", "有一份" }, { "you yi ge ren", "有一个人" }, { "you yi ke", "有一颗" },
			{ "you yi kuai", "有一块" }, { "you yi sai", "友谊赛" }, { "you yi shi", "有意识" }, { "you yi si", "有意思" }, { "you yi tao", "有一套" },
			{ "you yi tian", "有一天" }, { "you yi tiao", "有一条" }, { "you yi wei", "有一位" }, { "you yi wei", "有异味" }, { "you yi wu yi", "有意无意" },
			{ "you yi zhe", "有意者" }, { "you yi zhi", "有一只" }, { "you yi zhong", "有一种" }, { "you yi zuo", "有一座" }, { "you yin", "又因" }, { "you yin", "诱因" },
			{ "you ying xiang de", "有影响的" }, { "you yong", "又用" }, { "you yong", "有用" }, { "you yong", "游泳" }, { "you yong chi", "游泳池" },
			{ "you yong guan", "游泳馆" }, { "you yong ma", "有用吗" }, { "you you", "又有" }, { "you you", "幽幽" }, { "you you", "悠悠" }, { "you yu", "优于" },
			{ "you yu", "忧郁" }, { "you yu", "有余" }, { "you yu", "有雨" }, { "you yu", "犹豫" }, { "you yu", "由于" }, { "you yu", "鱿鱼" },
			{ "you yu bu jue", "犹豫不决" }, { "you yu qi", "由于其" }, { "you yu zheng", "忧郁症" }, { "you yuan", "幽怨" }, { "you yuan", "悠远" }, { "you yuan", "有源" },
			{ "you yuan", "有缘" }, { "you yuan", "游园" }, { "you yuan", "由原" }, { "you yuan ren", "有缘人" }, { "you yue", "优越" }, { "you yue", "有约" },
			{ "you yue gan", "优越感" }, { "you yue xing", "优越性" }, { "you zai", "又在" }, { "you zen", "又怎" }, { "you zha", "油炸" }, { "you zhao yi ri", "有朝一日" },
			{ "you zhe", "有着" }, { "you zhen dui xing", "有针对性" }, { "you zheng", "邮政" }, { "you zheng bian ma", "邮政编码" }, { "you zheng chu xu", "邮政储蓄" },
			{ "you zheng ju", "邮政局" }, { "you zhi", "优质" }, { "you zhi", "幼稚" }, { "you zhi", "有志" }, { "you zhi", "油脂" }, { "you zhi fu wu", "优质服务" },
			{ "you zhong", "有种" }, { "you zhong", "由衷" }, { "you zhu", "有助" }, { "you zhu yu", "有助于" }, { "you zhuan", "右转" }, { "you zi", "柚子" },
			{ "you zi", "游子" }, { "you zi", "游资" }, { "you zi", "邮资" }, { "you zou", "游走" }, { "you zui", "有罪" }, { "yu", "与" }, { "yu", "丿" }, { "yu", "予" },
			{ "yu", "于" }, { "yu", "亐" }, { "yu", "伃" }, { "yu", "伛" }, { "yu", "余" }, { "yu", "俁" }, { "yu", "俞" }, { "yu", "俣" }, { "yu", "偊" },
			{ "yu", "傴" }, { "yu", "僪" }, { "yu", "儥" }, { "yu", "兪" }, { "yu", "吁" }, { "yu", "唹" }, { "yu", "喁" }, { "yu", "喩" }, { "yu", "喻" },
			{ "yu", "噊" }, { "yu", "噳" }, { "yu", "圄" }, { "yu", "圉" }, { "yu", "域" }, { "yu", "堉" }, { "yu", "堣" }, { "yu", "堬" }, { "yu", "妤" },
			{ "yu", "妪" }, { "yu", "娛" }, { "yu", "娯" }, { "yu", "娱" }, { "yu", "媮" }, { "yu", "嫗" }, { "yu", "宇" }, { "yu", "寓" }, { "yu", "寙" },
			{ "yu", "尉" }, { "yu", "屿" }, { "yu", "峪" }, { "yu", "峿" }, { "yu", "崳" }, { "yu", "嵎" }, { "yu", "嵛" }, { "yu", "嶼" }, { "yu", "庾" },
			{ "yu", "彧" }, { "yu", "御" }, { "yu", "悆" }, { "yu", "悇" }, { "yu", "愈" }, { "yu", "愉" }, { "yu", "愚" }, { "yu", "慾" }, { "yu", "戫" },
			{ "yu", "扜" }, { "yu", "挧" }, { "yu", "揄" }, { "yu", "敔" }, { "yu", "斔" }, { "yu", "斞" }, { "yu", "於" }, { "yu", "旟" }, { "yu", "昱" },
			{ "yu", "杅" }, { "yu", "栯" }, { "yu", "桙" }, { "yu", "棜" }, { "yu", "棫" }, { "yu", "楀" }, { "yu", "楡" }, { "yu", "楰" }, { "yu", "榆" },
			{ "yu", "欝" }, { "yu", "欤" }, { "yu", "欲" }, { "yu", "歈" }, { "yu", "歟" }, { "yu", "歶" }, { "yu", "毓" }, { "yu", "汚" }, { "yu", "浴" },
			{ "yu", "淢" }, { "yu", "淤" }, { "yu", "淯" }, { "yu", "渔" }, { "yu", "渝" }, { "yu", "湡" }, { "yu", "漁" }, { "yu", "潏" }, { "yu", "澞" },
			{ "yu", "澦" }, { "yu", "灪" }, { "yu", "煜" }, { "yu", "熨" }, { "yu", "燏" }, { "yu", "燠" }, { "yu", "燰" }, { "yu", "爩" }, { "yu", "牏" },
			{ "yu", "狱" }, { "yu", "狳" }, { "yu", "獄" }, { "yu", "獝" }, { "yu", "玉" }, { "yu", "玗" }, { "yu", "瑀" }, { "yu", "瑜" }, { "yu", "璵" },
			{ "yu", "畬" }, { "yu", "畭" }, { "yu", "瘀" }, { "yu", "瘉" }, { "yu", "瘐" }, { "yu", "癒" }, { "yu", "盂" }, { "yu", "盓" }, { "yu", "睮" },
			{ "yu", "矞" }, { "yu", "砡" }, { "yu", "硢" }, { "yu", "礇" }, { "yu", "礖" }, { "yu", "礜" }, { "yu", "祤" }, { "yu", "禦" }, { "yu", "禹" },
			{ "yu", "禺" }, { "yu", "稢" }, { "yu", "稶" }, { "yu", "穻" }, { "yu", "窬" }, { "yu", "窳" }, { "yu", "竽" }, { "yu", "箊" }, { "yu", "篽" },
			{ "yu", "籅" }, { "yu", "籲" }, { "yu", "紆" }, { "yu", "緎" }, { "yu", "繘" }, { "yu", "纡" }, { "yu", "罭" }, { "yu", "羭" }, { "yu", "羽" },
			{ "yu", "翑" }, { "yu", "聿" }, { "yu", "育" }, { "yu", "腴" }, { "yu", "臾" }, { "yu", "舁" }, { "yu", "舆" }, { "yu", "與" }, { "yu", "艅" },
			{ "yu", "芋" }, { "yu", "荢" }, { "yu", "菸" }, { "yu", "萭" }, { "yu", "萸" }, { "yu", "蒮" }, { "yu", "蓣" }, { "yu", "蓹" }, { "yu", "蔚" },
			{ "yu", "蕍" }, { "yu", "蕷" }, { "yu", "薁" }, { "yu", "藇" }, { "yu", "蘌" }, { "yu", "蘛" }, { "yu", "虞" }, { "yu", "蜮" }, { "yu", "蝓" },
			{ "yu", "蝺" }, { "yu", "螸" }, { "yu", "蟈" }, { "yu", "衧" }, { "yu", "袬" }, { "yu", "裕" }, { "yu", "褕" }, { "yu", "覦" }, { "yu", "觎" },
			{ "yu", "誉" }, { "yu", "語" }, { "yu", "諛" }, { "yu", "諭" }, { "yu", "謣" }, { "yu", "譽" }, { "yu", "语" }, { "yu", "谀" }, { "yu", "谕" },
			{ "yu", "谷" }, { "yu", "豫" }, { "yu", "貍" }, { "yu", "貐" }, { "yu", "貗" }, { "yu", "踰" }, { "yu", "軉" }, { "yu", "輍" }, { "yu", "輿" },
			{ "yu", "轝" }, { "yu", "迂" }, { "yu", "逾" }, { "yu", "遇" }, { "yu", "遹" }, { "yu", "邘" }, { "yu", "郁" }, { "yu", "鄅" }, { "yu", "醧" },
			{ "yu", "釪" }, { "yu", "鈺" }, { "yu", "鋊" }, { "yu", "鋙" }, { "yu", "錥" }, { "yu", "钰" }, { "yu", "閼" }, { "yu", "閾" }, { "yu", "阈" },
			{ "yu", "陓" }, { "yu", "隃" }, { "yu", "隅" }, { "yu", "隩" }, { "yu", "雓" }, { "yu", "雨" }, { "yu", "雩" }, { "yu", "預" }, { "yu", "頨" },
			{ "yu", "顒" }, { "yu", "预" }, { "yu", "飫" }, { "yu", "餘" }, { "yu", "饇" }, { "yu", "饫" }, { "yu", "馀" }, { "yu", "馭" }, { "yu", "驈" },
			{ "yu", "驭" }, { "yu", "鬱" }, { "yu", "鬻" }, { "yu", "魊" }, { "yu", "魚" }, { "yu", "鮽" }, { "yu", "鯲" }, { "yu", "鰅" }, { "yu", "鱊" },
			{ "yu", "鱮" }, { "yu", "鱼" }, { "yu", "鳿" }, { "yu", "鴥" }, { "yu", "鴪" }, { "yu", "鵒" }, { "yu", "鷸" }, { "yu", "鸆" }, { "yu", "鸒" },
			{ "yu", "鹆" }, { "yu", "鹬" }, { "yu", "麌" }, { "yu", "齬" }, { "yu", "齵" }, { "yu", "龉" }, { "yu an", "预案" }, { "yu ba bu neng", "欲罢不能" },
			{ "yu bao", "预报" }, { "yu bei", "预备" }, { "yu bei dui", "预备队" }, { "yu bei yi", "预备役" }, { "yu cai", "育才" }, { "yu ce", "预测" },
			{ "yu chan qi", "预产期" }, { "yu chang", "浴场" }, { "yu chi", "浴池" }, { "yu chi", "鱼翅" }, { "yu chu li", "预处理" }, { "yu chuan", "渔船" },
			{ "yu chun", "宇春" }, { "yu chun", "愚蠢" }, { "yu ci", "与此" }, { "yu ci", "于此" }, { "yu ci", "遇刺" }, { "yu ci tong shi", "与此同时" },
			{ "yu cun", "渔村" }, { "yu cun", "预存" }, { "yu dan", "于丹" }, { "yu dao", "遇到" }, { "yu dao kun nan", "遇到困难" }, { "yu dao wen ti", "遇到问题" },
			{ "yu di", "余地" }, { "yu di", "玉帝" }, { "yu di", "雨滴" }, { "yu dian", "雨点" }, { "yu diao", "语调" }, { "yu ding", "预定" }, { "yu ding", "预订" },
			{ "yu e", "余额" } };
};
