package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN14 {
	public static String[][] pl = { { "feng", "丰" }, { "feng", "俸" }, { "feng", "偑" }, { "feng", "冯" }, { "feng", "凤" }, { "feng", "凬" }, { "feng", "唪" },
			{ "feng", "堸" }, { "feng", "奉" }, { "feng", "妦" }, { "feng", "封" }, { "feng", "峯" }, { "feng", "峰" }, { "feng", "崶" }, { "feng", "捀" },
			{ "feng", "枫" }, { "feng", "桻" }, { "feng", "楓" }, { "feng", "檒" }, { "feng", "沣" }, { "feng", "渢" }, { "feng", "灃" }, { "feng", "烽" },
			{ "feng", "焨" }, { "feng", "犎" }, { "feng", "猦" }, { "feng", "甮" }, { "feng", "疯" }, { "feng", "瘋" }, { "feng", "砜" }, { "feng", "縫" },
			{ "feng", "缝" }, { "feng", "艂" }, { "feng", "葑" }, { "feng", "蜂" }, { "feng", "覂" }, { "feng", "諷" }, { "feng", "讽" }, { "feng", "豐" },
			{ "feng", "賵" }, { "feng", "逢" }, { "feng", "酆" }, { "feng", "鋒" }, { "feng", "锋" }, { "feng", "風" }, { "feng", "飌" }, { "feng", "风" },
			{ "feng", "馮" }, { "feng", "鳳" }, { "feng", "麷" }, { "feng bao", "风暴" }, { "feng bei", "丰碑" }, { "feng bi", "封闭" }, { "feng bi shi", "封闭式" },
			{ "feng bo", "风波" }, { "feng cai", "风采" }, { "feng ce", "封测" }, { "feng chan", "丰产" }, { "feng chao", "风潮" }, { "feng che", "风车" },
			{ "feng chen", "风尘" }, { "feng cheng", "奉承" }, { "feng chui", "风吹" }, { "feng chui cao dong", "风吹草动" }, { "feng chui guo", "风吹过" },
			{ "feng ci", "讽刺" }, { "feng cun", "封存" }, { "feng da", "风大" }, { "feng di", "封底" }, { "feng di", "逢低" }, { "feng di", "风笛" },
			{ "feng dian", "疯癫" }, { "feng dian", "风电" }, { "feng diao", "疯掉" }, { "feng ding", "封顶" }, { "feng du", "封堵" }, { "feng du", "风度" },
			{ "feng er", "风儿" }, { "feng fan", "风帆" }, { "feng fan", "风范" }, { "feng feng huo huo", "风风火火" }, { "feng feng yu yu", "风风雨雨" },
			{ "feng fu", "丰富" }, { "feng fu duo cai", "丰富多彩" }, { "feng gan", "风干" }, { "feng ge", "风格" }, { "feng gong", "冯巩" }, { "feng gou", "疯狗" },
			{ "feng guang", "风光" }, { "feng guo", "风过" }, { "feng han", "风寒" }, { "feng hao", "封号" }, { "feng he", "缝合" }, { "feng hou", "丰厚" },
			{ "feng hua", "风化" }, { "feng hua", "风华" }, { "feng hua xue yue", "风花雪月" }, { "feng huang", "凤凰" }, { "feng huang cheng", "凤凰城" },
			{ "feng huang wang", "凤凰网" }, { "feng huang wei shi", "凤凰卫视" }, { "feng hui", "峰会" }, { "feng huo", "烽火" }, { "feng ji", "风机" },
			{ "feng jian", "封建" }, { "feng jian mi xin", "封建迷信" }, { "feng jian she hui", "封建社会" }, { "feng jiao", "蜂胶" }, { "feng jie", "凤姐" },
			{ "feng jing", "风景" }, { "feng jing qu", "风景区" }, { "feng jing xian", "风景线" }, { "feng kou", "封口" }, { "feng kou", "风口" },
			{ "feng kou lang jian", "风口浪尖" }, { "feng kuang", "疯狂" }, { "feng lang", "风浪" }, { "feng le", "封了" }, { "feng le", "疯了" }, { "feng lei", "风雷" },
			{ "feng li", "锋利" }, { "feng li", "风力" }, { "feng li", "风里" }, { "feng li fa dian", "风力发电" }, { "feng liang", "风量" }, { "feng lin", "枫林" },
			{ "feng ling", "风铃" }, { "feng liu", "风流" }, { "feng man", "丰满" }, { "feng mang", "锋芒" }, { "feng mao", "风貌" }, { "feng mao lin jiao", "凤毛麟角" },
			{ "feng mi", "蜂蜜" }, { "feng mi", "风靡" }, { "feng mian", "封面" }, { "feng ming", "奉命" }, { "feng neng", "风能" }, { "feng nian guo jie", "逢年过节" },
			{ "feng nu", "风怒" }, { "feng pei", "奉陪" }, { "feng ping lang jing", "风平浪静" }, { "feng qi", "风气" }, { "feng qi", "风起" },
			{ "feng qi yun yong", "风起云涌" }, { "feng qing", "风情" }, { "feng qing wan zhong", "风情万种" }, { "feng qu", "风趣" }, { "feng quan", "奉劝" },
			{ "feng ren", "缝纫" }, { "feng ren ji", "缝纫机" }, { "feng sao", "风骚" }, { "feng sha", "封杀" }, { "feng sha", "风沙" }, { "feng shan", "风扇" },
			{ "feng shang", "奉上" }, { "feng shang", "风尚" }, { "feng shen", "风神" }, { "feng shen bang", "封神榜" }, { "feng sheng", "丰盛" }, { "feng sheng", "风声" },
			{ "feng shi", "风湿" }, { "feng shi bing", "风湿病" }, { "feng shou", "丰收" }, { "feng shuang", "风霜" }, { "feng shui", "风水" }, { "feng shuo", "丰硕" },
			{ "feng si", "封死" }, { "feng su", "风俗" }, { "feng su", "风速" }, { "feng suo", "封锁" }, { "feng tai", "丰台" }, { "feng tai qu", "丰台区" },
			{ "feng tian", "丰田" }, { "feng tiao", "封条" }, { "feng tou", "风头" }, { "feng tou", "风投" }, { "feng tu ren qing", "风土人情" }, { "feng wei", "奉为" },
			{ "feng wei", "封为" }, { "feng wei", "风味" }, { "feng wo", "蜂窝" }, { "feng xi", "缝隙" }, { "feng xian", "奉献" }, { "feng xian", "奉贤" },
			{ "feng xian", "锋线" }, { "feng xian", "风险" }, { "feng xian guan li", "风险管理" }, { "feng xian jing shen", "奉献精神" }, { "feng xian kong zhi", "风险控制" },
			{ "feng xian tou zi", "风险投资" }, { "feng xiang", "风向" }, { "feng xiang biao", "风向标" }, { "feng xiao gang", "冯小刚" }, { "feng xin", "封信" },
			{ "feng xing", "奉行" }, { "feng xing", "风行" }, { "feng xiong", "丰胸" }, { "feng xue", "风雪" }, { "feng ya", "风雅" }, { "feng ye", "枫叶" },
			{ "feng yi", "风衣" }, { "feng yin", "封印" }, { "feng yong", "蜂拥" }, { "feng yu", "风雨" }, { "feng yue", "风月" }, { "feng yun", "风云" },
			{ "feng yun", "风韵" }, { "feng yun ren wu", "风云人物" }, { "feng zhang", "疯涨" }, { "feng zheng", "风筝" }, { "feng zhi", "峰值" }, { "feng zhi", "缝制" },
			{ "feng zhi", "风之" }, { "feng zhong", "风中" }, { "feng zhu", "封住" }, { "feng zhuang", "封装" }, { "feng zi", "疯子" }, { "feng zi", "风姿" },
			{ "fiao", "覅" }, { "fo", "仏" }, { "fo", "佛" }, { "fo", "坲" }, { "fo fa", "佛法" }, { "fo jia", "佛家" }, { "fo jiao", "佛教" }, { "fo jiao tu", "佛教徒" },
			{ "fo jing", "佛经" }, { "fo luo lun sa", "佛罗伦萨" }, { "fo men", "佛门" }, { "fo ru", "佛如" }, { "fo shan", "佛山" }, { "fo shan shi", "佛山市" },
			{ "fo tuo", "佛陀" }, { "fo xiang", "佛像" }, { "fo xue", "佛学" }, { "fo zu", "佛祖" }, { "fou", "否" }, { "fou", "紑" }, { "fou", "缶" }, { "fou", "缹" },
			{ "fou", "鴀" }, { "fou ding", "否定" }, { "fou jue", "否决" }, { "fou ren", "否认" }, { "fou ze", "否则" }, { "fu", "付" }, { "fu", "伏" }, { "fu", "伕" },
			{ "fu", "佛" }, { "fu", "俘" }, { "fu", "俯" }, { "fu", "偩" }, { "fu", "偪" }, { "fu", "傅" }, { "fu", "冨" }, { "fu", "冹" }, { "fu", "凫" },
			{ "fu", "刜" }, { "fu", "副" }, { "fu", "匐" }, { "fu", "呋" }, { "fu", "咈" }, { "fu", "咐" }, { "fu", "坿" }, { "fu", "垘" }, { "fu", "复" },
			{ "fu", "夫" }, { "fu", "妇" }, { "fu", "姇" }, { "fu", "婦" }, { "fu", "嬔" }, { "fu", "孚" }, { "fu", "孵" }, { "fu", "富" }, { "fu", "岪" },
			{ "fu", "帗" }, { "fu", "幅" }, { "fu", "幞" }, { "fu", "府" }, { "fu", "弗" }, { "fu", "弣" }, { "fu", "彿" }, { "fu", "復" }, { "fu", "怤" },
			{ "fu", "怫" }, { "fu", "扶" }, { "fu", "抚" }, { "fu", "拂" }, { "fu", "拊" }, { "fu", "撫" }, { "fu", "敷" }, { "fu", "斧" }, { "fu", "服" },
			{ "fu", "枎" }, { "fu", "枹" }, { "fu", "柎" }, { "fu", "柫" }, { "fu", "柭" }, { "fu", "桴" }, { "fu", "椨" }, { "fu", "榑" }, { "fu", "氟" },
			{ "fu", "泭" }, { "fu", "洑" }, { "fu", "浮" }, { "fu", "涪" }, { "fu", "滏" }, { "fu", "澓" }, { "fu", "烰" }, { "fu", "父" }, { "fu", "玸" },
			{ "fu", "琈" }, { "fu", "甫" }, { "fu", "畉" }, { "fu", "砆" }, { "fu", "砩" }, { "fu", "祓" }, { "fu", "祔" }, { "fu", "福" }, { "fu", "稃" },
			{ "fu", "符" }, { "fu", "笰" }, { "fu", "箙" }, { "fu", "簠" }, { "fu", "糐" }, { "fu", "紨" }, { "fu", "紱" }, { "fu", "紼" }, { "fu", "綍" },
			{ "fu", "綒" }, { "fu", "緮" }, { "fu", "縛" }, { "fu", "绂" }, { "fu", "绋" }, { "fu", "缚" }, { "fu", "罘" }, { "fu", "罦" }, { "fu", "翇" },
			{ "fu", "肤" }, { "fu", "脯" }, { "fu", "腐" }, { "fu", "腑" }, { "fu", "腹" }, { "fu", "膚" }, { "fu", "艀" }, { "fu", "艴" }, { "fu", "芙" },
			{ "fu", "芣" }, { "fu", "芾" }, { "fu", "苻" }, { "fu", "茀" }, { "fu", "茯" }, { "fu", "荂" }, { "fu", "荴" }, { "fu", "莩" }, { "fu", "菔" },
			{ "fu", "萉" }, { "fu", "萯" }, { "fu", "葍" }, { "fu", "蕧" }, { "fu", "虙" }, { "fu", "蚥" }, { "fu", "蚨" }, { "fu", "蚹" }, { "fu", "蛗" },
			{ "fu", "蜅" }, { "fu", "蜉" }, { "fu", "蝜" }, { "fu", "蝠" }, { "fu", "蝮" }, { "fu", "衭" }, { "fu", "袚" }, { "fu", "袱" }, { "fu", "複" },
			{ "fu", "褔" }, { "fu", "覆" }, { "fu", "訃" }, { "fu", "諨" }, { "fu", "讣" }, { "fu", "負" }, { "fu", "賦" }, { "fu", "賻" }, { "fu", "负" },
			{ "fu", "赋" }, { "fu", "赙" }, { "fu", "赴" }, { "fu", "趺" }, { "fu", "跗" }, { "fu", "踾" }, { "fu", "輔" }, { "fu", "輹" }, { "fu", "輻" },
			{ "fu", "辅" }, { "fu", "辐" }, { "fu", "邞" }, { "fu", "郙" }, { "fu", "郛" }, { "fu", "鄜" }, { "fu", "釜" }, { "fu", "釡" }, { "fu", "鈇" },
			{ "fu", "鍑" }, { "fu", "阜" }, { "fu", "附" }, { "fu", "韍" }, { "fu", "頫" }, { "fu", "馥" }, { "fu", "駙" }, { "fu", "驸" }, { "fu", "髴" },
			{ "fu", "鮒" }, { "fu", "鰒" }, { "fu", "鲋" }, { "fu", "鳆" }, { "fu", "鳧" }, { "fu", "鳬" }, { "fu", "鴔" }, { "fu", "鵩" }, { "fu", "鶝" },
			{ "fu", "麩" }, { "fu", "麸" }, { "fu", "黻" }, { "fu", "黼" }, { "fu ai", "父爱" }, { "fu bai", "腐败" }, { "fu bai fen zi", "腐败分子" },
			{ "fu bai xian xiang", "腐败现象" }, { "fu bei", "父辈" }, { "fu ben", "副本" }, { "fu bi", "伏笔" }, { "fu bi", "复辟" }, { "fu biao", "附表" },
			{ "fu bu", "腹部" }, { "fu bu si", "福布斯" }, { "fu cai", "福彩" }, { "fu cha", "复查" }, { "fu chan ke", "妇产科" }, { "fu chan pin", "副产品" },
			{ "fu chi", "扶持" }, { "fu chi zheng ce", "扶持政策" }, { "fu chou", "复仇" }, { "fu chu", "付出" }, { "fu chu", "复出" }, { "fu chu", "浮出" },
			{ "fu chu shui mian", "浮出水面" }, { "fu cong", "服从" }, { "fu dai", "附带" }, { "fu dan", "复旦" }, { "fu dan", "负担" }, { "fu dan da xue", "复旦大学" },
			{ "fu dao", "辅导" }, { "fu dao ban", "辅导班" }, { "fu dao yuan", "辅导员" }, { "fu de", "福德" }, { "fu di", "腹地" }, { "fu dian", "浮点" },
			{ "fu diao", "浮雕" }, { "fu dong", "浮动" }, { "fu du", "复读" }, { "fu du", "幅度" }, { "fu er mo si", "福尔摩斯" }, { "fu fa", "复发" }, { "fu fan", "复返" },
			{ "fu fang", "复方" }, { "fu fei", "付费" }, { "fu fu", "夫妇" }, { "fu gai", "覆盖" }, { "fu gai fan wei", "覆盖范围" }, { "fu gai lv", "覆盖率" },
			{ "fu gai mian", "覆盖面" }, { "fu gang", "赴港" }, { "fu ge sen", "弗格森" }, { "fu gei", "付给" }, { "fu gu", "复古" }, { "fu gui", "富贵" },
			{ "fu guo", "富国" }, { "fu han", "富含" }, { "fu hao", "富豪" }, { "fu hao", "符号" }, { "fu hao bang", "富豪榜" }, { "fu he", "复合" }, { "fu he", "复核" },
			{ "fu he", "符合" }, { "fu he", "负荷" }, { "fu he", "附和" }, { "fu he cai liao", "复合材料" }, { "fu he fei", "复合肥" }, { "fu he guo jia", "符合国家" },
			{ "fu he tiao jian", "符合条件" }, { "fu he xing", "复合型" }, { "fu hua", "孵化" }, { "fu hua", "幅画" }, { "fu hua", "浮华" }, { "fu hua", "腐化" },
			{ "fu hua qi", "孵化器" }, { "fu huang", "父皇" }, { "fu huo", "俘获" }, { "fu huo", "复活" }, { "fu huo jie", "复活节" }, { "fu ji", "伏击" },
			{ "fu ji", "腹肌" }, { "fu ji ni ya", "弗吉尼亚" }, { "fu jia", "富家" }, { "fu jia", "附加" }, { "fu jia fei", "附加费" }, { "fu jia zhi", "附加值" },
			{ "fu jian", "福建" }, { "fu jian", "附件" }, { "fu jian sheng", "福建省" }, { "fu jiao shou", "副教授" }, { "fu jin", "福晋" }, { "fu jin", "附近" },
			{ "fu jing", "赴京" }, { "fu jun", "夫君" }, { "fu kan", "俯瞰" }, { "fu kan", "副刊" }, { "fu kang", "富康" }, { "fu ke", "妇科" }, { "fu ke bing", "妇科病" },
			{ "fu ke si", "福克斯" }, { "fu kua", "浮夸" }, { "fu kuan", "付款" }, { "fu kuan fang shi", "付款方式" }, { "fu lan", "弗兰" }, { "fu lan", "腐烂" },
			{ "fu lan ke", "弗兰克" }, { "fu lang xi si", "弗朗西斯" }, { "fu lao xiang qin", "父老乡亲" }, { "fu lei", "弗雷" }, { "fu li", "富力" }, { "fu li", "福利" },
			{ "fu li cai piao", "福利彩票" }, { "fu li dai yu", "福利待遇" }, { "fu li yuan", "福利院" }, { "fu li zi", "负离子" }, { "fu lian", "妇联" }, { "fu liao", "辅料" },
			{ "fu ling", "涪陵" }, { "fu lu", "俘虏" }, { "fu lu", "附录" }, { "fu luo yi de", "弗洛伊德" }, { "fu ma", "驸马" }, { "fu mei", "赴美" },
			{ "fu mei lai", "福美来" }, { "fu mian", "负面" }, { "fu mian xin wen", "负面新闻" }, { "fu mian ying xiang", "负面影响" }, { "fu min", "富民" },
			{ "fu mo", "抚摩" }, { "fu mo", "抚摸" }, { "fu mo", "附魔" }, { "fu mu", "父母" }, { "fu mu qin", "父母亲" }, { "fu nv", "妇女" }, { "fu nv", "父女" },
			{ "fu nv er tong", "妇女儿童" }, { "fu pai", "复牌" }, { "fu pin", "扶贫" }, { "fu pin kai fa", "扶贫开发" }, { "fu ping", "抚平" }, { "fu ping", "浮萍" },
			{ "fu po", "富婆" }, { "fu qi", "夫妻" }, { "fu qi", "扶起" }, { "fu qi", "服气" }, { "fu qi", "浮起" }, { "fu qi", "福气" }, { "fu qi", "负起" },
			{ "fu qi guan xi", "夫妻关系" }, { "fu qi sheng huo", "夫妻生活" }, { "fu qi shuang fang", "夫妻双方" }, { "fu qi zhi jian", "夫妻之间" }, { "fu qian", "付钱" },
			{ "fu qian", "肤浅" }, { "fu qiang", "富强" }, { "fu qiang", "腹腔" }, { "fu qiang jing", "腹腔镜" }, { "fu qin", "父亲" }, { "fu qin jie", "父亲节" },
			{ "fu qing", "付清" }, { "fu qing", "福清" }, { "fu rao", "富饶" }, { "fu ren", "夫人" }, { "fu ren", "妇人" }, { "fu ren", "富人" }, { "fu rong", "芙蓉" },
			{ "fu rong jie jie", "芙蓉姐姐" }, { "fu sai", "复赛" }, { "fu se", "肤色" }, { "fu shan", "釜山" }, { "fu shang", "富商" }, { "fu shang", "浮上" },
			{ "fu shang", "负伤" }, { "fu shang", "附上" }, { "fu she", "敷设" }, { "fu she", "辐射" }, { "fu shen", "俯身" }, { "fu shen", "复审" }, { "fu sheng", "浮生" },
			{ "fu shi", "俯视" }, { "fu shi", "复式" }, { "fu shi", "复试" }, { "fu shi", "富士" }, { "fu shi", "服侍" }, { "fu shi", "服饰" }, { "fu shi", "腐蚀" },
			{ "fu shi", "辅食" }, { "fu shi kang", "富士康" }, { "fu shi shan", "富士山" }, { "fu shi tong", "富士通" }, { "fu shi xing", "腐蚀性" }, { "fu shou", "副手" },
			{ "fu shou", "扶手" }, { "fu shu", "复数" }, { "fu shu", "复述" }, { "fu shu", "服输" }, { "fu shu", "负数" }, { "fu shu", "附属" },
			{ "fu shu yi yuan", "附属医院" }, { "fu shui", "腹水" }, { "fu shun", "抚顺" }, { "fu si ji", "夫斯基" }, { "fu song", "附送" }, { "fu su", "复苏" },
			{ "fu tai", "赴台" }, { "fu te", "福特" }, { "fu ti", "附体" }, { "fu tian", "福田" }, { "fu tian qu", "福田区" }, { "fu tong", "腹痛" }, { "fu tou", "斧头" },
			{ "fu tu", "附图" }, { "fu wa", "福娃" }, { "fu wei", "复位" }, { "fu wei", "抚慰" }, { "fu wen", "符文" }, { "fu wen bu", "符文布" }, { "fu weng", "富翁" },
			{ "fu wo cheng", "俯卧撑" }, { "fu wu", "服务" }, { "fu wu bu", "服务部" }, { "fu wu duan", "服务端" }, { "fu wu dui xiang", "服务对象" }, { "fu wu fei", "服务费" },
			{ "fu wu gong neng", "服务功能" }, { "fu wu gong si", "服务公司" }, { "fu wu hang ye", "服务行业" }, { "fu wu ji gou", "服务机构" }, { "fu wu li nian", "服务理念" },
			{ "fu wu mao yi", "服务贸易" }, { "fu wu nei rong", "服务内容" }, { "fu wu ping tai", "服务平台" }, { "fu wu qi", "服务器" }, { "fu wu qi duan", "服务器端" },
			{ "fu wu qi shang", "服务器上" }, { "fu wu qu", "服务区" }, { "fu wu re xian", "服务热线" }, { "fu wu ren yuan", "服务人员" }, { "fu wu shang", "服务商" },
			{ "fu wu she shi", "服务设施" }, { "fu wu sheng", "服务生" }, { "fu wu shui ping", "服务水平" }, { "fu wu tai", "服务台" }, { "fu wu tai du", "服务态度" },
			{ "fu wu ti xi", "服务体系" }, { "fu wu wai bao", "服务外包" }, { "fu wu xiang mu", "服务项目" }, { "fu wu xing", "服务型" }, { "fu wu xing", "服务性" },
			{ "fu wu ye", "服务业" }, { "fu wu yi shi", "服务意识" }, { "fu wu yuan", "服务员" }, { "fu wu zhan", "服务站" }, { "fu wu zhi liang", "服务质量" },
			{ "fu wu zhong xin", "服务中心" }, { "fu xi", "伏羲" }, { "fu xi", "复习" }, { "fu xian", "浮现" }, { "fu xie", "腹泻" }, { "fu xin", "阜新" },
			{ "fu xing", "复兴" }, { "fu xing", "服刑" }, { "fu xing", "福星" }, { "fu xiu", "腐朽" }, { "fu xuan kuang", "复选框" }, { "fu yan", "敷衍" },
			{ "fu yang", "富阳" }, { "fu yang", "抚养" }, { "fu yang", "阜阳" }, { "fu yao", "服药" }, { "fu ye", "副业" }, { "fu yi", "复议" }, { "fu yi", "服役" },
			{ "fu yi", "辅以" }, { "fu yin", "复印" }, { "fu yin", "福音" }, { "fu yin ji", "复印机" }, { "fu yin jian", "复印件" }, { "fu yong", "复用" },
			{ "fu yong", "服用" }, { "fu you", "妇幼" }, { "fu you", "富有" }, { "fu you", "负有" }, { "fu you", "附有" }, { "fu yu", "富于" }, { "fu yu", "富余" },
			{ "fu yu", "富裕" }, { "fu yu", "负于" }, { "fu yu", "赋予" }, { "fu yuan", "复原" }, { "fu yun", "浮云" }, { "fu za", "复杂" }, { "fu za du", "复杂度" },
			{ "fu za hua", "复杂化" }, { "fu za xing", "复杂性" }, { "fu zai", "伏在" }, { "fu zai", "浮在" }, { "fu zai", "负载" }, { "fu zai", "附在" },
			{ "fu zai jun heng", "负载均衡" }, { "fu zao", "浮躁" }, { "fu ze", "负责" }, { "fu ze ren", "负责人" }, { "fu ze zhi", "负责制" }, { "fu zeng", "附赠" },
			{ "fu zeng zhang", "负增长" }, { "fu zhai", "负债" }, { "fu zhang", "付账" }, { "fu zhang", "腹胀" }, { "fu zhe", "扶着" }, { "fu zheng", "扶正" },
			{ "fu zhi", "副职" }, { "fu zhi", "复制" }, { "fu zhi", "扶植" }, { "fu zhi", "福祉" }, { "fu zhi", "肤质" }, { "fu zhi", "赋值" }, { "fu zhi dao", "复制到" },
			{ "fu zhong", "浮肿" }, { "fu zhong", "腹中" }, { "fu zhong", "负重" }, { "fu zhong", "附中" }, { "fu zhou", "抚州" }, { "fu zhou", "福州" },
			{ "fu zhou", "符咒" }, { "fu zhou shi", "福州市" }, { "fu zhu", "付诸" }, { "fu zhu", "扶住" }, { "fu zhu", "扶助" }, { "fu zhu", "辅助" },
			{ "fu zhuang", "服装" }, { "fu zhuang dian", "服装店" }, { "fu zhuang she ji", "服装设计" }, { "fu zhuo", "附着" }, { "fu zi", "夫子" }, { "fu zi", "斧子" },
			{ "fu zi", "父子" }, { "fu zong", "副总" }, { "fu zu", "富足" }, { "fu zuo", "辅佐" }, { "fu zuo yong", "副作用" }, { "ga", "伽" }, { "ga", "咖" },
			{ "ga", "嘎" }, { "ga", "噶" }, { "ga", "夹" }, { "ga", "尕" }, { "ga", "尜" }, { "ga", "尬" }, { "ga", "旮" }, { "ga", "轧" }, { "ga", "钆" },
			{ "ga ga", "嘎嘎" }, { "ga la", "旮旯" }, { "ga li", "咖喱" }, { "gai", "丐" }, { "gai", "乢" }, { "gai", "垓" }, { "gai", "峐" }, { "gai", "戤" },
			{ "gai", "改" }, { "gai", "概" }, { "gai", "槪" }, { "gai", "溉" }, { "gai", "漑" }, { "gai", "瓂" }, { "gai", "盖" }, { "gai", "祴" }, { "gai", "芥" },
			{ "gai", "荄" }, { "gai", "葢" }, { "gai", "蓋" }, { "gai", "該" }, { "gai", "该" }, { "gai", "豥" }, { "gai", "賅" }, { "gai", "賌" }, { "gai", "赅" },
			{ "gai", "鈣" }, { "gai", "钙" }, { "gai", "陔" }, { "gai an", "该案" }, { "gai ban", "改版" }, { "gai ban", "盖板" }, { "gai bang", "丐帮" },
			{ "gai bao", "该报" }, { "gai bian", "改变" }, { "gai bian", "改编" }, { "gai bian zi", "改编自" }, { "gai bian zi ji", "改变自己" }, { "gai bing", "该病" },
			{ "gai bu gai", "该不该" }, { "gai bu liao", "改不了" }, { "gai chang", "该厂" }, { "gai che", "该车" }, { "gai cheng", "改成" }, { "gai cheng", "改称" },
			{ "gai chu", "该处" }, { "gai ci", "盖茨" }, { "gai cun", "该村" }, { "gai dao", "改到" }, { "gai dao", "改道" }, { "gai de", "改得" }, { "gai di qu", "该地区" },
			{ "gai dian", "该店" }, { "gai diao", "改掉" }, { "gai dong", "改动" }, { "gai dui", "该队" }, { "gai fa", "该法" }, { "gai fang zi", "盖房子" },
			{ "gai gai", "改改" }, { "gai ge", "改个" }, { "gai ge", "改革" }, { "gai ge chuang xin", "改革创新" }, { "gai ge fa zhan", "改革发展" },
			{ "gai ge fang an", "改革方案" }, { "gai ge kai fang", "改革开放" }, { "gai ge shi dian", "改革试点" }, { "gai gong si", "该公司" }, { "gai gu", "该股" },
			{ "gai guan", "改观" }, { "gai guo", "改过" }, { "gai guo", "盖过" }, { "gai guo", "该国" }, { "gai hang", "改行" }, { "gai hang", "该行" },
			{ "gai hao", "改好" }, { "gai hui", "改回" }, { "gai ji", "该机" }, { "gai jian", "改建" }, { "gai jin", "改进" }, { "gai ju", "该剧" }, { "gai ju", "该局" },
			{ "gai kou", "改口" }, { "gai kuan", "改款" }, { "gai kuan", "该款" }, { "gai kuang", "概况" }, { "gai kuo", "概括" }, { "gai kuo jian", "改扩建" },
			{ "gai lei", "该类" }, { "gai liang", "改良" }, { "gai lou", "盖楼" }, { "gai lun", "概论" }, { "gai lv", "概率" }, { "gai mao", "盖帽" },
			{ "gai ming", "改名" }, { "gai ming zi", "改名字" }, { "gai nian", "概念" }, { "gai nian che", "概念车" }, { "gai nian gu", "概念股" }, { "gai pian", "该片" },
			{ "gai qi ye", "该企业" }, { "gai qian", "改签" }, { "gai qu", "该区" }, { "gai qu", "该去" }, { "gai ru he", "该如何" }, { "gai ruan jian", "该软件" },
			{ "gai shan", "改善" }, { "gai shan shui mian", "改善睡眠" }, { "gai shang", "盖上" }, { "gai sheng", "该省" }, { "gai shi", "盖世" }, { "gai shi", "该市" },
			{ "gai shi", "该是" }, { "gai shu", "概述" }, { "gai shu", "该书" }, { "gai shuo", "该说" }, { "gai si", "该死" }, { "gai suan", "概算" },
			{ "gai tian", "改天" }, { "gai tou huan mian", "改头换面" }, { "gai wan", "改完" }, { "gai wei", "改为" }, { "gai wen", "该文" }, { "gai wen jian", "该文件" },
			{ "gai xian", "该县" }, { "gai xiang", "该项" }, { "gai xiang mu", "该项目" }, { "gai xiao", "该校" }, { "gai xie", "改写" }, { "gai xing", "改性" },
			{ "gai yao", "概要" }, { "gai yong", "改用" }, { "gai yong hu", "该用户" }, { "gai you", "该有" }, { "gai yuan", "该院" }, { "gai zai", "盖在" },
			{ "gai zao", "改造" }, { "gai zao cheng", "改造成" }, { "gai zao gong cheng", "改造工程" }, { "gai zen me", "该怎么" }, { "gai zen me ban", "该怎么办" },
			{ "gai zen me zuo", "该怎么做" }, { "gai zen yang", "该怎样" }, { "gai zhang", "盖章" }, { "gai zhe", "盖着" }, { "gai zhen", "该镇" }, { "gai zheng", "改正" },
			{ "gai zhi", "改制" }, { "gai zhi", "钙质" }, { "gai zhu", "盖住" }, { "gai zhuang", "改装" }, { "gai zi", "盖子" }, { "gai zu", "改组" }, { "gai zuo", "该做" },
			{ "gan", "乾" }, { "gan", "凎" }, { "gan", "咁" }, { "gan", "坩" }, { "gan", "尴" }, { "gan", "尷" }, { "gan", "干" }, { "gan", "幹" }, { "gan", "感" },
			{ "gan", "擀" }, { "gan", "敢" }, { "gan", "旰" }, { "gan", "杆" }, { "gan", "柑" }, { "gan", "桿" }, { "gan", "橄" }, { "gan", "泔" }, { "gan", "淦" },
			{ "gan", "漧" }, { "gan", "澉" }, { "gan", "灨" }, { "gan", "玕" }, { "gan", "玵" }, { "gan", "甘" }, { "gan", "疳" }, { "gan", "皯" }, { "gan", "盰" },
			{ "gan", "矸" }, { "gan", "秆" }, { "gan", "稈" }, { "gan", "竿" }, { "gan", "笴" }, { "gan", "筸" }, { "gan", "簳" }, { "gan", "紺" }, { "gan", "绀" },
			{ "gan", "肝" }, { "gan", "苷" }, { "gan", "詌" }, { "gan", "贛" }, { "gan", "赣" }, { "gan", "赶" }, { "gan", "趕" }, { "gan", "酐" }, { "gan", "骭" },
			{ "gan ai", "肝癌" }, { "gan bei", "干杯" }, { "gan bing", "肝病" }, { "gan bu", "干部" }, { "gan bu dui wu", "干部队伍" }, { "gan bu gan", "敢不敢" },
			{ "gan bu qun zhong", "干部群众" }, { "gan bu shang", "赶不上" }, { "gan bu zhi gong", "干部职工" }, { "gan cai", "干菜" }, { "gan cao", "甘草" },
			{ "gan chao", "赶超" }, { "gan chu", "干出" }, { "gan chu", "感触" }, { "gan chu", "赶出" }, { "gan cui", "干脆" }, { "gan dan", "肝胆" }, { "gan dao", "干道" },
			{ "gan dao", "感到" }, { "gan dao", "赶到" }, { "gan dao hen", "感到很" }, { "gan de", "干得" }, { "gan de", "干的" }, { "gan dian", "干点" },
			{ "gan diao", "干掉" }, { "gan die", "干爹" }, { "gan dong", "感动" }, { "gan en", "感恩" }, { "gan en jie", "感恩节" }, { "gan fu", "赶赴" },
			{ "gan ga", "尴尬" } };
};
