package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN50 {
	public static String[][] pl = { { "wu liu guan li", "物流管理" }, { "wu liu qi ye", "物流企业" }, { "wu liu ye", "物流业" }, { "wu liu zhong xin", "物流中心" },
			{ "wu long", "乌龙" }, { "wu long cha", "乌龙茶" }, { "wu lou", "五楼" }, { "wu lu", "无路" }, { "wu lu mu qi", "乌鲁木齐" }, { "wu lun", "无论" },
			{ "wu lun ru he", "无论如何" }, { "wu ma", "无码" }, { "wu mao", "五毛" }, { "wu mei", "妩媚" }, { "wu mei", "物美" }, { "wu mei jia lian", "物美价廉" },
			{ "wu men", "无门" }, { "wu mian", "屋面" }, { "wu mian", "无眠" }, { "wu mie", "污蔑" }, { "wu mie", "诬蔑" }, { "wu ming", "五名" }, { "wu ming", "无名" },
			{ "wu ming zhi", "无名指" }, { "wu mou", "吴某" }, { "wu nai", "无奈" }, { "wu nei", "屋内" }, { "wu neng", "无能" }, { "wu neng wei li", "无能为力" },
			{ "wu ni", "污泥" }, { "wu nian", "五年" }, { "wu nian ji", "五年级" }, { "wu nian lai", "五年来" }, { "wu nian nei", "五年内" }, { "wu nong", "务农" },
			{ "wu nv", "舞女" }, { "wu pai", "无派" }, { "wu pan", "误判" }, { "wu pin", "物品" }, { "wu po", "巫婆" }, { "wu qi", "屋企" }, { "wu qi", "无期" },
			{ "wu qi", "武器" }, { "wu qi", "雾气" }, { "wu qi tu xing", "无期徒刑" }, { "wu qi zhuang bei", "武器装备" }, { "wu qian", "五千" }, { "wu qian", "无钱" },
			{ "wu qian", "无铅" }, { "wu qing", "无情" }, { "wu qiong", "无穷" }, { "wu qiong wu jin", "无穷无尽" }, { "wu qiu", "务求" }, { "wu qu", "无趣" },
			{ "wu qu", "舞曲" }, { "wu qu", "误区" }, { "wu quan", "无权" }, { "wu quan", "物权" }, { "wu quan fa", "物权法" }, { "wu ran", "污染" },
			{ "wu ran fang zhi", "污染防治" }, { "wu ran huan jing", "污染环境" }, { "wu ran wu", "污染物" }, { "wu ran yuan", "污染源" }, { "wu ran zhi li", "污染治理" },
			{ "wu rao", "勿扰" }, { "wu ren", "五人" }, { "wu ren", "无人" }, { "wu ren he", "无任何" }, { "wu ren ji", "无人机" }, { "wu ren wei", "误认为" },
			{ "wu ren wen jin", "无人问津" }, { "wu ren zi di", "误人子弟" }, { "wu ri", "五日" }, { "wu ru", "侮辱" }, { "wu ru", "污辱" }, { "wu ru", "误入" },
			{ "wu san gui", "吴三桂" }, { "wu se", "五色" }, { "wu se", "无色" }, { "wu se", "物色" }, { "wu sha", "误杀" }, { "wu shan", "巫山" }, { "wu shang", "无上" },
			{ "wu shang", "误伤" }, { "wu sheng", "无声" }, { "wu sheng wu xi", "无声无息" }, { "wu shi", "五十" }, { "wu shi", "务实" }, { "wu shi", "巫师" },
			{ "wu shi", "无事" }, { "wu shi", "无视" }, { "wu shi", "武士" }, { "wu shi duo", "五十多" }, { "wu shi nian dai", "五十年代" }, { "wu shi ren fei", "物是人非" },
			{ "wu shi sui", "五十岁" }, { "wu shi wan", "五十万" }, { "wu shi wu ke", "无时无刻" }, { "wu shu", "巫术" }, { "wu shu", "无数" }, { "wu shu", "武术" },
			{ "wu shu ci", "无数次" }, { "wu shuang", "无双" }, { "wu shui", "午睡" }, { "wu shui", "无水" }, { "wu shui", "污水" }, { "wu shui chu li", "污水处理" },
			{ "wu si", "五四" }, { "wu si", "无私" }, { "wu si feng xian", "无私奉献" }, { "wu song", "武松" }, { "wu sui", "五岁" }, { "wu sun", "无损" },
			{ "wu suo", "无所" }, { "wu suo bu neng", "无所不能" }, { "wu suo bu zai", "无所不在" }, { "wu suo shi cong", "无所适从" }, { "wu suo shi shi", "无所事事" },
			{ "wu suo wei", "无所谓" }, { "wu tai", "舞台" }, { "wu tai ju", "舞台剧" }, { "wu tai shan", "五台山" }, { "wu teng lan", "武藤兰" }, { "wu ti", "无题" },
			{ "wu ti", "物体" }, { "wu ti tou di", "五体投地" }, { "wu tian", "五天" }, { "wu tiao", "五条" }, { "wu tiao jian", "无条件" }, { "wu ting", "舞厅" },
			{ "wu tong", "梧桐" }, { "wu tong shu", "梧桐树" }, { "wu tou", "无头" }, { "wu tuo bang", "乌托邦" }, { "wu wai", "屋外" }, { "wu wan", "五万" },
			{ "wu wang", "吴王" }, { "wu wang", "无望" }, { "wu wei", "五位" }, { "wu wei", "五味" }, { "wu wei", "无为" }, { "wu wei", "无味" }, { "wu wei", "无畏" },
			{ "wu wei", "无谓" }, { "wu wei bu zhi", "无微不至" }, { "wu wen nong mo", "舞文弄墨" }, { "wu wu", "呜呜" }, { "wu wu", "无误" }, { "wu wu ran", "无污染" },
			{ "wu wu wu", "呜呜呜" }, { "wu xi", "唔系" }, { "wu xi", "无锡" }, { "wu xi shi", "无锡市" }, { "wu xia", "无暇" }, { "wu xia", "无瑕" }, { "wu xia", "武侠" },
			{ "wu xia xiao shuo", "武侠小说" }, { "wu xian", "无线" }, { "wu xian", "无限" }, { "wu xian", "诬陷" }, { "wu xian dian", "无线电" }, { "wu xian qi", "无限期" },
			{ "wu xian shang wang", "无线上网" }, { "wu xian tong xin", "无线通信" }, { "wu xian wang ka", "无线网卡" }, { "wu xian wang luo", "无线网络" },
			{ "wu xian zhi", "无限制" }, { "wu xiang", "五项" }, { "wu xiao", "无效" }, { "wu xie", "无邪" }, { "wu xie ke ji", "无懈可击" }, { "wu xin", "无心" },
			{ "wu xing", "五星" }, { "wu xing", "五行" }, { "wu xing", "悟性" }, { "wu xing", "无形" }, { "wu xing hong qi", "五星红旗" }, { "wu xing ji", "五星级" },
			{ "wu xing zhong", "无形中" }, { "wu xing zi chan", "无形资产" }, { "wu xiu", "午休" }, { "wu xiu zhi", "无休止" }, { "wu xu", "无序" }, { "wu xu", "无需" },
			{ "wu xu", "无须" }, { "wu xue", "武学" }, { "wu ya", "乌鸦" }, { "wu ya", "无涯" }, { "wu ya zui", "乌鸦嘴" }, { "wu yan", "屋檐" }, { "wu yan", "无烟" },
			{ "wu yan", "无言" }, { "wu yan liu se", "五颜六色" }, { "wu yan yi dui", "无言以对" }, { "wu yan zhang qi", "乌烟瘴气" }, { "wu yan zu", "吴彦祖" },
			{ "wu ye", "午夜" }, { "wu ye", "无业" }, { "wu ye", "物业" }, { "wu ye fei", "物业费" }, { "wu ye fu wu", "物业服务" }, { "wu ye gong si", "物业公司" },
			{ "wu ye guan li", "物业管理" }, { "wu ye shui", "物业税" }, { "wu yi", "五一" }, { "wu yi", "吴仪" }, { "wu yi", "无一" }, { "wu yi", "无以" },
			{ "wu yi", "无异" }, { "wu yi", "无意" }, { "wu yi", "无疑" }, { "wu yi", "无益" }, { "wu yi", "无遗" }, { "wu yi", "武夷" }, { "wu yi", "武艺" },
			{ "wu yi chang jia", "五一长假" }, { "wu yi jian", "无意间" }, { "wu yi jie", "五一节" }, { "wu yi qi jian", "五一期间" }, { "wu yi shan", "武夷山" },
			{ "wu yi shi", "无意识" }, { "wu yi yi", "无意义" }, { "wu yin", "无垠" }, { "wu ying", "无影" }, { "wu ying wu zong", "无影无踪" }, { "wu yong", "无用" },
			{ "wu yong zhi yi", "毋庸置疑" }, { "wu you", "无忧" }, { "wu you suo zhi", "物有所值" }, { "wu you wu lv", "无忧无虑" }, { "wu yu", "无欲" }, { "wu yu", "无语" },
			{ "wu yu", "物欲" }, { "wu yu", "物语" }, { "wu yu lun bi", "无与伦比" }, { "wu yu sen", "吴宇森" }, { "wu yuan", "五元" }, { "wu yuan", "婺源" },
			{ "wu yuan", "无缘" }, { "wu yuan wu gu", "无缘无故" }, { "wu yuan wu hui", "无怨无悔" }, { "wu yue", "五岳" }, { "wu yue", "五月" }, { "wu yue", "吴越" },
			{ "wu yue fen", "五月份" }, { "wu yue tian", "五月天" }, { "wu yun", "乌云" }, { "wu zang", "五脏" }, { "wu ze tian", "武则天" }, { "wu zhang ai", "无障碍" },
			{ "wu zhe", "五折" }, { "wu zhe", "捂着" }, { "wu zhe", "舞者" }, { "wu zhen", "乌镇" }, { "wu zhen", "误诊" }, { "wu zhen yu", "吴镇宇" },
			{ "wu zheng", "无证" }, { "wu zheng", "物证" }, { "wu zhi", "五指" }, { "wu zhi", "唔知" }, { "wu zhi", "无知" }, { "wu zhi", "物质" },
			{ "wu zhi ji chu", "物质基础" }, { "wu zhi jing", "无止境" }, { "wu zhi sheng huo", "物质生活" }, { "wu zhi wen ming", "物质文明" }, { "wu zhong", "五种" },
			{ "wu zhong", "物种" }, { "wu zhong quan hui", "五中全会" }, { "wu zhong sheng you", "无中生有" }, { "wu zhou", "五洲" }, { "wu zhou", "梧州" },
			{ "wu zhu", "捂住" }, { "wu zhu", "无主" }, { "wu zhu", "无助" }, { "wu zhuang", "武装" }, { "wu zhuang li liang", "武装力量" }, { "wu zhuo", "污浊" },
			{ "wu zi", "伍兹" }, { "wu zi", "屋子" }, { "wu zi", "污渍" }, { "wu zi", "物资" }, { "wu zi", "舞姿" }, { "wu zi li", "屋子里" }, { "wu zi qi", "五子棋" },
			{ "wu zong", "无踪" }, { "wu zong xian", "吴宗宪" }, { "wu zui", "无罪" }, { "xi", "习" }, { "xi", "係" }, { "xi", "俙" }, { "xi", "傒" }, { "xi", "僖" },
			{ "xi", "兮" }, { "xi", "凞" }, { "xi", "匸" }, { "xi", "卌" }, { "xi", "吸" }, { "xi", "呬" }, { "xi", "咥" }, { "xi", "唏" }, { "xi", "喜" },
			{ "xi", "嘻" }, { "xi", "夕" }, { "xi", "奚" }, { "xi", "媳" }, { "xi", "嬉" }, { "xi", "屖" }, { "xi", "屣" }, { "xi", "嶍" }, { "xi", "嶲" },
			{ "xi", "巂" }, { "xi", "巇" }, { "xi", "希" }, { "xi", "席" }, { "xi", "廗" }, { "xi", "徆" }, { "xi", "徙" }, { "xi", "徯" }, { "xi", "忥" },
			{ "xi", "怬" }, { "xi", "恄" }, { "xi", "恓" }, { "xi", "息" }, { "xi", "悉" }, { "xi", "悕" }, { "xi", "惁" }, { "xi", "惜" }, { "xi", "愾" },
			{ "xi", "憘" }, { "xi", "憙" }, { "xi", "戏" }, { "xi", "戯" }, { "xi", "戱" }, { "xi", "戲" }, { "xi", "扱" }, { "xi", "摡" }, { "xi", "昔" },
			{ "xi", "晞" }, { "xi", "晰" }, { "xi", "晳" }, { "xi", "暿" }, { "xi", "曦" }, { "xi", "析" }, { "xi", "枲" }, { "xi", "栖" }, { "xi", "桸" },
			{ "xi", "榽" }, { "xi", "槢" }, { "xi", "樨" }, { "xi", "橀" }, { "xi", "橲" }, { "xi", "檄" }, { "xi", "欯" }, { "xi", "欷" }, { "xi", "歙" },
			{ "xi", "氥" }, { "xi", "汐" }, { "xi", "洗" }, { "xi", "浠" }, { "xi", "淅" }, { "xi", "渓" }, { "xi", "溪" }, { "xi", "漇" }, { "xi", "潝" },
			{ "xi", "潟" }, { "xi", "烯" }, { "xi", "焟" }, { "xi", "煕" }, { "xi", "熂" }, { "xi", "熄" }, { "xi", "熙" }, { "xi", "熹" }, { "xi", "熺" },
			{ "xi", "燨" }, { "xi", "爔" }, { "xi", "牺" }, { "xi", "犀" }, { "xi", "犠" }, { "xi", "犧" }, { "xi", "狶" }, { "xi", "獡" }, { "xi", "玺" },
			{ "xi", "琋" }, { "xi", "璽" }, { "xi", "瓕" }, { "xi", "瘜" }, { "xi", "皙" }, { "xi", "盻" }, { "xi", "睎" }, { "xi", "矽" }, { "xi", "硒" },
			{ "xi", "碏" }, { "xi", "礂" }, { "xi", "禊" }, { "xi", "禧" }, { "xi", "稀" }, { "xi", "穸" }, { "xi", "窸" }, { "xi", "粞" }, { "xi", "系" },
			{ "xi", "細" }, { "xi", "綌" }, { "xi", "緆" }, { "xi", "縰" }, { "xi", "繫" }, { "xi", "纚" }, { "xi", "细" }, { "xi", "羲" }, { "xi", "習" },
			{ "xi", "翕" }, { "xi", "肸" }, { "xi", "腊" }, { "xi", "膝" }, { "xi", "舄" }, { "xi", "舾" }, { "xi", "茜" }, { "xi", "莃" }, { "xi", "莔" },
			{ "xi", "菥" }, { "xi", "葈" }, { "xi", "葸" }, { "xi", "蒠" }, { "xi", "蓆" }, { "xi", "蓰" }, { "xi", "蔇" }, { "xi", "蕮" }, { "xi", "虩" },
			{ "xi", "蜤" }, { "xi", "蜥" }, { "xi", "蝷" }, { "xi", "螅" }, { "xi", "螇" }, { "xi", "蟋" }, { "xi", "蟢" }, { "xi", "蠵" }, { "xi", "衋" },
			{ "xi", "袭" }, { "xi", "裼" }, { "xi", "襲" }, { "xi", "西" }, { "xi", "覡" }, { "xi", "覤" }, { "xi", "觋" }, { "xi", "觿" }, { "xi", "諰" },
			{ "xi", "謵" }, { "xi", "譆" }, { "xi", "谿" }, { "xi", "豨" }, { "xi", "豯" }, { "xi", "貕" }, { "xi", "赩" }, { "xi", "蹊" }, { "xi", "蹝" },
			{ "xi", "郋" }, { "xi", "郗" }, { "xi", "郤" }, { "xi", "鄎" }, { "xi", "酅" }, { "xi", "醯" }, { "xi", "釳" }, { "xi", "釸" }, { "xi", "鈒" },
			{ "xi", "銑" }, { "xi", "錫" }, { "xi", "鎴" }, { "xi", "鑴" }, { "xi", "铣" }, { "xi", "锡" }, { "xi", "闟" }, { "xi", "阋" }, { "xi", "隙" },
			{ "xi", "隰" }, { "xi", "雟" }, { "xi", "霫" }, { "xi", "飁" }, { "xi", "餼" }, { "xi", "饩" }, { "xi", "騱" }, { "xi", "騽" }, { "xi", "驨" },
			{ "xi", "鬩" }, { "xi", "鯑" }, { "xi", "鰓" }, { "xi", "鰼" }, { "xi", "鱚" }, { "xi", "鵗" }, { "xi", "鸂" }, { "xi", "黖" }, { "xi", "鼰" },
			{ "xi", "鼳" }, { "xi", "鼷" }, { "xi ai", "喜爱" }, { "xi an", "西安" }, { "xi an", "西岸" }, { "xi an shi", "西安市" }, { "xi ban ya", "西班牙" },
			{ "xi ban ya ren", "西班牙人" }, { "xi ban ya yu", "西班牙语" }, { "xi bao", "细胞" }, { "xi bao diao wang", "细胞凋亡" }, { "xi bao mo", "细胞膜" },
			{ "xi bei", "西北" }, { "xi bei bu", "西北部" }, { "xi bei di qu", "西北地区" }, { "xi bian", "西边" }, { "xi bo", "稀薄" }, { "xi bo li ya", "西伯利亚" },
			{ "xi bu", "西部" }, { "xi bu di qu", "西部地区" }, { "xi can", "西餐" }, { "xi can ting", "西餐厅" }, { "xi ce", "西侧" }, { "xi chang", "细长" },
			{ "xi chang", "西昌" }, { "xi che", "洗车" }, { "xi chen qi", "吸尘器" }, { "xi cheng", "戏称" }, { "xi cheng", "西城" }, { "xi cheng qu", "西城区" },
			{ "xi chu wang wai", "喜出望外" }, { "xi ci", "西祠" }, { "xi cun", "西村" }, { "xi dan", "西单" }, { "xi de", "洗得" }, { "xi de", "西德" },
			{ "xi deng", "熄灯" }, { "xi di", "洗涤" }, { "xi di ji", "洗涤剂" }, { "xi dian", "西点" }, { "xi diao", "洗掉" }, { "xi du", "吸毒" }, { "xi er", "希尔" },
			{ "xi er dun", "希尔顿" }, { "xi fa", "洗发" }, { "xi fa shui", "洗发水" }, { "xi fan", "稀饭" }, { "xi fang", "西方" }, { "xi fang guo jia", "西方国家" },
			{ "xi fang ren", "西方人" }, { "xi fang wen hua", "西方文化" }, { "xi fen", "戏份" }, { "xi fen", "细分" }, { "xi fen shi chang", "细分市场" },
			{ "xi feng", "西风" }, { "xi fu", "吸附" }, { "xi fu", "媳妇" }, { "xi fu", "西服" }, { "xi gai", "膝盖" }, { "xi gan jing", "洗干净" }, { "xi ge", "洗个" },
			{ "xi gu", "硒鼓" }, { "xi gua", "西瓜" }, { "xi guan", "习惯" }, { "xi guan", "吸管" }, { "xi guan", "西关" }, { "xi guan jie", "膝关节" },
			{ "xi guan xing", "习惯性" }, { "xi guo", "洗过" }, { "xi ha", "嘻哈" }, { "xi hai an", "西海岸" }, { "xi han", "稀罕" }, { "xi han", "西汉" },
			{ "xi hao", "喜好" }, { "xi hao", "洗好" }, { "xi hong shi", "西红柿" }, { "xi hu", "西湖" }, { "xi hua", "细化" }, { "xi hua", "西化" }, { "xi huan", "喜欢" },
			{ "xi huan chi", "喜欢吃" }, { "xi huan ni", "喜欢你" }, { "xi huan shen me", "喜欢什么" }, { "xi huan ting", "喜欢听" }, { "xi huan zi ji", "喜欢自己" },
			{ "xi huo", "喜获" }, { "xi huo", "熄火" }, { "xi ji", "希冀" }, { "xi ji", "袭击" }, { "xi jia", "西甲" }, { "xi jian", "席间" }, { "xi jiang", "西江" },
			{ "xi jiao", "洗脚" }, { "xi jiao", "西郊" }, { "xi jie", "希捷" }, { "xi jie", "细节" }, { "xi jie", "西街" }, { "xi jin ping", "习近平" },
			{ "xi jing", "洗净" }, { "xi jiu", "喜酒" }, { "xi ju", "喜剧" }, { "xi ju", "戏剧" }, { "xi ju pian", "喜剧片" }, { "xi ju xing", "戏剧性" },
			{ "xi juan", "席卷" }, { "xi jun", "细菌" }, { "xi jun gan ran", "细菌感染" }, { "xi jun xing", "细菌性" }, { "xi kan", "细看" }, { "xi ku", "西裤" },
			{ "xi la", "希腊" }, { "xi la ke", "希拉克" }, { "xi la li", "希拉里" }, { "xi lai", "袭来" }, { "xi le", "吸了" }, { "xi le", "喜乐" }, { "xi li", "戏里" },
			{ "xi li", "洗礼" }, { "xi li", "犀利" }, { "xi li", "系里" }, { "xi li", "西里" }, { "xi li hu tu", "稀里糊涂" }, { "xi li hua la", "稀里哗啦" },
			{ "xi lian", "洗脸" }, { "xi lie", "系列" }, { "xi lie chan pin", "系列产品" }, { "xi lie huo dong", "系列活动" }, { "xi lie zhi", "系列之" }, { "xi lin", "西林" },
			{ "xi liu", "溪流" }, { "xi lu", "西路" }, { "xi men", "西门" }, { "xi men qing", "西门庆" }, { "xi men zi", "西门子" }, { "xi meng", "西蒙" },
			{ "xi mi", "细密" }, { "xi mian", "西面" }, { "xi mian nai", "洗面奶" }, { "xi mie", "熄灭" }, { "xi na", "吸纳" }, { "xi nan", "西南" },
			{ "xi nan bu", "西南部" }, { "xi nan di qu", "西南地区" }, { "xi nao", "洗脑" }, { "xi nen", "细嫩" }, { "xi ni", "悉尼" }, { "xi ni", "细腻" },
			{ "xi ning", "西宁" }, { "xi niu", "犀牛" }, { "xi nong", "戏弄" }, { "xi nu ai le", "喜怒哀乐" }, { "xi ou", "西欧" }, { "xi pai", "洗牌" }, { "xi pan", "洗盘" },
			{ "xi qi", "习气" }, { "xi qi", "吸气" }, { "xi qi", "稀奇" }, { "xi qi gu guai", "稀奇古怪" }, { "xi qian", "洗钱" }, { "xi qing", "喜庆" }, { "xi qu", "吸取" },
			{ "xi qu", "戏曲" }, { "xi qu", "洗去" }, { "xi qu", "西区" }, { "xi que", "喜鹊" }, { "xi que", "稀缺" }, { "xi ren", "喜人" }, { "xi ren", "袭人" },
			{ "xi ri", "昔日" }, { "xi rou", "息肉" }, { "xi ru", "吸入" }, { "xi shan", "西山" }, { "xi shang", "席上" }, { "xi shao", "稀少" }, { "xi sheng", "牺牲" },
			{ "xi sheng pin", "牺牲品" }, { "xi shi", "吸食" }, { "xi shi", "喜事" }, { "xi shi", "稀释" }, { "xi shi", "西式" }, { "xi shi", "西施" }, { "xi shou", "吸收" },
			{ "xi shou", "洗手" }, { "xi shou jian", "洗手间" }, { "xi shu", "悉数" }, { "xi shu", "洗漱" }, { "xi shu", "稀疏" }, { "xi shu", "系数" }, { "xi shu", "细数" },
			{ "xi shua", "洗刷" }, { "xi shua shua", "洗刷刷" }, { "xi shuai", "蟋蟀" }, { "xi shuang ban na", "西双版纳" }, { "xi shui", "吸水" }, { "xi shui", "戏水" },
			{ "xi shui", "溪水" }, { "xi shun", "吸吮" }, { "xi shuo", "戏说" }, { "xi shuo", "细说" }, { "xi si", "西斯" }, { "xi su", "习俗" }, { "xi sui", "细碎" },
			{ "xi tang", "喜糖" }, { "xi tang", "西塘" }, { "xi te le", "希特勒" }, { "xi ti", "习题" }, { "xi tian", "西天" }, { "xi tong", "系统" },
			{ "xi tong gong cheng", "系统工程" }, { "xi tong guan li", "系统管理" }, { "xi tong hua", "系统化" }, { "xi tong huan yuan", "系统还原" },
			{ "xi tong ji cheng", "系统集成" }, { "xi tong pan", "系统盘" }, { "xi tong qi dong", "系统启动" }, { "xi tong ruan jian", "系统软件" },
			{ "xi tong she ji", "系统设计" }, { "xi tong ti shi", "系统提示" }, { "xi tong wei hu", "系统维护" }, { "xi tong wen jian", "系统文件" },
			{ "xi tong xing", "系统性" }, { "xi tong xing neng", "系统性能" }, { "xi tong zi yuan", "系统资源" }, { "xi tou", "洗头" }, { "xi tu", "稀土" },
			{ "xi wan", "洗完" }, { "xi wan", "洗碗" }, { "xi wang", "希望" }, { "xi wang da jia", "希望大家" }, { "xi wang gong cheng", "希望工程" },
			{ "xi wang neng gou", "希望能够" }, { "xi wang xiao xue", "希望小学" }, { "xi wei", "席位" }, { "xi wei", "细微" }, { "xi wen", "细纹" },
			{ "xi wen le jian", "喜闻乐见" }, { "xi wu", "习武" }, { "xi xi", "兮兮" }, { "xi xi", "嘻嘻" }, { "xi xi", "嬉戏" }, { "xi xi", "洗洗" }, { "xi xi", "细细" },
			{ "xi xi", "西溪" }, { "xi xi", "西西" }, { "xi xi de", "细细的" }, { "xi xi ha ha", "嘻嘻哈哈" }, { "xi xi li", "西西里" }, { "xi xi rang rang", "熙熙攘攘" },
			{ "xi xi xi", "嘻嘻嘻" }, { "xi xi xiang guan", "息息相关" }, { "xi xia", "西夏" }, { "xi xian", "西线" }, { "xi xiang", "细想" }, { "xi xiang", "西乡" },
			{ "xi xiao", "嬉笑" }, { "xi xiao", "细小" }, { "xi xin", "悉心" }, { "xi xin", "细心" }, { "xi xin yan jiu", "喜新厌旧" }, { "xi xing", "习性" },
			{ "xi xing", "西行" }, { "xi xu", "唏嘘" }, { "xi xue", "吸血" }, { "xi xue", "戏谑" }, { "xi xue gui", "吸血鬼" }, { "xi xun", "喜讯" }, { "xi ya", "西亚" },
			{ "xi ya tu", "西雅图" }, { "xi yan", "吸烟" }, { "xi yang", "夕阳" }, { "xi yang", "西洋" }, { "xi yao", "西药" }, { "xi yi", "洗衣" }, { "xi yi", "蜥蜴" },
			{ "xi yi", "西医" }, { "xi yi fen", "洗衣粉" }, { "xi yi fu", "洗衣服" }, { "xi yi ji", "洗衣机" }, { "xi yi wei chang", "习以为常" }, { "xi yin", "吸引" },
			{ "xi yin li", "吸引力" }, { "xi yin ren", "吸引人" }, { "xi yin wai zi", "吸引外资" }, { "xi yin zhu", "吸引住" }, { "xi ying", "喜迎" }, { "xi you", "稀有" },
			{ "xi you", "西游" }, { "xi you ji", "西游记" }, { "xi yu", "洗浴" }, { "xi yu", "细语" }, { "xi yu", "细雨" }, { "xi yu", "西域" }, { "xi yuan", "戏院" },
			{ "xi yuan", "西苑" }, { "xi yue", "喜悦" }, { "xi zang", "西藏" }, { "xi zao", "洗澡" }, { "xi ze", "细则" }, { "xi zhan", "西站" }, { "xi zhen", "溪镇" },
			{ "xi zhi", "细致" }, { "xi zhi", "西至" }, { "xi zhi men", "西直门" }, { "xi zhong", "戏中" }, { "xi zhou", "西周" }, { "xi zhu ren", "系主任" },
			{ "xi zhuang", "西装" }, { "xi zi", "席子" }, { "xi zi", "戏子" }, { "xi zi", "西子" }, { "xi zuo", "习作" }, { "xia", "下" }, { "xia", "侠" }, { "xia", "俠" },
			{ "xia", "匣" }, { "xia", "厦" }, { "xia", "吓" }, { "xia", "呷" }, { "xia", "唬" }, { "xia", "嚇" }, { "xia", "圷" }, { "xia", "夏" }, { "xia", "峡" },
			{ "xia", "峽" }, { "xia", "廈" }, { "xia", "徦" }, { "xia", "昰" }, { "xia", "暇" }, { "xia", "柙" }, { "xia", "梺" }, { "xia", "欱" }, { "xia", "浹" },
			{ "xia", "烚" }, { "xia", "煆" }, { "xia", "狎" }, { "xia", "狭" }, { "xia", "狹" }, { "xia", "珨" }, { "xia", "瑕" }, { "xia", "瞎" }, { "xia", "硖" },
			{ "xia", "硤" }, { "xia", "碬" }, { "xia", "祫" }, { "xia", "笚" }, { "xia", "縖" }, { "xia", "罅" }, { "xia", "舝" }, { "xia", "舺" }, { "xia", "芐" },
			{ "xia", "蕸" }, { "xia", "虾" }, { "xia", "蝦" }, { "xia", "螛" }, { "xia", "諕" }, { "xia", "謑" }, { "xia", "谺" }, { "xia", "赮" }, { "xia", "轄" },
			{ "xia", "辖" }, { "xia", "遐" }, { "xia", "鍜" }, { "xia", "鏬" }, { "xia", "閜" }, { "xia", "陜" }, { "xia", "霞" }, { "xia", "颬" }, { "xia", "騢" },
			{ "xia", "魻" }, { "xia", "鰕" }, { "xia", "鶷" }, { "xia", "黠" }, { "xia ai", "狭隘" }, { "xia ba", "下吧" }, { "xia ba", "下巴" }, { "xia bai", "瞎掰" },
			{ "xia ban", "下半" }, { "xia ban", "下班" }, { "xia ban chang", "下半场" }, { "xia ban nian", "下半年" }, { "xia ban shen", "下半身" },
			{ "xia bei zi", "下辈子" }, { "xia bi", "下笔" }, { "xia bian", "下边" }, { "xia biao", "下表" }, { "xia bu", "下部" }, { "xia bu lai", "下不来" },
			{ "xia bu liao", "下不了" }, { "xia cai", "瞎猜" }, { "xia ceng", "下层" }, { "xia chang", "下场" }, { "xia chang", "狭长" }, { "xia che", "下车" },
			{ "xia che", "瞎扯" }, { "xia chen", "下沉" }, { "xia chu", "下厨" }, { "xia chuang", "下床" }, { "xia chui", "下垂" }, { "xia ci", "下次" },
			{ "xia ci", "瑕疵" }, { "xia cuo", "下挫" }, { "xia da", "下达" }, { "xia da", "厦大" }, { "xia dan", "下单" }, { "xia dan", "下蛋" }, { "xia dao", "下到" },
			{ "xia dao", "吓倒" }, { "xia dao", "吓到" }, { "xia de", "下的" }, { "xia de", "吓得" }, { "xia die", "下跌" }, { "xia ding", "下定" },
			{ "xia ding jue xin", "下定决心" }, { "xia du", "下肚" }, { "xia duan", "下端" }, { "xia fa", "下发" }, { "xia fan", "下凡" }, { "xia fang", "下放" },
			{ "xia fang", "下方" }, { "xia feng", "下风" }, { "xia gang", "下岗" }, { "xia gang gong ren", "下岗工人" }, { "xia gang zhi gong", "下岗职工" },
			{ "xia gao", "瞎搞" }, { "xia ge", "下个" }, { "xia ge yue", "下个月" }, { "xia gong fu", "下工夫" }, { "xia gu", "峡谷" }, { "xia guang", "霞光" },
			{ "xia gui", "下跪" }, { "xia guo", "下过" }, { "xia guo", "下锅" }, { "xia hai", "下海" }, { "xia he", "下颌" }, { "xia hou", "夏侯" }, { "xia hu", "吓唬" },
			{ "xia hua", "下滑" }, { "xia hua", "厦华" }, { "xia hua xian", "下划线" }, { "xia huai", "吓坏" }, { "xia hui", "下回" }, { "xia ji", "下级" },
			{ "xia ji", "夏季" }, { "xia jia", "下家" }, { "xia jia", "下架" }, { "xia jian", "下贱" }, { "xia jiang", "下降" }, { "xia jie", "下届" }, { "xia ke", "下课" },
			{ "xia ke", "侠客" }, { "xia la", "下拉" }, { "xia la cai dan", "下拉菜单" }, { "xia la kuang", "下拉框" }, { "xia lai", "下来" }, { "xia le", "下了" },
			{ "xia le", "吓了" }, { "xia le", "瞎了" }, { "xia li", "夏利" }, { "xia lian", "下联" }, { "xia lie", "下列" }, { "xia ling", "下令" },
			{ "xia ling ying", "夏令营" }, { "xia liu", "下流" }, { "xia lou", "下楼" }, { "xia luo", "下落" }, { "xia luo bu ming", "下落不明" }, { "xia ma", "下马" },
			{ "xia mang", "瞎忙" }, { "xia men", "厦门" }, { "xia men da xue", "厦门大学" }, { "xia men shi", "厦门市" }, { "xia mi", "虾米" }, { "xia mian", "下面" },
			{ "xia pao", "吓跑" }, { "xia po", "下坡" }, { "xia pu", "下铺" }, { "xia pu", "夏普" }, { "xia qi", "下期" }, { "xia qi", "下棋" }, { "xia qu", "下去" },
			{ "xia qu", "辖区" }, { "xia ren", "吓人" }, { "xia ren", "虾仁" }, { "xia ri", "夏日" }, { "xia sha", "下沙" }, { "xia shan", "下山" }, { "xia she", "下设" },
			{ "xia shen", "下身" }, { "xia shou", "下手" }, { "xia shu", "下属" }, { "xia shu", "下述" }, { "xia shui", "下水" }, { "xia shui dao", "下水道" },
			{ "xia shuo", "瞎说" }, { "xia si", "吓死" }, { "xia ta", "下榻" }, { "xia tai", "下台" }, { "xia tan", "下探" }, { "xia ti", "下体" }, { "xia tian", "夏天" },
			{ "xia tiao", "下调" }, { "xia tu", "下图" }, { "xia wa", "夏娃" }, { "xia wan", "下完" }, { "xia wei yi", "夏威夷" }, { "xia wen", "下文" },
			{ "xia wu", "下午" }, { "xia wu cha", "下午茶" } };
};
