package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN45 {
	public static String[][] pl = { { "suan qi", "算起" }, { "suan qi lai", "算起来" }, { "suan shang", "算上" }, { "suan shen me", "算什么" }, { "suan shi", "算是" },
			{ "suan shu", "算数" }, { "suan shu", "算术" }, { "suan suan", "算算" }, { "suan suan", "酸酸" }, { "suan tian", "酸甜" }, { "suan tian ku la", "酸甜苦辣" },
			{ "suan tong", "酸痛" }, { "suan wei", "酸味" }, { "suan wo", "算我" }, { "suan xing", "酸性" }, { "suan zhang", "算账" }, { "suan zuo", "算作" },
			{ "sui", "倠" }, { "sui", "哸" }, { "sui", "埣" }, { "sui", "夊" }, { "sui", "娞" }, { "sui", "尿" }, { "sui", "岁" }, { "sui", "挼" }, { "sui", "旞" },
			{ "sui", "檖" }, { "sui", "歲" }, { "sui", "歳" }, { "sui", "毸" }, { "sui", "浽" }, { "sui", "滖" }, { "sui", "濉" }, { "sui", "瀡" }, { "sui", "燧" },
			{ "sui", "璲" }, { "sui", "眭" }, { "sui", "睢" }, { "sui", "砕" }, { "sui", "碎" }, { "sui", "祟" }, { "sui", "禭" }, { "sui", "穂" }, { "sui", "穗" },
			{ "sui", "穟" }, { "sui", "粋" }, { "sui", "綏" }, { "sui", "縗" }, { "sui", "繀" }, { "sui", "繐" }, { "sui", "繸" }, { "sui", "绥" }, { "sui", "脺" },
			{ "sui", "荽" }, { "sui", "荾" }, { "sui", "虽" }, { "sui", "襚" }, { "sui", "誶" }, { "sui", "谇" }, { "sui", "賥" }, { "sui", "遂" }, { "sui", "邃" },
			{ "sui", "鏸" }, { "sui", "鐆" }, { "sui", "鐩" }, { "sui", "陏" }, { "sui", "隋" }, { "sui", "随" }, { "sui", "隧" }, { "sui", "隨" }, { "sui", "雖" },
			{ "sui", "髄" }, { "sui", "髓" }, { "sui ban", "岁半" }, { "sui bi", "随笔" }, { "sui bian", "随便" }, { "sui bo zhu liu", "随波逐流" }, { "sui bu", "虽不" },
			{ "sui chu", "随处" }, { "sui chu ke jian", "随处可见" }, { "sui cong", "随从" }, { "sui dao", "隧道" }, { "sui de", "岁的" }, { "sui di", "随地" },
			{ "sui fang", "随访" }, { "sui feng", "随风" }, { "sui feng piao", "随风飘" }, { "sui he", "随和" }, { "sui hou", "随后" }, { "sui ji", "随即" },
			{ "sui ji", "随机" }, { "sui ji shu", "随机数" }, { "sui kou", "随口" }, { "sui le", "碎了" }, { "sui lie", "碎裂" }, { "sui mo", "岁末" },
			{ "sui na nian", "岁那年" }, { "sui ni", "随你" }, { "sui ning", "遂宁" }, { "sui pian", "碎片" }, { "sui ran", "虽然" }, { "sui shao nv", "岁少女" },
			{ "sui shen", "随身" }, { "sui shen ting", "随身听" }, { "sui shen xie dai", "随身携带" }, { "sui sheng ri", "岁生日" }, { "sui shi", "岁时" },
			{ "sui shi", "碎石" }, { "sui shi", "虽是" }, { "sui shi", "随时" }, { "sui shi sui di", "随时随地" }, { "sui shou", "随手" }, { "sui shu", "岁数" },
			{ "sui shuo", "虽说" }, { "sui sui", "岁岁" }, { "sui sui", "碎碎" }, { "sui sui bian bian", "随随便便" }, { "sui tang", "隋唐" }, { "sui tong", "随同" },
			{ "sui wei", "虽未" }, { "sui xiang", "随想" }, { "sui xiao", "虽小" }, { "sui xin", "随心" }, { "sui xin suo yu", "随心所欲" }, { "sui xing", "随性" },
			{ "sui xing", "随行" }, { "sui yi", "虽已" }, { "sui yi", "随意" }, { "sui yi shang", "岁以上" }, { "sui yi xia", "岁以下" }, { "sui yi xing", "随意性" },
			{ "sui you", "虽有" }, { "sui yu er an", "随遇而安" }, { "sui yuan", "随缘" }, { "sui yue", "岁月" }, { "sui zhe", "随着" }, { "sui zhi", "随之" },
			{ "sui zhi er lai", "随之而来" }, { "sui zuo you", "岁左右" }, { "sun", "喰" }, { "sun", "孙" }, { "sun", "孫" }, { "sun", "损" }, { "sun", "損" },
			{ "sun", "搎" }, { "sun", "榫" }, { "sun", "槂" }, { "sun", "潠" }, { "sun", "狲" }, { "sun", "猻" }, { "sun", "笋" }, { "sun", "筍" }, { "sun", "荪" },
			{ "sun", "蓀" }, { "sun", "蕵" }, { "sun", "薞" }, { "sun", "鎨" }, { "sun", "隼" }, { "sun", "飧" }, { "sun hai", "损害" },
			{ "sun hai pei chang", "损害赔偿" }, { "sun hao", "损耗" }, { "sun huai", "损坏" }, { "sun hui", "损毁" }, { "sun ji hai", "孙继海" }, { "sun li", "孙俪" },
			{ "sun nan", "孙楠" }, { "sun nv", "孙女" }, { "sun quan", "孙权" }, { "sun shang", "损伤" }, { "sun shi", "损失" }, { "sun wu kong", "孙悟空" },
			{ "sun xiang", "孙祥" }, { "sun yan zi", "孙燕姿" }, { "sun yi", "损益" }, { "sun yue", "孙悦" }, { "sun zhong shan", "孙中山" }, { "sun zi", "孙子" },
			{ "sun zi bing fa", "孙子兵法" }, { "suo", "傞" }, { "suo", "唆" }, { "suo", "唢" }, { "suo", "嗍" }, { "suo", "嗦" }, { "suo", "嗩" }, { "suo", "娑" },
			{ "suo", "惢" }, { "suo", "所" }, { "suo", "挲" }, { "suo", "摍" }, { "suo", "桫" }, { "suo", "梭" }, { "suo", "溹" }, { "suo", "琐" }, { "suo", "瑣" },
			{ "suo", "睃" }, { "suo", "簑" }, { "suo", "簔" }, { "suo", "索" }, { "suo", "縒" }, { "suo", "縮" }, { "suo", "缩" }, { "suo", "羧" }, { "suo", "莎" },
			{ "suo", "莏" }, { "suo", "葰" }, { "suo", "蓑" }, { "suo", "趖" }, { "suo", "逤" }, { "suo", "鎈" }, { "suo", "鎍" }, { "suo", "鎖" }, { "suo", "锁" },
			{ "suo", "靃" }, { "suo", "魦" }, { "suo", "鮻" }, { "suo ai", "所爱" }, { "suo ai", "索爱" }, { "suo bao han", "所包含" }, { "suo cai yong", "所采用" },
			{ "suo chang", "所长" }, { "suo cheng", "所称" }, { "suo chi", "所持" }, { "suo chu", "所处" }, { "suo ci", "所赐" }, { "suo da xue", "所大学" },
			{ "suo dai", "所带" }, { "suo dao", "索道" }, { "suo de", "所得" }, { "suo de shui", "所得税" }, { "suo ding", "所定" }, { "suo ding", "锁定" },
			{ "suo duan", "缩短" }, { "suo er", "索尔" }, { "suo fa", "所发" }, { "suo fa sheng", "所发生" }, { "suo fan", "所犯" }, { "suo fang", "缩放" },
			{ "suo gao xiao", "所高校" }, { "suo gou", "所购" }, { "suo gu", "锁骨" }, { "suo han", "所含" }, { "suo huo", "所获" }, { "suo jian", "所见" },
			{ "suo jian", "缩减" }, { "suo jian suo wen", "所见所闻" }, { "suo jiang", "所讲" }, { "suo jin", "缩进" }, { "suo ju you", "所具有" }, { "suo li", "所里" },
			{ "suo liang", "缩量" }, { "suo liao", "所料" }, { "suo lie", "所列" }, { "suo lue tu", "缩略图" }, { "suo luo si", "索罗斯" }, { "suo ma li", "索马里" },
			{ "suo men", "锁门" }, { "suo mian lin", "所面临" }, { "suo neng", "所能" }, { "suo ni", "索尼" }, { "suo pei", "索赔" }, { "suo po", "所迫" },
			{ "suo qi", "所起" }, { "suo qu", "索取" }, { "suo qu de", "所取得" }, { "suo she ji", "所涉及" }, { "suo sheng", "所生" }, { "suo sheng wu ji", "所剩无几" },
			{ "suo shi", "所示" }, { "suo shi", "琐事" }, { "suo shi yong", "所使用" }, { "suo shou", "所受" }, { "suo shu", "所属" }, { "suo shu", "所述" },
			{ "suo shui", "缩水" }, { "suo shuo", "所说" }, { "suo si", "所思" }, { "suo sui", "琐碎" }, { "suo suo chang", "所所长" }, { "suo ti", "所提" },
			{ "suo ti gong", "所提供" }, { "suo wei", "所为" }, { "suo wei", "所谓" }, { "suo xia", "所辖" }, { "suo xian", "所限" }, { "suo xiang", "所想" },
			{ "suo xiao", "缩小" }, { "suo xie", "所写" }, { "suo xie", "缩写" }, { "suo xing", "所幸" }, { "suo xing", "索性" }, { "suo xu", "所需" },
			{ "suo xu yao", "所需要" }, { "suo xuan", "所选" }, { "suo xue", "所学" }, { "suo xue xiao", "所学校" }, { "suo yan", "所言" }, { "suo yao", "所要" },
			{ "suo yao", "索要" }, { "suo yao qiu", "所要求" }, { "suo yi", "所以" }, { "suo yi ran", "所以然" }, { "suo yin", "索引" }, { "suo yin qi", "所引起" },
			{ "suo ying", "缩影" }, { "suo yong", "所用" }, { "suo yong you", "所拥有" }, { "suo you", "所有" }, { "suo you nei rong", "所有内容" },
			{ "suo you quan", "所有权" }, { "suo you quan li", "所有权利" }, { "suo you ren", "所有人" }, { "suo you ren dou", "所有人都" }, { "suo you wen jian", "所有文件" },
			{ "suo you wen zhang", "所有文章" }, { "suo you wen zi", "所有文字" }, { "suo you xin xi", "所有信息" }, { "suo you zhe", "所有者" }, { "suo you zhi", "所有制" },
			{ "suo you zuo pin", "所有作品" }, { "suo yu", "所欲" }, { "suo yuan", "所愿" }, { "suo zai", "所在" }, { "suo zai", "所载" }, { "suo zai", "缩在" },
			{ "suo zai", "锁在" }, { "suo zai cheng shi", "所在城市" }, { "suo zai dan wei", "所在单位" }, { "suo zai di qu", "所在地区" }, { "suo zao cheng", "所造成" },
			{ "suo zhan", "所占" }, { "suo zhang", "所长" }, { "suo zhi", "所指" }, { "suo zhi", "所知" }, { "suo zhi", "所致" }, { "suo zhu", "所著" },
			{ "suo zhu", "锁住" }, { "suo zuo", "所作" }, { "suo zuo", "所做" }, { "suo zuo suo wei", "所作所为" }, { "ta", "他" }, { "ta", "咜" }, { "ta", "嗒" },
			{ "ta", "嚃" }, { "ta", "塌" }, { "ta", "塔" }, { "ta", "她" }, { "ta", "它" }, { "ta", "拓" }, { "ta", "挞" }, { "ta", "搨" }, { "ta", "撘" },
			{ "ta", "撻" }, { "ta", "榙" }, { "ta", "榻" }, { "ta", "毾" }, { "ta", "沓" }, { "ta", "涾" }, { "ta", "溻" }, { "ta", "漯" }, { "ta", "澾" },
			{ "ta", "濌" }, { "ta", "牠" }, { "ta", "獭" }, { "ta", "獺" }, { "ta", "祂" }, { "ta", "禢" }, { "ta", "荅" }, { "ta", "褟" }, { "ta", "誻" },
			{ "ta", "趿" }, { "ta", "踏" }, { "ta", "蹋" }, { "ta", "逹" }, { "ta", "遝" }, { "ta", "遢" }, { "ta", "鉈" }, { "ta", "錔" }, { "ta", "鎉" },
			{ "ta", "铊" }, { "ta", "闒" }, { "ta", "闥" }, { "ta", "闼" }, { "ta", "鞈" }, { "ta", "鞜" }, { "ta", "鞳" }, { "ta", "鰨" }, { "ta", "鳎" },
			{ "ta ban", "踏板" }, { "ta bu", "他不" }, { "ta bu", "她不" }, { "ta bu", "它不" }, { "ta bu", "踏步" }, { "ta chu", "踏出" }, { "ta de", "他的" },
			{ "ta de", "她的" }, { "ta de", "它的" }, { "ta de shou", "他的手" }, { "ta de shou", "她的手" }, { "ta de xin", "他的心" }, { "ta dui", "他对" },
			{ "ta fang", "塌方" }, { "ta guo", "他国" }, { "ta hai", "它还" }, { "ta he", "他和" }, { "ta he ta", "他和她" }, { "ta hui", "他会" }, { "ta jia", "他家" },
			{ "ta jia", "她家" }, { "ta jiang", "他将" }, { "ta jiang", "它将" }, { "ta jin", "踏进" }, { "ta jiu", "他就" }, { "ta jiu", "它就" }, { "ta kong", "踏空" },
			{ "ta lai", "它来" }, { "ta le", "他了" }, { "ta li ban", "塔利班" }, { "ta lia", "他俩" }, { "ta lou", "塔楼" }, { "ta ma", "他妈" }, { "ta ma de", "他妈的" },
			{ "ta men", "他们" }, { "ta men", "她们" }, { "ta men", "它们" }, { "ta men jiang", "他们将" }, { "ta men lia", "他们俩" }, { "ta niang", "他娘" },
			{ "ta qing", "踏青" }, { "ta ren", "他人" }, { "ta ru", "踏入" }, { "ta shang", "踏上" }, { "ta shi", "他是" }, { "ta shi", "塌实" }, { "ta shi", "她是" },
			{ "ta shi", "它使" }, { "ta shi", "它是" }, { "ta shi", "踏实" }, { "ta shuo", "他说" }, { "ta shuo", "她说" }, { "ta suo", "他所" },
			{ "ta ta shi shi", "踏踏实实" }, { "ta xian", "塌陷" }, { "ta xiang", "他乡" }, { "ta xue", "踏雪" }, { "ta ye", "他也" }, { "ta ye", "她也" },
			{ "ta ye", "它也" }, { "ta yi yan", "他一眼" }, { "ta you", "他又" }, { "ta you", "他有" }, { "ta zai", "他在" }, { "ta zhe", "踏着" }, { "ta zhi", "他只" },
			{ "ta zong", "他总" }, { "tai", "儓" }, { "tai", "台" }, { "tai", "呔" }, { "tai", "咍" }, { "tai", "坮" }, { "tai", "太" }, { "tai", "嬯" },
			{ "tai", "态" }, { "tai", "態" }, { "tai", "抬" }, { "tai", "擡" }, { "tai", "斄" }, { "tai", "檯" }, { "tai", "汰" }, { "tai", "泰" }, { "tai", "溙" },
			{ "tai", "炱" }, { "tai", "燤" }, { "tai", "箈" }, { "tai", "籉" }, { "tai", "肽" }, { "tai", "胎" }, { "tai", "臺" }, { "tai", "苔" }, { "tai", "薹" },
			{ "tai", "跆" }, { "tai", "邰" }, { "tai", "酞" }, { "tai", "鈦" }, { "tai", "鈶" }, { "tai", "钛" }, { "tai", "颱" }, { "tai", "骀" }, { "tai", "鮐" },
			{ "tai", "鲐" }, { "tai ai", "太爱" }, { "tai an", "泰安" }, { "tai bai", "太白" }, { "tai bang le", "太棒了" }, { "tai bao", "台胞" }, { "tai bao", "太保" },
			{ "tai bei", "台北" }, { "tai bei shi", "台北市" }, { "tai ben", "太笨" }, { "tai bi", "台币" }, { "tai bu", "太不" }, { "tai cang", "太仓" },
			{ "tai cha", "太差" }, { "tai chang", "太长" }, { "tai chi", "太迟" }, { "tai chou", "太丑" }, { "tai ci", "台词" }, { "tai da", "太大" }, { "tai da", "泰达" },
			{ "tai da de", "太大的" }, { "tai deng", "台灯" }, { "tai di", "太低" }, { "tai dian", "台电" }, { "tai dong", "胎动" }, { "tai dou", "泰斗" },
			{ "tai du", "台独" }, { "tai du", "态度" }, { "tai duan", "太短" }, { "tai duo", "太多" }, { "tai duo de", "太多的" }, { "tai er", "胎儿" },
			{ "tai feng", "台风" }, { "tai fu", "台服" }, { "tai gang", "太钢" }, { "tai gang", "抬杠" }, { "tai gao", "太高" }, { "tai gao", "抬高" }, { "tai gu", "太古" },
			{ "tai gui", "太贵" }, { "tai guo", "太过" }, { "tai guo", "泰国" }, { "tai hai", "台海" }, { "tai hang", "太行" }, { "tai hang shan", "太行山" },
			{ "tai hao", "太好" }, { "tai he", "泰和" }, { "tai he jin", "钛合金" }, { "tai hei", "太黑" }, { "tai hen", "太狠" }, { "tai hou", "太厚" },
			{ "tai hou", "太后" }, { "tai hu", "太湖" }, { "tai huai", "太坏" }, { "tai ji", "台机" }, { "tai ji", "太急" }, { "tai ji", "太极" },
			{ "tai ji quan", "太极拳" }, { "tai jia", "太假" }, { "tai jian", "太监" }, { "tai jiao", "胎教" }, { "tai jie", "台阶" }, { "tai jin", "太紧" },
			{ "tai jin", "太近" }, { "tai jiu", "太久" }, { "tai ju", "抬举" }, { "tai jun", "台军" }, { "tai kong", "太空" }, { "tai kuai", "太快" }, { "tai lan", "太懒" },
			{ "tai lan", "太烂" }, { "tai lang", "太郎" }, { "tai lao", "太老" }, { "tai le", "泰勒" }, { "tai lei", "太累" }, { "tai leng", "太冷" },
			{ "tai luan", "太乱" }, { "tai man", "太慢" }, { "tai mang", "太忙" }, { "tai mei", "太没" }, { "tai mei", "太美" }, { "tai meng", "太猛" },
			{ "tai mian", "台面" }, { "tai nan", "台南" }, { "tai nan", "太难" }, { "tai pan", "胎盘" }, { "tai pang", "太胖" }, { "tai ping", "太平" },
			{ "tai ping tian guo", "太平天国" }, { "tai ping yang", "太平洋" }, { "tai qi", "抬起" }, { "tai qi tou", "抬起头" }, { "tai qian", "台前" },
			{ "tai qiang", "太强" }, { "tai qiu", "台球" }, { "tai quan dao", "跆拳道" }, { "tai re", "太热" }, { "tai ruo", "太弱" }, { "tai sen", "泰森" },
			{ "tai sha", "太傻" }, { "tai shan", "台山" }, { "tai shan", "泰山" }, { "tai shang", "台上" }, { "tai shang", "台商" }, { "tai shao", "太少" },
			{ "tai shao le", "太少了" }, { "tai shen", "太深" }, { "tai shi", "台式" }, { "tai shi", "态势" }, { "tai shi dian nao", "台式电脑" }, { "tai shi ji", "台式机" },
			{ "tai shou", "太守" }, { "tai shou", "太瘦" }, { "tai shou", "抬手" }, { "tai shuai", "太帅" }, { "tai sui", "太岁" }, { "tai tai", "太太" },
			{ "tai tan", "泰坦" }, { "tai tou", "抬头" }, { "tai tou kan", "抬头看" }, { "tai wan", "台湾" }, { "tai wan", "太晚" }, { "tai wan dang ju", "台湾当局" },
			{ "tai wan di qu", "台湾地区" }, { "tai wan hai xia", "台湾海峡" }, { "tai wan ren", "台湾人" }, { "tai wan sheng", "台湾省" }, { "tai wan tong bao", "台湾同胞" },
			{ "tai wan wen ti", "台湾问题" }, { "tai xia", "台下" }, { "tai xiang", "太想" }, { "tai xiao", "太小" }, { "tai xing", "泰兴" }, { "tai xu", "太虚" },
			{ "tai yan", "抬眼" }, { "tai yang", "太阳" }, { "tai yang dui", "太阳队" }, { "tai yang guang", "太阳光" }, { "tai yang jing", "太阳镜" },
			{ "tai yang neng", "太阳能" }, { "tai yang shen", "太阳神" }, { "tai yang xi", "太阳系" }, { "tai yang xue", "太阳穴" }, { "tai yi", "太医" },
			{ "tai you", "太有" }, { "tai yuan", "太原" }, { "tai yuan", "太远" }, { "tai yuan shi", "太原市" }, { "tai zai yi", "太在意" }, { "tai zao", "太早" },
			{ "tai zhang", "台帐" }, { "tai zhang", "台长" }, { "tai zhe", "抬着" }, { "tai zhong", "太重" }, { "tai zhou", "台州" }, { "tai zhou", "泰州" },
			{ "tai zhou shi", "台州市" }, { "tai zi", "台子" }, { "tai zi", "台资" }, { "tai zi", "太子" }, { "tai zi qi ye", "台资企业" }, { "tai zong", "太宗" },
			{ "tai zu", "太祖" }, { "tan", "倓" }, { "tan", "傝" }, { "tan", "僋" }, { "tan", "儃" }, { "tan", "叹" }, { "tan", "嗿" }, { "tan", "嘆" }, { "tan", "嘾" },
			{ "tan", "坍" }, { "tan", "坛" }, { "tan", "坦" }, { "tan", "埮" }, { "tan", "壇" }, { "tan", "壜" }, { "tan", "婒" }, { "tan", "弹" }, { "tan", "弾" },
			{ "tan", "彈" }, { "tan", "忐" }, { "tan", "怹" }, { "tan", "惔" }, { "tan", "憛" }, { "tan", "憳" }, { "tan", "探" }, { "tan", "摊" }, { "tan", "撣" },
			{ "tan", "攤" }, { "tan", "昙" }, { "tan", "暺" }, { "tan", "曇" }, { "tan", "榃" }, { "tan", "檀" }, { "tan", "歎" }, { "tan", "毯" }, { "tan", "湠" },
			{ "tan", "滩" }, { "tan", "潬" }, { "tan", "潭" }, { "tan", "澹" }, { "tan", "灘" }, { "tan", "炭" }, { "tan", "痰" }, { "tan", "瘫" }, { "tan", "癉" },
			{ "tan", "癱" }, { "tan", "碳" }, { "tan", "繵" }, { "tan", "罈" }, { "tan", "罎" }, { "tan", "舕" }, { "tan", "菼" }, { "tan", "藫" }, { "tan", "袒" },
			{ "tan", "裧" }, { "tan", "覃" }, { "tan", "談" }, { "tan", "譚" }, { "tan", "譠" }, { "tan", "谈" }, { "tan", "谭" }, { "tan", "貚" }, { "tan", "貪" },
			{ "tan", "賧" }, { "tan", "贪" }, { "tan", "郯" }, { "tan", "醓" }, { "tan", "醰" }, { "tan", "鉭" }, { "tan", "钽" }, { "tan", "锬" }, { "tan", "顃" },
			{ "tan", "餤" }, { "tan", "黮" }, { "tan bai", "坦白" }, { "tan ban", "探班" }, { "tan bo", "摊薄" }, { "tan bu shang", "谈不上" }, { "tan ce", "探测" },
			{ "tan ce qi", "探测器" }, { "tan cha", "探查" }, { "tan cheng", "坦承" }, { "tan cheng", "坦诚" }, { "tan chi", "贪吃" }, { "tan chu", "弹出" },
			{ "tan chu chuang kou", "弹出窗口" }, { "tan chu lai", "弹出来" }, { "tan chu yi ge", "弹出一个" }, { "tan dang", "坦荡" }, { "tan dao", "叹道" },
			{ "tan dao", "谈到" }, { "tan de", "谈得" }, { "tan di", "探底" }, { "tan dian", "摊点" }, { "tan fan", "摊贩" }, { "tan fang", "探访" },
			{ "tan gang qin", "弹钢琴" }, { "tan ge", "探戈" }, { "tan guan", "贪官" }, { "tan guan wu li", "贪官污吏" }, { "tan guo", "谈过" }, { "tan hao", "谈好" },
			{ "tan he", "弹劾" }, { "tan hua", "谈话" }, { "tan hua yi xian", "昙花一现" }, { "tan huan", "瘫痪" }, { "tan huang", "弹簧" }, { "tan ji", "谈及" },
			{ "tan jiu", "探究" }, { "tan kai", "摊开" }, { "tan ke", "坦克" }, { "tan kou qi", "叹口气" }, { "tan lan", "贪婪" }, { "tan le", "叹了" }, { "tan li", "弹力" },
			{ "tan lian", "贪恋" }, { "tan lian ai", "谈恋爱" }, { "tan lu", "探路" }, { "tan lun", "谈论" }, { "tan mi", "探秘" }, { "tan ming", "探明" },
			{ "tan pai", "摊派" }, { "tan pai", "摊牌" }, { "tan pan", "谈判" }, { "tan qi", "叹气" }, { "tan qi", "谈起" }, { "tan qin", "弹琴" }, { "tan qin", "探亲" },
			{ "tan qing shuo ai", "谈情说爱" }, { "tan qiu", "探求" }, { "tan ran", "坦然" }, { "tan shang", "摊上" }, { "tan shi", "探视" }, { "tan shuai", "坦率" },
			{ "tan suan", "碳酸" }, { "tan suo", "探索" }, { "tan ta", "坍塌" }, { "tan tan", "谈谈" }, { "tan tao", "探讨" }, { "tan te", "忐忑" },
			{ "tan te bu an", "忐忑不安" }, { "tan tiao", "弹跳" }, { "tan tou", "探头" }, { "tan tu", "滩涂" }, { "tan tu", "谈吐" }, { "tan tu", "贪图" },
			{ "tan wan", "贪玩" }, { "tan wang", "探望" }, { "tan wei", "摊位" }, { "tan wei guan zhi", "叹为观止" }, { "tan wu", "贪污" }, { "tan wu fu bai", "贪污腐败" },
			{ "tan wu shou hui", "贪污受贿" }, { "tan xi", "叹息" }, { "tan xi", "探析" }, { "tan xian", "探险" }, { "tan xian wei", "碳纤维" }, { "tan xiao", "摊销" },
			{ "tan xiao", "谈笑" }, { "tan xin", "谈心" }, { "tan xin", "贪心" }, { "tan xing", "弹性" }, { "tan xun", "探寻" }, { "tan yan", "坦言" },
			{ "tan yi tan", "谈一谈" }, { "tan yong lin", "谭咏麟" }, { "tan yu", "贪欲" }, { "tan zhen", "探针" }, { "tan zhi", "弹指" }, { "tan zhu", "摊主" },
			{ "tan zi", "坛子" }, { "tan zi", "摊子" }, { "tan zi", "毯子" }, { "tan zi", "谈资" }, { "tan zi li", "坛子里" }, { "tan zou", "弹奏" }, { "tang", "倘" },
			{ "tang", "傥" }, { "tang", "儻" }, { "tang", "唐" }, { "tang", "堂" }, { "tang", "塘" }, { "tang", "嵣" }, { "tang", "帑" }, { "tang", "惝" },
			{ "tang", "愓" }, { "tang", "戃" }, { "tang", "搪" }, { "tang", "摥" }, { "tang", "攩" }, { "tang", "曭" }, { "tang", "棠" }, { "tang", "榶" },
			{ "tang", "樘" }, { "tang", "橖" }, { "tang", "欓" }, { "tang", "汤" }, { "tang", "淌" }, { "tang", "湯" }, { "tang", "溏" }, { "tang", "漟" },
			{ "tang", "漡" }, { "tang", "烫" }, { "tang", "煻" }, { "tang", "燙" }, { "tang", "爣" }, { "tang", "瑭" }, { "tang", "矘" }, { "tang", "磄" },
			{ "tang", "簜" }, { "tang", "糖" }, { "tang", "羰" }, { "tang", "耥" }, { "tang", "膛" }, { "tang", "蓎" }, { "tang", "薚" }, { "tang", "蘯" },
			{ "tang", "蝪" }, { "tang", "螗" }, { "tang", "螳" }, { "tang", "赯" }, { "tang", "趟" }, { "tang", "踼" }, { "tang", "蹚" }, { "tang", "躺" },
			{ "tang", "逿" }, { "tang", "醣" }, { "tang", "鎕" }, { "tang", "鎲" }, { "tang", "鏜" }, { "tang", "鐋" }, { "tang", "钂" }, { "tang", "铴" },
			{ "tang", "镗" }, { "tang", "閶" }, { "tang", "闛" }, { "tang", "闣" }, { "tang", "鶶" }, { "tang", "鼞" }, { "tang bo hu", "唐伯虎" },
			{ "tang chao", "唐朝" }, { "tang chi", "汤匙" }, { "tang dai", "唐代" }, { "tang di", "堂弟" }, { "tang er huang zhi", "堂而皇之" }, { "tang fa", "烫发" },
			{ "tang fen", "糖分" }, { "tang ge", "堂哥" }, { "tang gu", "塘沽" }, { "tang guo", "糖果" }, { "tang jia", "唐家" }, { "tang jiang", "糖浆" },
			{ "tang jun", "唐骏" }, { "tang ke", "堂课" }, { "tang lang", "螳螂" }, { "tang lei", "糖类" }, { "tang mu", "汤姆" }, { "tang niao bing", "糖尿病" },
			{ "tang ren", "唐人" }, { "tang ren jie", "唐人街" }, { "tang ruo", "倘若" }, { "tang se", "搪塞" }, { "tang seng", "唐僧" }, { "tang shan", "唐山" },
			{ "tang shan shi", "唐山市" }, { "tang shang", "烫伤" }, { "tang shi", "唐诗" }, { "tang shou", "烫手" }, { "tang shui", "糖水" }, { "tang song", "唐宋" },
			{ "tang tai zong", "唐太宗" }, { "tang tang", "堂堂" }, { "tang tang", "糖糖" }, { "tang tang zheng zheng", "堂堂正正" }, { "tang tu", "唐突" },
			{ "tang wei", "汤唯" }, { "tang xia", "躺下" }, { "tang xiao", "唐笑" }, { "tang yuan", "汤圆" }, { "tang zai", "躺在" }, { "tang zhe", "躺着" },
			{ "tang zhi", "汤汁" }, { "tang zhu", "堂主" }, { "tao", "丶" }, { "tao", "匋" }, { "tao", "叨" }, { "tao", "啕" }, { "tao", "夲" }, { "tao", "套" },
			{ "tao", "嫍" }, { "tao", "幍" }, { "tao", "弢" }, { "tao", "慆" }, { "tao", "掏" }, { "tao", "搯" }, { "tao", "桃" }, { "tao", "梼" }, { "tao", "槄" },
			{ "tao", "檮" }, { "tao", "洮" }, { "tao", "涛" }, { "tao", "淘" }, { "tao", "滔" }, { "tao", "濤" }, { "tao", "焘" }, { "tao", "燾" }, { "tao", "祹" },
			{ "tao", "絛" }, { "tao", "綯" }, { "tao", "縚" }, { "tao", "绦" }, { "tao", "萄" }, { "tao", "蜪" }, { "tao", "討" }, { "tao", "讨" }, { "tao", "迯" },
			{ "tao", "逃" }, { "tao", "醄" }, { "tao", "鋾" }, { "tao", "錭" }, { "tao", "陶" }, { "tao", "鞀" }, { "tao", "韜" }, { "tao", "韬" }, { "tao", "饕" },
			{ "tao", "駣" }, { "tao", "騊" }, { "tao", "鼗" }, { "tao bao", "淘宝" }, { "tao bao wang", "淘宝网" }, { "tao bi", "逃避" }, { "tao can", "套餐" },
			{ "tao chu", "掏出" }, { "tao chu", "逃出" }, { "tao ci", "陶瓷" }, { "tao cuan", "逃窜" }, { "tao dao", "逃到" }, { "tao fa", "讨伐" }, { "tao fan", "讨饭" },
			{ "tao fan", "逃犯" }, { "tao fang", "套房" }, { "tao ge", "讨个" }, { "tao guan", "套管" }, { "tao guo", "逃过" }, { "tao hao", "讨好" }, { "tao hua", "桃花" },
			{ "tao hua yuan", "桃花源" }, { "tao hua yun", "桃花运" }, { "tao hui", "讨回" } };
};
