package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN48 {
	public static String[][] pl = { { "wai chuan", "外传" }, { "wai di", "外地" }, { "wai di ren", "外地人" }, { "wai dian", "外电" }, { "wai fang", "外方" },
			{ "wai fu", "外敷" }, { "wai fu", "外服" }, { "wai gao qiao", "外高桥" }, { "wai gong", "外公" }, { "wai gou", "外购" }, { "wai gua", "外挂" },
			{ "wai guan", "外观" }, { "wai guan she ji", "外观设计" }, { "wai guo", "外国" }, { "wai guo gong si", "外国公司" }, { "wai guo qi ye", "外国企业" },
			{ "wai guo ren", "外国人" }, { "wai guo yu", "外国语" }, { "wai hang", "外行" }, { "wai hao", "外号" }, { "wai huan", "外环" }, { "wai hui", "外汇" },
			{ "wai hui chu bei", "外汇储备" }, { "wai hui jiao yi", "外汇交易" }, { "wai hui shi chang", "外汇市场" }, { "wai ji", "外籍" }, { "wai jia", "外加" },
			{ "wai jiao", "外交" }, { "wai jiao", "外教" }, { "wai jiao bu", "外交部" }, { "wai jiao bu zhang", "外交部长" }, { "wai jiao guan", "外交官" },
			{ "wai jiao zheng ce", "外交政策" }, { "wai jie", "外接" }, { "wai jie", "外界" }, { "wai jing", "外景" }, { "wai jing mao", "外经贸" }, { "wai ke", "外壳" },
			{ "wai ke", "外科" }, { "wai ke shou shu", "外科手术" }, { "wai kuai", "外快" }, { "wai lai", "外来" }, { "wai lai gong", "外来工" },
			{ "wai lai ren kou", "外来人口" }, { "wai lai ren yuan", "外来人员" }, { "wai le", "歪了" }, { "wai li", "外力" }, { "wai lian", "外联" }, { "wai liu", "外流" },
			{ "wai lu", "外露" }, { "wai mai", "外卖" }, { "wai mao", "外貌" }, { "wai mao", "外贸" }, { "wai mao chu kou", "外贸出口" }, { "wai mao gong si", "外贸公司" },
			{ "wai mao qi ye", "外贸企业" }, { "wai mian", "外面" }, { "wai pai", "外拍" }, { "wai pai", "外派" }, { "wai pan", "外盘" }, { "wai pi", "外皮" },
			{ "wai pin", "外频" }, { "wai po", "外婆" }, { "wai po jia", "外婆家" }, { "wai qi", "外企" }, { "wai qiang", "外墙" }, { "wai qu", "歪曲" },
			{ "wai ren", "外人" }, { "wai shang", "外伤" }, { "wai shang", "外商" }, { "wai shang tou zi", "外商投资" }, { "wai she", "外设" }, { "wai sheng", "外甥" },
			{ "wai sheng", "外省" }, { "wai sheng nv", "外甥女" }, { "wai shi", "外事" }, { "wai sun", "外孙" }, { "wai tan", "外滩" }, { "wai tao", "外套" },
			{ "wai tao", "外逃" }, { "wai tou", "外头" }, { "wai wai", "歪歪" }, { "wai wang", "外网" }, { "wai wei", "外围" }, { "wai wen", "外文" },
			{ "wai xian", "外线" }, { "wai xiang", "外向" }, { "wai xiang", "外相" }, { "wai xiao", "外校" }, { "wai xiao", "外销" }, { "wai xie", "外泄" },
			{ "wai xing", "外型" }, { "wai xing", "外形" }, { "wai xing", "外星" }, { "wai xing ren", "外星人" }, { "wai yan", "外延" }, { "wai yi", "外衣" },
			{ "wai yin", "外阴" }, { "wai yong", "外用" }, { "wai yu", "外域" }, { "wai yu", "外语" }, { "wai yu", "外遇" }, { "wai yuan", "外援" }, { "wai yun", "外运" },
			{ "wai zai", "外在" }, { "wai zhai", "外债" }, { "wai zhang", "外长" }, { "wai zhe", "歪着" }, { "wai zhi", "外置" }, { "wai zhuan", "外传" },
			{ "wai zi", "外资" }, { "wai zi bing gou", "外资并购" }, { "wai zi qi ye", "外资企业" }, { "wai zi yin hang", "外资银行" }, { "wan", "万" }, { "wan", "丸" },
			{ "wan", "倇" }, { "wan", "刓" }, { "wan", "剜" }, { "wan", "卍" }, { "wan", "夘" }, { "wan", "婉" }, { "wan", "婠" }, { "wan", "完" }, { "wan", "宛" },
			{ "wan", "岏" }, { "wan", "弯" }, { "wan", "彎" }, { "wan", "忨" }, { "wan", "惋" }, { "wan", "抏" }, { "wan", "挽" }, { "wan", "捖" }, { "wan", "捥" },
			{ "wan", "掔" }, { "wan", "晚" }, { "wan", "晩" }, { "wan", "晼" }, { "wan", "杤" }, { "wan", "椀" }, { "wan", "槾" }, { "wan", "汍" }, { "wan", "湾" },
			{ "wan", "潫" }, { "wan", "澫" }, { "wan", "灣" }, { "wan", "烷" }, { "wan", "玩" }, { "wan", "琓" }, { "wan", "琬" }, { "wan", "畹" }, { "wan", "皖" },
			{ "wan", "睕" }, { "wan", "碗" }, { "wan", "笂" }, { "wan", "紈" }, { "wan", "綄" }, { "wan", "綩" }, { "wan", "綰" }, { "wan", "纨" }, { "wan", "绾" },
			{ "wan", "翫" }, { "wan", "脘" }, { "wan", "腕" }, { "wan", "芄" }, { "wan", "莞" }, { "wan", "菀" }, { "wan", "萬" }, { "wan", "蔓" }, { "wan", "薍" },
			{ "wan", "蜿" }, { "wan", "豌" }, { "wan", "輓" }, { "wan", "鄤" }, { "wan", "鋄" }, { "wan", "鍐" }, { "wan", "関" }, { "wan", "頑" }, { "wan", "顽" },
			{ "wan an", "晚安" }, { "wan an", "湾岸" }, { "wan ba", "玩吧" }, { "wan ban", "万般" }, { "wan ban", "晚班" }, { "wan ban", "玩伴" }, { "wan bao", "晚报" },
			{ "wan bei", "完备" }, { "wan bei", "晚辈" }, { "wan bi", "完毕" }, { "wan bi", "完璧" }, { "wan biao", "腕表" }, { "wan can", "晚餐" }, { "wan cheng", "完成" },
			{ "wan cheng qing kuang", "完成情况" }, { "wan cheng ren wu", "完成任务" }, { "wan da", "万达" }, { "wan dan", "完蛋" }, { "wan dao", "弯道" },
			{ "wan dao", "玩到" }, { "wan de", "玩得" }, { "wan de", "玩的" }, { "wan dian", "晚点" }, { "wan dian nao", "玩电脑" }, { "wan dou", "豌豆" },
			{ "wan dun", "万吨" }, { "wan dun ji", "万吨级" }, { "wan duo", "万多" }, { "wan e", "万恶" }, { "wan er", "婉儿" }, { "wan er", "玩儿" }, { "wan fa", "玩法" },
			{ "wan fan", "晚饭" }, { "wan fan", "碗饭" }, { "wan fang", "万方" }, { "wan fen", "万分" }, { "wan fen zhi yi", "万分之一" }, { "wan feng", "晚风" },
			{ "wan ge", "万个" }, { "wan gong", "完工" }, { "wan gu", "万古" }, { "wan gu", "万股" }, { "wan gu", "顽固" }, { "wan guo", "万国" }, { "wan guo", "玩过" },
			{ "wan hao", "完好" }, { "wan hou", "完后" }, { "wan hu", "万户" }, { "wan hui", "挽回" }, { "wan hui", "晚会" }, { "wan ji", "顽疾" }, { "wan jia", "万家" },
			{ "wan jia", "玩家" }, { "wan jian", "晚间" }, { "wan jie", "完结" }, { "wan jiu", "挽救" }, { "wan ju", "婉拒" }, { "wan ju", "玩具" }, { "wan ke", "万科" },
			{ "wan kuai", "万块" }, { "wan kuai", "碗筷" }, { "wan le", "完了" }, { "wan le", "玩乐" }, { "wan li", "万历" }, { "wan li", "万里" }, { "wan li", "碗里" },
			{ "wan liang", "万辆" }, { "wan liu", "挽留" }, { "wan lu", "弯路" }, { "wan man", "完满" }, { "wan mei", "完美" }, { "wan mei shi jie", "完美世界" },
			{ "wan mei yuan", "万美元" }, { "wan ming", "万名" }, { "wan ming", "玩命" }, { "wan mu", "万亩" }, { "wan neng", "万能" }, { "wan nian", "万年" },
			{ "wan nian", "晚年" }, { "wan nian li", "万年历" }, { "wan nong", "玩弄" }, { "wan ou", "玩偶" }, { "wan pi", "顽皮" }, { "wan qi", "晚期" },
			{ "wan qi", "玩起" }, { "wan qian", "万千" }, { "wan qian wa", "万千瓦" }, { "wan qiang", "顽强" }, { "wan qing", "晚清" }, { "wan qu", "弯曲" },
			{ "wan quan", "完全" }, { "wan quan bu tong", "完全不同" }, { "wan quan ke yi", "完全可以" }, { "wan quan mei you", "完全没有" },
			{ "wan quan mian fei", "完全免费" }, { "wan quan xiang tong", "完全相同" }, { "wan ren", "万人" }, { "wan ren", "完人" }, { "wan ren ci", "万人次" },
			{ "wan ren mi", "万人迷" }, { "wan ru", "宛如" }, { "wan ruo", "宛若" }, { "wan shan", "完善" }, { "wan shang", "晚上" }, { "wan shang hao", "晚上好" },
			{ "wan shang shui jiao", "晚上睡觉" }, { "wan shen me", "玩什么" }, { "wan sheng", "完胜" }, { "wan sheng jie", "万圣节" }, { "wan shi", "万事" },
			{ "wan shi", "完事" }, { "wan shi bu gong", "玩世不恭" }, { "wan shi ru yi", "万事如意" }, { "wan shua", "玩耍" }, { "wan shui", "晚睡" }, { "wan sui", "万岁" },
			{ "wan tai", "万台" }, { "wan tong", "万通" }, { "wan wan", "万万" }, { "wan wan", "弯弯" }, { "wan wan", "玩完" }, { "wan wan", "玩玩" },
			{ "wan wan quan quan", "完完全全" }, { "wan wang", "万网" }, { "wan wei", "玩味" }, { "wan wu", "万物" }, { "wan wu", "玩物" }, { "wan wu yi shi", "万无一失" },
			{ "wan xi", "惋惜" }, { "wan xia", "弯下" }, { "wan xia", "晚霞" }, { "wan xiang", "万象" }, { "wan xiao", "玩笑" }, { "wan xie", "晚些" },
			{ "wan xie shi hou", "晚些时候" }, { "wan xing", "万幸" }, { "wan yan", "完颜" }, { "wan yan", "晚宴" }, { "wan yan", "蜿蜒" }, { "wan yao", "弯腰" },
			{ "wan yi", "万一" }, { "wan yi", "万亿" }, { "wan yi", "玩意" }, { "wan yi", "玩艺" }, { "wan yi er", "玩意儿" }, { "wan yi shang", "万以上" },
			{ "wan yi yuan", "万亿元" }, { "wan yong biao", "万用表" }, { "wan you xi", "玩游戏" }, { "wan yu", "万余" }, { "wan yuan", "万元" },
			{ "wan yuan yi shang", "万元以上" }, { "wan yuan yi xia", "万元以下" }, { "wan yuan zuo you", "万元左右" }, { "wan yue", "婉约" }, { "wan zhang", "万丈" },
			{ "wan zhang", "万张" }, { "wan zhe", "挽着" }, { "wan zhe", "玩着" }, { "wan zheng", "完整" }, { "wan zheng ban", "完整版" }, { "wan zheng xing", "完整性" },
			{ "wan zhong", "万众" }, { "wan zhong", "万种" }, { "wan zhou", "万州" }, { "wan zhuan", "婉转" }, { "wan zhuan", "玩转" }, { "wan zi", "万字" },
			{ "wan zi", "丸子" }, { "wan zi xi", "晚自习" }, { "wan zuo you", "万左右" }, { "wang", "亡" }, { "wang", "仼" }, { "wang", "妄" }, { "wang", "尪" },
			{ "wang", "往" }, { "wang", "徃" }, { "wang", "忘" }, { "wang", "惘" }, { "wang", "抂" }, { "wang", "旺" }, { "wang", "暀" }, { "wang", "望" },
			{ "wang", "朢" }, { "wang", "枉" }, { "wang", "汪" }, { "wang", "瀇" }, { "wang", "王" }, { "wang", "盳" }, { "wang", "網" }, { "wang", "网" },
			{ "wang", "罔" }, { "wang", "莣" }, { "wang", "菵" }, { "wang", "輞" }, { "wang", "辋" }, { "wang", "迋" }, { "wang", "魍" }, { "wang an shi", "王安石" },
			{ "wang ba", "王八" }, { "wang ba", "网吧" }, { "wang ba dan", "王八蛋" }, { "wang bei", "往北" }, { "wang bin", "王斌" }, { "wang bu liao", "忘不了" },
			{ "wang cai", "旺财" }, { "wang chang", "往常" }, { "wang chao", "王朝" }, { "wang chao", "王超" }, { "wang chen mo ji", "望尘莫及" }, { "wang cheng", "王城" },
			{ "wang chong", "网虫" }, { "wang dan", "王丹" }, { "wang dao", "王道" }, { "wang dian", "网店" }, { "wang dian", "网点" }, { "wang diao", "忘掉" },
			{ "wang dong", "往东" }, { "wang dong", "王东" }, { "wang duan", "网段" }, { "wang er", "王二" }, { "wang er que bu", "望而却步" }, { "wang fan", "往返" },
			{ "wang fang", "王芳" }, { "wang fei", "王妃" }, { "wang fei", "王菲" }, { "wang fei", "网费" }, { "wang feng", "汪峰" }, { "wang fu", "王府" },
			{ "wang fu jing", "王府井" }, { "wang gang", "王刚" }, { "wang ge", "网格" }, { "wang gong", "王宫" }, { "wang gou", "网购" }, { "wang guan", "王冠" },
			{ "wang guan", "网关" }, { "wang guan", "网管" }, { "wang guo", "亡国" }, { "wang guo", "王国" }, { "wang hai", "王海" }, { "wang han", "汪涵" },
			{ "wang hao", "王浩" }, { "wang hao", "王皓" }, { "wang hou", "往后" }, { "wang hou", "王后" }, { "wang huai", "忘怀" }, { "wang hui", "往回" },
			{ "wang hui", "王辉" }, { "wang ji", "忘记" }, { "wang ji", "旺季" }, { "wang ji mi ma", "忘记密码" }, { "wang jia", "王佳" }, { "wang jia", "王家" },
			{ "wang jia wei", "王家卫" }, { "wang jian", "望见" }, { "wang jian", "王建" }, { "wang jian", "网监" }, { "wang jiao", "旺角" }, { "wang jie", "往届" },
			{ "wang jie", "王杰" }, { "wang jin ping", "王金平" }, { "wang jing", "望京" }, { "wang jing", "王晶" }, { "wang jing", "王静" }, { "wang jing wei", "汪精卫" },
			{ "wang jun", "王俊" }, { "wang jun", "王军" }, { "wang ka", "网卡" }, { "wang lai", "往来" }, { "wang lao ji", "王老吉" }, { "wang lao shi", "王老师" },
			{ "wang le", "忘了" }, { "wang le", "望了" }, { "wang lei", "王磊" }, { "wang li", "往里" }, { "wang li", "王丽" }, { "wang li", "王力" }, { "wang li", "王立" },
			{ "wang li hong", "王力宏" }, { "wang li qin", "王励勤" }, { "wang lian", "网恋" }, { "wang liang", "王亮" }, { "wang ling", "亡灵" }, { "wang lu", "网路" },
			{ "wang lun tan", "网论坛" }, { "wang luo", "网络" }, { "wang luo", "网罗" }, { "wang luo an quan", "网络安全" }, { "wang luo ban", "网络版" },
			{ "wang luo bu", "网络部" }, { "wang luo chuan bo", "网络传播" }, { "wang luo dao de", "网络道德" }, { "wang luo dian hua", "网络电话" },
			{ "wang luo dian shi", "网络电视" }, { "wang luo fu wu", "网络服务" }, { "wang luo gong si", "网络公司" }, { "wang luo guan li", "网络管理" },
			{ "wang luo guang gao", "网络广告" }, { "wang luo hua", "网络化" }, { "wang luo huan jing", "网络环境" }, { "wang luo ji shu", "网络技术" },
			{ "wang luo jian she", "网络建设" }, { "wang luo lian jie", "网络连接" }, { "wang luo mei ti", "网络媒体" }, { "wang luo ping tai", "网络平台" },
			{ "wang luo she bei", "网络设备" }, { "wang luo shi dai", "网络时代" }, { "wang luo shi jie", "网络世界" }, { "wang luo shi pin", "网络视频" },
			{ "wang luo tui guang", "网络推广" }, { "wang luo xi tong", "网络系统" }, { "wang luo xin xi", "网络信息" }, { "wang luo ying pan", "网络硬盘" },
			{ "wang luo ying xiao", "网络营销" }, { "wang luo ying yong", "网络应用" }, { "wang luo you xi", "网络游戏" }, { "wang luo zhong xin", "网络中心" },
			{ "wang luo zi yuan", "网络资源" }, { "wang meng", "王蒙" }, { "wang min", "网民" }, { "wang ming", "王明" }, { "wang ming", "网名" }, { "wang mou", "王某" },
			{ "wang nan", "往南" }, { "wang nan", "王楠" }, { "wang nei", "网内" }, { "wang nian", "往年" }, { "wang pai", "王牌" }, { "wang pan", "网盘" },
			{ "wang peng", "王鹏" }, { "wang ping", "王平" }, { "wang qian", "往前" }, { "wang qian zou", "往前走" }, { "wang qiang", "王强" }, { "wang qing", "忘情" },
			{ "wang qiu", "网球" }, { "wang qiu chang", "网球场" }, { "wang qu", "望去" }, { "wang que", "忘却" }, { "wang ri", "往日" }, { "wang shang", "往上" },
			{ "wang shang", "网上" }, { "wang shang", "网商" }, { "wang shang bao ming", "网上报名" }, { "wang shang gou wu", "网上购物" },
			{ "wang shang jiao yi", "网上交易" }, { "wang shang kan", "网上看" }, { "wang shang lin ju", "网上邻居" }, { "wang shang shang cheng", "网上商城" },
			{ "wang shang xia zai", "网上下载" }, { "wang shang yin hang", "网上银行" }, { "wang shang zhi fu", "网上支付" }, { "wang sheng", "往生" },
			{ "wang sheng", "旺盛" }, { "wang shi", "往事" }, { "wang shi", "王世" }, { "wang shi", "王室" }, { "wang shi", "王氏" }, { "wang shi", "王石" },
			{ "wang shuo", "王朔" }, { "wang su", "网速" }, { "wang tao", "王涛" }, { "wang tong", "网通" }, { "wang tu", "妄图" }, { "wang wai", "往外" },
			{ "wang wang", "往往" }, { "wang wang", "旺旺" }, { "wang wang", "望望" }, { "wang wang", "汪汪" }, { "wang wei", "王伟" }, { "wang wei", "王位" },
			{ "wang wei", "王维" }, { "wang wen", "王文" }, { "wang wo", "忘我" }, { "wang xi", "往昔" }, { "wang xi", "往西" }, { "wang xia", "往下" },
			{ "wang xia", "网下" }, { "wang xian", "网线" }, { "wang xian sheng", "王先生" }, { "wang xiang", "妄想" }, { "wang xiang", "望向" }, { "wang xiao", "王小" },
			{ "wang xiao", "王晓" }, { "wang xiao", "网校" }, { "wang xiao bo", "王小波" }, { "wang xiao ya", "王小丫" }, { "wang xin", "王新" },
			{ "wang xin ling", "王心凌" }, { "wang xun", "网讯" }, { "wang yan", "王燕" }, { "wang yang", "汪洋" }, { "wang ye", "王爷" }, { "wang ye", "网页" },
			{ "wang ye she ji", "网页设计" }, { "wang ye zhi zuo", "网页制作" }, { "wang yi", "王毅" }, { "wang yi", "网易" }, { "wang yin", "网瘾" }, { "wang yin", "网银" },
			{ "wang yong", "王勇" }, { "wang yong", "王永" }, { "wang yong qing", "王永庆" }, { "wang you", "网友" }, { "wang you", "网游" },
			{ "wang you guan dian", "网友观点" }, { "wang you ping lun", "网友评论" }, { "wang you shang chuan", "网友上传" }, { "wang yu", "王宇" }, { "wang yu", "王玉" },
			{ "wang yu", "网域" }, { "wang yuan jing", "望远镜" }, { "wang yue", "望月" }, { "wang zhai", "网摘" }, { "wang zhan", "网站" },
			{ "wang zhan di zhi", "网站地址" }, { "wang zhan jian she", "网站建设" }, { "wang zhan nei rong", "网站内容" }, { "wang zhan she ji", "网站设计" },
			{ "wang zhan tui guang", "网站推广" }, { "wang zhan xi tong", "网站系统" }, { "wang zhan you hua", "网站优化" }, { "wang zhan yuan ma", "网站源码" },
			{ "wang zhe", "望着" }, { "wang zhe", "王者" }, { "wang zhen", "王振" }, { "wang zhi", "王志" }, { "wang zhi", "网址" }, { "wang zhi", "网志" },
			{ "wang zhi zhi", "王治郅" }, { "wang zhuan", "网赚" }, { "wang zhuang", "网状" }, { "wang zi", "王子" }, { "wang zong", "王总" }, { "wei", "为" },
			{ "wei", "伟" }, { "wei", "伪" }, { "wei", "位" }, { "wei", "偉" }, { "wei", "偎" }, { "wei", "偽" }, { "wei", "僞" }, { "wei", "儰" }, { "wei", "卫" },
			{ "wei", "危" }, { "wei", "味" }, { "wei", "唯" }, { "wei", "喂" }, { "wei", "喡" }, { "wei", "噲" }, { "wei", "囗" }, { "wei", "围" }, { "wei", "圍" },
			{ "wei", "圩" }, { "wei", "壝" }, { "wei", "委" }, { "wei", "威" }, { "wei", "娓" }, { "wei", "媦" }, { "wei", "寪" }, { "wei", "尉" }, { "wei", "尾" },
			{ "wei", "峗" }, { "wei", "峞" }, { "wei", "崣" }, { "wei", "崴" }, { "wei", "嵬" }, { "wei", "巋" }, { "wei", "巍" }, { "wei", "帏" }, { "wei", "帷" },
			{ "wei", "幃" }, { "wei", "廆" }, { "wei", "徫" }, { "wei", "微" }, { "wei", "惟" }, { "wei", "愄" }, { "wei", "慰" }, { "wei", "揋" }, { "wei", "撱" },
			{ "wei", "斖" }, { "wei", "暐" }, { "wei", "未" }, { "wei", "桅" }, { "wei", "梶" }, { "wei", "椲" }, { "wei", "椳" }, { "wei", "沩" }, { "wei", "洈" },
			{ "wei", "洧" }, { "wei", "浘" }, { "wei", "涠" }, { "wei", "渨" }, { "wei", "渭" }, { "wei", "湋" }, { "wei", "溈" }, { "wei", "溦" }, { "wei", "潍" },
			{ "wei", "潿" }, { "wei", "濊" }, { "wei", "濰" }, { "wei", "濻" }, { "wei", "瀢" }, { "wei", "炜" }, { "wei", "為" }, { "wei", "烓" }, { "wei", "煒" },
			{ "wei", "煟" }, { "wei", "煨" }, { "wei", "爲" }, { "wei", "犚" }, { "wei", "犩" }, { "wei", "猥" }, { "wei", "猬" }, { "wei", "玮" }, { "wei", "瑋" },
			{ "wei", "瓗" }, { "wei", "畏" }, { "wei", "痏" }, { "wei", "痿" }, { "wei", "癐" }, { "wei", "癓" }, { "wei", "瞶" }, { "wei", "碨" }, { "wei", "磈" },
			{ "wei", "磑" }, { "wei", "維" }, { "wei", "緯" }, { "wei", "縅" }, { "wei", "纬" }, { "wei", "维" }, { "wei", "罻" }, { "wei", "胃" }, { "wei", "腲" },
			{ "wei", "艉" }, { "wei", "芛" }, { "wei", "苇" }, { "wei", "菋" }, { "wei", "萎" }, { "wei", "葦" }, { "wei", "葨" }, { "wei", "葳" }, { "wei", "蒍" },
			{ "wei", "蓶" }, { "wei", "蔚" }, { "wei", "蔿" }, { "wei", "薇" }, { "wei", "藯" }, { "wei", "蘶" }, { "wei", "蜲" }, { "wei", "蜼" }, { "wei", "蝛" },
			{ "wei", "蝟" }, { "wei", "衛" }, { "wei", "衞" }, { "wei", "褽" }, { "wei", "覣" }, { "wei", "覹" }, { "wei", "詴" }, { "wei", "諉" }, { "wei", "謂" },
			{ "wei", "讆" }, { "wei", "诿" }, { "wei", "谓" }, { "wei", "趡" }, { "wei", "踓" }, { "wei", "躗" }, { "wei", "軎" }, { "wei", "违" }, { "wei", "逶" },
			{ "wei", "違" }, { "wei", "遗" }, { "wei", "鄬" }, { "wei", "鍏" }, { "wei", "鍡" }, { "wei", "鏏" }, { "wei", "闈" }, { "wei", "闱" }, { "wei", "隇" },
			{ "wei", "隈" }, { "wei", "隗" }, { "wei", "霨" }, { "wei", "霺" }, { "wei", "韋" }, { "wei", "韙" }, { "wei", "韡" }, { "wei", "韦" }, { "wei", "韪" },
			{ "wei", "頠" }, { "wei", "餧" }, { "wei", "餵" }, { "wei", "饖" }, { "wei", "骫" }, { "wei", "魏" }, { "wei", "鮇" }, { "wei", "鮠" }, { "wei", "鮪" },
			{ "wei", "鰄" }, { "wei", "鲔" }, { "wei ai", "为爱" }, { "wei ai", "胃癌" }, { "wei ai la", "维埃拉" }, { "wei an", "伟岸" }, { "wei an", "未按" },
			{ "wei an fu", "慰安妇" }, { "wei ba", "尾巴" }, { "wei ban", "为伴" }, { "wei bei", "未被" }, { "wei bei", "违背" }, { "wei ben", "为本" }, { "wei bi", "未必" },
			{ "wei bian", "未变" }, { "wei bing", "卫兵" }, { "wei bing", "胃病" }, { "wei bo", "微波" }, { "wei bo", "微薄" }, { "wei bo", "韦伯" },
			{ "wei bo lu", "微波炉" }, { "wei bu", "尾部" }, { "wei bu", "胃部" }, { "wei bu zu dao", "微不足道" }, { "wei ceng", "未曾" }, { "wei chang", "未尝" },
			{ "wei chang", "胃肠" }, { "wei chang dao", "胃肠道" }, { "wei cheng", "围城" }, { "wei cheng", "围成" }, { "wei cheng nian", "未成年" }, { "wei chi", "为耻" },
			{ "wei chi", "维持" }, { "wei chu li qi", "微处理器" }, { "wei chuang", "微创" }, { "wei ci", "为此" }, { "wei da", "伟大" }, { "wei da fu xing", "伟大复兴" },
			{ "wei dao", "味道" }, { "wei dao", "未到" }, { "wei de", "韦德" }, { "wei de shi", "为的是" }, { "wei deng", "尾灯" }, { "wei deng lu", "未登录" },
			{ "wei di", "为敌" }, { "wei dian", "位点" }, { "wei dian zi", "微电子" }, { "wei ding", "未定" }, { "wei dong", "卫东" }, { "wei du", "唯独" },
			{ "wei du", "围堵" }, { "wei du", "惟独" }, { "wei du", "纬度" }, { "wei du", "维度" }, { "wei dui", "卫队" }, { "wei duo li ya", "维多利亚" },
			{ "wei e", "巍峨" }, { "wei er", "味儿" }, { "wei er", "威尔" }, { "wei er", "维尔" }, { "wei er shi", "威尔士" }, { "wei er si", "威尔斯" }, { "wei fa", "违法" },
			{ "wei fa an jian", "违法案件" }, { "wei fa fan zui", "违法犯罪" }, { "wei fa suo de", "违法所得" }, { "wei fa wei gui", "违法违规" }, { "wei fa wei ji", "违法违纪" },
			{ "wei fa xian", "未发现" }, { "wei fa xing wei", "违法行为" }, { "wei fan", "违反" }, { "wei fan gui ding", "违反规定" }, { "wei fang", "危房" },
			{ "wei fang", "潍坊" }, { "wei fang shi", "潍坊市" }, { "wei fen", "微分" }, { "wei feng", "威风" }, { "wei feng", "微风" }, { "wei fu", "为辅" },
			{ "wei gai", "为该" }, { "wei gan", "味甘" }, { "wei gang", "威刚" }, { "wei ge", "伟哥" }, { "wei gong", "围攻" }, { "wei guan", "为官" },
			{ "wei guan", "围观" }, { "wei guan", "微观" }, { "wei gui", "未归" }, { "wei gui", "违规" }, { "wei gui xing wei", "违规行为" }, { "wei guo", "为国" },
			{ "wei guo", "卫国" }, { "wei guo", "未果" }, { "wei guo", "魏国" }, { "wei hai", "为害" }, { "wei hai", "危害" }, { "wei hai", "威海" },
			{ "wei hai shi", "威海市" }, { "wei hai xing", "危害性" }, { "wei hao", "为好" }, { "wei he", "为何" }, { "wei he", "维和" }, { "wei he bu dui", "维和部队" },
			{ "wei he ru ci", "为何如此" }, { "wei hu", "维护" }, { "wei hu qi wei", "微乎其微" }, { "wei hui", "委会" }, { "wei hui yuan", "位会员" }, { "wei hun", "未婚" },
			{ "wei hun fu", "未婚夫" }, { "wei hun qi", "未婚妻" }, { "wei huo", "未获" }, { "wei ji", "危及" }, { "wei ji", "危急" }, { "wei ji", "危机" },
			{ "wei ji", "微机" }, { "wei ji", "维基" }, { "wei ji", "违纪" }, { "wei ji bai ke", "维基百科" }, { "wei ji chu de", "为基础的" }, { "wei ji fen", "微积分" },
			{ "wei ji gan", "危机感" }, { "wei jia", "为佳" }, { "wei jian", "未见" }, { "wei jiao", "围剿" }, { "wei jie", "慰藉" }, { "wei jin", "围巾" },
			{ "wei jin", "未尽" }, { "wei jin", "违禁" }, { "wei jin", "魏晋" }, { "wei jing", "味精" }, { "wei jing", "未经" }, { "wei jing shou quan", "未经授权" },
			{ "wei jing xu ke", "未经许可" }, { "wei jing yun xu", "未经允许" }, { "wei ju", "位居" }, { "wei ju", "微距" }, { "wei ju", "畏惧" }, { "wei jue", "味觉" },
			{ "wei jun", "为君" }, { "wei jun zi", "伪君子" }, { "wei ke xue", "伪科学" }, { "wei kong", "为空" }, { "wei kong", "唯恐" }, { "wei kong", "惟恐" },
			{ "wei kou", "胃口" }, { "wei kui yang", "胃溃疡" }, { "wei kun", "围困" }, { "wei la", "维拉" }, { "wei lai", "未来" }, { "wei lai fa zhan", "未来发展" },
			{ "wei lan", "围栏" }, { "wei lan", "蔚蓝" }, { "wei le", "为乐" }, { "wei le", "为了" }, { "wei li", "为例" }, { "wei li", "威力" }, { "wei li", "微利" },
			{ "wei li", "微粒" }, { "wei lian", "威廉" }, { "wei lian mu si", "威廉姆斯" }, { "wei liang", "微量" }, { "wei liang yuan su", "微量元素" },
			{ "wei lie", "伪劣" }, { "wei lie", "位列" }, { "wei ling", "为零" }, { "wei man", "未满" }, { "wei mei", "为每" }, { "wei mei", "唯美" },
			{ "wei meng", "威猛" }, { "wei mi", "微米" }, { "wei mi", "萎靡" }, { "wei mian", "卫冕" }, { "wei mian", "未免" }, { "wei miao", "为妙" },
			{ "wei miao", "微妙" }, { "wei min", "为民" }, { "wei ming", "为名" }, { "wei mu", "帷幕" }, { "wei na si", "维纳斯" }, { "wei nai", "喂奶" },
			{ "wei nan", "为难" }, { "wei nan", "危难" }, { "wei nei rui la", "委内瑞拉" }, { "wei neng", "未能" }, { "wei ni", "为你" }, { "wei ni", "维尼" },
			{ "wei ni si", "威尼斯" }, { "wei nin", "为您" }, { "wei nin fu wu", "为您服务" }, { "wei nin ti gong", "为您提供" }, { "wei pai", "委派" }, { "wei pan", "尾盘" },
			{ "wei qi", "为其" }, { "wei qi", "为妻" }, { "wei qi", "为期" }, { "wei qi", "围棋" }, { "wei qi", "尾气" }, { "wei qi", "维奇" }, { "wei qiang", "围墙" },
			{ "wei qing", "为情" }, { "wei qing", "卫青" }, { "wei qiu", "为求" }, { "wei qu", "委屈" }, { "wei qu de", "未取得" }, { "wei quan", "维权" },
			{ "wei qun", "围裙" }, { "wei rao", "围绕" }, { "wei ren", "为人" }, { "wei ren", "伟人" }, { "wei ren", "委任" }, { "wei ren chu shi", "为人处世" },
			{ "wei rong", "为荣" }, { "wei ruan", "微软" }, { "wei ruan gong si", "微软公司" }, { "wei ruo", "微弱" }, { "wei sa", "维萨" }, { "wei sha", "为啥" },
			{ "wei shan", "伪善" }, { "wei she", "威慑" }, { "wei shen", "为什" }, { "wei shen me", "为什么" } };
};
