package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN46 {
	public static String[][] pl = { { "tao ji", "套机" }, { "tao jia huan jia", "讨价还价" }, { "tao jian", "套件" }, { "tao jiao", "讨教" }, { "tao jin", "淘金" },
			{ "tao ke", "逃课" }, { "tao kong", "掏空" }, { "tao lao", "套牢" }, { "tao li", "套利" }, { "tao li", "桃李" }, { "tao li", "逃离" }, { "tao lu", "套路" },
			{ "tao lun", "讨论" }, { "tao lun hui", "讨论会" }, { "tao lun qu", "讨论区" }, { "tao ming", "逃命" }, { "tao pao", "逃跑" }, { "tao qi", "淘气" },
			{ "tao qi", "陶器" }, { "tao qian", "掏钱" }, { "tao ren xi huan", "讨人喜欢" }, { "tao shang", "套上" }, { "tao sheng", "逃生" }, { "tao shu", "套数" },
			{ "tao shu", "桃树" }, { "tao shui", "逃税" }, { "tao tai", "淘汰" }, { "tao tai luo hou", "淘汰落后" }, { "tao tai sai", "淘汰赛" }, { "tao tao", "套套" },
			{ "tao tao", "涛涛" }, { "tao tao", "淘淘" }, { "tao tao", "滔滔" }, { "tao tao bu jue", "滔滔不绝" }, { "tao tie", "饕餮" }, { "tao tou", "套头" },
			{ "tao tuo", "逃脱" }, { "tao wang", "逃亡" }, { "tao wang", "逃往" }, { "tao xian", "套现" }, { "tao xin", "讨薪" }, { "tao xing", "套型" },
			{ "tao yan", "讨厌" }, { "tao yao", "讨要" }, { "tao yao bao", "掏腰包" }, { "tao ye", "陶冶" }, { "tao yi", "逃逸" }, { "tao yong", "套用" },
			{ "tao yuan", "桃园" }, { "tao yuan", "桃源" }, { "tao yuan ming", "陶渊明" }, { "tao zai", "套在" }, { "tao zhai", "讨债" }, { "tao zhe", "套着" },
			{ "tao zhe", "陶喆" }, { "tao zhu", "套住" }, { "tao zhuang", "套装" }, { "tao zi", "套子" }, { "tao zi", "桃子" }, { "tao zou", "逃走" }, { "tao zui", "陶醉" },
			{ "te", "忑" }, { "te", "忒" }, { "te", "慝" }, { "te", "特" }, { "te", "蟘" }, { "te", "貣" }, { "te", "鋱" }, { "te", "铽" }, { "te ao", "特奥" },
			{ "te ao hui", "特奥会" }, { "te bie", "特别" }, { "te bie ban", "特别版" }, { "te bie guan zhu", "特别关注" }, { "te bie jie mu", "特别节目" },
			{ "te bie shi zai", "特别是在" }, { "te bie zhu yi", "特别注意" }, { "te chan", "特产" }, { "te chang", "特长" }, { "te ci", "特此" }, { "te da", "特大" },
			{ "te da xing", "特大型" }, { "te di", "特地" }, { "te dian", "特典" }, { "te dian", "特点" }, { "te ding", "特定" }, { "te duo", "特多" }, { "te er", "特尔" },
			{ "te gang", "特钢" }, { "te gong", "特供" }, { "te gong", "特工" }, { "te hui", "特惠" }, { "te ji", "特技" }, { "te ji", "特级" }, { "te ji", "特辑" },
			{ "te jia", "特价" }, { "te jia ji piao", "特价机票" }, { "te jing", "特警" }, { "te kan", "特刊" }, { "te kuai", "特快" }, { "te kun", "特困" },
			{ "te la", "特拉" }, { "te li", "特例" }, { "te li", "特里" }, { "te li du xing", "特立独行" }, { "te luo yi", "特洛伊" }, { "te ma", "特码" },
			{ "te mai", "特卖" }, { "te pai", "特派" }, { "te qu", "特区" }, { "te quan", "特权" }, { "te se", "特色" }, { "te se chan ye", "特色产业" }, { "te she", "特设" },
			{ "te shi", "特使" }, { "te shou", "特首" }, { "te shu", "特殊" }, { "te shu qing kuang", "特殊情况" }, { "te shu xing", "特殊性" },
			{ "te shu yao qiu", "特殊要求" }, { "te wu", "特务" }, { "te xiao", "特效" }, { "te xie", "特写" }, { "te xing", "特性" }, { "te xu", "特许" },
			{ "te xu jing ying", "特许经营" }, { "te yao", "特邀" }, { "te yi", "特异" }, { "te yi", "特意" }, { "te yi gong neng", "特异功能" }, { "te yi xing", "特异性" },
			{ "te you", "特有" }, { "te yue", "特约" }, { "te zheng", "特征" }, { "te zhi", "特制" }, { "te zhi", "特指" }, { "te zhi", "特质" }, { "te zhong", "特种" },
			{ "te zhong bing", "特种兵" }, { "te zhong bu dui", "特种部队" }, { "te zhong she bei", "特种设备" }, { "tei", "忒" }, { "teng", "滕" }, { "teng", "熥" },
			{ "teng", "疼" }, { "teng", "痋" }, { "teng", "籐" }, { "teng", "籘" }, { "teng", "縢" }, { "teng", "腾" }, { "teng", "藤" }, { "teng", "螣" },
			{ "teng", "誊" }, { "teng", "謄" }, { "teng", "邆" }, { "teng", "霯" }, { "teng", "騰" }, { "teng ai", "疼爱" }, { "teng chu", "腾出" },
			{ "teng de", "疼得" }, { "teng fei", "腾飞" }, { "teng kong", "腾空" }, { "teng long", "腾龙" }, { "teng tong", "疼痛" }, { "teng xun", "腾讯" },
			{ "teng xun gong si", "腾讯公司" }, { "ti", "体" }, { "ti", "俶" }, { "ti", "倜" }, { "ti", "偍" }, { "ti", "剃" }, { "ti", "剔" }, { "ti", "厗" },
			{ "ti", "啑" }, { "ti", "啼" }, { "ti", "嚏" }, { "ti", "姼" }, { "ti", "屉" }, { "ti", "屜" }, { "ti", "崹" }, { "ti", "嵜" }, { "ti", "徥" },
			{ "ti", "徲" }, { "ti", "悌" }, { "ti", "悐" }, { "ti", "惕" }, { "ti", "惿" }, { "ti", "戻" }, { "ti", "扌" }, { "ti", "提" }, { "ti", "揥" },
			{ "ti", "替" }, { "ti", "梯" }, { "ti", "楴" }, { "ti", "殢" }, { "ti", "洟" }, { "ti", "涕" }, { "ti", "渧" }, { "ti", "珶" }, { "ti", "瓋" },
			{ "ti", "磃" }, { "ti", "稊" }, { "ti", "籊" }, { "ti", "綈" }, { "ti", "緹" }, { "ti", "绨" }, { "ti", "缇" }, { "ti", "荑" }, { "ti", "蕛" },
			{ "ti", "薙" }, { "ti", "蝭" }, { "ti", "裼" }, { "ti", "褅" }, { "ti", "褆" }, { "ti", "詆" }, { "ti", "謕" }, { "ti", "趧" }, { "ti", "踢" },
			{ "ti", "蹄" }, { "ti", "躰" }, { "ti", "軆" }, { "ti", "迖" }, { "ti", "逖" }, { "ti", "醍" }, { "ti", "銻" }, { "ti", "鍗" }, { "ti", "锑" },
			{ "ti", "題" }, { "ti", "题" }, { "ti", "騠" }, { "ti", "體" }, { "ti", "鬄" }, { "ti", "鯷" }, { "ti", "鵜" }, { "ti", "鶗" }, { "ti", "鶙" },
			{ "ti", "鷈" }, { "ti", "鷤" }, { "ti", "鹈" }, { "ti an", "提案" }, { "ti ba", "提拔" }, { "ti bi", "提笔" }, { "ti biao", "体表" }, { "ti bu", "替补" },
			{ "ti cai", "体彩" }, { "ti cai", "体裁" }, { "ti cai", "题材" }, { "ti cao", "体操" }, { "ti chang", "提倡" }, { "ti che", "提车" }, { "ti cheng", "提成" },
			{ "ti chu", "剔除" }, { "ti chu", "提出" }, { "ti chu", "踢出" }, { "ti chu jian yi", "提出建议" }, { "ti chu lai", "提出来" }, { "ti chu shen qing", "提出申请" },
			{ "ti chu wen ti", "提出问题" }, { "ti chu yao qiu", "提出要求" }, { "ti ci", "题词" }, { "ti dai", "替代" }, { "ti dai pin", "替代品" }, { "ti dan", "提单" },
			{ "ti dao", "剃刀" }, { "ti dao", "提到" }, { "ti dao", "踢到" }, { "ti de", "体的" }, { "ti de", "踢得" }, { "ti dian", "提点" }, { "ti du", "梯度" },
			{ "ti dui", "梯队" }, { "ti fa", "体罚" }, { "ti fa", "提法" }, { "ti gang", "提纲" }, { "ti gao", "提高" }, { "ti gao jing ti", "提高警惕" },
			{ "ti gao qi ye", "提高企业" }, { "ti gao xiao lv", "提高效率" }, { "ti gao xue sheng", "提高学生" }, { "ti gao zi ji", "提高自己" }, { "ti gao zi shen", "提高自身" },
			{ "ti ge", "体格" }, { "ti ge", "提个" }, { "ti gong", "提供" }, { "ti gong dan bao", "提供担保" }, { "ti gong fu wu", "提供服务" },
			{ "ti gong ge zhong", "提供各种" }, { "ti gong mian fei", "提供免费" }, { "ti gong shang", "提供商" }, { "ti gong zhe", "提供者" },
			{ "ti gong zhi chi", "提供支持" }, { "ti guo", "提过" }, { "ti huan", "替换" }, { "ti hui", "体会" }, { "ti huo", "提货" }, { "ti ji", "体积" },
			{ "ti ji", "提及" }, { "ti ji xiao", "体积小" }, { "ti jia", "提价" }, { "ti jian", "体检" }, { "ti jiao", "提交" }, { "ti jiao ri qi", "提交日期" },
			{ "ti ku", "题库" }, { "ti kuan", "提款" }, { "ti li", "体力" }, { "ti li lao dong", "体力劳动" }, { "ti lian", "提炼" }, { "ti liang", "体谅" },
			{ "ti mian", "体面" }, { "ti ming", "提名" }, { "ti mu", "题目" }, { "ti nei", "体内" }, { "ti neng", "体能" }, { "ti ni", "替你" }, { "ti po", "体魄" },
			{ "ti qi", "提起" }, { "ti qi gong su", "提起公诉" }, { "ti qi su song", "提起诉讼" }, { "ti qian", "提前" }, { "ti qian huan dai", "提前还贷" },
			{ "ti qing", "提请" }, { "ti qiu", "踢球" }, { "ti qu", "提取" }, { "ti qu wu", "提取物" }, { "ti ren", "替人" }, { "ti shang", "提上" }, { "ti shen", "提神" },
			{ "ti shen", "替身" }, { "ti sheng", "提升" }, { "ti shi", "提示" }, { "ti shi xin xi", "提示信息" }, { "ti su", "提速" }, { "ti ta", "替他" },
			{ "ti tai", "体态" }, { "ti tan", "体坛" }, { "ti ti", "提提" }, { "ti tian", "梯田" }, { "ti tie", "体贴" }, { "ti tou", "剃头" }, { "ti wai", "体外" },
			{ "ti wai hua", "题外话" }, { "ti wei", "体位" }, { "ti wei", "体味" }, { "ti wei", "题为" }, { "ti wen", "体温" }, { "ti wen", "提问" }, { "ti wo", "替我" },
			{ "ti xi", "体系" }, { "ti xi jian she", "体系建设" }, { "ti xi jie gou", "体系结构" }, { "ti xian", "体现" }, { "ti xian", "提现" }, { "ti xian chu", "体现出" },
			{ "ti xiao", "体校" }, { "ti xie", "提携" }, { "ti xin diao dan", "提心吊胆" }, { "ti xing", "体型" }, { "ti xing", "体形" }, { "ti xing", "提醒" },
			{ "ti xing", "梯形" }, { "ti xing", "题型" }, { "ti xu", "体恤" }, { "ti xu dao", "剃须刀" }, { "ti yan", "体验" }, { "ti yao", "提要" }, { "ti ye", "体液" },
			{ "ti yi", "提议" }, { "ti yi jian", "提意见" }, { "ti yu", "体育" }, { "ti yu cai piao", "体育彩票" }, { "ti yu chang", "体育场" },
			{ "ti yu duan lian", "体育锻炼" }, { "ti yu guan", "体育馆" }, { "ti yu huo dong", "体育活动" }, { "ti yu ju", "体育局" }, { "ti yu ke", "体育课" },
			{ "ti yu pin dao", "体育频道" }, { "ti yu yong pin", "体育用品" }, { "ti yu yun dong", "体育运动" }, { "ti yu zhong xin", "体育中心" }, { "ti zao", "提早" },
			{ "ti zhe", "提着" }, { "ti zhen", "提振" }, { "ti zheng", "体征" }, { "ti zhi", "体制" }, { "ti zhi", "体质" }, { "ti zhi gai ge", "体制改革" },
			{ "ti zhong", "体重" }, { "ti zi", "梯子" }, { "ti zi", "蹄子" }, { "ti zu qiu", "踢足球" }, { "ti zui yang", "替罪羊" }, { "tian", "佃" }, { "tian", "倎" },
			{ "tian", "填" }, { "tian", "天" }, { "tian", "婖" }, { "tian", "屇" }, { "tian", "忝" }, { "tian", "恬" }, { "tian", "悿" }, { "tian", "捵" },
			{ "tian", "掭" }, { "tian", "搷" }, { "tian", "晪" }, { "tian", "殄" }, { "tian", "沺" }, { "tian", "淟" }, { "tian", "添" }, { "tian", "湉" },
			{ "tian", "琠" }, { "tian", "甛" }, { "tian", "甜" }, { "tian", "田" }, { "tian", "畋" }, { "tian", "畑" }, { "tian", "畠" }, { "tian", "痶" },
			{ "tian", "睼" }, { "tian", "碵" }, { "tian", "磌" }, { "tian", "窴" }, { "tian", "緂" }, { "tian", "腆" }, { "tian", "舑" }, { "tian", "舔" },
			{ "tian", "菾" }, { "tian", "賟" }, { "tian", "酟" }, { "tian", "鈿" }, { "tian", "钿" }, { "tian", "闐" }, { "tian", "阗" }, { "tian", "靦" },
			{ "tian", "顚" }, { "tian", "餂" }, { "tian", "鴫" }, { "tian", "鷆" }, { "tian", "鷏" }, { "tian a", "天啊" }, { "tian an", "天安" },
			{ "tian an men", "天安门" }, { "tian bao", "填报" }, { "tian bao", "天宝" }, { "tian bao zhi yuan", "填报志愿" }, { "tian bian", "天边" },
			{ "tian biao", "填表" }, { "tian bu", "填补" }, { "tian cai", "天才" }, { "tian chang di jiu", "天长地久" }, { "tian chao", "天朝" }, { "tian cheng", "天成" },
			{ "tian cheng", "天秤" }, { "tian cheng zuo", "天秤座" }, { "tian chi", "天池" }, { "tian chong", "填充" }, { "tian chuang", "天窗" }, { "tian ci", "填词" },
			{ "tian ci", "天赐" }, { "tian da", "天大" }, { "tian dan", "恬淡" }, { "tian dao", "天道" }, { "tian de", "天的" }, { "tian di", "天地" },
			{ "tian di", "天敌" }, { "tian di", "田地" }, { "tian di jian", "天地间" }, { "tian di xia", "天底下" }, { "tian dian", "甜点" }, { "tian e", "天鹅" },
			{ "tian fan di fu", "天翻地覆" }, { "tian fang ye tan", "天方夜谭" }, { "tian fen", "天分" }, { "tian fu", "天府" }, { "tian fu", "天赋" }, { "tian gao", "天高" },
			{ "tian gong", "天宫" }, { "tian guo", "天国" }, { "tian hai", "天海" }, { "tian hao", "填好" }, { "tian he", "天河" }, { "tian he qu", "天河区" },
			{ "tian hei", "天黑" }, { "tian hou", "天后" }, { "tian hua", "天华" }, { "tian hua", "天花" }, { "tian hua ban", "天花板" },
			{ "tian hua luan zhui", "天花乱坠" }, { "tian huang", "天皇" }, { "tian ji", "天机" }, { "tian ji", "天极" }, { "tian ji", "天际" }, { "tian jia", "天价" },
			{ "tian jia", "添加" }, { "tian jia ji", "添加剂" }, { "tian jian", "田间" }, { "tian jiang", "天降" }, { "tian jiao", "天骄" }, { "tian jie", "天界" },
			{ "tian jin", "天津" }, { "tian jin da xue", "天津大学" }, { "tian jin dui", "天津队" }, { "tian jin gang", "天津港" }, { "tian jin shi", "天津市" },
			{ "tian jing", "天井" }, { "tian jing", "恬静" }, { "tian jing", "田径" }, { "tian jing di yi", "天经地义" }, { "tian jiu", "天就" }, { "tian kong", "填空" },
			{ "tian kong", "天空" }, { "tian lai", "天来" }, { "tian lai", "天籁" }, { "tian lan", "天蓝" }, { "tian lei", "天雷" }, { "tian leng", "天冷" },
			{ "tian li", "天理" }, { "tian li", "田里" }, { "tian liang", "天亮" }, { "tian liang", "天量" }, { "tian liang", "田亮" }, { "tian liao", "填料" },
			{ "tian long", "天龙" }, { "tian long ba bu", "天龙八部" }, { "tian luan", "添乱" }, { "tian luo", "田螺" }, { "tian ma", "天马" }, { "tian ma fan", "添麻烦" },
			{ "tian ma xing kong", "天马行空" }, { "tian man", "填满" }, { "tian mei", "甜美" }, { "tian men", "天门" }, { "tian mi", "甜蜜" }, { "tian mi mi", "甜蜜蜜" },
			{ "tian ming", "天命" }, { "tian ming", "天明" }, { "tian na", "天哪" }, { "tian nan di bei", "天南地北" }, { "tian nei", "天内" }, { "tian pin", "甜品" },
			{ "tian ping", "天平" }, { "tian qi", "天气" }, { "tian qi yu bao", "天气预报" }, { "tian qian", "天前" }, { "tian qiao", "天桥" }, { "tian qing", "天晴" },
			{ "tian qing", "天青" }, { "tian ran", "天然" }, { "tian ran qi", "天然气" }, { "tian rang zhi bie", "天壤之别" }, { "tian re", "天热" },
			{ "tian ren he yi", "天人合一" }, { "tian ru", "填入" }, { "tian se", "天色" }, { "tian shan", "天山" }, { "tian shang", "填上" }, { "tian shang", "天上" },
			{ "tian shang", "添上" }, { "tian shang diao", "天上掉" }, { "tian shang ren jian", "天上人间" }, { "tian shen", "天神" }, { "tian sheng", "天生" },
			{ "tian sheng", "天盛" }, { "tian sheng li zhi", "天生丽质" }, { "tian shi", "天使" }, { "tian shi", "天师" }, { "tian shi", "天时" }, { "tian shi", "甜食" },
			{ "tian shu", "天书" }, { "tian shu", "天数" }, { "tian shui", "天水" }, { "tian tai", "天台" }, { "tian tan", "天坛" }, { "tian tang", "天堂" },
			{ "tian ti", "天体" }, { "tian tian", "天天" }, { "tian tian", "甜甜" }, { "tian tian", "田田" }, { "tian tian", "舔舔" }, { "tian tian de", "甜甜的" },
			{ "tian tian xiang shang", "天天向上" }, { "tian ting", "天庭" }, { "tian tong yuan", "天通苑" }, { "tian tou", "甜头" }, { "tian wai", "天外" },
			{ "tian wang", "天王" }, { "tian wang", "天网" }, { "tian wei", "天威" }, { "tian wei", "甜味" }, { "tian wen", "天文" }, { "tian wen shu zi", "天文数字" },
			{ "tian wen tai", "天文台" }, { "tian wen xue", "天文学" }, { "tian wen xue jia", "天文学家" }, { "tian xia", "天下" }, { "tian xia di yi", "天下第一" },
			{ "tian xia ren", "天下人" }, { "tian xia wu di", "天下无敌" }, { "tian xia wu zei", "天下无贼" }, { "tian xian", "天仙" }, { "tian xian", "天线" },
			{ "tian xiang", "天香" }, { "tian xie", "填写" }, { "tian xie", "天蝎" }, { "tian xie zuo", "天蝎座" }, { "tian xin", "天心" }, { "tian xin", "甜心" },
			{ "tian xing", "天性" }, { "tian xing", "天行" }, { "tian ya", "天崖" }, { "tian ya", "天涯" }, { "tian ya hai jiao", "天涯海角" }, { "tian ya lu", "天涯路" },
			{ "tian ya she qu", "天涯社区" }, { "tian ya za tan", "天涯杂谈" }, { "tian yan mi yu", "甜言蜜语" }, { "tian ye", "田野" }, { "tian yi", "天一" },
			{ "tian yi", "天意" }, { "tian yi wu feng", "天衣无缝" }, { "tian yin", "天音" }, { "tian you", "天佑" }, { "tian yu", "天娱" }, { "tian yu", "天宇" },
			{ "tian yuan", "天元" }, { "tian yuan", "田园" }, { "tian zai", "天灾" }, { "tian zhen", "天真" }, { "tian zheng", "天正" }, { "tian zhi", "天之" },
			{ "tian zhi", "添置" }, { "tian zhi dao", "天知道" }, { "tian zhi nei", "天之内" }, { "tian zhong", "田中" }, { "tian zhu", "天柱" }, { "tian zhu", "天竺" },
			{ "tian zhu jiao", "天主教" }, { "tian zi", "天子" }, { "tian zi", "天资" }, { "tiao", "佻" }, { "tiao", "儵" }, { "tiao", "咷" }, { "tiao", "嬥" },
			{ "tiao", "宨" }, { "tiao", "岧" }, { "tiao", "庣" }, { "tiao", "挑" }, { "tiao", "朓" }, { "tiao", "朷" }, { "tiao", "条" }, { "tiao", "條" },
			{ "tiao", "眺" }, { "tiao", "祒" }, { "tiao", "祧" }, { "tiao", "窕" }, { "tiao", "窱" }, { "tiao", "笤" }, { "tiao", "粜" }, { "tiao", "糶" },
			{ "tiao", "絩" }, { "tiao", "脁" }, { "tiao", "芀" }, { "tiao", "苕" }, { "tiao", "蓚" }, { "tiao", "蓨" }, { "tiao", "蜩" }, { "tiao", "覜" },
			{ "tiao", "誂" }, { "tiao", "調" }, { "tiao", "调" }, { "tiao", "趒" }, { "tiao", "跳" }, { "tiao", "迢" }, { "tiao", "鎥" }, { "tiao", "鞗" },
			{ "tiao", "髫" }, { "tiao", "鯈" }, { "tiao", "鰷" }, { "tiao", "鲦" }, { "tiao", "齠" }, { "tiao", "龆" }, { "tiao ban", "跳板" }, { "tiao bo", "挑拨" },
			{ "tiao cao", "跳槽" }, { "tiao cheng", "调成" }, { "tiao chu", "挑出" }, { "tiao chu", "调处" }, { "tiao chu", "跳出" }, { "tiao chu lai", "跳出来" },
			{ "tiao dao", "调到" }, { "tiao dao", "跳到" }, { "tiao de", "跳得" }, { "tiao di", "调低" }, { "tiao dong", "跳动" }, { "tiao dou", "挑逗" },
			{ "tiao duan xin", "条短信" }, { "tiao fu", "条幅" }, { "tiao gao", "调高" }, { "tiao gao", "跳高" }, { "tiao gui ding", "条规定" }, { "tiao guo", "跳过" },
			{ "tiao hao", "调好" }, { "tiao he", "调和" }, { "tiao ji", "调剂" }, { "tiao jia", "调价" }, { "tiao jian", "条件" }, { "tiao jian fan she", "条件反射" },
			{ "tiao jiao", "调教" }, { "tiao jie", "调节" }, { "tiao jie", "调解" }, { "tiao jin", "跳进" }, { "tiao kan", "调侃" }, { "tiao kong", "调控" },
			{ "tiao kong", "跳空" }, { "tiao kuan", "条款" }, { "tiao le", "跳了" }, { "tiao li", "条例" }, { "tiao li", "条理" }, { "tiao li", "调理" },
			{ "tiao liao", "调料" }, { "tiao lou", "跳楼" }, { "tiao lu", "条路" }, { "tiao ma", "条码" }, { "tiao mu", "条目" }, { "tiao pei", "调配" },
			{ "tiao pi", "调皮" }, { "tiao pin", "调频" }, { "tiao qi", "挑起" }, { "tiao qi", "跳起" }, { "tiao qi lai", "跳起来" }, { "tiao qing", "调情" },
			{ "tiao ru", "跳入" }, { "tiao san", "跳伞" }, { "tiao shang", "跳上" }, { "tiao sheng", "跳绳" }, { "tiao shi", "挑食" }, { "tiao shi", "调试" },
			{ "tiao shu", "条数" }, { "tiao shui", "跳水" }, { "tiao su", "调速" }, { "tiao ti", "挑剔" }, { "tiao tiao", "条条" }, { "tiao tiao", "跳跳" },
			{ "tiao tou", "跳投" }, { "tiao wang", "眺望" }, { "tiao wei", "调味" }, { "tiao wei liao", "调味料" }, { "tiao wei pin", "调味品" }, { "tiao wen", "条文" },
			{ "tiao wen", "条纹" }, { "tiao wen", "调温" }, { "tiao wu", "跳舞" }, { "tiao xi", "调戏" }, { "tiao xia", "跳下" }, { "tiao xia qu", "跳下去" },
			{ "tiao xian", "跳线" }, { "tiao xin", "挑衅" }, { "tiao xing ma", "条形码" }, { "tiao xiu", "调休" }, { "tiao xuan", "挑选" }, { "tiao yang", "调养" },
			{ "tiao yue", "条约" }, { "tiao yue", "跳跃" }, { "tiao yun", "调匀" }, { "tiao zao", "跳蚤" }, { "tiao zhan", "挑战" }, { "tiao zhan sai", "挑战赛" },
			{ "tiao zhan xing", "挑战性" }, { "tiao zhe", "挑着" }, { "tiao zhe", "跳着" }, { "tiao zheng", "调整" }, { "tiao zhi", "调制" }, { "tiao zhi", "调至" },
			{ "tiao zhuan", "跳转" }, { "tiao zi", "条子" }, { "tie", "僣" }, { "tie", "呫" }, { "tie", "帖" }, { "tie", "怗" }, { "tie", "惵" }, { "tie", "揲" },
			{ "tie", "萜" }, { "tie", "蛈" }, { "tie", "貼" }, { "tie", "贴" }, { "tie", "鉆" }, { "tie", "鋨" }, { "tie", "鐡" }, { "tie", "鐵" }, { "tie", "铁" },
			{ "tie", "餮" }, { "tie", "驖" }, { "tie", "鴩" }, { "tie ba", "贴吧" }, { "tie ban", "铁板" }, { "tie chu", "贴出" }, { "tie chui", "铁锤" },
			{ "tie dao", "贴到" }, { "tie dao", "铁道" }, { "tie dao bu", "铁道部" }, { "tie ding", "铁定" }, { "tie gan", "铁杆" }, { "tie guan yin", "铁观音" },
			{ "tie gui", "铁轨" }, { "tie guo", "铁锅" }, { "tie he", "贴合" }, { "tie jia", "铁甲" }, { "tie jiang", "铁匠" }, { "tie jin", "贴近" },
			{ "tie kuang", "铁矿" }, { "tie kuang shi", "铁矿石" }, { "tie lian", "铁链" }, { "tie ling", "铁岭" }, { "tie lu", "铁路" }, { "tie lu bao", "铁炉堡" },
			{ "tie lu jian she", "铁路建设" }, { "tie lu ju", "铁路局" }, { "tie lu yun shu", "铁路运输" }, { "tie men", "铁门" }, { "tie mo", "贴膜" }, { "tie pai", "贴牌" },
			{ "tie pi", "铁皮" }, { "tie pian", "贴片" }, { "tie qi", "铁骑" }, { "tie qie", "贴切" }, { "tie ren", "铁人" }, { "tie san jiao", "铁三角" },
			{ "tie shang", "贴上" }, { "tie shen", "贴身" }, { "tie si", "铁丝" }, { "tie ta", "铁塔" }, { "tie tong", "铁通" }, { "tie tu", "贴图" }, { "tie xi", "贴息" },
			{ "tie xian", "贴现" }, { "tie xin", "贴心" }, { "tie xue", "铁血" }, { "tie zai", "贴在" }, { "tie zhe", "贴着" }, { "tie zhi", "贴纸" }, { "tie zi", "帖子" },
			{ "tie zi", "贴子" }, { "ting", "亭" }, { "ting", "侹" }, { "ting", "停" }, { "ting", "厅" }, { "ting", "听" }, { "ting", "圢" }, { "ting", "娗" },
			{ "ting", "婷" }, { "ting", "嵉" }, { "ting", "庁" }, { "ting", "庭" }, { "ting", "廰" }, { "ting", "廳" }, { "ting", "廷" }, { "ting", "挺" },
			{ "ting", "桯" }, { "ting", "梃" }, { "ting", "楟" }, { "ting", "榳" }, { "ting", "汀" }, { "ting", "渟" }, { "ting", "濎" }, { "ting", "烃" },
			{ "ting", "烴" }, { "ting", "烶" }, { "ting", "珵" }, { "ting", "珽" }, { "ting", "町" }, { "ting", "筳" }, { "ting", "綎" }, { "ting", "聤" },
			{ "ting", "聴" }, { "ting", "聽" }, { "ting", "脡" }, { "ting", "艇" }, { "ting", "艼" }, { "ting", "莛" }, { "ting", "葶" }, { "ting", "蜓" },
			{ "ting", "蝏" }, { "ting", "諪" }, { "ting", "鋌" }, { "ting", "铤" }, { "ting", "閮" }, { "ting", "霆" }, { "ting", "頲" }, { "ting", "鼮" },
			{ "ting ba", "挺拔" }, { "ting bo", "停播" }, { "ting bo", "停泊" }, { "ting bu", "听不" }, { "ting bu dao", "听不到" }, { "ting bu dong", "听不懂" },
			{ "ting bu jian", "听不见" }, { "ting chan", "停产" }, { "ting che", "停车" }, { "ting che chang", "停车场" }, { "ting che fei", "停车费" },
			{ "ting che wei", "停车位" }, { "ting chu", "听出" }, { "ting cong", "听从" }, { "ting cuo", "听错" }, { "ting da", "挺大" }, { "ting dao", "听到" },
			{ "ting de", "听得" }, { "ting dian", "停电" }, { "ting diao", "停掉" }, { "ting dong", "听懂" }, { "ting dun", "停顿" }, { "ting duo", "挺多" },
			{ "ting fang", "停放" }, { "ting feng", "听风" }, { "ting feng", "霆锋" }, { "ting gao", "挺高" }, { "ting ge", "听歌" }, { "ting gong", "停工" },
			{ "ting gui", "挺贵" }, { "ting guo", "听过" }, { "ting hao", "挺好" }, { "ting hou", "听后" }, { "ting hua", "听话" }, { "ting huo", "停火" },
			{ "ting ji", "停机" }, { "ting jian", "听见" }, { "ting jiang", "听讲" }, { "ting jin", "挺进" }, { "ting jue", "听觉" }, { "ting kao", "停靠" },
			{ "ting ke", "停课" }, { "ting ke", "听课" }, { "ting kuai", "挺快" }, { "ting lai", "听来" }, { "ting lei", "挺累" }, { "ting li", "厅里" },
			{ "ting li", "听力" }, { "ting li", "挺立" }, { "ting liu", "停留" }, { "ting mang", "挺忙" }, { "ting nan", "挺难" }, { "ting ni", "听你" },
			{ "ting pai", "停牌" }, { "ting pan", "停盘" }, { "ting qi", "挺起" }, { "ting qi lai", "听起来" }, { "ting qian", "庭前" }, { "ting qing", "听清" },
			{ "ting qu", "听取" }, { "ting ren", "听人" }, { "ting sai", "停赛" }, { "ting shang qu", "听上去" }, { "ting shen", "庭审" }, { "ting shen er chu", "挺身而出" },
			{ "ting shuang", "挺爽" }, { "ting shui", "停水" }, { "ting shuo", "听说" }, { "ting ta", "听他" }, { "ting ta", "听她" }, { "ting tang", "厅堂" },
			{ "ting tian you ming", "听天由命" }, { "ting ting", "停停" }, { "ting ting", "听听" }, { "ting ting", "婷婷" }, { "ting tong", "听筒" }, { "ting wan", "听完" },
			{ "ting wen", "听闻" }, { "ting wo", "听我" }, { "ting wo shuo", "听我说" }, { "ting xia", "停下" }, { "ting xia lai", "停下来" }, { "ting xie", "停歇" },
			{ "ting xie", "听写" }, { "ting xin", "听信" }, { "ting yao", "停药" }, { "ting ye", "停业" }, { "ting yin yue", "听音乐" }, { "ting yong", "停用" },
			{ "ting yu", "听雨" }, { "ting yuan", "庭院" }, { "ting yuan", "挺远" }, { "ting yun", "停运" }, { "ting zai", "停在" }, { "ting zhang", "厅长" },
			{ "ting zhe", "停着" }, { "ting zhe", "听着" }, { "ting zhe", "听者" }, { "ting zhe", "挺着" }, { "ting zheng", "听证" }, { "ting zheng hui", "听证会" },
			{ "ting zhi", "停止" }, { "ting zhi", "停滞" }, { "ting zhi", "停职" }, { "ting zhi", "挺直" }, { "ting zhi bu qian", "停滞不前" }, { "ting zhong", "听众" },
			{ "ting zhu", "停住" }, { "ting zhu", "挺住" }, { "ting zi", "亭子" } };
};
