package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN37 {
	public static String[][] pl = { { "qian bai", "千百" }, { "qian bai nian", "千百年" }, { "qian ban", "前半" }, { "qian bao", "钱包" }, { "qian bei", "前辈" },
			{ "qian bei", "谦卑" }, { "qian bi", "倩碧" }, { "qian bi", "钱币" }, { "qian bi", "铅笔" }, { "qian bian", "前边" }, { "qian bian", "欠扁" },
			{ "qian bian wan hua", "千变万化" }, { "qian bo", "浅薄" }, { "qian bu", "前部" }, { "qian bu jiu", "前不久" }, { "qian cai", "钱财" }, { "qian cang", "潜藏" },
			{ "qian ceng", "千层" }, { "qian ceng", "浅层" }, { "qian cha wan bie", "千差万别" }, { "qian chang", "前场" }, { "qian che", "牵扯" },
			{ "qian che zhi jian", "前车之鉴" }, { "qian cheng", "前程" }, { "qian cheng", "虔诚" }, { "qian chu", "迁出" }, { "qian ci", "前次" }, { "qian dan", "签单" },
			{ "qian dao", "签到" }, { "qian dao", "迁到" }, { "qian dao hu", "千岛湖" }, { "qian ding", "签定" }, { "qian ding", "签订" },
			{ "qian ding he tong", "签订合同" }, { "qian dong", "牵动" }, { "qian du", "迁都" }, { "qian duan", "前段" }, { "qian duan", "前端" },
			{ "qian duan shi jian", "前段时间" }, { "qian duan zong xian", "前端总线" }, { "qian duo", "钱多" }, { "qian e", "前额" }, { "qian fa", "签发" },
			{ "qian fan", "遣返" }, { "qian fang", "前方" }, { "qian fang bai ji", "千方百计" }, { "qian fei", "欠费" }, { "qian fen zhi", "千分之" },
			{ "qian feng", "前锋" }, { "qian fu", "前夫" }, { "qian fu", "千伏" }, { "qian fu", "潜伏" }, { "qian fu qi", "潜伏期" }, { "qian gu", "千古" },
			{ "qian gua", "牵挂" }, { "qian gui", "钱柜" }, { "qian gui ze", "潜规则" }, { "qian he", "谦和" }, { "qian he tong", "签合同" }, { "qian hou", "前后" },
			{ "qian ji", "前几" }, { "qian ji nian", "前几年" }, { "qian ji tian", "前几天" }, { "qian jia", "千家" }, { "qian jia", "欠佳" },
			{ "qian jia wan hu", "千家万户" }, { "qian jiang", "钱江" }, { "qian jin", "前进" }, { "qian jin", "千斤" }, { "qian jin", "千金" }, { "qian jing", "前景" },
			{ "qian jiu", "前就" }, { "qian jiu", "迁就" }, { "qian jiu", "钱就" }, { "qian ju", "迁居" }, { "qian ke", "千克" }, { "qian kuan", "前款" },
			{ "qian kuan", "欠款" }, { "qian kun", "乾坤" }, { "qian lai", "前来" }, { "qian lai", "钱来" }, { "qian le", "欠了" }, { "qian li", "千里" },
			{ "qian li", "潜力" }, { "qian li gu", "潜力股" }, { "qian li ma", "千里马" }, { "qian li tiao tiao", "千里迢迢" }, { "qian li zhi wai", "千里之外" },
			{ "qian lian", "牵连" }, { "qian liang", "前两" }, { "qian liang tian", "前两天" }, { "qian lie", "前列" }, { "qian lie xian", "前列腺" },
			{ "qian lie xian yan", "前列腺炎" }, { "qian long", "乾隆" }, { "qian long", "千龙" }, { "qian lu", "前路" }, { "qian lun", "前轮" }, { "qian mai", "钱买" },
			{ "qian men", "前门" }, { "qian mi", "千米" }, { "qian mian", "前面" }, { "qian mian ban", "前面板" }, { "qian ming", "千名" }, { "qian ming", "签名" },
			{ "qian ming dang", "签名档" }, { "qian nan you", "前男友" }, { "qian ne", "钱呢" }, { "qian neng", "潜能" }, { "qian nian", "前年" }, { "qian nian", "千年" },
			{ "qian nv you", "前女友" }, { "qian pai", "前排" }, { "qian pian yi lv", "千篇一律" }, { "qian qi", "前妻" }, { "qian qi", "前期" },
			{ "qian qi bai guai", "千奇百怪" }, { "qian qi gong zuo", "前期工作" }, { "qian qian", "倩倩" }, { "qian qian", "千千" }, { "qian qian", "浅浅" },
			{ "qian qian", "纤纤" }, { "qian qian", "芊芊" }, { "qian qian", "钱钱" }, { "qian qian de", "浅浅的" }, { "qian qian hou hou", "前前后后" },
			{ "qian qian jing ting", "千千静听" }, { "qian qian wan wan", "千千万万" }, { "qian qiang", "牵强" }, { "qian qiu", "千秋" }, { "qian qu", "前去" },
			{ "qian que", "欠缺" }, { "qian rang", "谦让" }, { "qian ren", "前人" }, { "qian ren", "前任" }, { "qian ren", "千人" }, { "qian ri", "前日" },
			{ "qian ru", "嵌入" }, { "qian ru", "潜入" }, { "qian ru", "迁入" }, { "qian ru shi", "嵌入式" }, { "qian san", "前三" }, { "qian san ji du", "前三季度" },
			{ "qian san ming", "前三名" }, { "qian se", "浅色" }, { "qian shan", "千山" }, { "qian she", "牵涉" }, { "qian shen", "前身" }, { "qian sheng", "前生" },
			{ "qian shi", "前世" }, { "qian shi", "前十" }, { "qian shi", "钱是" }, { "qian shi ming", "前十名" }, { "qian shou", "牵手" }, { "qian shou", "签售" },
			{ "qian shou", "签收" }, { "qian shu", "前述" }, { "qian shu", "签署" }, { "qian shui", "潜水" }, { "qian shui ting", "潜水艇" }, { "qian shui yuan", "潜水员" },
			{ "qian si wan lv", "千丝万缕" }, { "qian song", "遣送" }, { "qian su lian", "前苏联" }, { "qian suo wei you", "前所未有" }, { "qian tai", "前台" },
			{ "qian tan", "浅谈" }, { "qian tang jiang", "钱塘江" }, { "qian tao", "嵌套" }, { "qian tao", "潜逃" }, { "qian ti", "前提" },
			{ "qian ti tiao jian", "前提条件" }, { "qian tian", "前天" }, { "qian tian", "前田" }, { "qian tiao", "欠条" }, { "qian ting", "潜艇" }, { "qian tou", "前头" },
			{ "qian tou", "牵头" }, { "qian tu", "前途" }, { "qian tu", "钱途" }, { "qian wa", "千瓦" }, { "qian wan", "前晚" }, { "qian wan", "千万" },
			{ "qian wan bie", "千万别" }, { "qian wan bu neng", "千万不能" }, { "qian wan bu yao", "千万不要" }, { "qian wan yuan", "千万元" }, { "qian wang", "前往" },
			{ "qian wang", "迁往" }, { "qian wei", "前卫" }, { "qian wen", "前文" }, { "qian wu", "前五" }, { "qian wu gu ren", "前无古人" }, { "qian xi", "前夕" },
			{ "qian xi", "前戏" }, { "qian xi", "浅析" }, { "qian xi", "迁徙" }, { "qian xia", "欠下" }, { "qian xia", "签下" }, { "qian xian", "前先" },
			{ "qian xian", "前线" }, { "qian xian", "浅显" }, { "qian xiao", "浅笑" }, { "qian xie", "前些" }, { "qian xie nian", "前些年" }, { "qian xin", "欠薪" },
			{ "qian xin", "潜心" }, { "qian xin wan ku", "千辛万苦" }, { "qian xing", "前行" }, { "qian xing", "潜行" }, { "qian xiong", "前胸" }, { "qian xu", "谦虚" },
			{ "qian xue sen", "钱学森" }, { "qian xun", "千寻" }, { "qian xun", "谦逊" }, { "qian yan", "前沿" }, { "qian yan", "前言" }, { "qian yan wan yu", "千言万语" },
			{ "qian ye", "前夜" }, { "qian yi", "前一" }, { "qian yi", "前移" }, { "qian yi", "千亿" }, { "qian yi", "歉意" }, { "qian yi", "浅议" }, { "qian yi", "迁移" },
			{ "qian yi mo hua", "潜移默化" }, { "qian yi shi", "潜意识" }, { "qian yi tian", "前一天" }, { "qian yin", "牵引" }, { "qian ying", "倩影" },
			{ "qian yu", "千余" }, { "qian yuan", "千元" }, { "qian yue", "签约" }, { "qian yue yi shi", "签约仪式" }, { "qian zai", "潜在" },
			{ "qian zai nan feng", "千载难逢" }, { "qian ze", "谴责" }, { "qian zhai", "欠债" }, { "qian zhan", "前瞻" }, { "qian zhan xing", "前瞻性" },
			{ "qian zhang", "签章" }, { "qian zhao", "前兆" }, { "qian zhao", "千兆" }, { "qian zhe", "前者" }, { "qian zhe", "牵着" }, { "qian zhen zi", "前阵子" },
			{ "qian zheng", "签证" }, { "qian zhi", "前置" }, { "qian zhi", "潜质" }, { "qian zhi", "牵制" }, { "qian zhi", "迁至" }, { "qian zhong shu", "钱钟书" },
			{ "qian zhu", "签注" }, { "qian zhuan", "前传" }, { "qian zhuang", "钱庄" }, { "qian zhui", "前缀" }, { "qian zi", "千字" }, { "qian zi", "签字" },
			{ "qian zi", "钳子" }, { "qian zi yi shi", "签字仪式" }, { "qian zong li", "前总理" }, { "qian zong tong", "前总统" }, { "qian zou", "前奏" },
			{ "qian zuo", "前作" }, { "qiang", "呛" }, { "qiang", "唴" }, { "qiang", "嗆" }, { "qiang", "墏" }, { "qiang", "墙" }, { "qiang", "墻" }, { "qiang", "嫱" },
			{ "qiang", "嬙" }, { "qiang", "嶈" }, { "qiang", "強" }, { "qiang", "强" }, { "qiang", "彊" }, { "qiang", "戕" }, { "qiang", "戗" }, { "qiang", "戧" },
			{ "qiang", "抢" }, { "qiang", "搶" }, { "qiang", "斨" }, { "qiang", "枪" }, { "qiang", "椌" }, { "qiang", "槍" }, { "qiang", "樯" }, { "qiang", "檣" },
			{ "qiang", "漒" }, { "qiang", "炝" }, { "qiang", "熗" }, { "qiang", "牄" }, { "qiang", "牆" }, { "qiang", "瑲" }, { "qiang", "矼" }, { "qiang", "繈" },
			{ "qiang", "繦" }, { "qiang", "羌" }, { "qiang", "羟" }, { "qiang", "羥" }, { "qiang", "羻" }, { "qiang", "腔" }, { "qiang", "艢" }, { "qiang", "蔷" },
			{ "qiang", "薔" }, { "qiang", "蘠" }, { "qiang", "蜣" }, { "qiang", "襁" }, { "qiang", "謒" }, { "qiang", "跄" }, { "qiang", "蹌" }, { "qiang", "蹡" },
			{ "qiang", "錆" }, { "qiang", "鎗" }, { "qiang", "鏘" }, { "qiang", "鏹" }, { "qiang", "锖" }, { "qiang", "锵" }, { "qiang", "镪" }, { "qiang", "鶬" },
			{ "qiang ban", "枪版" }, { "qiang bao", "强暴" }, { "qiang bi", "墙壁" }, { "qiang bi", "枪毙" }, { "qiang bian", "墙边" }, { "qiang da", "强大" },
			{ "qiang dao", "强盗" }, { "qiang dao", "抢到" }, { "qiang di", "强敌" }, { "qiang diao", "强调" }, { "qiang diao", "腔调" }, { "qiang du", "强度" },
			{ "qiang duan", "抢断" }, { "qiang dui", "强队" }, { "qiang duo", "抢夺" }, { "qiang fa", "枪法" }, { "qiang gong", "强攻" }, { "qiang gou", "抢购" },
			{ "qiang guan", "枪管" }, { "qiang guang", "强光" }, { "qiang guo", "强国" }, { "qiang guo", "抢过" }, { "qiang han", "强悍" }, { "qiang hua", "强化" },
			{ "qiang ji", "枪击" }, { "qiang ji", "羟基" }, { "qiang ji an", "枪击案" }, { "qiang jia", "强加" }, { "qiang jian", "强健" }, { "qiang jian", "强奸" },
			{ "qiang jian le", "强奸了" }, { "qiang jiao", "墙角" }, { "qiang jie", "抢劫" }, { "qiang jin", "强劲" }, { "qiang jing", "强劲" }, { "qiang jiu", "抢救" },
			{ "qiang kou", "枪口" }, { "qiang le", "抢了" }, { "qiang li", "强力" }, { "qiang lie", "强烈" }, { "qiang lie jian yi", "强烈建议" },
			{ "qiang lie tui jian", "强烈推荐" }, { "qiang lie yao qiu", "强烈要求" }, { "qiang mian", "墙面" }, { "qiang nei", "腔内" }, { "qiang po", "强迫" },
			{ "qiang po zheng", "强迫症" }, { "qiang qi ye", "强企业" }, { "qiang qian", "抢钱" }, { "qiang qiang", "强强" }, { "qiang qiu", "强求" },
			{ "qiang quan", "强权" }, { "qiang ren", "强人" }, { "qiang ren", "强忍" }, { "qiang ruo", "强弱" }, { "qiang sha", "枪杀" }, { "qiang shang", "墙上" },
			{ "qiang shen", "强身" }, { "qiang sheng", "强生" }, { "qiang sheng", "强盛" }, { "qiang sheng", "强省" }, { "qiang sheng", "枪声" }, { "qiang shi", "强势" },
			{ "qiang shi", "强市" }, { "qiang shou", "抢手" }, { "qiang shou", "枪手" }, { "qiang tan", "抢滩" }, { "qiang ti", "墙体" }, { "qiang tou", "墙头" },
			{ "qiang wei", "蔷薇" }, { "qiang xian", "抢先" }, { "qiang xian", "抢险" }, { "qiang xiang", "强项" }, { "qiang xiao", "强效" }, { "qiang xie", "枪械" },
			{ "qiang xing", "强行" }, { "qiang xiu", "抢修" }, { "qiang yan", "抢眼" }, { "qiang ying", "强硬" }, { "qiang you li", "强有力" }, { "qiang yu", "强于" },
			{ "qiang zhan", "抢占" }, { "qiang zhan", "枪战" }, { "qiang zhe", "强者" }, { "qiang zhe", "抢着" }, { "qiang zhi", "墙纸" }, { "qiang zhi", "强制" },
			{ "qiang zhi", "枪支" }, { "qiang zhi cuo shi", "强制措施" }, { "qiang zhi xing", "强制性" }, { "qiang zhi zhi xing", "强制执行" }, { "qiang zhu", "抢注" },
			{ "qiang zhuang", "强壮" }, { "qiang zou", "抢走" }, { "qiao", "乔" }, { "qiao", "侨" }, { "qiao", "俏" }, { "qiao", "僑" }, { "qiao", "劁" },
			{ "qiao", "喬" }, { "qiao", "嘺" }, { "qiao", "噭" }, { "qiao", "墝" }, { "qiao", "墽" }, { "qiao", "壳" }, { "qiao", "嫶" }, { "qiao", "峤" },
			{ "qiao", "峭" }, { "qiao", "嶠" }, { "qiao", "巧" }, { "qiao", "帩" }, { "qiao", "幧" }, { "qiao", "悄" }, { "qiao", "愀" }, { "qiao", "憔" },
			{ "qiao", "摮" }, { "qiao", "撬" }, { "qiao", "敲" }, { "qiao", "桥" }, { "qiao", "樵" }, { "qiao", "橇" }, { "qiao", "橋" }, { "qiao", "殼" },
			{ "qiao", "潐" }, { "qiao", "燋" }, { "qiao", "犞" }, { "qiao", "瞧" }, { "qiao", "硗" }, { "qiao", "磝" }, { "qiao", "磽" }, { "qiao", "礄" },
			{ "qiao", "礉" }, { "qiao", "窍" }, { "qiao", "竅" }, { "qiao", "繑" }, { "qiao", "缲" }, { "qiao", "翘" }, { "qiao", "翹" }, { "qiao", "荍" },
			{ "qiao", "荞" }, { "qiao", "蕎" }, { "qiao", "蟜" }, { "qiao", "誚" }, { "qiao", "譑" }, { "qiao", "譙" }, { "qiao", "诮" }, { "qiao", "谯" },
			{ "qiao", "趫" }, { "qiao", "趬" }, { "qiao", "跷" }, { "qiao", "踍" }, { "qiao", "蹺" }, { "qiao", "蹻" }, { "qiao", "躈" }, { "qiao", "郻" },
			{ "qiao", "鄡" }, { "qiao", "釥" }, { "qiao", "鍬" }, { "qiao", "锹" }, { "qiao", "雀" }, { "qiao", "鞒" }, { "qiao", "鞘" }, { "qiao", "頝" },
			{ "qiao", "髜" }, { "qiao bi", "峭壁" }, { "qiao bu qi", "瞧不起" }, { "qiao bu si", "乔布斯" }, { "qiao cui", "憔悴" }, { "qiao da", "敲打" },
			{ "qiao dan", "乔丹" }, { "qiao ding", "敲定" }, { "qiao duan", "桥段" }, { "qiao feng", "乔峰" }, { "qiao he", "巧合" }, { "qiao ji", "敲击" },
			{ "qiao jian", "瞧见" }, { "qiao kai", "敲开" }, { "qiao ke li", "巧克力" }, { "qiao le", "敲了" }, { "qiao li", "俏丽" }, { "qiao liang", "桥梁" },
			{ "qiao mai", "荞麦" }, { "qiao men", "敲门" }, { "qiao men", "窍门" }, { "qiao mian", "桥面" }, { "qiao miao", "巧妙" }, { "qiao mu", "乔木" },
			{ "qiao pai", "壳牌" }, { "qiao pi", "俏皮" }, { "qiao qi", "翘起" }, { "qiao qiao", "悄悄" }, { "qiao qiao", "瞧瞧" }, { "qiao qiao", "翘翘" },
			{ "qiao qiao de", "悄悄的" }, { "qiao qiao hua", "悄悄话" }, { "qiao ran", "悄然" }, { "qiao shang", "桥上" }, { "qiao shou", "翘首" }, { "qiao tou", "桥头" },
			{ "qiao wu sheng xi", "悄无声息" }, { "qiao xia", "桥下" }, { "qiao xiang", "敲响" }, { "qiao yan ling se", "巧言令色" }, { "qiao yu", "巧遇" },
			{ "qiao zha", "敲诈" }, { "qiao zhe", "瞧着" }, { "qiao zhen", "桥镇" }, { "qiao zhi", "乔治" }, { "qie", "且" }, { "qie", "伽" }, { "qie", "倢" },
			{ "qie", "切" }, { "qie", "厒" }, { "qie", "妾" }, { "qie", "怯" }, { "qie", "惬" }, { "qie", "愜" }, { "qie", "慊" }, { "qie", "挈" }, { "qie", "朅" },
			{ "qie", "椄" }, { "qie", "洯" }, { "qie", "疌" }, { "qie", "癿" }, { "qie", "窃" }, { "qie", "竊" }, { "qie", "箧" }, { "qie", "篋" }, { "qie", "緁" },
			{ "qie", "茄" }, { "qie", "藒" }, { "qie", "蛣" }, { "qie", "蛪" }, { "qie", "趄" }, { "qie", "踥" }, { "qie", "郄" }, { "qie", "鍥" }, { "qie", "鐑" },
			{ "qie", "锲" }, { "qie", "鯜" }, { "qie bu", "且不" }, { "qie bu shuo", "且不说" }, { "qie cheng", "切成" }, { "qie chu", "切除" }, { "qie chu shu", "切除术" },
			{ "qie cuo", "切磋" }, { "qie duan", "切断" }, { "qie er bu she", "锲而不舍" }, { "qie er xi", "切尔西" }, { "qie ge", "切割" }, { "qie he", "切合" },
			{ "qie huan", "切换" }, { "qie huan dao", "切换到" }, { "qie ji", "切忌" }, { "qie ji", "切记" }, { "qie kai", "切开" }, { "qie kou", "切口" },
			{ "qie mo", "切莫" }, { "qie ni", "切尼" }, { "qie nuo", "怯懦" }, { "qie pian", "切片" }, { "qie qie", "切切" }, { "qie qu", "窃取" }, { "qie ru", "切入" },
			{ "qie ru dian", "切入点" }, { "qie shen", "切身" }, { "qie shen li yi", "切身利益" }, { "qie shi", "切实" }, { "qie shi jia qiang", "切实加强" },
			{ "qie shi ke xing", "切实可行" }, { "qie shi zuo hao", "切实做好" }, { "qie sui", "切碎" }, { "qie ting", "窃听" }, { "qie wu", "切勿" }, { "qie xi", "窃喜" },
			{ "qie xiao", "切削" }, { "qie yi", "惬意" }, { "qie you", "且有" }, { "qie zei", "窃贼" }, { "qie zi", "茄子" }, { "qin", "亲" }, { "qin", "侵" },
			{ "qin", "儭" }, { "qin", "勤" }, { "qin", "吣" }, { "qin", "唚" }, { "qin", "嗪" }, { "qin", "噙" }, { "qin", "坅" }, { "qin", "埁" }, { "qin", "埐" },
			{ "qin", "墐" }, { "qin", "寑" }, { "qin", "寝" }, { "qin", "寢" }, { "qin", "嶔" }, { "qin", "嶜" }, { "qin", "庈" }, { "qin", "廑" }, { "qin", "忴" },
			{ "qin", "慬" }, { "qin", "懃" }, { "qin", "扲" }, { "qin", "揿" }, { "qin", "撳" }, { "qin", "擒" }, { "qin", "斳" }, { "qin", "昑" }, { "qin", "梫" },
			{ "qin", "檎" }, { "qin", "櫬" }, { "qin", "欽" }, { "qin", "沁" }, { "qin", "溱" }, { "qin", "澿" }, { "qin", "瀙" }, { "qin", "琴" }, { "qin", "瘽" },
			{ "qin", "矜" }, { "qin", "禽" }, { "qin", "秦" }, { "qin", "笉" }, { "qin", "耹" }, { "qin", "肣" }, { "qin", "芩" }, { "qin", "芹" }, { "qin", "菣" },
			{ "qin", "菳" }, { "qin", "藽" }, { "qin", "蘄" }, { "qin", "蚙" }, { "qin", "螓" }, { "qin", "螼" }, { "qin", "衾" }, { "qin", "覃" }, { "qin", "親" },
			{ "qin", "鈙" }, { "qin", "鋟" }, { "qin", "钦" }, { "qin", "锓" }, { "qin", "雂" }, { "qin", "靲" }, { "qin", "頜" }, { "qin", "顉" }, { "qin", "駸" },
			{ "qin", "鳹" }, { "qin ai", "亲爱" }, { "qin bi", "亲笔" }, { "qin cai", "芹菜" }, { "qin chao", "秦朝" }, { "qin fan", "侵犯" },
			{ "qin fan le nin", "侵犯了您" }, { "qin fen", "勤奋" }, { "qin gong jian xue", "勤工俭学" }, { "qin guo", "秦国" }, { "qin hai", "侵害" }, { "qin han", "秦汉" },
			{ "qin he", "亲和" }, { "qin he li", "亲和力" }, { "qin hua ri jun", "侵华日军" }, { "qin huai", "秦淮" }, { "qin huang dao", "秦皇岛" }, { "qin hui", "秦桧" },
			{ "qin jin", "亲近" }, { "qin kou", "亲口" }, { "qin kuai", "勤快" }, { "qin lao", "勤劳" }, { "qin le", "亲了" }, { "qin lei", "禽类" }, { "qin li", "亲历" },
			{ "qin lin", "亲临" }, { "qin ling", "秦岭" }, { "qin liu gan", "禽流感" }, { "qin lue", "侵略" }, { "qin lue zhe", "侵略者" }, { "qin men", "亲们" },
			{ "qin mi", "亲密" }, { "qin mi jie chu", "亲密接触" }, { "qin mian", "勤勉" }, { "qin min", "亲民" }, { "qin min dang", "亲民党" }, { "qin ni", "亲昵" },
			{ "qin pei", "钦佩" }, { "qin peng", "亲朋" }, { "qin peng hao you", "亲朋好友" }, { "qin qi", "亲戚" }, { "qin qie", "亲切" }, { "qin qie gan", "亲切感" },
			{ "qin qin", "亲亲" }, { "qin qing", "亲情" }, { "qin quan", "侵权" }, { "qin quan xing wei", "侵权行为" }, { "qin re", "亲热" }, { "qin ren", "亲人" },
			{ "qin ru", "侵入" }, { "qin shen", "亲身" }, { "qin shen jing li", "亲身经历" }, { "qin shen ti yan", "亲身体验" }, { "qin sheng", "亲生" },
			{ "qin sheng", "琴声" }, { "qin shi", "侵蚀" }, { "qin shi", "寝室" }, { "qin shi huang", "秦始皇" }, { "qin shou", "亲手" }, { "qin shou", "禽兽" },
			{ "qin shou bu ru", "禽兽不如" }, { "qin shu", "亲属" }, { "qin tun", "侵吞" }, { "qin wang", "亲王" }, { "qin wang", "秦王" }, { "qin wen", "亲吻" },
			{ "qin xi", "侵袭" }, { "qin xian", "琴弦" }, { "qin xin", "亲信" }, { "qin yan", "亲眼" }, { "qin yan jian", "亲眼见" }, { "qin yan mu du", "亲眼目睹" },
			{ "qin you", "亲友" }, { "qin yu", "勤于" }, { "qin zhan", "侵占" }, { "qin zhou", "钦州" }, { "qin zi", "亲子" }, { "qin zi", "亲自" }, { "qing", "亲" },
			{ "qing", "倾" }, { "qing", "傾" }, { "qing", "凊" }, { "qing", "勍" }, { "qing", "卿" }, { "qing", "圊" }, { "qing", "庆" }, { "qing", "廎" },
			{ "qing", "情" }, { "qing", "慶" }, { "qing", "掅" }, { "qing", "擎" }, { "qing", "擏" }, { "qing", "晴" }, { "qing", "樈" }, { "qing", "檠" },
			{ "qing", "氢" }, { "qing", "氫" }, { "qing", "氰" }, { "qing", "淸" }, { "qing", "清" }, { "qing", "渹" }, { "qing", "漀" }, { "qing", "硜" },
			{ "qing", "碃" }, { "qing", "磬" }, { "qing", "箐" }, { "qing", "綮" }, { "qing", "罄" }, { "qing", "苘" }, { "qing", "葝" }, { "qing", "蜻" },
			{ "qing", "請" }, { "qing", "謦" }, { "qing", "请" }, { "qing", "輕" }, { "qing", "轻" }, { "qing", "郬" }, { "qing", "鑋" }, { "qing", "靑" },
			{ "qing", "青" }, { "qing", "靘" }, { "qing", "頃" }, { "qing", "顷" }, { "qing", "鲭" }, { "qing", "黥" }, { "qing ai", "情爱" }, { "qing an", "请安" },
			{ "qing an", "请按" }, { "qing ba", "请把" }, { "qing bai", "清白" }, { "qing bao", "情报" }, { "qing bian", "轻便" }, { "qing bie", "请别" },
			{ "qing bo", "轻薄" }, { "qing bu yao", "请不要" }, { "qing bu zi jin", "情不自禁" }, { "qing cai", "青菜" }, { "qing can kao", "请参考" },
			{ "qing can yue", "请参阅" }, { "qing cang", "清仓" }, { "qing cao", "情操" }, { "qing cao", "青草" }, { "qing cha", "清查" }, { "qing cha", "清茶" },
			{ "qing chang", "情场" }, { "qing chang", "清偿" }, { "qing chao", "清朝" }, { "qing che", "清澈" }, { "qing chen", "清晨" }, { "qing cheng", "倾城" },
			{ "qing cheng shan", "青城山" }, { "qing chou", "情仇" }, { "qing chu", "清楚" }, { "qing chu", "清除" }, { "qing chun", "清纯" }, { "qing chun", "青春" },
			{ "qing chun dou", "青春痘" }, { "qing chun qi", "青春期" }, { "qing cui", "清脆" }, { "qing cui", "青翠" }, { "qing da jia", "请大家" }, { "qing dai", "清代" },
			{ "qing dan", "清单" }, { "qing dan", "清淡" }, { "qing dao", "倾倒" }, { "qing dao", "请到" }, { "qing dao", "青岛" }, { "qing dao pi jiu", "青岛啤酒" },
			{ "qing dao shi", "青岛市" }, { "qing deng dai", "请等待" }, { "qing deng lu", "请登录" }, { "qing di", "情敌" }, { "qing dian", "庆典" },
			{ "qing dian", "清点" }, { "qing dian", "轻点" }, { "qing dian ji", "请点击" }, { "qing diao", "情调" }, { "qing du", "清毒" }, { "qing du", "轻度" },
			{ "qing duo", "请多" }, { "qing er yi ju", "轻而易举" }, { "qing fa", "请发" }, { "qing fang wen", "请访问" }, { "qing feng", "清风" }, { "qing feng", "轻风" },
			{ "qing fu", "情妇" }, { "qing fu", "轻抚" }, { "qing fu", "轻浮" }, { "qing gan", "情感" }, { "qing gan tian di", "情感天地" }, { "qing gao", "清高" },
			{ "qing gao shou", "请高手" }, { "qing gao su wo", "请告诉我" }, { "qing gao zhi", "请告知" }, { "qing ge", "情歌" }, { "qing ge wei", "请各位" },
			{ "qing gei", "请给" }, { "qing gei wo", "请给我" }, { "qing gong", "庆功" }, { "qing gong", "清宫" }, { "qing gong", "轻功" }, { "qing gong", "轻工" },
			{ "qing gong ye", "轻工业" }, { "qing guan", "清关" }, { "qing guan", "清官" }, { "qing guang yan", "青光眼" }, { "qing gui", "轻轨" }, { "qing hai", "青海" },
			{ "qing hai hu", "青海湖" }, { "qing hai sheng", "青海省" }, { "qing he", "庆贺" }, { "qing he", "清河" }, { "qing hua", "情话" }, { "qing hua", "清华" },
			{ "qing hua", "青花" }, { "qing hua da xue", "清华大学" }, { "qing hua tong fang", "清华同方" }, { "qing huai", "情怀" }, { "qing ji", "情急" },
			{ "qing ji shi", "请及时" }, { "qing ji zhu", "请记住" }, { "qing jia", "请假" }, { "qing jia", "请加" }, { "qing jia dang chan", "倾家荡产" },
			{ "qing jian", "请柬" }, { "qing jian", "请见" }, { "qing jiang", "清江" }, { "qing jiang", "请将" }, { "qing jiao", "请教" }, { "qing jiao", "青椒" },
			{ "qing jie", "情结" }, { "qing jie", "情节" }, { "qing jie", "清洁" }, { "qing jie gong", "清洁工" }, { "qing jie ji", "清洁剂" },
			{ "qing jie neng yuan", "清洁能源" }, { "qing jie sheng chan", "清洁生产" }, { "qing jie yan zhong", "情节严重" }, { "qing jin", "请进" },
			{ "qing jin kuai", "请尽快" }, { "qing jin lai", "请进来" }, { "qing jing", "情境" }, { "qing jing", "情景" }, { "qing jing", "清净" }, { "qing jing", "清静" },
			{ "qing jun", "清军" }, { "qing kan", "请看" }, { "qing ke", "请客" }, { "qing kong", "晴空" }, { "qing kong", "清空" }, { "qing kuai", "轻快" },
			{ "qing kuang", "情况" }, { "qing kuang", "轻狂" }, { "qing kuang fen xi", "情况分析" }, { "qing kuang hui bao", "情况汇报" }, { "qing lai", "请来" },
			{ "qing lai", "青睐" }, { "qing lang", "晴朗" }, { "qing leng", "清冷" }, { "qing li", "倾力" }, { "qing li", "情理" }, { "qing li", "清丽" },
			{ "qing li", "清理" }, { "qing li ji", "请立即" }, { "qing li zheng dun", "清理整顿" }, { "qing li zhi zhong", "情理之中" }, { "qing lian", "清廉" },
			{ "qing lian xi", "请联系" }, { "qing liang", "清亮" }, { "qing liang", "清凉" }, { "qing ling", "清零" }, { "qing liu yan", "请留言" }, { "qing long", "青龙" },
			{ "qing lou", "青楼" }, { "qing lv", "情侣" }, { "qing mei", "青梅" }, { "qing mei su", "青霉素" }, { "qing mei zhu ma", "青梅竹马" },
			{ "qing miao dan xie", "轻描淡写" }, { "qing mie", "轻蔑" }, { "qing ming", "清明" }, { "qing ming jie", "清明节" }, { "qing mo", "清末" }, { "qing mu", "倾慕" },
			{ "qing ni", "请你" }, { "qing nian", "青年" }, { "qing nian dui", "青年队" }, { "qing nian jiao shi", "青年教师" }, { "qing nian ren", "青年人" },
			{ "qing nian xue sheng", "青年学生" }, { "qing niao", "青鸟" }, { "qing nin", "请您" }, { "qing piao piao", "轻飘飘" }, { "qing pin", "清贫" },
			{ "qing pu", "青浦" }, { "qing qi", "氢气" }, { "qing qian", "清欠" }, { "qing qiao", "轻巧" }, { "qing qing", "倾情" }, { "qing qing", "清清" },
			{ "qing qing", "轻轻" }, { "qing qing", "青青" }, { "qing qing chu chu", "清清楚楚" }, { "qing qing song song", "轻轻松松" }, { "qing qiu", "清秋" },
			{ "qing qiu", "请求" }, { "qing qiu quan", "请求权" }, { "qing qu", "情趣" }, { "qing quan", "清泉" }, { "qing que ren", "请确认" }, { "qing re", "清热" },
			{ "qing re jie du", "清热解毒" }, { "qing ren", "情人" }, { "qing ren", "请人" }, { "qing ren jie", "情人节" }, { "qing rou", "轻柔" }, { "qing sao", "清扫" },
			{ "qing se", "情色" }, { "qing se", "青涩" }, { "qing se", "青色" }, { "qing shan", "青山" }, { "qing shan lv shui", "青山绿水" }, { "qing shang", "情商" },
			{ "qing shang", "轻伤" } };
};
