package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN16 {
	public static String[][] pl = { { "gong ce", "公厕" }, { "gong ce", "公测" }, { "gong cha", "公差" }, { "gong chan", "共产" }, { "gong chan dang", "共产党" },
			{ "gong chan dang ren", "共产党人" }, { "gong chan dang yuan", "共产党员" }, { "gong chan zhu yi", "共产主义" }, { "gong chang", "共唱" },
			{ "gong chang", "工厂" }, { "gong che", "公车" }, { "gong chen", "功臣" }, { "gong cheng", "工程" }, { "gong cheng", "攻城" }, { "gong cheng bu", "工程部" },
			{ "gong cheng gong si", "工程公司" }, { "gong cheng ji shu", "工程技术" }, { "gong cheng ji xie", "工程机械" }, { "gong cheng jian li", "工程监理" },
			{ "gong cheng jian she", "工程建设" }, { "gong cheng kuan", "工程款" }, { "gong cheng liang", "工程量" }, { "gong cheng ming jiu", "功成名就" },
			{ "gong cheng she ji", "工程设计" }, { "gong cheng shi", "工程师" }, { "gong cheng shi gong", "工程施工" }, { "gong cheng xi", "工程系" },
			{ "gong cheng xiang mu", "工程项目" }, { "gong cheng xue", "工程学" }, { "gong cheng xue yuan", "工程学院" }, { "gong cheng zao jia", "工程造价" },
			{ "gong cheng zhi liang", "工程质量" }, { "gong chi", "公尺" }, { "gong chu", "共处" }, { "gong chuang", "共创" }, { "gong cun", "共存" }, { "gong da", "工大" },
			{ "gong da", "攻打" }, { "gong da yu qiu", "供大于求" }, { "gong dan", "工单" }, { "gong dang", "工党" }, { "gong dao", "公道" }, { "gong de", "公德" },
			{ "gong de", "功德" }, { "gong di", "功底" }, { "gong di", "工地" }, { "gong dian", "供电" }, { "gong dian", "宫殿" }, { "gong dian gong si", "供电公司" },
			{ "gong dian ju", "供电局" }, { "gong du", "共度" }, { "gong du", "攻读" }, { "gong fa", "功法" }, { "gong fang", "供方" }, { "gong fang", "公房" },
			{ "gong fang", "功放" }, { "gong fang", "攻防" }, { "gong fei", "公费" }, { "gong fen", "公分" }, { "gong fen", "共分" }, { "gong feng", "供奉" },
			{ "gong fu", "功夫" }, { "gong fu", "工夫" }, { "gong gan", "公干" }, { "gong gao", "供稿" }, { "gong gao", "公告" }, { "gong gei", "供给" },
			{ "gong gong", "公公" }, { "gong gong", "公共" }, { "gong gong an quan", "公共安全" }, { "gong gong cai zheng", "公共财政" }, { "gong gong chan pin", "公共产品" },
			{ "gong gong chang he", "公共场合" }, { "gong gong chang suo", "公共场所" }, { "gong gong fu wu", "公共服务" }, { "gong gong guan li", "公共管理" },
			{ "gong gong guan xi", "公共关系" }, { "gong gong jiao tong", "公共交通" }, { "gong gong li yi", "公共利益" }, { "gong gong qi che", "公共汽车" },
			{ "gong gong she shi", "公共设施" }, { "gong gong shi wu", "公共事务" }, { "gong gong wei sheng", "公共卫生" }, { "gong gong zheng ce", "公共政策" },
			{ "gong gu", "巩固" }, { "gong guan", "公关" }, { "gong guan", "公馆" }, { "gong guan", "攻关" }, { "gong guan bu", "公关部" }, { "gong hang", "工行" },
			{ "gong hao", "功耗" }, { "gong hao", "工号" }, { "gong he", "共和" }, { "gong he dang", "共和党" }, { "gong he guo", "共和国" }, { "gong hou", "恭候" },
			{ "gong hui", "公会" }, { "gong hui", "工会" }, { "gong hui zhu xi", "工会主席" }, { "gong hui zu zhi", "工会组织" }, { "gong huo", "供货" },
			{ "gong huo shang", "供货商" }, { "gong ji", "供给" }, { "gong ji", "公鸡" }, { "gong ji", "共计" }, { "gong ji", "功绩" }, { "gong ji", "攻击" },
			{ "gong ji jin", "公积金" }, { "gong ji li", "攻击力" }, { "gong ji xing", "攻击性" }, { "gong ji zhe", "攻击者" }, { "gong jia", "公家" },
			{ "gong jian", "共建" }, { "gong jian", "工件" }, { "gong jian", "弓箭" }, { "gong jian", "攻坚" }, { "gong jian shou", "弓箭手" }, { "gong jiang", "工匠" },
			{ "gong jiao", "公交" }, { "gong jiao che", "公交车" }, { "gong jiao gong si", "公交公司" }, { "gong jiao xian lu", "公交线路" }, { "gong jin", "公斤" },
			{ "gong jin", "共进" }, { "gong jing", "宫颈" }, { "gong jing", "恭敬" }, { "gong jing ai", "宫颈癌" }, { "gong jing mi lan", "宫颈糜烂" }, { "gong ju", "工具" },
			{ "gong ju lan", "工具栏" }, { "gong ju ruan jian", "工具软件" }, { "gong ju tiao", "工具条" }, { "gong ju xiang", "工具箱" }, { "gong jue", "公爵" },
			{ "gong kai", "公开" }, { "gong kai chang he", "公开场合" }, { "gong kai fa xing", "公开发行" }, { "gong kai ke", "公开课" }, { "gong kai sai", "公开赛" },
			{ "gong kai xin", "公开信" }, { "gong kai xuan ba", "公开选拔" }, { "gong kai zhao biao", "公开招标" }, { "gong kai zhao pin", "公开招聘" }, { "gong ke", "功课" },
			{ "gong ke", "工科" }, { "gong ke", "攻克" }, { "gong kong", "工控" }, { "gong kuan", "公款" }, { "gong kuang", "工况" }, { "gong lao", "功劳" },
			{ "gong li", "公历" }, { "gong li", "公理" }, { "gong li", "公立" }, { "gong li", "公里" }, { "gong li", "功利" }, { "gong li", "功力" }, { "gong li", "宫里" },
			{ "gong li", "巩俐" }, { "gong li chu", "公里处" }, { "gong li yi yuan", "公立医院" }, { "gong ling", "工龄" }, { "gong lu", "公路" },
			{ "gong lu jian she", "公路建设" }, { "gong lue", "攻略" }, { "gong lv", "功率" }, { "gong mao", "工贸" }, { "gong men", "攻门" }, { "gong mian", "共勉" },
			{ "gong min", "公民" }, { "gong min quan li", "公民权利" }, { "gong ming", "共鸣" }, { "gong ming", "功名" }, { "gong mou", "共谋" }, { "gong mu", "公墓" },
			{ "gong nei", "宫内" }, { "gong neng", "功能" }, { "gong neng jian", "功能键" }, { "gong neng mo kuai", "功能模块" }, { "gong neng qiang da", "功能强大" },
			{ "gong neng qu", "功能区" }, { "gong neng xing", "功能性" }, { "gong neng zhang ai", "功能障碍" }, { "gong niu", "公牛" }, { "gong nong", "工农" },
			{ "gong nuan", "供暖" }, { "gong nv", "宫女" }, { "gong ping", "公平" }, { "gong ping gong zheng", "公平公正" }, { "gong ping jing zheng", "公平竞争" },
			{ "gong ping xing", "公平性" }, { "gong ping zheng yi", "公平正义" }, { "gong po", "公婆" }, { "gong po", "攻破" }, { "gong pu", "公仆" }, { "gong qi", "供气" },
			{ "gong qi", "工期" }, { "gong qi jun", "宫崎骏" }, { "gong qian", "工钱" }, { "gong qing", "公顷" }, { "gong qing tuan", "共青团" }, { "gong qiu", "供求" },
			{ "gong qiu fa bu", "供求发布" }, { "gong qiu guan xi", "供求关系" }, { "gong qiu xin xi", "供求信息" }, { "gong quan li", "公权力" }, { "gong ran", "公然" },
			{ "gong re", "供热" }, { "gong ren", "公认" }, { "gong ren", "工人" }, { "gong ren jie ji", "工人阶级" }, { "gong ru", "攻入" }, { "gong shang", "共赏" },
			{ "gong shang", "工伤" }, { "gong shang", "工商" }, { "gong shang bao xian", "工伤保险" }, { "gong shang bu men", "工商部门" },
			{ "gong shang guan li", "工商管理" }, { "gong shang ju", "工商局" }, { "gong shang lian", "工商联" }, { "gong shang suo", "工商所" },
			{ "gong shang ye", "工商业" }, { "gong shang yin hang", "工商银行" }, { "gong she", "公社" }, { "gong sheng", "共生" }, { "gong shi", "公事" },
			{ "gong shi", "公式" }, { "gong shi", "公示" }, { "gong shi", "共事" }, { "gong shi", "共识" }, { "gong shi", "工事" }, { "gong shi", "工时" },
			{ "gong shi", "攻势" }, { "gong shou", "弓手" }, { "gong shou", "拱手" }, { "gong shu", "供述" }, { "gong shui", "供水" }, { "gong si", "公司" },
			{ "gong si", "公私" }, { "gong si chan pin", "公司产品" }, { "gong si cheng li", "公司成立" }, { "gong si fa", "公司法" }, { "gong si fa zhan", "公司发展" },
			{ "gong si jian jie", "公司简介" }, { "gong si jing li", "公司经理" }, { "gong si ming cheng", "公司名称" }, { "gong si nei bu", "公司内部" },
			{ "gong si sheng chan", "公司生产" }, { "gong si wang zhan", "公司网站" }, { "gong si wang zhi", "公司网址" }, { "gong si ye ji", "公司业绩" },
			{ "gong si ye wu", "公司业务" }, { "gong si yuan gong", "公司员工" }, { "gong si zhai quan", "公司债券" }, { "gong si zhang cheng", "公司章程" },
			{ "gong si zhi li", "公司治理" }, { "gong si zhu ce", "公司注册" }, { "gong si zong bu", "公司总部" }, { "gong si zong cai", "公司总裁" }, { "gong su", "公诉" },
			{ "gong sui", "弓虽" }, { "gong sun", "公孙" }, { "gong ti", "工体" }, { "gong ting", "宫廷" }, { "gong tong", "共同" }, { "gong tong", "共通" },
			{ "gong tong dian", "共同点" }, { "gong tong fa zhan", "共同发展" }, { "gong tong fu yu", "共同富裕" }, { "gong tong nu li", "共同努力" },
			{ "gong tong ti", "共同体" }, { "gong tong yu yan", "共同语言" }, { "gong tou", "公投" }, { "gong tou", "工头" }, { "gong wai yun", "宫外孕" },
			{ "gong wang", "公网" }, { "gong wei", "工位" }, { "gong wei", "工委" }, { "gong wei", "恭维" }, { "gong wen", "公文" }, { "gong wen bao", "公文包" },
			{ "gong wu", "公务" }, { "gong wu", "共舞" }, { "gong wu yuan", "公务员" }, { "gong wu yuan fa", "公务员法" }, { "gong xi", "恭喜" },
			{ "gong xi gong xi", "恭喜恭喜" }, { "gong xi ni", "恭喜你" }, { "gong xia", "攻下" }, { "gong xian", "贡献" }, { "gong xian lv", "贡献率" },
			{ "gong xiang", "共享" }, { "gong xiao", "供销" }, { "gong xiao", "功效" }, { "gong xiao she", "供销社" }, { "gong xin", "工薪" },
			{ "gong xin jie ceng", "工薪阶层" }, { "gong xin li", "公信力" }, { "gong xing", "共性" }, { "gong xu", "供需" }, { "gong xu", "工序" }, { "gong xue", "工学" },
			{ "gong xue yuan", "工学院" }, { "gong xun", "功勋" }, { "gong yang", "供养" }, { "gong yao", "公钥" }, { "gong ye", "工业" }, { "gong ye chan pin", "工业产品" },
			{ "gong ye da xue", "工业大学" }, { "gong ye fa zhan", "工业发展" }, { "gong ye ge ming", "工业革命" }, { "gong ye hua", "工业化" },
			{ "gong ye jing ji", "工业经济" }, { "gong ye pin", "工业品" }, { "gong ye qi ye", "工业企业" }, { "gong ye qu", "工业区" }, { "gong ye she ji", "工业设计" },
			{ "gong ye sheng chan", "工业生产" }, { "gong ye xiang mu", "工业项目" }, { "gong ye xie hui", "工业协会" }, { "gong ye yong di", "工业用地" },
			{ "gong ye yuan", "工业园" }, { "gong ye yuan qu", "工业园区" }, { "gong yi", "公益" }, { "gong yi", "工艺" }, { "gong yi guang gao", "公益广告" },
			{ "gong yi huo dong", "公益活动" }, { "gong yi ji shu", "工艺技术" }, { "gong yi liu cheng", "工艺流程" }, { "gong yi mei shu", "工艺美术" },
			{ "gong yi pin", "工艺品" }, { "gong yi shi ye", "公益事业" }, { "gong yi xing", "公益性" }, { "gong ying", "供应" }, { "gong ying", "公映" },
			{ "gong ying", "共赢" }, { "gong ying lian", "供应链" }, { "gong ying liang", "供应量" }, { "gong ying shang", "供应商" }, { "gong yong", "公用" },
			{ "gong yong", "共用" }, { "gong yong", "功用" }, { "gong yong shi ye", "公用事业" }, { "gong you", "公有" }, { "gong you", "共有" }, { "gong you", "工友" },
			{ "gong you zhi", "公有制" }, { "gong yu", "公寓" }, { "gong yuan", "公元" }, { "gong yuan", "公园" }, { "gong yuan li", "公园里" },
			{ "gong yuan qian", "公元前" }, { "gong yue", "公约" }, { "gong yun", "公允" }, { "gong yun jia zhi", "公允价值" }, { "gong zai", "公仔" },
			{ "gong zhan", "攻占" }, { "gong zhang", "公章" }, { "gong zhen", "共振" }, { "gong zheng", "公正" }, { "gong zheng", "公证" }, { "gong zheng", "工整" },
			{ "gong zheng chu", "公证处" }, { "gong zheng xing", "公正性" }, { "gong zhi", "供职" }, { "gong zhi", "公职" }, { "gong zhi ren yuan", "公职人员" },
			{ "gong zhong", "公众" }, { "gong zhong", "宫中" }, { "gong zhong", "工种" }, { "gong zhong can yu", "公众参与" }, { "gong zhong ren wu", "公众人物" },
			{ "gong zhu", "公主" }, { "gong zhu", "公猪" }, { "gong zhu fen", "公主坟" }, { "gong zhuang", "工装" }, { "gong zi", "公子" }, { "gong zi", "工资" },
			{ "gong zi dai yu", "工资待遇" }, { "gong zi dan", "工资单" }, { "gong zi ka", "工资卡" }, { "gong zi shou ru", "工资收入" }, { "gong zi shui ping", "工资水平" },
			{ "gong zi zong e", "工资总额" }, { "gong zuo", "工作" }, { "gong zuo an pai", "工作安排" }, { "gong zuo bao gao", "工作报告" }, { "gong zuo biao", "工作表" },
			{ "gong zuo bu shu", "工作部署" }, { "gong zuo dan wei", "工作单位" }, { "gong zuo di dian", "工作地点" }, { "gong zuo fang an", "工作方案" },
			{ "gong zuo fang fa", "工作方法" }, { "gong zuo fang shi", "工作方式" }, { "gong zuo fu", "工作服" }, { "gong zuo gang wei", "工作岗位" },
			{ "gong zuo huan jing", "工作环境" }, { "gong zuo hui bao", "工作汇报" }, { "gong zuo hui yi", "工作会议" }, { "gong zuo ji hua", "工作计划" },
			{ "gong zuo ji hui", "工作机会" }, { "gong zuo ji zhi", "工作机制" }, { "gong zuo jing li", "工作经历" }, { "gong zuo jing yan", "工作经验" },
			{ "gong zuo kuang", "工作狂" }, { "gong zuo li du", "工作力度" }, { "gong zuo liang", "工作量" }, { "gong zuo liu", "工作流" },
			{ "gong zuo liu cheng", "工作流程" }, { "gong zuo mu biao", "工作目标" }, { "gong zuo nei rong", "工作内容" }, { "gong zuo neng li", "工作能力" },
			{ "gong zuo qing kuang", "工作情况" }, { "gong zuo ren wu", "工作任务" }, { "gong zuo ren yuan", "工作人员" }, { "gong zuo ri", "工作日" },
			{ "gong zuo shi", "工作室" }, { "gong zuo shi jian", "工作时间" }, { "gong zuo shun li", "工作顺利" }, { "gong zuo si lu", "工作思路" },
			{ "gong zuo tai", "工作台" }, { "gong zuo tai du", "工作态度" }, { "gong zuo xiao lv", "工作效率" }, { "gong zuo xiao zu", "工作小组" },
			{ "gong zuo xing zhi", "工作性质" }, { "gong zuo xu yao", "工作需要" }, { "gong zuo ya li", "工作压力" }, { "gong zuo yuan li", "工作原理" },
			{ "gong zuo zhan", "工作站" }, { "gong zuo zhe", "工作者" }, { "gong zuo zheng", "工作证" }, { "gong zuo zhi du", "工作制度" }, { "gong zuo zhi ze", "工作职责" },
			{ "gong zuo zhong dian", "工作重点" }, { "gong zuo zhuang tai", "工作状态" }, { "gong zuo zong jie", "工作总结" }, { "gong zuo zu", "工作组" },
			{ "gong zuo zuo feng", "工作作风" }, { "gou", "佝" }, { "gou", "冓" }, { "gou", "勾" }, { "gou", "句" }, { "gou", "垢" }, { "gou", "够" }, { "gou", "夠" },
			{ "gou", "姤" }, { "gou", "媾" }, { "gou", "岣" }, { "gou", "彀" }, { "gou", "搆" }, { "gou", "构" }, { "gou", "枸" }, { "gou", "構" }, { "gou", "沟" },
			{ "gou", "溝" }, { "gou", "狗" }, { "gou", "玽" }, { "gou", "笱" }, { "gou", "篝" }, { "gou", "簼" }, { "gou", "緱" }, { "gou", "缑" }, { "gou", "耇" },
			{ "gou", "耉" }, { "gou", "芶" }, { "gou", "苟" }, { "gou", "袧" }, { "gou", "覯" }, { "gou", "觏" }, { "gou", "诟" }, { "gou", "購" }, { "gou", "购" },
			{ "gou", "遘" }, { "gou", "鈎" }, { "gou", "鉤" }, { "gou", "钩" }, { "gou", "雊" }, { "gou", "鞲" }, { "gou", "韝" }, { "gou bing", "诟病" },
			{ "gou bing", "购并" }, { "gou bu gou", "够不够" }, { "gou che", "购车" }, { "gou cheng", "构成" }, { "gou cheng fan zui", "构成犯罪" }, { "gou da", "勾搭" },
			{ "gou da", "够大" }, { "gou dang", "勾当" }, { "gou de", "购得" }, { "gou dui", "勾兑" }, { "gou duo", "够多" }, { "gou fang", "购房" },
			{ "gou fang he tong", "购房合同" }, { "gou fang zhe", "购房者" }, { "gou gou", "狗狗" }, { "gou hen", "够狠" }, { "gou hua", "勾画" }, { "gou huo", "篝火" },
			{ "gou ji", "购机" }, { "gou jia", "构架" }, { "gou jian", "构件" }, { "gou jian", "构建" }, { "gou jian he xie", "构建和谐" }, { "gou jie", "勾结" },
			{ "gou jin", "购进" }, { "gou kuai", "够快" }, { "gou le", "勾勒" }, { "gou li", "沟里" }, { "gou liang", "狗粮" }, { "gou mai", "购买" },
			{ "gou mai li", "购买力" }, { "gou mai zhe", "购买者" }, { "gou nian", "狗年" }, { "gou pi", "狗屁" }, { "gou piao", "购票" }, { "gou qi", "勾起" },
			{ "gou qi", "枸杞" }, { "gou qi zi", "枸杞子" }, { "gou qiang", "够呛" }, { "gou qu", "沟渠" }, { "gou ri", "狗日" }, { "gou rou", "狗肉" }, { "gou ru", "购入" },
			{ "gou shi", "狗屎" }, { "gou shu", "购书" }, { "gou si", "构思" }, { "gou tong", "沟通" }, { "gou tong", "苟同" }, { "gou tong neng li", "沟通能力" },
			{ "gou tou", "狗头" }, { "gou tu", "构图" }, { "gou wu", "购物" }, { "gou wu che", "购物车" }, { "gou wu zhong xin", "购物中心" }, { "gou xiang", "构想" },
			{ "gou xiao", "购销" }, { "gou xin dou jiao", "勾心斗角" }, { "gou xiong", "狗熊" }, { "gou xuan", "勾选" }, { "gou yin", "勾引" }, { "gou yong", "够用" },
			{ "gou zai dui", "狗仔队" }, { "gou zao", "构造" }, { "gou zao han shu", "构造函数" }, { "gou zhi", "购置" }, { "gou zhu", "构筑" }, { "gou zi", "狗仔" },
			{ "gou zi", "狗子" }, { "gou zi", "钩子" }, { "gu", "估" }, { "gu", "僱" }, { "gu", "凅" }, { "gu", "古" }, { "gu", "呱" }, { "gu", "咕" }, { "gu", "唃" },
			{ "gu", "啒" }, { "gu", "嘏" }, { "gu", "固" }, { "gu", "堌" }, { "gu", "姑" }, { "gu", "嫴" }, { "gu", "孤" }, { "gu", "尳" }, { "gu", "峠" },
			{ "gu", "崮" }, { "gu", "愲" }, { "gu", "故" }, { "gu", "柧" }, { "gu", "梏" }, { "gu", "棝" }, { "gu", "榖" }, { "gu", "榾" }, { "gu", "橭" },
			{ "gu", "毂" }, { "gu", "汩" }, { "gu", "沽" }, { "gu", "泒" }, { "gu", "濲" }, { "gu", "瀔" }, { "gu", "牯" }, { "gu", "牿" }, { "gu", "痼" },
			{ "gu", "皷" }, { "gu", "盬" }, { "gu", "瞽" }, { "gu", "硲" }, { "gu", "稒" }, { "gu", "穀" }, { "gu", "箍" }, { "gu", "箛" }, { "gu", "罛" },
			{ "gu", "罟" }, { "gu", "羖" }, { "gu", "股" }, { "gu", "臌" }, { "gu", "菇" }, { "gu", "菰" }, { "gu", "蓇" }, { "gu", "薣" }, { "gu", "蛄" },
			{ "gu", "蛊" }, { "gu", "蛌" }, { "gu", "蠱" }, { "gu", "觚" }, { "gu", "詁" }, { "gu", "诂" }, { "gu", "谷" }, { "gu", "贾" }, { "gu", "軱" },
			{ "gu", "轂" }, { "gu", "轱" }, { "gu", "辜" }, { "gu", "逧" }, { "gu", "酤" }, { "gu", "鈷" }, { "gu", "錮" }, { "gu", "钴" }, { "gu", "锢" },
			{ "gu", "雇" }, { "gu", "顧" }, { "gu", "顾" }, { "gu", "骨" }, { "gu", "鮕" }, { "gu", "鲴" }, { "gu", "鴣" }, { "gu", "鸪" }, { "gu", "鹄" },
			{ "gu", "鹘" }, { "gu", "鼓" }, { "gu ai ji", "古埃及" }, { "gu ao", "孤傲" }, { "gu ba", "古巴" }, { "gu ban", "古板" }, { "gu bao", "古堡" },
			{ "gu ben", "股本" }, { "gu bu de", "顾不得" }, { "gu bu shang", "顾不上" }, { "gu cheng", "古城" }, { "gu chu jun", "顾雏军" }, { "gu chui", "鼓吹" },
			{ "gu ci", "故此" }, { "gu dai", "古代" }, { "gu dan", "孤单" }, { "gu dao", "古道" }, { "gu dao", "孤岛" }, { "gu dao", "鼓捣" }, { "gu di", "谷底" },
			{ "gu dian", "古典" }, { "gu dian yin yue", "古典音乐" }, { "gu ding", "固定" }, { "gu ding bu bian", "固定不变" }, { "gu ding dian hua", "固定电话" },
			{ "gu ding li lv", "固定利率" }, { "gu ding zi chan", "固定资产" }, { "gu dong", "古董" }, { "gu dong", "股东" }, { "gu dong", "鼓动" },
			{ "gu dong da hui", "股东大会" }, { "gu dong hui", "股东会" }, { "gu du", "古都" }, { "gu du", "孤独" }, { "gu er", "孤儿" }, { "gu er", "故而" },
			{ "gu er yuan", "孤儿院" }, { "gu fen", "股份" }, { "gu fen gong si", "股份公司" }, { "gu fen zhi", "股份制" }, { "gu feng", "古风" }, { "gu fu", "姑父" },
			{ "gu fu", "辜负" }, { "gu gai", "股改" }, { "gu gai fang an", "股改方案" }, { "gu gan", "骨干" }, { "gu gan jiao shi", "骨干教师" }, { "gu gan qi ye", "骨干企业" },
			{ "gu ge", "谷歌" }, { "gu ge", "骨骼" }, { "gu gong", "故宫" }, { "gu gu", "咕咕" }, { "gu gu", "姑姑" }, { "gu gu", "鼓鼓" }, { "gu guai", "古怪" },
			{ "gu guo", "故国" }, { "gu hai", "股海" }, { "gu hua", "固化" }, { "gu hua", "固话" }, { "gu hui", "骨灰" }, { "gu huo", "蛊惑" }, { "gu huo zai", "古惑仔" },
			{ "gu ji", "估计" }, { "gu ji", "古籍" }, { "gu ji", "古迹" }, { "gu ji", "孤寂" }, { "gu ji", "顾及" }, { "gu ji", "顾忌" }, { "gu jia", "估价" },
			{ "gu jia", "股价" }, { "gu jia", "顾家" }, { "gu jia", "骨架" }, { "gu jian", "固件" }, { "gu jian zhu", "古建筑" }, { "gu jin", "古今" },
			{ "gu jin zhong wai", "古今中外" }, { "gu jing", "古井" }, { "gu ju", "故居" }, { "gu ju ji", "古巨基" }, { "gu ke", "顾客" }, { "gu ke", "骨科" },
			{ "gu lai", "古来" }, { "gu lang yu", "鼓浪屿" }, { "gu lao", "古老" }, { "gu li", "古力" }, { "gu li", "孤立" }, { "gu li", "故里" }, { "gu li", "股利" },
			{ "gu li", "鼓励" }, { "gu li xue sheng", "鼓励学生" }, { "gu liang", "估量" }, { "gu ling ling", "孤零零" }, { "gu long", "古龙" }, { "gu lou", "鼓楼" },
			{ "gu lou gua wen", "孤陋寡闻" }, { "gu lu", "咕噜" }, { "gu luo ma", "古罗马" }, { "gu lv", "顾虑" }, { "gu ma", "姑妈" }, { "gu min", "股民" },
			{ "gu ming si yi", "顾名思义" }, { "gu mu", "古墓" }, { "gu niang", "姑娘" }, { "gu pen", "骨盆" }, { "gu pi", "孤僻" }, { "gu piao", "股票" },
			{ "gu piao ji jin", "股票基金" }, { "gu piao jia ge", "股票价格" }, { "gu piao jiao yi", "股票交易" }, { "gu piao shi chang", "股票市场" },
			{ "gu piao tou zi", "股票投资" }, { "gu ping", "股评" }, { "gu pu", "古朴" }, { "gu qi", "骨气" }, { "gu qi", "鼓起" }, { "gu qie", "姑且" }, { "gu qin", "古琴" },
			{ "gu quan", "股权" }, { "gu quan fen zhi", "股权分置" }, { "gu quan ji li", "股权激励" }, { "gu quan jie gou", "股权结构" }, { "gu quan tou zi", "股权投资" },
			{ "gu quan zhuan rang", "股权转让" }, { "gu ran", "固然" }, { "gu ren", "古人" }, { "gu ren", "故人" }, { "gu rou", "骨肉" }, { "gu shen", "孤身" },
			{ "gu shen", "股神" }, { "gu shi", "古时" }, { "gu shi", "古诗" }, { "gu shi", "故事" }, { "gu shi", "股市" }, { "gu shi chang", "股市场" },
			{ "gu shi hou", "古时候" }, { "gu shi pian", "故事片" }, { "gu shi qing jie", "故事情节" }, { "gu shou", "固守" }, { "gu shou", "鼓手" }, { "gu shu", "古书" },
			{ "gu shu", "古树" }, { "gu shu", "股数" }, { "gu suan", "估算" }, { "gu sui", "骨髓" }, { "gu tai", "固态" }, { "gu ti", "固体" }, { "gu tian le", "古天乐" },
			{ "gu tou", "骨头" }, { "gu tu", "故土" }, { "gu wan", "古玩" }, { "gu wang", "固网" }, { "gu wang jin lai", "古往今来" }, { "gu wen", "古文" },
			{ "gu wen", "顾问" }, { "gu wu", "谷物" }, { "gu wu", "鼓舞" }, { "gu xi", "股息" }, { "gu xi la", "古希腊" }, { "gu xiang", "故乡" }, { "gu xing", "孤星" },
			{ "gu yi", "故意" }, { "gu yong", "雇佣" }, { "gu yong", "雇用" }, { "gu you", "固有" }, { "gu you", "故有" }, { "gu you", "股友" }, { "gu yuan", "雇员" },
			{ "gu yue", "古月" }, { "gu yun", "孤云" }, { "gu zai", "股灾" }, { "gu zhang", "故障" }, { "gu zhang", "鼓掌" }, { "gu zhang zhen duan", "故障诊断" },
			{ "gu zhe", "骨折" }, { "gu zhen", "古镇" }, { "gu zheng", "古筝" }, { "gu zhi", "估值" }, { "gu zhi", "固执" }, { "gu zhi", "股指" },
			{ "gu zhi qi huo", "股指期货" }, { "gu zhi shu song", "骨质疏松" }, { "gu zhou", "孤舟" }, { "gu zhu", "雇主" }, { "gu zhuang", "古装" }, { "gu zi", "谷子" },
			{ "gu zi li", "骨子里" }, { "gu zuo", "故作" }, { "gua", "刮" }, { "gua", "剐" }, { "gua", "剮" }, { "gua", "劀" }, { "gua", "卦" }, { "gua", "呱" },
			{ "gua", "寡" }, { "gua", "括" }, { "gua", "挂" }, { "gua", "掛" }, { "gua", "栝" }, { "gua", "瓜" }, { "gua", "緺" }, { "gua", "罣" }, { "gua", "胍" },
			{ "gua", "苽" }, { "gua", "褂" }, { "gua", "詿" }, { "gua", "诖" }, { "gua", "颪" }, { "gua", "颳" }, { "gua", "騧" }, { "gua", "鴰" }, { "gua", "鸹" },
			{ "gua dan", "挂单" }, { "gua dao", "挂到" }, { "gua diao", "挂掉" }, { "gua duan", "挂断" }, { "gua fen", "瓜分" }, { "gua feng", "刮风" },
			{ "gua fu", "寡妇" }, { "gua ge", "瓜葛" }, { "gua gou", "挂钩" }, { "gua gua", "呱呱" }, { "gua gua", "瓜瓜" }, { "gua guo", "瓜果" }, { "gua hao", "挂号" },
			{ "gua ji", "挂机" }, { "gua jian", "挂件" }, { "gua kao", "挂靠" }, { "gua li", "挂历" }, { "gua man", "挂满" }, { "gua mu xiang kan", "刮目相看" },
			{ "gua nian", "挂念" }, { "gua pai", "挂牌" }, { "gua qi", "刮起" }, { "gua qi", "挂起" }, { "gua ren", "寡人" }, { "gua shang", "挂上" }, { "gua shi", "挂失" },
			{ "gua shuai", "挂帅" }, { "gua tou", "寡头" }, { "gua zai", "挂在" }, { "gua zai", "挂载" }, { "gua zhe", "挂着" }, { "gua zhi", "挂职" },
			{ "gua zhu", "挂住" }, { "gua zi", "瓜子" }, { "guai", "乖" }, { "guai", "夬" }, { "guai", "怪" }, { "guai", "恠" }, { "guai", "拐" }, { "guai", "掴" },
			{ "guai", "枴" }, { "guai", "柺" }, { "guai", "罫" }, { "guai bu de", "怪不得" }, { "guai dian", "拐点" }, { "guai guai", "乖乖" }, { "guai guai", "怪怪" },
			{ "guai guai de", "乖乖的" }, { "guai jiao", "拐角" }, { "guai mai", "拐卖" }, { "guai ni", "怪你" }, { "guai qiao", "乖巧" }, { "guai quan", "怪圈" },
			{ "guai ren", "怪人" }, { "guai shi", "怪事" }, { "guai shou", "怪兽" }, { "guai tai", "怪胎" }, { "guai wan", "拐弯" }, { "guai wo", "怪我" },
			{ "guai wu", "怪物" }, { "guai yi", "怪异" }, { "guai zhang", "拐杖" }, { "guai zui", "怪罪" }, { "guan", "倌" }, { "guan", "关" }, { "guan", "冠" },
			{ "guan", "官" }, { "guan", "悹" }, { "guan", "悺" }, { "guan", "惯" }, { "guan", "慣" }, { "guan", "掼" }, { "guan", "摜" }, { "guan", "棺" },
			{ "guan", "樌" }, { "guan", "毌" }, { "guan", "涫" }, { "guan", "灌" }, { "guan", "爟" }, { "guan", "琯" }, { "guan", "瓘" }, { "guan", "痯" },
			{ "guan", "瘝" }, { "guan", "盥" }, { "guan", "矜" }, { "guan", "祼" }, { "guan", "筦" }, { "guan", "管" }, { "guan", "纶" }, { "guan", "罐" },
			{ "guan", "舘" }, { "guan", "莞" }, { "guan", "蒄" }, { "guan", "観" }, { "guan", "觀" }, { "guan", "观" }, { "guan", "貫" }, { "guan", "贯" },
			{ "guan", "錧" }, { "guan", "鏆" }, { "guan", "鑵" }, { "guan", "閞" }, { "guan", "關" }, { "guan", "館" }, { "guan", "馆" }, { "guan", "鱞" },
			{ "guan", "鱹" }, { "guan", "鳏" }, { "guan", "鸛" }, { "guan", "鹳" }, { "guan ai", "关爱" }, { "guan bi", "关闭" }, { "guan bing", "官兵" },
			{ "guan bu liao", "管不了" }, { "guan cai", "棺材" }, { "guan cai", "管材" }, { "guan cang", "馆藏" }, { "guan ce", "观测" }, { "guan cha", "观察" },
			{ "guan cha yuan", "观察员" }, { "guan cha zhe", "观察者" }, { "guan chang", "官场" }, { "guan chang", "灌肠" }, { "guan che", "贯彻" },
			{ "guan che luo shi", "贯彻落实" }, { "guan che shi shi", "贯彻实施" }, { "guan che zhi xing", "贯彻执行" }, { "guan chuan", "贯穿" }, { "guan dao", "管道" },
			{ "guan de", "管得" }, { "guan deng", "关灯" }, { "guan di", "官邸" }, { "guan dian", "观点" }, { "guan diao", "关掉" }, { "guan dong", "关东" },
			{ "guan fang", "官方" }, { "guan fang lun tan", "官方论坛" }, { "guan fang wang zhan", "官方网站" }, { "guan fu", "官府" }, { "guan gai", "灌溉" },
			{ "guan gan", "观感" }, { "guan gong", "关公" }, { "guan guan", "灌灌" }, { "guan guan", "管管" }, { "guan guan shui shui", "灌灌水水" },
			{ "guan guang", "观光" }, { "guan hao", "管好" }, { "guan hou gan", "观后感" }, { "guan hu", "关乎" }, { "guan hu", "管护" }, { "guan huai", "关怀" },
			{ "guan ji", "关机" }, { "guan jia", "管家" }, { "guan jian", "关键" }, { "guan jian", "管件" }, { "guan jian ci", "关键词" }, { "guan jian dian", "关键点" },
			{ "guan jian huan jie", "关键环节" }, { "guan jian ji shu", "关键技术" }, { "guan jian shi ke", "关键时刻" }, { "guan jian shi qi", "关键时期" },
			{ "guan jian wen ti", "关键问题" }, { "guan jian xing", "关键性" } };
};
