package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN39 {
	public static String[][] pl = { { "rao xing", "绕行" }, { "rao yue", "绕月" }, { "rao zhe", "绕着" }, { "rao zu", "绕组" }, { "re", "喏" }, { "re", "惹" },
			{ "re", "热" }, { "re", "熱" }, { "re ai", "热爱" }, { "re ai sheng huo", "热爱生活" }, { "re bo", "热播" }, { "re chao", "热潮" }, { "re chao", "热炒" },
			{ "re chen", "热忱" }, { "re cheng", "热诚" }, { "re chu li", "热处理" }, { "re ci", "热刺" }, { "re dai", "热带" }, { "re dai feng bao", "热带风暴" },
			{ "re dai yu lin", "热带雨林" }, { "re de", "惹得" }, { "re de", "热得" }, { "re dian", "热点" }, { "re dian", "热电" }, { "re dian chang", "热电厂" },
			{ "re dian wen ti", "热点问题" }, { "re du", "热度" }, { "re feng", "热风" }, { "re guan", "热管" }, { "re huo", "惹火" }, { "re huo", "热火" },
			{ "re huo chao tian", "热火朝天" }, { "re jian", "热键" }, { "re la", "热辣" }, { "re lai", "惹来" }, { "re lang", "热浪" }, { "re lei", "热泪" },
			{ "re lei ying kuang", "热泪盈眶" }, { "re li", "热力" }, { "re li xue", "热力学" }, { "re lian", "热恋" }, { "re liang", "热量" }, { "re liao", "热疗" },
			{ "re lie", "热烈" }, { "re lie zhu he", "热烈祝贺" }, { "re mai", "热卖" }, { "re men", "热门" }, { "re men hua ti", "热门话题" }, { "re nao", "热闹" },
			{ "re nao fei fan", "热闹非凡" }, { "re neng", "热能" }, { "re qi", "热气" }, { "re qian", "热钱" }, { "re qie", "热切" }, { "re qing", "热情" },
			{ "re qing yang yi", "热情洋溢" }, { "re re", "热热" }, { "re re nao nao", "热热闹闹" }, { "re ren", "惹人" }, { "re shen", "热身" }, { "re shen sai", "热身赛" },
			{ "re shi", "惹事" }, { "re shui", "热水" }, { "re shui qi", "热水器" }, { "re tu", "热土" }, { "re wen", "热吻" }, { "re wu", "热舞" }, { "re xian", "热线" },
			{ "re xian dian hua", "热线电话" }, { "re xiao", "热销" }, { "re xin", "热心" }, { "re xin ren", "热心人" }, { "re xue", "热血" },
			{ "re xue fei teng", "热血沸腾" }, { "re xue jiang hu", "热血江湖" }, { "re yi", "热议" }, { "re yuan", "热源" }, { "re zha", "热轧" }, { "re zhong", "热衷" },
			{ "ren", "人" }, { "ren", "亻" }, { "ren", "仁" }, { "ren", "仞" }, { "ren", "仭" }, { "ren", "任" }, { "ren", "刃" }, { "ren", "刄" }, { "ren", "壬" },
			{ "ren", "妊" }, { "ren", "姙" }, { "ren", "屻" }, { "ren", "忍" }, { "ren", "扨" }, { "ren", "栠" }, { "ren", "涊" }, { "ren", "牣" }, { "ren", "稔" },
			{ "ren", "紉" }, { "ren", "紝" }, { "ren", "綛" }, { "ren", "纫" }, { "ren", "肕" }, { "ren", "腍" }, { "ren", "芢" }, { "ren", "荏" }, { "ren", "荵" },
			{ "ren", "葚" }, { "ren", "衽" }, { "ren", "袵" }, { "ren", "訒" }, { "ren", "認" }, { "ren", "认" }, { "ren", "軔" }, { "ren", "轫" }, { "ren", "銋" },
			{ "ren", "靭" }, { "ren", "靱" }, { "ren", "韌" }, { "ren", "韧" }, { "ren", "飪" }, { "ren", "饪" }, { "ren", "鵀" }, { "ren a", "人啊" },
			{ "ren ai", "仁爱" }, { "ren bao", "人保" }, { "ren bu", "人不" }, { "ren bu chu", "认不出" }, { "ren bu zhu", "忍不住" }, { "ren cai", "人才" },
			{ "ren cai dui wu", "人才队伍" }, { "ren cai pei yang", "人才培养" }, { "ren cai shi chang", "人才市场" }, { "ren cai wang", "人才网" },
			{ "ren cai zhao pin", "人才招聘" }, { "ren cai zi yuan", "人才资源" }, { "ren chao", "人潮" }, { "ren cheng", "人称" }, { "ren chu", "人畜" },
			{ "ren chu", "认出" }, { "ren ci", "人次" }, { "ren ci", "仁慈" }, { "ren cuo", "认错" }, { "ren da", "人大" }, { "ren da dai biao", "人大代表" },
			{ "ren da gong zuo", "人大工作" }, { "ren da hua", "任达华" }, { "ren dai", "韧带" }, { "ren dao", "人道" }, { "ren dao zhu yi", "人道主义" }, { "ren de", "人的" },
			{ "ren de", "认得" }, { "ren ding", "认定" }, { "ren dou", "人都" }, { "ren dou zhi dao", "人都知道" }, { "ren dui", "人对" }, { "ren duo", "人多" },
			{ "ren duo le", "人多了" }, { "ren er", "人儿" }, { "ren fang", "人防" }, { "ren fu", "任副" }, { "ren gan", "人敢" }, { "ren ge", "人格" },
			{ "ren ge mei li", "人格魅力" }, { "ren gong", "人工" }, { "ren gong liu chan", "人工流产" }, { "ren gong zhi neng", "人工智能" }, { "ren gou", "认购" },
			{ "ren gou quan zheng", "认购权证" }, { "ren gu", "认沽" }, { "ren gu quan zheng", "认沽权证" }, { "ren hai", "人海" }, { "ren hai", "人还" },
			{ "ren hang", "人行" }, { "ren he", "人和" }, { "ren he", "仁和" }, { "ren he", "任何" }, { "ren he di fang", "任何地方" }, { "ren he dong xi", "任何东西" },
			{ "ren he ren", "任何人" }, { "ren he shi", "人和事" }, { "ren he shi hou", "任何时候" }, { "ren he shi qing", "任何事情" }, { "ren he yi zhong", "任何一种" },
			{ "ren hen", "人很" }, { "ren hua", "人话" }, { "ren hui", "人会" }, { "ren ji", "人机" }, { "ren ji", "人际" }, { "ren ji guan xi", "人际关系" },
			{ "ren ji jiao wang", "人际交往" }, { "ren jia", "人家" }, { "ren jian", "人间" }, { "ren jian ren ai", "人见人爱" }, { "ren jiao", "任教" },
			{ "ren jie", "人皆" }, { "ren jiu", "人就" }, { "ren ju", "人居" }, { "ren ju huan jing", "人居环境" }, { "ren jun", "人均" }, { "ren jun shou ru", "人均收入" },
			{ "ren kan", "人看" }, { "ren ke", "任课" }, { "ren ke", "认可" }, { "ren kou", "人口" }, { "ren lai", "人来" }, { "ren lai ren wang", "人来人往" },
			{ "ren lai shuo", "人来说" }, { "ren le", "忍了" }, { "ren le", "认了" }, { "ren lei", "人类" }, { "ren lei li shi", "人类历史" },
			{ "ren lei she hui", "人类社会" }, { "ren lei wen ming", "人类文明" }, { "ren lei xue", "人类学" }, { "ren li", "人力" }, { "ren li zi ben", "人力资本" },
			{ "ren li zi yuan", "人力资源" }, { "ren lian", "人脸" }, { "ren ling", "认领" }, { "ren liu", "人流" }, { "ren liu liang", "人流量" }, { "ren ma", "人吗" },
			{ "ren ma", "人马" }, { "ren ma", "人骂" }, { "ren mai", "人脉" }, { "ren man wei huan", "人满为患" }, { "ren men", "人们" }, { "ren mian", "人面" },
			{ "ren mian", "任免" }, { "ren min", "人民" }, { "ren min bi", "人民币" }, { "ren min da xue", "人民大学" }, { "ren min fa yuan", "人民法院" },
			{ "ren min guang chang", "人民广场" }, { "ren min jing cha", "人民警察" }, { "ren min lu", "人民路" }, { "ren min qun zhong", "人民群众" },
			{ "ren min ri bao", "人民日报" }, { "ren min sheng huo", "人民生活" }, { "ren min wang", "人民网" }, { "ren min yi yuan", "人民医院" },
			{ "ren min yin hang", "人民银行" }, { "ren min zheng fu", "人民政府" }, { "ren min zheng xie", "人民政协" }, { "ren ming", "人名" }, { "ren ming", "人命" },
			{ "ren ming", "任命" }, { "ren ming", "认命" }, { "ren nai", "忍耐" }, { "ren nao", "人脑" }, { "ren ne", "人呢" }, { "ren neng", "人能" }, { "ren ni", "任你" },
			{ "ren pin", "人品" }, { "ren ping", "任凭" }, { "ren qi", "人妻" }, { "ren qi", "人气" }, { "ren qi", "任其" }, { "ren qi", "任期" },
			{ "ren qi tun sheng", "忍气吞声" }, { "ren qian", "人前" }, { "ren qing", "人情" }, { "ren qing", "认清" }, { "ren qing wei", "人情味" }, { "ren qu", "人去" },
			{ "ren quan", "人权" }, { "ren que", "人却" }, { "ren qun", "人群" }, { "ren rang", "忍让" }, { "ren ren", "人人" }, { "ren ren dou you", "人人都有" },
			{ "ren ren zhen zhen", "认认真真" }, { "ren rou", "人肉" }, { "ren ru fu zhong", "忍辱负重" }, { "ren shan ren hai", "人山人海" }, { "ren shao", "人少" },
			{ "ren shen", "人参" }, { "ren shen", "人身" }, { "ren shen", "妊娠" }, { "ren shen an quan", "人身安全" }, { "ren shen gong ji", "人身攻击" },
			{ "ren shen qi", "妊娠期" }, { "ren shen shang", "人身上" }, { "ren shen zi you", "人身自由" }, { "ren sheng", "人声" }, { "ren sheng", "人生" },
			{ "ren sheng guan", "人生观" }, { "ren sheng jing li", "人生经历" }, { "ren sheng mu biao", "人生目标" }, { "ren shi", "人世" }, { "ren shi", "人事" },
			{ "ren shi", "人士" }, { "ren shi", "人是" }, { "ren shi", "认识" }, { "ren shi bian dong", "人事变动" }, { "ren shi bu", "人事部" },
			{ "ren shi bu men", "人事部门" }, { "ren shi chu", "人事处" }, { "ren shi jian", "人世间" }, { "ren shi ju", "人事局" }, { "ren shi shui", "人是谁" },
			{ "ren shi zi ji", "认识自己" }, { "ren shou", "人寿" }, { "ren shou", "人手" }, { "ren shou", "忍受" }, { "ren shou bao xian", "人寿保险" },
			{ "ren shu", "人数" }, { "ren shu", "认输" }, { "ren shu zui duo", "人数最多" }, { "ren shuo", "人说" }, { "ren shuo hua", "人说话" }, { "ren si", "人死" },
			{ "ren si wang", "人死亡" }, { "ren suo", "人所" }, { "ren ti", "人体" }, { "ren ti jian kang", "人体健康" }, { "ren ti yi shu", "人体艺术" },
			{ "ren tian tang", "任天堂" }, { "ren tong", "忍痛" }, { "ren tong", "认同" }, { "ren tong gan", "认同感" }, { "ren tou", "人头" }, { "ren wei", "人为" },
			{ "ren wei", "认为" }, { "ren wei zi ji", "认为自己" }, { "ren wen", "人文" }, { "ren wen guan huai", "人文关怀" }, { "ren wen jing guan", "人文景观" },
			{ "ren wen jing shen", "人文精神" }, { "ren wu", "人无" }, { "ren wu", "人物" }, { "ren wu", "任务" }, { "ren wu ke ren", "忍无可忍" }, { "ren wu lan", "任务栏" },
			{ "ren wu shu", "任务书" }, { "ren wu xing xiang", "人物形象" }, { "ren xian qi", "任贤齐" }, { "ren xiang", "人像" }, { "ren xin", "人心" },
			{ "ren xin", "忍心" }, { "ren xing", "人形" }, { "ren xing", "人性" }, { "ren xing", "任性" }, { "ren xing", "韧性" }, { "ren xing dao", "人行道" },
			{ "ren xing hua", "人性化" }, { "ren xiong", "仁兄" }, { "ren xuan", "人选" }, { "ren xuan", "任选" }, { "ren yan", "人眼" }, { "ren yao", "人妖" },
			{ "ren yao", "人要" }, { "ren ye", "人也" }, { "ren yi", "人意" }, { "ren yi", "仁义" }, { "ren yi", "任一" }, { "ren yi", "任意" }, { "ren yi qiu", "任意球" },
			{ "ren ying", "人影" }, { "ren yong", "人用" }, { "ren yong", "任用" }, { "ren you", "人有" }, { "ren you", "任由" }, { "ren yu", "人与" }, { "ren yu", "人鱼" },
			{ "ren yu ren", "人与人" }, { "ren yu zi ran", "人与自然" }, { "ren yuan", "人员" }, { "ren yuan", "人缘" }, { "ren yuan ming dan", "人员名单" },
			{ "ren yuan shang wang", "人员伤亡" }, { "ren yun yi yun", "人云亦云" }, { "ren zai", "人在" }, { "ren zao", "人造" }, { "ren zha", "人渣" },
			{ "ren zhe", "忍着" }, { "ren zhe", "忍者" }, { "ren zhe jian ren", "仁者见仁" }, { "ren zhe shen gui", "忍者神龟" }, { "ren zhen", "认真" },
			{ "ren zhen fu ze", "认真负责" }, { "ren zhen guan che", "认真贯彻" }, { "ren zhen luo shi", "认真落实" }, { "ren zhen xue xi", "认真学习" },
			{ "ren zhen zuo hao", "认真做好" }, { "ren zheng", "认证" }, { "ren zheng fei", "任正非" }, { "ren zheng ji gou", "认证机构" }, { "ren zhi", "人之" },
			{ "ren zhi", "人治" }, { "ren zhi", "人质" }, { "ren zhi", "任职" }, { "ren zhi", "认知" }, { "ren zhi chang qing", "人之常情" }, { "ren zhi dao", "人知道" },
			{ "ren zhi du", "认知度" }, { "ren zhi qiang", "任志强" }, { "ren zhi zi ge", "任职资格" }, { "ren zhong", "人种" }, { "ren zhong dao yuan", "任重道远" },
			{ "ren zhu", "忍住" }, { "ren zhun", "认准" }, { "ren zong tong", "任总统" }, { "ren zu", "人族" }, { "ren zui", "认罪" }, { "ren zuo", "人做" },
			{ "reng", "仍" }, { "reng", "扔" }, { "reng", "礽" }, { "reng", "芿" }, { "reng", "陾" }, { "reng bu", "仍不" }, { "reng chu", "扔出" },
			{ "reng dao", "扔到" }, { "reng diao", "扔掉" }, { "reng gei", "扔给" }, { "reng jiang", "仍将" }, { "reng jin", "扔进" }, { "reng jiu", "仍旧" },
			{ "reng ke", "仍可" }, { "reng le", "扔了" }, { "reng ran", "仍然" }, { "reng shi", "仍是" }, { "reng wei", "仍为" }, { "reng wei", "仍未" },
			{ "reng xia", "扔下" }, { "reng xu", "仍需" }, { "reng yao", "仍要" }, { "reng yi", "仍以" }, { "reng you", "仍有" }, { "reng zai", "仍在" },
			{ "reng zai", "扔在" }, { "ri", "日" }, { "ri", "鈤" }, { "ri", "馹" }, { "ri ban", "日版" }, { "ri bao", "日报" }, { "ri bao she", "日报社" },
			{ "ri ben", "日本" }, { "ri ben che", "日本车" }, { "ri ben dong jing", "日本东京" }, { "ri ben dui", "日本队" }, { "ri ben gui zi", "日本鬼子" },
			{ "ri ben jing ji", "日本经济" }, { "ri ben qi ye", "日本企业" }, { "ri ben ren", "日本人" }, { "ri ben shou xiang", "日本首相" }, { "ri ben zheng fu", "日本政府" },
			{ "ri chan", "日产" }, { "ri chang", "日常" }, { "ri chang gong zuo", "日常工作" }, { "ri chang guan li", "日常管理" }, { "ri chang sheng huo", "日常生活" },
			{ "ri cheng", "日程" }, { "ri cheng an pai", "日程安排" }, { "ri cheng biao", "日程表" }, { "ri chu", "日出" }, { "ri dian", "日电" }, { "ri fang", "日方" },
			{ "ri fu yi ri", "日复一日" }, { "ri guang", "日光" }, { "ri guang deng", "日光灯" }, { "ri han", "日韩" }, { "ri hou", "日后" }, { "ri hua", "日化" },
			{ "ri huo", "日货" }, { "ri ji", "日记" }, { "ri ji ben", "日记本" }, { "ri jian", "日渐" }, { "ri jian", "日间" }, { "ri jiu", "日久" }, { "ri ju", "日剧" },
			{ "ri jun", "日军" }, { "ri jun", "日均" }, { "ri kou", "日寇" }, { "ri li", "日历" }, { "ri li", "日立" }, { "ri luo", "日落" }, { "ri mei", "日美" },
			{ "ri mu", "日暮" }, { "ri nei", "日内" }, { "ri nei wa", "日内瓦" }, { "ri qi", "日期" }, { "ri qi", "日起" }, { "ri qian", "日前" }, { "ri qu", "日趋" },
			{ "ri ri", "日日" }, { "ri ri ye ye", "日日夜夜" }, { "ri shi", "日式" }, { "ri wan", "日晚" }, { "ri wen", "日文" }, { "ri xi", "日系" }, { "ri xian", "日线" },
			{ "ri xiang", "日向" }, { "ri xin yue yi", "日新月异" }, { "ri xun", "日讯" }, { "ri ye", "日夜" }, { "ri yi", "日益" }, { "ri yong", "日用" },
			{ "ri yong pin", "日用品" }, { "ri yu", "日语" }, { "ri yuan", "日元" }, { "ri yuan", "日圆" }, { "ri yue", "日月" }, { "ri zhao", "日照" },
			{ "ri zhao shi", "日照市" }, { "ri zhi", "日志" }, { "ri zhi wen jian", "日志文件" }, { "ri zhong", "日中" }, { "ri zi", "日子" }, { "ri zi li", "日子里" },
			{ "rong", "傇" }, { "rong", "冗" }, { "rong", "媶" }, { "rong", "嫆" }, { "rong", "容" }, { "rong", "峵" }, { "rong", "嵘" }, { "rong", "嶸" },
			{ "rong", "戎" }, { "rong", "栄" }, { "rong", "榕" }, { "rong", "榮" }, { "rong", "榵" }, { "rong", "毧" }, { "rong", "氄" }, { "rong", "溶" },
			{ "rong", "瀜" }, { "rong", "烿" }, { "rong", "熔" }, { "rong", "爃" }, { "rong", "狨" }, { "rong", "瑢" }, { "rong", "穃" }, { "rong", "絨" },
			{ "rong", "绒" }, { "rong", "羢" }, { "rong", "肜" }, { "rong", "茙" }, { "rong", "茸" }, { "rong", "荣" }, { "rong", "蓉" }, { "rong", "蝾" },
			{ "rong", "融" }, { "rong", "蠑" }, { "rong", "褣" }, { "rong", "軵" }, { "rong", "鎔" }, { "rong", "駥" }, { "rong", "髶" }, { "rong bu", "绒布" },
			{ "rong bu xia", "容不下" }, { "rong chang", "冗长" }, { "rong cuo", "容错" }, { "rong deng", "荣登" }, { "rong dong", "溶洞" }, { "rong he", "融合" },
			{ "rong hua", "溶化" }, { "rong hua", "熔化" }, { "rong hua", "荣华" }, { "rong hua", "融化" }, { "rong huo", "荣获" }, { "rong ji", "容积" },
			{ "rong ji", "溶剂" }, { "rong ji lv", "容积率" }, { "rong jie", "溶解" }, { "rong liang", "容量" }, { "rong lu", "熔炉" }, { "rong mao", "容貌" },
			{ "rong mao", "绒毛" }, { "rong na", "容纳" }, { "rong qi", "容器" }, { "rong qia", "融洽" }, { "rong quan", "融券" }, { "rong ren", "容忍" },
			{ "rong rong", "蓉蓉" }, { "rong ru", "溶入" }, { "rong ru", "荣辱" }, { "rong ru", "融入" }, { "rong ru guan", "荣辱观" }, { "rong shu", "榕树" },
			{ "rong tong", "融通" }, { "rong wei yi ti", "融为一体" }, { "rong xing", "荣幸" }, { "rong xu", "容许" }, { "rong yan", "容颜" }, { "rong yao", "荣耀" },
			{ "rong ye", "溶液" }, { "rong ye zhong", "溶液中" }, { "rong yi", "容易" }, { "rong yi yin qi", "容易引起" }, { "rong ying", "荣膺" }, { "rong yu", "冗余" },
			{ "rong yu", "溶于" }, { "rong yu", "荣誉" }, { "rong yu cheng hao", "荣誉称号" }, { "rong zai", "容灾" }, { "rong zi", "融资" }, { "rong zi qu dao", "融资渠道" },
			{ "rong zu er", "容祖儿" }, { "rou", "厹" }, { "rou", "媃" }, { "rou", "宍" }, { "rou", "揉" }, { "rou", "柔" }, { "rou", "楺" }, { "rou", "煣" },
			{ "rou", "禸" }, { "rou", "粈" }, { "rou", "糅" }, { "rou", "肉" }, { "rou", "莥" }, { "rou", "葇" }, { "rou", "蝚" }, { "rou", "蹂" }, { "rou", "輮" },
			{ "rou", "鍒" }, { "rou", "鞣" }, { "rou", "韖" }, { "rou", "騥" }, { "rou", "髳" }, { "rou", "鰇" }, { "rou", "鶔" }, { "rou bang", "肉棒" },
			{ "rou bo", "肉搏" }, { "rou cuo", "揉搓" }, { "rou dao", "柔道" }, { "rou he", "柔和" }, { "rou ji", "肉鸡" }, { "rou lei", "肉类" }, { "rou lin", "蹂躏" },
			{ "rou ma", "肉麻" }, { "rou mei", "柔美" }, { "rou nen", "柔嫩" }, { "rou niu", "肉牛" }, { "rou pian", "肉片" }, { "rou qing", "柔情" }, { "rou rou", "揉揉" },
			{ "rou rou", "柔柔" }, { "rou rou", "肉肉" }, { "rou ruan", "柔软" }, { "rou ruo", "柔弱" }, { "rou shen", "肉身" }, { "rou shi", "肉食" },
			{ "rou shun", "柔顺" }, { "rou si", "肉丝" }, { "rou ti", "肉体" }, { "rou xian", "肉馅" }, { "rou xing", "柔性" }, { "rou yan", "肉眼" }, { "rou zhe", "揉着" },
			{ "rou zhi", "肉质" }, { "ru", "乳" }, { "ru", "侞" }, { "ru", "儒" }, { "ru", "入" }, { "ru", "嗕" }, { "ru", "嚅" }, { "ru", "如" }, { "ru", "媷" },
			{ "ru", "嬬" }, { "ru", "孺" }, { "ru", "帤" }, { "ru", "挐" }, { "ru", "擩" }, { "ru", "曘" }, { "ru", "杁" }, { "ru", "汝" }, { "ru", "洳" },
			{ "ru", "溽" }, { "ru", "濡" }, { "ru", "獳" }, { "ru", "筎" }, { "ru", "縟" }, { "ru", "缛" }, { "ru", "茹" }, { "ru", "蒘" }, { "ru", "蓐" },
			{ "ru", "蕠" }, { "ru", "薷" }, { "ru", "蠕" }, { "ru", "袽" }, { "ru", "褥" }, { "ru", "襦" }, { "ru", "辱" }, { "ru", "込" }, { "ru", "鄏" },
			{ "ru", "醹" }, { "ru", "銣" }, { "ru", "铷" }, { "ru", "颥" }, { "ru", "鳰" }, { "ru", "鴽" }, { "ru bai se", "乳白色" }, { "ru bu", "如不" },
			{ "ru chang", "入场" }, { "ru chang", "如常" }, { "ru chang quan", "入场券" }, { "ru chao", "如潮" }, { "ru chong", "蠕虫" }, { "ru chu", "如初" },
			{ "ru chu yi zhe", "如出一辙" }, { "ru ci", "如此" }, { "ru ci duo", "如此多" }, { "ru ci yi lai", "如此一来" }, { "ru ci zhe ban", "如此这般" },
			{ "ru ci zhi", "如此之" }, { "ru dang", "入党" }, { "ru dong", "蠕动" }, { "ru dui", "如对" }, { "ru er", "入耳" }, { "ru fang", "乳房" }, { "ru feng", "如风" },
			{ "ru ge", "如歌" }, { "ru gong", "入宫" }, { "ru gou", "乳沟" }, { "ru gu", "入股" }, { "ru gu", "如故" }, { "ru guan", "入关" }, { "ru guo", "如果" },
			{ "ru hai", "入海" }, { "ru he", "如何" }, { "ru he cai neng", "如何才能" }, { "ru he cao zuo", "如何操作" }, { "ru he chu li", "如何处理" },
			{ "ru he dui dai", "如何对待" }, { "ru he jiang", "如何将" }, { "ru he jie jue", "如何解决" }, { "ru he jin xing", "如何进行" }, { "ru he kan dai", "如何看待" },
			{ "ru he li yong", "如何利用" }, { "ru he mian dui", "如何面对" }, { "ru he qu", "如何去" }, { "ru he shi hao", "如何是好" }, { "ru he shi xian", "如何实现" },
			{ "ru he shi yong", "如何使用" }, { "ru he ti gao", "如何提高" }, { "ru he xuan ze", "如何选择" }, { "ru he ying dui", "如何应对" }, { "ru he yong", "如何用" },
			{ "ru he zuo", "如何做" }, { "ru he zuo hao", "如何做好" }, { "ru hu", "入户" }, { "ru hua", "乳化" }, { "ru hua", "如画" }, { "ru hua", "如花" },
			{ "ru hui", "入会" }, { "ru huo", "入伙" }, { "ru huo", "如火" }, { "ru huo ru tu", "如火如荼" }, { "ru jia", "儒家" }, { "ru jia", "如家" },
			{ "ru jia si xiang", "儒家思想" }, { "ru jiao qi", "乳胶漆" }, { "ru jin", "如今" }, { "ru jing", "入境" }, { "ru kou", "入口" }, { "ru kou chu", "入口处" },
			{ "ru ku", "入库" }, { "ru lai", "如来" }, { "ru ma", "辱骂" }, { "ru men", "入门" }, { "ru men ji", "入门级" }, { "ru meng", "入梦" }, { "ru meng", "如梦" },
			{ "ru mian", "入眠" }, { "ru nei", "入内" }, { "ru neng", "如能" }, { "ru ni", "如你" }, { "ru nin", "如您" }, { "ru pin", "乳品" }, { "ru qi", "如期" },
			{ "ru qin", "入侵" }, { "ru qin zhe", "入侵者" }, { "ru qiu", "入球" }, { "ru ri zhong tian", "如日中天" }, { "ru ruo", "如若" }, { "ru shan", "如山" },
			{ "ru shang", "如上" }, { "ru shi", "入世" }, { "ru shi", "入室" }, { "ru shi", "入市" }, { "ru shi", "如实" }, { "ru shi", "如是" }, { "ru shi shuo", "如是说" },
			{ "ru shou", "入手" }, { "ru shui", "入睡" }, { "ru shui", "如水" }, { "ru si", "如斯" }, { "ru suan", "乳酸" }, { "ru ti", "如题" }, { "ru tong", "如同" },
			{ "ru tou", "乳头" }, { "ru tu", "如图" }, { "ru wang", "入网" }, { "ru wei", "入味" }, { "ru wei", "入围" }, { "ru wei", "入微" }, { "ru wu", "入伍" },
			{ "ru wu", "如无" }, { "ru xia", "如下" }, { "ru xia tu", "如下图" }, { "ru xian", "乳腺" }, { "ru xian ai", "乳腺癌" }, { "ru xin", "如新" }, { "ru xu", "如需" },
			{ "ru xuan", "入选" }, { "ru xue", "儒学" }, { "ru xue", "入学" }, { "ru xue", "如雪" }, { "ru xue kao shi", "入学考试" }, { "ru ya", "儒雅" },
			{ "ru yan", "如烟" }, { "ru yao", "如要" }, { "ru ye", "乳业" }, { "ru ye", "乳液" }, { "ru yi", "如意" }, { "ru yin", "如因" }, { "ru you", "如有" },
			{ "ru you wen ti", "如有问题" }, { "ru yu", "入狱" }, { "ru yu", "如玉" }, { "ru yu", "如遇" }, { "ru yu de shui", "如鱼得水" }, { "ru yuan", "入园" },
			{ "ru yuan", "入院" }, { "ru yuan", "如愿" }, { "ru yuan yi chang", "如愿以偿" }, { "ru yue", "如月" }, { "ru yue", "如约" }, { "ru yun", "如云" },
			{ "ru zai", "如在" }, { "ru zhang", "入账" }, { "ru zhi", "乳汁" }, { "ru zhi", "入职" }, { "ru zhi pin", "乳制品" }, { "ru zhu", "入主" }, { "ru zhu", "入住" },
			{ "ru zhu", "入驻" }, { "ruan", "堧" }, { "ruan", "壖" }, { "ruan", "朊" }, { "ruan", "檽" }, { "ruan", "燸" }, { "ruan", "瓀" }, { "ruan", "礝" },
			{ "ruan", "緛" }, { "ruan", "耎" }, { "ruan", "蝡" }, { "ruan", "軟" }, { "ruan", "软" }, { "ruan", "阮" }, { "ruan gao", "软膏" }, { "ruan gu", "软骨" },
			{ "ruan guan", "软管" }, { "ruan hua", "软化" }, { "ruan huan jing", "软环境" }, { "ruan jian", "软件" }, { "ruan jian bao", "软件包" },
			{ "ruan jian ce shi", "软件测试" }, { "ruan jian chan pin", "软件产品" }, { "ruan jian chan ye", "软件产业" }, { "ruan jian chang shang", "软件厂商" },
			{ "ruan jian gong cheng", "软件工程" }, { "ruan jian gong ju", "软件工具" }, { "ruan jian gong si", "软件公司" }, { "ruan jian kai fa", "软件开发" },
			{ "ruan jian qi ye", "软件企业" }, { "ruan jian wai bao", "软件外包" }, { "ruan jian xi tong", "软件系统" }, { "ruan jian xia zai", "软件下载" },
			{ "ruan jian xue yuan", "软件学院" }, { "ruan jian ye", "软件业" }, { "ruan jian yuan", "软件园" }, { "ruan jiao huan", "软交换" }, { "ruan jin", "软禁" },
			{ "ruan lei", "软肋" }, { "ruan mian mian", "软绵绵" }, { "ruan pan", "软盘" }, { "ruan qu", "软驱" }, { "ruan ruan", "软软" }, { "ruan ruo", "软弱" },
			{ "ruan shi li", "软实力" }, { "ruan ti", "软体" }, { "ruan wen", "软文" }, { "ruan wo", "软卧" }, { "ruan xing", "软性" }, { "ruan yin", "软银" },
			{ "ruan ying", "软硬" }, { "ruan ying jian", "软硬件" }, { "ruan zu zhi", "软组织" }, { "rui", "兊" }, { "rui", "叡" }, { "rui", "枘" }, { "rui", "桵" },
			{ "rui", "橤" }, { "rui", "汭" }, { "rui", "瑞" }, { "rui", "睿" }, { "rui", "緌" }, { "rui", "繠" }, { "rui", "芮" }, { "rui", "蕊" }, { "rui", "蕋" },
			{ "rui", "蕤" }, { "rui", "蘂" }, { "rui", "蚋" }, { "rui", "銳" }, { "rui", "锐" }, { "rui an", "瑞安" }, { "rui dian", "瑞典" }, { "rui jian", "锐减" },
			{ "rui jin", "瑞金" }, { "rui li", "瑞丽" }, { "rui li", "锐利" }, { "rui qi", "锐气" }, { "rui shi", "瑞士" }, { "rui xing", "瑞星" }, { "rui yi", "锐意" },
			{ "rui yin", "瑞银" }, { "rui zhi", "睿智" }, { "rui zhi", "锐志" }, { "run", "橍" }, { "run", "润" }, { "run", "潤" }, { "run", "閏" }, { "run", "閠" },
			{ "run", "闰" }, { "run fei", "润肺" }, { "run fu", "润肤" }, { "run hua", "润滑" }, { "run hua ji", "润滑剂" }, { "run hua you", "润滑油" },
			{ "run se", "润色" }, { "run ze", "润泽" }, { "ruo", "偌" }, { "ruo", "婼" }, { "ruo", "嵶" }, { "ruo", "弱" }, { "ruo", "撋" }, { "ruo", "楉" },
			{ "ruo", "渃" }, { "ruo", "爇" }, { "ruo", "箬" }, { "ruo", "篛" }, { "ruo", "若" }, { "ruo", "蒻" }, { "ruo", "鄀" }, { "ruo", "鰯" }, { "ruo", "鶸" },
			{ "ruo bu", "若不" }, { "ruo bu shi", "若不是" }, { "ruo da", "偌大" }, { "ruo dian", "弱点" }, { "ruo dian", "弱电" }, { "ruo fei", "若非" },
			{ "ruo gan", "若干" }, { "ruo gan wen ti", "若干问题" }, { "ruo gan yi jian", "若干意见" }, { "ruo guo", "弱国" }, { "ruo hua", "弱化" },
			{ "ruo ji ruo li", "若即若离" }, { "ruo mei you", "若没有" }, { "ruo neng", "若能" }, { "ruo shi", "弱势" }, { "ruo shi", "若是" },
			{ "ruo shi qun ti", "弱势群体" }, { "ruo shui", "若水" }, { "ruo wu", "若无" }, { "ruo wu qi shi", "若无其事" }, { "ruo xiang", "弱项" }, { "ruo xiang", "若想" },
			{ "ruo xiao", "弱小" }, { "ruo yao", "若要" }, { "ruo yin ruo xian", "若隐若现" }, { "ruo you", "若有" }, { "ruo you suo si", "若有所思" }, { "ruo zhe", "弱者" },
			{ "ruo zhi", "弱智" }, { "sa", "仨" }, { "sa", "卅" }, { "sa", "挲" }, { "sa", "摋" }, { "sa", "撒" }, { "sa", "攃" }, { "sa", "洒" }, { "sa", "灑" },
			{ "sa", "脎" }, { "sa", "萨" }, { "sa", "薩" }, { "sa", "隡" }, { "sa", "靸" }, { "sa", "颯" }, { "sa", "飒" }, { "sa", "馺" }, { "sa da mu", "萨达姆" },
			{ "sa dan", "撒旦" }, { "sa er", "萨尔" }, { "sa huang", "撒谎" }, { "sa jiao", "撒娇" } };
};
