package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN05 {
	public static String[][] pl = { { "cai gan", "才干" }, { "cai gan", "才敢" }, { "cai gang", "才刚" }, { "cai gei", "才给" }, { "cai gou", "采购" },
			{ "cai gou bu", "采购部" }, { "cai gou shang", "采购商" }, { "cai guai", "才怪" }, { "cai guan", "菜馆" }, { "cai guang", "采光" }, { "cai hao", "才好" },
			{ "cai he", "彩盒" }, { "cai hong", "彩虹" }, { "cai hong dao", "彩虹岛" }, { "cai hua", "才华" }, { "cai hua", "菜花" }, { "cai hua", "采花" },
			{ "cai hua heng yi", "才华横溢" }, { "cai hui", "彩绘" }, { "cai hui", "才会" }, { "cai hui", "才回" }, { "cai hui you", "才会有" }, { "cai ji", "猜忌" },
			{ "cai ji", "采集" }, { "cai jia", "菜价" }, { "cai jian", "裁减" }, { "cai jian", "裁剪" }, { "cai jiao", "才叫" }, { "cai jing", "财经" },
			{ "cai jing da xue", "财经大学" }, { "cai jue", "裁决" }, { "cai kai shi", "才开始" }, { "cai kang yong", "蔡康永" }, { "cai ke", "才可" },
			{ "cai ke yi", "才可以" }, { "cai ken", "才肯" }, { "cai kuai", "财会" }, { "cai kuang", "采矿" }, { "cai kuang quan", "采矿权" }, { "cai lai", "才来" },
			{ "cai li", "财力" }, { "cai liao", "材料" }, { "cai ling", "彩铃" }, { "cai mai", "才买" }, { "cai min", "彩民" }, { "cai ming bai", "才明白" },
			{ "cai na", "采纳" }, { "cai neng", "才能" }, { "cai neng gou", "才能够" }, { "cai neng rang", "才能让" }, { "cai nian", "财年" }, { "cai niao", "菜鸟" },
			{ "cai nong", "菜农" }, { "cai nuan", "采暖" }, { "cai nv", "才女" }, { "cai pai", "彩排" }, { "cai pan", "裁判" }, { "cai pan yuan", "裁判员" },
			{ "cai piao", "彩票" }, { "cai pin", "菜品" }, { "cai ping", "彩屏" }, { "cai pu", "菜谱" }, { "cai qi", "才气" }, { "cai qin", "蔡琴" }, { "cai qing", "才情" },
			{ "cai qu", "才去" }, { "cai qu", "采取" }, { "cai qu cuo shi", "采取措施" }, { "cai qu xing dong", "采取行动" }, { "cai rang", "才让" }, { "cai se", "彩色" },
			{ "cai shao fen", "蔡少芬" }, { "cai shen", "财神" }, { "cai shi", "才使" }, { "cai shi", "才是" }, { "cai shi", "菜式" }, { "cai shi chang", "菜市场" },
			{ "cai shi zhen zheng", "才是真正" }, { "cai shou", "采收" }, { "cai shui", "才睡" }, { "cai shui", "财税" }, { "cai shuo", "才说" }, { "cai si", "踩死" },
			{ "cai suan", "才算" }, { "cai suan shi", "才算是" }, { "cai ta", "踩踏" }, { "cai tuan", "财团" }, { "cai wu", "财务" }, { "cai wu", "财物" },
			{ "cai wu bao biao", "财务报表" }, { "cai wu bao gao", "财务报告" }, { "cai wu bu", "财务部" }, { "cai wu guan li", "财务管理" }, { "cai wu ren yuan", "财务人员" },
			{ "cai wu ruan jian", "财务软件" }, { "cai wu zhuang kuang", "财务状况" }, { "cai wu zong jian", "财务总监" }, { "cai xi", "菜系" }, { "cai xia", "彩霞" },
			{ "cai xian", "财险" }, { "cai xiang", "猜想" }, { "cai xie", "采写" }, { "cai xin", "彩信" }, { "cai xing", "才行" }, { "cai yang", "采样" },
			{ "cai yao", "才要" }, { "cai yao", "菜肴" }, { "cai yao", "采药" }, { "cai ye", "彩页" }, { "cai yi", "才艺" }, { "cai yi", "猜疑" }, { "cai yi lin", "蔡依林" },
			{ "cai yong", "才用" }, { "cai yong", "采用" }, { "cai you", "才有" }, { "cai yuan", "菜园" }, { "cai yuan", "裁员" }, { "cai yuan", "财源" },
			{ "cai yun", "彩云" }, { "cai yun", "财运" }, { "cai zai", "踩在" }, { "cai zhai", "采摘" }, { "cai zhang", "财长" }, { "cai zhe", "踩着" },
			{ "cai zheng", "财政" }, { "cai zheng bu", "财政部" }, { "cai zheng bu men", "财政部门" }, { "cai zheng bu tie", "财政补贴" }, { "cai zheng bu zhang", "财政部长" },
			{ "cai zheng ju", "财政局" }, { "cai zheng shou ru", "财政收入" }, { "cai zheng yu suan", "财政预算" }, { "cai zheng zheng ce", "财政政策" },
			{ "cai zheng zhi chu", "财政支出" }, { "cai zheng zi jin", "财政资金" }, { "cai zhi", "才智" }, { "cai zhi", "才知" }, { "cai zhi", "材质" },
			{ "cai zhi dao", "才知道" }, { "cai zhong", "猜中" }, { "cai zhu", "财主" }, { "cai zhuang", "彩妆" }, { "cai zi", "才子" }, { "cai zou", "才走" },
			{ "can", "参" }, { "can", "參" }, { "can", "嬠" }, { "can", "孱" }, { "can", "惨" }, { "can", "惭" }, { "can", "慘" }, { "can", "慙" }, { "can", "慚" },
			{ "can", "憯" }, { "can", "残" }, { "can", "殘" }, { "can", "澯" }, { "can", "灿" }, { "can", "燦" }, { "can", "璨" }, { "can", "粲" }, { "can", "蚕" },
			{ "can", "蠶" }, { "can", "飡" }, { "can", "餐" }, { "can", "驂" }, { "can", "骖" }, { "can", "黪" }, { "can", "黲" }, { "can an", "惨案" },
			{ "can ao hui", "残奥会" }, { "can bai", "参拜" }, { "can bai", "惨白" }, { "can bai", "惨败" }, { "can bao", "参保" }, { "can bao", "残暴" },
			{ "can bu ren du", "惨不忍睹" }, { "can cun", "残存" }, { "can dan", "惨淡" }, { "can dou", "蚕豆" }, { "can fei", "残废" }, { "can fei", "餐费" },
			{ "can gu", "参股" }, { "can guan", "参观" }, { "can guan", "餐馆" }, { "can guan zhe", "参观者" }, { "can hai", "残害" }, { "can hai", "残骸" },
			{ "can he", "参合" }, { "can hou", "餐后" }, { "can hui", "参会" }, { "can ji", "残疾" }, { "can ji ren", "残疾人" }, { "can jia", "参加" },
			{ "can jia gao kao", "参加高考" }, { "can jia gong zuo", "参加工作" }, { "can jia hui yi", "参加会议" }, { "can jia huo dong", "参加活动" },
			{ "can jia zhe", "参加者" }, { "can jian", "参见" }, { "can jiao", "惨叫" }, { "can ju", "惨剧" }, { "can ju", "餐具" }, { "can jun", "参军" },
			{ "can kan", "参看" }, { "can kao", "参考" }, { "can kao jia ge", "参考价格" }, { "can kao shu", "参考书" }, { "can kao wen xian", "参考文献" },
			{ "can kao zi liao", "参考资料" }, { "can ku", "残酷" }, { "can kui", "惭愧" }, { "can lan", "灿烂" }, { "can lian", "残联" }, { "can lie", "惨烈" },
			{ "can liu", "残留" }, { "can liu wu", "残留物" }, { "can mou", "参谋" }, { "can mou zhang", "参谋长" }, { "can ping", "参评" }, { "can po", "残破" },
			{ "can que", "残缺" }, { "can ren", "残忍" }, { "can sai", "参赛" }, { "can sai xuan shou", "参赛选手" }, { "can sai zhe", "参赛者" }, { "can sha", "残杀" },
			{ "can shi", "蚕食" }, { "can shu", "参数" }, { "can si", "惨死" }, { "can ting", "餐厅" }, { "can tong", "惨痛" }, { "can xuan", "参选" },
			{ "can yan", "参演" }, { "can yang", "残阳" }, { "can yi yuan", "参议员" }, { "can yi yuan", "参议院" }, { "can yin", "餐饮" }, { "can yin qi ye", "餐饮企业" },
			{ "can yin ye", "餐饮业" }, { "can yu", "参与" }, { "can yu", "残余" }, { "can yu zhe", "参与者" }, { "can yue", "参阅" }, { "can zao", "惨遭" },
			{ "can zha", "残渣" }, { "can zhan", "参展" }, { "can zhan", "参战" }, { "can zhan qi ye", "参展企业" }, { "can zhan shang", "参展商" }, { "can zhao", "参照" },
			{ "can zheng", "参政" }, { "can zheng yi zheng", "参政议政" }, { "can zhong", "惨重" }, { "can zhuo", "餐桌" }, { "cang", "仓" }, { "cang", "伧" },
			{ "cang", "倉" }, { "cang", "凔" }, { "cang", "嵢" }, { "cang", "欌" }, { "cang", "沧" }, { "cang", "滄" }, { "cang", "獊" }, { "cang", "臧" },
			{ "cang", "舱" }, { "cang", "艙" }, { "cang", "苍" }, { "cang", "蒼" }, { "cang", "藏" }, { "cang", "鑶" }, { "cang bai", "苍白" }, { "cang bao", "藏宝" },
			{ "cang chu", "仓储" }, { "cang cu", "仓促" }, { "cang hai", "沧海" }, { "cang huang", "仓皇" }, { "cang ku", "仓库" }, { "cang lao", "苍老" },
			{ "cang liang", "苍凉" }, { "cang mang", "苍茫" }, { "cang ni", "藏匿" }, { "cang pin", "藏品" }, { "cang qi lai", "藏起来" }, { "cang qiong", "苍穹" },
			{ "cang sang", "沧桑" }, { "cang shan", "苍山" }, { "cang shen", "藏身" }, { "cang sheng", "苍生" }, { "cang shu", "仓鼠" }, { "cang shu", "藏书" },
			{ "cang tian", "苍天" }, { "cang wei", "仓位" }, { "cang wei", "舱位" }, { "cang ying", "苍蝇" }, { "cang ying", "苍鹰" }, { "cang you", "藏有" },
			{ "cang zai", "藏在" }, { "cang zhe", "藏着" }, { "cang zhou", "沧州" }, { "cao", "嘈" }, { "cao", "嶆" }, { "cao", "操" }, { "cao", "曹" }, { "cao", "曺" },
			{ "cao", "槽" }, { "cao", "漕" }, { "cao", "糙" }, { "cao", "肏" }, { "cao", "艚" }, { "cao", "艸" }, { "cao", "艹" }, { "cao", "草" }, { "cao", "螬" },
			{ "cao", "襙" }, { "cao", "騲" }, { "cao an", "草案" }, { "cao ban", "操办" }, { "cao ben", "草本" }, { "cao cao", "曹操" }, { "cao cao", "草草" },
			{ "cao chang", "操场" }, { "cao chang", "草场" }, { "cao cong", "草丛" }, { "cao dao", "操刀" }, { "cao di", "草地" }, { "cao gao", "草稿" },
			{ "cao gen", "草根" }, { "cao kong", "操控" }, { "cao kong xing", "操控性" }, { "cao lao", "操劳" }, { "cao lian", "操练" }, { "cao mao", "草帽" },
			{ "cao mei", "草莓" }, { "cao min", "草民" }, { "cao mu", "草木" }, { "cao ni", "草拟" }, { "cao pan", "操盘" }, { "cao pan shou", "操盘手" },
			{ "cao pi", "草皮" }, { "cao ping", "草坪" }, { "cao shou", "操守" }, { "cao shuai", "草率" }, { "cao tang", "草堂" }, { "cao tu", "草图" },
			{ "cao xin", "操心" }, { "cao xue qin", "曹雪芹" }, { "cao yao", "草药" }, { "cao yuan", "草原" }, { "cao za", "嘈杂" }, { "cao zhe", "操着" },
			{ "cao zong", "操纵" }, { "cao zuo", "操作" }, { "cao zuo fang fa", "操作方法" }, { "cao zuo fang shi", "操作方式" }, { "cao zuo gui cheng", "操作规程" },
			{ "cao zuo guo cheng", "操作过程" }, { "cao zuo jie mian", "操作界面" }, { "cao zuo quan xian", "操作权限" }, { "cao zuo ren yuan", "操作人员" },
			{ "cao zuo xi tong", "操作系统" }, { "cao zuo xing", "操作性" }, { "cao zuo yuan", "操作员" }, { "cao zuo zhe", "操作者" }, { "ce", "侧" }, { "ce", "側" },
			{ "ce", "冊" }, { "ce", "册" }, { "ce", "厕" }, { "ce", "廁" }, { "ce", "恻" }, { "ce", "惻" }, { "ce", "憡" }, { "ce", "测" }, { "ce", "測" },
			{ "ce", "策" }, { "ce", "萴" }, { "ce", "蓛" }, { "ce bian lan", "侧边栏" }, { "ce ce", "测测" }, { "ce chu", "测出" }, { "ce de", "测得" },
			{ "ce ding", "测定" }, { "ce guang", "测光" }, { "ce hua", "策划" }, { "ce hua ren", "策划人" }, { "ce hui", "测绘" }, { "ce kong", "测控" },
			{ "ce liang", "测量" }, { "ce lue", "策略" }, { "ce mian", "侧面" }, { "ce mu", "侧目" }, { "ce ping", "测评" }, { "ce shen", "侧身" }, { "ce shi", "测试" },
			{ "ce shi ban", "测试版" }, { "ce shi jie guo", "测试结果" }, { "ce shi yi", "测试仪" }, { "ce shi yong li", "测试用例" }, { "ce su", "测速" },
			{ "ce suan", "测算" }, { "ce suo", "厕所" }, { "ce suo li", "厕所里" }, { "ce tu", "测土" }, { "ce xu", "测序" }, { "ce yan", "测验" }, { "ce zhong", "侧重" },
			{ "ce zhong dian", "侧重点" }, { "ce zi", "册子" }, { "cen", "参" }, { "cen", "岑" }, { "cen", "嵾" }, { "cen", "梣" }, { "cen", "涔" }, { "cen ci", "参差" },
			{ "cen ci bu qi", "参差不齐" }, { "ceng", "噌" }, { "ceng", "层" }, { "ceng", "層" }, { "ceng", "嶒" }, { "ceng", "曾" }, { "ceng", "蹭" }, { "ceng", "驓" },
			{ "ceng bei", "曾被" }, { "ceng ceng", "层层" }, { "ceng chu bu qiong", "层出不穷" }, { "ceng ci", "层次" }, { "ceng ci gan", "层次感" }, { "ceng dui", "曾对" },
			{ "ceng gao", "层高" }, { "ceng huo", "曾获" }, { "ceng ji", "层级" }, { "ceng ji he shi", "曾几何时" }, { "ceng jing", "曾经" }, { "ceng jing de", "曾经的" },
			{ "ceng jing shuo guo", "曾经说过" }, { "ceng jing yong you", "曾经拥有" }, { "ceng lou", "层楼" }, { "ceng mian", "层面" }, { "ceng ren", "曾任" },
			{ "ceng shi", "曾是" }, { "ceng shuo", "曾说" }, { "ceng wei", "曾为" }, { "ceng xiang", "曾向" }, { "ceng xiang", "曾想" }, { "ceng yi", "曾以" },
			{ "ceng yin", "曾因" }, { "ceng you", "曾有" }, { "ceng yu", "曾与" }, { "ceng yu", "曾于" }, { "ceng zai", "曾在" }, { "cha", "侘" }, { "cha", "偛" },
			{ "cha", "刹" }, { "cha", "叉" }, { "cha", "喳" }, { "cha", "嗏" }, { "cha", "嚓" }, { "cha", "垞" }, { "cha", "奼" }, { "cha", "姹" }, { "cha", "察" },
			{ "cha", "岔" }, { "cha", "差" }, { "cha", "插" }, { "cha", "搽" }, { "cha", "杈" }, { "cha", "查" }, { "cha", "査" }, { "cha", "楂" }, { "cha", "槎" },
			{ "cha", "檫" }, { "cha", "汊" }, { "cha", "猹" }, { "cha", "疀" }, { "cha", "碴" }, { "cha", "紁" }, { "cha", "臿" }, { "cha", "艖" }, { "cha", "茬" },
			{ "cha", "茶" }, { "cha", "衩" }, { "cha", "诧" }, { "cha", "蹅" }, { "cha", "鍤" }, { "cha", "锸" }, { "cha", "镲" }, { "cha", "靫" }, { "cha", "馇" },
			{ "cha ba", "插拔" }, { "cha ban", "查办" }, { "cha bei", "茶杯" }, { "cha bie", "差别" }, { "cha bo", "插播" }, { "cha bu dao", "查不到" },
			{ "cha bu duo", "差不多" }, { "cha can ting", "茶餐厅" }, { "cha cao", "插槽" }, { "cha cha", "叉叉" }, { "cha cha", "查查" }, { "cha che", "叉车" },
			{ "cha chu", "查出" }, { "cha chu", "查处" }, { "cha cuo", "差错" }, { "cha dao", "插到" }, { "cha dao", "查到" }, { "cha dao", "茶道" }, { "cha de", "差得" },
			{ "cha dian", "差点" }, { "cha dian er", "差点儿" }, { "cha du", "查毒" }, { "cha dui", "插队" }, { "cha e", "差额" }, { "cha er dun", "查尔顿" },
			{ "cha er si", "查尔斯" }, { "cha fen", "差分" }, { "cha fen", "查分" }, { "cha feng", "查封" }, { "cha guan", "茶馆" }, { "cha guo", "查过" },
			{ "cha hu", "茶壶" }, { "cha hua", "插画" }, { "cha hua", "插花" }, { "cha huo", "查获" }, { "cha ji", "茶几" }, { "cha jia", "差价" }, { "cha jian", "插件" },
			{ "cha jin", "差劲" }, { "cha jin", "插进" }, { "cha jin qu", "插进去" }, { "cha ju", "差距" }, { "cha ju", "茶具" }, { "cha jue", "察觉" }, { "cha ka", "插卡" },
			{ "cha kan", "察看" }, { "cha kan", "查看" }, { "cha kan geng duo", "查看更多" }, { "cha kong", "插孔" }, { "cha kou", "插口" }, { "cha li", "查理" },
			{ "cha lou", "茶楼" }, { "cha ming", "查明" }, { "cha na", "刹那" }, { "cha na jian", "刹那间" }, { "cha ping", "差评" }, { "cha qiang ren yi", "差强人意" },
			{ "cha qing", "查清" }, { "cha qu", "插曲" }, { "cha ru", "插入" }, { "cha sha", "查杀" }, { "cha shang", "插上" }, { "cha shao", "叉烧" },
			{ "cha shi", "查实" }, { "cha shou", "插手" }, { "cha shou", "查收" }, { "cha shu", "茶树" }, { "cha shui", "茶水" }, { "cha tou", "插头" },
			{ "cha tu", "插图" }, { "cha wei si", "查韦斯" }, { "cha wen hua", "茶文化" }, { "cha xun", "查询" }, { "cha xun jie guo", "查询结果" }, { "cha yan", "查验" },
			{ "cha ye", "茶叶" }, { "cha yi", "差异" }, { "cha yi", "诧异" }, { "cha yi dian", "差一点" }, { "cha yi hua", "差异化" }, { "cha yi xing", "差异性" },
			{ "cha yu fan hou", "茶余饭后" }, { "cha yuan", "茶园" }, { "cha yue", "查阅" }, { "cha zai", "插在" }, { "cha zhao", "查找" }, { "cha zhe", "插着" },
			{ "cha zheng", "查证" }, { "cha zhi", "差值" }, { "cha zhi", "插值" }, { "cha zi", "叉子" }, { "cha zui", "插嘴" }, { "cha zuo", "插座" }, { "chai", "侪" },
			{ "chai", "儕" }, { "chai", "喍" }, { "chai", "囆" }, { "chai", "差" }, { "chai", "拆" }, { "chai", "柴" }, { "chai", "犲" }, { "chai", "瘥" },
			{ "chai", "祡" }, { "chai", "虿" }, { "chai", "蠆" }, { "chai", "袃" }, { "chai", "豺" }, { "chai", "釵" }, { "chai", "钗" }, { "chai chu", "拆除" },
			{ "chai diao", "拆掉" }, { "chai fen", "拆分" }, { "chai huo", "柴火" }, { "chai ji", "拆机" }, { "chai jie", "拆解" }, { "chai kai", "拆开" },
			{ "chai le", "拆了" }, { "chai lv", "差旅" }, { "chai lv fei", "差旅费" }, { "chai qian", "拆迁" }, { "chai qian hu", "拆迁户" }, { "chai qian ren", "拆迁人" },
			{ "chai san", "拆散" }, { "chai shi", "差事" }, { "chai xia", "拆下" }, { "chai xie", "拆卸" }, { "chai you", "柴油" }, { "chai you ji", "柴油机" },
			{ "chai zhuang", "拆装" }, { "chan", "丳" }, { "chan", "产" }, { "chan", "儳" }, { "chan", "冁" }, { "chan", "剷" }, { "chan", "劖" }, { "chan", "单" },
			{ "chan", "嚵" }, { "chan", "囅" }, { "chan", "壥" }, { "chan", "婵" }, { "chan", "嬋" }, { "chan", "孱" }, { "chan", "嵼" }, { "chan", "巉" },
			{ "chan", "幝" }, { "chan", "幨" }, { "chan", "廛" }, { "chan", "忏" }, { "chan", "懴" }, { "chan", "懺" }, { "chan", "掺" }, { "chan", "搀" },
			{ "chan", "摲" }, { "chan", "摻" }, { "chan", "旵" }, { "chan", "梴" }, { "chan", "棎" }, { "chan", "毚" }, { "chan", "湹" }, { "chan", "滻" },
			{ "chan", "潺" }, { "chan", "澶" }, { "chan", "瀍" }, { "chan", "瀺" }, { "chan", "灛" }, { "chan", "煘" }, { "chan", "獑" }, { "chan", "產" },
			{ "chan", "産" }, { "chan", "磛" }, { "chan", "禅" }, { "chan", "禪" }, { "chan", "簅" }, { "chan", "繟" }, { "chan", "纏" }, { "chan", "纒" },
			{ "chan", "缠" }, { "chan", "羼" }, { "chan", "艬" }, { "chan", "蒇" }, { "chan", "蕆" }, { "chan", "蝉" }, { "chan", "蟬" }, { "chan", "蟾" },
			{ "chan", "襜" }, { "chan", "觇" }, { "chan", "諂" }, { "chan", "讒" }, { "chan", "谄" }, { "chan", "谗" }, { "chan", "躔" }, { "chan", "辿" },
			{ "chan", "酁" }, { "chan", "鋋" }, { "chan", "鋓" }, { "chan", "鏟" }, { "chan", "鑱" }, { "chan", "铲" }, { "chan", "闡" }, { "chan", "阐" },
			{ "chan", "顫" }, { "chan", "颤" }, { "chan", "饞" }, { "chan", "馋" }, { "chan", "骣" }, { "chan chan", "潺潺" }, { "chan chu", "产出" },
			{ "chan chu", "蟾蜍" }, { "chan chu", "铲除" }, { "chan di", "产地" }, { "chan dong", "颤动" }, { "chan dou", "颤抖" }, { "chan fang", "产房" },
			{ "chan fu", "产妇" }, { "chan fu", "搀扶" }, { "chan hou", "产后" }, { "chan hui", "忏悔" }, { "chan jia", "产假" }, { "chan ke", "产科" },
			{ "chan lian", "蝉联" }, { "chan liang", "产量" }, { "chan luan", "产卵" }, { "chan mian", "缠绵" }, { "chan ming", "阐明" }, { "chan neng", "产能" },
			{ "chan neng guo sheng", "产能过剩" }, { "chan pin", "产品" }, { "chan pin bu", "产品部" }, { "chan pin chu kou", "产品出口" },
			{ "chan pin chuang xin", "产品创新" }, { "chan pin jia ge", "产品价格" }, { "chan pin jie gou", "产品结构" }, { "chan pin jie shao", "产品介绍" },
			{ "chan pin jing li", "产品经理" }, { "chan pin kai fa", "产品开发" }, { "chan pin she ji", "产品设计" }, { "chan pin shi chang", "产品市场" },
			{ "chan pin xi lie", "产品系列" }, { "chan pin xian", "产品线" }, { "chan pin xiao shou", "产品销售" }, { "chan pin xin xi", "产品信息" },
			{ "chan pin yan fa", "产品研发" }, { "chan pin zhan shi", "产品展示" }, { "chan pin zhi liang", "产品质量" }, { "chan qian", "产前" }, { "chan qu", "产区" },
			{ "chan quan", "产权" }, { "chan quan fang", "产权房" }, { "chan quan zheng", "产权证" }, { "chan rao", "缠绕" }, { "chan shen", "缠身" },
			{ "chan sheng", "产生" }, { "chan sheng ying xiang", "产生影响" }, { "chan shi", "禅师" }, { "chan shi", "阐释" }, { "chan shu", "阐述" }, { "chan wu", "产物" },
			{ "chan xia", "产下" }, { "chan xiao", "产销" }, { "chan xiao liang", "产销量" }, { "chan xue yan", "产学研" }, { "chan ye", "产业" },
			{ "chan ye fa zhan", "产业发展" }, { "chan ye hua", "产业化" }, { "chan ye ji di", "产业基地" }, { "chan ye ji qun", "产业集群" }, { "chan ye jie gou", "产业结构" },
			{ "chan ye lian", "产业链" }, { "chan ye sheng ji", "产业升级" }, { "chan ye yuan", "产业园" }, { "chan ye zheng ce", "产业政策" },
			{ "chan ye zhuan yi", "产业转移" }, { "chan yu", "产于" }, { "chan yu", "单于" }, { "chan za", "掺杂" }, { "chan zhe", "缠着" }, { "chan zhi", "产值" },
			{ "chan zhu", "缠住" }, { "chan zi", "产自" }, { "chan zi", "铲子" }, { "chan zong", "禅宗" }, { "chang", "伥" }, { "chang", "倘" }, { "chang", "倡" },
			{ "chang", "偿" }, { "chang", "僘" }, { "chang", "償" }, { "chang", "厂" }, { "chang", "厰" }, { "chang", "唱" }, { "chang", "嘗" }, { "chang", "嚐" },
			{ "chang", "场" }, { "chang", "場" }, { "chang", "娼" }, { "chang", "嫦" }, { "chang", "尝" }, { "chang", "常" }, { "chang", "廠" }, { "chang", "徜" },
			{ "chang", "怅" }, { "chang", "悵" }, { "chang", "惝" }, { "chang", "敞" }, { "chang", "昌" }, { "chang", "昶" }, { "chang", "暢" }, { "chang", "椙" },
			{ "chang", "氅" }, { "chang", "淐" }, { "chang", "猖" }, { "chang", "琩" }, { "chang", "甞" }, { "chang", "畅" }, { "chang", "肠" }, { "chang", "腸" },
			{ "chang", "膓" }, { "chang", "苌" }, { "chang", "菖" }, { "chang", "萇" }, { "chang", "蟐" }, { "chang", "裮" }, { "chang", "裳" }, { "chang", "鋹" },
			{ "chang", "鋿" }, { "chang", "錩" }, { "chang", "長" }, { "chang", "长" }, { "chang", "阊" }, { "chang", "韔" }, { "chang", "鬯" }, { "chang", "鯧" },
			{ "chang", "鱨" }, { "chang", "鲳" }, { "chang", "鼚" }, { "chang an", "长安" }, { "chang an fu te", "长安福特" }, { "chang an jie", "长安街" },
			{ "chang bai shan", "长白山" }, { "chang bei", "常被" }, { "chang bi sai", "场比赛" }, { "chang bian", "场边" }, { "chang ce", "长策" },
			{ "chang chang", "尝尝" }, { "chang chang", "常常" }, { "chang chang", "长长" }, { "chang chang de", "长长的" }, { "chang cheng", "长城" },
			{ "chang chi", "常吃" }, { "chang chu", "唱出" }, { "chang chu", "长处" }, { "chang chuan", "长传" }, { "chang chun", "长春" }, { "chang chun shi", "长春市" },
			{ "chang ci", "场次" }, { "chang ci yi wang", "长此以往" }, { "chang da", "长达" }, { "chang dao", "倡导" }, { "chang dao", "唱到" }, { "chang dao", "尝到" },
			{ "chang dao", "肠道" }, { "chang de", "唱得" }, { "chang de", "唱的" }, { "chang de", "常德" }, { "chang de", "长的" }, { "chang de ge", "唱的歌" },
			{ "chang di", "场地" }, { "chang dian", "长电" }, { "chang du", "长度" }, { "chang duan", "长短" }, { "chang dui", "长队" }, { "chang e", "嫦娥" },
			{ "chang fa", "唱法" }, { "chang fa", "长发" }, { "chang fang", "厂房" }, { "chang fang", "厂方" }, { "chang fang xing", "长方形" }, { "chang feng", "长风" },
			{ "chang ge", "唱歌" }, { "chang gong", "唱功" }, { "chang gong", "长工" }, { "chang guan", "场馆" }, { "chang gui", "常规" }, { "chang gui sai", "常规赛" },
			{ "chang guo", "唱过" }, { "chang guo", "尝过" }, { "chang hao", "常昊" }, { "chang he", "场合" }, { "chang he", "长河" }, { "chang hong", "长虹" },
			{ "chang huan", "偿还" }, { "chang hui", "常会" }, { "chang jia", "厂家" }, { "chang jia", "长假" }, { "chang jia zhi xiao", "厂家直销" },
			{ "chang jian", "常见" }, { "chang jian", "长剑" }, { "chang jian bing", "常见病" }, { "chang jian wen ti", "常见问题" }, { "chang jiang", "长江" },
			{ "chang jiang da qiao", "长江大桥" }, { "chang jiang dian li", "长江电力" }, { "chang jiang liu yu", "长江流域" }, { "chang jiang zheng quan", "长江证券" },
			{ "chang jiao", "长焦" }, { "chang jin", "长今" }, { "chang jing", "场景" }, { "chang jing lu", "长颈鹿" }, { "chang jiu", "长久" }, { "chang ju li", "长距离" },
			{ "chang jue", "猖獗" }, { "chang jun", "场均" }, { "chang kai", "敞开" }, { "chang ke", "常客" }, { "chang kong", "长空" }, { "chang ku", "长裤" },
			{ "chang kuai", "畅快" }, { "chang kuan", "长宽" }, { "chang kuang", "猖狂" }, { "chang lai", "常来" }, { "chang lang", "长廊" }, { "chang le", "长乐" },
			{ "chang le", "长了" }, { "chang li", "厂里" }, { "chang li", "常理" }, { "chang liang", "常量" }, { "chang long", "长龙" }, { "chang mao", "长矛" },
			{ "chang mian", "场面" }, { "chang nei", "场内" }, { "chang nian", "常年" }, { "chang nian", "长年" }, { "chang ning", "长宁" }, { "chang ning qu", "长宁区" },
			{ "chang pai", "厂牌" }, { "chang pao", "长袍" }, { "chang pao", "长跑" }, { "chang pian", "唱片" }, { "chang pian", "长篇" },
			{ "chang pian da lun", "长篇大论" }, { "chang pian gong si", "唱片公司" }, { "chang pian xiao shuo", "长篇小说" }, { "chang ping", "昌平" },
			{ "chang ping qu", "昌平区" }, { "chang qi", "唱起" }, { "chang qi", "长期" }, { "chang qi shi yong", "长期使用" }, { "chang qi tou zi", "长期投资" },
			{ "chang qi xing", "长期性" }, { "chang qi yi lai", "长期以来" }, { "chang qiang", "唱腔" }, { "chang qiang", "长枪" }, { "chang qing", "常青" },
			{ "chang qing", "长青" }, { "chang qu", "厂区" }, { "chang qu", "常去" }, { "chang qun", "长裙" }, { "chang ren", "常人" }, { "chang san jiao", "长三角" },
			{ "chang sha", "长沙" }, { "chang sha shi", "长沙市" }, { "chang shan", "常山" }, { "chang shang", "厂商" }, { "chang shang", "场上" },
			{ "chang sheng", "昌盛" }, { "chang sheng", "长生" }, { "chang shi", "尝试" }, { "chang shi", "常事" }, { "chang shi", "常识" }, { "chang shi jian", "长时间" },
			{ "chang shou", "长寿" }, { "chang shu", "常数" }, { "chang shu", "常熟" }, { "chang shuo", "常说" }, { "chang suo", "场所" },
			{ "chang suo yu yan", "畅所欲言" }, { "chang tai", "常态" }, { "chang tan", "畅谈" }, { "chang tan", "长叹" }, { "chang tian", "长天" },
			{ "chang tiao", "长条" }, { "chang tong", "畅通" }, { "chang tou fa", "长头发" }, { "chang tu", "长途" }, { "chang tu dian hua", "长途电话" },
			{ "chang tui", "长腿" }, { "chang wai", "场外" }, { "chang wan", "唱完" }, { "chang wei", "常委" }, { "chang wei", "肠胃" }, { "chang wei", "长尾" },
			{ "chang wei hui", "常委会" }, { "chang wen", "常温" }, { "chang wu", "常务" }, { "chang wu hui yi", "常务会议" }, { "chang wu li shi", "常务理事" },
			{ "chang xi", "唱戏" }, { "chang xi", "场戏" }, { "chang xian", "长线" }, { "chang xiang", "唱响" }, { "chang xiang", "畅想" }, { "chang xiao", "畅销" },
			{ "chang xiao", "长效" }, { "chang xiao ji zhi", "长效机制" }, { "chang xiao shu", "畅销书" }, { "chang xing", "长兴" }, { "chang xiu", "长袖" },
			{ "chang yan", "肠炎" }, { "chang yang", "徜徉" }, { "chang yang", "长阳" }, { "chang ye", "长夜" } };
};
