package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN57 {
	public static String[][] pl = { { "yi xiang bu dao", "意想不到" }, { "yi xiang qing yuan", "一厢情愿" }, { "yi xiang shu", "意向书" },
			{ "yi xiang tian kai", "异想天开" }, { "yi xiao", "一小" }, { "yi xiao", "一笑" }, { "yi xiao cuo", "一小撮" }, { "yi xie", "一些" },
			{ "yi xie dong xi", "一些东西" }, { "yi xie ren", "一些人" }, { "yi xie shi qing", "一些事情" }, { "yi xie wen ti", "一些问题" }, { "yi xin", "一心" },
			{ "yi xin", "疑心" }, { "yi xin yi yi", "一心一意" }, { "yi xing", "一行" }, { "yi xing", "宜兴" }, { "yi xing", "异形" }, { "yi xing", "异性" },
			{ "yi xing lian", "异性恋" }, { "yi xiu", "一宿" }, { "yi xiu", "衣袖" }, { "yi xue", "医学" }, { "yi xue", "易学" }, { "yi xue jie", "医学界" },
			{ "yi xue yuan", "医学院" }, { "yi xue zhuan jia", "医学专家" }, { "yi ya", "咿呀" }, { "yi yan", "一眼" }, { "yi yan", "一言" }, { "yi yan", "遗言" },
			{ "yi yan bu fa", "一言不发" }, { "yi yan nan jin", "一言难尽" }, { "yi yan yi xing", "一言一行" }, { "yi yang", "一样" }, { "yi yang", "异样" },
			{ "yi yang", "益阳" }, { "yi yang hua tan", "一氧化碳" }, { "yi yang ma", "一样吗" }, { "yi yao", "医药" }, { "yi yao fei", "医药费" },
			{ "yi yao hang ye", "医药行业" }, { "yi ye", "一叶" }, { "yi ye", "一夜" }, { "yi ye", "一页" }, { "yi ye bao fu", "一夜暴富" }, { "yi ye qing", "一夜情" },
			{ "yi ye zhi jian", "一夜之间" }, { "yi yi", "一一" }, { "yi yi", "一亿" }, { "yi yi", "依依" }, { "yi yi", "异议" }, { "yi yi", "意义" }, { "yi yi", "疑议" },
			{ "yi yi bu she", "依依不舍" }, { "yi yi gu xing", "一意孤行" }, { "yi yi zhong", "以一种" }, { "yi yin", "意淫" }, { "yi ying ju quan", "一应俱全" },
			{ "yi yong", "医用" }, { "yi yong", "易用" }, { "yi yong xing", "易用性" }, { "yi you", "一游" }, { "yi you", "亦有" }, { "yi you", "已有" },
			{ "yi you", "已由" }, { "yi you wei jin", "意犹未尽" }, { "yi yu", "一语" }, { "yi yu", "一遇" }, { "yi yu", "一隅" }, { "yi yu", "已与" }, { "yi yu", "已于" },
			{ "yi yu", "异于" }, { "yi yu", "异域" }, { "yi yu", "意欲" }, { "yi yu", "抑郁" }, { "yi yu", "易于" }, { "yi yu", "益于" }, { "yi yu zheng", "抑郁症" },
			{ "yi yuan", "一元" }, { "yi yuan", "一员" }, { "yi yuan", "亿元" }, { "yi yuan", "医院" }, { "yi yuan", "意愿" }, { "yi yuan", "议员" },
			{ "yi yuan jian cha", "医院检查" }, { "yi yuan qian", "一元钱" }, { "yi yuan zhi liao", "医院治疗" }, { "yi yue", "一月" }, { "yi yue", "一跃" },
			{ "yi yue", "已阅" }, { "yi yue fen", "一月份" }, { "yi zai", "一再" }, { "yi zai", "已在" }, { "yi zai", "意在" }, { "yi zai", "移栽" }, { "yi zao", "一早" },
			{ "yi ze", "一则" }, { "yi zhan", "一展" }, { "yi zhan", "一战" }, { "yi zhan", "一盏" }, { "yi zhan", "一站" }, { "yi zhan", "已占" }, { "yi zhan", "驿站" },
			{ "yi zhan shi", "一站式" }, { "yi zhang", "一张" }, { "yi zhang", "一掌" }, { "yi zhang", "一章" }, { "yi zhang", "议长" }, { "yi zhang chuang", "一张床" },
			{ "yi zhang zhang", "一张张" }, { "yi zhang zhao pian", "一张照片" }, { "yi zhang zhi", "一张纸" }, { "yi zhao", "一招" }, { "yi zhao", "一朝" },
			{ "yi zhao", "依照" }, { "yi zhao yi xi", "一朝一夕" }, { "yi zhe", "译者" }, { "yi zhen", "一针" }, { "yi zhen", "一阵" }, { "yi zhen", "一震" },
			{ "yi zhen feng", "一阵风" }, { "yi zhen jian xie", "一针见血" }, { "yi zhen zhen", "一阵阵" }, { "yi zhen zi", "一阵子" }, { "yi zheng", "一怔" },
			{ "yi zheng", "一整" }, { "yi zheng tao", "一整套" }, { "yi zheng tian", "一整天" }, { "yi zhi", "一只" }, { "yi zhi", "一指" }, { "yi zhi", "一支" },
			{ "yi zhi", "一枝" }, { "yi zhi", "一直" }, { "yi zhi", "一纸" }, { "yi zhi", "一职" }, { "yi zhi", "一致" }, { "yi zhi", "以至" }, { "yi zhi", "以致" },
			{ "yi zhi", "医治" }, { "yi zhi", "已知" }, { "yi zhi", "意志" }, { "yi zhi", "抑制" }, { "yi zhi", "益智" }, { "yi zhi", "移植" }, { "yi zhi", "移至" },
			{ "yi zhi", "遗址" }, { "yi zhi ban jie", "一知半解" }, { "yi zhi dou zai", "一直都在" }, { "yi zhi du xiu", "一枝独秀" }, { "yi zhi hua", "一枝花" },
			{ "yi zhi ji", "抑制剂" }, { "yi zhi jiao", "一只脚" }, { "yi zhi li", "意志力" }, { "yi zhi mao", "一只猫" }, { "yi zhi mei you", "一直没有" },
			{ "yi zhi shou", "一只手" }, { "yi zhi xiao", "一只小" }, { "yi zhi xing", "一致性" }, { "yi zhi yan", "一支烟" }, { "yi zhi yi lai", "一直以来" },
			{ "yi zhi yi wei", "一直以为" }, { "yi zhi yu", "以至于" }, { "yi zhong", "一中" }, { "yi zhong", "一种" }, { "yi zhong te shu", "一种特殊" },
			{ "yi zhong tian", "易中天" }, { "yi zhou", "一周" }, { "yi zhou nei", "一周内" }, { "yi zhu", "一株" }, { "yi zhu", "医嘱" }, { "yi zhu", "遗嘱" },
			{ "yi zhuan", "一转" }, { "yi zhuan yan", "一转眼" }, { "yi zhuang", "一幢" }, { "yi zhuang", "一桩" }, { "yi zhuang", "亦庄" }, { "yi zhuo", "一桌" },
			{ "yi zhuo", "衣着" }, { "yi zi", "一字" }, { "yi zi", "椅子" }, { "yi zong", "一宗" }, { "yi zou", "一走" }, { "yi zu", "一族" }, { "yi zu", "一组" },
			{ "yi zu", "异族" }, { "yi zu", "彝族" }, { "yi zun", "一尊" }, { "yi zuo", "一坐" }, { "yi zuo", "一座" }, { "yi zuo zuo", "一座座" }, { "yin", "伒" },
			{ "yin", "傿" }, { "yin", "凐" }, { "yin", "印" }, { "yin", "吟" }, { "yin", "吲" }, { "yin", "喑" }, { "yin", "噾" }, { "yin", "嚚" }, { "yin", "因" },
			{ "yin", "圁" }, { "yin", "垔" }, { "yin", "垠" }, { "yin", "垽" }, { "yin", "堙" }, { "yin", "堷" }, { "yin", "夂" }, { "yin", "夤" }, { "yin", "姻" },
			{ "yin", "婬" }, { "yin", "寅" }, { "yin", "尹" }, { "yin", "崟" }, { "yin", "廕" }, { "yin", "廴" }, { "yin", "引" }, { "yin", "愔" }, { "yin", "慇" },
			{ "yin", "憖" }, { "yin", "朄" }, { "yin", "梀" }, { "yin", "檃" }, { "yin", "檭" }, { "yin", "欭" }, { "yin", "歅" }, { "yin", "殥" }, { "yin", "殷" },
			{ "yin", "氤" }, { "yin", "洇" }, { "yin", "淫" }, { "yin", "湚" }, { "yin", "湮" }, { "yin", "濦" }, { "yin", "烎" }, { "yin", "犾" }, { "yin", "狺" },
			{ "yin", "猌" }, { "yin", "瘖" }, { "yin", "瘾" }, { "yin", "癮" }, { "yin", "硍" }, { "yin", "禋" }, { "yin", "窨" }, { "yin", "粌" }, { "yin", "絪" },
			{ "yin", "胤" }, { "yin", "苂" }, { "yin", "茚" }, { "yin", "茵" }, { "yin", "荫" }, { "yin", "荶" }, { "yin", "蒑" }, { "yin", "蔩" }, { "yin", "蔭" },
			{ "yin", "蘟" }, { "yin", "蚓" }, { "yin", "螾" }, { "yin", "蟫" }, { "yin", "裀" }, { "yin", "訢" }, { "yin", "誾" }, { "yin", "諲" }, { "yin", "讔" },
			{ "yin", "趛" }, { "yin", "輑" }, { "yin", "鄞" }, { "yin", "酓" }, { "yin", "酳" }, { "yin", "釿" }, { "yin", "鈏" }, { "yin", "銀" }, { "yin", "銦" },
			{ "yin", "铟" }, { "yin", "银" }, { "yin", "闉" }, { "yin", "阴" }, { "yin", "陰" }, { "yin", "隐" }, { "yin", "隠" }, { "yin", "隱" }, { "yin", "霒" },
			{ "yin", "霠" }, { "yin", "霪" }, { "yin", "靷" }, { "yin", "音" }, { "yin", "韾" }, { "yin", "飮" }, { "yin", "飲" }, { "yin", "饮" }, { "yin", "駰" },
			{ "yin", "鷣" }, { "yin", "齗" }, { "yin", "齦" }, { "yin", "龈" }, { "yin an", "阴暗" }, { "yin bai se", "银白色" }, { "yin bao", "引爆" },
			{ "yin bi", "银币" }, { "yin bi", "隐蔽" }, { "yin biao", "音标" }, { "yin bing", "因病" }, { "yin bu", "阴部" }, { "yin cang", "隐藏" }, { "yin cha", "饮茶" },
			{ "yin cha yang cuo", "阴差阳错" }, { "yin chang", "吟唱" }, { "yin chen", "阴沉" }, { "yin cheng", "银城" }, { "yin chu", "引出" }, { "yin chuan", "银川" },
			{ "yin chuan shi", "银川市" }, { "yin chun", "阴唇" }, { "yin ci", "因此" }, { "yin dang", "淫荡" }, { "yin dao", "引到" }, { "yin dao", "引导" },
			{ "yin dao", "阴道" }, { "yin dao xue sheng", "引导学生" }, { "yin dao yan", "阴道炎" }, { "yin de", "引得" }, { "yin di", "阴蒂" },
			{ "yin di an ren", "印第安人" }, { "yin di zhi yi", "因地制宜" }, { "yin diao", "音调" }, { "yin du", "印度" }, { "yin du", "引渡" }, { "yin du ren", "印度人" },
			{ "yin du yang", "印度洋" }, { "yin er", "因而" }, { "yin er", "银耳" }, { "yin fa", "印发" }, { "yin fa", "引发" }, { "yin fu", "音符" }, { "yin gong", "因公" },
			{ "yin gu", "因故" }, { "yin gui", "音轨" }, { "yin guo", "因果" }, { "yin guo guan xi", "因果关系" }, { "yin han", "隐含" }, { "yin hang", "银行" },
			{ "yin hang cun kuan", "银行存款" }, { "yin hang dai kuan", "银行贷款" }, { "yin hang gu", "银行股" }, { "yin hang jia", "银行家" }, { "yin hang jian", "银行间" },
			{ "yin hang ka", "银行卡" }, { "yin hang ye", "银行业" }, { "yin hang zhang hu", "银行账户" }, { "yin hao", "引号" }, { "yin he", "银河" },
			{ "yin he xi", "银河系" }, { "yin he zheng quan", "银河证券" }, { "yin hua", "印花" }, { "yin hua", "银华" }, { "yin hua shui", "印花税" }, { "yin huan", "隐患" },
			{ "yin hui", "淫秽" }, { "yin hui", "隐晦" }, { "yin hui se", "银灰色" }, { "yin ji", "印记" }, { "yin jian", "引荐" }, { "yin jian hui", "银监会" },
			{ "yin jiao", "引脚" }, { "yin jie", "音节" }, { "yin jin", "引进" }, { "yin jin wai zi", "引进外资" }, { "yin jing", "阴茎" }, { "yin jiu", "饮酒" },
			{ "yin ju", "隐居" }, { "yin lai", "引来" }, { "yin leng", "阴冷" }, { "yin li", "引力" }, { "yin li", "阴历" }, { "yin lian", "银联" }, { "yin liang", "银两" },
			{ "yin liang", "阴凉" }, { "yin liang", "音量" }, { "yin liao", "饮料" }, { "yin ling", "引领" }, { "yin liu", "引流" }, { "yin luan", "淫乱" },
			{ "yin mai", "阴霾" }, { "yin man", "隐瞒" }, { "yin mao", "阴毛" }, { "yin mi", "隐秘" }, { "yin mou", "阴谋" }, { "yin mu", "银幕" }, { "yin nang", "阴囊" },
			{ "yin ni", "印尼" }, { "yin ni", "隐匿" }, { "yin nin", "因您" }, { "yin pai", "银牌" }, { "yin pin", "音频" }, { "yin pin", "饮品" }, { "yin qi", "因其" },
			{ "yin qi", "引起" }, { "yin qi", "阴气" }, { "yin qie", "殷切" }, { "yin qin", "殷勤" }, { "yin qing", "引擎" }, { "yin qu", "隐去" }, { "yin ran", "印染" },
			{ "yin ren", "隐忍" }, { "yin ren er yi", "因人而异" }, { "yin ren guan zhu", "引人关注" }, { "yin ren ru sheng", "引人入胜" }, { "yin ren zhu mu", "引人注目" },
			{ "yin rou", "阴柔" }, { "yin ru", "引入" }, { "yin se", "银色" }, { "yin se", "音色" }, { "yin sen", "阴森" }, { "yin shang", "因伤" }, { "yin shen", "引申" },
			{ "yin shen", "隐身" }, { "yin shi", "吟诗" }, { "yin shi", "银饰" }, { "yin shi", "隐士" }, { "yin shi", "饮食" }, { "yin shi pin", "音视频" },
			{ "yin shi wen hua", "饮食文化" }, { "yin shi xi guan", "饮食习惯" }, { "yin shu", "引述" }, { "yin shua", "印刷" }, { "yin shua chang", "印刷厂" },
			{ "yin shua pin", "印刷品" }, { "yin shui", "引水" }, { "yin shui", "淫水" }, { "yin shui", "饮水" }, { "yin shui ji", "饮水机" }, { "yin si", "隐私" },
			{ "yin si quan", "隐私权" }, { "yin su", "因素" }, { "yin su", "音速" }, { "yin su fen xi", "因素分析" }, { "yin tai", "银泰" }, { "yin te wang", "因特网" },
			{ "yin tian", "阴天" }, { "yin wei", "因为" }, { "yin wei ai", "因为爱" }, { "yin wei na", "因为那" }, { "yin wen", "引文" }, { "yin xian", "引线" },
			{ "yin xian", "阴线" }, { "yin xian", "阴险" }, { "yin xiang", "印象" }, { "yin xiang", "引向" }, { "yin xiang", "音像" }, { "yin xiang", "音响" },
			{ "yin xiang", "音箱" }, { "yin xiang dian", "音像店" }, { "yin xiang zhi pin", "音像制品" }, { "yin xiao", "音效" }, { "yin xin", "音信" },
			{ "yin xing", "银杏" }, { "yin xing", "阴性" }, { "yin xing", "隐形" }, { "yin xing", "隐性" }, { "yin xing yan jing", "隐形眼镜" }, { "yin xu", "阴虚" },
			{ "yin xun", "音讯" }, { "yin yan", "引言" }, { "yin yang", "阴阳" }, { "yin yi", "音译" }, { "yin yin", "隐隐" }, { "yin yin yue yue", "隐隐约约" },
			{ "yin ying", "阴影" }, { "yin yong", "引用" }, { "yin yong", "饮用" }, { "yin yong shui", "饮用水" }, { "yin yong tong gao", "引用通告" }, { "yin you", "印有" },
			{ "yin you", "引诱" }, { "yin you", "隐忧" }, { "yin yu", "阴郁" }, { "yin yu", "阴雨" }, { "yin yu", "隐喻" }, { "yin yu", "音域" }, { "yin yuan", "因缘" },
			{ "yin yuan", "姻缘" }, { "yin yuan", "音源" }, { "yin yue", "银月" }, { "yin yue", "隐约" }, { "yin yue", "音乐" }, { "yin yue bo fang", "音乐播放" },
			{ "yin yue feng ge", "音乐风格" }, { "yin yue he", "音乐盒" }, { "yin yue hui", "音乐会" }, { "yin yue jia", "音乐家" }, { "yin yue jie", "音乐节" },
			{ "yin yue ju", "音乐剧" }, { "yin yue ren", "音乐人" }, { "yin yue shou ji", "音乐手机" }, { "yin yue ting", "音乐厅" }, { "yin yue xue yuan", "音乐学院" },
			{ "yin yun", "氤氲" }, { "yin zai", "印在" }, { "yin zha ji", "因扎吉" }, { "yin zhang", "印章" }, { "yin zhe", "印着" }, { "yin zheng", "印证" },
			{ "yin zhi", "印制" }, { "yin zhi", "引致" }, { "yin zhi", "音质" }, { "yin zhong", "引种" }, { "yin zi", "因子" }, { "yin zi", "引子" }, { "yin zi", "引自" },
			{ "yin zi", "引资" }, { "yin zi", "银子" }, { "yin zuo", "银座" }, { "ying", "俓" }, { "ying", "偀" }, { "ying", "営" }, { "ying", "嘤" }, { "ying", "嚶" },
			{ "ying", "塋" }, { "ying", "夃" }, { "ying", "婴" }, { "ying", "媵" }, { "ying", "嫈" }, { "ying", "嬰" }, { "ying", "嬴" }, { "ying", "巆" },
			{ "ying", "应" }, { "ying", "廮" }, { "ying", "影" }, { "ying", "応" }, { "ying", "應" }, { "ying", "摬" }, { "ying", "撄" }, { "ying", "攍" },
			{ "ying", "攖" }, { "ying", "旲" }, { "ying", "映" }, { "ying", "暎" }, { "ying", "朠" }, { "ying", "柍" }, { "ying", "桜" }, { "ying", "梬" },
			{ "ying", "楹" }, { "ying", "樱" }, { "ying", "櫻" }, { "ying", "渶" }, { "ying", "滎" }, { "ying", "滢" }, { "ying", "潁" }, { "ying", "潆" },
			{ "ying", "濚" }, { "ying", "濴" }, { "ying", "瀅" }, { "ying", "瀛" }, { "ying", "瀠" }, { "ying", "瀯" }, { "ying", "瀴" }, { "ying", "灐" },
			{ "ying", "煐" }, { "ying", "熒" }, { "ying", "營" }, { "ying", "珱" }, { "ying", "瑛" }, { "ying", "瑩" }, { "ying", "璎" }, { "ying", "瓔" },
			{ "ying", "甇" }, { "ying", "甖" }, { "ying", "瘿" }, { "ying", "癭" }, { "ying", "盈" }, { "ying", "矨" }, { "ying", "硬" }, { "ying", "碤" },
			{ "ying", "礯" }, { "ying", "穎" }, { "ying", "籯" }, { "ying", "縄" }, { "ying", "縈" }, { "ying", "纓" }, { "ying", "缨" }, { "ying", "罂" },
			{ "ying", "罃" }, { "ying", "罌" }, { "ying", "膺" }, { "ying", "英" }, { "ying", "茔" }, { "ying", "荥" }, { "ying", "荧" }, { "ying", "莹" },
			{ "ying", "莺" }, { "ying", "萤" }, { "ying", "营" }, { "ying", "萦" }, { "ying", "蓥" }, { "ying", "藀" }, { "ying", "蘡" }, { "ying", "蛍" },
			{ "ying", "蝇" }, { "ying", "蝧" }, { "ying", "蝿" }, { "ying", "螢" }, { "ying", "蠅" }, { "ying", "蠳" }, { "ying", "褮" }, { "ying", "覮" },
			{ "ying", "謍" }, { "ying", "譻" }, { "ying", "賏" }, { "ying", "贏" }, { "ying", "赢" }, { "ying", "軈" }, { "ying", "迎" }, { "ying", "郢" },
			{ "ying", "鎣" }, { "ying", "霙" }, { "ying", "韹" }, { "ying", "韺" }, { "ying", "頴" }, { "ying", "颍" }, { "ying", "颖" }, { "ying", "鱦" },
			{ "ying", "鴬" }, { "ying", "鶧" }, { "ying", "鶯" }, { "ying", "鷹" }, { "ying", "鸚" }, { "ying", "鹦" }, { "ying", "鹰" }, { "ying an", "应按" },
			{ "ying ao yun", "迎奥运" }, { "ying bang", "英镑" }, { "ying bao kuo", "应包括" }, { "ying bi", "硬币" }, { "ying bian", "应变" },
			{ "ying bian neng li", "应变能力" }, { "ying bin", "迎宾" }, { "ying cai", "英才" }, { "ying cai qu", "应采取" }, { "ying chao", "英超" },
			{ "ying chen", "映衬" }, { "ying cheng", "影城" }, { "ying cheng dan", "应承担" }, { "ying chi", "影驰" }, { "ying chi", "英尺" }, { "ying chou", "应酬" },
			{ "ying chun", "迎春" }, { "ying cong", "应从" }, { "ying cun", "英寸" }, { "ying da", "应答" }, { "ying dang", "应当" }, { "ying dang an zhao", "应当按照" },
			{ "ying de", "应得" }, { "ying de", "赢得" }, { "ying di", "影帝" }, { "ying di", "营地" }, { "ying die", "影碟" }, { "ying du", "硬度" },
			{ "ying dui", "应对" }, { "ying dui cuo shi", "应对措施" }, { "ying duo", "应多" }, { "ying er", "婴儿" }, { "ying fa", "英法" }, { "ying feng", "迎风" },
			{ "ying fu", "应付" }, { "ying fu he", "应符合" }, { "ying gai", "应该" }, { "ying gai ke yi", "应该可以" }, { "ying gai ru he", "应该如何" },
			{ "ying gai yong", "应该用" }, { "ying gai zen me", "应该怎么" }, { "ying gai zen yang", "应该怎样" }, { "ying gai zhu yi", "应该注意" },
			{ "ying gai zuo", "应该做" }, { "ying ge lan", "英格兰" }, { "ying ge lan dui", "英格兰队" }, { "ying gen ju", "应根据" }, { "ying guang", "荧光" },
			{ "ying guo", "英国" }, { "ying guo lun dun", "英国伦敦" }, { "ying guo ren", "英国人" }, { "ying guo shou xiang", "英国首相" },
			{ "ying guo zheng fu", "英国政府" }, { "ying han", "英汉" }, { "ying hang", "英航" }, { "ying hao", "英豪" }, { "ying he", "迎合" }, { "ying hou", "影后" },
			{ "ying hua", "樱花" }, { "ying hua", "硬化" }, { "ying huang", "英皇" }, { "ying hui", "萦回" }, { "ying huo chong", "萤火虫" }, { "ying ji", "应急" },
			{ "ying ji", "应激" }, { "ying ji", "影集" }, { "ying ji jiu yuan", "应急救援" }, { "ying ji yu an", "应急预案" }, { "ying jia", "赢家" }, { "ying jian", "硬件" },
			{ "ying jian pei zhi", "硬件配置" }, { "ying jian she bei", "硬件设备" }, { "ying jian she shi", "硬件设施" }, { "ying jian wei hu", "硬件维护" },
			{ "ying jiang", "应将" }, { "ying jie", "应届" }, { "ying jie", "英杰" }, { "ying jie", "迎接" }, { "ying jie sheng", "应届生" }, { "ying jin", "应尽" },
			{ "ying jiu", "营救" }, { "ying ju bei", "应具备" }, { "ying ju you", "应具有" }, { "ying jun", "英俊" }, { "ying jun", "英军" }, { "ying kao lv", "应考虑" },
			{ "ying kou", "营口" }, { "ying kui", "盈亏" }, { "ying lai", "迎来" }, { "ying lang", "硬朗" }, { "ying li", "应力" }, { "ying li", "盈利" },
			{ "ying li", "英里" }, { "ying li", "营利" }, { "ying li", "赢利" }, { "ying li mo shi", "盈利模式" }, { "ying li neng li", "盈利能力" }, { "ying lou", "影楼" },
			{ "ying lun", "英伦" }, { "ying mei", "英美" }, { "ying mi", "影迷" }, { "ying mian", "迎面" }, { "ying ming", "英明" }, { "ying mu", "荧幕" },
			{ "ying na shui", "应纳税" }, { "ying pan", "硬盘" }, { "ying pan he", "硬盘盒" }, { "ying pan kong jian", "硬盘空间" }, { "ying pian", "影片" },
			{ "ying pin", "应聘" }, { "ying pin zhe", "应聘者" }, { "ying ping", "影评" }, { "ying ping", "荧屏" }, { "ying ping ren", "影评人" }, { "ying qiu", "赢球" },
			{ "ying qu", "赢取" }, { "ying qu", "迎娶" }, { "ying rao", "萦绕" }, { "ying ren er jie", "迎刃而解" }, { "ying ru he", "应如何" },
			{ "ying ru yan lian", "映入眼帘" }, { "ying shang", "硬伤" }, { "ying shang", "迎上" }, { "ying she", "影射" }, { "ying she", "映射" }, { "ying sheng", "应声" },
			{ "ying sheng sheng", "硬生生" }, { "ying shi", "应是" }, { "ying shi", "应试" }, { "ying shi", "影视" }, { "ying shi", "硬是" }, { "ying shi", "英式" },
			{ "ying shi jiao yu", "应试教育" }, { "ying shi ju", "影视剧" }, { "ying shi quan", "影视圈" }, { "ying shi zuo pin", "影视作品" }, { "ying shou", "应收" },
			{ "ying shou", "营收" }, { "ying shou kuan", "应收款" }, { "ying shou zhang kuan", "应收账款" }, { "ying shui", "应税" }, { "ying su", "应诉" },
			{ "ying su", "罂粟" }, { "ying tai", "映泰" }, { "ying tan", "影坛" }, { "ying tao", "樱桃" }, { "ying te er", "英特尔" }, { "ying wei", "应为" },
			{ "ying wen", "英文" }, { "ying wen ban", "英文版" }, { "ying wen ge", "英文歌" }, { "ying wen ming", "英文名" }, { "ying wen ming cheng", "英文名称" },
			{ "ying wen ming zi", "英文名字" }, { "ying wen zi mu", "英文字母" }, { "ying wo", "硬卧" }, { "ying wu", "鹦鹉" }, { "ying xian", "应先" },
			{ "ying xiang", "应向" }, { "ying xiang", "影像" }, { "ying xiang", "影响" }, { "ying xiang", "影象" }, { "ying xiang", "映像" }, { "ying xiang li", "影响力" },
			{ "ying xiang yin su", "影响因素" }, { "ying xiao", "营销" }, { "ying xiao bu", "营销部" }, { "ying xiao ce hua", "营销策划" }, { "ying xiao ce lue", "营销策略" },
			{ "ying xiao huo dong", "营销活动" }, { "ying xiao mo shi", "营销模式" }, { "ying xiao ren yuan", "营销人员" }, { "ying xiao wang luo", "营销网络" },
			{ "ying xin", "迎新" }, { "ying xing", "影星" }, { "ying xing", "硬性" }, { "ying xiong", "英雄" }, { "ying xiong wu di", "英雄无敌" }, { "ying yan", "应验" },
			{ "ying yang", "营养" }, { "ying yang bu liang", "营养不良" }, { "ying yang cheng fen", "营养成分" }, { "ying yang jia zhi", "营养价值" },
			{ "ying yang pin", "营养品" }, { "ying yang shi", "营养师" }, { "ying yang su", "营养素" }, { "ying yang wu zhi", "营养物质" }, { "ying yao", "应邀" },
			{ "ying yao", "硬要" }, { "ying ye", "营业" }, { "ying ye bu", "营业部" }, { "ying ye e", "营业额" }, { "ying ye shou ru", "营业收入" },
			{ "ying ye shui", "营业税" }, { "ying ye ting", "营业厅" }, { "ying ye wang dian", "营业网点" }, { "ying ye yuan", "营业员" }, { "ying ye zhi zhao", "营业执照" },
			{ "ying yi", "应以" }, { "ying yin", "影印" }, { "ying yin", "影音" }, { "ying ying", "盈盈" }, { "ying ying", "莹莹" }, { "ying ying", "莺莺" },
			{ "ying yong", "应用" }, { "ying yong", "英勇" }, { "ying yong ceng", "应用层" }, { "ying yong cheng xu", "应用程序" }, { "ying yong fan wei", "应用范围" },
			{ "ying yong ji shu", "应用技术" }, { "ying yong ling yu", "应用领域" }, { "ying yong qian jing", "应用前景" }, { "ying yong ruan jian", "应用软件" },
			{ "ying yong xi tong", "应用系统" }, { "ying yong yan jiu", "应用研究" }, { "ying you", "应有" }, { "ying you", "应由" }, { "ying you er", "婴幼儿" },
			{ "ying you jin you", "应有尽有" }, { "ying yu", "应与" }, { "ying yu", "应予" }, { "ying yu", "盈余" }, { "ying yu", "英语" }, { "ying yu jiao xue", "英语教学" },
			{ "ying yu ke", "英语课" }, { "ying yu kou yu", "英语口语" }, { "ying yu lao shi", "英语老师" }, { "ying yu shui ping", "英语水平" }, { "ying yu si ji", "英语四级" },
			{ "ying yu xue xi", "英语学习" }, { "ying yu zhuan ye", "英语专业" }, { "ying yuan", "影院" }, { "ying yue", "映月" }, { "ying yun", "营运" },
			{ "ying yun er sheng", "应运而生" }, { "ying zai", "应在" }, { "ying zao", "营造" }, { "ying zhan", "应战" }, { "ying zhan", "影展" }, { "ying zhan", "迎战" },
			{ "ying zhang", "营帐" }, { "ying zhang", "营长" }, { "ying zhao", "映照" }, { "ying zhe", "迎着" }, { "ying zhe tou pi", "硬着头皮" }, { "ying zheng", "应征" },
			{ "ying zhu yi", "应注意" }, { "ying zi", "影子" }, { "ying zi", "英姿" }, { "ying zi", "英子" }, { "ying zuo", "硬座" }, { "yo", "哟" }, { "yo", "唷" },
			{ "yo", "喲" }, { "yong", "佣" }, { "yong", "俑" }, { "yong", "傛" }, { "yong", "傭" }, { "yong", "勇" }, { "yong", "咏" }, { "yong", "喁" },
			{ "yong", "嗈" }, { "yong", "噰" }, { "yong", "埇" }, { "yong", "塎" }, { "yong", "墉" }, { "yong", "壅" }, { "yong", "嫞" }, { "yong", "嵱" },
			{ "yong", "庸" }, { "yong", "廱" }, { "yong", "怺" }, { "yong", "恿" }, { "yong", "悀" }, { "yong", "愑" }, { "yong", "慂" }, { "yong", "慵" },
			{ "yong", "拥" }, { "yong", "揘" }, { "yong", "擁" }, { "yong", "槦" }, { "yong", "永" }, { "yong", "泳" }, { "yong", "涌" }, { "yong", "湧" },
			{ "yong", "滽" }, { "yong", "澭" }, { "yong", "灉" }, { "yong", "用" }, { "yong", "甬" }, { "yong", "痈" }, { "yong", "癰" }, { "yong", "禜" },
			{ "yong", "筩" }, { "yong", "臃" }, { "yong", "蛹" }, { "yong", "詠" }, { "yong", "踊" }, { "yong", "踴" }, { "yong", "邕" }, { "yong", "郺" },
			{ "yong", "鄘" }, { "yong", "醟" }, { "yong", "鏞" }, { "yong", "镛" }, { "yong", "雍" }, { "yong", "雝" }, { "yong", "饔" }, { "yong", "鯒" },
			{ "yong", "鰫" }, { "yong", "鳙" }, { "yong", "鷛" }, { "yong an", "永安" }, { "yong bao", "拥抱" }, { "yong bi", "用笔" }, { "yong bie", "永别" },
			{ "yong bing", "佣兵" }, { "yong bing", "用兵" }, { "yong bu", "永不" }, { "yong bu liao", "用不了" }, { "yong bu wan", "用不完" }, { "yong bu yong", "用不用" },
			{ "yong bu zhao", "用不着" }, { "yong can", "用餐" }, { "yong chang", "用场" }, { "yong che", "用车" }, { "yong chi", "泳池" }, { "yong chu", "涌出" },
			{ "yong chu", "用处" }, { "yong ci", "用此" }, { "yong ci", "用词" }, { "yong cun", "永存" }, { "yong dai", "拥戴" }, { "yong dao", "用刀" },
			{ "yong dao", "用到" }, { "yong de", "用得" }, { "yong de", "用的" }, { "yong de shi", "用的是" }, { "yong de zhao", "用得着" }, { "yong di", "用地" },
			{ "yong dian", "用电" }, { "yong dian nao", "用电脑" }, { "yong diao", "用掉" }, { "yong dong", "涌动" }, { "yong du", "拥堵" }, { "yong duo", "勇夺" },
			{ "yong fa", "用法" }, { "yong fang", "用房" }, { "yong gan", "勇敢" }, { "yong gang", "永刚" }, { "yong gong", "用功" }, { "yong gong", "用工" },
			{ "yong guang", "用光" }, { "yong guo", "用过" }, { "yong hao", "用好" }, { "yong he", "永和" }, { "yong he gong", "雍和宫" }, { "yong heng", "永恒" },
			{ "yong hu", "拥护" }, { "yong hu", "用户" }, { "yong hu jie mian", "用户界面" }, { "yong hu ke yi", "用户可以" }, { "yong hu lie biao", "用户列表" },
			{ "yong hu ming", "用户名" }, { "yong hu qun", "用户群" }, { "yong hu shu", "用户数" }, { "yong hu ti gong", "用户提供" }, { "yong hu ti yan", "用户体验" },
			{ "yong hu xu qiu", "用户需求" }, { "yong hu zu", "用户组" }, { "yong ji", "拥挤" } };
};
