package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN23 {
	public static String[][] pl = { { "jiang chi", "僵持" }, { "jiang chu", "讲出" }, { "jiang ci", "将此" }, { "jiang cong", "将从" }, { "jiang da", "将达" },
			{ "jiang da dao", "将达到" }, { "jiang dao", "讲到" }, { "jiang dao", "降到" }, { "jiang dao li", "讲道理" }, { "jiang de", "讲得" }, { "jiang de", "讲的" },
			{ "jiang de shi", "讲的是" }, { "jiang de zhu", "奖得主" }, { "jiang di", "降低" }, { "jiang di cheng ben", "降低成本" }, { "jiang dong", "江东" },
			{ "jiang dui", "将对" }, { "jiang fu", "降幅" }, { "jiang gai", "将该" }, { "jiang gao", "讲稿" }, { "jiang gei", "将给" }, { "jiang gei", "讲给" },
			{ "jiang gu shi", "讲故事" }, { "jiang guo", "讲过" }, { "jiang hai", "江海" }, { "jiang han", "江汉" }, { "jiang he", "江河" }, { "jiang hu", "江湖" },
			{ "jiang hu", "浆糊" }, { "jiang hua", "僵化" }, { "jiang hua", "讲话" }, { "jiang hua jing shen", "讲话精神" }, { "jiang huai", "江淮" },
			{ "jiang hui", "将会" }, { "jiang ji", "降级" }, { "jiang jia", "讲价" }, { "jiang jia", "降价" }, { "jiang jian", "将建" }, { "jiang jiang", "讲讲" },
			{ "jiang jie", "讲解" }, { "jiang jie", "降解" }, { "jiang jie shi", "蒋介石" }, { "jiang jin", "奖金" }, { "jiang jin", "将近" },
			{ "jiang jing guo", "蒋经国" }, { "jiang jiu", "将就" }, { "jiang jiu", "讲究" }, { "jiang ju", "僵局" }, { "jiang jun", "将军" }, { "jiang ke", "讲课" },
			{ "jiang lai", "将来" }, { "jiang li", "奖励" }, { "jiang li", "讲理" }, { "jiang lin", "降临" }, { "jiang ling", "将领" }, { "jiang ling", "江铃" },
			{ "jiang ling", "江陵" }, { "jiang liu", "江流" }, { "jiang luo", "降落" }, { "jiang luo san", "降落伞" }, { "jiang men", "江门" },
			{ "jiang men shi", "江门市" }, { "jiang mian", "江面" }, { "jiang mian lin", "将面临" }, { "jiang min", "江民" }, { "jiang nan", "江南" },
			{ "jiang nan chun", "江南春" }, { "jiang ning", "江宁" }, { "jiang pai", "奖牌" }, { "jiang pin", "奖品" }, { "jiang qi", "将其" }, { "jiang qi", "讲起" },
			{ "jiang qin qin", "蒋勤勤" }, { "jiang qing", "江青" }, { "jiang qiu", "将球" }, { "jiang qiu", "讲求" }, { "jiang quan", "奖券" }, { "jiang shan", "江山" },
			{ "jiang shang", "奖赏" }, { "jiang shang", "江上" }, { "jiang sheng", "降生" }, { "jiang shi", "僵尸" }, { "jiang shi", "将使" }, { "jiang shi", "将士" },
			{ "jiang shi", "将是" }, { "jiang shi", "讲师" }, { "jiang shou", "将手" }, { "jiang shou", "讲授" }, { "jiang shu", "讲述" }, { "jiang shui", "江水" },
			{ "jiang shui", "降水" }, { "jiang shui liang", "降水量" }, { "jiang su", "江苏" }, { "jiang su sheng", "江苏省" }, { "jiang ta", "将他" },
			{ "jiang ta", "将她" }, { "jiang ta", "将它" }, { "jiang tai", "讲台" }, { "jiang tan", "讲坛" }, { "jiang tang", "讲堂" }, { "jiang wan", "讲完" },
			{ "jiang wei", "将为" }, { "jiang wei", "降为" }, { "jiang wen", "姜文" }, { "jiang wen", "降温" }, { "jiang wen li", "蒋雯丽" }, { "jiang xi", "江西" },
			{ "jiang xi", "降息" }, { "jiang xi sheng", "江西省" }, { "jiang xia", "降下" }, { "jiang xiang", "奖项" }, { "jiang xiang", "将向" }, { "jiang xue", "讲学" },
			{ "jiang xue", "降雪" }, { "jiang xue jin", "奖学金" }, { "jiang ya", "降压" }, { "jiang yan", "讲演" }, { "jiang yao", "将要" }, { "jiang yi", "将以" },
			{ "jiang yi", "讲义" }, { "jiang yin", "江阴" }, { "jiang ying", "僵硬" }, { "jiang you", "将有" }, { "jiang you", "将由" }, { "jiang you", "酱油" },
			{ "jiang yu", "将与" }, { "jiang yu", "将于" }, { "jiang yu", "降雨" }, { "jiang yu liang", "降雨量" }, { "jiang zai", "将在" }, { "jiang zao", "降噪" },
			{ "jiang ze min", "江泽民" }, { "jiang zhang", "奖章" }, { "jiang zhe", "江浙" }, { "jiang zhi", "将之" }, { "jiang zhi", "将至" }, { "jiang zhi", "降至" },
			{ "jiang zhong", "江中" }, { "jiang zhuang", "奖状" }, { "jiang zi", "酱紫" }, { "jiang zuo", "讲座" }, { "jiao", "交" }, { "jiao", "佼" }, { "jiao", "侥" },
			{ "jiao", "僥" }, { "jiao", "僬" }, { "jiao", "儌" }, { "jiao", "剿" }, { "jiao", "劋" }, { "jiao", "勦" }, { "jiao", "叫" }, { "jiao", "嘂" },
			{ "jiao", "嘄" }, { "jiao", "噍" }, { "jiao", "嚼" }, { "jiao", "姣" }, { "jiao", "娇" }, { "jiao", "嬌" }, { "jiao", "嬓" }, { "jiao", "峤" },
			{ "jiao", "嶕" }, { "jiao", "徼" }, { "jiao", "悎" }, { "jiao", "憍" }, { "jiao", "憿" }, { "jiao", "挍" }, { "jiao", "挢" }, { "jiao", "搅" },
			{ "jiao", "摷" }, { "jiao", "撟" }, { "jiao", "撹" }, { "jiao", "攪" }, { "jiao", "敎" }, { "jiao", "教" }, { "jiao", "敫" }, { "jiao", "敿" },
			{ "jiao", "斠" }, { "jiao", "曒" }, { "jiao", "校" }, { "jiao", "椒" }, { "jiao", "樔" }, { "jiao", "浇" }, { "jiao", "湫" }, { "jiao", "滘" },
			{ "jiao", "澆" }, { "jiao", "灚" }, { "jiao", "焦" }, { "jiao", "煍" }, { "jiao", "爝" }, { "jiao", "狡" }, { "jiao", "獥" }, { "jiao", "珓" },
			{ "jiao", "皎" }, { "jiao", "皦" }, { "jiao", "皭" }, { "jiao", "矫" }, { "jiao", "矯" }, { "jiao", "礁" }, { "jiao", "穚" }, { "jiao", "窖" },
			{ "jiao", "笅" }, { "jiao", "筊" }, { "jiao", "簥" }, { "jiao", "絞" }, { "jiao", "繳" }, { "jiao", "纐" }, { "jiao", "绞" }, { "jiao", "缴" },
			{ "jiao", "胶" }, { "jiao", "脚" }, { "jiao", "腳" }, { "jiao", "膠" }, { "jiao", "膲" }, { "jiao", "艽" }, { "jiao", "茭" }, { "jiao", "蕉" },
			{ "jiao", "蛟" }, { "jiao", "蟭" }, { "jiao", "觉" }, { "jiao", "角" }, { "jiao", "譥" }, { "jiao", "趭" }, { "jiao", "跤" }, { "jiao", "較" },
			{ "jiao", "轎" }, { "jiao", "轿" }, { "jiao", "较" }, { "jiao", "郊" }, { "jiao", "酵" }, { "jiao", "醮" }, { "jiao", "釂" }, { "jiao", "鉸" },
			{ "jiao", "鐎" }, { "jiao", "铰" }, { "jiao", "餃" }, { "jiao", "饺" }, { "jiao", "驕" }, { "jiao", "骄" }, { "jiao", "鮫" }, { "jiao", "鱎" },
			{ "jiao", "鲛" }, { "jiao", "鵁" }, { "jiao", "鵤" }, { "jiao", "鷦" }, { "jiao", "鷮" }, { "jiao", "鹪" }, { "jiao an", "教案" }, { "jiao ao", "骄傲" },
			{ "jiao ban", "交办" }, { "jiao ban", "叫板" }, { "jiao ban", "搅拌" }, { "jiao ban ji", "搅拌机" }, { "jiao ben", "脚本" }, { "jiao ben yu yan", "脚本语言" },
			{ "jiao bian", "狡辩" }, { "jiao bian", "脚边" }, { "jiao bu", "胶布" }, { "jiao bu", "脚步" }, { "jiao bu sheng", "脚步声" }, { "jiao cai", "教材" },
			{ "jiao cai", "脚踩" }, { "jiao cha", "交叉" }, { "jiao cha", "较差" }, { "jiao cha kou", "交叉口" }, { "jiao chai", "交差" }, { "jiao chang", "较长" },
			{ "jiao che", "轿车" }, { "jiao che shi chang", "轿车市场" }, { "jiao cheng", "教程" }, { "jiao chu", "交出" }, { "jiao chu lai", "交出来" },
			{ "jiao chuang", "叫床" }, { "jiao cun", "缴存" }, { "jiao cuo", "交错" }, { "jiao da", "交大" }, { "jiao da", "较大" }, { "jiao dai", "交代" },
			{ "jiao dai", "交待" }, { "jiao dai", "胶带" }, { "jiao dao", "交到" }, { "jiao dao", "交道" }, { "jiao dao", "叫到" }, { "jiao dao", "叫道" },
			{ "jiao dao", "教导" }, { "jiao de", "叫得" }, { "jiao di", "脚底" }, { "jiao di", "较低" }, { "jiao dian", "交点" }, { "jiao dian", "焦点" },
			{ "jiao dong", "搅动" }, { "jiao du", "角度" }, { "jiao du kan", "角度看" }, { "jiao duan", "较短" }, { "jiao dui", "校对" }, { "jiao duo", "较多" },
			{ "jiao fa", "叫法" }, { "jiao fa", "教法" }, { "jiao fang", "交房" }, { "jiao fei", "交费" }, { "jiao fei", "缴费" }, { "jiao feng", "交锋" },
			{ "jiao fu", "交付" }, { "jiao fu", "教父" }, { "jiao fu", "教辅" }, { "jiao fu shi yong", "交付使用" }, { "jiao gai", "教改" }, { "jiao gao", "较高" },
			{ "jiao ge", "交个" }, { "jiao ge", "交割" }, { "jiao ge", "叫个" }, { "jiao gei", "交给" }, { "jiao gei", "教给" }, { "jiao gen", "脚跟" },
			{ "jiao gong", "教工" }, { "jiao guan", "交管" }, { "jiao guan", "教官" }, { "jiao guan", "浇灌" }, { "jiao guo", "交过" }, { "jiao guo", "教过" },
			{ "jiao han", "叫喊" }, { "jiao hang", "交行" }, { "jiao hao", "叫好" }, { "jiao hao", "较好" }, { "jiao hao de", "较好的" }, { "jiao hou gen", "脚后跟" },
			{ "jiao hu", "交互" }, { "jiao hu shi", "交互式" }, { "jiao hua", "教化" }, { "jiao hua", "浇花" }, { "jiao hua", "焦化" }, { "jiao hua", "狡猾" },
			{ "jiao huai", "脚踝" }, { "jiao huan", "交换" }, { "jiao huan", "叫唤" }, { "jiao huan ji", "交换机" }, { "jiao huang", "教皇" }, { "jiao hui", "交会" },
			{ "jiao hui", "交汇" }, { "jiao hui", "教会" }, { "jiao hui", "教诲" }, { "jiao hui chu", "交汇处" }, { "jiao huo", "交火" }, { "jiao huo", "交货" },
			{ "jiao huo", "搅和" }, { "jiao huo", "缴获" }, { "jiao huo qi", "交货期" }, { "jiao ji", "交际" }, { "jiao ji", "交集" }, { "jiao ji", "焦急" },
			{ "jiao jia", "脚架" }, { "jiao jian", "矫健" }, { "jiao jian", "脚尖" }, { "jiao jiao", "娇娇" }, { "jiao jiao", "教教" }, { "jiao jiao", "觉觉" },
			{ "jiao jiao zhe", "佼佼者" }, { "jiao jie", "交接" }, { "jiao jie", "交界" }, { "jiao jie", "皎洁" }, { "jiao jie chu", "交界处" }, { "jiao jin", "较劲" },
			{ "jiao jin", "较近" }, { "jiao jin nao zhi", "绞尽脑汁" }, { "jiao jing", "交警" }, { "jiao jing da dui", "交警大队" }, { "jiao jing zhi dui", "交警支队" },
			{ "jiao ju", "焦距" }, { "jiao juan", "胶卷" }, { "jiao ke shu", "教科书" }, { "jiao kuai", "较快" }, { "jiao kuan", "交款" }, { "jiao kuan", "缴款" },
			{ "jiao le", "叫了" }, { "jiao lian", "教练" }, { "jiao lian yuan", "教练员" }, { "jiao lian zu", "教练组" }, { "jiao liang", "较量" }, { "jiao liu", "交流" },
			{ "jiao liu hui", "交流会" }, { "jiao liu huo dong", "交流活动" }, { "jiao liu ping tai", "交流平台" }, { "jiao long", "蛟龙" }, { "jiao luo", "角落" },
			{ "jiao luo li", "角落里" }, { "jiao lv", "焦虑" }, { "jiao mai", "叫卖" }, { "jiao man", "较慢" }, { "jiao mei", "娇媚" }, { "jiao mo", "角膜" },
			{ "jiao mu", "酵母" }, { "jiao na", "交纳" }, { "jiao na", "缴纳" }, { "jiao nan", "较难" }, { "jiao nang", "胶囊" }, { "jiao nen", "娇嫩" },
			{ "jiao ni", "教你" }, { "jiao pai", "教派" }, { "jiao pei", "交配" }, { "jiao peng you", "交朋友" }, { "jiao pian", "胶片" }, { "jiao qi", "娇妻" },
			{ "jiao qi", "娇气" }, { "jiao qi", "脚气" }, { "jiao qian", "交钱" }, { "jiao qiang", "较强" }, { "jiao qing", "交情" }, { "jiao qing", "矫情" },
			{ "jiao qing", "较轻" }, { "jiao qiu", "角球" }, { "jiao qu", "郊区" }, { "jiao rang", "叫嚷" }, { "jiao ren", "叫人" }, { "jiao ren", "教人" },
			{ "jiao ren", "骄人" }, { "jiao rong", "交融" }, { "jiao ruo", "较弱" }, { "jiao se", "角色" }, { "jiao sha", "叫啥" }, { "jiao shang", "交上" },
			{ "jiao shang", "叫上" }, { "jiao shang", "脚上" }, { "jiao shao", "较少" }, { "jiao she", "交涉" }, { "jiao shen", "较深" }, { "jiao shen me", "叫什么" },
			{ "jiao sheng", "叫声" }, { "jiao shi", "教室" }, { "jiao shi", "教师" }, { "jiao shi", "礁石" }, { "jiao shi dui wu", "教师队伍" }, { "jiao shi jie", "教师节" },
			{ "jiao shi li", "教室里" }, { "jiao shou", "交手" }, { "jiao shou", "教授" }, { "jiao shou jia", "脚手架" }, { "jiao shu", "教书" }, { "jiao shui", "交税" },
			{ "jiao shui", "浇水" }, { "jiao shui", "缴税" }, { "jiao shui", "胶水" }, { "jiao suo", "教唆" }, { "jiao ta", "教他" }, { "jiao ta", "脚踏" },
			{ "jiao ta shi di", "脚踏实地" }, { "jiao tan", "交谈" }, { "jiao tan", "焦炭" }, { "jiao tang", "教堂" }, { "jiao ti", "交替" }, { "jiao ti", "脚踢" },
			{ "jiao tiao", "教条" }, { "jiao ting", "叫停" }, { "jiao tong", "交通" }, { "jiao tong an quan", "交通安全" }, { "jiao tong bian li", "交通便利" },
			{ "jiao tong bu", "交通部" }, { "jiao tong bu men", "交通部门" }, { "jiao tong fei", "交通费" }, { "jiao tong gong ju", "交通工具" },
			{ "jiao tong guan li", "交通管理" }, { "jiao tong guan zhi", "交通管制" }, { "jiao tong ju", "交通局" }, { "jiao tong shi gu", "交通事故" },
			{ "jiao tong shu niu", "交通枢纽" }, { "jiao tong ting", "交通厅" }, { "jiao tong yin hang", "交通银行" }, { "jiao tong yun shu", "交通运输" },
			{ "jiao tou", "交投" }, { "jiao tou lan e", "焦头烂额" }, { "jiao tu", "教徒" }, { "jiao wai", "郊外" }, { "jiao wan", "较晚" }, { "jiao wang", "交往" },
			{ "jiao wei", "教委" }, { "jiao wei", "较为" }, { "jiao wo", "叫我" }, { "jiao wo", "教我" }, { "jiao wu", "教务" }, { "jiao wu chu", "教务处" },
			{ "jiao xia", "脚下" }, { "jiao xiang", "交响" }, { "jiao xiang qu", "交响曲" }, { "jiao xiang yue", "交响乐" }, { "jiao xiang yue tuan", "交响乐团" },
			{ "jiao xiao", "叫嚣" }, { "jiao xiao", "娇小" }, { "jiao xiao", "较小" }, { "jiao xin", "交心" }, { "jiao xing", "侥幸" }, { "jiao xing", "叫醒" },
			{ "jiao xiu", "娇羞" }, { "jiao xue", "教学" }, { "jiao xue fa", "教学法" }, { "jiao xue fang fa", "教学方法" }, { "jiao xue fei", "交学费" },
			{ "jiao xue gai ge", "教学改革" }, { "jiao xue gong zuo", "教学工作" }, { "jiao xue guo cheng", "教学过程" }, { "jiao xue huo dong", "教学活动" },
			{ "jiao xue ji hua", "教学计划" }, { "jiao xue lou", "教学楼" }, { "jiao xue mo shi", "教学模式" }, { "jiao xue mu biao", "教学目标" },
			{ "jiao xue nei rong", "教学内容" }, { "jiao xue she ji", "教学设计" }, { "jiao xue zhi liang", "教学质量" }, { "jiao xun", "教训" }, { "jiao ya", "脚丫" },
			{ "jiao yan", "娇艳" }, { "jiao yan", "教研" }, { "jiao yan", "校验" }, { "jiao yan shi", "教研室" }, { "jiao yang", "教养" }, { "jiao yang", "骄阳" },
			{ "jiao yi", "交易" }, { "jiao yi", "交椅" }, { "jiao yi", "教义" }, { "jiao yi", "较易" }, { "jiao yi cheng ben", "交易成本" }, { "jiao yi e", "交易额" },
			{ "jiao yi fang shi", "交易方式" }, { "jiao yi jia ge", "交易价格" }, { "jiao yi liang", "交易量" }, { "jiao yi ping tai", "交易平台" }, { "jiao yi ri", "交易日" },
			{ "jiao yi shang", "交易商" }, { "jiao yi sheng", "叫一声" }, { "jiao yi shi chang", "交易市场" }, { "jiao yi suo", "交易所" }, { "jiao yi xi tong", "交易系统" },
			{ "jiao yi yuan", "交易员" }, { "jiao yi zhe", "交易者" }, { "jiao yi zhong xin", "交易中心" }, { "jiao yin", "脚印" }, { "jiao you", "交友" },
			{ "jiao you", "交由" }, { "jiao you", "郊游" }, { "jiao yu", "教育" }, { "jiao yu bu", "教育部" }, { "jiao yu bu men", "教育部门" },
			{ "jiao yu fa zhan", "教育发展" }, { "jiao yu gai ge", "教育改革" }, { "jiao yu gong zuo", "教育工作" }, { "jiao yu hai zi", "教育孩子" },
			{ "jiao yu huo dong", "教育活动" }, { "jiao yu ji gou", "教育机构" }, { "jiao yu jia", "教育家" }, { "jiao yu jiao xue", "教育教学" }, { "jiao yu jie", "教育界" },
			{ "jiao yu jing fei", "教育经费" }, { "jiao yu ju", "教育局" }, { "jiao yu li nian", "教育理念" }, { "jiao yu pei xun", "教育培训" },
			{ "jiao yu shi ye", "教育事业" }, { "jiao yu si xiang", "教育思想" }, { "jiao yu ti xi", "教育体系" }, { "jiao yu ti zhi", "教育体制" }, { "jiao yu ting", "教育厅" },
			{ "jiao yu wang", "教育网" }, { "jiao yu xi tong", "教育系统" }, { "jiao yu xue", "教育学" }, { "jiao yu xue yuan", "教育学院" }, { "jiao yu zhe", "教育者" },
			{ "jiao yu zhi du", "教育制度" }, { "jiao yu zhi liang", "教育质量" }, { "jiao yu zi yuan", "教育资源" }, { "jiao yuan", "教员" }, { "jiao yuan", "胶原" },
			{ "jiao yuan", "较远" }, { "jiao yuan dan bai", "胶原蛋白" }, { "jiao zao", "焦躁" }, { "jiao zao", "较早" }, { "jiao zha", "狡诈" }, { "jiao zhan", "交战" },
			{ "jiao zhang", "脚掌" }, { "jiao zhe", "叫着" }, { "jiao zhen", "较真" }, { "jiao zheng", "校正" }, { "jiao zheng", "矫正" }, { "jiao zhi", "交织" },
			{ "jiao zhi", "胶质" }, { "jiao zhi", "脚趾" }, { "jiao zhi", "角质" }, { "jiao zhi", "较之" }, { "jiao zhi ceng", "角质层" }, { "jiao zhi gong", "教职工" },
			{ "jiao zhi tou", "脚趾头" }, { "jiao zhong", "较重" }, { "jiao zhu", "叫住" }, { "jiao zhu", "教主" }, { "jiao zhu", "浇筑" }, { "jiao zhun", "校准" },
			{ "jiao zi", "轿子" }, { "jiao zi", "饺子" }, { "jiao zuo", "叫作" }, { "jiao zuo", "叫做" }, { "jiao zuo", "焦作" }, { "jie", "介" }, { "jie", "价" },
			{ "jie", "借" }, { "jie", "倢" }, { "jie", "偈" }, { "jie", "傑" }, { "jie", "刧" }, { "jie", "劫" }, { "jie", "劼" }, { "jie", "卩" }, { "jie", "唶" },
			{ "jie", "喈" }, { "jie", "嗟" }, { "jie", "堺" }, { "jie", "妎" }, { "jie", "姐" }, { "jie", "婕" }, { "jie", "媎" }, { "jie", "孑" }, { "jie", "家" },
			{ "jie", "尐" }, { "jie", "屆" }, { "jie", "届" }, { "jie", "岊" }, { "jie", "岕" }, { "jie", "崨" }, { "jie", "嵥" }, { "jie", "巀" }, { "jie", "幯" },
			{ "jie", "戒" }, { "jie", "截" }, { "jie", "拮" }, { "jie", "捷" }, { "jie", "接" }, { "jie", "掲" }, { "jie", "揭" }, { "jie", "昅" }, { "jie", "曁" },
			{ "jie", "杰" }, { "jie", "桀" }, { "jie", "桔" }, { "jie", "桝" }, { "jie", "楬" }, { "jie", "楶" }, { "jie", "楷" }, { "jie", "榤" }, { "jie", "檞" },
			{ "jie", "洁" }, { "jie", "湝" }, { "jie", "滐" }, { "jie", "潔" }, { "jie", "犗" }, { "jie", "狤" }, { "jie", "玠" }, { "jie", "界" }, { "jie", "畍" },
			{ "jie", "疖" }, { "jie", "疥" }, { "jie", "痎" }, { "jie", "癤" }, { "jie", "皆" }, { "jie", "睫" }, { "jie", "砎" }, { "jie", "碣" }, { "jie", "秸" },
			{ "jie", "竭" }, { "jie", "節" }, { "jie", "紒" }, { "jie", "結" }, { "jie", "结" }, { "jie", "羯" }, { "jie", "耤" }, { "jie", "节" }, { "jie", "芥" },
			{ "jie", "藉" }, { "jie", "蚧" }, { "jie", "蛶" }, { "jie", "蝍" }, { "jie", "蝔" }, { "jie", "蠽" }, { "jie", "街" }, { "jie", "衱" }, { "jie", "袺" },
			{ "jie", "褯" }, { "jie", "解" }, { "jie", "訐" }, { "jie", "詰" }, { "jie", "誡" }, { "jie", "讦" }, { "jie", "诘" }, { "jie", "诫" }, { "jie", "趌" },
			{ "jie", "跲" }, { "jie", "踕" }, { "jie", "迼" }, { "jie", "鉣" }, { "jie", "鍻" }, { "jie", "阂" }, { "jie", "阶" }, { "jie", "階" }, { "jie", "鞂" },
			{ "jie", "鞊" }, { "jie", "頡" }, { "jie", "颉" }, { "jie", "骱" }, { "jie", "鲒" }, { "jie", "鶛" }, { "jie ai", "节哀" }, { "jie an", "结案" },
			{ "jie ba", "结巴" }, { "jie bai", "洁白" }, { "jie bai", "结拜" }, { "jie ban", "接班" }, { "jie ban", "结伴" }, { "jie ban ren", "接班人" },
			{ "jie bei", "戒备" }, { "jie bian", "街边" }, { "jie bie", "界别" }, { "jie bing", "结冰" }, { "jie ceng", "阶层" }, { "jie chang", "结肠" },
			{ "jie cheng", "竭诚" }, { "jie cheng", "结成" }, { "jie chi", "劫持" }, { "jie chu", "接触" }, { "jie chu", "杰出" }, { "jie chu", "结出" },
			{ "jie chu", "解除" }, { "jie chu bu liang", "接触不良" }, { "jie chu he tong", "解除合同" }, { "jie chuan", "揭穿" }, { "jie ci", "借此" },
			{ "jie ci ji hui", "借此机会" }, { "jie da", "捷达" }, { "jie da", "解答" }, { "jie da huan xi", "皆大欢喜" }, { "jie dai", "借贷" }, { "jie dai", "接待" },
			{ "jie dan", "接单" }, { "jie dao", "借到" }, { "jie dao", "接到" }, { "jie dao", "街道" }, { "jie di", "姐弟" }, { "jie di", "接地" },
			{ "jie di lian", "姐弟恋" }, { "jie dian", "结点" }, { "jie dian", "节点" }, { "jie dian", "节电" }, { "jie dian hua", "接电话" }, { "jie diao", "戒掉" },
			{ "jie ding", "界定" }, { "jie dong", "解冻" }, { "jie du", "戒毒" }, { "jie du", "解毒" }, { "jie du", "解读" }, { "jie duan", "截断" }, { "jie duan", "阶段" },
			{ "jie duan xing", "阶段性" }, { "jie dui", "结对" }, { "jie er lian san", "接二连三" }, { "jie fa", "揭发" }, { "jie fa", "解法" }, { "jie fang", "街坊" },
			{ "jie fang", "解放" }, { "jie fang bei", "解放碑" }, { "jie fang hou", "解放后" }, { "jie fang jun", "解放军" }, { "jie fang lu", "解放路" },
			{ "jie fang qian", "解放前" }, { "jie fang si xiang", "解放思想" }, { "jie fang zhan zheng", "解放战争" }, { "jie fei", "劫匪" }, { "jie feng", "解封" },
			{ "jie fu", "姐夫" }, { "jie fu", "杰夫" }, { "jie gan", "秸秆" }, { "jie ge", "借个" }, { "jie gei", "借给" }, { "jie gou", "结构" }, { "jie gou", "解构" },
			{ "jie gou hua", "结构化" }, { "jie gou she ji", "结构设计" }, { "jie gou tiao zheng", "结构调整" }, { "jie gou tu", "结构图" }, { "jie gou xing", "结构性" },
			{ "jie gu", "解雇" }, { "jie guan", "接管" }, { "jie gui", "接轨" }, { "jie guo", "接过" }, { "jie guo", "结果" }, { "jie guo biao ming", "结果表明" },
			{ "jie guo xian shi", "结果显示" }, { "jie he", "结合" }, { "jie he", "结核" }, { "jie he bing", "结核病" }, { "jie he qi lai", "结合起来" },
			{ "jie he shi ji", "结合实际" }, { "jie hou", "节后" }, { "jie hui", "接回" }, { "jie hui", "结汇" }, { "jie hun", "结婚" }, { "jie hun hou", "结婚后" },
			{ "jie hun qian", "结婚前" }, { "jie hun zhao", "结婚照" }, { "jie hun zheng", "结婚证" }, { "jie huo", "截获" }, { "jie huo", "解惑" }, { "jie ji", "借机" },
			{ "jie ji", "接机" }, { "jie ji", "街机" }, { "jie ji", "阶级" }, { "jie ji dou zheng", "阶级斗争" }, { "jie ji ka", "借记卡" }, { "jie jia ri", "节假日" },
			{ "jie jian", "借鉴" }, { "jie jian", "接见" }, { "jie jian", "节俭" }, { "jie jiao", "结交" }, { "jie jiao", "街角" }, { "jie jie", "姐姐" },
			{ "jie jie", "结界" }, { "jie jie", "结节" }, { "jie jie", "节节" }, { "jie jin", "接近" }, { "jie jin", "解禁" }, { "jie jin quan li", "竭尽全力" },
			{ "jie jing", "捷径" }, { "jie jing", "洁净" }, { "jie jing", "结晶" }, { "jie jiu", "戒酒" }, { "jie jiu", "解救" }, { "jie ju", "拮据" }, { "jie ju", "洁具" },
			{ "jie ju", "结局" }, { "jie jue", "解决" }, { "jie jue ban fa", "解决办法" }, { "jie jue fang an", "解决方案" }, { "jie jue fang fa", "解决方法" },
			{ "jie jue hao", "解决好" }, { "jie jue wen ti", "解决问题" }, { "jie kai", "揭开" }, { "jie kai", "解开" }, { "jie ke", "借壳" }, { "jie ke", "捷克" },
			{ "jie ke", "接客" }, { "jie ke", "杰克" }, { "jie ke", "皆可" }, { "jie ke", "节课" }, { "jie ke", "解渴" }, { "jie ke shang shi", "借壳上市" },
			{ "jie ke xun", "杰克逊" }, { "jie kou", "借口" }, { "jie kou", "接口" }, { "jie kuan", "借款" }, { "jie kuan ren", "借款人" }, { "jie la de", "杰拉德" },
			{ "jie lai", "借来" }, { "jie le", "借了" }, { "jie le hun", "结了婚" }, { "jie li", "借力" }, { "jie li", "接力" }, { "jie li", "竭力" }, { "jie lian", "接连" },
			{ "jie liu", "截留" }, { "jie long", "接龙" }, { "jie lu", "揭露" }, { "jie lun", "杰伦" }, { "jie lun", "结论" }, { "jie lv", "戒律" }, { "jie ma", "解码" },
			{ "jie ma qi", "解码器" }, { "jie man", "届满" }, { "jie mao", "睫毛" }, { "jie mao gao", "睫毛膏" }, { "jie mei", "姐妹" }, { "jie men", "姐们" },
			{ "jie men", "解闷" }, { "jie meng", "结盟" }, { "jie mi", "揭密" }, { "jie mi", "揭秘" }, { "jie mi", "解密" }, { "jie mian", "截面" }, { "jie mian", "洁面" },
			{ "jie mian", "界面" }, { "jie mo", "芥末" }, { "jie mu", "揭幕" }, { "jie mu", "节目" }, { "jie mu zu", "节目组" }, { "jie na", "接纳" }, { "jie nan", "劫难" },
			{ "jie neng", "节能" }, { "jie neng deng", "节能灯" }, { "jie neng huan bao", "节能环保" }, { "jie neng jiang hao", "节能降耗" }, { "jie pai", "接拍" },
			{ "jie pai", "揭牌" }, { "jie pai", "节拍" }, { "jie pan", "接盘" }, { "jie pi", "洁癖" }, { "jie pin", "解聘" }, { "jie ping", "截屏" }, { "jie pou", "解剖" },
			{ "jie qi", "节气" }, { "jie qia", "接洽" }, { "jie qian", "借钱" }, { "jie qian", "节前" }, { "jie qing", "结清" }, { "jie qing", "节庆" },
			{ "jie qiu", "接球" }, { "jie qu", "截取" }, { "jie qu", "街区" }, { "jie ran", "截然" }, { "jie ran bu tong", "截然不同" }, { "jie rang", "接壤" },
			{ "jie ren", "接任" }, { "jie ren da", "届人大" }, { "jie ri", "节日" }, { "jie ri kuai le", "节日快乐" }, { "jie ri qi jian", "节日期间" }, { "jie ru", "介入" },
			{ "jie ru", "接入" }, { "jie ru dian", "接入点" }, { "jie san", "解散" }, { "jie shang", "接上" }, { "jie shang", "街上" }, { "jie shao", "介绍" },
			{ "jie shao xin", "介绍信" }, { "jie shao yi xia", "介绍一下" }, { "jie sheng", "节省" }, { "jie shi", "届时" }, { "jie shi", "揭示" }, { "jie shi", "皆是" },
			{ "jie shi", "结实" }, { "jie shi", "结石" }, { "jie shi", "结识" }, { "jie shi", "节食" }, { "jie shi", "街市" }, { "jie shi", "解释" }, { "jie shou", "接受" },
			{ "jie shou", "接手" }, { "jie shou", "接收" }, { "jie shou cai fang", "接受采访" }, { "jie shou ji", "接收机" }, { "jie shou qi", "接收器" },
			{ "jie shu", "借书" }, { "jie shu", "结束" }, { "jie shui", "节水" }, { "jie shuo", "解说" }, { "jie shuo yuan", "解说员" }, { "jie song", "接送" },
			{ "jie su", "借宿" }, { "jie suan", "结算" }, { "jie suo", "解锁" }, { "jie tao", "解套" }, { "jie ti", "接替" }, { "jie ti", "解体" }, { "jie ti", "解题" },
			{ "jie ti", "阶梯" }, { "jie tiao", "借条" }, { "jie ting", "接听" }, { "jie tong", "接通" }, { "jie tou", "接头" }, { "jie tou", "街头" },
			{ "jie tou lan qiu", "街头篮球" }, { "jie tu", "截图" }, { "jie tuo", "解脱" }, { "jie wei", "皆为" }, { "jie wei", "结为" }, { "jie wei", "结尾" },
			{ "jie wei", "解围" }, { "jie wen", "接吻" }, { "jie wu", "街舞" }, { "jie xi", "解析" }, { "jie xia", "接下" }, { "jie xia", "结下" },
			{ "jie xia lai", "接下来" }, { "jie xia qu", "接下去" }, { "jie xian", "接线" }, { "jie xian", "界线" }, { "jie xian", "界限" }, { "jie xiang", "街巷" },
			{ "jie xiao", "揭晓" }, { "jie xin", "戒心" }, { "jie xu", "接续" }, { "jie xuan", "节选" }, { "jie ya", "解压" }, { "jie ya suo", "解压缩" },
			{ "jie yan", "戒严" }, { "jie yan", "戒烟" }, { "jie yang", "揭阳" }, { "jie yao", "解药" }, { "jie ye", "结业" }, { "jie yi", "介意" }, { "jie yi", "借以" },
			{ "jie yin", "皆因" }, { "jie ying", "接应" }, { "jie yong", "借用" }, { "jie you", "皆有" }, { "jie you", "节油" }, { "jie yu", "介于" }, { "jie yu", "结余" },
			{ "jie yuan", "结缘" }, { "jie yue", "借阅" }, { "jie yue", "节约" }, { "jie yue", "解约" } };
};
