package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN24 {
	public static String[][] pl = { { "jie yue neng yuan", "节约能源" }, { "jie zha", "结扎" }, { "jie zhang", "结帐" }, { "jie zhang", "结账" }, { "jie zhe", "借着" },
			{ "jie zhe", "接着" }, { "jie zhi", "介质" }, { "jie zhi", "戒指" }, { "jie zhi", "截止" }, { "jie zhi", "截至" }, { "jie zhi", "皆知" }, { "jie zhi", "节制" },
			{ "jie zhi ri qi", "截止日期" }, { "jie zhi shi jian", "截止时间" }, { "jie zhong", "接种" }, { "jie zhong er lai", "接踵而来" }, { "jie zhong er zhi", "接踵而至" },
			{ "jie zhu", "借助" }, { "jie zhu", "接住" }, { "jie zhuan", "结转" }, { "jie zou", "节奏" }, { "jie zou gan", "节奏感" }, { "jie zuo", "杰作" },
			{ "jin", "仅" }, { "jin", "今" }, { "jin", "侭" }, { "jin", "僅" }, { "jin", "僸" }, { "jin", "儘" }, { "jin", "劲" }, { "jin", "勁" }, { "jin", "卺" },
			{ "jin", "噤" }, { "jin", "嚍" }, { "jin", "堇" }, { "jin", "堻" }, { "jin", "壗" }, { "jin", "妗" }, { "jin", "嬧" }, { "jin", "寖" }, { "jin", "尽" },
			{ "jin", "巹" }, { "jin", "巾" }, { "jin", "廑" }, { "jin", "惍" }, { "jin", "搢" }, { "jin", "斤" }, { "jin", "晉" }, { "jin", "晋" }, { "jin", "枃" },
			{ "jin", "榗" }, { "jin", "槿" }, { "jin", "殣" }, { "jin", "津" }, { "jin", "浸" }, { "jin", "溍" }, { "jin", "濜" }, { "jin", "烬" }, { "jin", "煡" },
			{ "jin", "燼" }, { "jin", "珒" }, { "jin", "瑨" }, { "jin", "瑾" }, { "jin", "璡" }, { "jin", "璶" }, { "jin", "盡" }, { "jin", "矜" }, { "jin", "祲" },
			{ "jin", "禁" }, { "jin", "笒" }, { "jin", "筋" }, { "jin", "紟" }, { "jin", "紧" }, { "jin", "緊" }, { "jin", "縉" }, { "jin", "缙" }, { "jin", "荩" },
			{ "jin", "菫" }, { "jin", "蓳" }, { "jin", "藎" }, { "jin", "衿" }, { "jin", "襟" }, { "jin", "覲" }, { "jin", "觐" }, { "jin", "觔" }, { "jin", "謹" },
			{ "jin", "谨" }, { "jin", "賮" }, { "jin", "贐" }, { "jin", "赆" }, { "jin", "近" }, { "jin", "进" }, { "jin", "進" }, { "jin", "金" }, { "jin", "錦" },
			{ "jin", "锦" }, { "jin", "靳" }, { "jin", "饉" }, { "jin", "馑" }, { "jin ai", "紧挨" }, { "jin bai", "近百" }, { "jin ban", "近半" }, { "jin bao", "劲爆" },
			{ "jin bao", "金宝" }, { "jin bei", "金杯" }, { "jin beng", "紧绷" }, { "jin bi", "紧闭" }, { "jin bi", "金币" }, { "jin bi hui huang", "金碧辉煌" },
			{ "jin bian", "金边" }, { "jin biao sai", "锦标赛" }, { "jin bu", "进步" }, { "jin bu", "进补" }, { "jin bu liao", "进不了" }, { "jin bu qu", "进不去" },
			{ "jin bu zhu", "禁不住" }, { "jin can", "进餐" }, { "jin cha", "金叉" }, { "jin chang", "进厂" }, { "jin chang", "进场" }, { "jin chen", "今晨" },
			{ "jin cheng", "进城" }, { "jin cheng", "进程" }, { "jin cheng", "金城" }, { "jin cheng wu", "金城武" }, { "jin cheng wu gong", "进城务工" },
			{ "jin chi", "矜持" }, { "jin chu", "近处" }, { "jin chu", "进出" }, { "jin chu kou", "进出口" }, { "jin ci", "仅此" }, { "jin ci", "今次" },
			{ "jin ci er yi", "仅此而已" }, { "jin ci yu", "仅次于" }, { "jin cou", "紧凑" }, { "jin cou xing", "紧凑型" }, { "jin cun", "仅存" }, { "jin cun", "进村" },
			{ "jin dai", "近代" }, { "jin dai biao", "仅代表" }, { "jin dao", "尽到" }, { "jin dao", "进到" }, { "jin de", "金德" }, { "jin di", "金地" },
			{ "jin die", "金蝶" }, { "jin ding", "紧盯" }, { "jin dong", "今冬" }, { "jin du", "禁毒" }, { "jin du", "进度" }, { "jin du tiao", "进度条" },
			{ "jin e", "金额" }, { "jin er", "今儿" }, { "jin er", "劲儿" }, { "jin er", "进而" }, { "jin fa", "进发" }, { "jin fa", "金发" }, { "jin fang", "谨防" },
			{ "jin gang", "金刚" }, { "jin gang shi", "金刚石" }, { "jin gen", "紧跟" }, { "jin gong", "仅供" }, { "jin gong", "进宫" }, { "jin gong", "进攻" },
			{ "jin gong can kao", "仅供参考" }, { "jin gu", "禁锢" }, { "jin gu", "筋骨" }, { "jin guan", "尽管" }, { "jin guan ru ci", "尽管如此" }, { "jin guang", "金光" },
			{ "jin guo", "巾帼" }, { "jin guo", "进过" }, { "jin hai", "近海" }, { "jin hai", "金海" }, { "jin hou", "今后" }, { "jin hu", "近乎" }, { "jin hua", "进化" },
			{ "jin hua", "金华" }, { "jin hua", "金花" }, { "jin hua lun", "进化论" }, { "jin hua shi", "金华市" }, { "jin huang", "金黄" }, { "jin huang se", "金黄色" },
			{ "jin huo", "进货" }, { "jin ji", "晋级" }, { "jin ji", "禁忌" }, { "jin ji", "紧急" }, { "jin ji", "金鸡" }, { "jin ji nian", "近几年" },
			{ "jin ji nian lai", "近几年来" }, { "jin ji qing kuang", "紧急情况" }, { "jin ji tong zhi", "紧急通知" }, { "jin jia", "进价" }, { "jin jia", "金价" },
			{ "jin jiang", "晋江" }, { "jin jiang", "金奖" }, { "jin jiang", "锦江" }, { "jin jiao", "近郊" }, { "jin jie", "进阶" }, { "jin jie zhe", "紧接着" },
			{ "jin jin", "仅仅" }, { "jin jin", "紧紧" }, { "jin jin chu chu", "进进出出" }, { "jin jin ji jiao", "斤斤计较" }, { "jin jin le dao", "津津乐道" },
			{ "jin jin wei rao", "紧紧围绕" }, { "jin jin you wei", "津津有味" }, { "jin jin zhua zhu", "紧紧抓住" }, { "jin jing", "进京" }, { "jin ju li", "近距离" },
			{ "jin jun", "进军" }, { "jin ka", "金卡" }, { "jin kao", "仅靠" }, { "jin kao", "紧靠" }, { "jin ke neng", "尽可能" }, { "jin kou", "紧扣" },
			{ "jin kou", "进口" }, { "jin kou che", "进口车" }, { "jin kou guo", "进口国" }, { "jin kou liang", "进口量" }, { "jin kou shang", "进口商" },
			{ "jin ku", "金库" }, { "jin kuai", "尽快" }, { "jin kuang", "近况" }, { "jin kuang", "金矿" }, { "jin lai", "近来" }, { "jin lai", "进来" },
			{ "jin lai kan kan", "进来看看" }, { "jin le", "尽了" }, { "jin le", "近了" }, { "jin li", "尽力" }, { "jin li", "金利" }, { "jin lian", "金莲" },
			{ "jin liang", "尽量" }, { "jin liang", "近两" }, { "jin liang bi mian", "尽量避免" }, { "jin liang nian", "近两年" }, { "jin lin", "紧邻" },
			{ "jin ling", "禁令" }, { "jin ling", "金陵" }, { "jin long", "金龙" }, { "jin luo mi gu", "紧锣密鼓" }, { "jin ma", "金马" }, { "jin ma jiang", "金马奖" },
			{ "jin mao", "金毛" }, { "jin mao", "金茂" }, { "jin men", "进门" }, { "jin men", "金门" }, { "jin mi", "紧密" }, { "jin mi jie he", "紧密结合" },
			{ "jin mi lian xi", "紧密联系" }, { "jin ming", "今明" }, { "jin nang", "锦囊" }, { "jin neng", "仅能" }, { "jin nian", "今年" }, { "jin nian", "近年" },
			{ "jin nian chu", "今年初" }, { "jin nian chun jie", "今年春节" }, { "jin nian lai", "近年来" }, { "jin nian xia tian", "今年夏天" },
			{ "jin nian yi lai", "今年以来" }, { "jin niu", "金牛" }, { "jin niu zuo", "金牛座" }, { "jin pai", "金牌" }, { "jin pao", "浸泡" }, { "jin peng", "金鹏" },
			{ "jin pi li jin", "筋疲力尽" }, { "jin ping", "仅凭" }, { "jin ping mei", "金瓶梅" }, { "jin po", "紧迫" }, { "jin po gan", "紧迫感" },
			{ "jin po xing", "紧迫性" }, { "jin qi", "今起" }, { "jin qi", "近期" }, { "jin qi", "进气" }, { "jin qian", "近千" }, { "jin qian", "金钱" },
			{ "jin qiao", "紧俏" }, { "jin qiao", "金桥" }, { "jin qin", "近亲" }, { "jin qing", "尽情" }, { "jin qiu", "进球" }, { "jin qiu", "金秋" },
			{ "jin qiu jiang", "金球奖" }, { "jin qu", "禁区" }, { "jin qu", "进去" }, { "jin qu", "进取" }, { "jin qu", "金曲" }, { "jin qu jiang", "金曲奖" },
			{ "jin que", "紧缺" }, { "jin ran", "尽然" }, { "jin ren", "今人" }, { "jin ri", "今日" }, { "jin ri", "近日" }, { "jin ri cheng", "金日成" },
			{ "jin rong", "金融" }, { "jin rong chan pin", "金融产品" }, { "jin rong chuang xin", "金融创新" }, { "jin rong feng bao", "金融风暴" },
			{ "jin rong feng xian", "金融风险" }, { "jin rong fu wu", "金融服务" }, { "jin rong gai ge", "金融改革" }, { "jin rong gu", "金融股" },
			{ "jin rong hang ye", "金融行业" }, { "jin rong ji gou", "金融机构" }, { "jin rong jian guan", "金融监管" }, { "jin rong jie", "金融界" },
			{ "jin rong jie", "金融街" }, { "jin rong qi ye", "金融企业" }, { "jin rong shi chang", "金融市场" }, { "jin rong ti xi", "金融体系" },
			{ "jin rong wei ji", "金融危机" }, { "jin rong xi tong", "金融系统" }, { "jin rong xue", "金融学" }, { "jin rong ye", "金融业" },
			{ "jin rong zhong xin", "金融中心" }, { "jin rong zi chan", "金融资产" }, { "jin ru", "浸入" }, { "jin ru", "进入" }, { "jin ru ren yi", "尽如人意" },
			{ "jin ru shi chang", "进入市场" }, { "jin ru xi tong", "进入系统" }, { "jin ru you xi", "进入游戏" }, { "jin ru zhong guo", "进入中国" }, { "jin run", "浸润" },
			{ "jin sai", "禁赛" }, { "jin san", "近三" }, { "jin san nian", "近三年" }, { "jin se", "金色" }, { "jin sha", "金沙" }, { "jin sha", "金莎" },
			{ "jin sha jiang", "金沙江" }, { "jin shan", "进山" }, { "jin shan", "金山" }, { "jin shan ci ba", "金山词霸" }, { "jin shan du ba", "金山毒霸" },
			{ "jin shan jin mei", "尽善尽美" }, { "jin shang", "晋商" }, { "jin shang tian hua", "锦上添花" }, { "jin shen", "紧身" }, { "jin shen", "谨慎" },
			{ "jin shen", "近身" }, { "jin sheng", "仅剩" }, { "jin sheng", "今生" }, { "jin sheng", "晋升" }, { "jin shi", "仅是" }, { "jin shi", "今世" },
			{ "jin shi", "尽是" }, { "jin shi", "浸湿" }, { "jin shi", "近十" }, { "jin shi", "近视" }, { "jin shi", "进士" }, { "jin shi", "进食" }, { "jin shi", "金石" },
			{ "jin shi dun", "金士顿" }, { "jin shi nian", "近十年" }, { "jin shi yan", "近视眼" }, { "jin shou", "仅售" }, { "jin shou yan di", "尽收眼底" },
			{ "jin shou zhi", "金手指" }, { "jin shu", "金属" }, { "jin shu cai liao", "金属材料" }, { "jin shui", "进水" }, { "jin si", "近似" }, { "jin si", "金丝" },
			{ "jin song", "劲松" }, { "jin sui", "紧随" }, { "jin suo", "紧缩" }, { "jin suo", "紧锁" }, { "jin tai", "金泰" }, { "jin tan", "金坛" },
			{ "jin ti gong", "仅提供" }, { "jin tian", "今天" }, { "jin tiao", "金条" }, { "jin tie", "津贴" }, { "jin tie", "紧贴" }, { "jin tou", "劲头" },
			{ "jin tou", "尽头" }, { "jin tou", "浸透" }, { "jin tui", "进退" }, { "jin wan", "今晚" }, { "jin wei", "仅为" }, { "jin wo", "紧握" }, { "jin wu", "劲舞" },
			{ "jin wu", "进屋" }, { "jin wu tuan", "劲舞团" }, { "jin xi shan", "金喜善" }, { "jin xia", "今夏" }, { "jin xian", "仅限" }, { "jin xian", "尽显" },
			{ "jin xian dai", "近现代" }, { "jin xian yu", "仅限于" }, { "jin xiang", "尽享" }, { "jin xiang jiang", "金像奖" }, { "jin xiao cun", "进销存" },
			{ "jin xie nian", "近些年" }, { "jin xin", "尽心" }, { "jin xin", "金鑫" }, { "jin xin jin li", "尽心尽力" }, { "jin xing", "尽兴" }, { "jin xing", "进行" },
			{ "jin xing", "金星" }, { "jin xing bi jiao", "进行比较" }, { "jin xing dao di", "进行到底" }, { "jin xing diao cha", "进行调查" },
			{ "jin xing fen xi", "进行分析" }, { "jin xing jian cha", "进行检查" }, { "jin xing jiao liu", "进行交流" }, { "jin xing jiao yi", "进行交易" },
			{ "jin xing qu", "进行曲" }, { "jin xing quan mian", "进行全面" }, { "jin xing tiao zheng", "进行调整" }, { "jin xing xiu gai", "进行修改" },
			{ "jin xing yan jiu", "进行研究" }, { "jin xiu", "进修" }, { "jin xiu", "锦绣" }, { "jin xu", "仅需" }, { "jin yan", "禁烟" }, { "jin yan", "禁言" },
			{ "jin yao", "紧要" }, { "jin ye", "今夜" }, { "jin yi", "仅以" }, { "jin yi bu", "进一步" }, { "jin yi nian", "近一年" }, { "jin yin", "金银" },
			{ "jin yin hua", "金银花" }, { "jin ying", "金鹰" }, { "jin yong", "仅用" }, { "jin yong", "禁用" }, { "jin yong", "金庸" }, { "jin you", "仅有" },
			{ "jin you de", "仅有的" }, { "jin yu", "金玉" }, { "jin yu", "金鱼" }, { "jin yuan", "金源" }, { "jin zai", "仅在" }, { "jin zai", "尽在" },
			{ "jin zai zhi chi", "近在咫尺" }, { "jin zang", "进藏" }, { "jin zao", "今早" }, { "jin zao", "尽早" }, { "jin ze", "尽责" }, { "jin zhan", "仅占" },
			{ "jin zhan", "近战" }, { "jin zhan", "进展" }, { "jin zhan", "进站" }, { "jin zhan qing kuang", "进展情况" }, { "jin zhan shun li", "进展顺利" },
			{ "jin zhang", "紧张" }, { "jin zhang", "进账" }, { "jin zhao", "今朝" }, { "jin zhao", "近照" }, { "jin zheng ri", "金正日" }, { "jin zhi", "尽职" },
			{ "jin zhi", "禁止" }, { "jin zhi", "紧致" }, { "jin zhi", "进制" }, { "jin zhi jin ze", "尽职尽责" }, { "jin zhi shi yong", "禁止使用" },
			{ "jin zhi xia zai", "禁止下载" }, { "jin zhong", "金钟" }, { "jin zhou", "锦州" }, { "jin zhu", "进驻" }, { "jin zi", "金子" }, { "jin zi ta", "金字塔" },
			{ "jin zuo", "仅作" }, { "jing", "丼" }, { "jing", "井" }, { "jing", "京" }, { "jing", "亰" }, { "jing", "倞" }, { "jing", "儆" }, { "jing", "兢" },
			{ "jing", "净" }, { "jing", "凈" }, { "jing", "刭" }, { "jing", "剄" }, { "jing", "劤" }, { "jing", "劲" }, { "jing", "境" }, { "jing", "婛" },
			{ "jing", "婧" }, { "jing", "幜" }, { "jing", "弪" }, { "jing", "弳" }, { "jing", "径" }, { "jing", "徑" }, { "jing", "惊" }, { "jing", "憬" },
			{ "jing", "憼" }, { "jing", "敬" }, { "jing", "旌" }, { "jing", "旍" }, { "jing", "景" }, { "jing", "晶" }, { "jing", "暻" }, { "jing", "桱" },
			{ "jing", "橸" }, { "jing", "殑" }, { "jing", "汫" }, { "jing", "泾" }, { "jing", "浄" }, { "jing", "涇" }, { "jing", "淨" }, { "jing", "瀞" },
			{ "jing", "獍" }, { "jing", "獷" }, { "jing", "璟" }, { "jing", "璥" }, { "jing", "痉" }, { "jing", "痙" }, { "jing", "睛" }, { "jing", "穽" },
			{ "jing", "竞" }, { "jing", "竟" }, { "jing", "竫" }, { "jing", "競" }, { "jing", "竸" }, { "jing", "粳" }, { "jing", "精" }, { "jing", "経" },
			{ "jing", "經" }, { "jing", "经" }, { "jing", "肼" }, { "jing", "胫" }, { "jing", "腈" }, { "jing", "茎" }, { "jing", "荆" }, { "jing", "荊" },
			{ "jing", "莖" }, { "jing", "菁" }, { "jing", "蟼" }, { "jing", "警" }, { "jing", "迳" }, { "jing", "逕" }, { "jing", "鏡" }, { "jing", "镜" },
			{ "jing", "阱" }, { "jing", "靓" }, { "jing", "靖" }, { "jing", "静" }, { "jing", "靜" }, { "jing", "頚" }, { "jing", "頸" }, { "jing", "颈" },
			{ "jing", "驚" }, { "jing", "鯨" }, { "jing", "鲸" }, { "jing", "鵛" }, { "jing", "鶁" }, { "jing", "鶄" }, { "jing", "麠" }, { "jing", "鼱" },
			{ "jing ai", "敬爱" }, { "jing an", "静安" }, { "jing an qu", "静安区" }, { "jing an si", "静安寺" }, { "jing ban", "经办" }, { "jing ban ren", "经办人" },
			{ "jing bao", "劲爆" }, { "jing bao", "惊爆" }, { "jing bao", "警报" }, { "jing bei", "竟被" }, { "jing biao", "竞标" }, { "jing bing", "精兵" },
			{ "jing bu", "颈部" }, { "jing bu qi", "经不起" }, { "jing bu zhu", "经不住" }, { "jing cai", "竞猜" }, { "jing cai", "精彩" }, { "jing cai", "精采" },
			{ "jing cai fen cheng", "精彩纷呈" }, { "jing cai shun jian", "精彩瞬间" }, { "jing cha", "惊诧" }, { "jing cha", "警察" }, { "jing cha ju", "警察局" },
			{ "jing chang", "经常" }, { "jing chang chu xian", "经常出现" }, { "jing chang xing", "经常性" }, { "jing che", "警车" }, { "jing cheng", "京城" },
			{ "jing cheng", "精诚" }, { "jing cui", "精粹" }, { "jing da xi suan", "精打细算" }, { "jing dai", "惊呆" }, { "jing de qi", "经得起" },
			{ "jing de zhen", "景德镇" }, { "jing di", "境地" }, { "jing dian", "景点" }, { "jing dian", "经典" }, { "jing dian", "静电" },
			{ "jing dian zhi zuo", "经典之作" }, { "jing dong", "京东" }, { "jing dong", "惊动" }, { "jing dong fang", "京东方" }, { "jing du", "京都" },
			{ "jing du", "精度" }, { "jing du", "精读" }, { "jing e", "净额" }, { "jing e", "惊愕" }, { "jing er yuan zhi", "敬而远之" }, { "jing fang", "警方" },
			{ "jing fei", "经费" }, { "jing fu", "警服" }, { "jing gai", "井盖" }, { "jing gan", "竟敢" }, { "jing gan", "精干" }, { "jing gang shan", "井冈山" },
			{ "jing gao", "警告" }, { "jing gong", "精工" }, { "jing gou", "竞购" }, { "jing guan", "景观" }, { "jing guan", "经管" }, { "jing guan", "警官" },
			{ "jing guan she ji", "景观设计" }, { "jing guang", "精光" }, { "jing guo", "经过" }, { "jing guo shen she", "靖国神社" }, { "jing hu", "京沪" },
			{ "jing hu", "惊呼" }, { "jing hua", "京华" }, { "jing hua", "净化" }, { "jing hua", "精华" }, { "jing hua qu", "精华区" }, { "jing huang", "惊慌" },
			{ "jing huang shi cuo", "惊慌失措" }, { "jing hui", "竟会" }, { "jing hun", "惊魂" }, { "jing ji", "竞技" }, { "jing ji", "经济" }, { "jing ji", "经纪" },
			{ "jing ji", "荆棘" }, { "jing ji bu chang", "经济补偿" }, { "jing ji chang", "竞技场" }, { "jing ji fa", "经济法" }, { "jing ji fa zhan", "经济发展" },
			{ "jing ji gai ge", "经济改革" }, { "jing ji gong si", "经纪公司" }, { "jing ji gong zuo", "经济工作" }, { "jing ji gu", "荆棘谷" },
			{ "jing ji guan li", "经济管理" }, { "jing ji guo re", "经济过热" }, { "jing ji he zuo", "经济合作" }, { "jing ji huan jing", "经济环境" },
			{ "jing ji huo dong", "经济活动" }, { "jing ji ji chu", "经济基础" }, { "jing ji jia zhi", "经济价值" }, { "jing ji jian she", "经济建设" },
			{ "jing ji jie gou", "经济结构" }, { "jing ji kun nan", "经济困难" }, { "jing ji li yi", "经济利益" }, { "jing ji mao yi", "经济贸易" },
			{ "jing ji pu cha", "经济普查" }, { "jing ji qu", "经济区" }, { "jing ji quan", "经济圈" }, { "jing ji ren", "经纪人" }, { "jing ji she hui", "经济社会" },
			{ "jing ji sheng huo", "经济生活" }, { "jing ji shi", "经济师" }, { "jing ji shi li", "经济实力" }, { "jing ji shu ju", "经济数据" },
			{ "jing ji shuai tui", "经济衰退" }, { "jing ji sun shi", "经济损失" }, { "jing ji te qu", "经济特区" }, { "jing ji ti", "经济体" }, { "jing ji ti yu", "竞技体育" },
			{ "jing ji ti zhi", "经济体制" }, { "jing ji wei ji", "经济危机" }, { "jing ji wen ti", "经济问题" }, { "jing ji xiao yi", "经济效益" }, { "jing ji xing", "经济型" },
			{ "jing ji xing", "经济性" }, { "jing ji xing shi", "经济形势" }, { "jing ji xue", "经济学" }, { "jing ji xue jia", "经济学家" }, { "jing ji xue yuan", "经济学院" },
			{ "jing ji yun xing", "经济运行" }, { "jing ji zeng zhang", "经济增长" }, { "jing ji zheng ce", "经济政策" }, { "jing ji zhi biao", "经济指标" },
			{ "jing ji zhi du", "经济制度" }, { "jing ji zhi xu", "经济秩序" }, { "jing ji zhuang kuang", "经济状况" }, { "jing ji zong liang", "经济总量" },
			{ "jing ji zu zhi", "经济组织" }, { "jing ji zuo wu", "经济作物" }, { "jing jia", "竞价" }, { "jing jia pai ming", "竞价排名" }, { "jing jian", "精简" },
			{ "jing jian ban", "精简版" }, { "jing jiang", "靖江" }, { "jing jiao", "京郊" }, { "jing jiao", "惊叫" }, { "jing jie", "境界" }, { "jing jie", "警戒" },
			{ "jing jie xian", "警戒线" }, { "jing jin", "京津" }, { "jing jin", "精进" }, { "jing jing", "晶晶" }, { "jing jing", "菁菁" }, { "jing jing", "静静" },
			{ "jing jing de", "静静的" }, { "jing jing ye ye", "兢兢业业" }, { "jing jing you tiao", "井井有条" }, { "jing jiu", "敬酒" }, { "jing ju", "京剧" },
			{ "jing ju", "警局" }, { "jing jue", "警觉" }, { "jing kong", "惊恐" }, { "jing kou", "井口" }, { "jing kuang", "境况" }, { "jing lao yuan", "敬老院" },
			{ "jing li", "敬礼" }, { "jing li", "精力" }, { "jing li", "经历" }, { "jing li", "经理" }, { "jing li", "警力" }, { "jing li chong pei", "精力充沛" },
			{ "jing li ren", "经理人" }, { "jing li run", "净利润" }, { "jing lian", "精炼" }, { "jing liang", "精良" }, { "jing ling", "精灵" }, { "jing luan", "痉挛" },
			{ "jing luo", "经络" }, { "jing lv", "劲旅" }, { "jing mai", "竞买" }, { "jing mai", "经脉" }, { "jing mai", "静脉" }, { "jing mao", "经贸" },
			{ "jing mao guan xi", "经贸关系" }, { "jing mao he zuo", "经贸合作" }, { "jing mao wei", "经贸委" }, { "jing mei", "精美" }, { "jing men", "荆门" },
			{ "jing mi", "粳米" }, { "jing mi", "精密" }, { "jing mi", "静谧" }, { "jing mian", "镜面" }, { "jing miao", "精妙" }, { "jing ming", "精明" },
			{ "jing mo", "静默" }, { "jing nei", "境内" }, { "jing nei wai", "境内外" }, { "jing neng", "竟能" }, { "jing pai", "竞拍" }, { "jing pei", "敬佩" },
			{ "jing pen", "井喷" }, { "jing pi", "精辟" }, { "jing pian", "晶片" }, { "jing pian", "镜片" }, { "jing pin", "竞聘" }, { "jing pin", "精品" },
			{ "jing qi", "惊奇" }, { "jing qi", "景气" }, { "jing qi", "经期" }, { "jing qiao", "精巧" }, { "jing qiao qiao", "静悄悄" }, { "jing qing", "敬请" },
			{ "jing qu", "景区" }, { "jing que", "精确" }, { "jing que du", "精确度" }, { "jing ran", "竟然" }, { "jing ren", "惊人" }, { "jing rui", "精锐" },
			{ "jing sai", "竞赛" }, { "jing se", "景色" }, { "jing shang", "井上" }, { "jing shang", "经商" }, { "jing shen", "景深" }, { "jing shen", "精深" },
			{ "jing shen", "精神" }, { "jing shen bing", "精神病" }, { "jing shen bing ren", "精神病人" }, { "jing shen bing yuan", "精神病院" },
			{ "jing shen mian mao", "精神面貌" }, { "jing shen sheng huo", "精神生活" }, { "jing shen shi jie", "精神世界" }, { "jing shen shi zhi", "精神实质" },
			{ "jing shen wen hua", "精神文化" }, { "jing shen wen ming", "精神文明" }, { "jing shen zhuang tai", "精神状态" }, { "jing sheng", "经省" },
			{ "jing shi", "京师" }, { "jing shi", "竟是" }, { "jing shi", "警示" }, { "jing shi hai su", "惊世骇俗" }, { "jing shou", "经受" }, { "jing shu", "经书" },
			{ "jing shui", "井水" }, { "jing shui", "净水" }, { "jing song", "惊悚" }, { "jing su", "竞速" }, { "jing suan", "精算" }, { "jing sui", "精髓" },
			{ "jing tai", "静态" }, { "jing tan", "惊叹" }, { "jing ti", "晶体" }, { "jing ti", "警惕" }, { "jing ti guan", "晶体管" }, { "jing tian", "惊天" },
			{ "jing tian dong di", "惊天动地" }, { "jing ting", "静听" }, { "jing tong", "精通" }, { "jing tou", "镜头" }, { "jing tu", "净土" }, { "jing wai", "境外" },
			{ "jing wai tou zi", "境外投资" }, { "jing wei", "敬畏" }, { "jing wei", "经委" }, { "jing wei", "经纬" }, { "jing wei", "警卫" }, { "jing wen", "经文" },
			{ "jing wu", "景物" }, { "jing wu", "警务" }, { "jing xi", "惊喜" }, { "jing xi", "精细" }, { "jing xi hua", "精细化" }, { "jing xi hua gong", "精细化工" },
			{ "jing xia", "井下" }, { "jing xia", "惊吓" }, { "jing xian", "惊现" }, { "jing xian", "惊险" }, { "jing xiang", "景象" }, { "jing xiang", "竞相" },
			{ "jing xiang", "镜像" }, { "jing xiao", "经销" }, { "jing xiao shang", "经销商" }, { "jing xin", "精心" }, { "jing xin", "静心" },
			{ "jing xin dong po", "惊心动魄" }, { "jing xin she ji", "精心设计" }, { "jing xin zu zhi", "精心组织" }, { "jing xing", "惊醒" }, { "jing xing", "警醒" },
			{ "jing xuan", "竞选" }, { "jing xuan", "精选" }, { "jing ya", "惊讶" }, { "jing yan", "惊艳" }, { "jing yan", "经验" }, { "jing yan feng fu", "经验丰富" },
			{ "jing yan jiao liu", "经验交流" }, { "jing yan jiao xun", "经验教训" }, { "jing yan zhe", "经验者" }, { "jing yan zhi", "经验值" }, { "jing yang", "敬仰" },
			{ "jing yang", "景仰" }, { "jing ye", "敬业" }, { "jing ye", "竟也" }, { "jing ye", "精液" }, { "jing ye jing shen", "敬业精神" }, { "jing yi", "惊异" },
			{ "jing yi", "敬意" }, { "jing yi qiu jing", "精益求精" }, { "jing yin", "静音" }, { "jing ying", "晶莹" }, { "jing ying", "精英" }, { "jing ying", "经营" },
			{ "jing ying bu", "经营部" }, { "jing ying dan wei", "经营单位" }, { "jing ying fan wei", "经营范围" }, { "jing ying fang shi", "经营方式" },
			{ "jing ying guan li", "经营管理" }, { "jing ying hu", "经营户" }, { "jing ying huo dong", "经营活动" }, { "jing ying li nian", "经营理念" },
			{ "jing ying mo shi", "经营模式" }, { "jing ying qi ye", "经营企业" }, { "jing ying qing kuang", "经营情况" }, { "jing ying quan", "经营权" },
			{ "jing ying ti tou", "晶莹剔透" }, { "jing ying xing", "经营性" }, { "jing ying xing wei", "经营行为" }, { "jing ying ye ji", "经营业绩" },
			{ "jing ying zhe", "经营者" }, { "jing ying zhuang kuang", "经营状况" }, { "jing yong", "警用" }, { "jing you", "竟有" }, { "jing you", "精油" },
			{ "jing you", "经由" }, { "jing yu", "境遇" }, { "jing yu", "精于" }, { "jing yu", "鲸鱼" }, { "jing yuan", "警员" }, { "jing zhan", "精湛" },
			{ "jing zhang", "警长" }, { "jing zheng", "竞争" }, { "jing zheng dui shou", "竞争对手" }, { "jing zheng ge ju", "竞争格局" },
			{ "jing zheng huan jing", "竞争环境" }, { "jing zheng ji lie", "竞争激烈" }, { "jing zheng li", "竞争力" }, { "jing zheng neng li", "竞争能力" },
			{ "jing zheng xing", "竞争性" }, { "jing zheng you shi", "竞争优势" }, { "jing zheng zhe", "竞争者" }, { "jing zhi", "净值" }, { "jing zhi", "径直" },
			{ "jing zhi", "景致" }, { "jing zhi", "精制" }, { "jing zhi", "精致" }, { "jing zhi", "静止" }, { "jing zhong", "敬重" }, { "jing zhong", "警钟" },
			{ "jing zhong", "镜中" }, { "jing zhou", "荆州" }, { "jing zhuang", "精装" }, { "jing zhuang xiu", "精装修" }, { "jing zhui", "颈椎" },
			{ "jing zhui bing", "颈椎病" }, { "jing zhun", "精准" }, { "jing zi", "精子" }, { "jing zi", "镜子" }, { "jing zi chan", "净资产" }, { "jing zi li", "镜子里" },
			{ "jing zuo", "静坐" }, { "jiong", "冂" }, { "jiong", "冏" }, { "jiong", "囧" }, { "jiong", "坰" }, { "jiong", "扃" }, { "jiong", "昋" }, { "jiong", "泂" },
			{ "jiong", "浻" }, { "jiong", "炅" }, { "jiong", "炯" }, { "jiong", "烱" }, { "jiong", "煚" }, { "jiong", "熲" }, { "jiong", "燛" }, { "jiong", "窘" },
			{ "jiong", "絅" }, { "jiong", "臦" }, { "jiong", "臩" }, { "jiong", "褧" }, { "jiong", "迥" }, { "jiong", "逈" }, { "jiong", "駉" },
			{ "jiong jing", "窘境" }, { "jiong po", "窘迫" }, { "jiong yi", "迥异" }, { "jiu", "久" }, { "jiu", "九" }, { "jiu", "僦" }, { "jiu", "勼" }, { "jiu", "厩" },
			{ "jiu", "咎" }, { "jiu", "啾" }, { "jiu", "就" }, { "jiu", "廄" }, { "jiu", "廏" }, { "jiu", "廐" }, { "jiu", "慦" }, { "jiu", "揪" }, { "jiu", "揫" },
			{ "jiu", "救" }, { "jiu", "旧" }, { "jiu", "朻" }, { "jiu", "杦" }, { "jiu", "柩" }, { "jiu", "柾" }, { "jiu", "桕" }, { "jiu", "殧" }, { "jiu", "氿" },
			{ "jiu", "灸" }, { "jiu", "玖" }, { "jiu", "疚" }, { "jiu", "究" }, { "jiu", "糺" }, { "jiu", "糾" }, { "jiu", "纠" }, { "jiu", "臼" }, { "jiu", "舅" },
			{ "jiu", "舊" }, { "jiu", "萛" }, { "jiu", "赳" }, { "jiu", "酒" }, { "jiu", "阄" }, { "jiu", "韭" }, { "jiu", "韮" }, { "jiu", "鬏" }, { "jiu", "鬮" },
			{ "jiu", "鯦" }, { "jiu", "鳩" }, { "jiu", "鷲" }, { "jiu", "鸠" }, { "jiu", "鹫" }, { "jiu", "麔" }, { "jiu ai", "就爱" }, { "jiu ai", "旧爱" },
			{ "jiu an", "就按" }, { "jiu ba", "就把" }, { "jiu ba", "酒吧" }, { "jiu ba li", "酒吧里" }, { "jiu bai", "九百" }, { "jiu ban", "旧版" }, { "jiu bei", "就被" },
			{ "jiu bei", "酒杯" }, { "jiu bie", "就别" }, { "jiu bu", "就不" } };
};
