package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN19 {
	public static String[][] pl = { { "hen kuai le", "很快乐" }, { "hen kun", "很困" }, { "hen lan", "很懒" }, { "hen lan", "很烂" }, { "hen lao", "很老" },
			{ "hen lei", "很累" }, { "hen leng", "很冷" }, { "hen li hai", "很厉害" }, { "hen man", "很慢" }, { "hen man yi", "很满意" }, { "hen mang", "很忙" },
			{ "hen mei", "很美" }, { "hen men", "很闷" }, { "hen ming xian", "很明显" }, { "hen nan", "很难" }, { "hen nan shuo", "很难说" }, { "hen nong", "很浓" },
			{ "hen pa", "很怕" }, { "hen pang", "很胖" }, { "hen piao liang", "很漂亮" }, { "hen qi guai", "很奇怪" }, { "hen qiang", "很强" }, { "hen qing", "很轻" },
			{ "hen qing chu", "很清楚" }, { "hen re", "很热" }, { "hen rong yi", "很容易" }, { "hen ruo", "很弱" }, { "hen sha", "很傻" }, { "hen shao", "很少" },
			{ "hen shen", "很深" }, { "hen sheng qi", "很生气" }, { "hen shi", "很是" }, { "hen shou", "很受" }, { "hen shou", "很瘦" }, { "hen shu", "很熟" },
			{ "hen shu fu", "很舒服" }, { "hen shuai", "很帅" }, { "hen shuang", "很爽" }, { "hen si", "恨死" }, { "hen teng", "很疼" }, { "hen tian", "很甜" },
			{ "hen tong", "很痛" }, { "hen tong ku", "很痛苦" }, { "hen wan", "很晚" }, { "hen wo", "恨我" }, { "hen wu liao", "很无聊" }, { "hen xi", "很细" },
			{ "hen xi huan", "很喜欢" }, { "hen xiang", "很像" }, { "hen xiang", "很想" }, { "hen xiang", "很象" }, { "hen xiang", "很香" }, { "hen xiang ni", "很想你" },
			{ "hen xiao", "很小" }, { "hen xin", "狠心" }, { "hen xin ku", "很辛苦" }, { "hen xing fu", "很幸福" }, { "hen xiong", "很凶" }, { "hen yan", "很严" },
			{ "hen yan zhong", "很严重" }, { "hen you", "很有" }, { "hen you ke neng", "很有可能" }, { "hen you yi si", "很有意思" }, { "hen yuan", "很远" },
			{ "hen zao", "很早" }, { "hen zao jiu", "很早就" }, { "hen zao yi qian", "很早以前" }, { "hen zheng chang", "很正常" }, { "hen zhong", "很重" },
			{ "hen zhong yao", "很重要" }, { "hen zhua", "狠抓" }, { "hen zhun", "很准" }, { "hen zi ran", "很自然" }, { "heng", "亨" }, { "heng", "佷" }, { "heng", "哼" },
			{ "heng", "啈" }, { "heng", "姮" }, { "heng", "恆" }, { "heng", "恒" }, { "heng", "桁" }, { "heng", "横" }, { "heng", "橫" }, { "heng", "烆" },
			{ "heng", "珩" }, { "heng", "胻" }, { "heng", "脝" }, { "heng", "蘅" }, { "heng", "衡" }, { "heng", "鑅" }, { "heng", "鵆" }, { "heng bin", "横滨" },
			{ "heng chuan", "横穿" }, { "heng dian", "横店" }, { "heng ding", "恒定" }, { "heng fu", "横幅" }, { "heng heng", "哼哼" }, { "heng ji", "哼唧" },
			{ "heng jiu", "恒久" }, { "heng kong chu shi", "横空出世" }, { "heng kua", "横跨" }, { "heng le", "哼了" }, { "heng li", "亨利" }, { "heng liang", "横梁" },
			{ "heng liang", "衡量" }, { "heng pan", "横盘" }, { "heng sao", "横扫" }, { "heng shan", "衡山" }, { "heng sheng", "恒生" }, { "heng shu", "横竖" },
			{ "heng shui", "衡水" }, { "heng wen", "恒温" }, { "heng xian", "横线" }, { "heng xiang", "横向" }, { "heng xin", "恒心" }, { "heng xing", "恒星" },
			{ "heng xing", "横行" }, { "heng yang", "衡阳" }, { "heng zhe", "哼着" }, { "heng zhe", "横着" }, { "heng zhi", "恒指" }, { "hm", "噷" }, { "hng", "哼" },
			{ "hong", "仜" }, { "hong", "吰" }, { "hong", "吽" }, { "hong", "哄" }, { "hong", "嗊" }, { "hong", "嚝" }, { "hong", "垬" }, { "hong", "妅" },
			{ "hong", "宏" }, { "hong", "宖" }, { "hong", "弘" }, { "hong", "彋" }, { "hong", "愩" }, { "hong", "汯" }, { "hong", "泓" }, { "hong", "洪" },
			{ "hong", "浤" }, { "hong", "渱" }, { "hong", "澋" }, { "hong", "澒" }, { "hong", "灴" }, { "hong", "烘" }, { "hong", "焢" }, { "hong", "玒" },
			{ "hong", "竑" }, { "hong", "竤" }, { "hong", "篊" }, { "hong", "紅" }, { "hong", "紘" }, { "hong", "红" }, { "hong", "羾" }, { "hong", "翃" },
			{ "hong", "耾" }, { "hong", "苰" }, { "hong", "荭" }, { "hong", "葒" }, { "hong", "蕻" }, { "hong", "薨" }, { "hong", "虹" }, { "hong", "訇" },
			{ "hong", "訌" }, { "hong", "讧" }, { "hong", "谹" }, { "hong", "谼" }, { "hong", "軣" }, { "hong", "輷" }, { "hong", "轟" }, { "hong", "轰" },
			{ "hong", "鈜" }, { "hong", "鉷" }, { "hong", "鋐" }, { "hong", "鍧" }, { "hong", "閎" }, { "hong", "闳" }, { "hong", "霐" }, { "hong", "霟" },
			{ "hong", "鞃" }, { "hong", "魟" }, { "hong", "鴻" }, { "hong", "鸿" }, { "hong", "黉" }, { "hong", "黌" }, { "hong bai", "红白" }, { "hong ban", "红斑" },
			{ "hong bao", "红包" }, { "hong bao shi", "红宝石" }, { "hong bian", "红遍" }, { "hong bo", "洪波" }, { "hong cha", "红茶" }, { "hong chen", "红尘" },
			{ "hong chun", "红唇" }, { "hong da", "宏大" }, { "hong da", "宏达" }, { "hong deng", "红灯" }, { "hong deng qu", "红灯区" }, { "hong di tan", "红地毯" },
			{ "hong dian", "红点" }, { "hong dong", "轰动" }, { "hong dou", "红豆" }, { "hong feng", "洪峰" }, { "hong gan", "烘干" }, { "hong gou", "鸿沟" },
			{ "hong guan", "宏观" }, { "hong guan jing ji", "宏观经济" }, { "hong guan tiao kong", "宏观调控" }, { "hong guan zheng ce", "宏观政策" },
			{ "hong guang", "红光" }, { "hong hai", "红海" }, { "hong he", "红河" }, { "hong hei", "红黑" }, { "hong hong", "哄哄" }, { "hong hong", "红红" },
			{ "hong hong de", "红红的" }, { "hong hong huo huo", "红红火火" }, { "hong hong lie lie", "轰轰烈烈" }, { "hong hua", "红花" }, { "hong huo", "红火" },
			{ "hong ji", "宏基" }, { "hong jing", "红警" }, { "hong jiu", "红酒" }, { "hong jun", "红军" }, { "hong kao", "烘烤" }, { "hong kou", "虹口" },
			{ "hong le", "红了" }, { "hong li", "红利" }, { "hong lian", "红脸" }, { "hong liang", "洪亮" }, { "hong ling jin", "红领巾" }, { "hong liu", "洪流" },
			{ "hong long", "红龙" }, { "hong lou", "红楼" }, { "hong lou meng", "红楼梦" }, { "hong lv deng", "红绿灯" }, { "hong mei", "红梅" },
			{ "hong mei gui", "红玫瑰" }, { "hong ming", "轰鸣" }, { "hong mo", "红魔" }, { "hong mu", "红木" }, { "hong niang", "红娘" }, { "hong niu", "红牛" },
			{ "hong pai", "红牌" }, { "hong qi", "宏碁" }, { "hong qi", "红旗" }, { "hong qiao", "虹桥" }, { "hong ran", "轰然" }, { "hong ren", "红人" },
			{ "hong ri", "红日" }, { "hong run", "红润" }, { "hong se", "红色" }, { "hong se lv you", "红色旅游" }, { "hong shao", "红烧" }, { "hong shao rou", "红烧肉" },
			{ "hong shi zi", "红十字" }, { "hong shi zi hui", "红十字会" }, { "hong shu", "红薯" }, { "hong shu lin", "红树林" }, { "hong shui", "洪水" },
			{ "hong tang", "红糖" }, { "hong tao", "红桃" }, { "hong tu", "宏图" }, { "hong tuo", "烘托" }, { "hong wai", "红外" }, { "hong wai xian", "红外线" },
			{ "hong wei", "宏伟" }, { "hong wei bing", "红卫兵" }, { "hong wu", "洪武" }, { "hong xi bao", "红细胞" }, { "hong xia", "红霞" }, { "hong xian", "红线" },
			{ "hong xin", "红心" }, { "hong xing", "红星" }, { "hong xing", "红杏" }, { "hong xing chu qiang", "红杏出墙" }, { "hong xiu", "红袖" },
			{ "hong xue si", "红血丝" }, { "hong yan", "红眼" }, { "hong yan", "红颜" }, { "hong yan", "鸿雁" }, { "hong yan zhi ji", "红颜知己" }, { "hong yang", "弘扬" },
			{ "hong ye", "红叶" }, { "hong yi", "红衣" }, { "hong yuan", "宏远" }, { "hong yun", "红云" }, { "hong yun", "红晕" }, { "hong zai", "洪灾" },
			{ "hong zao", "红枣" }, { "hong zha", "轰炸" }, { "hong zha ji", "轰炸机" }, { "hong zhong", "红肿" }, { "hong zi", "红字" }, { "hou", "侯" }, { "hou", "候" },
			{ "hou", "厚" }, { "hou", "后" }, { "hou", "吼" }, { "hou", "喉" }, { "hou", "垕" }, { "hou", "堠" }, { "hou", "帿" }, { "hou", "後" }, { "hou", "洉" },
			{ "hou", "猴" }, { "hou", "瘊" }, { "hou", "篌" }, { "hou", "糇" }, { "hou", "翭" }, { "hou", "腄" }, { "hou", "茩" }, { "hou", "葔" }, { "hou", "詬" },
			{ "hou", "逅" }, { "hou", "郈" }, { "hou", "鄇" }, { "hou", "鍭" }, { "hou", "餱" }, { "hou", "骺" }, { "hou", "鯸" }, { "hou", "鱟" }, { "hou", "鲎" },
			{ "hou", "齁" }, { "hou ai", "厚爱" }, { "hou ban", "后半" }, { "hou ban ye", "后半夜" }, { "hou bei", "后备" }, { "hou bei", "后背" }, { "hou bei", "后被" },
			{ "hou bei", "后辈" }, { "hou bei xiang", "后备箱" }, { "hou bian", "后便" }, { "hou bian", "后边" }, { "hou bu", "候补" }, { "hou bu", "后部" },
			{ "hou cai", "后才" }, { "hou cai neng", "后才能" }, { "hou chang", "后场" }, { "hou che", "候车" }, { "hou chen", "后尘" }, { "hou dai", "后代" },
			{ "hou dao", "厚道" }, { "hou dao", "吼道" }, { "hou de", "厚的" }, { "hou du", "厚度" }, { "hou duan", "后端" }, { "hou dun", "后盾" }, { "hou fang", "后方" },
			{ "hou fang", "后防" }, { "hou gai", "后盖" }, { "hou gong", "后宫" }, { "hou gu zhi you", "后顾之忧" }, { "hou guo", "后果" }, { "hou hai", "后海" },
			{ "hou hou", "厚厚" }, { "hou hou", "吼吼" }, { "hou hou de", "厚厚的" }, { "hou hua", "后话" }, { "hou hui", "后会" }, { "hou hui", "后悔" },
			{ "hou hui mo ji", "后悔莫及" }, { "hou ji", "后继" }, { "hou ji", "后记" }, { "hou jiang", "后将" }, { "hou jiao", "吼叫" }, { "hou jin", "后劲" },
			{ "hou jin", "后进" }, { "hou jing", "后经" }, { "hou jiu", "后就" }, { "hou ke", "后可" }, { "hou lai", "后来" }, { "hou lai zhe", "后来者" },
			{ "hou long", "喉咙" }, { "hou lu", "后路" }, { "hou lun", "后轮" }, { "hou ma", "后妈" }, { "hou men", "后门" }, { "hou mian", "后面" },
			{ "hou nao shao", "后脑勺" }, { "hou niao", "候鸟" }, { "hou pa", "后怕" }, { "hou pai", "后排" }, { "hou pei cen", "侯佩岑" }, { "hou qi", "后期" },
			{ "hou qi zhi zuo", "后期制作" }, { "hou qin", "后勤" }, { "hou ren", "后人" }, { "hou shan", "后山" }, { "hou she", "喉舌" }, { "hou sheng", "后生" },
			{ "hou shi", "厚实" }, { "hou shi", "后世" }, { "hou shi", "后事" }, { "hou shi", "后市" }, { "hou shi jing", "后视镜" }, { "hou tai", "后台" },
			{ "hou tian", "后天" }, { "hou tou", "后头" }, { "hou tui", "后腿" }, { "hou tui", "后退" }, { "hou wang", "厚望" }, { "hou wei", "后卫" },
			{ "hou xian dai", "后现代" }, { "hou xu", "后续" }, { "hou xuan", "候选" }, { "hou xuan ren", "候选人" }, { "hou yang", "后仰" }, { "hou yao", "后腰" },
			{ "hou yao wen", "侯耀文" }, { "hou yi", "后羿" }, { "hou yi", "后裔" }, { "hou yi zheng", "后遗症" }, { "hou yin", "后因" }, { "hou yong", "后用" },
			{ "hou you", "后又" }, { "hou yuan", "后院" }, { "hou zai", "后再" }, { "hou zhe", "后者" }, { "hou zhong", "厚重" }, { "hou zhui", "后缀" },
			{ "hou zhui ming", "后缀名" }, { "hou zi", "猴子" }, { "hou zuo", "后座" }, { "hu", "乎" }, { "hu", "乕" }, { "hu", "互" }, { "hu", "俿" }, { "hu", "冱" },
			{ "hu", "冴" }, { "hu", "匢" }, { "hu", "呼" }, { "hu", "和" }, { "hu", "唬" }, { "hu", "唿" }, { "hu", "嘝" }, { "hu", "囫" }, { "hu", "垀" },
			{ "hu", "壶" }, { "hu", "壷" }, { "hu", "壺" }, { "hu", "婟" }, { "hu", "媩" }, { "hu", "嫭" }, { "hu", "嫮" }, { "hu", "寣" }, { "hu", "岵" },
			{ "hu", "弖" }, { "hu", "弧" }, { "hu", "忽" }, { "hu", "怙" }, { "hu", "惚" }, { "hu", "戏" }, { "hu", "戶" }, { "hu", "户" }, { "hu", "戸" },
			{ "hu", "戽" }, { "hu", "扈" }, { "hu", "抇" }, { "hu", "护" }, { "hu", "斛" }, { "hu", "昈" }, { "hu", "昒" }, { "hu", "曶" }, { "hu", "枑" },
			{ "hu", "核" }, { "hu", "楜" }, { "hu", "槲" }, { "hu", "槴" }, { "hu", "歑" }, { "hu", "沍" }, { "hu", "沪" }, { "hu", "浒" }, { "hu", "淈" },
			{ "hu", "淲" }, { "hu", "淴" }, { "hu", "湖" }, { "hu", "滬" }, { "hu", "滸" }, { "hu", "滹" }, { "hu", "瀫" }, { "hu", "烀" }, { "hu", "焀" },
			{ "hu", "煳" }, { "hu", "熩" }, { "hu", "狐" }, { "hu", "猢" }, { "hu", "琥" }, { "hu", "瑚" }, { "hu", "瓠" }, { "hu", "祜" }, { "hu", "笏" },
			{ "hu", "箎" }, { "hu", "粐" }, { "hu", "糊" }, { "hu", "綔" }, { "hu", "縎" }, { "hu", "縠" }, { "hu", "胡" }, { "hu", "葫" }, { "hu", "蔰" },
			{ "hu", "虎" }, { "hu", "虖" }, { "hu", "蝴" }, { "hu", "螜" }, { "hu", "衚" }, { "hu", "觳" }, { "hu", "護" }, { "hu", "许" }, { "hu", "轷" },
			{ "hu", "鄠" }, { "hu", "醐" }, { "hu", "鍙" }, { "hu", "雽" }, { "hu", "韄" }, { "hu", "頀" }, { "hu", "餬" }, { "hu", "鬍" }, { "hu", "魱" },
			{ "hu", "鯱" }, { "hu", "鰗" }, { "hu", "鵠" }, { "hu", "鶘" }, { "hu", "鶦" }, { "hu", "鶻" }, { "hu", "鹄" }, { "hu", "鹕" }, { "hu", "鹘" },
			{ "hu", "鹱" }, { "hu bei", "湖北" }, { "hu bei ren", "湖北人" }, { "hu bei sheng", "湖北省" }, { "hu bian", "湖边" }, { "hu bin", "湖滨" }, { "hu bu", "互不" },
			{ "hu bu", "互补" }, { "hu bu xing", "互补性" }, { "hu che", "胡扯" }, { "hu chu", "呼出" }, { "hu da", "湖大" }, { "hu dan long wei", "虎胆龙威" },
			{ "hu die", "蝴蝶" }, { "hu die jie", "蝴蝶结" }, { "hu dong", "互动" }, { "hu dong xing", "互动性" }, { "hu du", "弧度" }, { "hu er", "忽而" },
			{ "hu fa", "护法" }, { "hu fang", "互访" }, { "hu feng huan yu", "呼风唤雨" }, { "hu fu", "护肤" }, { "hu fu pin", "护肤品" }, { "hu ge", "胡戈" },
			{ "hu ge", "胡歌" }, { "hu han", "呼喊" }, { "hu hang", "护航" }, { "hu he hao te", "呼和浩特" }, { "hu hu", "乎乎" }, { "hu hu", "呼呼" }, { "hu hu", "忽忽" },
			{ "hu hu", "糊糊" }, { "hu huan", "互换" }, { "hu huan", "呼唤" }, { "hu hui", "互惠" }, { "hu ji", "户籍" }, { "hu jia", "护甲" }, { "hu jia", "胡佳" },
			{ "hu jiao", "呼叫" }, { "hu jiao", "胡椒" }, { "hu jiao fen", "胡椒粉" }, { "hu jiao zhong xin", "呼叫中心" }, { "hu jiao zhuan yi", "呼叫转移" },
			{ "hu jin tao", "胡锦涛" }, { "hu jin tao zai", "胡锦涛在" }, { "hu jiu", "呼救" }, { "hu jun", "胡军" }, { "hu kou", "户口" }, { "hu kou", "糊口" },
			{ "hu kou", "虎口" }, { "hu kou ben", "户口本" }, { "hu kou bu", "户口簿" }, { "hu lai", "胡来" }, { "hu lan", "护栏" }, { "hu li", "互利" }, { "hu li", "护理" },
			{ "hu li", "湖里" }, { "hu li", "狐狸" }, { "hu li hu tu", "糊里糊涂" }, { "hu li jing", "狐狸精" }, { "hu lian", "互联" }, { "hu lian", "互连" },
			{ "hu lian hu tong", "互联互通" }, { "hu lian wang", "互联网" }, { "hu lian xing kong", "互联星空" }, { "hu lu", "呼噜" }, { "hu lu", "葫芦" },
			{ "hu lu dao", "葫芦岛" }, { "hu luan", "胡乱" }, { "hu lue", "忽略" }, { "hu luo bo", "胡萝卜" }, { "hu luo bo su", "胡萝卜素" }, { "hu men", "虎门" },
			{ "hu mian", "湖面" }, { "hu ming", "户名" }, { "hu nan", "湖南" }, { "hu nan da xue", "湖南大学" }, { "hu nan ren", "湖南人" }, { "hu nan sheng", "湖南省" },
			{ "hu nan tai", "湖南台" }, { "hu nan wei shi", "湖南卫视" }, { "hu nao", "胡闹" }, { "hu nong", "糊弄" }, { "hu pan", "护盘" }, { "hu pan", "湖畔" },
			{ "hu pi", "虎皮" }, { "hu po", "湖泊" }, { "hu po", "琥珀" }, { "hu po se", "琥珀色" }, { "hu qi", "呼气" }, { "hu qu", "湖区" }, { "hu ran", "忽然" },
			{ "hu ran jian", "忽然间" }, { "hu ren", "湖人" }, { "hu ren dui", "湖人队" }, { "hu run", "胡润" }, { "hu shang", "沪上" }, { "hu shen", "沪深" },
			{ "hu shen fu", "护身符" }, { "hu shen gu shi", "沪深股市" }, { "hu sheng", "呼声" }, { "hu shi", "呼市" }, { "hu shi", "忽视" }, { "hu shi", "护士" },
			{ "hu shi", "沪市" }, { "hu shi", "胡适" }, { "hu shi dan dan", "虎视眈眈" }, { "hu shi zhang", "护士长" }, { "hu shu", "户数" }, { "hu shui", "湖水" },
			{ "hu shuo", "胡说" }, { "hu shuo ba dao", "胡说八道" }, { "hu si luan xiang", "胡思乱想" }, { "hu song", "护送" }, { "hu tong", "互通" }, { "hu tong", "胡同" },
			{ "hu tong li", "胡同里" }, { "hu tou", "户头" }, { "hu tou", "虎头" }, { "hu tu", "糊涂" }, { "hu wai", "户外" }, { "hu wai guang gao", "户外广告" },
			{ "hu wai huo dong", "户外活动" }, { "hu wai yun dong", "户外运动" }, { "hu wan", "护腕" }, { "hu wei", "互为" }, { "hu wei", "护卫" }, { "hu xi", "呼吸" },
			{ "hu xi dao", "呼吸道" }, { "hu xi kun nan", "呼吸困难" }, { "hu xian", "弧线" }, { "hu xiang", "互相" }, { "hu xiang bang zhu", "互相帮助" },
			{ "hu xiao", "呼啸" }, { "hu xin", "互信" }, { "hu xing", "弧形" }, { "hu xing", "户型" }, { "hu xing tu", "户型图" }, { "hu xu", "胡须" },
			{ "hu yan bin", "胡彦斌" }, { "hu yan luan yu", "胡言乱语" }, { "hu yao bang", "胡耀邦" }, { "hu yi", "狐疑" }, { "hu ying", "呼应" }, { "hu you", "忽悠" },
			{ "hu yu", "呼吁" }, { "hu zhao", "护照" }, { "hu zhe", "护着" }, { "hu zhi", "沪指" }, { "hu zhi yu chu", "呼之欲出" }, { "hu zhong", "湖中" },
			{ "hu zhou", "湖州" }, { "hu zhu", "互助" }, { "hu zhu", "户主" }, { "hu zhu", "护住" }, { "hu zhu xi", "胡主席" }, { "hu zhuang", "糊状" }, { "hu zi", "胡子" },
			{ "hu zi", "虎子" }, { "hua", "划" }, { "hua", "劃" }, { "hua", "化" }, { "hua", "华" }, { "hua", "吪" }, { "hua", "哗" }, { "hua", "嘩" }, { "hua", "埖" },
			{ "hua", "嫿" }, { "hua", "嬅" }, { "hua", "崋" }, { "hua", "搳" }, { "hua", "摦" }, { "hua", "杹" }, { "hua", "桦" }, { "hua", "椛" }, { "hua", "槬" },
			{ "hua", "樺" }, { "hua", "滑" }, { "hua", "澅" }, { "hua", "猾" }, { "hua", "画" }, { "hua", "畫" }, { "hua", "畵" }, { "hua", "砉" }, { "hua", "硴" },
			{ "hua", "糀" }, { "hua", "繣" }, { "hua", "花" }, { "hua", "華" }, { "hua", "蘤" }, { "hua", "螖" }, { "hua", "話" }, { "hua", "諙" }, { "hua", "譁" },
			{ "hua", "话" }, { "hua", "錵" }, { "hua", "鏵" }, { "hua", "铧" }, { "hua", "驊" }, { "hua", "骅" }, { "hua", "魤" }, { "hua", "鷨" }, { "hua an", "华安" },
			{ "hua bai", "花白" }, { "hua ban", "滑板" }, { "hua ban", "花瓣" }, { "hua bao", "华宝" }, { "hua bao", "画报" }, { "hua bei", "华北" },
			{ "hua bei di qu", "华北地区" }, { "hua bi", "画笔" }, { "hua bian", "花边" }, { "hua bing", "滑冰" }, { "hua bo", "划拨" }, { "hua bu", "画布" },
			{ "hua bu lai", "划不来" }, { "hua cao", "花草" }, { "hua ce", "画册" }, { "hua cha", "花茶" }, { "hua chen", "华晨" }, { "hua cheng", "化成" },
			{ "hua cheng", "花城" }, { "hua chi", "花痴" }, { "hua chu", "划出" }, { "hua chu", "画出" }, { "hua chuan", "划船" }, { "hua cong", "花丛" },
			{ "hua dan", "花旦" }, { "hua dan", "话单" }, { "hua de", "画得" }, { "hua dian", "华电" }, { "hua dian", "花店" }, { "hua dian", "花点" },
			{ "hua diao", "花掉" }, { "hua ding", "划定" }, { "hua dong", "华东" }, { "hua dong", "滑动" }, { "hua dong di qu", "华东地区" }, { "hua dou", "话都" },
			{ "hua du", "花都" }, { "hua duo", "花朵" }, { "hua duo shao qian", "花多少钱" }, { "hua er", "花儿" }, { "hua er jie", "华尔街" }, { "hua fa", "画法" },
			{ "hua fei", "化肥" }, { "hua fei", "花费" }, { "hua fei", "话费" }, { "hua fen", "划分" }, { "hua fen", "花粉" }, { "hua feng", "画风" }, { "hua fu", "华府" },
			{ "hua gai", "滑盖" }, { "hua gang yan", "花岗岩" }, { "hua gong", "化工" }, { "hua gong", "华工" }, { "hua gong chan pin", "化工产品" },
			{ "hua gong chang", "化工厂" }, { "hua guan", "花冠" }, { "hua guang", "华光" }, { "hua guang", "花光" }, { "hua gui", "划归" }, { "hua gui", "华贵" },
			{ "hua guo", "划过" }, { "hua guo", "滑过" }, { "hua guo feng", "华国锋" }, { "hua guo shan", "花果山" }, { "hua he wu", "化合物" }, { "hua hen", "划痕" },
			{ "hua hua", "哗哗" }, { "hua hua", "画画" }, { "hua hua", "花花" }, { "hua hua cao cao", "花花草草" }, { "hua hua gong zi", "花花公子" },
			{ "hua hua lv lv", "花花绿绿" }, { "hua hui", "花卉" }, { "hua ji", "滑稽" }, { "hua ji", "花季" }, { "hua ji", "话机" }, { "hua jia", "画家" },
			{ "hua jian", "花间" }, { "hua jiao", "花椒" }, { "hua jie", "化解" }, { "hua ju", "话剧" }, { "hua juan", "画卷" }, { "hua jun", "华军" },
			{ "hua kai", "花开" }, { "hua kang", "华康" }, { "hua la la", "哗啦啦" }, { "hua lai", "话来" }, { "hua lai shi", "华莱士" }, { "hua lan", "花篮" },
			{ "hua lang", "画廊" }, { "hua lei", "花蕾" }, { "hua li", "华丽" }, { "hua lian", "华联" }, { "hua liao", "化疗" }, { "hua long", "华龙" },
			{ "hua lu shui", "花露水" }, { "hua luo", "滑落" }, { "hua luo", "花落" }, { "hua mei", "华美" }, { "hua mian", "画面" }, { "hua ming", "化名" },
			{ "hua mu", "花木" }, { "hua na", "华纳" }, { "hua nan", "华南" }, { "hua nan di qu", "华南地区" }, { "hua nan hu", "华南虎" }, { "hua neng", "华能" },
			{ "hua niao", "花鸟" }, { "hua nong", "华农" }, { "hua pen", "花盆" }, { "hua ping", "花屏" }, { "hua ping", "花瓶" }, { "hua po", "划破" },
			{ "hua po", "滑坡" }, { "hua qi", "花旗" }, { "hua qi", "花期" }, { "hua qi yin hang", "花旗银行" }, { "hua qian", "花钱" }, { "hua qian mai", "花钱买" },
			{ "hua qiang", "华强" }, { "hua qiang bei", "华强北" }, { "hua qiao", "华侨" }, { "hua qiao cheng", "华侨城" }, { "hua qiao hua ren", "华侨华人" },
			{ "hua quan", "花圈" }, { "hua ran", "哗然" }, { "hua ren", "华人" }, { "hua ru", "划入" }, { "hua rui", "花蕊" }, { "hua run", "华润" }, { "hua se", "花色" },
			{ "hua shan", "华山" }, { "hua shang", "划上" }, { "hua shang", "划伤" }, { "hua shang", "华商" }, { "hua shang", "画上" }, { "hua shang", "花上" },
			{ "hua shang bao", "华商报" }, { "hua shao", "花哨" }, { "hua shen", "化身" }, { "hua sheng", "花生" }, { "hua sheng dun", "华盛顿" },
			{ "hua sheng ke", "花生壳" }, { "hua sheng mi", "花生米" }, { "hua sheng you", "花生油" }, { "hua shi", "化石" }, { "hua shi", "华师" }, { "hua shi", "画室" },
			{ "hua shi da", "华师大" }, { "hua shi dai", "划时代" }, { "hua shui", "划水" }, { "hua shuo", "华硕" }, { "hua shuo", "话说" }, { "hua suan", "划算" },
			{ "hua tai", "华泰" }, { "hua tan", "化痰" }, { "hua tan", "花坛" }, { "hua ti", "话题" }, { "hua tian", "华天" }, { "hua ting", "华庭" },
			{ "hua tong", "话筒" }, { "hua tou", "花头" }, { "hua tu", "画图" }, { "hua wei", "化为" }, { "hua wei", "华为" }, { "hua wen", "华文" }, { "hua wen", "花纹" },
			{ "hua wu", "话务" }, { "hua xi", "华西" }, { "hua xia", "华夏" }, { "hua xia yin hang", "华夏银行" }, { "hua xian", "划线" }, { "hua xian", "化纤" },
			{ "hua xiang", "画像" }, { "hua xiang", "花香" }, { "hua xiao", "花销" }, { "hua xin", "花心" }, { "hua xing", "华星" }, { "hua xing", "滑行" },
			{ "hua xu", "花絮" }, { "hua xue", "化学" }, { "hua xue", "滑雪" }, { "hua xue chang", "滑雪场" }, { "hua xue cheng fen", "化学成分" },
			{ "hua xue fan ying", "化学反应" }, { "hua xue pin", "化学品" }, { "hua xue wu zhi", "化学物质" }, { "hua yan", "化验" }, { "hua yan qiao yu", "花言巧语" },
			{ "hua yang", "华阳" }, { "hua yang", "花样" }, { "hua yang nian hua", "花样年华" }, { "hua yi", "华裔" }, { "hua yi", "华谊" }, { "hua yin", "话音" },
			{ "hua yu", "华宇" }, { "hua yu", "华语" }, { "hua yu", "花语" }, { "hua yu", "话语" }, { "hua yu quan", "话语权" }, { "hua yuan", "华源" },
			{ "hua yuan", "花园" }, { "hua yuan", "花苑" }, { "hua zai", "华仔" }, { "hua zai", "花在" }, { "hua zhan", "画展" }, { "hua zhao", "花招" },
			{ "hua zhe", "画着" }, { "hua zhi", "画质" }, { "hua zhi", "花枝" }, { "hua zhong", "华中" }, { "hua zhong", "画中" }, { "hua zhong qu chong", "哗众取宠" },
			{ "hua zhuan", "划转" }, { "hua zhuang", "化妆" }, { "hua zhuang", "化装" }, { "hua zhuang pin", "化妆品" }, { "hua zhuang shi", "化妆师" },
			{ "hua zhuang shui", "化妆水" }, { "hua zi", "华仔" }, { "hua zuo", "化作" }, { "hua zuo", "画作" }, { "huai", "划" }, { "huai", "坏" }, { "huai", "壊" },
			{ "huai", "壞" }, { "huai", "徊" }, { "huai", "怀" }, { "huai", "懐" }, { "huai", "懷" }, { "huai", "槐" }, { "huai", "櫰" }, { "huai", "淮" },
			{ "huai", "蘹" }, { "huai", "蘾" }, { "huai", "褢" }, { "huai", "褱" }, { "huai", "踝" }, { "huai an", "淮安" }, { "huai bao", "怀抱" },
			{ "huai bei", "淮北" }, { "huai chu", "坏处" }, { "huai chuai", "怀揣" }, { "huai dan", "坏蛋" }, { "huai dao", "坏道" }, { "huai dian", "坏点" },
			{ "huai diao", "坏掉" }, { "huai hai", "淮海" }, { "huai hai lu", "淮海路" }, { "huai he", "淮河" }, { "huai hua", "坏话" }, { "huai hua", "怀化" },
			{ "huai huai", "坏坏" }, { "huai jiu", "怀旧" }, { "huai le", "怀了" }, { "huai li", "怀里" }, { "huai nan", "淮南" }, { "huai nan ren", "坏男人" },
			{ "huai nian", "怀念" }, { "huai nv ren", "坏女人" }, { "huai ren", "坏人" }, { "huai rou", "怀柔" }, { "huai shang", "怀上" }, { "huai shi", "坏事" },
			{ "huai si", "坏死" }, { "huai te", "怀特" }, { "huai xi guan", "坏习惯" }, { "huai yi", "怀疑" } };
};
