package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN11 {
	public static String[][] pl = { { "die", "叠" }, { "die", "咥" }, { "die", "喋" }, { "die", "垤" }, { "die", "堞" }, { "die", "峌" }, { "die", "嵽" },
			{ "die", "昳" }, { "die", "爹" }, { "die", "牒" }, { "die", "瓞" }, { "die", "畳" }, { "die", "疂" }, { "die", "疉" }, { "die", "疊" }, { "die", "眣" },
			{ "die", "碟" }, { "die", "絰" }, { "die", "耋" }, { "die", "胅" }, { "die", "艓" }, { "die", "苵" }, { "die", "蜨" }, { "die", "蝶" }, { "die", "褋" },
			{ "die", "詄" }, { "die", "諜" }, { "die", "谍" }, { "die", "跌" }, { "die", "跮" }, { "die", "蹀" }, { "die", "迭" }, { "die", "镻" }, { "die", "鲽" },
			{ "die dai", "迭代" }, { "die dang qi fu", "跌宕起伏" }, { "die dao", "跌倒" }, { "die dao", "跌到" }, { "die de", "跌得" }, { "die die", "爹爹" },
			{ "die die bu xiu", "喋喋不休" }, { "die die zhuang zhuang", "跌跌撞撞" }, { "die fu", "跌幅" }, { "die jia", "叠加" }, { "die jia", "跌价" },
			{ "die luo", "跌落" }, { "die ma", "爹妈" }, { "die niang", "爹娘" }, { "die pian", "碟片" }, { "die po", "跌破" }, { "die ru", "跌入" }, { "die shi", "跌势" },
			{ "die ting", "跌停" }, { "die ting ban", "跌停板" }, { "die wu", "蝶舞" }, { "die yan jing", "跌眼镜" }, { "die yi", "蝶衣" }, { "die zhi", "跌至" },
			{ "die zi", "碟子" }, { "ding", "丁" }, { "ding", "仃" }, { "ding", "叮" }, { "ding", "啶" }, { "ding", "定" }, { "ding", "嵿" }, { "ding", "帄" },
			{ "ding", "掟" }, { "ding", "椗" }, { "ding", "玎" }, { "ding", "町" }, { "ding", "甼" }, { "ding", "疔" }, { "ding", "盯" }, { "ding", "碇" },
			{ "ding", "碠" }, { "ding", "耵" }, { "ding", "聢" }, { "ding", "腚" }, { "ding", "萣" }, { "ding", "薡" }, { "ding", "虰" }, { "ding", "訂" },
			{ "ding", "订" }, { "ding", "酊" }, { "ding", "釘" }, { "ding", "錠" }, { "ding", "钉" }, { "ding", "锭" }, { "ding", "靪" }, { "ding", "頂" },
			{ "ding", "顁" }, { "ding", "顶" }, { "ding", "飣" }, { "ding", "鼎" }, { "ding a", "顶啊" }, { "ding bu", "顶部" }, { "ding can", "订餐" },
			{ "ding ceng", "顶层" }, { "ding dan", "定单" }, { "ding dan", "订单" }, { "ding dan hao", "订单号" }, { "ding dang", "叮当" }, { "ding dao", "顶到" },
			{ "ding dian", "定点" }, { "ding dian", "顶点" }, { "ding ding", "丁丁" }, { "ding ding", "定定" }, { "ding ding", "顶顶" }, { "ding ding ding", "顶顶顶" },
			{ "ding ding ding ding", "顶顶顶顶" }, { "ding dong", "叮咚" }, { "ding duan", "顶端" }, { "ding duo", "定夺" }, { "ding duo", "顶多" }, { "ding e", "定额" },
			{ "ding fang", "订房" }, { "ding feng", "顶峰" }, { "ding feng", "顶风" }, { "ding gao", "定稿" }, { "ding ge", "定格" }, { "ding gou", "定购" },
			{ "ding gou", "订购" }, { "ding hao", "订好" }, { "ding hao", "鼎好" }, { "ding hun", "订婚" }, { "ding huo", "订货" }, { "ding ji", "定级" },
			{ "ding ji", "顶级" }, { "ding ji yu ming", "顶级域名" }, { "ding jia", "定价" }, { "ding jia quan", "定价权" }, { "ding jian", "顶尖" }, { "ding jin", "定金" },
			{ "ding jin", "订金" }, { "ding ju", "定局" }, { "ding ju", "定居" }, { "ding jun hui", "丁俊晖" }, { "ding le", "定了" }, { "ding le", "订了" },
			{ "ding lei", "丁磊" }, { "ding li", "定力" }, { "ding li", "定理" }, { "ding li", "订立" }, { "ding li", "鼎力" }, { "ding liang", "定量" },
			{ "ding lou", "顶楼" }, { "ding lun", "定论" }, { "ding lv", "定律" }, { "ding ning", "叮咛" }, { "ding piao", "订票" }, { "ding qi", "定期" },
			{ "ding qi", "顶起" }, { "ding qi cun kuan", "定期存款" }, { "ding qi jian cha", "定期检查" }, { "ding shang", "盯上" }, { "ding shang", "顶上" },
			{ "ding shang qu", "顶上去" }, { "ding shen", "定神" }, { "ding sheng", "鼎盛" }, { "ding shi", "定势" }, { "ding shi", "定时" }, { "ding shi qi", "定时器" },
			{ "ding ti", "顶替" }, { "ding wei", "定为" }, { "ding wei", "定位" }, { "ding xia", "定下" }, { "ding xia", "顶下" }, { "ding xiang", "丁香" },
			{ "ding xiang", "定向" }, { "ding xiang zeng fa", "定向增发" }, { "ding xing", "定型" }, { "ding xing", "定性" }, { "ding yao", "定要" }, { "ding yi", "定义" },
			{ "ding yi xia", "顶一下" }, { "ding yu", "定于" }, { "ding yue", "订阅" }, { "ding zai", "定在" }, { "ding zai", "钉在" }, { "ding zhe", "盯着" },
			{ "ding zhe", "顶着" }, { "ding zhi", "定制" }, { "ding zhi", "定植" }, { "ding zhi", "订制" }, { "ding zhu", "叮嘱" }, { "ding zhu", "盯住" },
			{ "ding zhu", "顶住" }, { "ding zi", "钉子" }, { "ding zi hu", "钉子户" }, { "ding zi ku", "丁字裤" }, { "ding zui", "定罪" }, { "ding zuo", "定做" },
			{ "ding zuo", "订做" }, { "diu", "丟" }, { "diu", "丢" }, { "diu", "銩" }, { "diu", "铥" }, { "diu", "颩" }, { "diu bao", "丢包" }, { "diu diao", "丢掉" },
			{ "diu diu", "丢丢" }, { "diu le", "丢了" }, { "diu lian", "丢脸" }, { "diu qi", "丢弃" }, { "diu ren", "丢人" }, { "diu ren xian yan", "丢人现眼" },
			{ "diu shi", "丢失" }, { "diu xia", "丢下" }, { "dong", "东" }, { "dong", "侗" }, { "dong", "働" }, { "dong", "冬" }, { "dong", "冻" }, { "dong", "凍" },
			{ "dong", "动" }, { "dong", "動" }, { "dong", "咚" }, { "dong", "垌" }, { "dong", "埬" }, { "dong", "夂" }, { "dong", "姛" }, { "dong", "嬞" },
			{ "dong", "岽" }, { "dong", "峒" }, { "dong", "崠" }, { "dong", "恫" }, { "dong", "懂" }, { "dong", "戙" }, { "dong", "挏" }, { "dong", "揰" },
			{ "dong", "東" }, { "dong", "栋" }, { "dong", "棟" }, { "dong", "氡" }, { "dong", "洞" }, { "dong", "涷" }, { "dong", "硐" }, { "dong", "胨" },
			{ "dong", "胴" }, { "dong", "苳" }, { "dong", "菄" }, { "dong", "董" }, { "dong", "蕫" }, { "dong", "蝀" }, { "dong", "諌" }, { "dong", "迵" },
			{ "dong", "霘" }, { "dong", "駧" }, { "dong", "鮗" }, { "dong", "鶇" }, { "dong", "鶫" }, { "dong", "鸫" }, { "dong", "鼕" }, { "dong an", "东安" },
			{ "dong an", "东岸" }, { "dong ao hui", "冬奥会" }, { "dong bei", "东北" }, { "dong bei bu", "东北部" }, { "dong bei da xue", "东北大学" },
			{ "dong bei di qu", "东北地区" }, { "dong bei hu", "东北虎" }, { "dong bei ren", "东北人" }, { "dong bei ya", "东北亚" }, { "dong bi", "动笔" },
			{ "dong bian", "东边" }, { "dong bu", "东部" }, { "dong bu di qu", "东部地区" }, { "dong bu dong", "动不动" }, { "dong ce", "东侧" }, { "dong cha", "洞察" },
			{ "dong cha li", "洞察力" }, { "dong che", "动车" }, { "dong che zu", "动车组" }, { "dong cheng", "东城" }, { "dong cheng qu", "东城区" },
			{ "dong chong xia cao", "冬虫夏草" }, { "dong chuang", "冻疮" }, { "dong ci", "动词" }, { "dong da", "东大" }, { "dong dang", "动荡" },
			{ "dong dao zhu", "东道主" }, { "dong de", "冻得" }, { "dong de", "懂得" }, { "dong de", "懂的" }, { "dong de zhen xi", "懂得珍惜" }, { "dong dong", "东东" },
			{ "dong dong", "冬冬" }, { "dong dong", "动动" }, { "dong dong", "咚咚" }, { "dong dong", "洞洞" }, { "dong fang", "东方" }, { "dong fang", "洞房" },
			{ "dong fang bu bai", "东方不败" }, { "dong fang hong", "东方红" }, { "dong fang ming zhu", "东方明珠" }, { "dong fang ren", "东方人" },
			{ "dong fang shen qi", "东方神起" }, { "dong fang wang", "东方网" }, { "dong fang wei shi", "东方卫视" }, { "dong fang zhuo", "董方卓" }, { "dong feng", "东风" },
			{ "dong feng ri chan", "东风日产" }, { "dong gan", "动感" }, { "dong gan di dai", "动感地带" }, { "dong gong", "动工" }, { "dong gua", "冬瓜" },
			{ "dong guan", "东莞" }, { "dong guan shi", "东莞市" }, { "dong guo", "动过" }, { "dong hai", "东海" }, { "dong han", "东汉" }, { "dong hang", "东航" },
			{ "dong hang", "懂行" }, { "dong hu", "东湖" }, { "dong hua", "东华" }, { "dong hua", "动画" }, { "dong hua pian", "动画片" }, { "dong ji", "冬季" },
			{ "dong ji", "动机" }, { "dong jia", "东家" }, { "dong jiang", "东江" }, { "dong jiao", "东郊" }, { "dong jie", "东街" }, { "dong jie", "冻结" },
			{ "dong jie", "董洁" }, { "dong jin", "东晋" }, { "dong jing", "东京" }, { "dong jing", "动静" }, { "dong kou", "洞口" }, { "dong le", "懂了" },
			{ "dong li", "动力" }, { "dong li", "洞里" }, { "dong li xue", "动力学" }, { "dong liang", "栋梁" }, { "dong lu", "东路" }, { "dong luan", "动乱" },
			{ "dong ma", "懂吗" }, { "dong mai", "动脉" }, { "dong mai ying hua", "动脉硬化" }, { "dong man", "动漫" }, { "dong man chan ye", "动漫产业" },
			{ "dong mei", "冬梅" }, { "dong men", "东门" }, { "dong meng", "东盟" }, { "dong mi", "董秘" }, { "dong mian", "东面" }, { "dong mian", "冬眠" },
			{ "dong nan", "东南" }, { "dong nan bu", "东南部" }, { "dong nan da xue", "东南大学" }, { "dong nan xi bei", "东南西北" }, { "dong nan ya", "东南亚" },
			{ "dong nao", "动脑" }, { "dong nao jin", "动脑筋" }, { "dong neng", "动能" }, { "dong ou", "东欧" }, { "dong po", "东坡" }, { "dong qi lai", "动起来" },
			{ "dong qian", "动迁" }, { "dong qing", "动情" }, { "dong qu", "东区" }, { "dong ren", "动人" }, { "dong ri", "冬日" }, { "dong rong", "动容" },
			{ "dong ruan", "东软" }, { "dong shan", "东山" }, { "dong shen", "动身" }, { "dong sheng", "东升" }, { "dong shi", "懂事" }, { "dong shi", "董事" },
			{ "dong shi hui", "董事会" }, { "dong shi ju", "董事局" }, { "dong shi zhang", "董事长" }, { "dong shi zhang jian", "董事长兼" }, { "dong shou", "动手" },
			{ "dong shou neng li", "动手能力" }, { "dong shou shu", "动手术" }, { "dong si", "冻死" }, { "dong tai", "动态" }, { "dong tan", "动弹" },
			{ "dong tian", "冬天" }, { "dong ting", "动听" }, { "dong ting", "洞庭" }, { "dong ting hu", "洞庭湖" }, { "dong wang", "动网" }, { "dong wu", "东吴" },
			{ "dong wu", "动武" }, { "dong wu", "动物" }, { "dong wu fang yi", "动物防疫" }, { "dong wu xing", "动物性" }, { "dong wu yuan", "动物园" }, { "dong xi", "东西" },
			{ "dong xi", "洞悉" }, { "dong xi fang", "东西方" }, { "dong xian", "东线" }, { "dong xiang", "动向" }, { "dong xin", "东信" }, { "dong xin", "动心" },
			{ "dong xue", "洞穴" }, { "dong ya", "东亚" }, { "dong yang", "东洋" }, { "dong yang", "东阳" }, { "dong yao", "动摇" }, { "dong yi", "动易" },
			{ "dong yi", "动议" }, { "dong yin", "动因" }, { "dong ying", "东营" }, { "dong yong", "动用" }, { "dong yuan", "动员" }, { "dong yuan da hui", "动员大会" },
			{ "dong yuan hui", "动员会" }, { "dong zhan", "东站" }, { "dong zhang xi wang", "东张西望" }, { "dong zhe", "动辄" }, { "dong zhi", "东至" },
			{ "dong zhi", "东芝" }, { "dong zhi", "冬至" }, { "dong zhi men", "东直门" }, { "dong zhi wu", "动植物" }, { "dong zhong", "洞中" }, { "dong zhuo", "董卓" },
			{ "dong zuo", "动作" }, { "dong zuo pian", "动作片" }, { "dou", "兜" }, { "dou", "唗" }, { "dou", "抖" }, { "dou", "斗" }, { "dou", "枓" }, { "dou", "梪" },
			{ "dou", "浢" }, { "dou", "痘" }, { "dou", "瞗" }, { "dou", "窦" }, { "dou", "竇" }, { "dou", "篼" }, { "dou", "脰" }, { "dou", "荳" }, { "dou", "蔸" },
			{ "dou", "蚪" }, { "dou", "读" }, { "dou", "豆" }, { "dou", "逗" }, { "dou", "郖" }, { "dou", "都" }, { "dou", "酘" }, { "dou", "鈄" }, { "dou", "钭" },
			{ "dou", "闘" }, { "dou", "陡" }, { "dou", "餖" }, { "dou", "鬥" }, { "dou", "鬪" }, { "dou ai", "都爱" }, { "dou ba", "都把" }, { "dou ban", "豆瓣" },
			{ "dou bei", "都被" }, { "dou bi", "都比" }, { "dou bu", "都不" }, { "dou bu gan", "都不敢" }, { "dou bu shi", "都不是" }, { "dou bu zhi dao", "都不知道" },
			{ "dou cheng", "都成" }, { "dou chi", "都吃" }, { "dou chuan", "都穿" }, { "dou da", "都打" }, { "dou dao", "都到" }, { "dou de", "逗得" }, { "dou de", "都得" },
			{ "dou dei", "都得" }, { "dou di zhu", "斗地主" }, { "dou dong", "抖动" }, { "dou dong", "都懂" }, { "dou dou", "兜兜" }, { "dou dou", "痘痘" },
			{ "dou dou", "豆豆" }, { "dou dou", "逗逗" }, { "dou dui", "都对" }, { "dou fa", "都发" }, { "dou feng", "兜风" }, { "dou fu", "豆腐" },
			{ "dou fu gan", "豆腐干" }, { "dou gao", "都搞" }, { "dou gei", "都给" }, { "dou gen", "都跟" }, { "dou guai", "都怪" }, { "dou hao", "逗号" },
			{ "dou hao", "都好" }, { "dou hen", "都很" }, { "dou hua", "豆花" }, { "dou hui", "都会" }, { "dou jiang", "豆浆" }, { "dou jiang", "都将" },
			{ "dou jiao", "豆角" }, { "dou jiao", "都叫" }, { "dou kan", "都看" }, { "dou ke", "都可" }, { "dou kuai", "都快" }, { "dou lai", "都来" }, { "dou le", "逗乐" },
			{ "dou lei", "豆类" }, { "dou li", "兜里" }, { "dou liu", "逗留" }, { "dou mei", "都没" }, { "dou na", "都拿" }, { "dou nan", "都难" }, { "dou neng", "都能" },
			{ "dou ni wan", "逗你玩" }, { "dou niu", "斗牛" }, { "dou ou", "斗殴" }, { "dou peng", "斗篷" }, { "dou po", "豆粕" }, { "dou qi", "斗气" },
			{ "dou qiao", "陡峭" }, { "dou qu", "都去" }, { "dou ran", "陡然" }, { "dou rang", "都让" }, { "dou sha", "豆沙" }, { "dou shi", "斗士" }, { "dou shi", "都是" },
			{ "dou shi zhe yang", "都是这样" }, { "dou shou", "兜售" }, { "dou shuo", "都说" }, { "dou suan", "都算" }, { "dou ting", "都听" }, { "dou wei", "窦唯" },
			{ "dou wei", "都为" }, { "dou wei", "都未" }, { "dou wu", "都无" }, { "dou xiang", "都像" }, { "dou xiang", "都想" }, { "dou xiao", "都笑" },
			{ "dou xie", "都写" }, { "dou xing", "都行" }, { "dou ya", "豆芽" }, { "dou yao", "都要" }, { "dou yi", "都以" }, { "dou yi", "都已" }, { "dou ying", "都应" },
			{ "dou yong", "都用" }, { "dou you", "豆油" }, { "dou you", "都有" }, { "dou you", "都由" }, { "dou you zi ji", "都有自己" }, { "dou yu", "都与" },
			{ "dou zai", "都在" }, { "dou zhao", "都找" }, { "dou zheng", "斗争" }, { "dou zhi", "斗志" }, { "dou zhi", "斗智" }, { "dou zhi pin", "豆制品" },
			{ "dou zi", "豆子" }, { "dou zou", "都走" }, { "dou zui", "斗嘴" }, { "du", "嘟" }, { "du", "堵" }, { "du", "妒" }, { "du", "妬" }, { "du", "帾" },
			{ "du", "度" }, { "du", "杜" }, { "du", "椟" }, { "du", "櫝" }, { "du", "殰" }, { "du", "毒" }, { "du", "涜" }, { "du", "渎" }, { "du", "渡" },
			{ "du", "瀆" }, { "du", "牍" }, { "du", "牘" }, { "du", "犊" }, { "du", "犢" }, { "du", "独" }, { "du", "獨" }, { "du", "皾" }, { "du", "督" },
			{ "du", "睹" }, { "du", "秺" }, { "du", "笃" }, { "du", "篤" }, { "du", "肚" }, { "du", "芏" }, { "du", "蝳" }, { "du", "蠧" }, { "du", "蠹" },
			{ "du", "裻" }, { "du", "覩" }, { "du", "詫" }, { "du", "読" }, { "du", "讀" }, { "du", "讟" }, { "du", "读" }, { "du", "賭" }, { "du", "贕" },
			{ "du", "赌" }, { "du", "都" }, { "du", "醏" }, { "du", "錖" }, { "du", "鍍" }, { "du", "镀" }, { "du", "韇" }, { "du", "韣" }, { "du", "韥" },
			{ "du", "顿" }, { "du", "髑" }, { "du", "黩" }, { "du", "黷" }, { "du ba", "毒霸" }, { "du ba", "独霸" }, { "du bai", "独白" }, { "du ban", "督办" },
			{ "du bang", "杜邦" }, { "du ben", "读本" }, { "du bo", "读博" }, { "du bo", "赌博" }, { "du bo shi", "读博士" }, { "du bu", "独步" }, { "du cai", "独裁" },
			{ "du cai zhe", "独裁者" }, { "du cha", "督察" }, { "du cha", "督查" }, { "du cha zu", "督查组" }, { "du chang", "独唱" }, { "du chang", "赌场" },
			{ "du che", "堵车" }, { "du cheng", "都城" }, { "du chu", "独处" }, { "du chu", "读出" }, { "du chuang", "独创" }, { "du cu", "督促" }, { "du da", "毒打" },
			{ "du da", "独大" }, { "du da xue", "读大学" }, { "du dao", "独到" }, { "du dao", "督导" }, { "du dao", "读到" }, { "du dao zu", "督导组" }, { "du de", "读得" },
			{ "du dong", "读懂" }, { "du dou", "肚兜" }, { "du du", "嘟嘟" }, { "du du", "肚肚" }, { "du du", "读读" }, { "du du", "都督" }, { "du fan", "毒贩" },
			{ "du fu", "杜甫" }, { "du fu zuo yong", "毒副作用" }, { "du ge", "镀铬" }, { "du gu", "独孤" }, { "du guo", "度过" }, { "du guo", "渡过" }, { "du guo", "读过" },
			{ "du hai", "毒害" }, { "du he", "渡河" }, { "du hou gan", "读后感" }, { "du hui", "都会" }, { "du ji", "妒忌" }, { "du jia", "度假" }, { "du jia", "渡假" },
			{ "du jia", "独家" }, { "du jia cun", "度假村" }, { "du jia qu", "度假区" }, { "du jiang", "渡江" }, { "du jiang yan", "都江堰" },
			{ "du jiang yan shi", "都江堰市" }, { "du jie", "堵截" }, { "du jin", "镀金" }, { "du ju", "独具" }, { "du ju", "独居" }, { "du ju te se", "独具特色" },
			{ "du juan", "杜鹃" }, { "du jue", "杜绝" }, { "du jun", "督军" }, { "du ka qi", "读卡器" }, { "du kou", "渡口" }, { "du lai", "读来" }, { "du li", "独立" },
			{ "du li", "肚里" }, { "du li dong shi", "独立董事" }, { "du li si kao", "独立思考" }, { "du li xian ka", "独立显卡" }, { "du li xing", "独立性" },
			{ "du li zi zhu", "独立自主" }, { "du liang", "度量" }, { "du ling", "都灵" }, { "du liu", "毒瘤" }, { "du men", "独门" }, { "du mo", "镀膜" },
			{ "du nang", "嘟囔" }, { "du pan", "读盘" }, { "du pi", "肚皮" }, { "du pi wu", "肚皮舞" }, { "du pin", "毒品" }, { "du qi", "毒气" }, { "du qi", "肚脐" },
			{ "du qi", "赌气" }, { "du qi feng", "杜琪峰" }, { "du qiu", "赌球" }, { "du qu", "读取" }, { "du ri", "度日" }, { "du ru", "读入" }, { "du sai", "堵塞" },
			{ "du se", "堵塞" }, { "du she", "毒蛇" }, { "du shen", "独身" }, { "du sheng zi nv", "独生子女" }, { "du shi", "都市" }, { "du shi", "都是" },
			{ "du shi bao", "都市报" }, { "du shu", "度数" }, { "du shu", "读书" }, { "du shu", "读数" }, { "du shu ren", "读书人" }, { "du shu yi zhi", "独树一帜" },
			{ "du si", "毒死" }, { "du su", "毒素" }, { "du te", "独特" }, { "du te xing", "独特性" }, { "du tu", "赌徒" }, { "du wan", "读完" }, { "du wei", "杜威" },
			{ "du wu", "毒物" }, { "du wu", "独舞" }, { "du wu", "读物" }, { "du xian", "独显" }, { "du xiang", "独享" }, { "du xie", "读写" }, { "du xin", "镀锌" },
			{ "du xing", "毒性" }, { "du xing", "独行" }, { "du yan", "读研" }, { "du yan jiu sheng", "读研究生" }, { "du yao", "毒药" }, { "du yao", "都要" },
			{ "du yi wu er", "独一无二" }, { "du yin", "读音" }, { "du you", "独有" }, { "du you", "都有" }, { "du zai", "堵在" }, { "du zhan", "独占" }, { "du zhe", "读着" },
			{ "du zhe", "读者" }, { "du zhi", "渎职" }, { "du zhu", "堵住" }, { "du zhu", "赌注" }, { "du zhuan", "杜撰" }, { "du zi", "独自" }, { "du zi", "独资" },
			{ "du zi", "肚子" }, { "du zi li", "肚子里" }, { "du zi shang", "肚子上" }, { "du zi teng", "肚子疼" }, { "du zi tong", "肚子痛" }, { "du zou", "独奏" },
			{ "du zuo", "独坐" }, { "duan", "偳" }, { "duan", "媏" }, { "duan", "断" }, { "duan", "斷" }, { "duan", "椴" }, { "duan", "段" }, { "duan", "毈" },
			{ "duan", "煅" }, { "duan", "短" }, { "duan", "碫" }, { "duan", "端" }, { "duan", "簖" }, { "duan", "籪" }, { "duan", "緞" }, { "duan", "缎" },
			{ "duan", "腶" }, { "duan", "葮" }, { "duan", "躖" }, { "duan", "鍛" }, { "duan", "锻" }, { "duan bei", "断臂" }, { "duan bei shan", "断背山" },
			{ "duan ceng", "断层" }, { "duan chang", "断肠" }, { "duan chu", "短处" }, { "duan de", "短的" }, { "duan dian", "断点" }, { "duan dian", "断电" },
			{ "duan dian", "端点" }, { "duan diao", "断掉" }, { "duan ding", "断定" }, { "duan duan", "短短" }, { "duan duan de", "短短的" },
			{ "duan duan xu xu", "断断续续" }, { "duan fa", "短发" }, { "duan huo", "断货" }, { "duan jue", "断绝" }, { "duan kai", "断开" }, { "duan kou", "端口" },
			{ "duan kou hao", "端口号" }, { "duan ku", "短裤" }, { "duan le", "断了" }, { "duan lian", "锻炼" }, { "duan lian shen ti", "锻炼身体" }, { "duan lie", "断裂" },
			{ "duan liu", "断流" }, { "duan lu", "短路" }, { "duan lu qi", "断路器" }, { "duan luo", "段落" }, { "duan mian", "断面" }, { "duan ming", "短命" },
			{ "duan mu", "端木" }, { "duan nai", "断奶" }, { "duan ni", "端倪" }, { "duan pian", "短片" }, { "duan pian", "短篇" }, { "duan pian xiao shuo", "短篇小说" },
			{ "duan qi", "短期" }, { "duan qi", "端起" }, { "duan qiao", "断桥" }, { "duan qiu", "断球" }, { "duan que", "短缺" }, { "duan qun", "短裙" },
			{ "duan ran", "断然" }, { "duan shang", "端上" }, { "duan shi", "短时" }, { "duan shi", "短视" }, { "duan shi jian", "段时间" }, { "duan shi jian", "短时间" },
			{ "duan shi jian nei", "短时间内" }, { "duan song", "断送" }, { "duan tu", "短途" }, { "duan wang", "断网" }, { "duan wen", "短文" }, { "duan wu", "端午" },
			{ "duan wu jie", "端午节" }, { "duan xian", "断线" }, { "duan xian", "短线" }, { "duan xiang", "端详" }, { "duan xiao", "短小" }, { "duan xiao xi", "短消息" },
			{ "duan xin", "短信" }, { "duan xin xi", "短信息" }, { "duan xiu", "短袖" }, { "duan xun", "短讯" }, { "duan yan", "断言" }, { "duan yu", "段誉" },
			{ "duan yu", "短语" }, { "duan zan", "短暂" }, { "duan zao", "锻造" }, { "duan zhang qu yi", "断章取义" }, { "duan zhe", "端着" }, { "duan zheng", "端正" },
			{ "duan zhuang", "端庄" }, { "duan zi", "段子" }, { "duan zi", "端子" }, { "duan zuo", "端坐" }, { "dui", "兌" }, { "dui", "兑" }, { "dui", "堆" },
			{ "dui", "对" }, { "dui", "対" }, { "dui", "對" }, { "dui", "怼" }, { "dui", "憝" }, { "dui", "懟" }, { "dui", "搥" }, { "dui", "敦" }, { "dui", "濧" },
			{ "dui", "瀩" }, { "dui", "痽" }, { "dui", "碓" }, { "dui", "祋" }, { "dui", "薱" }, { "dui", "譈" }, { "dui", "镦" }, { "dui", "队" }, { "dui", "隊" },
			{ "dui", "頧" }, { "dui", "鴭" }, { "dui a", "对啊" }, { "dui an", "对岸" }, { "dui bai", "对白" }, { "dui ben", "对本" }, { "dui bi", "对比" },
			{ "dui bi du", "对比度" }, { "dui bu", "对不" }, { "dui bu qi", "对不起" }, { "dui bu shang", "对不上" }, { "dui bu zhu", "对不住" }, { "dui ce", "对策" },
			{ "dui ce yan jiu", "对策研究" }, { "dui chang", "对唱" }, { "dui chen", "对称" }, { "dui cheng", "对称" }, { "dui chong", "对冲" },
			{ "dui chong ji jin", "对冲基金" }, { "dui ci", "对此" }, { "dui cuo", "对错" }, { "dui dai", "对待" }, { "dui de qi", "对得起" }, { "dui di", "对敌" },
			{ "dui dui", "对对" }, { "dui e", "对俄" }, { "dui fang", "堆放" }, { "dui fang", "对方" }, { "dui fu", "兑付" }, { "dui fu", "对付" }, { "dui fu", "队服" },
			{ "dui hao ru zuo", "对号入座" }, { "dui hua", "对华" }, { "dui hua", "对话" }, { "dui hua kuang", "对话框" }, { "dui hua kuang zhong", "对话框中" },
			{ "dui huan", "兑换" }, { "dui ji", "堆积" }, { "dui jia", "对价" }, { "dui jia", "对家" }, { "dui jiang", "兑奖" }, { "dui jiang ji", "对讲机" },
			{ "dui jiao", "对焦" }, { "dui jie", "对接" }, { "dui jue", "对决" }, { "dui kang", "对抗" }, { "dui kang sai", "对抗赛" }, { "dui kou", "对口" },
			{ "dui le", "对了" }, { "dui li", "堆里" }, { "dui li", "对立" }, { "dui li", "队里" }, { "dui li mian", "对立面" }, { "dui lian", "对联" },
			{ "dui lie", "队列" }, { "dui liu", "对流" }, { "dui ma", "对吗" }, { "dui ma", "对骂" }, { "dui man", "堆满" }, { "dui me", "对么" }, { "dui mei", "对美" },
			{ "dui mei yuan", "兑美元" }, { "dui men", "对门" }, { "dui mian", "对面" }, { "dui nei", "对内" }, { "dui nei", "队内" }, { "dui ni", "对你" },
			{ "dui ni shuo", "对你说" }, { "dui nin", "对您" }, { "dui qi", "堆砌" }, { "dui qi", "对其" }, { "dui qi", "对齐" }, { "dui ren", "对人" }, { "dui ri", "对日" },
			{ "dui shi", "对视" }, { "dui shou", "对手" }, { "dui shou xi", "对手戏" }, { "dui shu", "对数" }, { "dui shui", "对谁" }, { "dui ta", "对他" },
			{ "dui ta", "对她" }, { "dui ta", "对它" }, { "dui ta shuo", "对他说" }, { "dui ta shuo", "对她说" }, { "dui tai", "对台" }, { "dui tou", "对头" },
			{ "dui wai", "对外" }, { "dui wai kai fang", "对外开放" }, { "dui wai mao yi", "对外贸易" }, { "dui wai tou zi", "对外投资" }, { "dui wai xuan chuan", "对外宣传" },
			{ "dui wo", "对我" }, { "dui wo shuo", "对我说" }, { "dui wu", "队伍" }, { "dui wu jian she", "队伍建设" }, { "dui xian", "兑现" }, { "dui xiang", "对象" },
			{ "dui xin", "对新" }, { "dui xing", "对性" }, { "dui xing", "队形" }, { "dui ya", "对呀" }, { "dui yi", "对伊" }, { "dui yi", "对已" }, { "dui ying", "对应" },
			{ "dui you", "队友" }, { "dui yu", "对于" }, { "dui yuan", "队员" }, { "dui zhan", "堆栈" }, { "dui zhan", "对战" }, { "dui zhang", "对账" },
			{ "dui zhang", "队长" }, { "dui zhang dan", "对账单" }, { "dui zhao", "对照" }, { "dui zhao zu", "对照组" }, { "dui zhe", "对折" }, { "dui zhe", "对着" },
			{ "dui zhe", "对这" }, { "dui zhen", "对阵" }, { "dui zheng", "对症" }, { "dui zheng xia yao", "对症下药" }, { "dui zhi", "对峙" }, { "dui zhong", "队中" },
			{ "dui zhun", "对准" }, { "dui zi", "对子" } };
};
