package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN02 {
	public static String[][] pl = { { "ban an", "办案" }, { "ban ban", "斑斑" }, { "ban bei", "半杯" }, { "ban bei zi", "半辈子" }, { "ban ben", "版本" },
			{ "ban ben hao", "版本号" }, { "ban bi jiang shan", "半壁江山" }, { "ban bian", "半边" }, { "ban bian tian", "半边天" }, { "ban bo", "斑驳" },
			{ "ban bu", "半步" }, { "ban bu", "颁布" }, { "ban cai", "板材" }, { "ban chan", "班禅" }, { "ban chang", "半场" }, { "ban chang", "搬场" },
			{ "ban che", "板车" }, { "ban che", "班车" }, { "ban cheng", "办成" }, { "ban cheng", "半程" }, { "ban cheng pin", "半成品" }, { "ban chu", "搬出" },
			{ "ban ci", "班次" }, { "ban dao", "办到" }, { "ban dao", "半岛" }, { "ban dao", "搬到" }, { "ban dao", "绊倒" }, { "ban dao ti", "半导体" },
			{ "ban de", "办得" }, { "ban de", "般地" }, { "ban de", "般的" }, { "ban deng", "板凳" }, { "ban di", "班底" }, { "ban dian", "半点" }, { "ban dian", "斑点" },
			{ "ban duan", "半段" }, { "ban fa", "办法" }, { "ban fa", "颁发" }, { "ban fan", "拌饭" }, { "ban fen", "半分" }, { "ban gan bu", "班干部" },
			{ "ban ge", "办个" }, { "ban ge", "半个" }, { "ban ge shi ji", "半个世纪" }, { "ban ge xiao shi", "半个小时" }, { "ban ge yue", "半个月" }, { "ban gong", "办公" },
			{ "ban gong chang suo", "办公场所" }, { "ban gong da lou", "办公大楼" }, { "ban gong di dian", "办公地点" }, { "ban gong hui", "办公会" },
			{ "ban gong jia ju", "办公家具" }, { "ban gong lou", "办公楼" }, { "ban gong qu", "办公区" }, { "ban gong ruan jian", "办公软件" },
			{ "ban gong she bei", "办公设备" }, { "ban gong shi", "办公室" }, { "ban gong si", "办公司" }, { "ban gong ting", "办公厅" }, { "ban gong yong pin", "办公用品" },
			{ "ban gong zhuo", "办公桌" }, { "ban gui", "版规" }, { "ban hao", "办好" }, { "ban hen", "瘢痕" }, { "ban hua", "版画" }, { "ban hui", "扳回" },
			{ "ban hui", "搬回" }, { "ban hui", "班会" }, { "ban ji", "扳机" }, { "ban ji", "班机" }, { "ban ji", "班级" }, { "ban jia", "半价" }, { "ban jia", "搬家" },
			{ "ban jia", "板甲" }, { "ban jia gong si", "搬家公司" }, { "ban jiang", "颁奖" }, { "ban jiang dian li", "颁奖典礼" }, { "ban jiang li", "颁奖礼" },
			{ "ban jiang yi shi", "颁奖仪式" }, { "ban jiao", "半角" }, { "ban jie", "办结" }, { "ban jie", "半截" }, { "ban jin", "半斤" }, { "ban jin", "搬进" },
			{ "ban jing", "半径" }, { "ban ju", "半句" }, { "ban jue sai", "半决赛" }, { "ban ka", "办卡" }, { "ban ka", "板卡" }, { "ban kong", "半空" },
			{ "ban kuai", "板块" }, { "ban kuai", "版块" }, { "ban lai", "搬来" }, { "ban lan", "斑斓" }, { "ban lang", "伴郎" }, { "ban le", "搬了" }, { "ban li", "办理" },
			{ "ban li", "板栗" }, { "ban li", "班里" }, { "ban lu", "半路" }, { "ban luo", "半裸" }, { "ban lv", "伴侣" }, { "ban ma", "斑马" }, { "ban mian", "版面" },
			{ "ban nian", "半年" }, { "ban nian bao", "半年报" }, { "ban niang", "伴娘" }, { "ban pei", "般配" }, { "ban ping", "半瓶" }, { "ban ping", "扳平" },
			{ "ban qi", "办起" }, { "ban qian", "搬迁" }, { "ban qiao", "板桥" }, { "ban qiu", "半球" }, { "ban qu", "搬去" }, { "ban quan", "版权" },
			{ "ban quan bao hu", "版权保护" }, { "ban quan gui", "版权归" }, { "ban quan sheng ming", "版权声明" }, { "ban quan suo you", "版权所有" },
			{ "ban quan wen ti", "版权问题" }, { "ban ri", "半日" }, { "ban ruo", "般若" }, { "ban shan", "半山" }, { "ban shan yao", "半山腰" }, { "ban shang", "半晌" },
			{ "ban shang", "搬上" }, { "ban shang", "板上" }, { "ban shang", "班上" }, { "ban shen", "半身" }, { "ban sheng", "半生" }, { "ban shi", "办事" },
			{ "ban shi", "版式" }, { "ban shi chu", "办事处" }, { "ban shi ji gou", "办事机构" }, { "ban shi shi", "办实事" }, { "ban shou", "扳手" },
			{ "ban shou xu", "办手续" }, { "ban shu", "半数" }, { "ban shu yi shang", "半数以上" }, { "ban si", "半死" }, { "ban sui", "伴随" }, { "ban tian", "半天" },
			{ "ban tu", "版图" }, { "ban tu er fei", "半途而废" }, { "ban tuo", "办妥" }, { "ban wan", "办完" }, { "ban wo", "伴我" }, { "ban wu", "版务" },
			{ "ban xia zai", "版下载" }, { "ban xian", "半仙" }, { "ban xiang", "扮相" }, { "ban xue", "办学" }, { "ban xue tiao jian", "办学条件" }, { "ban yan", "扮演" },
			{ "ban yan zhe", "扮演者" }, { "ban ye", "半夜" }, { "ban you", "伴有" }, { "ban yue", "半月" }, { "ban yun", "拌匀" }, { "ban yun", "搬运" },
			{ "ban yun gong", "搬运工" }, { "ban zai", "板载" }, { "ban zhang", "班长" }, { "ban zhe", "伴着" }, { "ban zheng", "办证" }, { "ban zhu", "斑竹" },
			{ "ban zhu", "版主" }, { "ban zhu ren", "班主任" }, { "ban zhuan", "板砖" }, { "ban zi", "板子" }, { "ban zi", "班子" }, { "ban zi cheng yuan", "班子成员" },
			{ "ban zi dong", "半自动" }, { "ban zou", "伴奏" }, { "ban zou", "搬走" }, { "ban zu", "班组" }, { "bang", "傍" }, { "bang", "垹" }, { "bang", "塝" },
			{ "bang", "峀" }, { "bang", "帮" }, { "bang", "幇" }, { "bang", "幫" }, { "bang", "搒" }, { "bang", "旁" }, { "bang", "梆" }, { "bang", "棒" },
			{ "bang", "榜" }, { "bang", "浜" }, { "bang", "玤" }, { "bang", "磅" }, { "bang", "綁" }, { "bang", "縍" }, { "bang", "绑" }, { "bang", "膀" },
			{ "bang", "艕" }, { "bang", "蒡" }, { "bang", "蚌" }, { "bang", "謗" }, { "bang", "谤" }, { "bang", "邦" }, { "bang", "鎊" }, { "bang", "镑" },
			{ "bang", "鞤" }, { "bang bang", "帮帮" }, { "bang bang", "棒棒" }, { "bang bang mang", "帮帮忙" }, { "bang bang tang", "棒棒糖" }, { "bang dan", "榜单" },
			{ "bang dao", "帮到" }, { "bang de", "邦德" }, { "bang ding", "帮顶" }, { "bang ding", "绑定" }, { "bang fei", "绑匪" }, { "bang fu", "帮扶" },
			{ "bang hui", "帮会" }, { "bang jia", "绑架" }, { "bang le", "帮了" }, { "bang mang", "帮忙" }, { "bang ni", "帮你" }, { "bang nin", "帮您" },
			{ "bang pai", "帮派" }, { "bang qiu", "棒球" }, { "bang ren", "帮人" }, { "bang shang", "榜上" }, { "bang shang you ming", "榜上有名" }, { "bang shou", "帮手" },
			{ "bang shou", "榜首" }, { "bang ta", "帮他" }, { "bang ta", "帮她" }, { "bang wan", "傍晚" }, { "bang wo", "帮我" }, { "bang xiong", "帮凶" },
			{ "bang yang", "榜样" }, { "bang zai", "绑在" }, { "bang zhe", "帮着" }, { "bang zhu", "帮主" }, { "bang zhu", "帮助" }, { "bang zhu bie ren", "帮助别人" },
			{ "bang zhu wen jian", "帮助文件" }, { "bang zhu xue sheng", "帮助学生" }, { "bang zi", "棒子" }, { "bang zi", "膀子" }, { "bao", "保" }, { "bao", "儤" },
			{ "bao", "刨" }, { "bao", "剥" }, { "bao", "勹" }, { "bao", "包" }, { "bao", "堡" }, { "bao", "報" }, { "bao", "媬" }, { "bao", "孢" }, { "bao", "宀" },
			{ "bao", "宝" }, { "bao", "寳" }, { "bao", "寶" }, { "bao", "忁" }, { "bao", "怉" }, { "bao", "报" }, { "bao", "抱" }, { "bao", "暴" }, { "bao", "曝" },
			{ "bao", "瀑" }, { "bao", "炮" }, { "bao", "煲" }, { "bao", "爆" }, { "bao", "珤" }, { "bao", "窇" }, { "bao", "笣" }, { "bao", "胞" }, { "bao", "苞" },
			{ "bao", "菢" }, { "bao", "葆" }, { "bao", "蕔" }, { "bao", "薄" }, { "bao", "虣" }, { "bao", "褒" }, { "bao", "褓" }, { "bao", "豹" }, { "bao", "趵" },
			{ "bao", "鑤" }, { "bao", "雹" }, { "bao", "靤" }, { "bao", "飹" }, { "bao", "飽" }, { "bao", "饱" }, { "bao", "駂" }, { "bao", "髱" }, { "bao", "鮑" },
			{ "bao", "鲍" }, { "bao", "鳵" }, { "bao", "鴇" }, { "bao", "鸨" }, { "bao", "齙" }, { "bao", "龅" }, { "bao an", "保安" }, { "bao an", "宝安" },
			{ "bao an", "报案" }, { "bao an qu", "宝安区" }, { "bao ban", "包办" }, { "bao bao", "包包" }, { "bao bao", "宝宝" }, { "bao bao", "抱抱" },
			{ "bao bao", "饱饱" }, { "bao bao de", "薄薄的" }, { "bao bei", "宝贝" }, { "bao bei", "报备" }, { "bao bei er", "宝贝儿" }, { "bao ben", "保本" },
			{ "bao bi", "包庇" }, { "bao biao", "保镖" }, { "bao biao", "报表" }, { "bao chai", "宝钗" }, { "bao chao", "爆炒" }, { "bao che", "包车" },
			{ "bao chi", "保持" }, { "bao chou", "报仇" }, { "bao chou", "报酬" }, { "bao chu", "报出" }, { "bao chu", "曝出" }, { "bao chu", "爆出" },
			{ "bao cun", "保存" }, { "bao cuo", "报错" }, { "bao da", "报答" }, { "bao da", "暴打" }, { "bao dan", "保单" }, { "bao dao", "宝岛" }, { "bao dao", "报到" },
			{ "bao dao", "报导" }, { "bao dao", "报道" }, { "bao di", "保底" }, { "bao di", "宝地" }, { "bao dian", "宝典" }, { "bao die", "暴跌" }, { "bao ding", "保定" },
			{ "bao ding shi", "保定市" }, { "bao dong", "暴动" }, { "bao e", "保额" }, { "bao en", "报恩" }, { "bao er", "保尔" }, { "bao er", "宝儿" },
			{ "bao er nai", "包二奶" }, { "bao fa", "暴发" }, { "bao fa", "爆发" }, { "bao fa hu", "暴发户" }, { "bao fa li", "爆发力" }, { "bao fang", "包房" },
			{ "bao fei", "保费" }, { "bao fei", "报废" }, { "bao fei shou ru", "保费收入" }, { "bao feng", "暴风" }, { "bao feng xue", "暴风雪" },
			{ "bao feng ying yin", "暴风影音" }, { "bao feng yu", "暴风雨" }, { "bao fu", "包袱" }, { "bao fu", "报复" }, { "bao fu", "抱负" }, { "bao fu", "暴富" },
			{ "bao gan", "包干" }, { "bao gang", "包钢" }, { "bao gang", "宝钢" }, { "bao gang gu fen", "宝钢股份" }, { "bao gao", "报告" }, { "bao gao hui", "报告会" },
			{ "bao gao shu", "报告书" }, { "bao gong", "包公" }, { "bao gong tou", "包工头" }, { "bao guan", "保管" }, { "bao guan", "报关" }, { "bao guan dan", "报关单" },
			{ "bao guan yuan", "报关员" }, { "bao guang", "暴光" }, { "bao guang", "曝光" }, { "bao gui", "宝贵" }, { "bao gui yi jian", "宝贵意见" }, { "bao guo", "包裹" },
			{ "bao guo", "报国" }, { "bao han", "保函" }, { "bao han", "包含" }, { "bao han", "包涵" }, { "bao han", "饱含" }, { "bao hao", "包好" }, { "bao he", "饱和" },
			{ "bao he du", "饱和度" }, { "bao hu", "保护" }, { "bao hu cuo shi", "保护措施" }, { "bao hu dong wu", "保护动物" }, { "bao hu fei", "保护费" },
			{ "bao hu gong zuo", "保护工作" }, { "bao hu hao", "保护好" }, { "bao hu huan jing", "保护环境" }, { "bao hu mo", "保护膜" }, { "bao hu qu", "保护区" },
			{ "bao hu san", "保护伞" }, { "bao hu tiao li", "保护条例" }, { "bao hu xing", "保护性" }, { "bao hu zi ji", "保护自己" }, { "bao hu zuo yong", "保护作用" },
			{ "bao huan", "包换" }, { "bao ji", "保级" }, { "bao ji", "包机" }, { "bao ji", "宝鸡" }, { "bao ji", "暴击" }, { "bao ji", "爆击" }, { "bao jia", "报价" },
			{ "bao jia dan", "报价单" }, { "bao jia hu hang", "保驾护航" }, { "bao jia li ya", "保加利亚" }, { "bao jian", "保健" }, { "bao jian", "保荐" },
			{ "bao jian", "包间" }, { "bao jian", "宝剑" }, { "bao jian", "报检" }, { "bao jian hui", "保监会" }, { "bao jian pin", "保健品" }, { "bao jian ren", "保荐人" },
			{ "bao jian shi pin", "保健食品" }, { "bao jiao zi", "包饺子" }, { "bao jie", "保洁" }, { "bao jie", "宝洁" }, { "bao jin", "抱紧" }, { "bao jing", "报警" },
			{ "bao jing qi", "报警器" }, { "bao jun", "暴君" }, { "bao kan", "报刊" }, { "bao kao", "报考" }, { "bao ku", "宝库" }, { "bao kuo", "包括" },
			{ "bao lai", "宝来" }, { "bao lan", "包揽" }, { "bao lei", "堡垒" }, { "bao leng", "爆冷" }, { "bao li", "保利" }, { "bao li", "包里" }, { "bao li", "暴利" },
			{ "bao li", "暴力" }, { "bao liao", "报料" }, { "bao liao", "爆料" }, { "bao lie", "爆裂" }, { "bao ling qiu", "保龄球" }, { "bao liu", "保留" },
			{ "bao lu", "暴露" }, { "bao lu chu", "暴露出" }, { "bao luan", "暴乱" }, { "bao luo", "保罗" }, { "bao ma", "宝马" }, { "bao ma che", "宝马车" },
			{ "bao man", "爆满" }, { "bao man", "饱满" }, { "bao mi", "保密" }, { "bao mi hua", "爆米花" }, { "bao min", "暴民" }, { "bao ming", "保命" },
			{ "bao ming", "报名" }, { "bao ming biao", "报名表" }, { "bao ming can jia", "报名参加" }, { "bao ming dian", "报名点" }, { "bao ming fei", "报名费" },
			{ "bao ming ren shu", "报名人数" }, { "bao ming shi jian", "报名时间" }, { "bao ming zhe", "报名者" }, { "bao mu", "保姆" }, { "bao nu", "暴怒" },
			{ "bao nuan", "保暖" }, { "bao pi", "包皮" }, { "bao pi", "报批" }, { "bao po", "爆破" }, { "bao qi", "抱起" }, { "bao qian", "抱歉" }, { "bao qing", "报请" },
			{ "bao quan", "保全" }, { "bao rong", "包容" }, { "bao shai", "暴晒" }, { "bao shan", "宝山" }, { "bao shang", "报上" }, { "bao she", "报社" },
			{ "bao shi", "保湿" }, { "bao shi", "宝石" }, { "bao shi jie", "保时捷" }, { "bao shou", "保守" }, { "bao shou", "报收" }, { "bao shou", "饱受" },
			{ "bao shou pai", "保守派" }, { "bao shui", "保税" }, { "bao shui", "报税" }, { "bao shui qu", "保税区" }, { "bao song", "保送" }, { "bao song", "报送" },
			{ "bao ta", "宝塔" }, { "bao tang", "煲汤" }, { "bao tou", "包头" }, { "bao tou shi", "包头市" }, { "bao tu", "暴徒" }, { "bao wei", "保卫" },
			{ "bao wei", "包围" }, { "bao wei er", "鲍威尔" }, { "bao wei zhan", "保卫战" }, { "bao wen", "保温" }, { "bao wen", "报文" }, { "bao wu", "宝物" },
			{ "bao xian", "保险" }, { "bao xian", "保鲜" }, { "bao xian fei", "保险费" }, { "bao xian gang", "保险杠" }, { "bao xian gong si", "保险公司" },
			{ "bao xian gui", "保险柜" }, { "bao xian he tong", "保险合同" }, { "bao xian jin", "保险金" }, { "bao xian mo", "保鲜膜" }, { "bao xian ren", "保险人" },
			{ "bao xian si", "保险丝" }, { "bao xian xiang", "保险箱" }, { "bao xian ye", "保险业" }, { "bao xian zi jin", "保险资金" }, { "bao xiang", "包厢" },
			{ "bao xiang", "宝箱" }, { "bao xiao", "报销" }, { "bao xiao", "爆笑" }, { "bao xing", "暴行" }, { "bao xiu", "保修" }, { "bao xiu", "报修" },
			{ "bao xiu ka", "保修卡" }, { "bao xiu qi", "保修期" }, { "bao xue", "暴雪" }, { "bao xun", "报讯" }, { "bao yan", "保研" }, { "bao yang", "保养" },
			{ "bao yang", "包养" }, { "bao yang pin", "保养品" }, { "bao ye", "包夜" }, { "bao ye", "报业" }, { "bao ye ji tuan", "报业集团" }, { "bao yi", "报以" },
			{ "bao ying", "报应" }, { "bao you", "保佑" }, { "bao you", "保有" }, { "bao you", "抱有" }, { "bao you liang", "保有量" }, { "bao yu", "保育" },
			{ "bao yu", "宝玉" }, { "bao yu", "暴雨" }, { "bao yu", "鲍鱼" }, { "bao yuan", "抱怨" }, { "bao yue", "包月" }, { "bao zai", "抱在" }, { "bao zang", "宝藏" },
			{ "bao zao", "暴躁" }, { "bao zha", "包扎" }, { "bao zha", "爆炸" }, { "bao zha an", "爆炸案" }, { "bao zha shi jian", "爆炸事件" }, { "bao zha xing", "爆炸性" },
			{ "bao zhang", "保障" }, { "bao zhang", "报章" }, { "bao zhang", "报账" }, { "bao zhang", "暴涨" }, { "bao zhang cuo shi", "保障措施" },
			{ "bao zhang ji zhi", "保障机制" }, { "bao zhang ti xi", "保障体系" }, { "bao zhang xing", "保障性" }, { "bao zhang zhi du", "保障制度" }, { "bao zhe", "包着" },
			{ "bao zhe", "抱着" }, { "bao zhe ni", "抱着你" }, { "bao zhen", "抱枕" }, { "bao zheng", "保证" }, { "bao zheng", "暴政" }, { "bao zheng jin", "保证金" },
			{ "bao zheng qi", "保证其" }, { "bao zheng shu", "保证书" }, { "bao zhi", "保值" }, { "bao zhi", "报纸" }, { "bao zhi qi", "保质期" },
			{ "bao zhi zeng zhi", "保值增值" }, { "bao zhong", "保重" }, { "bao zhong", "包中" }, { "bao zhu", "保住" }, { "bao zhu", "包住" }, { "bao zhu", "宝珠" },
			{ "bao zhu", "抱住" }, { "bao zhu", "爆竹" }, { "bao zhuang", "包装" }, { "bao zhuang cai liao", "包装材料" }, { "bao zhuang dai", "包装袋" },
			{ "bao zhuang he", "包装盒" }, { "bao zhuang ji", "包装机" }, { "bao zhuang she ji", "包装设计" }, { "bao zi", "包子" }, { "bao zi", "孢子" },
			{ "bao zi", "豹子" }, { "bao zou", "暴走" }, { "bao zuo", "宝座" }, { "bei", "倍" }, { "bei", "偝" }, { "bei", "備" }, { "bei", "北" }, { "bei", "卑" },
			{ "bei", "呗" }, { "bei", "唄" }, { "bei", "备" }, { "bei", "孛" }, { "bei", "庳" }, { "bei", "悖" }, { "bei", "悲" }, { "bei", "惫" }, { "bei", "憊" },
			{ "bei", "揹" }, { "bei", "杯" }, { "bei", "桮" }, { "bei", "梖" }, { "bei", "椑" }, { "bei", "焙" }, { "bei", "牬" }, { "bei", "犕" }, { "bei", "狈" },
			{ "bei", "狽" }, { "bei", "珼" }, { "bei", "琲" }, { "bei", "盃" }, { "bei", "碑" }, { "bei", "碚" }, { "bei", "糒" }, { "bei", "背" }, { "bei", "臂" },
			{ "bei", "蓓" }, { "bei", "藣" }, { "bei", "被" }, { "bei", "褙" }, { "bei", "襬" }, { "bei", "誖" }, { "bei", "貝" }, { "bei", "贝" }, { "bei", "輩" },
			{ "bei", "辈" }, { "bei", "邶" }, { "bei", "鄁" }, { "bei", "鋇" }, { "bei", "鐾" }, { "bei", "钡" }, { "bei", "陂" }, { "bei", "鞁" }, { "bei", "鞴" },
			{ "bei", "骳" }, { "bei", "鵯" }, { "bei", "鹎" }, { "bei ai", "悲哀" }, { "bei ai", "被爱" }, { "bei an", "北岸" }, { "bei an", "备案" },
			{ "bei ban", "背板" }, { "bei bao", "背包" }, { "bei bao xian ren", "被保险人" }, { "bei bei", "北北" }, { "bei bei", "背背" }, { "bei bei", "贝贝" },
			{ "bei bi", "卑鄙" }, { "bei bi", "被逼" }, { "bei bian", "北边" }, { "bei bu", "北部" }, { "bei bu", "背部" }, { "bei bu", "被捕" }, { "bei bu wan", "北部湾" },
			{ "bei can", "悲惨" }, { "bei ce", "北侧" }, { "bei cha", "杯茶" }, { "bei chao xian", "北朝鲜" }, { "bei chen", "北辰" }, { "bei chuan", "北川" },
			{ "bei da", "北大" }, { "bei da", "被打" }, { "bei da huang", "北大荒" }, { "bei da qing niao", "北大青鸟" }, { "bei dai he", "北戴河" },
			{ "bei dan ci", "背单词" }, { "bei dao", "被盗" }, { "bei dao er chi", "背道而驰" }, { "bei de", "倍的" }, { "bei dian", "北电" }, { "bei dong", "被动" },
			{ "bei dou", "北斗" }, { "bei dui", "背对" }, { "bei duo fen", "贝多芬" }, { "bei er", "贝尔" }, { "bei fa", "北伐" }, { "bei fa", "被罚" },
			{ "bei fang", "北方" }, { "bei fang ren", "北方人" }, { "bei fei", "北非" }, { "bei fen", "备份" }, { "bei fen", "悲愤" }, { "bei fen", "辈份" },
			{ "bei feng", "北风" }, { "bei feng", "被封" }, { "bei feng chui", "被风吹" }, { "bei fu", "背负" }, { "bei fu", "被俘" }, { "bei gan", "倍感" },
			{ "bei gao", "被告" }, { "bei gao ren", "被告人" }, { "bei guan", "悲观" }, { "bei guan", "被关" }, { "bei guang", "背光" }, { "bei guo", "北国" },
			{ "bei hai", "北海" }, { "bei hai", "被害" }, { "bei hai dao", "北海道" }, { "bei hai ren", "被害人" }, { "bei han", "北韩" }, { "bei hang", "北航" },
			{ "bei hao", "备好" }, { "bei hei", "被黑" }, { "bei hou", "背后" }, { "bei huan li he", "悲欢离合" }, { "bei hui", "被毁" }, { "bei huo", "备货" },
			{ "bei ji", "北极" }, { "bei ji xiong", "北极熊" }, { "bei jia", "倍加" }, { "bei jian", "备件" }, { "bei jiao", "北郊" }, { "bei jiao", "被叫" },
			{ "bei jie", "北街" }, { "bei jin", "被禁" }, { "bei jing", "北京" }, { "bei jing", "背景" }, { "bei jing ao yun", "北京奥运" },
			{ "bei jing che zhan", "北京车展" }, { "bei jing cheng", "北京城" }, { "bei jing da xue", "北京大学" }, { "bei jing di qu", "北京地区" },
			{ "bei jing dui", "北京队" }, { "bei jing guo ji", "北京国际" }, { "bei jing lu", "北京路" }, { "bei jing ren", "北京人" }, { "bei jing se", "背景色" },
			{ "bei jing shi", "北京市" }, { "bei jing shi chang", "北京市场" }, { "bei jing shi jian", "北京时间" }, { "bei jing shi min", "北京市民" },
			{ "bei jing xian dai", "北京现代" }, { "bei jing yi dong", "北京移动" }, { "bei jing yin hang", "北京银行" }, { "bei jing yin yue", "背景音乐" },
			{ "bei jing zhan", "北京站" }, { "bei jiu", "杯酒" }, { "bei ju", "悲剧" }, { "bei ju", "被拒" }, { "bei kan", "被砍" }, { "bei kao", "备考" },
			{ "bei kao", "背靠" }, { "bei ke", "备课" }, { "bei ke", "贝克" }, { "bei ke", "贝壳" }, { "bei ke han mu", "贝克汉姆" }, { "bei kong", "被控" },
			{ "bei kou", "被扣" }, { "bei kun", "被困" }, { "bei le", "贝勒" }, { "bei li", "背离" }, { "bei li", "贝利" }, { "bei liang", "悲凉" }, { "bei lie", "卑劣" },
			{ "bei lou", "背篓" }, { "bei lu", "北路" }, { "bei lun", "北仑" }, { "bei lun", "悖论" }, { "bei mai", "被埋" }, { "bei mei", "北美" }, { "bei men", "北门" },
			{ "bei mian", "北面" }, { "bei mian", "背面" }, { "bei min", "悲悯" }, { "bei ni", "被你" }, { "bei ou", "北欧" }, { "bei pan", "背叛" }, { "bei pan", "被判" },
			{ "bei pian", "被骗" }, { "bei piao", "北漂" }, { "bei pin", "倍频" }, { "bei ping", "北平" }, { "bei po", "被迫" }, { "bei qi", "背起" },
			{ "bei qiang", "被抢" }, { "bei qiao", "北桥" }, { "bei qing", "悲情" }, { "bei qu", "北区" }, { "bei ren", "被人" }, { "bei ren wei shi", "被认为是" },
			{ "bei ru", "被褥" }, { "bei sai", "杯赛" }, { "bei sha", "被杀" }, { "bei shan", "北山" }, { "bei shan", "被删" }, { "bei shan chu", "被删除" },
			{ "bei shang", "北上" }, { "bei shang", "悲伤" }, { "bei shang", "背上" }, { "bei shi da", "北师大" }, { "bei shou", "倍受" }, { "bei shou", "备受" },
			{ "bei shu", "倍数" }, { "bei shu", "背书" }, { "bei shui", "杯水" }, { "bei song", "北宋" }, { "bei song", "背诵" }, { "bei ta", "被他" },
			{ "bei tao", "被套" }, { "bei tong", "悲痛" }, { "bei tou", "被偷" }, { "bei tou pai", "被偷拍" }, { "bei wai", "北外" }, { "bei wang", "备忘" },
			{ "bei wang lu", "备忘录" }, { "bei wei", "北纬" }, { "bei wei", "北魏" }, { "bei wei", "卑微" }, { "bei wen", "被问" }, { "bei wo", "被我" },
			{ "bei wo", "被窝" }, { "bei xi", "悲喜" }, { "bei xia", "被吓" }, { "bei xin", "背心" }, { "bei xuan", "备选" }, { "bei xuan", "被选" }, { "bei ya", "被压" },
			{ "bei yang", "北洋" }, { "bei yi shang", "倍以上" }, { "bei ying", "背影" }, { "bei yong", "备用" }, { "bei yong jin", "备用金" }, { "bei you", "北邮" },
			{ "bei you", "备有" }, { "bei yuan", "北苑" }, { "bei yue", "北约" }, { "bei za", "被砸" }, { "bei zeng", "倍增" }, { "bei zha", "被炸" },
			{ "bei zhan", "北站" }, { "bei zhan", "备战" }, { "bei zhe", "背着" }, { "bei zhi", "被指" }, { "bei zhi xing ren", "被执行人" }, { "bei zhong", "杯中" },
			{ "bei zhu", "备注" }, { "bei zhua", "被抓" }, { "bei zhuang", "悲壮" }, { "bei zhuang", "被撞" }, { "bei zi", "杯子" }, { "bei zi", "被子" },
			{ "bei zi", "辈子" }, { "bei zi li", "被子里" }, { "ben", "坌" }, { "ben", "夯" }, { "ben", "奔" }, { "ben", "本" }, { "ben", "栟" }, { "ben", "泍" },
			{ "ben", "渀" }, { "ben", "犇" }, { "ben", "畚" }, { "ben", "笨" }, { "ben", "苯" }, { "ben", "贲" }, { "ben", "錛" }, { "ben", "锛" }, { "ben an", "本案" },
			{ "ben ban", "本版" }, { "ben ban fa", "本办法" }, { "ben bao", "本报" }, { "ben bao ji zhe", "本报记者" }, { "ben bao xun", "本报讯" }, { "ben ben", "奔奔" },
			{ "ben ben", "本本" }, { "ben ben", "苯苯" }, { "ben bi", "本币" }, { "ben bing", "本病" }, { "ben bo", "奔波" }, { "ben bu", "本部" },
			{ "ben bu men", "本部门" }, { "ben cao", "本草" }, { "ben cao gang mu", "本草纲目" }, { "ben chan pin", "本产品" }, { "ben chang", "本厂" },
			{ "ben chang", "本场" }, { "ben chang bi sai", "本场比赛" }, { "ben chi", "奔驰" }, { "ben ci", "本次" }, { "ben cun", "本村" }, { "ben dan", "笨蛋" },
			{ "ben dan wei", "本单位" }, { "ben de", "笨的" }, { "ben di", "本地" }, { "ben di hua", "本地化" }, { "ben di lian jie", "本地连接" }, { "ben di qu", "本地区" },
			{ "ben di ren", "本地人" }, { "ben di wang", "本地网" }, { "ben dian", "本店" }, { "ben fa", "本法" }, { "ben fang", "奔放" }, { "ben fang", "本方" },
			{ "ben fen", "本分" }, { "ben fu", "奔赴" }, { "ben gai", "本该" }, { "ben gong si", "本公司" }, { "ben gui ding", "本规定" }, { "ben guo", "本国" },
			{ "ben hang", "本行" }, { "ben he tong", "本合同" }, { "ben ji", "本季" }, { "ben ji", "本机" }, { "ben ji", "本级" }, { "ben ji jin", "本基金" },
			{ "ben jie", "本届" }, { "ben jie", "本节" }, { "ben jin", "本金" }, { "ben jiu", "本就" }, { "ben ju", "本剧" }, { "ben kan", "本刊" }, { "ben ke", "本科" },
			{ "ben ke bi ye", "本科毕业" }, { "ben ke sheng", "本科生" }, { "ben ke xue li", "本科学历" }, { "ben lai", "本来" }, { "ben lai jiu shi", "本来就是" },
			{ "ben lai mian mu", "本来面目" }, { "ben lan mu", "本栏目" }, { "ben ling", "本领" }, { "ben lun", "本轮" }, { "ben lun tan", "本论坛" }, { "ben ming", "本名" },
			{ "ben ming nian", "本命年" }, { "ben neng", "本能" }, { "ben nian", "本年" }, { "ben nian du", "本年度" }, { "ben pao", "奔跑" }, { "ben pian", "本片" },
			{ "ben pian", "本篇" }, { "ben pin", "本品" }, { "ben qi", "本期" }, { "ben qi ye", "本企业" }, { "ben qian", "本钱" }, { "ben qu", "奔去" },
			{ "ben qu", "本区" }, { "ben ren", "本人" }, { "ben ruan jian", "本软件" }, { "ben sai ji", "本赛季" }, { "ben se", "本色" }, { "ben shan", "本山" },
			{ "ben she qu", "本社区" }, { "ben shen", "本身" }, { "ben shen jiu shi", "本身就是" }, { "ben sheng", "本省" }, { "ben shi", "本事" }, { "ben shi", "本市" },
			{ "ben shi", "本是" }, { "ben shi ji", "本世纪" }, { "ben shu", "本书" }, { "ben suo", "本所" }, { "ben teng", "奔腾" }, { "ben ti", "本体" },
			{ "ben ti", "本题" }, { "ben tian", "本田" }, { "ben tiao", "本条" }, { "ben tiao li", "本条例" }, { "ben tie", "本帖" }, { "ben tie", "本贴" },
			{ "ben tu", "本土" }, { "ben tu hua", "本土化" }, { "ben wang", "本网" }, { "ben wang zhan", "本网站" }, { "ben wei", "本位" }, { "ben wen", "本文" },
			{ "ben wu", "本无" }, { "ben xi", "本息" }, { "ben xi", "本溪" }, { "ben xi tong", "本系统" }, { "ben xian", "本县" }, { "ben xiang", "奔向" },
			{ "ben xiang", "本想" }, { "ben xiang mu", "本项目" }, { "ben xiao", "本校" }, { "ben xiao kang", "奔小康" }, { "ben xie yi", "本协议" }, { "ben xing", "本性" },
			{ "ben xue qi", "本学期" }, { "ben ye", "本页" }, { "ben yi", "本已" }, { "ben yi", "本意" }, { "ben ying", "本应" }, { "ben yuan", "本源" },
			{ "ben yuan", "本院" }, { "ben yue", "本月" }, { "ben yue di", "本月底" }, { "ben zhan", "本站" } };
};
