package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN13 {
	public static String[][] pl = { { "fa zi nei xin", "发自内心" }, { "fa zuo", "发作" }, { "fan", "仮" }, { "fan", "凡" }, { "fan", "勫" }, { "fan", "反" },
			{ "fan", "墦" }, { "fan", "奿" }, { "fan", "嬏" }, { "fan", "帆" }, { "fan", "幡" }, { "fan", "払" }, { "fan", "攵" }, { "fan", "旙" }, { "fan", "旛" },
			{ "fan", "杋" }, { "fan", "柉" }, { "fan", "梵" }, { "fan", "樊" }, { "fan", "橎" }, { "fan", "氾" }, { "fan", "汎" }, { "fan", "泛" }, { "fan", "滼" },
			{ "fan", "瀪" }, { "fan", "瀿" }, { "fan", "烦" }, { "fan", "煩" }, { "fan", "燔" }, { "fan", "犭" }, { "fan", "犯" }, { "fan", "璠" }, { "fan", "畈" },
			{ "fan", "番" }, { "fan", "矾" }, { "fan", "礬" }, { "fan", "笲" }, { "fan", "笵" }, { "fan", "範" }, { "fan", "籵" }, { "fan", "繁" }, { "fan", "繙" },
			{ "fan", "羳" }, { "fan", "翻" }, { "fan", "膰" }, { "fan", "舩" }, { "fan", "范" }, { "fan", "蕃" }, { "fan", "薠" }, { "fan", "藩" }, { "fan", "蘩" },
			{ "fan", "蠜" }, { "fan", "販" }, { "fan", "贩" }, { "fan", "蹯" }, { "fan", "軓" }, { "fan", "軬" }, { "fan", "轓" }, { "fan", "辺" }, { "fan", "返" },
			{ "fan", "釩" }, { "fan", "鐇" }, { "fan", "钒" }, { "fan", "颿" }, { "fan", "飜" }, { "fan", "飯" }, { "fan", "饭" }, { "fan", "鱕" }, { "fan", "鷭" },
			{ "fan an", "翻案" }, { "fan ban", "翻版" }, { "fan bei", "反被" }, { "fan bei", "翻倍" }, { "fan ben", "范本" }, { "fan bing bing", "范冰冰" },
			{ "fan bing du", "反病毒" }, { "fan bo", "反驳" }, { "fan bu", "帆布" }, { "fan bu zhao", "犯不着" }, { "fan cai", "饭菜" }, { "fan cha", "反差" },
			{ "fan chang", "反常" }, { "fan chang", "翻唱" }, { "fan chao", "反超" }, { "fan chao", "翻炒" }, { "fan chen", "凡尘" }, { "fan cheng", "返程" },
			{ "fan chi", "饭吃" }, { "fan chou", "犯愁" }, { "fan chou", "范畴" }, { "fan chu", "翻出" }, { "fan chu lai", "翻出来" }, { "fan chuan", "帆船" },
			{ "fan cuo", "犯错" }, { "fan cuo wu", "犯错误" }, { "fan dao", "反倒" }, { "fan dao", "翻到" }, { "fan de sa", "范德萨" }, { "fan di gang", "梵蒂冈" },
			{ "fan dian", "返点" }, { "fan dian", "饭店" }, { "fan dong", "反动" }, { "fan dong", "翻动" }, { "fan du", "贩毒" }, { "fan dui", "反对" },
			{ "fan dui dang", "反对党" }, { "fan dui pai", "反对派" }, { "fan dui xian fa", "反对宪法" }, { "fan dui zhe", "反对者" }, { "fan duo", "繁多" },
			{ "fan er", "反而" }, { "fan fa", "犯法" }, { "fan fan", "泛泛" }, { "fan fan", "翻番" }, { "fan fan", "翻翻" }, { "fan fan", "饭饭" },
			{ "fan fan fu fu", "反反复复" }, { "fan fu", "反复" }, { "fan fu", "反腐" }, { "fan fu", "繁复" }, { "fan fu bai", "反腐败" }, { "fan fu chang lian", "反腐倡廉" },
			{ "fan fu fa zuo", "反复发作" }, { "fan gai", "翻盖" }, { "fan gan", "反感" }, { "fan gan di", "范甘迪" }, { "fan gao", "梵高" }, { "fan ge ming", "反革命" },
			{ "fan gong", "反共" }, { "fan gong", "反攻" }, { "fan gong", "返工" }, { "fan guan", "反观" }, { "fan guan", "饭馆" }, { "fan guang", "反光" },
			{ "fan gui", "犯规" }, { "fan gun", "翻滚" }, { "fan guo", "犯过" }, { "fan guo", "翻过" }, { "fan guo lai", "反过来" }, { "fan guo lai", "翻过来" },
			{ "fan he", "饭盒" }, { "fan hong", "翻红" }, { "fan hou", "饭后" }, { "fan hua", "反华" }, { "fan hua", "番话" }, { "fan hua", "繁华" }, { "fan huan", "返还" },
			{ "fan huang", "泛黄" }, { "fan hui", "反悔" }, { "fan hui", "返回" }, { "fan hui zhi", "返回值" }, { "fan ji", "反击" }, { "fan jian", "凡间" },
			{ "fan jian", "犯贱" }, { "fan ju", "饭局" }, { "fan kai", "翻开" }, { "fan kan", "翻看" }, { "fan kang", "反抗" }, { "fan kong", "反恐" },
			{ "fan kui", "反馈" }, { "fan kui xin xi", "反馈信息" }, { "fan kun", "犯困" }, { "fan lai", "翻来" }, { "fan lai fu qu", "翻来覆去" }, { "fan lan", "泛滥" },
			{ "fan lan", "泛蓝" }, { "fan le", "烦了" }, { "fan le", "犯了" }, { "fan le", "翻了" }, { "fan li", "范例" }, { "fan li", "返利" }, { "fan lian", "翻脸" },
			{ "fan liang", "饭量" }, { "fan long duan", "反垄断" }, { "fan long duan fa", "反垄断法" }, { "fan mai", "贩卖" }, { "fan mang", "繁忙" }, { "fan mei", "反美" },
			{ "fan men", "烦闷" }, { "fan mian", "反面" }, { "fan nao", "烦恼" }, { "fan ni", "范尼" }, { "fan pai", "反派" }, { "fan pai", "翻拍" }, { "fan pan", "反叛" },
			{ "fan pan", "翻盘" }, { "fan pu", "反扑" }, { "fan qi", "泛起" }, { "fan qian", "反潜" }, { "fan qian", "饭前" }, { "fan qian", "饭钱" }, { "fan qie", "番茄" },
			{ "fan qie", "蕃茄" }, { "fan qie hua yuan", "番茄花园" }, { "fan qie jiang", "番茄酱" }, { "fan qing", "烦请" }, { "fan qing xiao", "反倾销" },
			{ "fan ren", "凡人" }, { "fan ren", "烦人" }, { "fan ren", "犯人" }, { "fan ri", "反日" }, { "fan rong", "繁荣" }, { "fan she", "反射" }, { "fan shen", "翻身" },
			{ "fan sheng", "繁盛" }, { "fan shi", "凡事" }, { "fan shi", "凡是" }, { "fan shi", "范式" }, { "fan shou", "反手" }, { "fan shu", "番薯" },
			{ "fan shu", "翻书" }, { "fan si", "反思" }, { "fan suo", "烦琐" }, { "fan suo", "繁琐" }, { "fan tan", "反弹" }, { "fan tan", "反贪" }, { "fan tang", "饭堂" },
			{ "fan teng", "翻腾" }, { "fan ti", "繁体" }, { "fan ti zi", "繁体字" }, { "fan tian fu di", "翻天覆地" }, { "fan tong", "饭桶" }, { "fan tuan", "饭团" },
			{ "fan wan", "饭碗" }, { "fan wei", "反胃" }, { "fan wei", "范伟" }, { "fan wei", "范围" }, { "fan wei qi", "范玮琪" }, { "fan wei zhi nei", "范围之内" },
			{ "fan wen", "反问" }, { "fan wen", "范文" }, { "fan xi qian", "反洗钱" }, { "fan xia", "犯下" }, { "fan xian", "范县" }, { "fan xiang", "反向" },
			{ "fan xiang", "反响" }, { "fan xiang", "返乡" }, { "fan xiao", "返校" }, { "fan xiao xuan", "范晓萱" }, { "fan xin", "烦心" }, { "fan xin", "翻新" },
			{ "fan xing", "反省" }, { "fan xing", "繁星" }, { "fan xiu", "返修" }, { "fan yan", "繁衍" }, { "fan ye", "翻页" }, { "fan yi", "翻译" },
			{ "fan yi cheng", "翻译成" }, { "fan yi gong si", "翻译公司" }, { "fan yin", "翻印" }, { "fan ying", "反应" }, { "fan ying", "反映" },
			{ "fan ying chu", "反映出" }, { "fan ying dui", "反应堆" }, { "fan ying qi", "反应器" }, { "fan ying su du", "反应速度" }, { "fan yu", "繁育" },
			{ "fan yue", "翻越" }, { "fan yue", "翻阅" }, { "fan za", "繁杂" }, { "fan zai", "凡在" }, { "fan zao", "烦躁" }, { "fan zhan", "反战" }, { "fan zhe", "泛着" },
			{ "fan zhe", "翻着" }, { "fan zhen", "反震" }, { "fan zheng", "反正" }, { "fan zheng fu", "反政府" }, { "fan zhi", "反之" }, { "fan zhi", "反制" },
			{ "fan zhi", "泛指" }, { "fan zhi", "繁殖" }, { "fan zhi yi", "范志毅" }, { "fan zhong", "繁重" }, { "fan zhu san jiao", "泛珠三角" }, { "fan zhuan", "反转" },
			{ "fan zhuan", "翻转" }, { "fan zhuo", "饭桌" }, { "fan zi", "贩子" }, { "fan zui", "犯罪" }, { "fan zui an jian", "犯罪案件" }, { "fan zui fen zi", "犯罪分子" },
			{ "fan zui xing wei", "犯罪行为" }, { "fan zuo yong", "反作用" }, { "fang", "仿" }, { "fang", "倣" }, { "fang", "坊" }, { "fang", "妨" }, { "fang", "彷" },
			{ "fang", "房" }, { "fang", "放" }, { "fang", "方" }, { "fang", "昉" }, { "fang", "昞" }, { "fang", "枋" }, { "fang", "淓" }, { "fang", "瓬" },
			{ "fang", "紡" }, { "fang", "纺" }, { "fang", "肪" }, { "fang", "舫" }, { "fang", "芳" }, { "fang", "訪" }, { "fang", "访" }, { "fang", "邡" },
			{ "fang", "鈁" }, { "fang", "錺" }, { "fang", "钫" }, { "fang", "防" }, { "fang", "髣" }, { "fang", "魴" }, { "fang", "鲂" }, { "fang", "鶭" },
			{ "fang ai", "妨碍" }, { "fang an", "方案" }, { "fang an she ji", "方案设计" }, { "fang bao", "防爆" }, { "fang bei", "防备" }, { "fang bian", "方便" },
			{ "fang bian kuai jie", "方便快捷" }, { "fang bian mian", "方便面" }, { "fang bing", "防病" }, { "fang bing du", "防病毒" }, { "fang bu sheng fang", "防不胜防" },
			{ "fang bu xia", "放不下" }, { "fang cai", "方才" }, { "fang cao", "芳草" }, { "fang cha", "方差" }, { "fang chan", "房产" }, { "fang chan shang", "房产商" },
			{ "fang chan zheng", "房产证" }, { "fang chan zhong jie", "房产中介" }, { "fang chao", "防潮" }, { "fang che", "房车" }, { "fang chen", "防尘" },
			{ "fang chen mi", "防沉迷" }, { "fang cheng", "方程" }, { "fang cheng shi", "方程式" }, { "fang chu", "放出" }, { "fang cun", "方寸" }, { "fang cun", "芳村" },
			{ "fang da", "放大" }, { "fang da jing", "放大镜" }, { "fang da qi", "放大器" }, { "fang dai", "房贷" }, { "fang dai", "放贷" }, { "fang dang", "放荡" },
			{ "fang dao", "放倒" }, { "fang dao", "放到" }, { "fang dao", "防盗" }, { "fang dao men", "防盗门" }, { "fang di", "房地" }, { "fang di", "放低" },
			{ "fang di chan", "房地产" }, { "fang di chan shang", "房地产商" }, { "fang di chan ye", "房地产业" }, { "fang dian", "放点" }, { "fang dian", "放电" },
			{ "fang diao", "放掉" }, { "fang ding", "房顶" }, { "fang dong", "房东" }, { "fang dou", "防抖" }, { "fang du", "防毒" }, { "fang fa", "方法" },
			{ "fang fa lai", "方法来" }, { "fang fa lun", "方法论" }, { "fang fa yan jiu", "方法研究" }, { "fang fan", "防范" }, { "fang fan cuo shi", "防范措施" },
			{ "fang fang", "方方" }, { "fang fang", "芳芳" }, { "fang fang mian mian", "方方面面" }, { "fang fei", "房费" }, { "fang fei", "放飞" }, { "fang fei", "芳菲" },
			{ "fang feng", "防风" }, { "fang feng zheng", "放风筝" }, { "fang fu", "仿佛" }, { "fang fu", "防腐" }, { "fang fu ji", "防腐剂" }, { "fang fu she", "防辐射" },
			{ "fang ge", "放个" }, { "fang ge", "放歌" }, { "fang ge", "方格" }, { "fang gu", "仿古" }, { "fang guan", "房管" }, { "fang guan ju", "房管局" },
			{ "fang guang", "放光" }, { "fang guo", "放过" }, { "fang hao", "放号" }, { "fang hao", "放好" }, { "fang hong", "防洪" }, { "fang hu", "防护" },
			{ "fang hua", "芳华" }, { "fang hua", "访华" }, { "fang hua", "防滑" }, { "fang huan", "放缓" }, { "fang hui", "放回" }, { "fang huo", "放火" },
			{ "fang huo", "防火" }, { "fang huo qiang", "防火墙" }, { "fang jia", "房价" }, { "fang jia", "放假" }, { "fang jia xia die", "房价下跌" },
			{ "fang jian", "坊间" }, { "fang jian", "房间" }, { "fang jian li", "房间里" }, { "fang jiao hui", "房交会" }, { "fang jin", "放进" },
			{ "fang jing dian", "防静电" }, { "fang kai", "放开" }, { "fang ke", "房客" }, { "fang ke", "方可" }, { "fang ke", "访客" }, { "fang kong", "防控" },
			{ "fang kong", "防空" }, { "fang kuai", "方块" }, { "fang kuan", "房款" }, { "fang kuan", "放宽" }, { "fang kuan", "放款" }, { "fang kuang", "方框" },
			{ "fang lei", "防雷" }, { "fang li", "房里" }, { "fang liang", "放量" }, { "fang liao", "放疗" }, { "fang lue", "方略" }, { "fang man", "放慢" },
			{ "fang mao", "仿冒" }, { "fang mei", "访美" }, { "fang men", "房门" }, { "fang mian", "方面" }, { "fang mian jun", "方面军" }, { "fang mu", "放牧" },
			{ "fang nei", "房内" }, { "fang neng", "方能" }, { "fang pao", "放炮" }, { "fang pi", "放屁" }, { "fang qi", "放弃" }, { "fang ren", "放人" },
			{ "fang ren", "放任" }, { "fang ru", "放入" }, { "fang shai", "防晒" }, { "fang shai shuang", "防晒霜" }, { "fang shan", "房山" }, { "fang shang", "放上" },
			{ "fang shang qu", "放上去" }, { "fang she", "放射" }, { "fang she xing", "放射性" }, { "fang shen", "防身" }, { "fang sheng", "放声" },
			{ "fang sheng", "放生" }, { "fang shi", "房事" }, { "fang shi", "房市" }, { "fang shi", "方式" }, { "fang shi fang fa", "方式方法" }, { "fang shou", "放手" },
			{ "fang shou", "防守" }, { "fang shu jia", "放暑假" }, { "fang shui", "放水" }, { "fang shui", "防水" }, { "fang si", "放肆" }, { "fang song", "放松" },
			{ "fang song", "放送" }, { "fang tan", "访谈" }, { "fang wan", "放完" }, { "fang wei", "方位" }, { "fang wei", "防伪" }, { "fang wei", "防卫" },
			{ "fang wen", "访问" }, { "fang wen liang", "访问量" }, { "fang wen zhe", "访问者" }, { "fang wu", "房屋" }, { "fang wu", "防务" },
			{ "fang wu chai qian", "房屋拆迁" }, { "fang wu zu lin", "房屋租赁" }, { "fang xia", "放下" }, { "fang xian", "防线" }, { "fang xiang", "方向" },
			{ "fang xiang", "芳香" }, { "fang xiang jian", "方向键" }, { "fang xiang pan", "方向盘" }, { "fang xiang xing", "方向性" }, { "fang xiao", "仿效" },
			{ "fang xin", "放心" }, { "fang xin", "芳心" }, { "fang xing", "房型" }, { "fang xing", "放行" }, { "fang xing", "方形" }, { "fang xing wei ai", "方兴未艾" },
			{ "fang xue", "放学" }, { "fang xun", "防汛" }, { "fang yan", "放眼" }, { "fang yan", "方言" }, { "fang yang", "放养" }, { "fang yang", "放羊" },
			{ "fang yi", "防疫" }, { "fang ying", "放映" }, { "fang yu", "防御" }, { "fang yuan", "房源" }, { "fang yuan", "方圆" }, { "fang zai", "放在" },
			{ "fang zai", "防灾" }, { "fang zai xin shang", "放在心上" }, { "fang zai yan li", "放在眼里" }, { "fang zai yi qi", "放在一起" }, { "fang zao", "仿造" },
			{ "fang zhan", "房展" }, { "fang zhang", "方丈" }, { "fang zhao", "仿照" }, { "fang zhe", "放着" }, { "fang zhen", "仿真" }, { "fang zhen", "方针" },
			{ "fang zhen", "方阵" }, { "fang zhen", "防震" }, { "fang zhen zheng ce", "方针政策" }, { "fang zheng", "方正" }, { "fang zheng ke ji", "方正科技" },
			{ "fang zhi", "仿制" }, { "fang zhi", "放置" }, { "fang zhi", "方知" }, { "fang zhi", "纺织" }, { "fang zhi", "防止" }, { "fang zhi", "防治" },
			{ "fang zhi fu zhuang", "纺织服装" }, { "fang zhi gong zuo", "防治工作" }, { "fang zhi pin", "纺织品" }, { "fang zhi ye", "纺织业" }, { "fang zhong", "房中" },
			{ "fang zhou", "方舟" }, { "fang zhou zi", "方舟子" }, { "fang zhu", "房主" }, { "fang zhu", "放逐" }, { "fang zhuang", "方庄" }, { "fang zi", "房子" },
			{ "fang zi", "方子" }, { "fang zi li", "房子里" }, { "fang zong", "放纵" }, { "fang zu", "房租" }, { "fei", "俷" }, { "fei", "剕" }, { "fei", "匪" },
			{ "fei", "厞" }, { "fei", "吠" }, { "fei", "啡" }, { "fei", "奜" }, { "fei", "妃" }, { "fei", "婓" }, { "fei", "屝" }, { "fei", "废" }, { "fei", "廃" },
			{ "fei", "廢" }, { "fei", "怫" }, { "fei", "悱" }, { "fei", "扉" }, { "fei", "斐" }, { "fei", "昲" }, { "fei", "暃" }, { "fei", "曊" }, { "fei", "棐" },
			{ "fei", "榧" }, { "fei", "櫠" }, { "fei", "沸" }, { "fei", "淝" }, { "fei", "濷" }, { "fei", "狒" }, { "fei", "疿" }, { "fei", "痱" }, { "fei", "癈" },
			{ "fei", "篚" }, { "fei", "緋" }, { "fei", "绯" }, { "fei", "翡" }, { "fei", "肥" }, { "fei", "肺" }, { "fei", "胇" }, { "fei", "腓" }, { "fei", "芾" },
			{ "fei", "菲" }, { "fei", "蜚" }, { "fei", "蜰" }, { "fei", "蟦" }, { "fei", "裶" }, { "fei", "襏" }, { "fei", "誹" }, { "fei", "诽" }, { "fei", "費" },
			{ "fei", "费" }, { "fei", "鐨" }, { "fei", "镄" }, { "fei", "霏" }, { "fei", "非" }, { "fei", "飛" }, { "fei", "飞" }, { "fei", "餥" }, { "fei", "馡" },
			{ "fei", "騑" }, { "fei", "騛" }, { "fei", "鯡" }, { "fei", "鲱" }, { "fei", "鼣" }, { "fei ai", "肺癌" }, { "fei bang", "诽谤" }, { "fei ben", "飞奔" },
			{ "fei bu", "肺部" }, { "fei chai", "废柴" }, { "fei chang", "非常" }, { "fei chang bu cuo", "非常不错" }, { "fei chang da", "非常大" },
			{ "fei chang fang bian", "非常方便" }, { "fei chang gan xie", "非常感谢" }, { "fei chang hao", "非常好" }, { "fei chang piao liang", "非常漂亮" },
			{ "fei chang xi huan", "非常喜欢" }, { "fei chang zhong shi", "非常重视" }, { "fei chang zhong yao", "非常重要" }, { "fei che", "飞车" }, { "fei cheng", "费城" },
			{ "fei chi", "飞驰" }, { "fei chu", "废除" }, { "fei chu", "非处" }, { "fei chu", "飞出" }, { "fei chuan", "飞船" }, { "fei cui", "翡翠" }, { "fei da", "肥大" },
			{ "fei dan", "非但" }, { "fei dan", "飞弹" }, { "fei dao", "飞刀" }, { "fei dao", "飞到" }, { "fei de", "飞得" }, { "fei de le", "费德勒" },
			{ "fei dei", "非得" }, { "fei di", "飞抵" }, { "fei dian", "沸点" }, { "fei dian", "非典" }, { "fei dian xing", "非典型" }, { "fei diao", "废掉" },
			{ "fei die", "飞碟" }, { "fei du", "飞度" }, { "fei e", "飞蛾" }, { "fei er", "菲儿" }, { "fei er", "菲尔" }, { "fei er", "费尔" }, { "fei er", "飞儿" },
			{ "fei fa", "非法" }, { "fei fan", "霏凡" }, { "fei fan", "非凡" }, { "fei fei", "狒狒" }, { "fei fei", "肥肥" }, { "fei fei", "菲菲" }, { "fei fei", "霏霏" },
			{ "fei fei", "飞飞" }, { "fei fei yang yang", "沸沸扬扬" }, { "fei fu", "肺腑" }, { "fei ge", "菲戈" }, { "fei ge", "飞鸽" }, { "fei gong kai", "非公开" },
			{ "fei gong you zhi", "非公有制" }, { "fei guan fang", "非官方" }, { "fei guo", "飞过" }, { "fei hong", "绯红" }, { "fei hong", "飞鸿" }, { "fei hou", "肥厚" },
			{ "fei hu", "飞狐" }, { "fei hua", "废话" }, { "fei hua", "飞花" }, { "fei hui", "飞回" }, { "fei ji", "飞机" }, { "fei ji chang", "飞机场" },
			{ "fei ji dong che", "非机动车" }, { "fei ji piao", "飞机票" }, { "fei jian", "飞溅" }, { "fei jie", "肥姐" }, { "fei jie", "费解" }, { "fei jie he", "肺结核" },
			{ "fei jin", "费劲" }, { "fei jin", "费尽" }, { "fei jiu", "废旧" }, { "fei kuai", "飞快" }, { "fei lai", "飞来" }, { "fei lai fei qu", "飞来飞去" },
			{ "fei le", "废了" }, { "fei li", "费力" }, { "fei li", "非礼" }, { "fei li pu", "菲利普" }, { "fei li pu", "飞利浦" }, { "fei li xing", "非理性" },
			{ "fei liao", "废料" }, { "fei liao", "肥料" }, { "fei liu tong gu", "非流通股" }, { "fei long", "飞龙" }, { "fei lun hai", "飞轮海" }, { "fei lv", "费率" },
			{ "fei lv bin", "菲律宾" }, { "fei mao tui", "飞毛腿" }, { "fei niao", "飞鸟" }, { "fei nong", "非农" }, { "fei pang", "肥胖" }, { "fei pin", "废品" },
			{ "fei qi", "废弃" }, { "fei qi", "废气" }, { "fei qi", "飞起" }, { "fei qi lai", "飞起来" }, { "fei qi wu", "废弃物" }, { "fei qian", "费钱" },
			{ "fei qu", "飞去" }, { "fei ren", "废人" }, { "fei ren", "非人" }, { "fei ren", "飞人" }, { "fei rou", "肥肉" }, { "fei shang", "飞上" },
			{ "fei shen", "飞身" }, { "fei sheng", "飞升" }, { "fei shi", "费事" }, { "fei shi", "费时" }, { "fei shi", "飞逝" }, { "fei shui", "废水" },
			{ "fei shui", "沸水" }, { "fei shui", "肥水" }, { "fei su", "飞速" }, { "fei su fa zhan", "飞速发展" }, { "fei teng", "沸腾" }, { "fei tian", "飞天" },
			{ "fei ting", "飞艇" }, { "fei tong xun chang", "非同寻常" }, { "fei tong yi ban", "非同一般" }, { "fei tu", "匪徒" }, { "fei wang", "飞往" },
			{ "fei wen", "绯闻" }, { "fei wo", "肥沃" }, { "fei wu", "废物" }, { "fei wu", "飞舞" }, { "fei wu zhi", "非物质" }, { "fei xian xing", "非线性" },
			{ "fei xiang", "飞向" }, { "fei xiang", "飞翔" }, { "fei xin", "费心" }, { "fei xing", "飞行" }, { "fei xing qi", "飞行器" }, { "fei xing yuan", "飞行员" },
			{ "fei xu", "废墟" }, { "fei xue", "飞雪" }, { "fei ya te", "菲亚特" }, { "fei yan", "肺炎" }, { "fei yan", "飞燕" }, { "fei yang", "飞扬" },
			{ "fei yao", "非要" }, { "fei yi", "非议" }, { "fei yi suo si", "匪夷所思" }, { "fei ying", "飞鹰" }, { "fei yong", "费用" }, { "fei yu", "飞鱼" },
			{ "fei yue", "飞越" }, { "fei yue", "飞跃" }, { "fei yun", "飞云" }, { "fei zao", "肥皂" }, { "fei zao ju", "肥皂剧" }, { "fei zhang", "飞涨" },
			{ "fei zheng chang", "非正常" }, { "fei zheng shi", "非正式" }, { "fei zhi", "废止" }, { "fei zhi", "废纸" }, { "fei zhou", "非洲" },
			{ "fei zhou guo jia", "非洲国家" }, { "fei zhu", "肥猪" }, { "fei zhu liu", "非主流" }, { "fei zhuan ye", "非专业" }, { "fei zi", "妃子" }, { "fei zi", "痱子" },
			{ "fei zou", "飞走" }, { "fen", "份" }, { "fen", "偾" }, { "fen", "僨" }, { "fen", "分" }, { "fen", "吩" }, { "fen", "坋" }, { "fen", "坟" },
			{ "fen", "墳" }, { "fen", "奋" }, { "fen", "奮" }, { "fen", "妢" }, { "fen", "幩" }, { "fen", "弅" }, { "fen", "忿" }, { "fen", "愤" }, { "fen", "憤" },
			{ "fen", "昐" }, { "fen", "枌" }, { "fen", "梤" }, { "fen", "棻" }, { "fen", "棼" }, { "fen", "橨" }, { "fen", "氛" }, { "fen", "汾" }, { "fen", "濆" },
			{ "fen", "瀵" }, { "fen", "炃" }, { "fen", "焚" }, { "fen", "玢" }, { "fen", "秎" }, { "fen", "竕" }, { "fen", "粉" }, { "fen", "粪" }, { "fen", "糞" },
			{ "fen", "紛" }, { "fen", "纷" }, { "fen", "羒" }, { "fen", "羵" }, { "fen", "翂" }, { "fen", "膹" }, { "fen", "芬" }, { "fen", "蒶" }, { "fen", "蕡" },
			{ "fen", "蚡" }, { "fen", "豶" }, { "fen", "轒" }, { "fen", "酚" }, { "fen", "鈖" }, { "fen", "鐼" }, { "fen", "雰" }, { "fen", "饙" }, { "fen", "魵" },
			{ "fen", "鲼" }, { "fen", "鳻" }, { "fen", "黂" }, { "fen", "黺" }, { "fen", "鼖" }, { "fen", "鼢" }, { "fen ban", "分班" }, { "fen bao", "分包" },
			{ "fen bei", "分贝" }, { "fen bi", "粉笔" }, { "fen bian", "分辨" }, { "fen bian", "粪便" }, { "fen bian lv", "分辨率" }, { "fen bian lv wei", "分辨率为" },
			{ "fen bie", "分别" }, { "fen bing", "粉饼" }, { "fen bu", "分布" }, { "fen bu", "分步" }, { "fen bu", "分部" }, { "fen bu gu shen", "奋不顾身" },
			{ "fen bu kai", "分不开" }, { "fen bu qing", "分不清" }, { "fen bu shi", "分布式" }, { "fen bu tu", "分布图" }, { "fen ceng", "分层" }, { "fen cha", "分叉" },
			{ "fen chai", "分拆" }, { "fen chang", "分厂" }, { "fen chen", "粉尘" }, { "fen cheng", "分成" }, { "fen chu", "分出" }, { "fen ci", "分词" },
			{ "fen ci", "粉刺" }, { "fen cun", "分寸" }, { "fen dan", "分担" }, { "fen dao", "分到" }, { "fen dao yang biao", "分道扬镳" }, { "fen de", "分得" },
			{ "fen di", "粉底" }, { "fen dian", "分店" }, { "fen dou", "奋斗" }, { "fen dou mu biao", "奋斗目标" }, { "fen duan", "分段" }, { "fen dui", "分队" },
			{ "fen e", "份额" }, { "fen er", "份儿" }, { "fen fa", "分发" }, { "fen fa", "分法" }, { "fen fan", "纷繁" }, { "fen fang", "芬芳" }, { "fen fei", "纷飞" },
			{ "fen fen", "分分" }, { "fen fen", "愤愤" }, { "fen fen", "粉粉" }, { "fen fen", "纷纷" }, { "fen fen bu ping", "愤愤不平" }, { "fen fu", "吩咐" },
			{ "fen ge", "分割" }, { "fen ge", "分隔" }, { "fen ge xian", "分割线" }, { "fen gei", "分给" }, { "fen gong", "分工" }, { "fen gong si", "分公司" },
			{ "fen guan", "分管" }, { "fen hang", "分行" }, { "fen hao", "分号" }, { "fen hen", "愤恨" }, { "fen hong", "分红" }, { "fen hong", "粉红" },
			{ "fen hong se", "粉红色" }, { "fen hu", "分户" }, { "fen hua", "分化" }, { "fen hui", "分会" }, { "fen hui chang", "分会场" }, { "fen ji", "分机" },
			{ "fen ji", "分级" }, { "fen jia", "分家" }, { "fen jie", "分解" }, { "fen jie duan", "分阶段" }, { "fen jie xian", "分界线" }, { "fen jin", "奋进" },
			{ "fen ju", "分局" }, { "fen ju", "分居" }, { "fen kai", "分开" }, { "fen kai", "愤慨" }, { "fen lan", "芬兰" }, { "fen lei", "分类" },
			{ "fen lei xin xi", "分类信息" }, { "fen li", "分离" }, { "fen li", "分立" }, { "fen li", "奋力" }, { "fen li chu", "分理处" }, { "fen liang", "份量" },
			{ "fen liang", "分量" }, { "fen lie", "分列" }, { "fen lie", "分裂" }, { "fen liu", "分流" }, { "fen luan", "纷乱" }, { "fen mei hui", "粉煤灰" },
			{ "fen mi", "分泌" }, { "fen mi wu", "分泌物" }, { "fen mian", "分娩" }, { "fen ming", "分明" }, { "fen mo", "粉末" }, { "fen mu", "坟墓" },
			{ "fen nen", "粉嫩" }, { "fen nu", "愤怒" }, { "fen pai", "分派" }, { "fen pei", "分配" }, { "fen pi", "分批" }, { "fen qi", "分期" }, { "fen qi", "分歧" },
			{ "fen qi", "奋起" }, { "fen qi fu kuan", "分期付款" }, { "fen qian", "分钱" }, { "fen qing", "分清" }, { "fen qing", "愤青" }, { "fen qu", "分区" },
			{ "fen qu biao", "分区表" }, { "fen quan", "分权" }, { "fen ran", "愤然" }, { "fen san", "分散" }, { "fen se", "粉色" }, { "fen shang", "份上" },
			{ "fen shao", "焚烧" }, { "fen she", "分社" }, { "fen shen", "分身" }, { "fen shi", "分时" }, { "fen shi", "粉饰" }, { "fen shou", "分手" },
			{ "fen shu", "分数" }, { "fen shu xian", "分数线" }, { "fen shua", "粉刷" }, { "fen shui ling", "分水岭" }, { "fen si", "粉丝" }, { "fen si men", "粉丝们" },
			{ "fen sui", "粉碎" }, { "fen tan", "分摊" }, { "fen tou", "分头" }, { "fen wai", "分外" }, { "fen wei", "分为" }, { "fen wei", "氛围" }, { "fen xi", "分析" },
			{ "fen xi bao gao", "分析报告" }, { "fen xi fa", "分析法" }, { "fen xi fang fa", "分析方法" }, { "fen xi jia", "分析家" }, { "fen xi shi", "分析师" },
			{ "fen xi wen ti", "分析问题" }, { "fen xi yan jiu", "分析研究" }, { "fen xi yi", "分析仪" }, { "fen xiang", "分享" }, { "fen xiang", "分项" },
			{ "fen xiao", "分校" }, { "fen xiao", "分销" }, { "fen xiao shang", "分销商" }, { "fen xin", "分心" }, { "fen xing", "分形" }, { "fen ye", "分页" },
			{ "fen yi shang", "分以上" }, { "fen yong", "奋勇" }, { "fen yuan", "分院" }, { "fen zhan", "分站" }, { "fen zhan", "奋战" }, { "fen zheng", "纷争" },
			{ "fen zhi", "分值" }, { "fen zhi", "分支" }, { "fen zhi ji gou", "分支机构" }, { "fen zhi ta lai", "纷至沓来" }, { "fen zhi yi", "分之一" },
			{ "fen zhong", "分众" }, { "fen zhong", "分钟" }, { "fen zhong xin", "分中心" }, { "fen zi", "份子" }, { "fen zi", "分子" }, { "fen zi liang", "分子量" },
			{ "fen zu", "分组" }, { "fen zuo you", "分左右" } };
};
