package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN27 {
	public static String[][] pl = { { "kou", "冦" }, { "kou", "口" }, { "kou", "叩" }, { "kou", "寇" }, { "kou", "彄" }, { "kou", "怐" }, { "kou", "扣" },
			{ "kou", "抠" }, { "kou", "摳" }, { "kou", "滱" }, { "kou", "眍" }, { "kou", "瞉" }, { "kou", "筘" }, { "kou", "簆" }, { "kou", "芤" }, { "kou", "蔻" },
			{ "kou", "釦" }, { "kou", "鷇" }, { "kou an", "口岸" }, { "kou bei", "口碑" }, { "kou cai", "口才" }, { "kou chi", "口吃" }, { "kou chou", "口臭" },
			{ "kou chu", "扣除" }, { "kou dai", "口袋" }, { "kou dai li", "口袋里" }, { "kou diao", "扣掉" }, { "kou fen", "扣分" }, { "kou fu", "口服" },
			{ "kou fu", "口福" }, { "kou fu ye", "口服液" }, { "kou gan", "口干" }, { "kou gan", "口感" }, { "kou gong", "口供" }, { "kou hao", "口号" },
			{ "kou hong", "口红" }, { "kou jiao", "口交" }, { "kou jiao", "口角" }, { "kou jing", "口径" }, { "kou jue", "口诀" }, { "kou ke", "口渴" },
			{ "kou kou", "口口" }, { "kou kou sheng sheng", "口口声声" }, { "kou kuan", "扣款" }, { "kou lan", "扣篮" }, { "kou li", "口里" }, { "kou liang", "口粮" },
			{ "kou ling", "口令" }, { "kou liu", "扣留" }, { "kou men", "抠门" }, { "kou qi", "口气" }, { "kou qian", "扣钱" }, { "kou qiang", "口腔" },
			{ "kou qiang kui yang", "口腔溃疡" }, { "kou qin", "口琴" }, { "kou rou", "扣肉" }, { "kou shang", "扣上" }, { "kou shao", "口哨" }, { "kou she", "口舌" },
			{ "kou shi", "口试" }, { "kou shu", "口述" }, { "kou shui", "口水" }, { "kou shui", "扣税" }, { "kou shui zhan", "口水战" }, { "kou tou", "口头" },
			{ "kou tou chan", "口头禅" }, { "kou wei", "口味" }, { "kou wen", "口吻" }, { "kou xiang tang", "口香糖" }, { "kou ya", "扣押" }, { "kou yi", "口译" },
			{ "kou yin", "口音" }, { "kou yu", "口语" }, { "kou zhao", "口罩" }, { "kou zhen", "口镇" }, { "kou zhong", "口中" }, { "kou zi", "口子" }, { "kou zi", "扣子" },
			{ "ku", "刳" }, { "ku", "哭" }, { "ku", "喾" }, { "ku", "嚳" }, { "ku", "堀" }, { "ku", "库" }, { "ku", "庫" }, { "ku", "捁" }, { "ku", "搰" },
			{ "ku", "朏" }, { "ku", "枯" }, { "ku", "桍" }, { "ku", "楛" }, { "ku", "狜" }, { "ku", "瘔" }, { "ku", "矻" }, { "ku", "窟" }, { "ku", "绔" },
			{ "ku", "胐" }, { "ku", "苦" }, { "ku", "袴" }, { "ku", "裤" }, { "ku", "褲" }, { "ku", "跍" }, { "ku", "酷" }, { "ku", "骷" }, { "ku ai", "酷爱" },
			{ "ku ba", "哭吧" }, { "ku bu kan yan", "苦不堪言" }, { "ku cha", "裤衩" }, { "ku cun", "库存" }, { "ku dang", "裤裆" }, { "ku de", "哭得" }, { "ku du", "苦读" },
			{ "ku er de", "库尔德" }, { "ku fang", "库房" }, { "ku gou", "酷狗" }, { "ku gua", "苦瓜" }, { "ku guo", "哭过" }, { "ku guo", "苦果" }, { "ku hai", "苦海" },
			{ "ku han", "哭喊" }, { "ku huang", "枯黄" }, { "ku jie", "枯竭" }, { "ku kou po xin", "苦口婆心" }, { "ku ku", "苦苦" }, { "ku ku", "酷酷" }, { "ku le", "苦了" },
			{ "ku li", "库里" }, { "ku li", "苦力" }, { "ku lian", "苦练" }, { "ku long", "窟窿" }, { "ku lou", "骷髅" }, { "ku men", "苦闷" }, { "ku ming", "苦命" },
			{ "ku nan", "苦难" }, { "ku nao", "哭闹" }, { "ku nao", "苦恼" }, { "ku pai", "酷派" }, { "ku ping", "酷评" }, { "ku qi", "哭泣" }, { "ku qu", "库区" },
			{ "ku re", "酷热" }, { "ku rui", "酷睿" }, { "ku se", "苦涩" }, { "ku sheng", "哭声" }, { "ku shu", "酷暑" }, { "ku si", "酷似" }, { "ku su", "哭诉" },
			{ "ku tong", "苦痛" }, { "ku tou", "苦头" }, { "ku wang", "酷网" }, { "ku wei", "枯萎" }, { "ku wei", "苦味" }, { "ku xiao", "苦笑" },
			{ "ku xiao bu de", "哭笑不得" }, { "ku xin", "苦心" }, { "ku xing", "酷刑" }, { "ku ye", "枯叶" }, { "ku yu", "苦于" }, { "ku zao", "枯燥" },
			{ "ku zhan", "苦战" }, { "ku zhe", "哭着" }, { "ku zhong", "库中" }, { "ku zhong", "苦衷" }, { "ku zi", "裤子" }, { "kua", "侉" }, { "kua", "垮" },
			{ "kua", "夸" }, { "kua", "姱" }, { "kua", "挎" }, { "kua", "絓" }, { "kua", "胯" }, { "kua", "舿" }, { "kua", "誇" }, { "kua", "跨" }, { "kua", "銙" },
			{ "kua", "錁" }, { "kua", "骻" }, { "kua bao", "挎包" }, { "kua chu", "跨出" }, { "kua da", "夸大" }, { "kua di qu", "跨地区" }, { "kua diao", "垮掉" },
			{ "kua du", "跨度" }, { "kua guo", "跨国" }, { "kua guo", "跨过" }, { "kua guo gong si", "跨国公司" }, { "kua guo qi ye", "跨国企业" }, { "kua hang", "跨行" },
			{ "kua jiang", "夸奖" }, { "kua jing", "跨境" }, { "kua ping tai", "跨平台" }, { "kua qu", "跨区" }, { "kua ru", "跨入" }, { "kua sheng", "跨省" },
			{ "kua ta", "垮塌" }, { "kua tai", "垮台" }, { "kua yue", "跨越" }, { "kua zhang", "夸张" }, { "kuai", "会" }, { "kuai", "侩" }, { "kuai", "儈" },
			{ "kuai", "哙" }, { "kuai", "圦" }, { "kuai", "块" }, { "kuai", "塊" }, { "kuai", "廥" }, { "kuai", "快" }, { "kuai", "旝" }, { "kuai", "浍" },
			{ "kuai", "澮" }, { "kuai", "狯" }, { "kuai", "獪" }, { "kuai", "璯" }, { "kuai", "筷" }, { "kuai", "脍" }, { "kuai", "膾" }, { "kuai", "蒯" },
			{ "kuai", "郐" }, { "kuai", "鄶" }, { "kuai", "鱠" }, { "kuai a", "快啊" }, { "kuai ba", "快把" }, { "kuai bao", "快报" }, { "kuai bu", "快步" },
			{ "kuai can", "快餐" }, { "kuai can dian", "快餐店" }, { "kuai che", "快车" }, { "kuai che dao", "快车道" }, { "kuai cheng", "快成" }, { "kuai dao", "快到" },
			{ "kuai di", "快递" }, { "kuai di fei", "快递费" }, { "kuai di gong si", "快递公司" }, { "kuai dian", "快点" }, { "kuai gan", "快感" }, { "kuai gong", "快攻" },
			{ "kuai huo", "快活" }, { "kuai ji", "会计" }, { "kuai ji bao biao", "会计报表" }, { "kuai ji he suan", "会计核算" }, { "kuai ji shi", "会计师" },
			{ "kuai ji xue", "会计学" }, { "kuai ji zhun ze", "会计准则" }, { "kuai jian", "快件" }, { "kuai jie", "快捷" }, { "kuai jie fang shi", "快捷方式" },
			{ "kuai jie jian", "快捷键" }, { "kuai jie zou", "快节奏" }, { "kuai jin", "快进" }, { "kuai jiu", "快就" }, { "kuai kan", "快看" }, { "kuai kuai", "快快" },
			{ "kuai kuai le le", "快快乐乐" }, { "kuai lai", "快来" }, { "kuai le", "快乐" }, { "kuai man", "快慢" }, { "kuai men", "快门" }, { "kuai pao", "快跑" },
			{ "kuai qian", "块钱" }, { "kuai qian", "快钱" }, { "kuai qu", "快去" }, { "kuai shuo", "快说" }, { "kuai su", "快速" }, { "kuai su fa zhan", "快速发展" },
			{ "kuai su fan ying", "快速反应" }, { "kuai su lu", "快速路" }, { "kuai su zeng zhang", "快速增长" }, { "kuai ting", "快艇" }, { "kuai xie", "快些" },
			{ "kuai xun", "快讯" }, { "kuai yao", "快要" }, { "kuai yi", "快意" }, { "kuai yi dian", "快一点" }, { "kuai you", "快又" }, { "kuai yun", "快运" },
			{ "kuai zhao", "快照" }, { "kuai zhi ren kou", "脍炙人口" }, { "kuai zhuang", "块状" }, { "kuai zi", "筷子" }, { "kuai zou", "快走" }, { "kuan", "宽" },
			{ "kuan", "寛" }, { "kuan", "寬" }, { "kuan", "梡" }, { "kuan", "款" }, { "kuan", "窾" }, { "kuan", "髋" }, { "kuan", "髖" }, { "kuan chang", "宽敞" },
			{ "kuan che xing", "款车型" }, { "kuan da", "宽大" }, { "kuan dai", "宽带" }, { "kuan dai", "款待" }, { "kuan dai jie ru", "宽带接入" },
			{ "kuan dai shang wang", "宽带上网" }, { "kuan de", "宽的" }, { "kuan du", "宽度" }, { "kuan fan", "宽泛" }, { "kuan fu", "宽幅" }, { "kuan guang", "宽广" },
			{ "kuan hou", "宽厚" }, { "kuan kuan", "款款" }, { "kuan kuo", "宽阔" }, { "kuan pin", "宽频" }, { "kuan ping", "宽屏" }, { "kuan rong", "宽容" },
			{ "kuan shi", "款式" }, { "kuan shu", "宽恕" }, { "kuan song", "宽松" }, { "kuan wei", "宽慰" }, { "kuan xiang", "款项" }, { "kuan yu", "宽裕" },
			{ "kuang", "丱" }, { "kuang", "况" }, { "kuang", "劻" }, { "kuang", "匡" }, { "kuang", "哐" }, { "kuang", "圹" }, { "kuang", "壙" }, { "kuang", "夼" },
			{ "kuang", "恇" }, { "kuang", "懭" }, { "kuang", "旷" }, { "kuang", "昿" }, { "kuang", "曠" }, { "kuang", "框" }, { "kuang", "況" }, { "kuang", "洭" },
			{ "kuang", "爌" }, { "kuang", "狂" }, { "kuang", "狅" }, { "kuang", "眶" }, { "kuang", "矌" }, { "kuang", "矿" }, { "kuang", "砿" }, { "kuang", "礦" },
			{ "kuang", "穬" }, { "kuang", "筐" }, { "kuang", "筺" }, { "kuang", "絋" }, { "kuang", "絖" }, { "kuang", "纊" }, { "kuang", "纩" }, { "kuang", "誆" },
			{ "kuang", "誑" }, { "kuang", "诓" }, { "kuang", "诳" }, { "kuang", "貺" }, { "kuang", "贶" }, { "kuang", "軠" }, { "kuang", "軦" }, { "kuang", "邝" },
			{ "kuang", "鄺" }, { "kuang", "鉱" }, { "kuang", "鑛" }, { "kuang", "鵟" }, { "kuang bao", "狂暴" }, { "kuang ben", "狂奔" }, { "kuang biao", "狂飙" },
			{ "kuang chan", "矿产" }, { "kuang chan zi yuan", "矿产资源" }, { "kuang chao", "狂潮" }, { "kuang chuang", "矿床" }, { "kuang die", "狂跌" },
			{ "kuang ding", "狂顶" }, { "kuang feng", "狂风" }, { "kuang feng bao yu", "狂风暴雨" }, { "kuang gong", "旷工" }, { "kuang gong", "矿工" },
			{ "kuang huan", "狂欢" }, { "kuang jia", "框架" }, { "kuang jia xie yi", "框架协议" }, { "kuang jing", "矿井" }, { "kuang ke", "旷课" },
			{ "kuang kuang", "框框" }, { "kuang nan", "矿难" }, { "kuang qie", "况且" }, { "kuang qu", "矿区" }, { "kuang quan bing", "狂犬病" },
			{ "kuang quan shui", "矿泉水" }, { "kuang re", "狂热" }, { "kuang ren", "狂人" }, { "kuang shan", "矿山" }, { "kuang shi", "矿石" }, { "kuang tu", "框图" },
			{ "kuang wang", "狂妄" }, { "kuang wu", "矿物" }, { "kuang wu zhi", "矿物质" }, { "kuang xi", "狂喜" }, { "kuang xiao", "狂笑" }, { "kuang ye", "旷野" },
			{ "kuang ye", "狂野" }, { "kuang ye", "矿业" }, { "kuang yun", "狂晕" }, { "kuang zhang", "狂涨" }, { "kuang zhong", "框中" }, { "kuang zhu", "矿主" },
			{ "kui", "亏" }, { "kui", "傀" }, { "kui", "刲" }, { "kui", "勹" }, { "kui", "匮" }, { "kui", "匱" }, { "kui", "卼" }, { "kui", "喟" }, { "kui", "喹" },
			{ "kui", "嘳" }, { "kui", "夔" }, { "kui", "奎" }, { "kui", "媿" }, { "kui", "嬇" }, { "kui", "岿" }, { "kui", "悝" }, { "kui", "愦" }, { "kui", "愧" },
			{ "kui", "憒" }, { "kui", "戣" }, { "kui", "揆" }, { "kui", "暌" }, { "kui", "楏" }, { "kui", "楑" }, { "kui", "樻" }, { "kui", "櫆" }, { "kui", "欳" },
			{ "kui", "溃" }, { "kui", "潰" }, { "kui", "煃" }, { "kui", "盔" }, { "kui", "睽" }, { "kui", "窥" }, { "kui", "窺" }, { "kui", "篑" }, { "kui", "簣" },
			{ "kui", "聧" }, { "kui", "聩" }, { "kui", "聵" }, { "kui", "葵" }, { "kui", "蒉" }, { "kui", "蕢" }, { "kui", "藈" }, { "kui", "蘬" }, { "kui", "虧" },
			{ "kui", "蝰" }, { "kui", "跬" }, { "kui", "蹞" }, { "kui", "躨" }, { "kui", "逵" }, { "kui", "鄈" }, { "kui", "鍷" }, { "kui", "鐀" }, { "kui", "闚" },
			{ "kui", "隗" }, { "kui", "頄" }, { "kui", "頍" }, { "kui", "頯" }, { "kui", "顝" }, { "kui", "餽" }, { "kui", "饋" }, { "kui", "馈" }, { "kui", "馗" },
			{ "kui", "騤" }, { "kui", "魁" }, { "kui ben", "亏本" }, { "kui dai", "亏待" }, { "kui de", "亏得" }, { "kui dui", "愧对" }, { "kui fa", "匮乏" },
			{ "kui hua", "葵花" }, { "kui jia", "盔甲" }, { "kui jiu", "愧疚" }, { "kui lan", "溃烂" }, { "kui lei", "傀儡" }, { "kui qian", "亏欠" },
			{ "kui qian", "亏钱" }, { "kui shi", "窥视" }, { "kui sun", "亏损" }, { "kui tan", "窥探" }, { "kui wu", "魁梧" }, { "kui yang", "溃疡" },
			{ "kui zeng", "馈赠" }, { "kun", "困" }, { "kun", "坤" }, { "kun", "壼" }, { "kun", "崑" }, { "kun", "悃" }, { "kun", "捆" }, { "kun", "昆" },
			{ "kun", "晜" }, { "kun", "梱" }, { "kun", "涃" }, { "kun", "焜" }, { "kun", "猑" }, { "kun", "琨" }, { "kun", "睏" }, { "kun", "硱" }, { "kun", "稛" },
			{ "kun", "綑" }, { "kun", "臗" }, { "kun", "菎" }, { "kun", "裍" }, { "kun", "褌" }, { "kun", "豤" }, { "kun", "醌" }, { "kun", "錕" }, { "kun", "锟" },
			{ "kun", "閫" }, { "kun", "阃" }, { "kun", "騉" }, { "kun", "髡" }, { "kun", "鯤" }, { "kun", "鰥" }, { "kun", "鲲" }, { "kun", "鶤" },
			{ "kun bang", "捆绑" }, { "kun chong", "昆虫" }, { "kun dun", "困顿" }, { "kun huo", "困惑" }, { "kun jing", "困境" }, { "kun ju", "困局" },
			{ "kun ku", "困苦" }, { "kun lun", "昆仑" }, { "kun ming", "昆明" }, { "kun ming shi", "昆明市" }, { "kun nan", "困难" }, { "kun nan chong chong", "困难重重" },
			{ "kun nan qun ti", "困难群体" }, { "kun nan qun zhong", "困难群众" }, { "kun qu", "昆曲" }, { "kun rao", "困扰" }, { "kun shan", "昆山" }, { "kun si", "困死" },
			{ "kun zai", "困在" }, { "kuo", "廓" }, { "kuo", "懖" }, { "kuo", "扩" }, { "kuo", "拡" }, { "kuo", "括" }, { "kuo", "擴" }, { "kuo", "濶" },
			{ "kuo", "筈" }, { "kuo", "萿" }, { "kuo", "葀" }, { "kuo", "蛞" }, { "kuo", "适" }, { "kuo", "闊" }, { "kuo", "阔" }, { "kuo", "霩" }, { "kuo", "鞹" },
			{ "kuo", "韕" }, { "kuo", "鬠" }, { "kuo chong", "扩充" }, { "kuo da", "扩大" }, { "kuo da hui yi", "扩大会议" }, { "kuo da nei xu", "扩大内需" },
			{ "kuo hao", "括号" }, { "kuo jian", "扩建" }, { "kuo jian gong cheng", "扩建工程" }, { "kuo rong", "扩容" }, { "kuo san", "扩散" }, { "kuo zeng", "扩增" },
			{ "kuo zhan", "扩展" }, { "kuo zhan ming", "扩展名" }, { "kuo zhan xing", "扩展性" }, { "kuo zhang", "扩张" }, { "kuo zhao", "扩招" }, { "la", "剌" },
			{ "la", "啦" }, { "la", "喇" }, { "la", "垃" }, { "la", "拉" }, { "la", "揧" }, { "la", "旯" }, { "la", "柆" }, { "la", "楋" }, { "la", "溂" },
			{ "la", "瘌" }, { "la", "砬" }, { "la", "翋" }, { "la", "腊" }, { "la", "臈" }, { "la", "臘" }, { "la", "菈" }, { "la", "落" }, { "la", "藞" },
			{ "la", "蜡" }, { "la", "蝋" }, { "la", "蠟" }, { "la", "辣" }, { "la", "邋" }, { "la", "鑞" }, { "la", "鞡" }, { "la", "鬎" }, { "la ba", "喇叭" },
			{ "la bi", "蜡笔" }, { "la bi xiao xin", "蜡笔小新" }, { "la chang", "拉长" }, { "la che", "拉扯" }, { "la chu", "拉出" }, { "la chu qu", "拉出去" },
			{ "la da", "拉大" }, { "la dao", "拉倒" }, { "la dao", "拉到" }, { "la de", "拉得" }, { "la de", "辣的" }, { "la deng", "拉登" }, { "la ding", "拉丁" },
			{ "la ding mei zhou", "拉丁美洲" }, { "la dong", "拉动" }, { "la du zi", "拉肚子" }, { "la feng", "拉风" }, { "la gao", "拉高" }, { "la guo", "拉过" },
			{ "la hui", "拉回" }, { "la ji", "垃圾" }, { "la ji chang", "垃圾场" }, { "la ji chu li", "垃圾处理" }, { "la ji dui", "垃圾堆" }, { "la ji gu", "垃圾股" },
			{ "la ji tong", "垃圾桶" }, { "la ji xiang", "垃圾箱" }, { "la ji you jian", "垃圾邮件" }, { "la jiao", "辣椒" }, { "la jin", "拉近" }, { "la jin", "拉进" },
			{ "la ju", "拉锯" }, { "la kai", "拉开" }, { "la ke", "拉客" }, { "la la", "啦啦" }, { "la la", "拉拉" }, { "la la dui", "啦啦队" }, { "la la la", "啦啦啦" },
			{ "la lai", "拉来" }, { "la li", "拉力" }, { "la lian", "拉练" }, { "la lian", "拉链" }, { "la long", "拉拢" }, { "la ma", "喇嘛" }, { "la mei", "拉美" },
			{ "la mei", "辣妹" }, { "la mian", "拉面" }, { "la mu", "拉姆" }, { "la piao", "拉票" }, { "la qi", "拉起" }, { "la qi ao", "拉齐奥" }, { "la qu", "拉去" },
			{ "la ren", "拉人" }, { "la rou", "腊肉" }, { "la sa", "拉萨" }, { "la shang", "拉上" }, { "la shen", "拉伸" }, { "la sheng", "拉升" }, { "la shi", "拉屎" },
			{ "la shou", "拉手" }, { "la si", "拉丝" }, { "la si", "拉斯" }, { "la ta", "邋遢" }, { "la xi", "拉稀" }, { "la xia", "拉下" }, { "la xia", "落下" },
			{ "la yue", "腊月" }, { "la zhe", "拉着" }, { "la zhu", "拉住" }, { "la zhu", "蜡烛" }, { "la zou", "拉走" }, { "lai", "來" }, { "lai", "唻" }, { "lai", "娕" },
			{ "lai", "崃" }, { "lai", "崍" }, { "lai", "庲" }, { "lai", "徕" }, { "lai", "徠" }, { "lai", "来" }, { "lai", "棶" }, { "lai", "涞" }, { "lai", "淶" },
			{ "lai", "濑" }, { "lai", "瀨" }, { "lai", "瀬" }, { "lai", "癞" }, { "lai", "癩" }, { "lai", "睐" }, { "lai", "睞" }, { "lai", "箂" }, { "lai", "籁" },
			{ "lai", "籟" }, { "lai", "莱" }, { "lai", "萊" }, { "lai", "藾" }, { "lai", "誺" }, { "lai", "賚" }, { "lai", "賴" }, { "lai", "赉" }, { "lai", "赖" },
			{ "lai", "錸" }, { "lai", "铼" }, { "lai", "頼" }, { "lai", "騋" }, { "lai", "鯠" }, { "lai", "鶆" }, { "lai a", "来啊" }, { "lai ba", "来吧" },
			{ "lai bang", "来帮" }, { "lai biao shi", "来表示" }, { "lai bin", "来宾" }, { "lai bu ji", "来不及" }, { "lai can jia", "来参加" },
			{ "lai chang xing", "赖昌星" }, { "lai chao", "来潮" }, { "lai chi", "来吃" }, { "lai ci", "来此" }, { "lai da", "来打" }, { "lai dao", "来到" },
			{ "lai dao zhe li", "来到这里" }, { "lai de", "来得" }, { "lai de", "来的" }, { "lai de ji", "来得及" }, { "lai dian", "来点" }, { "lai dian", "来电" },
			{ "lai dian hua", "来电话" }, { "lai dian xian shi", "来电显示" }, { "lai fang", "来访" }, { "lai fang zhe", "来访者" }, { "lai fu", "来福" },
			{ "lai gao", "来稿" }, { "lai ge", "来个" }, { "lai gei", "来给" }, { "lai guo", "来过" }, { "lai ha ma", "癞蛤蟆" }, { "lai han", "来函" },
			{ "lai heng liang", "来衡量" }, { "lai hua", "来华" }, { "lai hui", "来回" }, { "lai jiang", "来讲" }, { "lai jie", "来接" }, { "lai jin", "来劲" },
			{ "lai jing", "来京" }, { "lai jiu", "来救" }, { "lai ka", "徕卡" }, { "lai ka", "莱卡" }, { "lai kan", "来看" }, { "lai kan kan", "来看看" },
			{ "lai kan ni", "来看你" }, { "lai ke", "来客" }, { "lai la", "来啦" }, { "lai lai", "来来" }, { "lai lai hui hui", "来来回回" },
			{ "lai lai wang wang", "来来往往" }, { "lai le", "来了" }, { "lai li", "来历" }, { "lai lin", "来临" }, { "lai long qu mai", "来龙去脉" }, { "lai mai", "来买" },
			{ "lai na", "来拿" }, { "lai ne", "来呢" }, { "lai nian", "来年" }, { "lai pi", "赖皮" }, { "lai qu", "来去" }, { "lai ren", "来人" }, { "lai sheng", "来生" },
			{ "lai shi", "来世" }, { "lai shi", "来时" }, { "lai shi xian", "来实现" }, { "lai shuo", "来说" }, { "lai si", "莱斯" }, { "lai si", "赖斯" },
			{ "lai tan", "来谈" }, { "lai te", "莱特" }, { "lai ting", "来听" }, { "lai tou", "来头" }, { "lai wan", "来晚" }, { "lai wan", "来玩" },
			{ "lai wan cheng", "来完成" }, { "lai wang", "来往" }, { "lai wei", "来为" }, { "lai wen", "来问" }, { "lai wu", "莱芜" }, { "lai xi", "来袭" },
			{ "lai xie", "来写" }, { "lai xin", "来信" }, { "lai xing rong", "来形容" }, { "lai ya", "来呀" }, { "lai yi", "来意" }, { "lai yi", "赖以" },
			{ "lai yin", "莱茵" }, { "lai yuan", "来源" }, { "lai yuan yu", "来源于" }, { "lai yue jing", "来月经" }, { "lai zhao", "来找" }, { "lai zhe", "来着" },
			{ "lai zhe", "来者" }, { "lai zhe", "来这" }, { "lai zhe", "赖着" }, { "lai zhe li", "来这里" }, { "lai zhi bu yi", "来之不易" }, { "lai zhua", "来抓" },
			{ "lai zi", "来自" }, { "lai zi bei jing", "来自北京" }, { "lai zi zhong guo", "来自中国" }, { "lai zuo", "来作" }, { "lai zuo", "来做" }, { "lan", "儖" },
			{ "lan", "兰" }, { "lan", "嚂" }, { "lan", "壈" }, { "lan", "婪" }, { "lan", "嬾" }, { "lan", "岚" }, { "lan", "嵐" }, { "lan", "懒" }, { "lan", "懶" },
			{ "lan", "拦" }, { "lan", "揽" }, { "lan", "擥" }, { "lan", "攔" }, { "lan", "攬" }, { "lan", "斓" }, { "lan", "斕" }, { "lan", "暕" }, { "lan", "栏" },
			{ "lan", "榄" }, { "lan", "欄" }, { "lan", "欖" }, { "lan", "欗" }, { "lan", "浨" }, { "lan", "滥" }, { "lan", "漤" }, { "lan", "澜" }, { "lan", "濫" },
			{ "lan", "瀾" }, { "lan", "灆" }, { "lan", "灠" }, { "lan", "灡" }, { "lan", "烂" }, { "lan", "燗" }, { "lan", "爁" }, { "lan", "爛" }, { "lan", "爦" },
			{ "lan", "篮" }, { "lan", "籃" }, { "lan", "籣" }, { "lan", "糷" }, { "lan", "繿" }, { "lan", "纜" }, { "lan", "缆" }, { "lan", "罱" }, { "lan", "蓝" },
			{ "lan", "藍" }, { "lan", "蘭" }, { "lan", "褴" }, { "lan", "襤" }, { "lan", "襴" }, { "lan", "覧" }, { "lan", "覽" }, { "lan", "览" }, { "lan", "諫" },
			{ "lan", "譋" }, { "lan", "讕" }, { "lan", "谰" }, { "lan", "躝" }, { "lan", "醂" }, { "lan", "鑭" }, { "lan", "镧" }, { "lan", "闌" }, { "lan", "阑" },
			{ "lan ban", "篮板" }, { "lan bao", "蓝宝" }, { "lan bao shi", "蓝宝石" }, { "lan ben", "蓝本" }, { "lan bo ji ni", "兰博基尼" }, { "lan che", "缆车" },
			{ "lan chong", "懒虫" }, { "lan chou", "蓝筹" }, { "lan chou gu", "蓝筹股" }, { "lan de", "兰德" }, { "lan de", "懒得" }, { "lan de", "懒的" },
			{ "lan diao", "蓝调" }, { "lan duo", "懒惰" }, { "lan gan", "栏杆" }, { "lan guang", "蓝光" }, { "lan hai", "蓝海" }, { "lan hei", "蓝黑" },
			{ "lan hua", "兰花" }, { "lan jiao", "懒觉" }, { "lan jie", "拦截" }, { "lan jun", "蓝军" }, { "lan kou", "兰蔻" }, { "lan lan", "兰兰" }, { "lan lan", "懒懒" },
			{ "lan lan", "蓝蓝" }, { "lan ling", "蓝领" }, { "lan long", "蓝龙" }, { "lan lv", "蓝绿" }, { "lan man", "烂漫" }, { "lan mao", "懒猫" }, { "lan mei", "蓝莓" },
			{ "lan mo", "蓝魔" }, { "lan mu", "栏目" }, { "lan pa de", "兰帕德" }, { "lan pian", "烂片" }, { "lan ping", "蓝屏" }, { "lan qiu", "篮球" },
			{ "lan qiu chang", "篮球场" }, { "lan qiu dui", "篮球队" }, { "lan qiu sai", "篮球赛" }, { "lan ren", "懒人" }, { "lan san", "懒散" }, { "lan se", "蓝色" },
			{ "lan tian", "蓝天" }, { "lan tian", "蓝田" }, { "lan tian bai yun", "蓝天白云" }, { "lan tu", "蓝图" }, { "lan wang", "篮网" }, { "lan wei", "栏位" },
			{ "lan wei lou", "烂尾楼" }, { "lan xia", "拦下" }, { "lan xia", "篮下" }, { "lan xie", "篮协" }, { "lan xing", "蓝星" }, { "lan ya", "蓝牙" },
			{ "lan ya er ji", "蓝牙耳机" }, { "lan yang yang", "懒洋洋" }, { "lan yong", "滥用" }, { "lan yong zhi quan", "滥用职权" }, { "lan zao", "蓝藻" },
			{ "lan zhe", "拦着" }, { "lan zhi", "兰芝" }, { "lan zhong", "栏中" }, { "lan zhou", "兰州" }, { "lan zhou shi", "兰州市" }, { "lan zhu", "拦住" },
			{ "lan zi", "篮子" }, { "lang", "啷" }, { "lang", "埌" }, { "lang", "塱" }, { "lang", "崀" }, { "lang", "廊" }, { "lang", "朖" }, { "lang", "朗" },
			{ "lang", "桹" }, { "lang", "榔" }, { "lang", "欴" }, { "lang", "浪" }, { "lang", "烺" }, { "lang", "狼" }, { "lang", "琅" }, { "lang", "瑯" },
			{ "lang", "硠" }, { "lang", "稂" }, { "lang", "筤" }, { "lang", "羮" }, { "lang", "莨" }, { "lang", "蒗" }, { "lang", "螂" }, { "lang", "誏" },
			{ "lang", "郎" }, { "lang", "郞" }, { "lang", "鋃" }, { "lang", "鎯" }, { "lang", "锒" }, { "lang", "閬" }, { "lang", "阆" }, { "lang bei", "狼狈" },
			{ "lang chao", "浪潮" }, { "lang du", "朗读" }, { "lang fang", "廊坊" }, { "lang fei", "浪费" }, { "lang fei shi jian", "浪费时间" }, { "lang ge", "朗阁" },
			{ "lang gou", "狼狗" }, { "lang hua", "浪花" }, { "lang ji tian ya", "浪迹天涯" }, { "lang jun", "郎君" }, { "lang lang", "朗朗" }, { "lang lang", "郎朗" },
			{ "lang man", "浪漫" }, { "lang man man wu", "浪漫满屋" }, { "lang man zhu yi", "浪漫主义" }, { "lang qun", "狼群" }, { "lang ren", "浪人" },
			{ "lang ren", "狼人" }, { "lang song", "朗诵" }, { "lang wang", "狼王" }, { "lang xian ping", "郎咸平" }, { "lang xun", "朗讯" }, { "lang zhong", "郎中" },
			{ "lang zi", "浪子" } };
};
