package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN63 {
	public static String[][] pl = { { "zhi xing qing kuang", "执行情况" }, { "zhi xing zhe", "执行者" }, { "zhi xu", "只许" }, { "zhi xu", "只需" }, { "zhi xu", "只须" },
			{ "zhi xu", "秩序" }, { "zhi xu yao", "只需要" }, { "zhi xuan", "之选" }, { "zhi xuan", "直选" }, { "zhi xue", "止血" }, { "zhi xue", "治学" },
			{ "zhi xun", "质询" }, { "zhi ya", "质押" }, { "zhi yan", "之言" }, { "zhi yan", "只眼" }, { "zhi yan", "直言" }, { "zhi yan bu hui", "直言不讳" },
			{ "zhi yang", "止痒" }, { "zhi yao", "之遥" }, { "zhi yao", "制药" }, { "zhi yao", "只要" }, { "zhi yao chang", "制药厂" }, { "zhi ye", "之夜" },
			{ "zhi ye", "执业" }, { "zhi ye", "枝叶" }, { "zhi ye", "汁液" }, { "zhi ye", "纸业" }, { "zhi ye", "置业" }, { "zhi ye", "职业" }, { "zhi ye bing", "职业病" },
			{ "zhi ye dao de", "职业道德" }, { "zhi ye fa zhan", "职业发展" }, { "zhi ye gui hua", "职业规划" }, { "zhi ye hua", "职业化" }, { "zhi ye ji neng", "职业技能" },
			{ "zhi ye jiao yu", "职业教育" }, { "zhi ye jie shao", "职业介绍" }, { "zhi ye pei xun", "职业培训" }, { "zhi ye sheng ya", "职业生涯" },
			{ "zhi ye xue xiao", "职业学校" }, { "zhi ye xue yuan", "职业学院" }, { "zhi yi", "之一" }, { "zhi yi", "之义" }, { "zhi yi", "之以" }, { "zhi yi", "之意" },
			{ "zhi yi", "执意" }, { "zhi yi", "旨意" }, { "zhi yi", "直译" }, { "zhi yi", "置疑" }, { "zhi yi", "致以" }, { "zhi yi", "致意" }, { "zhi yi", "质疑" },
			{ "zhi yin", "之音" }, { "zhi yin", "只因" }, { "zhi yin", "指引" }, { "zhi yin", "知音" }, { "zhi yin wei", "只因为" }, { "zhi yong", "之用" },
			{ "zhi yong", "只用" }, { "zhi you", "之友" }, { "zhi you", "之忧" }, { "zhi you", "只有" }, { "zhi you", "挚友" }, { "zhi you jia lian", "质优价廉" },
			{ "zhi you yi ci", "只有一次" }, { "zhi yu", "之余" }, { "zhi yu", "之语" }, { "zhi yu", "止于" }, { "zhi yu", "治愈" }, { "zhi yu", "置于" },
			{ "zhi yu", "至于" }, { "zhi yuan", "之源" }, { "zhi yuan", "只愿" }, { "zhi yuan", "志愿" }, { "zhi yuan", "志远" }, { "zhi yuan", "支援" },
			{ "zhi yuan", "职员" }, { "zhi yuan", "致远" }, { "zhi yuan fu wu", "志愿服务" }, { "zhi yuan jun", "志愿军" }, { "zhi yuan ti", "支原体" },
			{ "zhi yuan zhe", "志愿者" }, { "zhi yue", "之约" }, { "zhi yue", "制约" }, { "zhi yun xu", "只允许" }, { "zhi zai", "只在" }, { "zhi zai", "志在" },
			{ "zhi zai", "旨在" }, { "zhi zao", "制造" }, { "zhi zao", "织造" }, { "zhi zao chang", "制造厂" }, { "zhi zao chu", "制造出" }, { "zhi zao gong yi", "制造工艺" },
			{ "zhi zao ji shu", "制造技术" }, { "zhi zao qi ye", "制造企业" }, { "zhi zao shang", "制造商" }, { "zhi zao ye", "制造业" }, { "zhi zao zhe", "制造者" },
			{ "zhi ze", "指责" }, { "zhi ze", "职责" }, { "zhi zhan", "之战" }, { "zhi zhan", "只占" }, { "zhi zhang", "执掌" }, { "zhi zhang", "智障" },
			{ "zhi zhang", "纸张" }, { "zhi zhao", "执照" }, { "zhi zhao", "支招" }, { "zhi zhe", "指着" }, { "zhi zhe", "智者" }, { "zhi zhen", "指针" },
			{ "zhi zheng", "之争" }, { "zhi zheng", "执政" }, { "zhi zheng", "指正" }, { "zhi zheng dang", "执政党" }, { "zhi zheng neng li", "执政能力" },
			{ "zhi zheng wei min", "执政为民" }, { "zhi zhi", "之至" }, { "zhi zhi", "制止" }, { "zhi zhi", "只知" }, { "zhi zhi", "吱吱" }, { "zhi zhi", "指指" },
			{ "zhi zhi", "直指" }, { "zhi zhi", "直直" }, { "zhi zhi", "直至" }, { "zhi zhi", "知之" }, { "zhi zhi", "纸质" }, { "zhi zhi", "脂质" },
			{ "zhi zhi bu li", "置之不理" }, { "zhi zhi chi", "只支持" }, { "zhi zhi dao", "只知道" }, { "zhi zhi dian dian", "指指点点" }, { "zhi zhong", "之中" },
			{ "zhi zhong", "之重" }, { "zhi zhu", "支柱" }, { "zhi zhu", "植株" }, { "zhi zhu", "止住" }, { "zhi zhu", "蜘蛛" }, { "zhi zhu chan ye", "支柱产业" },
			{ "zhi zhu xia", "蜘蛛侠" }, { "zhi zhuo", "执着" }, { "zhi zi", "之子" }, { "zhi zi", "侄子" }, { "zhi zi", "质子" }, { "zhi zu", "知足" },
			{ "zhi zui", "之最" }, { "zhi zun", "至尊" }, { "zhi zun bao", "至尊宝" }, { "zhi zuo", "之作" }, { "zhi zuo", "制作" }, { "zhi zuo", "只做" },
			{ "zhi zuo cheng", "制作成" }, { "zhi zuo fang fa", "制作方法" }, { "zhi zuo gong yi", "制作工艺" }, { "zhi zuo guo cheng", "制作过程" },
			{ "zhi zuo ren", "制作人" }, { "zhi zuo zhe", "制作者" }, { "zhong", "中" }, { "zhong", "仲" }, { "zhong", "伀" }, { "zhong", "众" }, { "zhong", "冢" },
			{ "zhong", "堹" }, { "zhong", "塚" }, { "zhong", "夂" }, { "zhong", "妐" }, { "zhong", "尰" }, { "zhong", "彸" }, { "zhong", "忠" }, { "zhong", "忪" },
			{ "zhong", "柊" }, { "zhong", "炂" }, { "zhong", "煄" }, { "zhong", "狆" }, { "zhong", "盅" }, { "zhong", "眾" }, { "zhong", "祌" }, { "zhong", "种" },
			{ "zhong", "種" }, { "zhong", "穜" }, { "zhong", "籦" }, { "zhong", "終" }, { "zhong", "緟" }, { "zhong", "终" }, { "zhong", "肿" }, { "zhong", "腫" },
			{ "zhong", "舯" }, { "zhong", "蔠" }, { "zhong", "蝩" }, { "zhong", "螤" }, { "zhong", "螽" }, { "zhong", "衆" }, { "zhong", "衶" }, { "zhong", "衷" },
			{ "zhong", "踵" }, { "zhong", "迚" }, { "zhong", "重" }, { "zhong", "鈆" }, { "zhong", "鍾" }, { "zhong", "鐘" }, { "zhong", "钟" }, { "zhong", "锺" },
			{ "zhong", "鼨" }, { "zhong ai", "钟爱" }, { "zhong ba", "中巴" }, { "zhong bang", "重磅" }, { "zhong bao", "中报" }, { "zhong biao", "中标" },
			{ "zhong biao", "钟表" }, { "zhong bing", "重病" }, { "zhong bu", "中部" }, { "zhong bu di qu", "中部地区" }, { "zhong bu jue qi", "中部崛起" },
			{ "zhong bu tong", "种不同" }, { "zhong cai", "仲裁" }, { "zhong cai", "种菜" }, { "zhong can", "中餐" }, { "zhong can guan", "中餐馆" },
			{ "zhong cang", "重仓" }, { "zhong cang gu", "重仓股" }, { "zhong cao yao", "中草药" }, { "zhong ceng", "中层" }, { "zhong ceng gan bu", "中层干部" },
			{ "zhong chan", "中产" }, { "zhong chan jie ji", "中产阶级" }, { "zhong chang", "中场" }, { "zhong chang", "终场" }, { "zhong chang qi", "中长期" },
			{ "zhong chang xian", "中长线" }, { "zhong chao", "中超" }, { "zhong chao lian sai", "中超联赛" }, { "zhong cheng", "中称" }, { "zhong cheng", "忠诚" },
			{ "zhong cheng", "终成" }, { "zhong cheng du", "忠诚度" }, { "zhong cheng yao", "中成药" }, { "zhong chuang", "重创" }, { "zhong da", "中大" },
			{ "zhong da", "肿大" }, { "zhong da", "重大" }, { "zhong da jue ce", "重大决策" }, { "zhong da shi jian", "重大事件" }, { "zhong da shi xiang", "重大事项" },
			{ "zhong da tu po", "重大突破" }, { "zhong da wen ti", "重大问题" }, { "zhong da xiang mu", "重大项目" }, { "zhong da yi yi", "重大意义" },
			{ "zhong da ying xiang", "重大影响" }, { "zhong dai", "中带" }, { "zhong dan", "重担" }, { "zhong dang", "中档" }, { "zhong de", "中德" },
			{ "zhong de", "中的" }, { "zhong deng", "中等" }, { "zhong di", "中的" }, { "zhong di", "种地" }, { "zhong di dang", "中低档" }, { "zhong di duan", "中低端" },
			{ "zhong di shou ru", "中低收入" }, { "zhong dian", "中电" }, { "zhong dian", "终点" }, { "zhong dian", "重点" }, { "zhong dian da xue", "重点大学" },
			{ "zhong dian gong", "钟点工" }, { "zhong dian gong cheng", "重点工程" }, { "zhong dian gong zuo", "重点工作" }, { "zhong dian jian she", "重点建设" },
			{ "zhong dian ling yu", "重点领域" }, { "zhong dian qi ye", "重点企业" }, { "zhong dian xiang mu", "重点项目" }, { "zhong dian zhan", "终点站" },
			{ "zhong dian zhong xue", "重点中学" }, { "zhong dong", "中东" }, { "zhong dong di qu", "中东地区" }, { "zhong du", "中度" }, { "zhong du", "中毒" },
			{ "zhong du", "中都" }, { "zhong du", "重度" }, { "zhong duan", "中断" }, { "zhong duan", "中段" }, { "zhong duan", "中端" }, { "zhong duan", "终端" },
			{ "zhong dui", "中对" }, { "zhong dui", "中队" }, { "zhong duo", "众多" }, { "zhong e", "中俄" }, { "zhong fa", "中法" }, { "zhong fan", "中饭" },
			{ "zhong fang", "中方" }, { "zhong fang fa", "种方法" }, { "zhong fei", "中非" }, { "zhong feng", "中锋" }, { "zhong feng", "中风" }, { "zhong gao", "忠告" },
			{ "zhong gao dang", "中高档" }, { "zhong gao duan", "中高端" }, { "zhong gao ji", "中高级" }, { "zhong gong", "中共" }, { "zhong gong", "重工" },
			{ "zhong gong dang yuan", "中共党员" }, { "zhong gong ye", "重工业" }, { "zhong gong zhong yang", "中共中央" }, { "zhong gu", "中古" },
			{ "zhong guan cun", "中关村" }, { "zhong gui", "终归" }, { "zhong guo", "中国" }, { "zhong guo ban", "中国版" }, { "zhong guo bei fang", "中国北方" },
			{ "zhong guo cheng shi", "中国城市" }, { "zhong guo chu kou", "中国出口" }, { "zhong guo chuan tong", "中国传统" }, { "zhong guo da lu", "中国大陆" },
			{ "zhong guo dang dai", "中国当代" }, { "zhong guo di yi", "中国第一" }, { "zhong guo dian xin", "中国电信" }, { "zhong guo dian ying", "中国电影" },
			{ "zhong guo dui", "中国队" }, { "zhong guo fa zhan", "中国发展" }, { "zhong guo ge ming", "中国革命" }, { "zhong guo gong min", "中国公民" },
			{ "zhong guo gong si", "中国公司" }, { "zhong guo gu dai", "中国古代" }, { "zhong guo gu shi", "中国股市" }, { "zhong guo guo ji", "中国国际" },
			{ "zhong guo guo qing", "中国国情" }, { "zhong guo hai jun", "中国海军" }, { "zhong guo hua", "中国画" }, { "zhong guo hua", "中国话" },
			{ "zhong guo jian zhu", "中国建筑" }, { "zhong guo jiao yu", "中国教育" }, { "zhong guo jin dai", "中国近代" }, { "zhong guo jin kou", "中国进口" },
			{ "zhong guo jin rong", "中国金融" }, { "zhong guo jing ji", "中国经济" }, { "zhong guo jun dui", "中国军队" }, { "zhong guo li shi", "中国历史" },
			{ "zhong guo lian tong", "中国联通" }, { "zhong guo lv ye", "中国铝业" }, { "zhong guo mei ti", "中国媒体" }, { "zhong guo nan lan", "中国男篮" },
			{ "zhong guo nan ren", "中国男人" }, { "zhong guo nei di", "中国内地" }, { "zhong guo nong cun", "中国农村" }, { "zhong guo nong min", "中国农民" },
			{ "zhong guo nv pai", "中国女排" }, { "zhong guo nv ren", "中国女人" }, { "zhong guo nv zu", "中国女足" }, { "zhong guo ping an", "中国平安" },
			{ "zhong guo qi che", "中国汽车" }, { "zhong guo qi ye", "中国企业" }, { "zhong guo qing nian", "中国青年" }, { "zhong guo qu", "中国区" },
			{ "zhong guo ren", "中国人" }, { "zhong guo ren kou", "中国人口" }, { "zhong guo ren min", "中国人民" }, { "zhong guo ren shou", "中国人寿" },
			{ "zhong guo she hui", "中国社会" }, { "zhong guo shi", "中国式" }, { "zhong guo shi chang", "中国市场" }, { "zhong guo shi da", "中国十大" },
			{ "zhong guo shi hua", "中国石化" }, { "zhong guo shi you", "中国石油" }, { "zhong guo tai wan", "中国台湾" }, { "zhong guo te se", "中国特色" },
			{ "zhong guo ti yu", "中国体育" }, { "zhong guo wang min", "中国网民" }, { "zhong guo wang tong", "中国网通" }, { "zhong guo wei lai", "中国未来" },
			{ "zhong guo wen hua", "中国文化" }, { "zhong guo wen xue", "中国文学" }, { "zhong guo xi bu", "中国西部" }, { "zhong guo xian dai", "中国现代" },
			{ "zhong guo xue sheng", "中国学生" }, { "zhong guo yi dong", "中国移动" }, { "zhong guo yin hang", "中国银行" }, { "zhong guo you ke", "中国游客" },
			{ "zhong guo you zheng", "中国邮政" }, { "zhong guo zheng fu", "中国政府" }, { "zhong guo zheng quan", "中国证券" }, { "zhong guo zhi zao", "中国制造" },
			{ "zhong guo zhong qi", "中国重汽" }, { "zhong guo zhu", "中国驻" }, { "zhong guo zu qiu", "中国足球" }, { "zhong guo zu xie", "中国足协" },
			{ "zhong guo zui da", "中国最大" }, { "zhong guo zui ju", "中国最具" }, { "zhong hai", "中海" }, { "zhong hai you", "中海油" }, { "zhong han", "中含" },
			{ "zhong han", "中韩" }, { "zhong hang", "中航" }, { "zhong hang", "中行" }, { "zhong hao", "中号" }, { "zhong hou", "忠厚" }, { "zhong hou qi", "中后期" },
			{ "zhong hou wei", "中后卫" }, { "zhong hua", "中化" }, { "zhong hua", "中华" }, { "zhong hua", "种花" }, { "zhong hua er nv", "中华儿女" },
			{ "zhong hua min guo", "中华民国" }, { "zhong hua min zu", "中华民族" }, { "zhong hua wang", "中华网" }, { "zhong hua wen hua", "中华文化" },
			{ "zhong hua wen ming", "中华文明" }, { "zhong huan", "中环" }, { "zhong hui", "终会" }, { "zhong ji", "中级" }, { "zhong ji", "中继" }, { "zhong ji", "终极" },
			{ "zhong ji che", "中级车" }, { "zhong ji fa yuan", "中级法院" }, { "zhong ji mu biao", "终极目标" }, { "zhong ji wei", "中纪委" }, { "zhong jia", "中加" },
			{ "zhong jia", "中甲" }, { "zhong jian", "中坚" }, { "zhong jian", "中建" }, { "zhong jian", "中间" }, { "zhong jian jia", "中间价" },
			{ "zhong jian jian", "中间件" }, { "zhong jian ren", "中间人" }, { "zhong jian shang", "中间商" }, { "zhong jiang", "中奖" }, { "zhong jiang", "中将" },
			{ "zhong jiang", "终将" }, { "zhong jiang", "重奖" }, { "zhong jie", "中介" }, { "zhong jie", "终结" }, { "zhong jie fei", "中介费" },
			{ "zhong jie fu wu", "中介服务" }, { "zhong jie gong si", "中介公司" }, { "zhong jie ji gou", "中介机构" }, { "zhong jie zhe", "终结者" },
			{ "zhong jie zu zhi", "中介组织" }, { "zhong jin", "中金" }, { "zhong jin", "重金" }, { "zhong jin gong si", "中金公司" }, { "zhong jin shu", "重金属" },
			{ "zhong jiu", "终究" }, { "zhong ka", "重卡" }, { "zhong kao", "中考" }, { "zhong ke", "中科" }, { "zhong ke yuan", "中科院" }, { "zhong ken", "中肯" },
			{ "zhong kong", "中空" }, { "zhong kong tai", "中控台" }, { "zhong kuai", "肿块" }, { "zhong lai", "中来" }, { "zhong lao nian", "中老年" },
			{ "zhong lao nian ren", "中老年人" }, { "zhong le", "中了" }, { "zhong lei", "种类" }, { "zhong lei xing", "种类型" }, { "zhong li", "中立" },
			{ "zhong li", "重力" }, { "zhong lian", "中联" }, { "zhong liang", "中粮" }, { "zhong liang", "种粮" }, { "zhong liang", "重量" },
			{ "zhong liang ji", "重量级" }, { "zhong liu", "肿瘤" }, { "zhong lou", "钟楼" }, { "zhong lu", "中路" }, { "zhong lv", "中铝" }, { "zhong mei", "中美" },
			{ "zhong mei guan xi", "中美关系" }, { "zhong miao", "种苗" }, { "zhong nan", "中南" }, { "zhong nan da xue", "中南大学" }, { "zhong nan hai", "中南海" },
			{ "zhong neng", "中能" }, { "zhong nian", "中年" }, { "zhong nian", "终年" }, { "zhong nian fu nv", "中年妇女" }, { "zhong nian nan ren", "中年男人" },
			{ "zhong nian nan zi", "中年男子" }, { "zhong nian ren", "中年人" }, { "zhong ou", "中欧" }, { "zhong pin", "中频" }, { "zhong qi", "中期" },
			{ "zhong qian", "中签" }, { "zhong qian lv", "中签率" }, { "zhong qing", "钟情" }, { "zhong qing ju", "中情局" }, { "zhong qing nian", "中青年" },
			{ "zhong qing zai xian", "中青在线" }, { "zhong qiu", "中秋" }, { "zhong qiu jie", "中秋节" }, { "zhong qiu kuai le", "中秋快乐" }, { "zhong qu", "中去" },
			{ "zhong quan", "重拳" }, { "zhong que", "中却" }, { "zhong qun", "种群" }, { "zhong ren", "中人" }, { "zhong ren", "众人" }, { "zhong ren", "重任" },
			{ "zhong ri", "中日" }, { "zhong ri", "终日" }, { "zhong ri guan xi", "中日关系" }, { "zhong ri han", "中日韩" }, { "zhong ruan", "中软" },
			{ "zhong shan", "中山" }, { "zhong shan da xue", "中山大学" }, { "zhong shan gong yuan", "中山公园" }, { "zhong shan lu", "中山路" },
			{ "zhong shan shi", "中山市" }, { "zhong shang", "中伤" }, { "zhong shang", "重伤" }, { "zhong shen", "众神" }, { "zhong shen", "终审" },
			{ "zhong shen", "终身" }, { "zhong sheng", "众生" }, { "zhong sheng", "终生" }, { "zhong sheng", "钟声" }, { "zhong shi", "中式" }, { "zhong shi", "忠实" },
			{ "zhong shi", "重视" }, { "zhong shi hua", "中石化" }, { "zhong shi ji", "中世纪" }, { "zhong shu", "中暑" }, { "zhong shu", "中枢" }, { "zhong shu", "种树" },
			{ "zhong shuo", "中说" }, { "zhong shuo fen yun", "众说纷纭" }, { "zhong su", "中苏" }, { "zhong suo zhou zhi", "众所周知" }, { "zhong tian", "中天" },
			{ "zhong tian", "种田" }, { "zhong tie", "中铁" }, { "zhong tou", "中投" }, { "zhong tou", "钟头" }, { "zhong tou xi", "重头戏" }, { "zhong tu", "中途" },
			{ "zhong wai", "中外" }, { "zhong wai he zi", "中外合资" }, { "zhong wei", "中卫" }, { "zhong wei", "中尉" }, { "zhong wen", "中文" },
			{ "zhong wen ban", "中文版" }, { "zhong wen lun tan", "中文论坛" }, { "zhong wen ming", "中文名" }, { "zhong wen wang", "中文网" }, { "zhong wen xi", "中文系" },
			{ "zhong wen yu ming", "中文域名" }, { "zhong wen zi mu", "中文字幕" }, { "zhong wu", "中午" }, { "zhong wu", "重物" }, { "zhong xi", "中戏" },
			{ "zhong xi", "中西" }, { "zhong xi bu", "中西部" }, { "zhong xia", "种下" }, { "zhong xia xun", "中下旬" }, { "zhong xia you", "中下游" },
			{ "zhong xian", "中仙" }, { "zhong xian", "中线" }, { "zhong xiao", "中小" }, { "zhong xiao ban", "中小板" }, { "zhong xiao cheng shi", "中小城市" },
			{ "zhong xiao qi ye", "中小企业" }, { "zhong xiao xing", "中小型" }, { "zhong xiao xue", "中小学" }, { "zhong xiao xue sheng", "中小学生" },
			{ "zhong xiao xue xiao", "中小学校" }, { "zhong xin", "中信" }, { "zhong xin", "中心" }, { "zhong xin", "忠心" }, { "zhong xin", "衷心" },
			{ "zhong xin", "重心" }, { "zhong xin cheng shi", "中心城市" }, { "zhong xin gong zuo", "中心工作" }, { "zhong xin qu", "中心区" }, { "zhong xin she", "中新社" },
			{ "zhong xin tai fu", "中信泰富" }, { "zhong xin wang", "中新网" }, { "zhong xin xiao xue", "中心小学" }, { "zhong xin yi yuan", "中心医院" },
			{ "zhong xin yin hang", "中信银行" }, { "zhong xin zheng quan", "中信证券" }, { "zhong xin zhu ren", "中心主任" }, { "zhong xin zu", "中心组" },
			{ "zhong xing", "中兴" }, { "zhong xing", "中型" }, { "zhong xing", "中性" }, { "zhong xing", "重型" }, { "zhong xing tong xun", "中兴通讯" },
			{ "zhong xuan", "中选" }, { "zhong xuan bu", "中宣部" }, { "zhong xue", "中学" }, { "zhong xue sheng", "中学生" }, { "zhong xun", "中旬" },
			{ "zhong ya", "中亚" }, { "zhong ya", "重压" }, { "zhong yan se", "种颜色" }, { "zhong yang", "中央" }, { "zhong yang cai zheng", "中央财政" },
			{ "zhong yang dang xiao", "中央党校" }, { "zhong yang ji wei", "中央纪委" }, { "zhong yang jun wei", "中央军委" }, { "zhong yang kong tiao", "中央空调" },
			{ "zhong yang ling dao", "中央领导" }, { "zhong yang qi ye", "中央企业" }, { "zhong yang she", "中央社" }, { "zhong yang tai", "中央台" },
			{ "zhong yang wei yuan", "中央委员" }, { "zhong yang yin hang", "中央银行" }, { "zhong yang zheng fu", "中央政府" }, { "zhong yao", "中药" },
			{ "zhong yao", "重要" }, { "zhong yao biao zhi", "重要标志" }, { "zhong yao cai", "中药材" }, { "zhong yao di wei", "重要地位" },
			{ "zhong yao jiang hua", "重要讲话" }, { "zhong yao ju cuo", "重要举措" }, { "zhong yao nei rong", "重要内容" }, { "zhong yao ren wu", "重要任务" },
			{ "zhong yao si xiang", "重要思想" }, { "zhong yao tu jing", "重要途径" }, { "zhong yao wen ti", "重要问题" }, { "zhong yao xing", "重要性" },
			{ "zhong yao yi yi", "重要意义" }, { "zhong yao yin su", "重要因素" }, { "zhong yao yuan yin", "重要原因" }, { "zhong yao zuo yong", "重要作用" },
			{ "zhong ye", "中也" }, { "zhong ye", "中叶" }, { "zhong yi", "中医" }, { "zhong yi", "中意" }, { "zhong yi", "忠义" }, { "zhong yi", "钟意" },
			{ "zhong yi dong", "中移动" }, { "zhong yi xue", "中医学" }, { "zhong yi yao", "中医药" }, { "zhong yi yuan", "中医院" }, { "zhong yi yuan", "众议院" },
			{ "zhong yin", "中印" }, { "zhong yin", "中银" }, { "zhong ying", "中应" }, { "zhong ying", "中英" }, { "zhong ying wen", "中英文" }, { "zhong yong", "中庸" },
			{ "zhong yong", "重用" }, { "zhong you", "中有" }, { "zhong you", "中油" }, { "zhong you", "中游" }, { "zhong you", "中邮" }, { "zhong you", "仲有" },
			{ "zhong you", "终有" }, { "zhong yu", "忠于" }, { "zhong yu", "终于" }, { "zhong yu", "重于" }, { "zhong yu ming bai", "终于明白" },
			{ "zhong yu zhao dao", "终于找到" }, { "zhong yuan", "中原" }, { "zhong yuan", "中远" }, { "zhong yuan", "中院" }, { "zhong yue", "中越" },
			{ "zhong zai", "重在" }, { "zhong zai qu", "重灾区" }, { "zhong zhan", "中占" }, { "zhong zhang", "肿胀" }, { "zhong zhao", "中招" }, { "zhong zhen", "忠贞" },
			{ "zhong zhen", "重镇" }, { "zhong zheng", "重症" }, { "zhong zhi", "中指" }, { "zhong zhi", "中止" }, { "zhong zhi", "中职" }, { "zhong zhi", "种植" },
			{ "zhong zhi", "终止" }, { "zhong zhi cheng cheng", "众志成城" }, { "zhong zhi mian ji", "种植面积" }, { "zhong zhi ye", "种植业" }, { "zhong zhong", "种种" },
			{ "zhong zhong", "重重" }, { "zhong zhong de", "重重地" }, { "zhong zhong zhi zhong", "重中之重" }, { "zhong zhuan", "中专" }, { "zhong zhuan", "中转" },
			{ "zhong zi", "中资" }, { "zhong zi", "种子" }, { "zhong zi yin hang", "中资银行" }, { "zhong zu", "种族" }, { "zhong zu bu", "中组部" },
			{ "zhong zu qi shi", "种族歧视" }, { "zhong zui", "中最" }, { "zhou", "侜" }, { "zhou", "僽" }, { "zhou", "冑" }, { "zhou", "周" }, { "zhou", "呪" },
			{ "zhou", "咒" }, { "zhou", "咮" }, { "zhou", "啁" }, { "zhou", "喌" }, { "zhou", "妯" }, { "zhou", "婤" }, { "zhou", "宙" }, { "zhou", "州" },
			{ "zhou", "帚" }, { "zhou", "徟" }, { "zhou", "昼" }, { "zhou", "晝" }, { "zhou", "椆" }, { "zhou", "洀" }, { "zhou", "洲" }, { "zhou", "淍" },
			{ "zhou", "珘" }, { "zhou", "甃" }, { "zhou", "皱" }, { "zhou", "皺" }, { "zhou", "盩" }, { "zhou", "睭" }, { "zhou", "碡" }, { "zhou", "箒" },
			{ "zhou", "籀" }, { "zhou", "粥" }, { "zhou", "紂" }, { "zhou", "紬" }, { "zhou", "縐" }, { "zhou", "繇" }, { "zhou", "纣" }, { "zhou", "绉" },
			{ "zhou", "翢" }, { "zhou", "肘" }, { "zhou", "胄" }, { "zhou", "胕" }, { "zhou", "舟" }, { "zhou", "荮" }, { "zhou", "菷" }, { "zhou", "薵" },
			{ "zhou", "詶" }, { "zhou", "謅" }, { "zhou", "譸" }, { "zhou", "诌" }, { "zhou", "賙" }, { "zhou", "軸" }, { "zhou", "輈" }, { "zhou", "輖" },
			{ "zhou", "轴" }, { "zhou", "週" }, { "zhou", "酎" }, { "zhou", "鈾" }, { "zhou", "銂" }, { "zhou", "駎" }, { "zhou", "駲" }, { "zhou", "騆" },
			{ "zhou", "驟" }, { "zhou", "骤" }, { "zhou", "鯞" }, { "zhou", "鵃" }, { "zhou bao", "周报" }, { "zhou bi chang", "周笔畅" }, { "zhou bian", "周边" },
			{ "zhou bian di qu", "周边地区" }, { "zhou bian guo jia", "周边国家" }, { "zhou bian huan jing", "周边环境" }, { "zhou chang", "周长" }, { "zhou cheng", "轴承" },
			{ "zhou dao", "周到" }, { "zhou dong", "周董" }, { "zhou en lai", "周恩来" }, { "zhou er", "周二" }, { "zhou er fu shi", "周而复始" }, { "zhou gong", "周公" },
			{ "zhou hou", "周后" }, { "zhou hua jian", "周华健" }, { "zhou hui min", "周慧敏" }, { "zhou ji", "周济" }, { "zhou ji", "洲际" }, { "zhou jia", "周家" },
			{ "zhou jie", "周杰" }, { "zhou jie lun", "周杰伦" }, { "zhou ju", "轴距" }, { "zhou kan", "周刊" }, { "zhou kou", "周口" }, { "zhou le", "皱了" },
			{ "zhou li da xue", "州立大学" }, { "zhou liu", "周六" }, { "zhou ma", "咒骂" }, { "zhou mei", "皱眉" }, { "zhou mei tou", "皱眉头" }, { "zhou mi", "周密" },
			{ "zhou mo", "周末" }, { "zhou mou", "周某" }, { "zhou nei", "周内" }, { "zhou nian", "周年" }, { "zhou nian ji nian", "周年纪念" },
			{ "zhou nian qing dian", "周年庆典" }, { "zhou qi", "周期" }, { "zhou qi xing", "周期性" }, { "zhou quan", "周全" }, { "zhou ran", "骤然" },
			{ "zhou ri", "周日" }, { "zhou run fa", "周润发" }, { "zhou san", "周三" }, { "zhou shan", "舟山" }, { "zhou shen", "周身" }, { "zhou si", "周四" },
			{ "zhou si", "宙斯" }, { "zhou sui", "周岁" }, { "zhou tao", "周涛" }, { "zhou tian", "周天" }, { "zhou wei", "周围" }, { "zhou wei huan jing", "周围环境" },
			{ "zhou wen", "周文" }, { "zhou wen", "皱纹" }, { "zhou wu", "周五" }, { "zhou xian", "周线" }, { "zhou xian", "轴线" }, { "zhou xiang", "轴向" },
			{ "zhou xiao chuan", "周小川" }, { "zhou xin", "轴心" }, { "zhou xing chi", "周星驰" }, { "zhou xing xing", "周星星" }, { "zhou xuan", "周旋" },
			{ "zhou xun", "周迅" }, { "zhou ye", "昼夜" }, { "zhou yi", "周一" }, { "zhou yi", "周易" }, { "zhou you", "周游" }, { "zhou yu", "周瑜" },
			{ "zhou yu", "咒语" }, { "zhou zao", "周遭" }, { "zhou zhang", "州长" }, { "zhou zhe", "周折" }, { "zhou zhe", "皱着" }, { "zhou zheng", "周正" },
			{ "zhou zheng fu", "州政府" }, { "zhou zheng yi", "周正毅" }, { "zhou zhou", "周周" }, { "zhou zhuan", "周转" }, { "zhou zhuang", "周庄" },
			{ "zhou zong li", "周总理" }, { "zhou zuo ren", "周作人" }, { "zhu", "丶" }, { "zhu", "主" }, { "zhu", "伫" }, { "zhu", "佇" }, { "zhu", "住" },
			{ "zhu", "侏" }, { "zhu", "助" }, { "zhu", "劯" }, { "zhu", "嘱" }, { "zhu", "囑" }, { "zhu", "墸" }, { "zhu", "壴" }, { "zhu", "孎" }, { "zhu", "尌" },
			{ "zhu", "属" }, { "zhu", "嵀" }, { "zhu", "拄" }, { "zhu", "斸" }, { "zhu", "术" }, { "zhu", "朱" }, { "zhu", "杼" }, { "zhu", "柱" }, { "zhu", "柷" },
			{ "zhu", "株" }, { "zhu", "槠" }, { "zhu", "樦" }, { "zhu", "橥" }, { "zhu", "櫧" }, { "zhu", "櫫" }, { "zhu", "欘" }, { "zhu", "殶" }, { "zhu", "泏" },
			{ "zhu", "注" }, { "zhu", "洙" }, { "zhu", "渚" }, { "zhu", "潴" }, { "zhu", "瀦" }, { "zhu", "灟" }, { "zhu", "炷" }, { "zhu", "烛" }, { "zhu", "煮" },
			{ "zhu", "燭" }, { "zhu", "猪" }, { "zhu", "珠" }, { "zhu", "疰" }, { "zhu", "瘃" }, { "zhu", "眝" }, { "zhu", "瞩" }, { "zhu", "矚" }, { "zhu", "砫" },
			{ "zhu", "硃" }, { "zhu", "磩" }, { "zhu", "祝" }, { "zhu", "祩" }, { "zhu", "窋" }, { "zhu", "竚" }, { "zhu", "竹" }, { "zhu", "竺" }, { "zhu", "笁" },
			{ "zhu", "筑" }, { "zhu", "箸" }, { "zhu", "築" }, { "zhu", "篫" }, { "zhu", "篴" }, { "zhu", "紵" }, { "zhu", "紸" }, { "zhu", "絑" }, { "zhu", "罜" },
			{ "zhu", "羜" }, { "zhu", "翥" }, { "zhu", "舳" }, { "zhu", "芧" }, { "zhu", "苎" }, { "zhu", "茱" }, { "zhu", "茿" }, { "zhu", "莇" }, { "zhu", "著" },
			{ "zhu", "蓫" }, { "zhu", "藷" }, { "zhu", "藸" }, { "zhu", "蛀" }, { "zhu", "蛛" }, { "zhu", "蝫" }, { "zhu", "蠋" }, { "zhu", "蠩" }, { "zhu", "蠾" },
			{ "zhu", "袾" }, { "zhu", "褚" }, { "zhu", "註" }, { "zhu", "誅" }, { "zhu", "諸" }, { "zhu", "诛" }, { "zhu", "诸" }, { "zhu", "豬" }, { "zhu", "貯" },
			{ "zhu", "贮" }, { "zhu", "跓" }, { "zhu", "跙" }, { "zhu", "跦" }, { "zhu", "躅" }, { "zhu", "軴" }, { "zhu", "逐" }, { "zhu", "邾" }, { "zhu", "鉒" },
			{ "zhu", "銖" }, { "zhu", "鋳" }, { "zhu", "鑄" }, { "zhu", "钃" }, { "zhu", "铢" }, { "zhu", "铸" }, { "zhu", "陼" }, { "zhu", "馵" }, { "zhu", "駐" },
			{ "zhu", "驻" }, { "zhu", "鮢" }, { "zhu", "鱁" }, { "zhu", "鴸" }, { "zhu", "鸀" }, { "zhu", "麆" }, { "zhu", "麈" }, { "zhu ba jie", "猪八戒" },
			{ "zhu ban", "主办" }, { "zhu ban", "主板" }, { "zhu ban dan wei", "主办单位" }, { "zhu ban fang", "主办方" }, { "zhu bao", "珠宝" }, { "zhu bian", "主编" },
			{ "zhu bo", "主播" }, { "zhu bu", "逐步" }, { "zhu cai dan", "主菜单" }, { "zhu cai pan", "主裁判" }, { "zhu cang", "贮藏" }, { "zhu ce", "注册" },
			{ "zhu ce biao", "注册表" }, { "zhu ce deng ji", "注册登记" }, { "zhu ce gong si", "注册公司" }, { "zhu ce hui yuan", "注册会员" }, { "zhu ce ji", "注册机" },
			{ "zhu ce ma", "注册码" }, { "zhu ce ri qi", "注册日期" }, { "zhu ce shang", "注册商" }, { "zhu ce shang biao", "注册商标" }, { "zhu ce yong hu", "注册用户" },
			{ "zhu ce zhang hao", "注册帐号" }, { "zhu ce zi ben", "注册资本" }, { "zhu ce zi jin", "注册资金" }, { "zhu chan qu", "主产区" }, { "zhu chang", "主唱" },
			{ "zhu chang", "主场" }, { "zhu cheng", "主城" }, { "zhu cheng", "著称" }, { "zhu cheng", "铸成" }, { "zhu cheng qu", "主城区" }, { "zhu cheng xu", "主程序" },
			{ "zhu chi", "主持" }, { "zhu chi hui yi", "主持会议" }, { "zhu chi ren", "主持人" }, { "zhu chong", "蛀虫" }, { "zhu chu", "住处" }, { "zhu chuang", "主创" },
			{ "zhu ci", "主次" }, { "zhu cun", "贮存" }, { "zhu da", "主打" }, { "zhu da ge", "主打歌" }, { "zhu da jia", "祝大家" } };
};
