package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN30 {
	public static String[][] pl = { { "ling shou ye", "零售业" }, { "ling shou zong e", "零售总额" }, { "ling sui", "零碎" }, { "ling ta", "令他" },
			{ "ling tang", "灵堂" }, { "ling ting", "聆听" }, { "ling tong", "灵通" }, { "ling tou", "零头" }, { "ling tou", "领头" }, { "ling tou yang", "领头羊" },
			{ "ling tu", "领土" }, { "ling wai", "另外" }, { "ling wo", "令我" }, { "ling wu", "领悟" }, { "ling xi", "灵犀" }, { "ling xia", "零下" },
			{ "ling xian", "领先" }, { "ling xian", "领衔" }, { "ling xing", "另行" }, { "ling xing", "灵性" }, { "ling xing", "菱形" }, { "ling xing", "零星" },
			{ "ling xiu", "领袖" }, { "ling yan", "灵验" }, { "ling yang", "羚羊" }, { "ling yang", "领养" }, { "ling yi", "另一" }, { "ling yi", "灵异" },
			{ "ling yi ban", "另一半" }, { "ling yi bian", "另一边" }, { "ling yi duan", "另一端" }, { "ling yi fang", "另一方" }, { "ling yi fang mian", "另一方面" },
			{ "ling yi ge ren", "另一个人" }, { "ling yi mian", "另一面" }, { "ling yi tai", "另一台" }, { "ling yi wei", "另一位" }, { "ling yi zhi", "另一只" },
			{ "ling yi zhong", "另一种" }, { "ling yin", "铃音" }, { "ling yong", "领用" }, { "ling yong qian", "零用钱" }, { "ling you", "另有" }, { "ling yu", "领域" },
			{ "ling yu", "领驭" }, { "ling yuan", "陵园" }, { "ling yun", "凌云" }, { "ling zhe", "领着" }, { "ling zheng", "领证" }, { "ling zhi", "灵芝" },
			{ "ling zhu", "领主" }, { "ling zi", "领子" }, { "liu", "六" }, { "liu", "刘" }, { "liu", "劉" }, { "liu", "嚠" }, { "liu", "塯" }, { "liu", "媹" },
			{ "liu", "嬼" }, { "liu", "嵧" }, { "liu", "廇" }, { "liu", "懰" }, { "liu", "旒" }, { "liu", "柳" }, { "liu", "栁" }, { "liu", "榴" }, { "liu", "流" },
			{ "liu", "浏" }, { "liu", "溜" }, { "liu", "澑" }, { "liu", "瀏" }, { "liu", "熘" }, { "liu", "珋" }, { "liu", "琉" }, { "liu", "瑠" }, { "liu", "璢" },
			{ "liu", "畄" }, { "liu", "留" }, { "liu", "瘤" }, { "liu", "硫" }, { "liu", "碌" }, { "liu", "磟" }, { "liu", "綹" }, { "liu", "绺" }, { "liu", "罶" },
			{ "liu", "蓅" }, { "liu", "藰" }, { "liu", "蟉" }, { "liu", "裗" }, { "liu", "蹓" }, { "liu", "遛" }, { "liu", "鎏" }, { "liu", "鎦" }, { "liu", "鏐" },
			{ "liu", "锍" }, { "liu", "镏" }, { "liu", "陆" }, { "liu", "雡" }, { "liu", "霤" }, { "liu", "飀" }, { "liu", "飂" }, { "liu", "餾" }, { "liu", "馏" },
			{ "liu", "騮" }, { "liu", "骝" }, { "liu", "鰡" }, { "liu", "鶹" }, { "liu", "鷚" }, { "liu", "鹨" }, { "liu", "麍" }, { "liu an", "六安" },
			{ "liu bai", "六百" }, { "liu bang", "刘邦" }, { "liu bei", "刘备" }, { "liu bi ti", "流鼻涕" }, { "liu bi xue", "流鼻血" }, { "liu bin", "刘斌" },
			{ "liu bing", "溜冰" }, { "liu bo", "刘波" }, { "liu bu zhu", "留不住" }, { "liu chan", "流产" }, { "liu chang", "流畅" }, { "liu cheng", "六成" },
			{ "liu cheng", "流程" }, { "liu cheng tu", "流程图" }, { "liu chu", "流出" }, { "liu chu", "留出" }, { "liu chu lai", "流出来" }, { "liu chuan", "流传" },
			{ "liu chuan zhi", "柳传志" }, { "liu ci", "六次" }, { "liu cuan", "流窜" }, { "liu cun", "留存" }, { "liu da", "六大" }, { "liu da", "溜达" },
			{ "liu dao", "六道" }, { "liu dao", "流到" }, { "liu dao", "留到" }, { "liu de", "刘德" }, { "liu de", "留得" }, { "liu de hua", "刘德华" },
			{ "liu dian", "六点" }, { "liu dian", "留点" }, { "liu dian ban", "六点半" }, { "liu dong", "流动" }, { "liu dong ren kou", "流动人口" },
			{ "liu dong xing", "流动性" }, { "liu dong zi jin", "流动资金" }, { "liu fang", "刘芳" }, { "liu fang", "流放" }, { "liu fang hui tan", "六方会谈" },
			{ "liu gan", "流感" }, { "liu gang", "刘刚" }, { "liu ge", "六个" }, { "liu ge", "留个" }, { "liu ge yue", "六个月" }, { "liu gei", "留给" },
			{ "liu gou", "遛狗" }, { "liu guang", "流光" }, { "liu guang fei wu", "流光飞舞" }, { "liu guo", "六国" }, { "liu guo", "流过" }, { "liu hai", "刘海" },
			{ "liu han", "流汗" }, { "liu hao", "六号" }, { "liu he", "六合" }, { "liu he cai", "六合彩" }, { "liu hua", "硫化" }, { "liu huan", "刘欢" },
			{ "liu huang", "硫磺" }, { "liu ji", "六级" }, { "liu ji", "留级" }, { "liu jia", "刘佳" }, { "liu jia", "刘家" }, { "liu jia ling", "刘嘉玲" },
			{ "liu jian", "刘建" }, { "liu jing", "流经" }, { "liu jun", "刘军" }, { "liu kou shui", "流口水" }, { "liu lan", "浏览" }, { "liu lan liang", "浏览量" },
			{ "liu lan qi", "浏览器" }, { "liu lan wang ye", "浏览网页" }, { "liu lan zhe", "浏览者" }, { "liu lang", "流浪" }, { "liu lang gou", "流浪狗" },
			{ "liu lang han", "流浪汉" }, { "liu lang mao", "流浪猫" }, { "liu lang zhe", "流浪者" }, { "liu le", "流了" }, { "liu lei", "流泪" }, { "liu li", "刘力" },
			{ "liu li", "流利" }, { "liu li", "琉璃" }, { "liu lian", "榴莲" }, { "liu lian", "流连" }, { "liu lian", "留恋" }, { "liu lian wang fan", "流连忘返" },
			{ "liu liang", "流量" }, { "liu liang ji", "流量计" }, { "liu liu", "溜溜" }, { "liu lou", "六楼" }, { "liu lu", "流露" }, { "liu lu chu", "流露出" },
			{ "liu luo", "流落" }, { "liu mang", "流氓" }, { "liu mang ruan jian", "流氓软件" }, { "liu mei", "留美" }, { "liu mei ti", "流媒体" }, { "liu ming", "六名" },
			{ "liu ming", "刘明" }, { "liu ming", "留名" }, { "liu mou", "刘某" }, { "liu nian", "六年" }, { "liu nian", "流年" }, { "liu nian", "留念" },
			{ "liu nian ji", "六年级" }, { "liu pai", "流派" }, { "liu peng", "刘鹏" }, { "liu qi", "六七" }, { "liu qian", "六千" }, { "liu qing", "留情" },
			{ "liu qing yun", "刘青云" }, { "liu qiu", "琉球" }, { "liu ren", "六人" }, { "liu ren", "留人" }, { "liu ri", "六日" }, { "liu ru", "流入" },
			{ "liu ruo ying", "刘若英" }, { "liu sha", "流沙" }, { "liu shao qi", "刘少奇" }, { "liu shen", "留神" }, { "liu shi", "六十" }, { "liu shi", "流失" },
			{ "liu shi", "流逝" }, { "liu shi nian dai", "六十年代" }, { "liu shou", "留守" }, { "liu shou er tong", "留守儿童" }, { "liu shu", "柳树" },
			{ "liu shui", "流水" }, { "liu shui hao", "流水号" }, { "liu shui xian", "流水线" }, { "liu shui zhang", "流水帐" }, { "liu si", "六四" }, { "liu su", "流苏" },
			{ "liu su", "流速" }, { "liu suan", "硫酸" }, { "liu sui", "六岁" }, { "liu tang", "流淌" }, { "liu tao", "刘涛" }, { "liu ti", "流体" }, { "liu tian", "六天" },
			{ "liu tiao", "六条" }, { "liu tong", "流通" }, { "liu tong gu", "流通股" }, { "liu tong gu dong", "流通股东" }, { "liu tong ling yu", "流通领域" },
			{ "liu wan", "六万" }, { "liu wang", "流亡" }, { "liu wei", "六位" }, { "liu wei", "刘伟" }, { "liu wen", "刘文" }, { "liu xia", "流下" }, { "liu xia", "留下" },
			{ "liu xia lai", "留下来" }, { "liu xian", "流线" }, { "liu xian sheng", "刘先生" }, { "liu xiang", "六项" }, { "liu xiang", "刘翔" }, { "liu xiang", "流向" },
			{ "liu xiao", "刘晓" }, { "liu xiao", "留校" }, { "liu xiao qing", "刘晓庆" }, { "liu xin", "留心" }, { "liu xing", "刘星" }, { "liu xing", "流星" },
			{ "liu xing", "流行" }, { "liu xing bing xue", "流行病学" }, { "liu xing ge qu", "流行歌曲" }, { "liu xing qu shi", "流行趋势" }, { "liu xing xing", "流行性" },
			{ "liu xing yin yue", "流行音乐" }, { "liu xing yu", "流星雨" }, { "liu xu", "柳絮" }, { "liu xue", "流血" }, { "liu xue", "留学" },
			{ "liu xue ren yuan", "留学人员" }, { "liu xue sheng", "留学生" }, { "liu yan", "流言" }, { "liu yan", "留言" }, { "liu yan ban", "留言板" },
			{ "liu yan ben", "留言本" }, { "liu yan lei", "流眼泪" }, { "liu yang", "刘洋" }, { "liu yang", "浏阳" }, { "liu yang", "留洋" }, { "liu ye", "刘烨" },
			{ "liu yi", "六一" }, { "liu yi", "留意" }, { "liu yi fei", "刘亦菲" }, { "liu yi si", "刘易斯" }, { "liu ying", "留影" }, { "liu you", "留有" },
			{ "liu yu", "刘玉" }, { "liu yu", "流于" }, { "liu yu", "流域" }, { "liu yue", "六月" }, { "liu yue fen", "六月份" }, { "liu yun", "流云" },
			{ "liu zai", "留在" }, { "liu zhe", "流着" }, { "liu zhe", "留着" }, { "liu zhe lei", "流着泪" }, { "liu zhong", "六种" }, { "liu zhong quan hui", "六中全会" },
			{ "liu zhou", "柳州" }, { "liu zhou shi", "柳州市" }, { "liu zhu", "留住" }, { "liu zhuan", "流转" }, { "liu zong", "刘总" }, { "liu zou", "溜走" },
			{ "lo", "咯" }, { "long", "儱" }, { "long", "咙" }, { "long", "哢" }, { "long", "嚨" }, { "long", "垄" }, { "long", "垅" }, { "long", "壟" },
			{ "long", "嶐" }, { "long", "巃" }, { "long", "弄" }, { "long", "徿" }, { "long", "拢" }, { "long", "攏" }, { "long", "曨" }, { "long", "朧" },
			{ "long", "栊" }, { "long", "梇" }, { "long", "槞" }, { "long", "櫳" }, { "long", "泷" }, { "long", "瀧" }, { "long", "珑" }, { "long", "瓏" },
			{ "long", "癃" }, { "long", "矓" }, { "long", "砻" }, { "long", "礱" }, { "long", "窿" }, { "long", "竜" }, { "long", "笼" }, { "long", "篢" },
			{ "long", "篭" }, { "long", "籠" }, { "long", "聋" }, { "long", "聾" }, { "long", "胧" }, { "long", "茏" }, { "long", "蘢" }, { "long", "蠪" },
			{ "long", "蠬" }, { "long", "襱" }, { "long", "谾" }, { "long", "豅" }, { "long", "躘" }, { "long", "鏧" }, { "long", "鑨" }, { "long", "陇" },
			{ "long", "隆" }, { "long", "隴" }, { "long", "霳" }, { "long", "靇" }, { "long", "鸗" }, { "long", "龍" }, { "long", "龙" }, { "long cheng", "龙城" },
			{ "long duan", "垄断" }, { "long duan hang ye", "垄断行业" }, { "long duan xing", "垄断性" }, { "long fei", "龙飞" }, { "long feng", "龙凤" },
			{ "long gang", "龙岗" }, { "long gang qu", "龙岗区" }, { "long ge", "龙哥" }, { "long gong", "龙宫" }, { "long gu", "龙骨" }, { "long hu", "龙湖" },
			{ "long hu", "龙虎" }, { "long hua", "龙华" }, { "long jiang", "龙江" }, { "long jing", "龙井" }, { "long juan feng", "龙卷风" }, { "long ka", "龙卡" },
			{ "long long", "隆隆" }, { "long long", "龙龙" }, { "long ma", "龙马" }, { "long mao", "龙猫" }, { "long men", "龙门" }, { "long nv", "龙女" },
			{ "long qi", "隆起" }, { "long qi shi", "龙骑士" }, { "long quan", "龙泉" }, { "long shan", "龙山" }, { "long tan", "龙潭" }, { "long teng", "龙腾" },
			{ "long tong", "笼统" }, { "long tou", "龙头" }, { "long tou qi ye", "龙头企业" }, { "long wang", "龙王" }, { "long xia", "龙虾" }, { "long xin", "龙芯" },
			{ "long xiong", "隆胸" }, { "long yan", "龙岩" }, { "long yan", "龙眼" }, { "long zhao", "笼罩" }, { "long zhong", "隆重" },
			{ "long zhong ju xing", "隆重举行" }, { "long zhong tui chu", "隆重推出" }, { "long zhou", "龙舟" }, { "long zhu", "龙珠" }, { "long zi", "笼子" },
			{ "long zu", "龙族" }, { "lou", "偻" }, { "lou", "僂" }, { "lou", "喽" }, { "lou", "嘍" }, { "lou", "塿" }, { "lou", "娄" }, { "lou", "婁" },
			{ "lou", "嵝" }, { "lou", "嶁" }, { "lou", "廔" }, { "lou", "搂" }, { "lou", "摟" }, { "lou", "楼" }, { "lou", "樓" }, { "lou", "漏" }, { "lou", "熡" },
			{ "lou", "瘘" }, { "lou", "瘺" }, { "lou", "瞜" }, { "lou", "窶" }, { "lou", "篓" }, { "lou", "耧" }, { "lou", "耬" }, { "lou", "艛" }, { "lou", "蒌" },
			{ "lou", "蝼" }, { "lou", "螻" }, { "lou", "鏤" }, { "lou", "镂" }, { "lou", "陋" }, { "lou", "露" }, { "lou", "鞻" }, { "lou", "髅" }, { "lou", "髏" },
			{ "lou ban", "楼板" }, { "lou ceng", "楼层" }, { "lou chu", "露出" }, { "lou dao", "楼道" }, { "lou dao li", "楼道里" }, { "lou di", "娄底" },
			{ "lou dian", "漏电" }, { "lou diao", "漏掉" }, { "lou ding", "楼顶" }, { "lou dong", "漏洞" }, { "lou dou", "漏斗" }, { "lou fang", "楼房" },
			{ "lou jia", "楼价" }, { "lou kong", "镂空" }, { "lou lan", "楼兰" }, { "lou li", "楼里" }, { "lou lian", "露脸" }, { "lou mian", "楼面" },
			{ "lou mian", "露面" }, { "lou pan", "楼盘" }, { "lou shang", "楼上" }, { "lou shi", "楼市" }, { "lou shui", "漏水" }, { "lou ti", "楼梯" },
			{ "lou xi", "陋习" }, { "lou xia", "楼下" }, { "lou xian", "露馅" }, { "lou you", "漏油" }, { "lou yu", "楼宇" }, { "lou zai", "搂在" }, { "lou zhe", "搂着" },
			{ "lou zhu", "搂住" }, { "lou zhu", "楼主" }, { "lu", "僇" }, { "lu", "六" }, { "lu", "勠" }, { "lu", "卢" }, { "lu", "卤" }, { "lu", "噜" }, { "lu", "嚕" },
			{ "lu", "嚧" }, { "lu", "坴" }, { "lu", "垆" }, { "lu", "塶" }, { "lu", "壚" }, { "lu", "庐" }, { "lu", "廘" }, { "lu", "廬" }, { "lu", "彔" },
			{ "lu", "录" }, { "lu", "戮" }, { "lu", "挔" }, { "lu", "掳" }, { "lu", "摝" }, { "lu", "撸" }, { "lu", "擄" }, { "lu", "擼" }, { "lu", "枦" },
			{ "lu", "栌" }, { "lu", "橹" }, { "lu", "櫓" }, { "lu", "氇" }, { "lu", "氌" }, { "lu", "泸" }, { "lu", "淕" }, { "lu", "淥" }, { "lu", "渌" },
			{ "lu", "滷" }, { "lu", "漉" }, { "lu", "漊" }, { "lu", "潞" }, { "lu", "濾" }, { "lu", "瀘" }, { "lu", "炉" }, { "lu", "熝" }, { "lu", "爐" },
			{ "lu", "玈" }, { "lu", "琭" }, { "lu", "璐" }, { "lu", "璷" }, { "lu", "甪" }, { "lu", "盝" }, { "lu", "盧" }, { "lu", "睩" }, { "lu", "硉" },
			{ "lu", "碌" }, { "lu", "磠" }, { "lu", "祿" }, { "lu", "禄" }, { "lu", "稑" }, { "lu", "穋" }, { "lu", "簏" }, { "lu", "簬" }, { "lu", "籙" },
			{ "lu", "籚" }, { "lu", "纑" }, { "lu", "绿" }, { "lu", "罏" }, { "lu", "翏" }, { "lu", "胪" }, { "lu", "膟" }, { "lu", "臚" }, { "lu", "舮" },
			{ "lu", "舻" }, { "lu", "艣" }, { "lu", "艪" }, { "lu", "艫" }, { "lu", "芦" }, { "lu", "菉" }, { "lu", "蓾" }, { "lu", "蔍" }, { "lu", "蕗" },
			{ "lu", "蘆" }, { "lu", "虏" }, { "lu", "虜" }, { "lu", "螰" }, { "lu", "蠦" }, { "lu", "觻" }, { "lu", "賂" }, { "lu", "赂" }, { "lu", "路" },
			{ "lu", "踛" }, { "lu", "蹗" }, { "lu", "轆" }, { "lu", "轤" }, { "lu", "轳" }, { "lu", "辂" }, { "lu", "辘" }, { "lu", "逯" }, { "lu", "醁" },
			{ "lu", "鈩" }, { "lu", "錄" }, { "lu", "錴" }, { "lu", "鏀" }, { "lu", "鏕" }, { "lu", "鐪" }, { "lu", "鑪" }, { "lu", "镥" }, { "lu", "陆" },
			{ "lu", "陸" }, { "lu", "露" }, { "lu", "顱" }, { "lu", "颅" }, { "lu", "騄" }, { "lu", "魯" }, { "lu", "魲" }, { "lu", "鯥" }, { "lu", "鱸" },
			{ "lu", "鲁" }, { "lu", "鲈" }, { "lu", "鵱" }, { "lu", "鷺" }, { "lu", "鸕" }, { "lu", "鸬" }, { "lu", "鹭" }, { "lu", "鹵" }, { "lu", "鹿" },
			{ "lu", "麓" }, { "lu bian", "路边" }, { "lu biao", "路标" }, { "lu bu", "卢布" }, { "lu cheng", "路程" }, { "lu chu", "露出" }, { "lu chuan zhong", "路传中" },
			{ "lu deng", "路灯" }, { "lu di", "陆地" }, { "lu dian", "露点" }, { "lu ding ji", "鹿鼎记" }, { "lu duan", "路段" }, { "lu fei", "路费" },
			{ "lu fu gong", "卢浮宫" }, { "lu gong jiao che", "路公交车" }, { "lu gu", "露骨" }, { "lu gu hu", "泸沽湖" }, { "lu guo", "路过" }, { "lu guo", "鲁国" },
			{ "lu hu", "路虎" }, { "lu hui", "芦荟" }, { "lu ji", "路基" }, { "lu jia zui", "陆家嘴" }, { "lu jing", "路径" }, { "lu jun", "陆军" }, { "lu kao", "路考" },
			{ "lu kou", "路口" }, { "lu kuang", "路况" }, { "lu lu", "璐璐" }, { "lu lu", "陆路" }, { "lu lu", "露露" }, { "lu lu xu xu", "陆陆续续" }, { "lu mang", "鲁莽" },
			{ "lu mian", "路面" }, { "lu mian", "露面" }, { "lu nei", "颅内" }, { "lu neng", "鲁能" }, { "lu ni", "鲁尼" }, { "lu pai", "路牌" }, { "lu pang", "路旁" },
			{ "lu qiao", "路桥" }, { "lu qu", "录取" }, { "lu ren", "路人" }, { "lu ru", "录入" }, { "lu sen bao", "卢森堡" }, { "lu shan", "庐山" }, { "lu shang", "路上" },
			{ "lu shang", "陆上" }, { "lu shui", "露水" }, { "lu su", "露宿" }, { "lu tai", "露台" }, { "lu tao", "陆涛" }, { "lu tian", "露天" }, { "lu tou", "路透" },
			{ "lu tou she", "路透社" }, { "lu tu", "路途" }, { "lu wang", "路网" }, { "lu wei", "芦苇" }, { "lu wu xuan", "卢武铉" }, { "lu xian", "路线" },
			{ "lu xian tu", "路线图" }, { "lu xiang", "录像" }, { "lu xiang", "录象" }, { "lu xiang dai", "录像带" }, { "lu xiang ji", "录像机" }, { "lu xu", "陆续" },
			{ "lu xun", "鲁迅" }, { "lu xun xian sheng", "鲁迅先生" }, { "lu yan", "路演" }, { "lu yi", "路易" }, { "lu yi", "陆毅" }, { "lu yi si", "路易斯" },
			{ "lu yin", "录音" }, { "lu yin bi", "录音笔" }, { "lu yin dai", "录音带" }, { "lu yin ji", "录音机" }, { "lu yin shi", "录音室" }, { "lu ying", "录影" },
			{ "lu ying", "露营" }, { "lu yong", "录用" }, { "lu you", "路由" }, { "lu you", "陆游" }, { "lu you qi", "路由器" }, { "lu yu", "鲁豫" }, { "lu zhi", "录制" },
			{ "lu zhou", "泸州" }, { "lu zhu", "露珠" }, { "lu zi", "炉子" }, { "lu zi", "路子" }, { "luan", "乱" }, { "luan", "亂" }, { "luan", "卵" }, { "luan", "圞" },
			{ "luan", "奱" }, { "luan", "娈" }, { "luan", "孌" }, { "luan", "孪" }, { "luan", "孿" }, { "luan", "峦" }, { "luan", "巒" }, { "luan", "挛" },
			{ "luan", "攣" }, { "luan", "曫" }, { "luan", "栾" }, { "luan", "欒" }, { "luan", "滦" }, { "luan", "灤" }, { "luan", "癵" }, { "luan", "羉" },
			{ "luan", "脔" }, { "luan", "臠" }, { "luan", "銮" }, { "luan", "鑾" }, { "luan", "鸞" }, { "luan", "鸾" }, { "luan chao", "卵巢" }, { "luan da", "乱打" },
			{ "luan dong", "乱动" }, { "luan fa", "乱发" }, { "luan fei", "乱飞" }, { "luan gao", "乱搞" }, { "luan hua", "乱花" }, { "luan jiang", "乱讲" },
			{ "luan jiao", "乱叫" }, { "luan lai", "乱来" }, { "luan le", "乱了" }, { "luan luan", "乱乱" }, { "luan lun", "乱伦" }, { "luan ma", "乱码" },
			{ "luan pao", "乱跑" }, { "luan pao", "卵泡" }, { "luan qi ba zao", "乱七八糟" }, { "luan reng", "乱扔" }, { "luan shi", "乱世" }, { "luan shou fei", "乱收费" },
			{ "luan shuo", "乱说" }, { "luan tan", "乱弹" }, { "luan tao", "乱套" }, { "luan wu", "乱舞" }, { "luan xiang", "乱想" }, { "luan xiang", "乱象" },
			{ "luan xie", "乱写" }, { "luan yong", "乱用" }, { "luan zao zao", "乱糟糟" }, { "luan zi", "卵子" }, { "lue", "掠" }, { "lue", "略" }, { "lue", "畧" },
			{ "lue", "鋝" }, { "lue", "锊" }, { "lue dai", "略带" }, { "lue di", "略低" }, { "lue duo", "掠夺" }, { "lue guo", "掠过" }, { "lue wei", "略微" },
			{ "lue xian", "略显" }, { "lue you", "略有" }, { "lun", "仑" }, { "lun", "伦" }, { "lun", "侖" }, { "lun", "倫" }, { "lun", "囵" }, { "lun", "圇" },
			{ "lun", "崘" }, { "lun", "崙" }, { "lun", "惀" }, { "lun", "抡" }, { "lun", "掄" }, { "lun", "棆" }, { "lun", "沦" }, { "lun", "淪" }, { "lun", "溣" },
			{ "lun", "睔" }, { "lun", "碖" }, { "lun", "稐" }, { "lun", "綸" }, { "lun", "纶" }, { "lun", "菕" }, { "lun", "蜦" }, { "lun", "論" }, { "lun", "论" },
			{ "lun", "踚" }, { "lun", "輪" }, { "lun", "轮" }, { "lun", "錀" }, { "lun", "陯" }, { "lun chuan", "轮船" }, { "lun dao", "轮到" }, { "lun dian", "论点" },
			{ "lun diao", "论调" }, { "lun du", "轮渡" }, { "lun duan", "论断" }, { "lun dun", "伦敦" }, { "lun fan", "轮番" }, { "lun gu", "轮毂" }, { "lun hua", "轮滑" },
			{ "lun huan", "轮换" }, { "lun hui", "轮回" }, { "lun jian", "轮奸" }, { "lun ju", "论据" }, { "lun kuo", "轮廓" }, { "lun li", "伦理" },
			{ "lun li dao de", "伦理道德" }, { "lun li xue", "伦理学" }, { "lun liu", "轮流" }, { "lun luo", "沦落" }, { "lun pan", "轮盘" }, { "lun sang", "沦丧" },
			{ "lun shu", "论述" }, { "lun tai", "轮胎" }, { "lun tan", "论坛" }, { "lun tan", "论谈" }, { "lun tan hui yuan", "论坛会员" }, { "lun tan li", "论坛里" },
			{ "lun ti", "论题" }, { "lun wei", "沦为" }, { "lun wen", "论文" }, { "lun wen ji", "论文集" }, { "lun xian", "沦陷" }, { "lun yi", "轮椅" },
			{ "lun yu", "论语" }, { "lun zhan", "论战" }, { "lun zhe", "论者" }, { "lun zheng", "论证" }, { "lun zi", "轮子" }, { "luo", "倮" }, { "luo", "儸" },
			{ "luo", "儽" }, { "luo", "剆" }, { "luo", "咯" }, { "luo", "囉" }, { "luo", "峈" }, { "luo", "捋" }, { "luo", "摞" }, { "luo", "攎" }, { "luo", "攭" },
			{ "luo", "椤" }, { "luo", "欏" }, { "luo", "欙" }, { "luo", "泺" }, { "luo", "洛" }, { "luo", "漯" }, { "luo", "烙" }, { "luo", "犖" }, { "luo", "猓" },
			{ "luo", "猡" }, { "luo", "玀" }, { "luo", "珞" }, { "luo", "瘰" }, { "luo", "皪" }, { "luo", "硌" }, { "luo", "礫" }, { "luo", "箩" }, { "luo", "籮" },
			{ "luo", "絡" }, { "luo", "纙" }, { "luo", "络" }, { "luo", "罗" }, { "luo", "羅" }, { "luo", "脶" }, { "luo", "腡" }, { "luo", "臝" }, { "luo", "茖" },
			{ "luo", "荦" }, { "luo", "萝" }, { "luo", "落" }, { "luo", "蓏" }, { "luo", "蘿" }, { "luo", "螺" }, { "luo", "蠃" }, { "luo", "裸" }, { "luo", "覶" },
			{ "luo", "詻" }, { "luo", "跞" }, { "luo", "逻" }, { "luo", "邏" }, { "luo", "鏍" }, { "luo", "鑼" }, { "luo", "锣" }, { "luo", "镙" }, { "luo", "雒" },
			{ "luo", "駱" }, { "luo", "騾" }, { "luo", "骆" }, { "luo", "骡" }, { "luo", "鮥" }, { "luo", "鱳" }, { "luo", "鵅" }, { "luo", "鸁" },
			{ "luo bai", "落败" }, { "luo bang", "落榜" }, { "luo ben", "罗本" }, { "luo ben", "裸奔" }, { "luo bin", "罗宾" }, { "luo bo", "萝卜" },
			{ "luo bo te", "罗伯特" }, { "luo bu po", "罗布泊" }, { "luo cha", "落差" }, { "luo cheng", "落成" }, { "luo da you", "罗大佑" }, { "luo dan", "罗丹" },
			{ "luo dao shi chu", "落到实处" }, { "luo de", "落得" }, { "luo di", "落地" }, { "luo dian", "落点" }, { "luo ding", "螺钉" }, { "luo fu", "洛夫" },
			{ "luo fu", "罗夫" }, { "luo fu", "罗孚" }, { "luo ge", "罗格" }, { "luo gu", "锣鼓" }, { "luo han", "罗汉" }, { "luo he", "漯河" }, { "luo hou", "落后" },
			{ "luo hu", "罗湖" }, { "luo hu", "落户" }, { "luo hu qu", "罗湖区" }, { "luo hua", "落花" }, { "luo ji", "罗技" }, { "luo ji", "逻辑" },
			{ "luo ji xing", "逻辑性" }, { "luo jiao", "落脚" }, { "luo jiao dian", "落脚点" }, { "luo jie", "罗杰" }, { "luo jie si", "罗杰斯" },
			{ "luo jing xia shi", "落井下石" }, { "luo ke", "洛克" }, { "luo kong", "落空" }, { "luo kuan", "落款" }, { "luo la", "罗拉" }, { "luo lan", "罗兰" },
			{ "luo le", "落了" }, { "luo lei", "落泪" }, { "luo li", "萝莉" }, { "luo liao", "裸聊" }, { "luo lie", "罗列" }, { "luo lu", "裸露" }, { "luo luo", "落落" },
			{ "luo ma", "罗马" }, { "luo ma", "落马" }, { "luo ma di guo", "罗马帝国" }, { "luo ma ni ya", "罗马尼亚" }, { "luo mi ou", "罗密欧" }, { "luo mo", "落寞" },
			{ "luo mu", "落幕" }, { "luo mu", "螺母" }, { "luo na", "罗纳" }, { "luo na er duo", "罗纳尔多" }, { "luo ni", "罗尼" }, { "luo nv", "裸女" },
			{ "luo pan", "罗盘" }, { "luo po", "落魄" }, { "luo qi", "洛奇" }, { "luo qu", "落去" }, { "luo ri", "落日" }, { "luo ru", "落入" }, { "luo shan ji", "洛杉矶" },
			{ "luo shang", "罗裳" }, { "luo shi", "罗氏" }, { "luo shi", "落实" }, { "luo shi qing kuang", "落实情况" }, { "luo shuan", "螺栓" }, { "luo shui", "落水" },
			{ "luo shui", "裸睡" }, { "luo si", "罗斯" }, { "luo si", "螺丝" }, { "luo si dao", "螺丝刀" }, { "luo si fu", "罗斯福" }, { "luo su", "罗素" },
			{ "luo suo", "罗嗦" }, { "luo ti", "裸体" }, { "luo tuo", "骆驼" }, { "luo wang", "落网" }, { "luo wen", "螺纹" }, { "luo wu", "落伍" }, { "luo xi", "罗西" },
			{ "luo xia", "落下" }, { "luo xuan", "落选" }, { "luo xuan", "螺旋" }, { "luo xuan zao", "螺旋藻" }, { "luo yang", "洛阳" }, { "luo yang shi", "洛阳市" },
			{ "luo ye", "落叶" }, { "luo yi", "罗衣" }, { "luo yi bu jue", "络绎不绝" }, { "luo yu", "落于" }, { "luo yu", "落雨" } };
};
