package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN44 {
	public static String[][] pl = { { "shui bo", "水波" }, { "shui bu", "谁不" }, { "shui bu hao", "睡不好" }, { "shui bu zhao", "睡不着" }, { "shui cao", "水槽" },
			{ "shui cao", "水草" }, { "shui chan", "水产" }, { "shui chan pin", "水产品" }, { "shui chan yang zhi", "水产养殖" }, { "shui chang", "水厂" },
			{ "shui cheng", "水城" }, { "shui chi", "水池" }, { "shui chu li", "水处理" }, { "shui dai", "睡袋" }, { "shui dao", "水稻" }, { "shui dao", "水道" },
			{ "shui dao", "睡到" }, { "shui dao qu cheng", "水到渠成" }, { "shui de", "睡得" }, { "shui de", "谁的" }, { "shui di", "水底" }, { "shui di", "水滴" },
			{ "shui dian", "水电" }, { "shui dian fei", "水电费" }, { "shui dian zhan", "水电站" }, { "shui dou", "水痘" }, { "shui dou", "谁都" },
			{ "shui dou hui", "谁都会" }, { "shui e", "税额" }, { "shui fa", "税法" }, { "shui fei", "水费" }, { "shui fei", "税费" }, { "shui fen", "水分" },
			{ "shui fu", "税负" }, { "shui fu", "说服" }, { "shui gan", "谁敢" }, { "shui ge", "睡个" }, { "shui gou", "水沟" }, { "shui guan", "水管" },
			{ "shui guo", "水果" }, { "shui guo", "睡过" }, { "shui hai", "谁还" }, { "shui hao", "睡好" }, { "shui he", "水和" }, { "shui hou", "税后" },
			{ "shui hu", "水壶" }, { "shui hu", "水浒" }, { "shui hu zhuan", "水浒传" }, { "shui hua", "水花" }, { "shui huan jing", "水环境" }, { "shui hui", "谁会" },
			{ "shui huo", "水火" }, { "shui huo", "水货" }, { "shui jia", "水价" }, { "shui jia", "谁家" }, { "shui jian", "水煎" }, { "shui jiao", "水饺" },
			{ "shui jiao", "睡觉" }, { "shui jiao", "谁叫" }, { "shui jiao ni", "谁叫你" }, { "shui jiao qian", "睡觉前" }, { "shui jie", "水解" }, { "shui jin", "税金" },
			{ "shui jing", "水井" }, { "shui jing", "水景" }, { "shui jing", "水晶" }, { "shui jiu", "谁就" }, { "shui jun", "水军" }, { "shui ku", "水库" },
			{ "shui kuan", "税款" }, { "shui lai", "谁来" }, { "shui lan jiao", "睡懒觉" }, { "shui leng", "水冷" }, { "shui li", "水利" }, { "shui li", "水力" },
			{ "shui li", "水里" }, { "shui li bu", "水利部" }, { "shui li fang", "水立方" }, { "shui li gong cheng", "水利工程" }, { "shui li jian she", "水利建设" },
			{ "shui li ju", "水利局" }, { "shui liang", "水量" }, { "shui ling", "水灵" }, { "shui liu", "水流" }, { "shui long tou", "水龙头" }, { "shui lu", "水路" },
			{ "shui luo shi chu", "水落石出" }, { "shui lv", "税率" }, { "shui meng", "睡梦" }, { "shui mian", "水面" }, { "shui mian", "睡眠" },
			{ "shui mian bu zu", "睡眠不足" }, { "shui mian shi jian", "睡眠时间" }, { "shui mo", "水墨" }, { "shui mu", "水木" }, { "shui mu", "水母" },
			{ "shui ne", "谁呢" }, { "shui neng", "谁能" }, { "shui ni", "水泥" }, { "shui ni chang", "水泥厂" }, { "shui ni lu", "水泥路" }, { "shui niu", "水牛" },
			{ "shui pao", "水泡" }, { "shui ping", "水平" }, { "shui ping", "水瓶" }, { "shui ping zuo", "水瓶座" }, { "shui qi", "水气" }, { "shui qi", "水汽" },
			{ "shui qian", "睡前" }, { "shui qian", "税前" }, { "shui qu", "水区" }, { "shui qu", "睡去" }, { "shui qu", "谁去" }, { "shui rang", "谁让" },
			{ "shui rang ni", "谁让你" }, { "shui rong xing", "水溶性" }, { "shui se", "水色" }, { "shui shang", "水上" }, { "shui shen", "水深" },
			{ "shui shen huo re", "水深火热" }, { "shui sheng", "水声" }, { "shui sheng", "水生" }, { "shui shi", "谁是" }, { "shui shi shui", "谁是谁" },
			{ "shui shou", "水手" }, { "shui shou", "税收" }, { "shui shou shou ru", "税收收入" }, { "shui shou you hui", "税收优惠" }, { "shui shou zheng ce", "税收政策" },
			{ "shui shou zheng guan", "税收征管" }, { "shui shui", "水水" }, { "shui shui", "睡睡" }, { "shui shui", "谁谁" }, { "shui shui guan guan", "水水灌灌" },
			{ "shui shui shui", "水水水" }, { "shui shuo", "谁说" }, { "shui tang", "水塘" }, { "shui ti", "水体" }, { "shui tian", "水田" }, { "shui tie", "水贴" },
			{ "shui tong", "水桶" }, { "shui tu", "水土" }, { "shui tu bao chi", "水土保持" }, { "shui tu bu fu", "水土不服" }, { "shui tu liu shi", "水土流失" },
			{ "shui wei", "水位" }, { "shui wen", "水文" }, { "shui wen", "水温" }, { "shui wu", "水务" }, { "shui wu", "税务" }, { "shui wu deng ji", "税务登记" },
			{ "shui wu ji guan", "税务机关" }, { "shui wu jiao", "睡午觉" }, { "shui wu ju", "税务局" }, { "shui wu ran", "水污染" }, { "shui xi", "水洗" },
			{ "shui xi", "水系" }, { "shui xia", "水下" }, { "shui xia", "睡下" }, { "shui xian", "水仙" }, { "shui xian", "谁先" }, { "shui xiang", "水乡" },
			{ "shui xiang", "水箱" }, { "shui xing", "水性" }, { "shui xing", "水星" }, { "shui xing", "睡醒" }, { "shui ya", "水压" }, { "shui ya", "谁呀" },
			{ "shui yang", "水样" }, { "shui yao", "谁要" }, { "shui ye", "谁也" }, { "shui ye bu", "谁也不" }, { "shui yi", "睡意" }, { "shui yi", "睡衣" },
			{ "shui yin", "水印" }, { "shui yin", "水银" }, { "shui you", "谁又" }, { "shui you", "谁有" }, { "shui yu", "水域" }, { "shui yuan", "水源" },
			{ "shui yuan", "税源" }, { "shui yuan di", "水源地" }, { "shui yuan su", "水元素" }, { "shui yue", "水月" }, { "shui yun", "水运" }, { "shui zai", "水灾" },
			{ "shui zai", "睡在" }, { "shui zai", "谁在" }, { "shui zha", "水闸" }, { "shui zhang chuan gao", "水涨船高" }, { "shui zhao", "睡着" }, { "shui zhe", "睡着" },
			{ "shui zheng qi", "水蒸汽" }, { "shui zhi", "水质" }, { "shui zhi", "税制" }, { "shui zhi", "谁知" }, { "shui zhi dao", "谁知道" }, { "shui zhong", "水中" },
			{ "shui zhong", "水肿" }, { "shui zhong", "税种" }, { "shui zhu", "水煮" }, { "shui zhu", "水珠" }, { "shui zhu yu", "水煮鱼" }, { "shui zhun", "水准" },
			{ "shui zi yuan", "水资源" }, { "shui zu", "水族" }, { "shun", "吮" }, { "shun", "巛" }, { "shun", "楯" }, { "shun", "橓" }, { "shun", "瞚" },
			{ "shun", "瞬" }, { "shun", "舜" }, { "shun", "蕣" }, { "shun", "輴" }, { "shun", "順" }, { "shun", "顺" }, { "shun", "鬊" }, { "shun bian", "顺便" },
			{ "shun cha", "顺差" }, { "shun chan", "顺产" }, { "shun chang", "顺畅" }, { "shun chi", "顺驰" }, { "shun cong", "顺从" }, { "shun dai", "顺带" },
			{ "shun dao", "顺道" }, { "shun de", "顺德" }, { "shun de qu", "顺德区" }, { "shun fa", "顺发" }, { "shun feng", "顺丰" }, { "shun feng", "顺风" },
			{ "shun feng che", "顺风车" }, { "shun jian", "瞬间" }, { "shun kou", "顺口" }, { "shun kou liu", "顺口溜" }, { "shun li", "顺利" },
			{ "shun li cheng zhang", "顺理成章" }, { "shun li jin xing", "顺利进行" }, { "shun li tong guo", "顺利通过" }, { "shun li wan cheng", "顺利完成" },
			{ "shun lu", "顺路" }, { "shun qi zi ran", "顺其自然" }, { "shun shi", "瞬时" }, { "shun shi", "顺势" }, { "shun shi zhen", "顺时针" }, { "shun shou", "顺手" },
			{ "shun tian", "舜天" }, { "shun xi", "吮吸" }, { "shun xin", "顺心" }, { "shun xu", "顺序" }, { "shun yan", "顺延" }, { "shun yan", "顺眼" },
			{ "shun yi", "顺义" }, { "shun ying", "顺应" }, { "shun zhe", "顺着" }, { "shun zhi", "顺治" }, { "shun zhu", "顺祝" }, { "shun zi", "顺子" }, { "shuo", "妁" },
			{ "shuo", "搠" }, { "shuo", "数" }, { "shuo", "朔" }, { "shuo", "槊" }, { "shuo", "烁" }, { "shuo", "爍" }, { "shuo", "硕" }, { "shuo", "碩" },
			{ "shuo", "蒴" }, { "shuo", "說" }, { "shuo", "说" }, { "shuo", "鎙" }, { "shuo", "铄" }, { "shuo ba", "说吧" }, { "shuo ba", "说罢" },
			{ "shuo bai le", "说白了" }, { "shuo bu", "说不" }, { "shuo bu chu", "说不出" }, { "shuo bu ding", "说不定" }, { "shuo bu guo qu", "说不过去" },
			{ "shuo bu qing", "说不清" }, { "shuo bu qing chu", "说不清楚" }, { "shuo bu shang", "说不上" }, { "shuo chang", "说唱" }, { "shuo cheng", "说成" },
			{ "shuo chu", "说出" }, { "shuo chu kou", "说出口" }, { "shuo ci", "说辞" }, { "shuo cuo", "说错" }, { "shuo da", "硕大" }, { "shuo dao", "说到" },
			{ "shuo dao", "说道" }, { "shuo dao di", "说到底" }, { "shuo de", "说得" }, { "shuo de", "说的" }, { "shuo de hao", "说得好" }, { "shuo dian", "说点" },
			{ "shuo fa", "说法" }, { "shuo fu", "说服" }, { "shuo fu li", "说服力" }, { "shuo ge", "说个" }, { "shuo gei", "说给" }, { "shuo guo", "硕果" },
			{ "shuo guo", "说过" }, { "shuo hao", "说好" }, { "shuo hua", "说话" }, { "shuo huang", "说谎" }, { "shuo jiao", "说教" }, { "shuo ju", "说句" },
			{ "shuo lai", "说来" }, { "shuo lai shuo qu", "说来说去" }, { "shuo le", "说了" }, { "shuo le suan", "说了算" }, { "shuo li", "说理" }, { "shuo ming", "说明" },
			{ "shuo ming shen me", "说明什么" }, { "shuo ming shu", "说明书" }, { "shuo na", "说那" }, { "shuo ne", "说呢" }, { "shuo qi", "说起" }, { "shuo qing", "说清" },
			{ "shuo san dao si", "说三道四" }, { "shuo sha", "说啥" }, { "shuo sheng", "说声" }, { "shuo shi", "硕士" }, { "shuo shi", "说事" }, { "shuo shi", "说是" },
			{ "shuo shi sheng", "硕士生" }, { "shuo shi xue wei", "硕士学位" }, { "shuo shuo", "说说" }, { "shuo wan", "说完" }, { "shuo xiao", "说笑" },
			{ "shuo xie", "说些" }, { "shuo yao", "说要" }, { "shuo yi ju", "说一句" }, { "shuo yi sheng", "说一声" }, { "shuo you", "说有" }, { "shuo zhe", "说着" },
			{ "si", "丝" }, { "si", "伺" }, { "si", "似" }, { "si", "価" }, { "si", "俟" }, { "si", "俬" }, { "si", "偲" }, { "si", "儩" }, { "si", "兕" },
			{ "si", "凘" }, { "si", "厮" }, { "si", "厶" }, { "si", "司" }, { "si", "咝" }, { "si", "嗣" }, { "si", "嘶" }, { "si", "四" }, { "si", "姒" },
			{ "si", "媤" }, { "si", "寺" }, { "si", "巳" }, { "si", "廝" }, { "si", "思" }, { "si", "撕" }, { "si", "斯" }, { "si", "柶" }, { "si", "梩" },
			{ "si", "楒" }, { "si", "榹" }, { "si", "死" }, { "si", "汜" }, { "si", "泀" }, { "si", "泗" }, { "si", "洍" }, { "si", "涘" }, { "si", "澌" },
			{ "si", "祀" }, { "si", "禗" }, { "si", "禠" }, { "si", "私" }, { "si", "竢" }, { "si", "笥" }, { "si", "絲" }, { "si", "緦" }, { "si", "纟" },
			{ "si", "缌" }, { "si", "罳" }, { "si", "耜" }, { "si", "肂" }, { "si", "肆" }, { "si", "蕬" }, { "si", "蕼" }, { "si", "虒" }, { "si", "蛳" },
			{ "si", "螄" }, { "si", "蟴" }, { "si", "覗" }, { "si", "貄" }, { "si", "鉰" }, { "si", "锶" }, { "si", "颸" }, { "si", "食" }, { "si", "飼" },
			{ "si", "饲" }, { "si", "駟" }, { "si", "驷" }, { "si", "鷥" }, { "si", "鸶" }, { "si", "鼶" }, { "si ba da", "斯巴达" }, { "si bai", "四百" },
			{ "si ban", "死板" }, { "si bei", "四倍" }, { "si ben", "私奔" }, { "si bu", "四部" }, { "si bu", "死不" }, { "si ceng", "四层" },
			{ "si ceng xiang shi", "似曾相识" }, { "si chan", "死缠" }, { "si chao", "思潮" }, { "si che", "撕扯" }, { "si che", "私车" }, { "si cheng", "四成" },
			{ "si chou", "丝绸" }, { "si chou zhi lu", "丝绸之路" }, { "si chu", "四处" }, { "si chu", "私处" }, { "si chuan", "四川" }, { "si chuan da xue", "四川大学" },
			{ "si chuan ren", "四川人" }, { "si chuan sheng", "四川省" }, { "si ci", "四次" }, { "si da", "四大" }, { "si da kang", "斯达康" }, { "si da lin", "斯大林" },
			{ "si da tian wang", "四大天王" }, { "si dai", "丝带" }, { "si dai", "四代" }, { "si dang", "死党" }, { "si de", "似的" }, { "si de", "死得" },
			{ "si de", "死的" }, { "si di", "死地" }, { "si di fen", "斯蒂芬" }, { "si di xia", "私底下" }, { "si dian", "四点" }, { "si diao", "撕掉" },
			{ "si diao", "死掉" }, { "si fa", "司法" }, { "si fa bu", "司法部" }, { "si fa bu men", "司法部门" }, { "si fa gong zheng", "司法公正" },
			{ "si fa ji guan", "司法机关" }, { "si fa jian ding", "司法鉴定" }, { "si fa jie shi", "司法解释" }, { "si fa ju", "司法局" }, { "si fa kao shi", "司法考试" },
			{ "si fa xing zheng", "司法行政" }, { "si fang", "四方" }, { "si fang", "私房" }, { "si fang qian", "私房钱" }, { "si fen", "四分" }, { "si fen zhi", "四分之" },
			{ "si fu", "司副" }, { "si fu", "私服" }, { "si fu qi", "伺服器" }, { "si ge", "四个" }, { "si ge", "四哥" }, { "si ge ren", "四个人" }, { "si ge yue", "四个月" },
			{ "si ge zi", "四个字" }, { "si gua", "丝瓜" }, { "si guang", "死光" }, { "si guo", "四国" }, { "si hai", "四海" }, { "si hao", "丝毫" }, { "si hao", "四号" },
			{ "si hao mei you", "丝毫没有" }, { "si he", "四核" }, { "si he yuan", "四合院" }, { "si hou", "死后" }, { "si hu", "似乎" }, { "si huan", "四环" },
			{ "si huo", "似火" }, { "si huo", "死活" }, { "si huo", "私活" }, { "si ji", "伺机" }, { "si ji", "司机" }, { "si ji", "四季" }, { "si ji", "四级" },
			{ "si ji", "斯基" }, { "si ji", "死寂" }, { "si ji", "死机" }, { "si ji du", "四季度" }, { "si jia", "四家" }, { "si jia", "思佳" }, { "si jia", "私家" },
			{ "si jia che", "私家车" }, { "si jiao", "四角" }, { "si jiao", "死角" }, { "si jie", "四届" }, { "si jin", "丝巾" }, { "si ju", "四句" }, { "si ka", "斯卡" },
			{ "si kai", "撕开" }, { "si kao", "司考" }, { "si kao", "思考" }, { "si ke", "思科" }, { "si ke", "斯克" }, { "si ke", "斯科" }, { "si ke da", "斯柯达" },
			{ "si kong jian guan", "司空见惯" }, { "si kou", "四口" }, { "si kuan", "四款" }, { "si le", "死了" }, { "si lei", "四类" }, { "si li", "死里" },
			{ "si li", "私利" }, { "si li", "私立" }, { "si li lan ka", "斯里兰卡" }, { "si li xue xiao", "私立学校" }, { "si liang", "思量" }, { "si liao", "私聊" },
			{ "si liao", "饲料" }, { "si lie", "撕裂" }, { "si ling", "司令" }, { "si ling", "死灵" }, { "si ling bu", "司令部" }, { "si ling yuan", "司令员" },
			{ "si liu ji", "四六级" }, { "si lou", "四楼" }, { "si lu", "丝路" }, { "si lu", "四路" }, { "si lu", "思路" }, { "si lun", "四轮" }, { "si ma", "司马" },
			{ "si ma qian", "司马迁" }, { "si ma yi", "司马懿" }, { "si men", "四门" }, { "si mi", "私密" }, { "si mian", "四面" }, { "si mian ba fang", "四面八方" },
			{ "si miao", "寺庙" }, { "si ming", "四名" }, { "si ming", "死命" }, { "si mu", "私募" }, { "si mu ji jin", "私募基金" }, { "si ni", "死你" },
			{ "si nian", "四年" }, { "si nian", "思念" }, { "si nian ji", "四年级" }, { "si nue", "肆虐" }, { "si nuo", "斯诺" }, { "si nuo ke", "斯诺克" },
			{ "si ping", "四平" }, { "si qi", "四期" }, { "si qi", "四起" }, { "si qi", "私企" }, { "si qian", "四千" }, { "si qian", "死前" }, { "si qiang", "四强" },
			{ "si qu", "四区" }, { "si qu", "四驱" }, { "si qu", "死去" }, { "si qu huo lai", "死去活来" }, { "si ren", "四人" }, { "si ren", "死人" }, { "si ren", "私人" },
			{ "si ren bang", "四人帮" }, { "si ri", "四日" }, { "si san", "四散" }, { "si sha", "厮杀" }, { "si shang", "死伤" }, { "si she", "四射" }, { "si shen", "死神" },
			{ "si sheng huo", "私生活" }, { "si sheng zi", "私生子" }, { "si shi", "似是" }, { "si shi", "四十" }, { "si shi", "四时" }, { "si shi", "四是" },
			{ "si shi", "死尸" }, { "si shi", "私事" }, { "si shi er fei", "似是而非" }, { "si shi sui", "四十岁" }, { "si shi wu", "四十五" }, { "si shou", "厮守" },
			{ "si shou", "死守" }, { "si shu", "私塾" }, { "si shui", "似水" }, { "si shui", "死水" }, { "si si", "丝丝" }, { "si si", "思思" }, { "si si", "死死" },
			{ "si si zhang", "司司长" }, { "si sui", "四岁" }, { "si sui", "撕碎" }, { "si suo", "思索" }, { "si ta", "斯塔" }, { "si tan", "斯坦" },
			{ "si tan fu", "斯坦福" }, { "si tao", "四套" }, { "si te", "斯特" }, { "si tian", "四天" }, { "si tiao", "四条" }, { "si tong", "四通" }, { "si tong", "斯通" },
			{ "si tu", "司徒" }, { "si tu jia te", "斯图加特" }, { "si tuo", "斯托" }, { "si wa", "丝袜" }, { "si wan", "四万" }, { "si wang", "死亡" },
			{ "si wang bi ji", "死亡笔记" }, { "si wang lv", "死亡率" }, { "si wang ren shu", "死亡人数" }, { "si wei", "四位" }, { "si wei", "四维" }, { "si wei", "思维" },
			{ "si wei", "饲喂" }, { "si wei fang shi", "思维方式" }, { "si wei mo shi", "思维模式" }, { "si wei neng li", "思维能力" }, { "si wen", "斯文" },
			{ "si wo le", "死我了" }, { "si wu", "四五" }, { "si wu ji dan", "肆无忌惮" }, { "si xia", "四下" }, { "si xia", "撕下" }, { "si xia", "私下" },
			{ "si xian", "丝线" }, { "si xiang", "四项" }, { "si xiang", "思乡" }, { "si xiang", "思想" }, { "si xiang dao de", "思想道德" },
			{ "si xiang gong zuo", "思想工作" }, { "si xiang guan nian", "思想观念" }, { "si xiang jia", "思想家" }, { "si xiang jiao yu", "思想教育" },
			{ "si xiang ren shi", "思想认识" }, { "si xiang zheng zhi", "思想政治" }, { "si xin", "死心" }, { "si xin", "私心" }, { "si xin lie fei", "撕心裂肺" },
			{ "si xin ta di", "死心塌地" }, { "si xing", "四星" }, { "si xing", "死刑" }, { "si xu", "思绪" }, { "si ya", "嘶哑" }, { "si yan", "四眼" },
			{ "si yang", "饲养" }, { "si ye", "四爷" }, { "si ye", "死也" }, { "si ye cao", "四叶草" }, { "si yi", "司仪" }, { "si yi", "四溢" }, { "si yi", "肆意" },
			{ "si yin", "死因" }, { "si ying", "私营" }, { "si ying qi ye", "私营企业" }, { "si you", "似有" }, { "si you", "私有" }, { "si you cai chan", "私有财产" },
			{ "si you hua", "私有化" }, { "si you zhi", "私有制" }, { "si yu", "思域" }, { "si yu", "死于" }, { "si yu", "死鱼" }, { "si yu", "私欲" }, { "si yu", "私语" },
			{ "si yuan", "寺院" }, { "si yuan", "思源" }, { "si yuan", "思远" }, { "si yue", "四月" }, { "si yue fen", "四月份" }, { "si zai", "死在" },
			{ "si zhang", "司长" }, { "si zhang", "四张" }, { "si zhe", "死者" }, { "si zhi", "四只" }, { "si zhi", "四肢" }, { "si zhong", "四种" },
			{ "si zhong quan hui", "四中全会" }, { "si zhou", "四周" }, { "si zhu", "死猪" }, { "si zi", "四字" }, { "si zi", "私自" }, { "si zuo", "四座" },
			{ "song", "倯" }, { "song", "傱" }, { "song", "凇" }, { "song", "娀" }, { "song", "宋" }, { "song", "崧" }, { "song", "嵩" }, { "song", "嵷" },
			{ "song", "忪" }, { "song", "怂" }, { "song", "悚" }, { "song", "愯" }, { "song", "慫" }, { "song", "憁" }, { "song", "松" }, { "song", "枩" },
			{ "song", "棇" }, { "song", "淞" }, { "song", "漎" }, { "song", "濍" }, { "song", "硹" }, { "song", "竦" }, { "song", "耸" }, { "song", "聳" },
			{ "song", "菘" }, { "song", "蘴" }, { "song", "蜙" }, { "song", "訟" }, { "song", "誦" }, { "song", "讼" }, { "song", "诵" }, { "song", "送" },
			{ "song", "鍶" }, { "song", "鎹" }, { "song", "頌" }, { "song", "颂" }, { "song", "駷" }, { "song", "鬆" }, { "song bai", "松柏" }, { "song bie", "送别" },
			{ "song chao", "宋朝" }, { "song chi", "松弛" }, { "song chu", "送出" }, { "song chu qu", "送出去" }, { "song chu yu", "宋楚瑜" }, { "song ci", "宋词" },
			{ "song da", "送达" }, { "song dai", "宋代" }, { "song dan dan", "宋丹丹" }, { "song dao", "送到" }, { "song dao feng", "松岛枫" }, { "song dong", "松动" },
			{ "song du", "诵读" }, { "song fan", "送饭" }, { "song ge", "颂歌" }, { "song gei", "送给" }, { "song gu", "送股" }, { "song guo", "送过" },
			{ "song hua", "送花" }, { "song hua jiang", "松花江" }, { "song hui", "送回" }, { "song hui qiao", "宋慧乔" }, { "song huo", "送货" },
			{ "song huo shang men", "送货上门" }, { "song jian", "送检" }, { "song jiang", "宋江" }, { "song jiang", "松江" }, { "song jiao", "送交" },
			{ "song jin", "送进" }, { "song kai", "松开" }, { "song lai", "送来" }, { "song li", "耸立" }, { "song li", "送礼" }, { "song li wu", "送礼物" },
			{ "song lin", "松林" }, { "song ling", "松岭" }, { "song mei ling", "宋美龄" }, { "song ni", "送你" }, { "song piao", "送票" }, { "song qian", "送钱" },
			{ "song qing ling", "宋庆龄" }, { "song qu", "送去" }, { "song ren", "送人" }, { "song ru", "送入" }, { "song ruan", "松软" }, { "song san", "松散" },
			{ "song shan", "嵩山" }, { "song shang", "送上" }, { "song shang men", "送上门" }, { "song shen", "送审" }, { "song shou", "松手" }, { "song shu", "松树" },
			{ "song shu", "松鼠" }, { "song shui", "送水" }, { "song si", "送死" }, { "song song", "松松" }, { "song ta", "送他" }, { "song ta", "送她" },
			{ "song ti", "宋体" }, { "song wang", "送往" }, { "song wen nuan", "送温暖" }, { "song wo", "送我" }, { "song xia", "松下" }, { "song xie", "松懈" },
			{ "song xing", "送行" }, { "song xiu", "送修" }, { "song yong", "怂恿" }, { "song zhi", "送至" }, { "song zi", "松子" }, { "song zou", "送走" },
			{ "song zu de", "宋祖德" }, { "song zu ying", "宋祖英" }, { "sou", "叟" }, { "sou", "嗖" }, { "sou", "嗽" }, { "sou", "嗾" }, { "sou", "廋" }, { "sou", "捜" },
			{ "sou", "搜" }, { "sou", "擞" }, { "sou", "擻" }, { "sou", "櫢" }, { "sou", "欶" }, { "sou", "溲" }, { "sou", "獀" }, { "sou", "瞍" }, { "sou", "籔" },
			{ "sou", "艘" }, { "sou", "蒐" }, { "sou", "薮" }, { "sou", "藪" }, { "sou", "螋" }, { "sou", "鄋" }, { "sou", "醙" }, { "sou", "鎪" }, { "sou", "锼" },
			{ "sou", "颼" }, { "sou", "颾" }, { "sou", "飕" }, { "sou", "餿" }, { "sou", "馊" }, { "sou", "騪" }, { "sou cha", "搜查" }, { "sou chu", "搜出" },
			{ "sou fang", "搜房" }, { "sou fang wang", "搜房网" }, { "sou gou", "搜狗" }, { "sou gua", "搜刮" }, { "sou hu", "搜狐" }, { "sou hu bo ke", "搜狐博客" },
			{ "sou hu ti yu", "搜狐体育" }, { "sou ji", "搜集" }, { "sou jiu", "搜救" }, { "sou luo", "搜罗" }, { "sou sou", "嗖嗖" }, { "sou suo", "搜索" },
			{ "sou suo gong neng", "搜索功能" }, { "sou suo jie guo", "搜索结果" }, { "sou suo yin qing", "搜索引擎" }, { "sou xun", "搜寻" }, { "su", "俗" }, { "su", "傃" },
			{ "su", "僳" }, { "su", "嗉" }, { "su", "囌" }, { "su", "塑" }, { "su", "夙" }, { "su", "嫊" }, { "su", "宿" }, { "su", "愫" }, { "su", "愬" },
			{ "su", "憟" }, { "su", "摵" }, { "su", "棴" }, { "su", "榡" }, { "su", "樕" }, { "su", "櫯" }, { "su", "泝" }, { "su", "洬" }, { "su", "涑" },
			{ "su", "溯" }, { "su", "玊" }, { "su", "甦" }, { "su", "稣" }, { "su", "穌" }, { "su", "窣" }, { "su", "簌" }, { "su", "粛" }, { "su", "粟" },
			{ "su", "素" }, { "su", "縤" }, { "su", "缩" }, { "su", "肃" }, { "su", "肅" }, { "su", "膆" }, { "su", "苏" }, { "su", "蔌" }, { "su", "藗" },
			{ "su", "蘇" }, { "su", "蘓" }, { "su", "觫" }, { "su", "訴" }, { "su", "謖" }, { "su", "诉" }, { "su", "谡" }, { "su", "蹜" }, { "su", "速" },
			{ "su", "遡" }, { "su", "酥" }, { "su", "鋉" }, { "su", "餗" }, { "su", "驌" }, { "su", "鱐" }, { "su", "鷫" }, { "su bei", "苏北" }, { "su bo er", "苏泊尔" },
			{ "su bu xiang shi", "素不相识" }, { "su cai", "素材" }, { "su cai", "素菜" }, { "su cheng", "俗称" }, { "su cheng", "速成" }, { "su dan", "苏丹" },
			{ "su dan hong", "苏丹红" }, { "su di", "速递" }, { "su dong", "速冻" }, { "su dong po", "苏东坡" }, { "su du", "速度" }, { "su du kuai", "速度快" },
			{ "su du man", "速度慢" }, { "su du zui kuai", "速度最快" }, { "su fei", "苏菲" }, { "su ge la di", "苏格拉底" }, { "su ge lan", "苏格兰" }, { "su hua", "俗话" },
			{ "su hua shuo", "俗话说" }, { "su jiao", "塑胶" }, { "su jun", "苏军" }, { "su ku", "诉苦" }, { "su lai", "素来" }, { "su li shi", "苏黎世" },
			{ "su lian", "苏联" }, { "su liao", "塑料" }, { "su liao dai", "塑料袋" }, { "su liao zhi pin", "塑料制品" }, { "su lv", "速率" }, { "su miao", "素描" },
			{ "su ming", "宿命" }, { "su mu", "肃穆" }, { "su nan", "苏南" }, { "su ning", "苏宁" }, { "su ning dian qi", "苏宁电器" }, { "su qi", "俗气" },
			{ "su qian", "宿迁" }, { "su qiu", "诉求" }, { "su qu", "苏区" }, { "su ren", "俗人" }, { "su shan", "苏珊" }, { "su she", "宿舍" }, { "su she lou", "宿舍楼" },
			{ "su shen", "塑身" }, { "su shi", "素食" }, { "su shi", "苏轼" }, { "su shuo", "诉说" }, { "su song", "诉讼" }, { "su song qing qiu", "诉讼请求" },
			{ "su su", "素素" }, { "su su", "苏苏" }, { "su tao", "俗套" }, { "su teng", "速腾" }, { "su wei ai", "苏维埃" }, { "su xiang", "塑像" }, { "su xing", "塑性" },
			{ "su xing", "苏醒" }, { "su yang", "素养" }, { "su yi", "素以" }, { "su you", "素有" }, { "su you peng", "苏有朋" }, { "su yu", "俗语" }, { "su yu", "粟裕" },
			{ "su zao", "塑造" }, { "su zhen chang", "苏贞昌" }, { "su zhi", "素质" }, { "su zhi jiao yu", "素质教育" }, { "su zhou", "宿州" }, { "su zhou", "苏州" },
			{ "su zhou shi", "苏州市" }, { "su zhu", "宿主" }, { "su zhu", "诉诸" }, { "su zhuang", "诉状" }, { "suan", "匴" }, { "suan", "狻" }, { "suan", "痠" },
			{ "suan", "筭" }, { "suan", "算" }, { "suan", "蒜" }, { "suan", "酸" }, { "suan bu shang", "算不上" }, { "suan bu suan", "算不算" }, { "suan cai", "酸菜" },
			{ "suan chu", "算出" }, { "suan chu", "酸楚" }, { "suan cuo", "算错" }, { "suan de", "算得" }, { "suan fa", "算法" }, { "suan ge", "算个" },
			{ "suan hao", "算好" }, { "suan ji", "算计" }, { "suan la", "算啦" }, { "suan la", "酸辣" }, { "suan lai", "算来" }, { "suan le", "算了" },
			{ "suan ming", "算命" }, { "suan nai", "酸奶" }, { "suan ni", "算你" }, { "suan pan", "算盘" } };
};
