package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN34 {
	public static String[][] pl = { { "neng zai", "能再" }, { "neng zai", "能在" }, { "neng zhuan", "能赚" }, { "neng zou", "能走" }, { "neng zuo", "能做" },
			{ "neng zuo shen me", "能做什么" }, { "ng", "唔" }, { "ng", "嗯" }, { "ni", "伲" }, { "ni", "你" }, { "ni", "倪" }, { "ni", "児" }, { "ni", "匿" },
			{ "ni", "呢" }, { "ni", "坭" }, { "ni", "堄" }, { "ni", "妮" }, { "ni", "妳" }, { "ni", "婗" }, { "ni", "嫟" }, { "ni", "嬭" }, { "ni", "尼" },
			{ "ni", "屔" }, { "ni", "怩" }, { "ni", "惄" }, { "ni", "抳" }, { "ni", "拟" }, { "ni", "擬" }, { "ni", "旎" }, { "ni", "昵" }, { "ni", "晲" },
			{ "ni", "暱" }, { "ni", "柅" }, { "ni", "檷" }, { "ni", "泥" }, { "ni", "淣" }, { "ni", "溺" }, { "ni", "濔" }, { "ni", "灄" }, { "ni", "狔" },
			{ "ni", "猊" }, { "ni", "眤" }, { "ni", "睨" }, { "ni", "秜" }, { "ni", "籾" }, { "ni", "縌" }, { "ni", "腻" }, { "ni", "膩" }, { "ni", "臡" },
			{ "ni", "苨" }, { "ni", "薿" }, { "ni", "蜺" }, { "ni", "袮" }, { "ni", "觬" }, { "ni", "誽" }, { "ni", "貎" }, { "ni", "跜" }, { "ni", "迡" },
			{ "ni", "逆" }, { "ni", "郳" }, { "ni", "鈮" }, { "ni", "铌" }, { "ni", "隬" }, { "ni", "霓" }, { "ni", "馜" }, { "ni", "鯢" }, { "ni", "鲵" },
			{ "ni", "麑" }, { "ni", "齯" }, { "ni ai", "你爱" }, { "ni ai", "溺爱" }, { "ni ai wo", "你爱我" }, { "ni ao", "尼奥" }, { "ni ba", "泥巴" }, { "ni bi", "你比" },
			{ "ni bo er", "尼泊尔" }, { "ni bu", "你不" }, { "ni bu shi", "你不是" }, { "ni bu zai", "你不在" }, { "ni cai", "你才" }, { "ni cai", "你猜" },
			{ "ni cai", "尼采" }, { "ni cha", "逆差" }, { "ni cheng", "昵称" }, { "ni dao", "你到" }, { "ni de", "你得" }, { "ni de", "你的" }, { "ni de ai", "你的爱" },
			{ "ni de shou", "你的手" }, { "ni de xin", "你的心" }, { "ni dei", "你得" }, { "ni ding", "拟定" }, { "ni ding", "拟订" }, { "ni dong", "你懂" },
			{ "ni dui", "你对" }, { "ni er", "尼尔" }, { "ni er sen", "尼尔森" }, { "ni feng", "逆风" }, { "ni gai", "你该" }, { "ni gan", "你敢" }, { "ni ge", "你个" },
			{ "ni gu", "尼姑" }, { "ni gu ding", "尼古丁" }, { "ni guang", "逆光" }, { "ni hai", "你还" }, { "ni hai hui", "你还会" }, { "ni hao", "你好" },
			{ "ni hao a", "你好啊" }, { "ni hao ma", "你好吗" }, { "ni he", "你和" }, { "ni he", "拟合" }, { "ni hen", "你很" }, { "ni hong", "霓虹" },
			{ "ni hong deng", "霓虹灯" }, { "ni hui", "你会" }, { "ni jia", "你家" }, { "ni jian", "拟建" }, { "ni jiang", "你将" }, { "ni jiang", "泥浆" },
			{ "ni jing", "逆境" }, { "ni jiu", "你就" }, { "ni jiu hui", "你就会" }, { "ni kan", "你看" }, { "ni kang", "尼康" }, { "ni ke", "你可" }, { "ni ke", "妮可" },
			{ "ni ke", "尼克" }, { "ni ke si", "尼克斯" }, { "ni ke song", "尼克松" }, { "ni kuai le", "你快乐" }, { "ni lai", "你来" }, { "ni liu", "逆流" },
			{ "ni long", "尼龙" }, { "ni luo he", "尼罗河" }, { "ni ma", "你妈" }, { "ni mei", "你没" }, { "ni men", "你们" }, { "ni men hao", "你们好" },
			{ "ni ming", "匿名" }, { "ni nan", "呢喃" }, { "ni neng", "你能" }, { "ni ni", "妮妮" }, { "ni ning", "泥泞" }, { "ni o", "你哦" }, { "ni pa", "你怕" },
			{ "ni ping", "倪萍" }, { "ni qiu", "泥鳅" }, { "ni ri li ya", "尼日利亚" }, { "ni ruo", "你若" }, { "ni sha", "泥沙" }, { "ni shang", "霓裳" },
			{ "ni shi", "你是" }, { "ni shi", "逆势" }, { "ni shi", "逆市" }, { "ni shi liu", "泥石流" }, { "ni shi shei", "你是谁" }, { "ni shi shui", "你是谁" },
			{ "ni shi wo", "你是我" }, { "ni shi zhen", "逆时针" }, { "ni shui", "溺水" }, { "ni shuo", "你说" }, { "ni shuo de", "你说的" }, { "ni shuo guo", "你说过" },
			{ "ni shuo wo", "你说我" }, { "ni si", "尼斯" }, { "ni si wo huo", "你死我活" }, { "ni suo", "你所" }, { "ni tai", "你太" }, { "ni tan", "泥潭" },
			{ "ni tian", "逆天" }, { "ni ting", "你听" }, { "ni tu", "泥土" }, { "ni wei", "腻味" }, { "ni wen", "你问" }, { "ni wo", "你我" }, { "ni xiang", "你想" },
			{ "ni xiang", "逆向" }, { "ni xiang yao", "你想要" }, { "ni xing", "逆行" }, { "ni ya", "尼亚" }, { "ni yao", "你要" }, { "ni ye", "你也" }, { "ni yi", "你一" },
			{ "ni yi wei", "你以为" }, { "ni yong", "你用" }, { "ni you", "你有" }, { "ni zai", "你在" }, { "ni zai", "拟在" }, { "ni zhen", "你真" }, { "ni zhi", "你只" },
			{ "ni zhuan", "逆转" }, { "ni zi", "妮子" }, { "ni zi", "腻子" }, { "ni zou le", "你走了" }, { "ni zui", "你最" }, { "ni zuo", "你做" }, { "nian", "卄" },
			{ "nian", "哖" }, { "nian", "唸" }, { "nian", "埝" }, { "nian", "姩" }, { "nian", "年" }, { "nian", "廿" }, { "nian", "念" }, { "nian", "拈" },
			{ "nian", "捻" }, { "nian", "撚" }, { "nian", "撵" }, { "nian", "攆" }, { "nian", "碾" }, { "nian", "秊" }, { "nian", "簐" }, { "nian", "粘" },
			{ "nian", "蔫" }, { "nian", "跈" }, { "nian", "蹍" }, { "nian", "躎" }, { "nian", "輦" }, { "nian", "辇" }, { "nian", "辗" }, { "nian", "鮎" },
			{ "nian", "鯰" }, { "nian", "鲇" }, { "nian", "鲶" }, { "nian", "黏" }, { "nian ban", "年半" }, { "nian bao", "年报" }, { "nian chan", "年产" },
			{ "nian chan zhi", "年产值" }, { "nian chou", "粘稠" }, { "nian chu", "年初" }, { "nian dai", "年代" }, { "nian dai chu", "年代初" }, { "nian dai mo", "年代末" },
			{ "nian dai yi lai", "年代以来" }, { "nian dao", "念叨" }, { "nian de", "年的" }, { "nian di", "年底" }, { "nian di qian", "年底前" }, { "nian du", "年度" },
			{ "nian du", "粘度" }, { "nian du bao gao", "年度报告" }, { "nian du kao he", "年度考核" }, { "nian du zhong guo", "年度中国" }, { "nian du zui jia", "年度最佳" },
			{ "nian fei", "年费" }, { "nian fen", "年份" }, { "nian fo", "念佛" }, { "nian fu yi nian", "年复一年" }, { "nian gao", "年糕" }, { "nian guan", "年关" },
			{ "nian hou", "年后" }, { "nian hua", "年华" }, { "nian hua", "年画" }, { "nian hui", "年会" }, { "nian huo", "年货" }, { "nian ji", "年级" },
			{ "nian ji", "年纪" }, { "nian jia", "年假" }, { "nian jian", "年检" }, { "nian jian", "年鉴" }, { "nian jian", "年间" }, { "nian jin", "年仅" },
			{ "nian jin", "年近" }, { "nian jin", "年金" }, { "nian jing", "念经" }, { "nian jun", "年均" }, { "nian jun zeng zhang", "年均增长" }, { "nian lai", "年来" },
			{ "nian lao", "年老" }, { "nian li", "年里" }, { "nian ling", "年龄" }, { "nian ling duan", "年龄段" }, { "nian mai", "年迈" }, { "nian man", "年满" },
			{ "nian mo", "年末" }, { "nian mo", "粘膜" }, { "nian mo", "黏膜" }, { "nian nei", "年内" }, { "nian nian", "年年" }, { "nian nian", "念念" },
			{ "nian nian bu wang", "念念不忘" }, { "nian qi", "年期" }, { "nian qian", "年前" }, { "nian qing", "年轻" }, { "nian qing", "年青" },
			{ "nian qing hua", "年轻化" }, { "nian qing ren", "年轻人" }, { "nian qing yi dai", "年轻一代" }, { "nian shao", "年少" }, { "nian shen", "年审" },
			{ "nian shu", "念书" }, { "nian sui", "年岁" }, { "nian tie", "粘帖" }, { "nian tou", "年头" }, { "nian tou", "念头" }, { "nian tu", "粘土" },
			{ "nian xian", "年限" }, { "nian xiao shou e", "年销售额" }, { "nian xin", "年薪" }, { "nian xing", "粘性" }, { "nian xiu jia", "年休假" }, { "nian ya", "碾压" },
			{ "nian ye", "粘液" }, { "nian ye fan", "年夜饭" }, { "nian you", "年幼" }, { "nian yue", "年月" }, { "nian yue ri", "年月日" }, { "nian zhang", "年长" },
			{ "nian zhe", "念着" }, { "nian zhong", "年中" }, { "nian zhong", "年终" }, { "nian zhong jiang", "年终奖" }, { "niang", "娘" }, { "niang", "嬢" },
			{ "niang", "孃" }, { "niang", "酿" }, { "niang", "醸" }, { "niang", "釀" }, { "niang cheng", "酿成" }, { "niang jia", "娘家" }, { "niang jiu", "酿酒" },
			{ "niang niang", "娘娘" }, { "niang niang qiang", "娘娘腔" }, { "niang zao", "酿造" }, { "niang zi", "娘子" }, { "niao", "嫋" }, { "niao", "嬝" },
			{ "niao", "嬲" }, { "niao", "尿" }, { "niao", "樢" }, { "niao", "溺" }, { "niao", "脲" }, { "niao", "茑" }, { "niao", "蔦" }, { "niao", "袅" },
			{ "niao", "裊" }, { "niao", "褭" }, { "niao", "鳥" }, { "niao", "鸟" }, { "niao bu", "尿布" }, { "niao chao", "鸟巢" }, { "niao dao", "尿道" },
			{ "niao du zheng", "尿毒症" }, { "niao er", "鸟儿" }, { "niao lei", "鸟类" }, { "niao niao", "尿尿" }, { "niao niao", "袅袅" }, { "niao pin", "尿频" },
			{ "niao ren", "鸟人" }, { "niao su", "尿素" }, { "niao suan", "尿酸" }, { "niao ye", "尿液" }, { "niao yu", "鸟语" }, { "nie", "乜" }, { "nie", "啮" },
			{ "nie", "嗫" }, { "nie", "嚙" }, { "nie", "囓" }, { "nie", "孼" }, { "nie", "孽" }, { "nie", "峊" }, { "nie", "嵲" }, { "nie", "嶭" }, { "nie", "巕" },
			{ "nie", "捏" }, { "nie", "摄" }, { "nie", "摰" }, { "nie", "敜" }, { "nie", "櫱" }, { "nie", "涅" }, { "nie", "篞" }, { "nie", "糱" }, { "nie", "聂" },
			{ "nie", "聶" }, { "nie", "臬" }, { "nie", "臲" }, { "nie", "苶" }, { "nie", "蘖" }, { "nie", "蠥" }, { "nie", "讘" }, { "nie", "踂" }, { "nie", "踗" },
			{ "nie", "踙" }, { "nie", "蹑" }, { "nie", "躡" }, { "nie", "鎳" }, { "nie", "鑈" }, { "nie", "鑷" }, { "nie", "镊" }, { "nie", "镍" }, { "nie", "闑" },
			{ "nie", "陧" }, { "nie", "隉" }, { "nie", "顳" }, { "nie", "颞" }, { "nie", "齧" }, { "nie le", "捏了" }, { "nie nie", "捏捏" }, { "nie pan", "涅磐" },
			{ "nie zao", "捏造" }, { "nie zhe", "捏着" }, { "nin", "您" }, { "nin", "拰" }, { "nin bi xu", "您必须" }, { "nin de", "您的" }, { "nin dui", "您对" },
			{ "nin hai", "您还" }, { "nin hai mei you", "您还没有" }, { "nin hao", "您好" }, { "nin hui", "您会" }, { "nin jiang", "您将" }, { "nin jiu", "您就" },
			{ "nin kan", "您看" }, { "nin ke", "您可" }, { "nin lao", "您老" }, { "nin mei you", "您没有" }, { "nin men", "您们" }, { "nin neng", "您能" },
			{ "nin shang wei", "您尚未" }, { "nin shi", "您是" }, { "nin shuo", "您说" }, { "nin suo", "您所" }, { "nin xiang", "您想" }, { "nin xu yao", "您需要" },
			{ "nin yao", "您要" }, { "nin ye", "您也" }, { "nin yi", "您已" }, { "nin you", "您有" }, { "nin zai", "您在" }, { "ning", "佞" }, { "ning", "侫" },
			{ "ning", "儜" }, { "ning", "凝" }, { "ning", "咛" }, { "ning", "嚀" }, { "ning", "嬣" }, { "ning", "宁" }, { "ning", "寍" }, { "ning", "寗" },
			{ "ning", "寧" }, { "ning", "拧" }, { "ning", "擰" }, { "ning", "柠" }, { "ning", "檸" }, { "ning", "泞" }, { "ning", "濘" }, { "ning", "狞" },
			{ "ning", "獰" }, { "ning", "甯" }, { "ning", "聍" }, { "ning", "聹" }, { "ning", "苧" }, { "ning", "薴" }, { "ning", "鑏" }, { "ning", "鸋" },
			{ "ning bo", "宁波" }, { "ning bo shi", "宁波市" }, { "ning de", "宁德" }, { "ning gu", "凝固" }, { "ning hai", "宁海" }, { "ning jiao", "凝胶" },
			{ "ning jie", "凝结" }, { "ning jing", "宁静" }, { "ning ju", "凝聚" }, { "ning ju li", "凝聚力" }, { "ning ke", "宁可" }, { "ning ken", "宁肯" },
			{ "ning meng", "柠檬" }, { "ning meng zhi", "柠檬汁" }, { "ning ning", "宁宁" }, { "ning shen", "凝神" }, { "ning shi", "凝视" }, { "ning wang", "凝望" },
			{ "ning xia", "宁夏" }, { "ning yuan", "宁愿" }, { "ning zhong", "凝重" }, { "niu", "妞" }, { "niu", "忸" }, { "niu", "怓" }, { "niu", "扭" },
			{ "niu", "拗" }, { "niu", "杻" }, { "niu", "炄" }, { "niu", "牛" }, { "niu", "狃" }, { "niu", "紐" }, { "niu", "纽" }, { "niu", "鈕" }, { "niu", "钮" },
			{ "niu bi", "牛比" }, { "niu bi", "牛逼" }, { "niu cha", "牛叉" }, { "niu dai", "纽带" }, { "niu dong", "扭动" }, { "niu dun", "牛顿" }, { "niu fen", "牛粪" },
			{ "niu gu", "牛股" }, { "niu jiao", "牛角" }, { "niu jin", "牛津" }, { "niu ju", "扭矩" }, { "niu ka si er", "纽卡斯尔" }, { "niu kou", "纽扣" },
			{ "niu kui", "扭亏" }, { "niu lang", "牛郎" }, { "niu man", "纽曼" }, { "niu mo wang", "牛魔王" }, { "niu nai", "牛奶" }, { "niu niu", "妞妞" },
			{ "niu niu", "牛牛" }, { "niu pai", "牛排" }, { "niu pi", "牛皮" }, { "niu pi xuan", "牛皮癣" }, { "niu qu", "扭曲" }, { "niu qun", "牛群" },
			{ "niu ren", "牛人" }, { "niu rou", "牛肉" }, { "niu rou gan", "牛肉干" }, { "niu rou mian", "牛肉面" }, { "niu shang", "扭伤" }, { "niu shi", "牛市" },
			{ "niu tou", "扭头" }, { "niu tou", "牛头" }, { "niu yang", "牛羊" }, { "niu yue", "纽约" }, { "niu yue shi", "纽约市" }, { "niu yue shi bao", "纽约时报" },
			{ "niu zai", "牛仔" }, { "niu zai ku", "牛仔裤" }, { "niu zhuan", "扭转" }, { "nong", "侬" }, { "nong", "儂" }, { "nong", "农" }, { "nong", "哝" },
			{ "nong", "噥" }, { "nong", "弄" }, { "nong", "浓" }, { "nong", "濃" }, { "nong", "穠" }, { "nong", "繷" }, { "nong", "脓" }, { "nong", "膿" },
			{ "nong", "襛" }, { "nong", "農" }, { "nong", "醲" }, { "nong", "齈" }, { "nong chan pin", "农产品" }, { "nong chang", "农场" }, { "nong cheng", "弄成" },
			{ "nong chu", "弄出" }, { "nong cun", "农村" }, { "nong cun di qu", "农村地区" }, { "nong cun fa zhan", "农村发展" }, { "nong cun fu nv", "农村妇女" },
			{ "nong cun gai ge", "农村改革" }, { "nong cun gong zuo", "农村工作" }, { "nong cun ji ceng", "农村基层" }, { "nong cun jiao yu", "农村教育" },
			{ "nong cun jin rong", "农村金融" }, { "nong cun jing ji", "农村经济" }, { "nong cun ju min", "农村居民" }, { "nong cun ren kou", "农村人口" },
			{ "nong cun shi chang", "农村市场" }, { "nong cuo", "弄错" }, { "nong da", "农大" }, { "nong dao", "弄到" }, { "nong de", "弄得" }, { "nong dian", "弄点" },
			{ "nong diu", "弄丢" }, { "nong dong", "弄懂" }, { "nong du", "浓度" }, { "nong fu", "农夫" }, { "nong fu", "农妇" }, { "nong fu chan pin", "农副产品" },
			{ "nong ge", "弄个" }, { "nong geng", "农耕" }, { "nong guo", "弄过" }, { "nong hang", "农行" }, { "nong hao", "侬好" }, { "nong hao", "弄好" },
			{ "nong hou", "浓厚" }, { "nong hu", "农户" }, { "nong huai", "弄坏" }, { "nong huo", "农活" }, { "nong ji", "农技" }, { "nong ji", "农机" },
			{ "nong jia", "农家" }, { "nong jia le", "农家乐" }, { "nong ke yuan", "农科院" }, { "nong ken", "农垦" }, { "nong lai", "弄来" }, { "nong li", "农历" },
			{ "nong lie", "浓烈" }, { "nong lin", "农林" }, { "nong mao shi chang", "农贸市场" }, { "nong mi", "浓密" }, { "nong min", "农民" },
			{ "nong min fu dan", "农民负担" }, { "nong min gong", "农民工" }, { "nong min shou ru", "农民收入" }, { "nong min zeng shou", "农民增收" },
			{ "nong min zhi fu", "农民致富" }, { "nong mu", "农牧" }, { "nong mu min", "农牧民" }, { "nong mu ye", "农牧业" }, { "nong nong", "弄弄" },
			{ "nong nong", "浓浓" }, { "nong nong de", "浓浓的" }, { "nong qing", "弄清" }, { "nong shi", "弄湿" }, { "nong si", "弄死" }, { "nong suo", "浓缩" },
			{ "nong tian", "农田" }, { "nong tian shui li", "农田水利" }, { "nong wei", "农委" }, { "nong xin she", "农信社" }, { "nong xu zuo jia", "弄虚作假" },
			{ "nong yan", "浓烟" }, { "nong yao", "农药" }, { "nong yao can liu", "农药残留" }, { "nong ye", "农业" }, { "nong ye bao xian", "农业保险" },
			{ "nong ye bu", "农业部" }, { "nong ye bu men", "农业部门" }, { "nong ye da xue", "农业大学" }, { "nong ye fa zhan", "农业发展" }, { "nong ye he zuo", "农业合作" },
			{ "nong ye ji shu", "农业技术" }, { "nong ye ji xie", "农业机械" }, { "nong ye ju", "农业局" }, { "nong ye ke ji", "农业科技" }, { "nong ye pu cha", "农业普查" },
			{ "nong ye sheng chan", "农业生产" }, { "nong ye shui", "农业税" }, { "nong ye ting", "农业厅" }, { "nong ye yin hang", "农业银行" }, { "nong yong", "农用" },
			{ "nong yu", "浓郁" }, { "nong zang", "弄脏" }, { "nong zhong", "浓重" }, { "nong zhuang", "农庄" }, { "nong zi", "农资" }, { "nong zuo wu", "农作物" },
			{ "nou", "羺" }, { "nou", "耨" }, { "nou", "譨" }, { "nou", "鎒" }, { "nu", "努" }, { "nu", "奴" }, { "nu", "孥" }, { "nu", "帑" }, { "nu", "弩" },
			{ "nu", "怒" }, { "nu", "砮" }, { "nu", "笯" }, { "nu", "胬" }, { "nu", "駑" }, { "nu", "驽" }, { "nu bi", "奴婢" }, { "nu cai", "奴才" },
			{ "nu chi", "怒斥" }, { "nu fang", "怒放" }, { "nu hou", "怒吼" }, { "nu huo", "怒火" }, { "nu jiang", "怒江" }, { "nu li", "努力" }, { "nu li", "奴隶" },
			{ "nu li fen dou", "努力奋斗" }, { "nu li gong zuo", "努力工作" }, { "nu li shi xian", "努力实现" }, { "nu li ti gao", "努力提高" }, { "nu li xue xi", "努力学习" },
			{ "nu qi", "怒气" }, { "nu yi", "奴役" }, { "nuan", "奻" }, { "nuan", "暖" }, { "nuan", "渜" }, { "nuan", "餪" }, { "nuan feng", "暖风" },
			{ "nuan he", "暖和" }, { "nuan huo", "暖和" }, { "nuan liu", "暖流" }, { "nuan nuan", "暖暖" }, { "nuan nuan de", "暖暖的" }, { "nuan qi", "暖气" },
			{ "nuan shen", "暖身" }, { "nuan yi", "暖意" }, { "nue", "疟" }, { "nue", "瘧" }, { "nue", "虐" }, { "nue dai", "虐待" }, { "nue ji", "疟疾" },
			{ "nuo", "傩" }, { "nuo", "儺" }, { "nuo", "喏" }, { "nuo", "娜" }, { "nuo", "懦" }, { "nuo", "懧" }, { "nuo", "挪" }, { "nuo", "搦" }, { "nuo", "梛" },
			{ "nuo", "橠" }, { "nuo", "糑" }, { "nuo", "糯" }, { "nuo", "袲" }, { "nuo", "諾" }, { "nuo", "诺" }, { "nuo", "逽" }, { "nuo", "锘" },
			{ "nuo bei er", "诺贝尔" }, { "nuo bei er jiang", "诺贝尔奖" }, { "nuo dong", "挪动" }, { "nuo dun", "诺顿" }, { "nuo fu", "懦夫" }, { "nuo fu", "诺夫" },
			{ "nuo ji ya", "诺基亚" }, { "nuo mi", "糯米" }, { "nuo ruo", "懦弱" }, { "nuo si", "诺斯" }, { "nuo wei", "挪威" }, { "nuo wei ci ji", "诺维茨基" },
			{ "nuo yan", "诺言" }, { "nuo yong", "挪用" }, { "nv", "女" }, { "nv", "恧" }, { "nv", "朒" }, { "nv", "籹" }, { "nv", "聏" }, { "nv", "衂" }, { "nv", "衄" },
			{ "nv", "釹" }, { "nv", "钕" }, { "nv ban", "女伴" }, { "nv bing", "女兵" }, { "nv bo shi", "女博士" }, { "nv da xue sheng", "女大学生" }, { "nv dan", "女单" },
			{ "nv de", "女的" }, { "nv dui", "女队" }, { "nv er", "女儿" }, { "nv fang", "女方" }, { "nv ge shou", "女歌手" }, { "nv gong", "女工" }, { "nv gui", "女鬼" },
			{ "nv hai", "女孩" }, { "nv hai er", "女孩儿" }, { "nv hai zi", "女孩子" }, { "nv huang", "女皇" }, { "nv ji zhe", "女记者" }, { "nv jiao shi", "女教师" },
			{ "nv jing", "女警" }, { "nv lan", "女篮" }, { "nv lang", "女郎" }, { "nv lao ban", "女老板" }, { "nv lao shi", "女老师" }, { "nv mi shu", "女秘书" },
			{ "nv ming xing", "女明星" }, { "nv pai", "女排" }, { "nv peng you", "女朋友" }, { "nv pu", "女仆" }, { "nv qiang ren", "女强人" }, { "nv qing nian", "女青年" },
			{ "nv ren", "女人" }, { "nv ren shi", "女人是" }, { "nv ren wei", "女人味" }, { "nv se", "女色" }, { "nv shen", "女神" }, { "nv sheng", "女声" },
			{ "nv sheng", "女生" }, { "nv sheng su she", "女生宿舍" }, { "nv shi", "女士" }, { "nv shi", "女尸" }, { "nv shi", "女式" }, { "nv shuang", "女双" },
			{ "nv tong", "女童" }, { "nv tong shi", "女同事" }, { "nv tong xue", "女同学" }, { "nv tong zhi", "女同志" }, { "nv wa", "女娲" }, { "nv wang", "女王" },
			{ "nv wu", "女巫" }, { "nv xia", "女侠" }, { "nv xing", "女性" }, { "nv xing", "女星" }, { "nv xing hua", "女性化" }, { "nv xing peng you", "女性朋友" },
			{ "nv xu", "女婿" }, { "nv xue sheng", "女学生" }, { "nv yan yuan", "女演员" }, { "nv yi ren", "女艺人" }, { "nv ying", "女婴" }, { "nv you", "女优" },
			{ "nv you", "女友" }, { "nv zhi gong", "女职工" }, { "nv zhu", "女主" }, { "nv zhu bo", "女主播" }, { "nv zhu jue", "女主角" }, { "nv zhu ren", "女主人" },
			{ "nv zhu ren gong", "女主人公" }, { "nv zhuang", "女装" }, { "nv zi", "女子" }, { "nv zu", "女足" }, { "nv zuo jia", "女作家" }, { "o", "哦" }, { "o", "喔" },
			{ "o", "噢" }, { "o", "嚄" }, { "o", "筽" }, { "o o", "哦哦" }, { "o o", "噢噢" }, { "o o o", "哦哦哦" }, { "o yo", "哦哟" }, { "ou", "偶" }, { "ou", "区" },
			{ "ou", "吘" }, { "ou", "呕" }, { "ou", "嘔" }, { "ou", "怄" }, { "ou", "慪" }, { "ou", "櫙" }, { "ou", "欧" }, { "ou", "歐" }, { "ou", "殴" },
			{ "ou", "毆" }, { "ou", "沤" }, { "ou", "漚" }, { "ou", "熰" }, { "ou", "瓯" }, { "ou", "甌" }, { "ou", "耦" }, { "ou", "腢" }, { "ou", "蕅" },
			{ "ou", "藕" }, { "ou", "藲" }, { "ou", "讴" }, { "ou", "鏂" }, { "ou", "鴎" }, { "ou", "鷗" }, { "ou", "鸥" }, { "ou ban", "欧版" }, { "ou da", "殴打" },
			{ "ou di", "偶滴" }, { "ou er", "偶尔" }, { "ou ge", "讴歌" }, { "ou guan", "欧冠" }, { "ou he", "耦合" }, { "ou jia", "偶家" }, { "ou jin sai", "欧锦赛" },
			{ "ou lai ya", "欧莱雅" }, { "ou lu", "欧陆" }, { "ou mei", "欧美" }, { "ou mei guo jia", "欧美国家" }, { "ou men", "偶们" }, { "ou meng", "欧盟" },
			{ "ou pei ke", "欧佩克" }, { "ou ran", "偶然" }, { "ou ran xing", "偶然性" }, { "ou shi", "欧式" }, { "ou shu", "偶数" }, { "ou tu", "呕吐" },
			{ "ou wen", "欧文" }, { "ou xiang", "偶像" }, { "ou xiang ju", "偶像剧" }, { "ou ya", "欧亚" }, { "ou yang", "欧阳" }, { "ou you", "偶有" }, { "ou yu", "偶遇" },
			{ "ou yuan", "欧元" }, { "ou yuan qu", "欧元区" }, { "ou zhou", "欧洲" }, { "ou zhou bei", "欧洲杯" }, { "ou zhou guo jia", "欧洲国家" },
			{ "ou zhou ren", "欧洲人" }, { "ou zhou shi chang", "欧洲市场" }, { "pa", "啪" }, { "pa", "帊" }, { "pa", "帕" }, { "pa", "怕" }, { "pa", "扒" },
			{ "pa", "掱" }, { "pa", "杷" }, { "pa", "汃" }, { "pa", "爬" }, { "pa", "琶" }, { "pa", "筢" }, { "pa", "耙" }, { "pa", "舥" }, { "pa", "葩" },
			{ "pa", "袙" }, { "pa", "趴" }, { "pa", "跁" }, { "pa", "鈀" }, { "pa", "钯" }, { "pa chong", "爬虫" }, { "pa chu", "爬出" }, { "pa dao", "爬到" },
			{ "pa guo", "爬过" }, { "pa ke", "帕克" }, { "pa le", "怕了" }, { "pa leng", "怕冷" }, { "pa pa", "啪啪" }, { "pa pa", "怕怕" }, { "pa qi lai", "爬起来" },
			{ "pa sa te", "帕萨特" }, { "pa sha", "怕啥" }, { "pa shan", "爬山" }, { "pa shang", "爬上" }, { "pa shen me", "怕什么" }, { "pa shi", "怕是" },
			{ "pa si", "怕死" }, { "pa wa luo di", "帕瓦罗蒂" }, { "pa xia", "趴下" }, { "pa xing", "爬行" }, { "pa zai", "趴在" }, { "pa zhe", "趴着" }, { "pai", "俳" },
			{ "pai", "哌" }, { "pai", "徘" }, { "pai", "拍" }, { "pai", "排" }, { "pai", "棑" }, { "pai", "派" }, { "pai", "湃" }, { "pai", "牌" }, { "pai", "犤" },
			{ "pai", "箄" }, { "pai", "簰" }, { "pai", "蒎" }, { "pai", "迫" }, { "pai", "鎃" }, { "pai ban", "拍板" }, { "pai ban", "排版" }, { "pai bian", "排便" },
			{ "pai bian", "牌匾" }, { "pai bie", "派别" }, { "pai bing", "派兵" }, { "pai cha", "排查" }, { "pai chang", "排场" }, { "pai cheng", "拍成" },
			{ "pai cheng", "排成" }, { "pai chi", "排斥" }, { "pai chu", "拍出" }, { "pai chu", "排出" }, { "pai chu", "排除" }, { "pai chu", "派出" },
			{ "pai chu suo", "派出所" }, { "pai da", "拍打" }, { "pai dao", "拍到" }, { "pai dao", "排到" }, { "pai dao", "派到" }, { "pai de", "拍得" },
			{ "pai de", "拍的" }, { "pai dian ying", "拍电影" }, { "pai du", "排毒" }, { "pai dui", "排队" }, { "pai dui", "派对" }, { "pai fa", "派发" },
			{ "pai fang", "排放" }, { "pai fang", "牌坊" }, { "pai fang biao zhun", "排放标准" }, { "pai fang liang", "排放量" }, { "pai gu", "排骨" },
			{ "pai guang gao", "拍广告" }, { "pai guo", "拍过" }, { "pai han", "排汗" }, { "pai hang", "排行" }, { "pai hang bang", "排行榜" }, { "pai hao", "拍好" },
			{ "pai hao", "排好" }, { "pai hao", "牌号" }, { "pai huai", "徘徊" }, { "pai ji", "排挤" }, { "pai jie", "排解" }, { "pai ke", "派克" }, { "pai lai", "派来" },
			{ "pai le pai", "拍了拍" }, { "pai lian", "排练" }, { "pai liang", "排量" }, { "pai lie", "排列" }, { "pai luan", "排卵" }, { "pai luan qi", "排卵期" },
			{ "pai ma pi", "拍马屁" }, { "pai mai", "拍卖" }, { "pai mai hang", "拍卖行" }, { "pai mai hui", "拍卖会" }, { "pai ming", "排名" }, { "pai ming qian", "排名前" },
			{ "pai niao", "排尿" }, { "pai pai", "拍拍" }, { "pai pian", "拍片" }, { "pai qi", "排期" }, { "pai qi", "排气" }, { "pai qi", "排起" },
			{ "pai qi guan", "排气管" }, { "pai qian", "派遣" }, { "pai qiu", "排球" }, { "pai ren", "派人" }, { "pai ru", "排入" }, { "pai she", "拍摄" },
			{ "pai sheng", "派生" } };
};
