package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN54 {
	public static String[][] pl = { { "xuan ge", "选个" }, { "xuan gou", "选购" }, { "xuan gu", "选股" }, { "xuan gua", "悬挂" }, { "xuan guan", "玄关" },
			{ "xuan hao", "选号" }, { "xuan hao", "选好" }, { "xuan hua", "喧哗" }, { "xuan huan", "玄幻" }, { "xuan ji", "旋即" }, { "xuan ji", "玄机" },
			{ "xuan jia", "悬架" }, { "xuan jiang", "宣讲" }, { "xuan jiang hui", "宣讲会" }, { "xuan jiao", "宣教" }, { "xuan ju", "选举" },
			{ "xuan ju chan sheng", "选举产生" }, { "xuan ke", "选课" }, { "xuan kong", "悬空" }, { "xuan lan", "绚烂" }, { "xuan li", "绚丽" }, { "xuan lv", "旋律" },
			{ "xuan mei", "选美" }, { "xuan miao", "玄妙" }, { "xuan min", "选民" }, { "xuan mu", "炫目" }, { "xuan mu", "眩目" }, { "xuan nao", "喧闹" },
			{ "xuan nian", "悬念" }, { "xuan niu", "旋钮" }, { "xuan pai", "选派" }, { "xuan pan", "宣判" }, { "xuan pei", "选配" }, { "xuan piao", "选票" },
			{ "xuan pin", "选聘" }, { "xuan qu", "选区" }, { "xuan qu", "选取" }, { "xuan ran", "渲染" }, { "xuan ran da bo", "轩然大波" }, { "xuan ren", "选人" },
			{ "xuan shang", "悬赏" }, { "xuan shang", "选上" }, { "xuan shang fen", "悬赏分" }, { "xuan shi", "宣示" }, { "xuan shi", "宣誓" }, { "xuan shou", "选手" },
			{ "xuan shu", "悬殊" }, { "xuan ti", "选题" }, { "xuan wei", "选为" }, { "xuan wo", "旋涡" }, { "xuan wo", "漩涡" }, { "xuan wu", "宣武" },
			{ "xuan wu", "玄武" }, { "xuan wu qu", "宣武区" }, { "xuan xiang", "选项" }, { "xuan xiang ka", "选项卡" }, { "xuan xiang zhong", "选项中" },
			{ "xuan xiao", "喧嚣" }, { "xuan xie", "宣泄" }, { "xuan xing", "选型" }, { "xuan xiu", "选修" }, { "xuan xiu", "选秀" }, { "xuan xiu ke", "选修课" },
			{ "xuan xuan", "宣萱" }, { "xuan ya", "悬崖" }, { "xuan yan", "宣言" }, { "xuan yang", "宣扬" }, { "xuan yao", "炫耀" }, { "xuan yi", "悬疑" },
			{ "xuan yong", "选用" }, { "xuan yu", "选育" }, { "xuan yuan", "轩辕" }, { "xuan yuan jian", "轩辕剑" }, { "xuan yun", "眩晕" }, { "xuan zai", "悬在" },
			{ "xuan zang", "玄奘" }, { "xuan ze", "选择" }, { "xuan ze hao", "选择好" }, { "xuan ze quan", "选择权" }, { "xuan ze ti", "选择题" },
			{ "xuan ze xing", "选择性" }, { "xuan zhan", "宣战" }, { "xuan zhe", "悬着" }, { "xuan zhi", "选址" }, { "xuan zhong", "选中" }, { "xuan zhuan", "旋转" },
			{ "xuan zi", "选自" }, { "xue", "削" }, { "xue", "吷" }, { "xue", "噱" }, { "xue", "壆" }, { "xue", "学" }, { "xue", "學" }, { "xue", "岤" },
			{ "xue", "嶨" }, { "xue", "彐" }, { "xue", "怴" }, { "xue", "斈" }, { "xue", "梋" }, { "xue", "樰" }, { "xue", "泧" }, { "xue", "泬" }, { "xue", "泶" },
			{ "xue", "澩" }, { "xue", "燢" }, { "xue", "狘" }, { "xue", "疶" }, { "xue", "瞲" }, { "xue", "穴" }, { "xue", "膤" }, { "xue", "艝" }, { "xue", "蒆" },
			{ "xue", "薛" }, { "xue", "血" }, { "xue", "袕" }, { "xue", "觷" }, { "xue", "謔" }, { "xue", "谑" }, { "xue", "趐" }, { "xue", "踅" }, { "xue", "轌" },
			{ "xue", "雪" }, { "xue", "靴" }, { "xue", "鱈" }, { "xue", "鳕" }, { "xue", "鷽" }, { "xue an", "血案" }, { "xue bai", "雪白" }, { "xue bao", "学报" },
			{ "xue ben", "血本" }, { "xue beng", "雪崩" }, { "xue bi", "雪碧" }, { "xue che", "学车" }, { "xue cheng", "学成" }, { "xue dao", "学到" }, { "xue de", "学得" },
			{ "xue di", "学弟" }, { "xue di", "雪地" }, { "xue dian", "学点" }, { "xue er", "雪儿" }, { "xue fa", "学法" }, { "xue fei", "学费" }, { "xue fen", "学分" },
			{ "xue feng", "学风" }, { "xue feng", "雪峰" }, { "xue fo", "学佛" }, { "xue fu", "学府" }, { "xue fu lan", "雪佛兰" }, { "xue gao", "雪糕" },
			{ "xue guan", "血管" }, { "xue guo", "学过" }, { "xue guo", "雪国" }, { "xue han", "血汗" }, { "xue han qian", "血汗钱" }, { "xue hao", "学号" },
			{ "xue hao", "学好" }, { "xue hong", "血红" }, { "xue hong dan bai", "血红蛋白" }, { "xue hua", "雪花" }, { "xue huai", "学坏" }, { "xue hui", "学会" },
			{ "xue ji", "学籍" }, { "xue ji", "血迹" }, { "xue jia", "学家" }, { "xue jia", "雪茄" }, { "xue jian", "削减" }, { "xue jiang", "血浆" }, { "xue jie", "学姐" },
			{ "xue jie", "学界" }, { "xue jing", "雪景" }, { "xue jing ling", "血精灵" }, { "xue ke", "学科" }, { "xue ke jian she", "学科建设" }, { "xue lei", "血泪" },
			{ "xue li", "学历" }, { "xue li", "雪梨" }, { "xue li jiao yu", "学历教育" }, { "xue lian", "雪莲" }, { "xue liang", "血量" }, { "xue liang", "雪亮" },
			{ "xue lin lin", "血淋淋" }, { "xue liu", "血流" }, { "xue liu liang", "血流量" }, { "xue mai", "血脉" }, { "xue mei", "学妹" }, { "xue mei", "雪梅" },
			{ "xue ming", "学名" }, { "xue nian", "学年" }, { "xue niao", "血尿" }, { "xue pai", "学派" }, { "xue pin", "血拼" }, { "xue qi", "学期" }, { "xue qi", "学起" },
			{ "xue qi", "血气" }, { "xue qing", "血清" }, { "xue qu", "学区" }, { "xue ren", "学人" }, { "xue ren", "雪人" }, { "xue rou", "血肉" }, { "xue ruo", "削弱" },
			{ "xue se", "血色" }, { "xue shan", "雪山" }, { "xue shang jia shuang", "雪上加霜" }, { "xue shen me", "学什么" }, { "xue sheng", "学生" },
			{ "xue sheng hui", "学生会" }, { "xue sheng jia zhang", "学生家长" }, { "xue sheng jin xing", "学生进行" }, { "xue sheng piao", "学生票" },
			{ "xue sheng shi dai", "学生时代" }, { "xue sheng su she", "学生宿舍" }, { "xue sheng xue xi", "学生学习" }, { "xue sheng zheng", "学生证" }, { "xue shi", "学士" },
			{ "xue shi", "学时" }, { "xue shi", "学识" }, { "xue shi xue wei", "学士学位" }, { "xue shu", "学术" }, { "xue shu hui yi", "学术会议" },
			{ "xue shu jiao liu", "学术交流" }, { "xue shu jie", "学术界" }, { "xue shu lun wen", "学术论文" }, { "xue shu yan jiu", "学术研究" }, { "xue shuan", "血栓" },
			{ "xue shuo", "学说" }, { "xue si", "血丝" }, { "xue song", "雪松" }, { "xue tang", "学堂" }, { "xue tang", "血糖" }, { "xue tie long", "雪铁龙" },
			{ "xue tong", "血统" }, { "xue tou", "噱头" }, { "xue tu", "学徒" }, { "xue wei", "学位" }, { "xue wei", "穴位" }, { "xue wei zheng", "学位证" },
			{ "xue wen", "学问" }, { "xue xi", "学习" }, { "xue xi ban", "学习班" }, { "xue xi cheng ji", "学习成绩" }, { "xue xi fang fa", "学习方法" },
			{ "xue xi fang shi", "学习方式" }, { "xue xi guan che", "学习贯彻" }, { "xue xi guo cheng", "学习过程" }, { "xue xi huan jing", "学习环境" },
			{ "xue xi huo dong", "学习活动" }, { "xue xi ji", "学习机" }, { "xue xi neng li", "学习能力" }, { "xue xi sheng huo", "学习生活" }, { "xue xi xing", "学习型" },
			{ "xue xi xing qu", "学习兴趣" }, { "xue xi ying yu", "学习英语" }, { "xue xi zhe", "学习者" }, { "xue xiao", "学校" }, { "xue xiao ban", "血小板" },
			{ "xue xiao jiao yu", "学校教育" }, { "xue xiao li", "学校里" }, { "xue xiao ling dao", "学校领导" }, { "xue xing", "血型" }, { "xue xing", "血性" },
			{ "xue xing", "血腥" }, { "xue xue", "学学" }, { "xue xue", "雪雪" }, { "xue ya", "血压" }, { "xue yan jiu", "学研究" }, { "xue ye", "学业" },
			{ "xue ye", "血液" }, { "xue ye xun huan", "血液循环" }, { "xue yi", "学医" }, { "xue yi", "学艺" }, { "xue ying yu", "学英语" }, { "xue you", "学友" },
			{ "xue yu", "雪域" }, { "xue yuan", "学员" }, { "xue yuan", "学园" }, { "xue yuan", "学院" }, { "xue yuan", "血缘" }, { "xue yuan guan xi", "血缘关系" },
			{ "xue yuan lu", "学院路" }, { "xue yuan yuan zhang", "学院院长" }, { "xue za fei", "学杂费" }, { "xue zai", "雪灾" }, { "xue zhan", "血战" },
			{ "xue zhan", "血站" }, { "xue zhang", "学长" }, { "xue zhe", "学着" }, { "xue zhe", "学者" }, { "xue zheng", "血症" }, { "xue zhi", "学制" },
			{ "xue zhi", "血脂" }, { "xue zhong", "血肿" }, { "xue zhong", "雪中" }, { "xue zi", "学子" }, { "xue zi", "靴子" }, { "xun", "侚" }, { "xun", "勋" },
			{ "xun", "勛" }, { "xun", "勲" }, { "xun", "勳" }, { "xun", "咰" }, { "xun", "噀" }, { "xun", "噚" }, { "xun", "埙" }, { "xun", "塤" }, { "xun", "壎" },
			{ "xun", "寻" }, { "xun", "尋" }, { "xun", "峋" }, { "xun", "巡" }, { "xun", "巽" }, { "xun", "徇" }, { "xun", "循" }, { "xun", "恂" }, { "xun", "愻" },
			{ "xun", "揗" }, { "xun", "撏" }, { "xun", "攳" }, { "xun", "旬" }, { "xun", "曛" }, { "xun", "栒" }, { "xun", "殉" }, { "xun", "汛" }, { "xun", "洵" },
			{ "xun", "浔" }, { "xun", "浚" }, { "xun", "潯" }, { "xun", "濬" }, { "xun", "灥" }, { "xun", "焄" }, { "xun", "熏" }, { "xun", "燂" }, { "xun", "燅" },
			{ "xun", "燖" }, { "xun", "燻" }, { "xun", "獯" }, { "xun", "珣" }, { "xun", "璕" }, { "xun", "眴" }, { "xun", "矄" }, { "xun", "窨" }, { "xun", "紃" },
			{ "xun", "纁" }, { "xun", "臐" }, { "xun", "荀" }, { "xun", "荨" }, { "xun", "葷" }, { "xun", "蔒" }, { "xun", "蕈" }, { "xun", "薫" }, { "xun", "薰" },
			{ "xun", "蟳" }, { "xun", "襑" }, { "xun", "訊" }, { "xun", "訓" }, { "xun", "詢" }, { "xun", "训" }, { "xun", "讯" }, { "xun", "询" }, { "xun", "迅" },
			{ "xun", "迿" }, { "xun", "逊" }, { "xun", "遜" }, { "xun", "郇" }, { "xun", "鄩" }, { "xun", "醺" }, { "xun", "馴" }, { "xun", "驯" }, { "xun", "鱘" },
			{ "xun", "鲟" }, { "xun bao", "寻宝" }, { "xun cha", "巡查" }, { "xun chang", "寻常" }, { "xun chi", "训斥" }, { "xun chi", "迅驰" }, { "xun fang", "寻访" },
			{ "xun fu", "巡抚" }, { "xun fu", "驯服" }, { "xun gen", "寻根" }, { "xun hang", "巡航" }, { "xun hang dao dan", "巡航导弹" }, { "xun hao", "讯号" },
			{ "xun hu", "寻呼" }, { "xun huan", "循环" }, { "xun huan jing ji", "循环经济" }, { "xun huan xi tong", "循环系统" }, { "xun hui", "巡回" },
			{ "xun hui sai", "巡回赛" }, { "xun jia", "询价" }, { "xun jian", "巡检" }, { "xun jie", "迅捷" }, { "xun jing", "巡警" }, { "xun lei", "迅雷" },
			{ "xun lei xia zai", "迅雷下载" }, { "xun lian", "训练" }, { "xun lian chang", "训练场" }, { "xun lian ji di", "训练基地" }, { "xun lian shi", "训练师" },
			{ "xun lian ying", "训练营" }, { "xun lian you su", "训练有素" }, { "xun luo", "巡逻" }, { "xun ma zhen", "荨麻疹" }, { "xun meng", "寻梦" },
			{ "xun meng", "迅猛" }, { "xun meng fa zhan", "迅猛发展" }, { "xun mi", "寻觅" }, { "xun qi", "汛期" }, { "xun qiu", "寻求" }, { "xun se", "逊色" },
			{ "xun shi", "巡视" }, { "xun shi yuan", "巡视员" }, { "xun si", "寻思" }, { "xun su", "迅速" }, { "xun su fa zhan", "迅速发展" }, { "xun tao", "熏陶" },
			{ "xun wen", "讯问" }, { "xun wen", "询问" }, { "xun xi", "讯息" }, { "xun xu jian jin", "循序渐进" }, { "xun yan", "巡演" }, { "xun yang jian", "巡洋舰" },
			{ "xun yi cao", "薰衣草" }, { "xun you", "巡游" }, { "xun yu", "逊于" }, { "xun zhan", "巡展" }, { "xun zhang", "勋章" }, { "xun zhao", "寻找" },
			{ "xun zheng", "熏蒸" }, { "xun zhi", "寻址" }, { "xun zu", "寻租" }, { "ya", "丫" }, { "ya", "亚" }, { "ya", "亜" }, { "ya", "亞" }, { "ya", "伢" },
			{ "ya", "劜" }, { "ya", "厊" }, { "ya", "压" }, { "ya", "厓" }, { "ya", "吖" }, { "ya", "呀" }, { "ya", "呾" }, { "ya", "哑" }, { "ya", "唖" },
			{ "ya", "啞" }, { "ya", "圔" }, { "ya", "圠" }, { "ya", "圧" }, { "ya", "垭" }, { "ya", "埡" }, { "ya", "堐" }, { "ya", "壓" }, { "ya", "姶" },
			{ "ya", "娅" }, { "ya", "婭" }, { "ya", "孲" }, { "ya", "岈" }, { "ya", "崕" }, { "ya", "崖" }, { "ya", "庌" }, { "ya", "押" }, { "ya", "掗" },
			{ "ya", "揠" }, { "ya", "桠" }, { "ya", "椏" }, { "ya", "氩" }, { "ya", "氬" }, { "ya", "涯" }, { "ya", "牙" }, { "ya", "犽" }, { "ya", "猰" },
			{ "ya", "玡" }, { "ya", "琊" }, { "ya", "疋" }, { "ya", "痖" }, { "ya", "睚" }, { "ya", "砑" }, { "ya", "磍" }, { "ya", "穵" }, { "ya", "聐" },
			{ "ya", "芽" }, { "ya", "蕥" }, { "ya", "蚜" }, { "ya", "衙" }, { "ya", "襾" }, { "ya", "訝" }, { "ya", "讶" }, { "ya", "輅" }, { "ya", "輵" },
			{ "ya", "轧" }, { "ya", "迓" }, { "ya", "錏" }, { "ya", "鐚" }, { "ya", "雅" }, { "ya", "鴉" }, { "ya", "鴨" }, { "ya", "鸦" }, { "ya", "鸭" },
			{ "ya", "齖" }, { "ya", "齾" }, { "ya an", "雅安" }, { "ya ba", "哑巴" }, { "ya chi", "牙齿" }, { "ya dan", "鸭蛋" }, { "ya dang", "亚当" },
			{ "ya dao", "压倒" }, { "ya de", "压得" }, { "ya di", "压低" }, { "ya dian", "雅典" }, { "ya dian na", "雅典娜" }, { "ya dong", "亚东" }, { "ya fang", "雅芳" },
			{ "ya gao", "牙膏" }, { "ya ge", "雅阁" }, { "ya ge er", "雅戈尔" }, { "ya gen", "压根" }, { "ya guan", "亚冠" }, { "ya hu", "雅虎" },
			{ "ya hu zhong guo", "雅虎中国" }, { "ya huan", "丫鬟" }, { "ya jia", "压价" }, { "ya jia da", "雅加达" }, { "ya jian kang", "亚健康" }, { "ya jin", "押金" },
			{ "ya jun", "亚军" }, { "ya ke", "亚克" }, { "ya ke", "牙科" }, { "ya li", "压力" }, { "ya li da", "压力大" }, { "ya li shan da", "亚历山大" },
			{ "ya ling", "哑铃" }, { "ya ma", "亚麻" }, { "ya ma xun", "亚马逊" }, { "ya men", "衙门" }, { "ya ou", "亚欧" }, { "ya pian", "鸦片" },
			{ "ya pian zhan zheng", "鸦片战争" }, { "ya po", "压迫" }, { "ya qian", "牙签" }, { "ya re dai", "亚热带" }, { "ya se", "亚瑟" }, { "ya shi", "亚视" },
			{ "ya shua", "牙刷" }, { "ya si", "压死" }, { "ya si", "雅思" }, { "ya sui qian", "压岁钱" }, { "ya suo", "压缩" }, { "ya suo bao", "压缩包" },
			{ "ya suo ji", "压缩机" }, { "ya suo wen jian", "压缩文件" }, { "ya tai", "亚太" }, { "ya tai", "亚泰" }, { "ya tai di qu", "亚太地区" }, { "ya tai qu", "亚太区" },
			{ "ya te lan da", "亚特兰大" }, { "ya teng", "牙疼" }, { "ya tong", "牙痛" }, { "ya tou", "丫头" }, { "ya xia", "压下" }, { "ya xin", "亚信" },
			{ "ya ya", "丫丫" }, { "ya ya", "呀呀" }, { "ya ya", "牙牙" }, { "ya yi", "亚裔" }, { "ya yi", "压抑" }, { "ya yi", "牙医" }, { "ya yin", "牙龈" },
			{ "ya yu", "亚于" }, { "ya yun", "亚运" }, { "ya yun cun", "亚运村" }, { "ya yun hui", "亚运会" }, { "ya zai", "压在" }, { "ya zha", "压榨" },
			{ "ya zhe", "压着" }, { "ya zhi", "压制" }, { "ya zhi", "雅致" }, { "ya zhou", "亚洲" }, { "ya zhou", "压轴" }, { "ya zhou bei", "亚洲杯" },
			{ "ya zhou di yi", "亚洲第一" }, { "ya zhou guo jia", "亚洲国家" }, { "ya zhou qu", "亚洲区" }, { "ya zhou ren", "亚洲人" }, { "ya zhou zui da", "亚洲最大" },
			{ "ya zhu", "压住" }, { "ya zi", "鸭子" }, { "ya zu lian", "亚足联" }, { "yan", "严" }, { "yan", "俨" }, { "yan", "偃" }, { "yan", "偐" }, { "yan", "偣" },
			{ "yan", "儼" }, { "yan", "兖" }, { "yan", "兗" }, { "yan", "円" }, { "yan", "剡" }, { "yan", "匽" }, { "yan", "厌" }, { "yan", "厣" }, { "yan", "厭" },
			{ "yan", "厳" }, { "yan", "厴" }, { "yan", "咽" }, { "yan", "唁" }, { "yan", "唌" }, { "yan", "喦" }, { "yan", "喭" }, { "yan", "噞" }, { "yan", "嚥" },
			{ "yan", "嚴" }, { "yan", "埏" }, { "yan", "堰" }, { "yan", "塩" }, { "yan", "壛" }, { "yan", "壧" }, { "yan", "奄" }, { "yan", "妍" }, { "yan", "姲" },
			{ "yan", "姸" }, { "yan", "娮" }, { "yan", "媕" }, { "yan", "嫣" }, { "yan", "嬐" }, { "yan", "嬮" }, { "yan", "嬿" }, { "yan", "孍" }, { "yan", "宴" },
			{ "yan", "岩" }, { "yan", "崦" }, { "yan", "嵃" }, { "yan", "嵒" }, { "yan", "嵓" }, { "yan", "嶮" }, { "yan", "巌" }, { "yan", "巖" }, { "yan", "巘" },
			{ "yan", "延" }, { "yan", "弇" }, { "yan", "彥" }, { "yan", "彦" }, { "yan", "恹" }, { "yan", "愝" }, { "yan", "扊" }, { "yan", "抁" }, { "yan", "挩" },
			{ "yan", "挻" }, { "yan", "掩" }, { "yan", "揅" }, { "yan", "揜" }, { "yan", "敥" }, { "yan", "晏" }, { "yan", "晻" }, { "yan", "曮" }, { "yan", "棪" },
			{ "yan", "椻" }, { "yan", "椼" }, { "yan", "楌" }, { "yan", "樮" }, { "yan", "橪" }, { "yan", "檐" }, { "yan", "殷" }, { "yan", "沇" }, { "yan", "沿" },
			{ "yan", "洝" }, { "yan", "淊" }, { "yan", "淹" }, { "yan", "渰" }, { "yan", "湮" }, { "yan", "湺" }, { "yan", "溎" }, { "yan", "滟" }, { "yan", "演" },
			{ "yan", "漹" }, { "yan", "灩" }, { "yan", "炎" }, { "yan", "烟" }, { "yan", "烻" }, { "yan", "焉" }, { "yan", "焔" }, { "yan", "焰" }, { "yan", "焱" },
			{ "yan", "煙" }, { "yan", "燄" }, { "yan", "燕" }, { "yan", "爓" }, { "yan", "牪" }, { "yan", "狿" }, { "yan", "猒" }, { "yan", "珚" }, { "yan", "琰" },
			{ "yan", "甗" }, { "yan", "盐" }, { "yan", "眼" }, { "yan", "研" }, { "yan", "砚" }, { "yan", "硏" }, { "yan", "硯" }, { "yan", "碞" }, { "yan", "礹" },
			{ "yan", "筵" }, { "yan", "篶" }, { "yan", "簷" }, { "yan", "綖" }, { "yan", "縯" }, { "yan", "罨" }, { "yan", "胭" }, { "yan", "腌" }, { "yan", "臙" },
			{ "yan", "艳" }, { "yan", "艶" }, { "yan", "艷" }, { "yan", "芫" }, { "yan", "莚" }, { "yan", "菴" }, { "yan", "菸" }, { "yan", "萒" }, { "yan", "薟" },
			{ "yan", "虤" }, { "yan", "蜒" }, { "yan", "蝘" }, { "yan", "衍" }, { "yan", "裺" }, { "yan", "褗" }, { "yan", "觾" }, { "yan", "言" }, { "yan", "諺" },
			{ "yan", "讌" }, { "yan", "讞" }, { "yan", "讠" }, { "yan", "谚" }, { "yan", "谳" }, { "yan", "豔" }, { "yan", "豜" }, { "yan", "贋" }, { "yan", "贗" },
			{ "yan", "赝" }, { "yan", "躽" }, { "yan", "軅" }, { "yan", "郔" }, { "yan", "郾" }, { "yan", "鄢" }, { "yan", "酀" }, { "yan", "酽" }, { "yan", "醃" },
			{ "yan", "醼" }, { "yan", "釅" }, { "yan", "錟" }, { "yan", "铅" }, { "yan", "閆" }, { "yan", "閹" }, { "yan", "閻" }, { "yan", "闫" }, { "yan", "阉" },
			{ "yan", "阎" }, { "yan", "阏" }, { "yan", "阽" }, { "yan", "隒" }, { "yan", "雁" }, { "yan", "顏" }, { "yan", "顔" }, { "yan", "顩" }, { "yan", "颜" },
			{ "yan", "餍" }, { "yan", "饜" }, { "yan", "験" }, { "yan", "騴" }, { "yan", "驗" }, { "yan", "驠" }, { "yan", "验" }, { "yan", "鬳" }, { "yan", "魇" },
			{ "yan", "魘" }, { "yan", "鰋" }, { "yan", "鳫" }, { "yan", "鳱" }, { "yan", "鴈" }, { "yan", "鴳" }, { "yan", "鶠" }, { "yan", "鷃" }, { "yan", "鷰" },
			{ "yan", "鹽" }, { "yan", "麙" }, { "yan", "黤" }, { "yan", "黫" }, { "yan", "黭" }, { "yan", "黶" }, { "yan", "鼴" }, { "yan", "鼹" }, { "yan", "齞" },
			{ "yan", "齴" }, { "yan", "龑" }, { "yan an", "延安" }, { "yan an", "沿岸" }, { "yan ba", "严把" }, { "yan ba ba", "眼巴巴" }, { "yan bian", "延边" },
			{ "yan bian", "演变" }, { "yan bo shi", "演播室" }, { "yan bu", "眼部" }, { "yan cang", "掩藏" }, { "yan cao", "烟草" }, { "yan cha", "严查" },
			{ "yan chang", "延长" }, { "yan chang", "演唱" }, { "yan chang hui", "演唱会" }, { "yan chang xian", "延长线" }, { "yan chen", "烟尘" }, { "yan cheng", "严惩" },
			{ "yan cheng", "盐城" }, { "yan cheng xu", "言承旭" }, { "yan chi", "延迟" }, { "yan chu", "演出" }, { "yan ci", "言词" }, { "yan ci", "言辞" },
			{ "yan cong", "烟囱" }, { "yan da", "严打" }, { "yan dai", "眼袋" }, { "yan de", "演得" }, { "yan de", "演的" }, { "yan di", "炎帝" }, { "yan di", "眼底" },
			{ "yan dong", "严冬" }, { "yan dou", "烟斗" }, { "yan du", "研读" }, { "yan fa", "研发" }, { "yan fa bu", "研发部" }, { "yan fa ren yuan", "研发人员" },
			{ "yan fa zhong xin", "研发中心" }, { "yan fan", "厌烦" }, { "yan fang", "严防" }, { "yan fang", "验房" }, { "yan gai", "掩盖" }, { "yan ge", "严格" },
			{ "yan ge", "阉割" }, { "yan ge an zhao", "严格按照" }, { "yan ge kong zhi", "严格控制" }, { "yan ge yao qiu", "严格要求" }, { "yan ge zhi xing", "严格执行" },
			{ "yan ge zun shou", "严格遵守" }, { "yan guang", "眼光" }, { "yan guo", "演过" }, { "yan hai", "沿海" }, { "yan hai di qu", "沿海地区" }, { "yan han", "严寒" },
			{ "yan he", "沿河" }, { "yan hong", "眼红" }, { "yan hou", "咽喉" }, { "yan hou", "延后" }, { "yan hu", "掩护" }, { "yan hua", "演化" }, { "yan hua", "烟花" },
			{ "yan hua", "眼花" }, { "yan hua bao zhu", "烟花爆竹" }, { "yan hua liao luan", "眼花缭乱" }, { "yan huan", "延缓" }, { "yan huan shuai lao", "延缓衰老" },
			{ "yan huang", "炎黄" }, { "yan huang zi sun", "炎黄子孙" }, { "yan hui", "宴会" }, { "yan hui", "烟灰" }, { "yan hui gang", "烟灰缸" }, { "yan huo", "烟火" },
			{ "yan huo", "焰火" }, { "yan huo", "验货" }, { "yan ji", "延吉" }, { "yan ji", "演技" }, { "yan jian", "眼睑" }, { "yan jian", "眼见" },
			{ "yan jiang", "岩浆" }, { "yan jiang", "沿江" }, { "yan jiang", "演讲" }, { "yan jiang gao", "演讲稿" }, { "yan jiao", "燕郊" }, { "yan jiao", "眼角" },
			{ "yan jie", "沿街" }, { "yan jie", "眼界" }, { "yan jin", "严禁" }, { "yan jin", "严谨" }, { "yan jin", "演进" }, { "yan jing", "燕京" },
			{ "yan jing", "眼睛" }, { "yan jing", "眼镜" }, { "yan jing li", "眼睛里" }, { "yan jiu", "烟酒" }, { "yan jiu", "研究" }, { "yan jiu bao gao", "研究报告" },
			{ "yan jiu bu", "研究部" }, { "yan jiu cheng guo", "研究成果" }, { "yan jiu dui xiang", "研究对象" }, { "yan jiu fa xian", "研究发现" },
			{ "yan jiu fang fa", "研究方法" }, { "yan jiu fang xiang", "研究方向" }, { "yan jiu gong zuo", "研究工作" }, { "yan jiu hui", "研究会" },
			{ "yan jiu ji gou", "研究机构" }, { "yan jiu jin zhan", "研究进展" }, { "yan jiu kai fa", "研究开发" }, { "yan jiu ke ti", "研究课题" },
			{ "yan jiu ling yu", "研究领域" }, { "yan jiu ren yuan", "研究人员" }, { "yan jiu sheng", "研究生" }, { "yan jiu sheng yuan", "研究生院" },
			{ "yan jiu shi", "研究室" }, { "yan jiu suo", "研究所" }, { "yan jiu xian zhuang", "研究现状" }, { "yan jiu xiang mu", "研究项目" },
			{ "yan jiu xiao zu", "研究小组" }, { "yan jiu xing", "研究型" }, { "yan jiu yuan", "研究员" }, { "yan jiu yuan", "研究院" }, { "yan jiu zhe", "研究者" },
			{ "yan jiu zhong xin", "研究中心" }, { "yan juan", "厌倦" }, { "yan jun", "严峻" }, { "yan kan", "眼看" }, { "yan ke", "眼科" }, { "yan ku", "严酷" },
			{ "yan kuang", "眼眶" }, { "yan lei", "眼泪" }, { "yan li", "严厉" }, { "yan li", "眼力" }, { "yan li", "眼里" }, { "yan li", "艳丽" },
			{ "yan li da ji", "严厉打击" }, { "yan lian", "演练" }, { "yan lian", "眼帘" }, { "yan liao", "颜料" }, { "yan lu", "沿路" }, { "yan lun", "言论" },
			{ "yan lun zi you", "言论自由" }, { "yan mai", "掩埋" }, { "yan mai", "燕麦" }, { "yan mi", "严密" }, { "yan mian", "颜面" }, { "yan mie", "湮灭" },
			{ "yan ming", "严明" }, { "yan mo", "淹没" }, { "yan mo", "研磨" }, { "yan mou", "眼眸" }, { "yan nian yi shou", "延年益寿" }, { "yan pan", "研判" },
			{ "yan pi", "眼皮" }, { "yan pin", "赝品" }, { "yan qi", "延期" }, { "yan qi", "烟气" }, { "yan qian", "眼前" }, { "yan qing", "宴请" }, { "yan qing", "延庆" },
			{ "yan qing", "言情" }, { "yan qing xiao shuo", "言情小说" }, { "yan qiu", "眼球" }, { "yan quan", "眼圈" }, { "yan ran", "俨然" }, { "yan ran", "嫣然" },
			{ "yan re", "炎热" }, { "yan se", "眼色" }, { "yan se", "颜色" }, { "yan shan", "燕山" }, { "yan she", "衍射" }, { "yan shen", "延伸" }, { "yan shen", "眼神" },
			{ "yan shen zhi", "延伸至" }, { "yan sheng", "衍生" }, { "yan sheng chu", "衍生出" }, { "yan sheng pin", "衍生品" }, { "yan sheng wu", "衍生物" },
			{ "yan shi", "岩石" }, { "yan shi", "延时" }, { "yan shi", "掩饰" }, { "yan shi", "演示" }, { "yan shou", "验收" }, { "yan shu", "眼熟" },
			{ "yan shuang", "眼霜" }, { "yan shui", "盐水" }, { "yan shuo", "演说" }, { "yan shuo", "言说" }, { "yan si", "淹死" }, { "yan su", "严肃" },
			{ "yan su chu li", "严肃处理" }, { "yan su xing", "严肃性" }, { "yan suan", "盐酸" }, { "yan tai", "烟台" }, { "yan tai shi", "烟台市" }, { "yan tan", "言谈" },
			{ "yan tao", "研讨" }, { "yan tao hui", "研讨会" }, { "yan tou", "烟头" }, { "yan tu", "沿途" }, { "yan wang", "阎王" }, { "yan wei", "烟味" },
			{ "yan wo", "燕窝" }, { "yan wu", "厌恶" }, { "yan wu", "延误" }, { "yan wu", "烟雾" }, { "yan xi", "宴席" }, { "yan xi", "沿袭" }, { "yan xi", "演习" },
			{ "yan xi", "演戏" }, { "yan xia", "咽下" }, { "yan xia", "眼下" } };
};
