package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN32 {
	public static String[][] pl = { { "mei xiao", "媚笑" }, { "mei xin mei fei", "没心没肺" }, { "mei xue", "没学" }, { "mei xue", "美学" }, { "mei ya", "美亚" },
			{ "mei yan", "媚眼" }, { "mei yan", "眉眼" }, { "mei yan", "美艳" }, { "mei yan fang", "梅艳芳" }, { "mei yang", "每样" }, { "mei ye", "每页" },
			{ "mei ye", "煤业" }, { "mei yi", "每一" }, { "mei yi bu", "每一步" }, { "mei yi ci", "每一次" }, { "mei yi ge ren", "每一个人" }, { "mei yi si", "没意思" },
			{ "mei yi tian", "每一天" }, { "mei yi wei", "每一位" }, { "mei yi zhong", "每一种" }, { "mei ying", "美英" }, { "mei ying", "魅影" }, { "mei yong", "没用" },
			{ "mei you", "没有" }, { "mei you an zhuang", "没有安装" }, { "mei you ban fa", "没有办法" }, { "mei you bi yao", "没有必要" }, { "mei you cuo", "没有错" },
			{ "mei you fa xian", "没有发现" }, { "mei you fan ying", "没有反应" }, { "mei you gan jue", "没有感觉" }, { "mei you guan xi", "没有关系" },
			{ "mei you ji hui", "没有机会" }, { "mei you jian guo", "没有见过" }, { "mei you li you", "没有理由" }, { "mei you qian", "没有钱" },
			{ "mei you ren he", "没有任何" }, { "mei you ren hui", "没有人会" }, { "mei you shen me", "没有什么" }, { "mei you sheng yin", "没有声音" },
			{ "mei you shi jian", "没有时间" }, { "mei you wen ti", "没有问题" }, { "mei you xiang dao", "没有想到" }, { "mei you yi si", "没有意思" },
			{ "mei you yi yi", "没有意义" }, { "mei you yong", "没有用" }, { "mei you zhao dao", "没有找到" }, { "mei you zu gou", "没有足够" }, { "mei yu", "梅雨" },
			{ "mei yu", "美玉" }, { "mei yu", "美誉" }, { "mei yu", "美语" }, { "mei yu du", "美誉度" }, { "mei yuan", "美元" }, { "mei yuan", "美圆" },
			{ "mei yuan", "美院" }, { "mei yuan dui", "美元兑" }, { "mei yue", "每月" }, { "mei zai", "没再" }, { "mei zai", "没在" }, { "mei zhang", "每张" },
			{ "mei zhao", "没招" }, { "mei zhe", "没辙" }, { "mei zhi", "每只" }, { "mei zhong", "每种" }, { "mei zhong", "美中" }, { "mei zhong bu zu", "美中不足" },
			{ "mei zhou", "梅州" }, { "mei zhou", "每周" }, { "mei zhou", "美洲" }, { "mei zhou bei", "美洲杯" }, { "mei zhun", "没准" }, { "mei zi", "妹子" },
			{ "mei zi", "梅子" }, { "mei zi", "美子" }, { "mei zu", "每组" }, { "mei zu", "魅族" }, { "mei zuo", "没做" }, { "men", "亹" }, { "men", "们" },
			{ "men", "們" }, { "men", "悗" }, { "men", "悶" }, { "men", "懑" }, { "men", "懣" }, { "men", "扪" }, { "men", "捫" }, { "men", "暪" }, { "men", "椚" },
			{ "men", "殙" }, { "men", "満" }, { "men", "焖" }, { "men", "燜" }, { "men", "璊" }, { "men", "菛" }, { "men", "虋" }, { "men", "鍆" }, { "men", "钔" },
			{ "men", "門" }, { "men", "门" }, { "men", "闷" }, { "men", "鞔" }, { "men ban", "门板" }, { "men bian", "门边" }, { "men chuang", "门窗" },
			{ "men dang hu dui", "门当户对" }, { "men dao", "门道" }, { "men de", "们的" }, { "men dian", "门店" }, { "men feng", "门缝" }, { "men hou", "门后" },
			{ "men hu", "门户" }, { "men hu wang zhan", "门户网站" }, { "men jiang", "门将" }, { "men jin", "门禁" }, { "men jiu", "们就" }, { "men kai", "门开" },
			{ "men kan", "门槛" }, { "men ke", "门课" }, { "men ke cheng", "门课程" }, { "men kou", "门口" }, { "men kuang", "门框" }, { "men lei", "门类" },
			{ "men ling", "门铃" }, { "men lu", "门路" }, { "men men", "闷闷" }, { "men mian", "门面" }, { "men pai", "门派" }, { "men pai", "门牌" },
			{ "men piao", "门票" }, { "men qian", "门前" }, { "men re", "闷热" }, { "men sao", "闷骚" }, { "men shang", "门上" }, { "men shen", "门神" },
			{ "men shi", "门市" }, { "men si", "闷死" }, { "men suo", "门锁" }, { "men tu", "门徒" }, { "men wai", "门外" }, { "men wei", "门卫" }, { "men xia", "门下" },
			{ "men ya", "门牙" }, { "men zhen", "门诊" }, { "men zhen bu", "门诊部" }, { "men zhu", "门柱" }, { "meng", "儚" }, { "meng", "勐" }, { "meng", "夢" },
			{ "meng", "孟" }, { "meng", "幪" }, { "meng", "庬" }, { "meng", "懞" }, { "meng", "懵" }, { "meng", "曚" }, { "meng", "朦" }, { "meng", "梦" },
			{ "meng", "檬" }, { "meng", "氋" }, { "meng", "氓" }, { "meng", "濛" }, { "meng", "猛" }, { "meng", "瓾" }, { "meng", "甍" }, { "meng", "甿" },
			{ "meng", "盟" }, { "meng", "瞢" }, { "meng", "矇" }, { "meng", "礞" }, { "meng", "罞" }, { "meng", "艋" }, { "meng", "艨" }, { "meng", "萌" },
			{ "meng", "萠" }, { "meng", "蒙" }, { "meng", "蕄" }, { "meng", "虻" }, { "meng", "蜢" }, { "meng", "蠓" }, { "meng", "鄳" }, { "meng", "鄸" },
			{ "meng", "鋂" }, { "meng", "錳" }, { "meng", "锰" }, { "meng", "霥" }, { "meng", "饛" }, { "meng", "鸏" }, { "meng", "鼆" }, { "meng bi", "蒙蔽" },
			{ "meng dao", "梦到" }, { "meng de", "猛地" }, { "meng di ou", "蒙迪欧" }, { "meng dong", "懵懂" }, { "meng fa", "萌发" }, { "meng gong chang", "梦工厂" },
			{ "meng gu", "蒙古" }, { "meng gu ren", "蒙古人" }, { "meng gu zu", "蒙古族" }, { "meng guo", "盟国" }, { "meng hu", "猛虎" }, { "meng huan", "梦幻" },
			{ "meng huan xi you", "梦幻西游" }, { "meng jia la", "孟加拉" }, { "meng jian", "梦见" }, { "meng jiang", "猛将" }, { "meng jing", "梦境" },
			{ "meng jun", "盟军" }, { "meng le", "蒙了" }, { "meng li", "梦里" }, { "meng lie", "猛烈" }, { "meng long", "朦胧" }, { "meng long", "猛龙" },
			{ "meng lu", "梦露" }, { "meng mai", "孟买" }, { "meng mei yi qiu", "梦寐以求" }, { "meng meng", "梦梦" }, { "meng meng", "萌萌" }, { "meng meng", "蒙蒙" },
			{ "meng mian", "蒙面" }, { "meng na li sha", "蒙娜丽莎" }, { "meng nan", "猛男" }, { "meng niu", "蒙牛" }, { "meng pian", "蒙骗" }, { "meng ran", "猛然" },
			{ "meng shang", "蒙上" }, { "meng sheng", "萌生" }, { "meng shou", "猛兽" }, { "meng shou", "蒙受" }, { "meng te li er", "蒙特利尔" }, { "meng wang", "梦网" },
			{ "meng xiang", "梦乡" }, { "meng xiang", "梦想" }, { "meng xiang cheng zhen", "梦想成真" }, { "meng xing", "梦醒" }, { "meng ya", "萌芽" },
			{ "meng yan", "梦魇" }, { "meng you", "梦游" }, { "meng you", "盟友" }, { "meng zeng", "猛增" }, { "meng zhang", "猛涨" }, { "meng zhe", "蒙着" },
			{ "meng zhong", "梦中" }, { "meng zhong de", "梦中的" }, { "meng zhong qing ren", "梦中情人" }, { "meng zhu", "盟主" }, { "meng zi", "孟子" }, { "mi", "冞" },
			{ "mi", "冪" }, { "mi", "咪" }, { "mi", "嘧" }, { "mi", "塓" }, { "mi", "宓" }, { "mi", "密" }, { "mi", "尒" }, { "mi", "尓" }, { "mi", "峚" },
			{ "mi", "幂" }, { "mi", "幎" }, { "mi", "幦" }, { "mi", "弥" }, { "mi", "弭" }, { "mi", "彌" }, { "mi", "敉" }, { "mi", "榓" }, { "mi", "樒" },
			{ "mi", "櫁" }, { "mi", "汨" }, { "mi", "汩" }, { "mi", "泌" }, { "mi", "渳" }, { "mi", "滵" }, { "mi", "漞" }, { "mi", "瀰" }, { "mi", "灖" },
			{ "mi", "熐" }, { "mi", "爢" }, { "mi", "猕" }, { "mi", "獼" }, { "mi", "眯" }, { "mi", "瞇" }, { "mi", "祕" }, { "mi", "祢" }, { "mi", "秘" },
			{ "mi", "穈" }, { "mi", "米" }, { "mi", "糜" }, { "mi", "糸" }, { "mi", "縻" }, { "mi", "羃" }, { "mi", "羋" }, { "mi", "脒" }, { "mi", "芈" },
			{ "mi", "葞" }, { "mi", "蓂" }, { "mi", "蔝" }, { "mi", "蔤" }, { "mi", "蘼" }, { "mi", "蜜" }, { "mi", "蝆" }, { "mi", "覓" }, { "mi", "覛" },
			{ "mi", "觅" }, { "mi", "謎" }, { "mi", "謐" }, { "mi", "谜" }, { "mi", "谧" }, { "mi", "迷" }, { "mi", "醚" }, { "mi", "醾" }, { "mi", "銤" },
			{ "mi", "靡" }, { "mi", "鸍" }, { "mi", "麊" }, { "mi", "麋" }, { "mi", "麛" }, { "mi", "鼏" }, { "mi bi", "密闭" }, { "mi bu", "密布" }, { "mi bu", "弥补" },
			{ "mi bu ke fen", "密不可分" }, { "mi cai", "迷彩" }, { "mi chu", "米处" }, { "mi dao", "迷倒" }, { "mi de", "米的" }, { "mi di", "谜底" }, { "mi du", "密度" },
			{ "mi er", "米尔" }, { "mi fa", "秘法" }, { "mi fan", "米饭" }, { "mi fang", "秘方" }, { "mi fen", "米粉" }, { "mi feng", "密封" }, { "mi feng", "蜜蜂" },
			{ "mi gao", "米高" }, { "mi gong", "迷宫" }, { "mi guo", "米国" }, { "mi hou tao", "猕猴桃" }, { "mi hu", "迷糊" }, { "mi huan", "迷幻" }, { "mi huo", "迷惑" },
			{ "mi ji", "密集" }, { "mi ji", "秘笈" }, { "mi ji", "秘籍" }, { "mi ji xing", "密集型" }, { "mi jin", "迷津" }, { "mi jiu", "米酒" }, { "mi jue", "秘诀" },
			{ "mi la", "米拉" }, { "mi lan", "米兰" }, { "mi lan", "糜烂" }, { "mi lao shu", "米老鼠" }, { "mi le", "米勒" }, { "mi li", "米粒" }, { "mi li", "迷离" },
			{ "mi lian", "迷恋" }, { "mi lin", "密林" }, { "mi lu", "米卢" }, { "mi lu", "迷路" }, { "mi luan", "迷乱" }, { "mi ma", "密码" }, { "mi ma bao hu", "密码保护" },
			{ "mi man", "弥漫" }, { "mi mang", "迷茫" }, { "mi men", "迷们" }, { "mi meng", "迷蒙" }, { "mi mi", "咪咪" }, { "mi mi", "密密" }, { "mi mi", "秘密" },
			{ "mi mi", "米米" }, { "mi mi hu hu", "迷迷糊糊" }, { "mi mi ma ma", "密密麻麻" }, { "mi mou", "密谋" }, { "mi ni", "迷你" }, { "mi qi", "米奇" },
			{ "mi qi lin", "米其林" }, { "mi qie", "密切" }, { "mi qie guan zhu", "密切关注" }, { "mi qie lian xi", "密切联系" }, { "mi qie pei he", "密切配合" },
			{ "mi qie xiang guan", "密切相关" }, { "mi ren", "迷人" }, { "mi se", "米色" }, { "mi shang", "迷上" }, { "mi shi", "密室" }, { "mi shi", "觅食" },
			{ "mi shi", "迷失" }, { "mi shu", "秘书" }, { "mi shu chu", "秘书处" }, { "mi shu zhang", "秘书长" }, { "mi tang", "蜜糖" }, { "mi tu", "迷途" },
			{ "mi tuan", "谜团" }, { "mi wang", "迷惘" }, { "mi wu", "迷雾" }, { "mi xian", "米线" }, { "mi xin", "迷信" }, { "mi yao", "密钥" }, { "mi yi shang", "米以上" },
			{ "mi you", "密友" }, { "mi yu", "谜语" }, { "mi yue", "密钥" }, { "mi yue", "蜜月" }, { "mi yun", "密云" }, { "mi zhe", "眯着" }, { "mi zhu", "迷住" },
			{ "mi zong", "密宗" }, { "mi zui", "迷醉" }, { "mi zuo you", "米左右" }, { "mian", "丏" }, { "mian", "俛" }, { "mian", "偭" }, { "mian", "免" },
			{ "mian", "冕" }, { "mian", "勉" }, { "mian", "喕" }, { "mian", "娩" }, { "mian", "婂" }, { "mian", "媔" }, { "mian", "愐" }, { "mian", "棉" },
			{ "mian", "櫋" }, { "mian", "沔" }, { "mian", "渑" }, { "mian", "湎" }, { "mian", "眄" }, { "mian", "眠" }, { "mian", "矊" }, { "mian", "矏" },
			{ "mian", "綿" }, { "mian", "緜" }, { "mian", "緬" }, { "mian", "绵" }, { "mian", "缅" }, { "mian", "腼" }, { "mian", "葂" }, { "mian", "蝒" },
			{ "mian", "面" }, { "mian", "靦" }, { "mian", "鮸" }, { "mian", "麪" }, { "mian", "麵" }, { "mian", "麺" }, { "mian ao", "棉袄" }, { "mian ban", "面板" },
			{ "mian bao", "面包" }, { "mian bao che", "面包车" }, { "mian bei", "棉被" }, { "mian bi", "面壁" }, { "mian bu", "棉布" }, { "mian bu", "面部" },
			{ "mian bu liao", "免不了" }, { "mian chao", "面朝" }, { "mian chu", "免除" }, { "mian dai", "面带" }, { "mian dai wei xiao", "面带微笑" }, { "mian de", "免得" },
			{ "mian di", "面的" }, { "mian dian", "缅甸" }, { "mian dui", "面对" }, { "mian dui mian", "面对面" }, { "mian e", "面额" }, { "mian fei", "免费" },
			{ "mian fei ban", "免费版" }, { "mian fei dian ying", "免费电影" }, { "mian fei shi yong", "免费使用" }, { "mian fei song", "免费送" },
			{ "mian fei ti gong", "免费提供" }, { "mian fei xia zai", "免费下载" }, { "mian fei zeng song", "免费赠送" }, { "mian fei zhu ce", "免费注册" },
			{ "mian fen", "面粉" }, { "mian guan", "面馆" }, { "mian guang", "面广" }, { "mian hong er chi", "面红耳赤" }, { "mian hua", "棉花" },
			{ "mian hua tang", "棉花糖" }, { "mian huai", "缅怀" }, { "mian ji", "面积" }, { "mian jia", "面颊" }, { "mian ju", "面具" }, { "mian kong", "面孔" },
			{ "mian li", "勉励" }, { "mian liao", "面料" }, { "mian lin", "面临" }, { "mian lu", "面露" }, { "mian mao", "面貌" }, { "mian mian", "绵绵" },
			{ "mian mian", "面面" }, { "mian mo", "面膜" }, { "mian mu", "面目" }, { "mian mu quan fei", "面目全非" }, { "mian pang", "面庞" }, { "mian qian", "面前" },
			{ "mian qiang", "勉强" }, { "mian qu", "免去" }, { "mian rong", "面容" }, { "mian se", "面色" }, { "mian sha", "面纱" }, { "mian shang", "面上" },
			{ "mian shi", "免试" }, { "mian shi", "面世" }, { "mian shi", "面市" }, { "mian shi", "面试" }, { "mian shi", "面食" }, { "mian shi guan", "面试官" },
			{ "mian shi shi", "面试时" }, { "mian shou", "免受" }, { "mian shou", "免收" }, { "mian shou quan", "面授权" }, { "mian shu", "面熟" },
			{ "mian shuang", "面霜" }, { "mian shui", "免税" }, { "mian tan", "免谈" }, { "mian tan", "面瘫" }, { "mian tan", "面谈" }, { "mian tian", "腼腆" },
			{ "mian tiao", "面条" }, { "mian tuan", "面团" }, { "mian wu biao qing", "面无表情" }, { "mian xiang", "面向" }, { "mian xiang", "面相" },
			{ "mian xiang dui xiang", "面向对象" }, { "mian xiang quan guo", "面向全国" }, { "mian xiang she hui", "面向社会" }, { "mian yan", "绵延" },
			{ "mian yang", "绵羊" }, { "mian yang", "绵阳" }, { "mian yang shi", "绵阳市" }, { "mian yi", "免疫" }, { "mian yi", "棉衣" }, { "mian yi", "面议" },
			{ "mian yi gong neng", "免疫功能" }, { "mian yi li", "免疫力" }, { "mian yi xi tong", "免疫系统" }, { "mian yu", "免于" }, { "mian ze", "免责" },
			{ "mian ze sheng ming", "免责声明" }, { "mian zhao", "面罩" }, { "mian zheng", "免征" }, { "mian zhi", "免职" }, { "mian zhi", "面值" }, { "mian zhu", "绵竹" },
			{ "mian zi", "面子" }, { "miao", "喵" }, { "miao", "妙" }, { "miao", "媌" }, { "miao", "嫹" }, { "miao", "庙" }, { "miao", "廟" }, { "miao", "描" },
			{ "miao", "杪" }, { "miao", "淼" }, { "miao", "渺" }, { "miao", "眇" }, { "miao", "瞄" }, { "miao", "秒" }, { "miao", "竗" }, { "miao", "篎" },
			{ "miao", "緲" }, { "miao", "缈" }, { "miao", "缪" }, { "miao", "苗" }, { "miao", "藐" }, { "miao", "訬" }, { "miao", "邈" }, { "miao", "鱙" },
			{ "miao", "鹋" }, { "miao hou", "秒后" }, { "miao hui", "庙会" }, { "miao hui", "描绘" }, { "miao li", "庙里" }, { "miao mang", "渺茫" },
			{ "miao miao", "喵喵" }, { "miao miao", "苗苗" }, { "miao mu", "苗木" }, { "miao nei", "秒内" }, { "miao pu", "苗圃" }, { "miao sha", "秒杀" },
			{ "miao shi", "藐视" }, { "miao shu", "描述" }, { "miao tiao", "苗条" }, { "miao tou", "苗头" }, { "miao xiao", "渺小" }, { "miao xie", "描写" },
			{ "miao yong", "妙用" }, { "miao yu", "庙宇" }, { "miao zhong", "秒钟" }, { "miao zhun", "瞄准" }, { "miao zi", "苗子" }, { "miao zu", "苗族" },
			{ "mie", "乜" }, { "mie", "咩" }, { "mie", "幭" }, { "mie", "懱" }, { "mie", "搣" }, { "mie", "滅" }, { "mie", "灭" }, { "mie", "篾" }, { "mie", "蔑" },
			{ "mie", "薎" }, { "mie", "蠛" }, { "mie", "衊" }, { "mie", "鱴" }, { "mie diao", "灭掉" }, { "mie huo", "灭火" }, { "mie huo qi", "灭火器" },
			{ "mie jue", "灭绝" }, { "mie jun", "灭菌" }, { "mie le", "灭了" }, { "mie mie", "咩咩" }, { "mie shi", "蔑视" }, { "mie wang", "灭亡" }, { "min", "僶" },
			{ "min", "刡" }, { "min", "岷" }, { "min", "崏" }, { "min", "怋" }, { "min", "悯" }, { "min", "愍" }, { "min", "憫" }, { "min", "抿" }, { "min", "敃" },
			{ "min", "敏" }, { "min", "敯" }, { "min", "旻" }, { "min", "旼" }, { "min", "暋" }, { "min", "民" }, { "min", "泯" }, { "min", "湣" }, { "min", "潣" },
			{ "min", "玟" }, { "min", "珉" }, { "min", "琝" }, { "min", "痻" }, { "min", "皿" }, { "min", "笢" }, { "min", "簢" }, { "min", "緡" }, { "min", "缗" },
			{ "min", "罠" }, { "min", "苠" }, { "min", "蠠" }, { "min", "鈱" }, { "min", "錉" }, { "min", "閔" }, { "min", "閩" }, { "min", "闵" }, { "min", "闽" },
			{ "min", "鳘" }, { "min", "黽" }, { "min", "黾" }, { "min ban", "民办" }, { "min ban gao xiao", "民办高校" }, { "min ban jiao yu", "民办教育" },
			{ "min ban xue xiao", "民办学校" }, { "min bing", "民兵" }, { "min diao", "民调" }, { "min fa", "民法" }, { "min fang", "民房" }, { "min feng", "民风" },
			{ "min gan", "敏感" }, { "min gan du", "敏感度" }, { "min gan xing", "敏感性" }, { "min ge", "民歌" }, { "min gong", "民工" }, { "min guo", "民国" },
			{ "min hang", "民航" }, { "min hang", "闵行" }, { "min hang qu", "闵行区" }, { "min hang zong ju", "民航总局" }, { "min jian", "民间" },
			{ "min jian yi shu", "民间艺术" }, { "min jian zi ben", "民间资本" }, { "min jian zu zhi", "民间组织" }, { "min jiang", "岷江" }, { "min jie", "敏捷" },
			{ "min jin dang", "民进党" }, { "min jing", "民警" }, { "min ju", "民居" }, { "min meng", "民盟" }, { "min mie", "泯灭" }, { "min min", "敏敏" },
			{ "min nan", "闽南" }, { "min qi", "民企" }, { "min qing", "民情" }, { "min quan", "民权" }, { "min rui", "敏锐" }, { "min sheng", "民生" },
			{ "min sheng wen ti", "民生问题" }, { "min sheng yin hang", "民生银行" }, { "min shi", "民事" }, { "min shi su song", "民事诉讼" }, { "min shi ze ren", "民事责任" },
			{ "min su", "民俗" }, { "min su wen hua", "民俗文化" }, { "min tai", "闽台" }, { "min xin", "民心" }, { "min yao", "民谣" }, { "min yi", "民意" },
			{ "min yi diao cha", "民意调查" }, { "min ying", "民营" }, { "min ying jing ji", "民营经济" }, { "min ying qi ye", "民营企业" }, { "min yong", "民用" },
			{ "min yue", "民乐" }, { "min yun", "民运" }, { "min zhai", "民宅" }, { "min zheng", "民政" }, { "min zheng bu", "民政部" }, { "min zheng bu men", "民政部门" },
			{ "min zheng ju", "民政局" }, { "min zhong", "民众" }, { "min zhu", "民主" }, { "min zhu dang", "民主党" }, { "min zhu dang pai", "民主党派" },
			{ "min zhu guan li", "民主管理" }, { "min zhu hua", "民主化" }, { "min zhu jian du", "民主监督" }, { "min zhu zheng zhi", "民主政治" },
			{ "min zhu zhi du", "民主制度" }, { "min zu", "民族" }, { "min zu di qu", "民族地区" }, { "min zu jing shen", "民族精神" }, { "min zu pin pai", "民族品牌" },
			{ "min zu te se", "民族特色" }, { "min zu tuan jie", "民族团结" }, { "min zu wen hua", "民族文化" }, { "min zu ying xiong", "民族英雄" },
			{ "min zu zhu yi", "民族主义" }, { "ming", "冥" }, { "ming", "名" }, { "ming", "命" }, { "ming", "姳" }, { "ming", "嫇" }, { "ming", "慏" }, { "ming", "掵" },
			{ "ming", "明" }, { "ming", "暝" }, { "ming", "榠" }, { "ming", "洺" }, { "ming", "溟" }, { "ming", "眳" }, { "ming", "瞑" }, { "ming", "茗" },
			{ "ming", "蓂" }, { "ming", "螟" }, { "ming", "覭" }, { "ming", "詺" }, { "ming", "鄍" }, { "ming", "酩" }, { "ming", "銘" }, { "ming", "铭" },
			{ "ming", "鳴" }, { "ming", "鸣" }, { "ming an", "命案" }, { "ming an", "明暗" }, { "ming bai", "明白" }, { "ming bai zhe", "明摆着" }, { "ming cai", "名菜" },
			{ "ming ce", "名册" }, { "ming chao", "明朝" }, { "ming che", "名车" }, { "ming cheng", "名城" }, { "ming cheng", "名称" }, { "ming ci", "名次" },
			{ "ming ci", "名词" }, { "ming dai", "明代" }, { "ming dan", "名单" }, { "ming dao", "明道" }, { "ming de", "明德" }, { "ming deng", "明灯" },
			{ "ming e", "名额" }, { "ming er", "明儿" }, { "ming fen", "名分" }, { "ming fu qi shi", "名副其实" }, { "ming gui", "名贵" }, { "ming hao", "名号" },
			{ "ming hou tian", "明后天" }, { "ming ji", "名妓" }, { "ming ji", "明基" }, { "ming ji", "铭记" }, { "ming jia", "名家" }, { "ming jiang", "名将" },
			{ "ming jiao", "名叫" }, { "ming jiao", "明教" }, { "ming jiao", "鸣叫" }, { "ming jie", "冥界" }, { "ming jing", "明镜" }, { "ming ju", "名句" },
			{ "ming ku", "命苦" }, { "ming kuai", "明快" }, { "ming lang", "明朗" }, { "ming li", "名利" }, { "ming li", "命理" }, { "ming liang", "明亮" },
			{ "ming liao", "明了" }, { "ming lie", "名列" }, { "ming lie qian mao", "名列前茅" }, { "ming ling", "命令" }, { "ming ling hang", "命令行" },
			{ "ming liu", "名流" }, { "ming lu", "名录" }, { "ming ma biao jia", "明码标价" }, { "ming mai", "命脉" }, { "ming mei", "明媚" }, { "ming men", "名门" },
			{ "ming ming", "冥冥" }, { "ming ming", "命名" }, { "ming ming", "明明" }, { "ming ming bai bai", "明明白白" }, { "ming ming zhi dao", "明明知道" },
			{ "ming mo", "名模" }, { "ming mu", "名目" }, { "ming mu", "明目" }, { "ming mu zhang dan", "明目张胆" }, { "ming nian", "明年" }, { "ming pai", "名牌" },
			{ "ming pai", "铭牌" }, { "ming pai chan pin", "名牌产品" }, { "ming pai da xue", "名牌大学" }, { "ming pian", "名片" }, { "ming pin", "名品" },
			{ "ming qi", "名企" }, { "ming qi", "名气" }, { "ming qing", "明清" }, { "ming qu", "名曲" }, { "ming que", "明确" }, { "ming que gui ding", "明确规定" },
			{ "ming que ti chu", "明确提出" }, { "ming ren", "名人" }, { "ming ren", "鸣人" }, { "ming ri", "明日" }, { "ming rui", "明锐" }, { "ming shan", "名山" },
			{ "ming sheng", "名声" }, { "ming sheng", "名胜" }, { "ming sheng gu ji", "名胜古迹" }, { "ming shi", "名士" }, { "ming shi", "名师" }, { "ming shi", "明示" },
			{ "ming shuo", "明说" }, { "ming tang", "名堂" }, { "ming ti", "命题" }, { "ming tian", "明天" }, { "ming tou", "名头" }, { "ming wan", "明晚" },
			{ "ming wang", "冥王" }, { "ming wang xing", "冥王星" }, { "ming wei", "名为" }, { "ming wen", "明文" }, { "ming wen gui ding", "明文规定" },
			{ "ming xi", "明晰" }, { "ming xi", "明细" }, { "ming xi biao", "明细表" }, { "ming xia", "名下" }, { "ming xian", "明显" }, { "ming xiang", "冥想" },
			{ "ming xiao", "名校" }, { "ming xin pian", "明信片" }, { "ming xing", "明星" }, { "ming xue sheng", "名学生" }, { "ming yan", "名言" },
			{ "ming yan ren", "明眼人" }, { "ming yi", "名义" }, { "ming yi", "名医" }, { "ming you", "名优" }, { "ming yu", "名誉" }, { "ming yu quan", "名誉权" },
			{ "ming yue", "名曰" }, { "ming yue", "明月" }, { "ming yue zhao", "明月照" }, { "ming yun", "命运" }, { "ming zao", "明早" }, { "ming zhao", "明朝" },
			{ "ming zheng yan shun", "名正言顺" }, { "ming zhi", "明智" }, { "ming zhi", "明治" }, { "ming zhi", "明知" }, { "ming zhi dao", "明知道" },
			{ "ming zhong", "命中" }, { "ming zhong lv", "命中率" }, { "ming zhong zhu ding", "命中注定" }, { "ming zhu", "名著" }, { "ming zhu", "明珠" },
			{ "ming zhuang", "名状" }, { "ming zi", "名字" }, { "ming zi jiao", "名字叫" }, { "ming zui", "名嘴" }, { "ming zuo", "名作" }, { "miu", "繆" },
			{ "miu", "缪" }, { "miu", "謬" }, { "miu", "谬" }, { "miu lun", "谬论" }, { "miu wu", "谬误" }, { "mo", "万" }, { "mo", "么" }, { "mo", "冒" },
			{ "mo", "劘" }, { "mo", "嗼" }, { "mo", "嘿" }, { "mo", "塻" }, { "mo", "墨" }, { "mo", "妺" }, { "mo", "嫫" }, { "mo", "嬷" }, { "mo", "寞" },
			{ "mo", "抹" }, { "mo", "摩" }, { "mo", "摸" }, { "mo", "摹" }, { "mo", "攠" }, { "mo", "暯" }, { "mo", "末" }, { "mo", "枺" }, { "mo", "模" },
			{ "mo", "歿" }, { "mo", "殁" }, { "mo", "没" }, { "mo", "沫" }, { "mo", "漠" }, { "mo", "瀎" }, { "mo", "爅" }, { "mo", "狢" }, { "mo", "瘼" },
			{ "mo", "眽" }, { "mo", "瞙" }, { "mo", "磨" }, { "mo", "秣" }, { "mo", "粖" }, { "mo", "糢" }, { "mo", "絈" }, { "mo", "絔" }, { "mo", "纆" },
			{ "mo", "耱" }, { "mo", "脉" }, { "mo", "膜" }, { "mo", "茉" }, { "mo", "莈" }, { "mo", "莫" }, { "mo", "蓦" }, { "mo", "藦" }, { "mo", "蘑" },
			{ "mo", "蛨" }, { "mo", "蟔" }, { "mo", "袹" }, { "mo", "謨" }, { "mo", "谟" }, { "mo", "貊" }, { "mo", "貘" }, { "mo", "銆" }, { "mo", "鏌" },
			{ "mo", "镆" }, { "mo", "陌" }, { "mo", "靺" }, { "mo", "饃" }, { "mo", "馍" }, { "mo", "驀" }, { "mo", "髍" }, { "mo", "魔" }, { "mo", "麽" },
			{ "mo", "麿" }, { "mo", "默" }, { "mo", "黙" }, { "mo ai", "默哀" }, { "mo bai", "膜拜" }, { "mo ban", "模板" }, { "mo ban", "模版" },
			{ "mo ban che", "末班车" }, { "mo bu", "莫不" }, { "mo ca", "摩擦" }, { "mo ca", "磨擦" }, { "mo ceng", "磨蹭" }, { "mo chu", "摸出" }, { "mo da", "莫大" },
			{ "mo dao", "摸到" }, { "mo deng", "摩登" }, { "mo di", "摸底" }, { "mo duan", "末端" }, { "mo duo ke", "默多克" }, { "mo er", "摩尔" }, { "mo er ben", "墨尔本" },
			{ "mo fa", "魔法" }, { "mo fa shi", "魔法师" }, { "mo fan", "模范" }, { "mo fang", "模仿" }, { "mo fang", "魔方" }, { "mo fei", "莫非" }, { "mo gen", "摩根" },
			{ "mo gen da tong", "摩根大通" }, { "mo gu", "蘑菇" }, { "mo gui", "魔鬼" }, { "mo guo", "摸过" }, { "mo guo yu", "莫过于" }, { "mo he", "墨盒" },
			{ "mo he", "磨合" }, { "mo he qi", "磨合期" }, { "mo hei", "抹黑" }, { "mo hu", "模糊" } };
};
