package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN12 {
	public static String[][] pl = { { "dun", "不" }, { "dun", "伅" }, { "dun", "吨" }, { "dun", "噸" }, { "dun", "囤" }, { "dun", "墩" }, { "dun", "壿" },
			{ "dun", "惇" }, { "dun", "撉" }, { "dun", "敦" }, { "dun", "楯" }, { "dun", "沌" }, { "dun", "潡" }, { "dun", "炖" }, { "dun", "燉" }, { "dun", "盹" },
			{ "dun", "盾" }, { "dun", "砘" }, { "dun", "礅" }, { "dun", "趸" }, { "dun", "蹲" }, { "dun", "躉" }, { "dun", "遁" }, { "dun", "遯" }, { "dun", "鈍" },
			{ "dun", "鐓" }, { "dun", "钝" }, { "dun", "镦" }, { "dun", "頓" }, { "dun", "顿" }, { "dun", "驐" }, { "dun cu", "敦促" }, { "dun dian", "蹲点" },
			{ "dun fan", "顿饭" }, { "dun huang", "敦煌" }, { "dun le", "顿了" }, { "dun pai", "盾牌" }, { "dun shi", "顿时" }, { "dun wei", "吨位" }, { "dun wu", "顿悟" },
			{ "dun xia", "蹲下" }, { "dun zai", "蹲在" }, { "dun zhe", "蹲着" }, { "duo", "剁" }, { "duo", "剟" }, { "duo", "剫" }, { "duo", "咄" }, { "duo", "哆" },
			{ "duo", "哚" }, { "duo", "嚲" }, { "duo", "垛" }, { "duo", "埵" }, { "duo", "堕" }, { "duo", "墮" }, { "duo", "墯" }, { "duo", "多" }, { "duo", "夺" },
			{ "duo", "奪" }, { "duo", "奲" }, { "duo", "嶞" }, { "duo", "度" }, { "duo", "惰" }, { "duo", "掇" }, { "duo", "敓" }, { "duo", "敪" }, { "duo", "朵" },
			{ "duo", "朶" }, { "duo", "杕" }, { "duo", "柁" }, { "duo", "柮" }, { "duo", "椯" }, { "duo", "毲" }, { "duo", "沲" }, { "duo", "痑" }, { "duo", "綞" },
			{ "duo", "舵" }, { "duo", "裰" }, { "duo", "趓" }, { "duo", "跢" }, { "duo", "跺" }, { "duo", "踱" }, { "duo", "躱" }, { "duo", "躲" }, { "duo", "鈬" },
			{ "duo", "錞" }, { "duo", "鐸" }, { "duo", "铎" }, { "duo", "陊" }, { "duo", "驮" }, { "duo", "鬌" }, { "duo", "鮵" }, { "duo", "鵽" }, { "duo a", "多啊" },
			{ "duo ba", "多吧" }, { "duo ban", "多半" }, { "duo bao", "多宝" }, { "duo bi", "躲避" }, { "duo bian", "多变" }, { "duo bian", "多边" },
			{ "duo bian xing", "多边形" }, { "duo bu", "多部" }, { "duo bu duo", "多不多" }, { "duo cai", "多彩" }, { "duo cai duo yi", "多才多艺" }, { "duo cang", "躲藏" },
			{ "duo ceng", "多层" }, { "duo ceng ci", "多层次" }, { "duo chang", "多长" }, { "duo chang shi jian", "多长时间" }, { "duo chi", "多吃" },
			{ "duo chong", "多重" }, { "duo chou shan gan", "多愁善感" }, { "duo chu", "多出" }, { "duo chu", "多处" }, { "duo ci", "多次" }, { "duo da", "多大" },
			{ "duo da", "多打" }, { "duo da", "多达" }, { "duo dai", "多带" }, { "duo dao", "躲到" }, { "duo de", "多得" }, { "duo de", "多的" }, { "duo de", "夺得" },
			{ "duo de duo", "多得多" }, { "duo de shi", "多得是" }, { "duo dian", "多点" }, { "duo duo", "多多" }, { "duo duo", "朵朵" }, { "duo duo bi ren", "咄咄逼人" },
			{ "duo duo shao shao", "多多少少" }, { "duo duo yi shan", "多多益善" }, { "duo er", "多尔" }, { "duo er gun", "多尔衮" }, { "duo fa", "多发" },
			{ "duo fang", "多方" }, { "duo fang mian", "多方面" }, { "duo fen", "多分" }, { "duo gao", "多高" }, { "duo ge", "多个" }, { "duo gei", "多给" },
			{ "duo gong neng", "多功能" }, { "duo guan", "夺冠" }, { "duo guo", "多国" }, { "duo guo", "躲过" }, { "duo ha", "多哈" }, { "duo hao", "多好" },
			{ "duo he", "多喝" }, { "duo he shui", "多喝水" }, { "duo hu", "多户" }, { "duo hua", "多花" }, { "duo hui", "夺回" }, { "duo ji", "多级" },
			{ "duo jia", "多加" }, { "duo jia", "多家" }, { "duo jian", "多件" }, { "duo jian", "多见" }, { "duo jiao", "多交" }, { "duo jiao", "跺脚" },
			{ "duo jiao du", "多角度" }, { "duo jin", "夺金" }, { "duo jin", "躲进" }, { "duo jing gui", "多晶硅" }, { "duo jiu", "多久" }, { "duo kai", "躲开" },
			{ "duo kan", "多看" }, { "duo kong", "多孔" }, { "duo kong", "多空" }, { "duo kuai", "多块" }, { "duo kuan", "多款" }, { "duo kui", "多亏" },
			{ "duo la", "哆啦" }, { "duo la", "多拉" }, { "duo lai", "多来" }, { "duo le", "多了" }, { "duo lei", "多累" }, { "duo liao", "多了" }, { "duo lu", "多路" },
			{ "duo lun duo", "多伦多" }, { "duo luo", "堕落" }, { "duo lv", "多虑" }, { "duo ma", "多玛" }, { "duo mai", "多买" }, { "duo me", "多么" },
			{ "duo mei", "多美" }, { "duo mei ti", "多媒体" }, { "duo mi", "多米" }, { "duo ming", "多名" }, { "duo mu", "夺目" }, { "duo nan", "多难" },
			{ "duo nian", "多年" }, { "duo nian lai", "多年来" }, { "duo nian qian", "多年前" }, { "duo nian yi hou", "多年以后" }, { "duo pian", "多篇" },
			{ "duo pu da", "多普达" }, { "duo pu le", "多普勒" }, { "duo qi", "多起" }, { "duo qian", "多钱" }, { "duo qing", "多情" }, { "duo qu", "多去" },
			{ "duo qu", "夺去" }, { "duo qu", "夺取" }, { "duo qu dao", "多渠道" }, { "duo ren", "多人" }, { "duo ri", "多日" }, { "duo ru", "堕入" }, { "duo sha", "多杀" },
			{ "duo shan", "躲闪" }, { "duo shao", "多少" }, { "duo shao ci", "多少次" }, { "duo shao fen", "多少分" }, { "duo shao ji", "多少级" },
			{ "duo shao qian", "多少钱" }, { "duo shao ren", "多少人" }, { "duo shao shi jian", "多少时间" }, { "duo shao tian", "多少天" }, { "duo shi", "多事" },
			{ "duo shi", "多时" }, { "duo shi", "多是" }, { "duo shi", "多食" }, { "duo shou", "多收" }, { "duo shou", "舵手" }, { "duo shu", "多数" },
			{ "duo shu ren", "多数人" }, { "duo shui", "多睡" }, { "duo shuo", "多说" }, { "duo sui", "多岁" }, { "duo suo", "哆嗦" }, { "duo tai", "堕胎" },
			{ "duo tai", "多台" }, { "duo tang", "多糖" }, { "duo tao", "多套" }, { "duo ti", "多提" }, { "duo tian", "多天" }, { "duo tiao", "多条" },
			{ "duo ting", "多听" }, { "duo tou", "多头" }, { "duo wan", "多万" }, { "duo wan", "多玩" }, { "duo wei", "多为" }, { "duo wei", "多位" }, { "duo wei", "多维" },
			{ "duo wen", "多问" }, { "duo xian cheng", "多线程" }, { "duo xiang", "多想" }, { "duo xiang", "多项" }, { "duo xiao shi", "多小时" }, { "duo xie", "多些" },
			{ "duo xie", "多写" }, { "duo xie", "多谢" }, { "duo xin", "多心" }, { "duo xing", "惰性" }, { "duo xuan", "多选" }, { "duo xue ke", "多学科" },
			{ "duo yang", "多样" }, { "duo yang hua", "多样化" }, { "duo yang xing", "多样性" }, { "duo ye", "多页" }, { "duo yi", "多亿" }, { "duo yi", "多以" },
			{ "duo yi", "多疑" }, { "duo yi dian", "多一点" }, { "duo yong", "多用" }, { "duo yong hu", "多用户" }, { "duo yong tu", "多用途" }, { "duo you", "多有" },
			{ "duo yu", "多于" }, { "duo yu", "多余" }, { "duo yuan", "多元" }, { "duo yuan", "多远" }, { "duo yuan hua", "多元化" }, { "duo yue", "多月" },
			{ "duo yun", "多云" }, { "duo zai", "躲在" }, { "duo ze", "多则" }, { "duo zhang", "多张" }, { "duo zhe", "躲着" }, { "duo zhi", "多只" },
			{ "duo zhong", "多种" }, { "duo zhong", "多重" }, { "duo zhong", "多钟" }, { "duo zhong duo yang", "多种多样" }, { "duo zhong fang shi", "多种方式" },
			{ "duo zhong xing shi", "多种形式" }, { "duo zhuan", "多赚" }, { "duo zi", "多姿" }, { "duo zi duo cai", "多姿多彩" }, { "duo zou", "夺走" },
			{ "duo zui", "多嘴" }, { "duo zuo", "多做" }, { "e", "丨" }, { "e", "俄" }, { "e", "匎" }, { "e", "厄" }, { "e", "呃" }, { "e", "咢" }, { "e", "哦" },
			{ "e", "噁" }, { "e", "噩" }, { "e", "囮" }, { "e", "垩" }, { "e", "堊" }, { "e", "堮" }, { "e", "娥" }, { "e", "娾" }, { "e", "婀" }, { "e", "屙" },
			{ "e", "峉" }, { "e", "峨" }, { "e", "峩" }, { "e", "崿" }, { "e", "廅" }, { "e", "恶" }, { "e", "悪" }, { "e", "惡" }, { "e", "愕" }, { "e", "扼" },
			{ "e", "搹" }, { "e", "枙" }, { "e", "櫮" }, { "e", "欸" }, { "e", "歞" }, { "e", "涐" }, { "e", "珴" }, { "e", "皒" }, { "e", "睋" }, { "e", "砐" },
			{ "e", "砨" }, { "e", "砵" }, { "e", "腭" }, { "e", "苊" }, { "e", "莪" }, { "e", "萼" }, { "e", "蕚" }, { "e", "蚅" }, { "e", "蛾" }, { "e", "蝁" },
			{ "e", "訛" }, { "e", "諤" }, { "e", "譌" }, { "e", "讹" }, { "e", "诶" }, { "e", "谔" }, { "e", "豟" }, { "e", "軛" }, { "e", "軶" }, { "e", "轭" },
			{ "e", "迗" }, { "e", "遏" }, { "e", "遻" }, { "e", "鄂" }, { "e", "鍔" }, { "e", "鑩" }, { "e", "锇" }, { "e", "锷" }, { "e", "阨" }, { "e", "阿" },
			{ "e", "頞" }, { "e", "額" }, { "e", "顎" }, { "e", "颚" }, { "e", "额" }, { "e", "餓" }, { "e", "餩" }, { "e", "饿" }, { "e", "鰐" }, { "e", "鱷" },
			{ "e", "鳄" }, { "e", "鵈" }, { "e", "鵝" }, { "e", "鵞" }, { "e", "鶚" }, { "e", "鹅" }, { "e", "鹗" }, { "e", "齶" }, { "e ba", "恶霸" },
			{ "e bao", "恶报" }, { "e bu", "恶补" }, { "e chou", "恶臭" }, { "e de", "饿得" }, { "e ding", "额定" }, { "e du", "恶毒" }, { "e du", "额度" }, { "e e", "哦哦" },
			{ "e er duo si", "鄂尔多斯" }, { "e fang", "俄方" }, { "e gao", "恶搞" }, { "e gua duo er", "厄瓜多尔" }, { "e guo", "俄国" }, { "e guo", "恶果" },
			{ "e hao", "噩耗" }, { "e hen hen", "恶狠狠" }, { "e hua", "恶化" }, { "e jun", "俄军" }, { "e lang", "恶狼" }, { "e lie", "恶劣" }, { "e ling", "恶灵" },
			{ "e luo si", "俄罗斯" }, { "e luo si ren", "俄罗斯人" }, { "e mei", "峨嵋" }, { "e mei shan", "峨眉山" }, { "e meng", "噩梦" }, { "e meng", "恶梦" },
			{ "e mi tuo fo", "阿弥陀佛" }, { "e mo", "恶魔" }, { "e nuo", "婀娜" }, { "e ran", "愕然" }, { "e ren", "恶人" }, { "e sha", "扼杀" }, { "e shi li", "恶势力" },
			{ "e si", "饿死" }, { "e su", "恶俗" }, { "e tou", "额头" }, { "e wai", "额外" }, { "e wen", "俄文" }, { "e xi", "恶习" }, { "e xin", "恶心" },
			{ "e xing", "恶性" }, { "e xing", "恶行" }, { "e xing jing zheng", "恶性竞争" }, { "e xing xun huan", "恶性循环" }, { "e xing zhong liu", "恶性肿瘤" },
			{ "e yi", "恶意" }, { "e yi ruan jian", "恶意软件" }, { "e yu", "俄语" }, { "e yu", "鳄鱼" }, { "e yun", "厄运" }, { "e zhe", "饿着" }, { "e zhi", "遏制" },
			{ "e zhi", "遏止" }, { "e zuo ju", "恶作剧" }, { "ei", "诶" }, { "en", "唔" }, { "en", "嗯" }, { "en", "奀" }, { "en", "峎" }, { "en", "恩" }, { "en", "摁" },
			{ "en", "蒽" }, { "en a", "嗯啊" }, { "en ai", "恩爱" }, { "en chou", "恩仇" }, { "en ci", "恩赐" }, { "en dian", "恩典" }, { "en en", "嗯嗯" },
			{ "en en", "恩恩" }, { "en ge si", "恩格斯" }, { "en hui", "恩惠" }, { "en na", "恩纳" }, { "en qing", "恩情" }, { "en ren", "恩人" }, { "en shi", "恩师" },
			{ "en shi", "恩施" }, { "en yuan", "恩怨" }, { "eng", "鞥" }, { "er", "二" }, { "er", "佴" }, { "er", "侕" }, { "er", "儿" }, { "er", "兒" }, { "er", "刵" },
			{ "er", "咡" }, { "er", "尔" }, { "er", "峏" }, { "er", "弍" }, { "er", "弐" }, { "er", "栭" }, { "er", "栮" }, { "er", "毦" }, { "er", "洏" },
			{ "er", "洱" }, { "er", "爾" }, { "er", "珥" }, { "er", "粫" }, { "er", "而" }, { "er", "耳" }, { "er", "胹" }, { "er", "荋" }, { "er", "薾" },
			{ "er", "衈" }, { "er", "貮" }, { "er", "貳" }, { "er", "贰" }, { "er", "輀" }, { "er", "轜" }, { "er", "迩" }, { "er", "邇" }, { "er", "鉺" },
			{ "er", "铒" }, { "er", "陑" }, { "er", "餌" }, { "er", "饵" }, { "er", "駬" }, { "er", "鮞" }, { "er", "鲕" }, { "er", "鴯" }, { "er", "鸸" },
			{ "er ba", "二八" }, { "er ba", "而把" }, { "er bai", "二百" }, { "er bai wu", "二百五" }, { "er ban", "二班" }, { "er bei", "而被" }, { "er ben", "二本" },
			{ "er bian", "耳边" }, { "er bu", "二部" }, { "er bu", "而不" }, { "er bu shi", "而不是" }, { "er ceng", "二层" }, { "er cheng", "而成" }, { "er chu", "而出" },
			{ "er ci", "二次" }, { "er ci kai fa", "二次开发" }, { "er cong", "而从" }, { "er dai", "二代" }, { "er dang", "而当" }, { "er de", "尔德" },
			{ "er deng", "二等" }, { "er deng jiang", "二等奖" }, { "er di", "尔迪" }, { "er ding", "而定" }, { "er ding", "耳钉" }, { "er dong", "而动" },
			{ "er du", "二度" }, { "er dui", "二队" }, { "er dui", "而对" }, { "er duo", "耳朵" }, { "er duo li", "耳朵里" }, { "er fei", "而非" }, { "er fen", "二分" },
			{ "er fen zhi yi", "二分之一" }, { "er ge", "二个" }, { "er ge", "二哥" }, { "er ge", "儿歌" }, { "er ge yue", "二个月" }, { "er guang", "耳光" },
			{ "er gui", "而归" }, { "er guo", "而过" }, { "er guo tou", "二锅头" }, { "er hao", "二号" }, { "er hou", "而后" }, { "er hu", "二胡" },
			{ "er hua bu shuo", "二话不说" }, { "er huan", "二环" }, { "er huan", "耳环" }, { "er ji", "二级" }, { "er ji", "耳机" }, { "er ji du", "二季度" },
			{ "er ji guan", "二极管" }, { "er ji huan cun", "二级缓存" }, { "er ji shi chang", "二级市场" }, { "er ji yu ming", "二级域名" }, { "er jian", "而建" },
			{ "er jie", "二姐" }, { "er jin", "而今" }, { "er jin zhi", "二进制" }, { "er ke", "儿科" }, { "er lai", "二来" }, { "er lai", "而来" }, { "er lao", "二老" },
			{ "er lei", "二类" }, { "er li", "而立" }, { "er liang", "二两" }, { "er ling ling", "二零零" }, { "er liu", "二流" }, { "er long", "耳聋" },
			{ "er lou", "二楼" }, { "er lu", "二路" }, { "er lun", "而论" }, { "er mai", "耳麦" }, { "er ming", "耳鸣" }, { "er mu", "耳目" }, { "er mu yi xin", "耳目一新" },
			{ "er nai", "二奶" }, { "er ni", "而你" }, { "er nian", "二年" }, { "er nian ji", "二年级" }, { "er nv", "儿女" }, { "er pan", "耳畔" }, { "er qi", "二期" },
			{ "er qi", "而其" }, { "er qi", "而起" }, { "er qi gong cheng", "二期工程" }, { "er qian", "二千" }, { "er qie", "而且" }, { "er qu", "二区" },
			{ "er qu", "而去" }, { "er ren", "二人" }, { "er ren zhuan", "二人转" }, { "er ri", "二日" }, { "er ru", "而入" }, { "er sai", "耳塞" }, { "er san", "二三" },
			{ "er sen", "尔森" }, { "er shang", "而上" }, { "er shen", "二审" }, { "er sheng", "而生" }, { "er shi", "二世" }, { "er shi", "二十" }, { "er shi", "二是" },
			{ "er shi", "儿时" }, { "er shi", "而使" }, { "er shi", "而是" }, { "er shi ba", "二十八" }, { "er shi duo", "二十多" }, { "er shi er", "二十二" },
			{ "er shi ji", "二十几" }, { "er shi jiu", "二十九" }, { "er shi liu", "二十六" }, { "er shi qi", "二十七" }, { "er shi san", "二十三" },
			{ "er shi shi ji", "二十世纪" }, { "er shi si", "二十四" }, { "er shi sui", "二十岁" }, { "er shi wan", "二十万" }, { "er shi wu", "二十五" },
			{ "er shi yi", "二十一" }, { "er shou", "二手" }, { "er shou che", "二手车" }, { "er shou fang", "二手房" }, { "er shu", "二叔" }, { "er shu", "耳熟" },
			{ "er shu neng xiang", "耳熟能详" }, { "er si", "尔斯" }, { "er si", "而死" }, { "er sun", "儿孙" }, { "er ta", "而他" }, { "er ta", "而她" },
			{ "er tian", "二天" }, { "er tong", "儿童" }, { "er tong jie", "儿童节" }, { "er tong yi yuan", "儿童医院" }, { "er tui", "而退" }, { "er wai", "而外" },
			{ "er wang", "而亡" }, { "er wei", "二位" }, { "er wei", "二维" }, { "er wei", "而为" }, { "er wei", "而未" }, { "er wei ma", "二维码" }, { "er wen", "耳闻" },
			{ "er wo", "而我" }, { "er wu", "而无" }, { "er xi", "儿媳" }, { "er xi", "儿戏" }, { "er xi fu", "儿媳妇" }, { "er xia", "而下" }, { "er xian", "二线" },
			{ "er xing", "而行" }, { "er yan", "而言" }, { "er yang hua liu", "二氧化硫" }, { "er yang hua tan", "二氧化碳" }, { "er yao", "二要" }, { "er yao", "而要" },
			{ "er ye", "二爷" }, { "er yi", "而以" }, { "er yi", "而已" }, { "er yi", "而异" }, { "er ying", "而应" }, { "er you", "而又" }, { "er you", "而有" },
			{ "er yu", "耳语" }, { "er yuan", "二元" }, { "er yuan", "二院" }, { "er yue", "二月" }, { "er zai", "而在" }, { "er zhan", "二战" }, { "er zhan", "而战" },
			{ "er zhe", "二者" }, { "er zhe", "而这" }, { "er zhi", "而至" }, { "er zhi", "而致" }, { "er zhong", "二中" }, { "er zhong", "二种" }, { "er zi", "二字" },
			{ "er zi", "儿子" }, { "er zuo", "而作" }, { "er zuo", "而坐" }, { "fa", "乏" }, { "fa", "伐" }, { "fa", "发" }, { "fa", "垡" }, { "fa", "沷" },
			{ "fa", "法" }, { "fa", "珐" }, { "fa", "琺" }, { "fa", "疺" }, { "fa", "発" }, { "fa", "發" }, { "fa", "瞂" }, { "fa", "砝" }, { "fa", "筏" },
			{ "fa", "罚" }, { "fa", "罰" }, { "fa", "罸" }, { "fa", "藅" }, { "fa", "醗" }, { "fa", "閥" }, { "fa", "阀" }, { "fa", "髪" }, { "fa", "髮" },
			{ "fa an", "法案" }, { "fa bai", "发白" }, { "fa bao", "发包" }, { "fa bao", "法宝" }, { "fa biao", "发表" }, { "fa biao", "发飙" },
			{ "fa biao lun wen", "发表论文" }, { "fa biao ping lun", "发表评论" }, { "fa biao sheng ming", "发表声明" }, { "fa biao wen zhang", "发表文章" },
			{ "fa biao yan lun", "发表言论" }, { "fa biao yi jian", "发表意见" }, { "fa biao zhe", "发表者" }, { "fa bing", "发病" }, { "fa bing lv", "发病率" },
			{ "fa bu", "发布" }, { "fa bu chu", "发不出" }, { "fa bu gong gao", "发布公告" }, { "fa bu guang gao", "发布广告" }, { "fa bu hui", "发布会" },
			{ "fa bu ri qi", "发布日期" }, { "fa bu shi jian", "发布时间" }, { "fa bu xi tong", "发布系统" }, { "fa bu xin xi", "发布信息" }, { "fa bu zhe", "发布者" },
			{ "fa cai", "发财" }, { "fa cao an", "法草案" }, { "fa che", "发车" }, { "fa chou", "发愁" }, { "fa chu", "发出" }, { "fa chu tong zhi", "发出通知" },
			{ "fa chun", "发春" }, { "fa cuo", "发错" }, { "fa da", "发达" }, { "fa da cai", "发大财" }, { "fa da di qu", "发达地区" }, { "fa da guo jia", "发达国家" },
			{ "fa dai", "发呆" }, { "fa dan", "罚单" }, { "fa dao", "发到" }, { "fa dian", "发点" }, { "fa dian", "发电" }, { "fa dian", "法典" },
			{ "fa dian chang", "发电厂" }, { "fa dian ji", "发电机" }, { "fa dian ji zu", "发电机组" }, { "fa dian liang", "发电量" }, { "fa ding", "法定" },
			{ "fa ding cheng xu", "法定程序" }, { "fa dong", "发动" }, { "fa dong ji", "发动机" }, { "fa dou", "发抖" }, { "fa duan xin", "发短信" }, { "fa fa", "发发" },
			{ "fa fang", "发放" }, { "fa fen", "发奋" }, { "fa feng", "发疯" }, { "fa fu", "发福" }, { "fa gai wei", "发改委" }, { "fa gao", "发稿" }, { "fa ge", "发个" },
			{ "fa ge", "发哥" }, { "fa gei", "发给" }, { "fa gei ni", "发给你" }, { "fa gong zi", "发工资" }, { "fa guan", "法官" }, { "fa guang", "发光" },
			{ "fa guang gao", "发广告" }, { "fa gui", "法规" }, { "fa guo", "发过" }, { "fa guo", "法国" }, { "fa guo ba li", "法国巴黎" }, { "fa guo dui", "法国队" },
			{ "fa guo ren", "法国人" }, { "fa guo zong tong", "法国总统" }, { "fa hei", "发黑" }, { "fa hong", "发红" }, { "fa hua", "发话" }, { "fa huang", "发黄" },
			{ "fa hui", "发回" }, { "fa hui", "发挥" }, { "fa hui zuo yong", "发挥作用" }, { "fa huo", "发火" }, { "fa huo", "发货" }, { "fa jia", "发夹" },
			{ "fa jia", "发家" }, { "fa jiao", "发酵" }, { "fa jin", "罚金" }, { "fa jue", "发掘" }, { "fa jue", "发觉" }, { "fa ka", "发卡" }, { "fa kan", "发刊" },
			{ "fa kuan", "罚款" }, { "fa kuang", "发狂" }, { "fa la", "法拉" }, { "fa la li", "法拉利" }, { "fa lai", "发来" }, { "fa lan", "法兰" },
			{ "fa lan ke fu", "法兰克福" }, { "fa lan xi", "法兰西" }, { "fa lang", "发廊" }, { "fa lao", "法老" }, { "fa lao sao", "发牢骚" }, { "fa li", "乏力" },
			{ "fa li", "发力" }, { "fa li", "法力" }, { "fa li", "法理" }, { "fa liang", "发亮" }, { "fa ling", "法令" }, { "fa lun gong", "法轮功" }, { "fa lv", "法律" },
			{ "fa lv bao hu", "法律保护" }, { "fa lv cheng xu", "法律程序" }, { "fa lv fa gui", "法律法规" }, { "fa lv fu wu", "法律服务" }, { "fa lv gu wen", "法律顾问" },
			{ "fa lv guan xi", "法律关系" }, { "fa lv gui ding", "法律规定" }, { "fa lv gui fan", "法律规范" }, { "fa lv ti xi", "法律体系" }, { "fa lv wen shu", "法律文书" },
			{ "fa lv wen ti", "法律问题" }, { "fa lv xiao li", "法律效力" }, { "fa lv yi ju", "法律依据" }, { "fa lv yi shi", "法律意识" }, { "fa lv yuan zhu", "法律援助" },
			{ "fa lv ze ren", "法律责任" }, { "fa lv zhi du", "法律制度" }, { "fa lv zhi shi", "法律知识" }, { "fa lv zi xun", "法律咨询" }, { "fa ma", "发麻" },
			{ "fa ma", "砝码" }, { "fa mao", "发毛" }, { "fa mei", "发霉" }, { "fa men", "法门" }, { "fa men", "阀门" }, { "fa ming", "发明" },
			{ "fa ming chuang zao", "发明创造" }, { "fa ming zhuan li", "发明专利" }, { "fa mu", "伐木" }, { "fa nan", "发难" }, { "fa nu", "发怒" }, { "fa pang", "发胖" },
			{ "fa pao", "发泡" }, { "fa pei", "发配" }, { "fa pi qi", "发脾气" }, { "fa pian", "发片" }, { "fa piao", "发票" }, { "fa qi", "发起" }, { "fa qi ren", "发起人" },
			{ "fa qian", "发钱" }, { "fa qing", "发情" }, { "fa qiu", "发球" }, { "fa qiu", "罚球" }, { "fa re", "发热" }, { "fa re liang", "发热量" }, { "fa ren", "法人" },
			{ "fa ren dai biao", "法人代表" }, { "fa ren gu", "法人股" }, { "fa ren zi ge", "法人资格" }, { "fa ruan", "发软" }, { "fa san", "发散" }, { "fa sao", "发骚" },
			{ "fa shang", "发上" }, { "fa shao", "发烧" }, { "fa shao you", "发烧友" }, { "fa she", "发射" }, { "fa she qi", "发射器" }, { "fa sheng", "发声" },
			{ "fa sheng", "发生" }, { "fa sheng bao zha", "发生爆炸" }, { "fa sheng bian hua", "发生变化" }, { "fa sheng chong tu", "发生冲突" },
			{ "fa sheng guan xi", "发生关系" }, { "fa sheng huo zai", "发生火灾" }, { "fa sheng lv", "发生率" }, { "fa sheng qi", "发生器" }, { "fa sheng shen me", "发生什么" },
			{ "fa sheng shi gu", "发生事故" }, { "fa sheng yi wai", "发生意外" }, { "fa sheng zhong da", "发生重大" }, { "fa shi", "发誓" }, { "fa shi", "法师" },
			{ "fa shi", "法式" }, { "fa shou", "发售" }, { "fa shu", "法术" }, { "fa si", "发丝" }, { "fa song", "发送" }, { "fa song duan xin", "发送短信" },
			{ "fa song gei", "发送给" }, { "fa song you jian", "发送邮件" }, { "fa song zhe", "发送者" }, { "fa tang", "发烫" }, { "fa tiao", "发条" }, { "fa tiao", "法条" },
			{ "fa tie", "发帖" }, { "fa tie", "发贴" }, { "fa tie zi", "发帖子" }, { "fa ting", "法庭" }, { "fa wang", "发往" }, { "fa wang", "法王" }, { "fa wang", "法网" },
			{ "fa wei", "乏味" }, { "fa wei", "发威" }, { "fa wen", "发文" }, { "fa wen", "发问" }, { "fa wen", "法文" }, { "fa wu", "法务" }, { "fa xi", "法系" },
			{ "fa xi si", "法西斯" }, { "fa xia", "罚下" }, { "fa xian", "发现" }, { "fa xian wen ti", "发现问题" }, { "fa xian zi ji", "发现自己" }, { "fa xiao", "发笑" },
			{ "fa xiao xi", "发消息" }, { "fa xie", "发些" }, { "fa xie", "发泄" }, { "fa xin", "发信" }, { "fa xin she", "法新社" }, { "fa xin xi", "发信息" },
			{ "fa xing", "发型" }, { "fa xing", "发行" }, { "fa xing gu piao", "发行股票" }, { "fa xing jia", "发行价" }, { "fa xing jia ge", "发行价格" },
			{ "fa xing liang", "发行量" }, { "fa xing ren", "发行人" }, { "fa xing shi", "发型师" }, { "fa xue", "法学" }, { "fa xue jia", "法学家" },
			{ "fa xue yuan", "法学院" }, { "fa ya", "发芽" }, { "fa yan", "发炎" }, { "fa yan", "发言" }, { "fa yan quan", "发言权" }, { "fa yan ren", "发言人" },
			{ "fa yang", "发扬" }, { "fa yang", "发痒" }, { "fa yang guang da", "发扬光大" }, { "fa yi", "法医" }, { "fa yin", "发音" }, { "fa you jian", "发邮件" },
			{ "fa yu", "发育" }, { "fa yu", "法语" }, { "fa yuan", "法院" }, { "fa yuan di", "发源地" }, { "fa yuan pan jue", "法院判决" }, { "fa yuan shen li", "法院审理" },
			{ "fa yun", "发运" }, { "fa zai", "发在" }, { "fa ze", "法则" }, { "fa zhan", "发展" }, { "fa zhan bian hua", "发展变化" }, { "fa zhan cheng wei", "发展成为" },
			{ "fa zhan dao lu", "发展道路" }, { "fa zhan fang xiang", "发展方向" }, { "fa zhan guan", "发展观" }, { "fa zhan gui hua", "发展规划" },
			{ "fa zhan gui lv", "发展规律" }, { "fa zhan guo cheng", "发展过程" }, { "fa zhan huan jing", "发展环境" }, { "fa zhan ji hua", "发展计划" },
			{ "fa zhan ji yu", "发展机遇" }, { "fa zhan jie duan", "发展阶段" }, { "fa zhan jin cheng", "发展进程" }, { "fa zhan jing ji", "发展经济" },
			{ "fa zhan kong jian", "发展空间" }, { "fa zhan li cheng", "发展历程" }, { "fa zhan li shi", "发展历史" }, { "fa zhan lun tan", "发展论坛" },
			{ "fa zhan mo shi", "发展模式" }, { "fa zhan mu biao", "发展目标" }, { "fa zhan qi lai", "发展起来" }, { "fa zhan qian jing", "发展前景" },
			{ "fa zhan qian li", "发展潜力" }, { "fa zhan qing kuang", "发展情况" }, { "fa zhan qu shi", "发展趋势" }, { "fa zhan shang", "发展商" },
			{ "fa zhan shi", "发展史" }, { "fa zhan shui ping", "发展水平" }, { "fa zhan si lu", "发展思路" }, { "fa zhan su du", "发展速度" },
			{ "fa zhan xian zhuang", "发展现状" }, { "fa zhan xu yao", "发展需要" }, { "fa zhan xun su", "发展迅速" }, { "fa zhan zhan lue", "发展战略" },
			{ "fa zhan zhong xin", "发展中心" }, { "fa zhan zhuang da", "发展壮大" }, { "fa zhan zhuang kuang", "发展状况" }, { "fa zhang", "发张" }, { "fa zhang", "法杖" },
			{ "fa zhe", "发着" }, { "fa zheng", "发证" }, { "fa zhi", "发至" }, { "fa zhi", "发质" }, { "fa zhi", "法制" }, { "fa zhi", "法治" }, { "fa zhi ban", "法制办" },
			{ "fa zhi hua", "法制化" }, { "fa zhi jian she", "法制建设" }, { "fa zhi jiao yu", "法制教育" }, { "fa zi", "发自" }, { "fa zi", "法子" } };
};
