package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN15 {
	public static String[][] pl = { { "gan gan", "干干" }, { "gan gan jing jing", "干干净净" }, { "gan gong neng", "肝功能" }, { "gan guan", "感官" },
			{ "gan guang", "感光" }, { "gan guang du", "感光度" }, { "gan guo", "干过" }, { "gan han", "干旱" }, { "gan hao", "干好" }, { "gan he", "干涸" },
			{ "gan hua", "感化" }, { "gan huai", "感怀" }, { "gan hui", "赶回" }, { "gan huo", "干活" }, { "gan ji", "感激" }, { "gan ji", "赶集" },
			{ "gan ji bu jin", "感激不尽" }, { "gan jin", "干劲" }, { "gan jin", "赶紧" }, { "gan jing", "干净" }, { "gan jing", "干警" }, { "gan ju", "柑桔" },
			{ "gan ju", "柑橘" }, { "gan jue", "感觉" }, { "gan jue bu dao", "感觉不到" }, { "gan jue zhen hao", "感觉真好" }, { "gan jun", "杆菌" }, { "gan kai", "感慨" },
			{ "gan kai wan qian", "感慨万千" }, { "gan ku", "干枯" }, { "gan kuai", "赶快" }, { "gan lai", "赶来" }, { "gan lan", "橄榄" }, { "gan lan qiu", "橄榄球" },
			{ "gan lan you", "橄榄油" }, { "gan le", "干了" }, { "gan le", "赶了" }, { "gan lian", "干练" }, { "gan liang", "干粮" }, { "gan liu", "干流" },
			{ "gan lu", "甘露" }, { "gan lu", "赶路" }, { "gan ma", "干吗" }, { "gan ma", "干嘛" }, { "gan ma", "干妈" }, { "gan mang", "赶忙" }, { "gan mao", "感冒" },
			{ "gan mao le", "感冒了" }, { "gan mao yao", "感冒药" }, { "gan me", "干么" }, { "gan qing", "感情" }, { "gan qing", "敢情" },
			{ "gan qing sheng huo", "感情生活" }, { "gan qu", "敢去" }, { "gan qu", "赶去" }, { "gan ran", "感染" }, { "gan ran li", "感染力" }, { "gan ran zhe", "感染者" },
			{ "gan rao", "干扰" }, { "gan rao su", "干扰素" }, { "gan ren", "感人" }, { "gan se", "干涩" }, { "gan sha", "干啥" }, { "gan shang", "感伤" },
			{ "gan shang", "赶上" }, { "gan she", "干涉" }, { "gan shen", "肝肾" }, { "gan shen me", "干什么" }, { "gan shi", "干事" }, { "gan shi jian", "赶时间" },
			{ "gan shou", "感受" }, { "gan shuo", "敢说" }, { "gan si", "干死" }, { "gan si dui", "敢死队" }, { "gan su", "甘肃" }, { "gan su sheng", "甘肃省" },
			{ "gan tan", "感叹" }, { "gan tan hao", "感叹号" }, { "gan tian", "甘甜" }, { "gan tong shen shou", "感同身受" }, { "gan wan", "干完" }, { "gan wang", "赶往" },
			{ "gan wen", "敢问" }, { "gan wu", "感悟" }, { "gan xi", "干洗" }, { "gan xi", "干系" }, { "gan xi bao", "干细胞" }, { "gan xi bao", "肝细胞" },
			{ "gan xian", "干线" }, { "gan xiang", "感想" }, { "gan xiang", "敢想" }, { "gan xie", "干些" }, { "gan xie", "感谢" }, { "gan xin", "甘心" },
			{ "gan xing", "干性" }, { "gan xing", "感性" }, { "gan xing qu", "感兴趣" }, { "gan yan", "感言" }, { "gan yan", "肝炎" }, { "gan ying", "感应" },
			{ "gan ying hua", "肝硬化" }, { "gan ying qi", "感应器" }, { "gan you", "甘油" }, { "gan yu", "干预" }, { "gan yu", "敢于" }, { "gan yu", "甘于" },
			{ "gan yuan", "甘愿" }, { "gan zai", "赶在" }, { "gan zang", "肝脏" }, { "gan zao", "干燥" }, { "gan zhao", "感召" }, { "gan zhe", "干着" },
			{ "gan zhe", "甘蔗" }, { "gan zhe", "赶着" }, { "gan zhi", "感知" }, { "gan zhou", "赣州" }, { "gan zi", "杆子" }, { "gan zou", "赶走" }, { "gan zuo", "敢做" },
			{ "gang", "冈" }, { "gang", "刚" }, { "gang", "剛" }, { "gang", "堈" }, { "gang", "堽" }, { "gang", "岗" }, { "gang", "岡" }, { "gang", "崗" },
			{ "gang", "戆" }, { "gang", "扛" }, { "gang", "杠" }, { "gang", "棡" }, { "gang", "槓" }, { "gang", "港" }, { "gang", "犅" }, { "gang", "疘" },
			{ "gang", "筻" }, { "gang", "綱" }, { "gang", "纲" }, { "gang", "缸" }, { "gang", "罡" }, { "gang", "肛" }, { "gang", "釭" }, { "gang", "鋼" },
			{ "gang", "钢" }, { "gang ao", "港澳" }, { "gang ao tai", "港澳台" }, { "gang ban", "港版" }, { "gang ban", "钢板" }, { "gang bei", "刚被" },
			{ "gang bi", "港币" }, { "gang bi", "钢笔" }, { "gang bi ye", "刚毕业" }, { "gang cai", "刚才" }, { "gang cai", "钢材" }, { "gang cai jia ge", "钢材价格" },
			{ "gang chang", "钢厂" }, { "gang chu", "刚出" }, { "gang chu dao", "刚出道" }, { "gang chu sheng", "刚出生" }, { "gang cong", "刚从" }, { "gang da", "港大" },
			{ "gang dao", "刚到" }, { "gang du", "刚度" }, { "gang gan", "杠杆" }, { "gang gang", "刚刚" }, { "gang gang hao", "刚刚好" },
			{ "gang gang kai shi", "刚刚开始" }, { "gang gou", "钢构" }, { "gang gu", "港股" }, { "gang guan", "钢管" }, { "gang guo", "刚果" }, { "gang guo", "刚过" },
			{ "gang hang", "港行" }, { "gang hao", "刚好" }, { "gang jiao", "肛交" }, { "gang jie", "港姐" }, { "gang jie gou", "钢结构" }, { "gang jin", "刚进" },
			{ "gang jin", "钢筋" }, { "gang ju", "港剧" }, { "gang kai shi", "刚开始" }, { "gang kan", "刚看" }, { "gang kou", "港口" }, { "gang lai", "刚来" },
			{ "gang ling", "纲领" }, { "gang luo", "刚落" }, { "gang mai", "刚买" }, { "gang men", "肛门" }, { "gang pian", "港片" }, { "gang qiang", "刚强" },
			{ "gang qin", "钢琴" }, { "gang qin jia", "钢琴家" }, { "gang qin qu", "钢琴曲" }, { "gang qu", "刚去" }, { "gang qu", "港区" }, { "gang ren", "港人" },
			{ "gang shang", "港商" }, { "gang si", "钢丝" }, { "gang tai", "港台" }, { "gang tie", "钢铁" }, { "gang tie hang ye", "钢铁行业" },
			{ "gang tie qi ye", "钢铁企业" }, { "gang tie ye", "钢铁业" }, { "gang wan", "港湾" }, { "gang wei", "岗位" }, { "gang wei zhi ze", "岗位职责" },
			{ "gang xia", "刚下" }, { "gang xiang", "刚想" }, { "gang xing", "刚性" }, { "gang yao", "刚要" }, { "gang yao", "纲要" }, { "gang yi", "刚一" },
			{ "gang yi", "刚毅" }, { "gang yuan", "港元" }, { "gang zai", "刚在" }, { "gang zou", "刚走" }, { "gao", "勂" }, { "gao", "告" }, { "gao", "搞" },
			{ "gao", "杲" }, { "gao", "槁" }, { "gao", "槔" }, { "gao", "槹" }, { "gao", "檺" }, { "gao", "櫜" }, { "gao", "皋" }, { "gao", "皐" }, { "gao", "睪" },
			{ "gao", "睾" }, { "gao", "祰" }, { "gao", "稿" }, { "gao", "筶" }, { "gao", "篙" }, { "gao", "糕" }, { "gao", "縞" }, { "gao", "缟" }, { "gao", "羔" },
			{ "gao", "膏" }, { "gao", "藁" }, { "gao", "誥" }, { "gao", "诰" }, { "gao", "郜" }, { "gao", "鋯" }, { "gao", "锆" }, { "gao", "镐" }, { "gao", "韟" },
			{ "gao", "高" }, { "gao", "髙" }, { "gao", "鷎" }, { "gao", "鼛" }, { "gao ang", "高昂" }, { "gao ao", "高傲" }, { "gao bai", "告白" },
			{ "gao biao zhun", "高标准" }, { "gao bie", "告别" }, { "gao bu dong", "搞不懂" }, { "gao bu hao", "搞不好" }, { "gao cai sheng", "高材生" },
			{ "gao ceng", "高层" }, { "gao ceng ci", "高层次" }, { "gao ceng jian zhu", "高层建筑" }, { "gao ceng ling dao", "高层领导" }, { "gao chan", "高产" },
			{ "gao chang", "高唱" }, { "gao chao", "高潮" }, { "gao chao", "高超" }, { "gao cheng", "搞成" }, { "gao cheng", "高程" }, { "gao chou", "稿酬" },
			{ "gao chu", "搞出" }, { "gao chu", "高出" }, { "gao chu", "高处" }, { "gao ci", "告辞" }, { "gao cuo", "搞错" }, { "gao da", "高大" }, { "gao da", "高达" },
			{ "gao dan bai", "高蛋白" }, { "gao dang", "高档" }, { "gao dao", "搞到" }, { "gao de", "搞得" }, { "gao de", "搞的" }, { "gao de", "高的" },
			{ "gao deng", "高等" }, { "gao deng jiao yu", "高等教育" }, { "gao deng shu xue", "高等数学" }, { "gao deng xue xiao", "高等学校" },
			{ "gao deng yuan xiao", "高等院校" }, { "gao di", "高低" }, { "gao di", "高地" }, { "gao dian", "搞掂" }, { "gao dian", "搞点" }, { "gao dian", "糕点" },
			{ "gao dian", "高点" }, { "gao diao", "高调" }, { "gao ding", "搞定" }, { "gao dong", "搞懂" }, { "gao du", "高度" }, { "gao du ping jia", "高度评价" },
			{ "gao du zhong shi", "高度重视" }, { "gao duan", "高端" }, { "gao duan chan pin", "高端产品" }, { "gao e", "高额" }, { "gao er", "高二" },
			{ "gao er fu", "高尔夫" }, { "gao er fu qiu", "高尔夫球" }, { "gao fa", "高发" }, { "gao fang", "高仿" }, { "gao fang jia", "高房价" }, { "gao fei", "稿费" },
			{ "gao fei", "高飞" }, { "gao fen", "高分" }, { "gao fen bian lv", "高分辨率" }, { "gao fen zi", "高分子" }, { "gao feng", "高峰" },
			{ "gao feng lun tan", "高峰论坛" }, { "gao feng qi", "高峰期" }, { "gao feng xian", "高风险" }, { "gao fu jia zhi", "高附加值" }, { "gao gan", "高干" },
			{ "gao gao", "搞搞" }, { "gao gao", "高高" }, { "gao gao de", "高高的" }, { "gao gao xing xing", "高高兴兴" }, { "gao gao zai shang", "高高在上" },
			{ "gao ge", "高歌" }, { "gao ge zi", "高个子" }, { "gao gen", "高跟" }, { "gao gen xie", "高跟鞋" }, { "gao gong", "高工" }, { "gao gu", "高估" },
			{ "gao guai", "搞怪" }, { "gao guan", "高官" }, { "gao guan", "高管" }, { "gao guang", "高光" }, { "gao gui", "高贵" }, { "gao guo", "搞过" },
			{ "gao guo", "高过" }, { "gao han", "高喊" }, { "gao hao", "搞好" }, { "gao hao neng", "高耗能" }, { "gao hu", "高呼" }, { "gao huai", "搞坏" },
			{ "gao huo", "搞活" }, { "gao ji", "告急" }, { "gao ji", "高级" }, { "gao ji guan yuan", "高级官员" }, { "gao ji ren cai", "高级人才" }, { "gao ji shu", "高技术" },
			{ "gao ji zhong xue", "高级中学" }, { "gao jia", "高价" }, { "gao jia", "高架" }, { "gao jian", "稿件" }, { "gao jian", "高见" }, { "gao jiao", "高教" },
			{ "gao jie", "告诫" }, { "gao jie", "高洁" }, { "gao jie", "高阶" }, { "gao jing", "告警" }, { "gao jing du", "高精度" }, { "gao jiu", "高就" },
			{ "gao ju", "高举" }, { "gao ju", "高居" }, { "gao kai", "高开" }, { "gao kang", "高亢" }, { "gao kao", "高考" }, { "gao kao cheng ji", "高考成绩" },
			{ "gao ke", "高科" }, { "gao ke ji", "高科技" }, { "gao kong", "高空" }, { "gao li", "高丽" }, { "gao li dai", "高利贷" }, { "gao liang", "高亮" },
			{ "gao liang", "高粱" }, { "gao ling", "高龄" }, { "gao lou", "高楼" }, { "gao lou da sha", "高楼大厦" }, { "gao lu", "高卢" }, { "gao lu", "高炉" },
			{ "gao mi du", "高密度" }, { "gao ming", "高明" }, { "gao nan du", "高难度" }, { "gao neng", "高能" }, { "gao nian ji", "高年级" }, { "gao nong du", "高浓度" },
			{ "gao pei", "高配" }, { "gao pin", "高频" }, { "gao pin zhi", "高品质" }, { "gao qi", "搞起" }, { "gao qi", "高企" }, { "gao qi dian", "高起点" },
			{ "gao qiang", "高强" }, { "gao qiang du", "高强度" }, { "gao qiao", "高桥" }, { "gao qing", "搞清" }, { "gao qing", "高清" }, { "gao qing chu", "搞清楚" },
			{ "gao qing xi", "高清晰" }, { "gao re", "高热" }, { "gao ren", "高人" }, { "gao san", "高三" }, { "gao seng", "高僧" }, { "gao shan", "高山" },
			{ "gao shang", "告上" }, { "gao shang", "高尚" }, { "gao shao", "高烧" }, { "gao shen", "高深" }, { "gao shen me", "搞什么" }, { "gao sheng", "高升" },
			{ "gao sheng", "高声" }, { "gao sheng", "高盛" }, { "gao shi", "告示" }, { "gao shou", "高手" }, { "gao shou ru", "高收入" }, { "gao shu", "高数" },
			{ "gao shui ping", "高水平" }, { "gao shui zhun", "高水准" }, { "gao si", "搞死" }, { "gao si", "高斯" }, { "gao song", "高耸" }, { "gao su", "告诉" },
			{ "gao su", "高速" }, { "gao su da jia", "告诉大家" }, { "gao su fa zhan", "高速发展" }, { "gao su gong lu", "高速公路" }, { "gao su ji zhe", "告诉记者" },
			{ "gao su lu", "高速路" }, { "gao su nin", "告诉您" }, { "gao su tie lu", "高速铁路" }, { "gao su zeng zhang", "高速增长" }, { "gao su zhi", "高素质" },
			{ "gao su zi ji", "告诉自己" }, { "gao tai", "高台" }, { "gao tiao", "高挑" }, { "gao tie", "高铁" }, { "gao tong", "高通" }, { "gao tou", "搞头" },
			{ "gao wan", "搞完" }, { "gao wan", "睾丸" }, { "gao wei", "高位" }, { "gao wei", "高危" }, { "gao wen", "高温" }, { "gao xia", "高下" }, { "gao xiao", "搞笑" },
			{ "gao xiao", "高效" }, { "gao xiao", "高校" }, { "gao xiao fei", "高消费" }, { "gao xiao lv", "高效率" }, { "gao xiao xue sheng", "高校学生" },
			{ "gao xiao zhao sheng", "高校招生" }, { "gao xie", "高些" }, { "gao xin", "高新" }, { "gao xin", "高薪" }, { "gao xin ji shu", "高新技术" },
			{ "gao xin qu", "高新区" }, { "gao xing", "高兴" }, { "gao xing jia bi", "高性价比" }, { "gao xing neng", "高性能" }, { "gao xiong", "高雄" },
			{ "gao xue li", "高学历" }, { "gao xue ya", "高血压" }, { "gao xue ya bing", "高血压病" }, { "gao ya", "高压" }, { "gao ya", "高雅" }, { "gao ya guo", "高压锅" },
			{ "gao ya xian", "高压线" }, { "gao yang", "羔羊" }, { "gao yang", "高阳" }, { "gao yao", "膏药" }, { "gao yi", "高一" }, { "gao yi duan luo", "告一段落" },
			{ "gao yin", "高音" }, { "gao you jia", "高油价" }, { "gao yu", "高于" }, { "gao yuan", "高原" }, { "gao yuan", "高远" }, { "gao yuan", "高院" },
			{ "gao yuan yuan", "高圆圆" }, { "gao zeng zhang", "高增长" }, { "gao zhan yuan zhu", "高瞻远瞩" }, { "gao zhang", "高涨" }, { "gao zhao", "高招" },
			{ "gao zhi", "告之" }, { "gao zhi", "告知" }, { "gao zhi", "高知" }, { "gao zhi", "高职" }, { "gao zhi liang", "高质量" }, { "gao zhi yuan xiao", "高职院校" },
			{ "gao zhong", "告终" }, { "gao zhong", "高中" }, { "gao zhong bi ye", "高中毕业" }, { "gao zhong jie duan", "高中阶段" }, { "gao zhong sheng", "高中生" },
			{ "gao zhong tong xue", "高中同学" }, { "gao zhuang", "告状" }, { "gao zi", "稿子" }, { "gao zong", "高宗" }, { "ge", "个" }, { "ge", "仡" }, { "ge", "佮" },
			{ "ge", "個" }, { "ge", "割" }, { "ge", "各" }, { "ge", "合" }, { "ge", "吤" }, { "ge", "咯" }, { "ge", "哥" }, { "ge", "哿" }, { "ge", "嗝" },
			{ "ge", "圪" }, { "ge", "塥" }, { "ge", "彁" }, { "ge", "愅" }, { "ge", "戈" }, { "ge", "戓" }, { "ge", "搁" }, { "ge", "搿" }, { "ge", "擱" },
			{ "ge", "杚" }, { "ge", "格" }, { "ge", "歌" }, { "ge", "滆" }, { "ge", "滒" }, { "ge", "獦" }, { "ge", "疙" }, { "ge", "盖" }, { "ge", "硌" },
			{ "ge", "箇" }, { "ge", "纥" }, { "ge", "胳" }, { "ge", "膈" }, { "ge", "舸" }, { "ge", "葛" }, { "ge", "虼" }, { "ge", "蛤" }, { "ge", "袼" },
			{ "ge", "觡" }, { "ge", "謌" }, { "ge", "轕" }, { "ge", "鉻" }, { "ge", "鎘" }, { "ge", "铬" }, { "ge", "镉" }, { "ge", "閣" }, { "ge", "閤" },
			{ "ge", "阁" }, { "ge", "隔" }, { "ge", "革" }, { "ge", "鞷" }, { "ge", "韐" }, { "ge", "颌" }, { "ge", "騔" }, { "ge", "骼" }, { "ge", "鬲" },
			{ "ge", "鮯" }, { "ge", "鴐" }, { "ge", "鴿" }, { "ge", "鸽" }, { "ge an", "个案" }, { "ge ban", "个半" }, { "ge ban", "各班" }, { "ge ben ha gen", "哥本哈根" },
			{ "ge bi", "戈壁" }, { "ge bi", "隔壁" }, { "ge bie", "个别" }, { "ge bo", "胳膊" }, { "ge bu", "各部" }, { "ge bu xiang tong", "各不相同" },
			{ "ge chang", "个唱" }, { "ge chang", "歌唱" }, { "ge chang jia", "歌唱家" }, { "ge chu", "各处" }, { "ge ci", "歌词" }, { "ge cun", "各村" },
			{ "ge da", "个大" }, { "ge da", "各大" }, { "ge da", "疙瘩" }, { "ge da cheng shi", "各大城市" }, { "ge de", "歌德" }, { "ge di", "各地" }, { "ge diao", "割掉" },
			{ "ge diao", "格调" }, { "ge dou", "格斗" }, { "ge duan", "割断" }, { "ge duan", "隔断" }, { "ge dui", "各队" }, { "ge er", "个儿" }, { "ge er", "戈尔" },
			{ "ge er", "格尔" }, { "ge er mu", "格尔木" }, { "ge fang", "各方" }, { "ge ge", "个个" }, { "ge ge", "各个" }, { "ge ge", "咯咯" }, { "ge ge", "哥哥" },
			{ "ge ge", "格格" }, { "ge ge bu ru", "格格不入" }, { "ge ge fang mian", "各个方面" }, { "ge ge guo jia", "各个国家" }, { "ge ge huan jie", "各个环节" },
			{ "ge gu", "个股" }, { "ge guo", "各国" }, { "ge hang ge ye", "各行各业" }, { "ge he", "隔阂" }, { "ge hou", "歌喉" }, { "ge hua", "歌华" }, { "ge hui", "歌会" },
			{ "ge ji", "各级" }, { "ge ji dang wei", "各级党委" }, { "ge ji ling dao", "各级领导" }, { "ge ji zheng fu", "各级政府" }, { "ge jia", "各家" },
			{ "ge jie", "割接" }, { "ge jie", "各界" }, { "ge jie ren shi", "各界人士" }, { "ge ju", "割据" }, { "ge ju", "格局" }, { "ge ju", "歌剧" },
			{ "ge ju te se", "各具特色" }, { "ge ju yuan", "歌剧院" }, { "ge jue", "隔绝" }, { "ge kai", "隔开" }, { "ge ke", "各科" }, { "ge la", "格拉" },
			{ "ge lan", "格兰" }, { "ge lan shi", "格兰仕" }, { "ge lei", "各类" }, { "ge lei", "格雷" }, { "ge li", "格力" }, { "ge li", "格里" }, { "ge li", "隔离" },
			{ "ge li shuang", "隔离霜" }, { "ge li you", "个理由" }, { "ge lie", "割裂" }, { "ge lin", "格林" }, { "ge lin si pan", "格林斯潘" }, { "ge lou", "阁楼" },
			{ "ge lu", "各路" }, { "ge lu ji ya", "格鲁吉亚" }, { "ge lun bi ya", "哥伦比亚" }, { "ge men", "哥们" }, { "ge men er", "哥们儿" }, { "ge mi", "歌迷" },
			{ "ge ming", "歌名" }, { "ge ming", "革命" }, { "ge ming xing", "革命性" }, { "ge mo", "隔膜" }, { "ge ni", "格尼" }, { "ge nv ren", "个女人" },
			{ "ge pai", "各派" }, { "ge qian", "搁浅" }, { "ge qu", "各区" }, { "ge qu", "歌曲" }, { "ge qu xian", "各区县" }, { "ge re", "隔热" }, { "ge ren", "个人" },
			{ "ge ren", "各人" }, { "ge ren bo ke", "个人博客" }, { "ge ren dang an", "个人档案" }, { "ge ren dian nao", "个人电脑" }, { "ge ren guan dian", "个人观点" },
			{ "ge ren jian li", "个人简历" }, { "ge ren kong jian", "个人空间" }, { "ge ren li yi", "个人利益" }, { "ge ren mei li", "个人魅力" },
			{ "ge ren neng li", "个人能力" }, { "ge ren ren wei", "个人认为" }, { "ge ren ri ji", "个人日记" }, { "ge ren wang zhan", "个人网站" },
			{ "ge ren xin xi", "个人信息" }, { "ge ren xing wei", "个人行为" }, { "ge ren yi jian", "个人意见" }, { "ge ren yin si", "个人隐私" },
			{ "ge ren yong hu", "个人用户" }, { "ge ren zhang hu", "个人账户" }, { "ge ren zhu ye", "个人主页" }, { "ge ren zhu yi", "个人主义" },
			{ "ge ren zhuan ji", "个人专辑" }, { "ge ren zi liao", "个人资料" }, { "ge rou", "割肉" }, { "ge se", "各色" }, { "ge shan", "格栅" }, { "ge she", "割舍" },
			{ "ge sheng", "个省" }, { "ge sheng", "各省" }, { "ge sheng", "歌声" }, { "ge sheng shi", "各省市" }, { "ge shi", "各市" }, { "ge shi", "各式" },
			{ "ge shi", "格式" }, { "ge shi ge yang", "各式各样" }, { "ge shi hua", "格式化" }, { "ge shou", "歌手" }, { "ge shu", "个数" }, { "ge shui", "个税" },
			{ "ge song", "歌颂" }, { "ge tan", "歌坛" }, { "ge te", "哥特" }, { "ge ti", "个体" }, { "ge ti hu", "个体户" }, { "ge tian", "隔天" }, { "ge tiao", "各条" },
			{ "ge ting", "歌厅" }, { "ge tou", "个头" }, { "ge wai", "格外" }, { "ge wei", "个位" }, { "ge wei", "各位" }, { "ge wei ling dao", "各位领导" },
			{ "ge wei peng you", "各位朋友" }, { "ge wu", "歌舞" }, { "ge wu tuan", "歌舞团" }, { "ge xia", "阁下" }, { "ge xian", "各县" }, { "ge xiang", "各项" },
			{ "ge xiang gong zuo", "各项工作" }, { "ge xiang zhi biao", "各项指标" }, { "ge xiao", "各校" }, { "ge xin", "革新" }, { "ge xing", "个性" },
			{ "ge xing", "歌星" }, { "ge xing hua", "个性化" }, { "ge xing qian ming", "个性签名" }, { "ge yan", "格言" }, { "ge yang", "各样" }, { "ge yao", "歌谣" },
			{ "ge ye", "隔夜" }, { "ge yi", "各异" }, { "ge yin", "隔音" }, { "ge you", "各有" }, { "ge you", "葛优" }, { "ge you hui", "歌友会" },
			{ "ge you qian qiu", "各有千秋" }, { "ge yue", "个月" }, { "ge zhan", "各占" }, { "ge zhe", "歌者" }, { "ge zhe", "隔着" }, { "ge zhen", "各镇" },
			{ "ge zhi", "搁置" }, { "ge zhong", "各种" }, { "ge zhong ge yang", "各种各样" }, { "ge zhong lei xing", "各种类型" }, { "ge zhong xing shi", "各种形式" },
			{ "ge zhou", "各州" }, { "ge zhou ba", "葛洲坝" }, { "ge zi", "个子" }, { "ge zi", "个字" }, { "ge zi", "各自" }, { "ge zi", "格子" }, { "ge zi", "鸽子" },
			{ "ge zi fu", "个字符" }, { "ge zu", "各族" }, { "ge zu", "各组" }, { "ge zu ren min", "各族人民" }, { "gei", "給" }, { "gei", "给" }, { "gei bao bao", "给宝宝" },
			{ "gei chu", "给出" }, { "gei dian", "给点" }, { "gei ding", "给定" }, { "gei fu", "给付" }, { "gei ge", "给个" }, { "gei ke hu", "给客户" },
			{ "gei le", "给了" }, { "gei le ni", "给了你" }, { "gei le ta", "给了他" }, { "gei le wo", "给了我" }, { "gei ni", "给你" }, { "gei ni de", "给你的" },
			{ "gei ni kan", "给你看" }, { "gei nin", "给您" }, { "gei pai shui", "给排水" }, { "gei qian", "给钱" }, { "gei ren", "给人" }, { "gei ren yi", "给人以" },
			{ "gei shui", "给水" }, { "gei shui", "给谁" }, { "gei ta", "给他" }, { "gei ta", "给她" }, { "gei ta", "给它" }, { "gei wo", "给我" }, { "gei wo fa", "给我发" },
			{ "gei yao", "给药" }, { "gei yu", "给与" }, { "gei yu", "给予" }, { "gen", "亘" }, { "gen", "哏" }, { "gen", "揯" }, { "gen", "根" }, { "gen", "艮" },
			{ "gen", "茛" }, { "gen", "跟" }, { "gen ban", "跟班" }, { "gen ben", "根本" }, { "gen ben li yi", "根本利益" }, { "gen ben xing", "根本性" },
			{ "gen ben yuan yin", "根本原因" }, { "gen bie ren", "跟别人" }, { "gen bu", "根部" }, { "gen bu shang", "跟不上" }, { "gen chu", "根除" }, { "gen dan", "跟单" },
			{ "gen feng", "跟风" }, { "gen gu", "亘古" }, { "gen ji", "根基" }, { "gen jin", "跟进" }, { "gen ju", "根据" }, { "gen ju di", "根据地" },
			{ "gen ju xu yao", "根据需要" }, { "gen mu lu", "根目录" }, { "gen mu lu xia", "根目录下" }, { "gen ni", "跟你" }, { "gen nin", "跟您" }, { "gen qian", "跟前" },
			{ "gen ren", "跟人" }, { "gen shang", "跟上" }, { "gen shen di gu", "根深蒂固" }, { "gen shui", "跟谁" }, { "gen sui", "跟随" }, { "gen ta", "跟他" },
			{ "gen ta", "跟她" }, { "gen tie", "跟帖" }, { "gen tie", "跟贴" }, { "gen tou", "跟头" }, { "gen tuan", "跟团" }, { "gen wo", "跟我" },
			{ "gen wo lai", "跟我来" }, { "gen wo shuo", "跟我说" }, { "gen xi", "根系" }, { "gen yuan", "根源" }, { "gen zai", "跟在" }, { "gen zhe", "跟着" },
			{ "gen zhi", "根治" }, { "gen zhu", "跟住" }, { "gen zong", "跟踪" }, { "geng", "亙" }, { "geng", "哽" }, { "geng", "埂" }, { "geng", "堩" },
			{ "geng", "峺" }, { "geng", "庚" }, { "geng", "挭" }, { "geng", "更" }, { "geng", "梗" }, { "geng", "浭" }, { "geng", "畊" }, { "geng", "綆" },
			{ "geng", "緪" }, { "geng", "绠" }, { "geng", "羹" }, { "geng", "耕" }, { "geng", "耿" }, { "geng", "菮" }, { "geng", "賡" }, { "geng", "赓" },
			{ "geng", "郠" }, { "geng", "颈" }, { "geng", "骾" }, { "geng", "鯁" }, { "geng", "鲠" }, { "geng", "鶊" }, { "geng ai", "更爱" },
			{ "geng an quan", "更安全" }, { "geng bu", "更不" }, { "geng bu yong shuo", "更不用说" }, { "geng can", "更惨" }, { "geng cha", "更差" },
			{ "geng chang", "更长" }, { "geng da", "更大" }, { "geng da de", "更大的" }, { "geng di", "更低" }, { "geng di", "耕地" }, { "geng die", "更迭" },
			{ "geng duo", "更多" }, { "geng duo de", "更多的" }, { "geng duo guan yu", "更多关于" }, { "geng duo jing cai", "更多精彩" }, { "geng duo xin xi", "更多信息" },
			{ "geng fang bian", "更方便" }, { "geng gai", "更改" }, { "geng gao", "更高" }, { "geng gao de", "更高的" }, { "geng geng yu huai", "耿耿于怀" },
			{ "geng guang", "更广" }, { "geng gui", "更贵" }, { "geng hao", "更好" }, { "geng hao de", "更好地" }, { "geng hao de", "更好的" }, { "geng hao di", "更好地" },
			{ "geng he kuang", "更何况" }, { "geng huan", "更换" }, { "geng hui", "更会" }, { "geng jia", "更佳" }, { "geng jia", "更加" }, { "geng jin", "更紧" },
			{ "geng jin", "更近" }, { "geng jin yi bu", "更进一步" }, { "geng jing cai", "更精彩" }, { "geng jiu", "更久" }, { "geng ju", "更具" }, { "geng ke", "更可" },
			{ "geng ke pa", "更可怕" }, { "geng kuai", "更快" }, { "geng li hai", "更厉害" }, { "geng ling", "更令" }, { "geng mei", "更没" }, { "geng mei", "更美" },
			{ "geng mei hao", "更美好" }, { "geng ming", "更名" }, { "geng nan", "更难" }, { "geng neng", "更能" }, { "geng nian qi", "更年期" },
			{ "geng piao liang", "更漂亮" }, { "geng qiang", "更强" }, { "geng qing xi", "更清晰" }, { "geng rang", "更让" }, { "geng rong yi", "更容易" },
			{ "geng shao", "更少" }, { "geng shen", "更深" }, { "geng shen", "更甚" }, { "geng shi", "更是" }, { "geng shi he", "更适合" }, { "geng ti", "更替" },
			{ "geng wei", "更为" }, { "geng xi huan", "更喜欢" }, { "geng xian", "更显" }, { "geng xiang", "更像" }, { "geng xiang", "更象" }, { "geng xiang xi", "更详细" },
			{ "geng xiao", "更小" }, { "geng xin", "更新" }, { "geng xin huan dai", "更新换代" }, { "geng xu yao", "更需要" }, { "geng yao", "更要" }, { "geng ye", "哽咽" },
			{ "geng yi", "更易" }, { "geng yi", "更衣" }, { "geng yi shi", "更衣室" }, { "geng ying", "更应" }, { "geng you", "更有" }, { "geng you xiao", "更有效" },
			{ "geng yuan", "更远" }, { "geng yun", "耕耘" }, { "geng zao", "更早" }, { "geng zao", "更糟" }, { "geng zheng", "更正" }, { "geng zhi", "耿直" },
			{ "geng zhong", "更重" }, { "geng zhong", "耕种" }, { "geng zhong yao", "更重要" }, { "geng zu", "梗阻" }, { "geng zuo", "耕作" }, { "gong", "供" },
			{ "gong", "公" }, { "gong", "共" }, { "gong", "功" }, { "gong", "匑" }, { "gong", "塨" }, { "gong", "宫" }, { "gong", "宮" }, { "gong", "工" },
			{ "gong", "巩" }, { "gong", "幊" }, { "gong", "弓" }, { "gong", "恭" }, { "gong", "拱" }, { "gong", "拲" }, { "gong", "攻" }, { "gong", "栱" },
			{ "gong", "汞" }, { "gong", "熕" }, { "gong", "珙" }, { "gong", "红" }, { "gong", "肱" }, { "gong", "蚣" }, { "gong", "觥" }, { "gong", "貢" },
			{ "gong", "贡" }, { "gong", "躬" }, { "gong", "輁" }, { "gong", "鞏" }, { "gong", "龔" }, { "gong", "龚" }, { "gong an", "公安" }, { "gong an bu", "公安部" },
			{ "gong an bu men", "公安部门" }, { "gong an fen ju", "公安分局" }, { "gong an ji guan", "公安机关" }, { "gong an ju", "公安局" }, { "gong an ju zhang", "公安局长" },
			{ "gong an min jing", "公安民警" }, { "gong an ting", "公安厅" }, { "gong ban", "公办" }, { "gong ban", "公版" }, { "gong bao", "公报" }, { "gong bao", "工包" },
			{ "gong ben fei", "工本费" }, { "gong bing", "工兵" }, { "gong bu", "公布" }, { "gong bu ke mo", "功不可没" }, { "gong bu ying qiu", "供不应求" } };
};
