package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN40 {
	public static String[][] pl = { { "sa ke si", "萨克斯" }, { "sa la", "萨拉" }, { "sa luo", "洒落" }, { "sa man", "萨满" }, { "sa niao", "撒尿" }, { "sa te", "萨特" },
			{ "sa tuo", "洒脱" }, { "sa ye", "撒野" }, { "sa zai", "撒在" }, { "sa zai", "洒在" }, { "sai", "僿" }, { "sai", "噻" }, { "sai", "塞" }, { "sai", "揌" },
			{ "sai", "毢" }, { "sai", "腮" }, { "sai", "賽" }, { "sai", "赛" }, { "sai", "顋" }, { "sai", "鳃" }, { "sai ban", "塞班" }, { "sai bo", "赛博" },
			{ "sai chang", "赛场" }, { "sai che", "塞车" }, { "sai che", "赛车" }, { "sai cheng", "赛程" }, { "sai dao", "塞到" }, { "sai dao", "赛道" },
			{ "sai di", "赛迪" }, { "sai er", "塞尔" }, { "sai er", "赛尔" }, { "sai er wei ya", "塞尔维亚" }, { "sai ge", "赛格" }, { "sai gei", "塞给" },
			{ "sai hei", "塞黑" }, { "sai hong", "腮红" }, { "sai hou", "赛后" }, { "sai ji", "赛季" }, { "sai jin", "塞进" }, { "sai la tu", "赛拉图" },
			{ "sai ma", "赛马" }, { "sai man", "塞满" }, { "sai men tie ke", "赛门铁克" }, { "sai pao", "赛跑" }, { "sai qian", "赛前" }, { "sai qu", "赛区" },
			{ "sai shi", "赛事" }, { "sai wai", "塞外" }, { "sai wei li ya", "塞维利亚" }, { "sai yang", "赛扬" }, { "sai zhi", "赛制" }, { "san", "三" }, { "san", "伞" },
			{ "san", "傘" }, { "san", "叁" }, { "san", "帴" }, { "san", "彡" }, { "san", "散" }, { "san", "毵" }, { "san", "毿" }, { "san", "氵" }, { "san", "糁" },
			{ "san", "糂" }, { "san", "糝" }, { "san", "繖" }, { "san", "鏒" }, { "san", "閐" }, { "san", "馓" }, { "san", "鬖" }, { "san ba", "三八" },
			{ "san bai", "三百" }, { "san bai duo", "三百多" }, { "san ban", "三班" }, { "san bao", "三包" }, { "san bao", "三宝" }, { "san bei", "三倍" },
			{ "san bei", "三杯" }, { "san ben", "三本" }, { "san bian", "三遍" }, { "san bo", "散播" }, { "san bu", "三步" }, { "san bu", "三部" }, { "san bu", "散布" },
			{ "san bu", "散步" }, { "san bu qu", "三部曲" }, { "san bu yao yan", "散布谣言" }, { "san can", "三餐" }, { "san ceng", "三层" }, { "san chang", "三场" },
			{ "san chang", "散场" }, { "san cheng", "三成" }, { "san chi", "三尺" }, { "san chong", "三重" }, { "san chu", "三处" }, { "san ci", "三次" },
			{ "san ci hui yi", "三次会议" }, { "san da", "三大" }, { "san da", "散打" }, { "san dai", "三代" }, { "san dao", "三到" }, { "san dao", "三道" },
			{ "san deng", "三等" }, { "san deng jiang", "三等奖" }, { "san di", "三地" }, { "san dian", "三点" }, { "san du", "三度" }, { "san duan", "三段" },
			{ "san duo", "三多" }, { "san fa", "散发" }, { "san fa chu", "散发出" }, { "san fan", "三番" }, { "san fang", "三房" }, { "san fang", "三方" },
			{ "san fang mian", "三方面" }, { "san fen", "三份" }, { "san fen", "三分" }, { "san fen qiu", "三分球" }, { "san fen zhi er", "三分之二" },
			{ "san fen zhi yi", "三分之一" }, { "san fen zhong", "三分钟" }, { "san ge", "三个" }, { "san ge", "三哥" }, { "san ge dai biao", "三个代表" },
			{ "san ge fang mian", "三个方面" }, { "san ge jie duan", "三个阶段" }, { "san ge ren", "三个人" }, { "san ge yue", "三个月" }, { "san ge zi", "三个字" },
			{ "san gen", "三根" }, { "san geng", "三更" }, { "san guo", "三国" }, { "san guo wu shuang", "三国无双" }, { "san guo yan yi", "三国演义" },
			{ "san guo zhi", "三国志" }, { "san hao", "三号" }, { "san he yi", "三合一" }, { "san hu", "散户" }, { "san huan", "三环" }, { "san huo", "散伙" },
			{ "san huo", "散货" }, { "san ji", "三级" }, { "san ji bao", "三季报" }, { "san ji du", "三季度" }, { "san ji guan", "三极管" }, { "san ji pian", "三级片" },
			{ "san jia", "三家" }, { "san jia", "三甲" }, { "san jian", "三件" }, { "san jian", "三间" }, { "san jian", "散件" }, { "san jian ke", "三剑客" },
			{ "san jiang", "三江" }, { "san jiao", "三角" }, { "san jiao jia", "三脚架" }, { "san jiao xing", "三角形" }, { "san jiao zhou", "三角洲" },
			{ "san jie", "三姐" }, { "san jie", "三届" }, { "san jie", "三界" }, { "san jin", "散尽" }, { "san jing", "三井" }, { "san jiu", "三九" },
			{ "san ju hua", "三句话" }, { "san ju qing an", "三聚氰胺" }, { "san jun", "三军" }, { "san kai", "散开" }, { "san ke", "三颗" }, { "san ke", "散客" },
			{ "san kou", "三口" }, { "san kuai", "三块" }, { "san kuan", "三款" }, { "san lang", "三郎" }, { "san le", "散了" }, { "san lei", "三类" },
			{ "san li tun", "三里屯" }, { "san lian", "三联" }, { "san liang", "三两" }, { "san ling", "三菱" }, { "san liu", "三流" }, { "san lou", "三楼" },
			{ "san lu", "三路" }, { "san lu", "三鹿" }, { "san luan", "散乱" }, { "san lun", "三轮" }, { "san lun che", "三轮车" }, { "san luo", "散落" },
			{ "san man", "散漫" }, { "san mao", "三毛" }, { "san mei", "三枚" }, { "san men", "三门" }, { "san men xia", "三门峡" }, { "san mian", "三面" },
			{ "san ming", "三名" }, { "san ming", "三明" }, { "san ming zhi", "三明治" }, { "san nian", "三年" }, { "san nian hou", "三年后" }, { "san nian ji", "三年级" },
			{ "san nian lai", "三年来" }, { "san nian nei", "三年内" }, { "san nian qian", "三年前" }, { "san nong", "三农" }, { "san pei", "三陪" }, { "san pian", "三篇" },
			{ "san qi", "三七" }, { "san qi", "三期" }, { "san qian", "三千" }, { "san qian duo", "三千多" }, { "san qiang", "三强" }, { "san qu", "三区" },
			{ "san qu", "散去" }, { "san re", "散热" }, { "san re pian", "散热片" }, { "san re qi", "散热器" }, { "san ren", "三人" }, { "san ren xing", "三人行" },
			{ "san ri", "三日" }, { "san san", "三三" }, { "san san liang liang", "三三两两" }, { "san san xin", "散散心" }, { "san se", "三色" }, { "san she", "散射" },
			{ "san sheng", "三声" }, { "san shi", "三世" }, { "san shi", "三十" }, { "san shi", "三是" }, { "san shi ba", "三十八" }, { "san shi er", "三十二" },
			{ "san shi liu", "三十六" }, { "san shi nian dai", "三十年代" }, { "san shi ri", "三十日" }, { "san shi sui", "三十岁" }, { "san shi wan", "三十万" },
			{ "san shi wu", "三十五" }, { "san shou", "三首" }, { "san shui", "三水" }, { "san si", "三四" }, { "san si", "三思" }, { "san sui", "三岁" },
			{ "san tai", "三台" }, { "san tao", "三套" }, { "san tian", "三天" }, { "san tian liang tou", "三天两头" }, { "san tiao", "三条" }, { "san tong", "三通" },
			{ "san wan", "三万" }, { "san wei", "三位" }, { "san wei", "三围" }, { "san wei", "三维" }, { "san wei yi ti", "三位一体" }, { "san wen", "散文" },
			{ "san wen yu", "三文鱼" }, { "san wu", "三五" }, { "san xia", "三下" }, { "san xia", "三峡" }, { "san xia da ba", "三峡大坝" },
			{ "san xia gong cheng", "三峡工程" }, { "san xia ku qu", "三峡库区" }, { "san xian", "三线" }, { "san xiang", "三厢" }, { "san xiang", "三相" },
			{ "san xiang", "三项" }, { "san xin", "散心" }, { "san xing", "三星" }, { "san xing dian zi", "三星电子" }, { "san ya", "三亚" }, { "san ya shi", "三亚市" },
			{ "san yang", "三洋" }, { "san yao", "三要" }, { "san ye", "三夜" }, { "san yi", "三一" }, { "san yuan", "三元" }, { "san yuan qiao", "三元桥" },
			{ "san yue", "三月" }, { "san yue fen", "三月份" }, { "san zhang", "三张" }, { "san zhe", "三者" }, { "san zhi", "三只" }, { "san zhi", "三支" },
			{ "san zhi", "三至" }, { "san zhong", "三中" }, { "san zhong", "三种" }, { "san zhong quan hui", "三中全会" }, { "san zhou", "三周" }, { "san zhuang", "散装" },
			{ "san zi", "三字" }, { "san zu", "三组" }, { "san zuo", "三座" }, { "sang", "丧" }, { "sang", "喪" }, { "sang", "嗓" }, { "sang", "搡" }, { "sang", "桑" },
			{ "sang", "桒" }, { "sang", "磉" }, { "sang", "褬" }, { "sang", "鎟" }, { "sang", "顙" }, { "sang", "颡" }, { "sang men", "嗓门" }, { "sang ming", "丧命" },
			{ "sang na", "桑拿" }, { "sang na yu", "桑拿浴" }, { "sang sheng", "丧生" }, { "sang shi", "丧失" }, { "sang ta na", "桑塔纳" }, { "sang yin", "嗓音" },
			{ "sang zi", "嗓子" }, { "sao", "埽" }, { "sao", "嫂" }, { "sao", "慅" }, { "sao", "懆" }, { "sao", "扫" }, { "sao", "掃" }, { "sao", "掻" },
			{ "sao", "搔" }, { "sao", "氉" }, { "sao", "溞" }, { "sao", "瘙" }, { "sao", "矂" }, { "sao", "缫" }, { "sao", "缲" }, { "sao", "臊" }, { "sao", "鄵" },
			{ "sao", "鐰" }, { "sao", "騒" }, { "sao", "騷" }, { "sao", "骚" }, { "sao", "髞" }, { "sao", "鱢" }, { "sao", "鳋" }, { "sao ba", "扫把" },
			{ "sao chu", "扫除" }, { "sao dang", "扫荡" }, { "sao di", "扫地" }, { "sao dong", "骚动" }, { "sao guo", "扫过" }, { "sao huo", "骚货" }, { "sao lei", "扫雷" },
			{ "sao luan", "骚乱" }, { "sao mang", "扫盲" }, { "sao miao", "扫描" }, { "sao miao yi", "扫描仪" }, { "sao mu", "扫墓" }, { "sao rao", "骚扰" },
			{ "sao sao", "嫂嫂" }, { "sao she", "扫射" }, { "sao xing", "扫兴" }, { "sao yang", "瘙痒" }, { "sao zhou", "扫帚" }, { "sao zi", "嫂子" }, { "se", "啬" },
			{ "se", "嗇" }, { "se", "塞" }, { "se", "廧" }, { "se", "拺" }, { "se", "栜" }, { "se", "涩" }, { "se", "渋" }, { "se", "澀" }, { "se", "澁" },
			{ "se", "濇" }, { "se", "濏" }, { "se", "瑟" }, { "se", "璱" }, { "se", "穑" }, { "se", "穡" }, { "se", "粣" }, { "se", "色" }, { "se", "譅" },
			{ "se", "轖" }, { "se", "鉍" }, { "se", "銫" }, { "se", "鏼" }, { "se", "铯" }, { "se", "飋" }, { "se ban", "色斑" }, { "se cai", "色彩" },
			{ "se cha", "色差" }, { "se diao", "色调" }, { "se gui", "色鬼" }, { "se ji shi kong", "色即是空" }, { "se jie", "色戒" }, { "se lang", "色狼" },
			{ "se mang", "色盲" }, { "se mo", "色魔" }, { "se pu", "色谱" }, { "se qing", "色情" }, { "se se", "瑟瑟" }, { "se se", "色色" }, { "se su", "色素" },
			{ "se xi", "色系" }, { "se xiang", "色相" }, { "se you", "色诱" }, { "se ze", "色泽" }, { "sen", "森" }, { "sen lin", "森林" },
			{ "sen lin fang huo", "森林防火" }, { "sen lin gong yuan", "森林公园" }, { "sen lin lang", "森林狼" }, { "sen lin li", "森林里" }, { "sen lin zi yuan", "森林资源" },
			{ "sen sen", "森森" }, { "seng", "僧" }, { "seng", "鬙" }, { "seng lv", "僧侣" }, { "seng ren", "僧人" }, { "sha", "乷" }, { "sha", "傻" }, { "sha", "刹" },
			{ "sha", "剎" }, { "sha", "厦" }, { "sha", "唦" }, { "sha", "唼" }, { "sha", "啥" }, { "sha", "喢" }, { "sha", "嗄" }, { "sha", "挲" }, { "sha", "杀" },
			{ "sha", "杉" }, { "sha", "樧" }, { "sha", "歃" }, { "sha", "殺" }, { "sha", "沙" }, { "sha", "濈" }, { "sha", "煞" }, { "sha", "猀" }, { "sha", "痧" },
			{ "sha", "砂" }, { "sha", "硰" }, { "sha", "箑" }, { "sha", "紗" }, { "sha", "繌" }, { "sha", "纱" }, { "sha", "翜" }, { "sha", "翣" }, { "sha", "莎" },
			{ "sha", "菨" }, { "sha", "萐" }, { "sha", "蔱" }, { "sha", "裟" }, { "sha", "铩" }, { "sha", "霎" }, { "sha", "鯊" }, { "sha", "鲨" }, { "sha bi", "傻逼" },
			{ "sha bi", "煞笔" }, { "sha bu", "纱布" }, { "sha chang", "沙场" }, { "sha che", "刹车" }, { "sha chen", "沙尘" }, { "sha chen bao", "沙尘暴" },
			{ "sha cheng", "沙城" }, { "sha chong", "杀虫" }, { "sha chong ji", "杀虫剂" }, { "sha chu", "杀出" }, { "sha chuang", "纱窗" }, { "sha dan", "傻蛋" },
			{ "sha dao", "杀到" }, { "sha de", "杀得" }, { "sha di", "杀敌" }, { "sha di", "沙地" }, { "sha diao", "杀掉" }, { "sha die", "杀跌" }, { "sha du", "杀毒" },
			{ "sha du ruan jian", "杀毒软件" }, { "sha fa", "沙发" }, { "sha gua", "傻瓜" }, { "sha guang", "杀光" }, { "sha guo", "砂锅" }, { "sha hai", "杀害" },
			{ "sha hai zi", "傻孩子" }, { "sha he", "沙河" }, { "sha hu hu", "傻乎乎" }, { "sha huang", "沙皇" }, { "sha ji", "杀机" }, { "sha ji", "杀鸡" },
			{ "sha jiang", "砂浆" }, { "sha jin", "杀进" }, { "sha jun", "杀菌" }, { "sha la", "沙拉" }, { "sha la", "莎拉" }, { "sha le", "傻了" }, { "sha le", "杀了" },
			{ "sha long", "沙龙" }, { "sha lou", "沙漏" }, { "sha lu", "杀戮" }, { "sha mao", "傻冒" }, { "sha mie", "杀灭" }, { "sha mo", "沙漠" }, { "sha pan", "沙盘" },
			{ "sha ping ba", "沙坪坝" }, { "sha qi", "杀气" }, { "sha qing", "杀青" }, { "sha qiu", "沙丘" }, { "sha ren", "杀人" }, { "sha ren an", "杀人案" },
			{ "sha ren fan", "杀人犯" }, { "sha ru", "杀入" }, { "sha ruan", "杀软" }, { "sha sha", "傻傻" }, { "sha sha", "杀杀" }, { "sha sha", "沙沙" },
			{ "sha sha", "莎莎" }, { "sha sha de", "傻傻的" }, { "sha shang", "杀伤" }, { "sha shang li", "杀伤力" }, { "sha shang xing", "杀伤性" }, { "sha shi", "傻事" },
			{ "sha shi", "啥事" }, { "sha shi", "啥时" }, { "sha shi", "砂石" }, { "sha shi bi ya", "莎士比亚" }, { "sha shi hou", "啥时候" }, { "sha shou", "杀手" },
			{ "sha shou jian", "杀手锏" }, { "sha si", "杀死" }, { "sha tan", "沙滩" }, { "sha te", "沙特" }, { "sha xian", "纱线" }, { "sha xiao", "傻笑" },
			{ "sha ya", "沙哑" }, { "sha ya tou", "傻丫头" }, { "sha yan", "傻眼" }, { "sha yang", "啥样" }, { "sha yi si", "啥意思" }, { "sha yu", "鲨鱼" },
			{ "sha zhu", "杀猪" }, { "sha zi", "傻子" }, { "sha zi", "啥子" }, { "sha zi", "沙子" }, { "shai", "攦" }, { "shai", "晒" }, { "shai", "曬" },
			{ "shai", "筛" }, { "shai", "篩" }, { "shai", "簁" }, { "shai", "繺" }, { "shai", "色" }, { "shai", "酾" }, { "shai", "閷" }, { "shai", "骰" },
			{ "shai cha", "筛查" }, { "shai de", "晒得" }, { "shai gan", "晒干" }, { "shai hei", "晒黑" }, { "shai shai", "晒晒" }, { "shai tai yang", "晒太阳" },
			{ "shai xuan", "筛选" }, { "shan", "僤" }, { "shan", "删" }, { "shan", "刪" }, { "shan", "剡" }, { "shan", "剼" }, { "shan", "单" }, { "shan", "単" },
			{ "shan", "善" }, { "shan", "圸" }, { "shan", "埏" }, { "shan", "墠" }, { "shan", "墡" }, { "shan", "姍" }, { "shan", "姗" }, { "shan", "嬗" },
			{ "shan", "山" }, { "shan", "彡" }, { "shan", "扇" }, { "shan", "掞" }, { "shan", "掸" }, { "shan", "搧" }, { "shan", "擅" }, { "shan", "攙" },
			{ "shan", "敾" }, { "shan", "晱" }, { "shan", "杉" }, { "shan", "杣" }, { "shan", "柵" }, { "shan", "栅" }, { "shan", "樿" }, { "shan", "汕" },
			{ "shan", "潸" }, { "shan", "灗" }, { "shan", "煔" }, { "shan", "煽" }, { "shan", "狦" }, { "shan", "猭" }, { "shan", "珊" }, { "shan", "疝" },
			{ "shan", "痁" }, { "shan", "睒" }, { "shan", "禅" }, { "shan", "穇" }, { "shan", "笘" }, { "shan", "繕" }, { "shan", "纔" }, { "shan", "缮" },
			{ "shan", "羶" }, { "shan", "膳" }, { "shan", "膻" }, { "shan", "舢" }, { "shan", "芟" }, { "shan", "苫" }, { "shan", "蔪" }, { "shan", "蟮" },
			{ "shan", "衫" }, { "shan", "襂" }, { "shan", "覢" }, { "shan", "訕" }, { "shan", "謆" }, { "shan", "譱" }, { "shan", "讪" }, { "shan", "贍" },
			{ "shan", "赡" }, { "shan", "赸" }, { "shan", "跚" }, { "shan", "鄯" }, { "shan", "鐥" }, { "shan", "钐" }, { "shan", "閃" }, { "shan", "閊" },
			{ "shan", "闪" }, { "shan", "陕" }, { "shan", "陝" }, { "shan", "饍" }, { "shan", "騸" }, { "shan", "骟" }, { "shan", "髟" }, { "shan", "鱔" },
			{ "shan", "鳝" }, { "shan bei", "陕北" }, { "shan ben", "山本" }, { "shan bi", "闪避" }, { "shan bian", "善变" }, { "shan chang", "擅长" },
			{ "shan cheng", "山城" }, { "shan chu", "删除" }, { "shan chu", "闪出" }, { "shan chuan", "山川" }, { "shan cun", "山村" }, { "shan cun", "闪存" },
			{ "shan da", "山大" }, { "shan dai", "善待" }, { "shan di", "山地" }, { "shan dian", "闪电" }, { "shan diao", "删掉" }, { "shan ding", "山顶" },
			{ "shan dong", "山东" }, { "shan dong", "山洞" }, { "shan dong", "煽动" }, { "shan dong", "闪动" }, { "shan dong da xue", "山东大学" },
			{ "shan dong lu neng", "山东鲁能" }, { "shan dong ren", "山东人" }, { "shan dong sheng", "山东省" }, { "shan e", "善恶" }, { "shan feng", "山峰" },
			{ "shan gao", "山高" }, { "shan ge", "山歌" }, { "shan gou", "山沟" }, { "shan gu", "山谷" }, { "shan guang", "闪光" }, { "shan guang deng", "闪光灯" },
			{ "shan guang dian", "闪光点" }, { "shan guo", "闪过" }, { "shan hai", "山海" }, { "shan hai guan", "山海关" }, { "shan he", "山河" }, { "shan hong", "山洪" },
			{ "shan hou", "善后" }, { "shan hu", "珊瑚" }, { "shan hu chong", "珊瑚虫" }, { "shan jian", "删减" }, { "shan jian", "山间" }, { "shan jiao", "山脚" },
			{ "shan jiao xia", "山脚下" }, { "shan jie ren yi", "善解人意" }, { "shan kai", "闪开" }, { "shan kou", "山口" }, { "shan kuan", "善款" }, { "shan li", "山里" },
			{ "shan liang", "善良" }, { "shan liang", "闪亮" }, { "shan liang deng chang", "闪亮登场" }, { "shan lin", "山林" }, { "shan ling", "山岭" },
			{ "shan lu", "山路" }, { "shan luan", "山峦" }, { "shan mai", "山脉" }, { "shan mao", "山猫" }, { "shan men", "山门" }, { "shan men", "扇门" },
			{ "shan po", "山坡" }, { "shan qing", "煽情" }, { "shan qiu", "山丘" }, { "shan qu", "删去" }, { "shan qu", "山区" }, { "shan qu", "扇区" },
			{ "shan quan", "山泉" }, { "shan ren", "山人" }, { "shan ren", "闪人" }, { "shan shan", "姗姗" }, { "shan shan", "杉杉" }, { "shan shan", "珊珊" },
			{ "shan shan", "闪闪" }, { "shan shan fa guang", "闪闪发光" }, { "shan shang", "山上" }, { "shan shi", "善事" }, { "shan shi", "山石" }, { "shan shi", "膳食" },
			{ "shan shui", "山水" }, { "shan shui hua", "山水画" }, { "shan shuo", "闪烁" }, { "shan ti", "山体" }, { "shan tian", "山田" }, { "shan tie", "删帖" },
			{ "shan tie", "删贴" }, { "shan tou", "山头" }, { "shan tou", "汕头" }, { "shan tou shi", "汕头市" }, { "shan wei", "汕尾" }, { "shan xi", "山西" },
			{ "shan xi", "陕西" }, { "shan xi sheng", "山西省" }, { "shan xi sheng", "陕西省" }, { "shan xia", "山下" }, { "shan xian", "闪现" }, { "shan xin", "善心" },
			{ "shan ya", "山崖" }, { "shan yang", "山羊" }, { "shan yang", "赡养" }, { "shan yao", "山药" }, { "shan yao", "闪耀" }, { "shan ye", "山野" },
			{ "shan yi", "善意" }, { "shan yong", "善用" }, { "shan yu", "善于" }, { "shan yu", "山芋" }, { "shan zei", "山贼" }, { "shan zha", "山楂" },
			{ "shan zhai", "山寨" }, { "shan zhe", "闪着" }, { "shan zhen", "山镇" }, { "shan zhong", "山中" }, { "shan zhuang", "山庄" }, { "shan zi", "扇子" },
			{ "shan zi", "擅自" }, { "shang", "上" }, { "shang", "仩" }, { "shang", "伤" }, { "shang", "傷" }, { "shang", "商" }, { "shang", "垧" }, { "shang", "塲" },
			{ "shang", "墒" }, { "shang", "尙" }, { "shang", "尚" }, { "shang", "恦" }, { "shang", "慯" }, { "shang", "晌" }, { "shang", "殇" }, { "shang", "殤" },
			{ "shang", "汤" }, { "shang", "熵" }, { "shang", "绱" }, { "shang", "蔏" }, { "shang", "螪" }, { "shang", "蠰" }, { "shang", "裳" }, { "shang", "觞" },
			{ "shang", "觴" }, { "shang", "謪" }, { "shang", "賞" }, { "shang", "赏" }, { "shang", "鬺" }, { "shang an", "上岸" }, { "shang ba", "伤疤" },
			{ "shang bai", "上百" }, { "shang bai wan", "上百万" }, { "shang ban", "上班" }, { "shang ban chang", "上半场" }, { "shang ban nian", "上半年" },
			{ "shang ban shen", "上半身" }, { "shang ban shi jian", "上班时间" }, { "shang ban zu", "上班族" }, { "shang bang", "上榜" }, { "shang bao", "上报" },
			{ "shang bao", "商报" }, { "shang bei", "伤悲" }, { "shang bei zi", "上辈子" }, { "shang bian", "上边" }, { "shang biao", "商标" },
			{ "shang biao zhu ce", "商标注册" }, { "shang bing", "伤病" }, { "shang bu", "上部" }, { "shang bu liao", "上不了" }, { "shang bu qu", "上不去" },
			{ "shang cai", "上菜" }, { "shang can", "伤残" }, { "shang cang", "上苍" }, { "shang ce", "上策" }, { "shang ceng", "上层" },
			{ "shang ceng jian zhu", "上层建筑" }, { "shang chang", "上场" }, { "shang chang", "商场" }, { "shang che", "上车" }, { "shang cheng", "上乘" },
			{ "shang cheng", "商城" }, { "shang chong", "上冲" }, { "shang chuan", "上传" }, { "shang chuan", "上船" }, { "shang chuan dao", "上传到" },
			{ "shang chuan tu pian", "上传图片" }, { "shang chuang", "上床" }, { "shang ci", "上次" }, { "shang ci", "赏赐" }, { "shang cun", "尚存" },
			{ "shang dai", "尚待" }, { "shang dang", "上当" }, { "shang dang shou pian", "上当受骗" }, { "shang dao", "上到" }, { "shang dao", "上岛" },
			{ "shang dao", "伤到" }, { "shang de", "上的" }, { "shang di", "上地" }, { "shang di", "上帝" }, { "shang dian", "上电" }, { "shang dian", "商店" },
			{ "shang diao", "上吊" }, { "shang diao", "上调" }, { "shang ding", "商定" }, { "shang dou", "上都" }, { "shang du", "上都" }, { "shang duan", "上端" },
			{ "shang fan", "商贩" }, { "shang fang", "上方" }, { "shang fang", "上访" }, { "shang fen qi", "上分器" }, { "shang feng", "上风" }, { "shang feng", "伤风" },
			{ "shang fu", "上浮" }, { "shang fu lin", "尚福林" }, { "shang gai", "上盖" }, { "shang gan", "伤感" }, { "shang gang", "上岗" },
			{ "shang gang shang xian", "上纲上线" }, { "shang ge", "上个" }, { "shang ge shi ji", "上个世纪" }, { "shang ge yue", "上个月" }, { "shang gong", "上攻" },
			{ "shang gou", "上钩" }, { "shang gu", "上古" }, { "shang guan", "上官" }, { "shang guo", "上过" }, { "shang hai", "上海" }, { "shang hai", "上还" },
			{ "shang hai", "伤害" }, { "shang hai che zhan", "上海车展" }, { "shang hai da xue", "上海大学" }, { "shang hai da zhong", "上海大众" },
			{ "shang hai dao", "伤害到" }, { "shang hai di qu", "上海地区" }, { "shang hai guo ji", "上海国际" }, { "shang hai hua", "上海话" },
			{ "shang hai jiao da", "上海交大" }, { "shang hai lou shi", "上海楼市" }, { "shang hai pu dong", "上海浦东" }, { "shang hai qi che", "上海汽车" },
			{ "shang hai ren", "上海人" }, { "shang hai shi", "上海市" }, { "shang hai tan", "上海滩" }, { "shang hai tong yong", "上海通用" }, { "shang hai zhan", "上海站" },
			{ "shang han", "伤寒" }, { "shang hang", "上航" }, { "shang hang", "商行" }, { "shang hao", "上好" }, { "shang hao", "商号" }, { "shang hen", "伤痕" },
			{ "shang hen lei lei", "伤痕累累" }, { "shang hu", "商户" }, { "shang hua", "上画" }, { "shang hua", "赏花" }, { "shang hui", "上回" }, { "shang hui", "商会" },
			{ "shang huo", "上火" }, { "shang ji", "上机" }, { "shang ji", "上级" }, { "shang ji", "伤及" }, { "shang ji", "商机" }, { "shang ji ling dao", "上级领导" },
			{ "shang jia", "上佳" }, { "shang jia", "上加" }, { "shang jia", "上家" }, { "shang jia", "上架" }, { "shang jia", "商家" }, { "shang jian", "商检" },
			{ "shang jiang", "上将" }, { "shang jiang", "上讲" }, { "shang jiao", "上交" }, { "shang jiao", "上缴" }, { "shang jiao suo", "上交所" },
			{ "shang jie", "上届" }, { "shang jie", "上街" }, { "shang jie", "商界" }, { "shang jin", "上进" }, { "shang jin", "赏金" }, { "shang jin xin", "上进心" },
			{ "shang jing", "上镜" }, { "shang jiu", "上就" }, { "shang kan", "上看" }, { "shang ke", "上课" }, { "shang ke", "商科" }, { "shang ke", "尚可" },
			{ "shang kong", "上空" }, { "shang kou", "伤口" }, { "shang lai", "上来" }, { "shang lan", "上篮" }, { "shang le", "上了" }, { "shang lian", "上联" },
			{ "shang liang", "商量" }, { "shang liu she hui", "上流社会" }, { "shang lou", "上楼" }, { "shang lu", "上路" }, { "shang lun", "上轮" }, { "shang lv", "商旅" },
			{ "shang ma", "上马" }, { "shang mao", "商贸" }, { "shang men", "上门" }, { "shang men fu wu", "上门服务" }, { "shang mian", "上面" }, { "shang na", "上哪" },
			{ "shang nao jin", "伤脑筋" }, { "shang neng", "尚能" }, { "shang nian", "上年" }, { "shang pai", "上牌" }, { "shang pi", "上皮" },
			{ "shang pi xi bao", "上皮细胞" }, { "shang pin", "上品" }, { "shang pin", "商品" }, { "shang pin fang", "商品房" }, { "shang pin hua", "商品化" },
			{ "shang pin jia ge", "商品价格" }, { "shang pin jing ji", "商品经济" }, { "shang pin shi chang", "商品市场" }, { "shang pin zhu fang", "商品住房" },
			{ "shang pin zhu zhai", "商品住宅" }, { "shang po", "上坡" }, { "shang pu", "上铺" }, { "shang pu", "商铺" }, { "shang qi", "上期" }, { "shang qi", "上汽" },
			{ "shang qi", "商祺" }, { "shang qian", "上前" }, { "shang qian", "上千" }, { "shang qian wan", "上千万" }, { "shang qie", "尚且" }, { "shang qing", "伤情" },
			{ "shang qiu", "商丘" }, { "shang qu", "上去" }, { "shang quan", "商圈" }, { "shang que", "上却" }, { "shang que", "商榷" }, { "shang rao", "上饶" },
			{ "shang ren", "上任" }, { "shang ren", "伤人" }, { "shang ren", "商人" }, { "shang se", "上色" }, { "shang sha", "商厦" }, { "shang shan", "上山" },
			{ "shang shang", "上上" }, { "shang shang xia xia", "上上下下" }, { "shang shen", "上身" }, { "shang shen", "伤身" }, { "shang sheng", "上升" },
			{ "shang shi", "上市" }, { "shang shi", "上师" }, { "shang shi", "伤势" }, { "shang shi", "赏识" }, { "shang shi gong si", "上市公司" },
			{ "shang shi jiao yi", "上市交易" }, { "shang shi shi jian", "上市时间" }, { "shang shou", "上手" }, { "shang shu", "上书" }, { "shang shu", "上述" },
			{ "shang shu", "尚书" }, { "shang shu", "尚属" }, { "shang shuo", "上说" }, { "shang si", "上司" }, { "shang su", "上诉" }, { "shang su ren", "上诉人" },
			{ "shang tai", "上台" }, { "shang tan", "商谈" }, { "shang tao", "商讨" }, { "shang tian", "上天" }, { "shang tiao", "上调" }, { "shang tong", "伤痛" },
			{ "shang tou", "上头" }, { "shang tou", "上投" }, { "shang tou", "伤透" }, { "shang tou mo gen", "上投摩根" } };
};
