package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN18 {
	public static String[][] pl = { { "hai wan", "海湾" }, { "hai wan", "还玩" }, { "hai wang", "海王" }, { "hai wang", "还望" }, { "hai wei", "还为" },
			{ "hai wei", "还未" }, { "hai wen", "还问" }, { "hai wo", "害我" }, { "hai xia", "海峡" }, { "hai xia liang an", "海峡两岸" }, { "hai xia xi an", "海峡西岸" },
			{ "hai xian", "海鲜" }, { "hai xian", "还嫌" }, { "hai xiang", "还像" }, { "hai xiang", "还想" }, { "hai xiao", "海啸" }, { "hai xiao", "还小" },
			{ "hai xin", "海信" }, { "hai xin", "海欣" }, { "hai xing", "海星" }, { "hai xing", "还行" }, { "hai xiu", "害羞" }, { "hai xu", "还需" }, { "hai xu", "还须" },
			{ "hai xuan", "海选" }, { "hai ya", "海牙" }, { "hai yan", "海岩" }, { "hai yan", "海燕" }, { "hai yan", "海盐" }, { "hai yang", "海洋" }, { "hai yao", "还要" },
			{ "hai yi", "还以" }, { "hai ying", "还应" }, { "hai yong", "还用" }, { "hai you", "还有" }, { "hai you hen duo", "还有很多" }, { "hai you mei you", "还有没有" },
			{ "hai you shen me", "还有什么" }, { "hai you shui", "还有谁" }, { "hai you yi xie", "还有一些" }, { "hai yu", "海域" }, { "hai yuan", "还远" },
			{ "hai yun", "海运" }, { "hai zai", "还在" }, { "hai zao", "海藻" }, { "hai zao", "还早" }, { "hai zei", "海贼" }, { "hai zei wang", "海贼王" },
			{ "hai zhan", "海战" }, { "hai zhao", "还找" }, { "hai zhen", "还真" }, { "hai zhen shi", "还真是" }, { "hai zhi", "海之" }, { "hai zhong", "海中" },
			{ "hai zhu", "海珠" }, { "hai zhu qu", "海珠区" }, { "hai zi", "孩子" }, { "hai zi", "海子" }, { "hai zi qi", "孩子气" }, { "han", "函" }, { "han", "凾" },
			{ "han", "含" }, { "han", "哻" }, { "han", "唅" }, { "han", "喊" }, { "han", "寒" }, { "han", "嵅" }, { "han", "悍" }, { "han", "憨" }, { "han", "憾" },
			{ "han", "扞" }, { "han", "捍" }, { "han", "撖" }, { "han", "撼" }, { "han", "旱" }, { "han", "晗" }, { "han", "晥" }, { "han", "暵" }, { "han", "梒" },
			{ "han", "榦" }, { "han", "汉" }, { "han", "汗" }, { "han", "涆" }, { "han", "涵" }, { "han", "漢" }, { "han", "瀚" }, { "han", "焊" }, { "han", "焓" },
			{ "han", "犴" }, { "han", "琀" }, { "han", "甝" }, { "han", "睅" }, { "han", "罕" }, { "han", "翰" }, { "han", "莟" }, { "han", "菡" }, { "han", "蔊" },
			{ "han", "虷" }, { "han", "蚶" }, { "han", "蜬" }, { "han", "蜭" }, { "han", "螒" }, { "han", "谽" }, { "han", "豃" }, { "han", "邗" }, { "han", "邯" },
			{ "han", "酣" }, { "han", "釬" }, { "han", "銲" }, { "han", "鋎" }, { "han", "鋡" }, { "han", "閈" }, { "han", "阚" }, { "han", "雗" }, { "han", "韓" },
			{ "han", "韩" }, { "han", "頇" }, { "han", "頷" }, { "han", "顄" }, { "han", "顸" }, { "han", "颔" }, { "han", "駻" }, { "han", "鬫" }, { "han", "魽" },
			{ "han", "鶾" }, { "han", "鼾" }, { "han ban", "韩版" }, { "han bao", "汉堡" }, { "han bing", "寒冰" }, { "han chao", "汉朝" }, { "han cheng", "汉城" },
			{ "han chu", "喊出" }, { "han dai", "汉代" }, { "han dan", "邯郸" }, { "han dan shi", "邯郸市" }, { "han dao", "喊道" }, { "han dong", "寒冬" },
			{ "han dong", "撼动" }, { "han dou", "憨豆" }, { "han fang", "汉方" }, { "han feng", "寒风" }, { "han feng", "焊缝" }, { "han fu", "汉服" },
			{ "han fu", "韩服" }, { "han gai", "涵盖" }, { "han guo", "韩国" }, { "han guo dian ying", "韩国电影" }, { "han guo dui", "韩国队" }, { "han guo ren", "韩国人" },
			{ "han han", "韩寒" }, { "han hong", "韩红" }, { "han hou", "憨厚" }, { "han hu", "含糊" }, { "han hua", "喊话" }, { "han hua", "汉化" },
			{ "han hua ban", "汉化版" }, { "han jia", "寒假" }, { "han jian", "函件" }, { "han jian", "汉奸" }, { "han jian", "罕见" }, { "han jiang", "寒江" },
			{ "han jiang", "汉江" }, { "han jiao", "喊叫" }, { "han jie", "焊接" }, { "han jin liang", "含金量" }, { "han ju", "韩剧" }, { "han jun", "汉军" },
			{ "han kou", "汉口" }, { "han le", "喊了" }, { "han lei", "含泪" }, { "han leng", "寒冷" }, { "han liang", "含量" }, { "han lin", "翰林" },
			{ "han liu", "寒流" }, { "han liu", "韩流" }, { "han ma", "悍马" }, { "han mao", "汗毛" }, { "han mi er dun", "汉密尔顿" }, { "han peng", "韩鹏" },
			{ "han qi", "寒气" }, { "han qing", "旱情" }, { "han ren", "汉人" }, { "han ri", "韩日" }, { "han sheng", "喊声" }, { "han sheng", "鼾声" },
			{ "han shi", "韩式" }, { "han shou", "函授" }, { "han shu", "函数" }, { "han shu jia", "寒暑假" }, { "han shui", "含税" }, { "han shui", "汗水" },
			{ "han shui liang", "含水量" }, { "han si", "汉斯" }, { "han suan", "寒酸" }, { "han tang", "汉唐" }, { "han wang", "汉王" }, { "han wei", "捍卫" },
			{ "han wen", "韩文" }, { "han wu di", "汉武帝" }, { "han xian", "汗腺" }, { "han xiao", "含笑" }, { "han xin", "寒心" }, { "han xin", "韩信" },
			{ "han xu", "含蓄" }, { "han xuan", "寒暄" }, { "han xue", "韩雪" }, { "han yan", "汗颜" }, { "han yang", "汉阳" }, { "han yang", "涵养" }, { "han yi", "含义" },
			{ "han yi", "寒意" }, { "han yi", "涵义" }, { "han you", "含有" }, { "han yu", "汉语" }, { "han yu", "韩语" }, { "han yu pin yin", "汉语拼音" },
			{ "han yuan", "韩元" }, { "han zai", "旱灾" }, { "han zhe", "含着" }, { "han zhe", "喊着" }, { "han zhong", "汉中" }, { "han zhu", "汗珠" },
			{ "han zi", "汉子" }, { "han zi", "汉字" }, { "han zu", "汉族" }, { "hang", "吭" }, { "hang", "垳" }, { "hang", "夯" }, { "hang", "巷" }, { "hang", "斻" },
			{ "hang", "杭" }, { "hang", "沆" }, { "hang", "笐" }, { "hang", "絎" }, { "hang", "绗" }, { "hang", "航" }, { "hang", "苀" }, { "hang", "蚢" },
			{ "hang", "行" }, { "hang", "貥" }, { "hang", "迒" }, { "hang", "頏" }, { "hang", "颃" }, { "hang", "魧" }, { "hang ban", "航班" },
			{ "hang ban cha xun", "航班查询" }, { "hang cheng", "杭城" }, { "hang cheng", "航程" }, { "hang dang", "行当" }, { "hang dao", "航道" }, { "hang gui", "行规" },
			{ "hang hai", "航海" }, { "hang hui", "行会" }, { "hang huo", "行货" }, { "hang jia", "航嘉" }, { "hang jia", "行家" }, { "hang kong", "航空" },
			{ "hang kong gong si", "航空公司" }, { "hang kong hang tian", "航空航天" }, { "hang kong mu jian", "航空母舰" }, { "hang kong ye", "航空业" },
			{ "hang kong yun shu", "航空运输" }, { "hang lie", "行列" }, { "hang mu", "航母" }, { "hang qing", "行情" }, { "hang shi", "夯实" }, { "hang shu", "行数" },
			{ "hang tian", "航天" }, { "hang tian fei ji", "航天飞机" }, { "hang tian yuan", "航天员" }, { "hang xian", "航线" }, { "hang xiao", "杭萧" },
			{ "hang xing", "航行" }, { "hang ye", "行业" }, { "hang ye biao zhun", "行业标准" }, { "hang ye fa zhan", "行业发展" }, { "hang ye guan li", "行业管理" },
			{ "hang ye long tou", "行业龙头" }, { "hang ye xie hui", "行业协会" }, { "hang ye zi lv", "行业自律" }, { "hang ye zi xun", "行业资讯" }, { "hang yun", "航运" },
			{ "hang zhan lou", "航站楼" }, { "hang zhang", "行长" }, { "hang zhou", "杭州" }, { "hang zhou shi", "杭州市" }, { "hao", "号" }, { "hao", "哠" },
			{ "hao", "嗥" }, { "hao", "嚆" }, { "hao", "嚎" }, { "hao", "壕" }, { "hao", "好" }, { "hao", "昊" }, { "hao", "昦" }, { "hao", "晧" }, { "hao", "暠" },
			{ "hao", "毫" }, { "hao", "浩" }, { "hao", "淏" }, { "hao", "滈" }, { "hao", "澔" }, { "hao", "濠" }, { "hao", "灏" }, { "hao", "灝" }, { "hao", "皓" },
			{ "hao", "皜" }, { "hao", "皞" }, { "hao", "竓" }, { "hao", "籇" }, { "hao", "耗" }, { "hao", "蒿" }, { "hao", "薃" }, { "hao", "薅" }, { "hao", "號" },
			{ "hao", "蚝" }, { "hao", "蠔" }, { "hao", "譹" }, { "hao", "豪" }, { "hao", "貉" }, { "hao", "郝" }, { "hao", "鄗" }, { "hao", "鎬" }, { "hao", "镐" },
			{ "hao", "顥" }, { "hao", "颢" }, { "hao", "鰝" }, { "hao a", "好啊" }, { "hao an", "毫安" }, { "hao ba", "好吧" }, { "hao ban", "好办" },
			{ "hao ban fa", "好办法" }, { "hao ban tian", "好半天" }, { "hao bang", "好棒" }, { "hao bang shou", "好帮手" }, { "hao bao", "好报" }, { "hao bi", "好比" },
			{ "hao bu", "好不" }, { "hao bu", "毫不" }, { "hao bu hao", "好不好" }, { "hao bu ke qi", "毫不客气" }, { "hao bu liu qing", "毫不留情" },
			{ "hao bu rong yi", "好不容易" }, { "hao bu you yu", "毫不犹豫" }, { "hao cai", "好彩" }, { "hao cai", "好菜" }, { "hao cai", "耗材" }, { "hao can", "好惨" },
			{ "hao chang", "好长" }, { "hao che", "好车" }, { "hao cheng", "号称" }, { "hao chi", "好吃" }, { "hao chou", "好丑" }, { "hao chu", "好处" },
			{ "hao da", "好大" }, { "hao da", "浩大" }, { "hao dai", "好歹" }, { "hao dang", "浩荡" }, { "hao de", "好得" }, { "hao de", "好的" }, { "hao di", "好地" },
			{ "hao di", "好滴" }, { "hao di fang", "好地方" }, { "hao dian", "好点" }, { "hao dian", "耗电" }, { "hao dian liang", "耗电量" }, { "hao dian ying", "好电影" },
			{ "hao dong", "好动" }, { "hao dong dong", "好东东" }, { "hao dong xi", "好东西" }, { "hao du", "豪赌" }, { "hao duan", "号段" }, { "hao duan duan", "好端端" },
			{ "hao duo", "好多" }, { "hao duo ren", "好多人" }, { "hao e", "好饿" }, { "hao fa", "好发" }, { "hao fa", "毫发" }, { "hao fan", "好烦" },
			{ "hao fang", "浩方" }, { "hao fang", "豪放" }, { "hao fang fa", "好方法" }, { "hao fei", "耗费" }, { "hao gan", "好感" }, { "hao ge", "好歌" },
			{ "hao gong zuo", "好工作" }, { "hao gui", "好贵" }, { "hao guo", "好过" }, { "hao hai zi", "好孩子" }, { "hao han", "好汉" }, { "hao han", "浩瀚" },
			{ "hao hao", "好好" }, { "hao hao", "浩浩" }, { "hao hao dang dang", "浩浩荡荡" }, { "hao hao hao", "好好好" }, { "hao hao wan", "好好玩" },
			{ "hao hao xue xi", "好好学习" }, { "hao he", "好喝" }, { "hao hou", "好后" }, { "hao hua", "好话" }, { "hao hua", "豪华" }, { "hao hua ban", "豪华版" },
			{ "hao hua che", "豪华车" }, { "hao hua xing", "豪华型" }, { "hao huai", "好坏" }, { "hao huo", "好货" }, { "hao ji", "好几" }, { "hao ji", "好记" },
			{ "hao ji bai", "好几百" }, { "hao ji ci", "好几次" }, { "hao ji hui", "好机会" }, { "hao ji tian", "好几天" }, { "hao jiao", "号角" }, { "hao jiao", "嚎叫" },
			{ "hao jiao", "好觉" }, { "hao jie", "浩劫" }, { "hao jie", "豪杰" }, { "hao jin", "耗尽" }, { "hao jiu", "好久" }, { "hao jiu", "好酒" },
			{ "hao jiu bu jian", "好久不见" }, { "hao jiu mei you", "好久没有" }, { "hao kan", "好看" }, { "hao kan ma", "好看吗" }, { "hao ke", "好客" }, { "hao ke", "毫克" },
			{ "hao ke ai", "好可爱" }, { "hao ku", "好酷" }, { "hao kuai", "好快" }, { "hao la", "好啦" }, { "hao lai", "好莱" }, { "hao lai wu", "好莱坞" },
			{ "hao lao po", "好老婆" }, { "hao lao shi", "好老师" }, { "hao le", "好了" }, { "hao lei", "好累" }, { "hao leng", "好冷" }, { "hao ling", "号令" },
			{ "hao lou", "号楼" }, { "hao ma", "号码" }, { "hao ma", "好吗" }, { "hao ma", "好嘛" }, { "hao mai", "好卖" }, { "hao mai", "豪迈" }, { "hao man", "好慢" },
			{ "hao mang", "好忙" }, { "hao me", "好么" }, { "hao mei", "好美" }, { "hao men", "豪门" }, { "hao meng", "好梦" }, { "hao mi", "毫米" }, { "hao miao", "毫秒" },
			{ "hao ming zi", "好名字" }, { "hao nan", "好男" }, { "hao nan", "好难" }, { "hao nan er", "好男儿" }, { "hao nan ren", "好男人" }, { "hao ne", "好呢" },
			{ "hao neng", "耗能" }, { "hao nv hai", "好女孩" }, { "hao nv ren", "好女人" }, { "hao o", "好哦" }, { "hao pa", "好怕" }, { "hao pai", "号牌" },
			{ "hao peng you", "好朋友" }, { "hao pian", "好片" }, { "hao piao liang", "好漂亮" }, { "hao ping", "好评" }, { "hao qi", "好奇" }, { "hao qi", "豪气" },
			{ "hao qi lai", "好起来" }, { "hao qi xin", "好奇心" }, { "hao qiang", "好强" }, { "hao qing", "豪情" }, { "hao qiu", "好球" }, { "hao qu chu", "好去处" },
			{ "hao ran", "浩然" }, { "hao rang", "好让" }, { "hao re", "好热" }, { "hao ren", "好人" }, { "hao ri zi", "好日子" }, { "hao rong yi", "好容易" },
			{ "hao se", "好色" }, { "hao sha", "好傻" }, { "hao sheng", "好生" }, { "hao sheng", "毫升" }, { "hao shi", "好事" }, { "hao shi", "好似" },
			{ "hao shi", "好使" }, { "hao shi", "好诗" }, { "hao shi", "耗时" }, { "hao shou", "好受" }, { "hao shou", "好手" }, { "hao shu", "好书" },
			{ "hao shu fu", "好舒服" }, { "hao shua", "好耍" }, { "hao shuang", "好爽" }, { "hao shuang", "豪爽" }, { "hao shuo", "好说" }, { "hao si", "好似" },
			{ "hao tie", "好帖" }, { "hao tie", "好贴" }, { "hao ting", "好听" }, { "hao tong", "好痛" }, { "hao tu", "好图" }, { "hao wa", "好哇" }, { "hao wan", "好玩" },
			{ "hao wan de", "好玩的" }, { "hao wen", "好文" }, { "hao wen zhang", "好文章" }, { "hao wu", "毫无" }, { "hao wu yi wen", "毫无疑问" },
			{ "hao wu yi yi", "毫无意义" }, { "hao xi", "好戏" }, { "hao xi guan", "好习惯" }, { "hao xi huan", "好喜欢" }, { "hao xian", "号线" }, { "hao xian", "好险" },
			{ "hao xiang", "好像" }, { "hao xiang", "好想" }, { "hao xiang", "好象" }, { "hao xiang ni", "好想你" }, { "hao xiang shi", "好象是" }, { "hao xiao", "好笑" },
			{ "hao xiao xi", "好消息" }, { "hao xie", "好些" }, { "hao xin", "好心" }, { "hao xin qing", "好心情" }, { "hao xin ren", "好心人" }, { "hao xiong di", "好兄弟" },
			{ "hao xue", "好学" }, { "hao xue sheng", "好学生" }, { "hao ya", "好呀" }, { "hao yang", "好样" }, { "hao ye", "好耶" }, { "hao yi", "好意" },
			{ "hao yi si", "好意思" }, { "hao yong", "好用" }, { "hao you", "好友" }, { "hao you", "耗油" }, { "hao you duo", "好又多" }, { "hao yu", "好于" },
			{ "hao yuan", "好远" }, { "hao yue", "皓月" }, { "hao yun", "好运" }, { "hao yun qi", "好运气" }, { "hao zai", "好在" }, { "hao zhai", "豪宅" },
			{ "hao zhao", "号召" }, { "hao zhao", "好找" }, { "hao zhao li", "号召力" }, { "hao zhu yi", "好主意" }, { "hao zhuan", "好转" }, { "hao zi", "号子" },
			{ "hao zi", "耗子" }, { "hao zi", "耗资" }, { "hao zuo", "好做" }, { "he", "何" }, { "he", "佫" }, { "he", "劾" }, { "he", "合" }, { "he", "吓" },
			{ "he", "呵" }, { "he", "和" }, { "he", "啝" }, { "he", "喝" }, { "he", "嗬" }, { "he", "壑" }, { "he", "姀" }, { "he", "寉" }, { "he", "峆" },
			{ "he", "挌" }, { "he", "敆" }, { "he", "曷" }, { "he", "核" }, { "he", "楁" }, { "he", "河" }, { "he", "涸" }, { "he", "渮" }, { "he", "澕" },
			{ "he", "煂" }, { "he", "熆" }, { "he", "熇" }, { "he", "爀" }, { "he", "犵" }, { "he", "盉" }, { "he", "盍" }, { "he", "盒" }, { "he", "禾" },
			{ "he", "篕" }, { "he", "籺" }, { "he", "粭" }, { "he", "紇" }, { "he", "纥" }, { "he", "翮" }, { "he", "翯" }, { "he", "荷" }, { "he", "菏" },
			{ "he", "蚵" }, { "he", "褐" }, { "he", "覈" }, { "he", "訶" }, { "he", "诃" }, { "he", "貉" }, { "he", "賀" }, { "he", "贺" }, { "he", "赫" },
			{ "he", "郃" }, { "he", "鉌" }, { "he", "鑉" }, { "he", "閡" }, { "he", "闔" }, { "he", "阂" }, { "he", "阖" }, { "he", "靍" }, { "he", "靏" },
			{ "he", "鞨" }, { "he", "颌" }, { "he", "餲" }, { "he", "魺" }, { "he", "鶡" }, { "he", "鶴" }, { "he", "鹤" }, { "he", "麧" }, { "he", "齃" },
			{ "he", "齕" }, { "he", "龢" }, { "he ai", "和蔼" }, { "he an", "河岸" }, { "he bao", "荷包" }, { "he bei", "喝杯" }, { "he bei", "河北" },
			{ "he bei sheng", "河北省" }, { "he ben", "赫本" }, { "he bi", "何必" }, { "he bian", "河边" }, { "he bing", "合并" }, { "he bu", "何不" }, { "he cai", "喝彩" },
			{ "he ceng", "何曾" }, { "he cha", "喝茶" }, { "he cha", "核查" }, { "he chang", "何尝" }, { "he chang", "合唱" }, { "he chang tuan", "合唱团" },
			{ "he cheng", "合成" }, { "he chi", "呵斥" }, { "he chu", "何处" }, { "he chuang", "河床" }, { "he dan", "核弹" }, { "he dao", "喝到" }, { "he dao", "喝道" },
			{ "he dao", "河道" }, { "he de", "喝得" }, { "he de", "喝的" }, { "he deng", "何等" }, { "he di", "何地" }, { "he dian", "喝点" }, { "he dian", "核电" },
			{ "he dian zhan", "核电站" }, { "he ding", "核定" }, { "he dong", "河东" }, { "he duan", "河段" }, { "he dui", "核对" }, { "he duo", "喝多" },
			{ "he duo le", "喝多了" }, { "he er", "赫尔" }, { "he er lai", "何而来" }, { "he er meng", "荷尔蒙" }, { "he er wei yi", "合二为一" }, { "he fa", "合法" },
			{ "he fa", "核发" }, { "he fa hua", "合法化" }, { "he fa quan yi", "合法权益" }, { "he fa xing", "合法性" }, { "he fan", "盒饭" }, { "he fang", "何妨" },
			{ "he fang", "何方" }, { "he fei", "合肥" }, { "he fei shi", "合肥市" }, { "he fu", "和服" }, { "he ge", "合格" }, { "he ge", "和各" },
			{ "he ge chan pin", "合格产品" }, { "he ge lv", "合格率" }, { "he ge zhe", "合格者" }, { "he ge zheng", "合格证" }, { "he gu", "河谷" }, { "he gui", "合规" },
			{ "he guo", "喝过" }, { "he hao", "和好" }, { "he he", "呵呵" }, { "he he", "喝喝" }, { "he he", "嗬嗬" }, { "he he", "赫赫" }, { "he he he", "呵呵呵" },
			{ "he he you ming", "赫赫有名" }, { "he hu", "合乎" }, { "he hu", "呵护" }, { "he hua", "荷花" }, { "he huan", "合欢" }, { "he huang", "和黄" },
			{ "he huo", "合伙" }, { "he huo ren", "合伙人" }, { "he ji", "合剂" }, { "he ji", "合计" }, { "he ji", "合集" }, { "he jie", "何洁" }, { "he jie", "和解" },
			{ "he jie jie", "和姐姐" }, { "he jin", "合金" }, { "he jiong", "何炅" }, { "he jiu", "喝酒" }, { "he ka", "贺卡" }, { "he ka fei", "喝咖啡" },
			{ "he kou", "河口" }, { "he ku", "何苦" }, { "he kuang", "何况" }, { "he lai", "何来" }, { "he lan", "荷兰" }, { "he lan dui", "荷兰队" },
			{ "he lan ren", "荷兰人" }, { "he li", "合力" }, { "he li", "合理" }, { "he li", "河里" }, { "he li an pai", "合理安排" }, { "he li hua", "合理化" },
			{ "he li li yong", "合理利用" }, { "he li shi yong", "合理使用" }, { "he li xing", "合理性" }, { "he liu", "河流" }, { "he long", "贺龙" }, { "he ma", "河马" },
			{ "he mai", "合买" }, { "he mou", "合谋" }, { "he mu", "和睦" }, { "he nai", "喝奶" }, { "he nan", "河南" }, { "he nan ren", "河南人" },
			{ "he nan sheng", "河南省" }, { "he nan you", "和男友" }, { "he nei", "河内" }, { "he neng", "核能" }, { "he ni", "和你" }, { "he niu nai", "喝牛奶" },
			{ "he pai", "合拍" }, { "he pan", "河畔" }, { "he pi jiu", "喝啤酒" }, { "he ping", "和平" }, { "he ping fa zhan", "和平发展" }, { "he ping qu", "和平区" },
			{ "he ping tong yi", "和平统一" }, { "he qi", "何其" }, { "he qi", "和气" }, { "he qi lai", "合起来" }, { "he qian ting", "核潜艇" },
			{ "he qing he li", "合情合理" }, { "he qu he cong", "何去何从" }, { "he ran", "赫然" }, { "he ren", "何人" }, { "he ren", "和人" }, { "he ri", "何日" },
			{ "he ru", "何如" }, { "he run dong", "何润东" }, { "he se", "褐色" }, { "he shan", "和善" }, { "he shan", "河山" }, { "he shang", "和尚" },
			{ "he shang", "喝上" }, { "he shen", "合身" }, { "he sheng", "和声" }, { "he shi", "何事" }, { "he shi", "何时" }, { "he shi", "合适" }, { "he shi", "和室" },
			{ "he shi", "核实" }, { "he shi yan", "核试验" }, { "he shui", "和谁" }, { "he shui", "喝水" }, { "he shui", "河水" }, { "he suan", "合算" },
			{ "he suan", "核算" }, { "he suan", "核酸" }, { "he sui", "贺岁" }, { "he ta", "和他" }, { "he ta", "和她" }, { "he tang", "喝汤" }, { "he tao", "核桃" },
			{ "he ti", "合体" }, { "he tian", "和田" }, { "he tong", "合同" }, { "he tong fa", "合同法" }, { "he wan", "喝完" }, { "he wei", "何为" }, { "he wei", "何谓" },
			{ "he wen ti", "核问题" }, { "he wo", "和我" }, { "he wu", "何物" }, { "he wu", "核武" }, { "he wu ju", "河务局" }, { "he wu qi", "核武器" }, { "he xi", "河西" },
			{ "he xia", "喝下" }, { "he xian", "和弦" }, { "he xiao", "核销" }, { "he xie", "和谐" }, { "he xie", "河蟹" }, { "he xie fa zhan", "和谐发展" },
			{ "he xie she hui", "和谐社会" }, { "he xie xiang chu", "和谐相处" }, { "he xin", "核心" }, { "he xin ji shu", "核心技术" }, { "he xin jia zhi", "核心价值" },
			{ "he xin nei rong", "核心内容" }, { "he xin qu", "核心区" }, { "he xin wang", "核心网" }, { "he xin ye wu", "核心业务" }, { "he xu", "何须" }, { "he xun", "和讯" },
			{ "he yang", "河阳" }, { "he ye", "荷叶" }, { "he yi", "何以" }, { "he yi", "合一" }, { "he yi", "合意" }, { "he yi bei", "喝一杯" }, { "he yi ting", "合议庭" },
			{ "he ying", "合影" }, { "he ying liu nian", "合影留念" }, { "he yong", "何用" }, { "he yong", "合用" }, { "he yuan", "河源" }, { "he yue", "合约" },
			{ "he zai", "何在" }, { "he zai", "荷载" }, { "he zai yi qi", "合在一起" }, { "he ze", "菏泽" }, { "he zhao", "合照" }, { "he zhe", "喝着" }, { "he zhi", "何止" },
			{ "he zhong", "何种" }, { "he zhong", "河中" }, { "he zhou", "喝粥" }, { "he zhuang", "盒装" }, { "he zhun", "核准" }, { "he zi", "合资" }, { "he zi", "盒子" },
			{ "he zi gong si", "合资公司" }, { "he zi qi ye", "合资企业" }, { "he zu", "合租" }, { "he zui", "喝醉" }, { "he zui le", "喝醉了" }, { "he zuo", "合作" },
			{ "he zuo fang", "合作方" }, { "he zuo fang shi", "合作方式" }, { "he zuo guan xi", "合作关系" }, { "he zuo huo ban", "合作伙伴" },
			{ "he zuo jian fang", "合作建房" }, { "he zuo kai fa", "合作开发" }, { "he zuo she", "合作社" }, { "he zuo xiang mu", "合作项目" }, { "he zuo xie yi", "合作协议" },
			{ "he zuo yi liao", "合作医疗" }, { "he zuo yu kuai", "合作愉快" }, { "he zuo zhe", "合作者" }, { "he zuo zu zhi", "合作组织" }, { "hei", "嗨" }, { "hei", "嘿" },
			{ "hei", "潶" }, { "hei", "黑" }, { "hei", "黒" }, { "hei an", "黑暗" }, { "hei bai", "黑白" }, { "hei ban", "黑板" }, { "hei ban bao", "黑板报" },
			{ "hei bang", "黑帮" }, { "hei bao", "黑豹" }, { "hei che", "黑车" }, { "hei dao", "黑道" }, { "hei dian", "黑店" }, { "hei dian", "黑点" },
			{ "hei dong", "黑洞" }, { "hei dou", "黑豆" }, { "hei fa", "黑发" }, { "hei ge er", "黑格尔" }, { "hei he", "黑河" }, { "hei hei", "嘿嘿" },
			{ "hei hei", "黑黑" }, { "hei hei de", "黑黑的" }, { "hei hu hu", "黑乎乎" }, { "hei jin", "黑金" }, { "hei ke", "黑客" }, { "hei ke di guo", "黑客帝国" },
			{ "hei le", "黑了" }, { "hei lian", "黑脸" }, { "hei long", "黑龙" }, { "hei long jiang", "黑龙江" }, { "hei long jiang sheng", "黑龙江省" },
			{ "hei ma", "黑马" }, { "hei mao", "黑猫" }, { "hei mei", "黑莓" }, { "hei ming dan", "黑名单" }, { "hei mu", "黑幕" }, { "hei mu er", "黑木耳" },
			{ "hei pi", "黑皮" }, { "hei ping", "黑屏" }, { "hei ren", "黑人" }, { "hei se", "黑色" }, { "hei se su", "黑色素" }, { "hei se you mo", "黑色幽默" },
			{ "hei shan", "黑山" }, { "hei she hui", "黑社会" }, { "hei shi", "黑市" }, { "hei shi", "黑石" }, { "hei shou", "黑手" }, { "hei tao", "黑桃" },
			{ "hei ti", "黑体" }, { "hei tie", "黑铁" }, { "hei tou", "黑头" }, { "hei xian", "黑线" }, { "hei xin", "黑心" }, { "hei xing xing", "黑猩猩" },
			{ "hei xiong", "黑熊" }, { "hei xiu", "嘿咻" }, { "hei ya ya", "黑压压" }, { "hei yan", "黑烟" }, { "hei yan quan", "黑眼圈" }, { "hei ye", "黑夜" },
			{ "hei ye li", "黑夜里" }, { "hei yi", "黑衣" }, { "hei yi ren", "黑衣人" }, { "hei ying", "黑影" }, { "hei zhi ma", "黑芝麻" }, { "hei zi", "黑子" },
			{ "hen", "很" }, { "hen", "恨" }, { "hen", "拫" }, { "hen", "狠" }, { "hen", "痕" }, { "hen", "鞎" }, { "hen ai", "很爱" }, { "hen ai ni", "很爱你" },
			{ "hen bang", "很棒" }, { "hen bao", "很薄" }, { "hen bao qian", "很抱歉" }, { "hen ben", "很笨" }, { "hen bu", "很不" }, { "hen bu cuo", "很不错" },
			{ "hen bu de", "恨不得" }, { "hen bu neng", "恨不能" }, { "hen cha", "很差" }, { "hen chang", "很长" }, { "hen chang shi jian", "很长时间" },
			{ "hen chou", "很丑" }, { "hen da", "很大" }, { "hen da de", "很大的" }, { "hen dan", "很淡" }, { "hen di", "很低" }, { "hen du", "狠毒" },
			{ "hen duan", "很短" }, { "hen duo", "很多" }, { "hen duo ci", "很多次" }, { "hen duo dong xi", "很多东西" }, { "hen duo ren", "很多人" },
			{ "hen duo ren dou", "很多人都" }, { "hen duo shi hou", "很多时候" }, { "hen duo shi qing", "很多事情" }, { "hen fan", "很烦" }, { "hen fang bian", "很方便" },
			{ "hen gao", "很高" }, { "hen gao xing", "很高兴" }, { "hen guai", "很乖" }, { "hen guai", "很怪" }, { "hen guang", "很广" }, { "hen gui", "很贵" },
			{ "hen hao", "很好" }, { "hen hao de", "很好的" }, { "hen hao kan", "很好看" }, { "hen hao ting", "很好听" }, { "hen hei", "很黑" }, { "hen hen", "恨恨" },
			{ "hen hen", "狠狠" }, { "hen hong", "很红" }, { "hen hou", "很厚" }, { "hen huai", "很坏" }, { "hen hui", "很会" }, { "hen huo", "很火" }, { "hen ji", "很急" },
			{ "hen ji", "痕迹" }, { "hen jian dan", "很简单" }, { "hen jin", "很紧" }, { "hen jin", "很近" }, { "hen jiu", "很久" }, { "hen jiu le", "很久了" },
			{ "hen jiu mei you", "很久没有" }, { "hen jiu yi qian", "很久以前" }, { "hen kai xin", "很开心" }, { "hen ke ai", "很可爱" }, { "hen ke neng", "很可能" },
			{ "hen ku", "很苦" }, { "hen ku", "很酷" }, { "hen kuai", "很快" } };
};
