package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN51 {
	public static String[][] pl = { { "xia xia", "下下" }, { "xia xia", "下辖" }, { "xia xian", "下线" }, { "xia xian", "下限" }, { "xia xiang", "下乡" },
			{ "xia xiang", "遐想" }, { "xia xiao", "狭小" }, { "xia xin", "夏新" }, { "xia xing", "下行" }, { "xia xing qi", "下星期" }, { "xia xue", "下雪" },
			{ "xia xun", "下旬" }, { "xia ye", "夏夜" }, { "xia yi", "下一" }, { "xia yi", "下移" }, { "xia yi", "侠义" }, { "xia yi", "狭义" }, { "xia yi bu", "下一步" },
			{ "xia yi ci", "下一次" }, { "xia yi dai", "下一代" }, { "xia yi pian", "下一篇" }, { "xia yi shi", "下意识" }, { "xia yi tiao", "吓一跳" },
			{ "xia yi ye", "下一页" }, { "xia yi zhan", "下一站" }, { "xia you", "下游" }, { "xia yu", "下雨" }, { "xia yu", "夏雨" }, { "xia yu le", "下雨了" },
			{ "xia yu tian", "下雨天" }, { "xia yue", "下月" }, { "xia zai", "下载" }, { "xia zai an zhuang", "下载安装" }, { "xia zai di zhi", "下载地址" },
			{ "xia zai ruan jian", "下载软件" }, { "xia zai su du", "下载速度" }, { "xia zhai", "狭窄" }, { "xia zhe", "下着" }, { "xia zhe", "吓着" }, { "xia zhi", "下肢" },
			{ "xia zhi", "下至" }, { "xia zhou", "下周" }, { "xia zhou yi", "下周一" }, { "xia zhu", "下注" }, { "xia zi", "下子" }, { "xia zi", "瞎子" }, { "xian", "仙" },
			{ "xian", "仚" }, { "xian", "伭" }, { "xian", "佡" }, { "xian", "俔" }, { "xian", "僊" }, { "xian", "僩" }, { "xian", "僴" }, { "xian", "先" },
			{ "xian", "冼" }, { "xian", "县" }, { "xian", "咁" }, { "xian", "咸" }, { "xian", "啣" }, { "xian", "嘕" }, { "xian", "埳" }, { "xian", "堿" },
			{ "xian", "壏" }, { "xian", "奾" }, { "xian", "姭" }, { "xian", "姺" }, { "xian", "娊" }, { "xian", "娴" }, { "xian", "娹" }, { "xian", "嫌" },
			{ "xian", "嫺" }, { "xian", "嫻" }, { "xian", "孅" }, { "xian", "宪" }, { "xian", "尟" }, { "xian", "尠" }, { "xian", "屳" }, { "xian", "岘" },
			{ "xian", "峴" }, { "xian", "幰" }, { "xian", "廯" }, { "xian", "弦" }, { "xian", "彡" }, { "xian", "忺" }, { "xian", "慳" }, { "xian", "憪" },
			{ "xian", "憲" }, { "xian", "憸" }, { "xian", "掀" }, { "xian", "搟" }, { "xian", "撊" }, { "xian", "攇" }, { "xian", "攕" }, { "xian", "显" },
			{ "xian", "晛" }, { "xian", "暹" }, { "xian", "杴" }, { "xian", "槏" }, { "xian", "櫶" }, { "xian", "毨" }, { "xian", "氙" }, { "xian", "洗" },
			{ "xian", "涀" }, { "xian", "涎" }, { "xian", "溓" }, { "xian", "澖" }, { "xian", "瀗" }, { "xian", "灦" }, { "xian", "烍" }, { "xian", "燹" },
			{ "xian", "猃" }, { "xian", "献" }, { "xian", "獫" }, { "xian", "獮" }, { "xian", "獻" }, { "xian", "玁" }, { "xian", "现" }, { "xian", "珗" },
			{ "xian", "現" }, { "xian", "痫" }, { "xian", "癇" }, { "xian", "癎" }, { "xian", "盷" }, { "xian", "県" }, { "xian", "睍" }, { "xian", "祆" },
			{ "xian", "禒" }, { "xian", "禰" }, { "xian", "秈" }, { "xian", "筅" }, { "xian", "筧" }, { "xian", "籼" }, { "xian", "粯" }, { "xian", "糮" },
			{ "xian", "絃" }, { "xian", "綅" }, { "xian", "綫" }, { "xian", "線" }, { "xian", "縣" }, { "xian", "繊" }, { "xian", "纎" }, { "xian", "纖" },
			{ "xian", "纤" }, { "xian", "线" }, { "xian", "羡" }, { "xian", "羨" }, { "xian", "羬" }, { "xian", "胘" }, { "xian", "腺" }, { "xian", "舷" },
			{ "xian", "苋" }, { "xian", "莧" }, { "xian", "莶" }, { "xian", "藓" }, { "xian", "蘚" }, { "xian", "蘞" }, { "xian", "蚬" }, { "xian", "蚿" },
			{ "xian", "蛝" }, { "xian", "蜆" }, { "xian", "衔" }, { "xian", "褼" }, { "xian", "襳" }, { "xian", "见" }, { "xian", "誸" }, { "xian", "諴" },
			{ "xian", "譀" }, { "xian", "譣" }, { "xian", "豏" }, { "xian", "賢" }, { "xian", "贒" }, { "xian", "贤" }, { "xian", "赻" }, { "xian", "跣" },
			{ "xian", "跹" }, { "xian", "躚" }, { "xian", "酰" }, { "xian", "釤" }, { "xian", "銛" }, { "xian", "銜" }, { "xian", "鋧" }, { "xian", "錎" },
			{ "xian", "鍌" }, { "xian", "鏾" }, { "xian", "铣" }, { "xian", "锨" }, { "xian", "閑" }, { "xian", "閒" }, { "xian", "闞" }, { "xian", "闲" },
			{ "xian", "限" }, { "xian", "陥" }, { "xian", "险" }, { "xian", "陷" }, { "xian", "険" }, { "xian", "險" }, { "xian", "霰" }, { "xian", "韅" },
			{ "xian", "韱" }, { "xian", "顈" }, { "xian", "顕" }, { "xian", "顯" }, { "xian", "餡" }, { "xian", "馅" }, { "xian", "馦" }, { "xian", "鮮" },
			{ "xian", "鰔" }, { "xian", "鲜" }, { "xian", "鶱" }, { "xian", "鷳" }, { "xian", "鷴" }, { "xian", "鹇" }, { "xian", "鹹" }, { "xian", "鼸" },
			{ "xian ai", "腺癌" }, { "xian ai xin", "献爱心" }, { "xian ba", "先把" }, { "xian bai", "显摆" }, { "xian bei", "先辈" }, { "xian bie", "先别" },
			{ "xian bing", "馅饼" }, { "xian cai", "咸菜" }, { "xian cai", "线材" }, { "xian chang", "献唱" }, { "xian chang", "现场" }, { "xian chang hui", "现场会" },
			{ "xian chang zhi bo", "现场直播" }, { "xian cheng", "县城" }, { "xian cheng", "现成" }, { "xian cheng", "线程" }, { "xian chi", "先吃" },
			{ "xian chong", "线虫" }, { "xian chu", "显出" }, { "xian chu", "献出" }, { "xian chu", "现出" }, { "xian cong", "先从" }, { "xian cun", "显存" },
			{ "xian cun", "现存" }, { "xian da", "先打" }, { "xian dai", "现代" }, { "xian dai du shi", "现代都市" }, { "xian dai hua", "现代化" },
			{ "xian dai ke ji", "现代科技" }, { "xian dai ke xue", "现代科学" }, { "xian dai nong ye", "现代农业" }, { "xian dai qi ye", "现代企业" },
			{ "xian dai ren", "现代人" }, { "xian dai she hui", "现代社会" }, { "xian dai sheng huo", "现代生活" }, { "xian dai wen ming", "现代文明" },
			{ "xian dai wu liu", "现代物流" }, { "xian dai xing", "现代性" }, { "xian dai yi xue", "现代医学" }, { "xian dao", "先到" }, { "xian dao", "先导" },
			{ "xian de", "先得" }, { "xian de", "显得" }, { "xian ding", "限定" }, { "xian du", "限度" }, { "xian duan", "线段" }, { "xian e", "限额" },
			{ "xian e", "险恶" }, { "xian er yi jian", "显而易见" }, { "xian fa", "先发" }, { "xian fa", "宪法" }, { "xian fan", "嫌犯" }, { "xian fang", "现房" },
			{ "xian feng", "先锋" }, { "xian fu", "先富" }, { "xian gei", "先给" }, { "xian gei", "献给" }, { "xian gong an ju", "县公安局" }, { "xian guan", "县官" },
			{ "xian guang", "闲逛" }, { "xian guo", "鲜果" }, { "xian hai", "陷害" }, { "xian he", "先河" }, { "xian he", "显赫" }, { "xian hong", "鲜红" },
			{ "xian hou", "先后" }, { "xian hua", "献花" }, { "xian hua", "闲话" }, { "xian hua", "鲜花" }, { "xian hui", "贤惠" }, { "xian huo", "现货" },
			{ "xian huo", "鲜活" }, { "xian huo shi chang", "现货市场" }, { "xian ji", "先机" }, { "xian ji", "县级" }, { "xian ji shi", "县级市" },
			{ "xian ji yi shang", "县级以上" }, { "xian jia", "现价" }, { "xian jia", "限价" }, { "xian jia fang", "限价房" }, { "xian jian", "仙剑" },
			{ "xian jiang", "先将" }, { "xian jiang", "现将" }, { "xian jie", "衔接" }, { "xian jie duan", "现阶段" }, { "xian jin", "先进" }, { "xian jin", "现今" },
			{ "xian jin", "现金" }, { "xian jin", "陷进" }, { "xian jin dan wei", "先进单位" }, { "xian jin dian xing", "先进典型" }, { "xian jin ge ren", "先进个人" },
			{ "xian jin ji shu", "先进技术" }, { "xian jin ji ti", "先进集体" }, { "xian jin jing yan", "先进经验" }, { "xian jin liu", "现金流" },
			{ "xian jin liu liang", "现金流量" }, { "xian jin shi ji", "先进事迹" }, { "xian jin wen hua", "先进文化" }, { "xian jin xing", "先进性" }, { "xian jing", "仙境" },
			{ "xian jing", "陷阱" }, { "xian jiu", "现就" }, { "xian ju", "县局" }, { "xian jue tiao jian", "先决条件" }, { "xian ka", "显卡" },
			{ "xian ka qu dong", "显卡驱动" }, { "xian kai", "掀开" }, { "xian kan", "先看" }, { "xian kong", "线控" }, { "xian lai", "先来" }, { "xian lan", "线缆" },
			{ "xian li", "先例" }, { "xian li", "县里" }, { "xian li", "献礼" }, { "xian liang", "限量" }, { "xian liang", "鲜亮" }, { "xian liang ban", "限量版" },
			{ "xian liao", "闲聊" }, { "xian lie", "先烈" }, { "xian ling", "县令" }, { "xian lu", "显露" }, { "xian lu", "线路" }, { "xian lu ban", "线路板" },
			{ "xian mai", "先买" }, { "xian mei", "鲜美" }, { "xian min", "先民" }, { "xian ming", "鲜明" }, { "xian mu", "羡慕" }, { "xian nai", "鲜奶" },
			{ "xian nen", "鲜嫩" }, { "xian nv", "仙女" }, { "xian qi", "先期" }, { "xian qi", "嫌弃" }, { "xian qi", "掀起" }, { "xian qi", "限期" },
			{ "xian qi liang mu", "贤妻良母" }, { "xian qian", "先前" }, { "xian qian", "闲钱" }, { "xian qin", "先秦" }, { "xian qing", "闲情" }, { "xian qing", "险情" },
			{ "xian qu", "先去" }, { "xian qu", "先取" }, { "xian qu", "先驱" }, { "xian qu", "县区" }, { "xian quan", "线圈" }, { "xian ran", "显然" },
			{ "xian rang", "先让" }, { "xian ren", "仙人" }, { "xian ren", "先人" }, { "xian ren", "现任" }, { "xian ren", "闲人" }, { "xian ren zhang", "仙人掌" },
			{ "xian ru", "陷入" }, { "xian ru jin", "现如今" }, { "xian ru wei zhu", "先入为主" }, { "xian san", "闲散" }, { "xian shang", "献上" }, { "xian shang", "线上" },
			{ "xian shen", "献身" }, { "xian shen", "现身" }, { "xian sheng", "先声" }, { "xian sheng", "先生" }, { "xian sheng", "险胜" }, { "xian shi", "先是" },
			{ "xian shi", "县市" }, { "xian shi", "显示" }, { "xian shi", "现世" }, { "xian shi", "现实" }, { "xian shi", "现时" }, { "xian shi", "闲时" },
			{ "xian shi", "闲适" }, { "xian shi", "限时" }, { "xian shi chu", "显示出" }, { "xian shi chu lai", "显示出来" }, { "xian shi ka", "显示卡" },
			{ "xian shi ping", "显示屏" }, { "xian shi qi", "显示器" }, { "xian shi qu", "县市区" }, { "xian shi sheng huo", "现实生活" }, { "xian shi xiao guo", "显示效果" },
			{ "xian shi yi yi", "现实意义" }, { "xian shi zhu yi", "现实主义" }, { "xian shu", "娴熟" }, { "xian shuo", "先说" }, { "xian su", "限速" },
			{ "xian suo", "线索" }, { "xian tan", "闲谈" }, { "xian ti", "纤体" }, { "xian ti", "腺体" }, { "xian tian", "先天" }, { "xian tian xing", "先天性" },
			{ "xian tiao", "线条" }, { "xian tu", "线图" }, { "xian wei", "县委" }, { "xian wei", "显微" }, { "xian wei", "现为" }, { "xian wei", "纤维" },
			{ "xian wei jing", "显微镜" }, { "xian wei ren zhi", "鲜为人知" }, { "xian wei shu ji", "县委书记" }, { "xian wei su", "纤维素" }, { "xian wen", "先问" },
			{ "xian xi", "纤细" }, { "xian xia", "线下" }, { "xian xia", "闲暇" }, { "xian xian", "先贤" }, { "xian xian", "显现" }, { "xian xiang", "县乡" },
			{ "xian xiang", "现象" }, { "xian xie", "先写" }, { "xian xie", "险些" }, { "xian xin", "闲心" }, { "xian xing", "先行" }, { "xian xing", "显性" },
			{ "xian xing", "现行" }, { "xian xing", "线性" }, { "xian xing zhe", "先行者" }, { "xian xue", "献血" }, { "xian xue", "鲜血" }, { "xian yan", "显眼" },
			{ "xian yan", "鲜艳" }, { "xian yang", "咸阳" }, { "xian yao", "先要" }, { "xian yi", "嫌疑" }, { "xian yi", "现已" }, { "xian yi", "现役" },
			{ "xian yi ren", "嫌疑人" }, { "xian yong", "先用" }, { "xian you", "先有" }, { "xian you", "先由" }, { "xian you", "现有" }, { "xian you", "鲜有" },
			{ "xian yu", "先于" }, { "xian yu", "县域" }, { "xian yu", "咸鱼" }, { "xian yu", "限于" }, { "xian yu", "陷于" }, { "xian yu jing ji", "县域经济" },
			{ "xian yue", "弦乐" }, { "xian za", "闲杂" }, { "xian zai", "先在" }, { "xian zai", "现在" }, { "xian zai kai shi", "现在开始" },
			{ "xian zai liu xing", "现在流行" }, { "xian zai you", "现在又" }, { "xian zhang", "县长" }, { "xian zhao", "先兆" }, { "xian zhao", "先找" },
			{ "xian zhe", "显着" }, { "xian zhe", "闲着" }, { "xian zheng", "宪政" }, { "xian zheng", "现正" }, { "xian zheng fu", "县政府" }, { "xian zhi", "先知" },
			{ "xian zhi", "闲置" }, { "xian zhi", "限制" }, { "xian zhi xing", "限制性" }, { "xian zhong", "险种" }, { "xian zhu", "显著" }, { "xian zhuang", "现状" },
			{ "xian zhuang ji", "现状及" }, { "xian zi", "仙子" }, { "xian zou", "先走" }, { "xian zu", "先祖" }, { "xian zuo", "先做" }, { "xiang", "乡" },
			{ "xiang", "享" }, { "xiang", "像" }, { "xiang", "儴" }, { "xiang", "厢" }, { "xiang", "向" }, { "xiang", "响" }, { "xiang", "啌" }, { "xiang", "嚮" },
			{ "xiang", "姠" }, { "xiang", "巷" }, { "xiang", "庠" }, { "xiang", "廂" }, { "xiang", "忀" }, { "xiang", "想" }, { "xiang", "晑" }, { "xiang", "曏" },
			{ "xiang", "橡" }, { "xiang", "欀" }, { "xiang", "湘" }, { "xiang", "珦" }, { "xiang", "瓖" }, { "xiang", "瓨" }, { "xiang", "相" }, { "xiang", "祥" },
			{ "xiang", "箱" }, { "xiang", "緗" }, { "xiang", "纕" }, { "xiang", "缃" }, { "xiang", "缿" }, { "xiang", "翔" }, { "xiang", "膷" }, { "xiang", "芗" },
			{ "xiang", "萫" }, { "xiang", "葙" }, { "xiang", "薌" }, { "xiang", "蟓" }, { "xiang", "蠁" }, { "xiang", "衖" }, { "xiang", "襄" }, { "xiang", "襐" },
			{ "xiang", "詳" }, { "xiang", "详" }, { "xiang", "象" }, { "xiang", "郷" }, { "xiang", "鄉" }, { "xiang", "鄕" }, { "xiang", "銗" }, { "xiang", "鐌" },
			{ "xiang", "鑲" }, { "xiang", "镶" }, { "xiang", "閧" }, { "xiang", "闀" }, { "xiang", "降" }, { "xiang", "響" }, { "xiang", "項" }, { "xiang", "项" },
			{ "xiang", "飨" }, { "xiang", "餉" }, { "xiang", "饗" }, { "xiang", "饟" }, { "xiang", "饷" }, { "xiang", "香" }, { "xiang", "驤" }, { "xiang", "骧" },
			{ "xiang", "鬨" }, { "xiang", "鯗" }, { "xiang", "鱌" }, { "xiang", "鱶" }, { "xiang", "鲞" }, { "xiang a", "想啊" }, { "xiang ai", "相爱" },
			{ "xiang ba", "想把" }, { "xiang ban", "相伴" }, { "xiang ban fa", "想办法" }, { "xiang bao", "箱包" }, { "xiang bei", "向北" }, { "xiang bei", "相悖" },
			{ "xiang bi", "想必" }, { "xiang bi", "相比" }, { "xiang bi zhi xia", "相比之下" }, { "xiang bin", "香槟" }, { "xiang bu dao", "想不到" },
			{ "xiang bu kai", "想不开" }, { "xiang bu tong", "想不通" }, { "xiang cai", "湘菜" }, { "xiang cai", "香菜" }, { "xiang cao", "香草" }, { "xiang ce", "相册" },
			{ "xiang cha", "相差" }, { "xiang cha wu ji", "相差无几" }, { "xiang chang", "香肠" }, { "xiang che", "响彻" }, { "xiang chen", "相称" },
			{ "xiang cheng", "相称" }, { "xiang cheng wei", "想成为" }, { "xiang chi", "想吃" }, { "xiang chou", "乡愁" }, { "xiang chu", "想出" }, { "xiang chu", "相处" },
			{ "xiang chuan", "相传" }, { "xiang cong", "想从" }, { "xiang cun", "乡村" }, { "xiang da", "想打" }, { "xiang dai", "相待" }, { "xiang dang", "想当" },
			{ "xiang dang", "相当" }, { "xiang dang chu", "想当初" }, { "xiang dang dang", "响当当" }, { "xiang dang nian", "想当年" }, { "xiang dang ran", "想当然" },
			{ "xiang dao", "向导" }, { "xiang dao", "想到" }, { "xiang de", "想得" }, { "xiang de dao", "想得到" }, { "xiang de yi zhang", "相得益彰" },
			{ "xiang deng", "相等" }, { "xiang dong", "向东" }, { "xiang dui", "相对" }, { "xiang dui er yan", "相对而言" }, { "xiang dui lai shuo", "相对来说" },
			{ "xiang dui lun", "相对论" }, { "xiang dui ren", "相对人" }, { "xiang dui shi du", "相对湿度" }, { "xiang duo", "想多" }, { "xiang fa", "想法" },
			{ "xiang fan", "相反" }, { "xiang fan", "襄樊" }, { "xiang fang", "相仿" }, { "xiang fang she fa", "想方设法" }, { "xiang fei", "想飞" },
			{ "xiang feng", "相逢" }, { "xiang fu", "享福" }, { "xiang fu", "相符" }, { "xiang fu xiang cheng", "相辅相成" }, { "xiang gan", "想干" },
			{ "xiang gan", "相干" }, { "xiang gang", "香港" }, { "xiang gang da xue", "香港大学" }, { "xiang gang dian ying", "香港电影" },
			{ "xiang gang gu shi", "香港股市" }, { "xiang gang hui gui", "香港回归" }, { "xiang gang mei ti", "香港媒体" }, { "xiang gang ren", "香港人" },
			{ "xiang gang shang shi", "香港上市" }, { "xiang gang te qu", "香港特区" }, { "xiang gang zheng fu", "香港政府" }, { "xiang ge", "像个" }, { "xiang ge", "想个" },
			{ "xiang ge", "相隔" }, { "xiang ge", "象个" }, { "xiang ge li la", "香格里拉" }, { "xiang gei", "想给" }, { "xiang gen", "想跟" }, { "xiang gong", "相公" },
			{ "xiang gu", "香菇" }, { "xiang guan", "相关" }, { "xiang guan bao dao", "相关报道" }, { "xiang guan bu men", "相关部门" }, { "xiang guan chan pin", "相关产品" },
			{ "xiang guan fa lv", "相关法律" }, { "xiang guan gui ding", "相关规定" }, { "xiang guan lian jie", "相关链接" }, { "xiang guan nei rong", "相关内容" },
			{ "xiang guan qi ye", "相关企业" }, { "xiang guan shi yi", "相关事宜" }, { "xiang guan shou xu", "相关手续" }, { "xiang guan shu ju", "相关数据" },
			{ "xiang guan wen jian", "相关文件" }, { "xiang guan wen zhang", "相关文章" }, { "xiang guan xin wen", "相关新闻" }, { "xiang guan xin xi", "相关信息" },
			{ "xiang guan xing", "相关性" }, { "xiang guan zheng ce", "相关政策" }, { "xiang guan zhi shi", "相关知识" }, { "xiang guan zhuan ye", "相关专业" },
			{ "xiang guan zi liao", "相关资料" }, { "xiang guo", "想过" }, { "xiang hao", "向好" }, { "xiang hao", "想好" }, { "xiang hao", "相好" }, { "xiang he", "祥和" },
			{ "xiang hou", "向后" }, { "xiang hu", "相互" }, { "xiang hu guan xi", "相互关系" }, { "xiang hu jian", "相互间" }, { "xiang hu zhi jian", "相互之间" },
			{ "xiang hu zuo yong", "相互作用" }, { "xiang hua", "香花" }, { "xiang hui", "想回" }, { "xiang hui", "相会" }, { "xiang huo", "香火" }, { "xiang ji", "相机" },
			{ "xiang ji", "相继" }, { "xiang jia", "想家" }, { "xiang jia", "相加" }, { "xiang jian", "乡间" }, { "xiang jian", "想见" }, { "xiang jian", "相见" },
			{ "xiang jian", "相间" }, { "xiang jian", "详见" }, { "xiang jiang", "湘江" }, { "xiang jiang", "香江" }, { "xiang jiao", "橡胶" }, { "xiang jiao", "相交" },
			{ "xiang jiao", "相较" }, { "xiang jiao", "香蕉" }, { "xiang jie", "想借" }, { "xiang jie", "相接" }, { "xiang jie", "详解" }, { "xiang jie he de", "相结合的" },
			{ "xiang jin", "想尽" }, { "xiang jin", "想进" }, { "xiang jin", "相近" }, { "xiang jin", "详尽" }, { "xiang jing", "香精" }, { "xiang ju", "相聚" },
			{ "xiang ju", "相距" }, { "xiang jun", "湘军" }, { "xiang kai", "想开" }, { "xiang kan", "想看" }, { "xiang kan kan", "想看看" }, { "xiang ke", "相克" },
			{ "xiang ku", "想哭" }, { "xiang kuang", "相框" }, { "xiang la", "香辣" }, { "xiang lai", "向来" }, { "xiang lai", "想来" },
			{ "xiang lai xiang qu", "想来想去" }, { "xiang le", "享乐" }, { "xiang le", "响了" }, { "xiang le xiang", "想了想" }, { "xiang li", "乡里" },
			{ "xiang lian", "相恋" }, { "xiang lian", "相连" }, { "xiang lian", "项链" }, { "xiang liang", "向量" }, { "xiang liang", "响亮" }, { "xiang liao", "香料" },
			{ "xiang liao jie", "想了解" }, { "xiang lin", "相邻" }, { "xiang lu", "香炉" }, { "xiang mai", "想买" }, { "xiang mao", "相貌" }, { "xiang mu", "项目" },
			{ "xiang mu bu", "项目部" }, { "xiang mu guan li", "项目管理" }, { "xiang mu jian she", "项目建设" }, { "xiang mu jing li", "项目经理" },
			{ "xiang mu kai fa", "项目开发" }, { "xiang mu shi shi", "项目实施" }, { "xiang mu tou zi", "项目投资" }, { "xiang mu zu", "项目组" }, { "xiang nan", "向南" },
			{ "xiang nei", "向内" }, { "xiang nei", "箱内" }, { "xiang ni", "像你" }, { "xiang ni", "向你" }, { "xiang ni", "想你" }, { "xiang ni", "象你" },
			{ "xiang ni le", "想你了" }, { "xiang nian", "想念" }, { "xiang nin", "向您" }, { "xiang nong", "香浓" }, { "xiang pei", "相配" }, { "xiang pen pen", "香喷喷" },
			{ "xiang pi", "橡皮" }, { "xiang pian", "相片" }, { "xiang qi", "向其" }, { "xiang qi", "响起" }, { "xiang qi", "想起" }, { "xiang qi", "象棋" },
			{ "xiang qi", "香气" }, { "xiang qi lai", "想起来" }, { "xiang qian", "向前" }, { "xiang qian", "镶嵌" }, { "xiang qin", "乡亲" }, { "xiang qin", "相亲" },
			{ "xiang qing", "想请" }, { "xiang qing", "详情" }, { "xiang qing qing", "详情请" }, { "xiang qu", "想去" }, { "xiang qu shen yuan", "相去甚远" },
			{ "xiang rang", "想让" }, { "xiang ri kui", "向日葵" }, { "xiang rong", "相容" }, { "xiang ru fei fei", "想入非非" }, { "xiang ru yi mo", "相濡以沫" },
			{ "xiang shan", "象山" }, { "xiang shan", "香山" }, { "xiang shang", "向上" }, { "xiang shen me", "想什么" }, { "xiang sheng", "响声" },
			{ "xiang sheng", "相声" }, { "xiang shi", "像是" }, { "xiang shi", "相视" }, { "xiang shi", "相识" }, { "xiang shi", "翔实" }, { "xiang shi", "象是" },
			{ "xiang shou", "享受" }, { "xiang shou", "相守" }, { "xiang shou sheng huo", "享受生活" }, { "xiang shu", "橡树" }, { "xiang shu", "详述" },
			{ "xiang shui", "想睡" }, { "xiang shui", "香水" }, { "xiang shuo", "想说" }, { "xiang si", "想死" }, { "xiang si", "相似" }, { "xiang si", "相思" },
			{ "xiang si xing", "相似性" }, { "xiang si zhi chu", "相似之处" }, { "xiang su", "像素" }, { "xiang su", "象素" }, { "xiang sui", "相随" },
			{ "xiang ta", "像他" }, { "xiang ta", "像她" }, { "xiang ta", "向他" }, { "xiang ta", "向她" }, { "xiang tai duo", "想太多" }, { "xiang tan", "湘潭" },
			{ "xiang tan", "详谈" }, { "xiang ti", "箱体" }, { "xiang ti bing lun", "相提并论" }, { "xiang tian", "香甜" }, { "xiang ting", "想听" },
			{ "xiang tong", "想通" }, { "xiang tong", "相同" }, { "xiang tong", "相通" }, { "xiang tu", "乡土" }, { "xiang tu", "想吐" }, { "xiang wai", "向外" },
			{ "xiang wan", "想玩" }, { "xiang wang", "向往" }, { "xiang wang", "相望" }, { "xiang wei", "相位" }, { "xiang wei", "香味" }, { "xiang wen", "想问" },
			{ "xiang wo", "像我" }, { "xiang wo", "向我" }, { "xiang wo", "象我" }, { "xiang xi", "向西" }, { "xiang xi", "湘西" }, { "xiang xi", "详细" },
			{ "xiang xi jie shao", "详细介绍" }, { "xiang xi nei rong", "详细内容" }, { "xiang xi qing kuang", "详细情况" }, { "xiang xi shuo ming", "详细说明" },
			{ "xiang xi xin xi", "详细信息" }, { "xiang xi zi liao", "详细资料" }, { "xiang xia", "乡下" }, { "xiang xia", "向下" }, { "xiang xia", "项下" },
			{ "xiang xia ren", "乡下人" }, { "xiang xiang", "想像" }, { "xiang xiang", "想想" }, { "xiang xiang", "想象" }, { "xiang xiang", "相像" },
			{ "xiang xiang", "相向" }, { "xiang xiang", "香香" }, { "xiang xiang li", "想像力" }, { "xiang xiang li", "想象力" }, { "xiang xiao", "想笑" },
			{ "xiang xie", "想写" }, { "xiang xin", "相信" }, { "xiang xin ai qing", "相信爱情" }, { "xiang xin zi ji", "相信自己" }, { "xiang xue", "想学" },
			{ "xiang ya", "象牙" }, { "xiang yan", "香烟" }, { "xiang yan", "香艳" }, { "xiang yang", "像样" }, { "xiang yang", "向阳" }, { "xiang yang", "襄阳" },
			{ "xiang yao", "想要" }, { "xiang yao de", "想要的" }, { "xiang yi", "相依" }, { "xiang yi", "相宜" }, { "xiang yi wei ming", "相依为命" },
			{ "xiang yi xiang", "想一想" }, { "xiang ying", "响应" }, { "xiang ying", "相应" }, { "xiang ying shi jian", "响应时间" }, { "xiang yong", "享用" },
			{ "xiang yong", "想用" }, { "xiang yong", "相拥" }, { "xiang yong you", "想拥有" }, { "xiang you", "享有" }, { "xiang you", "向右" }, { "xiang you", "香油" },
			{ "xiang yu", "享誉" }, { "xiang yu", "相遇" }, { "xiang yu", "项羽" }, { "xiang yue", "相约" }, { "xiang yun", "祥云" }, { "xiang zai", "想再" },
			{ "xiang zai", "想在" }, { "xiang zao", "香皂" }, { "xiang zhang", "乡长" }, { "xiang zhao", "想找" }, { "xiang zhao ge", "想找个" }, { "xiang zhe", "向着" },
			{ "xiang zhe", "想着" }, { "xiang zhen", "乡镇" }, { "xiang zhen qi ye", "乡镇企业" }, { "xiang zheng", "象征" }, { "xiang zheng fu", "乡政府" },
			{ "xiang zheng xing", "象征性" }, { "xiang zheng yi yi", "象征意义" }, { "xiang zhi", "相知" }, { "xiang zhi dao", "想知道" }, { "xiang zhong", "相中" },
			{ "xiang zhu", "相助" }, { "xiang zhuang", "相撞" }, { "xiang zi", "巷子" }, { "xiang zi", "祥子" }, { "xiang zi", "箱子" }, { "xiang zi li", "箱子里" },
			{ "xiang zou", "想走" }, { "xiang zuo", "向左" }, { "xiang zuo", "想做" }, { "xiao", "傚" }, { "xiao", "削" }, { "xiao", "効" }, { "xiao", "呺" },
			{ "xiao", "咲" }, { "xiao", "哓" }, { "xiao", "哮" }, { "xiao", "啋" }, { "xiao", "啸" }, { "xiao", "嗃" }, { "xiao", "嘐" }, { "xiao", "嘯" },
			{ "xiao", "嘵" }, { "xiao", "嚣" }, { "xiao", "囂" }, { "xiao", "孝" }, { "xiao", "宵" }, { "xiao", "小" }, { "xiao", "崤" }, { "xiao", "庨" },
			{ "xiao", "恔" }, { "xiao", "恷" }, { "xiao", "憢" }, { "xiao", "揱" }, { "xiao", "效" }, { "xiao", "斅" }, { "xiao", "晓" }, { "xiao", "暁" },
			{ "xiao", "曉" }, { "xiao", "枭" }, { "xiao", "枵" }, { "xiao", "校" }, { "xiao", "梟" }, { "xiao", "橚" }, { "xiao", "歊" }, { "xiao", "毊" },
			{ "xiao", "洨" }, { "xiao", "消" }, { "xiao", "涍" }, { "xiao", "淆" }, { "xiao", "漻" }, { "xiao", "潇" }, { "xiao", "潚" }, { "xiao", "瀟" },
			{ "xiao", "灱" }, { "xiao", "熽" }, { "xiao", "燆" }, { "xiao", "猇" }, { "xiao", "獢" }, { "xiao", "痚" }, { "xiao", "痟" }, { "xiao", "皛" },
			{ "xiao", "睄" }, { "xiao", "硝" }, { "xiao", "穘" }, { "xiao", "窙" }, { "xiao", "笑" }, { "xiao", "笹" }, { "xiao", "筱" }, { "xiao", "箫" },
			{ "xiao", "箾" }, { "xiao", "篠" }, { "xiao", "簫" }, { "xiao", "綃" }, { "xiao", "縿" }, { "xiao", "绡" }, { "xiao", "翛" }, { "xiao", "肖" },
			{ "xiao", "膮" }, { "xiao", "莦" }, { "xiao", "萧" }, { "xiao", "萷" }, { "xiao", "蕭" }, { "xiao", "薂" }, { "xiao", "藃" }, { "xiao", "虈" },
			{ "xiao", "虓" }, { "xiao", "蛸" }, { "xiao", "蟂" }, { "xiao", "蠨" }, { "xiao", "詨" }, { "xiao", "謏" }, { "xiao", "謞" }, { "xiao", "謼" },
			{ "xiao", "譊" }, { "xiao", "踃" }, { "xiao", "轇" }, { "xiao", "逍" }, { "xiao", "郩" }, { "xiao", "銷" }, { "xiao", "销" }, { "xiao", "霄" },
			{ "xiao", "驍" }, { "xiao", "骁" }, { "xiao", "骹" }, { "xiao", "髇" }, { "xiao", "髐" }, { "xiao", "魈" }, { "xiao", "鴞" }, { "xiao", "鷍" } };
};
