package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN59 {
	public static String[][] pl = { { "yu er", "育儿" }, { "yu er", "鱼儿" }, { "yu fa", "愈发" }, { "yu fa", "语法" }, { "yu fang", "预防" },
			{ "yu fang cuo shi", "预防措施" }, { "yu fei", "与非" }, { "yu fen", "鱼粉" }, { "yu fou", "与否" }, { "yu fu", "渔夫" }, { "yu fu", "迂腐" }, { "yu fu", "预付" },
			{ "yu fu fei", "预付费" }, { "yu fu kuan", "预付款" }, { "yu gai", "与该" }, { "yu gan", "语感" }, { "yu gan", "预感" }, { "yu gang", "浴缸" },
			{ "yu gang", "渔港" }, { "yu gang", "鱼缸" }, { "yu gao", "预告" }, { "yu gao pian", "预告片" }, { "yu ge", "余个" }, { "yu gou", "预购" }, { "yu gu", "预估" },
			{ "yu guang", "余光" }, { "yu guo", "雨果" }, { "yu hai", "遇害" }, { "yu han", "御寒" }, { "yu hang", "余杭" }, { "yu hang", "宇航" },
			{ "yu hang yuan", "宇航员" }, { "yu he", "愈合" }, { "yu hou", "雨后" }, { "yu hou", "预后" }, { "yu hou chun sun", "雨后春笋" }, { "yu hua", "余华" },
			{ "yu huan", "玉环" }, { "yu hui", "与会" }, { "yu hui", "迂回" }, { "yu hui zhe", "与会者" }, { "yu huo", "欲火" }, { "yu ji", "淤积" }, { "yu ji", "雨季" },
			{ "yu ji", "预计" }, { "yu jia", "余家" }, { "yu jia", "愈加" }, { "yu jia", "瑜伽" }, { "yu jia", "瑜珈" }, { "yu jian", "遇见" }, { "yu jian", "预见" },
			{ "yu jian ni", "遇见你" }, { "yu jie", "御姐" }, { "yu jin", "浴巾" }, { "yu jin xiang", "郁金香" }, { "yu jing", "语境" }, { "yu jing", "预警" },
			{ "yu ju", "语句" }, { "yu jun", "与君" }, { "yu ke", "预科" }, { "yu ku wu lei", "欲哭无泪" }, { "yu kuai", "愉快" }, { "yu kuan", "余款" },
			{ "yu lai yu", "愈来愈" }, { "yu lan", "玉兰" }, { "yu lan", "预览" }, { "yu le", "娱乐" }, { "yu le ba gua", "娱乐八卦" }, { "yu le chang suo", "娱乐场所" },
			{ "yu le huo dong", "娱乐活动" }, { "yu le jie", "娱乐界" }, { "yu le jie mu", "娱乐节目" }, { "yu le quan", "娱乐圈" }, { "yu le xin wen", "娱乐新闻" },
			{ "yu le xing", "娱乐性" }, { "yu le ye", "娱乐业" }, { "yu lei", "鱼类" }, { "yu lei", "鱼雷" }, { "yu liang", "雨量" }, { "yu liao", "语聊" },
			{ "yu liao", "预料" }, { "yu lin", "榆林" }, { "yu lin", "玉林" }, { "yu lin", "雨林" }, { "yu ling fu nv", "育龄妇女" }, { "yu liu", "预留" },
			{ "yu long", "玉龙" }, { "yu long hun za", "鱼龙混杂" }, { "yu long xue shan", "玉龙雪山" }, { "yu lu", "语录" }, { "yu lu", "雨露" }, { "yu lun", "舆论" },
			{ "yu lun jian du", "舆论监督" }, { "yu mao", "羽毛" }, { "yu mao qiu", "羽毛球" }, { "yu mei", "愚昧" }, { "yu men", "郁闷" }, { "yu men de", "郁闷的" },
			{ "yu mi", "玉米" }, { "yu mi jia ge", "玉米价格" }, { "yu miao", "育苗" }, { "yu min", "于民" }, { "yu min", "愚民" }, { "yu min", "渔民" },
			{ "yu ming", "余名" }, { "yu ming", "域名" }, { "yu ming jiao yi", "域名交易" }, { "yu ming jie xi", "域名解析" }, { "yu ming zhu ce", "域名注册" },
			{ "yu mou", "预谋" }, { "yu nan", "遇难" }, { "yu nan zhe", "遇难者" }, { "yu ni", "与你" }, { "yu ni", "淤泥" }, { "yu nian", "余年" }, { "yu nin", "与您" },
			{ "yu nong", "愚弄" }, { "yu nv", "玉女" }, { "yu pei", "玉佩" }, { "yu pian", "鱼片" }, { "yu qi", "与其" }, { "yu qi", "于其" }, { "yu qi", "玉器" },
			{ "yu qi", "语气" }, { "yu qi", "逾期" }, { "yu qi", "预期" }, { "yu qi shuo", "与其说" }, { "yu qiu", "欲求" }, { "yu qiu yu", "余秋雨" }, { "yu quan", "玉泉" },
			{ "yu quan", "羽泉" }, { "yu re", "余热" }, { "yu re", "预热" }, { "yu ren", "与人" }, { "yu ren", "于人" }, { "yu ren", "余人" }, { "yu ren", "愚人" },
			{ "yu ren", "渔人" }, { "yu ren", "育人" }, { "yu ren jie", "愚人节" }, { "yu ri ju zeng", "与日俱增" }, { "yu rong", "羽绒" }, { "yu rong fu", "羽绒服" },
			{ "yu rou", "鱼肉" }, { "yu sai", "预赛" }, { "yu san", "雨伞" }, { "yu shang", "遇上" }, { "yu she", "预设" }, { "yu shen", "预审" }, { "yu sheng", "余生" },
			{ "yu sheng", "雨声" }, { "yu shi", "于世" }, { "yu shi", "于是" }, { "yu shi", "御史" }, { "yu shi", "浴室" }, { "yu shi", "玉石" }, { "yu shi", "遇事" },
			{ "yu shi", "预示" }, { "yu shi ge jue", "与世隔绝" }, { "yu shi hu", "于是乎" }, { "yu shi ju jin", "与时俱进" }, { "yu shou", "预售" }, { "yu shou", "预收" },
			{ "yu shu", "玉树" }, { "yu shui", "雨水" }, { "yu su", "语速" }, { "yu suan", "预算" }, { "yu suo", "寓所" }, { "yu ta", "与他" }, { "yu ta", "与她" },
			{ "yu tang", "鱼塘" }, { "yu tian", "雨天" }, { "yu tou", "芋头" }, { "yu tou", "鱼头" }, { "yu wan", "余万" }, { "yu wan", "鱼丸" }, { "yu wan yuan", "余万元" },
			{ "yu wang", "欲望" }, { "yu wei", "誉为" }, { "yu wen", "宇文" }, { "yu wen", "语文" }, { "yu wen jiao xue", "语文教学" }, { "yu wen ke", "语文课" },
			{ "yu wen lao shi", "语文老师" }, { "yu wo", "与我" }, { "yu wu lun ci", "语无伦次" }, { "yu xi", "玉溪" }, { "yu xi", "预习" }, { "yu xia", "余下" },
			{ "yu xia", "鱼虾" }, { "yu xian", "遇险" }, { "yu xian", "预先" }, { "yu xiang", "预想" }, { "yu xin", "于心" }, { "yu xuan sai", "预选赛" },
			{ "yu xue", "雨雪" }, { "yu yan", "寓言" }, { "yu yan", "浴盐" }, { "yu yan", "语言" }, { "yu yan", "雨燕" }, { "yu yan", "预演" }, { "yu yan", "预言" },
			{ "yu yan bao", "语言包" }, { "yu yan biao da", "语言表达" }, { "yu yan wen ming", "语言文明" }, { "yu yan wen zi", "语言文字" }, { "yu yan xue", "语言学" },
			{ "yu yan you zhi", "欲言又止" }, { "yu yan yu lie", "愈演愈烈" }, { "yu yao", "余姚" }, { "yu ye", "渔业" }, { "yu ye", "雨夜" }, { "yu yi", "予以" },
			{ "yu yi", "寓意" }, { "yu yi", "羽翼" }, { "yu yi", "羽衣" }, { "yu yi", "语义" }, { "yu yi", "雨衣" }, { "yu yin", "语音" }, { "yu ying li", "预应力" },
			{ "yu yong", "御用" }, { "yu you", "遇有" }, { "yu yu", "郁郁" }, { "yu yu cong cong", "郁郁葱葱" }, { "yu yuan", "余元" }, { "yu yue", "愉悦" },
			{ "yu yue", "逾越" }, { "yu yue", "预约" }, { "yu zeng", "预增" }, { "yu zhao", "玉照" }, { "yu zhao", "预兆" }, { "yu zhen", "余震" }, { "yu zhi", "与之" },
			{ "yu zhi", "欲知" }, { "yu zhi", "阈值" }, { "yu zhi", "预制" }, { "yu zhi", "预支" }, { "yu zhi", "预知" }, { "yu zhi", "预置" }, { "yu zhong", "余种" },
			{ "yu zhong", "狱中" }, { "yu zhong", "育种" }, { "yu zhong", "语种" }, { "yu zhong", "雨中" }, { "yu zhong bu tong", "与众不同" }, { "yu zhong qu", "渝中区" },
			{ "yu zhong xin chang", "语重心长" }, { "yu zhou", "宇宙" }, { "yu zhu", "预祝" }, { "yu zhuang", "预装" }, { "yuan", "元" }, { "yuan", "冤" },
			{ "yuan", "原" }, { "yuan", "员" }, { "yuan", "員" }, { "yuan", "噮" }, { "yuan", "园" }, { "yuan", "圆" }, { "yuan", "園" }, { "yuan", "圓" },
			{ "yuan", "圜" }, { "yuan", "垣" }, { "yuan", "垸" }, { "yuan", "塬" }, { "yuan", "夗" }, { "yuan", "妧" }, { "yuan", "妴" }, { "yuan", "媛" },
			{ "yuan", "媴" }, { "yuan", "嫄" }, { "yuan", "嬽" }, { "yuan", "寃" }, { "yuan", "怨" }, { "yuan", "悁" }, { "yuan", "惌" }, { "yuan", "愿" },
			{ "yuan", "掾" }, { "yuan", "援" }, { "yuan", "杬" }, { "yuan", "棩" }, { "yuan", "楥" }, { "yuan", "榞" }, { "yuan", "榬" }, { "yuan", "橼" },
			{ "yuan", "櫞" }, { "yuan", "沅" }, { "yuan", "淵" }, { "yuan", "渊" }, { "yuan", "渕" }, { "yuan", "湲" }, { "yuan", "源" }, { "yuan", "溒" },
			{ "yuan", "灁" }, { "yuan", "爰" }, { "yuan", "猿" }, { "yuan", "獂" }, { "yuan", "瑗" }, { "yuan", "眢" }, { "yuan", "禐" }, { "yuan", "笎" },
			{ "yuan", "箢" }, { "yuan", "緣" }, { "yuan", "縁" }, { "yuan", "缘" }, { "yuan", "羱" }, { "yuan", "肙" }, { "yuan", "芫" }, { "yuan", "苑" },
			{ "yuan", "葾" }, { "yuan", "蒝" }, { "yuan", "蒬" }, { "yuan", "薗" }, { "yuan", "薳" }, { "yuan", "蚖" }, { "yuan", "蜎" }, { "yuan", "蝝" },
			{ "yuan", "蝯" }, { "yuan", "螈" }, { "yuan", "袁" }, { "yuan", "裫" }, { "yuan", "裷" }, { "yuan", "褑" }, { "yuan", "謜" }, { "yuan", "輐" },
			{ "yuan", "轅" }, { "yuan", "辕" }, { "yuan", "远" }, { "yuan", "遠" }, { "yuan", "邍" }, { "yuan", "邧" }, { "yuan", "鋺" }, { "yuan", "鎱" },
			{ "yuan", "院" }, { "yuan", "願" }, { "yuan", "駌" }, { "yuan", "騵" }, { "yuan", "鳶" }, { "yuan", "鴛" }, { "yuan", "鵷" }, { "yuan", "鶢" },
			{ "yuan", "鸢" }, { "yuan", "鸳" }, { "yuan", "黿" }, { "yuan", "鼋" }, { "yuan", "鼘" }, { "yuan an", "冤案" }, { "yuan ban", "原版" },
			{ "yuan bao", "元宝" }, { "yuan ben", "原本" }, { "yuan bi", "远比" }, { "yuan bo", "渊博" }, { "yuan cai liao", "原材料" }, { "yuan chan", "原产" },
			{ "yuan chan di", "原产地" }, { "yuan chang", "原厂" }, { "yuan chang", "原唱" }, { "yuan chao", "元朝" }, { "yuan cheng", "远程" },
			{ "yuan cheng jiao yu", "远程教育" }, { "yuan cheng kong zhi", "远程控制" }, { "yuan cheng xie zhu", "远程协助" }, { "yuan cheng xu", "源程序" },
			{ "yuan chong huan", "袁崇焕" }, { "yuan chu", "远处" }, { "yuan chuang", "原创" }, { "yuan chuang wen zhang", "原创文章" }, { "yuan chuang xing", "原创性" },
			{ "yuan chuang zuo pin", "原创作品" }, { "yuan da", "远大" }, { "yuan dai", "元代" }, { "yuan dai ma", "源代码" }, { "yuan dan", "元旦" }, { "yuan dan", "原单" },
			{ "yuan dan wei", "原单位" }, { "yuan di", "原地" }, { "yuan di", "园地" }, { "yuan dian", "原点" }, { "yuan dian", "远点" }, { "yuan ding", "原定" },
			{ "yuan ding", "园丁" }, { "yuan dong", "远东" }, { "yuan dong li", "原动力" }, { "yuan duan", "远端" }, { "yuan fa xing", "原发性" }, { "yuan fang", "远方" },
			{ "yuan fang", "院方" }, { "yuan fei", "远非" }, { "yuan fen", "缘份" }, { "yuan fen", "缘分" }, { "yuan fu", "原副" }, { "yuan fu", "怨妇" },
			{ "yuan fu", "远赴" }, { "yuan fu yuan zhang", "院副院长" }, { "yuan gao", "原告" }, { "yuan gao", "原稿" }, { "yuan gong", "员工" }, { "yuan gu", "缘故" },
			{ "yuan gu", "远古" }, { "yuan hang", "远航" }, { "yuan he", "缘何" }, { "yuan hen", "怨恨" }, { "yuan hu", "圆弧" }, { "yuan hua", "原画" },
			{ "yuan hua", "原话" }, { "yuan hua", "圆滑" }, { "yuan hun", "冤魂" }, { "yuan ji", "原籍" }, { "yuan jia", "冤家" }, { "yuan jia", "原价" },
			{ "yuan jian", "元件" }, { "yuan jian", "原件" }, { "yuan jian", "援建" }, { "yuan jian", "远见" }, { "yuan jiao", "圆角" }, { "yuan jin", "远近" },
			{ "yuan jing", "愿景" }, { "yuan jing", "远景" }, { "yuan ju li", "远距离" }, { "yuan kan", "远看" }, { "yuan lai", "原来" }, { "yuan lai ru ci", "原来如此" },
			{ "yuan lao", "元老" }, { "yuan le", "圆了" }, { "yuan li", "原理" }, { "yuan li", "远离" }, { "yuan li", "院里" }, { "yuan li tu", "原理图" },
			{ "yuan liang", "原谅" }, { "yuan liao", "原料" }, { "yuan liao yao", "原料药" }, { "yuan lin", "园林" }, { "yuan lin lv hua", "园林绿化" },
			{ "yuan long ping", "袁隆平" }, { "yuan lu", "原路" }, { "yuan luo", "院落" }, { "yuan ma", "源码" }, { "yuan man", "圆满" },
			{ "yuan man cheng gong", "圆满成功" }, { "yuan man jie shu", "圆满结束" }, { "yuan man wan cheng", "圆满完成" }, { "yuan mao", "原貌" }, { "yuan meng", "圆梦" },
			{ "yuan ming", "原名" }, { "yuan ming yuan", "圆明园" }, { "yuan mu", "原木" }, { "yuan nei", "园内" }, { "yuan nei", "院内" }, { "yuan nian", "元年" },
			{ "yuan nian", "怨念" }, { "yuan pan", "圆盘" }, { "yuan pei", "原配" }, { "yuan qi", "元气" }, { "yuan qi", "怨气" }, { "yuan qi", "缘起" },
			{ "yuan qi", "远期" }, { "yuan qi jian", "元器件" }, { "yuan qian", "元钱" }, { "yuan qu", "园区" }, { "yuan qu", "远去" }, { "yuan quan", "圆圈" },
			{ "yuan quan", "源泉" }, { "yuan quan", "袁泉" }, { "yuan ren min bi", "元人民币" }, { "yuan run", "圆润" }, { "yuan se", "原色" }, { "yuan shan", "远山" },
			{ "yuan shao", "袁绍" }, { "yuan she", "远射" }, { "yuan shen", "元神" }, { "yuan shen", "原审" }, { "yuan sheng", "原声" }, { "yuan sheng", "原生" },
			{ "yuan sheng tai", "原生态" }, { "yuan shi", "原始" }, { "yuan shi", "原是" }, { "yuan shi", "院士" }, { "yuan shi kai", "袁世凯" },
			{ "yuan shi sen lin", "原始森林" }, { "yuan shou", "元首" }, { "yuan shou", "援手" }, { "yuan shu ju", "元数据" }, { "yuan shuai", "元帅" },
			{ "yuan shui", "原水" }, { "yuan su", "元素" }, { "yuan tian you ren", "怨天尤人" }, { "yuan tiao", "远眺" }, { "yuan tie", "原帖" }, { "yuan tong", "圆通" },
			{ "yuan tou", "源头" }, { "yuan tu", "原图" }, { "yuan wai", "员外" }, { "yuan wang", "冤枉" }, { "yuan wang", "愿望" }, { "yuan wang", "远望" },
			{ "yuan wei", "原为" }, { "yuan wei", "原位" }, { "yuan wei", "原味" }, { "yuan wei", "原委" }, { "yuan wei", "愿为" }, { "yuan wei", "远未" },
			{ "yuan wen", "原文" }, { "yuan wen jian", "源文件" }, { "yuan xi", "院系" }, { "yuan xian", "原先" }, { "yuan xian", "院线" }, { "yuan xiao", "元宵" },
			{ "yuan xiao", "远销" }, { "yuan xiao", "院校" }, { "yuan xiao jie", "元宵节" }, { "yuan xin", "圆心" }, { "yuan xing", "原型" }, { "yuan xing", "原形" },
			{ "yuan xing", "圆形" }, { "yuan xing", "远行" }, { "yuan xiong", "元凶" }, { "yuan yan", "怨言" }, { "yuan yang", "原样" }, { "yuan yang", "远洋" },
			{ "yuan yang", "鸳鸯" }, { "yuan ye", "原野" }, { "yuan yi", "原意" }, { "yuan yi", "园艺" }, { "yuan yi", "愿意" }, { "yuan yi shang", "元以上" },
			{ "yuan yi xia", "元以下" }, { "yuan yin", "原因" }, { "yuan yin", "援引" }, { "yuan yin fen xi", "原因分析" }, { "yuan yin zhi yi", "原因之一" },
			{ "yuan you", "原有" }, { "yuan you", "原油" }, { "yuan you", "原由" }, { "yuan you", "缘由" }, { "yuan you jia ge", "原油价格" },
			{ "yuan you qi huo", "原油期货" }, { "yuan yu", "愿与" }, { "yuan yu", "源于" }, { "yuan yu", "缘于" }, { "yuan yuan", "元元" }, { "yuan yuan", "圆圆" },
			{ "yuan yuan", "媛媛" }, { "yuan yuan", "渊源" }, { "yuan yuan", "远远" }, { "yuan yuan bu duan", "源源不断" }, { "yuan yuan chao guo", "远远超过" },
			{ "yuan yuan de", "圆圆的" }, { "yuan yuan liu chang", "源远流长" }, { "yuan yue", "元月" }, { "yuan zai", "远在" }, { "yuan zang", "援藏" },
			{ "yuan ze", "原则" }, { "yuan ze xing", "原则性" }, { "yuan zhang", "园长" }, { "yuan zhang", "院长" }, { "yuan zheng", "远征" },
			{ "yuan zhi yuan wei", "原汁原味" }, { "yuan zhong", "园中" }, { "yuan zhu", "原著" }, { "yuan zhu", "圆柱" }, { "yuan zhu", "援助" },
			{ "yuan zhu bi", "圆珠笔" }, { "yuan zhu min", "原住民" }, { "yuan zhuang", "原装" }, { "yuan zhui", "圆锥" }, { "yuan zhuo", "圆桌" }, { "yuan zi", "原子" },
			{ "yuan zi", "园子" }, { "yuan zi", "源自" }, { "yuan zi", "院子" }, { "yuan zi dan", "原子弹" }, { "yuan zi li", "院子里" }, { "yuan zi neng", "原子能" },
			{ "yuan zou", "远走" }, { "yuan zui", "原罪" }, { "yuan zuo", "原作" }, { "yuan zuo you", "元左右" }, { "yuan zuo zhe", "原作者" }, { "yue", "乐" },
			{ "yue", "刖" }, { "yue", "哕" }, { "yue", "噦" }, { "yue", "岳" }, { "yue", "嶽" }, { "yue", "悅" }, { "yue", "悦" }, { "yue", "戉" }, { "yue", "扚" },
			{ "yue", "抈" }, { "yue", "擽" }, { "yue", "曰" }, { "yue", "月" }, { "yue", "栎" }, { "yue", "樾" }, { "yue", "櫟" }, { "yue", "瀹" }, { "yue", "焆" },
			{ "yue", "爚" }, { "yue", "玥" }, { "yue", "矱" }, { "yue", "礿" }, { "yue", "禴" }, { "yue", "箹" }, { "yue", "籥" }, { "yue", "粤" }, { "yue", "粵" },
			{ "yue", "約" }, { "yue", "约" }, { "yue", "臒" }, { "yue", "蘥" }, { "yue", "蚎" }, { "yue", "蛻" }, { "yue", "説" }, { "yue", "说" }, { "yue", "越" },
			{ "yue", "趯" }, { "yue", "跃" }, { "yue", "躍" }, { "yue", "躒" }, { "yue", "軏" }, { "yue", "鈅" }, { "yue", "鉞" }, { "yue", "鋭" }, { "yue", "鑠" },
			{ "yue", "钥" }, { "yue", "钺" }, { "yue", "閱" }, { "yue", "閲" }, { "yue", "阅" }, { "yue", "髺" }, { "yue", "鸑" }, { "yue", "鸙" }, { "yue", "黦" },
			{ "yue", "龠" }, { "yue", "龥" }, { "yue bao", "月报" }, { "yue bing", "月饼" }, { "yue bing", "阅兵" }, { "yue cai", "粤菜" }, { "yue chang", "越长" },
			{ "yue chu", "月初" }, { "yue chu sheng", "月出生" }, { "yue da", "越大" }, { "yue dan", "约旦" }, { "yue di", "月底" }, { "yue di", "越低" },
			{ "yue ding", "约定" }, { "yue dong", "越冬" }, { "yue du", "月度" }, { "yue du", "阅读" }, { "yue du li jie", "阅读理解" }, { "yue du qi", "阅读器" },
			{ "yue du quan wen", "阅读全文" }, { "yue dui", "乐队" }, { "yue duo", "越多" }, { "yue duo yue hao", "越多越好" }, { "yue er", "悦耳" }, { "yue er", "月儿" },
			{ "yue fa", "越发" }, { "yue fei", "岳飞" }, { "yue fen", "月份" }, { "yue fu", "岳父" }, { "yue gao", "约稿" }, { "yue gao", "越高" }, { "yue gong", "月供" },
			{ "yue gong zi", "月工资" }, { "yue guang", "月光" }, { "yue guo", "越过" }, { "yue han", "约翰" }, { "yue han xun", "约翰逊" }, { "yue hao", "月号" },
			{ "yue hao", "约好" }, { "yue hao", "越好" }, { "yue he", "约合" }, { "yue hua", "月华" }, { "yue hui", "约会" }, { "yue ji", "月季" }, { "yue jian", "月间" },
			{ "yue jian", "约见" }, { "yue jie", "月结" }, { "yue jin", "越近" }, { "yue jin", "跃进" }, { "yue jing", "月经" }, { "yue jiu", "越久" }, { "yue ju", "越剧" },
			{ "yue ju", "跃居" }, { "yue juan", "阅卷" }, { "yue ka", "月卡" }, { "yue kan", "月刊" }, { "yue kan", "越看" }, { "yue ke", "约克" }, { "yue kuai", "越快" },
			{ "yue lai", "悦来" }, { "yue lai yue", "越来越" }, { "yue lai yue da", "越来越大" }, { "yue lai yue duo", "越来越多" }, { "yue lai yue gao", "越来越高" },
			{ "yue lai yue hao", "越来越好" }, { "yue lai yue shao", "越来越少" }, { "yue lai yue xiao", "越来越小" }, { "yue lan", "阅览" }, { "yue lan shi", "阅览室" },
			{ "yue li", "阅历" }, { "yue liang", "月亮" }, { "yue mi", "乐迷" }, { "yue ming", "月明" }, { "yue mo", "月末" }, { "yue mu", "岳母" }, { "yue nan", "越南" },
			{ "yue piao", "月票" }, { "yue pu", "乐谱" }, { "yue qi", "乐器" }, { "yue qian", "月前" }, { "yue qiang", "越强" }, { "yue qing", "乐清" },
			{ "yue qiu", "月球" }, { "yue qu", "乐曲" }, { "yue ru", "月入" }, { "yue sao", "月嫂" }, { "yue se", "月色" }, { "yue se fu", "约瑟夫" },
			{ "yue shang", "跃上" }, { "yue shang xun", "月上旬" }, { "yue shao", "越少" }, { "yue shen", "越深" }, { "yue sheng", "跃升" }, { "yue shi", "越是" },
			{ "yue shou", "乐手" }, { "yue shou ru", "月收入" }, { "yue shu", "约束" }, { "yue shu ji zhi", "约束机制" }, { "yue shu li", "约束力" }, { "yue shuo", "越说" },
			{ "yue tan", "乐坛" }, { "yue tuan", "乐团" }, { "yue wei", "约为" }, { "yue wei", "越位" }, { "yue xia", "月下" }, { "yue xiang", "越想" },
			{ "yue xiao", "越小" }, { "yue xin", "月薪" }, { "yue xiu", "越秀" }, { "yue xiu qu", "越秀区" }, { "yue ya", "月牙" }, { "yue yang", "岳阳" },
			{ "yue ye", "月夜" }, { "yue ye", "越野" }, { "yue ye che", "越野车" }, { "yue yi lai", "月以来" }, { "yue ying", "月影" }, { "yue you", "约有" },
			{ "yue you", "越有" }, { "yue yu", "粤语" }, { "yue yu", "越狱" }, { "yue yuan", "月圆" }, { "yue yuan", "越远" }, { "yue yue", "月月" },
			{ "yue yue yu shi", "跃跃欲试" }, { "yue zai", "约在" }, { "yue zao", "越早" }, { "yue zhan", "约占" }, { "yue zhan", "越战" }, { "yue zhang", "乐章" },
			{ "yue zhong", "月中" }, { "yue zhong xun", "月中旬" }, { "yue zi", "月子" }, { "yue zou", "越走" }, { "yue zu", "月租" }, { "yue zu fei", "月租费" },
			{ "yue zuo", "越做" }, { "yun", "云" }, { "yun", "伝" }, { "yun", "允" }, { "yun", "勻" }, { "yun", "匀" }, { "yun", "员" }, { "yun", "奫" },
			{ "yun", "妘" }, { "yun", "媼" }, { "yun", "孕" }, { "yun", "恽" }, { "yun", "惲" }, { "yun", "愠" }, { "yun", "慍" }, { "yun", "抎" }, { "yun", "昀" },
			{ "yun", "晕" }, { "yun", "暈" }, { "yun", "枟" }, { "yun", "橒" }, { "yun", "殒" }, { "yun", "殞" }, { "yun", "氲" }, { "yun", "氳" }, { "yun", "沄" },
			{ "yun", "涒" }, { "yun", "溳" }, { "yun", "澐" }, { "yun", "煇" }, { "yun", "熅" }, { "yun", "熉" }, { "yun", "熨" }, { "yun", "狁" }, { "yun", "玧" },
			{ "yun", "畇" }, { "yun", "眃" }, { "yun", "筠" }, { "yun", "篔" }, { "yun", "紜" }, { "yun", "緷" }, { "yun", "縕" }, { "yun", "縜" }, { "yun", "繧" },
			{ "yun", "纭" }, { "yun", "耘" }, { "yun", "芸" }, { "yun", "荺" }, { "yun", "蕓" }, { "yun", "蕴" }, { "yun", "薀" }, { "yun", "蘊" }, { "yun", "蜵" },
			{ "yun", "蝹" }, { "yun", "褞" }, { "yun", "賱" }, { "yun", "贇" }, { "yun", "轀" }, { "yun", "运" }, { "yun", "運" }, { "yun", "郓" }, { "yun", "郧" },
			{ "yun", "鄆" }, { "yun", "鄖" }, { "yun", "酝" }, { "yun", "醞" }, { "yun", "鈗" }, { "yun", "鋆" }, { "yun", "阭" }, { "yun", "陨" }, { "yun", "隕" },
			{ "yun", "雲" }, { "yun", "霣" }, { "yun", "韗" }, { "yun", "韞" }, { "yun", "韫" }, { "yun", "韵" }, { "yun", "韻" }, { "yun", "頵" }, { "yun", "餫" },
			{ "yun", "馧" }, { "yun", "馻" }, { "yun", "齫" }, { "yun cai", "云彩" }, { "yun cai", "晕菜" }, { "yun cang", "蕴藏" }, { "yun ceng", "云层" },
			{ "yun che", "晕车" }, { "yun chen", "匀称" }, { "yun cheng", "运城" }, { "yun cheng", "运程" }, { "yun dao", "晕倒" }, { "yun dao", "运到" },
			{ "yun dong", "运动" }, { "yun dong chang", "运动场" }, { "yun dong fu", "运动服" }, { "yun dong hui", "运动会" }, { "yun dong liang", "运动量" },
			{ "yun dong xie", "运动鞋" }, { "yun dong xing", "运动型" }, { "yun dong yuan", "运动员" }, { "yun duan", "云端" }, { "yun duo", "云朵" }, { "yun er", "云儿" },
			{ "yun fei", "云飞" }, { "yun fei", "运费" }, { "yun feng", "云峰" }, { "yun fu", "孕妇" }, { "yun hai", "云海" }, { "yun han", "蕴含" }, { "yun han", "蕴涵" },
			{ "yun hao", "允浩" }, { "yun he", "运河" }, { "yun ji", "云集" }, { "yun jia", "运价" }, { "yun lai", "运来" }, { "yun li", "云里" }, { "yun li", "运力" },
			{ "yun long", "云龙" }, { "yun lv", "韵律" }, { "yun meng", "云梦" }, { "yun nan", "云南" }, { "yun nan sheng", "云南省" }, { "yun niang", "酝酿" },
			{ "yun qi", "孕期" }, { "yun qi", "运气" }, { "yun qiu", "运球" }, { "yun shan", "云山" }, { "yun shi", "运势" }, { "yun shi", "陨石" }, { "yun shu", "运输" },
			{ "yun shu ji", "运输机" }, { "yun si", "晕死" }, { "yun song", "运送" }, { "yun suan", "运算" }, { "yun suan fu", "运算符" }, { "yun tai", "云台" },
			{ "yun tian", "云天" }, { "yun tong", "运通" }, { "yun tou zhuan xiang", "晕头转向" }, { "yun wang", "运往" }, { "yun wei", "运维" }, { "yun wei", "韵味" },
			{ "yun wu", "云雾" }, { "yun xia", "云霞" }, { "yun xiao", "云霄" }, { "yun xing", "运行" }, { "yun xing ji zhi", "运行机制" },
			{ "yun xing qing kuang", "运行情况" }, { "yun xing su du", "运行速度" }, { "yun xu", "允许" }, { "yun xuan", "晕眩" }, { "yun yan", "云烟" },
			{ "yun ying", "运营" }, { "yun ying cheng ben", "运营成本" }, { "yun ying mo shi", "运营模式" }, { "yun ying shang", "运营商" }, { "yun yong", "运用" },
			{ "yun yu", "孕育" }, { "yun yun", "云云" }, { "yun yun", "晕晕" }, { "yun yun zhong sheng", "芸芸众生" }, { "yun zai", "运载" },
			{ "yun zai huo jian", "运载火箭" }, { "yun zhong", "云中" }, { "yun zhuan", "运转" }, { "yun zuo", "运作" }, { "yun zuo fang shi", "运作方式" },
			{ "yun zuo mo shi", "运作模式" }, { "za", "匝" }, { "za", "咂" }, { "za", "咋" }, { "za", "噈" }, { "za", "扎" }, { "za", "拶" }, { "za", "杂" },
			{ "za", "砸" }, { "za", "磼" }, { "za", "襍" }, { "za", "鉔" }, { "za", "雑" }, { "za", "雜" }, { "za", "雥" }, { "za ban", "咋办" }, { "za cao", "杂草" },
			{ "za fei", "杂费" }, { "za ge", "咋个" }, { "za hui shi", "咋回事" }, { "za huo", "杂货" }, { "za huo dian", "杂货店" }, { "za ji", "杂技" },
			{ "za jiao", "杂交" }, { "za le", "砸了" }, { "za luan", "杂乱" }, { "za men", "咱们" }, { "za men", "砸门" }, { "za nian", "杂念" }, { "za pai", "杂牌" },
			{ "za qi za ba", "杂七杂八" }, { "za shi", "杂事" }, { "za si", "砸死" }, { "za sui", "杂碎" }, { "za tan", "杂谈" }, { "za wen", "杂文" }, { "za wu", "杂物" },
			{ "za yang", "咋样" }, { "za yin", "杂音" }, { "za zai", "砸在" }, { "za zhi", "杂志" }, { "za zhi", "杂质" }, { "za zhi she", "杂志社" }, { "za zhong", "杂种" },
			{ "zai", "仔" }, { "zai", "再" }, { "zai", "哉" }, { "zai", "在" }, { "zai", "宰" }, { "zai", "崽" }, { "zai", "栽" }, { "zai", "渽" }, { "zai", "災" },
			{ "zai", "灾" }, { "zai", "甾" }, { "zai", "賳" }, { "zai", "載" }, { "zai", "载" }, { "zai an", "再按" }, { "zai ba", "再把" }, { "zai bai du", "在百度" },
			{ "zai bo", "载波" }, { "zai bu", "再不" }, { "zai chang", "在场" } };
};
