package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN20 {
	public static String[][] pl = { { "huai you", "怀有" }, { "huai yun", "怀孕" }, { "huai yun hou", "怀孕后" }, { "huai yun qi jian", "怀孕期间" },
			{ "huai zhang", "坏账" }, { "huai zhe", "怀着" }, { "huai zhong", "怀中" }, { "huan", "唤" }, { "huan", "喚" }, { "huan", "嚾" }, { "huan", "圜" },
			{ "huan", "奂" }, { "huan", "奐" }, { "huan", "嬛" }, { "huan", "宦" }, { "huan", "寰" }, { "huan", "峘" }, { "huan", "幻" }, { "huan", "患" },
			{ "huan", "懽" }, { "huan", "换" }, { "huan", "換" }, { "huan", "擐" }, { "huan", "攌" }, { "huan", "桓" }, { "huan", "欢" }, { "huan", "歓" },
			{ "huan", "歡" }, { "huan", "洹" }, { "huan", "浣" }, { "huan", "涣" }, { "huan", "渙" }, { "huan", "漶" }, { "huan", "潅" }, { "huan", "澣" },
			{ "huan", "澴" }, { "huan", "焕" }, { "huan", "煥" }, { "huan", "犿" }, { "huan", "獾" }, { "huan", "环" }, { "huan", "瑍" }, { "huan", "環" },
			{ "huan", "痪" }, { "huan", "瘓" }, { "huan", "睆" }, { "huan", "瞣" }, { "huan", "緩" }, { "huan", "繯" }, { "huan", "缓" }, { "huan", "缳" },
			{ "huan", "羦" }, { "huan", "肒" }, { "huan", "荁" }, { "huan", "萑" }, { "huan", "讙" }, { "huan", "豢" }, { "huan", "豩" }, { "huan", "豲" },
			{ "huan", "貆" }, { "huan", "轘" }, { "huan", "还" }, { "huan", "逭" }, { "huan", "郇" }, { "huan", "鍰" }, { "huan", "锾" }, { "huan", "闤" },
			{ "huan", "雈" }, { "huan", "雚" }, { "huan", "驩" }, { "huan", "鬟" }, { "huan", "鯇" }, { "huan", "鰀" }, { "huan", "鲩" }, { "huan", "鴅" },
			{ "huan bao", "环保" }, { "huan bao", "环抱" }, { "huan bao bu men", "环保部门" }, { "huan bao ju", "环保局" }, { "huan bao xing", "环保型" },
			{ "huan bao yi shi", "环保意识" }, { "huan bao zong ju", "环保总局" }, { "huan bi", "环比" }, { "huan bing", "患病" }, { "huan bo hai", "环渤海" },
			{ "huan che", "换车" }, { "huan cheng", "换乘" }, { "huan cheng", "换成" }, { "huan cheng", "环城" }, { "huan chong", "缓冲" }, { "huan chong qu", "缓冲区" },
			{ "huan chu", "患处" }, { "huan cun", "缓存" }, { "huan dai", "换代" }, { "huan dai", "还贷" }, { "huan dang", "换挡" }, { "huan dang", "换档" },
			{ "huan dao", "换到" }, { "huan dao", "环岛" }, { "huan de", "换得" }, { "huan de huan shi", "患得患失" }, { "huan deng", "幻灯" },
			{ "huan deng pian", "幻灯片" }, { "huan diao", "换掉" }, { "huan er", "患儿" }, { "huan fa", "换发" }, { "huan fa", "焕发" }, { "huan ge", "换个" },
			{ "huan gei", "还给" }, { "huan gong zuo", "换工作" }, { "huan gu", "环顾" }, { "huan guan", "宦官" }, { "huan guo", "换过" }, { "huan hang", "换行" },
			{ "huan hao", "换号" }, { "huan hao", "换好" }, { "huan he", "缓和" }, { "huan hu", "欢呼" }, { "huan hu sheng", "欢呼声" }, { "huan hua", "幻化" },
			{ "huan huan", "换换" }, { "huan huan", "欢欢" }, { "huan huan", "缓缓" }, { "huan hui", "换回" }, { "huan huo", "换货" }, { "huan ji", "换季" },
			{ "huan ji", "还击" }, { "huan jia", "还价" }, { "huan jie", "换届" }, { "huan jie", "环节" }, { "huan jie", "缓解" }, { "huan jie xuan ju", "换届选举" },
			{ "huan jie ya li", "缓解压力" }, { "huan jing", "幻境" }, { "huan jing", "环境" }, { "huan jing bao hu", "环境保护" }, { "huan jing bian liang", "环境变量" },
			{ "huan jing jian ce", "环境监测" }, { "huan jing tiao jian", "环境条件" }, { "huan jing wei sheng", "环境卫生" }, { "huan jing wen ti", "环境问题" },
			{ "huan jing wu ran", "环境污染" }, { "huan jing yin su", "环境因素" }, { "huan jing ying xiang", "环境影响" }, { "huan jing you hao", "环境友好" },
			{ "huan jing you mei", "环境优美" }, { "huan jing zhi liang", "环境质量" }, { "huan ju hua shuo", "换句话说" }, { "huan jue", "幻觉" }, { "huan kuai", "欢快" },
			{ "huan kuan", "还款" }, { "huan lai", "换来" }, { "huan le", "患了" }, { "huan le", "欢乐" }, { "huan le gu", "欢乐谷" }, { "huan lu", "环路" },
			{ "huan man", "缓慢" }, { "huan mie", "幻灭" }, { "huan nan", "患难" }, { "huan ni", "还你" }, { "huan ping", "环评" }, { "huan qi", "唤起" },
			{ "huan qi", "换气" }, { "huan qian", "换钱" }, { "huan qian", "还钱" }, { "huan qing", "欢庆" }, { "huan qing", "还清" }, { "huan qiu", "环球" },
			{ "huan qiu shi bao", "环球时报" }, { "huan qu", "换取" }, { "huan ran yi xin", "焕然一新" }, { "huan rao", "环绕" }, { "huan re qi", "换热器" },
			{ "huan ren", "换人" }, { "huan san", "涣散" }, { "huan shang", "患上" }, { "huan shang", "换上" }, { "huan sheng xiao yu", "欢声笑语" }, { "huan shi", "环视" },
			{ "huan shou", "换手" }, { "huan shou", "还手" }, { "huan shou lv", "换手率" }, { "huan shui", "换水" }, { "huan song", "欢送" }, { "huan suan", "换算" },
			{ "huan tian xi di", "欢天喜地" }, { "huan wei", "换位" }, { "huan wei", "环卫" }, { "huan wei si kao", "换位思考" }, { "huan xi", "欢喜" },
			{ "huan xia", "换下" }, { "huan xian", "环线" }, { "huan xiang", "幻想" }, { "huan xiang", "幻象" }, { "huan xiao", "欢笑" }, { "huan xin", "换新" },
			{ "huan xin", "欢心" }, { "huan xing", "唤醒" }, { "huan xing", "环形" }, { "huan xing", "缓刑" }, { "huan xing shan", "环形山" }, { "huan yan zhi", "换言之" },
			{ "huan yang", "环氧" }, { "huan yao", "换药" }, { "huan yi", "换衣" }, { "huan yi fu", "换衣服" }, { "huan ying", "幻影" }, { "huan ying", "欢迎" },
			{ "huan ying da jia", "欢迎大家" }, { "huan ying fang wen", "欢迎访问" }, { "huan ying guang da", "欢迎广大" }, { "huan ying guang lin", "欢迎光临" },
			{ "huan ying jia ru", "欢迎加入" }, { "huan ying lai", "欢迎来" }, { "huan ying lai dao", "欢迎来到" }, { "huan you", "患有" }, { "huan you", "还有" },
			{ "huan yu", "欢愉" }, { "huan yuan", "还原" }, { "huan zhai", "还债" }, { "huan zhe", "患者" }, { "huan zheng", "换证" }, { "huan zhuang", "换装" },
			{ "huan zhuang", "环状" }, { "huang", "偟" }, { "huang", "兤" }, { "huang", "凰" }, { "huang", "喤" }, { "huang", "堭" }, { "huang", "奛" },
			{ "huang", "媓" }, { "huang", "崲" }, { "huang", "巟" }, { "huang", "幌" }, { "huang", "徨" }, { "huang", "怳" }, { "huang", "恍" }, { "huang", "惶" },
			{ "huang", "愰" }, { "huang", "慌" }, { "huang", "晃" }, { "huang", "晄" }, { "huang", "楻" }, { "huang", "榥" }, { "huang", "汻" }, { "huang", "湟" },
			{ "huang", "滉" }, { "huang", "潢" }, { "huang", "炾" }, { "huang", "煌" }, { "huang", "熿" }, { "huang", "獚" }, { "huang", "璜" }, { "huang", "癀" },
			{ "huang", "皇" }, { "huang", "皝" }, { "huang", "磺" }, { "huang", "穔" }, { "huang", "篁" }, { "huang", "簧" }, { "huang", "肓" }, { "huang", "艎" },
			{ "huang", "荒" }, { "huang", "葟" }, { "huang", "蝗" }, { "huang", "蟥" }, { "huang", "衁" }, { "huang", "諻" }, { "huang", "謊" }, { "huang", "谎" },
			{ "huang", "趪" }, { "huang", "遑" }, { "huang", "鍠" }, { "huang", "鎤" }, { "huang", "鐄" }, { "huang", "隍" }, { "huang", "餭" }, { "huang", "騜" },
			{ "huang", "鰉" }, { "huang", "鳇" }, { "huang", "鷬" }, { "huang", "黃" }, { "huang", "黄" }, { "huang an", "黄安" }, { "huang chao", "皇朝" },
			{ "huang cheng", "皇城" }, { "huang cheng", "谎称" }, { "huang chong", "蝗虫" }, { "huang dan", "荒诞" }, { "huang dan", "黄疸" }, { "huang dang", "晃荡" },
			{ "huang di", "皇帝" }, { "huang di", "荒地" }, { "huang di", "黄帝" }, { "huang dong", "晃动" }, { "huang dou", "黄豆" }, { "huang fei", "荒废" },
			{ "huang fei hong", "黄飞鸿" }, { "huang feng", "黄蜂" }, { "huang fu", "皇甫" }, { "huang gang", "黄冈" }, { "huang gong", "皇宫" }, { "huang gua", "黄瓜" },
			{ "huang guan", "皇冠" }, { "huang guang yu", "黄光裕" }, { "huang hai", "黄海" }, { "huang he", "黄河" }, { "huang he ban", "黄褐斑" },
			{ "huang he lou", "黄鹤楼" }, { "huang hou", "皇后" }, { "huang hu", "恍惚" }, { "huang hua", "谎话" }, { "huang hua", "黄花" }, { "huang huang", "晃晃" },
			{ "huang huang", "黄黄" }, { "huang huang you you", "晃晃悠悠" }, { "huang hun", "黄昏" }, { "huang jia", "皇家" }, { "huang jia ju", "黄家驹" },
			{ "huang jian", "黄建" }, { "huang jian xiang", "黄健翔" }, { "huang jin", "黄金" }, { "huang jin jia", "黄金甲" }, { "huang jin jia ge", "黄金价格" },
			{ "huang jin shi dai", "黄金时代" }, { "huang jin shi duan", "黄金时段" }, { "huang jin zhou", "黄金周" }, { "huang jing", "黄静" }, { "huang jiu", "黄酒" },
			{ "huang ju", "黄菊" }, { "huang kong", "惶恐" }, { "huang lao shi", "黄老师" }, { "huang le", "慌了" }, { "huang lei", "黄磊" }, { "huang lian", "黄连" },
			{ "huang liang", "荒凉" }, { "huang long", "黄龙" }, { "huang luan", "慌乱" }, { "huang ma", "皇马" }, { "huang mang", "慌忙" }, { "huang mao", "黄毛" },
			{ "huang mei", "黄梅" }, { "huang miu", "荒谬" }, { "huang mo", "荒漠" }, { "huang mou", "黄某" }, { "huang niu", "黄牛" }, { "huang pai", "黄牌" },
			{ "huang pian", "黄片" }, { "huang pu", "黄埔" }, { "huang pu", "黄浦" }, { "huang pu jiang", "黄浦江" }, { "huang pu qu", "黄浦区" }, { "huang qi", "黄芪" },
			{ "huang qiu sheng", "黄秋生" }, { "huang qu", "晃去" }, { "huang quan", "皇权" }, { "huang quan", "黄泉" }, { "huang ran", "恍然" },
			{ "huang ran da wu", "恍然大悟" }, { "huang rong", "黄蓉" }, { "huang se", "黄色" }, { "huang sha", "黄沙" }, { "huang shan", "荒山" }, { "huang shan", "黄山" },
			{ "huang shan", "黄衫" }, { "huang shan", "黄鳝" }, { "huang shang", "皇上" }, { "huang sheng yi", "黄圣依" }, { "huang shi", "皇室" }, { "huang shi", "黄石" },
			{ "huang tai ji", "皇太极" }, { "huang tang", "荒唐" }, { "huang tu", "黄土" }, { "huang tu gao yuan", "黄土高原" }, { "huang wei", "皇位" },
			{ "huang wu", "荒芜" }, { "huang xiao ming", "黄晓明" }, { "huang yan", "谎言" }, { "huang yan", "黄岩" }, { "huang ye", "荒野" }, { "huang ye", "黄叶" },
			{ "huang ye", "黄页" }, { "huang yi", "黄奕" }, { "huang you", "晃悠" }, { "huang you", "黄油" }, { "huang yuan", "荒原" }, { "huang zhang", "慌张" },
			{ "huang zhong", "黄忠" }, { "huang zi", "幌子" }, { "huang zi", "皇子" }, { "huang zu", "皇族" }, { "huang zuan", "黄钻" }, { "hui", "会" }, { "hui", "佪" },
			{ "hui", "匯" }, { "hui", "卉" }, { "hui", "咴" }, { "hui", "喙" }, { "hui", "嘒" }, { "hui", "噅" }, { "hui", "囘" }, { "hui", "回" }, { "hui", "圚" },
			{ "hui", "廻" }, { "hui", "彗" }, { "hui", "彙" }, { "hui", "徊" }, { "hui", "徻" }, { "hui", "徽" }, { "hui", "恚" }, { "hui", "恛" }, { "hui", "恢" },
			{ "hui", "恵" }, { "hui", "悔" }, { "hui", "惠" }, { "hui", "慧" }, { "hui", "憓" }, { "hui", "拻" }, { "hui", "挥" }, { "hui", "揮" }, { "hui", "撝" },
			{ "hui", "晖" }, { "hui", "晦" }, { "hui", "暉" }, { "hui", "暳" }, { "hui", "會" }, { "hui", "桧" }, { "hui", "楎" }, { "hui", "槥" }, { "hui", "橞" },
			{ "hui", "檅" }, { "hui", "檓" }, { "hui", "檜" }, { "hui", "毀" }, { "hui", "毁" }, { "hui", "毇" }, { "hui", "汇" }, { "hui", "洃" }, { "hui", "洄" },
			{ "hui", "溃" }, { "hui", "潓" }, { "hui", "灰" }, { "hui", "烠" }, { "hui", "烩" }, { "hui", "燬" }, { "hui", "燴" }, { "hui", "獩" }, { "hui", "珲" },
			{ "hui", "痐" }, { "hui", "瞺" }, { "hui", "硊" }, { "hui", "禈" }, { "hui", "秽" }, { "hui", "穢" }, { "hui", "篲" }, { "hui", "絵" }, { "hui", "繢" },
			{ "hui", "繪" }, { "hui", "绘" }, { "hui", "缋" }, { "hui", "翬" }, { "hui", "翽" }, { "hui", "芔" }, { "hui", "茴" }, { "hui", "荟" }, { "hui", "蔧" },
			{ "hui", "蕙" }, { "hui", "薈" }, { "hui", "薉" }, { "hui", "藱" }, { "hui", "蘳" }, { "hui", "虺" }, { "hui", "蛔" }, { "hui", "螝" }, { "hui", "蟪" },
			{ "hui", "襘" }, { "hui", "詼" }, { "hui", "誨" }, { "hui", "諱" }, { "hui", "譓" }, { "hui", "譭" }, { "hui", "譿" }, { "hui", "讳" }, { "hui", "诙" },
			{ "hui", "诲" }, { "hui", "豗" }, { "hui", "賄" }, { "hui", "贿" }, { "hui", "輝" }, { "hui", "輠" }, { "hui", "辉" }, { "hui", "迴" }, { "hui", "鐬" },
			{ "hui", "闠" }, { "hui", "隓" }, { "hui", "隳" }, { "hui", "顪" }, { "hui", "餯" }, { "hui", "鰴" }, { "hui", "麾" }, { "hui an", "灰暗" },
			{ "hui ba", "会把" }, { "hui bai", "灰白" }, { "hui bao", "回报" }, { "hui bao", "汇报" }, { "hui bao lv", "回报率" }, { "hui bei", "会被" },
			{ "hui bi", "会比" }, { "hui bi", "回避" }, { "hui bian", "会变" }, { "hui bian", "汇编" }, { "hui bo", "回拨" }, { "hui bu", "回补" },
			{ "hui bu hui", "会不会" }, { "hui bu qu", "回不去" }, { "hui chang", "会唱" }, { "hui chang", "会场" }, { "hui che", "回车" }, { "hui chen", "灰尘" },
			{ "hui cheng", "回城" }, { "hui cheng", "回程" }, { "hui cheng", "汇成" }, { "hui chong", "蛔虫" }, { "hui chu", "汇出" }, { "hui chuan", "回传" },
			{ "hui cong", "慧聪" }, { "hui cui", "荟萃" }, { "hui da", "回答" }, { "hui da wen ti", "回答问题" }, { "hui dang", "回档" }, { "hui dang", "回荡" },
			{ "hui dao", "回到" }, { "hui dao jia", "回到家" }, { "hui de", "慧德" }, { "hui dian", "回电" }, { "hui diao", "回调" }, { "hui diao", "毁掉" },
			{ "hui dong", "挥动" }, { "hui du", "灰度" }, { "hui dui", "会对" }, { "hui dui", "汇兑" }, { "hui er", "会儿" }, { "hui fa", "会发" }, { "hui fa", "挥发" },
			{ "hui fa you", "挥发油" }, { "hui fang", "回放" }, { "hui fang", "回访" }, { "hui fei", "会费" }, { "hui fei", "会飞" }, { "hui fei yan mie", "灰飞烟灭" },
			{ "hui feng", "汇丰" }, { "hui feng yin hang", "汇丰银行" }, { "hui fou", "会否" }, { "hui fu", "回复" }, { "hui fu", "回覆" }, { "hui fu", "恢复" },
			{ "hui fu ri qi", "回复日期" }, { "hui fu zheng chang", "恢复正常" }, { "hui gai", "悔改" }, { "hui ge zi", "灰鸽子" }, { "hui gei", "会给" },
			{ "hui gen", "会跟" }, { "hui geng", "会更" }, { "hui geng hao", "会更好" }, { "hui gou", "回购" }, { "hui gu", "回顾" }, { "hui gu", "惠顾" },
			{ "hui gu", "灰谷" }, { "hui gu niang", "灰姑娘" }, { "hui guan", "会馆" }, { "hui gui", "回归" }, { "hui gun", "回滚" }, { "hui guo", "回国" },
			{ "hui guo", "回过" }, { "hui guo rou", "回锅肉" }, { "hui he", "会合" }, { "hui he", "回合" }, { "hui he", "汇合" }, { "hui hen", "会很" },
			{ "hui hen", "悔恨" }, { "hui hou", "会后" }, { "hui hua", "会话" }, { "hui hua", "回话" }, { "hui hua", "绘画" }, { "hui huai", "毁坏" },
			{ "hui huang", "辉煌" }, { "hui hui", "回回" }, { "hui hui", "慧慧" }, { "hui hui", "挥挥" }, { "hui hui lai", "会回来" }, { "hui huo", "挥霍" },
			{ "hui ji", "回击" }, { "hui ji", "徽记" }, { "hui ji", "惠及" }, { "hui ji", "汇集" }, { "hui jia", "回家" }, { "hui jia", "汇价" },
			{ "hui jia guo nian", "回家过年" }, { "hui jian", "会见" }, { "hui jian", "回见" }, { "hui jiang", "会将" }, { "hui jiao", "会叫" }, { "hui jiao", "回教" },
			{ "hui jin", "汇金" }, { "hui jin", "灰烬" }, { "hui jing", "回京" }, { "hui jing", "回敬" }, { "hui ju", "汇聚" }, { "hui jue", "回绝" }, { "hui kan", "会刊" },
			{ "hui kao", "会考" }, { "hui kou", "回扣" }, { "hui kuan", "回款" }, { "hui kuan", "汇款" }, { "hui kui", "回馈" }, { "hui lai", "会来" },
			{ "hui lai", "回来" }, { "hui lai ba", "回来吧" }, { "hui lao jia", "回老家" }, { "hui li", "会里" }, { "hui ling", "会令" }, { "hui liu", "回流" },
			{ "hui long", "回笼" }, { "hui long guan", "回龙观" }, { "hui lu", "回路" }, { "hui lu", "贿赂" }, { "hui luo", "回落" }, { "hui lv", "汇率" },
			{ "hui meng meng", "灰蒙蒙" }, { "hui mian", "会面" }, { "hui mie", "毁灭" }, { "hui mie xing", "毁灭性" }, { "hui min", "回民" }, { "hui min", "惠民" },
			{ "hui mou", "回眸" }, { "hui niang jia", "回娘家" }, { "hui nong", "惠农" }, { "hui nuan", "回暖" }, { "hui piao", "汇票" }, { "hui pu", "惠普" },
			{ "hui qi", "晦气" }, { "hui qian", "汇钱" }, { "hui qu", "会去" }, { "hui qu", "回去" }, { "hui rang", "会让" }, { "hui rong", "毁容" }, { "hui ru", "汇入" },
			{ "hui sa", "挥洒" }, { "hui se", "晦涩" }, { "hui se", "灰色" }, { "hui shang", "会上" }, { "hui shen", "回身" }, { "hui sheng", "回升" },
			{ "hui sheng", "回声" }, { "hui shi", "会使" }, { "hui shi", "会师" }, { "hui shi", "会是" }, { "hui shi", "回事" }, { "hui shi", "汇市" },
			{ "hui shou", "回收" }, { "hui shou", "回首" }, { "hui shou", "挥手" }, { "hui shou zhan", "回收站" }, { "hui shuo", "会说" }, { "hui si", "会死" },
			{ "hui su", "回溯" }, { "hui suo", "会所" }, { "hui tan", "会谈" }, { "hui tiao", "回调" }, { "hui tie", "回帖" }, { "hui tie", "回贴" }, { "hui tong", "会同" },
			{ "hui tong", "汇通" }, { "hui tou", "回头" }, { "hui tou kan", "回头看" }, { "hui tu", "回吐" }, { "hui tu", "绘图" }, { "hui tui", "回退" },
			{ "hui wan", "会玩" }, { "hui wang", "回望" }, { "hui wei", "会为" }, { "hui wei", "回味" }, { "hui wei", "惠威" }, { "hui wei wu qiong", "回味无穷" },
			{ "hui wen", "会问" }, { "hui wu", "会务" }, { "hui wu", "会晤" }, { "hui wu", "挥舞" }, { "hui xia", "麾下" }, { "hui xiang", "会向" }, { "hui xiang", "回乡" },
			{ "hui xiang", "回响" }, { "hui xiang", "回想" }, { "hui xiao", "回校" }, { "hui xie", "诙谐" }, { "hui xin", "会心" }, { "hui xin", "回信" },
			{ "hui xin", "灰心" }, { "hui xing", "彗星" }, { "hui xiong", "灰熊" }, { "hui xuan", "回旋" }, { "hui yan", "慧眼" }, { "hui yi", "会以" },
			{ "hui yi", "会议" }, { "hui yi", "回忆" }, { "hui yi ji lu", "会议记录" }, { "hui yi ji yao", "会议纪要" }, { "hui yi jing shen", "会议精神" },
			{ "hui yi lu", "回忆录" }, { "hui yi shi", "会议室" }, { "hui yi zhao kai", "会议召开" }, { "hui yi zhong xin", "会议中心" }, { "hui yin", "会因" },
			{ "hui yin", "回音" }, { "hui ying", "回应" }, { "hui ying", "辉映" }, { "hui yong", "会用" }, { "hui you", "会有" }, { "hui yuan", "会员" },
			{ "hui yuan", "汇源" }, { "hui yuan dan wei", "会员单位" }, { "hui yuan ka", "会员卡" }, { "hui yuan zi liao", "会员资料" }, { "hui zai", "会再" },
			{ "hui zai", "会在" }, { "hui zhan", "会展" }, { "hui zhan", "会战" }, { "hui zhan zhong xin", "会展中心" }, { "hui zhang", "会长" }, { "hui zhang", "徽章" },
			{ "hui zhao", "会找" }, { "hui zhen", "会诊" }, { "hui zhi", "回执" }, { "hui zhi", "绘制" }, { "hui zhi bu qu", "挥之不去" }, { "hui zhou", "徽州" },
			{ "hui zhou", "惠州" }, { "hui zhou shi", "惠州市" }, { "hui zhuan", "回转" }, { "hui zong", "汇总" }, { "hui zong biao", "汇总表" }, { "hui zu", "回族" },
			{ "hui zuo", "会做" }, { "hun", "倱" }, { "hun", "圂" }, { "hun", "婚" }, { "hun", "惛" }, { "hun", "慁" }, { "hun", "掍" }, { "hun", "昏" },
			{ "hun", "棔" }, { "hun", "浑" }, { "hun", "涽" }, { "hun", "混" }, { "hun", "渾" }, { "hun", "溷" }, { "hun", "珲" }, { "hun", "琿" }, { "hun", "睧" },
			{ "hun", "睯" }, { "hun", "緄" }, { "hun", "繉" }, { "hun", "荤" }, { "hun", "觨" }, { "hun", "諢" }, { "hun", "诨" }, { "hun", "閽" }, { "hun", "阍" },
			{ "hun", "餛" }, { "hun", "馄" }, { "hun", "魂" }, { "hun", "鼲" }, { "hun an", "昏暗" }, { "hun da", "混搭" }, { "hun dan", "混蛋" }, { "hun dao", "昏倒" },
			{ "hun dao", "混到" }, { "hun de", "混得" }, { "hun dun", "混沌" }, { "hun he", "混合" }, { "hun he dong li", "混合动力" }, { "hun he wu", "混合物" },
			{ "hun he xing", "混合型" }, { "hun hou", "婚后" }, { "hun hou", "浑厚" }, { "hun huang", "昏黄" }, { "hun hun", "昏昏" }, { "hun hun", "混混" },
			{ "hun hun chen chen", "昏昏沉沉" }, { "hun hun e e", "浑浑噩噩" }, { "hun hun yu shui", "昏昏欲睡" }, { "hun ji", "混迹" }, { "hun jia", "婚嫁" },
			{ "hun jian", "婚检" }, { "hun jie", "婚介" }, { "hun jin", "混进" }, { "hun le", "昏了" }, { "hun li", "婚礼" }, { "hun lian", "婚恋" }, { "hun luan", "混乱" },
			{ "hun mi", "昏迷" }, { "hun ning tu", "混凝土" }, { "hun po", "魂魄" }, { "hun qi", "婚期" }, { "hun qian", "婚前" }, { "hun qing", "婚庆" },
			{ "hun ri zi", "混日子" }, { "hun ru", "混入" }, { "hun sha", "婚纱" }, { "hun sha she ying", "婚纱摄影" }, { "hun sha zhao", "婚纱照" }, { "hun shen", "浑身" },
			{ "hun shi", "婚事" }, { "hun shui", "昏睡" }, { "hun shui", "混水" }, { "hun si", "昏死" }, { "hun tun", "馄饨" }, { "hun wai lian", "婚外恋" },
			{ "hun wai qing", "婚外情" }, { "hun wei yi tan", "混为一谈" }, { "hun xiao", "混淆" }, { "hun xue", "混血" }, { "hun yan", "婚宴" }, { "hun yin", "婚姻" },
			{ "hun yin", "混音" }, { "hun yin fa", "婚姻法" }, { "hun yin sheng huo", "婚姻生活" }, { "hun yin zhuang kuang", "婚姻状况" }, { "hun za", "混杂" },
			{ "hun zai", "混在" }, { "hun zai yi qi", "混在一起" }, { "hun zhan", "混战" }, { "hun zhe", "混着" }, { "hun zhuo", "浑浊" }, { "hun zhuo", "混浊" },
			{ "huo", "伙" }, { "huo", "佸" }, { "huo", "劐" }, { "huo", "吙" }, { "huo", "咊" }, { "huo", "和" }, { "huo", "嗀" }, { "huo", "嚄" }, { "huo", "嚯" },
			{ "huo", "夥" }, { "huo", "姡" }, { "huo", "惑" }, { "huo", "或" }, { "huo", "捇" }, { "huo", "攉" }, { "huo", "曤" }, { "huo", "檴" }, { "huo", "沎" },
			{ "huo", "活" }, { "huo", "湱" }, { "huo", "漷" }, { "huo", "濩" }, { "huo", "瀖" }, { "huo", "火" }, { "huo", "灬" }, { "huo", "獲" }, { "huo", "癨" },
			{ "huo", "眓" }, { "huo", "矐" }, { "huo", "祸" }, { "huo", "禍" }, { "huo", "秮" }, { "huo", "穫" }, { "huo", "耠" }, { "huo", "膕" }, { "huo", "臛" },
			{ "huo", "获" }, { "huo", "藿" }, { "huo", "蠖" }, { "huo", "謋" }, { "huo", "豁" }, { "huo", "豰" }, { "huo", "貨" }, { "huo", "货" }, { "huo", "趏" },
			{ "huo", "鈥" }, { "huo", "鑊" }, { "huo", "钬" }, { "huo", "锪" }, { "huo", "镬" }, { "huo", "霍" }, { "huo", "騞" }, { "huo ba", "火把" },
			{ "huo ban", "伙伴" }, { "huo ban guan xi", "伙伴关系" }, { "huo bao", "活宝" }, { "huo bao", "火暴" }, { "huo bao", "火爆" }, { "huo bei", "或被" },
			{ "huo beng luan tiao", "活蹦乱跳" }, { "huo bi", "货币" }, { "huo bi ji jin", "货币基金" }, { "huo bi shi chang", "货币市场" }, { "huo bi zheng ce", "货币政策" },
			{ "huo bu", "或不" }, { "huo bu xia qu", "活不下去" }, { "huo chai", "火柴" }, { "huo che", "火车" }, { "huo che", "货车" }, { "huo che piao", "火车票" },
			{ "huo che tou", "火车头" }, { "huo che zhan", "火车站" }, { "huo chu qu", "豁出去" }, { "huo da", "豁达" }, { "huo dai", "货代" }, { "huo dao", "活到" },
			{ "huo dao", "货到" }, { "huo dao fu kuan", "货到付款" }, { "huo de", "活得" }, { "huo de", "获得" }, { "huo de cheng gong", "获得成功" },
			{ "huo de geng duo", "获得更多" }, { "huo de zhe", "获得者" }, { "huo dian", "火电" }, { "huo dong", "活动" }, { "huo dong chang suo", "活动场所" },
			{ "huo dong nei rong", "活动内容" }, { "huo dong shi jian", "活动时间" }, { "huo dong zhong xin", "活动中心" }, { "huo er", "活儿" }, { "huo er", "霍尔" },
			{ "huo fo", "活佛" }, { "huo fu", "霍夫" }, { "huo gai", "活该" }, { "huo guang", "火光" }, { "huo gui", "货柜" }, { "huo guo", "火锅" },
			{ "huo guo dian", "火锅店" }, { "huo hai", "火海" }, { "huo hai", "祸害" }, { "huo hao", "货号" }, { "huo hong", "火红" }, { "huo hou", "火候" },
			{ "huo hu", "火狐" }, { "huo hua", "活化" }, { "huo hua", "火化" }, { "huo hua", "火花" }, { "huo hua de", "霍华德" }, { "huo hua sai", "火花塞" },
			{ "huo huo", "活活" }, { "huo ji", "伙计" }, { "huo ji", "火鸡" }, { "huo jia", "货架" }, { "huo jian", "活检" }, { "huo jian", "火箭" },
			{ "huo jian dui", "火箭队" }, { "huo jiang", "或将" }, { "huo jiang", "获奖" }, { "huo jiang ming dan", "获奖名单" }, { "huo jiang zhe", "获奖者" },
			{ "huo jiang zuo pin", "获奖作品" }, { "huo jin", "霍金" }, { "huo jiu", "获救" }, { "huo ju", "火炬" }, { "huo ju shou", "火炬手" }, { "huo kang", "火抗" },
			{ "huo kuan", "货款" }, { "huo la", "火辣" }, { "huo la la", "火辣辣" }, { "huo le", "活了" }, { "huo le", "火了" }, { "huo li", "活力" }, { "huo li", "火力" },
			{ "huo li", "获利" }, { "huo li pan", "获利盘" }, { "huo long", "火龙" }, { "huo lu", "活路" }, { "huo lu", "火炉" }, { "huo luan", "霍乱" },
			{ "huo mian", "豁免" }, { "huo miao", "火苗" }, { "huo ming", "活命" }, { "huo pao", "火炮" }, { "huo pi", "获批" }, { "huo pin", "火拼" },
			{ "huo pin", "货品" }, { "huo po", "活泼" }, { "huo qi", "或其" }, { "huo qi", "活期" }, { "huo qi", "火气" }, { "huo qi ta", "或其他" },
			{ "huo qi ta", "或其它" }, { "huo qiang", "火枪" }, { "huo qiu", "火球" }, { "huo qu", "获取" }, { "huo ran kai lang", "豁然开朗" }, { "huo re", "火热" },
			{ "huo ren", "活人" }, { "huo sai", "活塞" }, { "huo se", "货色" }, { "huo shan", "火山" }, { "huo shan chu", "或删除" }, { "huo shao", "或少" },
			{ "huo shao", "火烧" }, { "huo sheng", "获胜" } };
};
