package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN64 {
	public static String[][] pl = { { "zhu dao", "主导" }, { "zhu dao", "住到" }, { "zhu dao chan pin", "主导产品" }, { "zhu dao chan ye", "主导产业" },
			{ "zhu dao di wei", "主导地位" }, { "zhu dao zuo yong", "主导作用" }, { "zhu de", "住得" }, { "zhu de", "住的" }, { "zhu de", "朱德" }, { "zhu di", "朱棣" },
			{ "zhu di", "驻地" }, { "zhu ding", "注定" }, { "zhu dong", "主动" }, { "zhu dong quan", "主动权" }, { "zhu dong xing", "主动性" }, { "zhu dui", "主队" },
			{ "zhu duo", "诸多" }, { "zhu er", "主儿" }, { "zhu fan", "主犯" }, { "zhu fan", "煮饭" }, { "zhu fang", "住房" }, { "zhu fang dai kuan", "住房贷款" },
			{ "zhu fang wen ti", "住房问题" }, { "zhu fei", "煮沸" }, { "zhu feng", "主峰" }, { "zhu feng", "珠峰" }, { "zhu fo", "诸佛" }, { "zhu fu", "主妇" },
			{ "zhu fu", "嘱咐" }, { "zhu fu", "祝福" }, { "zhu fu ni", "祝福你" }, { "zhu gan", "主干" }, { "zhu gan", "猪肝" }, { "zhu gan", "竹竿" },
			{ "zhu gan dao", "主干道" }, { "zhu ge", "诸葛" }, { "zhu ge", "逐个" }, { "zhu ge liang", "诸葛亮" }, { "zhu gong", "主攻" }, { "zhu gong", "助攻" },
			{ "zhu guan", "主管" }, { "zhu guan", "主观" }, { "zhu guan bu men", "主管部门" }, { "zhu guan ji guan", "主管机关" }, { "zhu guang", "烛光" },
			{ "zhu guang hu", "朱广沪" }, { "zhu guo", "住过" }, { "zhu hai", "珠海" }, { "zhu hai shi", "珠海市" }, { "zhu hao", "煮好" }, { "zhu he", "祝贺" },
			{ "zhu hou", "诸侯" }, { "zhu hu", "住户" }, { "zhu hua", "驻华" }, { "zhu hui chang", "主会场" }, { "zhu ji", "主机" }, { "zhu ji", "助剂" },
			{ "zhu ji", "诸暨" }, { "zhu ji", "逐级" }, { "zhu jia", "住家" }, { "zhu jia", "朱家" }, { "zhu jian", "主见" }, { "zhu jian", "主键" }, { "zhu jian", "逐渐" },
			{ "zhu jian", "铸件" }, { "zhu jiang", "主将" }, { "zhu jiang", "主讲" }, { "zhu jiang", "珠江" }, { "zhu jiang lu", "珠江路" }, { "zhu jiao", "主叫" },
			{ "zhu jiao", "主教" }, { "zhu jiao", "主角" }, { "zhu jiao", "助教" }, { "zhu jiao", "猪脚" }, { "zhu jiao lian", "主教练" }, { "zhu jie", "注解" },
			{ "zhu jin", "住进" }, { "zhu jiu", "铸就" }, { "zhu juan", "猪圈" }, { "zhu jue", "主角" }, { "zhu jun", "朱军" }, { "zhu jun", "朱骏" }, { "zhu jun", "驻军" },
			{ "zhu kong", "主控" }, { "zhu li", "主力" }, { "zhu li", "伫立" }, { "zhu li", "助力" }, { "zhu li", "助理" }, { "zhu li jun", "主力军" },
			{ "zhu li ye", "朱丽叶" }, { "zhu lin", "竹林" }, { "zhu ling", "朱令" }, { "zhu liu", "主流" }, { "zhu liu", "驻留" }, { "zhu liu mei ti", "主流媒体" },
			{ "zhu lou", "主楼" }, { "zhu ming", "注明" }, { "zhu ming", "著名" }, { "zhu ming chu chu", "注明出处" }, { "zhu ming dao yan", "著名导演" },
			{ "zhu ming pin pai", "著名品牌" }, { "zhu ming zuo jia", "著名作家" }, { "zhu mu", "注目" }, { "zhu mu", "瞩目" }, { "zhu ni", "祝你" }, { "zhu nian", "猪年" },
			{ "zhu nian", "逐年" }, { "zhu nin", "助您" }, { "zhu nin", "祝您" }, { "zhu pin", "主频" }, { "zhu quan", "主权" }, { "zhu que", "朱雀" },
			{ "zhu ren", "主人" }, { "zhu ren", "主任" }, { "zhu ren", "助人" }, { "zhu ren gong", "主人公" }, { "zhu ren wei yuan", "主任委员" },
			{ "zhu ren weng", "主人翁" }, { "zhu ren yi shi", "主任医师" }, { "zhu rou", "猪肉" }, { "zhu rou jia ge", "猪肉价格" }, { "zhu ru", "侏儒" }, { "zhu ru", "注入" },
			{ "zhu ru", "诸如" }, { "zhu ru ci lei", "诸如此类" }, { "zhu san jiao", "珠三角" }, { "zhu se diao", "主色调" }, { "zhu shang", "住上" }, { "zhu she", "注射" },
			{ "zhu she qi", "注射器" }, { "zhu she ye", "注射液" }, { "zhu shen", "诸神" }, { "zhu shi", "主食" }, { "zhu shi", "注视" }, { "zhu shi", "注释" },
			{ "zhu shi hui she", "株式会社" }, { "zhu shou", "助手" }, { "zhu shou", "驻守" }, { "zhu shu", "煮熟" }, { "zhu shu", "著述" }, { "zhu shuai", "主帅" },
			{ "zhu shui", "注水" }, { "zhu si ma ji", "蛛丝马迹" }, { "zhu su", "住宿" }, { "zhu su", "注塑" }, { "zhu su fei", "住宿费" }, { "zhu sun", "竹笋" },
			{ "zhu suo", "住所" }, { "zhu tan", "竹炭" }, { "zhu ti", "主体" }, { "zhu ti", "主题" }, { "zhu ti", "猪蹄" }, { "zhu ti ge", "主题歌" },
			{ "zhu ti gong yuan", "主题公园" }, { "zhu ti huo dong", "主题活动" }, { "zhu ti qu", "主题曲" }, { "zhu ti xing", "主体性" }, { "zhu tie", "主贴" },
			{ "zhu tie", "铸铁" }, { "zhu tou", "猪头" }, { "zhu tui", "主推" }, { "zhu tui", "助推" }, { "zhu wai", "驻外" }, { "zhu wei", "主委" }, { "zhu wei", "助威" },
			{ "zhu wei", "诸位" }, { "zhu wo", "主卧" }, { "zhu xi", "主席" }, { "zhu xi", "朱熹" }, { "zhu xi tai", "主席台" }, { "zhu xi tuan", "主席团" },
			{ "zhu xia", "住下" }, { "zhu xian", "主线" }, { "zhu xian", "诛仙" }, { "zhu xiang", "逐项" }, { "zhu xiao", "住校" }, { "zhu xiao", "注销" },
			{ "zhu xing", "助兴" }, { "zhu xiu", "主修" }, { "zhu xuan lv", "主旋律" }, { "zhu xue", "助学" }, { "zhu xue dai kuan", "助学贷款" }, { "zhu xue jin", "助学金" },
			{ "zhu ya", "蛀牙" }, { "zhu yan", "主演" }, { "zhu yao", "主要" }, { "zhu yao bao kuo", "主要包括" }, { "zhu yao biao xian", "主要表现" },
			{ "zhu yao chan pin", "主要产品" }, { "zhu yao cheng fen", "主要成分" }, { "zhu yao fen bu", "主要分布" }, { "zhu yao gong neng", "主要功能" },
			{ "zhu yao gong zuo", "主要工作" }, { "zhu yao jing ying", "主要经营" }, { "zhu yao lai yuan", "主要来源" }, { "zhu yao ling dao", "主要领导" },
			{ "zhu yao mao dun", "主要矛盾" }, { "zhu yao mu biao", "主要目标" }, { "zhu yao nei rong", "主要内容" }, { "zhu yao ren wu", "主要任务" },
			{ "zhu yao shi zhi", "主要是指" }, { "zhu yao te dian", "主要特点" }, { "zhu yao te zheng", "主要特征" }, { "zhu yao ti xian", "主要体现" },
			{ "zhu yao wen ti", "主要问题" }, { "zhu yao yan yuan", "主要演员" }, { "zhu yao ye wu", "主要业务" }, { "zhu yao yin su", "主要因素" },
			{ "zhu yao yong yu", "主要用于" }, { "zhu yao yuan liao", "主要原料" }, { "zhu yao yuan yin", "主要原因" }, { "zhu yao ze ren", "主要责任" },
			{ "zhu yao zhi ze", "主要职责" }, { "zhu ye", "主业" }, { "zhu ye", "主页" }, { "zhu ye", "竹叶" }, { "zhu yi", "主义" }, { "zhu yi", "主意" },
			{ "zhu yi", "注意" }, { "zhu yi", "逐一" }, { "zhu yi an quan", "注意安全" }, { "zhu yi dian", "注意点" }, { "zhu yi li", "注意力" },
			{ "zhu yi mei jun", "驻伊美军" }, { "zhu yi shi xiang", "注意事项" }, { "zhu yi zhe", "主义者" }, { "zhu yin", "主因" }, { "zhu yin", "朱茵" },
			{ "zhu ying", "主营" }, { "zhu ying ye wu", "主营业务" }, { "zhu you", "猪油" }, { "zhu yu", "主语" }, { "zhu yuan", "住院" }, { "zhu yuan", "祝愿" },
			{ "zhu yuan zhang", "朱元璋" }, { "zhu yue", "逐月" }, { "zhu zai", "主宰" }, { "zhu zai", "住在" }, { "zhu zao", "铸造" }, { "zhu zha", "驻扎" },
			{ "zhu zhai", "住宅" }, { "zhu zhai lou", "住宅楼" }, { "zhu zhai qu", "住宅区" }, { "zhu zhai xiao qu", "住宅小区" }, { "zhu zhan", "主站" },
			{ "zhu zhang", "主张" }, { "zhu zhang", "助长" }, { "zhu zhe", "住着" }, { "zhu zhen", "助阵" }, { "zhu zhi", "主旨" }, { "zhu zhi", "主治" },
			{ "zhu zhi", "住址" }, { "zhu zhong", "注重" }, { "zhu zhou", "主轴" }, { "zhu zhou", "株洲" }, { "zhu zhou", "煮粥" }, { "zhu zhu", "猪猪" },
			{ "zhu zi", "主子" }, { "zhu zi", "柱子" }, { "zhu zi", "注资" }, { "zhu zi", "珠子" }, { "zhu zi", "竹子" }, { "zhu zu", "驻足" }, { "zhu zuo", "著作" },
			{ "zhu zuo quan", "著作权" }, { "zhu zuo quan ren", "著作权人" }, { "zhua", "抓" }, { "zhua", "挝" }, { "zhua", "檛" }, { "zhua", "爪" }, { "zhua", "簻" },
			{ "zhua", "膼" }, { "zhua", "髽" }, { "zhua bu", "抓捕" }, { "zhua dao", "抓到" }, { "zhua de", "抓得" }, { "zhua hao", "抓好" }, { "zhua huo", "抓获" },
			{ "zhua jin", "抓紧" }, { "zhua jin shi jian", "抓紧时间" }, { "zhua kuang", "抓狂" }, { "zhua pai", "抓拍" }, { "zhua qi", "抓起" }, { "zhua qu", "抓取" },
			{ "zhua ren", "抓人" }, { "zhua shou", "抓手" }, { "zhua tu", "抓图" }, { "zhua zhe", "抓着" }, { "zhua zhu", "抓住" }, { "zhua zhu ji yu", "抓住机遇" },
			{ "zhua zi", "爪子" }, { "zhuai", "拽" }, { "zhuai", "捙" }, { "zhuai", "跩" }, { "zhuai zhe", "拽着" }, { "zhuan", "专" }, { "zhuan", "传" },
			{ "zhuan", "僝" }, { "zhuan", "剸" }, { "zhuan", "啭" }, { "zhuan", "囀" }, { "zhuan", "塼" }, { "zhuan", "嫥" }, { "zhuan", "専" }, { "zhuan", "專" },
			{ "zhuan", "恮" }, { "zhuan", "摶" }, { "zhuan", "撰" }, { "zhuan", "漙" }, { "zhuan", "瑑" }, { "zhuan", "瑼" }, { "zhuan", "甎" }, { "zhuan", "砖" },
			{ "zhuan", "磚" }, { "zhuan", "篆" }, { "zhuan", "篿" }, { "zhuan", "簨" }, { "zhuan", "縳" }, { "zhuan", "耑" }, { "zhuan", "腞" }, { "zhuan", "膞" },
			{ "zhuan", "蟤" }, { "zhuan", "諯" }, { "zhuan", "譔" }, { "zhuan", "賺" }, { "zhuan", "赚" }, { "zhuan", "転" }, { "zhuan", "轉" }, { "zhuan", "转" },
			{ "zhuan", "鄟" }, { "zhuan", "顓" }, { "zhuan", "颛" }, { "zhuan", "饌" }, { "zhuan", "馔" }, { "zhuan", "鱄" }, { "zhuan an", "专案" },
			{ "zhuan an zu", "专案组" }, { "zhuan ban", "专版" }, { "zhuan bao", "转包" }, { "zhuan bian", "转变" }, { "zhuan bian cheng", "转变成" },
			{ "zhuan bo", "转播" }, { "zhuan chang", "专场" }, { "zhuan chang", "专长" }, { "zhuan che", "专车" }, { "zhuan che", "转车" }, { "zhuan cheng", "专程" },
			{ "zhuan cheng", "转成" }, { "zhuan chu", "转出" }, { "zhuan da", "转达" }, { "zhuan da qian", "赚大钱" }, { "zhuan dao", "赚到" }, { "zhuan dao", "转到" },
			{ "zhuan de", "赚得" }, { "zhuan dian", "专电" }, { "zhuan dian", "赚点" }, { "zhuan dong", "转动" }, { "zhuan er", "转而" }, { "zhuan fa", "转发" },
			{ "zhuan fang", "专访" }, { "zhuan gao", "专稿" }, { "zhuan gao", "转告" }, { "zhuan gei", "转给" }, { "zhuan gong", "专供" }, { "zhuan gong", "专攻" },
			{ "zhuan gui", "专柜" }, { "zhuan gui", "转轨" }, { "zhuan guo", "转过" }, { "zhuan guo shen", "转过身" }, { "zhuan guo tou", "转过头" },
			{ "zhuan hang", "转行" }, { "zhuan hu", "专户" }, { "zhuan hua", "转化" }, { "zhuan hua cheng", "转化成" }, { "zhuan huan", "转换" },
			{ "zhuan huan cheng", "转换成" }, { "zhuan huan qi", "转换器" }, { "zhuan hui", "转会" }, { "zhuan hui", "转回" }, { "zhuan ji", "专机" },
			{ "zhuan ji", "专辑" }, { "zhuan ji", "专集" }, { "zhuan ji", "传记" }, { "zhuan ji", "转机" }, { "zhuan ji jie shao", "专辑介绍" }, { "zhuan ji yin", "转基因" },
			{ "zhuan jia", "专家" }, { "zhuan jia", "转嫁" }, { "zhuan jia cheng", "专家称" }, { "zhuan jia fen xi", "专家分析" }, { "zhuan jia jian yi", "专家建议" },
			{ "zhuan jia jie shao", "专家介绍" }, { "zhuan jia ren wei", "专家认为" }, { "zhuan jia ti xing", "专家提醒" }, { "zhuan jia xue zhe", "专家学者" },
			{ "zhuan jia zu", "专家组" }, { "zhuan jiao", "转交" }, { "zhuan jiao", "转角" }, { "zhuan jie", "转接" }, { "zhuan jing", "专精" }, { "zhuan kai", "转开" },
			{ "zhuan kan", "专刊" }, { "zhuan ke", "专科" }, { "zhuan kuan", "专款" }, { "zhuan lai", "转来" }, { "zhuan lai zhuan qu", "转来转去" },
			{ "zhuan lan", "专栏" }, { "zhuan le", "赚了" }, { "zhuan li", "专利" }, { "zhuan li ji shu", "专利技术" }, { "zhuan li quan", "专利权" },
			{ "zhuan li shen qing", "专利申请" }, { "zhuan lu", "转录" }, { "zhuan mai", "专卖" }, { "zhuan mai dian", "专卖店" }, { "zhuan men", "专门" },
			{ "zhuan men cong shi", "专门从事" }, { "zhuan nian", "转念" }, { "zhuan pan", "转盘" }, { "zhuan qian", "赚钱" }, { "zhuan qu", "专区" },
			{ "zhuan qu", "赚取" }, { "zhuan quan", "转圈" }, { "zhuan rang", "转让" }, { "zhuan ren", "专人" }, { "zhuan ru", "转入" }, { "zhuan sha", "专杀" },
			{ "zhuan shen", "转身" }, { "zhuan sheng", "转生" }, { "zhuan sheng ben", "专升本" }, { "zhuan shi", "砖石" }, { "zhuan shi", "转世" },
			{ "zhuan shou", "转手" }, { "zhuan shu", "专属" }, { "zhuan shu", "转述" }, { "zhuan su", "转速" }, { "zhuan tai", "转台" }, { "zhuan ti", "专题" },
			{ "zhuan ti jiang zuo", "专题讲座" }, { "zhuan ti yan jiu", "专题研究" }, { "zhuan tie", "转帖" }, { "zhuan tie", "转贴" }, { "zhuan tou", "砖头" },
			{ "zhuan tou", "转头" }, { "zhuan tou", "转投" }, { "zhuan wan", "转弯" }, { "zhuan wang", "专网" }, { "zhuan wei", "专为" }, { "zhuan wei", "转为" },
			{ "zhuan wen", "撰文" }, { "zhuan xian", "专线" }, { "zhuan xiang", "专项" }, { "zhuan xiang", "转向" }, { "zhuan xiang jian cha", "专项检查" },
			{ "zhuan xiang zheng zhi", "专项整治" }, { "zhuan xiang zhi li", "专项治理" }, { "zhuan xiang zi jin", "专项资金" }, { "zhuan xie", "撰写" },
			{ "zhuan xin", "专心" }, { "zhuan xing", "转型" }, { "zhuan xing qi", "转型期" }, { "zhuan xiu", "专修" }, { "zhuan xue", "转学" }, { "zhuan yan", "转眼" },
			{ "zhuan yan jian", "转眼间" }, { "zhuan yao", "砖窑" }, { "zhuan ye", "专业" }, { "zhuan ye", "转业" }, { "zhuan ye ban", "专业版" },
			{ "zhuan ye bi ye", "专业毕业" }, { "zhuan ye cong shi", "专业从事" }, { "zhuan ye fu wu", "专业服务" }, { "zhuan ye hu", "专业户" }, { "zhuan ye hua", "专业化" },
			{ "zhuan ye ji", "专业级" }, { "zhuan ye ji neng", "专业技能" }, { "zhuan ye ji shu", "专业技术" }, { "zhuan ye ke", "专业课" }, { "zhuan ye pei xun", "专业培训" },
			{ "zhuan ye ren cai", "专业人才" }, { "zhuan ye ren shi", "专业人士" }, { "zhuan ye ren yuan", "专业人员" }, { "zhuan ye sheng chan", "专业生产" },
			{ "zhuan ye shi chang", "专业市场" }, { "zhuan ye xing", "专业性" }, { "zhuan ye zhi shi", "专业知识" }, { "zhuan yi", "专一" }, { "zhuan yi", "转移" },
			{ "zhuan yi zhi fu", "转移支付" }, { "zhuan ying", "专营" }, { "zhuan ying dian", "专营店" }, { "zhuan yong", "专用" }, { "zhuan yong fa piao", "专用发票" },
			{ "zhuan you", "专有" }, { "zhuan you", "转悠" }, { "zhuan yuan", "专员" }, { "zhuan yun", "转运" }, { "zhuan zai", "转载" }, { "zhuan zai gao", "转载稿" },
			{ "zhuan zai zi", "转载自" }, { "zhuan zeng", "转增" }, { "zhuan zhai", "转债" }, { "zhuan zhan", "转战" }, { "zhuan zhang", "转帐" },
			{ "zhuan zhang", "转账" }, { "zhuan zhe", "转折" }, { "zhuan zhe dian", "转折点" }, { "zhuan zheng", "专政" }, { "zhuan zheng", "转正" },
			{ "zhuan zhi", "专制" }, { "zhuan zhi", "专职" }, { "zhuan zhi", "转制" }, { "zhuan zhi", "转职" }, { "zhuan zhi", "转至" }, { "zhuan zhu", "专注" },
			{ "zhuan zhuan", "转转" }, { "zhuan zi", "转子" }, { "zhuan zi", "转自" }, { "zhuan zu", "转租" }, { "zhuang", "僮" }, { "zhuang", "壮" }, { "zhuang", "壯" },
			{ "zhuang", "奘" }, { "zhuang", "妆" }, { "zhuang", "妝" }, { "zhuang", "幢" }, { "zhuang", "庄" }, { "zhuang", "戆" }, { "zhuang", "戇" },
			{ "zhuang", "撞" }, { "zhuang", "桩" }, { "zhuang", "梉" }, { "zhuang", "樁" }, { "zhuang", "湷" }, { "zhuang", "焋" }, { "zhuang", "状" },
			{ "zhuang", "狀" }, { "zhuang", "獞" }, { "zhuang", "粧" }, { "zhuang", "荘" }, { "zhuang", "莊" }, { "zhuang", "装" }, { "zhuang", "裝" },
			{ "zhuang ban", "装扮" }, { "zhuang bei", "装备" }, { "zhuang che", "撞车" }, { "zhuang che", "装车" }, { "zhuang cheng", "装成" }, { "zhuang chu", "装出" },
			{ "zhuang chuan", "装船" }, { "zhuang cun", "庄村" }, { "zhuang da", "壮大" }, { "zhuang da", "装大" }, { "zhuang dao", "撞倒" }, { "zhuang dao", "撞到" },
			{ "zhuang dao", "装到" }, { "zhuang de", "装得" }, { "zhuang dian", "装点" }, { "zhuang ding", "装订" }, { "zhuang gao", "状告" }, { "zhuang guan", "壮观" },
			{ "zhuang han", "壮汉" }, { "zhuang hao", "装好" }, { "zhuang huang", "装潢" }, { "zhuang ji", "撞击" }, { "zhuang ji", "装机" },
			{ "zhuang ji rong liang", "装机容量" }, { "zhuang jia", "庄家" }, { "zhuang jia", "庄稼" }, { "zhuang jia", "装甲" }, { "zhuang jia che", "装甲车" },
			{ "zhuang jian", "撞见" }, { "zhuang jin", "装进" }, { "zhuang ju", "壮举" }, { "zhuang kuang", "状况" }, { "zhuang le", "撞了" }, { "zhuang li", "壮丽" },
			{ "zhuang lie", "壮烈" }, { "zhuang man", "装满" }, { "zhuang pei", "装配" }, { "zhuang qiang", "撞墙" }, { "zhuang ren", "撞人" }, { "zhuang rong", "妆容" },
			{ "zhuang ru", "装入" }, { "zhuang sha", "装傻" }, { "zhuang shang", "撞上" }, { "zhuang shang", "装上" }, { "zhuang shi", "壮士" }, { "zhuang shi", "装饰" },
			{ "zhuang shi cai liao", "装饰材料" }, { "zhuang shi gong si", "装饰公司" }, { "zhuang shi pin", "装饰品" }, { "zhuang shi zhuang xiu", "装饰装修" },
			{ "zhuang shu", "装束" }, { "zhuang si", "撞死" }, { "zhuang si", "装死" }, { "zhuang tai", "状态" }, { "zhuang tai lan", "状态栏" }, { "zhuang wan", "装完" },
			{ "zhuang xi tong", "装系统" }, { "zhuang xiang", "装箱" }, { "zhuang xie", "装卸" }, { "zhuang xiu", "装修" }, { "zhuang xiu gong si", "装修公司" },
			{ "zhuang yan", "庄严" }, { "zhuang yang", "壮阳" }, { "zhuang you", "装有" }, { "zhuang yuan", "庄园" }, { "zhuang yuan", "状元" }, { "zhuang yun", "装运" },
			{ "zhuang zai", "撞在" }, { "zhuang zai", "装在" }, { "zhuang zai", "装载" }, { "zhuang zhe", "装着" }, { "zhuang zhen", "庄镇" }, { "zhuang zhi", "壮志" },
			{ "zhuang zhi", "装置" }, { "zhuang zhong", "庄重" }, { "zhuang zhu", "庄主" }, { "zhuang zhuang", "壮壮" }, { "zhuang zi", "庄子" }, { "zhuang zu", "壮族" },
			{ "zhuang zuo", "装作" }, { "zhui", "倕" }, { "zhui", "坠" }, { "zhui", "埀" }, { "zhui", "墜" }, { "zhui", "娷" }, { "zhui", "惴" }, { "zhui", "椎" },
			{ "zhui", "甀" }, { "zhui", "畷" }, { "zhui", "硾" }, { "zhui", "箠" }, { "zhui", "綴" }, { "zhui", "縋" }, { "zhui", "缀" }, { "zhui", "缒" },
			{ "zhui", "腏" }, { "zhui", "膇" }, { "zhui", "諈" }, { "zhui", "贅" }, { "zhui", "赘" }, { "zhui", "轛" }, { "zhui", "追" }, { "zhui", "醀" },
			{ "zhui", "醊" }, { "zhui", "錐" }, { "zhui", "錣" }, { "zhui", "鑆" }, { "zhui", "锥" }, { "zhui", "隹" }, { "zhui", "餟" }, { "zhui", "騅" },
			{ "zhui", "骓" }, { "zhui", "鵻" }, { "zhui bu", "追捕" }, { "zhui bu shang", "追不上" }, { "zhui cha", "追查" }, { "zhui dao", "追到" },
			{ "zhui dao hui", "追悼会" }, { "zhui feng", "追风" }, { "zhui gan", "追赶" }, { "zhui hui", "坠毁" }, { "zhui hui", "追回" }, { "zhui ji", "追击" },
			{ "zhui jia", "追加" }, { "zhui jiao", "追缴" }, { "zhui jiu", "追究" }, { "zhui jiu qi", "追究其" }, { "zhui jiu ze ren", "追究责任" }, { "zhui le", "追了" },
			{ "zhui lou", "坠楼" }, { "zhui luo", "坠落" }, { "zhui peng", "追捧" }, { "zhui qiu", "追求" }, { "zhui qiu wan mei", "追求完美" }, { "zhui qiu zhe", "追求者" },
			{ "zhui rou", "赘肉" }, { "zhui ru", "坠入" }, { "zhui sha", "追杀" }, { "zhui shang", "追上" }, { "zhui shu", "赘述" }, { "zhui su", "追溯" },
			{ "zhui sui", "追随" }, { "zhui sui zhe", "追随者" }, { "zhui tao", "追讨" }, { "zhui wei", "追尾" }, { "zhui wen", "追问" }, { "zhui xing", "追星" },
			{ "zhui xun", "追寻" }, { "zhui yi", "追忆" }, { "zhui zhang", "追涨" }, { "zhui zhe", "追着" }, { "zhui zhu", "追逐" }, { "zhui zong", "追踪" },
			{ "zhun", "准" }, { "zhun", "凖" }, { "zhun", "啍" }, { "zhun", "埻" }, { "zhun", "宒" }, { "zhun", "屯" }, { "zhun", "忳" }, { "zhun", "旽" },
			{ "zhun", "準" }, { "zhun", "甽" }, { "zhun", "稕" }, { "zhun", "窀" }, { "zhun", "綧" }, { "zhun", "肫" }, { "zhun", "訰" }, { "zhun", "諄" },
			{ "zhun", "谆" }, { "zhun", "迍" }, { "zhun bei", "准备" }, { "zhun bei gong zuo", "准备工作" }, { "zhun bei hao", "准备好" }, { "zhun bei jin", "准备金" },
			{ "zhun bei jin lv", "准备金率" }, { "zhun kao zheng", "准考证" }, { "zhun ma ma", "准妈妈" }, { "zhun que", "准确" }, { "zhun que du", "准确度" },
			{ "zhun que lv", "准确率" }, { "zhun que xing", "准确性" }, { "zhun ru", "准入" }, { "zhun shi", "准时" }, { "zhun xu", "准许" }, { "zhun yu", "准予" },
			{ "zhun ze", "准则" }, { "zhuo", "倬" }, { "zhuo", "剢" }, { "zhuo", "卓" }, { "zhuo", "啄" }, { "zhuo", "啅" }, { "zhuo", "噣" }, { "zhuo", "圴" },
			{ "zhuo", "彴" }, { "zhuo", "拙" }, { "zhuo", "捉" }, { "zhuo", "捔" }, { "zhuo", "擢" }, { "zhuo", "斀" }, { "zhuo", "斫" }, { "zhuo", "斮" },
			{ "zhuo", "斲" }, { "zhuo", "晫" }, { "zhuo", "桌" }, { "zhuo", "梲" }, { "zhuo", "棳" }, { "zhuo", "椓" }, { "zhuo", "櫡" }, { "zhuo", "汋" },
			{ "zhuo", "浊" }, { "zhuo", "浞" }, { "zhuo", "涿" }, { "zhuo", "濁" }, { "zhuo", "濯" }, { "zhuo", "灂" }, { "zhuo", "灼" }, { "zhuo", "焯" },
			{ "zhuo", "琢" }, { "zhuo", "琸" }, { "zhuo", "着" }, { "zhuo", "矠" }, { "zhuo", "硺" }, { "zhuo", "禚" }, { "zhuo", "穛" }, { "zhuo", "穱" },
			{ "zhuo", "篧" }, { "zhuo", "籗" }, { "zhuo", "缴" }, { "zhuo", "罬" }, { "zhuo", "茁" }, { "zhuo", "著" }, { "zhuo", "蓔" }, { "zhuo", "藋" },
			{ "zhuo", "蝃" }, { "zhuo", "蠗" }, { "zhuo", "蠿" }, { "zhuo", "諑" }, { "zhuo", "謶" }, { "zhuo", "诼" }, { "zhuo", "趠" }, { "zhuo", "蹠" },
			{ "zhuo", "酌" }, { "zhuo", "鐲" }, { "zhuo", "镯" }, { "zhuo", "鵫" }, { "zhuo", "鷟" }, { "zhuo bu", "桌布" }, { "zhuo jin jian zhou", "捉襟见肘" },
			{ "zhuo li", "着力" }, { "zhuo li dian", "着力点" }, { "zhuo lie", "拙劣" }, { "zhuo lu", "着陆" }, { "zhuo mi cang", "捉迷藏" }, { "zhuo mian", "桌面" },
			{ "zhuo mo", "琢磨" }, { "zhuo nong", "捉弄" }, { "zhuo qian", "桌前" }, { "zhuo qing", "酌情" }, { "zhuo qiu", "桌球" }, { "zhuo re", "灼热" },
			{ "zhuo se", "着色" }, { "zhuo shang", "桌上" }, { "zhuo shang", "灼伤" }, { "zhuo shi", "着实" }, { "zhuo shou", "着手" }, { "zhuo xiang", "着想" },
			{ "zhuo yan", "着眼" }, { "zhuo yi", "桌椅" }, { "zhuo you cheng xiao", "卓有成效" }, { "zhuo yue", "卓越" }, { "zhuo yue wang", "卓越网" },
			{ "zhuo zhong", "着重" }, { "zhuo zhu", "卓著" }, { "zhuo zhu", "捉住" }, { "zhuo zhuang", "着装" }, { "zhuo zhuang cheng zhang", "茁壮成长" },
			{ "zhuo zi", "桌子" }, { "zi", "仔" }, { "zi", "倳" }, { "zi", "兹" }, { "zi", "剚" }, { "zi", "吱" }, { "zi", "呰" }, { "zi", "呲" }, { "zi", "咨" },
			{ "zi", "姉" }, { "zi", "姊" }, { "zi", "姿" }, { "zi", "子" }, { "zi", "孖" }, { "zi", "字" }, { "zi", "孜" }, { "zi", "孳" }, { "zi", "崰" },
			{ "zi", "嵫" }, { "zi", "恣" }, { "zi", "杍" }, { "zi", "栥" }, { "zi", "梓" }, { "zi", "椔" }, { "zi", "沝" }, { "zi", "淄" }, { "zi", "渍" },
			{ "zi", "滋" }, { "zi", "滓" }, { "zi", "漬" }, { "zi", "澬" }, { "zi", "牸" }, { "zi", "玆" }, { "zi", "璾" }, { "zi", "眥" }, { "zi", "眦" },
			{ "zi", "矷" }, { "zi", "秭" }, { "zi", "秶" }, { "zi", "穧" }, { "zi", "笫" }, { "zi", "籽" }, { "zi", "粢" }, { "zi", "紎" }, { "zi", "紫" },
			{ "zi", "緇" }, { "zi", "缁" }, { "zi", "耔" }, { "zi", "胏" }, { "zi", "胔" }, { "zi", "胾" }, { "zi", "自" }, { "zi", "芓" }, { "zi", "茈" },
			{ "zi", "茲" }, { "zi", "菑" }, { "zi", "蓻" }, { "zi", "薋" }, { "zi", "觜" }, { "zi", "訾" }, { "zi", "訿" }, { "zi", "諮" }, { "zi", "谘" },
			{ "zi", "貲" }, { "zi", "資" }, { "zi", "赀" }, { "zi", "资" }, { "zi", "趑" }, { "zi", "輜" }, { "zi", "辎" }, { "zi", "鄑" }, { "zi", "釨" },
			{ "zi", "鈭" }, { "zi", "錙" }, { "zi", "鎡" }, { "zi", "锱" }, { "zi", "髭" }, { "zi", "鯔" }, { "zi", "鲻" }, { "zi", "鶅" }, { "zi", "鼒" },
			{ "zi", "齍" }, { "zi", "齜" }, { "zi", "龇" }, { "zi ai", "自爱" }, { "zi ao", "自傲" }, { "zi ba", "自拔" }, { "zi bai", "自白" }, { "zi bao", "自保" },
			{ "zi bao", "自曝" }, { "zi bao", "自爆" }, { "zi bao zi qi", "自暴自弃" }, { "zi bei", "自卑" }, { "zi bei", "自备" }, { "zi ben", "资本" },
			{ "zi ben jia", "资本家" }, { "zi ben jin", "资本金" }, { "zi ben shi chang", "资本市场" }, { "zi ben yun zuo", "资本运作" }, { "zi ben zhu yi", "资本主义" },
			{ "zi bi", "自闭" }, { "zi bian", "自编" }, { "zi bo", "淄博" }, { "zi bo shi", "淄博市" }, { "zi bu", "滋补" }, { "zi cai", "紫菜" }, { "zi can", "自残" },
			{ "zi ce", "自测" }, { "zi cha", "自查" }, { "zi chan", "自产" }, { "zi chan", "资产" }, { "zi chan chong zu", "资产重组" }, { "zi chan guan li", "资产管理" },
			{ "zi chan gui mo", "资产规模" }, { "zi chan jie ji", "资产阶级" }, { "zi chan ping gu", "资产评估" }, { "zi chao", "自嘲" }, { "zi cheng", "自成" },
			{ "zi cheng", "自称" }, { "zi chou", "自筹" }, { "zi chuan", "字串" }, { "zi chuang", "自创" }, { "zi ci", "字词" }, { "zi ci", "自此" }, { "zi cong", "自从" },
			{ "zi da", "自大" }, { "zi da", "自打" }, { "zi dai", "自带" }, { "zi dan", "子弹" }, { "zi dan", "自担" }, { "zi dao", "自导" }, { "zi di", "子弟" },
			{ "zi dian", "字典" }, { "zi ding", "自定" }, { "zi ding yi", "自定义" }, { "zi dong", "自动" }, { "zi dong bo fang", "自动播放" }, { "zi dong dang", "自动挡" },
			{ "zi dong dang", "自动档" }, { "zi dong dui jiao", "自动对焦" }, { "zi dong geng xin", "自动更新" }, { "zi dong guan bi", "自动关闭" },
			{ "zi dong guan ji", "自动关机" }, { "zi dong hua", "自动化" }, { "zi dong kong zhi", "自动控制" }, { "zi dong sheng cheng", "自动生成" },
			{ "zi dong shi bie", "自动识别" }, { "zi dong yun xing", "自动运行" }, { "zi duan", "字段" }, { "zi fa", "自发" }, { "zi fei", "自费" }, { "zi fei", "资费" },
			{ "zi fen", "自焚" }, { "zi fu", "字符" }, { "zi fu", "自负" }, { "zi fu chuan", "字符串" }, { "zi fu ji", "字符集" }, { "zi ge", "自个" }, { "zi ge", "资格" },
			{ "zi ge er", "自个儿" }, { "zi ge kao shi", "资格考试" }, { "zi ge sai", "资格赛" }, { "zi ge shen cha", "资格审查" }, { "zi ge zheng", "资格证" },
			{ "zi ge zheng shu", "资格证书" }, { "zi gong", "子宫" }, { "zi gong", "自宫" }, { "zi gong", "自贡" }, { "zi gong jing", "子宫颈" }, { "zi gong nei", "子宫内" },
			{ "zi gong si", "子公司" }, { "zi gu", "自古" }, { "zi gu", "自顾" }, { "zi gu yi lai", "自古以来" }, { "zi gu zi", "自顾自" }, { "zi guang", "紫光" },
			{ "zi hao", "字号" }, { "zi hao", "自豪" }, { "zi hao gan", "自豪感" }, { "zi hong se", "紫红色" }, { "zi hua", "字画" } };
};
