package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN17 {
	public static String[][] pl = { { "guan jian yin su", "关键因素" }, { "guan jian zai yu", "关键在于" }, { "guan jian zi", "关键字" }, { "guan jiao", "管教" },
			{ "guan jie", "关节" }, { "guan jie teng tong", "关节疼痛" }, { "guan jie yan", "关节炎" }, { "guan jin", "关进" }, { "guan jing", "观景" },
			{ "guan jun", "冠军" }, { "guan jun bei", "冠军杯" }, { "guan jun lian sai", "冠军联赛" }, { "guan ka", "关卡" }, { "guan kan", "观看" }, { "guan kong", "管控" },
			{ "guan kou", "关口" }, { "guan kou", "管口" }, { "guan lan", "灌篮" }, { "guan lan gao shou", "灌篮高手" }, { "guan le", "惯了" }, { "guan li", "官吏" },
			{ "guan li", "惯例" }, { "guan li", "管理" }, { "guan li ban fa", "管理办法" }, { "guan li bu", "管理部" }, { "guan li bu men", "管理部门" },
			{ "guan li ceng", "管理层" }, { "guan li chu", "管理处" }, { "guan li chuang xin", "管理创新" }, { "guan li fang fa", "管理方法" },
			{ "guan li fang shi", "管理方式" }, { "guan li fei", "管理费" }, { "guan li fei yong", "管理费用" }, { "guan li fu wu", "管理服务" },
			{ "guan li gong ju", "管理工具" }, { "guan li gong neng", "管理功能" }, { "guan li gong si", "管理公司" }, { "guan li gong zuo", "管理工作" },
			{ "guan li gui ding", "管理规定" }, { "guan li ji gou", "管理机构" }, { "guan li ji shu", "管理技术" }, { "guan li ji zhi", "管理机制" },
			{ "guan li jing yan", "管理经验" }, { "guan li ju", "管理局" }, { "guan li ke", "管理科" }, { "guan li li nian", "管理理念" }, { "guan li mo shi", "管理模式" },
			{ "guan li neng li", "管理能力" }, { "guan li ping tai", "管理平台" }, { "guan li qi", "管理器" }, { "guan li qu", "管理区" }, { "guan li quan xian", "管理权限" },
			{ "guan li ren", "管理人" }, { "guan li ren cai", "管理人才" }, { "guan li ren yuan", "管理人员" }, { "guan li ruan jian", "管理软件" },
			{ "guan li shui ping", "管理水平" }, { "guan li ti xi", "管理体系" }, { "guan li ti zhi", "管理体制" }, { "guan li tiao li", "管理条例" },
			{ "guan li tuan dui", "管理团队" }, { "guan li xi tong", "管理系统" }, { "guan li xue", "管理学" }, { "guan li xue yuan", "管理学院" }, { "guan li yuan", "管理员" },
			{ "guan li zhe", "管理者" }, { "guan li zhi du", "管理制度" }, { "guan li zhi neng", "管理职能" }, { "guan li zhong xin", "管理中心" },
			{ "guan li zi xun", "管理咨询" }, { "guan lian", "关联" }, { "guan lian fang", "关联方" }, { "guan lian jiao yi", "关联交易" }, { "guan lian xing", "关联性" },
			{ "guan liao", "官僚" }, { "guan liao zhu yi", "官僚主义" }, { "guan lu", "管路" }, { "guan men", "关门" }, { "guan mian tang huang", "冠冕堂皇" },
			{ "guan ming", "冠名" }, { "guan mo", "观摩" }, { "guan mu", "灌木" }, { "guan nei", "关内" }, { "guan nei", "管内" }, { "guan nei", "馆内" },
			{ "guan nian", "观念" }, { "guan qie", "关切" }, { "guan qu", "灌区" }, { "guan shan", "关山" }, { "guan shang", "关上" }, { "guan shang", "观赏" },
			{ "guan shang xing", "观赏性" }, { "guan shi", "管事" }, { "guan shu", "灌输" }, { "guan shui", "关税" }, { "guan shui", "灌水" }, { "guan si", "官司" },
			{ "guan ta", "管他" }, { "guan ta", "管它" }, { "guan ting", "关停" }, { "guan tong", "贯通" }, { "guan tou", "关头" }, { "guan tou", "罐头" },
			{ "guan wai", "关外" }, { "guan wang", "官网" }, { "guan wang", "管网" }, { "guan wang", "观望" }, { "guan wei hui", "管委会" }, { "guan xi", "关系" },
			{ "guan xi", "关西" }, { "guan xia", "管辖" }, { "guan xia quan", "管辖权" }, { "guan xian", "管线" }, { "guan xin", "关心" }, { "guan xin bing", "冠心病" },
			{ "guan xing", "惯性" }, { "guan ya", "关押" }, { "guan yi", "冠以" }, { "guan yin", "观音" }, { "guan ying", "观影" }, { "guan yong", "惯用" },
			{ "guan yong", "管用" }, { "guan yu", "关于" }, { "guan yu", "关羽" }, { "guan yu jia qiang", "关于加强" }, { "guan yu kai zhan", "关于开展" },
			{ "guan yu yin fa", "关于印发" }, { "guan yu zhong guo", "关于中国" }, { "guan yu zuo hao", "关于做好" }, { "guan yuan", "官员" }, { "guan zai", "关在" },
			{ "guan zhan", "观战" }, { "guan zhang", "馆长" }, { "guan zhao", "关照" }, { "guan zhe", "关着" }, { "guan zhe", "管着" }, { "guan zhe", "观者" },
			{ "guan zhi", "官职" }, { "guan zhi", "管制" }, { "guan zhi lin", "关之琳" }, { "guan zhong", "关中" }, { "guan zhong", "观众" }, { "guan zhong xi", "观众席" },
			{ "guan zhu", "关注" }, { "guan zhu", "灌注" }, { "guan zhu", "管住" }, { "guan zhu dian", "关注点" }, { "guan zhu du", "关注度" }, { "guan zhuang", "灌装" },
			{ "guan zhuang dong mai", "冠状动脉" }, { "guan zi", "管子" }, { "guan zi", "罐子" }, { "guan zi", "馆子" }, { "guan zui", "灌醉" }, { "guang", "侊" },
			{ "guang", "俇" }, { "guang", "光" }, { "guang", "咣" }, { "guang", "垙" }, { "guang", "广" }, { "guang", "広" }, { "guang", "廣" }, { "guang", "撗" },
			{ "guang", "桄" }, { "guang", "欟" }, { "guang", "洸" }, { "guang", "炚" }, { "guang", "烡" }, { "guang", "犷" }, { "guang", "珖" }, { "guang", "胱" },
			{ "guang", "茪" }, { "guang", "逛" }, { "guang", "銧" }, { "guang an", "广安" }, { "guang ben", "广本" }, { "guang biao", "光标" }, { "guang bo", "光波" },
			{ "guang bo", "广博" }, { "guang bo", "广播" }, { "guang bo dian shi", "广播电视" }, { "guang bo dian tai", "广播电台" }, { "guang cai", "光彩" },
			{ "guang chang", "广场" }, { "guang da", "光大" }, { "guang da", "广大" }, { "guang da dang yuan", "广大党员" }, { "guang da ke hu", "广大客户" },
			{ "guang da qun zhong", "广大群众" }, { "guang da ren min", "广大人民" }, { "guang da yin hang", "光大银行" }, { "guang da yong hu", "广大用户" },
			{ "guang dao", "广岛" }, { "guang dian", "光电" }, { "guang dian", "广电" }, { "guang dian zong ju", "广电总局" }, { "guang diao", "光雕" },
			{ "guang die", "光碟" }, { "guang dong", "广东" }, { "guang dong hua", "广东话" }, { "guang dong ren", "广东人" }, { "guang dong sheng", "广东省" },
			{ "guang du", "广度" }, { "guang fa", "广发" }, { "guang fa zheng quan", "广发证券" }, { "guang fan", "广泛" }, { "guang fan kai zhan", "广泛开展" },
			{ "guang fan ying yong", "广泛应用" }, { "guang fu", "光伏" }, { "guang gao", "广告" }, { "guang gao ci", "广告词" }, { "guang gao fei", "广告费" },
			{ "guang gao gong si", "广告公司" }, { "guang gao he zuo", "广告合作" }, { "guang gao pai", "广告牌" }, { "guang gao pian", "广告片" },
			{ "guang gao shang", "广告商" }, { "guang gao shou ru", "广告收入" }, { "guang gao tiao", "广告条" }, { "guang gao tou fang", "广告投放" },
			{ "guang gao wei", "广告位" }, { "guang gao xuan chuan", "广告宣传" }, { "guang gao yu", "广告语" }, { "guang gao zhu", "广告主" }, { "guang gu", "光顾" },
			{ "guang guang", "光光" }, { "guang guang", "逛逛" }, { "guang gun", "光棍" }, { "guang he zuo yong", "光合作用" }, { "guang hua", "光华" },
			{ "guang hua", "光滑" }, { "guang huan", "光环" }, { "guang hui", "光辉" }, { "guang jiao", "光脚" }, { "guang jiao", "广角" }, { "guang jiao hui", "广交会" },
			{ "guang jie", "光洁" }, { "guang jie", "逛街" }, { "guang jing", "光景" }, { "guang kan", "光看" }, { "guang kao", "光靠" }, { "guang kuo", "广阔" },
			{ "guang lan", "光缆" }, { "guang le", "光了" }, { "guang liang", "光亮" }, { "guang liang", "光良" }, { "guang lin", "光临" }, { "guang mang", "光芒" },
			{ "guang mao", "广袤" }, { "guang ming", "光明" }, { "guang ming zheng da", "光明正大" }, { "guang nian", "光年" }, { "guang pan", "光盘" },
			{ "guang pu", "光谱" }, { "guang qian", "光纤" }, { "guang qu", "光驱" }, { "guang quan", "光圈" }, { "guang rong", "光荣" }, { "guang sha", "广厦" },
			{ "guang shan", "光栅" }, { "guang shen", "广深" }, { "guang shi", "光是" }, { "guang shou", "广受" }, { "guang shu", "光束" }, { "guang su", "光速" },
			{ "guang tian hua ri", "光天化日" }, { "guang tou", "光头" }, { "guang wai", "广外" }, { "guang wei", "广为" }, { "guang xi", "广西" }, { "guang xian", "光纤" },
			{ "guang xian", "光线" }, { "guang xian", "光鲜" }, { "guang xu", "光绪" }, { "guang xue", "光学" }, { "guang xue bian jiao", "光学变焦" },
			{ "guang yi", "广义" }, { "guang yin", "光阴" }, { "guang ying", "光影" }, { "guang yu wang", "广域网" }, { "guang yuan", "光源" }, { "guang yuan", "广元" },
			{ "guang yun", "光晕" }, { "guang ze", "光泽" }, { "guang zhao", "光照" }, { "guang zhe", "光着" }, { "guang zhou", "广州" },
			{ "guang zhou ben tian", "广州本田" }, { "guang zhou che zhan", "广州车展" }, { "guang zhou ren", "广州人" }, { "guang zhou ri bao", "广州日报" },
			{ "guang zhou shi", "广州市" }, { "guang zi", "光子" }, { "gui", "亀" }, { "gui", "佹" }, { "gui", "刽" }, { "gui", "刿" }, { "gui", "劊" }, { "gui", "劌" },
			{ "gui", "匦" }, { "gui", "匭" }, { "gui", "厬" }, { "gui", "圭" }, { "gui", "垝" }, { "gui", "妫" }, { "gui", "姽" }, { "gui", "媯" }, { "gui", "宄" },
			{ "gui", "帰" }, { "gui", "庋" }, { "gui", "庪" }, { "gui", "归" }, { "gui", "摫" }, { "gui", "撌" }, { "gui", "晷" }, { "gui", "柜" }, { "gui", "桂" },
			{ "gui", "桧" }, { "gui", "椢" }, { "gui", "槶" }, { "gui", "槻" }, { "gui", "槼" }, { "gui", "櫃" }, { "gui", "歸" }, { "gui", "氿" }, { "gui", "湀" },
			{ "gui", "炅" }, { "gui", "猤" }, { "gui", "珪" }, { "gui", "瑰" }, { "gui", "癸" }, { "gui", "皈" }, { "gui", "瞡" }, { "gui", "硅" }, { "gui", "祪" },
			{ "gui", "禬" }, { "gui", "筀" }, { "gui", "簋" }, { "gui", "茥" }, { "gui", "蛫" }, { "gui", "蟡" }, { "gui", "袿" }, { "gui", "規" }, { "gui", "规" },
			{ "gui", "觤" }, { "gui", "詭" }, { "gui", "诡" }, { "gui", "貴" }, { "gui", "贵" }, { "gui", "跪" }, { "gui", "軌" }, { "gui", "轨" }, { "gui", "邽" },
			{ "gui", "閨" }, { "gui", "闺" }, { "gui", "鬼" }, { "gui", "鲑" }, { "gui", "鳜" }, { "gui", "鳺" }, { "gui", "龜" }, { "gui", "龟" }, { "gui an", "归案" },
			{ "gui bao", "瑰宝" }, { "gui bi", "规避" }, { "gui bin", "贵宾" }, { "gui cheng", "规程" }, { "gui chui deng", "鬼吹灯" }, { "gui dang", "归档" },
			{ "gui dao", "轨道" }, { "gui dao jiao tong", "轨道交通" }, { "gui de", "贵的" }, { "gui di", "跪地" }, { "gui dian", "贵点" }, { "gui ding", "规定" },
			{ "gui dui", "归队" }, { "gui fan", "规范" }, { "gui fan guan li", "规范管理" }, { "gui fan hua", "规范化" }, { "gui fan xing", "规范性" }, { "gui fang", "贵方" },
			{ "gui fang", "闺房" }, { "gui fei", "规费" }, { "gui fei", "贵妃" }, { "gui fu", "贵妇" }, { "gui ge", "规格" }, { "gui ge xing hao", "规格型号" },
			{ "gui gen dao di", "归根到底" }, { "gui gen jie di", "归根结底" }, { "gui gong", "归功" }, { "gui gong si", "贵公司" }, { "gui gu", "硅谷" },
			{ "gui gu shi", "鬼故事" }, { "gui guai", "鬼怪" }, { "gui guan", "桂冠" }, { "gui gui", "鬼鬼" }, { "gui gui", "龟龟" }, { "gui guo", "归国" },
			{ "gui hua", "桂花" }, { "gui hua", "规划" }, { "gui hua", "鬼话" }, { "gui hua bian zhi", "规划编制" }, { "gui hua gang yao", "规划纲要" },
			{ "gui hua jian she", "规划建设" }, { "gui hua ju", "规划局" }, { "gui hua she ji", "规划设计" }, { "gui huan", "归还" }, { "gui hun", "鬼混" },
			{ "gui hun", "鬼魂" }, { "gui ji", "诡计" }, { "gui ji", "轨迹" }, { "gui jian", "贵贱" }, { "gui jiao", "硅胶" }, { "gui jie", "归结" },
			{ "gui jin shu", "贵金属" }, { "gui jiu", "归咎" }, { "gui ju", "规矩" }, { "gui kou", "归口" }, { "gui lai", "归来" }, { "gui lao", "鬼佬" },
			{ "gui lei", "归类" }, { "gui li", "瑰丽" }, { "gui lian", "鬼脸" }, { "gui lin", "桂林" }, { "gui lin shi", "桂林市" }, { "gui lv", "规律" },
			{ "gui lv xing", "规律性" }, { "gui mei", "鬼魅" }, { "gui mo", "规模" }, { "gui mo hua", "规模化" }, { "gui mo yi shang", "规模以上" },
			{ "gui mo zui da", "规模最大" }, { "gui na", "归纳" }, { "gui nv", "闺女" }, { "gui pian", "鬼片" }, { "gui qi", "鬼泣" }, { "gui qiu", "跪求" },
			{ "gui qu", "归去" }, { "gui ren", "贵人" }, { "gui ru", "归入" }, { "gui shen", "鬼神" }, { "gui shu", "归属" }, { "gui shu di", "归属地" },
			{ "gui shu gan", "归属感" }, { "gui su", "归宿" }, { "gui tai", "柜台" }, { "gui tou", "龟头" }, { "gui wang", "鬼王" }, { "gui wei", "归为" },
			{ "gui xia", "跪下" }, { "gui xiao", "贵校" }, { "gui xing", "贵姓" }, { "gui yang", "贵阳" }, { "gui yang shi", "贵阳市" }, { "gui yi", "皈依" },
			{ "gui yi", "诡异" }, { "gui yu", "归于" }, { "gui yuan", "柜员" }, { "gui zai", "跪在" }, { "gui ze", "规则" }, { "gui zhan", "贵站" }, { "gui zhang", "规章" },
			{ "gui zhang zhi du", "规章制度" }, { "gui zhe", "跪着" }, { "gui zhi", "规制" }, { "gui zhong", "贵重" }, { "gui zhou", "贵州" }, { "gui zhou sheng", "贵州省" },
			{ "gui zi", "柜子" }, { "gui zi", "鬼子" }, { "gui zi shou", "刽子手" }, { "gui zu", "贵族" }, { "gun", "丨" }, { "gun", "惃" }, { "gun", "棍" },
			{ "gun", "棞" }, { "gun", "滚" }, { "gun", "滾" }, { "gun", "璭" }, { "gun", "磙" }, { "gun", "绲" }, { "gun", "蔉" }, { "gun", "衮" }, { "gun", "袞" },
			{ "gun", "輥" }, { "gun", "辊" }, { "gun", "鯀" }, { "gun", "鲧" }, { "gun chu", "滚出" }, { "gun dan", "滚蛋" }, { "gun dong", "滚动" },
			{ "gun dong tiao", "滚动条" }, { "gun gun", "滚滚" }, { "gun lun", "滚轮" }, { "gun shi", "滚石" }, { "gun tang", "滚烫" }, { "gun tong", "滚筒" },
			{ "gun zi", "棍子" }, { "guo", "呙" }, { "guo", "嘓" }, { "guo", "囗" }, { "guo", "国" }, { "guo", "圀" }, { "guo", "國" }, { "guo", "埚" }, { "guo", "墎" },
			{ "guo", "崞" }, { "guo", "帼" }, { "guo", "幗" }, { "guo", "彉" }, { "guo", "惈" }, { "guo", "慖" }, { "guo", "掴" }, { "guo", "摑" }, { "guo", "果" },
			{ "guo", "椁" }, { "guo", "槨" }, { "guo", "涡" }, { "guo", "淉" }, { "guo", "漍" }, { "guo", "猓" }, { "guo", "瘑" }, { "guo", "簂" }, { "guo", "粿" },
			{ "guo", "聒" }, { "guo", "聝" }, { "guo", "菓" }, { "guo", "蔮" }, { "guo", "虢" }, { "guo", "蜾" }, { "guo", "蝈" }, { "guo", "裹" }, { "guo", "褁" },
			{ "guo", "过" }, { "guo", "過" }, { "guo", "郭" }, { "guo", "鍋" }, { "guo", "鐹" }, { "guo", "锅" }, { "guo", "馘" }, { "guo an", "国安" },
			{ "guo ao", "国奥" }, { "guo ao dui", "国奥队" }, { "guo ba", "锅巴" }, { "guo ban", "过半" }, { "guo bao", "国宝" }, { "guo biao", "国标" },
			{ "guo bu liao", "过不了" }, { "guo bu qu", "过不去" }, { "guo ce", "国策" }, { "guo chan", "国产" }, { "guo chan che", "国产车" }, { "guo chan hua", "国产化" },
			{ "guo chan pin pai", "国产品牌" }, { "guo chan shou ji", "国产手机" }, { "guo chang", "过场" }, { "guo chang", "过长" }, { "guo cheng", "过程" },
			{ "guo cui", "国粹" }, { "guo cuo", "过错" }, { "guo da", "过大" }, { "guo dao", "国道" }, { "guo dao", "过道" }, { "guo de", "过得" },
			{ "guo de gang", "郭德纲" }, { "guo de qu", "过得去" }, { "guo di", "过低" }, { "guo di", "锅底" }, { "guo dian", "国电" }, { "guo dong", "果冻" },
			{ "guo dong", "过冬" }, { "guo du", "国度" }, { "guo du", "过度" }, { "guo du", "过渡" }, { "guo du qi", "过渡期" }, { "guo duan", "果断" },
			{ "guo duan", "过段" }, { "guo duo", "过多" }, { "guo fang", "国防" }, { "guo fang bu", "国防部" }, { "guo fang bu zhang", "国防部长" },
			{ "guo fang sheng", "国防生" }, { "guo fen", "国分" }, { "guo fen", "过份" }, { "guo fen", "过分" }, { "guo fu", "国富" }, { "guo fu cheng", "郭富城" },
			{ "guo gai", "锅盖" }, { "guo gan", "果敢" }, { "guo gao", "过高" }, { "guo ge", "国歌" }, { "guo gong", "国共" }, { "guo guan", "过关" },
			{ "guo guang", "国光" }, { "guo guo", "果果" }, { "guo guo", "蝈蝈" }, { "guo guo", "过过" }, { "guo hang", "国航" }, { "guo hao", "过好" },
			{ "guo he", "过河" }, { "guo hou", "过后" }, { "guo hu", "过户" }, { "guo hua", "国华" }, { "guo hua", "国画" }, { "guo hui", "国会" },
			{ "guo hui er", "过会儿" }, { "guo huo", "国货" }, { "guo huo", "过活" }, { "guo huo", "过火" }, { "guo ji", "国籍" }, { "guo ji", "国际" }, { "guo ji", "过激" },
			{ "guo ji biao zhun", "国际标准" }, { "guo ji ci", "过几次" }, { "guo ji fa", "国际法" }, { "guo ji guan li", "国际惯例" }, { "guo ji guan xi", "国际关系" },
			{ "guo ji guo nei", "国际国内" }, { "guo ji he zuo", "国际合作" }, { "guo ji hua", "国际化" }, { "guo ji huan jing", "国际环境" }, { "guo ji hui yi", "国际会议" },
			{ "guo ji ji chang", "国际机场" }, { "guo ji ji piao", "国际机票" }, { "guo ji jiao liu", "国际交流" }, { "guo ji jin rong", "国际金融" },
			{ "guo ji jing ji", "国际经济" }, { "guo ji jing zheng", "国际竞争" }, { "guo ji mao yi", "国际贸易" }, { "guo ji mi lan", "国际米兰" },
			{ "guo ji min sheng", "国计民生" }, { "guo ji pin pai", "国际品牌" }, { "guo ji she hui", "国际社会" }, { "guo ji shi chang", "国际市场" },
			{ "guo ji shi wu", "国际事务" }, { "guo ji shou zhi", "国际收支" }, { "guo ji tian", "过几天" }, { "guo ji xiang qi", "国际象棋" }, { "guo ji xing", "国际性" },
			{ "guo ji xing shi", "国际形势" }, { "guo ji you jia", "国际油价" }, { "guo ji yu ming", "国际域名" }, { "guo ji zheng zhi", "国际政治" },
			{ "guo ji zhi ming", "国际知名" }, { "guo ji zhu ming", "国际著名" }, { "guo ji zi ben", "国际资本" }, { "guo ji zu lian", "国际足联" },
			{ "guo ji zu zhi", "国际组织" }, { "guo jia", "国家" }, { "guo jia", "郭嘉" }, { "guo jia an quan", "国家安全" }, { "guo jia biao zhun", "国家标准" },
			{ "guo jia cai zheng", "国家财政" }, { "guo jia di li", "国家地理" }, { "guo jia dui", "国家队" }, { "guo jia fa lv", "国家法律" }, { "guo jia fa zhan", "国家发展" },
			{ "guo jia gui ding", "国家规定" }, { "guo jia ji", "国家级" }, { "guo jia ji guan", "国家机关" }, { "guo jia ji wei", "国家计委" },
			{ "guo jia jing ji", "国家经济" }, { "guo jia ju", "国家局" }, { "guo jia li yi", "国家利益" }, { "guo jia quan li", "国家权力" }, { "guo jia tong yi", "国家统一" },
			{ "guo jia yi ji", "国家一级" }, { "guo jia zhan lue", "国家战略" }, { "guo jia zheng ce", "国家政策" }, { "guo jia zheng quan", "国家政权" },
			{ "guo jia zhong dian", "国家重点" }, { "guo jiang", "果酱" }, { "guo jiang", "过奖" }, { "guo jiang", "过江" }, { "guo jiao", "国脚" }, { "guo jie", "国界" },
			{ "guo jie", "过节" }, { "guo jing", "过境" }, { "guo jing", "郭靖" }, { "guo jing jing", "郭晶晶" }, { "guo jing ming", "郭敬明" }, { "guo jun", "国军" },
			{ "guo jun", "国君" }, { "guo ke", "过客" }, { "guo ku", "国库" }, { "guo kuai", "过快" }, { "guo lai", "过来" }, { "guo lai ren", "过来人" },
			{ "guo le", "过了" }, { "guo li", "国力" }, { "guo li", "国立" }, { "guo li", "锅里" }, { "guo liang", "过量" }, { "guo liang tian", "过两天" },
			{ "guo lu", "过路" }, { "guo lu", "锅炉" }, { "guo lv", "国旅" }, { "guo lv", "过滤" }, { "guo lv qi", "过滤器" }, { "guo ma", "过吗" }, { "guo mao", "国贸" },
			{ "guo mei", "国美" }, { "guo mei dian qi", "国美电器" }, { "guo men", "国门" }, { "guo mi", "国米" }, { "guo min", "国民" }, { "guo min", "过敏" },
			{ "guo min dang", "国民党" }, { "guo min fan ying", "过敏反应" }, { "guo min jing ji", "国民经济" }, { "guo min xing", "过敏性" },
			{ "guo min zheng fu", "国民政府" }, { "guo mo ruo", "郭沫若" }, { "guo mu", "过目" }, { "guo nei", "国内" }, { "guo nei", "锅内" }, { "guo nei qi ye", "国内企业" },
			{ "guo nei shi chang", "国内市场" }, { "guo nei wai", "国内外" }, { "guo nei zhi ming", "国内知名" }, { "guo nei zhu ming", "国内著名" },
			{ "guo nei zui da", "国内最大" }, { "guo ni", "过你" }, { "guo nian", "过年" }, { "guo nong", "果农" }, { "guo pi", "果皮" }, { "guo pin", "果品" },
			{ "guo qi", "国企" }, { "guo qi", "国旗" }, { "guo qi", "过期" }, { "guo qi", "过气" }, { "guo qi gai ge", "国企改革" }, { "guo qiang", "国强" },
			{ "guo qiao", "过桥" }, { "guo qing", "国庆" }, { "guo qing", "国情" }, { "guo qing jie", "国庆节" }, { "guo qu", "过去" }, { "guo ran", "果然" },
			{ "guo ran shi", "果然是" }, { "guo re", "过热" }, { "guo ren", "国人" }, { "guo ren", "过人" }, { "guo ri zi", "过日子" }, { "guo rou", "果肉" },
			{ "guo shan che", "过山车" }, { "guo shang", "过上" }, { "guo shao", "过少" }, { "guo sheng", "过剩" }, { "guo sheng ri", "过生日" }, { "guo shi", "国事" },
			{ "guo shi", "国士" }, { "guo shi", "果实" }, { "guo shi", "过世" }, { "guo shi", "过失" }, { "guo shi", "过时" }, { "guo shu", "果树" }, { "guo shu", "果蔬" },
			{ "guo shui", "国税" }, { "guo shui ju", "国税局" }, { "guo tai", "国泰" }, { "guo tai jun an", "国泰君安" }, { "guo tai ming", "郭台铭" }, { "guo tou", "国投" },
			{ "guo tou", "过头" }, { "guo tu", "国土" }, { "guo tu ju", "国土局" }, { "guo tu zi yuan", "国土资源" }, { "guo wai", "国外" }, { "guo wan", "过万" },
			{ "guo wan", "过完" }, { "guo wan", "过弯" }, { "guo wang", "国王" }, { "guo wang", "过往" }, { "guo wen", "过问" }, { "guo wo", "过我" }, { "guo wu", "国务" },
			{ "guo wu qing", "国务卿" }, { "guo wu yuan", "国务院" }, { "guo xie", "过些" }, { "guo xin", "国信" }, { "guo xue", "国学" }, { "guo ye", "过夜" },
			{ "guo yi", "过亿" }, { "guo yi bu qu", "过意不去" }, { "guo yin", "过瘾" }, { "guo ying", "国营" }, { "guo ying", "过硬" }, { "guo ying qi ye", "国营企业" },
			{ "guo you", "国有" }, { "guo you gu", "国有股" }, { "guo you jing ji", "国有经济" }, { "guo you qi ye", "国有企业" }, { "guo you tu di", "国有土地" },
			{ "guo you yin hang", "国有银行" }, { "guo you zi ben", "国有资本" }, { "guo you zi chan", "国有资产" }, { "guo yu", "国语" }, { "guo yu", "过于" },
			{ "guo yuan", "果园" }, { "guo zao", "过早" }, { "guo zhai", "国债" }, { "guo zhao", "过招" }, { "guo zhe", "裹着" }, { "guo zhe", "过着" },
			{ "guo zhen", "果真" }, { "guo zhi", "国之" }, { "guo zhi", "果汁" }, { "guo zhong", "过重" }, { "guo zhong", "锅中" }, { "guo zi", "国资" },
			{ "guo zi", "果子" }, { "guo zi wei", "国资委" }, { "guo zu", "国足" }, { "ha", "哈" }, { "ha", "虾" }, { "ha", "蛤" }, { "ha", "铪" }, { "ha da", "哈达" },
			{ "ha er", "哈尔" }, { "ha er bin", "哈尔滨" }, { "ha er bin shi", "哈尔滨市" }, { "ha fei", "哈飞" }, { "ha fo", "哈佛" }, { "ha fo da xue", "哈佛大学" },
			{ "ha gen da si", "哈根达斯" }, { "ha gong da", "哈工大" }, { "ha ha", "哈哈" }, { "ha ha da xiao", "哈哈大笑" }, { "ha ha ha", "哈哈哈" },
			{ "ha ha ha ha", "哈哈哈哈" }, { "ha han", "哈韩" }, { "ha ka", "哈卡" }, { "ha li", "哈利" }, { "ha li", "哈里" }, { "ha li bo te", "哈利波特" },
			{ "ha lou", "哈喽" }, { "ha luo", "哈罗" }, { "ha ma", "蛤蟆" }, { "ha ma si", "哈马斯" }, { "ha mi", "哈密" }, { "ha mi gua", "哈密瓜" }, { "ha ni", "哈尼" },
			{ "ha po", "哈珀" }, { "ha qian", "哈欠" }, { "ha shi", "哈市" }, { "ha shi qi", "哈士奇" }, { "ha te", "哈特" }, { "hai", "亥" }, { "hai", "侅" },
			{ "hai", "咳" }, { "hai", "嗐" }, { "hai", "嗨" }, { "hai", "嘿" }, { "hai", "塰" }, { "hai", "孩" }, { "hai", "害" }, { "hai", "氦" }, { "hai", "海" },
			{ "hai", "烸" }, { "hai", "絯" }, { "hai", "胲" }, { "hai", "还" }, { "hai", "還" }, { "hai", "醢" }, { "hai", "餀" }, { "hai", "駭" }, { "hai", "駴" },
			{ "hai", "骇" }, { "hai", "骸" }, { "hai an", "海岸" }, { "hai an xian", "海岸线" }, { "hai ba", "海拔" }, { "hai ba", "还把" }, { "hai bao", "海报" },
			{ "hai bao", "海豹" }, { "hai bei", "还被" }, { "hai bian", "海边" }, { "hai bin", "海滨" }, { "hai bo", "海波" }, { "hai bu", "还不" },
			{ "hai bu shi", "还不是" }, { "hai bu zhi dao", "还不知道" }, { "hai cha", "还差" }, { "hai chan pin", "海产品" }, { "hai chao", "海潮" }, { "hai cheng", "海城" },
			{ "hai chong", "害虫" }, { "hai chu", "害处" }, { "hai da", "海大" }, { "hai da", "还大" }, { "hai dai", "海带" }, { "hai dai", "还带" }, { "hai dao", "海岛" },
			{ "hai dao", "海盗" }, { "hai dao", "海道" }, { "hai dao chuan", "海盗船" }, { "hai de", "害得" }, { "hai de", "海德" }, { "hai de", "还得" },
			{ "hai dei", "还得" }, { "hai di", "海地" }, { "hai di", "海底" }, { "hai dian", "海淀" }, { "hai dian qu", "海淀区" }, { "hai dui", "还对" },
			{ "hai duo", "还多" }, { "hai er", "孩儿" }, { "hai er", "海尔" }, { "hai feng", "海峰" }, { "hai feng", "海风" }, { "hai gan", "还敢" }, { "hai gang", "海港" },
			{ "hai gao", "还高" }, { "hai gei", "还给" }, { "hai guan", "海关" }, { "hai guan zong shu", "海关总署" }, { "hai gui", "海归" }, { "hai gui", "海龟" },
			{ "hai gui", "还贵" }, { "hai hai", "海海" }, { "hai hang", "海航" }, { "hai hao", "还好" }, { "hai hao ma", "还好吗" }, { "hai he", "海河" },
			{ "hai he", "还和" }, { "hai hen", "还很" }, { "hai hui", "还会" }, { "hai hui you", "还会有" }, { "hai ji de wo", "还记得我" }, { "hai jiang", "还将" },
			{ "hai jiao", "海角" }, { "hai jiao", "还叫" }, { "hai jing", "海景" }, { "hai jun", "海军" }, { "hai kan", "还看" }, { "hai ke", "还可" },
			{ "hai kou", "海口" }, { "hai kou shi", "海口市" }, { "hai kuai", "还快" }, { "hai kuo tian kong", "海阔天空" }, { "hai lai", "还来" }, { "hai lang", "海浪" },
			{ "hai li", "海里" }, { "hai liang", "海量" }, { "hai long", "海龙" }, { "hai lun", "海伦" }, { "hai luo", "海螺" }, { "hai luo yin", "海洛因" },
			{ "hai ma", "海马" }, { "hai mei", "还没" }, { "hai men", "海门" }, { "hai mian", "海绵" }, { "hai mian", "海面" }, { "hai ming wei", "海明威" },
			{ "hai nan", "海南" }, { "hai nan dao", "海南岛" }, { "hai nan sheng", "海南省" }, { "hai nei", "海内" }, { "hai nei wai", "海内外" }, { "hai neng", "还能" },
			{ "hai ning", "海宁" }, { "hai ou", "海鸥" }, { "hai pa", "害怕" }, { "hai pa", "还怕" }, { "hai qing", "还请" }, { "hai qu", "海区" }, { "hai qu", "还去" },
			{ "hai rang", "还让" }, { "hai ren", "害人" }, { "hai ren", "骇人" }, { "hai shang", "海上" }, { "hai shao", "还少" }, { "hai shen", "海参" },
			{ "hai shen", "海神" }, { "hai sheng", "还剩" }, { "hai shi", "海事" }, { "hai shi", "还是" }, { "hai shi hen", "还是很" }, { "hai shi ju", "海事局" },
			{ "hai shi mei you", "还是没有" }, { "hai shi yong", "还是用" }, { "hai shui", "海水" }, { "hai shuo", "还说" }, { "hai si", "害死" }, { "hai suan", "还算" },
			{ "hai tan", "海滩" }, { "hai tang", "海棠" }, { "hai tao", "海涛" }, { "hai tian", "海天" }, { "hai ting", "还挺" }, { "hai tong", "孩童" },
			{ "hai tong", "海通" }, { "hai tong zheng quan", "海通证券" }, { "hai tun", "海豚" }, { "hai wai", "海外" }, { "hai wai hua ren", "海外华人" },
			{ "hai wai shang shi", "海外上市" }, { "hai wai shi chang", "海外市场" }, { "hai wai tou zi", "海外投资" } };
};
