package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN26 {
	public static String[][] pl = { { "kai fang xing", "开放性" }, { "kai feng", "开封" }, { "kai ge", "凯歌" }, { "kai ge", "开个" }, { "kai gong", "开工" },
			{ "kai gong jian she", "开工建设" }, { "kai gong si", "开公司" }, { "kai guan", "开关" }, { "kai guan dian yuan", "开关电源" }, { "kai guang", "开光" },
			{ "kai guo", "开国" }, { "kai guo", "开过" }, { "kai hao", "开好" }, { "kai hu", "开户" }, { "kai hu hang", "开户行" }, { "kai hua", "开花" },
			{ "kai huai", "开怀" }, { "kai huang", "开荒" }, { "kai hui", "开会" }, { "kai huo", "开火" }, { "kai ji", "开机" }, { "kai jia", "开价" },
			{ "kai jia", "开家" }, { "kai jia", "铠甲" }, { "kai jiang", "开奖" }, { "kai jin", "开进" }, { "kai ju", "开具" }, { "kai ju", "开局" }, { "kai juan", "开卷" },
			{ "kai kai", "开开" }, { "kai kai xin xin", "开开心心" }, { "kai kao", "开考" }, { "kai ke", "开课" }, { "kai ken", "开垦" }, { "kai kou", "开口" },
			{ "kai kuo", "开阔" }, { "kai lai", "开来" }, { "kai lang", "开朗" }, { "kai li", "凯利" }, { "kai li", "开立" }, { "kai lie", "开裂" }, { "kai lu", "开路" },
			{ "kai luo", "开罗" }, { "kai ma", "开骂" }, { "kai man", "开满" }, { "kai mei rui", "凯美瑞" }, { "kai men", "开门" }, { "kai men hong", "开门红" },
			{ "kai ming", "开明" }, { "kai mo", "楷模" }, { "kai mu", "开幕" }, { "kai mu shi", "开幕式" }, { "kai pai", "开拍" }, { "kai pan", "开盘" },
			{ "kai pan jia", "开盘价" }, { "kai pao", "开炮" }, { "kai pi", "开辟" }, { "kai pian", "开篇" }, { "kai piao", "开票" }, { "kai ping", "开平" },
			{ "kai qi", "开启" }, { "kai qi", "开起" }, { "kai qiang", "开枪" }, { "kai qiao", "开窍" }, { "kai qiu", "开球" }, { "kai qu", "开去" }, { "kai sa", "凯撒" },
			{ "kai sai", "开赛" }, { "kai se lin", "凯瑟琳" }, { "kai shan", "开山" }, { "kai she", "开设" }, { "kai shen me", "开什么" }, { "kai shi", "开始" },
			{ "kai shi", "开市" }, { "kai shi cai dan", "开始菜单" }, { "kai shi shi shi", "开始实施" }, { "kai shi shi yong", "开始使用" }, { "kai shi zuo", "开始做" },
			{ "kai shu", "楷书" }, { "kai shui", "开水" }, { "kai suo", "开锁" }, { "kai tan", "慨叹" }, { "kai te", "凯特" }, { "kai ti", "开题" }, { "kai ti", "楷体" },
			{ "kai ti bao gao", "开题报告" }, { "kai ting", "开庭" }, { "kai ting shen li", "开庭审理" }, { "kai tong", "开通" }, { "kai tou", "开头" }, { "kai tuo", "开拓" },
			{ "kai tuo", "开脱" }, { "kai tuo chuang xin", "开拓创新" }, { "kai tuo shi chang", "开拓市场" }, { "kai tuo zhe", "开拓者" }, { "kai wa", "开挖" },
			{ "kai wai", "开外" }, { "kai wan", "开完" }, { "kai wan xiao", "开玩笑" }, { "kai wang", "开往" }, { "kai wei", "开胃" }, { "kai wen", "凯文" },
			{ "kai xian", "开县" }, { "kai xiang", "开箱" }, { "kai xiao", "开销" }, { "kai xin", "开心" }, { "kai xin", "开新" }, { "kai xin guo", "开心果" },
			{ "kai xin jiu hao", "开心就好" }, { "kai xing", "开行" }, { "kai xuan", "凯旋" }, { "kai xue", "开学" }, { "kai ye", "开业" }, { "kai yi jia", "开一家" },
			{ "kai yuan", "开元" }, { "kai yuan", "开源" }, { "kai yuan ruan jian", "开源软件" }, { "kai yue", "凯越" }, { "kai zhan", "开展" }, { "kai zhan", "开战" },
			{ "kai zhan gong zuo", "开展工作" }, { "kai zhan ye wu", "开展业务" }, { "kai zhang", "开张" }, { "kai zhe", "开着" }, { "kai zheng", "开征" },
			{ "kai zhi", "开支" }, { "kai zi", "凯子" }, { "kai zou", "开走" }, { "kan", "丬" }, { "kan", "侃" }, { "kan", "刊" }, { "kan", "勘" }, { "kan", "坎" },
			{ "kan", "堪" }, { "kan", "墈" }, { "kan", "崁" }, { "kan", "嵌" }, { "kan", "戡" }, { "kan", "栞" }, { "kan", "槛" }, { "kan", "檻" }, { "kan", "看" },
			{ "kan", "瞰" }, { "kan", "矙" }, { "kan", "砍" }, { "kan", "磡" }, { "kan", "竷" }, { "kan", "莰" }, { "kan", "衎" }, { "kan", "轗" }, { "kan", "阚" },
			{ "kan", "顑" }, { "kan", "龛" }, { "kan a", "看啊" }, { "kan ba", "看吧" }, { "kan bi", "堪比" }, { "kan bing", "看病" }, { "kan bing nan", "看病难" },
			{ "kan bu", "看不" }, { "kan bu chu", "看不出" }, { "kan bu chu lai", "看不出来" }, { "kan bu dao", "看不到" }, { "kan bu dong", "看不懂" },
			{ "kan bu guan", "看不惯" }, { "kan bu jian", "看不见" }, { "kan bu qi", "看不起" }, { "kan bu qing", "看不清" }, { "kan bu qing chu", "看不清楚" },
			{ "kan bu shang", "看不上" }, { "kan bu xia qu", "看不下去" }, { "kan ce", "勘测" }, { "kan cha", "勘察" }, { "kan cha", "勘查" }, { "kan cha she ji", "勘察设计" },
			{ "kan chai", "砍柴" }, { "kan che", "看车" }, { "kan cheng", "堪称" }, { "kan cheng", "看成" }, { "kan chu", "刊出" }, { "kan chu", "看出" },
			{ "kan chu lai", "看出来" }, { "kan chuan", "看穿" }, { "kan cuo", "看错" }, { "kan dai", "看待" }, { "kan dan", "看淡" }, { "kan dao", "看到" },
			{ "kan dao", "砍刀" }, { "kan de", "看得" }, { "kan de chu", "看得出" }, { "kan de dao", "看得到" }, { "kan de jian", "看得见" }, { "kan de qi", "看得起" },
			{ "kan deng", "刊登" }, { "kan dian", "看点" }, { "kan dian shi", "看电视" }, { "kan dian ying", "看电影" }, { "kan diao", "砍掉" }, { "kan die", "看碟" },
			{ "kan dong", "看懂" }, { "kan duo", "看多" }, { "kan fa", "刊发" }, { "kan fa", "看法" }, { "kan fa", "砍伐" }, { "kan fang", "看房" },
			{ "kan feng jing", "看风景" }, { "kan ge", "看个" }, { "kan guan", "看官" }, { "kan guan", "看管" }, { "kan guo", "看过" }, { "kan guo lai", "看过来" },
			{ "kan hai", "看海" }, { "kan hao", "看好" }, { "kan hou", "看后" }, { "kan hu", "看护" }, { "kan jia", "看家" }, { "kan jia", "砍价" }, { "kan jian", "看见" },
			{ "kan kai", "看开" }, { "kan kan", "侃侃" }, { "kan kan", "看看" }, { "kan kan ba", "看看吧" }, { "kan kan er tan", "侃侃而谈" }, { "kan ke", "坎坷" },
			{ "kan ke", "看客" }, { "kan kong", "看空" }, { "kan lai", "看来" }, { "kan le", "看了" }, { "kan le kan", "看了看" }, { "kan mei nv", "看美女" },
			{ "kan men", "看门" }, { "kan na", "看那" }, { "kan ni", "看你" }, { "kan pan", "看盘" }, { "kan pian", "看片" }, { "kan po", "看破" }, { "kan qi", "看起" },
			{ "kan qi", "看齐" }, { "kan qi lai", "看起来" }, { "kan qing", "看清" }, { "kan qing chu", "看清楚" }, { "kan qiu", "看球" }, { "kan qu", "看去" },
			{ "kan re nao", "看热闹" }, { "kan ren", "看人" }, { "kan ren", "砍人" }, { "kan shang", "看上" }, { "kan shang qu", "看上去" }, { "kan shen me", "看什么" },
			{ "kan shi", "看是" }, { "kan shou", "看守" }, { "kan shou suo", "看守所" }, { "kan shu", "看书" }, { "kan shui", "看谁" }, { "kan si", "看似" },
			{ "kan si", "砍死" }, { "kan tai", "看台" }, { "kan tan", "勘探" }, { "kan tie", "看帖" }, { "kan tie", "看贴" }, { "kan tou", "看头" }, { "kan tou", "看透" },
			{ "kan tu", "看图" }, { "kan wan", "看完" }, { "kan wan le", "看完了" }, { "kan wang", "看望" }, { "kan wen ti", "看问题" }, { "kan wo", "看我" },
			{ "kan wu", "刊物" }, { "kan xi", "看戏" }, { "kan xia", "看下" }, { "kan xia", "砍下" }, { "kan xia qu", "看下去" }, { "kan xiang", "看向" },
			{ "kan xiao shuo", "看小说" }, { "kan xin wen", "看新闻" }, { "kan yang zi", "看样子" }, { "kan yi kan", "看一看" }, { "kan yi sheng", "看医生" },
			{ "kan yi xia", "看一下" }, { "kan yong", "刊用" }, { "kan you", "堪忧" }, { "kan zai", "刊载" }, { "kan zai", "看在" }, { "kan zhang", "看涨" },
			{ "kan zhe", "看着" }, { "kan zhe", "看这" }, { "kan zhe ban", "看着办" }, { "kan zhe ni", "看着你" }, { "kan zhe ta", "看着他" }, { "kan zhe wo", "看着我" },
			{ "kan zhong", "看中" }, { "kan zhong", "看重" }, { "kan zhun", "看准" }, { "kan zuo", "看作" }, { "kan zuo", "看做" }, { "kang", "亢" }, { "kang", "伉" },
			{ "kang", "匟" }, { "kang", "囥" }, { "kang", "嫝" }, { "kang", "康" }, { "kang", "慷" }, { "kang", "扛" }, { "kang", "抗" }, { "kang", "摃" },
			{ "kang", "漮" }, { "kang", "炕" }, { "kang", "犺" }, { "kang", "糠" }, { "kang", "邟" }, { "kang", "鈧" }, { "kang", "鏮" }, { "kang", "钪" },
			{ "kang", "閌" }, { "kang", "闶" }, { "kang", "鱇" }, { "kang ai", "抗癌" }, { "kang bing", "抗病" }, { "kang bing du", "抗病毒" }, { "kang de", "康德" },
			{ "kang die", "抗跌" }, { "kang ding", "康定" }, { "kang fen", "亢奋" }, { "kang fu", "康复" }, { "kang gan rao", "抗干扰" }, { "kang han", "抗旱" },
			{ "kang heng", "抗衡" }, { "kang hong", "抗洪" }, { "kang ji", "抗击" }, { "kang jia", "康佳" }, { "kang ju", "抗拒" }, { "kang jun", "抗菌" },
			{ "kang kai", "慷慨" }, { "kang kang", "康康" }, { "kang le", "康乐" }, { "kang mei yuan chao", "抗美援朝" }, { "kang ning", "康宁" }, { "kang qiao", "康桥" },
			{ "kang ri", "抗日" }, { "kang ri zhan zheng", "抗日战争" }, { "kang sheng su", "抗生素" }, { "kang shi fu", "康师傅" }, { "kang shuai lao", "抗衰老" },
			{ "kang ti", "抗体" }, { "kang xi", "康熙" }, { "kang xing", "抗性" }, { "kang yang hua", "抗氧化" }, { "kang yi", "抗议" }, { "kang yuan", "抗原" },
			{ "kang zai", "抗灾" }, { "kang zhan", "抗战" }, { "kang zhe", "扛着" }, { "kang zhen", "抗震" }, { "kang zhen jiu zai", "抗震救灾" }, { "kang zheng", "抗争" },
			{ "kao", "尻" }, { "kao", "拷" }, { "kao", "攷" }, { "kao", "栲" }, { "kao", "洘" }, { "kao", "烤" }, { "kao", "犒" }, { "kao", "稾" }, { "kao", "考" },
			{ "kao", "薧" }, { "kao", "銬" }, { "kao", "铐" }, { "kao", "靠" }, { "kao bei", "拷贝" }, { "kao bei", "靠背" }, { "kao bei dao", "拷贝到" },
			{ "kao bian", "靠边" }, { "kao bo", "考博" }, { "kao bu zhu", "靠不住" }, { "kao cha", "考察" }, { "kao cha", "考查" }, { "kao cha tuan", "考察团" },
			{ "kao chang", "考场" }, { "kao chuang", "靠窗" }, { "kao da xue", "考大学" }, { "kao de", "考得" }, { "kao dian", "考点" }, { "kao dian", "靠垫" },
			{ "kao gong wu yuan", "考公务员" }, { "kao gu", "考古" }, { "kao gu xue jia", "考古学家" }, { "kao guan", "考官" }, { "kao guo", "考过" }, { "kao he", "考核" },
			{ "kao hou", "靠后" }, { "kao ji", "考级" }, { "kao jin", "靠近" }, { "kao jiu", "考究" }, { "kao juan", "考卷" }, { "kao kao", "考考" }, { "kao kao", "靠靠" },
			{ "kao la", "考拉" }, { "kao lao", "犒劳" }, { "kao liang", "考量" }, { "kao long", "靠拢" }, { "kao lu", "考录" }, { "kao lv", "考虑" }, { "kao ping", "考评" },
			{ "kao pu", "靠谱" }, { "kao qi", "烤漆" }, { "kao qian", "考前" }, { "kao qian", "靠前" }, { "kao qiang", "靠墙" }, { "kao qin", "考勤" }, { "kao qu", "考取" },
			{ "kao rou", "烤肉" }, { "kao ru", "考入" }, { "kao shan", "靠山" }, { "kao shang", "考上" }, { "kao shang da xue", "考上大学" }, { "kao sheng", "考生" },
			{ "kao shi", "考试" }, { "kao shi cheng ji", "考试成绩" }, { "kao shi da gang", "考试大纲" }, { "kao shi ke mu", "考试科目" }, { "kao shi shi jian", "考试时间" },
			{ "kao shi shi ti", "考试试题" }, { "kao shi zhong xin", "考试中心" }, { "kao ti", "考题" }, { "kao wan", "考完" }, { "kao wen", "拷问" }, { "kao xiang", "烤箱" },
			{ "kao ya", "烤鸭" }, { "kao yan", "烤烟" }, { "kao yan", "考研" }, { "kao yan", "考验" }, { "kao yu", "烤鱼" }, { "kao zai", "靠在" }, { "kao zhe", "靠着" },
			{ "kao zheng", "考证" }, { "ke", "克" }, { "ke", "刻" }, { "ke", "剋" }, { "ke", "匼" }, { "ke", "可" }, { "ke", "咳" }, { "ke", "嗑" }, { "ke", "坷" },
			{ "ke", "堁" }, { "ke", "壳" }, { "ke", "客" }, { "ke", "岢" }, { "ke", "峇" }, { "ke", "嵑" }, { "ke", "嵙" }, { "ke", "嶱" }, { "ke", "恪" },
			{ "ke", "悈" }, { "ke", "搕" }, { "ke", "敤" }, { "ke", "柯" }, { "ke", "棵" }, { "ke", "榼" }, { "ke", "樖" }, { "ke", "毼" }, { "ke", "氪" },
			{ "ke", "渇" }, { "ke", "渴" }, { "ke", "溘" }, { "ke", "濭" }, { "ke", "牁" }, { "ke", "犐" }, { "ke", "珂" }, { "ke", "疴" }, { "ke", "痾" },
			{ "ke", "瞌" }, { "ke", "砢" }, { "ke", "磆" }, { "ke", "磕" }, { "ke", "科" }, { "ke", "稞" }, { "ke", "窠" }, { "ke", "緙" }, { "ke", "缂" },
			{ "ke", "翗" }, { "ke", "苛" }, { "ke", "萪" }, { "ke", "薖" }, { "ke", "蚵" }, { "ke", "蝌" }, { "ke", "課" }, { "ke", "课" }, { "ke", "趷" },
			{ "ke", "軻" }, { "ke", "轲" }, { "ke", "鈳" }, { "ke", "鉿" }, { "ke", "錒" }, { "ke", "钶" }, { "ke", "锞" }, { "ke", "頦" }, { "ke", "顆" },
			{ "ke", "颏" }, { "ke", "颗" }, { "ke", "騍" }, { "ke", "骒" }, { "ke", "髁" }, { "ke", "龕" }, { "ke ai", "可爱" }, { "ke an", "可按" }, { "ke ban", "刻板" },
			{ "ke bei", "可悲" }, { "ke ben", "课本" }, { "ke bi", "可比" }, { "ke bi", "科比" }, { "ke bi xing", "可比性" }, { "ke bian", "可变" },
			{ "ke bian cheng", "可编程" }, { "ke biao", "课表" }, { "ke bie", "可别" }, { "ke bo", "刻薄" }, { "ke bu", "可不" }, { "ke bu ke yi", "可不可以" },
			{ "ke bu rong huan", "刻不容缓" }, { "ke cai yong", "可采用" }, { "ke cao zuo xing", "可操作性" }, { "ke ceng", "可曾" }, { "ke cha", "可查" },
			{ "ke chang", "客场" }, { "ke che", "客车" }, { "ke cheng", "课程" }, { "ke cheng gai ge", "课程改革" }, { "ke cheng she ji", "课程设计" },
			{ "ke cheng she zhi", "课程设置" }, { "ke chi", "可耻" }, { "ke chi xu", "可持续" }, { "ke chi xu xing", "可持续性" }, { "ke chuan", "客串" },
			{ "ke cong", "可从" }, { "ke da", "可达" }, { "ke da", "柯达" }, { "ke da", "科大" }, { "ke da dao", "可达到" }, { "ke dang", "可当" }, { "ke dao", "可到" },
			{ "ke de", "可得" }, { "ke dou", "蝌蚪" }, { "ke du", "刻度" }, { "ke du xing", "可读性" }, { "ke dui", "可对" }, { "ke dui", "客队" }, { "ke duo", "可多" },
			{ "ke er", "克尔" }, { "ke er", "可儿" }, { "ke er", "科尔" }, { "ke fang", "客房" }, { "ke fen", "可分" }, { "ke fen wei", "可分为" }, { "ke fou", "可否" },
			{ "ke fu", "克服" }, { "ke fu", "客服" }, { "ke fu", "科夫" }, { "ke fu dian hua", "客服电话" }, { "ke fu kun nan", "克服困难" }, { "ke fu ren yuan", "客服人员" },
			{ "ke fu zhong xin", "客服中心" }, { "ke gai", "课改" }, { "ke gen ju", "可根据" }, { "ke gong", "可供" }, { "ke gu ming xin", "刻骨铭心" }, { "ke guan", "可观" },
			{ "ke guan", "客观" }, { "ke guan cun zai", "客观存在" }, { "ke guan gui lv", "客观规律" }, { "ke guan xing", "客观性" }, { "ke gui", "可贵" },
			{ "ke hao", "可好" }, { "ke hen", "可恨" }, { "ke hou", "课后" }, { "ke hu", "客户" }, { "ke hu duan", "客户端" }, { "ke hu fu wu", "客户服务" },
			{ "ke hu guan xi", "客户关系" }, { "ke hu ji", "客户机" }, { "ke hu jing li", "客户经理" }, { "ke hu qun", "客户群" }, { "ke hu ti gong", "客户提供" },
			{ "ke hu xu qiu", "客户需求" }, { "ke hu yao qiu", "客户要求" }, { "ke hu zi yuan", "客户资源" }, { "ke hua", "刻画" }, { "ke huan", "科幻" },
			{ "ke huan pian", "科幻片" }, { "ke huo", "可获" }, { "ke huo de", "可获得" }, { "ke ji", "客机" }, { "ke ji", "科技" }, { "ke ji bu", "科技部" },
			{ "ke ji cheng guo", "科技成果" }, { "ke ji chuang xin", "科技创新" }, { "ke ji da xue", "科技大学" }, { "ke ji fa zhan", "科技发展" },
			{ "ke ji gong si", "科技公司" }, { "ke ji gong zuo", "科技工作" }, { "ke ji gu", "科技股" }, { "ke ji guan", "科技馆" }, { "ke ji han liang", "科技含量" },
			{ "ke ji he zuo", "科技合作" }, { "ke ji jin bu", "科技进步" }, { "ke ji ju", "科技局" }, { "ke ji ren cai", "科技人才" }, { "ke ji ren yuan", "科技人员" },
			{ "ke ji xing", "科技型" }, { "ke ji yuan", "科技园" }, { "ke ji yuan qu", "科技园区" }, { "ke jia", "客家" }, { "ke jia ren", "客家人" }, { "ke jian", "可见" },
			{ "ke jian", "课件" }, { "ke jian", "课间" }, { "ke jian yi ban", "可见一斑" }, { "ke jiang", "可将" }, { "ke jiao", "科教" }, { "ke jiao xue", "课教学" },
			{ "ke jie shou", "可接受" }, { "ke jing", "可敬" }, { "ke jiu", "可就" }, { "ke ju", "科举" }, { "ke kan", "可看" }, { "ke kao", "可靠" }, { "ke kao", "科考" },
			{ "ke kao xing", "可靠性" }, { "ke ke", "可可" }, { "ke ke", "咳咳" }, { "ke ke", "苛刻" }, { "ke ke xi li", "可可西里" }, { "ke kong", "可控" },
			{ "ke kou", "克扣" }, { "ke kou", "可口" }, { "ke kou ke le", "可口可乐" }, { "ke ku", "刻苦" }, { "ke kuo zhan", "可扩展" }, { "ke kuo zhan xing", "可扩展性" },
			{ "ke la", "克拉" }, { "ke la ke", "克拉克" }, { "ke la ma yi", "克拉玛依" }, { "ke lai", "克莱" }, { "ke lai si le", "克莱斯勒" }, { "ke le", "可乐" },
			{ "ke lei si bo", "克雷斯波" }, { "ke li", "克里" }, { "ke li", "颗粒" }, { "ke li si", "克里斯" }, { "ke li yong", "可利用" }, { "ke lian", "可怜" },
			{ "ke lin dun", "克林顿" }, { "ke lin si man", "克林斯曼" }, { "ke liu", "客流" }, { "ke liu liang", "客流量" }, { "ke long", "克隆" }, { "ke long", "科隆" },
			{ "ke long", "科龙" }, { "ke lu", "刻录" }, { "ke lu ji", "刻录机" }, { "ke lu pan", "刻录盘" }, { "ke lu si", "克鲁斯" }, { "ke luo", "克罗" },
			{ "ke luo di ya", "克罗地亚" }, { "ke mao", "科贸" }, { "ke mei", "可没" }, { "ke mu", "科目" }, { "ke na", "可那" }, { "ke nan", "柯南" }, { "ke neng", "可能" },
			{ "ke neng cheng wei", "可能成为" }, { "ke neng chu xian", "可能出现" }, { "ke neng fa sheng", "可能发生" }, { "ke neng mei you", "可能没有" },
			{ "ke neng xing", "可能性" }, { "ke ni", "可逆" }, { "ke pa", "可怕" }, { "ke pan", "刻盘" }, { "ke piao", "客票" }, { "ke pu", "科普" }, { "ke qi", "可气" },
			{ "ke qi", "客气" }, { "ke qian", "课前" }, { "ke qin", "可亲" }, { "ke qiu", "渴求" }, { "ke qiu", "苛求" }, { "ke qu", "可取" },
			{ "ke quan ke dian", "可圈可点" }, { "ke rang", "可让" }, { "ke ren", "可人" }, { "ke ren", "客人" }, { "ke shang", "客商" }, { "ke shang", "课上" },
			{ "ke shen qing", "可申请" }, { "ke shi", "可使" }, { "ke shi", "可是" }, { "ke shi", "可视" }, { "ke shi", "科室" }, { "ke shi", "课时" },
			{ "ke shi hua", "可视化" }, { "ke shi xian", "可实现" }, { "ke shi yong", "可使用" }, { "ke shou", "恪守" }, { "ke shu", "棵树" }, { "ke shui", "瞌睡" },
			{ "ke shuo", "可说" }, { "ke si", "克斯" }, { "ke si", "科斯" }, { "ke sou", "咳嗽" }, { "ke su xing", "可塑性" }, { "ke suan", "可算" },
			{ "ke suo wo", "科索沃" }, { "ke ta", "可他" }, { "ke tang", "课堂" }, { "ke tang jiao xue", "课堂教学" }, { "ke tao", "客套" }, { "ke te bu si", "科特布斯" },
			{ "ke te di wa", "科特迪瓦" }, { "ke ti", "客体" }, { "ke ti", "课题" }, { "ke ti gong", "可提供" }, { "ke ti yan jiu", "课题研究" }, { "ke ti zu", "课题组" },
			{ "ke tiao", "可调" }, { "ke ting", "客厅" }, { "ke ting li", "客厅里" }, { "ke tou", "磕头" }, { "ke wai", "课外" }, { "ke wang", "可望" },
			{ "ke wang", "渴望" }, { "ke wei", "可为" }, { "ke wei", "可谓" }, { "ke wei", "科委" }, { "ke wei qi", "科维奇" }, { "ke wei te", "科威特" },
			{ "ke wen", "课文" }, { "ke wo", "可我" }, { "ke wu", "可恶" }, { "ke xi", "可喜" }, { "ke xi", "可惜" }, { "ke xian", "可先" }, { "ke xiang", "可向" },
			{ "ke xiang er zhi", "可想而知" }, { "ke xiang shou", "可享受" }, { "ke xiao", "可笑" }, { "ke xie", "科协" }, { "ke xin", "可信" }, { "ke xin du", "可信度" },
			{ "ke xing", "克星" }, { "ke xing", "可行" }, { "ke xing", "颗星" }, { "ke xing xing", "可行性" }, { "ke xuan", "可选" }, { "ke xuan ze", "可选择" },
			{ "ke xue", "科学" }, { "ke xue fa zhan", "科学发展" }, { "ke xue guan li", "科学管理" }, { "ke xue hua", "科学化" }, { "ke xue ji shu", "科学技术" },
			{ "ke xue jia", "科学家" }, { "ke xue jie", "科学界" }, { "ke xue jing shen", "科学精神" }, { "ke xue xing", "科学性" }, { "ke xue yan jiu", "科学研究" },
			{ "ke xue yi ju", "科学依据" }, { "ke xue yuan", "科学院" }, { "ke xue zhi shi", "科学知识" }, { "ke xun", "可循" }, { "ke yan", "可言" }, { "ke yan", "科研" },
			{ "ke yan cheng guo", "科研成果" }, { "ke yan dan wei", "科研单位" }, { "ke yan gong zuo", "科研工作" }, { "ke yan ji gou", "科研机构" },
			{ "ke yan ren yuan", "科研人员" }, { "ke yan xiang mu", "科研项目" }, { "ke yan yuan suo", "科研院所" }, { "ke yao", "可要" }, { "ke yi", "刻意" },
			{ "ke yi", "可以" }, { "ke yi", "可依" }, { "ke yi", "可疑" }, { "ke yi bang zhu", "可以帮助" }, { "ke yi cai yong", "可以采用" }, { "ke yi cha kan", "可以查看" },
			{ "ke yi chi", "可以吃" }, { "ke yi da", "可以打" }, { "ke yi da dao", "可以达到" }, { "ke yi de dao", "可以得到" }, { "ke yi fang", "可以放" },
			{ "ke yi fen wei", "可以分为" }, { "ke yi gen ju", "可以根据" }, { "ke yi huan", "可以换" }, { "ke yi huo de", "可以获得" }, { "ke yi jie shou", "可以接受" },
			{ "ke yi kan chu", "可以看出" }, { "ke yi kan dao", "可以看到" }, { "ke yi kan jian", "可以看见" }, { "ke yi kao lv", "可以考虑" }, { "ke yi li jie", "可以理解" },
			{ "ke yi li yong", "可以利用" }, { "ke yi ma", "可以吗" }, { "ke yi mai", "可以买" }, { "ke yi mai dao", "可以买到" }, { "ke yi man zu", "可以满足" },
			{ "ke yi min", "柯以敏" }, { "ke yi na", "可以拿" }, { "ke yi shang wang", "可以上网" }, { "ke yi shen qing", "可以申请" }, { "ke yi shi xian", "可以实现" },
			{ "ke yi shi yong", "可以使用" }, { "ke yi shuo shi", "可以说是" }, { "ke yi sui shi", "可以随时" }, { "ke yi ti gong", "可以提供" }, { "ke yi tong guo", "可以通过" },
			{ "ke yi xia zai", "可以下载" }, { "ke yi xian shi", "可以显示" }, { "ke yi xiang shou", "可以享受" }, { "ke yi xuan ze", "可以选择" }, { "ke yi yong", "可以用" },
			{ "ke yi yong lai", "可以用来" }, { "ke yi yong yu", "可以用于" }, { "ke yi zeng jia", "可以增加" }, { "ke yi zhao dao", "可以找到" }, { "ke yi zhi jie", "可以直接" },
			{ "ke yi zuo wei", "可以作为" }, { "ke yong", "可用" }, { "ke yong xing", "可用性" }, { "ke yong yu", "可用于" }, { "ke you", "刻有" }, { "ke you", "可有" },
			{ "ke you", "可由" }, { "ke you ke wu", "可有可无" }, { "ke yu", "可与" }, { "ke yu", "课余" }, { "ke yuan", "客源" }, { "ke yuan", "科员" }, { "ke yun", "客运" },
			{ "ke yun zhan", "客运站" }, { "ke yun zhuan xian", "客运专线" }, { "ke zai", "刻在" }, { "ke zai", "可在" }, { "ke zhan", "客栈" }, { "ke zhang", "科长" },
			{ "ke zhe", "刻着" }, { "ke zhe", "可这" }, { "ke zhen", "可真" }, { "ke zhi", "克制" }, { "ke zhi", "可治" }, { "ke zhi", "可知" }, { "ke zhi jie", "可直接" },
			{ "ke zhi wu", "科植物" }, { "ke zhi xing", "可执行" }, { "ke zhuan zhai", "可转债" }, { "ke zhuo", "课桌" }, { "ke zi", "壳子" }, { "ke zuo", "可作" },
			{ "ke zuo", "可做" }, { "kei", "剋" }, { "kei", "勀" }, { "kei", "尅" }, { "ken", "啃" }, { "ken", "垦" }, { "ken", "墾" }, { "ken", "恳" }, { "ken", "懇" },
			{ "ken", "掯" }, { "ken", "肯" }, { "ken", "裉" }, { "ken", "錹" }, { "ken", "龈" }, { "ken de ji", "肯德基" }, { "ken ding", "肯定" }, { "ken en", "肯恩" },
			{ "ken ni di", "肯尼迪" }, { "ken ni ya", "肯尼亚" }, { "ken qing", "恳请" }, { "ken qiu", "恳求" }, { "keng", "吭" }, { "keng", "坑" }, { "keng", "牼" },
			{ "keng", "硻" }, { "keng", "脛" }, { "keng", "誙" }, { "keng", "銵" }, { "keng", "鍞" }, { "keng", "鏗" }, { "keng", "铿" }, { "keng", "阬" },
			{ "keng li", "坑里" }, { "keng nei", "坑内" }, { "keng qiang", "铿锵" }, { "keng sheng", "吭声" }, { "kong", "倥" }, { "kong", "孔" }, { "kong", "崆" },
			{ "kong", "恐" }, { "kong", "悾" }, { "kong", "控" }, { "kong", "硿" }, { "kong", "空" }, { "kong", "箜" }, { "kong", "錓" }, { "kong", "鞚" },
			{ "kong bai", "空白" }, { "kong bu", "恐怖" }, { "kong bu fen zi", "恐怖分子" }, { "kong bu pian", "恐怖片" }, { "kong bu xi ji", "恐怖袭击" },
			{ "kong bu zhu yi", "恐怖主义" }, { "kong bu zu zhi", "恐怖组织" }, { "kong cang", "空仓" }, { "kong dang", "空档" }, { "kong dang dang", "空荡荡" },
			{ "kong di", "空地" }, { "kong dong", "空洞" }, { "kong fang", "空方" }, { "kong fu", "空腹" }, { "kong gang", "空港" }, { "kong gao", "控告" },
			{ "kong ge", "空格" }, { "kong gu", "控股" }, { "kong gu gong si", "控股公司" }, { "kong gu gu dong", "控股股东" }, { "kong gu ji tuan", "控股集团" },
			{ "kong he", "恐吓" }, { "kong hua", "空话" }, { "kong huang", "恐慌" }, { "kong jian", "控件" }, { "kong jian", "空间" }, { "kong jian zhan", "空间站" },
			{ "kong jiang", "空降" }, { "kong jie", "空姐" }, { "kong ju", "恐惧" }, { "kong ju gan", "恐惧感" }, { "kong ju zheng", "恐惧症" }, { "kong jun", "空军" },
			{ "kong ke", "空壳" }, { "kong ke", "空客" }, { "kong kong", "空空" }, { "kong kuang", "空旷" }, { "kong ling", "空灵" }, { "kong long", "恐龙" },
			{ "kong men", "空门" }, { "kong ming", "孔明" }, { "kong nan", "空难" }, { "kong pa", "恐怕" }, { "kong pan", "控盘" }, { "kong qi", "空气" },
			{ "kong qi wu ran", "空气污染" }, { "kong qi zhi liang", "空气质量" }, { "kong qian", "空前" }, { "kong qiu", "控球" }, { "kong que", "孔雀" },
			{ "kong que", "空缺" }, { "kong shou", "空手" }, { "kong shou dao", "空手道" }, { "kong su", "控诉" }, { "kong tan", "空谈" }, { "kong tiao", "空调" },
			{ "kong tiao wei xiu", "空调维修" }, { "kong tou", "空头" }, { "kong tou", "空投" }, { "kong wei", "空位" }, { "kong wen", "控温" },
			{ "kong wu yi ren", "空无一人" }, { "kong xi", "空袭" }, { "kong xi", "空隙" }, { "kong xian", "空闲" }, { "kong xiang", "空想" }, { "kong xin", "空心" },
			{ "kong xu", "空虚" }, { "kong xue lai feng", "空穴来风" }, { "kong you", "控油" }, { "kong yu", "空余" }, { "kong yun", "空运" }, { "kong zhan", "空战" },
			{ "kong zhe", "空着" }, { "kong zhi", "控制" }, { "kong zhi", "空置" }, { "kong zhi ji shu", "控制技术" }, { "kong zhi li", "控制力" },
			{ "kong zhi mian ban", "控制面板" }, { "kong zhi qi", "控制器" }, { "kong zhi quan", "控制权" }, { "kong zhi tai", "控制台" }, { "kong zhi xi tong", "控制系统" },
			{ "kong zhi zhong xin", "控制中心" }, { "kong zhi zhu", "控制住" }, { "kong zhong", "空中" }, { "kong zi", "孔子" }, { "kong zi", "空子" },
			{ "kong zi xue yuan", "孔子学院" } };
};
