package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN01 {
	public static String[][] pl = { { "a", "吖" }, { "a", "呵" }, { "a", "啊" }, { "a", "嗄" }, { "a", "腌" }, { "a", "锕" }, { "a", "阿" }, { "a a", "啊啊" },
			{ "a a a", "啊啊啊" }, { "a a a a", "啊啊啊啊" }, { "a ba", "阿坝" }, { "a ba si", "阿巴斯" }, { "a bao", "阿宝" }, { "a bian", "阿扁" }, { "a bo luo", "阿波罗" },
			{ "a bu", "阿布" }, { "a da", "阿达" }, { "a dai", "阿呆" }, { "a de", "阿德" }, { "a di", "阿迪" }, { "a di da si", "阿迪达斯" }, { "a dou", "阿斗" },
			{ "a du", "阿杜" }, { "a duo", "阿朵" }, { "a er", "阿尔" }, { "a er fa", "阿尔法" }, { "a er ka te", "阿尔卡特" }, { "a er si tong", "阿尔斯通" },
			{ "a fei", "阿飞" }, { "a fu", "阿福" }, { "a fu han", "阿富汗" }, { "a gan", "阿甘" }, { "a ge", "阿哥" }, { "a gen ting", "阿根廷" },
			{ "a gen ting dui", "阿根廷队" }, { "a ha", "啊哈" }, { "a han", "阿含" }, { "a hua", "阿华" }, { "a jiao", "阿娇" }, { "a jie", "阿姐" }, { "a ka", "阿卡" },
			{ "a kui na", "阿奎那" }, { "a la", "阿拉" }, { "a la bo", "阿拉伯" }, { "a la bo ren", "阿拉伯人" }, { "a la fa te", "阿拉法特" }, { "a la si jia", "阿拉斯加" },
			{ "a la xi", "阿拉希" }, { "a lan", "阿兰" }, { "a li", "阿里" }, { "a li ba ba", "阿里巴巴" }, { "a lian", "阿联" }, { "a lian qiu", "阿联酋" },
			{ "a long", "阿龙" }, { "a long suo", "阿隆索" }, { "a lun", "阿伦" }, { "a ma", "阿妈" }, { "a man", "阿曼" }, { "a mao", "阿毛" }, { "a mei", "阿妹" },
			{ "a mei", "阿梅" }, { "a men", "阿门" }, { "a mi", "阿弥" }, { "a mi", "阿米" }, { "a ming", "阿明" }, { "a mu", "阿木" }, { "a ni", "阿尼" },
			{ "a nuo", "阿诺" }, { "a po", "阿婆" }, { "a qiang", "阿强" }, { "a san", "阿三" }, { "a sen na", "阿森纳" }, { "a si", "阿斯" }, { "a si dun", "阿斯顿" },
			{ "a si pi lin", "阿司匹林" }, { "a tu", "阿土" }, { "a wen", "阿文" }, { "a xin", "阿信" }, { "a xiu luo", "阿修罗" }, { "a ya", "啊呀" }, { "a ya", "阿雅" },
			{ "a yi", "阿姨" }, { "a yo", "啊哟" }, { "a zhu", "阿朱" }, { "a zi", "阿紫" }, { "ai", "僾" }, { "ai", "呆" }, { "ai", "哀" }, { "ai", "哎" }, { "ai", "唉" },
			{ "ai", "啀" }, { "ai", "嗌" }, { "ai", "嗳" }, { "ai", "噯" }, { "ai", "埃" }, { "ai", "壒" }, { "ai", "娭" }, { "ai", "嫒" }, { "ai", "嬡" },
			{ "ai", "愛" }, { "ai", "挨" }, { "ai", "捱" }, { "ai", "敳" }, { "ai", "昹" }, { "ai", "暧" }, { "ai", "曖" }, { "ai", "欸" }, { "ai", "毐" },
			{ "ai", "溰" }, { "ai", "溾" }, { "ai", "爱" }, { "ai", "瑷" }, { "ai", "璦" }, { "ai", "癌" }, { "ai", "皑" }, { "ai", "皚" }, { "ai", "瞹" },
			{ "ai", "矮" }, { "ai", "砹" }, { "ai", "碍" }, { "ai", "礙" }, { "ai", "艾" }, { "ai", "蔼" }, { "ai", "薆" }, { "ai", "藹" }, { "ai", "譪" },
			{ "ai", "鑀" }, { "ai", "锿" }, { "ai", "隘" }, { "ai", "霭" }, { "ai", "靄" }, { "ai", "餲" }, { "ai", "騃" }, { "ai", "鴱" }, { "ai ai", "唉唉" },
			{ "ai ai", "爱爱" }, { "ai ai", "皑皑" }, { "ai bu ai", "爱不爱" }, { "ai bu shi shou", "爱不释手" }, { "ai che", "爱车" }, { "ai cheng", "爱城" },
			{ "ai chi", "爱吃" }, { "ai chou", "哀愁" }, { "ai da", "挨打" }, { "ai dai", "爱戴" }, { "ai dao", "哀悼" }, { "ai dao", "爱到" }, { "ai de", "爱得" },
			{ "ai de", "爱的" }, { "ai de hua", "爱德华" }, { "ai de ren", "爱的人" }, { "ai di sheng", "爱迪生" }, { "ai e", "挨饿" }, { "ai er", "埃尔" },
			{ "ai er", "艾尔" }, { "ai er lan", "爱尔兰" }, { "ai fu", "爱抚" }, { "ai fu dun", "埃弗顿" }, { "ai fu sen", "艾弗森" }, { "ai ge", "挨个" },
			{ "ai guo", "爱国" }, { "ai guo", "爱过" }, { "ai guo zhe", "爱国者" }, { "ai guo zhu yi", "爱国主义" }, { "ai hao", "哀嚎" }, { "ai hao", "爱好" },
			{ "ai hao zhe", "爱好者" }, { "ai hen", "爱恨" }, { "ai hu", "爱护" }, { "ai hua", "爱华" }, { "ai ji", "埃及" }, { "ai jia", "爱家" }, { "ai ka", "爱卡" },
			{ "ai kan", "爱看" }, { "ai le", "挨了" }, { "ai li ke sen", "埃里克森" }, { "ai li she", "爱丽舍" }, { "ai li si", "爱丽丝" }, { "ai li xin", "爱立信" },
			{ "ai lian", "爱怜" }, { "ai lian", "爱恋" }, { "ai lun", "艾伦" }, { "ai ma", "挨骂" }, { "ai mei", "暧昧" }, { "ai mei", "爱美" }, { "ai min", "爱民" },
			{ "ai mu", "爱慕" }, { "ai ni", "爱你" }, { "ai pu sheng", "爱普生" }, { "ai qi", "爱妻" }, { "ai qin hai", "爱琴海" }, { "ai qing", "爱情" },
			{ "ai qing gu shi", "爱情故事" }, { "ai qing guan", "爱情观" }, { "ai qing pian", "爱情片" }, { "ai qing shi", "爱情是" }, { "ai qiu", "哀求" },
			{ "ai quan", "爱犬" }, { "ai ren", "爱人" }, { "ai ren", "矮人" }, { "ai rui", "艾瑞" }, { "ai shang", "哀伤" }, { "ai shang", "爱上" },
			{ "ai shang ta", "爱上他" }, { "ai shang wo", "爱上我" }, { "ai shang yi ge", "爱上一个" }, { "ai shen", "爱神" }, { "ai sheng huo", "爱生活" },
			{ "ai shi", "爱是" }, { "ai si", "爱死" }, { "ai ta", "爱他" }, { "ai ta", "爱她" }, { "ai tan", "哀叹" }, { "ai ting", "爱听" }, { "ai tuo ao", "埃托奥" },
			{ "ai wan", "爱玩" }, { "ai wei er", "艾薇儿" }, { "ai wo", "爱我" }, { "ai xi", "爱惜" }, { "ai xi bao", "癌细胞" }, { "ai xiao", "爱笑" }, { "ai xiao", "矮小" },
			{ "ai xin", "爱心" }, { "ai ya", "哎呀" }, { "ai ya ya", "哎呀呀" }, { "ai yi", "爱意" }, { "ai yi ge ren", "爱一个人" }, { "ai yin huo wen", "埃因霍温" },
			{ "ai yin si tan", "爱因斯坦" }, { "ai yo", "哎哟" }, { "ai you", "哎呦" }, { "ai yu", "爱与" }, { "ai yu", "碍于" }, { "ai yuan", "哀怨" }, { "ai zai", "爱在" },
			{ "ai ze la si", "艾泽拉斯" }, { "ai zhe", "挨着" }, { "ai zhe", "爱着" }, { "ai zhe ni", "爱着你" }, { "ai zheng", "癌症" }, { "ai zhi", "爱之" },
			{ "ai zi", "爱子" }, { "ai zi", "矮子" }, { "ai zi", "艾滋" }, { "ai zi bing", "爱滋病" }, { "ai zi bing", "艾滋病" }, { "ai zi ji", "爱自己" }, { "an", "侒" },
			{ "an", "俺" }, { "an", "儑" }, { "an", "厂" }, { "an", "唵" }, { "an", "啽" }, { "an", "垵" }, { "an", "埯" }, { "an", "安" }, { "an", "岸" },
			{ "an", "峖" }, { "an", "广" }, { "an", "庵" }, { "an", "按" }, { "an", "揞" }, { "an", "暗" }, { "an", "案" }, { "an", "桉" }, { "an", "氨" },
			{ "an", "犴" }, { "an", "盦" }, { "an", "胺" }, { "an", "腤" }, { "an", "荌" }, { "an", "萻" }, { "an", "諳" }, { "an", "谙" }, { "an", "豻" },
			{ "an", "銨" }, { "an", "錌" }, { "an", "铵" }, { "an", "闇" }, { "an", "雸" }, { "an", "鞍" }, { "an", "韽" }, { "an", "馣" }, { "an", "鮟" },
			{ "an", "鵪" }, { "an", "鹌" }, { "an", "黯" }, { "an an", "安安" }, { "an an", "暗暗" }, { "an an jing jing", "安安静静" }, { "an bao", "安保" },
			{ "an bei", "安倍" }, { "an bi li", "按比例" }, { "an bian", "岸边" }, { "an bu jiu ban", "按部就班" }, { "an cang", "暗藏" }, { "an chu", "暗处" },
			{ "an chuang", "暗疮" }, { "an chun", "鹌鹑" }, { "an ci", "按此" }, { "an da", "安达" }, { "an dan", "暗淡" }, { "an dan", "黯淡" }, { "an de", "安得" },
			{ "an de", "安德" }, { "an de lu", "安德鲁" }, { "an de sen", "安德森" }, { "an di", "安迪" }, { "an di", "暗地" }, { "an di li", "暗地里" }, { "an ding", "安定" },
			{ "an dong ni", "安东尼" }, { "an dun", "安顿" }, { "an fa", "案发" }, { "an fang", "安放" }, { "an fang", "安防" }, { "an fang", "暗访" }, { "an fen", "安分" },
			{ "an fu", "安抚" }, { "an gang", "鞍钢" }, { "an ge", "安格" }, { "an ge la", "安哥拉" }, { "an gui ding", "按规定" }, { "an hao", "安好" }, { "an hao", "暗号" },
			{ "an hei", "暗黑" }, { "an hong se", "暗红色" }, { "an hui", "安徽" }, { "an hui sheng", "安徽省" }, { "an ji", "安吉" }, { "an ji", "氨基" },
			{ "an ji suan", "氨基酸" }, { "an jia", "俺家" }, { "an jia", "安家" }, { "an jian", "安检" }, { "an jian", "安监" }, { "an jian", "按键" },
			{ "an jian", "案件" }, { "an jian ju", "安监局" }, { "an jie", "按揭" }, { "an jie dai kuan", "按揭贷款" }, { "an jing", "安静" }, { "an ju", "安居" },
			{ "an ju le ye", "安居乐业" }, { "an juan", "案卷" }, { "an kang", "安康" }, { "an le", "安乐" }, { "an le si", "安乐死" }, { "an li", "安利" },
			{ "an li", "按理" }, { "an li", "案例" }, { "an li fen xi", "案例分析" }, { "an li hui", "安理会" }, { "an li shuo", "按理说" }, { "an lian", "暗恋" },
			{ "an liu", "暗流" }, { "an lu", "安陆" }, { "an men", "俺们" }, { "an mian yao", "安眠药" }, { "an mo", "按摩" }, { "an mo qi", "按摩器" }, { "an mu", "暗牧" },
			{ "an na", "安娜" }, { "an na bu zhu", "按捺不住" }, { "an nan", "安南" }, { "an ni", "安妮" }, { "an ning", "安宁" }, { "an niu", "按钮" }, { "an pai", "安排" },
			{ "an pai hao", "安排好" }, { "an qi", "安琪" }, { "an qi", "按其" }, { "an qi", "按期" }, { "an qi", "暗器" }, { "an qie luo di", "安切洛蒂" },
			{ "an qing", "安庆" }, { "an qing", "案情" }, { "an quan", "安全" }, { "an quan bao zhang", "安全保障" }, { "an quan cuo shi", "安全措施" },
			{ "an quan dai", "安全带" }, { "an quan di yi", "安全第一" }, { "an quan fang fan", "安全防范" }, { "an quan fang hu", "安全防护" },
			{ "an quan fang mian", "安全方面" }, { "an quan gan", "安全感" }, { "an quan gong zuo", "安全工作" }, { "an quan guan li", "安全管理" },
			{ "an quan ji shu", "安全技术" }, { "an quan jian cha", "安全检查" }, { "an quan jian guan", "安全监管" }, { "an quan jiao yu", "安全教育" },
			{ "an quan ke kao", "安全可靠" }, { "an quan lou dong", "安全漏洞" }, { "an quan qi", "安全期" }, { "an quan qi nang", "安全气囊" },
			{ "an quan sheng chan", "安全生产" }, { "an quan shi gu", "安全事故" }, { "an quan tao", "安全套" }, { "an quan wei shi", "安全卫士" },
			{ "an quan wen ti", "安全问题" }, { "an quan xing", "安全性" }, { "an quan xing neng", "安全性能" }, { "an quan yi shi", "安全意识" },
			{ "an quan yin huan", "安全隐患" }, { "an ran", "安然" }, { "an ran", "黯然" }, { "an ran wu yang", "安然无恙" }, { "an sha", "暗杀" }, { "an shan", "鞍山" },
			{ "an shan shi", "鞍山市" }, { "an shang", "岸上" }, { "an shen", "安神" }, { "an sheng", "安生" }, { "an shi", "按时" }, { "an shi", "暗示" },
			{ "an shun", "安顺" }, { "an shun xu", "按顺序" }, { "an shuo", "按说" }, { "an suan", "暗算" }, { "an tai", "安泰" }, { "an tu sheng", "安徒生" },
			{ "an wei", "安危" }, { "an wei", "安慰" }, { "an wen", "安稳" }, { "an xi", "安息" }, { "an xi", "安溪" }, { "an xia", "按下" }, { "an xian", "岸线" },
			{ "an xiang", "安详" }, { "an xiang", "暗香" }, { "an xiang cao zuo", "暗箱操作" }, { "an xin", "安信" }, { "an xin", "安心" }, { "an xu", "按需" },
			{ "an ya", "按压" }, { "an yang", "安阳" }, { "an yao qiu", "按要求" }, { "an ye", "暗夜" }, { "an yi", "安逸" }, { "an ying", "暗影" }, { "an yuan", "按原" },
			{ "an yue", "按月" }, { "an zai", "安在" }, { "an zang", "安葬" }, { "an zhao", "按照" }, { "an zhao gui ding", "按照规定" }, { "an zhe", "按着" },
			{ "an zhen", "安贞" }, { "an zhi", "安置" }, { "an zhong", "暗中" }, { "an zhong", "案中" }, { "an zhu", "按住" }, { "an zhuang", "安装" },
			{ "an zhuang bao", "安装包" }, { "an zhuang cheng xu", "安装程序" }, { "an zhuang guo cheng", "安装过程" }, { "an zhuang mu lu", "安装目录" },
			{ "an zhuang pan", "安装盘" }, { "an zhuang wan", "安装完" }, { "an zhuang wen jian", "安装文件" }, { "an zi", "暗自" }, { "an zi", "案子" }, { "ang", "昂" },
			{ "ang", "昻" }, { "ang", "盎" }, { "ang", "肮" }, { "ang", "醠" }, { "ang", "骯" }, { "ang da", "昂达" }, { "ang gui", "昂贵" }, { "ang ran", "盎然" },
			{ "ang si", "盎司" }, { "ang yang", "昂扬" }, { "ang zang", "肮脏" }, { "ao", "傲" }, { "ao", "凹" }, { "ao", "嗷" }, { "ao", "坳" }, { "ao", "墺" },
			{ "ao", "奡" }, { "ao", "奥" }, { "ao", "奧" }, { "ao", "媪" }, { "ao", "岙" }, { "ao", "岰" }, { "ao", "嶴" }, { "ao", "廒" }, { "ao", "懊" },
			{ "ao", "扷" }, { "ao", "拗" }, { "ao", "擙" }, { "ao", "敖" }, { "ao", "柪" }, { "ao", "滶" }, { "ao", "澳" }, { "ao", "熬" }, { "ao", "爊" },
			{ "ao", "獒" }, { "ao", "璈" }, { "ao", "翱" }, { "ao", "聱" }, { "ao", "艹" }, { "ao", "芺" }, { "ao", "蔜" }, { "ao", "螯" }, { "ao", "袄" },
			{ "ao", "襖" }, { "ao", "謷" }, { "ao", "遨" }, { "ao", "鏊" }, { "ao", "鏖" }, { "ao", "镺" }, { "ao", "隞" }, { "ao", "骜" }, { "ao", "鰲" },
			{ "ao", "鳌" }, { "ao", "鼇" }, { "ao ao", "嗷嗷" }, { "ao ba", "奥巴" }, { "ao da li ya", "澳大利亚" }, { "ao dao", "熬到" }, { "ao di", "奥迪" },
			{ "ao di li", "奥地利" }, { "ao dong", "敖东" }, { "ao er", "奥尔" }, { "ao ge", "奥格" }, { "ao guo", "熬过" }, { "ao hui", "懊悔" }, { "ao ke lan", "奥克兰" },
			{ "ao ke si", "奥克斯" }, { "ao la", "奥拉" }, { "ao lan duo", "奥兰多" }, { "ao lin ba si", "奥林巴斯" }, { "ao lin pi ke", "奥林匹克" }, { "ao man", "傲慢" },
			{ "ao mei", "奥美" }, { "ao men", "澳门" }, { "ao mi", "奥秘" }, { "ao miao", "奥妙" }, { "ao nao", "懊恼" }, { "ao ni er", "奥尼尔" }, { "ao qi", "傲气" },
			{ "ao shan", "奥山" }, { "ao shi", "傲视" }, { "ao shu", "奥数" }, { "ao shu", "奥术" }, { "ao si ka", "奥斯卡" }, { "ao te", "奥特" }, { "ao te man", "奥特曼" },
			{ "ao tu", "凹凸" }, { "ao tuo", "奥拓" }, { "ao wang", "澳网" }, { "ao wei hui", "奥委会" }, { "ao xian", "凹陷" }, { "ao xiang", "翱翔" }, { "ao ye", "熬夜" },
			{ "ao you", "傲游" }, { "ao you", "遨游" }, { "ao yuan", "澳元" }, { "ao yun", "奥运" }, { "ao yun chang guan", "奥运场馆" }, { "ao yun guan jun", "奥运冠军" },
			{ "ao yun hui", "奥运会" }, { "ao yun huo ju", "奥运火炬" }, { "ao yun sheng huo", "奥运圣火" }, { "ao zhou", "澳洲" }, { "ao zu wei", "奥组委" }, { "ba", "仈" },
			{ "ba", "八" }, { "ba", "叭" }, { "ba", "吧" }, { "ba", "坝" }, { "ba", "壩" }, { "ba", "岜" }, { "ba", "巴" }, { "ba", "弝" }, { "ba", "扒" },
			{ "ba", "把" }, { "ba", "抜" }, { "ba", "拔" }, { "ba", "捌" }, { "ba", "朳" }, { "ba", "灞" }, { "ba", "爸" }, { "ba", "犮" }, { "ba", "疤" },
			{ "ba", "癹" }, { "ba", "矲" }, { "ba", "笆" }, { "ba", "粑" }, { "ba", "罢" }, { "ba", "罷" }, { "ba", "耙" }, { "ba", "胈" }, { "ba", "芭" },
			{ "ba", "茇" }, { "ba", "菝" }, { "ba", "蚆" }, { "ba", "覇" }, { "ba", "豝" }, { "ba", "跋" }, { "ba", "軷" }, { "ba", "釛" }, { "ba", "釟" },
			{ "ba", "钯" }, { "ba", "霸" }, { "ba", "靶" }, { "ba", "魃" }, { "ba", "鲅" }, { "ba", "鼥" }, { "ba ba", "巴巴" }, { "ba ba", "爸爸" }, { "ba ba", "粑粑" },
			{ "ba ba ma ma", "爸爸妈妈" }, { "ba bai", "八百" }, { "ba bao", "八宝" }, { "ba bi", "芭比" }, { "ba bi lun", "巴比伦" }, { "ba bing", "把柄" },
			{ "ba bu de", "巴不得" }, { "ba che", "把车" }, { "ba cheng", "八成" }, { "ba chi", "把持" }, { "ba chu", "拔出" }, { "ba ci", "八次" }, { "ba da", "八大" },
			{ "ba da ling", "八达岭" }, { "ba dao", "把刀" }, { "ba dao", "霸道" }, { "ba di", "巴蒂" }, { "ba di er", "巴蒂尔" }, { "ba dian", "八点" },
			{ "ba dian ban", "八点半" }, { "ba diao", "拔掉" }, { "ba du", "八度" }, { "ba dun", "巴顿" }, { "ba er", "巴尔" }, { "ba fang", "八方" },
			{ "ba fei te", "巴菲特" }, { "ba fen", "八分" }, { "ba gao", "拔高" }, { "ba ge", "八个" }, { "ba ge", "八哥" }, { "ba ge da", "巴格达" },
			{ "ba ge yue", "八个月" }, { "ba gong", "罢工" }, { "ba gua", "八卦" }, { "ba guan", "把关" }, { "ba guo lian jun", "八国联军" }, { "ba hao", "八号" },
			{ "ba hao", "把好" }, { "ba he", "巴赫" }, { "ba hen", "疤痕" }, { "ba hua", "把话" }, { "ba ji", "八级" }, { "ba ji", "吧唧" }, { "ba ji si tan", "巴基斯坦" },
			{ "ba jian", "拔剑" }, { "ba jiao", "八角" }, { "ba jiao", "芭蕉" }, { "ba jie", "八届" }, { "ba jie", "八戒" }, { "ba jie", "巴结" }, { "ba jin", "巴金" },
			{ "ba jiu", "八九" }, { "ba jiu", "把酒" }, { "ba ke", "巴克" }, { "ba la", "巴拉" }, { "ba la ke", "巴拉克" }, { "ba le", "罢了" }, { "ba le si tan", "巴勒斯坦" },
			{ "ba lei", "芭蕾" }, { "ba lei wu", "芭蕾舞" }, { "ba li", "巴里" }, { "ba li", "巴黎" }, { "ba li dao", "巴厘岛" }, { "ba lian", "把脸" }, { "ba lin", "巴林" },
			{ "ba lu", "八路" }, { "ba lu jun", "八路军" }, { "ba ma", "爸妈" }, { "ba men", "把门" }, { "ba mian", "罢免" }, { "ba na", "把那" }, { "ba na ma", "巴拿马" },
			{ "ba ni", "把你" }, { "ba nian", "八年" }, { "ba po", "八婆" }, { "ba qi", "霸气" }, { "ba qian", "八千" }, { "ba qian", "把钱" }, { "ba qiang", "八强" },
			{ "ba qiao", "巴乔" }, { "ba qiu", "把球" }, { "ba quan", "霸权" }, { "ba ren", "把人" }, { "ba ri", "八日" }, { "ba sa", "巴萨" },
			{ "ba sai luo na", "巴塞罗那" }, { "ba shang", "坝上" }, { "ba she", "跋涉" }, { "ba shi", "八十" }, { "ba shi", "巴士" }, { "ba shi nian dai", "八十年代" },
			{ "ba shou", "把守" }, { "ba shou", "把手" }, { "ba shu", "巴蜀" }, { "ba shu", "把书" }, { "ba shui", "把水" }, { "ba si", "巴斯" }, { "ba si teng", "巴斯滕" },
			{ "ba sui", "八岁" }, { "ba ta", "把他" }, { "ba ta", "把她" }, { "ba ta", "把它" }, { "ba tai", "吧台" }, { "ba te", "巴特" }, { "ba tou", "把头" },
			{ "ba wan", "八万" }, { "ba wan", "把玩" }, { "ba wang", "霸王" }, { "ba wang bie ji", "霸王别姬" }, { "ba wei", "八位" }, { "ba wo", "把我" },
			{ "ba wo", "把握" }, { "ba wo hao", "把握好" }, { "ba wo zhu", "把握住" }, { "ba xi", "巴西" }, { "ba xi", "把戏" }, { "ba xi dui", "巴西队" },
			{ "ba xi ren", "巴西人" }, { "ba xia", "拔下" }, { "ba xian", "八仙" }, { "ba xiang", "八项" }, { "ba xiao shi", "八小时" }, { "ba xin", "把心" },
			{ "ba xiu", "罢休" }, { "ba ya", "拔牙" }, { "ba yi", "八一" }, { "ba yi", "巴以" }, { "ba yi dui", "八一队" }, { "ba yi fu", "把衣服" }, { "ba yue", "八月" },
			{ "ba yue fen", "八月份" }, { "ba zhan", "霸占" }, { "ba zhang", "巴掌" }, { "ba zhe", "八折" }, { "ba zhe", "把这" }, { "ba zhong", "八种" },
			{ "ba zhu", "吧主" }, { "ba zhu", "霸主" }, { "ba zi", "八字" }, { "ba zi", "靶子" }, { "bai", "伯" }, { "bai", "佰" }, { "bai", "呗" }, { "bai", "拜" },
			{ "bai", "拝" }, { "bai", "挀" }, { "bai", "捭" }, { "bai", "掰" }, { "bai", "摆" }, { "bai", "擘" }, { "bai", "擺" }, { "bai", "敗" }, { "bai", "柏" },
			{ "bai", "栢" }, { "bai", "白" }, { "bai", "百" }, { "bai", "稗" }, { "bai", "竡" }, { "bai", "粨" }, { "bai", "粺" }, { "bai", "败" },
			{ "bai an ju", "百安居" }, { "bai ba shi", "百八十" }, { "bai bai", "拜拜" }, { "bai bai", "掰掰" }, { "bai bai", "摆摆" }, { "bai bai", "白白" },
			{ "bai bai de", "白白的" }, { "bai ban", "白板" }, { "bai ban", "白班" }, { "bai ban", "百般" }, { "bai bao xiang", "百宝箱" }, { "bai bei", "百倍" },
			{ "bai bi", "败笔" }, { "bai bian", "百变" }, { "bai bu", "摆布" }, { "bai bu", "白布" }, { "bai cai", "白菜" }, { "bai cao", "百草" }, { "bai chi", "白吃" },
			{ "bai chi", "白痴" }, { "bai chu", "摆出" }, { "bai chu", "百出" }, { "bai chuan", "百川" }, { "bai da", "白搭" }, { "bai da", "百搭" }, { "bai dai", "白带" },
			{ "bai dao", "摆到" }, { "bai de", "败德" }, { "bai di", "白底" }, { "bai dian feng", "白癜风" }, { "bai dong", "摆动" }, { "bai du", "拜读" },
			{ "bai du", "摆渡" }, { "bai du", "百度" }, { "bai du sou suo", "百度搜索" }, { "bai du tie ba", "百度贴吧" }, { "bai du zhi dao", "百度知道" },
			{ "bai e luo si", "白俄罗斯" }, { "bai fa", "白发" }, { "bai fan", "白饭" }, { "bai fang", "拜访" }, { "bai fang", "摆放" }, { "bai fei", "白费" },
			{ "bai fen", "白粉" }, { "bai fen", "百分" }, { "bai fen bai", "百分百" }, { "bai fen bi", "百分比" }, { "bai fen dian", "百分点" }, { "bai fen zhi", "百分之" },
			{ "bai fen zhi bai", "百分之百" }, { "bai fen zhi shi", "百分之十" }, { "bai fen zhi yi", "百分之一" }, { "bai fo", "拜佛" }, { "bai ge", "百个" },
			{ "bai gei", "败给" }, { "bai gong", "白宫" }, { "bai gong li", "百公里" }, { "bai gu", "白骨" }, { "bai guang", "白光" }, { "bai guo", "百果" },
			{ "bai hao", "摆好" }, { "bai he", "白鹤" }, { "bai he", "百合" }, { "bai he hua", "百合花" }, { "bai hu", "白狐" }, { "bai hu", "白虎" }, { "bai hua", "白花" },
			{ "bai hua", "白话" }, { "bai hua", "百花" }, { "bai hua hua", "白花花" }, { "bai hua qi fang", "百花齐放" }, { "bai huai", "败坏" }, { "bai hui", "拜会" },
			{ "bai huo", "百货" }, { "bai huo gong si", "百货公司" }, { "bai jia", "百佳" }, { "bai jia", "百家" }, { "bai jia", "败家" }, { "bai jia jiang tan", "百家讲坛" },
			{ "bai jian", "拜见" }, { "bai jie", "白洁" }, { "bai jin", "白金" }, { "bai jing", "白净" }, { "bai jiu", "白酒" }, { "bai ju yi", "白居易" },
			{ "bai kai", "掰开" }, { "bai kai shui", "白开水" }, { "bai ke", "百科" }, { "bai ke quan shu", "百科全书" }, { "bai lan di", "白兰地" },
			{ "bai lao hui", "百老汇" }, { "bai le", "摆了" }, { "bai lei", "败类" }, { "bai li", "百里" }, { "bai lian", "百联" }, { "bai ling", "白领" },
			{ "bai ling", "百灵" }, { "bai lu", "白露" }, { "bai lu", "白鹭" }, { "bai luo bo", "白萝卜" }, { "bai ma", "白马" }, { "bai ma wang zi", "白马王子" },
			{ "bai man", "摆满" }, { "bai mang", "百忙" }, { "bai mao", "白猫" }, { "bai mi", "百米" }, { "bai ming", "摆明" }, { "bai ming", "百名" },
			{ "bai nao hui", "百脑汇" }, { "bai nei zhang", "白内障" }, { "bai nen", "白嫩" }, { "bai nian", "拜年" }, { "bai nian", "百年" }, { "bai nian lai", "百年来" },
			{ "bai nong", "摆弄" }, { "bai pi shu", "白皮书" }, { "bai ping", "摆平" }, { "bai ping heng", "白平衡" }, { "bai qiang", "百强" }, { "bai re hua", "白热化" },
			{ "bai ren", "拜仁" }, { "bai ren", "白人" }, { "bai ren", "百人" }, { "bai ri", "白日" }, { "bai ri", "百日" }, { "bai ri meng", "白日梦" },
			{ "bai se", "白色" }, { "bai se", "百色" }, { "bai sha", "白沙" }, { "bai shang", "摆上" }, { "bai she", "摆设" }, { "bai sheng", "百盛" },
			{ "bai shi", "拜师" }, { "bai shi", "白石" }, { "bai shi", "百事" }, { "bai shi ke le", "百事可乐" }, { "bai shou", "摆手" }, { "bai shou qi jia", "白手起家" },
			{ "bai shui", "白水" }, { "bai si", "百思" }, { "bai si mai", "百思买" }, { "bai song", "白送" }, { "bai su", "败诉" }, { "bai sui", "百岁" },
			{ "bai tai", "百态" }, { "bai tan", "摆摊" }, { "bai tang", "白糖" }, { "bai tian", "白天" }, { "bai tou", "白头" }, { "bai tuo", "拜托" },
			{ "bai tuo", "摆脱" }, { "bai tuo le", "拜托了" }, { "bai wan", "百万" }, { "bai wan fu weng", "百万富翁" }, { "bai wan xiang su", "百万像素" },
			{ "bai wan yuan", "百万元" }, { "bai wei", "百位" }, { "bai wu liao lai", "百无聊赖" }, { "bai xi", "白皙" }, { "bai xi bao", "白细胞" },
			{ "bai xiao jie", "白小姐" }, { "bai xing", "百姓" }, { "bai xue", "白雪" }, { "bai xue bing", "白血病" }, { "bai xue gong zhu", "白雪公主" },
			{ "bai yan", "白眼" }, { "bai yan song", "白岩松" }, { "bai yang", "白杨" }, { "bai yang", "白羊" }, { "bai yang zuo", "白羊座" }, { "bai yi", "白蚁" },
			{ "bai yi", "白衣" }, { "bai yi", "百亿" }, { "bai yin", "白银" }, { "bai yu", "白玉" }, { "bai yu", "百余" }, { "bai yuan", "百元" }, { "bai yun", "白云" },
			{ "bai yun qu", "白云区" }, { "bai yun shan", "白云山" }, { "bai zai", "摆在" }, { "bai zhao", "百兆" }, { "bai zhe", "摆着" }, { "bai zheng", "摆正" },
			{ "bai zhi", "柏芝" }, { "bai zhi", "白纸" }, { "bai zhong", "百种" }, { "bai zhou", "白昼" }, { "ban", "伴" }, { "ban", "办" }, { "ban", "半" },
			{ "ban", "坂" }, { "ban", "姅" }, { "ban", "怑" }, { "ban", "扮" }, { "ban", "扳" }, { "ban", "拌" }, { "ban", "搬" }, { "ban", "攽" }, { "ban", "斑" },
			{ "ban", "斒" }, { "ban", "昄" }, { "ban", "板" }, { "ban", "柈" }, { "ban", "湴" }, { "ban", "版" }, { "ban", "班" }, { "ban", "瓣" }, { "ban", "瘢" },
			{ "ban", "癍" }, { "ban", "粄" }, { "ban", "絆" }, { "ban", "绊" }, { "ban", "舨" }, { "ban", "般" }, { "ban", "蝂" }, { "ban", "螁" }, { "ban", "辦" },
			{ "ban", "鈑" }, { "ban", "鉡" }, { "ban", "钣" }, { "ban", "闆" }, { "ban", "阪" }, { "ban", "靽" }, { "ban", "頒" }, { "ban", "颁" }, { "ban", "魬" } };
};
