package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN31 {
	public static String[][] pl = { { "luo zai", "落在" }, { "luo zhao", "裸照" }, { "luo zhi xiang", "罗志祥" }, { "luo zi", "骡子" }, { "lv", "侣" }, { "lv", "侶" },
			{ "lv", "偻" }, { "lv", "儢" }, { "lv", "勴" }, { "lv", "吕" }, { "lv", "呂" }, { "lv", "哷" }, { "lv", "垏" }, { "lv", "寠" }, { "lv", "屡" },
			{ "lv", "屢" }, { "lv", "履" }, { "lv", "嵂" }, { "lv", "律" }, { "lv", "慮" }, { "lv", "慺" }, { "lv", "捋" }, { "lv", "旅" }, { "lv", "梠" },
			{ "lv", "榈" }, { "lv", "櫚" }, { "lv", "櫨" }, { "lv", "氯" }, { "lv", "滤" }, { "lv", "率" }, { "lv", "瘻" }, { "lv", "祣" }, { "lv", "稆" },
			{ "lv", "穭" }, { "lv", "簍" }, { "lv", "絽" }, { "lv", "綠" }, { "lv", "緑" }, { "lv", "縷" }, { "lv", "繂" }, { "lv", "绿" }, { "lv", "缕" },
			{ "lv", "膂" }, { "lv", "膢" }, { "lv", "葎" }, { "lv", "蔞" }, { "lv", "藘" }, { "lv", "虑" }, { "lv", "褛" }, { "lv", "褸" }, { "lv", "謱" },
			{ "lv", "郘" }, { "lv", "鋁" }, { "lv", "録" }, { "lv", "鑢" }, { "lv", "铝" }, { "lv", "閭" }, { "lv", "闾" }, { "lv", "驢" }, { "lv", "驴" },
			{ "lv", "鷜" }, { "lv bo", "滤波" }, { "lv bo", "铝箔" }, { "lv bo qi", "滤波器" }, { "lv bu", "吕布" }, { "lv cao", "绿草" }, { "lv cha", "绿茶" },
			{ "lv cheng", "旅程" }, { "lv cheng", "绿城" }, { "lv ci", "屡次" }, { "lv deng", "绿灯" }, { "lv di", "率低" }, { "lv di", "绿地" }, { "lv dian", "旅店" },
			{ "lv dou", "绿豆" }, { "lv dou tang", "绿豆汤" }, { "lv fa", "律法" }, { "lv gao", "率高" }, { "lv guan", "旅馆" }, { "lv guang", "绿光" },
			{ "lv he jin", "铝合金" }, { "lv hua", "氯化" }, { "lv hua", "绿化" }, { "lv hua dai", "绿化带" }, { "lv jian bu xian", "屡见不鲜" }, { "lv jing", "滤镜" },
			{ "lv ka", "绿卡" }, { "lv ke", "旅客" }, { "lv li", "履历" }, { "lv lv", "屡屡" }, { "lv mao zi", "绿帽子" }, { "lv se", "绿色" }, { "lv se ban", "绿色版" },
			{ "lv se huan bao", "绿色环保" }, { "lv se shi pin", "绿色食品" }, { "lv se tong dao", "绿色通道" }, { "lv she", "旅社" }, { "lv shi", "律师" },
			{ "lv shu", "绿树" }, { "lv shui", "绿水" }, { "lv shun", "旅顺" }, { "lv tu", "旅途" }, { "lv wei", "率为" }, { "lv xin", "滤芯" }, { "lv xing", "履行" },
			{ "lv xing", "旅行" }, { "lv xing she", "旅行社" }, { "lv xing tuan", "旅行团" }, { "lv xing zhe", "旅行者" }, { "lv xing zhi ze", "履行职责" },
			{ "lv xiu lian", "吕秀莲" }, { "lv ye", "绿叶" }, { "lv ye", "绿野" }, { "lv ye", "铝业" }, { "lv yi", "绿意" }, { "lv yin", "绿茵" }, { "lv you", "旅游" },
			{ "lv you", "驴友" }, { "lv you chan pin", "旅游产品" }, { "lv you chan ye", "旅游产业" }, { "lv you cheng shi", "旅游城市" }, { "lv you du jia", "旅游度假" },
			{ "lv you jie", "旅游节" }, { "lv you jing dian", "旅游景点" }, { "lv you jing qu", "旅游景区" }, { "lv you ju", "旅游局" }, { "lv you kai fa", "旅游开发" },
			{ "lv you qu", "旅游区" }, { "lv you sheng di", "旅游胜地" }, { "lv you shi chang", "旅游市场" }, { "lv you tuan", "旅游团" }, { "lv you wang", "旅游网" },
			{ "lv you xian lu", "旅游线路" }, { "lv you xiang mu", "旅游项目" }, { "lv you ye", "旅游业" }, { "lv you you", "绿油油" }, { "lv you zhe", "旅游者" },
			{ "lv you zi yuan", "旅游资源" }, { "lv yue", "履约" }, { "lv zhou", "绿洲" }, { "lv zhuang", "绿装" }, { "lv zi", "驴子" }, { "m", "呒" }, { "m", "呣" },
			{ "m", "嘸" }, { "ma", "么" }, { "ma", "傌" }, { "ma", "吗" }, { "ma", "嗎" }, { "ma", "嘛" }, { "ma", "嘜" }, { "ma", "妈" }, { "ma", "媽" },
			{ "ma", "嬤" }, { "ma", "孖" }, { "ma", "抹" }, { "ma", "摩" }, { "ma", "杩" }, { "ma", "榪" }, { "ma", "溤" }, { "ma", "犘" }, { "ma", "犸" },
			{ "ma", "玛" }, { "ma", "瑪" }, { "ma", "痲" }, { "ma", "痳" }, { "ma", "码" }, { "ma", "碼" }, { "ma", "礣" }, { "ma", "禡" }, { "ma", "罵" },
			{ "ma", "蚂" }, { "ma", "螞" }, { "ma", "蟆" }, { "ma", "蟇" }, { "ma", "鎷" }, { "ma", "馬" }, { "ma", "马" }, { "ma", "骂" }, { "ma", "鬕" },
			{ "ma", "鷌" }, { "ma", "麻" }, { "ma", "麽" }, { "ma an shan", "马鞍山" }, { "ma bi", "麻痹" }, { "ma bu", "抹布" }, { "ma bu ting ti", "马不停蹄" },
			{ "ma chang", "马场" }, { "ma chao", "马超" }, { "ma che", "马车" }, { "ma ci", "马刺" }, { "ma ci dui", "马刺队" }, { "ma da", "马达" }, { "ma dai", "麻袋" },
			{ "ma dao", "骂道" }, { "ma de", "骂得" }, { "ma de li", "马德里" }, { "ma ding", "马丁" }, { "ma er", "马儿" }, { "ma er", "马尔" },
			{ "ma er dai fu", "马尔代夫" }, { "ma er di ni", "马尔蒂尼" }, { "ma fan", "麻烦" }, { "ma fan shi", "麻烦事" }, { "ma gang", "马钢" }, { "ma hu", "马虎" },
			{ "ma hua", "麻花" }, { "ma hua teng", "马化腾" }, { "ma ji", "马季" }, { "ma jia", "马甲" }, { "ma jia jue", "马加爵" }, { "ma jiang", "麻将" },
			{ "ma jie", "骂街" }, { "ma kai", "马凯" }, { "ma ke", "马克" }, { "ma ke", "马可" }, { "ma ke si", "马克思" }, { "ma la", "马拉" }, { "ma la", "麻辣" },
			{ "ma la duo na", "马拉多纳" }, { "ma la song", "马拉松" }, { "ma la tang", "麻辣烫" }, { "ma lai", "马来" }, { "ma lai xi ya", "马来西亚" }, { "ma lan", "马兰" },
			{ "ma li", "玛丽" }, { "ma li", "马力" }, { "ma li", "马里" }, { "ma li", "麻利" }, { "ma li ao", "马里奥" }, { "ma li ya", "玛丽亚" },
			{ "ma liang xing", "马良行" }, { "ma lie zhu yi", "马列主义" }, { "ma lin", "马琳" }, { "ma ling shu", "马铃薯" }, { "ma long", "马龙" }, { "ma lu", "马路" },
			{ "ma lu bian", "马路边" }, { "ma lv", "码率" }, { "ma ma", "妈妈" }, { "ma ma", "骂骂" }, { "ma ma", "麻麻" }, { "ma ma hu hu", "马马虎虎" }, { "ma mi", "妈咪" },
			{ "ma mu", "麻木" }, { "ma nao", "玛瑙" }, { "ma ni la", "马尼拉" }, { "ma niang", "骂娘" }, { "ma pi", "马匹" }, { "ma pi", "马屁" }, { "ma que", "麻雀" },
			{ "ma ren", "骂人" }, { "ma sa", "马萨" }, { "ma sai", "马赛" }, { "ma sai ke", "马赛克" }, { "ma shang", "马上" }, { "ma shang jiu yao", "马上就要" },
			{ "ma sheng", "骂声" }, { "ma shu", "马术" }, { "ma si", "马斯" }, { "ma si", "骂死" }, { "ma te", "马特" }, { "ma te la qi", "马特拉齐" }, { "ma ti", "马蹄" },
			{ "ma tian yu", "马天宇" }, { "ma tong", "马桶" }, { "ma tou", "码头" }, { "ma wei", "马尾" }, { "ma wo", "骂我" }, { "ma xi tuan", "马戏团" },
			{ "ma xiao xu", "马晓旭" }, { "ma ya", "妈呀" }, { "ma ya", "玛雅" }, { "ma yao", "麻药" }, { "ma yi", "蚂蚁" }, { "ma yi", "麻衣" }, { "ma ying jiu", "马英九" },
			{ "ma you", "麻油" }, { "ma yun", "马云" }, { "ma zhen", "麻疹" }, { "ma zi", "码字" }, { "ma zi", "马子" }, { "ma zi", "麻子" }, { "ma zi da", "马自达" },
			{ "ma zui", "麻醉" }, { "mai", "买" }, { "mai", "劢" }, { "mai", "勱" }, { "mai", "卖" }, { "mai", "唛" }, { "mai", "嘪" }, { "mai", "埋" }, { "mai", "売" },
			{ "mai", "脈" }, { "mai", "脉" }, { "mai", "荬" }, { "mai", "買" }, { "mai", "賣" }, { "mai", "迈" }, { "mai", "邁" }, { "mai", "霢" }, { "mai", "霾" },
			{ "mai", "鷶" }, { "mai", "麥" }, { "mai", "麦" }, { "mai a mi", "迈阿密" }, { "mai bao xian", "买保险" }, { "mai bo", "脉搏" }, { "mai bu", "迈步" },
			{ "mai bu dao", "买不到" }, { "mai bu qi", "买不起" }, { "mai cai", "买菜" }, { "mai cai", "卖菜" }, { "mai cai piao", "买彩票" }, { "mai cang", "埋藏" },
			{ "mai chang", "卖场" }, { "mai che", "买车" }, { "mai che", "卖车" }, { "mai chong", "脉冲" }, { "mai chu", "卖出" }, { "mai chu", "迈出" },
			{ "mai dan", "买单" }, { "mai dan", "卖单" }, { "mai dan", "埋单" }, { "mai dang lao", "麦当劳" }, { "mai dang na", "麦当娜" }, { "mai dao", "买到" },
			{ "mai dao", "卖到" }, { "mai de", "买得" }, { "mai de", "买的" }, { "mai de", "卖得" }, { "mai de", "卖的" }, { "mai de long", "麦德龙" },
			{ "mai de qi", "买得起" }, { "mai di", "麦蒂" }, { "mai di", "麦迪" }, { "mai dian", "买点" }, { "mai dian", "卖点" }, { "mai dian nao", "买电脑" },
			{ "mai diao", "卖掉" }, { "mai dong", "脉动" }, { "mai dong xi", "买东西" }, { "mai dong xi", "卖东西" }, { "mai dou", "麦兜" }, { "mai duan", "买断" },
			{ "mai fang", "买房" }, { "mai fang", "买方" }, { "mai fang", "卖房" }, { "mai fang", "卖方" }, { "mai fang zi", "买房子" }, { "mai fu", "埋伏" },
			{ "mai ge", "买个" }, { "mai gei", "卖给" }, { "mai gu piao", "买股票" }, { "mai guo", "买过" }, { "mai guo", "卖国" }, { "mai guo", "卖过" },
			{ "mai hao", "买好" }, { "mai hui", "买回" }, { "mai ji jin", "买基金" }, { "mai jia", "买家" }, { "mai jia", "卖家" }, { "mai jin", "买进" },
			{ "mai jin", "迈进" }, { "mai kai en", "麦凯恩" }, { "mai kai lun", "迈凯轮" }, { "mai ke", "迈克" }, { "mai ke", "麦克" }, { "mai ke er", "迈克尔" },
			{ "mai ke feng", "麦克风" }, { "mai ke la lun", "麦克拉伦" }, { "mai ken xi", "麦肯锡" }, { "mai lai", "买来" }, { "mai le", "买了" }, { "mai li", "卖力" },
			{ "mai liang", "买辆" }, { "mai luo", "脉络" }, { "mai mai", "买卖" }, { "mai mai he tong", "买卖合同" }, { "mai mai shuang fang", "买卖双方" },
			{ "mai ming", "卖命" }, { "mai mo", "埋没" }, { "mai nong", "卖弄" }, { "mai pan", "买盘" }, { "mai pan", "卖盘" }, { "mai pian", "麦片" },
			{ "mai piao", "买票" }, { "mai piao", "卖票" }, { "mai qian", "卖钱" }, { "mai ru", "买入" }, { "mai ru", "迈入" }, { "mai shang", "迈上" },
			{ "mai shen", "卖身" }, { "mai shen me", "买什么" }, { "mai shou ji", "买手机" }, { "mai shou ren", "买受人" }, { "mai shu", "买书" }, { "mai tian", "麦田" },
			{ "mai tou", "埋头" }, { "mai wan", "卖完" }, { "mai xia", "买下" }, { "mai xia", "埋下" }, { "mai xiang", "迈向" }, { "mai xie", "买些" },
			{ "mai xue", "卖血" }, { "mai ya", "麦芽" }, { "mai yao", "买药" }, { "mai yi", "买一" }, { "mai yi", "卖艺" }, { "mai yi fu", "买衣服" }, { "mai yin", "卖淫" },
			{ "mai yuan", "埋怨" }, { "mai zai", "埋在" }, { "mai zang", "埋葬" }, { "mai zhang", "买张" }, { "mai zhe", "迈着" }, { "mai zhu", "买主" },
			{ "mai zi", "麦子" }, { "mai zuo", "卖座" }, { "man", "僈" }, { "man", "埋" }, { "man", "墁" }, { "man", "姏" }, { "man", "嫚" }, { "man", "屘" },
			{ "man", "幔" }, { "man", "慢" }, { "man", "慲" }, { "man", "曼" }, { "man", "樠" }, { "man", "满" }, { "man", "滿" }, { "man", "漫" }, { "man", "熳" },
			{ "man", "獌" }, { "man", "睌" }, { "man", "瞒" }, { "man", "瞞" }, { "man", "矕" }, { "man", "縵" }, { "man", "缦" }, { "man", "蔓" }, { "man", "蘰" },
			{ "man", "蛮" }, { "man", "螨" }, { "man", "蟃" }, { "man", "蠻" }, { "man", "謾" }, { "man", "谩" }, { "man", "鏝" }, { "man", "镘" }, { "man", "鞔" },
			{ "man", "顢" }, { "man", "颟" }, { "man", "饅" }, { "man", "馒" }, { "man", "鬗" }, { "man", "鬘" }, { "man", "鰻" }, { "man", "鳗" }, { "man bu", "漫步" },
			{ "man bu jing xin", "漫不经心" }, { "man bu zhe", "漫步者" }, { "man cang", "满仓" }, { "man chang", "漫长" }, { "man cheng", "曼城" }, { "man cheng", "满城" },
			{ "man da", "蛮大" }, { "man di", "满地" }, { "man dian", "慢点" }, { "man fen", "满分" }, { "man fu", "满腹" }, { "man gu", "曼谷" }, { "man ha dun", "曼哈顿" },
			{ "man hao", "蛮好" }, { "man heng", "蛮横" }, { "man hua", "漫画" }, { "man hua jia", "漫画家" }, { "man huai", "满怀" }, { "man huang", "蛮荒" },
			{ "man ji", "满级" }, { "man jie", "满街" }, { "man kou", "满口" }, { "man kuai", "蛮快" }, { "man lian", "曼联" }, { "man lian", "满脸" }, { "man ma", "漫骂" },
			{ "man ma", "谩骂" }, { "man man", "慢慢" }, { "man man", "满满" }, { "man man", "漫漫" }, { "man man de", "满满的" }, { "man man lai", "慢慢来" },
			{ "man mian", "满面" }, { "man miao", "曼妙" }, { "man mu", "满目" }, { "man nao zi", "满脑子" }, { "man pao", "慢跑" }, { "man qi ni", "曼奇尼" },
			{ "man qiang", "满腔" }, { "man qing", "满清" }, { "man shan", "满山" }, { "man shen", "满身" }, { "man shi", "满是" }, { "man shi jie", "满世界" },
			{ "man su", "慢速" }, { "man tan", "漫谈" }, { "man tang", "满堂" }, { "man tian", "满天" }, { "man tian", "漫天" }, { "man tian fei", "满天飞" },
			{ "man tou", "满头" }, { "man tou", "馒头" }, { "man tou da han", "满头大汗" }, { "man wu", "满屋" }, { "man wu mu di", "漫无目的" }, { "man xin", "满心" },
			{ "man xing", "慢性" }, { "man xing bing", "慢性病" }, { "man yan", "满眼" }, { "man yan", "蔓延" }, { "man yi", "满意" }, { "man yi du", "满意度" },
			{ "man you", "漫游" }, { "man you fei", "漫游费" }, { "man you you", "慢悠悠" }, { "man yu", "鳗鱼" }, { "man yuan", "埋怨" }, { "man yue", "满月" },
			{ "man zai", "满载" }, { "man zhe", "瞒着" }, { "man zhou", "满洲" }, { "man zou", "慢走" }, { "man zu", "满族" }, { "man zu", "满足" },
			{ "man zu gan", "满足感" }, { "man zui", "满嘴" }, { "mang", "厖" }, { "mang", "哤" }, { "mang", "壾" }, { "mang", "娏" }, { "mang", "忙" }, { "mang", "杗" },
			{ "mang", "氓" }, { "mang", "汒" }, { "mang", "漭" }, { "mang", "牻" }, { "mang", "痝" }, { "mang", "盲" }, { "mang", "硥" }, { "mang", "硭" },
			{ "mang", "笀" }, { "mang", "芒" }, { "mang", "茫" }, { "mang", "莽" }, { "mang", "蘉" }, { "mang", "蛖" }, { "mang", "蟒" }, { "mang", "蠎" },
			{ "mang", "邙" }, { "mang", "鋩" }, { "mang", "駹" }, { "mang", "龒" }, { "mang bu guo lai", "忙不过来" }, { "mang cong", "盲从" }, { "mang dao", "忙到" },
			{ "mang de", "忙得" }, { "mang dian", "盲点" }, { "mang guo", "芒果" }, { "mang huo", "忙活" }, { "mang li tou xian", "忙里偷闲" }, { "mang lu", "忙碌" },
			{ "mang mang", "茫茫" }, { "mang mang lu lu", "忙忙碌碌" }, { "mang mang ren hai", "茫茫人海" }, { "mang mu", "盲目" }, { "mang qu", "盲区" },
			{ "mang ran", "茫然" }, { "mang ren", "盲人" }, { "mang yu", "忙于" }, { "mang zhe", "忙着" }, { "mao", "冇" }, { "mao", "冐" }, { "mao", "冒" },
			{ "mao", "卯" }, { "mao", "媢" }, { "mao", "峁" }, { "mao", "帽" }, { "mao", "懋" }, { "mao", "旄" }, { "mao", "昴" }, { "mao", "枆" }, { "mao", "楙" },
			{ "mao", "毛" }, { "mao", "毷" }, { "mao", "氂" }, { "mao", "泖" }, { "mao", "渵" }, { "mao", "牦" }, { "mao", "犛" }, { "mao", "猫" }, { "mao", "瑁" },
			{ "mao", "皃" }, { "mao", "眊" }, { "mao", "瞀" }, { "mao", "矛" }, { "mao", "秏" }, { "mao", "耄" }, { "mao", "芼" }, { "mao", "茂" }, { "mao", "茅" },
			{ "mao", "茆" }, { "mao", "蓩" }, { "mao", "蝐" }, { "mao", "蝥" }, { "mao", "蟊" }, { "mao", "袤" }, { "mao", "貌" }, { "mao", "貓" }, { "mao", "貿" },
			{ "mao", "贸" }, { "mao", "軞" }, { "mao", "鄚" }, { "mao", "鄮" }, { "mao", "酕" }, { "mao", "鉚" }, { "mao", "錨" }, { "mao", "铆" }, { "mao", "锚" },
			{ "mao", "髦" }, { "mao", "鶜" }, { "mao bi", "毛笔" }, { "mao bing", "毛病" }, { "mao chong", "冒充" }, { "mao chu", "冒出" }, { "mao dou", "毛豆" },
			{ "mao dun", "矛盾" }, { "mao dun jiu fen", "矛盾纠纷" }, { "mao er", "猫儿" }, { "mao fa", "毛发" }, { "mao fan", "冒犯" }, { "mao gou", "猫狗" },
			{ "mao gu song ran", "毛骨悚然" }, { "mao han", "冒汗" }, { "mao jin", "毛巾" }, { "mao kong", "毛孔" }, { "mao le", "冒了" }, { "mao li", "毛利" },
			{ "mao li lv", "毛利率" }, { "mao liang", "猫粮" }, { "mao liao", "毛料" }, { "mao lv", "毛驴" }, { "mao mao", "毛毛" }, { "mao mao", "猫猫" },
			{ "mao mao chong", "毛毛虫" }, { "mao mei", "冒昧" }, { "mao mi", "猫咪" }, { "mao mi", "茂密" }, { "mao ming", "茂名" }, { "mao nang", "毛囊" },
			{ "mao ni", "猫腻" }, { "mao niu", "牦牛" }, { "mao pai", "冒牌" }, { "mao pao", "冒泡" }, { "mao pi", "毛坯" }, { "mao pi", "毛皮" }, { "mao pian", "毛片" },
			{ "mao pu", "猫扑" }, { "mao qian", "毛钱" }, { "mao ran", "贸然" }, { "mao rong", "毛绒" }, { "mao rong rong", "毛茸茸" }, { "mao sheng", "茂盛" },
			{ "mao shi", "冒失" }, { "mao si", "冒死" }, { "mao si", "貌似" }, { "mao tai", "茅台" }, { "mao tan", "毛毯" }, { "mao tou", "矛头" },
			{ "mao tou ying", "猫头鹰" }, { "mao xi kong", "毛细孔" }, { "mao xi xue guan", "毛细血管" }, { "mao xian", "冒险" }, { "mao xian", "毛线" },
			{ "mao xian dao", "冒险岛" }, { "mao yan", "冒烟" }, { "mao yan", "猫眼" }, { "mao yi", "毛衣" }, { "mao yi", "贸易" }, { "mao yi bi lei", "贸易壁垒" },
			{ "mao yi e", "贸易额" }, { "mao yi gong si", "贸易公司" }, { "mao yi huo ban", "贸易伙伴" }, { "mao yi mo ca", "贸易摩擦" }, { "mao yi ni cha", "贸易逆差" },
			{ "mao yi shang", "贸易商" }, { "mao yi shun cha", "贸易顺差" }, { "mao yi tong", "贸易通" }, { "mao yong", "冒用" }, { "mao yu", "冒雨" },
			{ "mao ze dong", "毛泽东" }, { "mao zhe", "冒着" }, { "mao zhu xi", "毛主席" }, { "mao zi", "帽子" }, { "me", "么" }, { "me", "嚜" }, { "me", "麼" },
			{ "me", "麽" }, { "me me", "么么" }, { "me yang", "么样" }, { "mei", "堳" }, { "mei", "塺" }, { "mei", "妹" }, { "mei", "媄" }, { "mei", "媒" },
			{ "mei", "媚" }, { "mei", "媺" }, { "mei", "寐" }, { "mei", "嵋" }, { "mei", "徾" }, { "mei", "挴" }, { "mei", "攗" }, { "mei", "昧" }, { "mei", "枚" },
			{ "mei", "栂" }, { "mei", "梅" }, { "mei", "楣" }, { "mei", "楳" }, { "mei", "毎" }, { "mei", "每" }, { "mei", "沒" }, { "mei", "没" }, { "mei", "沬" },
			{ "mei", "浼" }, { "mei", "渼" }, { "mei", "湄" }, { "mei", "煝" }, { "mei", "煤" }, { "mei", "燘" }, { "mei", "猸" }, { "mei", "玫" }, { "mei", "瑂" },
			{ "mei", "痗" }, { "mei", "眉" }, { "mei", "眛" }, { "mei", "禖" }, { "mei", "糜" }, { "mei", "美" }, { "mei", "脢" }, { "mei", "腜" }, { "mei", "苺" },
			{ "mei", "莓" }, { "mei", "蘪" }, { "mei", "蝞" }, { "mei", "袂" }, { "mei", "躾" }, { "mei", "郿" }, { "mei", "酶" }, { "mei", "鎂" }, { "mei", "镁" },
			{ "mei", "镅" }, { "mei", "霉" }, { "mei", "魅" }, { "mei", "鹛" }, { "mei", "黴" }, { "mei ba", "没把" }, { "mei bai", "美白" }, { "mei ban", "美版" },
			{ "mei bei", "没被" }, { "mei bi", "每笔" }, { "mei bian", "没变" }, { "mei bing", "没病" }, { "mei bu", "每部" }, { "mei ceng", "每层" },
			{ "mei ceng", "煤层" }, { "mei chang", "每场" }, { "mei chi", "没吃" }, { "mei chu", "没出" }, { "mei chu xi", "没出息" }, { "mei chuan", "没穿" },
			{ "mei ci", "每次" }, { "mei cuo", "没错" }, { "mei da", "没打" }, { "mei dai", "没带" }, { "mei dang", "每当" }, { "mei dao", "每到" }, { "mei dao", "没到" },
			{ "mei dao li", "没道理" }, { "mei de", "没得" }, { "mei de", "美得" }, { "mei de", "美德" }, { "mei de", "美的" }, { "mei de shuo", "没得说" },
			{ "mei di", "没底" }, { "mei di", "美的" }, { "mei dian", "没点" }, { "mei dian", "没电" }, { "mei dian", "煤电" }, { "mei dong", "没动" }, { "mei du", "梅毒" },
			{ "mei duan", "每段" }, { "mei dun", "每吨" }, { "mei er", "梅尔" }, { "mei fa", "没法" }, { "mei fa", "美发" }, { "mei fa zi", "没法子" },
			{ "mei fang", "美方" }, { "mei fen", "每份" }, { "mei fen", "美分" }, { "mei feng", "每逢" }, { "mei fu", "妹夫" }, { "mei fu", "美服" }, { "mei gan", "没干" },
			{ "mei gan", "没敢" }, { "mei gan", "美感" }, { "mei gan jue", "没感觉" }, { "mei ge", "每个" }, { "mei ge", "每隔" }, { "mei ge ren", "每个人" },
			{ "mei ge ren dou", "每个人都" }, { "mei ge yue", "每个月" }, { "mei gei", "没给" }, { "mei gong", "美工" }, { "mei gu", "每股" }, { "mei gu", "美股" },
			{ "mei gu shou yi", "每股收益" }, { "mei guan", "没关" }, { "mei guan", "美观" }, { "mei guan xi", "没关系" }, { "mei gui", "玫瑰" }, { "mei gui hua", "玫瑰花" },
			{ "mei guo", "没过" }, { "mei guo", "美国" }, { "mei guo dui", "美国队" }, { "mei guo gong si", "美国公司" }, { "mei guo gu shi", "美国股市" },
			{ "mei guo guo hui", "美国国会" }, { "mei guo hai jun", "美国海军" }, { "mei guo jia zhou", "美国加州" }, { "mei guo jing ji", "美国经济" },
			{ "mei guo kong jun", "美国空军" }, { "mei guo lian bang", "美国联邦" }, { "mei guo mei ti", "美国媒体" }, { "mei guo niu yue", "美国纽约" },
			{ "mei guo ren", "美国人" }, { "mei guo shi chang", "美国市场" }, { "mei guo zheng fu", "美国政府" }, { "mei guo zhu ming", "美国著名" },
			{ "mei guo zong tong", "美国总统" }, { "mei hang", "每行" }, { "mei hao", "没好" }, { "mei hao", "美好" }, { "mei hao qi", "没好气" },
			{ "mei hao sheng huo", "美好生活" }, { "mei hu", "每户" }, { "mei hua", "梅花" }, { "mei hua", "没话" }, { "mei hua", "美化" }, { "mei hua gong", "煤化工" },
			{ "mei hua shuo", "没话说" }, { "mei hui", "每回" }, { "mei hui", "没回" }, { "mei huo", "魅惑" }, { "mei ji", "每集" }, { "mei jia", "每家" },
			{ "mei jia", "美甲" }, { "mei jian", "每件" }, { "mei jian", "没见" }, { "mei jian guo", "没见过" }, { "mei jiao", "没交" }, { "mei jie", "媒介" },
			{ "mei jie", "没接" }, { "mei jin", "没劲" }, { "mei jin", "没进" }, { "mei jin", "美金" }, { "mei jin pai", "枚金牌" }, { "mei jing", "美景" },
			{ "mei jiu", "没救" }, { "mei jiu", "美酒" }, { "mei ju", "枚举" }, { "mei ju", "美剧" }, { "mei jun", "美军" }, { "mei jun", "霉菌" },
			{ "mei kai er du", "梅开二度" }, { "mei kan", "没看" }, { "mei kong", "没空" }, { "mei kuang", "煤矿" }, { "mei kuang an quan", "煤矿安全" },
			{ "mei lai", "没来" }, { "mei lan fang", "梅兰芳" }, { "mei le", "没了" }, { "mei li", "美丽" }, { "mei li", "魅力" }, { "mei lian", "没脸" },
			{ "mei lian chu", "美联储" }, { "mei lian she", "美联社" }, { "mei liang xin", "没良心" }, { "mei lin", "梅林" }, { "mei lin", "美林" },
			{ "mei lin kai", "玫琳凯" }, { "mei mai", "没买" }, { "mei man", "美满" }, { "mei mao", "眉毛" }, { "mei mao", "美貌" }, { "mei mei", "妹妹" },
			{ "mei mei", "每每" }, { "mei mei", "美眉" }, { "mei mei", "美美" }, { "mei meng", "美梦" }, { "mei miao", "每秒" }, { "mei miao", "美妙" },
			{ "mei ming", "每名" }, { "mei ming", "美名" }, { "mei mu", "每亩" }, { "mei mu", "眉目" }, { "mei na", "没拿" }, { "mei nan", "美男" }, { "mei neng", "没能" },
			{ "mei neng da", "美能达" }, { "mei ni", "煤泥" }, { "mei nian", "每年" }, { "mei nv", "美女" }, { "mei ou", "美欧" }, { "mei pian", "每篇" },
			{ "mei ping mi", "每平米" }, { "mei po", "媒婆" }, { "mei pu", "没谱" }, { "mei qi", "每期" }, { "mei qi", "煤气" }, { "mei qi ming yue", "美其名曰" },
			{ "mei qian", "没钱" }, { "mei qu", "没去" }, { "mei ren", "媒人" }, { "mei ren", "每人" }, { "mei ren", "没人" }, { "mei ren", "美人" },
			{ "mei ren yu", "美人鱼" }, { "mei ri", "每日" }, { "mei ri", "美日" }, { "mei ri mei ye", "没日没夜" }, { "mei rong", "美容" }, { "mei rong mei fa", "美容美发" },
			{ "mei rong shi", "美容师" }, { "mei rong yuan", "美容院" }, { "mei se", "美色" }, { "mei sha", "没啥" }, { "mei shang", "没上" },
			{ "mei shang liang", "没商量" }, { "mei shao", "没少" }, { "mei shao nian", "美少年" }, { "mei shao nv", "美少女" }, { "mei shen me", "没什么" },
			{ "mei sheng", "美声" }, { "mei sheng yin", "没声音" }, { "mei shi", "没事" }, { "mei shi", "美式" }, { "mei shi", "美食" }, { "mei shi er", "没事儿" },
			{ "mei shi mei ke", "每时每刻" }, { "mei shu", "美术" }, { "mei shu guan", "美术馆" }, { "mei shu xue yuan", "美术学院" }, { "mei shui", "没睡" },
			{ "mei shuo", "没说" }, { "mei si", "没死" }, { "mei su", "媚俗" }, { "mei su", "霉素" }, { "mei tai", "每台" }, { "mei tan", "煤炭" },
			{ "mei tan hang ye", "煤炭行业" }, { "mei tan qi ye", "煤炭企业" }, { "mei tan zi yuan", "煤炭资源" }, { "mei tao", "每套" }, { "mei ti", "媒体" },
			{ "mei ti", "美体" }, { "mei ti bao dao", "媒体报道" }, { "mei tian", "每天" }, { "mei tian dou yao", "每天都要" }, { "mei tian dou you", "每天都有" },
			{ "mei tian wan shang", "每天晚上" }, { "mei tiao", "每条" }, { "mei ting", "梅婷" }, { "mei ting", "没听" }, { "mei tong", "每桶" }, { "mei tou", "眉头" },
			{ "mei tu", "美图" }, { "mei tui", "美腿" }, { "mei wan", "每晚" }, { "mei wan", "没完" }, { "mei wan", "没玩" }, { "mei wang", "美网" }, { "mei wei", "每位" },
			{ "mei wei", "美味" }, { "mei wen", "美文" }, { "mei xi", "梅西" }, { "mei xi", "没戏" }, { "mei xiang", "每项" }, { "mei xiang", "没想" },
			{ "mei xiang guo", "没想过" } };
};
