package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN38 {
	public static String[][] pl = { { "qing shao hou", "请稍候" }, { "qing shao nian", "青少年" }, { "qing shen", "情深" }, { "qing sheng", "庆生" },
			{ "qing sheng", "情圣" }, { "qing sheng", "轻声" }, { "qing sheng", "轻生" }, { "qing shi", "情事" }, { "qing shi", "情势" }, { "qing shi", "请示" },
			{ "qing shi", "轻视" }, { "qing shi", "青石" }, { "qing shi yong", "请使用" }, { "qing shu", "情书" }, { "qing shu ru", "请输入" }, { "qing shuai", "轻率" },
			{ "qing shuang", "清爽" }, { "qing shui", "清水" }, { "qing shuo", "请说" }, { "qing si", "青丝" }, { "qing song", "轻松" }, { "qing song", "青松" },
			{ "qing song yu kuai", "轻松愉快" }, { "qing su", "倾诉" }, { "qing su", "情愫" }, { "qing suan", "清算" }, { "qing ta", "请他" }, { "qing ta", "请她" },
			{ "qing tai", "青苔" }, { "qing tang", "清汤" }, { "qing tian", "晴天" }, { "qing tian", "青天" }, { "qing tian zhu", "擎天柱" }, { "qing tie", "请帖" },
			{ "qing ting", "倾听" }, { "qing ting", "清廷" }, { "qing ting", "蜻蜓" }, { "qing tong", "青铜" }, { "qing tong qi", "青铜器" }, { "qing wa", "青蛙" },
			{ "qing wei", "轻微" }, { "qing wen", "请问" }, { "qing wo", "请我" }, { "qing wu", "请勿" }, { "qing wu bi", "请务必" }, { "qing xi", "情系" },
			{ "qing xi", "清晰" }, { "qing xi", "清洗" }, { "qing xi du", "清晰度" }, { "qing xi ke jian", "清晰可见" }, { "qing xian", "清闲" }, { "qing xian", "请先" },
			{ "qing xiang", "倾向" }, { "qing xiang", "清香" }, { "qing xiang", "请向" }, { "qing xiang xing", "倾向性" }, { "qing xiao", "倾销" }, { "qing xie", "倾斜" },
			{ "qing xie", "倾泻" }, { "qing xin", "倾心" }, { "qing xin", "清心" }, { "qing xin", "清新" }, { "qing xin", "轻信" }, { "qing xing", "庆幸" },
			{ "qing xing", "情形" }, { "qing xing", "清醒" }, { "qing xing", "轻型" }, { "qing xiu", "清秀" }, { "qing xu", "情绪" }, { "qing xu hua", "情绪化" },
			{ "qing xuan ze", "请选择" }, { "qing ya", "清雅" }, { "qing yan", "轻言" }, { "qing yan", "青烟" }, { "qing yi", "情义" }, { "qing yi", "情意" },
			{ "qing yi", "情谊" }, { "qing yi", "请以" }, { "qing yi", "轻易" }, { "qing yi", "青衣" }, { "qing yi se", "清一色" }, { "qing yin yue", "轻音乐" },
			{ "qing ying", "轻盈" }, { "qing yong", "请用" }, { "qing you", "清幽" }, { "qing you du zhong", "情有独钟" }, { "qing yu", "情欲" }, { "qing yu", "请与" },
			{ "qing yu", "请于" }, { "qing yu wo", "请与我" }, { "qing yuan", "情愿" }, { "qing yuan", "情缘" }, { "qing yuan", "清远" }, { "qing yuan", "请愿" },
			{ "qing yun", "青云" }, { "qing zai", "请在" }, { "qing zai ci", "请在此" }, { "qing zang", "青藏" }, { "qing zang gao yuan", "青藏高原" },
			{ "qing zang tie lu", "青藏铁路" }, { "qing zao", "清早" }, { "qing zhen", "清真" }, { "qing zhen si", "清真寺" }, { "qing zheng", "清蒸" },
			{ "qing zheng fu", "清政府" }, { "qing zhi", "轻质" }, { "qing zhi jie", "请直接" }, { "qing zhong", "轻重" }, { "qing zhou", "青州" }, { "qing zhu", "倾注" },
			{ "qing zhu", "庆祝" }, { "qing zhu huo dong", "庆祝活动" }, { "qing zhu ming", "请注明" }, { "qing zhu yi", "请注意" }, { "qing zhuang nian", "青壮年" },
			{ "qing zi xing", "请自行" }, { "qing zun shou", "请遵守" }, { "qiong", "惸" }, { "qiong", "憌" }, { "qiong", "桏" }, { "qiong", "橩" }, { "qiong", "煢" },
			{ "qiong", "琼" }, { "qiong", "璚" }, { "qiong", "瓊" }, { "qiong", "瞏" }, { "qiong", "穷" }, { "qiong", "穹" }, { "qiong", "窮" }, { "qiong", "笻" },
			{ "qiong", "筇" }, { "qiong", "舼" }, { "qiong", "茕" }, { "qiong", "藑" }, { "qiong", "藭" }, { "qiong", "蛩" }, { "qiong", "蛬" }, { "qiong", "赹" },
			{ "qiong", "跫" }, { "qiong", "邛" }, { "qiong", "銎" }, { "qiong de", "穷得" }, { "qiong guang dan", "穷光蛋" }, { "qiong ku", "穷苦" },
			{ "qiong kun", "穷困" }, { "qiong ren", "穷人" }, { "qiong si", "琼斯" }, { "qiong yao", "琼瑶" }, { "qiu", "丘" }, { "qiu", "仇" }, { "qiu", "俅" },
			{ "qiu", "唒" }, { "qiu", "囚" }, { "qiu", "坵" }, { "qiu", "媝" }, { "qiu", "崷" }, { "qiu", "巯" }, { "qiu", "巰" }, { "qiu", "恘" }, { "qiu", "捄" },
			{ "qiu", "朹" }, { "qiu", "梂" }, { "qiu", "楸" }, { "qiu", "殏" }, { "qiu", "毬" }, { "qiu", "求" }, { "qiu", "泅" }, { "qiu", "湫" }, { "qiu", "煪" },
			{ "qiu", "犰" }, { "qiu", "球" }, { "qiu", "璆" }, { "qiu", "盚" }, { "qiu", "秋" }, { "qiu", "穐" }, { "qiu", "糗" }, { "qiu", "紌" }, { "qiu", "絿" },
			{ "qiu", "緧" }, { "qiu", "莍" }, { "qiu", "萩" }, { "qiu", "虬" }, { "qiu", "虯" }, { "qiu", "蚯" }, { "qiu", "蛷" }, { "qiu", "蝤" }, { "qiu", "蝵" },
			{ "qiu", "蟗" }, { "qiu", "蠤" }, { "qiu", "裘" }, { "qiu", "觓" }, { "qiu", "觩" }, { "qiu", "訄" }, { "qiu", "賕" }, { "qiu", "赇" }, { "qiu", "趥" },
			{ "qiu", "逎" }, { "qiu", "逑" }, { "qiu", "遒" }, { "qiu", "邱" }, { "qiu", "酋" }, { "qiu", "釓" }, { "qiu", "釚" }, { "qiu", "銶" }, { "qiu", "鞦" },
			{ "qiu", "鮂" }, { "qiu", "鯄" }, { "qiu", "鰌" }, { "qiu", "鰍" }, { "qiu", "鰽" }, { "qiu", "鳅" }, { "qiu", "鶖" }, { "qiu", "鼽" }, { "qiu", "龝" },
			{ "qiu", "龟" }, { "qiu ai", "求爱" }, { "qiu chang", "球场" }, { "qiu chu", "求出" }, { "qiu de", "求得" }, { "qiu dong", "秋冬" }, { "qiu dui", "球队" },
			{ "qiu fa zhan", "求发展" }, { "qiu fan", "囚犯" }, { "qiu feng", "秋风" }, { "qiu gou", "求购" }, { "qiu hun", "求婚" }, { "qiu ji", "球技" },
			{ "qiu ji", "秋季" }, { "qiu jiao", "求教" }, { "qiu jie", "求解" }, { "qiu jin", "囚禁" }, { "qiu jiu", "求救" }, { "qiu ling", "丘陵" }, { "qiu men", "球门" },
			{ "qiu mi", "球迷" }, { "qiu mo ji", "球磨机" }, { "qiu ni", "求你" }, { "qiu pai", "球拍" }, { "qiu qian", "秋千" }, { "qiu qing", "求情" },
			{ "qiu qiu", "求求" }, { "qiu qiu", "球球" }, { "qiu qiu", "秋秋" }, { "qiu qiu ni", "求求你" }, { "qiu rao", "求饶" }, { "qiu ren", "求人" },
			{ "qiu ri", "秋日" }, { "qiu sai", "球赛" }, { "qiu se", "秋色" }, { "qiu sheng", "求生" }, { "qiu shi", "求实" }, { "qiu shou", "球手" },
			{ "qiu shui", "秋水" }, { "qiu suo", "求索" }, { "qiu tian", "秋天" }, { "qiu tian", "秋田" }, { "qiu wang", "球王" }, { "qiu xie", "球鞋" },
			{ "qiu xing", "球形" }, { "qiu xing", "球星" }, { "qiu xue", "求学" }, { "qiu ye", "秋叶" }, { "qiu yi", "求医" }, { "qiu yi", "球衣" }, { "qiu yin", "蚯蚓" },
			{ "qiu yu", "秋雨" }, { "qiu yuan", "球员" }, { "qiu yue", "秋月" }, { "qiu zhang", "酋长" }, { "qiu zhen", "丘疹" }, { "qiu zhen wu shi", "求真务实" },
			{ "qiu zheng", "求证" }, { "qiu zhi", "求知" }, { "qiu zhi", "求职" }, { "qiu zhi zhe", "求职者" }, { "qiu zhu", "求助" }, { "qiu zu", "求租" }, { "qu", "佉" },
			{ "qu", "佢" }, { "qu", "刞" }, { "qu", "劬" }, { "qu", "匤" }, { "qu", "匷" }, { "qu", "区" }, { "qu", "區" }, { "qu", "去" }, { "qu", "取" },
			{ "qu", "呿" }, { "qu", "坥" }, { "qu", "娶" }, { "qu", "屈" }, { "qu", "岖" }, { "qu", "嶇" }, { "qu", "彡" }, { "qu", "抾" }, { "qu", "敺" },
			{ "qu", "斪" }, { "qu", "曲" }, { "qu", "朐" }, { "qu", "欋" }, { "qu", "氍" }, { "qu", "浀" }, { "qu", "淭" }, { "qu", "渠" }, { "qu", "灈" },
			{ "qu", "焌" }, { "qu", "璩" }, { "qu", "癯" }, { "qu", "瞿" }, { "qu", "磲" }, { "qu", "祛" }, { "qu", "竘" }, { "qu", "籧" }, { "qu", "紶" },
			{ "qu", "絇" }, { "qu", "翵" }, { "qu", "胠" }, { "qu", "脥" }, { "qu", "臞" }, { "qu", "苣" }, { "qu", "菃" }, { "qu", "葋" }, { "qu", "蕖" },
			{ "qu", "蘧" }, { "qu", "蛆" }, { "qu", "蛐" }, { "qu", "螶" }, { "qu", "蟝" }, { "qu", "蠷" }, { "qu", "蠼" }, { "qu", "衢" }, { "qu", "袪" },
			{ "qu", "覷" }, { "qu", "觑" }, { "qu", "詘" }, { "qu", "诎" }, { "qu", "趋" }, { "qu", "趍" }, { "qu", "趜" }, { "qu", "趣" }, { "qu", "趨" },
			{ "qu", "跼" }, { "qu", "躣" }, { "qu", "躯" }, { "qu", "軀" }, { "qu", "軥" }, { "qu", "迲" }, { "qu", "郥" }, { "qu", "鐻" }, { "qu", "闃" },
			{ "qu", "阒" }, { "qu", "阹" }, { "qu", "駆" }, { "qu", "駈" }, { "qu", "驅" }, { "qu", "驱" }, { "qu", "髷" }, { "qu", "鮈" }, { "qu", "鱋" },
			{ "qu", "鴝" }, { "qu", "鶌" }, { "qu", "鸲" }, { "qu", "麮" }, { "qu", "麴" }, { "qu", "麹" }, { "qu", "黢" }, { "qu", "鼁" }, { "qu", "鼩" },
			{ "qu", "齲" }, { "qu", "龋" }, { "qu a", "去啊" }, { "qu ai", "去爱" }, { "qu ba", "去吧" }, { "qu ba", "去把" }, { "qu ban", "去办" }, { "qu ban", "祛斑" },
			{ "qu bei jing", "去北京" }, { "qu bie", "区别" }, { "qu cai", "取材" }, { "qu cha", "去查" }, { "qu che", "驱车" }, { "qu chen shi", "屈臣氏" },
			{ "qu chi", "去吃" }, { "qu chu", "去处" }, { "qu chu", "去除" }, { "qu chu", "取出" }, { "qu chu", "祛除" }, { "qu chu", "驱除" }, { "qu da", "去打" },
			{ "qu dai", "取代" }, { "qu dao", "去到" }, { "qu dao", "渠道" }, { "qu dao shang", "渠道商" }, { "qu de", "去的" }, { "qu de", "取得" },
			{ "qu de cheng gong", "取得成功" }, { "qu de lian xi", "取得联系" }, { "qu di", "取缔" }, { "qu diao", "去掉" }, { "qu diao", "曲调" }, { "qu dong", "驱动" },
			{ "qu dong cheng xu", "驱动程序" }, { "qu dong li", "驱动力" }, { "qu dong qi", "驱动器" }, { "qu dong zhi jia", "驱动之家" }, { "qu duan", "区段" },
			{ "qu er dai zhi", "取而代之" }, { "qu fen", "区分" }, { "qu feng", "曲风" }, { "qu fu", "屈服" }, { "qu fu", "曲阜" }, { "qu gan", "去干" }, { "qu gan", "躯干" },
			{ "qu gan", "驱赶" }, { "qu ge", "娶个" }, { "qu gei", "去给" }, { "qu gen", "去跟" }, { "qu guang", "去逛" }, { "qu guo", "去过" }, { "qu hao", "区号" },
			{ "qu hua", "区划" }, { "qu huan", "去换" }, { "qu huan", "趋缓" }, { "qu hui", "取回" }, { "qu huo", "取货" }, { "qu ji", "区级" }, { "qu jian", "区间" },
			{ "qu jian", "去见" }, { "qu jiao zhi", "去角质" }, { "qu jie", "去接" }, { "qu jie", "曲解" }, { "qu jing", "取景" }, { "qu jing", "取经" },
			{ "qu jing", "曲靖" }, { "qu jing qi", "取景器" }, { "qu jue", "取决" }, { "qu kan", "去看" }, { "qu kuai", "区块" }, { "qu kuan", "取款" }, { "qu le", "去了" },
			{ "qu le", "娶了" }, { "qu li", "区里" }, { "qu liu", "去留" }, { "qu ma", "去吗" }, { "qu mai", "去买" }, { "qu mei guo", "去美国" }, { "qu mian", "曲面" },
			{ "qu mian dui", "去面对" }, { "qu ming", "取名" }, { "qu mu", "曲目" }, { "qu na", "去哪" }, { "qu na", "去拿" }, { "qu na", "去那" }, { "qu na er", "去哪儿" },
			{ "qu na li", "去哪里" }, { "qu na li", "去那里" }, { "qu nei", "区内" }, { "qu ni", "去呢" }, { "qu ni", "娶你" }, { "qu nian", "去年" },
			{ "qu nian di", "去年底" }, { "qu nian tong qi", "去年同期" }, { "qu nuan", "取暖" }, { "qu pi", "去皮" }, { "qu qi", "取其" }, { "qu qian", "取钱" },
			{ "qu qu", "区区" }, { "qu qu", "去取" }, { "qu qu", "蛐蛐" }, { "qu ren", "去任" }, { "qu ri ben", "去日本" }, { "qu ru", "屈辱" }, { "qu san", "驱散" },
			{ "qu she", "取舍" }, { "qu sheng", "取胜" }, { "qu shi", "区市" }, { "qu shi", "去世" }, { "qu shi", "趋势" }, { "qu shi", "趣事" }, { "qu shi", "驱使" },
			{ "qu shui", "去睡" }, { "qu shui", "取水" }, { "qu si", "去死" }, { "qu si ba", "去死吧" }, { "qu si pi", "去死皮" }, { "qu ta", "娶她" }, { "qu ti", "躯体" },
			{ "qu ting", "去听" }, { "qu tong", "趋同" }, { "qu wan", "去玩" }, { "qu wang", "去往" }, { "qu wei", "区位" }, { "qu wei", "区委" }, { "qu wei", "趣味" },
			{ "qu wei shu ji", "区委书记" }, { "qu wei xing", "趣味性" }, { "qu wei you shi", "区位优势" }, { "qu wen", "去问" }, { "qu wen", "趣闻" }, { "qu xia", "取下" },
			{ "qu xian", "区县" }, { "qu xian", "取现" }, { "qu xian", "曲线" }, { "qu xiang", "去向" }, { "qu xiang", "去想" }, { "qu xiang", "取向" },
			{ "qu xiang", "趋向" }, { "qu xiang gang", "去香港" }, { "qu xiao", "取消" }, { "qu xiao", "取笑" }, { "qu yang", "取样" }, { "qu yi", "曲艺" },
			{ "qu yu", "区域" }, { "qu yu", "趋于" }, { "qu yu fa zhan", "区域发展" }, { "qu yu he zuo", "区域合作" }, { "qu yu jing ji", "区域经济" },
			{ "qu yu shi chang", "区域市场" }, { "qu yu xing", "区域性" }, { "qu yuan", "屈原" }, { "qu yue", "取悦" }, { "qu zhang", "区长" }, { "qu zhao", "去找" },
			{ "qu zhe", "曲折" }, { "qu zheng", "取证" }, { "qu zheng fu", "区政府" }, { "qu zhi", "取之" }, { "qu zhi", "取值" }, { "qu zhi ke shu", "屈指可数" },
			{ "qu zhou", "衢州" }, { "qu zhu", "去住" }, { "qu zhu", "驱逐" }, { "qu zhu jian", "驱逐舰" }, { "qu zhua", "去抓" }, { "qu zhui", "去追" }, { "qu zi", "取自" },
			{ "qu zi", "曲子" }, { "qu zou", "取走" }, { "qu zuo", "去做" }, { "quan", "佺" }, { "quan", "全" }, { "quan", "券" }, { "quan", "劝" }, { "quan", "勧" },
			{ "quan", "勸" }, { "quan", "圈" }, { "quan", "圏" }, { "quan", "埢" }, { "quan", "姾" }, { "quan", "婘" }, { "quan", "巏" }, { "quan", "巻" },
			{ "quan", "弮" }, { "quan", "悛" }, { "quan", "惓" }, { "quan", "拳" }, { "quan", "权" }, { "quan", "棬" }, { "quan", "椦" }, { "quan", "楾" },
			{ "quan", "権" }, { "quan", "權" }, { "quan", "汱" }, { "quan", "泉" }, { "quan", "湶" }, { "quan", "烇" }, { "quan", "牶" }, { "quan", "牷" },
			{ "quan", "犈" }, { "quan", "犬" }, { "quan", "犭" }, { "quan", "瑔" }, { "quan", "畎" }, { "quan", "痊" }, { "quan", "矔" }, { "quan", "筌" },
			{ "quan", "絟" }, { "quan", "綣" }, { "quan", "縓" }, { "quan", "绻" }, { "quan", "腃" }, { "quan", "荃" }, { "quan", "虇" }, { "quan", "蜷" },
			{ "quan", "蠸" }, { "quan", "觠" }, { "quan", "詮" }, { "quan", "诠" }, { "quan", "踡" }, { "quan", "輇" }, { "quan", "辁" }, { "quan", "酄" },
			{ "quan", "醛" }, { "quan", "銓" }, { "quan", "鐉" }, { "quan", "铨" }, { "quan", "韏" }, { "quan", "顴" }, { "quan", "颧" }, { "quan", "駩" },
			{ "quan", "鬈" }, { "quan", "齤" }, { "quan ban", "全班" }, { "quan bao", "全包" }, { "quan bu", "全部" }, { "quan bu nei rong", "全部内容" },
			{ "quan chang", "全场" }, { "quan chang", "全长" }, { "quan che", "全车" }, { "quan cheng", "全城" }, { "quan cheng", "全称" }, { "quan cheng", "全程" },
			{ "quan cun", "全村" }, { "quan dang", "全党" }, { "quan dang", "权当" }, { "quan dao", "劝导" }, { "quan di", "圈地" }, { "quan dou", "全都" },
			{ "quan dui", "全队" }, { "quan e", "全额" }, { "quan fang wei", "全方位" }, { "quan fu", "全副" }, { "quan gao", "劝告" }, { "quan gong lue", "全攻略" },
			{ "quan gu", "颧骨" }, { "quan gui", "权贵" }, { "quan guo", "全国" }, { "quan guo ge da", "全国各大" }, { "quan guo ge di", "全国各地" },
			{ "quan guo ren da", "全国人大" }, { "quan guo ren min", "全国人民" }, { "quan guo tong yi", "全国统一" }, { "quan guo xing", "全国性" },
			{ "quan guo zheng xie", "全国政协" }, { "quan guo zui da", "全国最大" }, { "quan hei", "全黑" }, { "quan heng", "权衡" }, { "quan huang", "拳皇" },
			{ "quan hui", "全会" }, { "quan ji", "全集" }, { "quan ji", "拳击" }, { "quan jia", "全价" }, { "quan jia", "全家" }, { "quan jia fu", "全家福" },
			{ "quan jia ren", "全家人" }, { "quan jiao", "全角" }, { "quan jiao", "拳脚" }, { "quan jing", "全景" }, { "quan ju", "全剧" }, { "quan ju", "全局" },
			{ "quan ju de", "全聚德" }, { "quan jun", "全军" }, { "quan jun fu mo", "全军覆没" }, { "quan kai", "全开" }, { "quan kao", "全靠" }, { "quan kuan", "全款" },
			{ "quan li", "全力" }, { "quan li", "圈里" }, { "quan li", "权利" }, { "quan li", "权力" }, { "quan li ren", "权利人" }, { "quan li yi fu", "全力以赴" },
			{ "quan li yi wu", "权利义务" }, { "quan li zhi chi", "全力支持" }, { "quan liu tong", "全流通" }, { "quan luo", "全裸" }, { "quan mao", "全貌" },
			{ "quan mei", "全美" }, { "quan mian", "全棉" }, { "quan mian", "全面" }, { "quan mian fa zhan", "全面发展" }, { "quan mian guan che", "全面贯彻" },
			{ "quan mian luo shi", "全面落实" }, { "quan mian shi shi", "全面实施" }, { "quan mian ti gao", "全面提高" }, { "quan mian ti sheng", "全面提升" },
			{ "quan mian tui jin", "全面推进" }, { "quan mian tui xing", "全面推行" }, { "quan min", "全民" }, { "quan min jian shen", "全民健身" }, { "quan ming", "全名" },
			{ "quan ming xing", "全明星" }, { "quan nei", "圈内" }, { "quan neng", "全能" }, { "quan nian", "全年" }, { "quan pan", "全盘" }, { "quan pian", "全片" },
			{ "quan ping", "全凭" }, { "quan ping", "全屏" }, { "quan qian", "圈钱" }, { "quan qiu", "全球" }, { "quan qiu bian nuan", "全球变暖" },
			{ "quan qiu di yi", "全球第一" }, { "quan qiu hua", "全球化" }, { "quan qiu hua ren", "全球华人" }, { "quan qiu jing ji", "全球经济" },
			{ "quan qiu ling xian", "全球领先" }, { "quan qiu shi chang", "全球市场" }, { "quan qiu tong", "全球通" }, { "quan qiu xing", "全球性" },
			{ "quan qiu zui da", "全球最大" }, { "quan qu", "全区" }, { "quan quan", "全权" }, { "quan quan", "劝劝" }, { "quan quan", "圈圈" }, { "quan ran", "全然" },
			{ "quan ren lei", "全人类" }, { "quan ri zhi", "全日制" }, { "quan shang", "券商" }, { "quan shen", "全身" }, { "quan shen guan zhu", "全神贯注" },
			{ "quan sheng", "全省" }, { "quan sheng", "全胜" }, { "quan shi", "全市" }, { "quan shi", "全是" }, { "quan shi", "权势" }, { "quan shi", "诠释" },
			{ "quan shi jie", "全世界" }, { "quan shu", "全书" }, { "quan shu", "全数" }, { "quan shu", "权属" }, { "quan shui", "泉水" }, { "quan shuo", "劝说" },
			{ "quan su", "全速" }, { "quan suo", "蜷缩" }, { "quan ta", "劝他" }, { "quan tao", "全套" }, { "quan tao", "圈套" }, { "quan ti", "全体" },
			{ "quan ti hui yi", "全体会议" }, { "quan ti yuan gong", "全体员工" }, { "quan tian", "全天" }, { "quan tian hou", "全天候" }, { "quan tou", "拳头" },
			{ "quan wang", "全网" }, { "quan wang", "拳王" }, { "quan wei", "权威" }, { "quan wei ji gou", "权威机构" }, { "quan wei ren shi", "权威人士" },
			{ "quan wei xing", "权威性" }, { "quan wen", "全文" }, { "quan wo", "劝我" }, { "quan wu", "全无" }, { "quan xi", "全息" }, { "quan xi", "全系" },
			{ "quan xian", "全县" }, { "quan xian", "全线" }, { "quan xian", "权限" }, { "quan xiang", "全乡" }, { "quan xiao", "全校" }, { "quan xin", "全心" },
			{ "quan xin", "全新" }, { "quan xin quan yi", "全心全意" }, { "quan xuan", "全选" }, { "quan ye cha", "犬夜叉" }, { "quan yi", "权益" }, { "quan yu", "痊愈" },
			{ "quan yuan", "全员" }, { "quan yuan", "全院" }, { "quan zhan", "全站" }, { "quan zhen", "全镇" }, { "quan zheng", "权证" }, { "quan zhi", "全职" },
			{ "quan zhi xian", "全智贤" }, { "quan zhong", "圈中" }, { "quan zhong", "权重" }, { "quan zhou", "全州" }, { "quan zhou", "泉州" },
			{ "quan zhou shi", "泉州市" }, { "quan zi", "全资" }, { "quan zi", "圈子" }, { "quan zi dong", "全自动" }, { "quan zu", "劝阻" }, { "que", "却" },
			{ "que", "卻" }, { "que", "埆" }, { "que", "塙" }, { "que", "悫" }, { "que", "愨" }, { "que", "慤" }, { "que", "搉" }, { "que", "榷" }, { "que", "殻" },
			{ "que", "毃" }, { "que", "炔" }, { "que", "瘸" }, { "que", "皵" }, { "que", "硞" }, { "que", "确" }, { "que", "確" }, { "que", "碻" }, { "que", "礐" },
			{ "que", "礭" }, { "que", "缺" }, { "que", "蒛" }, { "que", "蚗" }, { "que", "躤" }, { "que", "闋" }, { "que", "闕" }, { "que", "阕" }, { "que", "阙" },
			{ "que", "雀" }, { "que", "鵲" }, { "que", "鹊" }, { "que ba", "却把" }, { "que ban", "雀斑" }, { "que bao", "确保" }, { "que bei", "却被" },
			{ "que bu", "却不" }, { "que bu neng", "却不能" }, { "que bu shi", "却不是" }, { "que bu zhi", "却不知" }, { "que bu zhi dao", "却不知道" }, { "que chao", "雀巢" },
			{ "que de", "缺德" }, { "que de", "缺的" }, { "que dian", "缺点" }, { "que ding", "确定" }, { "que ding xing", "确定性" }, { "que fa", "缺乏" },
			{ "que gai", "缺钙" }, { "que hai", "却还" }, { "que han", "缺憾" }, { "que hen", "却很" }, { "que huo", "缺货" }, { "que jian", "却见" }, { "que kou", "缺口" },
			{ "que li", "确立" }, { "que lian", "却连" }, { "que mei", "却没" }, { "que mei you", "却没有" }, { "que neng", "却能" }, { "que qian", "缺钱" },
			{ "que qie", "确切" }, { "que que shi shi", "确确实实" }, { "que rang", "却让" }, { "que ren", "确认" }, { "que ren", "缺人" }, { "que reng", "却仍" },
			{ "que shao", "缺少" }, { "que sheng", "缺省" }, { "que shi", "却是" }, { "que shi", "确实" }, { "que shi", "确是" }, { "que shi", "缺失" },
			{ "que shui", "缺水" }, { "que shuo", "却说" }, { "que sun", "缺损" }, { "que wei", "缺位" }, { "que wu", "却无" }, { "que xi", "缺席" }, { "que xian", "缺陷" },
			{ "que xin", "确信" }, { "que xue", "缺血" }, { "que xue xing", "缺血性" }, { "que yang", "缺氧" }, { "que yao", "却要" }, { "que ye", "却也" },
			{ "que yi", "却以" }, { "que yi", "却已" }, { "que yi bu ke", "缺一不可" }, { "que yin", "却因" }, { "que you", "却又" }, { "que you", "却有" },
			{ "que you", "确有" }, { "que yue", "雀跃" }, { "que zai", "却在" }, { "que zhen", "确诊" }, { "que zhen", "缺阵" }, { "qun", "囷" }, { "qun", "夋" },
			{ "qun", "宭" }, { "qun", "峮" }, { "qun", "箘" }, { "qun", "羣" }, { "qun", "群" }, { "qun", "裙" }, { "qun", "逡" }, { "qun", "麇" }, { "qun", "麕" },
			{ "qun dao", "群岛" }, { "qun fa", "群发" }, { "qun fa ruan jian", "群发软件" }, { "qun hao", "群号" }, { "qun ji", "群集" }, { "qun li", "群里" },
			{ "qun liao", "群聊" }, { "qun luo", "群落" }, { "qun nei", "群内" }, { "qun ou", "群殴" }, { "qun shan", "群山" }, { "qun ti", "群体" }, { "qun xing", "群星" },
			{ "qun xiong", "群雄" }, { "qun ying", "群英" }, { "qun zhong", "群中" }, { "qun zhong", "群众" }, { "qun zhong li yi", "群众利益" },
			{ "qun zhong xing", "群众性" }, { "qun zhong yan yuan", "群众演员" }, { "qun zi", "裙子" }, { "qun zu", "群组" }, { "ran", "冉" }, { "ran", "呥" },
			{ "ran", "姌" }, { "ran", "染" }, { "ran", "然" }, { "ran", "熯" }, { "ran", "燃" }, { "ran", "珃" }, { "ran", "苒" }, { "ran", "蚺" }, { "ran", "袡" },
			{ "ran", "髥" }, { "ran", "髯" }, { "ran cheng", "染成" }, { "ran er", "然而" }, { "ran fa", "染发" }, { "ran fang", "燃放" }, { "ran hong", "染红" },
			{ "ran hou", "然后" }, { "ran hou an", "然后按" }, { "ran hou dan ji", "然后单击" }, { "ran hou you", "然后又" }, { "ran liao", "染料" }, { "ran liao", "燃料" },
			{ "ran liao dian chi", "燃料电池" }, { "ran liao you", "燃料油" }, { "ran mei", "燃煤" }, { "ran qi", "燃气" }, { "ran qi", "燃起" }, { "ran ran", "冉冉" },
			{ "ran se", "染色" }, { "ran se ti", "染色体" }, { "ran shang", "染上" }, { "ran shao", "燃烧" }, { "ran you", "燃油" }, { "ran you shui", "燃油税" },
			{ "ran zhi", "染指" }, { "rang", "勷" }, { "rang", "嚷" }, { "rang", "壌" }, { "rang", "壤" }, { "rang", "懹" }, { "rang", "攘" }, { "rang", "瀼" },
			{ "rang", "爙" }, { "rang", "獽" }, { "rang", "瓤" }, { "rang", "禳" }, { "rang", "穣" }, { "rang", "穰" }, { "rang", "蘘" }, { "rang", "譲" },
			{ "rang", "讓" }, { "rang", "让" }, { "rang", "躟" }, { "rang", "鬤" }, { "rang ai", "让爱" }, { "rang bu", "让步" }, { "rang chu", "让出" },
			{ "rang gei", "让给" }, { "rang li", "让利" }, { "rang lu", "让路" }, { "rang ni", "让你" }, { "rang nin", "让您" }, { "rang nv ren", "让女人" },
			{ "rang qi", "让其" }, { "rang rang", "嚷嚷" }, { "rang ren", "让人" }, { "rang ren gan dong", "让人感动" }, { "rang ta", "让他" }, { "rang ta", "让她" },
			{ "rang ta", "让它" }, { "rang wo", "让我" }, { "rang zhe", "嚷着" }, { "rang zhe", "让这" }, { "rang zuo", "让座" }, { "rao", "娆" }, { "rao", "嬈" },
			{ "rao", "扰" }, { "rao", "擾" }, { "rao", "桡" }, { "rao", "橈" }, { "rao", "犪" }, { "rao", "繞" }, { "rao", "绕" }, { "rao", "荛" }, { "rao", "襓" },
			{ "rao", "遶" }, { "rao", "隢" }, { "rao", "饒" }, { "rao", "饶" }, { "rao dao", "绕到" }, { "rao dao", "绕道" }, { "rao guo", "绕过" }, { "rao kai", "绕开" },
			{ "rao le", "饶了" }, { "rao luan", "扰乱" }, { "rao min", "扰民" } };
};
