package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN09 {
	public static String[][] pl = { { "da xing", "大兴" }, { "da xing", "大型" }, { "da xing chao shi", "大型超市" }, { "da xing huo dong", "大型活动" },
			{ "da xing qi dao", "大行其道" }, { "da xing qi ye", "大型企业" }, { "da xing qu", "大兴区" }, { "da xing xing", "大猩猩" }, { "da xiong", "大熊" },
			{ "da xiong", "大雄" }, { "da xiong mao", "大熊猫" }, { "da xiu", "大修" }, { "da xuan", "大选" }, { "da xue", "大学" }, { "da xue", "大雪" },
			{ "da xue ben ke", "大学本科" }, { "da xue bi ye", "大学毕业" }, { "da xue cheng", "大学城" }, { "da xue jiao shou", "大学教授" }, { "da xue jiao yu", "大学教育" },
			{ "da xue lao shi", "大学老师" }, { "da xue li", "大学里" }, { "da xue sheng", "大学生" }, { "da xue sheng huo", "大学生活" }, { "da xue shi dai", "大学时代" },
			{ "da xue si nian", "大学四年" }, { "da xue tong xue", "大学同学" }, { "da xue xiao yuan", "大学校园" }, { "da xue xiao zhang", "大学校长" },
			{ "da xue ying yu", "大学英语" }, { "da ya", "大牙" }, { "da ya", "打压" }, { "da ya wan", "大亚湾" }, { "da yan", "大眼" }, { "da yan", "大雁" },
			{ "da yan bu can", "大言不惭" }, { "da yan jing", "大眼睛" }, { "da yang", "大洋" }, { "da yang", "打样" }, { "da yao fang", "大药房" }, { "da ye", "大业" },
			{ "da ye", "大爷" }, { "da ye", "大野" }, { "da yi", "大一" }, { "da yi", "大义" }, { "da yi", "大姨" }, { "da yi", "大意" }, { "da yi", "大衣" },
			{ "da yi", "打一" }, { "da yi", "答疑" }, { "da yi ma", "大姨妈" }, { "da yi yuan", "大医院" }, { "da yin", "打印" }, { "da yin chu lai", "打印出来" },
			{ "da yin ji", "打印机" }, { "da ying", "打赢" }, { "da ying", "答应" }, { "da ying jia", "大赢家" }, { "da ying wo", "答应我" }, { "da yong", "大勇" },
			{ "da you", "大有" }, { "da you ke wei", "大有可为" }, { "da you ren zai", "大有人在" }, { "da you xi", "打游戏" }, { "da yu", "大于" }, { "da yu", "大宇" },
			{ "da yu", "大禹" }, { "da yu", "大雨" }, { "da yu", "大鱼" }, { "da yu mao qiu", "打羽毛球" }, { "da yuan", "大元" }, { "da yuan", "大院" },
			{ "da yuan shuai", "大元帅" }, { "da yue", "大约" }, { "da yue jin", "大跃进" }, { "da yun", "大运" }, { "da za", "打杂" }, { "da za hui", "大杂烩" },
			{ "da zai", "打在" }, { "da zai", "搭在" }, { "da zai", "搭载" }, { "da zao", "大枣" }, { "da zao", "打造" }, { "da zao cheng", "打造成" },
			{ "da zao chu", "打造出" }, { "da zeng", "大增" }, { "da zha xie", "大闸蟹" }, { "da zhan", "大展" }, { "da zhan", "大战" }, { "da zhang", "大涨" },
			{ "da zhang", "打仗" }, { "da zhang fu", "大丈夫" }, { "da zhang qi gu", "大张旗鼓" }, { "da zhao hu", "打招呼" }, { "da zhe", "打折" }, { "da zhe", "打着" },
			{ "da zhe ji piao", "打折机票" }, { "da zhen", "大震" }, { "da zhen", "打针" }, { "da zhi", "大志" }, { "da zhi", "大致" }, { "da zhi", "大郅" },
			{ "da zhi hui", "大智慧" }, { "da zhong", "大中" }, { "da zhong", "大众" }, { "da zhong", "打中" }, { "da zhong cheng shi", "大中城市" },
			{ "da zhong hua", "大中华" }, { "da zhong hua", "大众化" }, { "da zhong hua qu", "大中华区" }, { "da zhong qi che", "大众汽车" }, { "da zhong xing", "大中型" },
			{ "da zhong zhuan", "大中专" }, { "da zhou", "达州" }, { "da zhu", "大猪" }, { "da zhu", "打住" }, { "da zhuan", "大专" }, { "da zhuan", "大赚" },
			{ "da zhuan", "打转" }, { "da zhuan yuan xiao", "大专院校" }, { "da zi", "大字" }, { "da zi", "打字" }, { "da zi bao", "大字报" }, { "da zi ran", "大自然" },
			{ "da zong", "大宗" }, { "da zui", "大嘴" }, { "da zui ba", "大嘴巴" }, { "da zuo", "大作" }, { "da zuo", "打坐" }, { "dai", "代" }, { "dai", "傣" },
			{ "dai", "呆" }, { "dai", "呔" }, { "dai", "埭" }, { "dai", "大" }, { "dai", "岱" }, { "dai", "带" }, { "dai", "帯" }, { "dai", "帶" }, { "dai", "待" },
			{ "dai", "怠" }, { "dai", "戴" }, { "dai", "柋" }, { "dai", "歹" }, { "dai", "殆" }, { "dai", "汏" }, { "dai", "瀻" }, { "dai", "獃" }, { "dai", "玳" },
			{ "dai", "甙" }, { "dai", "紿" }, { "dai", "绐" }, { "dai", "艜" }, { "dai", "袋" }, { "dai", "襶" }, { "dai", "貸" }, { "dai", "贷" }, { "dai", "軑" },
			{ "dai", "軩" }, { "dai", "迨" }, { "dai", "逮" }, { "dai", "靆" }, { "dai", "黛" }, { "dai an na", "戴安娜" }, { "dai ban", "代办" }, { "dai ban", "呆板" },
			{ "dai biao", "代表" }, { "dai biao chu", "代表处" }, { "dai biao da hui", "代表大会" }, { "dai biao dui", "代表队" }, { "dai biao ren wu", "代表人物" },
			{ "dai biao tuan", "代表团" }, { "dai biao xing", "代表性" }, { "dai biao zuo", "代表作" }, { "dai bing", "带兵" }, { "dai bing", "带病" }, { "dai bu", "代步" },
			{ "dai bu", "逮捕" }, { "dai chu", "带出" }, { "dai dai", "呆呆" }, { "dai dai", "带带" }, { "dai dai de", "呆呆的" }, { "dai dao", "带刀" },
			{ "dai dao", "带到" }, { "dai dao", "待到" }, { "dai dao", "逮到" }, { "dai dian", "带点" }, { "dai dian", "带电" }, { "dai ding", "待定" },
			{ "dai dong", "带动" }, { "dai dui", "带队" }, { "dai er", "戴尔" }, { "dai er gong si", "戴尔公司" }, { "dai fa", "代发" }, { "dai fu", "大夫" },
			{ "dai ge", "带个" }, { "dai gei", "带给" }, { "dai gei ni", "带给你" }, { "dai gong", "代工" }, { "dai gou", "代沟" }, { "dai gou", "代购" },
			{ "dai guan", "代管" }, { "dai guo", "呆过" }, { "dai guo", "带过" }, { "dai hai zi", "带孩子" }, { "dai hao", "代号" }, { "dai hao", "带好" },
			{ "dai huai", "带坏" }, { "dai hui", "代会" }, { "dai hui", "带回" }, { "dai hui er", "待会儿" }, { "dai hui jia", "带回家" }, { "dai ji", "待机" },
			{ "dai ji shi jian", "待机时间" }, { "dai jia", "代价" }, { "dai jian", "待见" }, { "dai jin", "带进" }, { "dai jin", "殆尽" }, { "dai kai", "代开" },
			{ "dai kao", "代考" }, { "dai ke", "代课" }, { "dai kuan", "带宽" }, { "dai kuan", "贷款" }, { "dai kuan li lv", "贷款利率" }, { "dai lai", "带来" },
			{ "dai lao", "代劳" }, { "dai le", "待了" }, { "dai li", "代理" }, { "dai li fei", "代理费" }, { "dai li gong si", "代理公司" }, { "dai li ji gou", "代理机构" },
			{ "dai li ren", "代理人" }, { "dai li shang", "代理商" }, { "dai lian", "代练" }, { "dai ling", "带领" }, { "dai lu", "带路" }, { "dai ma", "代码" },
			{ "dai man", "怠慢" }, { "dai ming", "待命" }, { "dai ming ci", "代名词" }, { "dai ni", "带你" }, { "dai qiu", "带球" }, { "dai qu", "带去" },
			{ "dai ren", "代人" }, { "dai ren", "带人" }, { "dai ren", "待人" }, { "dai ru", "代入" }, { "dai ru", "带入" }, { "dai shang", "带上" },
			{ "dai shang", "戴上" }, { "dai shou", "代收" }, { "dai shu", "代数" }, { "dai shu", "袋鼠" }, { "dai su", "怠速" }, { "dai ta", "带他" }, { "dai ta", "带她" },
			{ "dai ti", "代替" }, { "dai tou", "带头" }, { "dai tou ren", "带头人" }, { "dai tu", "歹徒" }, { "dai wei", "代为" }, { "dai wei", "戴维" },
			{ "dai wei si", "戴维斯" }, { "dai wo", "带我" }, { "dai wo", "待我" }, { "dai xiao", "代销" }, { "dai xie", "代谢" }, { "dai xie", "带些" },
			{ "dai xin", "带薪" }, { "dai xin xiu jia", "带薪休假" }, { "dai yan", "代言" }, { "dai yan jing", "戴眼镜" }, { "dai yan ren", "代言人" }, { "dai ye", "待业" },
			{ "dai you", "带有" }, { "dai yu", "带鱼" }, { "dai yu", "待遇" }, { "dai yu", "黛玉" }, { "dai zai", "呆在" }, { "dai zai", "待在" }, { "dai zai", "戴在" },
			{ "dai zhe", "呆着" }, { "dai zhe", "带着" }, { "dai zhe", "待着" }, { "dai zhe", "戴着" }, { "dai zhe hai zi", "带着孩子" }, { "dai zhi", "代之" },
			{ "dai zhi", "呆滞" }, { "dai zhu", "呆住" }, { "dai zhu", "逮住" }, { "dai zhuang", "袋装" }, { "dai zi", "呆子" }, { "dai zi", "带子" }, { "dai zi", "袋子" },
			{ "dai zou", "带走" }, { "dai zu", "傣族" }, { "dan", "丹" }, { "dan", "亶" }, { "dan", "亻" }, { "dan", "但" }, { "dan", "儋" }, { "dan", "刐" },
			{ "dan", "勯" }, { "dan", "匰" }, { "dan", "单" }, { "dan", "卩" }, { "dan", "啖" }, { "dan", "啗" }, { "dan", "啿" }, { "dan", "單" }, { "dan", "噉" },
			{ "dan", "嚪" }, { "dan", "帎" }, { "dan", "弹" }, { "dan", "惮" }, { "dan", "憚" }, { "dan", "憺" }, { "dan", "担" }, { "dan", "掸" }, { "dan", "擔" },
			{ "dan", "旦" }, { "dan", "柦" }, { "dan", "殚" }, { "dan", "殫" }, { "dan", "氮" }, { "dan", "沊" }, { "dan", "泹" }, { "dan", "淡" }, { "dan", "澸" },
			{ "dan", "澹" }, { "dan", "燀" }, { "dan", "狚" }, { "dan", "玬" }, { "dan", "甔" }, { "dan", "疸" }, { "dan", "瘅" }, { "dan", "癚" }, { "dan", "眈" },
			{ "dan", "石" }, { "dan", "砃" }, { "dan", "禫" }, { "dan", "窞" }, { "dan", "箪" }, { "dan", "簞" }, { "dan", "紞" }, { "dan", "耽" }, { "dan", "聃" },
			{ "dan", "聸" }, { "dan", "胆" }, { "dan", "膽" }, { "dan", "萏" }, { "dan", "蛋" }, { "dan", "蜑" }, { "dan", "衴" }, { "dan", "褝" }, { "dan", "襌" },
			{ "dan", "觛" }, { "dan", "誕" }, { "dan", "譂" }, { "dan", "诞" }, { "dan", "贉" }, { "dan", "赕" }, { "dan", "郸" }, { "dan", "鄲" }, { "dan", "酖" },
			{ "dan", "霮" }, { "dan", "髧" }, { "dan", "鴠" }, { "dan", "黕" }, { "dan bai", "蛋白" }, { "dan bai zhi", "蛋白质" }, { "dan ban", "单板" },
			{ "dan bao", "担保" }, { "dan bao gong si", "担保公司" }, { "dan bao ren", "担保人" }, { "dan bian", "单边" }, { "dan bo", "单薄" }, { "dan bo", "淡泊" },
			{ "dan bo", "淡薄" }, { "dan bu", "但不" }, { "dan bu neng", "但不能" }, { "dan ceng", "单层" }, { "dan chan", "单产" }, { "dan chang", "单场" },
			{ "dan chao fan", "蛋炒饭" }, { "dan che", "单车" }, { "dan chen", "诞辰" }, { "dan cheng", "单程" }, { "dan chu", "淡出" }, { "dan chun", "单纯" },
			{ "dan ci", "单次" }, { "dan ci", "单词" }, { "dan cong", "但从" }, { "dan cong", "单从" }, { "dan da", "单打" }, { "dan da", "胆大" }, { "dan dan", "丹丹" },
			{ "dan dan", "单单" }, { "dan dan", "淡淡" }, { "dan dan", "蛋蛋" }, { "dan dang", "但当" }, { "dan dang", "担当" }, { "dan dao", "单刀" },
			{ "dan dao", "弹道" }, { "dan dao dao dan", "弹道导弹" }, { "dan dian", "单点" }, { "dan diao", "单调" }, { "dan ding", "淡定" }, { "dan dong", "丹东" },
			{ "dan dou", "但都" }, { "dan du", "单独" }, { "dan dui", "但对" }, { "dan dui yu", "但对于" }, { "dan fan", "但凡" }, { "dan fan", "单反" },
			{ "dan fang", "单方" }, { "dan fang mian", "单方面" }, { "dan fei", "单飞" }, { "dan fei", "氮肥" }, { "dan fu", "担负" }, { "dan gai", "但该" },
			{ "dan gan", "单干" }, { "dan gan", "胆敢" }, { "dan gang", "担纲" }, { "dan gao", "蛋糕" }, { "dan ge", "单个" }, { "dan ge", "耽搁" },
			{ "dan gu chun", "胆固醇" }, { "dan hai", "但还" }, { "dan hai shi", "但还是" }, { "dan hao", "单号" }, { "dan he", "单核" }, { "dan hen", "但很" },
			{ "dan hong su", "胆红素" }, { "dan hua", "淡化" }, { "dan huang", "蛋黄" }, { "dan huang se", "淡黄色" }, { "dan ji", "单击" }, { "dan ji", "单机" },
			{ "dan ji", "淡季" }, { "dan ji ban", "单机版" }, { "dan ji you xi", "单机游戏" }, { "dan jia", "单价" }, { "dan jia", "担架" }, { "dan jian", "但见" },
			{ "dan jian", "单件" }, { "dan jian", "单间" }, { "dan jiu", "单就" }, { "dan ju", "单据" }, { "dan kao", "单靠" }, { "dan ke", "蛋壳" },
			{ "dan ke yi", "但可以" }, { "dan lan", "淡蓝" }, { "dan lan se", "淡蓝色" }, { "dan le", "淡了" }, { "dan lian", "单恋" }, { "dan liang", "胆量" },
			{ "dan mai", "丹麦" }, { "dan mei", "但没" }, { "dan mei", "耽美" }, { "dan mian", "单面" }, { "dan mo", "淡漠" }, { "dan mu qian", "但目前" },
			{ "dan na", "但那" }, { "dan nang", "胆囊" }, { "dan neng", "但能" }, { "dan ni", "丹尼" }, { "dan ni", "但你" }, { "dan ni er", "丹尼尔" },
			{ "dan ni si", "丹尼斯" }, { "dan pian", "单片" }, { "dan pian ji", "单片机" }, { "dan pin", "单品" }, { "dan ping", "单凭" }, { "dan qi", "但其" },
			{ "dan qi", "氮气" }, { "dan qie", "胆怯" }, { "dan qin", "单亲" }, { "dan qing", "丹青" }, { "dan qing", "蛋清" }, { "dan qiu", "但求" }, { "dan qu", "单曲" },
			{ "dan que", "但却" }, { "dan ran", "淡然" }, { "dan ren", "单人" }, { "dan ren", "担任" }, { "dan reng", "但仍" }, { "dan ri", "单日" }, { "dan se", "单色" },
			{ "dan shen", "单身" }, { "dan shen han", "单身汉" }, { "dan sheng", "诞生" }, { "dan shi", "但是" }, { "dan shi", "单是" }, { "dan shi", "胆识" },
			{ "dan shou", "单手" }, { "dan shu", "单数" }, { "dan shuang", "单双" }, { "dan shui", "淡水" }, { "dan ta", "但他" }, { "dan ta", "但她" },
			{ "dan ta", "但它" }, { "dan ta", "蛋挞" }, { "dan ta men", "但他们" }, { "dan ta que", "但他却" }, { "dan ti", "单体" }, { "dan tian", "丹田" },
			{ "dan tiao", "单挑" }, { "dan tiao", "单条" }, { "dan tong shi", "但同时" }, { "dan tou", "弹头" }, { "dan wang", "淡忘" }, { "dan wei", "但未" },
			{ "dan wei", "单位" }, { "dan wei ling dao", "单位领导" }, { "dan wo", "但我" }, { "dan wu", "耽误" }, { "dan xian", "单线" }, { "dan xian zai", "但现在" },
			{ "dan xiang", "单向" }, { "dan xiang", "单项" }, { "dan xiang shou fei", "单向收费" }, { "dan xiao", "胆小" }, { "dan xiao gui", "胆小鬼" },
			{ "dan xin", "担心" }, { "dan xing", "单行" }, { "dan xuan", "单选" }, { "dan ya", "淡雅" }, { "dan yan pi", "单眼皮" }, { "dan yang", "丹阳" },
			{ "dan yao", "但要" }, { "dan yao", "弹药" }, { "dan ye", "但也" }, { "dan ye", "单页" }, { "dan yi", "单一" }, { "dan yin", "但因" }, { "dan you", "但又" },
			{ "dan you", "但有" }, { "dan you", "担忧" }, { "dan you yu", "但由于" }, { "dan yu", "但与" }, { "dan yu", "耽于" }, { "dan yuan", "但愿" },
			{ "dan yuan", "单元" }, { "dan yuan ce shi", "单元测试" }, { "dan yuan ge", "单元格" }, { "dan yue", "单月" }, { "dan zai", "但在" },
			{ "dan zhan xin jing", "胆战心惊" }, { "dan zhang", "单张" }, { "dan zhe", "但这" }, { "dan zheng", "单证" }, { "dan zhi", "胆汁" }, { "dan zi", "单子" },
			{ "dan zi", "担子" }, { "dan zi", "胆子" }, { "dan zong", "但总" }, { "dang", "儅" }, { "dang", "党" }, { "dang", "凼" }, { "dang", "噹" }, { "dang", "宕" },
			{ "dang", "当" }, { "dang", "挡" }, { "dang", "擋" }, { "dang", "档" }, { "dang", "檔" }, { "dang", "澢" }, { "dang", "璗" }, { "dang", "璫" },
			{ "dang", "瓽" }, { "dang", "當" }, { "dang", "盪" }, { "dang", "砀" }, { "dang", "碭" }, { "dang", "礑" }, { "dang", "簹" }, { "dang", "艡" },
			{ "dang", "荡" }, { "dang", "菪" }, { "dang", "蕩" }, { "dang", "蟷" }, { "dang", "裆" }, { "dang", "襠" }, { "dang", "讜" }, { "dang", "谠" },
			{ "dang", "鐺" }, { "dang", "铛" }, { "dang", "黨" }, { "dang an", "档案" }, { "dang an gong zuo", "档案工作" }, { "dang an guan", "档案馆" },
			{ "dang an guan li", "档案管理" }, { "dang an ju", "档案局" }, { "dang ban", "挡板" }, { "dang bao", "党报" }, { "dang bing", "当兵" },
			{ "dang bu zhu", "挡不住" }, { "dang chang", "当场" }, { "dang cheng", "当成" }, { "dang chu", "当初" }, { "dang chu", "挡出" }, { "dang ci", "档次" },
			{ "dang dai", "当代" }, { "dang dai biao", "党代表" }, { "dang dai hui", "党代会" }, { "dang dai yi shu", "当代艺术" }, { "dang dai zhong guo", "当代中国" },
			{ "dang dang", "当当" }, { "dang dang wang", "当当网" }, { "dang dao", "当道" }, { "dang de", "党的" }, { "dang di", "当地" }, { "dang di ren", "当地人" },
			{ "dang di shi jian", "当地时间" }, { "dang di zheng fu", "当地政府" }, { "dang dui", "党对" }, { "dang fei", "党费" }, { "dang fu", "荡妇" },
			{ "dang ge", "当个" }, { "dang gong wei", "党工委" }, { "dang guan", "当官" }, { "dang gui", "当归" }, { "dang guo", "当过" }, { "dang hao", "当好" },
			{ "dang he guo jia", "党和国家" }, { "dang he ren min", "党和人民" }, { "dang he zheng fu", "党和政府" }, { "dang hong", "当红" }, { "dang ji", "当即" },
			{ "dang jia", "当家" }, { "dang jia zuo zhu", "当家作主" }, { "dang jian", "党建" }, { "dang jian gong zuo", "党建工作" }, { "dang jie", "当街" },
			{ "dang jin", "当今" }, { "dang jin she hui", "当今社会" }, { "dang jin shi jie", "当今世界" }, { "dang jin zhong guo", "当今中国" }, { "dang ju", "当局" },
			{ "dang ke", "党课" }, { "dang lao ban", "当老板" }, { "dang le", "当了" }, { "dang mian", "当面" }, { "dang nei", "党内" }, { "dang nei min zhu", "党内民主" },
			{ "dang ni", "当你" }, { "dang nian", "当年" }, { "dang nin", "当您" }, { "dang pai", "党派" }, { "dang pu", "当铺" }, { "dang qi", "当期" },
			{ "dang qi", "档期" }, { "dang qi hui chang", "荡气回肠" }, { "dang qian", "当前" }, { "dang quan zhe", "当权者" }, { "dang ran", "当然" },
			{ "dang ran wu cun", "荡然无存" }, { "dang ren", "当人" }, { "dang ren bu rang", "当仁不让" }, { "dang ri", "当日" }, { "dang shang", "当上" },
			{ "dang shang le", "当上了" }, { "dang shi", "党史" }, { "dang shi", "当事" }, { "dang shi", "当时" }, { "dang shi ren", "当事人" }, { "dang shu", "当属" },
			{ "dang ta", "当他" }, { "dang ta", "当她" }, { "dang ta", "当它" }, { "dang tian", "当天" }, { "dang ting", "当庭" }, { "dang tou", "当头" },
			{ "dang wan", "当晚" }, { "dang wei", "党委" }, { "dang wei", "档位" }, { "dang wei shu ji", "党委书记" }, { "dang wo", "当我" }, { "dang wu", "党务" },
			{ "dang wu zhi ji", "当务之急" }, { "dang xia", "当下" }, { "dang xiao", "党校" }, { "dang xin", "当心" }, { "dang xing", "党性" }, { "dang xuan", "当选" },
			{ "dang yang", "荡漾" }, { "dang yuan", "党员" }, { "dang yuan gan bu", "党员干部" }, { "dang yue", "当月" }, { "dang zai", "党在" }, { "dang zai", "挡在" },
			{ "dang zhang", "党章" }, { "dang zhe", "当着" }, { "dang zhe", "挡着" }, { "dang zhen", "当真" }, { "dang zheng", "党政" },
			{ "dang zheng ji guan", "党政机关" }, { "dang zheng ling dao", "党政领导" }, { "dang zhi bu", "党支部" }, { "dang zhi wu kui", "当之无愧" },
			{ "dang zhong", "当中" }, { "dang zhong", "当众" }, { "dang zhong yang", "党中央" }, { "dang zhu", "挡住" }, { "dang zhu xi", "党主席" },
			{ "dang zong zhi", "党总支" }, { "dang zu", "党组" }, { "dang zu shu ji", "党组书记" }, { "dang zu zhi", "党组织" }, { "dang zuo", "当作" },
			{ "dang zuo", "当做" }, { "dao", "倒" }, { "dao", "儔" }, { "dao", "刀" }, { "dao", "刂" }, { "dao", "到" }, { "dao", "叨" }, { "dao", "壔" },
			{ "dao", "导" }, { "dao", "導" }, { "dao", "屶" }, { "dao", "岛" }, { "dao", "島" }, { "dao", "嶋" }, { "dao", "嶌" }, { "dao", "嶹" }, { "dao", "帱" },
			{ "dao", "幬" }, { "dao", "忉" }, { "dao", "悼" }, { "dao", "捣" }, { "dao", "捯" }, { "dao", "搗" }, { "dao", "擣" }, { "dao", "椡" }, { "dao", "槝" },
			{ "dao", "檤" }, { "dao", "氘" }, { "dao", "焘" }, { "dao", "瓙" }, { "dao", "盗" }, { "dao", "盜" }, { "dao", "祷" }, { "dao", "禂" }, { "dao", "禱" },
			{ "dao", "稲" }, { "dao", "稻" }, { "dao", "纛" }, { "dao", "翿" }, { "dao", "舠" }, { "dao", "菿" }, { "dao", "裯" }, { "dao", "蹈" }, { "dao", "道" },
			{ "dao", "釖" }, { "dao", "陦" }, { "dao", "隝" }, { "dao", "隯" }, { "dao", "魛" }, { "dao ban", "盗版" }, { "dao bi", "倒闭" }, { "dao bie", "道别" },
			{ "dao bu", "倒不" }, { "dao bu liao", "到不了" }, { "dao bu ru", "倒不如" }, { "dao bu shi", "倒不是" }, { "dao cai", "道菜" }, { "dao cao", "稻草" },
			{ "dao cao ren", "稻草人" }, { "dao chang", "到场" }, { "dao chang", "道场" }, { "dao che", "倒车" }, { "dao chu", "到处" }, { "dao chu", "导出" },
			{ "dao chu", "道出" }, { "dao chu dou shi", "到处都是" }, { "dao ci", "到此" }, { "dao da", "到达" }, { "dao dan", "导弹" }, { "dao dan", "捣蛋" },
			{ "dao dao", "刀刀" }, { "dao dao", "叨叨" }, { "dao dao", "道道" }, { "dao de", "道德" }, { "dao de guan", "道德观" }, { "dao de gui fan", "道德规范" },
			{ "dao de jiao yu", "道德教育" }, { "dao di", "倒地" }, { "dao di", "到底" }, { "dao di", "到第" }, { "dao di shi shui", "到底是谁" }, { "dao di shui", "到底谁" },
			{ "dao dian", "导电" }, { "dao diao", "倒掉" }, { "dao du", "导读" }, { "dao fa", "刀法" }, { "dao fang", "到访" }, { "dao feng", "刀锋" },
			{ "dao gai", "到该" }, { "dao gang", "到港" }, { "dao gao", "祷告" }, { "dao gou", "导购" }, { "dao gu", "捣鼓" }, { "dao gu", "稻谷" }, { "dao gua", "倒挂" },
			{ "dao guan", "导管" }, { "dao guang", "道光" }, { "dao gui", "导轨" }, { "dao guo", "到过" }, { "dao guo", "岛国" }, { "dao guo lai", "倒过来" },
			{ "dao hai", "倒还" }, { "dao hang", "导航" }, { "dao hang jian", "导航键" }, { "dao hang xi tong", "导航系统" }, { "dao hao", "倒好" }, { "dao hao", "盗号" },
			{ "dao heng", "道行" }, { "dao hu", "到户" }, { "dao hui", "到会" }, { "dao hui", "捣毁" }, { "dao huo", "到货" }, { "dao huo suo", "导火索" },
			{ "dao huo xian", "导火线" }, { "dao ji shi", "倒计时" }, { "dao jia", "到家" }, { "dao jia", "道家" }, { "dao jian", "刀剑" }, { "dao jiao", "道教" },
			{ "dao jin", "倒进" }, { "dao ju", "刀具" }, { "dao ju", "道具" }, { "dao ke", "刀客" }, { "dao kou", "刀口" }, { "dao kou", "道口" }, { "dao lai", "到来" },
			{ "dao lang", "刀郎" }, { "dao lao", "到老" }, { "dao le", "倒了" }, { "dao le", "到了" }, { "dao li", "倒立" }, { "dao li", "道理" }, { "dao lian", "盗链" },
			{ "dao liu", "倒流" }, { "dao lu", "道路" }, { "dao lu jiao tong", "道路交通" }, { "dao lu yun shu", "道路运输" }, { "dao luan", "捣乱" }, { "dao lun", "导论" },
			{ "dao mai", "倒卖" }, { "dao mao an ran", "道貌岸然" }, { "dao mei", "倒霉" }, { "dao mi", "稻米" }, { "dao mu", "盗墓" }, { "dao na", "到哪" },
			{ "dao na", "到那" }, { "dao na li qu", "到哪里去" }, { "dao na qu", "到哪去" }, { "dao nei", "岛内" }, { "dao ni", "到你" }, { "dao nian", "悼念" },
			{ "dao nin", "到您" }, { "dao pian", "刀片" }, { "dao qi", "到期" }, { "dao qi", "到齐" }, { "dao qian", "道歉" }, { "dao qiao", "刀鞘" }, { "dao qie", "盗窃" },
			{ "dao qiong si", "道琼斯" }, { "dao qu", "盗取" }, { "dao ren", "刀刃" }, { "dao ren", "道人" }, { "dao ru", "倒入" }, { "dao ru", "导入" },
			{ "dao shang", "岛上" }, { "dao shang", "道上" }, { "dao shi", "倒是" }, { "dao shi", "到时" }, { "dao shi", "导师" }, { "dao shi", "道士" },
			{ "dao shou", "到手" }, { "dao shu", "倒数" }, { "dao shu di er", "倒数第二" }, { "dao shui", "倒水" }, { "dao si", "到死" }, { "dao ta", "倒塌" },
			{ "dao ta", "到他" }, { "dao teng", "倒腾" }, { "dao ti", "导体" }, { "dao ti", "道题" }, { "dao tian", "稻田" }, { "dao tie", "倒贴" },
			{ "dao ting tu shuo", "道听途说" }, { "dao tou", "到头" }, { "dao tou lai", "到头来" }, { "dao tui", "倒退" }, { "dao wan", "到晚" }, { "dao wei", "到位" },
			{ "dao wo", "到我" }, { "dao xia", "倒下" }, { "dao xian", "导线" }, { "dao xiang", "导向" }, { "dao xiao", "到校" }, { "dao xie", "道谢" },
			{ "dao xin", "到新" }, { "dao yan", "导演" }, { "dao ye", "倒也" }, { "dao yi", "道义" }, { "dao yin", "导引" }, { "dao ying", "倒影" }, { "dao yong", "盗用" },
			{ "dao you", "导游" }, { "dao yu", "岛屿" }, { "dao zai", "倒在" }, { "dao zei", "盗贼" }, { "dao zhan", "到站" }, { "dao zhang", "到帐" },
			{ "dao zhang", "道长" }, { "dao zhe", "到这" }, { "dao zhi", "倒置" }, { "dao zhi", "导致" }, { "dao zi", "刀子" }, { "de", "地" }, { "de", "底" },
			{ "de", "得" }, { "de", "徳" }, { "de", "德" }, { "de", "悳" }, { "de", "淂" }, { "de", "的" }, { "de", "锝" }, { "de ai", "的爱" },
			{ "de bang zhu xia", "的帮助下" }, { "de bi", "得比" }, { "de bi", "德比" }, { "de bing", "得病" }, { "de bo ke", "的博客" }, { "de bu", "得不" },
			{ "de bu chang shi", "得不偿失" }, { "de bu dao", "得不到" }, { "de cheng", "得逞" }, { "de chu", "得出" }, { "de da", "的大" }, { "de dang", "得当" },
			{ "de dao", "得到" }, { "de dao", "得道" }, { "de dao shen me", "得到什么" }, { "de de", "得得" }, { "de di", "的第" }, { "de duo", "得多" }, { "de er", "德尔" },
			{ "de er man", "德尔曼" }, { "de fen", "得分" }, { "de feng", "的风" }, { "de gao wang zhong", "德高望重" }, { "de ge", "的歌" }, { "de geng", "得更" },
			{ "de guo", "得过" }, { "de guo", "德国" }, { "de guo dui", "德国队" }, { "de guo ren", "德国人" }, { "de hao", "得好" }, { "de hao", "的好" },
			{ "de hen", "得很" }, { "de hen hao", "得很好" }, { "de hua", "的话" }, { "de ji chu shang", "的基础上" }, { "de jia", "德甲" }, { "de jia", "的家" },
			{ "de jian", "得见" }, { "de jiang", "得奖" }, { "de jiu", "得救" }, { "de jun", "德军" }, { "de ke", "德科" }, { "de kuai", "得快" }, { "de la", "德拉" },
			{ "de lai", "得来" }, { "de lao", "的老" }, { "de le", "得了" }, { "de li", "得利" }, { "de li", "得力" }, { "de lian", "的脸" }, { "de liao", "得了" },
			{ "de long", "德隆" }, { "de lu", "的路" }, { "de lu yi", "德鲁伊" }, { "de luo ba", "德罗巴" }, { "de ma", "的吗" }, { "de ming", "得名" }, { "de piao", "得票" },
			{ "de qi", "得起" }, { "de qian", "的钱" }, { "de qin", "德勤" }, { "de ren", "得人" }, { "de ren", "的人" }, { "de shang", "得上" }, { "de sheng", "德胜" },
			{ "de shi", "得失" }, { "de shi", "的事" }, { "de shi", "的是" } };
};
