package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN53 {
	public static String[][] pl = { { "xin lai", "信赖" }, { "xin lai", "心来" }, { "xin lai", "新来" }, { "xin lai de", "新来的" }, { "xin lang", "新浪" },
			{ "xin lang", "新郎" }, { "xin lang bo ke", "新浪博客" }, { "xin lang cai jing", "新浪财经" }, { "xin lang ke ji", "新浪科技" }, { "xin lang ti yu", "新浪体育" },
			{ "xin lang wang", "新浪网" }, { "xin lang yu le", "新浪娱乐" }, { "xin lao", "新老" }, { "xin lao", "辛劳" }, { "xin li", "心力" }, { "xin li", "心理" },
			{ "xin li", "心里" }, { "xin li ce shi", "心理测试" }, { "xin li hua", "心里话" }, { "xin li jian kang", "心理健康" }, { "xin li shuai jie", "心力衰竭" },
			{ "xin li su zhi", "心理素质" }, { "xin li wen ti", "心理问题" }, { "xin li xue", "心理学" }, { "xin li xue jia", "心理学家" }, { "xin li ya li", "心理压力" },
			{ "xin li yi sheng", "心理医生" }, { "xin li yin su", "心理因素" }, { "xin li zhang ai", "心理障碍" }, { "xin li zhi liao", "心理治疗" },
			{ "xin li zhuang tai", "心理状态" }, { "xin li zhun bei", "心理准备" }, { "xin li zi xun", "心理咨询" }, { "xin ling", "信令" }, { "xin ling", "心灵" },
			{ "xin lou", "新楼" }, { "xin lu", "新路" }, { "xin lu li cheng", "心路历程" }, { "xin lv", "心率" }, { "xin lv shi chang", "心律失常" }, { "xin mai", "新买" },
			{ "xin man yi zu", "心满意足" }, { "xin mei ti", "新媒体" }, { "xin min", "新民" }, { "xin mo", "心魔" }, { "xin mu", "心目" }, { "xin nian", "信念" },
			{ "xin nian", "新年" }, { "xin nian kuai le", "新年快乐" }, { "xin niang", "新娘" }, { "xin niang zi", "新娘子" }, { "xin pan", "新盘" }, { "xin pian", "新片" },
			{ "xin pian", "芯片" }, { "xin pian zu", "芯片组" }, { "xin pin", "新品" }, { "xin ping qi he", "心平气和" }, { "xin pu sen", "辛普森" }, { "xin qi", "新奇" },
			{ "xin qiao", "新桥" }, { "xin qie", "心切" }, { "xin qin", "辛勤" }, { "xin qin lao dong", "辛勤劳动" }, { "xin qing", "心情" },
			{ "xin qing bu hao", "心情不好" }, { "xin qing hao", "心情好" }, { "xin qu", "新区" }, { "xin qu", "新曲" }, { "xin ran", "欣然" }, { "xin ren", "信任" },
			{ "xin ren", "新人" }, { "xin ren", "新任" }, { "xin ren du", "信任度" }, { "xin ru", "心如" }, { "xin ruan", "心软" }, { "xin rui", "新锐" },
			{ "xin sai ji", "新赛季" }, { "xin shang", "心上" }, { "xin shang", "欣赏" }, { "xin shang ren", "心上人" }, { "xin shen", "心神" }, { "xin sheng", "心声" },
			{ "xin sheng", "心生" }, { "xin sheng", "新生" }, { "xin sheng dai", "新生代" }, { "xin sheng er", "新生儿" }, { "xin sheng shi wu", "新生事物" },
			{ "xin shi", "信使" }, { "xin shi", "心事" }, { "xin shi", "新式" }, { "xin shi", "新诗" }, { "xin shi dan dan", "信誓旦旦" }, { "xin shi li", "新势力" },
			{ "xin shou", "新手" }, { "xin shou ji", "新手机" }, { "xin shu", "新书" }, { "xin shui", "薪水" }, { "xin si", "心思" }, { "xin si jun", "新四军" },
			{ "xin suan", "心酸" }, { "xin suan", "辛酸" }, { "xin sui", "心碎" }, { "xin tai", "心态" }, { "xin teng", "心疼" }, { "xin tian", "心田" },
			{ "xin tiao", "信条" }, { "xin tiao", "心跳" }, { "xin tie", "新帖" }, { "xin tong", "心痛" }, { "xin tou", "心头" }, { "xin tu", "信徒" },
			{ "xin tuo", "信托" }, { "xin tuo gong si", "信托公司" }, { "xin wang", "新网" }, { "xin wei", "欣慰" }, { "xin wen", "新闻" }, { "xin wen ban", "新闻办" },
			{ "xin wen bao dao", "新闻报道" }, { "xin wen chu ban", "新闻出版" }, { "xin wen fa bu", "新闻发布" }, { "xin wen gao", "新闻稿" }, { "xin wen ji zhe", "新闻记者" },
			{ "xin wen jie", "新闻界" }, { "xin wen lian bo", "新闻联播" }, { "xin wen mei ti", "新闻媒体" }, { "xin wen pin dao", "新闻频道" }, { "xin wen wang", "新闻网" },
			{ "xin wen wang zhan", "新闻网站" }, { "xin wen zhong xin", "新闻中心" }, { "xin wen zi you", "新闻自由" }, { "xin xi", "信息" }, { "xin xi", "心系" },
			{ "xin xi", "欣喜" }, { "xin xi an quan", "信息安全" }, { "xin xi bu", "信息部" }, { "xin xi chan ye", "信息产业" }, { "xin xi chu li", "信息处理" },
			{ "xin xi chuan bo", "信息传播" }, { "xin xi chuan di", "信息传递" }, { "xin xi fa bu", "信息发布" }, { "xin xi fu wu", "信息服务" }, { "xin xi gang", "信息港" },
			{ "xin xi gong xiang", "信息共享" }, { "xin xi guan li", "信息管理" }, { "xin xi hua", "信息化" }, { "xin xi ji shu", "信息技术" }, { "xin xi jiao liu", "信息交流" },
			{ "xin xi ku", "信息库" }, { "xin xi lai yuan", "信息来源" }, { "xin xi lan", "新西兰" }, { "xin xi liang", "信息量" }, { "xin xi nei rong", "信息内容" },
			{ "xin xi pi lu", "信息披露" }, { "xin xi ping tai", "信息平台" }, { "xin xi ruo kuang", "欣喜若狂" }, { "xin xi shi dai", "信息时代" }, { "xin xi wang", "信息网" },
			{ "xin xi wang luo", "信息网络" }, { "xin xi xi tong", "信息系统" }, { "xin xi yuan", "信息员" }, { "xin xi zhong xin", "信息中心" },
			{ "xin xi zi yuan", "信息资源" }, { "xin xia", "心下" }, { "xin xian", "心弦" }, { "xin xian", "新鲜" }, { "xin xian gan", "新鲜感" },
			{ "xin xian shi", "新鲜事" }, { "xin xiang", "信箱" }, { "xin xiang", "心想" }, { "xin xiang", "新乡" }, { "xin xiang shi cheng", "心想事成" },
			{ "xin xiao qu", "新校区" }, { "xin xin", "信心" }, { "xin xin", "心心" }, { "xin xin", "新新" }, { "xin xin", "欣欣" }, { "xin xin ku ku", "辛辛苦苦" },
			{ "xin xin shi zu", "信心十足" }, { "xin xin xiang rong", "欣欣向荣" }, { "xin xing", "心性" }, { "xin xing", "新兴" }, { "xin xing", "新型" },
			{ "xin xing", "新星" }, { "xin xing chan ye", "新兴产业" }, { "xin xing shi chang", "新兴市场" }, { "xin xing shi xia", "新形势下" }, { "xin xiong", "心胸" },
			{ "xin xiu", "新秀" }, { "xin xu", "心绪" }, { "xin xu", "心虚" }, { "xin xue", "心血" }, { "xin xue guan", "心血管" }, { "xin xue lai chao", "心血来潮" },
			{ "xin yan", "心眼" }, { "xin yang", "信仰" }, { "xin yang", "信阳" }, { "xin yao", "新药" }, { "xin ye", "心也" }, { "xin yi", "心仪" }, { "xin yi", "心意" },
			{ "xin yi", "新意" }, { "xin yi", "新衣" }, { "xin yi jie", "新一届" }, { "xin yi lun", "新一轮" }, { "xin ying", "新颖" }, { "xin yong", "信用" },
			{ "xin yong dan bao", "信用担保" }, { "xin yong ka", "信用卡" }, { "xin yong she", "信用社" }, { "xin yong ti xi", "信用体系" }, { "xin yong zheng", "信用证" },
			{ "xin you", "心有" }, { "xin you ling xi", "心有灵犀" }, { "xin you xi", "新游戏" }, { "xin you yu ji", "心有余悸" }, { "xin yu", "信誉" }, { "xin yu", "心语" },
			{ "xin yu", "新宇" }, { "xin yu du", "信誉度" }, { "xin yuan", "心愿" }, { "xin yue", "新月" }, { "xin yue tuan", "信乐团" }, { "xin zang", "心脏" },
			{ "xin zang bing", "心脏病" }, { "xin zeng", "新增" }, { "xin zhan", "新站" }, { "xin zhao", "新招" }, { "xin zhao bu xuan", "心照不宣" },
			{ "xin zheng", "新政" }, { "xin zhi", "信纸" }, { "xin zhi", "心智" }, { "xin zhi", "新知" }, { "xin zhi du ming", "心知肚明" }, { "xin zhong", "信中" },
			{ "xin zhong", "心中" }, { "xin zhong guo", "新中国" }, { "xin zhong you shu", "心中有数" }, { "xin zhuang", "新装" }, { "xin zhuang", "莘庄" },
			{ "xin zi", "薪资" }, { "xin zui", "心醉" }, { "xin zuo", "新作" }, { "xing", "侀" }, { "xing", "倖" }, { "xing", "兴" }, { "xing", "刑" }, { "xing", "哘" },
			{ "xing", "坙" }, { "xing", "型" }, { "xing", "垶" }, { "xing", "姓" }, { "xing", "娙" }, { "xing", "婞" }, { "xing", "巠" }, { "xing", "幸" },
			{ "xing", "形" }, { "xing", "性" }, { "xing", "悻" }, { "xing", "惺" }, { "xing", "擤" }, { "xing", "星" }, { "xing", "杏" }, { "xing", "洐" },
			{ "xing", "涬" }, { "xing", "煋" }, { "xing", "狌" }, { "xing", "猩" }, { "xing", "瑆" }, { "xing", "省" }, { "xing", "硎" }, { "xing", "箵" },
			{ "xing", "腥" }, { "xing", "興" }, { "xing", "荇" }, { "xing", "荥" }, { "xing", "莕" }, { "xing", "蛵" }, { "xing", "行" }, { "xing", "裄" },
			{ "xing", "觲" }, { "xing", "邢" }, { "xing", "醒" }, { "xing", "鈃" }, { "xing", "鉶" }, { "xing", "鋞" }, { "xing", "陉" }, { "xing", "陘" },
			{ "xing", "餳" }, { "xing", "饧" }, { "xing", "騂" }, { "xing ai", "性爱" }, { "xing ba ke", "星巴克" }, { "xing ban", "兴办" }, { "xing ban lv", "性伴侣" },
			{ "xing bie", "性别" }, { "xing bing", "性病" }, { "xing bu tong", "行不通" }, { "xing bu xing", "行不行" }, { "xing cai", "型材" }, { "xing che", "行车" },
			{ "xing chen", "星辰" }, { "xing cheng", "形成" }, { "xing cheng", "行程" }, { "xing cheng ji zhi", "形成机制" }, { "xing chong chong", "兴冲冲" },
			{ "xing cun", "幸存" }, { "xing cun zhe", "幸存者" }, { "xing dong", "行动" }, { "xing dong ji hua", "行动计划" }, { "xing er shang xue", "形而上学" },
			{ "xing fa", "刑法" }, { "xing fa", "刑罚" }, { "xing fen", "兴奋" }, { "xing fen bu yi", "兴奋不已" }, { "xing fen ji", "兴奋剂" }, { "xing fu", "幸福" },
			{ "xing fu", "性福" }, { "xing fu gan", "幸福感" }, { "xing fu sheng huo", "幸福生活" }, { "xing gan", "性感" }, { "xing gao cai lie", "兴高采烈" },
			{ "xing gao chao", "性高潮" }, { "xing ge", "性格" }, { "xing gong", "行宫" }, { "xing gong neng", "性功能" }, { "xing guan jie yan", "性关节炎" },
			{ "xing guan xi", "性关系" }, { "xing guang", "星光" }, { "xing guang da dao", "星光大道" }, { "xing guo", "兴国" }, { "xing hai", "星海" },
			{ "xing hao", "型号" }, { "xing hao", "幸好" }, { "xing he", "星河" }, { "xing hua", "兴华" }, { "xing hua", "杏花" }, { "xing huan xiang", "性幻想" },
			{ "xing hui", "行贿" }, { "xing huo", "星火" }, { "xing ji", "星级" }, { "xing ji", "星际" }, { "xing ji bing", "性疾病" }, { "xing ji jin", "型基金" },
			{ "xing ji jiu dian", "星级酒店" }, { "xing ji zheng ba", "星际争霸" }, { "xing jia bi", "性价比" }, { "xing jia bi gao", "性价比高" }, { "xing jian", "兴建" },
			{ "xing jiao", "性交" }, { "xing jiao yu", "性教育" }, { "xing jin", "行进" }, { "xing jing", "刑警" }, { "xing jing", "行径" }, { "xing ju", "刑拘" },
			{ "xing jun", "行军" }, { "xing kong", "星空" }, { "xing kui", "幸亏" }, { "xing lai", "醒来" }, { "xing li", "行李" }, { "xing li", "行礼" },
			{ "xing li xiang", "行李箱" }, { "xing long", "兴隆" }, { "xing ma", "行吗" }, { "xing mian", "幸免" }, { "xing ming", "姓名" }, { "xing ming", "性命" },
			{ "xing mu", "醒目" }, { "xing nan", "型男" }, { "xing nang", "行囊" }, { "xing neng", "性能" }, { "xing neng ce shi", "性能测试" }, { "xing neng li", "性能力" },
			{ "xing neng yan jiu", "性能研究" }, { "xing neng zhi biao", "性能指标" }, { "xing pian", "行骗" }, { "xing qi", "兴起" }, { "xing qi", "星期" },
			{ "xing qi er", "星期二" }, { "xing qi guan", "性器官" }, { "xing qi liu", "星期六" }, { "xing qi ri", "星期日" }, { "xing qi san", "星期三" },
			{ "xing qi si", "星期四" }, { "xing qi tian", "星期天" }, { "xing qi wu", "星期五" }, { "xing qi ye", "型企业" }, { "xing qi yi", "星期一" },
			{ "xing qiang", "性强" }, { "xing qing", "性情" }, { "xing qing zhong ren", "性情中人" }, { "xing qiu", "星球" }, { "xing qu", "兴趣" }, { "xing qu", "性趣" },
			{ "xing qu ai hao", "兴趣爱好" }, { "xing qu xiang", "性取向" }, { "xing quan", "行权" }, { "xing ren", "杏仁" }, { "xing ren", "行人" }, { "xing rong", "形容" },
			{ "xing rong ci", "形容词" }, { "xing ru", "形如" }, { "xing sao rao", "性骚扰" }, { "xing shan", "行善" }, { "xing sheng", "兴盛" },
			{ "xing sheng huo", "性生活" }, { "xing shi", "刑事" }, { "xing shi", "型式" }, { "xing shi", "姓氏" }, { "xing shi", "形势" }, { "xing shi", "形式" },
			{ "xing shi", "行事" }, { "xing shi", "行使" }, { "xing shi", "行驶" }, { "xing shi an jian", "刑事案件" }, { "xing shi duo yang", "形式多样" },
			{ "xing shi fan zui", "刑事犯罪" }, { "xing shi ju liu", "刑事拘留" }, { "xing shi su song", "刑事诉讼" }, { "xing shi ze ren", "刑事责任" },
			{ "xing shi zheng", "行驶证" }, { "xing shi zhu yi", "形式主义" }, { "xing shi zou rou", "行尸走肉" }, { "xing shuai", "兴衰" }, { "xing si", "形似" },
			{ "xing tai", "形态" }, { "xing tai", "邢台" }, { "xing tang niao bing", "型糖尿病" }, { "xing ti", "形体" }, { "xing tong", "形同" },
			{ "xing tong xu she", "形同虚设" }, { "xing tou", "行头" }, { "xing wang", "兴旺" }, { "xing wang", "姓王" }, { "xing wei", "腥味" }, { "xing wei", "行为" },
			{ "xing wei gui fan", "行为规范" }, { "xing wei ren", "行为人" }, { "xing wei yi shu", "行为艺术" }, { "xing wei zhun ze", "行为准则" }, { "xing wen", "行文" },
			{ "xing wen ti", "性问题" }, { "xing wu", "醒悟" }, { "xing xi", "性息" }, { "xing xi", "星系" }, { "xing xian", "性腺" }, { "xing xiang", "形象" },
			{ "xing xiang da shi", "形象大使" }, { "xing xiao", "行销" }, { "xing xing", "星星" }, { "xing xing", "猩猩" }, { "xing xing", "行刑" }, { "xing xing", "行星" },
			{ "xing xing", "醒醒" }, { "xing xing se se", "形形色色" }, { "xing xing wei", "性行为" }, { "xing xiong", "行凶" }, { "xing xiu", "星宿" },
			{ "xing xu", "兴许" }, { "xing xun bi gong", "刑讯逼供" }, { "xing ye", "兴业" }, { "xing ye", "星爷" }, { "xing ye yin hang", "兴业银行" }, { "xing yi", "行医" },
			{ "xing yin dao yan", "性阴道炎" }, { "xing yu", "性欲" }, { "xing yue", "星月" }, { "xing yun", "幸运" }, { "xing yun", "星云" }, { "xing yun er", "幸运儿" },
			{ "xing yun liu shui", "行云流水" }, { "xing yun xing", "幸运星" }, { "xing zai le huo", "幸灾乐祸" }, { "xing zhang", "姓张" }, { "xing zhe", "行者" },
			{ "xing zhe", "醒着" }, { "xing zhen", "刑侦" }, { "xing zheng", "行政" }, { "xing zheng bu", "行政部" }, { "xing zheng bu men", "行政部门" },
			{ "xing zheng chu fa", "行政处罚" }, { "xing zheng chu fen", "行政处分" }, { "xing zheng cun", "行政村" }, { "xing zheng fa", "行政法" },
			{ "xing zheng fa gui", "行政法规" }, { "xing zheng fu yi", "行政复议" }, { "xing zheng guan li", "行政管理" }, { "xing zheng ji guan", "行政机关" },
			{ "xing zheng qu", "行政区" }, { "xing zheng qu hua", "行政区划" }, { "xing zheng qu yu", "行政区域" }, { "xing zheng quan li", "行政权力" },
			{ "xing zheng shen pi", "行政审批" }, { "xing zheng shi ye", "行政事业" }, { "xing zheng su song", "行政诉讼" }, { "xing zheng xing wei", "行政行为" },
			{ "xing zheng xu ke", "行政许可" }, { "xing zheng zhang guan", "行政长官" }, { "xing zheng zhi fa", "行政执法" }, { "xing zheng zhu guan", "行政主管" },
			{ "xing zhi", "兴致" }, { "xing zhi", "性质" }, { "xing zhi", "行之" }, { "xing zhi", "行至" }, { "xing zhi bo bo", "兴致勃勃" }, { "xing zhi shi", "性知识" },
			{ "xing zhi you xiao", "行之有效" }, { "xing zhuang", "形状" }, { "xing zhuang", "性状" }, { "xing zi", "性子" }, { "xing zong", "行踪" },
			{ "xing zou", "行走" }, { "xing zuo", "星座" }, { "xiong", "兄" }, { "xiong", "兇" }, { "xiong", "凶" }, { "xiong", "匈" }, { "xiong", "哅" },
			{ "xiong", "夐" }, { "xiong", "忷" }, { "xiong", "恟" }, { "xiong", "敻" }, { "xiong", "汹" }, { "xiong", "洶" }, { "xiong", "熊" }, { "xiong", "胸" },
			{ "xiong", "芎" }, { "xiong", "詗" }, { "xiong", "赨" }, { "xiong", "雄" }, { "xiong bu", "胸部" }, { "xiong can", "凶残" }, { "xiong di", "兄弟" },
			{ "xiong di jie mei", "兄弟姐妹" }, { "xiong di lian", "兄弟连" }, { "xiong e", "凶恶" }, { "xiong feng", "雄风" }, { "xiong han", "凶悍" },
			{ "xiong hen", "凶狠" }, { "xiong hou", "雄厚" }, { "xiong huai", "胸怀" }, { "xiong ji", "胸肌" }, { "xiong jin", "胸襟" }, { "xiong kou", "胸口" },
			{ "xiong lu", "雄鹿" }, { "xiong mao", "熊猫" }, { "xiong mei", "兄妹" }, { "xiong men", "胸闷" }, { "xiong meng", "凶猛" }, { "xiong nu", "匈奴" },
			{ "xiong pu", "胸脯" }, { "xiong qi", "凶器" }, { "xiong qi", "雄起" }, { "xiong qian", "胸前" }, { "xiong qiang", "胸腔" }, { "xiong shi", "熊市" },
			{ "xiong shi", "雄狮" }, { "xiong shou", "凶手" }, { "xiong tai", "兄台" }, { "xiong tang", "胸膛" }, { "xiong wei", "胸围" }, { "xiong wei", "雄伟" },
			{ "xiong xian", "凶险" }, { "xiong xin", "雄心" }, { "xiong xin bo bo", "雄心勃勃" }, { "xiong xing", "雄性" }, { "xiong xiong", "熊熊" },
			{ "xiong ya li", "匈牙利" }, { "xiong ying", "雄鹰" }, { "xiong yong", "汹涌" }, { "xiong you cheng zhu", "胸有成竹" }, { "xiong zhang", "兄长" },
			{ "xiong zhang", "熊掌" }, { "xiong zhao", "胸罩" }, { "xiong zhong", "胸中" }, { "xiong zhuang", "雄壮" }, { "xiu", "休" }, { "xiu", "修" }, { "xiu", "咻" },
			{ "xiu", "嗅" }, { "xiu", "嚊" }, { "xiu", "宿" }, { "xiu", "岫" }, { "xiu", "庥" }, { "xiu", "朽" }, { "xiu", "樇" }, { "xiu", "櫹" }, { "xiu", "溴" },
			{ "xiu", "滫" }, { "xiu", "烋" }, { "xiu", "珛" }, { "xiu", "琇" }, { "xiu", "秀" }, { "xiu", "糔" }, { "xiu", "綉" }, { "xiu", "繍" }, { "xiu", "繡" },
			{ "xiu", "绣" }, { "xiu", "羞" }, { "xiu", "脙" }, { "xiu", "脩" }, { "xiu", "臭" }, { "xiu", "臹" }, { "xiu", "苬" }, { "xiu", "茠" }, { "xiu", "螑" },
			{ "xiu", "袖" }, { "xiu", "貅" }, { "xiu", "銝" }, { "xiu", "鎀" }, { "xiu", "鏥" }, { "xiu", "鏽" }, { "xiu", "锈" }, { "xiu", "饈" }, { "xiu", "馐" },
			{ "xiu", "髹" }, { "xiu", "鮴" }, { "xiu", "鵂" }, { "xiu", "鸺" }, { "xiu bu", "修补" }, { "xiu cai", "秀才" }, { "xiu chang", "修长" },
			{ "xiu chang", "秀场" }, { "xiu che", "修车" }, { "xiu cheng", "修成" }, { "xiu chi", "羞耻" }, { "xiu ci", "修辞" }, { "xiu dao", "修道" },
			{ "xiu dao", "嗅到" }, { "xiu dao yuan", "修道院" }, { "xiu de", "修得" }, { "xiu dian nao", "修电脑" }, { "xiu ding", "修订" }, { "xiu dou", "秀逗" },
			{ "xiu fa", "秀发" }, { "xiu fu", "修复" }, { "xiu gai", "修改" }, { "xiu gai gao", "修改稿" }, { "xiu gai qi", "修改器" }, { "xiu hao", "修好" },
			{ "xiu hu", "修护" }, { "xiu hua", "绣花" }, { "xiu jia", "休假" }, { "xiu jian", "修剪" }, { "xiu jian", "修建" }, { "xiu jue", "嗅觉" }, { "xiu ke", "休克" },
			{ "xiu kou", "袖口" }, { "xiu kui", "羞愧" }, { "xiu li", "修理" }, { "xiu li", "秀丽" }, { "xiu li chang", "修理厂" }, { "xiu li fei", "修理费" },
			{ "xiu lian", "修炼" }, { "xiu lu", "修路" }, { "xiu luo", "修罗" }, { "xiu mei", "秀美" }, { "xiu mian", "休眠" }, { "xiu nv", "修女" }, { "xiu qi", "休憩" },
			{ "xiu qi", "秀气" }, { "xiu ru", "羞辱" }, { "xiu se", "羞涩" }, { "xiu shan", "修缮" }, { "xiu shen", "修身" }, { "xiu shen yang xing", "修身养性" },
			{ "xiu shi", "休市" }, { "xiu shi", "修饰" }, { "xiu shui", "秀水" }, { "xiu si dun", "休斯敦" }, { "xiu si dun", "休斯顿" }, { "xiu wei", "修为" },
			{ "xiu xi", "休息" }, { "xiu xi", "修习" }, { "xiu xi ri", "休息日" }, { "xiu xi shi", "休息室" }, { "xiu xi shi jian", "休息时间" },
			{ "xiu xi yi xia", "休息一下" }, { "xiu xian", "休闲" }, { "xiu xian du jia", "休闲度假" }, { "xiu xian yu le", "休闲娱乐" }, { "xiu xiang", "休想" },
			{ "xiu xing", "修行" }, { "xiu xiu", "秀秀" }, { "xiu xue", "休学" }, { "xiu yang", "休养" }, { "xiu yang", "修养" }, { "xiu zhen", "修真" },
			{ "xiu zhen", "袖珍" }, { "xiu zheng", "休整" }, { "xiu zheng", "修整" }, { "xiu zheng", "修正" }, { "xiu zheng an", "修正案" }, { "xiu zhu", "修筑" },
			{ "xiu zi", "袖子" }, { "xu", "侐" }, { "xu", "冔" }, { "xu", "勖" }, { "xu", "勗" }, { "xu", "卹" }, { "xu", "叙" }, { "xu", "吁" }, { "xu", "呴" },
			{ "xu", "喣" }, { "xu", "嘘" }, { "xu", "噓" }, { "xu", "圩" }, { "xu", "垿" }, { "xu", "墟" }, { "xu", "壻" }, { "xu", "姁" }, { "xu", "婿" },
			{ "xu", "嬃" }, { "xu", "幁" }, { "xu", "序" }, { "xu", "徐" }, { "xu", "恤" }, { "xu", "慉" }, { "xu", "戌" }, { "xu", "掝" }, { "xu", "揟" },
			{ "xu", "敍" }, { "xu", "敘" }, { "xu", "旭" }, { "xu", "旴" }, { "xu", "昫" }, { "xu", "晇" }, { "xu", "暊" }, { "xu", "栩" }, { "xu", "楈" },
			{ "xu", "欨" }, { "xu", "欻" }, { "xu", "歔" }, { "xu", "殈" }, { "xu", "沀" }, { "xu", "洫" }, { "xu", "浒" }, { "xu", "湑" }, { "xu", "溆" },
			{ "xu", "漵" }, { "xu", "烅" }, { "xu", "烼" }, { "xu", "煦" }, { "xu", "珝" }, { "xu", "畜" }, { "xu", "盱" }, { "xu", "瞁" }, { "xu", "砉" },
			{ "xu", "稰" }, { "xu", "窢" }, { "xu", "糈" }, { "xu", "絮" }, { "xu", "続" }, { "xu", "緒" }, { "xu", "緖" }, { "xu", "緰" }, { "xu", "縃" },
			{ "xu", "繻" }, { "xu", "續" }, { "xu", "绪" }, { "xu", "续" }, { "xu", "聟" }, { "xu", "胊" }, { "xu", "胥" }, { "xu", "蓄" }, { "xu", "蓲" },
			{ "xu", "蓿" }, { "xu", "蕦" }, { "xu", "藚" }, { "xu", "虚" }, { "xu", "虛" }, { "xu", "蚼" }, { "xu", "蝑" }, { "xu", "訏" }, { "xu", "許" },
			{ "xu", "訹" }, { "xu", "詡" }, { "xu", "諝" }, { "xu", "諿" }, { "xu", "謳" }, { "xu", "许" }, { "xu", "诩" }, { "xu", "鄦" }, { "xu", "酗" },
			{ "xu", "醑" }, { "xu", "銊" }, { "xu", "鑐" }, { "xu", "需" }, { "xu", "須" }, { "xu", "頊" }, { "xu", "须" }, { "xu", "顼" }, { "xu", "驉" },
			{ "xu", "鬚" }, { "xu", "魆" }, { "xu", "魖" }, { "xu bao", "虚报" }, { "xu bu xu yao", "需不需要" }, { "xu chan pin", "畜产品" }, { "xu chang", "许昌" },
			{ "xu chuan", "续传" }, { "xu dian chi", "蓄电池" }, { "xu dong", "旭东" }, { "xu du", "虚度" }, { "xu duo", "许多" }, { "xu duo ren", "许多人" },
			{ "xu fei", "续费" }, { "xu fei", "许飞" }, { "xu gao", "虚高" }, { "xu gong", "徐工" }, { "xu gou", "虚构" }, { "xu hang", "续航" }, { "xu hao", "序号" },
			{ "xu hua", "虚化" }, { "xu huan", "虚幻" }, { "xu hui", "徐汇" }, { "xu hui qu", "徐汇区" }, { "xu ji", "续集" }, { "xu jia", "虚假" },
			{ "xu jia guang gao", "虚假广告" }, { "xu jia hui", "徐家汇" }, { "xu jing", "须经" }, { "xu jing lei", "徐静蕾" }, { "xu jiu", "许久" }, { "xu jiu", "酗酒" },
			{ "xu ke", "徐克" }, { "xu ke", "许可" }, { "xu ke zheng", "许可证" }, { "xu kong", "虚空" }, { "xu li ya", "叙利亚" }, { "xu lie", "序列" },
			{ "xu lie hao", "序列号" }, { "xu lie hua", "序列化" }, { "xu ming", "徐明" }, { "xu ming", "虚名" }, { "xu mu", "序幕" }, { "xu mu", "畜牧" },
			{ "xu mu shou yi", "畜牧兽医" }, { "xu mu ye", "畜牧业" }, { "xu ni", "虚拟" }, { "xu ni guang qu", "虚拟光驱" }, { "xu ni hua", "虚拟化" },
			{ "xu ni huo bi", "虚拟货币" }, { "xu ni ji", "虚拟机" }, { "xu ni nei cun", "虚拟内存" }, { "xu ni shi jie", "虚拟世界" }, { "xu ni zhu ji", "虚拟主机" },
			{ "xu nuo", "许诺" }, { "xu qian", "续签" }, { "xu qiu", "需求" }, { "xu qiu fen xi", "需求分析" }, { "xu qiu liang", "需求量" }, { "xu qu", "序曲" },
			{ "xu ri", "旭日" }, { "xu rong", "虚荣" }, { "xu rong xin", "虚荣心" }, { "xu ru yun", "许茹芸" }, { "xu ruo", "虚弱" }, { "xu ruo xuan", "徐若瑄" },
			{ "xu sheng", "嘘声" }, { "xu shi", "叙事" }, { "xu shi", "蓄势" }, { "xu shi", "虚实" }, { "xu shi dai fa", "蓄势待发" }, { "xu shu", "叙述" },
			{ "xu shui", "蓄水" }, { "xu tuo", "虚脱" }, { "xu wang", "虚妄" }, { "xu wei", "虚伪" }, { "xu wei", "许巍" }, { "xu wei lun", "许玮伦" }, { "xu wu", "虚无" },
			{ "xu xia", "许下" }, { "xu xian", "虚线" }, { "xu xian", "许仙" }, { "xu xie", "续写" }, { "xu xin", "虚心" }, { "xu xu", "徐徐" },
			{ "xu xu duo duo", "许许多多" }, { "xu xu ru sheng", "栩栩如生" }, { "xu yan", "序言" }, { "xu yao", "需要" }, { "xu yao", "须要" },
			{ "xu yao bang zhu", "需要帮助" }, { "xu yao shen me", "需要什么" }, { "xu yao shi jian", "需要时间" }, { "xu yao yong", "需要用" }, { "xu yao zhu yi", "需要注意" },
			{ "xu yao zuo", "需要做" }, { "xu yi", "蓄意" }, { "xu yong", "需用" }, { "xu yuan", "许愿" }, { "xu yue", "续约" }, { "xu zai", "须在" }, { "xu zhi", "须知" },
			{ "xu zhi mo", "徐志摩" }, { "xu zhou", "徐州" }, { "xu zhou shi", "徐州市" }, { "xu zong", "徐总" }, { "xuan", "儇" }, { "xuan", "券" }, { "xuan", "县" },
			{ "xuan", "咺" }, { "xuan", "喧" }, { "xuan", "妶" }, { "xuan", "媗" }, { "xuan", "嫙" }, { "xuan", "宣" }, { "xuan", "悬" }, { "xuan", "愃" },
			{ "xuan", "愋" }, { "xuan", "懁" }, { "xuan", "懸" }, { "xuan", "揈" }, { "xuan", "揎" }, { "xuan", "旋" }, { "xuan", "昍" }, { "xuan", "昡" },
			{ "xuan", "晅" }, { "xuan", "暄" }, { "xuan", "楦" }, { "xuan", "泫" }, { "xuan", "渲" }, { "xuan", "漩" }, { "xuan", "炫" }, { "xuan", "烜" },
			{ "xuan", "煊" }, { "xuan", "煖" }, { "xuan", "狟" }, { "xuan", "獧" }, { "xuan", "玄" }, { "xuan", "玹" }, { "xuan", "琁" }, { "xuan", "琄" },
			{ "xuan", "瑄" }, { "xuan", "璇" }, { "xuan", "璿" }, { "xuan", "痃" }, { "xuan", "癣" }, { "xuan", "癬" }, { "xuan", "眩" }, { "xuan", "矎" },
			{ "xuan", "碹" }, { "xuan", "禤" }, { "xuan", "絢" }, { "xuan", "縼" }, { "xuan", "绚" }, { "xuan", "翾" }, { "xuan", "萱" }, { "xuan", "萲" },
			{ "xuan", "蓒" }, { "xuan", "蔙" }, { "xuan", "蜁" }, { "xuan", "蝖" }, { "xuan", "蠉" }, { "xuan", "衒" }, { "xuan", "袨" }, { "xuan", "諠" },
			{ "xuan", "諼" }, { "xuan", "讂" }, { "xuan", "谖" }, { "xuan", "贙" }, { "xuan", "軒" }, { "xuan", "轋" }, { "xuan", "轩" }, { "xuan", "选" },
			{ "xuan", "選" }, { "xuan", "鉉" }, { "xuan", "鋗" }, { "xuan", "鍹" }, { "xuan", "鏇" }, { "xuan", "鐶" }, { "xuan", "铉" }, { "xuan", "镟" },
			{ "xuan", "鞙" }, { "xuan", "駽" }, { "xuan ba", "选拔" }, { "xuan ba sai", "选拔赛" }, { "xuan bu", "宣布" }, { "xuan cai", "选材" }, { "xuan cheng", "宣称" },
			{ "xuan chu", "选出" }, { "xuan chuan", "宣传" }, { "xuan chuan bao dao", "宣传报道" }, { "xuan chuan bu", "宣传部" }, { "xuan chuan bu zhang", "宣传部长" },
			{ "xuan chuan ce", "宣传册" }, { "xuan chuan dan", "宣传单" }, { "xuan chuan gong zuo", "宣传工作" }, { "xuan chuan huo dong", "宣传活动" },
			{ "xuan chuan jiao yu", "宣传教育" }, { "xuan chuan pian", "宣传片" }, { "xuan chuan tui guang", "宣传推广" }, { "xuan chuan zi liao", "宣传资料" },
			{ "xuan de", "玄德" }, { "xuan ding", "选定" }, { "xuan du", "宣读" }, { "xuan fang", "选房" }, { "xuan feng", "旋风" }, { "xuan fu", "悬浮" },
			{ "xuan gao", "宣告" } };
};
