package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN28 {
	public static String[][] pl = { { "lao", "佬" }, { "lao", "僗" }, { "lao", "劳" }, { "lao", "労" }, { "lao", "勞" }, { "lao", "咾" }, { "lao", "唠" },
			{ "lao", "嘮" }, { "lao", "姥" }, { "lao", "嫪" }, { "lao", "崂" }, { "lao", "嶗" }, { "lao", "恅" }, { "lao", "捞" }, { "lao", "撈" }, { "lao", "栳" },
			{ "lao", "橑" }, { "lao", "橯" }, { "lao", "浶" }, { "lao", "涝" }, { "lao", "潦" }, { "lao", "澇" }, { "lao", "烙" }, { "lao", "牢" }, { "lao", "狫" },
			{ "lao", "痨" }, { "lao", "癆" }, { "lao", "簩" }, { "lao", "络" }, { "lao", "老" }, { "lao", "耢" }, { "lao", "荖" }, { "lao", "落" }, { "lao", "蛯" },
			{ "lao", "軂" }, { "lao", "酪" }, { "lao", "醪" }, { "lao", "銠" }, { "lao", "鐒" }, { "lao", "铑" }, { "lao", "铹" }, { "lao", "顟" }, { "lao", "鮱" },
			{ "lao ba", "老爸" }, { "lao ba lao ma", "老爸老妈" }, { "lao bai", "老白" }, { "lao bai xing", "老百姓" }, { "lao ban", "老伴" }, { "lao ban", "老板" },
			{ "lao ban", "老版" }, { "lao ban ben", "老版本" }, { "lao ban niang", "老板娘" }, { "lao ban tian", "老半天" }, { "lao bao", "劳保" }, { "lao bao", "老鸨" },
			{ "lao bei jing", "老北京" }, { "lao bing", "老兵" }, { "lao bo", "老伯" }, { "lao cai", "老蔡" }, { "lao cao", "老曹" }, { "lao chen", "老陈" },
			{ "lao cheng", "老城" }, { "lao cheng qu", "老城区" }, { "lao chu", "捞出" }, { "lao da", "老大" }, { "lao da ge", "老大哥" }, { "lao da ye", "老大爷" },
			{ "lao dang yuan", "老党员" }, { "lao dao", "唠叨" }, { "lao dao", "老道" }, { "lao di", "老弟" }, { "lao di fang", "老地方" }, { "lao dian", "老店" },
			{ "lao die", "老爹" }, { "lao dong", "劳动" }, { "lao dong bao chou", "劳动报酬" }, { "lao dong bao zhang", "劳动保障" }, { "lao dong bu men", "劳动部门" },
			{ "lao dong fa", "劳动法" }, { "lao dong guan xi", "劳动关系" }, { "lao dong he tong", "劳动合同" }, { "lao dong jie", "劳动节" }, { "lao dong jiu ye", "劳动就业" },
			{ "lao dong ju", "劳动局" }, { "lao dong li", "劳动力" }, { "lao dong mo fan", "劳动模范" }, { "lao dong ren min", "劳动人民" }, { "lao dong zhe", "劳动者" },
			{ "lao dong zheng yi", "劳动争议" }, { "lao dou", "老豆" }, { "lao du", "老杜" }, { "lao er", "劳尔" }, { "lao er", "老二" }, { "lao fang", "牢房" },
			{ "lao fang zi", "老房子" }, { "lao fu", "老夫" }, { "lao fu ren", "老妇人" }, { "lao gan bu", "老干部" }, { "lao gao", "老高" }, { "lao ge", "老哥" },
			{ "lao ge", "老歌" }, { "lao gong", "劳工" }, { "lao gong", "老公" }, { "lao gu", "牢固" }, { "lao gu min", "老股民" }, { "lao gu shu li", "牢固树立" },
			{ "lao gui", "老鬼" }, { "lao guo", "老郭" }, { "lao han", "老汉" }, { "lao han", "落汗" }, { "lao he", "老何" }, { "lao he shang", "老和尚" },
			{ "lao hei", "老黑" }, { "lao hu", "老胡" }, { "lao hu", "老虎" }, { "lao hu ji", "老虎机" }, { "lao hua", "老化" }, { "lao hua", "老话" },
			{ "lao huang", "老黄" }, { "lao huo", "老火" }, { "lao ji", "牢记" }, { "lao jia", "老家" }, { "lao jiang", "老将" }, { "lao jiang", "老蒋" },
			{ "lao jiao", "劳教" }, { "lao jiao shou", "老教授" }, { "lao jie", "老姐" }, { "lao jie", "老街" }, { "lao jin", "老金" }, { "lao jiu", "老旧" },
			{ "lao jiu", "老酒" }, { "lao kao", "牢靠" }, { "lao ke hu", "老客户" }, { "lao ku", "劳苦" }, { "lao kuan", "老款" }, { "lao la", "劳拉" },
			{ "lao lang", "老狼" }, { "lao lao", "姥姥" }, { "lao lao", "牢牢" }, { "lao lao shi shi", "老老实实" }, { "lao lei", "劳累" }, { "lao li", "劳力" },
			{ "lao li", "老李" }, { "lao lian", "老练" }, { "lao ling", "老龄" }, { "lao ling hua", "老龄化" }, { "lao liu", "老六" }, { "lao liu", "老刘" },
			{ "lao lu", "老路" }, { "lao lun si", "劳伦斯" }, { "lao luo", "老罗" }, { "lao ma", "老妈" }, { "lao ma", "老马" }, { "lao mao", "老毛" }, { "lao mao", "老猫" },
			{ "lao mei", "老妹" }, { "lao mei", "老美" }, { "lao mo", "劳模" }, { "lao mu", "老母" }, { "lao na", "老衲" }, { "lao nai nai", "老奶奶" },
			{ "lao nan ren", "老男人" }, { "lao nian", "老年" }, { "lao nian", "老蔫" }, { "lao nian ren", "老年人" }, { "lao niang", "老娘" }, { "lao niao", "老鸟" },
			{ "lao niu", "老牛" }, { "lao nong", "老农" }, { "lao nv ren", "老女人" }, { "lao pai", "老牌" }, { "lao pan", "老潘" }, { "lao peng you", "老朋友" },
			{ "lao po", "老婆" }, { "lao po po", "老婆婆" }, { "lao qi", "捞起" }, { "lao qi", "老七" }, { "lao qian", "捞钱" }, { "lao qian bei", "老前辈" },
			{ "lao qu", "老区" }, { "lao qu", "老去" }, { "lao ren", "老人" }, { "lao ren jia", "老人家" }, { "lao san", "老三" }, { "lao sao", "牢骚" },
			{ "lao shan", "崂山" }, { "lao shao", "老少" }, { "lao she", "老舍" }, { "lao shi", "老实" }, { "lao shi", "老师" }, { "lao shi", "老式" },
			{ "lao shi", "老是" }, { "lao shi hua", "老实话" }, { "lao shi jiao", "老师教" }, { "lao shi ren", "老实人" }, { "lao shou", "老手" }, { "lao shu", "老树" },
			{ "lao shu", "老鼠" }, { "lao shuo", "老说" }, { "lao si", "老四" }, { "lao si", "老死" }, { "lao si lai si", "劳斯莱斯" }, { "lao song", "老宋" },
			{ "lao sun", "老孙" }, { "lao tai", "老太" }, { "lao tai po", "老太婆" }, { "lao tai tai", "老太太" }, { "lao tao", "老套" }, { "lao tian", "老天" },
			{ "lao tian ye", "老天爷" }, { "lao tong xue", "老同学" }, { "lao tong zhi", "老同志" }, { "lao tou", "老头" }, { "lao tou er", "老头儿" },
			{ "lao tou zi", "老头子" }, { "lao tu", "老土" }, { "lao wai", "老外" }, { "lao wang", "老王" }, { "lao weng", "老翁" }, { "lao wo", "老挝" },
			{ "lao wu", "劳务" }, { "lao wu", "老五" }, { "lao wu", "老吴" }, { "lao wu", "老屋" }, { "lao wu fei", "劳务费" }, { "lao wu pai qian", "劳务派遣" },
			{ "lao wu shu chu", "劳务输出" }, { "lao xian sheng", "老先生" }, { "lao xiang", "老乡" }, { "lao xiang", "老想" }, { "lao xie", "老谢" },
			{ "lao xiong", "老兄" }, { "lao xu", "老徐" }, { "lao yang", "老杨" }, { "lao yang zi", "老样子" }, { "lao yao", "老妖" }, { "lao ye", "姥爷" },
			{ "lao ye", "老爷" }, { "lao ye ye", "老爷爷" }, { "lao ye zi", "老爷子" }, { "lao yi bei", "老一辈" }, { "lao yi jie he", "劳逸结合" }, { "lao yin", "烙印" },
			{ "lao ying", "老鹰" }, { "lao you", "老友" }, { "lao you ji", "老友记" }, { "lao yuan", "老远" }, { "lao zao", "老早" }, { "lao zhang", "老张" },
			{ "lao zhao", "老赵" }, { "lao zhao pian", "老照片" }, { "lao zhe", "老者" }, { "lao zhou", "老周" }, { "lao zhu", "老朱" }, { "lao zhu", "老猪" },
			{ "lao zhuang", "老庄" }, { "lao zi", "劳资" }, { "lao zi", "老子" }, { "lao zi hao", "老字号" }, { "lao zong", "老总" }, { "lao zu zong", "老祖宗" },
			{ "lao zuo", "劳作" }, { "le", "乐" }, { "le", "了" }, { "le", "仂" }, { "le", "勒" }, { "le", "叻" }, { "le", "楽" }, { "le", "樂" }, { "le", "氻" },
			{ "le", "泐" }, { "le", "牞" }, { "le", "砳" }, { "le", "竻" }, { "le", "肋" }, { "le", "阞" }, { "le", "鰳" }, { "le", "鳓" }, { "le ci bu pi", "乐此不疲" },
			{ "le de", "乐得" }, { "le feng", "乐风" }, { "le gou", "乐购" }, { "le guan", "乐观" }, { "le he he", "乐呵呵" }, { "le le", "乐乐" }, { "le ling", "勒令" },
			{ "le ma", "了吗" }, { "le qu", "乐趣" }, { "le shan", "乐山" }, { "le shi", "乐事" }, { "le suo", "勒索" }, { "le tian", "乐天" }, { "le wang", "乐网" },
			{ "le xin de", "了新的" }, { "le yi", "乐意" }, { "le yi", "了一" }, { "le yi chang", "了一场" }, { "le yu", "乐于" }, { "le yuan", "乐园" },
			{ "le zai qi zhong", "乐在其中" }, { "le zi", "乐子" }, { "lei", "儡" }, { "lei", "勒" }, { "lei", "嘞" }, { "lei", "垒" }, { "lei", "塁" }, { "lei", "壘" },
			{ "lei", "壨" }, { "lei", "嫘" }, { "lei", "擂" }, { "lei", "樏" }, { "lei", "檑" }, { "lei", "櫐" }, { "lei", "泪" }, { "lei", "涙" }, { "lei", "淚" },
			{ "lei", "灅" }, { "lei", "瓃" }, { "lei", "畾" }, { "lei", "瘣" }, { "lei", "癗" }, { "lei", "磊" }, { "lei", "磥" }, { "lei", "礌" }, { "lei", "礧" },
			{ "lei", "礨" }, { "lei", "禷" }, { "lei", "类" }, { "lei", "累" }, { "lei", "絫" }, { "lei", "縲" }, { "lei", "纇" }, { "lei", "纍" }, { "lei", "缧" },
			{ "lei", "罍" }, { "lei", "羸" }, { "lei", "耒" }, { "lei", "肋" }, { "lei", "蔂" }, { "lei", "蕾" }, { "lei", "藟" }, { "lei", "蘱" }, { "lei", "蘲" },
			{ "lei", "虆" }, { "lei", "蠝" }, { "lei", "誄" }, { "lei", "讄" }, { "lei", "诔" }, { "lei", "轠" }, { "lei", "郲" }, { "lei", "酹" }, { "lei", "銇" },
			{ "lei", "鐳" }, { "lei", "鑸" }, { "lei", "镭" }, { "lei", "雷" }, { "lei", "頛" }, { "lei", "類" }, { "lei", "鸓" }, { "lei bi", "类比" },
			{ "lei bie", "类别" }, { "lei da", "雷达" }, { "lei de", "累得" }, { "lei de", "雷德" }, { "lei dian", "雷电" }, { "lei feng", "雷锋" },
			{ "lei feng shi", "类风湿" }, { "lei gu", "肋骨" }, { "lei guang", "泪光" }, { "lei hen", "泪痕" }, { "lei hua", "泪花" }, { "lei huai", "累坏" },
			{ "lei ji", "累积" }, { "lei ji", "累计" }, { "lei ji", "雷击" }, { "lei jia", "累加" }, { "lei ke sa si", "雷克萨斯" }, { "lei ku", "类库" },
			{ "lei lei", "累累" }, { "lei lei", "蕾蕾" }, { "lei liu", "泪流" }, { "lei liu man mian", "泪流满面" }, { "lei man", "雷曼" }, { "lei man xiong di", "雷曼兄弟" },
			{ "lei ming", "雷鸣" }, { "lei mu", "类目" }, { "lei nuo", "雷诺" }, { "lei ren", "累人" }, { "lei shen", "雷神" }, { "lei sheng", "雷声" },
			{ "lei shui", "泪水" }, { "lei si", "类似" }, { "lei si", "累死" }, { "lei si", "蕾丝" }, { "lei si", "雷斯" }, { "lei tai", "擂台" }, { "lei ting", "雷霆" },
			{ "lei tong", "雷同" }, { "lei tui", "类推" }, { "lei xing", "类型" }, { "lei yan", "泪眼" }, { "lei yu", "雷雨" }, { "lei zhen yu", "雷阵雨" },
			{ "lei zhong", "类中" }, { "lei zhu", "泪珠" }, { "lei zhui", "累赘" }, { "leng", "冷" }, { "leng", "堎" }, { "leng", "塄" }, { "leng", "崚" },
			{ "leng", "愣" }, { "leng", "棱" }, { "leng", "楞" }, { "leng", "睖" }, { "leng", "稜" }, { "leng", "薐" }, { "leng", "踜" }, { "leng bing bing", "冷冰冰" },
			{ "leng cang", "冷藏" }, { "leng chang", "冷场" }, { "leng chao re feng", "冷嘲热讽" }, { "leng dan", "冷淡" }, { "leng de", "冷得" }, { "leng dong", "冷冻" },
			{ "leng feng", "冷风" }, { "leng han", "冷汗" }, { "leng jiao", "棱角" }, { "leng jing", "冷静" }, { "leng jun", "冷峻" }, { "leng kong qi", "冷空气" },
			{ "leng ku", "冷库" }, { "leng ku", "冷酷" }, { "leng le", "冷了" }, { "leng le", "愣了" }, { "leng leng", "冷冷" }, { "leng leng", "愣愣" },
			{ "leng leng de", "冷冷的" }, { "leng luo", "冷落" }, { "leng men", "冷门" }, { "leng mian", "冷面" }, { "leng mo", "冷漠" }, { "leng nuan", "冷暖" },
			{ "leng qi", "冷气" }, { "leng qing", "冷清" }, { "leng que", "冷却" }, { "leng re", "冷热" }, { "leng shi", "愣是" }, { "leng shui", "冷水" },
			{ "leng xiao", "冷笑" }, { "leng xiao hua", "冷笑话" }, { "leng xue", "冷血" }, { "leng yan", "冷眼" }, { "leng yan", "冷艳" }, { "leng yin", "冷饮" },
			{ "leng yue", "冷月" }, { "leng zha", "冷轧" }, { "leng zhan", "冷战" }, { "leng zhu", "愣住" }, { "li", "丽" }, { "li", "例" }, { "li", "俐" },
			{ "li", "俚" }, { "li", "俪" }, { "li", "傈" }, { "li", "儮" }, { "li", "儷" }, { "li", "刂" }, { "li", "刕" }, { "li", "利" }, { "li", "剺" },
			{ "li", "劙" }, { "li", "力" }, { "li", "励" }, { "li", "勵" }, { "li", "历" }, { "li", "厉" }, { "li", "厘" }, { "li", "厤" }, { "li", "厲" },
			{ "li", "吏" }, { "li", "呖" }, { "li", "哩" }, { "li", "唎" }, { "li", "唳" }, { "li", "喱" }, { "li", "嚦" }, { "li", "坜" }, { "li", "塛" },
			{ "li", "壢" }, { "li", "娌" }, { "li", "娳" }, { "li", "嫠" }, { "li", "孋" }, { "li", "孷" }, { "li", "屴" }, { "li", "岦" }, { "li", "峛" },
			{ "li", "廲" }, { "li", "悧" }, { "li", "悷" }, { "li", "慄" }, { "li", "戾" }, { "li", "扐" }, { "li", "搮" }, { "li", "暦" }, { "li", "曆" },
			{ "li", "曞" }, { "li", "朸" }, { "li", "李" }, { "li", "枥" }, { "li", "栃" }, { "li", "栎" }, { "li", "栗" }, { "li", "栵" }, { "li", "梨" },
			{ "li", "樆" }, { "li", "檪" }, { "li", "櫪" }, { "li", "欐" }, { "li", "欚" }, { "li", "歴" }, { "li", "歷" }, { "li", "沥" }, { "li", "浬" },
			{ "li", "涖" }, { "li", "溧" }, { "li", "漓" }, { "li", "漦" }, { "li", "澧" }, { "li", "濿" }, { "li", "瀝" }, { "li", "灕" }, { "li", "犁" },
			{ "li", "犂" }, { "li", "犡" }, { "li", "狸" }, { "li", "猁" }, { "li", "理" }, { "li", "琍" }, { "li", "瑮" }, { "li", "璃" }, { "li", "瓅" },
			{ "li", "瓥" }, { "li", "疠" }, { "li", "疬" }, { "li", "痢" }, { "li", "癘" }, { "li", "癧" }, { "li", "盭" }, { "li", "砅" }, { "li", "砺" },
			{ "li", "砾" }, { "li", "磿" }, { "li", "礪" }, { "li", "礰" }, { "li", "礼" }, { "li", "禮" }, { "li", "禲" }, { "li", "离" }, { "li", "秝" },
			{ "li", "立" }, { "li", "竰" }, { "li", "笠" }, { "li", "筣" }, { "li", "篥" }, { "li", "篱" }, { "li", "籬" }, { "li", "粒" }, { "li", "粝" },
			{ "li", "粴" }, { "li", "糎" }, { "li", "糲" }, { "li", "縭" }, { "li", "缡" }, { "li", "罹" }, { "li", "苈" }, { "li", "苙" }, { "li", "茘" },
			{ "li", "荔" }, { "li", "莅" }, { "li", "莉" }, { "li", "菞" }, { "li", "蒚" }, { "li", "蒞" }, { "li", "蓠" }, { "li", "蔾" }, { "li", "藜" },
			{ "li", "藶" }, { "li", "蘺" }, { "li", "蚸" }, { "li", "蛎" }, { "li", "蜊" }, { "li", "蜧" }, { "li", "蠇" }, { "li", "蠡" }, { "li", "蠣" },
			{ "li", "蠫" }, { "li", "裏" }, { "li", "裡" }, { "li", "褵" }, { "li", "詈" }, { "li", "謧" }, { "li", "讈" }, { "li", "豊" }, { "li", "赲" },
			{ "li", "跞" }, { "li", "轢" }, { "li", "轣" }, { "li", "轹" }, { "li", "逦" }, { "li", "邐" }, { "li", "郦" }, { "li", "醨" }, { "li", "醴" },
			{ "li", "里" }, { "li", "釐" }, { "li", "鋰" }, { "li", "鑗" }, { "li", "锂" }, { "li", "隶" }, { "li", "隷" }, { "li", "隸" }, { "li", "離" },
			{ "li", "雳" }, { "li", "靂" }, { "li", "靋" }, { "li", "驪" }, { "li", "骊" }, { "li", "鬁" }, { "li", "鬲" }, { "li", "鯉" }, { "li", "鯏" },
			{ "li", "鯬" }, { "li", "鱧" }, { "li", "鱱" }, { "li", "鱺" }, { "li", "鲡" }, { "li", "鲤" }, { "li", "鳢" }, { "li", "鴗" }, { "li", "鵹" },
			{ "li", "鷅" }, { "li", "鸝" }, { "li", "鹂" }, { "li", "麗" }, { "li", "麜" }, { "li", "黎" }, { "li", "黧" }, { "li an", "李安" }, { "li an", "离岸" },
			{ "li an", "立案" }, { "li ang", "里昂" }, { "li ao", "李敖" }, { "li ao", "里奥" }, { "li ba", "篱笆" }, { "li ba nen", "黎巴嫩" }, { "li bai", "李白" },
			{ "li bai", "礼拜" }, { "li bai liu", "礼拜六" }, { "li bai tian", "礼拜天" }, { "li bai wu", "礼拜五" }, { "li bai yi", "礼拜一" }, { "li bao", "礼包" },
			{ "li bi", "利弊" }, { "li bi ya", "利比亚" }, { "li bian", "里边" }, { "li bie", "离别" }, { "li bin", "李斌" }, { "li bing bing", "李冰冰" },
			{ "li bu cong xin", "力不从心" }, { "li bu kai", "离不开" }, { "li cai", "理睬" }, { "li cai", "理财" }, { "li cai chan pin", "理财产品" }, { "li cha", "利差" },
			{ "li cha de", "理查德" }, { "li chang", "离场" }, { "li chang", "立场" }, { "li chang chun", "李长春" }, { "li chang hao", "李昌镐" }, { "li cheng", "历程" },
			{ "li cheng", "李成" }, { "li cheng", "里程" }, { "li cheng bei", "里程碑" }, { "li ci", "历次" }, { "li dai", "历代" }, { "li dao", "力道" },
			{ "li de", "李德" }, { "li de", "离得" }, { "li deng hui", "李登辉" }, { "li di", "离地" }, { "li dian chi", "锂电池" }, { "li dong", "李东" },
			{ "li dou", "里都" }, { "li du", "力度" }, { "li du", "粒度" }, { "li dui", "离队" }, { "li duo", "利多" }, { "li fa", "理发" }, { "li fa", "立法" },
			{ "li fa dian", "理发店" }, { "li fa shi", "理发师" }, { "li fan", "力帆" }, { "li fang", "立方" }, { "li fang", "里放" }, { "li fang mi", "立方米" },
			{ "li fu", "礼服" }, { "li gan jian ying", "立竿见影" }, { "li gang", "李刚" }, { "li ge", "离歌" }, { "li gen", "里根" }, { "li gong", "理工" },
			{ "li gong", "立功" }, { "li gong da xue", "理工大学" }, { "li gong ke", "理工科" }, { "li gong xue yuan", "理工学院" }, { "li guang", "李广" },
			{ "li guang", "理光" }, { "li guo", "李国" }, { "li guo", "立国" }, { "li hai", "利害" }, { "li hai", "厉害" }, { "li hai", "李海" }, { "li hai", "里还" },
			{ "li hai guan xi", "利害关系" }, { "li hao", "利好" }, { "li he", "礼盒" }, { "li he", "离合" }, { "li he qi", "离合器" }, { "li hong", "力宏" },
			{ "li hong", "李红" }, { "li hong zhang", "李鸿章" }, { "li hua", "丽华" }, { "li hua", "李华" }, { "li hua", "梨花" }, { "li hua", "理化" },
			{ "li huan", "罹患" }, { "li hui", "例会" }, { "li hui", "李辉" }, { "li hui", "理会" }, { "li hun", "离婚" }, { "li hun le", "离婚了" }, { "li ji", "立即" },
			{ "li jia", "例假" }, { "li jia", "李佳" }, { "li jia", "李家" }, { "li jia", "离家" }, { "li jia cheng", "李嘉诚" }, { "li jia chu zou", "离家出走" },
			{ "li jia xin", "李嘉欣" }, { "li jian", "利剑" }, { "li jian", "李健" }, { "li jian", "李建" }, { "li jiang", "丽江" }, { "li jiang", "漓江" },
			{ "li jiao", "立交" }, { "li jiao qiao", "立交桥" }, { "li jie", "历届" }, { "li jie", "李杰" }, { "li jie", "理解" }, { "li jie", "礼节" }, { "li jin", "历尽" },
			{ "li jin", "礼金" }, { "li jin yu", "李金羽" }, { "li jing", "历经" }, { "li jing", "李静" }, { "li jiu", "里就" }, { "li juan", "丽娟" }, { "li jun", "李俊" },
			{ "li jun", "李军" }, { "li jun ji", "李俊基" }, { "li kai", "离开" }, { "li kai fu", "李开复" }, { "li kai jia", "离开家" }, { "li kan", "里看" },
			{ "li ke", "力克" }, { "li ke", "理科" }, { "li ke", "立刻" }, { "li ke", "里克" }, { "li ke er mei", "里克尔梅" }, { "li ke qin", "李克勤" },
			{ "li kong", "利空" }, { "li kui", "李逵" }, { "li lai", "历来" }, { "li lao shi", "李老师" }, { "li le", "离了" }, { "li lei", "李磊" }, { "li li", "丽丽" },
			{ "li li", "李丽" }, { "li li", "莉莉" }, { "li li zai mu", "历历在目" }, { "li lian", "历练" }, { "li lian jie", "李连杰" }, { "li liang", "力量" },
			{ "li liao", "理疗" }, { "li lin", "莅临" }, { "li lu", "里路" }, { "li lun", "理论" }, { "li lun chuang xin", "理论创新" }, { "li lun ji chu", "理论基础" },
			{ "li lun jia", "理论家" }, { "li lun ti xi", "理论体系" }, { "li lun xue xi", "理论学习" }, { "li lun yan jiu", "理论研究" }, { "li lun zhi shi", "理论知识" },
			{ "li luo", "利落" }, { "li lv", "利率" }, { "li ma", "立马" }, { "li mao", "礼貌" }, { "li mei you", "里没有" }, { "li mi", "厘米" }, { "li mian", "立面" },
			{ "li mian", "里面" }, { "li min", "利民" }, { "li min", "李敏" }, { "li ming", "李明" }, { "li ming", "黎明" }, { "li mou", "李某" }, { "li na", "丽娜" },
			{ "li na", "厉娜" }, { "li na", "李娜" }, { "li nan", "李楠" }, { "li ni", "理你" }, { "li ni", "离你" }, { "li nian", "历年" }, { "li nian", "理念" },
			{ "li nian lai", "历年来" }, { "li niao", "利尿" }, { "li ning", "李宁" }, { "li pei", "理赔" }, { "li peng", "李鹏" }, { "li pi", "里皮" }, { "li pin", "礼品" },
			{ "li ping", "李平" }, { "li pu", "离谱" }, { "li qi", "利器" }, { "li qi", "力气" }, { "li qi", "离奇" }, { "li qi", "里奇" }, { "li qiang", "力强" },
			{ "li qiang", "李强" }, { "li qing", "沥青" }, { "li qing", "理清" }, { "li qing zhao", "李清照" }, { "li qiu", "力求" }, { "li qiu", "立秋" },
			{ "li qu", "离去" }, { "li qu", "里去" }, { "li ren", "丽人" }, { "li ren", "利刃" }, { "li ren", "历任" }, { "li ren", "离任" }, { "li ru", "例如" },
			{ "li run", "利润" }, { "li run fen pei", "利润分配" }, { "li run lv", "利润率" }, { "li run zeng zhang", "利润增长" }, { "li run zong e", "利润总额" },
			{ "li san", "离散" }, { "li sha", "丽莎" }, { "li sheng", "厉声" }, { "li shi", "力士" }, { "li shi", "历史" }, { "li shi", "历时" }, { "li shi", "李氏" },
			{ "li shi", "理事" }, { "li shi", "立式" }, { "li shi", "立时" }, { "li shi bei jing", "历史背景" }, { "li shi hui", "理事会" }, { "li shi ji lu", "历史记录" },
			{ "li shi jin cheng", "历史进程" }, { "li shi jing yan", "历史经验" }, { "li shi ju", "历史剧" }, { "li shi min", "李世民" }, { "li shi ren wu", "历史人物" },
			{ "li shi shang zui", "历史上最" }, { "li shi shi jian", "历史事件" }, { "li shi shi ming", "历史使命" }, { "li shi shi qi", "历史时期" },
			{ "li shi tiao jian", "历史条件" }, { "li shi wen hua", "历史文化" }, { "li shi wen ti", "历史问题" }, { "li shi xi", "历史系" }, { "li shi xing", "历史性" },
			{ "li shi xue", "历史学" }, { "li shi xue jia", "历史学家" }, { "li shi yi liu", "历史遗留" }, { "li shi yi yi", "历史意义" }, { "li shi you jiu", "历史悠久" },
			{ "li shi zhang", "理事长" }, { "li shu", "隶书" }, { "li shu", "隶属" }, { "li shui", "丽水" }, { "li shui", "利税" }, { "li shun", "理顺" },
			{ "li shuo", "里说" }, { "li si", "利斯" }, { "li si", "李四" }, { "li si", "李斯" }, { "li si", "里斯" }, { "li si ben", "里斯本" }, { "li suo", "利索" },
			{ "li suo dang ran", "理所当然" }, { "li suo neng ji", "力所能及" }, { "li ta", "理他" }, { "li ta", "离他" }, { "li tang", "礼堂" }, { "li tao", "李涛" },
			{ "li tao wan", "立陶宛" }, { "li ti", "例题" }, { "li ti", "立体" }, { "li ti gan", "立体感" }, { "li ti sheng", "立体声" }, { "li tian", "李天" },
			{ "li tie", "李铁" }, { "li ting", "力挺" }, { "li tou", "里头" }, { "li tu", "力图" }, { "li tui", "力推" }, { "li tui xiu", "离退休" }, { "li wai", "例外" },
			{ "li wai", "里外" }, { "li wei", "李伟" }, { "li wei", "立委" }, { "li wei feng", "李玮峰" }, { "li wen", "李文" }, { "li wo", "离我" }, { "li wu", "礼物" },
			{ "li wu", "里屋" }, { "li wu pu", "利物浦" }, { "li xi", "利息" }, { "li xi shui", "利息税" }, { "li xia", "立下" }, { "li xian", "离线" },
			{ "li xian sheng", "李先生" }, { "li xiang", "李湘" }, { "li xiang", "理想" }, { "li xiang", "立项" }, { "li xiang hua", "理想化" },
			{ "li xiang xin nian", "理想信念" }, { "li xiang zhu yi", "理想主义" }, { "li xiao", "李小" }, { "li xiao", "李晓" }, { "li xiao", "离校" },
			{ "li xiao li", "李孝利" }, { "li xiao long", "李小龙" }, { "li xin", "离心" }, { "li xin", "立新" }, { "li xin ji", "离心机" }, { "li xing", "例行" },
			{ "li xing", "理性" }, { "li xiu", "李秀" }, { "li xiu", "离休" }, { "li xu", "李旭" }, { "li xue", "力学" }, { "li xue", "理学" }, { "li ya", "利亚" },
			{ "li ya", "力压" }, { "li ya", "里亚" }, { "li ya peng", "李亚鹏" }, { "li yan hong", "李彦宏" }, { "li yang", "李阳" }, { "li ye", "立业" }, { "li ye", "里也" },
			{ "li yi", "利益" }, { "li yi", "李毅" }, { "li yi", "礼仪" }, { "li yi", "离异" }, { "li yi", "立意" }, { "li yi chong tu", "利益冲突" },
			{ "li yi fen pei", "利益分配" }, { "li yi guan xi", "利益关系" }, { "li yi ji tuan", "利益集团" }, { "li yin he", "李银河" }, { "li ying", "理应" },
			{ "li yong", "利用" }, { "li yong", "李勇" }, { "li yong", "李咏" }, { "li yong lv", "利用率" }, { "li yong wang luo", "利用网络" },
			{ "li yong xiao lv", "利用效率" }, { "li you", "理由" }, { "li you", "里有" }, { "li you ge", "里有个" }, { "li yu", "利于" }, { "li yu", "李玉" },
			{ "li yu", "礼遇" }, { "li yu", "立于" }, { "li yu", "鲤鱼" }, { "li yu chun", "李宇春" }, { "li yuan", "李元" }, { "li yuan", "梨园" }, { "li yun", "李云" },
			{ "li yun long", "李云龙" }, { "li zhao xing", "李肇星" }, { "li zhe", "立着" }, { "li zheng", "例证" }, { "li zheng", "力争" }, { "li zhi", "励志" },
			{ "li zhi", "李志" }, { "li zhi", "理智" }, { "li zhi", "离职" }, { "li zhi", "立志" }, { "li zhi", "荔枝" }, { "li zhi qi zhuang", "理直气壮" },
			{ "li zhu", "立柱" }, { "li zi", "例子" }, { "li zi", "李子" }, { "li zi", "栗子" }, { "li zi", "梨子" }, { "li zi", "离子" }, { "li zi", "粒子" },
			{ "li zi", "黎姿" }, { "li zi cheng", "李自成" }, { "li zong", "李总" }, { "li zong sheng", "李宗盛" }, { "li zu", "立足" }, { "li zuo", "力作" } };
};
