package com.webnation.util.keyboard.PinyinLists;

public class PINYIN_EN56 {
	public static String[][] pl = { { "yi an", "一案" }, { "yi an", "议案" }, { "yi ba", "一把" }, { "yi ba dao", "一把刀" }, { "yi ba shou", "一把手" },
			{ "yi bai", "一百" }, { "yi bai duo", "一百多" }, { "yi bai er shi", "一百二十" }, { "yi bai wan", "一百万" }, { "yi bai wu shi", "一百五十" },
			{ "yi bai yuan", "一百元" }, { "yi ban", "一半" }, { "yi ban", "一版" }, { "yi ban", "一班" }, { "yi ban", "一般" }, { "yi ban er yan", "一般而言" },
			{ "yi ban lai shuo", "一般来说" }, { "yi ban ren", "一般人" }, { "yi ban shuo lai", "一般说来" }, { "yi ban xing", "一般性" }, { "yi bang", "一帮" },
			{ "yi bao", "一包" }, { "yi bao", "医保" }, { "yi bei", "一倍" }, { "yi bei", "一杯" }, { "yi bei", "一辈" }, { "yi bei", "以北" }, { "yi bei", "以备" },
			{ "yi bei", "已被" }, { "yi bei", "易被" }, { "yi bei jiu", "一杯酒" }, { "yi bei shui", "一杯水" }, { "yi bei zi", "一辈子" }, { "yi ben", "一本" },
			{ "yi ben", "译本" }, { "yi ben zheng jing", "一本正经" }, { "yi bi", "一比" }, { "yi bi", "一笔" }, { "yi bi qian", "一笔钱" }, { "yi bi yi", "一比一" },
			{ "yi bian", "一变" }, { "yi bian", "一边" }, { "yi bian", "一遍" }, { "yi bian", "以便" }, { "yi bian bian", "一遍遍" }, { "yi bian dao", "一边倒" },
			{ "yi biao", "仪表" }, { "yi biao pan", "仪表盘" }, { "yi bin", "宜宾" }, { "yi bing", "一并" }, { "yi bing", "疫病" }, { "yi bo", "一拨" }, { "yi bo", "一波" },
			{ "yi bo san zhe", "一波三折" }, { "yi bu", "一步" }, { "yi bu", "一部" }, { "yi bu", "亦不" }, { "yi bu", "伊布" }, { "yi bu", "已不" }, { "yi bu", "异步" },
			{ "yi bu bu", "一步步" }, { "yi bu dao wei", "一步到位" }, { "yi bu rong ci", "义不容辞" }, { "yi bu xiao xin", "一不小心" }, { "yi bu yi bu", "一步一步" },
			{ "yi can", "一餐" }, { "yi ce", "一侧" }, { "yi ceng", "一层" }, { "yi cha", "一查" }, { "yi cha na", "一刹那" }, { "yi chan", "遗产" }, { "yi chang", "一场" },
			{ "yi chang", "一长" }, { "yi chang", "宜昌" }, { "yi chang", "异常" }, { "yi chang meng", "一场梦" }, { "yi chang shi", "宜昌市" }, { "yi che", "一车" },
			{ "yi cheng", "一城" }, { "yi cheng", "一成" }, { "yi cheng", "一程" }, { "yi cheng", "亦称" }, { "yi cheng", "已成" }, { "yi cheng", "议程" },
			{ "yi cheng", "译成" }, { "yi cheng bu bian", "一成不变" }, { "yi chi", "一尺" }, { "yi chou", "一筹" }, { "yi chu", "一出" }, { "yi chu", "一处" },
			{ "yi chu", "溢出" }, { "yi chu", "益处" }, { "yi chu", "移除" }, { "yi chu", "衣橱" }, { "yi chu ji fa", "一触即发" }, { "yi chu lian hua", "易初莲花" },
			{ "yi chuan", "一串" }, { "yi chuan", "遗传" }, { "yi chuan chuan", "一串串" }, { "yi chuan suan fa", "遗传算法" }, { "yi chuan xue", "遗传学" },
			{ "yi chuang", "一床" }, { "yi chui", "一吹" }, { "yi chun", "乙醇" }, { "yi chun", "宜春" }, { "yi ci", "一次" }, { "yi ci", "一词" }, { "yi ci", "以此" },
			{ "yi ci", "依次" }, { "yi ci ci", "一次次" }, { "yi ci hui yi", "一次会议" }, { "yi ci xing", "一次性" }, { "yi cong", "已从" }, { "yi cu er jiu", "一蹴而就" },
			{ "yi cun", "一寸" }, { "yi cun", "一村" }, { "yi cun", "依存" }, { "yi cun", "遗存" }, { "yi da", "一大" }, { "yi da", "一打" }, { "yi da", "已达" },
			{ "yi da ban", "一大半" }, { "yi da dui", "一大堆" }, { "yi da li", "意大利" }, { "yi da li dui", "意大利队" }, { "yi da li ren", "意大利人" },
			{ "yi da li yu", "意大利语" }, { "yi da zao", "一大早" }, { "yi dai", "一代" }, { "yi dai", "一带" }, { "yi dai", "一袋" }, { "yi dai", "以待" },
			{ "yi dai ren", "一代人" }, { "yi dan", "一旦" }, { "yi dang", "一党" }, { "yi dang", "一档" }, { "yi dao", "一刀" }, { "yi dao", "一到" }, { "yi dao", "一道" },
			{ "yi dao", "已到" }, { "yi dao", "移到" }, { "yi dao dao", "一道道" }, { "yi dao qie", "一刀切" }, { "yi dao su", "胰岛素" }, { "yi de", "医德" },
			{ "yi deng", "一等" }, { "yi deng jiang", "一等奖" }, { "yi di", "一地" }, { "yi di", "一滴" }, { "yi di", "异地" }, { "yi di lei", "一滴泪" },
			{ "yi di shui", "一滴水" }, { "yi dian", "一点" }, { "yi dian", "疑点" }, { "yi dian dian", "一点点" }, { "yi dian er", "一点儿" }, { "yi dian ye bu", "一点也不" },
			{ "yi dian yi di", "一点一滴" }, { "yi dian yi dian", "一点一点" }, { "yi dian yuan", "伊甸园" }, { "yi die", "一叠" }, { "yi die", "一碟" }, { "yi ding", "一定" },
			{ "yi ding", "一顶" }, { "yi ding", "已定" }, { "yi ding cheng du", "一定程度" }, { "yi ding dian", "一丁点" }, { "yi ding liang", "一定量" },
			{ "yi ding yao ba", "一定要把" }, { "yi ding yao kan", "一定要看" }, { "yi dong", "一动" }, { "yi dong", "一栋" }, { "yi dong", "以东" }, { "yi dong", "异动" },
			{ "yi dong", "易懂" }, { "yi dong", "移动" }, { "yi dong bu dong", "一动不动" }, { "yi dong dao", "移动到" }, { "yi dong dian hua", "移动电话" },
			{ "yi dong dian shi", "移动电视" }, { "yi dong gong si", "移动公司" }, { "yi dong she bei", "移动设备" }, { "yi dong tong xin", "移动通信" },
			{ "yi dong ying pan", "移动硬盘" }, { "yi dong yong hu", "移动用户" }, { "yi dou", "一抖" }, { "yi du", "一度" }, { "yi du", "一睹" }, { "yi duan", "一段" },
			{ "yi duan", "一端" }, { "yi duan hua", "一段话" }, { "yi duan shi jian", "一段时间" }, { "yi dui", "一堆" }, { "yi dui", "一对" }, { "yi dui", "一队" },
			{ "yi dui yi", "一对一" }, { "yi dun", "一吨" }, { "yi dun", "一顿" }, { "yi dun", "亿吨" }, { "yi duo", "一朵" }, { "yi duo", "亿多" },
			{ "yi duo hua", "一朵花" }, { "yi er", "一二" }, { "yi er", "伊尔" }, { "yi er zai", "一而再" }, { "yi fa", "一发" }, { "yi fa", "依法" }, { "yi fa", "已发" },
			{ "yi fa xing zheng", "依法行政" }, { "yi fa zhi guo", "依法治国" }, { "yi fan", "一番" }, { "yi fan", "一翻" }, { "yi fan", "疑犯" },
			{ "yi fan feng shun", "一帆风顺" }, { "yi fan hua", "一番话" }, { "yi fang", "一放" }, { "yi fang", "一方" }, { "yi fang", "乙方" }, { "yi fang", "以防" },
			{ "yi fang da", "易方达" }, { "yi fen", "一份" }, { "yi fen", "一分" }, { "yi fen tian ying", "义愤填膺" }, { "yi fen wei er", "一分为二" }, { "yi feng", "一封" },
			{ "yi feng xin", "一封信" }, { "yi fu", "一副" }, { "yi fu", "一夫" }, { "yi fu", "一幅" }, { "yi fu", "依附" }, { "yi fu", "姨夫" }, { "yi fu", "已付" },
			{ "yi fu", "衣服" }, { "yi fu fu", "一幅幅" }, { "yi fu hua", "一幅画" }, { "yi gai", "一改" }, { "yi gai", "一概" }, { "yi gai", "医改" }, { "yi gan", "一干" },
			{ "yi gan", "一杆" }, { "yi gan", "乙肝" }, { "yi gan bing du", "乙肝病毒" }, { "yi gan er jing", "一干二净" }, { "yi gan yi miao", "乙肝疫苗" },
			{ "yi gang", "一刚" }, { "yi gang", "一缸" }, { "yi ge", "一个" }, { "yi ge", "一格" }, { "yi ge jin", "一个劲" }, { "yi ge nv sheng", "一个女生" },
			{ "yi ge ren zhu", "一个人住" }, { "yi ge ren zou", "一个人走" }, { "yi ge yue hou", "一个月后" }, { "yi ge yue nei", "一个月内" }, { "yi gen", "一根" },
			{ "yi gen yan", "一根烟" }, { "yi gong", "一共" }, { "yi gong", "义工" }, { "yi gong", "以供" }, { "yi gou", "异构" }, { "yi gu", "一股" }, { "yi gu", "亿股" },
			{ "yi gu", "已故" }, { "yi guan", "一关" }, { "yi guan", "一罐" }, { "yi guan", "一贯" }, { "yi guan", "衣冠" }, { "yi gui", "衣柜" }, { "yi guo", "一国" },
			{ "yi guo", "一过" }, { "yi guo", "一锅" }, { "yi guo", "已过" }, { "yi guo", "异国" }, { "yi guo liang zhi", "一国两制" }, { "yi han", "遗憾" },
			{ "yi hang", "一行" }, { "yi hao", "一号" }, { "yi hao xian", "一号线" }, { "yi he", "一盒" }, { "yi he yuan", "颐和园" }, { "yi hong", "一红" },
			{ "yi hou", "以后" }, { "yi hu", "一壶" }, { "yi hu", "一户" }, { "yi hu ren yuan", "医护人员" }, { "yi hua", "异化" }, { "yi huan", "一环" },
			{ "yi huan", "医患" }, { "yi huan", "易患" }, { "yi huang", "一晃" }, { "yi hui", "一会" }, { "yi hui", "一回" }, { "yi hui", "一挥" }, { "yi hui", "亦会" },
			{ "yi hui", "议会" }, { "yi hui er", "一会儿" }, { "yi hui shi", "一回事" }, { "yi hun", "已婚" }, { "yi huo", "一伙" }, { "yi huo", "亦或" },
			{ "yi huo", "已获" }, { "yi huo", "抑或" }, { "yi huo", "疑惑" }, { "yi ji", "一击" }, { "yi ji", "一剂" }, { "yi ji", "一季" }, { "yi ji", "一己" },
			{ "yi ji", "一级" }, { "yi ji", "一记" }, { "yi ji", "一集" }, { "yi ji", "乙级" }, { "yi ji", "亦即" }, { "yi ji", "以及" }, { "yi ji", "遗迹" },
			{ "yi ji du", "一季度" }, { "yi ji qi ta", "以及其他" }, { "yi ji shi chang", "一级市场" }, { "yi ji zhi chang", "一技之长" }, { "yi jia", "一家" },
			{ "yi jia", "一架" }, { "yi jia", "宜家" }, { "yi jia", "意甲" }, { "yi jia", "溢价" }, { "yi jia", "衣架" }, { "yi jia", "议价" }, { "yi jia zi", "一家子" },
			{ "yi jian", "一件" }, { "yi jian", "一剑" }, { "yi jian", "一见" }, { "yi jian", "一键" }, { "yi jian", "一间" }, { "yi jian", "意见" },
			{ "yi jian jian", "一件件" }, { "yi jian jian yi", "意见建议" }, { "yi jian lian", "易建联" }, { "yi jian shi", "一件事" }, { "yi jian shi qing", "一件事情" },
			{ "yi jian shu", "意见书" }, { "yi jian zhong qing", "一见钟情" }, { "yi jiang", "一讲" }, { "yi jiang", "已将" }, { "yi jiao", "一脚" }, { "yi jiao", "一觉" },
			{ "yi jiao", "一角" }, { "yi jiao", "一跤" }, { "yi jiao", "移交" }, { "yi jiao", "衣角" }, { "yi jie", "一介" }, { "yi jie", "一劫" }, { "yi jie", "一届" },
			{ "yi jie", "一截" }, { "yi jie", "一节" }, { "yi jie", "异界" }, { "yi jie ke", "一节课" }, { "yi jin", "一斤" }, { "yi jin", "一进" }, { "yi jin", "已尽" },
			{ "yi jin", "已近" }, { "yi jin", "衣襟" }, { "yi jing", "一惊" }, { "yi jing", "一经" }, { "yi jing", "已经" }, { "yi jing", "意境" }, { "yi jing", "易经" },
			{ "yi jing", "遗精" }, { "yi jing hen", "已经很" }, { "yi jiu", "一九" }, { "yi jiu", "依旧" }, { "yi jiu", "已久" }, { "yi jiu ba", "一九八" },
			{ "yi jiu qi", "一九七" }, { "yi jiu si", "一九四" }, { "yi ju", "一举" }, { "yi ju", "一具" }, { "yi ju", "一句" }, { "yi ju", "一局" }, { "yi ju", "一居" },
			{ "yi ju", "依据" }, { "yi ju", "宜居" }, { "yi ju", "移居" }, { "yi ju hua", "一句话" }, { "yi ju liang de", "一举两得" }, { "yi ju yi dong", "一举一动" },
			{ "yi juan", "一卷" }, { "yi jue", "一绝" }, { "yi jue bu zhen", "一蹶不振" }, { "yi jun", "以军" }, { "yi jun tu qi", "异军突起" }, { "yi ka", "一卡" },
			{ "yi ka tong", "一卡通" }, { "yi kai", "一开" }, { "yi kai", "移开" }, { "yi kan", "一看" }, { "yi kao", "依靠" }, { "yi ke", "一刻" }, { "yi ke", "一棵" },
			{ "yi ke", "一科" }, { "yi ke", "一课" }, { "yi ke", "一颗" }, { "yi ke", "亦可" }, { "yi ke da xue", "医科大学" }, { "yi ke ke", "一颗颗" },
			{ "yi ke shu", "一棵树" }, { "yi ke xin", "一颗心" }, { "yi kong", "一空" }, { "yi kou", "一口" }, { "yi kou jia", "一口价" }, { "yi kou qi", "一口气" },
			{ "yi kou tong sheng", "异口同声" }, { "yi kou yi kou", "一口一口" }, { "yi ku", "衣裤" }, { "yi kuai", "一块" }, { "yi kuai er", "一块儿" },
			{ "yi kuai kuai", "一块块" }, { "yi kuai qian", "一块钱" }, { "yi kuan", "一款" }, { "yi la", "一拉" }, { "yi la guan", "易拉罐" }, { "yi la ke", "伊拉克" },
			{ "yi la ke ren", "伊拉克人" }, { "yi lai", "一来" }, { "yi lai", "以来" }, { "yi lai", "依赖" }, { "yi lai ke si", "伊莱克斯" }, { "yi lai xing", "依赖性" },
			{ "yi lan", "一栏" }, { "yi lan", "一览" }, { "yi lan biao", "一览表" }, { "yi lan te", "伊兰特" }, { "yi lan zi", "一揽子" }, { "yi lang", "一浪" },
			{ "yi lang", "一郎" }, { "yi lang", "伊朗" }, { "yi lao yong yi", "一劳永逸" }, { "yi lei", "一类" }, { "yi lei", "异类" }, { "yi leng", "一愣" },
			{ "yi li", "一例" }, { "yi li", "一粒" }, { "yi li", "以利" }, { "yi li", "伊利" }, { "yi li", "伊犁" }, { "yi li", "屹立" }, { "yi li", "毅力" },
			{ "yi li sha bai", "伊丽莎白" }, { "yi lian", "一脸" }, { "yi lian", "一连" }, { "yi lian", "依恋" }, { "yi lian chuan", "一连串" }, { "yi lian de", "一脸的" },
			{ "yi lian you meng", "一帘幽梦" }, { "yi liang", "一两" }, { "yi liang", "一亮" }, { "yi liang", "一辆" }, { "yi liang che", "一辆车" }, { "yi liao", "医疗" },
			{ "yi liao", "意料" }, { "yi liao bao jian", "医疗保健" }, { "yi liao bao xian", "医疗保险" }, { "yi liao bao zhang", "医疗保障" }, { "yi liao dui", "医疗队" },
			{ "yi liao fei", "医疗费" }, { "yi liao fei yong", "医疗费用" }, { "yi liao fu wu", "医疗服务" }, { "yi liao ji gou", "医疗机构" }, { "yi liao jiu zhu", "医疗救助" },
			{ "yi liao qi xie", "医疗器械" }, { "yi liao she bei", "医疗设备" }, { "yi liao shi gu", "医疗事故" }, { "yi liao wei sheng", "医疗卫生" },
			{ "yi liao zhi wai", "意料之外" }, { "yi liao zhi zhong", "意料之中" }, { "yi lie", "一列" }, { "yi ling", "衣领" }, { "yi liu", "一流" }, { "yi liu", "一溜" },
			{ "yi liu", "遗留" }, { "yi liu wen ti", "遗留问题" }, { "yi lou", "一楼" }, { "yi lou", "遗漏" }, { "yi lu", "一路" }, { "yi lu shun feng", "一路顺风" },
			{ "yi lu zou lai", "一路走来" }, { "yi lun", "一轮" }, { "yi lun", "议论" }, { "yi lun fen fen", "议论纷纷" }, { "yi lv", "一律" }, { "yi lv", "一缕" },
			{ "yi lv", "疑虑" }, { "yi ma", "一马" }, { "yi ma", "姨妈" }, { "yi mai", "义卖" }, { "yi mai xiang cheng", "一脉相承" }, { "yi man", "已满" },
			{ "yi mao", "一毛" }, { "yi mei", "一枚" }, { "yi mei", "亿美" }, { "yi men", "一门" }, { "yi mi", "一米" }, { "yi mian", "一面" }, { "yi mian", "以免" },
			{ "yi miao", "一秒" }, { "yi miao", "疫苗" }, { "yi min", "益民" }, { "yi min", "移民" }, { "yi min ju", "移民局" }, { "yi ming", "一名" }, { "yi ming", "一命" },
			{ "yi ming", "译名" }, { "yi ming jing ren", "一鸣惊人" }, { "yi mo", "一抹" }, { "yi mo", "一摸" }, { "yi mo yi yang", "一模一样" }, { "yi mu", "一亩" },
			{ "yi mu", "一幕" }, { "yi mu liao ran", "一目了然" }, { "yi mu mu", "一幕幕" }, { "yi mu yi yang", "一模一样" }, { "yi nan", "一男" }, { "yi nan", "以南" },
			{ "yi nan", "疑难" }, { "yi nan wen ti", "疑难问题" }, { "yi nan yi nv", "一男一女" }, { "yi nan zi", "一男子" }, { "yi nei", "以内" }, { "yi neng", "异能" },
			{ "yi neng jing", "伊能静" }, { "yi ni", "旖旎" }, { "yi nian", "一年" }, { "yi nian", "一念" }, { "yi nian", "意念" }, { "yi nian ban", "一年半" },
			{ "yi nian de", "一年的" }, { "yi nian duo", "一年多" }, { "yi nian hou", "一年后" }, { "yi nian lai", "一年来" }, { "yi nian nei", "一年内" },
			{ "yi nian qi", "一年期" }, { "yi nian qian", "一年前" }, { "yi nian si ji", "一年四季" }, { "yi nian yi du", "一年一度" }, { "yi nv", "一女" },
			{ "yi pai", "一拍" }, { "yi pai", "一排" }, { "yi pai", "一派" }, { "yi pai pai", "一排排" }, { "yi pan", "一盘" }, { "yi pang", "一旁" }, { "yi pao", "一炮" },
			{ "yi pen", "一盆" }, { "yi peng", "一碰" }, { "yi pi", "一匹" }, { "yi pi", "一批" }, { "yi pian", "一片" }, { "yi pian", "一篇" },
			{ "yi pian kong bai", "一片空白" }, { "yi pian pian", "一片片" }, { "yi pian wen zhang", "一篇文章" }, { "yi piao", "一票" }, { "yi pie", "一瞥" },
			{ "yi pin", "一品" }, { "yi pin", "一拼" }, { "yi ping", "一平" }, { "yi ping", "一瓶" }, { "yi qi", "一期" }, { "yi qi", "一气" }, { "yi qi", "一汽" },
			{ "yi qi", "一起" }, { "yi qi", "一齐" }, { "yi qi", "义气" }, { "yi qi", "以其" }, { "yi qi", "以期" }, { "yi qi", "仪器" }, { "yi qi", "忆起" },
			{ "yi qi", "意气" }, { "yi qi", "益气" }, { "yi qi", "遗弃" }, { "yi qi chi", "一起吃" }, { "yi qi da zhong", "一汽大众" }, { "yi qi fen xiang", "一起分享" },
			{ "yi qi feng fa", "意气风发" }, { "yi qi feng tian", "一汽丰田" }, { "yi qi he cheng", "一气呵成" }, { "yi qi kan", "一起看" }, { "yi qi qu", "一起去" },
			{ "yi qi she bei", "仪器设备" }, { "yi qi wan", "一起玩" }, { "yi qi yi biao", "仪器仪表" }, { "yi qi zhi xia", "一气之下" }, { "yi qi zou", "一起走" },
			{ "yi qi zou guo", "一起走过" }, { "yi qi zuo", "一起做" }, { "yi qian", "一千" }, { "yi qian", "以前" }, { "yi qian duo", "一千多" }, { "yi qian wan", "一千万" },
			{ "yi qiang", "一枪" }, { "yi qiang", "一腔" }, { "yi qiao bu tong", "一窍不通" }, { "yi qie", "一切" }, { "yi qie dou shi", "一切都是" }, { "yi qing", "疫情" },
			{ "yi qing", "移情" }, { "yi qing er chu", "一清二楚" }, { "yi qiu", "一球" }, { "yi qiu", "以求" }, { "yi qu", "一区" }, { "yi qu", "一去" }, { "yi qu", "一曲" },
			{ "yi qu", "易趣" }, { "yi qu", "疫区" }, { "yi qu tong gong", "异曲同工" }, { "yi quan", "一圈" }, { "yi quan", "一拳" }, { "yi qun", "一群" },
			{ "yi qun ren", "一群人" }, { "yi ran", "亦然" }, { "yi ran", "依然" }, { "yi ran", "已然" }, { "yi ran", "毅然" }, { "yi re", "一热" }, { "yi ren", "一人" },
			{ "yi ren", "一任" }, { "yi ren", "亿人" }, { "yi ren", "伊人" }, { "yi ren", "宜人" }, { "yi ren", "怡人" }, { "yi ren", "艺人" },
			{ "yi ren wei ben", "以人为本" }, { "yi reng", "一扔" }, { "yi ri", "一日" }, { "yi ri san can", "一日三餐" }, { "yi ri you", "一日游" }, { "yi ru", "一如" },
			{ "yi ru ji wang", "一如既往" }, { "yi sao", "一扫" }, { "yi se", "一色" }, { "yi se lie", "以色列" }, { "yi shan", "一山" }, { "yi shan", "一扇" },
			{ "yi shan", "一闪" }, { "yi shan", "依山" }, { "yi shan", "衣衫" }, { "yi shan er guo", "一闪而过" }, { "yi shan men", "一扇门" }, { "yi shang", "以上" },
			{ "yi shang", "椅上" }, { "yi shang", "衣裳" }, { "yi shang xue li", "以上学历" }, { "yi shao", "一勺" }, { "yi shen", "一审" }, { "yi shen", "一身" },
			{ "yi shen pan jue", "一审判决" }, { "yi shen xiang xu", "以身相许" }, { "yi shen zuo ze", "以身作则" }, { "yi sheng", "一声" }, { "yi sheng", "一生" },
			{ "yi sheng", "医生" }, { "yi sheng bu keng", "一声不吭" }, { "yi sheng tan xi", "一声叹息" }, { "yi sheng yi shi", "一生一世" }, { "yi shi", "一世" },
			{ "yi shi", "一事" }, { "yi shi", "一室" }, { "yi shi", "一式" }, { "yi shi", "一时" }, { "yi shi", "一是" }, { "yi shi", "一石" }, { "yi shi", "一试" },
			{ "yi shi", "亦是" }, { "yi shi", "以使" }, { "yi shi", "以示" }, { "yi shi", "仪式" }, { "yi shi", "伊始" }, { "yi shi", "医师" }, { "yi shi", "已是" },
			{ "yi shi", "意识" }, { "yi shi", "衣食" }, { "yi shi", "议事" }, { "yi shi", "遗失" }, { "yi shi jian", "一时间" }, { "yi shi ri cheng", "议事日程" },
			{ "yi shi tong ren", "一视同仁" }, { "yi shi wu cheng", "一事无成" }, { "yi shi wu you", "衣食无忧" }, { "yi shi xing tai", "意识形态" },
			{ "yi shi yi ting", "一室一厅" }, { "yi shi zhu xing", "衣食住行" }, { "yi shou", "一手" }, { "yi shou", "一首" }, { "yi shou ge", "一首歌" },
			{ "yi shou shi", "一首诗" }, { "yi shu", "一书" }, { "yi shu", "一束" }, { "yi shu", "一树" }, { "yi shu", "医术" }, { "yi shu", "艺术" }, { "yi shu", "遗书" },
			{ "yi shu chuang zuo", "艺术创作" }, { "yi shu guan", "艺术馆" }, { "yi shu jia", "艺术家" }, { "yi shu jie", "艺术节" }, { "yi shu lei", "艺术类" },
			{ "yi shu pin", "艺术品" }, { "yi shu she ji", "艺术设计" }, { "yi shu tuan", "艺术团" }, { "yi shu xing", "艺术性" }, { "yi shu xing shi", "艺术形式" },
			{ "yi shu xue yuan", "艺术学院" }, { "yi shu zhao", "艺术照" }, { "yi shu zhong xin", "艺术中心" }, { "yi shu zuo pin", "艺术作品" }, { "yi shuang", "一双" },
			{ "yi shui", "一水" }, { "yi shun", "一瞬" }, { "yi shun jian", "一瞬间" }, { "yi shuo", "一说" }, { "yi si", "一丝" }, { "yi si", "一死" }, { "yi si", "已死" },
			{ "yi si", "意思" }, { "yi si", "疑似" }, { "yi si bu gou", "一丝不苟" }, { "yi si bu gua", "一丝不挂" }, { "yi si lan", "伊斯兰" }, { "yi si lan jiao", "伊斯兰教" },
			{ "yi si si", "一丝丝" }, { "yi song", "移送" }, { "yi sou", "一艘" }, { "yi sui", "一岁" }, { "yi suo", "一所" }, { "yi ta hu tu", "一塌糊涂" },
			{ "yi tai", "一台" }, { "yi tai dian nao", "一台电脑" }, { "yi tai wang", "以太网" }, { "yi tan", "一探" }, { "yi tang", "一堂" }, { "yi tang", "一趟" },
			{ "yi tao", "一套" }, { "yi teng", "伊藤" }, { "yi ti", "一体" }, { "yi ti", "一提" }, { "yi ti", "一题" }, { "yi ti", "议题" }, { "yi ti", "遗体" },
			{ "yi ti hua", "一体化" }, { "yi ti ji", "一体机" }, { "yi tian", "一天" }, { "yi tian", "倚天" }, { "yi tian dao wan", "一天到晚" }, { "yi tian tian", "一天天" },
			{ "yi tian yi tian", "一天一天" }, { "yi tiao", "一条" }, { "yi tiao", "一跳" }, { "yi tiao gou", "一条狗" }, { "yi tiao jie", "一条街" },
			{ "yi tiao long", "一条龙" }, { "yi tiao lu", "一条路" }, { "yi tiao tiao", "一条条" }, { "yi tiao tui", "一条腿" }, { "yi tiao xian", "一条线" },
			{ "yi tiao yu", "一条鱼" }, { "yi tie", "一帖" }, { "yi tie", "一贴" }, { "yi ting", "一厅" }, { "yi ting", "一听" }, { "yi tong", "一同" },
			{ "yi tong", "一桶" }, { "yi tong", "一统" }, { "yi tong", "一通" }, { "yi tong", "异同" }, { "yi tou", "一头" }, { "yi tou wu shui", "一头雾水" },
			{ "yi tu", "意图" }, { "yi tuan", "一团" }, { "yi tuan zao", "一团糟" }, { "yi tui", "一推" }, { "yi tui", "一腿" }, { "yi tuo", "一拖" }, { "yi tuo", "依托" },
			{ "yi wai", "以外" }, { "yi wai", "意外" }, { "yi wan", "一万" }, { "yi wan", "一晚" }, { "yi wan", "一碗" }, { "yi wan", "亿万" },
			{ "yi wan fu weng", "亿万富翁" }, { "yi wan yuan", "一万元" }, { "yi wang", "一望" }, { "yi wang", "以往" }, { "yi wang", "遗忘" },
			{ "yi wang da jin", "一网打尽" }, { "yi wang wu ji", "一望无际" }, { "yi wei", "一位" }, { "yi wei", "一味" }, { "yi wei", "一维" }, { "yi wei", "亦为" },
			{ "yi wei", "以为" }, { "yi wei", "依偎" }, { "yi wei", "已为" }, { "yi wei", "异位" }, { "yi wei", "异味" }, { "yi wei", "意为" }, { "yi wei", "意味" },
			{ "yi wei", "移位" }, { "yi wei", "译为" }, { "yi wei shen chang", "意味深长" }, { "yi wei zhe", "意味着" }, { "yi wei zi ji", "以为自己" }, { "yi wen", "一吻" },
			{ "yi wen", "一文" }, { "yi wen", "一问" }, { "yi wen", "疑问" }, { "yi wen", "译文" }, { "yi wen bu zhi", "一文不值" }, { "yi wo", "一窝" },
			{ "yi wo feng", "一窝蜂" }, { "yi wu", "义乌" }, { "yi wu", "义务" }, { "yi wu", "亦无" }, { "yi wu", "已无" }, { "yi wu", "异物" }, { "yi wu", "衣物" },
			{ "yi wu", "遗物" }, { "yi wu fan gu", "义无反顾" }, { "yi wu fan gu", "义无返顾" }, { "yi wu jiao yu", "义务教育" }, { "yi wu ren yuan", "医务人员" },
			{ "yi wu shi", "义乌市" }, { "yi wu shi chu", "一无是处" }, { "yi wu suo huo", "一无所获" }, { "yi wu suo you", "一无所有" }, { "yi wu suo zhi", "一无所知" },
			{ "yi xi", "一席" }, { "yi xi", "一袭" }, { "yi xi", "乙烯" }, { "yi xi", "以西" }, { "yi xi", "依稀" }, { "yi xi hua", "一席话" }, { "yi xi lie", "一系列" },
			{ "yi xi lie de", "一系列的" }, { "yi xi zhi di", "一席之地" }, { "yi xia", "一下" }, { "yi xia", "以下" }, { "yi xia ba", "一下吧" },
			{ "yi xia ji dian", "以下几点" }, { "yi xia jian cheng", "以下简称" }, { "yi xia nei rong", "以下内容" }, { "yi xia xia", "一下下" }, { "yi xia zi", "一下子" },
			{ "yi xian", "一线" }, { "yi xian", "胰腺" }, { "yi xian ai", "胰腺癌" }, { "yi xiang", "一向" }, { "yi xiang", "一响" }, { "yi xiang", "一想" },
			{ "yi xiang", "一箱" }, { "yi xiang", "一项" }, { "yi xiang", "已向" }, { "yi xiang", "异乡" }, { "yi xiang", "意向" }, { "yi xiang", "意象" },
			{ "yi xiang", "臆想" } };
};
