package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R10 {
	public static String[][] kl = { { "ma", "眞" }, { "ma", "真" }, { "ma", "磨" }, { "ma", "糅" }, { "ma", "舞" }, { "ma", "茉" }, { "ma", "萬" }, { "ma", "蟆" },
			{ "ma", "蟇" }, { "ma", "誠" }, { "ma", "豆" }, { "ma", "負" }, { "ma", "部" }, { "ma", "間" }, { "ma", "馬" }, { "ma", "魔" }, { "ma", "麗" },
			{ "ma", "麻" }, { "ma", "麼" }, { "ma", "麿" }, { "maTU", "松" }, { "maTU", "真" }, { "maa", "真" }, { "maa", "麻" }, { "maba", "疎" }, { "maba", "踈" },
			{ "mabara", "疏" }, { "mabara", "稀" }, { "mabe", "米" }, { "maborosi", "幻" }, { "mabu", "眩" }, { "mabusi", "蔟" }, { "mabuta", "瞼" },
			{ "madara", "斑" }, { "madara", "駁" }, { "madara", "駮" }, { "madarausi", "犖" }, { "madare", "广" }, { "made", "迄" }, { "mado", "円" },
			{ "mado", "圓" }, { "mado", "惑" }, { "mado", "真" }, { "mado", "眩" }, { "mado", "窓" }, { "mado", "窗" }, { "madoka", "円" }, { "madoka", "欒" },
			{ "mae", "前" }, { "maga", "擬" }, { "maga", "紆" }, { "magaki", "樊" }, { "magaki", "篳" }, { "magaki", "籬" }, { "magari", "勾" },
			{ "magarigawa", "巛" }, { "magata", "曲" }, { "mage", "髷" }, { "magemono", "椦" }, { "magi", "紛" }, { "mago", "孫" }, { "magokoro", "悃" },
			{ "maguro", "鮪" }, { "magusa", "秣" }, { "magusa", "芻" }, { "magusa", "蒭" }, { "magusakau", "秣" }, { "mai", "剃" }, { "mai", "前" }, { "mai", "参" },
			{ "mai", "參" }, { "mai", "埋" }, { "mai", "妹" }, { "mai", "昧" }, { "mai", "枚" }, { "mai", "毎" }, { "mai", "煤" }, { "mai", "牧" }, { "mai", "瑁" },
			{ "mai", "眛" }, { "mai", "米" }, { "mai", "舛" }, { "mai", "舞" }, { "mai", "苺" }, { "mai", "莓" }, { "mai", "蒔" }, { "mai", "詣" }, { "mai", "邁" },
			{ "mai", "鞠" }, { "mai", "黴" }, { "maiasi", "舛" }, { "maina", "賂" }, { "mairu", "哩" }, { "maka", "任" }, { "maka", "罷" }, { "maka", "蒔" },
			{ "makana", "賄" }, { "makase", "委" }, { "maki", "卷" }, { "maki", "填" }, { "maki", "巻" }, { "maki", "槇" }, { "maki", "槙" }, { "maki", "牧" },
			{ "maki", "蒔" }, { "maki", "薪" }, { "makigamae", "冂" }, { "mako", "眞" }, { "mako", "真" }, { "mako", "誠" }, { "makomo", "菰" }, { "makomo", "蒋" },
			{ "makoto", "一" }, { "makoto", "丹" }, { "makoto", "亮" }, { "makoto", "信" }, { "makoto", "允" }, { "makoto", "周" }, { "makoto", "実" },
			{ "makoto", "實" }, { "makoto", "忱" }, { "makoto", "恂" }, { "makoto", "惇" }, { "makoto", "愨" }, { "makoto", "慎" }, { "makoto", "洵" },
			{ "makoto", "淳" }, { "makoto", "理" }, { "makoto", "眞" }, { "makoto", "真" }, { "makoto", "紳" }, { "makoto", "胆" }, { "makoto", "良" },
			{ "makoto", "詢" }, { "makoto", "誠" }, { "makoto", "諒" }, { "makoto", "諦" }, { "makoto", "賢" }, { "makotoni", "凉" }, { "makotoni", "実" },
			{ "makotoni", "寔" }, { "makotoni", "涼" }, { "makotoni", "諒" }, { "maku", "寞" }, { "maku", "幔" }, { "maku", "幕" }, { "maku", "捲" }, { "maku", "摸" },
			{ "maku", "繃" }, { "maku", "膜" }, { "maku", "莫" }, { "maku", "蒔" }, { "makura", "枕" }, { "mama", "侭" }, { "mama", "儘" }, { "mama", "圸" },
			{ "mama", "墹" }, { "mama", "壗" }, { "mama", "海" }, { "mama", "畑" }, { "mama", "盡" }, { "mama", "継" }, { "mama", "繼" }, { "mame", "荳" },
			{ "mame", "菽" }, { "mame", "豆" }, { "mami", "塗" }, { "mami", "猯" }, { "mami", "覲" }, { "mami", "逅" }, { "mami", "遘" }, { "mamo", "守" },
			{ "mamo", "戍" }, { "mamo", "掫" }, { "mamo", "衞" }, { "mamo", "護" }, { "mamori", "戍" }, { "mamori", "衞" }, { "mamoru", "葵" }, { "mamoru", "衛" },
			{ "mamoru", "衞" }, { "mamusi", "蝮" }, { "man", "万" }, { "man", "卍" }, { "man", "幔" }, { "man", "幡" }, { "man", "悗" }, { "man", "慢" },
			{ "man", "懣" }, { "man", "政" }, { "man", "曼" }, { "man", "満" }, { "man", "滿" }, { "man", "漫" }, { "man", "瞞" }, { "man", "縵" }, { "man", "茨" },
			{ "man", "萬" }, { "man", "蔓" }, { "man", "謾" }, { "man", "蹣" }, { "man", "鏝" }, { "man", "饅" }, { "man", "鬘" }, { "man", "鰻" }, { "mana", "学" },
			{ "mana", "學" }, { "mana", "愛" }, { "mana", "斈" }, { "mana", "真" }, { "manabiya", "庠" }, { "manaita", "俎" }, { "manaita", "爼" }, { "manako", "眼" },
			{ "manaziri", "眥" }, { "manaziri", "眦" }, { "manaziri", "睚" }, { "mane", "招" }, { "manimani", "随" }, { "manimani", "隨" }, { "manuga", "免" },
			{ "manuka", "免" }, { "manzi", "卍" }, { "mara", "厩" }, { "mare", "希" }, { "mare", "稀" }, { "mare", "罕" }, { "mari", "毬" }, { "mari", "鞠" },
			{ "maro", "円" }, { "maro", "圓" }, { "maro", "理" }, { "maro", "転" }, { "maro", "轉" }, { "maro", "麿" }, { "maru", "丸" }, { "maru", "円" },
			{ "maru", "団" }, { "maru", "圓" }, { "maru", "團" }, { "maru", "圜" }, { "maru", "摶" }, { "marui", "欒" }, { "marui", "肱" }, { "masa", "仁" },
			{ "masa", "倭" }, { "masa", "傑" }, { "masa", "優" }, { "masa", "允" }, { "masa", "充" }, { "masa", "全" }, { "masa", "公" }, { "masa", "剛" },
			{ "masa", "勝" }, { "masa", "匡" }, { "masa", "和" }, { "masa", "多" }, { "masa", "夛" }, { "masa", "大" }, { "masa", "存" }, { "masa", "容" },
			{ "masa", "将" }, { "masa", "將" }, { "masa", "幹" }, { "masa", "庄" }, { "masa", "当" }, { "masa", "征" }, { "masa", "応" }, { "masa", "愈" },
			{ "masa", "成" }, { "masa", "政" }, { "masa", "方" }, { "masa", "昌" }, { "masa", "晶" }, { "masa", "暢" }, { "masa", "柾" }, { "masa", "橸" },
			{ "masa", "款" }, { "masa", "正" }, { "masa", "理" }, { "masa", "甲" }, { "masa", "當" }, { "masa", "眞" }, { "masa", "真" }, { "masa", "祐" },
			{ "masa", "祥" }, { "masa", "稚" }, { "masa", "聖" }, { "masa", "誠" }, { "masa", "諒" }, { "masa", "賢" }, { "masa", "雅" }, { "masa", "順" },
			{ "masaka", "作" }, { "masakari", "戉" }, { "masakari", "鉞" }, { "masaki", "柾" }, { "masame", "柾" }, { "masani", "応" }, { "masani", "應" },
			{ "masani", "祇" }, { "masani", "祗" }, { "masaru", "克" }, { "masaru", "冠" }, { "masaru", "大" }, { "masaru", "將" }, { "masaru", "甲" },
			{ "masaru", "豪" }, { "masaru", "賢" }, { "masaru", "超" }, { "masasi", "仁" }, { "masasi", "匡" }, { "masasi", "奨" }, { "masasi", "昌" },
			{ "masasi", "正" }, { "masasi", "理" }, { "masasi", "雅" }, { "mase", "柵" }, { "masi", "况" }, { "masi", "増" }, { "masi", "況" }, { "masi", "猿" },
			{ "masi", "益" }, { "masimasu", "坐" }, { "masu", "倍" }, { "masu", "升" }, { "masu", "増" }, { "masu", "斗" }, { "masu", "枡" }, { "masu", "桀" },
			{ "masu", "桝" }, { "masu", "益" }, { "masu", "舛" }, { "masu", "裨" }, { "masu", "鱒" }, { "masura", "丈" }, { "mata", "也" }, { "mata", "亦" },
			{ "mata", "俣" }, { "mata", "又" }, { "mata", "叉" }, { "mata", "岐" }, { "mata", "復" }, { "mata", "椏" }, { "mata", "殳" }, { "mata", "股" },
			{ "mata", "胯" }, { "mata", "街" }, { "mata", "跨" }, { "mataga", "跨" }, { "matata", "瞬" }, { "mate", "蟶" }, { "mate", "鮴" }, { "mati", "待" },
			{ "mati", "海" }, { "mati", "町" }, { "mati", "街" }, { "mati", "襠" }, { "mati", "陌" }, { "mati", "韈" }, { "mato", "本" }, { "mato", "的" },
			{ "mato", "繆" }, { "mato", "繚" }, { "mato", "纏" }, { "mato", "纒" }, { "mato", "鵠" }, { "matou", "綢" }, { "matou", "繞" }, { "matta", "全" },
			{ "matu", "奉" }, { "matu", "奠" }, { "matu", "待" }, { "matu", "抹" }, { "matu", "末" }, { "matu", "松" }, { "matu", "枌" }, { "matu", "枩" },
			{ "matu", "沫" }, { "matu", "眞" }, { "matu", "祀" }, { "matu", "祭" }, { "matu", "祷" }, { "matu", "秣" }, { "matu", "竢" }, { "matu", "纏" },
			{ "matu", "纒" }, { "matu", "茉" }, { "matu", "茨" }, { "matu", "靺" }, { "matu", "須" }, { "matuge", "睫" }, { "maturi", "祀" }, { "maturi", "祭" },
			{ "maturigoto", "政" }, { "maturu", "祠" }, { "mawa", "周" }, { "mawa", "囘" }, { "mawa", "回" }, { "mawa", "廻" }, { "mawa", "繞" }, { "mawari", "仗" },
			{ "maya", "厩" }, { "mayo", "迷" }, { "mayu", "眉" }, { "mayu", "真" }, { "mayu", "繭" }, { "mayumi", "檀" }, { "mayuzumi", "黛" }, { "mazi", "交" },
			{ "mazi", "爻" }, { "mazi", "襍" }, { "mazi", "雑" }, { "mazi", "雜" }, { "mazi", "駁" }, { "mazina", "呪" }, { "mazina", "咒" }, { "mazinai", "咒" },
			{ "maziwaru", "参" }, { "maziwaru", "參" }, { "maziwaru", "爻" }, { "mazu", "貧" }, { "me", "め" }, { "me", "メ" }, { "me", "五" }, { "me", "免" },
			{ "me", "匁" }, { "me", "召" }, { "me", "売" }, { "me", "女" }, { "me", "妻" }, { "me", "明" }, { "me", "海" }, { "me", "牝" }, { "me", "瑪" },
			{ "me", "目" }, { "me", "眼" }, { "me", "碼" }, { "me", "米" }, { "me", "聘" }, { "me", "芽" }, { "me", "辟" }, { "me", "銘" }, { "me", "雌" },
			{ "me", "馬" }, { "meawa", "娶" }, { "mebae", "萌" }, { "mebae", "萠" }, { "mebaru", "鮴" }, { "medogi", "筮" }, { "medogi", "筴" }, { "medogi", "蓍" },
			{ "meetoru", "米" }, { "megu", "匝" }, { "megu", "匯" }, { "megu", "圜" }, { "megu", "寵" }, { "megu", "巡" }, { "megu", "廻" }, { "megu", "徼" },
			{ "megu", "恤" }, { "megu", "恵" }, { "megu", "惠" }, { "megu", "愛" }, { "megu", "斡" }, { "megu", "紆" }, { "megu", "繚" }, { "megu", "繞" },
			{ "megu", "芽" }, { "megu", "輾" }, { "megu", "遶" }, { "megu", "邏" }, { "megumi", "恩" }, { "megumi", "愛" }, { "megumi", "慈" }, { "megumi", "潤" },
			{ "megumu", "萠" }, { "meguru", "流" }, { "mei", "冥" }, { "mei", "名" }, { "mei", "命" }, { "mei", "姪" }, { "mei", "明" }, { "mei", "暝" },
			{ "mei", "溟" }, { "mei", "盟" }, { "mei", "瞑" }, { "mei", "茗" }, { "mei", "螟" }, { "mei", "謎" }, { "mei", "迷" }, { "mei", "酩" }, { "mei", "銘" },
			{ "mei", "鳴" }, { "mekake", "妾" }, { "mekki", "鍍" }, { "meku", "捲" }, { "mekura", "盲" }, { "mekura", "瞎" }, { "mema", "眩" }, { "memai", "暈" },
			{ "meme", "爻" }, { "men", "俛" }, { "men", "免" }, { "men", "冕" }, { "men", "宀" }, { "men", "校" }, { "men", "棉" }, { "men", "毛" }, { "men", "泯" },
			{ "men", "湎" }, { "men", "牝" }, { "men", "眄" }, { "men", "瞑" }, { "men", "粫" }, { "men", "綿" }, { "men", "緜" }, { "men", "緬" }, { "men", "雌" },
			{ "men", "面" }, { "men", "麪" }, { "men", "麺" }, { "men", "黽" }, { "meoto", "娚" }, { "mesi", "瞽" }, { "mesi", "矇" }, { "mesi", "飯" },
			{ "mesu", "牝" }, { "mesu", "雌" }, { "meto", "娶" }, { "metu", "滅" }, { "meziri", "眥" }, { "meziri", "眦" }, { "mezura", "奇" }, { "mezura", "珍" },
			{ "mezura", "珎" }, { "mezura", "瑰" }, { "mezura", "竒" }, { "mi", "み" }, { "mi", "ミ" }, { "mi", "三" }, { "mi", "五" }, { "mi", "充" }, { "mi", "光" },
			{ "mi", "利" }, { "mi", "務" }, { "mi", "参" }, { "mi", "君" }, { "mi", "味" }, { "mi", "塞" }, { "mi", "妃" }, { "mi", "実" }, { "mi", "宮" },
			{ "mi", "實" }, { "mi", "寳" }, { "mi", "己" }, { "mi", "已" }, { "mi", "巳" }, { "mi", "弥" }, { "mi", "弭" }, { "mi", "彌" }, { "mi", "御" },
			{ "mi", "微" }, { "mi", "恵" }, { "mi", "明" }, { "mi", "望" }, { "mi", "未" }, { "mi", "果" }, { "mi", "桃" }, { "mi", "毅" }, { "mi", "民" },
			{ "mi", "水" }, { "mi", "江" }, { "mi", "海" }, { "mi", "深" }, { "mi", "湖" }, { "mi", "満" }, { "mi", "溢" }, { "mi", "滿" }, { "mi", "澄" },
			{ "mi", "瀰" }, { "mi", "爾" }, { "mi", "珠" }, { "mi", "生" }, { "mi", "男" }, { "mi", "皇" }, { "mi", "盈" }, { "mi", "省" }, { "mi", "眉" },
			{ "mi", "看" }, { "mi", "睥" }, { "mi", "睹" }, { "mi", "瞰" }, { "mi", "瞻" }, { "mi", "瞿" }, { "mi", "矚" }, { "mi", "神" }, { "mi", "稔" },
			{ "mi", "箕" }, { "mi", "純" }, { "mi", "縻" }, { "mi", "績" }, { "mi", "美" }, { "mi", "聖" }, { "mi", "胥" }, { "mi", "臣" }, { "mi", "臨" },
			{ "mi", "茉" }, { "mi", "薬" }, { "mi", "蛇" }, { "mi", "見" }, { "mi", "規" }, { "mi", "視" }, { "mi", "覧" }, { "mi", "覩" }, { "mi", "観" },
			{ "mi", "覽" }, { "mi", "觀" }, { "mi", "診" }, { "mi", "身" }, { "mi", "躬" }, { "mi", "農" }, { "mi", "造" }, { "mi", "銘" }, { "mi", "靡" },
			{ "mi", "顧" }, { "mi", "魅" }, { "mi", "麼" }, { "mi", "黴" }, { "mida", "乱" }, { "mida", "亂" }, { "mida", "妄" }, { "mida", "婬" }, { "mida", "撓" },
			{ "mida", "撹" }, { "mida", "擾" }, { "mida", "攪" }, { "mida", "淫" }, { "mida", "溷" }, { "mida", "濫" }, { "mida", "猥" }, { "mida", "紊" },
			{ "mida", "紜" }, { "midara", "姦" }, { "midare", "婬" }, { "midari", "淫" }, { "midari", "猥" }, { "midarini", "叨" }, { "midaru", "妛" },
			{ "midori", "碧" }, { "midori", "緑" }, { "midori", "翆" }, { "midori", "翠" }, { "midorigo", "嬰" }, { "miga", "琢" }, { "miga", "瑳" }, { "miga", "砥" },
			{ "miga", "砺" }, { "miga", "磋" }, { "miga", "磨" }, { "miga", "礪" }, { "migarini", "漫" }, { "migi", "右" }, { "migiri", "砌" }, { "migiwa", "汀" },
			{ "migomo", "妊" }, { "migomo", "姙" }, { "miha", "瞠" }, { "mihari", "哨" }, { "mika", "甕" }, { "mikado", "帝" }, { "mikaduki", "朏" }, { "miki", "寸" },
			{ "miki", "幹" }, { "miko", "巫" }, { "miko", "覡" }, { "mikoto", "尊" }, { "mikotonori", "勅" }, { "mikotonori", "敕" }, { "mikotonori", "詔" },
			{ "mima", "薨" }, { "mimami", "南" }, { "mimeyo", "娥" }, { "mimi", "耳" }, { "mimidama", "珥" }, { "mimiki", "馘" }, { "miminagusa", "苓" },
			{ "mimisii", "聾" }, { "mimizato", "聡" }, { "mimizato", "聰" }, { "mimizu", "蚓" }, { "mimizu", "蚯" }, { "min", "三" }, { "min", "岷" }, { "min", "愍" },
			{ "min", "憫" }, { "min", "旻" }, { "min", "明" }, { "min", "民" }, { "min", "水" }, { "min", "泯" }, { "min", "眠" }, { "min", "瞑" }, { "min", "緡" },
			{ "min", "罠" }, { "min", "閔" }, { "min", "黽" }, { "mina", "僉" }, { "mina", "凡" }, { "mina", "南" }, { "mina", "咸" }, { "mina", "水" },
			{ "mina", "汎" }, { "mina", "波" }, { "mina", "源" }, { "mina", "皆" }, { "mina", "胥" }, { "minagi", "漲" }, { "minagoro", "鏖" }, { "minami", "南" },
			{ "minami", "波" }, { "minamoto", "源" }, { "minato", "港" }, { "minato", "湊" }, { "mine", "岑" }, { "mine", "岫" }, { "mine", "峯" }, { "mine", "峰" },
			{ "mine", "崟" }, { "mine", "嶂" }, { "mine", "嶺" }, { "mine", "巒" }, { "miniku", "妛" }, { "miniku", "醜" }, { "minna", "皆" }, { "mino", "実" },
			{ "mino", "實" }, { "mino", "稔" }, { "mino", "箕" }, { "mino", "簑" }, { "mino", "簔" }, { "mino", "蓑" }, { "minori", "稔" }, { "minoru", "稔" },
			{ "minoru", "穣" }, { "minoru", "穰" }, { "minoru", "聡" }, { "minoru", "酉" }, { "mio", "澪" }, { "miri", "粍" }, { "miriguramu", "瓱" },
			{ "mirimeetoru", "粍" }, { "miririttoru", "竓" }, { "misa", "操" }, { "misa", "水" }, { "misago", "鶚" }, { "misaki", "埼" }, { "misaki", "岫" },
			{ "misaki", "岬" }, { "misaki", "崎" }, { "misaki", "嵜" }, { "misaki", "碕" }, { "misao", "操" }, { "misasagi", "陵" }, { "mise", "店" },
			{ "mise", "廛" }, { "mise", "肆" }, { "mise", "鋪" }, { "misogi", "禊" }, { "misoka", "晦" }, { "misona", "臠" }, { "misu", "簾" }, { "mit", "三" },
			{ "mitamaya", "寝" }, { "mitamaya", "寢" }, { "mitamaya", "廟" }, { "miti", "亨" }, { "miti", "享" }, { "miti", "倫" }, { "miti", "充" }, { "miti", "実" },
			{ "miti", "實" }, { "miti", "導" }, { "miti", "康" }, { "miti", "廸" }, { "miti", "往" }, { "miti", "徃" }, { "miti", "径" }, { "miti", "徑" },
			{ "miti", "慶" }, { "miti", "方" }, { "miti", "治" }, { "miti", "満" }, { "miti", "理" }, { "miti", "甼" }, { "miti", "真" }, { "miti", "至" },
			{ "miti", "芳" }, { "miti", "行" }, { "miti", "衢" }, { "miti", "路" }, { "miti", "蹊" }, { "miti", "迪" }, { "miti", "途" }, { "miti", "逕" },
			{ "miti", "通" }, { "miti", "道" }, { "miti", "達" }, { "miti", "闡" }, { "miti", "陌" }, { "miti", "陸" }, { "miti", "隧" }, { "mitibi", "導" },
			{ "mito", "認" }, { "mitu", "三" }, { "mitu", "允" }, { "mitu", "充" }, { "mitu", "光" }, { "mitu", "円" }, { "mitu", "参" }, { "mitu", "參" },
			{ "mitu", "密" }, { "mitu", "實" }, { "mitu", "弘" }, { "mitu", "弥" }, { "mitu", "慎" }, { "mitu", "晃" }, { "mitu", "樒" }, { "mitu", "櫁" },
			{ "mitu", "水" }, { "mitu", "満" }, { "mitu", "瑞" }, { "mitu", "盈" }, { "mitu", "舜" }, { "mitu", "苗" }, { "mitu", "蜜" }, { "mitu", "貢" },
			{ "mitu", "道" }, { "mitugu", "諠" }, { "miturou", "蝋" }, { "mituru", "暢" }, { "mituru", "満" }, { "miu", "苗" }, { "miuti", "戚" }, { "miya", "宮" },
			{ "miya", "都" }, { "miya", "雅" }, { "miyabiyaka", "嫺" }, { "miyabiyaka", "嫻" }, { "miyako", "京" }, { "miyako", "亰" }, { "miyako", "畿" },
			{ "miyako", "都" }, { "miyakogae", "遷" }, { "miyuki", "幸" }, { "mizi", "惨" }, { "mizi", "慘" }, { "mizika", "短" }, { "mizo", "洫" }, { "mizo", "涜" },
			{ "mizo", "渠" }, { "mizo", "溝" }, { "mizore", "霙" }, { "mizu", "水" }, { "mizu", "瑞" }, { "mizu", "端" }, { "mizugane", "汞" }, { "mizuka", "自" },
			{ "mizukaki", "蹼" }, { "mizumori", "凖" }, { "mizumori", "準" }, { "mizunoe", "壬" }, { "mizunoto", "癸" }, { "mizura", "髻" }, { "mizura", "鬟" },
			{ "mizutade", "薔" }, { "mizutamari", "潴" }, { "mizutamari", "瀦" }, { "mizuti", "蛟" }, { "mizuti", "鮫" }, { "mizuumi", "湖" }, { "mo", "も" },
			{ "mo", "モ" }, { "mo", "三" }, { "mo", "喪" }, { "mo", "妹" }, { "mo", "姆" }, { "mo", "姥" }, { "mo", "媽" }, { "mo", "守" }, { "mo", "持" },
			{ "mo", "捩" }, { "mo", "揉" }, { "mo", "摸" }, { "mo", "文" }, { "mo", "方" }, { "mo", "最" }, { "mo", "望" }, { "mo", "木" }, { "mo", "模" },
			{ "mo", "母" }, { "mo", "毛" }, { "mo", "泄" }, { "mo", "洩" }, { "mo", "添" }, { "mo", "溌" }, { "mo", "漏" }, { "mo", "燃" }, { "mo", "畆" },
			{ "mo", "畝" }, { "mo", "百" }, { "mo", "盛" }, { "mo", "真" }, { "mo", "糢" }, { "mo", "若" }, { "mo", "茂" }, { "mo", "莫" }, { "mo", "萌" },
			{ "mo", "萠" }, { "mo", "藻" }, { "mo", "裳" }, { "mo", "謨" }, { "mo", "輪" }, { "mo", "門" }, { "mo", "面" }, { "mo", "馬" }, { "mo", "麼" },
			{ "moda", "悶" }, { "moda", "懣" }, { "moda", "默" }, { "moda", "黙" }, { "modae", "悶" }, { "modo", "戻" }, { "modo", "擬" }, { "moe", "萌" },
			{ "moenokori", "燼" }, { "mogasa", "疱" }, { "mogu", "潛" }, { "mogu", "潜" }, { "mogu", "濳" }, { "mogusa", "艾" }, { "mokko", "畚" }, { "mokko", "簣" },
			{ "moku", "工" }, { "moku", "木" }, { "moku", "杢" }, { "moku", "沐" }, { "moku", "牧" }, { "moku", "目" }, { "moku", "睦" }, { "moku", "穆" },
			{ "moku", "苜" }, { "moku", "默" }, { "moku", "黙" }, { "momi", "樅" }, { "momi", "籾" }, { "momi", "粟" }, { "momi", "紅" }, { "momizi", "栴" },
			{ "momizi", "椛" }, { "momo", "李" }, { "momo", "桃" }, { "momo", "百" }, { "momo", "股" }, { "momo", "腿" }, { "momo", "髀" }, { "momu", "蟐" },
			{ "mon", "主" }, { "mon", "們" }, { "mon", "問" }, { "mon", "悶" }, { "mon", "懣" }, { "mon", "捫" }, { "mon", "文" }, { "mon", "瞞" }, { "mon", "紋" },
			{ "mon", "聞" }, { "mon", "郎" }, { "mon", "門" }, { "mon", "馼" }, { "mondo", "百" }, { "monme", "匁" }, { "mono", "桃" }, { "mono", "物" },
			{ "mono", "者" }, { "monoimi", "斎" }, { "monoimi", "齋" }, { "monoui", "嬾" }, { "monoui", "慵" }, { "monoui", "懶" }, { "monu", "蛻" },
			{ "moppa", "専" }, { "moppa", "專" }, { "moppara", "醇" }, { "mora", "貰" }, { "mori", "保" }, { "mori", "傅" }, { "mori", "守" }, { "mori", "晦" },
			{ "mori", "月" } };
};
