package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R7 {
	public static String[][] kl = { { "kamo", "醗" }, { "kamo", "醸" }, { "kamo", "釀" }, { "kamo", "鳧" }, { "kamo", "鳬" }, { "kamo", "鴨" }, { "kamome", "鴎" },
			{ "kamosika", "羚" }, { "kamozi", "髢" }, { "kamu", "齟" }, { "kamuro", "禿" }, { "kan", "上" }, { "kan", "丱" }, { "kan", "串" }, { "kan", "乾" },
			{ "kan", "亘" }, { "kan", "亙" }, { "kan", "侃" }, { "kan", "冠" }, { "kan", "凵" }, { "kan", "函" }, { "kan", "凾" }, { "kan", "刊" }, { "kan", "刋" },
			{ "kan", "勘" }, { "kan", "勧" }, { "kan", "勸" }, { "kan", "卷" }, { "kan", "厂" }, { "kan", "咸" }, { "kan", "啣" }, { "kan", "喊" }, { "kan", "喚" },
			{ "kan", "圜" }, { "kan", "坎" }, { "kan", "坩" }, { "kan", "堪" }, { "kan", "奐" }, { "kan", "奸" }, { "kan", "姜" }, { "kan", "姦" }, { "kan", "嫺" },
			{ "kan", "嫻" }, { "kan", "完" }, { "kan", "官" }, { "kan", "宦" }, { "kan", "寒" }, { "kan", "寛" }, { "kan", "寰" }, { "kan", "嵌" }, { "kan", "巻" },
			{ "kan", "干" }, { "kan", "幹" }, { "kan", "康" }, { "kan", "悍" }, { "kan", "患" }, { "kan", "愃" }, { "kan", "感" }, { "kan", "慣" }, { "kan", "慳" },
			{ "kan", "憾" }, { "kan", "懽" }, { "kan", "戡" }, { "kan", "扞" }, { "kan", "拑" }, { "kan", "捍" }, { "kan", "揀" }, { "kan", "換" }, { "kan", "撼" },
			{ "kan", "敢" }, { "kan", "斡" }, { "kan", "旱" }, { "kan", "杆" }, { "kan", "柑" }, { "kan", "柬" }, { "kan", "栞" }, { "kan", "桓" }, { "kan", "桿" },
			{ "kan", "棺" }, { "kan", "樌" }, { "kan", "樺" }, { "kan", "橄" }, { "kan", "檻" }, { "kan", "款" }, { "kan", "歉" }, { "kan", "歓" }, { "kan", "歡" },
			{ "kan", "汗" }, { "kan", "浣" }, { "kan", "涵" }, { "kan", "淦" }, { "kan", "渙" }, { "kan", "湛" }, { "kan", "湲" }, { "kan", "漢" }, { "kan", "潅" },
			{ "kan", "澗" }, { "kan", "澣" }, { "kan", "瀚" }, { "kan", "灌" }, { "kan", "煖" }, { "kan", "煥" }, { "kan", "燗" }, { "kan", "環" }, { "kan", "甘" },
			{ "kan", "甲" }, { "kan", "疳" }, { "kan", "癇" }, { "kan", "皖" }, { "kan", "監" }, { "kan", "盥" }, { "kan", "看" }, { "kan", "眩" }, { "kan", "瞰" },
			{ "kan", "神" }, { "kan", "稈" }, { "kan", "竿" }, { "kan", "箝" }, { "kan", "管" }, { "kan", "篏" }, { "kan", "簡" }, { "kan", "綸" }, { "kan", "緘" },
			{ "kan", "緩" }, { "kan", "繝" }, { "kan", "缶" }, { "kan", "罐" }, { "kan", "罕" }, { "kan", "羮" }, { "kan", "羹" }, { "kan", "翰" }, { "kan", "肝" },
			{ "kan", "舘" }, { "kan", "艦" }, { "kan", "艱" }, { "kan", "苅" }, { "kan", "莞" }, { "kan", "莟" }, { "kan", "菅" }, { "kan", "蒄" }, { "kan", "蚶" },
			{ "kan", "観" }, { "kan", "觀" }, { "kan", "諌" }, { "kan", "諫" }, { "kan", "讙" }, { "kan", "豢" }, { "kan", "貫" }, { "kan", "轗" }, { "kan", "遑" },
			{ "kan", "還" }, { "kan", "邯" }, { "kan", "酣" }, { "kan", "金" }, { "kan", "鉗" }, { "kan", "銜" }, { "kan", "鐶" }, { "kan", "鑑" }, { "kan", "鑒" },
			{ "kan", "鑵" }, { "kan", "閑" }, { "kan", "間" }, { "kan", "関" }, { "kan", "關" }, { "kan", "陥" }, { "kan", "陷" }, { "kan", "韓" }, { "kan", "頷" },
			{ "kan", "顴" }, { "kan", "餡" }, { "kan", "館" }, { "kan", "駻" }, { "kan", "驩" }, { "kan", "骭" }, { "kan", "鬟" }, { "kan", "鰔" }, { "kan", "鰥" },
			{ "kan", "鸛" }, { "kan", "鹸" }, { "kan", "鹹" }, { "kan", "鼾" }, { "kan", "龕" }, { "kana", "乎" }, { "kana", "叶" }, { "kana", "哀" }, { "kana", "哉" },
			{ "kana", "奏" }, { "kana", "恊" }, { "kana", "悲" }, { "kana", "愛" }, { "kana", "敵" }, { "kana", "神" }, { "kana", "称" }, { "kana", "稱" },
			{ "kana", "縢" }, { "kana", "諧" }, { "kana", "適" }, { "kana", "金" }, { "kana", "銀" }, { "kanae", "中" }, { "kanae", "鬲" }, { "kanae", "鼎" },
			{ "kanamari", "鋺" }, { "kaname", "要" }, { "kanara", "必" }, { "kanba", "樺" }, { "kanba", "芳" }, { "kane", "兼" }, { "kane", "包" }, { "kane", "懐" },
			{ "kane", "摂" }, { "kane", "攝" }, { "kane", "矩" }, { "kane", "謙" }, { "kane", "金" }, { "kane", "釛" }, { "kane", "鉦" }, { "kane", "銀" },
			{ "kane", "錦" }, { "kane", "鍾" }, { "kane", "鎌" }, { "kane", "鐘" }, { "kanegura", "帑" }, { "kanezasi", "矩" }, { "kanga", "攷" }, { "kanga", "稽" },
			{ "kanga", "考" }, { "kanga", "鑑" }, { "kanga", "鑒" }, { "kani", "蟹" }, { "kani", "蠏" }, { "kanmuri", "冕" }, { "kanmuri", "冠" }, { "kanna", "鉋" },
			{ "kannagi", "巫" }, { "kannagi", "覡" }, { "kannohaha", "毋" }, { "kannuki", "閂" }, { "kannuki", "関" }, { "kannuki", "關" }, { "kannyou", "凵" },
			{ "kano", "叶" }, { "kano", "彼" }, { "kanoe", "庚" }, { "kanohoko", "戈" }, { "kanoko", "麑" }, { "kanoto", "辛" }, { "kanou", "叶" },
			{ "kanzasi", "簪" }, { "kanzasi", "釵" }, { "kanzasi", "鈿" }, { "kanziki", "橇" }, { "kanzou", "萱" }, { "kao", "薫" }, { "kao", "顏" }, { "kao", "顔" },
			{ "kao", "香" }, { "kao", "馥" }, { "kao", "馨" }, { "kaori", "芬" }, { "kaori", "薫" }, { "kaori", "馨" }, { "kaorigusa", "鬯" }, { "kaoru", "彪" },
			{ "kaoru", "芳" }, { "kaoru", "薫" }, { "kaoru", "郁" }, { "kaoru", "馨" }, { "kappu", "冠" }, { "kara", "唐" }, { "kara", "搦" }, { "kara", "方" },
			{ "kara", "柄" }, { "kara", "樺" }, { "kara", "殻" }, { "kara", "殼" }, { "kara", "空" }, { "kara", "絡" }, { "kara", "縢" }, { "kara", "辛" },
			{ "kara", "辣" }, { "kara", "韓" }, { "kara", "鹹" }, { "karada", "体" }, { "karada", "躯" }, { "karada", "躰" }, { "karada", "軆" }, { "karada", "體" },
			{ "karageru", "紮" }, { "karai", "苛" }, { "karaka", "揶" }, { "karakuri", "枢" }, { "karakuri", "樞" }, { "karakuri", "関" }, { "karakuri", "關" },
			{ "karamusi", "苧" }, { "karanasi", "奈" }, { "karansi", "苧" }, { "karasi", "芥" }, { "karasu", "烏" }, { "karasu", "鴉" }, { "karatati", "枳" },
			{ "karazao", "枷" }, { "kare", "伊" }, { "kare", "儂" }, { "kare", "彼" }, { "kare", "渠" }, { "karei", "餉" }, { "karei", "鰈" }, { "karei", "鰔" },
			{ "kari", "仮" }, { "kari", "假" }, { "kari", "刈" }, { "kari", "権" }, { "kari", "權" }, { "kari", "滑" }, { "kari", "狩" }, { "kari", "猟" },
			{ "kari", "獵" }, { "kari", "甸" }, { "kari", "畋" }, { "kari", "苅" }, { "kari", "藉" }, { "kari", "雁" }, { "kari", "鳫" }, { "kari", "鴈" },
			{ "karigane", "厂" }, { "karigane", "雁" }, { "karigane", "鳫" }, { "karigane", "鴈" }, { "karimogari", "殯" }, { "karizumai", "寓" }, { "karo", "唐" },
			{ "karo", "藐" }, { "karo", "軽" }, { "karo", "輕" }, { "karu", "佻" }, { "karu", "剤" }, { "karu", "劑" }, { "karu", "嫖" }, { "karu", "苅" },
			{ "karu", "軽" }, { "karu", "輕" }, { "kasa", "傘" }, { "kasa", "套" }, { "kasa", "嵩" }, { "kasa", "暈" }, { "kasa", "畳" }, { "kasa", "疂" },
			{ "kasa", "疉" }, { "kasa", "疊" }, { "kasa", "疽" }, { "kasa", "痂" }, { "kasa", "痒" }, { "kasa", "瘍" }, { "kasa", "瘡" }, { "kasa", "瘻" },
			{ "kasa", "盖" }, { "kasa", "笠" }, { "kasa", "葢" }, { "kasa", "蓋" }, { "kasa", "襲" }, { "kasa", "重" }, { "kasane", "褶" }, { "kasasagi", "鵲" },
			{ "kase", "枷" }, { "kase", "械" }, { "kase", "稼" }, { "kase", "綛" }, { "kasi", "傾" }, { "kasi", "柏" }, { "kasi", "槝" }, { "kasi", "樫" },
			{ "kasi", "橿" }, { "kasi", "爨" }, { "kasi", "貸" }, { "kasiko", "俐" }, { "kasiko", "畏" }, { "kasiko", "賢" }, { "kasima", "囂" }, { "kasima", "姦" },
			{ "kasira", "仟" }, { "kasira", "孟" }, { "kasira", "頁" }, { "kasira", "頭" }, { "kasira", "顱" }, { "kasira", "魁" }, { "kasiwa", "怕" },
			{ "kasiwa", "柏" }, { "kasiwa", "栢" }, { "kasiwa", "槲" }, { "kasiwa", "膳" }, { "kasizu", "傅" }, { "kasizuku", "俾" }, { "kasu", "微" },
			{ "kasu", "掠" }, { "kasu", "春" }, { "kasu", "粕" }, { "kasu", "糟" }, { "kasu", "霞" }, { "kasugai", "鎹" }, { "kasui", "鷆" }, { "kasui", "鷏" },
			{ "kasumi", "霞" }, { "kasuri", "絣" }, { "kasuri", "綛" }, { "kasuri", "緕" }, { "kasuri", "纃" }, { "kata", "交" }, { "kata", "傾" }, { "kata", "像" },
			{ "kata", "剛" }, { "kata", "固" }, { "kata", "型" }, { "kata", "堅" }, { "kata", "塙" }, { "kata", "容" }, { "kata", "形" }, { "kata", "方" },
			{ "kata", "淵" }, { "kata", "渊" }, { "kata", "渕" }, { "kata", "潟" }, { "kata", "片" }, { "kata", "牢" }, { "kata", "硬" }, { "kata", "糢" },
			{ "kata", "肩" }, { "kata", "艱" }, { "kata", "語" }, { "kata", "議" }, { "kata", "賢" }, { "kata", "鎌" }, { "kata", "難" }, { "kata", "騙" },
			{ "katabu", "傾" }, { "katado", "象" }, { "katadoru", "皃" }, { "katadoru", "貌" }, { "katagata", "旁" }, { "katai", "鞏" }, { "kataki", "仇" },
			{ "kataki", "敵" }, { "kataku", "頑" }, { "katamari", "団" }, { "katamari", "團" }, { "katamari", "塊" }, { "katame", "瞎" }, { "katami", "互" },
			{ "katami", "匪" }, { "katami", "筐" }, { "katami", "筺" }, { "katamu", "仄" }, { "katamu", "傾" }, { "katamu", "昃" }, { "katana", "刀" },
			{ "katana", "釖" }, { "katanu", "袒" }, { "katasiro", "尸" }, { "katati", "体" }, { "katati", "形" }, { "katati", "皃" }, { "katati", "貌" },
			{ "katati", "躰" }, { "katati", "軆" }, { "katati", "頌" }, { "katati", "體" }, { "katatumuri", "蝸" }, { "katawa", "傍" }, { "katawara", "旁" },
			{ "katayo", "偏" }, { "katayo", "頗" }, { "katazikena", "忝" }, { "kate", "粮" }, { "kate", "糧" }, { "kati", "勝" }, { "kati", "徒" }, { "kati", "葛" },
			{ "katidoki", "凱" }, { "katu", "一" }, { "katu", "且" }, { "katu", "健" }, { "katu", "克" }, { "katu", "刮" }, { "katu", "剋" }, { "katu", "割" },
			{ "katu", "功" }, { "katu", "劼" }, { "katu", "勝" }, { "katu", "和" }, { "katu", "喝" }, { "katu", "嘗" }, { "katu", "尅" }, { "katu", "将" },
			{ "katu", "巧" }, { "katu", "戛" }, { "katu", "戞" }, { "katu", "戡" }, { "katu", "担" }, { "katu", "括" }, { "katu", "拮" }, { "katu", "捷" },
			{ "katu", "揩" }, { "katu", "擔" }, { "katu", "曷" }, { "katu", "曽" }, { "katu", "曾" }, { "katu", "桂" }, { "katu", "歇" }, { "katu", "活" },
			{ "katu", "渇" }, { "katu", "滑" }, { "katu", "濶" }, { "katu", "猾" }, { "katu", "甞" }, { "katu", "瞎" }, { "katu", "磆" }, { "katu", "禊" },
			{ "katu", "筈" }, { "katu", "羯" }, { "katu", "聒" }, { "katu", "葛" }, { "katu", "蛞" }, { "katu", "蝎" }, { "katu", "蠍" }, { "katu", "褐" },
			{ "katu", "豁" }, { "katu", "轄" }, { "katu", "達" }, { "katu", "闊" }, { "katu", "雄" }, { "katu", "鞨" }, { "katu", "頡" }, { "katu", "鶻" },
			{ "katu", "黠" }, { "katuo", "鰹" }, { "katura", "桂" }, { "katura", "葛" }, { "katura", "蘰" }, { "katura", "鬘" }, { "katuri", "和" },
			{ "katuri", "将" }, { "katute", "曽" }, { "kau", "耗" }, { "kawa", "乾" }, { "kawa", "交" }, { "kawa", "代" }, { "kawa", "側" }, { "kawa", "巛" },
			{ "kawa", "川" }, { "kawa", "晞" }, { "kawa", "楊" }, { "kawa", "河" }, { "kawa", "渇" }, { "kawa", "渝" }, { "kawa", "煕" }, { "kawa", "熈" },
			{ "kawa", "熙" }, { "kawa", "獺" }, { "kawa", "皮" }, { "kawa", "躱" }, { "kawa", "逓" }, { "kawa", "遞" }, { "kawa", "銷" }, { "kawa", "革" },
			{ "kawagoromo", "裘" }, { "kawagutu", "鞨" }, { "kawara", "瓦" }, { "kawara", "甎" }, { "kawara", "甓" }, { "kawara", "磚" }, { "kawara", "磧" },
			{ "kawarage", "駱" }, { "kawasemi", "翆" }, { "kawasemi", "翠" }, { "kawauso", "獺" }, { "kawaya", "厠" }, { "kawaya", "廁" }, { "kawaya", "溷" },
			{ "kawazu", "蛙" }, { "kaya", "栢" }, { "kaya", "榧" }, { "kaya", "茅" }, { "kaya", "茆" }, { "kaya", "茨" }, { "kaya", "萱" }, { "kayo", "通" },
			{ "kayowa", "孅" }, { "kayu", "痒" }, { "kayu", "癢" }, { "kayu", "粥" }, { "kayu", "餬" }, { "kayu", "鬻" }, { "kaza", "翳" }, { "kaza", "風" },
			{ "kaza", "飾" }, { "kaza", "餝" }, { "kazari", "文" }, { "kazari", "錺" }, { "kazari", "餝" }, { "kazasi", "釵" }, { "kaze", "風" }, { "kazi", "囓" },
			{ "kazi", "柁" }, { "kazi", "梶" }, { "kazi", "楫" }, { "kazi", "榜" }, { "kazi", "橈" }, { "kazi", "櫂" }, { "kazi", "舵" }, { "kazi", "齧" },
			{ "kazika", "鮖" }, { "kazika", "鰍" }, { "kazo", "数" }, { "kazo", "數" }, { "kazu", "一" }, { "kazu", "万" }, { "kazu", "上" }, { "kazu", "主" },
			{ "kazu", "千" }, { "kazu", "和" }, { "kazu", "員" }, { "kazu", "嘉" }, { "kazu", "壱" }, { "kazu", "壽" }, { "kazu", "宗" }, { "kazu", "寿" },
			{ "kazu", "憲" }, { "kazu", "数" }, { "kazu", "數" }, { "kazu", "昭" }, { "kazu", "胤" }, { "kazu", "萬" }, { "kazu", "葛" }, { "kazu", "計" },
			{ "kazu", "量" }, { "kazumi", "昭" }, { "kazunoko", "鯑" }, { "kazura", "葛" }, { "kazura", "鬘" }, { "kazutori", "籌" }, { "kazutori", "籖" },
			{ "kazutori", "籤" }, { "ke", "け" }, { "ke", "ケ" }, { "ke", "亟" }, { "ke", "仮" }, { "ke", "価" }, { "ke", "假" }, { "ke", "價" }, { "ke", "化" },
			{ "ke", "卉" }, { "ke", "卦" }, { "ke", "咼" }, { "ke", "嘩" }, { "ke", "圭" }, { "ke", "塊" }, { "ke", "外" }, { "ke", "子" }, { "ke", "宅" },
			{ "ke", "家" }, { "ke", "希" }, { "ke", "廨" }, { "ke", "怪" }, { "ke", "恠" }, { "ke", "恢" }, { "ke", "恵" }, { "ke", "愾" }, { "ke", "慶" },
			{ "ke", "懈" }, { "ke", "懸" }, { "ke", "挂" }, { "ke", "敬" }, { "ke", "旡" }, { "ke", "明" }, { "ke", "毛" }, { "ke", "气" }, { "ke", "気" },
			{ "ke", "氣" }, { "ke", "消" }, { "ke", "瓜" }, { "ke", "異" }, { "ke", "痂" }, { "ke", "祁" }, { "ke", "稀" }, { "ke", "笥" }, { "ke", "罅" },
			{ "ke", "罫" }, { "ke", "膾" }, { "ke", "芥" }, { "ke", "花" }, { "ke", "華" }, { "ke", "葵" }, { "ke", "薊" }, { "ke", "袈" }, { "ke", "褂" },
			{ "ke", "襾" }, { "ke", "計" }, { "ke", "譁" }, { "ke", "蹴" }, { "ke", "迦" }, { "ke", "銷" }, { "ke", "閨" }, { "ke", "餉" }, { "ke", "鱠" },
			{ "keba", "毳" }, { "keda", "盖" }, { "keda", "葢" }, { "keda", "蓋" }, { "kedamono", "獣" }, { "kedamono", "獸" }, { "kega", "汚" }, { "kega", "涜" },
			{ "kega", "溷" }, { "kega", "穢" }, { "kega", "褻" }, { "kega", "黷" }, { "kegawa", "皮" }, { "kei", "京" }, { "kei", "亰" }, { "kei", "佳" },
			{ "kei", "係" }, { "kei", "偈" }, { "kei", "傾" }, { "kei", "兄" }, { "kei", "兮" }, { "kei", "冂" }, { "kei", "冏" }, { "kei", "刑" }, { "kei", "剄" },
			{ "kei", "勁" }, { "kei", "勍" }, { "kei", "匸" }, { "kei", "卿" }, { "kei", "哇" }, { "kei", "啓" }, { "kei", "圭" }, { "kei", "型" }, { "kei", "境" },
			{ "kei", "夐" }, { "kei", "奎" }, { "kei", "契" }, { "kei", "奚" }, { "kei", "彑" }, { "kei", "彗" }, { "kei", "形" }, { "kei", "径" }, { "kei", "徑" },
			{ "kei", "恵" }, { "kei", "惠" }, { "kei", "慧" }, { "kei", "慶" }, { "kei", "憇" }, { "kei", "憩" }, { "kei", "憬" }, { "kei", "挂" }, { "kei", "挈" },
			{ "kei", "掛" }, { "kei", "掲" }, { "kei", "携" }, { "kei", "攜" }, { "kei", "敬" }, { "kei", "景" }, { "kei", "枅" }, { "kei", "桂" }, { "kei", "檠" },
			{ "kei", "渓" }, { "kei", "溪" }, { "kei", "炯" }, { "kei", "烱" }, { "kei", "煢" }, { "kei", "珪" }, { "kei", "瓊" }, { "kei", "畦" }, { "kei", "痙" },
			{ "kei", "盻" }, { "kei", "眤" }, { "kei", "矜" }, { "kei", "硅" }, { "kei", "磬" }, { "kei", "禊" }, { "kei", "稽" }, { "kei", "竟" }, { "kei", "競" },
			{ "kei", "竸" }, { "kei", "笄" }, { "kei", "系" }, { "kei", "絅" }, { "kei", "経" }, { "kei", "經" }, { "kei", "継" }, { "kei", "綮" }, { "kei", "繋" },
			{ "kei", "繼" }, { "kei", "罫" }, { "kei", "脛" }, { "kei", "茎" }, { "kei", "荊" }, { "kei", "莖" }, { "kei", "薊" }, { "kei", "蛍" }, { "kei", "螢" },
			{ "kei", "袿" }, { "kei", "褂" }, { "kei", "計" }, { "kei", "詣" }, { "kei", "謦" }, { "kei", "警" }, { "kei", "谿" }, { "kei", "蹊" }, { "kei", "蹶" },
			{ "kei", "軽" }, { "kei", "輕" }, { "kei", "迥" }, { "kei", "逕" }, { "kei", "醯" }, { "kei", "鏡" }, { "kei", "閠" }, { "kei", "閨" }, { "kei", "頃" },
			{ "kei", "頚" }, { "kei", "頸" }, { "kei", "馨" }, { "kei", "髻" }, { "kei", "鮭" }, { "kei", "鴃" }, { "kei", "鶏" }, { "kei", "鷄" }, { "kei", "黥" },
			{ "keigamae", "冂" }, { "keigasira", "彑" }, { "keki", "屐" }, { "keki", "檄" }, { "keki", "覡" }, { "keki", "郤" }, { "keki", "闃" }, { "keki", "隙" },
			{ "keki", "鬩" }, { "keki", "鴃" }, { "keki", "鵙" }, { "kemi", "閲" }, { "kemono", "獣" }, { "kemono", "獸" }, { "kemu", "烟" }, { "kemu", "煙" },
			{ "kemudasi", "窓" }, { "kemudasi", "窗" }, { "kemuri", "烟" }, { "kemuri", "煙" }, { "ken", "丱" }, { "ken", "串" }, { "ken", "乾" }, { "ken", "件" },
			{ "ken", "俔" }, { "ken", "倦" }, { "ken", "倹" }, { "ken", "健" }, { "ken", "儉" }, { "ken", "兼" }, { "ken", "券" }, { "ken", "剣" }, { "ken", "剱" },
			{ "ken", "劍" }, { "ken", "劒" }, { "ken", "劔" }, { "ken", "劵" }, { "ken", "勧" }, { "ken", "勸" }, { "ken", "卷" }, { "ken", "喧" }, { "ken", "圈" },
			{ "ken", "圏" }, { "ken", "堅" }, { "ken", "夐" }, { "ken", "妍" }, { "ken", "姦" }, { "ken", "娟" }, { "ken", "嫌" }, { "ken", "嶮" }, { "ken", "巻" },
			{ "ken", "建" }, { "ken", "悁" }, { "ken", "惓" }, { "ken", "愃" }, { "ken", "愆" }, { "ken", "慊" }, { "ken", "慳" }, { "ken", "憲" }, { "ken", "懸" },
			{ "ken", "拑" }, { "ken", "拳" }, { "ken", "捲" }, { "ken", "掀" }, { "ken", "揀" }, { "ken", "搴" }, { "ken", "暄" }, { "ken", "柬" }, { "ken", "検" },
			{ "ken", "椦" }, { "ken", "権" }, { "ken", "檢" }, { "ken", "權" }, { "ken", "欠" }, { "ken", "歉" }, { "ken", "涓" }, { "ken", "澗" }, { "ken", "煖" },
			{ "ken", "牽" }, { "ken", "犬" }, { "ken", "狷" }, { "ken", "狽" }, { "ken", "献" }, { "ken", "獻" }, { "ken", "玄" }, { "ken", "甄" }, { "ken", "痃" },
			{ "ken", "監" }, { "ken", "県" }, { "ken", "眷" }, { "ken", "瞼" }, { "ken", "研" }, { "ken", "硯" }, { "ken", "筧" }, { "ken", "箝" }, { "ken", "絢" },
			{ "ken", "絹" }, { "ken", "綣" }, { "ken", "縣" }, { "ken", "繝" }, { "ken", "繭" }, { "ken", "缺" }, { "ken", "羂" }, { "ken", "肩" }, { "ken", "腱" },
			{ "ken", "臉" }, { "ken", "艱" }, { "ken", "菅" }, { "ken", "萱" }, { "ken", "蒹" }, { "ken", "虔" }, { "ken", "蛯" }, { "ken", "蜆" }, { "ken", "蜷" },
			{ "ken", "衒" }, { "ken", "見" }, { "ken", "諠" }, { "ken", "謇" }, { "ken", "謙" }, { "ken", "譴" }, { "ken", "讙" }, { "ken", "豢" }, { "ken", "賢" },
			{ "ken", "蹇" }, { "ken", "軒" }, { "ken", "遣" }, { "ken", "釼" }, { "ken", "鉄" }, { "ken", "鉉" }, { "ken", "鉗" }, { "ken", "鍵" }, { "ken", "鎌" },
			{ "ken", "間" }, { "ken", "険" }, { "ken", "險" }, { "ken", "顕" }, { "ken", "顯" }, { "ken", "顴" }, { "ken", "験" }, { "ken", "騫" }, { "ken", "驗" },
			{ "ken", "鰹" }, { "ken", "鵑" }, { "ken", "鹸" }, { "ken", "黔" }, { "kena", "穴" }, { "kenu", "鑷" }, { "kenuki", "鑷" }, { "kera", "螻" },
			{ "keri", "鳧" }, { "keri", "鳬" }, { "kesa", "畩" }, { "kesi", "岸" }, { "kesika", "嗾" }, { "keta", "桁" }, { "keti", "决" }, { "keti", "劼" },
			{ "keti", "夬" }, { "keti", "結" }, { "keti", "纈" }, { "keti", "頡" }, { "ketu", "亅" }, { "ketu", "偈" }, { "ketu", "傑" }, { "ketu", "决" },
			{ "ketu", "刔" }, { "ketu", "厥" }, { "ketu", "囓" }, { "ketu", "夬" }, { "ketu", "孑" }, { "ketu", "抉" } };
};
