package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R19 {
	public static String[][] kl = { { "tuduki", "仲" }, { "tuduki", "續" }, { "tudumayaka", "倹" }, { "tudumayaka", "儉" }, { "tudumi", "皷" }, { "tudumi", "鼓" },
			{ "tudura", "葛" }, { "tuduri", "綴" }, { "tue", "仗" }, { "tue", "杖" }, { "tue", "枴" }, { "tue", "梃" }, { "tue", "棍" }, { "tuga", "栂" },
			{ "tuga", "樛" }, { "tuga", "番" }, { "tuge", "柘" }, { "tugi", "亜" }, { "tugi", "嗣" }, { "tugi", "族" }, { "tugi", "次" }, { "tugi", "胤" },
			{ "tugi", "調" }, { "tugomori", "晦" }, { "tugu", "二" }, { "tugu", "亜" }, { "tugu", "嗣" }, { "tugu", "噤" }, { "tugu", "尋" }, { "tugu", "序" },
			{ "tugu", "承" }, { "tugu", "拑" }, { "tugu", "次" }, { "tugu", "紹" }, { "tugu", "続" }, { "tugu", "維" }, { "tugu", "續" }, { "tugu", "胤" },
			{ "tugu", "鉗" }, { "tugu", "韶" }, { "tugu", "頌" }, { "tugumi", "鶇" }, { "tugumi", "鶫" }, { "tuguna", "償" }, { "tui", "叙" }, { "tui", "堆" },
			{ "tui", "墜" }, { "tui", "対" }, { "tui", "對" }, { "tui", "序" }, { "tui", "敍" }, { "tui", "敘" }, { "tui", "椎" }, { "tui", "槌" }, { "tui", "潰" },
			{ "tui", "立" }, { "tui", "築" }, { "tui", "終" }, { "tui", "縋" }, { "tui", "費" }, { "tui", "追" }, { "tui", "遂" }, { "tui", "鎚" }, { "tui", "隧" },
			{ "tuiba", "啄" }, { "tuiba", "喋" }, { "tuide", "叙" }, { "tuide", "序" }, { "tuide", "敍" }, { "tuide", "敘" }, { "tuini", "卆" }, { "tuini", "卒" },
			{ "tuini", "竟" }, { "tuini", "訖" }, { "tuitati", "朔" }, { "tuka", "亊" }, { "tuka", "事" }, { "tuka", "仕" }, { "tuka", "使" }, { "tuka", "倦" },
			{ "tuka", "冢" }, { "tuka", "劬" }, { "tuka", "労" }, { "tuka", "勞" }, { "tuka", "司" }, { "tuka", "埠" }, { "tuka", "塚" }, { "tuka", "壟" },
			{ "tuka", "家" }, { "tuka", "尽" }, { "tuka", "憊" }, { "tuka", "憑" }, { "tuka", "拏" }, { "tuka", "拿" }, { "tuka", "捕" }, { "tuka", "掴" },
			{ "tuka", "攫" }, { "tuka", "支" }, { "tuka", "束" }, { "tuka", "杷" }, { "tuka", "柄" }, { "tuka", "疲" }, { "tuka", "瘁" }, { "tuka", "発" },
			{ "tuka", "發" }, { "tuka", "羸" }, { "tuka", "遣" }, { "tuka", "閊" }, { "tukae", "痞" }, { "tukai", "徭" }, { "tukasa", "務" }, { "tukasa", "台" },
			{ "tukasa", "司" }, { "tukasa", "嗣" }, { "tukasa", "宦" }, { "tukasa", "曹" }, { "tukasa", "臺" }, { "tukasado", "司" }, { "tuke", "付" },
			{ "tuke", "野" }, { "tuki", "付" }, { "tuki", "坏" }, { "tuki", "女" }, { "tuki", "尽" }, { "tuki", "属" }, { "tuki", "月" }, { "tuki", "槻" },
			{ "tuki", "欟" }, { "tuki", "殄" }, { "tuki", "殫" }, { "tuki", "築" }, { "tuku", "作" }, { "tuku", "做" }, { "tuku", "傅" }, { "tuku", "創" },
			{ "tuku", "啄" }, { "tuku", "土" }, { "tuku", "属" }, { "tuku", "屬" }, { "tuku", "捏" }, { "tuku", "殄" }, { "tuku", "殱" }, { "tuku", "殲" },
			{ "tuku", "為" }, { "tuku", "爲" }, { "tuku", "竭" }, { "tuku", "筑" }, { "tuku", "築" }, { "tuku", "造" }, { "tuku", "鏗" }, { "tukuba", "蹲" },
			{ "tukuda", "佃" }, { "tukue", "几" }, { "tukue", "机" }, { "tukue", "案" }, { "tukuri", "旁" }, { "tukuro", "繕" }, { "tuma", "倹" }, { "tuma", "儉" },
			{ "tuma", "妻" }, { "tuma", "嬬" }, { "tuma", "抓" }, { "tuma", "撮" }, { "tuma", "最" }, { "tuma", "爪" }, { "tuma", "褄" }, { "tumabasa", "襭" },
			{ "tumabi", "審" }, { "tumabi", "詳" }, { "tumabiraka", "諦" }, { "tumada", "翹" }, { "tumada", "跂" }, { "tumako", "孥" }, { "tumami", "鈕" },
			{ "tumazu", "跌" }, { "tumazu", "蹉" }, { "tumazu", "蹶" }, { "tumazu", "躓" }, { "tumazu", "頓" }, { "tume", "冷" }, { "tume", "爪" }, { "tumi", "積" },
			{ "tumi", "罪" }, { "tumi", "辜" }, { "tumo", "妬" }, { "tumu", "勣" }, { "tumu", "摘" }, { "tumu", "瞑" }, { "tumu", "紡" }, { "tumu", "紬" },
			{ "tumu", "緝" }, { "tumu", "錘" }, { "tumugi", "紬" }, { "tumuri", "頭" }, { "tumuzikaze", "飃" }, { "tumuzikaze", "飄" }, { "tumuzikaze", "飆" },
			{ "tuna", "之" }, { "tuna", "婁" }, { "tuna", "紘" }, { "tuna", "絆" }, { "tuna", "綱" }, { "tuna", "緤" }, { "tuna", "繋" }, { "tuna", "羇" },
			{ "tuna", "羈" }, { "tuna", "覊" }, { "tunagu", "紘" }, { "tunbo", "聾" }, { "tune", "典" }, { "tune", "常" }, { "tune", "庸" }, { "tune", "彜" },
			{ "tune", "彝" }, { "tune", "恆" }, { "tune", "恒" }, { "tune", "抓" }, { "tune", "毎" }, { "tune", "矩" }, { "tune", "経" }, { "tune", "經" },
			{ "tuneni", "恒" }, { "tuno", "募" }, { "tuno", "角" }, { "tunza", "劈" }, { "tura", "緜" }, { "tura", "聨" }, { "tura", "聯" }, { "tura", "肆" },
			{ "tura", "貫" }, { "tura", "辛" }, { "tura", "連" }, { "tura", "面" }, { "turanu", "串" }, { "turanu", "貫" }, { "turanuku", "琲" }, { "turatura", "倩" },
			{ "ture", "連" }, { "turea", "対" }, { "turea", "對" }, { "turea", "逑" }, { "tureai", "仇" }, { "tureai", "儷" }, { "turi", "釣" }, { "turiito", "緡" },
			{ "turu", "吊" }, { "turu", "寉" }, { "turu", "弦" }, { "turu", "敦" }, { "turu", "蔓" }, { "turu", "霍" }, { "turu", "鶴" }, { "turugi", "剣" },
			{ "turugi", "剱" }, { "turugi", "劍" }, { "turugi", "劒" }, { "turugi", "劔" }, { "turugi", "釼" }, { "turugi", "鋏" }, { "tusa", "橲" }, { "tusi", "対" },
			{ "tusi", "對" }, { "tuta", "伝" }, { "tuta", "傳" }, { "tuta", "樢" }, { "tuta", "蔦" }, { "tuta", "蘿" }, { "tutae", "伝" }, { "tutana", "拙" },
			{ "tute", "伝" }, { "tute", "傳" }, { "tuti", "土" }, { "tuti", "坤" }, { "tuti", "壌" }, { "tuti", "壤" }, { "tuti", "椎" }, { "tuti", "槌" },
			{ "tuti", "鎚" }, { "tutihuru", "霾" }, { "tutika", "培" }, { "tutikure", "塊" }, { "tutinoe", "戊" }, { "tutinoto", "己" }, { "tuto", "努" },
			{ "tuto", "劭" }, { "tuto", "勉" }, { "tuto", "勗" }, { "tuto", "務" }, { "tuto", "勤" }, { "tuto", "孜" }, { "tuto", "懋" }, { "tuto", "苞" },
			{ "tuto", "苴" }, { "tuto", "黽" }, { "tutomu", "力" }, { "tutomu", "功" }, { "tutomu", "孟" }, { "tutomu", "惇" }, { "tutomu", "茂" }, { "tutoni", "夙" },
			{ "tutu", "兢" }, { "tutu", "勹" }, { "tutu", "包" }, { "tutu", "啄" }, { "tutu", "坡" }, { "tutu", "筒" }, { "tutu", "裹" }, { "tutu", "韜" },
			{ "tutuga", "恙" }, { "tutumi", "堤" }, { "tutumi", "塘" }, { "tutumi", "陂" }, { "tutumigamae", "勹" }, { "tutusi", "恪" }, { "tutusi", "愨" },
			{ "tutusi", "愼" }, { "tutusi", "愿" }, { "tutusi", "慎" }, { "tutusi", "斎" }, { "tutusi", "欽" }, { "tutusi", "矜" }, { "tutusi", "祗" },
			{ "tutusi", "竦" }, { "tutusi", "粛" }, { "tutusi", "肅" }, { "tutusi", "虔" }, { "tutusi", "謹" }, { "tutusi", "齋" }, { "tuu", "痛" }, { "tuu", "通" },
			{ "tuwamono", "仗" }, { "tuwamono", "兵" }, { "tuwamono", "戎" }, { "tuya", "彩" }, { "tuya", "沢" }, { "tuya", "澤" }, { "tuya", "艶" }, { "tuya", "艷" },
			{ "tuyo", "侃" }, { "tuyo", "倔" }, { "tuyo", "剛" }, { "tuyo", "勁" }, { "tuyo", "勍" }, { "tuyo", "強" }, { "tuyo", "彊" }, { "tuyo", "毅" },
			{ "tuyo", "逎" }, { "tuyo", "遒" }, { "tuyosi", "剛" }, { "tuyosi", "壮" }, { "tuyosi", "幹" }, { "tuyosi", "彊" }, { "tuyosi", "彪" }, { "tuyosi", "毅" },
			{ "tuyosi", "雄" }, { "tuyu", "汁" }, { "tuyu", "露" }, { "tuzi", "辻" }, { "tya", "ちゃ" }, { "tya", "チャ" }, { "tya", "楪" }, { "tya", "茗" },
			{ "tya", "茶" }, { "tyaku", "嫡" }, { "tyaku", "役" }, { "tyaku", "擲" }, { "tyaku", "着" }, { "tyaku", "磔" }, { "tyaku", "箸" }, { "tyaku", "著" },
			{ "tyaku", "謫" }, { "tyaku", "躇" }, { "tyan", "荘" }, { "tyan", "莊" }, { "tyan", "頭" }, { "tyo", "ちょ" }, { "tyo", "チョ" }, { "tyo", "佇" },
			{ "tyo", "儲" }, { "tyo", "墸" }, { "tyo", "屠" }, { "tyo", "杼" }, { "tyo", "楮" }, { "tyo", "樗" }, { "tyo", "潴" }, { "tyo", "瀦" }, { "tyo", "猪" },
			{ "tyo", "竚" }, { "tyo", "箸" }, { "tyo", "紵" }, { "tyo", "緒" }, { "tyo", "苧" }, { "tyo", "著" }, { "tyo", "豬" }, { "tyo", "貯" }, { "tyo", "躇" },
			{ "tyo", "迢" }, { "tyoku", "勅" }, { "tyoku", "捗" }, { "tyoku", "敕" }, { "tyoku", "直" }, { "tyoku", "矗" }, { "tyoku", "稙" }, { "tyoku", "躅" },
			{ "tyoku", "陟" }, { "tyoku", "隲" }, { "tyoku", "飭" }, { "tyou", "丁" }, { "tyou", "仗" }, { "tyou", "佻" }, { "tyou", "傭" }, { "tyou", "兆" },
			{ "tyou", "冢" }, { "tyou", "凋" }, { "tyou", "剳" }, { "tyou", "吊" }, { "tyou", "喋" }, { "tyou", "嘲" }, { "tyou", "場" }, { "tyou", "塚" },
			{ "tyou", "塲" }, { "tyou", "姚" }, { "tyou", "寵" }, { "tyou", "帖" }, { "tyou", "帳" }, { "tyou", "幀" }, { "tyou", "庁" }, { "tyou", "廰" },
			{ "tyou", "廳" }, { "tyou", "弔" }, { "tyou", "張" }, { "tyou", "彫" }, { "tyou", "徴" }, { "tyou", "恰" }, { "tyou", "悵" }, { "tyou", "懲" },
			{ "tyou", "挑" }, { "tyou", "挺" }, { "tyou", "掉" }, { "tyou", "掟" }, { "tyou", "提" }, { "tyou", "敏" }, { "tyou", "敦" }, { "tyou", "昶" },
			{ "tyou", "晁" }, { "tyou", "暢" }, { "tyou", "朝" }, { "tyou", "杓" }, { "tyou", "条" }, { "tyou", "梃" }, { "tyou", "條" }, { "tyou", "樗" },
			{ "tyou", "樢" }, { "tyou", "沾" }, { "tyou", "渫" }, { "tyou", "漲" }, { "tyou", "潮" }, { "tyou", "澂" }, { "tyou", "澄" }, { "tyou", "牒" },
			{ "tyou", "町" }, { "tyou", "甼" }, { "tyou", "畳" }, { "tyou", "疂" }, { "tyou", "疉" }, { "tyou", "疊" }, { "tyou", "疔" }, { "tyou", "登" },
			{ "tyou", "眺" }, { "tyou", "稠" }, { "tyou", "窕" }, { "tyou", "笘" }, { "tyou", "箚" }, { "tyou", "糴" }, { "tyou", "糶" }, { "tyou", "聴" },
			{ "tyou", "聽" }, { "tyou", "肇" }, { "tyou", "脹" }, { "tyou", "腸" }, { "tyou", "膓" }, { "tyou", "萇" }, { "tyou", "蔦" }, { "tyou", "蜩" },
			{ "tyou", "蝶" }, { "tyou", "褶" }, { "tyou", "誂" }, { "tyou", "調" }, { "tyou", "諜" }, { "tyou", "貂" }, { "tyou", "貼" }, { "tyou", "超" },
			{ "tyou", "趙" }, { "tyou", "跳" }, { "tyou", "輒" }, { "tyou", "輙" }, { "tyou", "迢" }, { "tyou", "重" }, { "tyou", "釘" }, { "tyou", "釣" },
			{ "tyou", "銚" }, { "tyou", "長" }, { "tyou", "陦" }, { "tyou", "雕" }, { "tyou", "頂" }, { "tyou", "髫" }, { "tyou", "鬯" }, { "tyou", "鯛" },
			{ "tyou", "鰈" }, { "tyou", "鳥" }, { "tyou", "齠" }, { "tyouzame", "鰉" }, { "tyu", "ちゅ" }, { "tyu", "チュ" }, { "tyu", "丶" }, { "tyu", "厨" },
			{ "tyu", "廚" }, { "tyu", "蛛" }, { "tyu", "誅" }, { "tyu", "躊" }, { "tyu", "酎" }, { "tyun", "仲" }, { "tyun", "椿" }, { "tyutu", "朮" },
			{ "tyutu", "黜" }, { "tyuu", "丑" }, { "tyuu", "中" }, { "tyuu", "仲" }, { "tyuu", "住" }, { "tyuu", "偸" }, { "tyuu", "儔" }, { "tyuu", "冑" },
			{ "tyuu", "冲" }, { "tyuu", "厨" }, { "tyuu", "宙" }, { "tyuu", "廚" }, { "tyuu", "忠" }, { "tyuu", "惆" }, { "tyuu", "抽" }, { "tyuu", "昼" },
			{ "tyuu", "晝" }, { "tyuu", "柱" }, { "tyuu", "沖" }, { "tyuu", "注" }, { "tyuu", "狆" }, { "tyuu", "畴" }, { "tyuu", "疇" }, { "tyuu", "痩" },
			{ "tyuu", "稠" }, { "tyuu", "籀" }, { "tyuu", "籌" }, { "tyuu", "紂" }, { "tyuu", "紐" }, { "tyuu", "紬" }, { "tyuu", "綢" }, { "tyuu", "肘" },
			{ "tyuu", "胄" }, { "tyuu", "舳" }, { "tyuu", "虫" }, { "tyuu", "蟄" }, { "tyuu", "蟲" }, { "tyuu", "衷" }, { "tyuu", "註" }, { "tyuu", "誅" },
			{ "tyuu", "躊" }, { "tyuu", "酎" }, { "tyuu", "鈕" }, { "tyuu", "鋳" }, { "tyuu", "鍮" }, { "tyuu", "鑄" }, { "tyuu", "駐" }, { "u", "う" }, { "u", "ウ" },
			{ "u", "于" }, { "u", "享" }, { "u", "伐" }, { "u", "佑" }, { "u", "侑" }, { "u", "保" }, { "u", "倦" }, { "u", "傴" }, { "u", "優" }, { "u", "卯" },
			{ "u", "友" }, { "u", "受" }, { "u", "右" }, { "u", "吁" }, { "u", "售" }, { "u", "嗚" }, { "u", "埋" }, { "u", "塢" }, { "u", "売" }, { "u", "夘" },
			{ "u", "失" }, { "u", "嫗" }, { "u", "孳" }, { "u", "宇" }, { "u", "守" }, { "u", "布" }, { "u", "府" }, { "u", "得" }, { "u", "御" }, { "u", "憂" },
			{ "u", "打" }, { "u", "承" }, { "u", "抃" }, { "u", "挌" }, { "u", "挧" }, { "u", "掫" }, { "u", "搏" }, { "u", "搨" }, { "u", "撃" }, { "u", "擣" },
			{ "u", "擽" }, { "u", "有" }, { "u", "桙" }, { "u", "植" }, { "u", "椎" }, { "u", "武" }, { "u", "沽" }, { "u", "浮" }, { "u", "烏" }, { "u", "熟" },
			{ "u", "燠" }, { "u", "瓜" }, { "u", "生" }, { "u", "産" }, { "u", "盂" }, { "u", "碓" }, { "u", "碾" }, { "u", "磑" }, { "u", "祐" }, { "u", "禹" },
			{ "u", "笛" }, { "u", "糴" }, { "u", "紆" }, { "u", "綿" }, { "u", "羽" }, { "u", "胡" }, { "u", "膿" }, { "u", "芋" }, { "u", "芸" }, { "u", "苑" },
			{ "u", "茹" }, { "u", "菟" }, { "u", "蒔" }, { "u", "藝" }, { "u", "討" }, { "u", "請" }, { "u", "謳" }, { "u", "賈" }, { "u", "賣" }, { "u", "迂" },
			{ "u", "遊" }, { "u", "防" }, { "u", "雅" }, { "u", "雨" }, { "u", "飢" }, { "u", "餒" }, { "u", "餓" }, { "u", "饉" }, { "u", "饑" }, { "u", "饗" },
			{ "u", "鵜" }, { "u", "齲" }, { "uba", "奪" }, { "uba", "姆" }, { "uba", "姥" }, { "uba", "簒" }, { "uba", "褫" }, { "ubu", "幼" }, { "ubu", "生" },
			{ "ubu", "産" }, { "ude", "腕" }, { "udewa", "釧" }, { "udon", "饂" }, { "ue", "上" }, { "ue", "植" }, { "ue", "樹" }, { "ue", "殖" }, { "ue", "筌" },
			{ "uezini", "殍" }, { "uga", "穿" }, { "uga", "鑿" }, { "ugai", "漱" }, { "ugo", "動" }, { "ugo", "揺" }, { "ugo", "搖" }, { "ugo", "盪" }, { "ugo", "蕩" },
			{ "ugo", "蘯" }, { "ugo", "蠢" }, { "ugo", "蹌" }, { "ugoka", "撼" }, { "ugome", "蠕" }, { "ugui", "鯏" }, { "uguisu", "鴬" }, { "uguisu", "鶯" },
			{ "uhu", "大" }, { "ui", "初" }, { "ui", "外" }, { "ui", "茴" }, { "ui", "黄" }, { "uka", "泛" }, { "ukaga", "伺" }, { "ukaga", "俔" }, { "ukaga", "窺" },
			{ "ukaga", "覗" }, { "ukaga", "覘" }, { "ukaga", "諜" }, { "ukaga", "遉" }, { "ukaga", "闖" }, { "ukanmuri", "宀" }, { "uke", "筌" }, { "uke", "請" },
			{ "ukebako", "凵" }, { "uketamawa", "承" }, { "uki", "浮" }, { "ukibukuro", "鰾" }, { "ukikusa", "萍" }, { "ukikusa", "蘋" }, { "uma", "午" },
			{ "uma", "巧" }, { "uma", "旨" }, { "uma", "甘" }, { "uma", "甜" }, { "uma", "馬" }, { "umai", "生" }, { "umaka", "圉" }, { "umare", "生" },
			{ "umaya", "厩" }, { "umaya", "廏" }, { "umaya", "廐" }, { "ume", "呻" }, { "ume", "梅" }, { "ume", "楳" }, { "umeki", "呻" }, { "umi", "海" },
			{ "umi", "湖" }, { "umi", "溟" }, { "umi", "瀛" }, { "umi", "膿" }, { "umu", "惓" }, { "umusa", "茂" }, { "un", "云" }, { "un", "吽" }, { "un", "怨" },
			{ "un", "慍" }, { "un", "暈" }, { "un", "欝" }, { "un", "殞" }, { "un", "海" }, { "un", "紜" }, { "un", "繧" }, { "un", "耘" }, { "un", "芸" },
			{ "un", "薀" }, { "un", "藝" }, { "un", "蘊" }, { "un", "褞" }, { "un", "運" }, { "un", "銀" }, { "un", "隕" }, { "un", "雲" }, { "un", "饂" },
			{ "un", "鶤" }, { "una", "唸" }, { "una", "海" }, { "una", "髫" }, { "una", "魘" }, { "unaga", "促" }, { "unagi", "鰻" }, { "unari", "唸" },
			{ "unazi", "項" }, { "unazu", "頷" }, { "une", "壟" }, { "une", "畆" }, { "une", "畝" }, { "une", "畦" }, { "une", "畴" }, { "une", "疇" }, { "une", "釆" },
			{ "uo", "魚" }, { "ura", "卜" }, { "ura", "占" }, { "ura", "怏" }, { "ura", "怨" }, { "ura", "恨" }, { "ura", "悵" }, { "ura", "惆" }, { "ura", "慊" },
			{ "ura", "慍" }, { "ura", "憾" }, { "ura", "浦" }, { "ura", "裏" }, { "ura", "裡" }, { "ura", "麗" }, { "urakata", "卦" }, { "urami", "怨" },
			{ "urana", "卜" }, { "urana", "占" }, { "urana", "筮" }, { "uranai", "卜" }, { "urasi", "嬉" }, { "uraya", "羨" }, { "ure", "嬉" }, { "ure", "恤" },
			{ "ure", "悄" }, { "ure", "悒" }, { "ure", "愁" }, { "ure", "憂" }, { "ure", "憫" }, { "ure", "戚" }, { "ure", "邑" }, { "ure", "閔" },
			{ "ureerusama", "忙" }, { "urei", "騒" }, { "urei", "騷" }, { "uresi", "嬉" }, { "uri", "売" }, { "uri", "瓜" }, { "uriyone", "糶" }, { "uroko", "鱗" },
			{ "uru", "売" }, { "uru", "漆" }, { "uru", "潤" }, { "uruo", "沢" }, { "uruo", "沾" }, { "uruo", "洽" }, { "uruo", "渥" }, { "uruo", "湿" },
			{ "uruo", "潤" }, { "uruo", "澤" }, { "uruo", "濕" }, { "uruo", "濡" }, { "uruo", "霑" }, { "urusakusyabe", "譫" }, { "urusi", "漆" }, { "uruti", "粳" },
			{ "uruu", "閏" }, { "uruu", "閠" }, { "uruwa", "彬" }, { "uruwa", "斌" }, { "uruwa", "麗" }, { "us", "欝" }, { "us", "鬱" }, { "usa", "総" },
			{ "usagi", "兎" }, { "usagi", "兔" }, { "usagi", "莵" }, { "usagi", "菟" }, { "usagiami", "罘" }, { "usagiuma", "驢" }, { "usi", "丑" }, { "usi", "後" },
			{ "usi", "牛" }, { "usina", "失" }, { "usio", "汐" }, { "usio", "潮" }, { "usiro", "後" }, { "usitora", "艮" }, { "uso", "嘘" }, { "uso", "獺" },
			{ "uso", "鷽" }, { "usobu", "嘯" }, { "usu", "凉" }, { "usu", "涼" }, { "usu", "漓" }, { "usu", "碓" }, { "usu", "臼" }, { "usu", "菲" }, { "usu", "薄" },
			{ "usudu", "臼" }, { "usudu", "舂" }, { "usuginu", "紗" }, { "usuginu", "繻" }, { "usugu", "腰" }, { "usutu", "舂" }, { "uta", "咏" }, { "uta", "哥" },
			{ "uta", "唄" }, { "uta", "嘔" }, { "uta", "宴" }, { "uta", "欧" }, { "uta", "歌" }, { "uta", "歐" }, { "uta", "詠" }, { "uta", "詩" }, { "uta", "謌" },
			{ "uta", "謠" }, { "uta", "謡" }, { "uta", "謳" }, { "uta", "賦" }, { "utaga", "疑" }, { "utage", "宴" }, { "utage", "讌" }, { "utaime", "妓" },
			{ "utata", "転" }, { "utata", "轉" }, { "utena", "台" }, { "utena", "柎" }, { "utena", "臺" }, { "utena", "萼" }, { "utena", "蕚" }, { "uti", "中" },
			{ "uti", "内" }, { "uti", "家" }, { "uti", "打" }, { "uti", "蔚" }, { "uti", "裡" }, { "utibari", "梁" }, { "utigi", "袿" }, { "utikake", "袿" },
			{ "utikake", "裲" }, { "utikake", "褂" }, { "utiki", "袿" }, { "utiki", "褂" }, { "uto", "疎" }, { "uto", "疏" }, { "uto", "踈" }, { "utta", "愬" },
			{ "utta", "訴" }, { "utta", "諍" }, { "utu", "写" }, { "utu", "冩" }, { "utu", "寫" }, { "utu", "徙" }, { "utu", "拊" }, { "utu", "映" }, { "utu", "暎" },
			{ "utu", "槍" }, { "utu", "欝" }, { "utu", "熨" }, { "utu", "移" }, { "utu", "空" }, { "utu", "蔚" }, { "utu", "虚" }, { "utu", "転" }, { "utu", "轉" },
			{ "utu", "遷" }, { "utu", "鬱" }, { "utubari", "梁" }, { "utubo", "笂" }, { "utubo", "靫" }, { "utubo", "靭" }, { "utubo", "靱" }, { "utuku", "佼" },
			{ "utuku", "倩" }, { "utuku", "妍" }, { "utuku", "姚" }, { "utuku", "娃" }, { "utuku", "婉" }, { "utuku", "窕" }, { "utuku", "美" }, { "utukusi", "旺" },
			{ "utumu", "俯" }, { "utuo", "靫" }, { "utuo", "靱" }, { "utuwa", "噐" }, { "utuwa", "器" }, { "uwa", "上" }, { "uwabami", "蟒" }, { "uwabami", "蠎" },
			{ "uwagoto", "譫" }, { "uwagusuri", "釉" }, { "uwasa", "噂" }, { "uyama", "敬" }, { "uyauya", "恭" }, { "uzi", "氏" }, { "uzi", "牛" }, { "uzi", "蛆" },
			{ "uzu", "埋" }, { "uzu", "填" }, { "uzu", "水" }, { "uzu", "渦" }, { "uzu", "疼" }, { "uzuku", "踞" }, { "uzukuma", "蹲" }, { "uzumaki", "巴" },
			{ "uzura", "鶉" }, { "uzutaka", "堆" }, { "va", "ヴァ" }, { "ve", "ヴェ" }, { "vi", "ヴィ" }, { "vo", "ヴォ" }, { "vu", "ヴ" }, { "wa", "わ" }, { "wa", "ワ" },
			{ "wa", "丸" }, { "wa", "久" }, { "wa", "二" }, { "wa", "佗" }, { "wa", "侘" }, { "wa", "倭" }, { "wa", "分" }, { "wa", "別" }, { "wa", "割" },
			{ "wa", "劃" }, { "wa", "十" }, { "wa", "和" } };
};
