package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R17 {
	public static String[][] kl = { { "ta", "タ" }, { "ta", "丹" }, { "ta", "仔" }, { "ta", "他" }, { "ta", "佗" }, { "ta", "侘" }, { "ta", "原" }, { "ta", "反" },
			{ "ta", "向" }, { "ta", "咤" }, { "ta", "咫" }, { "ta", "哮" }, { "ta", "唾" }, { "ta", "垂" }, { "ta", "埀" }, { "ta", "堪" }, { "ta", "多" },
			{ "ta", "夛" }, { "ta", "大" }, { "ta", "天" }, { "ta", "太" }, { "ta", "女" }, { "ta", "它" }, { "ta", "屋" }, { "ta", "岔" }, { "ta", "度" },
			{ "ta", "建" }, { "ta", "憚" }, { "ta", "手" }, { "ta", "断" }, { "ta", "斷" }, { "ta", "朶" }, { "ta", "柁" }, { "ta", "楕" }, { "ta", "楽" },
			{ "ta", "樔" }, { "ta", "殄" }, { "ta", "汰" }, { "ta", "沱" }, { "ta", "泰" }, { "ta", "海" }, { "ta", "溜" }, { "ta", "澑" }, { "ta", "炊" },
			{ "ta", "点" }, { "ta", "焚" }, { "ta", "田" }, { "ta", "発" }, { "ta", "發" }, { "ta", "矯" }, { "ta", "種" }, { "ta", "立" }, { "ta", "竪" },
			{ "ta", "経" }, { "ta", "絶" }, { "ta", "綏" }, { "ta", "經" }, { "ta", "耐" }, { "ta", "舵" }, { "ta", "荼" }, { "ta", "裁" }, { "ta", "詑" },
			{ "ta", "詫" }, { "ta", "誑" }, { "ta", "誰" }, { "ta", "謖" }, { "ta", "豎" }, { "ta", "貯" }, { "ta", "起" }, { "ta", "足" }, { "ta", "躱" },
			{ "ta", "閇" }, { "ta", "閉" }, { "ta", "闌" }, { "ta", "陀" }, { "ta", "隋" }, { "ta", "食" }, { "ta", "馬" }, { "ta", "駄" }, { "ta", "駝" },
			{ "ta", "騨" }, { "ta", "高" }, { "ta", "鴕" }, { "ta", "點" }, { "taTU", "立" }, { "taba", "把" }, { "taba", "抱" }, { "taba", "束" }, { "taba", "煙" },
			{ "taba", "繃" }, { "tabaka", "誑" }, { "tabaka", "謀" }, { "tabako", "莨" }, { "tabi", "度" }, { "tabi", "旅" }, { "tabi", "羇" }, { "tabi", "羈" },
			{ "tabi", "覊" }, { "tabi", "韈" }, { "tabo", "髱" }, { "tabu", "椨" }, { "tabura", "誑" }, { "tabusa", "髻" }, { "tada", "三" }, { "tada", "伊" },
			{ "tada", "但" }, { "tada", "内" }, { "tada", "匡" }, { "tada", "只" }, { "tada", "唯" }, { "tada", "啻" }, { "tada", "宰" }, { "tada", "尹" },
			{ "tada", "弾" }, { "tada", "彈" }, { "tada", "征" }, { "tada", "忠" }, { "tada", "惟" }, { "tada", "政" }, { "tada", "斉" }, { "tada", "正" },
			{ "tada", "爛" }, { "tada", "理" }, { "tada", "直" }, { "tada", "真" }, { "tada", "督" }, { "tada", "祇" }, { "tada", "禎" }, { "tada", "糜" },
			{ "tada", "糺" }, { "tada", "糾" }, { "tada", "縄" }, { "tada", "繩" }, { "tada", "聖" }, { "tada", "董" }, { "tada", "貭" }, { "tada", "質" },
			{ "tada", "飭" }, { "tadasi", "侃" }, { "tadasi", "公" }, { "tadasi", "匡" }, { "tadasi", "忠" }, { "tadasi", "旦" }, { "tadasi", "正" },
			{ "tadasi", "理" }, { "tadasi", "真" }, { "tadasi", "督" }, { "tadasi", "矩" }, { "tadasi", "禎" }, { "tadasi", "端" }, { "tadasi", "義" },
			{ "tadasi", "肇" }, { "tadasi", "規" }, { "tadasi", "貞" }, { "tadasi", "雅" }, { "tadasu", "匡" }, { "tadasu", "擶" }, { "tadasu", "紀" },
			{ "tadatini", "径" }, { "tadatini", "徑" }, { "tadatini", "逕" }, { "tadayo", "汎" }, { "tadayo", "漂" }, { "tadayo", "漾" }, { "tade", "蓼" },
			{ "tado", "辿" }, { "tadori", "辿" }, { "taduna", "羇" }, { "taduna", "羈" }, { "taduna", "覊" }, { "taduna", "轡" }, { "tae", "妙" }, { "tae", "成" },
			{ "tae", "栲" }, { "tae", "紗" }, { "tae", "耐" }, { "taga", "互" }, { "taga", "畊" }, { "taga", "箍" }, { "taga", "違" }, { "taga", "靠" },
			{ "tagaini", "逓" }, { "tagaini", "遞" }, { "tagane", "鏨" }, { "tagau", "爽" }, { "tagaya", "畉" }, { "tagaya", "耕" }, { "tagi", "滾" },
			{ "tagosi", "輦" }, { "tagu", "伉" }, { "tagu", "類" }, { "tagui", "双" }, { "tagui", "畴" }, { "tagui", "疇" }, { "tagui", "雙" }, { "tahu", "椨" },
			{ "tai", "代" }, { "tai", "体" }, { "tai", "來" }, { "tai", "兌" }, { "tai", "台" }, { "tai", "堆" }, { "tai", "大" }, { "tai", "太" }, { "tai", "夷" },
			{ "tai", "対" }, { "tai", "對" }, { "tai", "岱" }, { "tai", "帯" }, { "tai", "帶" }, { "tai", "平" }, { "tai", "当" }, { "tai", "待" }, { "tai", "怠" },
			{ "tai", "態" }, { "tai", "戴" }, { "tai", "抬" }, { "tai", "擡" }, { "tai", "敦" }, { "tai", "替" }, { "tai", "来" }, { "tai", "梯" }, { "tai", "棣" },
			{ "tai", "歹" }, { "tai", "殆" }, { "tai", "汰" }, { "tai", "泰" }, { "tai", "滞" }, { "tai", "滯" }, { "tai", "炬" }, { "tai", "玳" }, { "tai", "碓" },
			{ "tai", "秦" }, { "tai", "紿" }, { "tai", "耐" }, { "tai", "胎" }, { "tai", "腿" }, { "tai", "臺" }, { "tai", "苔" }, { "tai", "蒂" }, { "tai", "蔕" },
			{ "tai", "薹" }, { "tai", "蛻" }, { "tai", "袋" }, { "tai", "褪" }, { "tai", "詆" }, { "tai", "詒" }, { "tai", "諦" }, { "tai", "豸" }, { "tai", "貸" },
			{ "tai", "躰" }, { "tai", "軆" }, { "tai", "退" }, { "tai", "逮" }, { "tai", "醍" }, { "tai", "鎚" }, { "tai", "鐓" }, { "tai", "隊" }, { "tai", "隶" },
			{ "tai", "靆" }, { "tai", "頽" }, { "tai", "颱" }, { "tai", "駘" }, { "tai", "體" }, { "tai", "鯛" }, { "tai", "黛" }, { "taimai", "玳" },
			{ "taira", "坦" }, { "taira", "平" }, { "taira", "砥" }, { "taka", "享" }, { "taka", "京" }, { "taka", "公" }, { "taka", "剛" }, { "taka", "卓" },
			{ "taka", "喬" }, { "taka", "堯" }, { "taka", "太" }, { "taka", "好" }, { "taka", "孝" }, { "taka", "学" }, { "taka", "宅" }, { "taka", "宇" },
			{ "taka", "宗" }, { "taka", "宜" }, { "taka", "寶" }, { "taka", "将" }, { "taka", "尊" }, { "taka", "尚" }, { "taka", "尭" }, { "taka", "就" },
			{ "taka", "岌" }, { "taka", "岳" }, { "taka", "峻" }, { "taka", "崇" }, { "taka", "崛" }, { "taka", "嵩" }, { "taka", "巍" }, { "taka", "延" },
			{ "taka", "廷" }, { "taka", "応" }, { "taka", "挙" }, { "taka", "敞" }, { "taka", "敬" }, { "taka", "昂" }, { "taka", "杲" }, { "taka", "琢" },
			{ "taka", "登" }, { "taka", "竹" }, { "taka", "考" }, { "taka", "聖" }, { "taka", "能" }, { "taka", "臣" }, { "taka", "誉" }, { "taka", "貴" },
			{ "taka", "賢" }, { "taka", "銘" }, { "taka", "陟" }, { "taka", "隆" }, { "taka", "顧" }, { "taka", "高" }, { "taka", "魏" }, { "taka", "鷹" },
			{ "takaburu", "亢" }, { "takadono", "楼" }, { "takadono", "樓" }, { "takamu", "崇" }, { "takamura", "篁" }, { "takamusiro", "簟" }, { "takanna", "笋" },
			{ "takanna", "筍" }, { "takara", "宝" }, { "takara", "寳" }, { "takara", "寶" }, { "takara", "珍" }, { "takara", "珎" }, { "takara", "用" },
			{ "takara", "財" }, { "takara", "貲" }, { "takasi", "丘" }, { "takasi", "享" }, { "takasi", "卓" }, { "takasi", "喬" }, { "takasi", "大" },
			{ "takasi", "天" }, { "takasi", "孝" }, { "takasi", "尚" }, { "takasi", "尭" }, { "takasi", "岐" }, { "takasi", "峻" }, { "takasi", "崇" },
			{ "takasi", "嵩" }, { "takasi", "巍" }, { "takasi", "律" }, { "takasi", "敞" }, { "takasi", "敬" }, { "takasi", "昂" }, { "takasi", "皐" },
			{ "takasi", "節" }, { "takasi", "貴" }, { "takasi", "長" }, { "takasi", "隆" }, { "takasi", "髞" }, { "takatuki", "鐙" }, { "take", "丈" },
			{ "take", "健" }, { "take", "傑" }, { "take", "全" }, { "take", "剛" }, { "take", "和" }, { "take", "威" }, { "take", "孟" }, { "take", "宅" },
			{ "take", "尊" }, { "take", "岳" }, { "take", "嵩" }, { "take", "嶽" }, { "take", "建" }, { "take", "彪" }, { "take", "敬" }, { "take", "斌" },
			{ "take", "武" }, { "take", "毅" }, { "take", "猛" }, { "take", "穀" }, { "take", "竹" }, { "take", "茸" }, { "take", "蕈" }, { "take", "虎" },
			{ "take", "誉" }, { "take", "豪" }, { "take", "赳" }, { "take", "長" }, { "take", "雄" }, { "takeki", "彪" }, { "taken", "岳" }, { "taken", "武" },
			{ "takenawa", "酣" }, { "takenawa", "闌" }, { "takenoko", "笋" }, { "takenoko", "筍" }, { "takeru", "猛" }, { "takesi", "健" }, { "takesi", "剛" },
			{ "takesi", "壯" }, { "takesi", "威" }, { "takesi", "孟" }, { "takesi", "彪" }, { "takesi", "悍" }, { "takesi", "武" }, { "takesi", "毅" },
			{ "takesi", "洸" }, { "takesi", "猛" }, { "takesi", "豪" }, { "takesi", "赳" }, { "takesi", "驍" }, { "taki", "嶽" }, { "taki", "滝" }, { "taki", "瀑" },
			{ "taki", "瀧" }, { "takigi", "掫" }, { "takigi", "蕘" }, { "takigi", "薪" }, { "tako", "凧" }, { "tako", "蛸" }, { "tako", "鮹" }, { "tako", "鱆" },
			{ "taku", "倬" }, { "taku", "卓" }, { "taku", "啄" }, { "taku", "啅" }, { "taku", "宅" }, { "taku", "巧" }, { "taku", "度" }, { "taku", "戳" },
			{ "taku", "托" }, { "taku", "択" }, { "taku", "拆" }, { "taku", "拓" }, { "taku", "擇" }, { "taku", "擢" }, { "taku", "柝" }, { "taku", "棹" },
			{ "taku", "櫂" }, { "taku", "沢" }, { "taku", "澤" }, { "taku", "濯" }, { "taku", "炸" }, { "taku", "琢" }, { "taku", "磔" }, { "taku", "託" },
			{ "taku", "詫" }, { "taku", "謫" }, { "taku", "躅" }, { "taku", "鈬" }, { "taku", "鐸" }, { "taku", "魄" }, { "takuma", "逞" }, { "takumi", "倆" },
			{ "takumi", "匠" }, { "takumi", "工" }, { "takumi", "巧" }, { "takuwa", "儲" }, { "takuwa", "蓄" }, { "takuwa", "薀" }, { "takuwa", "貯" },
			{ "tama", "偶" }, { "tama", "圭" }, { "tama", "堪" }, { "tama", "弾" }, { "tama", "彈" }, { "tama", "溜" }, { "tama", "澑" }, { "tama", "玉" },
			{ "tama", "玖" }, { "tama", "玲" }, { "tama", "珠" }, { "tama", "珪" }, { "tama", "球" }, { "tama", "瑞" }, { "tama", "瑤" }, { "tama", "瑰" },
			{ "tama", "瑶" }, { "tama", "璧" }, { "tama", "環" }, { "tama", "瓊" }, { "tama", "碧" }, { "tama", "給" }, { "tama", "賚" }, { "tama", "賜" },
			{ "tama", "錫" }, { "tama", "霊" }, { "tama", "靈" }, { "tama", "魂" }, { "tama", "魄" }, { "tamago", "卵" }, { "tamago", "孚" }, { "tamaki", "環" },
			{ "tamaki", "鐶" }, { "tamamono", "賚" }, { "tamari", "溜" }, { "tamari", "澑" }, { "tamasii", "魂" }, { "tamato", "袂" }, { "tamawa", "賜" },
			{ "tamaya", "廟" }, { "tame", "溜" }, { "tame", "澑" }, { "tame", "為" }, { "tame", "爲" }, { "tame", "試" }, { "tame", "験" }, { "tame", "驗" },
			{ "tameiki", "愾" }, { "tamera", "躇" }, { "tamera", "躊" }, { "tamesi", "験" }, { "tamesi", "驗" }, { "tami", "丹" }, { "tami", "民" }, { "tami", "氓" },
			{ "tamo", "保" }, { "tamo", "給" }, { "tamo", "賜" }, { "tamoto", "袂" }, { "tamotu", "維" }, { "tamusi", "癬" }, { "tan", "丹" }, { "tan", "丼" },
			{ "tan", "亶" }, { "tan", "但" }, { "tan", "単" }, { "tan", "反" }, { "tan", "唐" }, { "tan", "啖" }, { "tan", "啗" }, { "tan", "單" }, { "tan", "嘆" },
			{ "tan", "坦" }, { "tan", "堪" }, { "tan", "壇" }, { "tan", "壜" }, { "tan", "弾" }, { "tan", "彈" }, { "tan", "彖" }, { "tan", "怛" }, { "tan", "愽" },
			{ "tan", "慱" }, { "tan", "憚" }, { "tan", "憺" }, { "tan", "担" }, { "tan", "探" }, { "tan", "揣" }, { "tan", "摶" }, { "tan", "擔" }, { "tan", "攤" },
			{ "tan", "旦" }, { "tan", "椴" }, { "tan", "槫" }, { "tan", "檀" }, { "tan", "檐" }, { "tan", "歎" }, { "tan", "殫" }, { "tan", "段" }, { "tan", "毯" },
			{ "tan", "淡" }, { "tan", "湍" }, { "tan", "湛" }, { "tan", "潭" }, { "tan", "澹" }, { "tan", "灘" }, { "tan", "炭" }, { "tan", "猯" }, { "tan", "田" },
			{ "tan", "疸" }, { "tan", "痰" }, { "tan", "眈" }, { "tan", "短" }, { "tan", "站" }, { "tan", "端" }, { "tan", "箪" }, { "tan", "簟" }, { "tan", "綻" },
			{ "tan", "緞" }, { "tan", "罎" }, { "tan", "耽" }, { "tan", "胆" }, { "tan", "膽" }, { "tan", "葮" }, { "tan", "蕁" }, { "tan", "蛋" }, { "tan", "蜑" },
			{ "tan", "蜒" }, { "tan", "袒" }, { "tan", "褝" }, { "tan", "襌" }, { "tan", "覃" }, { "tan", "誕" }, { "tan", "譚" }, { "tan", "譫" }, { "tan", "谷" },
			{ "tan", "貪" }, { "tan", "賺" }, { "tan", "赧" }, { "tan", "鄲" }, { "tan", "酖" }, { "tan", "鍛" }, { "tan", "鐔" }, { "tan", "靼" }, { "tan", "餤" },
			{ "tan", "騨" }, { "tana", "屶" }, { "tana", "店" }, { "tana", "廛" }, { "tana", "棚" }, { "tanagokoro", "掌" }, { "tanagokoro", "掬" }, { "tane", "稙" },
			{ "tane", "種" }, { "tane", "胤" }, { "tani", "壑" }, { "tani", "峪" }, { "tani", "渓" }, { "tani", "溪" }, { "tani", "澗" }, { "tani", "谷" },
			{ "tani", "谿" }, { "tanigawa", "渓" }, { "tanigawa", "溪" }, { "tanigawa", "谿" }, { "tanimizu", "澗" }, { "tano", "倚" }, { "tano", "嘱" },
			{ "tano", "囑" }, { "tano", "嬉" }, { "tano", "怙" }, { "tano", "恃" }, { "tano", "愉" }, { "tano", "憑" }, { "tano", "托" }, { "tano", "楽" },
			{ "tano", "樂" }, { "tano", "頼" }, { "tano", "馮" }, { "tanosi", "佚" }, { "tanosi", "煕" }, { "tanosi", "熈" }, { "tanosi", "熙" }, { "tanuki", "狸" },
			{ "tanuki", "貍" }, { "tao", "乢" }, { "tao", "仆" }, { "tao", "倒" }, { "tao", "僵" }, { "tao", "垰" }, { "tao", "嫋" }, { "tao", "嵶" }, { "tao", "斃" },
			{ "tao", "殪" }, { "tao", "蹶" }, { "tao", "顛" }, { "taoyaka", "婀" }, { "tara", "平" }, { "tara", "槃" }, { "tara", "鰔" }, { "tara", "鱈" },
			{ "tarai", "盥" }, { "tarasi", "足" }, { "tare", "孰" }, { "tare", "誰" }, { "taregami", "髦" }, { "tari", "渡" }, { "tari", "為" }, { "tari", "爲" },
			{ "tari", "谷" }, { "taru", "善" }, { "taru", "垂" }, { "taru", "弛" }, { "taru", "樽" }, { "taruki", "桷" }, { "taruki", "椽" }, { "taruki", "榱" },
			{ "tasi", "慥" }, { "tasi", "碓" }, { "tasi", "確" }, { "tasina", "嗜" }, { "tasina", "窘" }, { "tasu", "丞" }, { "tasu", "佑" }, { "tasu", "侑" },
			{ "tasu", "助" }, { "tasu", "幇" }, { "tasu", "弼" }, { "tasu", "扶" }, { "tasu", "掖" }, { "tasu", "毘" }, { "tasu", "祐" }, { "tasu", "裨" },
			{ "tasu", "賛" }, { "tasu", "贊" }, { "tasu", "輔" }, { "tasuki", "襷" }, { "tasuku", "亮" }, { "tasuku", "佑" }, { "tasuku", "弼" }, { "tasuku", "祐" },
			{ "tasuku", "輔" }, { "tata", "叩" }, { "tata", "彳" }, { "tata", "忠" }, { "tata", "扣" }, { "tata", "敲" }, { "tata", "毆" }, { "tata", "湛" },
			{ "tata", "畳" }, { "tata", "疂" }, { "tata", "疉" }, { "tata", "疊" }, { "tata", "祟" }, { "tata", "称" }, { "tata", "稱" }, { "tata", "讃" },
			{ "tata", "讚" }, { "tata", "賛" }, { "tata", "贊" }, { "tata", "頌" }, { "tataka", "戦" }, { "tataka", "戰" }, { "tataka", "闘" }, { "tataka", "鬪" },
			{ "tatakaigamae", "鬥" }, { "tatami", "畳" }, { "tatami", "疂" }, { "tatami", "疉" }, { "tatami", "疊" }, { "tatara", "鑪" }, { "tatazu", "佇" },
			{ "tatazu", "竚" }, { "tate", "健" }, { "tate", "帯" }, { "tate", "建" }, { "tate", "楯" }, { "tate", "盾" }, { "tate", "立" }, { "tate", "竪" },
			{ "tate", "縦" }, { "tate", "縱" }, { "tate", "舘" }, { "tate", "豎" }, { "tate", "賢" }, { "tate", "館" }, { "tate", "鹵" }, { "tategami", "鬣" },
			{ "tatehuda", "榜" }, { "tateito", "経" }, { "tateito", "經" }, { "tatematu", "亨" }, { "tatematu", "奉" }, { "tatematu", "献" }, { "tatematu", "獻" },
			{ "tati", "城" }, { "tati", "日" }, { "tati", "朔" }, { "tati", "立" }, { "tati", "舘" }, { "tati", "貭" }, { "tati", "質" }, { "tati", "逹" },
			{ "tati", "達" }, { "tati", "闥" }, { "tati", "陸" }, { "tati", "靼" }, { "tati", "館" }, { "tatibana", "橘" }, { "tatiki", "樹" }, { "tatima", "乍" },
			{ "tatima", "忽" }, { "tatimati", "倏" }, { "tatimati", "奄" }, { "tatimotoo", "裴" }, { "tatimotoo", "躑" }, { "tato", "例" }, { "tato", "俔" },
			{ "tato", "喩" }, { "tato", "譬" }, { "tatto", "尊" }, { "tatto", "貴" }, { "tatu", "建" }, { "tatu", "怛" }, { "tatu", "截" }, { "tatu", "撻" },
			{ "tatu", "樹" }, { "tatu", "燵" }, { "tatu", "獺" }, { "tatu", "立" }, { "tatu", "竜" }, { "tatu", "蔦" }, { "tatu", "辰" }, { "tatu", "逹" },
			{ "tatu", "達" }, { "tatu", "闥" }, { "tatu", "靼" }, { "tatu", "韃" }, { "tatu", "龍" }, { "tatumi", "巽" }, { "taturu", "樹" }, { "tawa", "乢" },
			{ "tawa", "垰" }, { "tawa", "嵶" }, { "tawa", "懈" }, { "tawa", "撓" }, { "tawa", "橈" }, { "tawagoto", "譫" }, { "tawamu", "弄" }, { "tawamu", "戯" },
			{ "tawamu", "戲" }, { "tawamu", "謔" }, { "tawamure", "詼" }, { "tawara", "俵" }, { "tayo", "便" }, { "tayo", "頼" }, { "tayu", "弛" }, { "tazi", "但" },
			{ "tazu", "尋" }, { "tazu", "訊" }, { "tazu", "訪" }, { "tazu", "鶴" }, { "tazune", "繹" }, { "tazusa", "携" }, { "tazusa", "攜" }, { "te", "て" },
			{ "te", "テ" }, { "te", "勅" }, { "te", "因" }, { "te", "天" }, { "te", "守" }, { "te", "弖" }, { "te", "弟" }, { "te", "手" }, { "te", "樋" },
			{ "te", "殿" }, { "te", "汀" }, { "te", "照" }, { "te", "稲" }, { "te", "稻" }, { "te", "豊" }, { "te", "逹" }, { "te", "達" }, { "teTU", "哲" },
			{ "teTU", "徹" }, { "teTU", "鉄" }, { "tegata", "劵" }, { "teguruma", "輦" }, { "tei", "丁" }, { "tei", "亭" }, { "tei", "低" }, { "tei", "体" },
			{ "tei", "俤" }, { "tei", "停" }, { "tei", "偵" }, { "tei", "剃" }, { "tei", "剔" }, { "tei", "叮" }, { "tei", "呈" }, { "tei", "啼" }, { "tei", "嚏" },
			{ "tei", "嚔" }, { "tei", "堤" }, { "tei", "奠" }, { "tei", "姨" }, { "tei", "定" }, { "tei", "帝" }, { "tei", "幀" }, { "tei", "庁" }, { "tei", "底" },
			{ "tei", "庭" }, { "tei", "廰" }, { "tei", "廳" }, { "tei", "廷" }, { "tei", "弟" }, { "tei", "悌" }, { "tei", "抵" }, { "tei", "挺" }, { "tei", "掟" },
			{ "tei", "提" }, { "tei", "柢" }, { "tei", "梃" }, { "tei", "梯" }, { "tei", "棣" }, { "tei", "楴" }, { "tei", "汀" }, { "tei", "洟" }, { "tei", "涕" },
			{ "tei", "渟" }, { "tei", "滞" }, { "tei", "滯" }, { "tei", "牴" }, { "tei", "畷" }, { "tei", "疔" }, { "tei", "眤" }, { "tei", "睇" }, { "tei", "砥" },
			{ "tei", "碇" }, { "tei", "禎" }, { "tei", "程" }, { "tei", "第" }, { "tei", "綴" }, { "tei", "締" }, { "tei", "羝" }, { "tei", "聴" }, { "tei", "艇" },
			{ "tei", "蒂" }, { "tei", "蔕" }, { "tei", "薙" }, { "tei", "蟶" }, { "tei", "袋" }, { "tei", "裼" }, { "tei", "觝" }, { "tei", "訂" }, { "tei", "詆" },
			{ "tei", "諦" }, { "tei", "貞" }, { "tei", "蹄" }, { "tei", "躰" }, { "tei", "軆" }, { "tei", "逓" }, { "tei", "逞" }, { "tei", "遉" }, { "tei", "遞" },
			{ "tei", "邸" }, { "tei", "鄭" }, { "tei", "酊" }, { "tei", "酲" }, { "tei", "醍" }, { "tei", "釘" }, { "tei", "錣" }, { "tei", "霆" }, { "tei", "騁" },
			{ "tei", "體" }, { "tei", "髢" }, { "tei", "鵜" }, { "tei", "鼎" }, { "tekase", "梏" }, { "teki", "俶" }, { "teki", "剔" }, { "teki", "嫡" },
			{ "teki", "廸" }, { "teki", "彳" }, { "teki", "摘" }, { "teki", "擢" }, { "teki", "擲" }, { "teki", "敵" }, { "teki", "杓" }, { "teki", "滌" },
			{ "teki", "滴" }, { "teki", "狄" }, { "teki", "的" }, { "teki", "笛" }, { "teki", "糴" }, { "teki", "荻" }, { "teki", "覿" }, { "teki", "躑" },
			{ "teki", "迪" }, { "teki", "逖" }, { "teki", "適" }, { "teki", "鏑" }, { "teko", "杆" }, { "teko", "杠" }, { "teko", "桿" }, { "teko", "梃" },
			{ "teko", "槓" }, { "ten", "一" }, { "ten", "丶" }, { "ten", "伝" }, { "ten", "佃" }, { "ten", "傳" }, { "ten", "典" }, { "ten", "出" }, { "ten", "唸" },
			{ "ten", "囀" }, { "ten", "填" }, { "ten", "壥" }, { "ten", "天" }, { "ten", "奠" }, { "ten", "展" }, { "ten", "巓" }, { "ten", "店" }, { "ten", "廛" },
			{ "ten", "忝" }, { "ten", "恬" }, { "ten", "掾" }, { "ten", "椽" }, { "ten", "槇" }, { "ten", "槙" }, { "ten", "殄" }, { "ten", "殿" }, { "ten", "沾" },
			{ "ten", "淀" }, { "ten", "添" }, { "ten", "澱" } };
};
