package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R4 {
	public static String[][] kl = { { "hanabira", "辯" }, { "hanabusa", "英" }, { "hanada", "縹" }, { "hanadi", "衂" }, { "hanadi", "衄" }, { "hanaha", "甚" },
			{ "hanahada", "已" }, { "hanaiki", "嚊" }, { "hanamuke", "贐" }, { "hanamuke", "餞" }, { "hanare", "放" }, { "hanasi", "咄" }, { "hanasi", "噺" },
			{ "hanasi", "話" }, { "hanasi", "譚" }, { "hanawa", "塙" }, { "hanawa", "淵" }, { "hanawa", "渊" }, { "hanawa", "渕" }, { "hane", "羽" }, { "hane", "翅" },
			{ "hane", "翰" }, { "hanebou", "亅" }, { "hani", "埴" }, { "hanzou", "楾" }, { "hara", "原" }, { "hara", "妊" }, { "hara", "姙" }, { "hara", "孕" },
			{ "hara", "払" }, { "hara", "拂" }, { "hara", "攘" }, { "hara", "服" }, { "hara", "源" }, { "hara", "祓" }, { "hara", "禊" }, { "hara", "禳" },
			{ "hara", "肚" }, { "hara", "胚" }, { "hara", "腹" }, { "hara", "襄" }, { "harai", "払" }, { "harai", "秡" }, { "harami", "孕" }, { "harami", "胚" },
			{ "haranomusi", "蛔" }, { "hararago", "鯡" }, { "harawata", "腑" }, { "harawata", "腸" }, { "harawata", "膓" }, { "harawata", "臓" },
			{ "harawata", "臟" }, { "hare", "晴" }, { "haremono", "癰" }, { "haremono", "腫" }, { "hari", "張" }, { "hari", "播" }, { "hari", "梁" }, { "hari", "榛" },
			{ "hari", "治" }, { "hari", "箴" }, { "hari", "針" }, { "hari", "鍼" }, { "harinezumi", "彙" }, { "harinezumi", "蝟" }, { "harituke", "桀" },
			{ "harituke", "磔" }, { "haru", "元" }, { "haru", "問" }, { "haru", "孟" }, { "haru", "明" }, { "haru", "春" }, { "haru", "晴" }, { "haru", "東" },
			{ "haru", "榛" }, { "haru", "治" }, { "haru", "温" }, { "haru", "玄" }, { "haru", "美" }, { "haru", "脩" }, { "haru", "迢" }, { "haru", "遙" },
			{ "haru", "遥" }, { "haru", "開" }, { "haru", "陽" }, { "haruka", "夐" }, { "haruka", "杳" }, { "haruka", "玄" }, { "haruka", "迥" }, { "haruka", "遼" },
			{ "has", "罸" }, { "hasa", "夾" }, { "hasa", "挟" }, { "hasa", "挾" }, { "hasa", "挿" }, { "hasa", "插" }, { "hasa", "箝" }, { "hasa", "襭" },
			{ "hasa", "迫" }, { "hasa", "鋏" }, { "hasama", "迫" }, { "hasami", "螯" }, { "hasami", "鋏" }, { "hase", "騁" }, { "hase", "驟" }, { "hasi", "啄" },
			{ "hasi", "嘴" }, { "hasi", "枦" }, { "hasi", "梁" }, { "hasi", "橋" }, { "hasi", "端" }, { "hasi", "箸" }, { "hasi", "觜" }, { "hasi", "走" },
			{ "hasi", "赱" }, { "hasi", "趨" }, { "hasi", "階" }, { "hasibami", "榛" }, { "hasigo", "梯" }, { "hasika", "疹" }, { "hasike", "艀" }, { "hasira", "柱" },
			{ "hasira", "楹" }, { "hasiri", "走" }, { "hasitame", "婢" }, { "hasu", "斜" }, { "hasu", "泰" }, { "hasu", "芙" }, { "hasu", "荷" }, { "hasu", "蓉" },
			{ "hasu", "蓮" }, { "hasunone", "藕" }, { "hasya", "燥" }, { "hata", "傍" }, { "hata", "叩" }, { "hata", "将" }, { "hata", "將" }, { "hata", "幡" },
			{ "hata", "幢" }, { "hata", "拮" }, { "hata", "旃" }, { "hata", "旆" }, { "hata", "旌" }, { "hata", "旗" }, { "hata", "旙" }, { "hata", "旛" },
			{ "hata", "果" }, { "hata", "機" }, { "hata", "畑" }, { "hata", "畠" }, { "hata", "礑" }, { "hata", "秦" }, { "hata", "端" }, { "hata", "籏" },
			{ "hataasi", "旒" }, { "hataboko", "纛" }, { "hatagasira", "覇" }, { "hatagasira", "霸" }, { "hatahata", "鰰" }, { "hatake", "圃" }, { "hatake", "畑" },
			{ "hatake", "畠" }, { "hatake", "疥" }, { "hatara", "仂" }, { "hatara", "働" }, { "hatasu", "毅" }, { "hatato", "礑" }, { "hate", "垓" }, { "hate", "崖" },
			{ "hate", "涯" }, { "hati", "八" }, { "hati", "平" }, { "hati", "捌" }, { "hati", "椀" }, { "hati", "甌" }, { "hati", "盂" }, { "hati", "蜂" },
			{ "hati", "釟" }, { "hati", "鉢" }, { "hatigasira", "八" }, { "hatisu", "蓮" }, { "hato", "鳩" }, { "hato", "鴿" }, { "hatoba", "埠" }, { "hatu", "伐" },
			{ "hatu", "八" }, { "hatu", "初" }, { "hatu", "削" }, { "hatu", "叭" }, { "hatu", "垈" }, { "hatu", "廿" }, { "hatu", "抜" }, { "hatu", "捌" },
			{ "hatu", "撥" }, { "hatu", "服" }, { "hatu", "泊" }, { "hatu", "溌" }, { "hatu", "癶" }, { "hatu", "発" }, { "hatu", "發" }, { "hatu", "秡" },
			{ "hatu", "筏" }, { "hatu", "罰" }, { "hatu", "罸" }, { "hatu", "肇" }, { "hatu", "跋" }, { "hatu", "醗" }, { "hatu", "釟" }, { "hatu", "鉢" },
			{ "hatu", "髪" }, { "hatu", "髮" }, { "hatu", "魃" }, { "hatugasira", "癶" }, { "haya", "勇" }, { "haya", "囃" }, { "haya", "捷" }, { "haya", "早" },
			{ "haya", "湍" }, { "haya", "趾" }, { "haya", "速" }, { "haya", "逸" }, { "haya", "隼" }, { "haya", "駛" }, { "haya", "鮠" }, { "hayabusa", "隼" },
			{ "hayabusa", "鶻" }, { "hayai", "夙" }, { "hayai", "斉" }, { "hayai", "蚤" }, { "hayai", "齊" }, { "hayao", "駿" }, { "hayase", "湍" },
			{ "hayasi", "林" }, { "hayasi", "駿" }, { "haza", "挾" }, { "haza", "狭" }, { "haza", "硲" }, { "haza", "陌" }, { "hazama", "峡" }, { "hazama", "峽" },
			{ "hazama", "硲" }, { "hazama", "迫" }, { "haze", "枦" }, { "haze", "櫨" }, { "haze", "鯊" }, { "hazi", "初" }, { "hazi", "剏" }, { "hazi", "創" },
			{ "hazi", "垢" }, { "hazi", "始" }, { "hazi", "弾" }, { "hazi", "彈" }, { "hazi", "忸" }, { "hazi", "恥" }, { "hazi", "愧" }, { "hazi", "慙" },
			{ "hazi", "慚" }, { "hazi", "甫" }, { "hazi", "羞" }, { "hazi", "耻" }, { "hazi", "肇" }, { "hazi", "詬" }, { "hazikami", "椒" }, { "hazikami", "薑" },
			{ "hazime", "一" }, { "hazime", "俶" }, { "hazime", "元" }, { "hazime", "創" }, { "hazime", "哉" }, { "hazime", "啓" }, { "hazime", "大" },
			{ "hazime", "孟" }, { "hazime", "弌" }, { "hazime", "甫" }, { "hazime", "肇" }, { "hazu", "外" }, { "hazu", "弾" }, { "hazu", "彈" }, { "hazu", "筈" },
			{ "hazukasi", "愧" }, { "hazukasi", "詬" }, { "hazukasi", "辱" }, { "hazumi", "勢" }, { "he", "へ" }, { "he", "ヘ" }, { "he", "兵" }, { "he", "剥" },
			{ "he", "圧" }, { "he", "壓" }, { "he", "屁" }, { "he", "平" }, { "he", "戸" }, { "he", "日" }, { "he", "減" }, { "he", "経" }, { "he", "經" },
			{ "he", "舳" }, { "he", "閉" }, { "hebi", "它" }, { "hebi", "蛇" }, { "heda", "距" }, { "heda", "隔" }, { "heda", "鬲" }, { "hei", "丙" }, { "hei", "並" },
			{ "hei", "併" }, { "hei", "俾" }, { "hei", "僻" }, { "hei", "兵" }, { "hei", "凭" }, { "hei", "坪" }, { "hei", "塀" }, { "hei", "娉" }, { "hei", "嬖" },
			{ "hei", "屏" }, { "hei", "幣" }, { "hei", "幤" }, { "hei", "平" }, { "hei", "幵" }, { "hei", "并" }, { "hei", "弊" }, { "hei", "恵" }, { "hei", "憊" },
			{ "hei", "敝" }, { "hei", "斃" }, { "hei", "枋" }, { "hei", "柄" }, { "hei", "炳" }, { "hei", "瓶" }, { "hei", "病" }, { "hei", "睥" }, { "hei", "砒" },
			{ "hei", "秉" }, { "hei", "竝" }, { "hei", "箆" }, { "hei", "篦" }, { "hei", "聘" }, { "hei", "苹" }, { "hei", "萍" }, { "hei", "蓖" }, { "hei", "蔽" },
			{ "hei", "薜" }, { "hei", "閇" }, { "hei", "閉" }, { "hei", "閖" }, { "hei", "陛" }, { "hei", "餅" }, { "hei", "餠" }, { "hei", "髀" }, { "hei", "鮃" },
			{ "heki", "僻" }, { "heki", "劈" }, { "heki", "壁" }, { "heki", "擘" }, { "heki", "璧" }, { "heki", "甓" }, { "heki", "癖" }, { "heki", "碧" },
			{ "heki", "襞" }, { "heki", "躄" }, { "heki", "辟" }, { "heki", "闢" }, { "heki", "霹" }, { "heko", "凹" }, { "hekutoguramu", "瓸" },
			{ "hekutomeetoru", "粨" }, { "hekutorittoru", "竡" }, { "hen", "偏" }, { "hen", "卞" }, { "hen", "変" }, { "hen", "平" }, { "hen", "弁" }, { "hen", "扁" },
			{ "hen", "扮" }, { "hen", "旙" }, { "hen", "旛" }, { "hen", "汳" }, { "hen", "片" }, { "hen", "瓣" }, { "hen", "篇" }, { "hen", "編" }, { "hen", "翩" },
			{ "hen", "胼" }, { "hen", "蝙" }, { "hen", "褊" }, { "hen", "諞" }, { "hen", "變" }, { "hen", "貶" }, { "hen", "辧" }, { "hen", "辨" }, { "hen", "辮" },
			{ "hen", "辯" }, { "hen", "辺" }, { "hen", "返" }, { "hen", "逸" }, { "hen", "遍" }, { "hen", "邉" }, { "hen", "邊" }, { "hen", "鞭" }, { "hen", "駢" },
			{ "hen", "騙" }, { "hena", "埴" }, { "hera", "箆" }, { "hera", "篦" }, { "heri", "縁" }, { "herikuda", "遜" }, { "hesaki", "舮" }, { "hesaki", "舳" },
			{ "hesaki", "艫" }, { "heso", "臍" }, { "heta", "蒂" }, { "heta", "蔕" }, { "heti", "暼" }, { "hettui", "竃" }, { "hettui", "竈" }, { "hetu", "丿" },
			{ "hetu", "暼" }, { "hetu", "瞥" }, { "hetu", "蔽" }, { "hetu", "鼈" }, { "hetura", "諂" }, { "hetura", "諛" }, { "heya", "曹" }, { "hezu", "剥" },
			{ "hi", "ひ" }, { "hi", "ヒ" }, { "hi", "一" }, { "hi", "丕" }, { "hi", "乾" }, { "hi", "井" }, { "hi", "似" }, { "hi", "俾" }, { "hi", "僻" },
			{ "hi", "冰" }, { "hi", "冱" }, { "hi", "冴" }, { "hi", "冷" }, { "hi", "匕" }, { "hi", "匪" }, { "hi", "卑" }, { "hi", "否" }, { "hi", "嚊" },
			{ "hi", "坡" }, { "hi", "妃" }, { "hi", "妣" }, { "hi", "婁" }, { "hi", "婢" }, { "hi", "孫" }, { "hi", "屁" }, { "hi", "常" }, { "hi", "干" },
			{ "hi", "平" }, { "hi", "庇" }, { "hi", "引" }, { "hi", "弯" }, { "hi", "弾" }, { "hi", "彈" }, { "hi", "彎" }, { "hi", "彼" }, { "hi", "怫" },
			{ "hi", "悲" }, { "hi", "惹" }, { "hi", "扉" }, { "hi", "批" }, { "hi", "披" }, { "hi", "拏" }, { "hi", "拿" }, { "hi", "挽" }, { "hi", "掎" },
			{ "hi", "掣" }, { "hi", "攣" }, { "hi", "斐" }, { "hi", "日" }, { "hi", "旭" }, { "hi", "春" }, { "hi", "暃" }, { "hi", "曳" }, { "hi", "曵" },
			{ "hi", "朏" }, { "hi", "杼" }, { "hi", "枇" }, { "hi", "桧" }, { "hi", "梭" }, { "hi", "榧" }, { "hi", "樋" }, { "hi", "檜" }, { "hi", "比" },
			{ "hi", "毘" }, { "hi", "氷" }, { "hi", "沍" }, { "hi", "泌" }, { "hi", "火" }, { "hi", "灯" }, { "hi", "燈" }, { "hi", "牽" }, { "hi", "狒" },
			{ "hi", "理" }, { "hi", "琵" }, { "hi", "疲" }, { "hi", "痞" }, { "hi", "痺" }, { "hi", "皮" }, { "hi", "砒" }, { "hi", "碑" }, { "hi", "碾" },
			{ "hi", "祕" }, { "hi", "秕" }, { "hi", "秘" }, { "hi", "稗" }, { "hi", "等" }, { "hi", "簸" }, { "hi", "粃" }, { "hi", "紕" }, { "hi", "絅" },
			{ "hi", "緋" }, { "hi", "罷" }, { "hi", "羆" }, { "hi", "翡" }, { "hi", "肥" }, { "hi", "脾" }, { "hi", "腓" }, { "hi", "臂" }, { "hi", "英" },
			{ "hi", "茯" }, { "hi", "菲" }, { "hi", "蓖" }, { "hi", "蜚" }, { "hi", "被" }, { "hi", "裨" }, { "hi", "裴" }, { "hi", "誹" }, { "hi", "譬" },
			{ "hi", "豼" }, { "hi", "貔" }, { "hi", "費" }, { "hi", "賁" }, { "hi", "贔" }, { "hi", "跛" }, { "hi", "輓" }, { "hi", "輝" }, { "hi", "轡" },
			{ "hi", "轢" }, { "hi", "辟" }, { "hi", "退" }, { "hi", "避" }, { "hi", "鄙" }, { "hi", "陂" }, { "hi", "陳" }, { "hi", "陽" }, { "hi", "霏" },
			{ "hi", "非" }, { "hi", "靡" }, { "hi", "鞁" }, { "hi", "鞴" }, { "hi", "飛" }, { "hi", "髀" }, { "hi", "鯡" }, { "hi", "鵯" }, { "hibi", "皴" },
			{ "hibi", "皸" }, { "hibi", "皹" }, { "hibi", "罅" }, { "hibi", "響" }, { "hibiki", "韵" }, { "hida", "摺" }, { "hida", "襞" }, { "hidari", "左" },
			{ "hide", "任" }, { "hide", "偉" }, { "hide", "嗣" }, { "hide", "栄" }, { "hide", "秀" }, { "hide", "英" }, { "hide", "豪" }, { "hideri", "旱" },
			{ "hidesi", "秀" }, { "hido", "酷" }, { "hidume", "蹄" }, { "hie", "稗" }, { "hie", "肥" }, { "higa", "僻" }, { "higa", "東" }, { "higai", "鰉" },
			{ "higasi", "東" }, { "hige", "須" }, { "hige", "髪" }, { "hige", "髭" }, { "hige", "髯" }, { "hige", "鬚" }, { "higuma", "羆" }, { "higurasi", "蜩" },
			{ "hihi", "狒" }, { "hii", "秀" }, { "hiiragi", "柊" }, { "hika", "光" }, { "hika", "扣" }, { "hika", "控" }, { "hika", "煕" }, { "hika", "熈" },
			{ "hika", "熙" }, { "hika", "爍" }, { "hika", "皓" }, { "hikagami", "膕" }, { "hikari", "光" }, { "hikari", "晶" }, { "hikari", "洸" }, { "hikari", "燿" },
			{ "hikari", "耀" }, { "hikari", "耿" }, { "hikaru", "晃" }, { "hikaru", "輝" }, { "hike", "引" }, { "hiki", "匹" }, { "hiki", "引" }, { "hiki", "抽" },
			{ "hiki", "挽" }, { "hiki", "曳" }, { "hiki", "率" }, { "hiki", "疋" }, { "hiki", "蟆" }, { "hiki", "蟇" }, { "hiki", "逼" }, { "hikii", "将" },
			{ "hikii", "將" }, { "hikiri", "燧" }, { "hikitu", "痙" }, { "hikituke", "癇" }, { "hiko", "人" }, { "hiko", "光" }, { "hiko", "勉" }, { "hiko", "彦" },
			{ "hikobae", "蘖" }, { "hiku", "低" }, { "hiku", "矮" }, { "hima", "暇" }, { "hima", "遑" }, { "hima", "釁" }, { "hima", "隙" }, { "hime", "姫" },
			{ "hime", "媛" }, { "hime", "嬪" }, { "himo", "紐" }, { "himo", "綬" }, { "himogori", "膰" }, { "himono", "鱶" }, { "himorogi", "胙" },
			{ "himorogi", "膰" }, { "himoto", "繙" }, { "himusi", "蛾" }, { "hin", "品" }, { "hin", "嬪" }, { "hin", "彬" }, { "hin", "擯" }, { "hin", "斌" },
			{ "hin", "梹" }, { "hin", "檳" }, { "hin", "殯" }, { "hin", "浜" }, { "hin", "濱" }, { "hin", "瀕" }, { "hin", "牝" }, { "hin", "禀" }, { "hin", "秤" },
			{ "hin", "稟" }, { "hin", "繽" }, { "hin", "蘋" }, { "hin", "貧" }, { "hin", "賓" }, { "hin", "頻" }, { "hin", "顰" }, { "hin", "鬢" }, { "hina", "鄙" },
			{ "hina", "雛" }, { "hine", "拈" }, { "hine", "捻" }, { "hine", "撚" }, { "hineku", "弄" }, { "hinoe", "丙" }, { "hinoki", "桧" }, { "hinoki", "檜" },
			{ "hinokuti", "閘" }, { "hinosi", "熨" }, { "hinoto", "丁" }, { "hira", "啓" }, { "hira", "平" }, { "hira", "成" }, { "hira", "拓" }, { "hira", "挨" },
			{ "hira", "擺" }, { "hira", "攤" }, { "hira", "枚" }, { "hira", "波" }, { "hira", "衡" }, { "hira", "豁" }, { "hira", "辟" }, { "hira", "開" },
			{ "hira", "闢" }, { "hirabi", "曰" }, { "hiraku", "拆" }, { "hiraku", "磔" }, { "hirame", "閃" }, { "hirame", "鮃" }, { "hiratai", "扁" },
			{ "hire", "鰭" }, { "hiro", "丑" }, { "hiro", "仁" }, { "hiro", "伯" }, { "hiro", "倫" }, { "hiro", "公" }, { "hiro", "凡" }, { "hiro", "博" },
			{ "hiro", "周" }, { "hiro", "啓" }, { "hiro", "嘉" }, { "hiro", "大" }, { "hiro", "太" }, { "hiro", "央" }, { "hiro", "宇" }, { "hiro", "宏" },
			{ "hiro", "宗" }, { "hiro", "宙" }, { "hiro", "容" }, { "hiro", "寛" }, { "hiro", "尋" }, { "hiro", "展" }, { "hiro", "幸" }, { "hiro", "広" },
			{ "hiro", "廣" }, { "hiro", "弘" }, { "hiro", "弥" }, { "hiro", "彦" }, { "hiro", "恢" }, { "hiro", "拓" }, { "hiro", "拡" }, { "hiro", "拾" },
			{ "hiro", "擴" }, { "hiro", "敞" }, { "hiro", "敬" }, { "hiro", "普" }, { "hiro", "欧" }, { "hiro", "氾" }, { "hiro", "汎" }, { "hiro", "汪" },
			{ "hiro", "泰" }, { "hiro", "洋" }, { "hiro", "洸" }, { "hiro", "浩" }, { "hiro", "海" }, { "hiro", "滉" }, { "hiro", "濶" }, { "hiro", "瀚" },
			{ "hiro", "煕" }, { "hiro", "熈" }, { "hiro", "熙" }, { "hiro", "皓" }, { "hiro", "碵" }, { "hiro", "祐" }, { "hiro", "祥" }, { "hiro", "禮" },
			{ "hiro", "紘" }, { "hiro", "緩" }, { "hiro", "聖" }, { "hiro", "胖" }, { "hiro", "裕" }, { "hiro", "豁" }, { "hiro", "郭" }, { "hiro", "闊" },
			{ "hiro", "陽" }, { "hiromu", "弘" }, { "hiron", "寛" }, { "hirosi", "大" }, { "hirosi", "宇" }, { "hirosi", "宏" }, { "hirosi", "寛" },
			{ "hirosi", "弘" }, { "hirosi", "汎" }, { "hirosi", "洋" }, { "hirosi", "洸" }, { "hirosi", "浩" }, { "hirosi", "海" }, { "hirosi", "煕" },
			{ "hirosi", "皓" }, { "hirosi", "礼" }, { "hirosi", "祐" }, { "hirosi", "紘" }, { "hirosi", "裕" }, { "hirosi", "豊" }, { "hiru", "怯" }, { "hiru", "昼" },
			{ "hiru", "晝" }, { "hiru", "蒜" }, { "hiru", "蛭" }, { "hiruga", "翩" }, { "hiruga", "飃" }, { "hiruga", "飄" }, { "hiruga", "飜" }, { "hirugae", "翻" },
			{ "hisa", "久" }, { "hisa", "亀" }, { "hisa", "剛" }, { "hisa", "史" }, { "hisa", "壽" }, { "hisa", "央" }, { "hisa", "宣" }, { "hisa", "寿" },
			{ "hisa", "尚" }, { "hisa", "廂" }, { "hisa", "弥" }, { "hisa", "彌" }, { "hisa", "恒" }, { "hisa", "教" }, { "hisa", "桐" }, { "hisa", "永" },
			{ "hisa", "玖" }, { "hisa", "粥" }, { "hisa", "長" }, { "hisa", "鬻" }, { "hisagi", "楸" }, { "hisago", "匏" }, { "hisago", "瓠" }, { "hisago", "瓢" },
			{ "hisago", "蠡" }, { "hisame", "霈" }, { "hisasi", "九" }, { "hisasi", "亀" }, { "hisasi", "亘" }, { "hisasi", "壽" }, { "hisasi", "寿" },
			{ "hisasi", "尚" }, { "hisasi", "庇" }, { "hisasi", "廂" }, { "hisasi", "廡" }, { "hisasi", "弥" }, { "hisasi", "彌" }, { "hisasi", "恆" },
			{ "hisasi", "恒" }, { "hisasi", "梠" }, { "hisasi", "檐" }, { "hisasi", "永" }, { "hisasi", "簷" }, { "hisasi", "龜" }, { "hisi", "拉" }, { "hisi", "犇" },
			{ "hisi", "菱" }, { "hisi", "蔆" }, { "hisi", "西" }, { "hisihisi", "犇" }, { "hisikui", "鴻" }, { "hisio", "醢" }, { "hisio", "醤" }, { "hiso", "密" },
			{ "hiso", "潛" }, { "hiso", "潜" }, { "hiso", "濳" }, { "hiso", "秘" }, { "hiso", "窃" }, { "hiso", "竊" }, { "hiso", "顰" }, { "hissa", "挈" },
			{ "hissori", "闃" }, { "hisyaku", "杓" }, { "hita", "婬" }, { "hita", "常" }, { "hita", "浸" }, { "hita", "涵" }, { "hita", "淫" }, { "hita", "溲" },
			{ "hitai", "額" }, { "hitaki", "鶲" }, { "hiti", "七" }, { "hiti", "篳" }, { "hitigi", "柩" }, { "hitikudo", "諄" }, { "hito", "一" }, { "hito", "人" },
			{ "hito", "仁" }, { "hito", "傭" }, { "hito", "凖" }, { "hito", "匡" }, { "hito", "史" }, { "hito", "弌" }, { "hito", "斉" }, { "hito", "智" },
			{ "hito", "民" }, { "hito", "準" }, { "hito", "独" }, { "hito", "獨" }, { "hito", "畴" }, { "hito", "疇" }, { "hito", "等" }, { "hito", "薺" },
			{ "hito", "鈞" }, { "hito", "齊" }, { "hitoasi", "儿" }, { "hitoe", "単" }, { "hitoe", "單" }, { "hitoe", "褝" }, { "hitoe", "襌" }, { "hitomi", "眸" },
			{ "hitomi", "睛" }, { "hitomi", "瞳" }, { "hitomosi", "鐙" }, { "hitori", "孑" }, { "hitorimono", "煢" }, { "hitosi", "仁" }, { "hitosi", "倫" },
			{ "hitosi", "均" }, { "hitosi", "平" }, { "hitosi", "整" }, { "hitosi", "斉" }, { "hitosi", "斎" }, { "hitosi", "欽" }, { "hitosi", "齊" },
			{ "hitotu", "一" }, { "hitotu", "壱" }, { "hitotu", "壹" }, { "hitotu", "弌" }, { "hitoya", "圄" }, { "hitoya", "圉" }, { "hitoya", "牢" },
			{ "hitu", "匱" }, { "hitu", "匹" }, { "hitu", "弼" }, { "hitu", "必" }, { "hitu", "払" }, { "hitu", "拂" }, { "hitu", "櫃" }, { "hitu", "泌" },
			{ "hitu", "畢" }, { "hitu", "疋" }, { "hitu", "筆" }, { "hitu", "篳" }, { "hitu", "謐" }, { "hitu", "蹕" }, { "hitu", "逼" }, { "hitu", "鵯" },
			{ "hitugi", "柩" }, { "hitugiguruma", "轜" }, { "hituzi", "未" }, { "hituzi", "羊" }, { "hituzisaru", "坤" }, { "hiuti", "燧" }, { "hiwa", "鶸" },
			{ "hiya", "凉" }, { "hiya", "涼" }, { "hiyodori", "鵯" }, { "hiyoko", "雛" }, { "hiyorinotori", "酉" }, { "hiza", "膝" }, { "hizamazu", "跪" },
			{ "hizi", "土" }, { "hizi", "泥" }, { "hizi", "肘" }, { "hizi", "肱" }, { "hizi", "臂" }, { "hiziki", "枅" }, { "hiziki", "欒" }, { "hiziri", "聖" },
			{ "hizu", "歪" }, { "ho", "ほ" }, { "ho", "ホ" }, { "ho", "乾" }, { "ho", "保" }, { "ho", "匍" }, { "ho", "匏" }, { "ho", "反" }, { "ho", "吠" },
			{ "ho", "吼" }, { "ho", "咆" }, { "ho", "咐" }, { "ho", "哮" }, { "ho", "哺" }, { "ho", "圃" }, { "ho", "埔" }, { "ho", "埠" }, { "ho", "堡" },
			{ "ho", "娉" }, { "ho", "宝" }, { "ho", "峰" }, { "ho", "布" }, { "ho", "帆" }, { "ho", "干" }, { "ho", "彫" }, { "ho", "怖" }, { "ho", "恍" },
			{ "ho", "惚" }, { "ho", "捕" }, { "ho", "捗" }, { "ho", "掘" }, { "ho", "枋" }, { "ho", "枹" }, { "ho", "欲" }, { "ho", "歩" }, { "ho", "法" },
			{ "ho", "浦" }, { "ho", "火" }, { "ho", "灯" }, { "ho", "燈" }, { "ho", "甫" }, { "ho", "畆" } };
};
