package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R16 {
	public static String[][] kl = { { "su", "耡" }, { "su", "芻" }, { "su", "菅" }, { "su", "蒭" }, { "su", "蘇" }, { "su", "蘓" }, { "su", "西" }, { "su", "角" },
			{ "su", "諏" }, { "su", "透" }, { "su", "過" }, { "su", "酢" }, { "su", "酸" }, { "su", "醋" }, { "su", "釈" }, { "su", "釋" }, { "su", "鋤" },
			{ "su", "陶" }, { "su", "隙" }, { "su", "雛" }, { "su", "須" }, { "su", "饐" }, { "su", "首" }, { "su", "鬚" }, { "su", "鷲" }, { "su", "麈" },
			{ "suTU", "出" }, { "suTU", "寿" }, { "subaru", "昴" }, { "sube", "全" }, { "sube", "凡" }, { "sube", "渾" }, { "sube", "滑" }, { "sube", "総" },
			{ "sube", "總" }, { "sube", "術" }, { "sube", "辷" }, { "subekara", "須" }, { "subesi", "須" }, { "subo", "窄" }, { "sudama", "魑" }, { "sudare", "箔" },
			{ "sudare", "簾" }, { "sude", "已" }, { "sude", "既" }, { "sudenotukuri", "旡" }, { "sue", "季" }, { "sue", "居" }, { "sue", "末" }, { "sue", "甄" },
			{ "sue", "陶" }, { "suga", "清" }, { "suga", "管" }, { "suga", "縋" }, { "suga", "菅" }, { "sugame", "眇" }, { "sugata", "姿" }, { "suge", "菅" },
			{ "sugi", "叩" }, { "sugi", "杉" }, { "sugi", "椙" }, { "sugi", "生" }, { "sugi", "軼" }, { "sugiru", "宕" }, { "sugo", "凄" }, { "sugo", "淒" },
			{ "sugo", "菅" }, { "sugu", "傑" }, { "sugu", "儁" }, { "sugu", "優" }, { "sugu", "儻" }, { "sugu", "勝" }, { "sugu", "杰" }, { "sugu", "直" },
			{ "sugu", "雋" }, { "sugu", "駿" }, { "suguru", "俊" }, { "suguru", "卓" }, { "suguru", "英" }, { "suguru", "豪" }, { "sui", "出" }, { "sui", "剤" },
			{ "sui", "劑" }, { "sui", "吹" }, { "sui", "垂" }, { "sui", "埀" }, { "sui", "塁" }, { "sui", "壘" }, { "sui", "夊" }, { "sui", "崔" }, { "sui", "帥" },
			{ "sui", "彗" }, { "sui", "忰" }, { "sui", "悴" }, { "sui", "惴" }, { "sui", "捶" }, { "sui", "推" }, { "sui", "揣" }, { "sui", "椎" }, { "sui", "榱" },
			{ "sui", "水" }, { "sui", "氷" }, { "sui", "炊" }, { "sui", "燧" }, { "sui", "瑞" }, { "sui", "瘁" }, { "sui", "睡" }, { "sui", "祟" }, { "sui", "穂" },
			{ "sui", "穗" }, { "sui", "粋" }, { "sui", "粹" }, { "sui", "綏" }, { "sui", "翆" }, { "sui", "翠" }, { "sui", "膵" }, { "sui", "萃" }, { "sui", "衰" },
			{ "sui", "觜" }, { "sui", "誰" }, { "sui", "遂" }, { "sui", "邃" }, { "sui", "酔" }, { "sui", "醉" }, { "sui", "錐" }, { "sui", "錘" }, { "sui", "陲" },
			{ "sui", "隋" }, { "sui", "隧" }, { "sui", "隹" }, { "sui", "雖" }, { "sui", "騅" }, { "suinyou", "夊" }, { "suka", "賺" }, { "suke", "丞" },
			{ "suke", "亮" }, { "suke", "介" }, { "suke", "佐" }, { "suke", "佑" }, { "suke", "允" }, { "suke", "典" }, { "suke", "助" }, { "suke", "右" },
			{ "suke", "哉" }, { "suke", "弼" }, { "suke", "昌" }, { "suke", "甫" }, { "suke", "相" }, { "suke", "祐" }, { "suke", "裕" }, { "suke", "賃" },
			{ "suke", "資" }, { "suke", "輔" }, { "suki", "次" }, { "suki", "犁" }, { "suki", "犂" }, { "suki", "罅" }, { "suki", "耒" }, { "suki", "耜" },
			{ "suki", "耡" }, { "suki", "耨" }, { "suki", "釁" }, { "suki", "銛" }, { "suki", "銭" }, { "suki", "鋤" }, { "suki", "錢" }, { "suki", "鍬" },
			{ "suki", "隙" }, { "suko", "健" }, { "suko", "少" }, { "sukobu", "頗" }, { "sukosi", "毫" }, { "suku", "丞" }, { "suku", "匡" }, { "suku", "句" },
			{ "suku", "城" }, { "suku", "宿" }, { "suku", "少" }, { "suku", "抔" }, { "suku", "拯" }, { "suku", "掬" }, { "suku", "救" }, { "suku", "樔" },
			{ "suku", "淑" }, { "suku", "済" }, { "suku", "濟" }, { "suku", "竦" }, { "suku", "粛" }, { "suku", "肅" }, { "suku", "贍" }, { "sukumo", "粭" },
			{ "sukumo", "糘" }, { "sukumomusi", "蝎" }, { "sukuna", "尠" }, { "suma", "澂" }, { "sumi", "住" }, { "sumi", "墨" }, { "sumi", "寿" }, { "sumi", "栖" },
			{ "sumi", "清" }, { "sumi", "澄" }, { "sumi", "炭" }, { "sumi", "純" }, { "sumi", "綴" }, { "sumi", "角" }, { "sumi", "速" }, { "sumi", "陬" },
			{ "sumi", "隅" }, { "sumi", "隈" }, { "sumire", "菫" }, { "sumiyaka", "亟" }, { "sumiyaka", "遽" }, { "sumomo", "李" }, { "sumu", "済" }, { "sun", "吋" },
			{ "sun", "寸" }, { "sun", "駿" }, { "suna", "沙" }, { "suna", "砂" }, { "sunao", "淳" }, { "sunawa", "乃" }, { "sunawa", "即" }, { "sunawa", "廼" },
			{ "sunawa", "迺" }, { "sunawati", "曽" }, { "sunawati", "曾" }, { "sunawati", "而" }, { "sunawati", "輒" }, { "sunawati", "輙" }, { "sune", "強" },
			{ "sune", "脛" }, { "sune", "臑" }, { "suno", "墨" }, { "suno", "春" }, { "sunori", "規" }, { "suppon", "鼇" }, { "suppon", "鼈" }, { "suru", "摺" },
			{ "suru", "駿" }, { "surudo", "尖" }, { "surudo", "鋭" }, { "surume", "鯣" }, { "susa", "凄" }, { "susa", "淒" }, { "susa", "荒" }, { "susi", "鮓" },
			{ "susi", "鮨" }, { "suso", "裔" }, { "suso", "裾" }, { "susu", "侑" }, { "susu", "勧" }, { "susu", "勸" }, { "susu", "啜" }, { "susu", "嗽" },
			{ "susu", "奨" }, { "susu", "奬" }, { "susu", "廸" }, { "susu", "慂" }, { "susu", "慫" }, { "susu", "晉" }, { "susu", "晋" }, { "susu", "歃" },
			{ "susu", "洒" }, { "susu", "漱" }, { "susu", "澄" }, { "susu", "濯" }, { "susu", "煤" }, { "susu", "獎" }, { "susu", "膳" }, { "susu", "薦" },
			{ "susu", "迪" }, { "susu", "進" }, { "susu", "邁" }, { "susu", "陟" }, { "susuki", "芒" }, { "susuki", "薄" }, { "susume", "羞" }, { "susumi", "晋" },
			{ "susumi", "迪" }, { "susumu", "侑" }, { "susumu", "奏" }, { "susumu", "将" }, { "susumu", "晋" }, { "susumu", "迪" }, { "susurina", "歔" },
			{ "suta", "廃" }, { "suta", "廢" }, { "sute", "弃" }, { "sutu", "出" }, { "suu", "崇" }, { "suu", "嵩" }, { "suu", "数" }, { "suu", "數" }, { "suu", "枢" },
			{ "suu", "樞" }, { "suu", "皺" }, { "suu", "芻" }, { "suu", "菘" }, { "suu", "蒭" }, { "suu", "趨" }, { "suu", "鄒" }, { "suu", "陬" }, { "suu", "雛" },
			{ "suwa", "坐" }, { "suwa", "座" }, { "suwae", "楚" }, { "suzi", "条" }, { "suzi", "條" }, { "suzi", "筋" }, { "suzi", "綫" }, { "suzi", "線" },
			{ "suzi", "脈" }, { "suzi", "脉" }, { "suzu", "凉" }, { "suzu", "涼" }, { "suzu", "篶" }, { "suzu", "紗" }, { "suzu", "鈴" }, { "suzu", "錫" },
			{ "suzu", "鐸" }, { "suzu", "鑾" }, { "suzuki", "鱸" }, { "suzume", "雀" }, { "suzuri", "硯" }, { "sya", "しゃ" }, { "sya", "シャ" }, { "sya", "予" },
			{ "sya", "些" }, { "sya", "偖" }, { "sya", "写" }, { "sya", "冩" }, { "sya", "卸" }, { "sya", "叉" }, { "sya", "嗟" }, { "sya", "奢" }, { "sya", "姐" },
			{ "sya", "娑" }, { "sya", "寫" }, { "sya", "射" }, { "sya", "左" }, { "sya", "捨" }, { "sya", "斜" }, { "sya", "柘" }, { "sya", "沙" }, { "sya", "洒" },
			{ "sya", "瀉" }, { "sya", "灑" }, { "sya", "炙" }, { "sya", "煮" }, { "sya", "畭" }, { "sya", "砂" }, { "sya", "社" }, { "sya", "紗" }, { "sya", "者" },
			{ "sya", "舍" }, { "sya", "舎" }, { "sya", "苴" }, { "sya", "莎" }, { "sya", "蔗" }, { "sya", "藉" }, { "sya", "裟" }, { "sya", "謝" }, { "sya", "豫" },
			{ "sya", "貰" }, { "sya", "赦" }, { "sya", "赭" }, { "sya", "車" }, { "sya", "這" }, { "sya", "遮" }, { "sya", "釈" }, { "sya", "鉈" }, { "sya", "鯊" },
			{ "sya", "鷓" }, { "sya", "麝" }, { "syabe", "喋" }, { "syaga", "嗄" }, { "syaga", "躑" }, { "syake", "鮭" }, { "syako", "積" }, { "syaku", "借" },
			{ "syaku", "勣" }, { "syaku", "勺" }, { "syaku", "呎" }, { "syaku", "嚼" }, { "syaku", "妁" }, { "syaku", "尺" }, { "syaku", "斫" }, { "syaku", "昔" },
			{ "syaku", "晰" }, { "syaku", "杓" }, { "syaku", "灼" }, { "syaku", "爍" }, { "syaku", "爵" }, { "syaku", "癪" }, { "syaku", "皙" }, { "syaku", "石" },
			{ "syaku", "笏" }, { "syaku", "筰" }, { "syaku", "綽" }, { "syaku", "芍" }, { "syaku", "蜥" }, { "syaku", "赤" }, { "syaku", "蹟" }, { "syaku", "迹" },
			{ "syaku", "酌" }, { "syaku", "釈" }, { "syaku", "釋" }, { "syaku", "錫" }, { "syaku", "錯" }, { "syaku", "鑠" }, { "syaku", "雀" }, { "syaku", "鵲" },
			{ "syaku", "齣" }, { "syamo", "鶤" }, { "syan", "上" }, { "syao", "小" }, { "syati", "鯱" }, { "syatihoko", "鯱" }, { "syo", "しょ" }, { "syo", "ショ" },
			{ "syo", "且" }, { "syo", "俎" }, { "syo", "処" }, { "syo", "初" }, { "syo", "咀" }, { "syo", "埜" }, { "syo", "墅" }, { "syo", "岨" }, { "syo", "嶼" },
			{ "syo", "庶" }, { "syo", "恕" }, { "syo", "所" }, { "syo", "抒" }, { "syo", "暑" }, { "syo", "曙" }, { "syo", "書" }, { "syo", "杵" }, { "syo", "杼" },
			{ "syo", "松" }, { "syo", "楚" }, { "syo", "沮" }, { "syo", "渚" }, { "syo", "爼" }, { "syo", "狙" }, { "syo", "疋" }, { "syo", "疎" }, { "syo", "疏" },
			{ "syo", "疽" }, { "syo", "砠" }, { "syo", "絮" }, { "syo", "緒" }, { "syo", "署" }, { "syo", "胥" }, { "syo", "舒" }, { "syo", "苴" }, { "syo", "蔗" },
			{ "syo", "蔬" }, { "syo", "薯" }, { "syo", "藷" }, { "syo", "處" }, { "syo", "蛆" }, { "syo", "蜍" }, { "syo", "詛" }, { "syo", "諸" }, { "syo", "踈" },
			{ "syo", "野" }, { "syo", "鋤" }, { "syo", "雎" }, { "syo", "黍" }, { "syo", "鼠" }, { "syo", "鼡" }, { "syo", "齟" }, { "syoku", "厠" }, { "syoku", "喞" },
			{ "syoku", "嗇" }, { "syoku", "嘱" }, { "syoku", "囑" }, { "syoku", "埴" }, { "syoku", "寔" }, { "syoku", "属" }, { "syoku", "屬" }, { "syoku", "廁" },
			{ "syoku", "惻" }, { "syoku", "拭" }, { "syoku", "昃" }, { "syoku", "昵" }, { "syoku", "植" }, { "syoku", "殖" }, { "syoku", "燭" }, { "syoku", "矚" },
			{ "syoku", "禝" }, { "syoku", "稙" }, { "syoku", "稷" }, { "syoku", "穡" }, { "syoku", "粟" }, { "syoku", "続" }, { "syoku", "織" }, { "syoku", "續" },
			{ "syoku", "職" }, { "syoku", "色" }, { "syoku", "薔" }, { "syoku", "蜀" }, { "syoku", "蝕" }, { "syoku", "触" }, { "syoku", "觸" }, { "syoku", "謖" },
			{ "syoku", "贖" }, { "syoku", "軾" }, { "syoku", "食" }, { "syoku", "飾" }, { "syoku", "餝" }, { "syou", "上" }, { "syou", "且" }, { "syou", "丞" },
			{ "syou", "丼" }, { "syou", "乗" }, { "syou", "井" }, { "syou", "从" }, { "syou", "倡" }, { "syou", "傷" }, { "syou", "償" }, { "syou", "剏" },
			{ "syou", "創" }, { "syou", "剿" }, { "syou", "劭" }, { "syou", "勝" }, { "syou", "勦" }, { "syou", "匠" }, { "syou", "升" }, { "syou", "厰" },
			{ "syou", "召" }, { "syou", "咲" }, { "syou", "哨" }, { "syou", "唱" }, { "syou", "商" }, { "syou", "嘗" }, { "syou", "嘯" }, { "syou", "噌" },
			{ "syou", "囁" }, { "syou", "囎" }, { "syou", "墻" }, { "syou", "声" }, { "syou", "奨" }, { "syou", "奬" }, { "syou", "妝" }, { "syou", "妾" },
			{ "syou", "姓" }, { "syou", "娼" }, { "syou", "宵" }, { "syou", "将" }, { "syou", "將" }, { "syou", "小" }, { "syou", "少" }, { "syou", "尚" },
			{ "syou", "峭" }, { "syou", "嶂" }, { "syou", "庄" }, { "syou", "床" }, { "syou", "庠" }, { "syou", "廂" }, { "syou", "廠" }, { "syou", "彰" },
			{ "syou", "従" }, { "syou", "從" }, { "syou", "性" }, { "syou", "悄" }, { "syou", "悚" }, { "syou", "愀" }, { "syou", "慫" }, { "syou", "慯" },
			{ "syou", "慴" }, { "syou", "慵" }, { "syou", "憔" }, { "syou", "憧" }, { "syou", "懾" }, { "syou", "扱" }, { "syou", "承" }, { "syou", "抄" },
			{ "syou", "招" }, { "syou", "拯" }, { "syou", "挟" }, { "syou", "挾" }, { "syou", "捷" }, { "syou", "掌" }, { "syou", "接" }, { "syou", "搶" },
			{ "syou", "摂" }, { "syou", "摺" }, { "syou", "攝" }, { "syou", "政" }, { "syou", "敞" }, { "syou", "旌" }, { "syou", "昇" }, { "syou", "昌" },
			{ "syou", "星" }, { "syou", "昭" }, { "syou", "晶" }, { "syou", "杪" }, { "syou", "松" }, { "syou", "枌" }, { "syou", "枩" }, { "syou", "梢" },
			{ "syou", "椄" }, { "syou", "椒" }, { "syou", "楫" }, { "syou", "槍" }, { "syou", "様" }, { "syou", "樅" }, { "syou", "樟" }, { "syou", "樣" },
			{ "syou", "樵" }, { "syou", "橡" }, { "syou", "橦" }, { "syou", "檣" }, { "syou", "歃" }, { "syou", "歙" }, { "syou", "正" }, { "syou", "殤" },
			{ "syou", "沼" }, { "syou", "浹" }, { "syou", "消" }, { "syou", "淞" }, { "syou", "清" }, { "syou", "渉" }, { "syou", "湘" }, { "syou", "湫" },
			{ "syou", "漿" }, { "syou", "瀞" }, { "syou", "瀟" }, { "syou", "炒" }, { "syou", "烝" }, { "syou", "焦" }, { "syou", "焼" }, { "syou", "照" },
			{ "syou", "燒" }, { "syou", "燮" }, { "syou", "爿" }, { "syou", "牀" }, { "syou", "牆" }, { "syou", "猖" }, { "syou", "猩" }, { "syou", "獎" },
			{ "syou", "璋" }, { "syou", "甑" }, { "syou", "甞" }, { "syou", "生" }, { "syou", "甥" }, { "syou", "症" }, { "syou", "瘡" }, { "syou", "瘴" },
			{ "syou", "登" }, { "syou", "相" }, { "syou", "省" }, { "syou", "睛" }, { "syou", "睫" }, { "syou", "硝" }, { "syou", "礁" }, { "syou", "祥" },
			{ "syou", "秀" }, { "syou", "秤" }, { "syou", "称" }, { "syou", "稍" }, { "syou", "稱" }, { "syou", "章" }, { "syou", "竦" }, { "syou", "笑" },
			{ "syou", "笙" }, { "syou", "筝" }, { "syou", "筱" }, { "syou", "箏" }, { "syou", "篠" }, { "syou", "簫" }, { "syou", "粧" }, { "syou", "精" },
			{ "syou", "紹" }, { "syou", "翔" }, { "syou", "聖" }, { "syou", "聲" }, { "syou", "聳" }, { "syou", "聶" }, { "syou", "肖" }, { "syou", "腥" },
			{ "syou", "腫" }, { "syou", "舂" }, { "syou", "艘" }, { "syou", "艟" }, { "syou", "艢" }, { "syou", "荘" }, { "syou", "莊" }, { "syou", "菁" },
			{ "syou", "菖" }, { "syou", "蒋" }, { "syou", "蕉" }, { "syou", "蕭" }, { "syou", "薔" }, { "syou", "蚣" }, { "syou", "蛸" }, { "syou", "衝" },
			{ "syou", "装" }, { "syou", "裝" }, { "syou", "裳" }, { "syou", "褶" }, { "syou", "襄" }, { "syou", "觴" }, { "syou", "訟" }, { "syou", "証" },
			{ "syou", "詔" }, { "syou", "詳" }, { "syou", "誚" }, { "syou", "誦" }, { "syou", "請" }, { "syou", "諍" }, { "syou", "證" }, { "syou", "象" },
			{ "syou", "賞" }, { "syou", "踪" }, { "syou", "踵" }, { "syou", "蹌" }, { "syou", "蹤" }, { "syou", "逍" }, { "syou", "邵" }, { "syou", "醤" },
			{ "syou", "鈔" }, { "syou", "鉦" }, { "syou", "銷" }, { "syou", "錆" }, { "syou", "鍬" }, { "syou", "鍾" }, { "syou", "鎗" }, { "syou", "鏘" },
			{ "syou", "鐘" }, { "syou", "陞" }, { "syou", "障" }, { "syou", "霄" }, { "syou", "霎" }, { "syou", "青" }, { "syou", "鞘" }, { "syou", "韶" },
			{ "syou", "頌" }, { "syou", "顳" }, { "syou", "餉" }, { "syou", "驤" }, { "syou", "驫" }, { "syou", "鬆" }, { "syou", "鮹" }, { "syou", "鯖" },
			{ "syou", "鱆" }, { "syou", "鱶" }, { "syou", "鷦" }, { "syouhen", "爿" }, { "syouzyou", "猩" }, { "syu", "しゅ" }, { "syu", "シュ" }, { "syu", "主" },
			{ "syu", "侏" }, { "syu", "修" }, { "syu", "取" }, { "syu", "周" }, { "syu", "呪" }, { "syu", "咒" }, { "syu", "娵" }, { "syu", "娶" }, { "syu", "守" },
			{ "syu", "戍" }, { "syu", "手" }, { "syu", "捜" }, { "syu", "掃" }, { "syu", "搜" }, { "syu", "撞" }, { "syu", "数" }, { "syu", "數" }, { "syu", "最" },
			{ "syu", "朱" }, { "syu", "枢" }, { "syu", "柊" }, { "syu", "株" }, { "syu", "棕" }, { "syu", "椶" }, { "syu", "樞" }, { "syu", "橦" }, { "syu", "殊" },
			{ "syu", "殳" }, { "syu", "洙" }, { "syu", "溲" }, { "syu", "狩" }, { "syu", "珠" }, { "syu", "痩" }, { "syu", "秀" }, { "syu", "種" }, { "syu", "繻" },
			{ "syu", "聚" }, { "syu", "腫" }, { "syu", "茱" }, { "syu", "蛛" }, { "syu", "衆" }, { "syu", "諏" }, { "syu", "趣" }, { "syu", "趨" }, { "syu", "輸" },
			{ "syu", "鄒" }, { "syu", "酒" }, { "syu", "酬" }, { "syu", "銖" }, { "syu", "銹" }, { "syu", "鋳" }, { "syu", "鍾" }, { "syu", "鑄" }, { "syu", "須" },
			{ "syu", "首" }, { "syu", "鬆" }, { "syu", "鬚" }, { "syu", "鰌" }, { "syu", "鰍" }, { "syu", "麈" }, { "syuku", "俶" }, { "syuku", "倏" },
			{ "syuku", "叔" }, { "syuku", "夙" }, { "syuku", "宿" }, { "syuku", "槭" }, { "syuku", "淑" }, { "syuku", "矗" }, { "syuku", "祝" }, { "syuku", "粛" },
			{ "syuku", "粥" }, { "syuku", "縮" }, { "syuku", "肅" }, { "syuku", "菽" }, { "syuku", "蓿" }, { "syuku", "謖" }, { "syuku", "蹙" }, { "syuku", "蹴" },
			{ "syuku", "鬻" }, { "syuku", "齪" }, { "syun", "俊" }, { "syun", "儁" }, { "syun", "吮" }, { "syun", "墫" }, { "syun", "峻" }, { "syun", "徇" },
			{ "syun", "恂" }, { "syun", "悛" }, { "syun", "惇" }, { "syun", "惷" }, { "syun", "旬" }, { "syun", "春" }, { "syun", "洵" }, { "syun", "浚" },
			{ "syun", "淳" }, { "syun", "濬" }, { "syun", "皴" }, { "syun", "瞬" }, { "syun", "竣" }, { "syun", "笋" }, { "syun", "筍" }, { "syun", "舜" },
			{ "syun", "荀" }, { "syun", "蓴" }, { "syun", "蕣" }, { "syun", "蠢" }, { "syun", "訊" }, { "syun", "詢" }, { "syun", "諄" }, { "syun", "蹲" },
			{ "syun", "逡" }, { "syun", "遁" }, { "syun", "醇" }, { "syun", "隼" }, { "syun", "雋" }, { "syun", "馴" }, { "syun", "駲" }, { "syun", "駿" },
			{ "syun", "鰆" }, { "syun", "鶉" }, { "syutu", "出" }, { "syutu", "卆" }, { "syutu", "卒" }, { "syutu", "恤" }, { "syutu", "朮" }, { "syutu", "率" },
			{ "syutu", "蟀" }, { "syutu", "齣" }, { "syuu", "主" }, { "syuu", "什" }, { "syuu", "修" }, { "syuu", "厨" }, { "syuu", "収" }, { "syuu", "叟" },
			{ "syuu", "周" }, { "syuu", "呪" }, { "syuu", "咒" }, { "syuu", "售" }, { "syuu", "啾" }, { "syuu", "嗽" }, { "syuu", "囚" }, { "syuu", "執" },
			{ "syuu", "壽" }, { "syuu", "夂" }, { "syuu", "娵" }, { "syuu", "宗" }, { "syuu", "寿" }, { "syuu", "就" }, { "syuu", "岫" }, { "syuu", "嵩" },
			{ "syuu", "州" }, { "syuu", "帚" }, { "syuu", "廚" }, { "syuu", "愀" }, { "syuu", "愁" }, { "syuu", "慴" }, { "syuu", "拾" }, { "syuu", "捜" },
			{ "syuu", "掫" }, { "syuu", "揖" }, { "syuu", "搜" }, { "syuu", "摺" }, { "syuu", "收" }, { "syuu", "昇" }, { "syuu", "柊" }, { "syuu", "楢" },
			{ "syuu", "楫" }, { "syuu", "楸" }, { "syuu", "泅" }, { "syuu", "洲" }, { "syuu", "渋" }, { "syuu", "湫" }, { "syuu", "湿" }, { "syuu", "溲" },
			{ "syuu", "漱" }, { "syuu", "澀" }, { "syuu", "澁" }, { "syuu", "濕" }, { "syuu", "甃" }, { "syuu", "痩" }, { "syuu", "皺" }, { "syuu", "祝" },
			{ "syuu", "秀" }, { "syuu", "秋" }, { "syuu", "穐" }, { "syuu", "箒" }, { "syuu", "籀" }, { "syuu", "終" }, { "syuu", "綉" }, { "syuu", "緝" },
			{ "syuu", "繍" }, { "syuu", "羞" }, { "syuu", "羽" }, { "syuu", "習" }, { "syuu", "聚" }, { "syuu", "脩" }, { "syuu", "臭" }, { "syuu", "舟" },
			{ "syuu", "艘" }, { "syuu", "芻" }, { "syuu", "菘" }, { "syuu", "菷" }, { "syuu", "萩" }, { "syuu", "葺" }, { "syuu", "蒐" }, { "syuu", "蒭" },
			{ "syuu", "蓚" }, { "syuu", "螽" }, { "syuu", "衆" }, { "syuu", "袖" }, { "syuu", "褶" }, { "syuu", "襲" }, { "syuu", "讎" }, { "syuu", "讐" },
			{ "syuu", "蹴" }, { "syuu", "躊" }, { "syuu", "輯" }, { "syuu", "逎" }, { "syuu", "週" }, { "syuu", "遒" }, { "syuu", "鄒" }, { "syuu", "酋" },
			{ "syuu", "酬" }, { "syuu", "醜" }, { "syuu", "銹" }, { "syuu", "鋳" }, { "syuu", "鍬" }, { "syuu", "鏥" }, { "syuu", "鑄" }, { "syuu", "陬" },
			{ "syuu", "隰" }, { "syuu", "集" }, { "syuu", "鞦" }, { "syuu", "駲" }, { "syuu", "驟" }, { "syuu", "鰌" }, { "syuu", "鰍" }, { "syuu", "鷲" },
			{ "syuu", "齪" }, { "syuu", "龝" }, { "syuuto", "姑" }, { "syuuto", "舅" }, { "syuutome", "姑" }, { "t", "っ" }, { "t", "ッ" }, { "ta", "た" } };
};
