package com.webnation.util.keyboard.KanjiLists;

public class KANJI_R11 {
	public static String[][] kl = { { "mori", "杜" }, { "mori", "森" }, { "mori", "盛" }, { "mori", "籠" }, { "mori", "衛" }, { "mori", "護" }, { "mori", "銛" },
			{ "moro", "両" }, { "moro", "師" }, { "moro", "脆" }, { "moro", "艶" }, { "moro", "諸" }, { "moromi", "醪" }, { "moromoro", "烝" }, { "mosi", "儻" },
			{ "mosuso", "裙" }, { "mosuso", "裳" }, { "mot", "以" }, { "mota", "凭" }, { "mota", "抬" }, { "mota", "擡" }, { "mota", "靠" }, { "mota", "齎" },
			{ "motai", "瓮" }, { "motai", "甕" }, { "motai", "罅" }, { "motai", "罌" }, { "mote", "茂" }, { "moteaso", "弄" }, { "moteaso", "玩" },
			{ "moteaso", "翫" }, { "motena", "饗" }, { "moti", "以" }, { "moti", "勿" }, { "moti", "持" }, { "moti", "望" }, { "moti", "用" }, { "moti", "韈" },
			{ "moti", "須" }, { "moti", "餅" }, { "moti", "餌" }, { "moti", "餠" }, { "moti", "黐" }, { "motiaso", "玩" }, { "motiawa", "朮" }, { "motigome", "糯" },
			{ "motii", "餅" }, { "motii", "餠" }, { "motinoki", "橿" }, { "moto", "下" }, { "moto", "亘" }, { "moto", "亙" }, { "moto", "元" }, { "moto", "剌" },
			{ "moto", "基" }, { "moto", "大" }, { "moto", "夲" }, { "moto", "始" }, { "moto", "孕" }, { "moto", "宗" }, { "moto", "幹" }, { "moto", "很" },
			{ "moto", "忤" }, { "moto", "悖" }, { "moto", "愎" }, { "moto", "意" }, { "moto", "旧" }, { "moto", "智" }, { "moto", "木" }, { "moto", "本" },
			{ "moto", "東" }, { "moto", "森" }, { "moto", "求" }, { "moto", "源" }, { "moto", "狠" }, { "moto", "産" }, { "moto", "礎" }, { "moto", "紀" },
			{ "moto", "素" }, { "moto", "職" }, { "moto", "舊" }, { "moto", "覓" }, { "moto", "許" }, { "moto", "貭" }, { "moto", "資" }, { "moto", "質" },
			{ "moto", "邀" }, { "moto", "順" }, { "moto", "須" }, { "motodori", "髻" }, { "motoi", "基" }, { "motomu", "須" }, { "motoo", "囘" }, { "motoo", "回" },
			{ "motoo", "廻" }, { "motoru", "乖" }, { "motou", "繞" }, { "motte", "将" }, { "motte", "將" }, { "motto", "尤" }, { "motto", "最" }, { "mottomo", "尢" },
			{ "motu", "持" }, { "motu", "沒" }, { "motu", "没" }, { "motu", "物" }, { "motu", "縺" }, { "mou", "亡" }, { "mou", "儚" }, { "mou", "儲" },
			{ "mou", "卯" }, { "mou", "妄" }, { "mou", "孟" }, { "mou", "帽" }, { "mou", "忙" }, { "mou", "惘" }, { "mou", "摸" }, { "mou", "旄" }, { "mou", "曚" },
			{ "mou", "望" }, { "mou", "朦" }, { "mou", "檬" }, { "mou", "毛" }, { "mou", "濛" }, { "mou", "猛" }, { "mou", "瑁" }, { "mou", "生" }, { "mou", "申" },
			{ "mou", "盲" }, { "mou", "矇" }, { "mou", "網" }, { "mou", "网" }, { "mou", "罔" }, { "mou", "耄" }, { "mou", "耗" }, { "mou", "艨" }, { "mou", "芒" },
			{ "mou", "莽" }, { "mou", "蒙" }, { "mou", "蟒" }, { "mou", "蠎" }, { "mou", "設" }, { "mou", "詣" }, { "mou", "髦" }, { "mou", "魍" }, { "mouke", "儲" },
			{ "mousen", "氈" }, { "moya", "舫" }, { "moya", "霏" }, { "moya", "靄" }, { "moyaibune", "舫" }, { "moyoo", "催" }, { "moyou", "催" }, { "mozi", "綟" },
			{ "mozu", "鴃" }, { "mozu", "鵙" }, { "mu", "む" }, { "mu", "ム" }, { "mu", "六" }, { "mu", "剥" }, { "mu", "務" }, { "mu", "厶" }, { "mu", "向" },
			{ "mu", "嘸" }, { "mu", "噎" }, { "mu", "夢" }, { "mu", "慶" }, { "mu", "撫" }, { "mu", "无" }, { "mu", "旡" }, { "mu", "梦" }, { "mu", "武" },
			{ "mu", "毋" }, { "mu", "浮" }, { "mu", "烝" }, { "mu", "無" }, { "mu", "牟" }, { "mu", "生" }, { "mu", "産" }, { "mu", "畆" }, { "mu", "畝" },
			{ "mu", "眸" }, { "mu", "睦" }, { "mu", "矛" }, { "mu", "羣" }, { "mu", "群" }, { "mu", "茂" }, { "mu", "蒸" }, { "mu", "蕪" }, { "mu", "虫" },
			{ "mu", "謀" }, { "mu", "鉾" }, { "mu", "陸" }, { "mu", "霧" }, { "mu", "鵐" }, { "mu", "鵡" }, { "mu", "鶩" }, { "muduka", "難" }, { "mugi", "麥" },
			{ "mugi", "麦" }, { "mugiko", "麪" }, { "mugiko", "麺" }, { "mugo", "惨" }, { "mugo", "慘" }, { "mugura", "葎" }, { "mui", "六" }, { "muka", "向" },
			{ "muka", "嚮" }, { "muka", "対" }, { "muka", "對" }, { "muka", "迎" }, { "muka", "這" }, { "muka", "逢" }, { "muka", "邀" }, { "mukabaki", "縢" },
			{ "mukabaki", "逼" }, { "mukae", "迎" }, { "mukai", "向" }, { "mukasi", "昔" }, { "mukatu", "嘔" }, { "muko", "向" }, { "muko", "壻" }, { "muko", "婿" },
			{ "muko", "甥" }, { "muko", "聟" }, { "mukou", "向" }, { "muku", "報" }, { "muku", "椋" }, { "muku", "讎" }, { "muku", "讐" }, { "muku", "酬" },
			{ "mukuge", "椴" }, { "mukuge", "槿" }, { "mukuge", "毳" }, { "mukuge", "葮" }, { "mukuge", "蕣" }, { "mukuinu", "尨" }, { "mukuro", "躯" },
			{ "mukuro", "骸" }, { "muna", "宗" }, { "muna", "昿" }, { "muna", "曠" }, { "muna", "棟" }, { "muna", "皆" }, { "muna", "空" }, { "muna", "胸" },
			{ "muna", "虚" }, { "munagai", "鞅" }, { "mune", "宗" }, { "mune", "旨" }, { "mune", "棟" }, { "mune", "睦" }, { "mune", "統" }, { "mune", "胸" },
			{ "mune", "膺" }, { "mune", "臆" }, { "mune", "順" }, { "munyou", "无" }, { "mura", "党" }, { "mura", "叢" }, { "mura", "村" }, { "mura", "簇" },
			{ "mura", "羣" }, { "mura", "群" }, { "mura", "西" }, { "mura", "邑" }, { "mura", "邨" }, { "mura", "邸" }, { "mura", "黨" }, { "murasaki", "紫" },
			{ "murazi", "連" }, { "mure", "羣" }, { "muro", "室" }, { "muro", "榁" }, { "muro", "窩" }, { "musabo", "婪" }, { "musabo", "昧" }, { "musabo", "貪" },
			{ "musabo", "餮" }, { "musabo", "饕" }, { "muse", "咽" }, { "muse", "哽" }, { "muse", "噎" }, { "muse", "饐" }, { "musi", "寧" }, { "musi", "毟" },
			{ "musi", "虫" }, { "musi", "蟲" }, { "musiatu", "溽" }, { "musiba", "蝕" }, { "musiba", "齲" }, { "musiro", "席" }, { "musiro", "筵" },
			{ "musiro", "莚" }, { "musiro", "蓆" }, { "musu", "掬" }, { "musu", "結" }, { "musume", "娘" }, { "musume", "嬢" }, { "musume", "孃" }, { "mut", "六" },
			{ "muta", "村" }, { "muti", "笞" }, { "muti", "鞭" }, { "mutiu", "捶" }, { "mutiutu", "撻" }, { "mutiutu", "鞭" }, { "mutu", "六" }, { "mutu", "睦" },
			{ "mutu", "陸" }, { "mutuka", "難" }, { "mutuki", "繦" }, { "mutuki", "褓" }, { "mutuki", "襁" }, { "mutuyubi", "跂" }, { "muzina", "狢" },
			{ "muzina", "貉" }, { "muzinahen", "豸" }, { "muzuka", "難" }, { "mya", "みゃ" }, { "mya", "ミャ" }, { "myaku", "獏" }, { "myaku", "脈" }, { "myaku", "脉" },
			{ "myaku", "覓" }, { "myaku", "貊" }, { "myaku", "貘" }, { "myo", "みょ" }, { "myo", "ミョ" }, { "myou", "冥" }, { "myou", "名" }, { "myou", "命" },
			{ "myou", "妙" }, { "myou", "孟" }, { "myou", "廟" }, { "myou", "明" }, { "myou", "暝" }, { "myou", "甍" }, { "myou", "眇" }, { "myou", "瞑" },
			{ "myou", "緲" }, { "myou", "苗" }, { "myou", "茅" }, { "myou", "茗" }, { "myou", "螟" }, { "myou", "錨" }, { "myu", "みゅ" }, { "myu", "ミュ" },
			{ "myuu", "謬" }, { "n", "ん" }, { "n", "ン" }, { "n", "武" }, { "n", "金" }, { "na", "な" }, { "na", "ナ" }, { "na", "七" }, { "na", "並" }, { "na", "亡" },
			{ "na", "今" }, { "na", "做" }, { "na", "儺" }, { "na", "八" }, { "na", "凪" }, { "na", "南" }, { "na", "名" }, { "na", "向" }, { "na", "和" },
			{ "na", "哭" }, { "na", "啼" }, { "na", "啾" }, { "na", "嘗" }, { "na", "嚶" }, { "na", "奈" }, { "na", "女" }, { "na", "娜" }, { "na", "字" },
			{ "na", "慣" }, { "na", "成" }, { "na", "投" }, { "na", "拊" }, { "na", "拏" }, { "na", "拿" }, { "na", "捫" }, { "na", "撫" }, { "na", "方" },
			{ "na", "梛" }, { "na", "楠" }, { "na", "樹" }, { "na", "泣" }, { "na", "流" }, { "na", "涕" }, { "na", "済" }, { "na", "濟" }, { "na", "為" },
			{ "na", "無" }, { "na", "爲" }, { "na", "狃" }, { "na", "狎" }, { "na", "甞" }, { "na", "生" }, { "na", "痿" }, { "na", "稲" }, { "na", "穴" },
			{ "na", "竝" }, { "na", "糯" }, { "na", "納" }, { "na", "綯" }, { "na", "舐" }, { "na", "菜" }, { "na", "萎" }, { "na", "葦" }, { "na", "薙" },
			{ "na", "褻" }, { "na", "農" }, { "na", "那" }, { "na", "長" }, { "na", "阿" }, { "na", "難" }, { "na", "韲" }, { "na", "馴" }, { "na", "鳴" },
			{ "na", "齏" }, { "naTU", "納" }, { "naba", "生" }, { "nabe", "辺" }, { "nabe", "邉" }, { "nabe", "邊" }, { "nabe", "銚" }, { "nabe", "鍋" },
			{ "nabe", "鎬" }, { "nabe", "鐺" }, { "nabebuta", "亠" }, { "nabi", "並" }, { "nabi", "靡" }, { "nabu", "嫐" }, { "nabu", "嬲" }, { "nada", "宥" },
			{ "nada", "洋" }, { "nada", "灘" }, { "nade", "撫" }, { "nadesi", "撫" }, { "nado", "抔" }, { "nado", "等" }, { "nae", "秧" }, { "nae", "苗" },
			{ "naga", "乍" }, { "naga", "亨" }, { "naga", "修" }, { "naga", "呂" }, { "naga", "寿" }, { "naga", "暢" }, { "naga", "曼" }, { "naga", "栄" },
			{ "naga", "永" }, { "naga", "流" }, { "naga", "眺" }, { "naga", "脩" }, { "naga", "良" }, { "naga", "酉" }, { "naga", "長" }, { "nagaame", "霖" },
			{ "nagae", "轅" }, { "nagare", "流" }, { "nagasa", "袤" }, { "nagasime", "睥" }, { "nage", "哭" }, { "nage", "唏" }, { "nage", "喟" }, { "nage", "嗟" },
			{ "nage", "嘆" }, { "nage", "慟" }, { "nage", "歎" }, { "nageku", "欷" }, { "nageu", "抛" }, { "nageu", "擲" }, { "nagi", "凪" }, { "nagi", "柳" },
			{ "nagi", "梛" }, { "nagi", "椥" }, { "nagi", "渚" }, { "nagi", "薙" }, { "nagisa", "汀" }, { "nagisa", "沚" }, { "nagisa", "渚" }, { "nagisa", "瀲" },
			{ "nago", "和" }, { "nagu", "擲" }, { "nagu", "殴" }, { "nagu", "毆" }, { "nagusa", "慰" }, { "nai", "乃" }, { "nai", "内" }, { "nai", "奈" },
			{ "nai", "廼" }, { "nai", "无" }, { "nai", "毋" }, { "nai", "沒" }, { "nai", "没" }, { "nai", "泥" }, { "nai", "祢" }, { "nai", "禰" }, { "nai", "罔" },
			{ "nai", "莫" }, { "nai", "袋" }, { "nai", "迺" }, { "nai", "靡" }, { "naigasiro", "蔑" }, { "naisi", "尚" }, { "naka", "中" }, { "naka", "仲" },
			{ "naka", "勿" }, { "naka", "半" }, { "naka", "史" }, { "naka", "央" }, { "naka", "毋" }, { "naka", "莫" }, { "nakama", "党" }, { "nakama", "黨" },
			{ "nakare", "毋" }, { "nakatu", "仲" }, { "nakihaha", "妣" }, { "nakoudo", "妁" }, { "nama", "天" }, { "nama", "妖" }, { "nama", "怠" }, { "nama", "生" },
			{ "nama", "膾" }, { "nama", "艶" }, { "nama", "艷" }, { "nama", "訛" }, { "nama", "譌" }, { "nama", "鈍" }, { "namagusa", "羶" }, { "namagusa", "腥" },
			{ "namaku", "鈍" }, { "namameka", "嬌" }, { "namari", "鉛" }, { "namasu", "鱠" }, { "namazi", "憖" }, { "namazu", "癜" }, { "namazu", "鮎" },
			{ "namazu", "鯰" }, { "name", "滑" }, { "name", "行" }, { "name", "靼" }, { "name", "鞣" }, { "nameri", "滑" }, { "namesigawa", "靼" },
			{ "namesigawa", "鞣" }, { "namesigawa", "韋" }, { "nami", "凡" }, { "nami", "南" }, { "nami", "波" }, { "nami", "浪" }, { "nami", "涛" }, { "nami", "濤" },
			{ "nami", "瀚" }, { "nami", "瀾" }, { "nami", "甫" }, { "nami", "蔑" }, { "nami", "行" }, { "namida", "泗" }, { "namida", "泪" }, { "namida", "涕" },
			{ "namida", "涙" }, { "nan", "何" }, { "nan", "南" }, { "nan", "喃" }, { "nan", "娚" }, { "nan", "楠" }, { "nan", "灘" }, { "nan", "煖" }, { "nan", "男" },
			{ "nan", "納" }, { "nan", "軟" }, { "nan", "難" }, { "nana", "七" }, { "nana", "斜" }, { "naname", "陀" }, { "nani", "何" }, { "nani", "曷" },
			{ "nani", "浪" }, { "nani", "渠" }, { "nani", "那" }, { "nani", "難" }, { "nanigasi", "某" }, { "nannanto", "垂" }, { "nannanto", "埀" }, { "nano", "七" },
			{ "nanzi", "乃" }, { "nanzi", "尓" }, { "nanzi", "廼" }, { "nanzi", "汝" }, { "nanzi", "爾" }, { "nanzi", "而" }, { "nanzi", "迺" }, { "nanzo", "奚" },
			{ "nanzo", "怎" }, { "nanzo", "曷" }, { "nanzo", "渠" }, { "nanzo", "烏" }, { "nanzo", "瑕" }, { "nanzo", "盍" }, { "nanzo", "胡" }, { "nanzo", "遐" },
			{ "nanzo", "那" }, { "nao", "仍" }, { "nao", "作" }, { "nao", "尚" }, { "nao", "巨" }, { "nao", "忠" }, { "nao", "成" }, { "nao", "有" }, { "nao", "治" },
			{ "nao", "温" }, { "nao", "犹" }, { "nao", "猶" }, { "nao", "直" }, { "nao", "真" }, { "nao", "矗" }, { "nao", "胖" }, { "nao", "順" }, { "nara", "並" },
			{ "nara", "伉" }, { "nara", "倣" }, { "nara", "傚" }, { "nara", "効" }, { "nara", "均" }, { "nara", "嫺" }, { "nara", "嫻" }, { "nara", "対" },
			{ "nara", "對" }, { "nara", "并" }, { "nara", "效" }, { "nara", "楢" }, { "nara", "狃" }, { "nara", "竝" }, { "nara", "習" }, { "nara", "肄" },
			{ "nara", "駢" }, { "narabu", "儷" }, { "narabu", "双" }, { "narabu", "雙" }, { "nare", "汝" }, { "naresika", "麋" }, { "nari", "也" }, { "nari", "体" },
			{ "nari", "城" }, { "nari", "尚" }, { "nari", "就" }, { "nari", "形" }, { "nari", "成" }, { "nari", "斉" }, { "nari", "業" }, { "nari", "済" },
			{ "nari", "為" }, { "nari", "爲" }, { "nari", "百" }, { "nari", "礼" }, { "nari", "稔" }, { "nari", "芸" }, { "nari", "鳴" }, { "naru", "徳" },
			{ "naru", "成" }, { "naru", "稔" }, { "naru", "鳴" }, { "nasa", "情" }, { "nasi", "勿" }, { "nasi", "无" }, { "nasi", "旡" }, { "nasi", "梨" },
			{ "nasi", "莫" }, { "nata", "屶" }, { "nata", "方" }, { "nata", "鉈" }, { "natu", "夏" }, { "natu", "懐" }, { "natu", "懷" }, { "natu", "捺" },
			{ "natume", "棗" }, { "nawa", "綯" }, { "nawa", "緡" }, { "nawa", "縄" }, { "nawa", "繩" }, { "nawa", "苗" }, { "nawa", "輪" }, { "nawate", "畷" },
			{ "naya", "悩" }, { "naya", "惱" }, { "naya", "懊" }, { "naya", "艱" }, { "naya", "蹇" }, { "nayami", "悩" }, { "nayami", "惱" }, { "nayami", "艱" },
			{ "nayo", "嫋" }, { "nazo", "謎" }, { "nazora", "凖" }, { "nazora", "準" }, { "nazu", "懐" }, { "nazuna", "薺" }, { "ne", "ね" }, { "ne", "ネ" },
			{ "ne", "人" }, { "ne", "値" }, { "ne", "十" }, { "ne", "合" }, { "ne", "如" }, { "ne", "婦" }, { "ne", "子" }, { "ne", "寐" }, { "ne", "寝" },
			{ "ne", "寢" }, { "ne", "峯" }, { "ne", "峰" }, { "ne", "嶺" }, { "ne", "年" }, { "ne", "捏" }, { "ne", "捩" }, { "ne", "捻" }, { "ne", "柢" },
			{ "ne", "根" }, { "ne", "殕" }, { "ne", "煉" }, { "ne", "眠" }, { "ne", "祢" }, { "ne", "禰" }, { "ne", "称" }, { "ne", "稔" }, { "ne", "練" },
			{ "ne", "袮" }, { "ne", "錬" }, { "ne", "音" }, { "neTU", "子" }, { "neba", "粘" }, { "neba", "黏" }, { "nebu", "舐" }, { "neesan", "姐" },
			{ "nega", "覦" }, { "nega", "願" }, { "negai", "願" }, { "negi", "葱" }, { "negira", "労" }, { "negira", "勞" }, { "negira", "犒" }, { "negura", "塒" },
			{ "nei", "佞" }, { "nei", "侫" }, { "nei", "嚀" }, { "nei", "寧" }, { "nei", "檸" }, { "nei", "濘" }, { "nei", "獰" }, { "nei", "聹" }, { "nei", "苗" },
			{ "nei", "蚋" }, { "neko", "猫" }, { "nemu", "眠" }, { "nemunoki", "棔" }, { "nen", "冉" }, { "nen", "年" }, { "nen", "念" }, { "nen", "拈" },
			{ "nen", "捻" }, { "nen", "撚" }, { "nen", "棯" }, { "nen", "楠" }, { "nen", "然" }, { "nen", "燃" }, { "nen", "稔" }, { "nen", "粘" }, { "nen", "縁" },
			{ "nen", "蠕" }, { "nen", "輾" }, { "nen", "鮎" }, { "nen", "鯰" }, { "nen", "黏" }, { "nengo", "懇" }, { "nengo", "諄" }, { "nengoro", "懃" },
			{ "nera", "狙" }, { "neri", "練" }, { "neta", "妬" }, { "neta", "嫉" }, { "neta", "悋" }, { "neta", "猜" }, { "neti", "捏" }, { "neti", "蚋" },
			{ "netu", "捏" }, { "netu", "涅" }, { "netu", "熱" }, { "neya", "閨" }, { "nezi", "拗" }, { "nezi", "捩" }, { "nezi", "捻" }, { "nezu", "鼠" },
			{ "nezu", "鼡" }, { "nezukuri", "艮" }, { "nezumi", "鼠" }, { "nezumi", "鼡" }, { "ni", "に" }, { "ni", "ニ" }, { "ni", "丹" }, { "ni", "二" },
			{ "ni", "于" }, { "ni", "仁" }, { "ni", "似" }, { "ni", "児" }, { "ni", "兒" }, { "ni", "入" }, { "ni", "合" }, { "ni", "尓" }, { "ni", "尼" },
			{ "ni", "岻" }, { "ni", "弍" }, { "ni", "弐" }, { "ni", "新" }, { "ni", "日" }, { "ni", "泥" }, { "ni", "烹" }, { "ni", "煎" }, { "ni", "煮" },
			{ "ni", "爾" }, { "ni", "理" }, { "ni", "而" }, { "ni", "膩" }, { "ni", "荷" }, { "ni", "貮" }, { "ni", "貳" }, { "ni", "迩" }, { "ni", "迯" },
			{ "ni", "逃" }, { "ni", "邇" }, { "ni", "餌" }, { "niTU", "新" }, { "niTU", "日" }, { "nibe", "膠" }, { "nibu", "鈍" }, { "nibu", "駑" }, { "nie", "贄" },
			{ "nie", "錵" }, { "niga", "苦" }, { "nigana", "荼" }, { "nigi", "和" }, { "nigi", "握" }, { "nigi", "賑" }, { "nigo", "汰" }, { "nigo", "渾" },
			{ "nigo", "溷" }, { "nigo", "濁" }, { "nigori", "濁" }, { "nigorizake", "醪" }, { "niguruma", "輜" }, { "niho", "薫" }, { "nii", "二" }, { "nii", "新" },
			{ "nikawa", "膠" }, { "nikibi", "皰" }, { "nikibi", "靤" }, { "niku", "嫉" }, { "niku", "宍" }, { "niku", "悪" }, { "niku", "惡" }, { "niku", "憎" },
			{ "niku", "肉" }, { "niku", "蓐" }, { "niku", "難" }, { "nin", "人" }, { "nin", "仁" }, { "nin", "任" }, { "nin", "儿" }, { "nin", "刃" }, { "nin", "刄" },
			{ "nin", "壬" }, { "nin", "妊" }, { "nin", "姙" }, { "nin", "忍" }, { "nin", "恁" }, { "nin", "稔" }, { "nin", "荏" }, { "nin", "荵" }, { "nin", "衽" },
			{ "nin", "袵" }, { "nin", "認" }, { "nin", "靫" }, { "nin", "靭" }, { "nin", "靱" }, { "nina", "担" }, { "nina", "擔" }, { "nina", "蜷" }, { "nina", "螺" },
			{ "nina", "蠡" }, { "ninniku", "蒜" }, { "ninnyou", "儿" }, { "nio", "匂" }, { "nio", "臭" }, { "nio", "鳰" }, { "nira", "盻" }, { "nira", "眈" },
			{ "nira", "睨" }, { "nira", "薤" }, { "nira", "韭" }, { "nira", "韮" }, { "niragu", "淬" }, { "nire", "楡" }, { "nise", "偽" }, { "nise", "僞" },
			{ "nise", "贋" }, { "nisi", "螺" }, { "nisi", "襾" }, { "nisi", "西" }, { "nisi", "錦" }, { "nisiki", "錦" }, { "nisin", "鯡" }, { "nisin", "鰊" },
			{ "nisui", "冫" }, { "nita", "似" }, { "niti", "日" }, { "nitu", "新" }, { "nitu", "日" }, { "niu", "生" }, { "niwa", "圃" }, { "niwa", "庭" },
			{ "niwaka", "俄" }, { "niwaka", "卆" }, { "niwaka", "卒" }, { "niwaka", "怱" }, { "niwaka", "猝" }, { "niwaka", "遽" }, { "niwaka", "霍" },
			{ "niwaka", "頓" }, { "niwaka", "驟" }, { "niwakaame", "瀑" }, { "niwakani", "勃" }, { "niwatazumi", "潦" }, { "niwatori", "鶏" }, { "niwatori", "鷄" },
			{ "niwazakura", "棣" }, { "nizi", "滲" }, { "nizi", "虹" }, { "nizi", "躙" }, { "nizi", "躪" }, { "nizi", "霓" }, { "nizyuu", "廾" }, { "nizyuu", "廿" },
			{ "nizyuuasi", "廾" }, { "no", "の" }, { "no", "ノ" }, { "no", "丿" }, { "no", "乃" }, { "no", "之" }, { "no", "乗" }, { "no", "乘" }, { "no", "伸" },
			{ "no", "入" }, { "no", "典" }, { "no", "及" }, { "no", "呑" }, { "no", "咽" }, { "no", "喃" }, { "no", "嚥" }, { "no", "埜" }, { "no", "布" },
			{ "no", "延" }, { "no", "廼" }, { "no", "抒" }, { "no", "泉" }, { "no", "洩" }, { "no", "洵" }, { "no", "濃" }, { "no", "熨" }, { "no", "箆" },
			{ "no", "篠" }, { "no", "篦" }, { "no", "納" }, { "no", "能" }, { "no", "舒" }, { "no", "載" }, { "no", "農" }, { "no", "述" }, { "no", "迺" },
			{ "no", "退" }, { "no", "野" }, { "no", "飮" }, { "no", "飲" }, { "no", "餐" }, { "no", "饒" }, { "nobe", "延" }, { "nobi", "信" }, { "nobi", "暢" },
			{ "nobi", "燹" }, { "nobiru", "蒜" }, { "nobo", "上" }, { "nobo", "昇" }, { "nobo", "登" }, { "nobo", "躋" }, { "nobo", "陞" }, { "nobo", "陟" },
			{ "nobo", "隲" }, { "nobori", "上" } };
};
